### ISSUE TITLE
telegraaf.nl

### ISSUE THREAD

**Issue by zooi1** [reek/anti-adblock-killer#1000]
http://www.telegraaf.nl/
http://imgur.com/oSzB447
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it.

**Comment by reek** [comment]
Try this
<code>@@||telegraaf.tcdn.nl/javascript/showads.*.js$script</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
