### ISSUE TITLE
PopUp new tab can bypass no script and adblock 

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#1001]
![image](https://cloud.githubusercontent.com/assets/15664251/12795852/f7cfdb42-cab3-11e5-8d8a-42c48b4cec9e.png)

i've tried everything, on filters,
they have random id's but i can't find the source where they generate these ID's
![image](https://cloud.githubusercontent.com/assets/15664251/12796962/91f6192a-cab9-11e5-9981-6a4294486aee.png)

web site is http://neodrive.co/embed/QDHS20ASC0DUDU4YDWG3J6EEQ
they are smart please if anyone can help

**Comment by fabiobarao94** [comment]
When i click play on the video it opens in a net tab that link

**Comment by fabiobarao94** [comment]
this script loads the video player and the popup tab also, so i can't block it http://neodrive.co/js/jquery-1.10.2.min.js
mean while i can't block the id's because they are generated, and i can't find the source where it's generated

**Comment by reek** [comment]
Source where they generate these ID's:
http://pastebin.com/udAmm0fn

**Comment by reek** [comment]
here is a solution that only works with Firefox + uBlock Origin
<code>neodrive.co##script:contains(var j5V={'A91':function(V,c){return V>c;})</code>

otherwise you must decrypt the above script

**Comment by fabiobarao94** [comment]
it give this error 
![image](https://cloud.githubusercontent.com/assets/15664251/12799985/f6efbf38-cac9-11e5-8b84-4338cbdbbd22.png)

**Comment by reek** [comment]
só funciona com Firefox + uBlock Origin
<code>neodrive.co##script:contains(var j5V={'A91':function(V,c){return V>c;})</code>

**Comment by fabiobarao94** [comment]
and so, there is not another way to bypass this problem with adblock?

**Comment by reek** [comment]
No

**Comment by fabiobarao94** [comment]
thansk anyway for answering

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
