### ISSUE TITLE
ebookdz.com

### ISSUE THREAD

**Issue by Miscios** [reek/anti-adblock-killer#1003]
http://ebookdz.com/
http://imgbox.com/IaKXLmWq
Mozilla Firefox
uBlock Origin
Adblock Warning Removal List‎ + EasyList + Peter Lowe’s Ad server list‎ + EasyPrivacy + Fanboy’s Enhanced Tracking List + Malware domains‎

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#instruction
