### ISSUE TITLE
linkdrop.net

### ISSUE THREAD

**Issue by arminmacx** [reek/anti-adblock-killer#1004]
@#Hi

I'm using your script on safari within tampermonkey and ublock but link drop.net now detect the script and prompt me to disable ad blocker and redirect me to other domain.

Can you fix it please

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by arminmacx** [comment]
http://sznpaste.net/yc5mSxhn

you need to click on one of link to work if you open it on other tab it only show you linkdrop.net main page.
http://imgur.com/siNpzNC

Safari
Tampermonkey+ anti-adblock-killer scripts
uBlock
Easylist+Aaklist

**Comment by reek** [comment]
Give me a linkdrop link

**Comment by arminmacx** [comment]
i told you i can give you the link but it goes only to main page but if you need that here the link http://linkdrop.net/YZaQb

**Comment by reek** [comment]
AakScript kill it on:
<pre>
Firefox + Greasemonkey
Chrome + Tampermonkey
Opera + Tampermonkey
</pre>

I cannot test on Safari on Windows, because the development has been stopped, I recommend you to try with one of the Browsers cited above

**Comment by arminmacx** [comment]
last night it worked but today after reinstalling my mac and setup it again it didn't work

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
