### ISSUE TITLE
uploadshub.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1006]
Hi, 
`#@##banner_ad` not solve the anti-adblock on `https://uploadshub.com/s3u1pqnsnoat`

screenshot: http://i.imgur.com/tLiBzws.png

source: https://forums.lanik.us/viewtopic.php?f=62&t=28367

Thanks!

**Comment by SMed79** [comment]
`@@||uploadshub.com^$generichide`
source: https://adblockplus.org/forum/viewtopic.php?p=147047

**Comment by reek** [comment]
Hi,

He uses <code>blockadblock.com</code> anti-adb.
I have a solution with AakScript

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
