### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by lemane** [reek/anti-adblock-killer#1007]
Hi, 
#@##banner_ad not solve the anti-adblock on http://www.spaste.com/site/checkPasteUrl?c=fSZHx59593

screenshot: http://i.imgur.com/oLwtXZR.png

source: https://psarips.com/tv-show/american-crime-story/

Thanks ^^

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Have you added AakList ?
http://reek.github.io/anti-adblock-killer/#filterlist

**Comment by reek** [comment]
Your Ad-Blocker and filterlists ?
