### ISSUE TITLE
mocospace.com

### ISSUE THREAD

**Issue by damnnative** [reek/anti-adblock-killer#1008]
http://mocospace.com/
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
I dont see anti-adb, make screenshot

**Comment by FugeeMan** [comment]
http://mocospace.com/
http://imgur.com/yUvzlJu
Firefox
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Thanks, now I see and will kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
