### ISSUE TITLE
ebookdz.com

### ISSUE THREAD

**Issue by Miscios** [reek/anti-adblock-killer#1009]
Hi,

Yesterday, I created a new issue about ebookdz.com and you removed it without responding. There must be a mistake. Anyway, I hope that is alright if I put it back.
http://ebookdz.com/
http://imgbox.com/EhBlOblv (this is a message that asks me to disable adblock)
Mozilla Firefox
uBlock Origin
Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek + EasyList + Peter Lowe’s Ad server list + EasyPrivacy + AakList

**Comment by xxcriticxx** [comment]
https://github.com/reek/anti-adblock-killer#instruction

please install greasemonkey (https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/) and users scripts (https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js)

**Comment by IDKwhattoputhere** [comment]
It wasn't deleted. That's not even possible on GitHub. Here it is: https://github.com/reek/anti-adblock-killer/issues/1003

You were told to follow the instructions: https://github.com/reek/anti-adblock-killer#instruction
Please do so.

**Comment by Miscios** [comment]
Nevermind, I thought the filter was sufficient with uBlock Origin. I'll be more careful next time.

**Comment by IDKwhattoputhere** [comment]
Would you please close the issue if it is resolved?

**Comment by reek** [comment]
@Miscios 
sorry to have closed the issue too quickly, but enough to read the email notification

@IDKwhattoputhere 
thank you for having explained @Miscios
