### ISSUE TITLE
moje-filmy.tk

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1010]
Reek I have little problem.
On page https://www.moje-filmy.tk/film/spectre-57b05fd7033eb58822af37c962696103 I see ads on video. I try block ads by rule |http://get-contents.video-ads.tk/files/*.mp4, but then I block this movie not start. On code I see script: 
[Bez tytułu 1.txt](https://github.com/reek/anti-adblock-killer/files/119630/Bez.tytulu.1.txt)

Have you any idea how block it?

**Comment by reek** [comment]
Hi,

Yes, with AakScript, add this rule
``` javascript
    moje_filmy_tk : {
      // issue: https://github.com/reek/anti-adblock-killer/issues/1010
      host : ['moje-filmy.tk'],
      onIdle : function () {
        Aak.uw.load_reklama = function () {};
        Aak.uw.load_player();
      }
    },

**Comment by MajkiIT** [comment]
Ok thank I will check it. You are awesome.

**Comment by MajkiIT** [comment]
Ok it works. Do you add this rule to yours scripts?

**Comment by reek** [comment]
Yes

2016-02-05 21:28 GMT+01:00 Maciej M. <notifications@github.com>:

**Comment by MajkiIT** [comment]
Ok thanks again

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
@reek I see that ads come back. Can you look for it ?

**Comment by reek** [comment]
I'll see

**Comment by reek** [comment]
I am redirected to https://www.moje-filmy.tk/zaloguj

**Comment by MajkiIT** [comment]
try this.
login jocaloy@flemail.ru
password start123

**Comment by reek** [comment]
Thanks, I'll fix it.

**Comment by MajkiIT** [comment]
OK Thanks. Sorry, but 2 days ago I didn't see alert to register on this page.

**Comment by xxcriticxx** [comment]
every time you play with the website they go to register users only

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
