### ISSUE TITLE
designtaxi.com

### ISSUE THREAD

**Issue by Alvin602** [reek/anti-adblock-killer#1011]
http://designtaxi.com/
http://imgur.com/mBXL07d
Chrome v48
Tampermonkey
AdBlock v2.49
EasyList & AakList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by maynak00** [comment]
**try with:**
>@@||designtaxi.com/js/ads.js$script

*Static filter /js/ads. found in:EasyList*

**Comment by Alvin602** [comment]
Works like a charm.  Thanks.
