### ISSUE TITLE
videomega.tv (filmovizija.studio)

### ISSUE THREAD

**Issue by JohnMiller9898** [reek/anti-adblock-killer#1012]
http://www.filmovizija.studio/movie/steve-jobs-2015-video_451316882.html#tabify
![capture555](https://cloud.githubusercontent.com/assets/13141946/12860048/673fc062-cc5a-11e5-8167-c29baa68d686.JPG)

Google Chrome
Tempormonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
