### ISSUE TITLE
rapid-games.org

### ISSUE THREAD

**Issue by DrDustwolf** [reek/anti-adblock-killer#1014]
http://www.rapid-games.org/fallout-4-multi2-rft/
https://imgur.com/Qj7cwGy
Mozilla Firefox 45b2
Noscript
Ublock Origin
uBlock filters‎
uBlock filters – Badware risks‎  (github.com)
uBlock filters – Block-then-redirect
uBlock filters – Experimental‎  (github.com)
uBlock filters – Privacy
uBlock filters – Unbreak
Adblock Warning Removal List‎ (forums.lanik.us)
Anti-Adblock Killer | Reek‎  (github.com)
EasyList‎ (forums.lanik.us)
Peter Lowe’s Ad server list‎ (pgl.yoyo.org)
Basic tracking list by Disconnect
EasyPrivacy‎ (forums.lanik.us)
Fanboy’s Enhanced Tracking List‎ (forums.lanik.us)
Malware Domain List‎ (malwaredomainlist.com)
Malware domains‎ (www.malwaredomains.com)
Malware domains (long-lived)‎ (www.malwaredomains.com)
Malware filter list by Disconnect
Spam404‎ (www.spam404.com)
Anti-ThirdpartySocial (see warning inside list)‎ (forums.lanik.us)
Fanboy’s Annoyance List‎ (forums.lanik.us)
Fanboy’s Social Blocking List‎ (forums.lanik.us)
Dan Pollock’s hosts file‎ (someonewhocares.org)
Fanboy+Easylist-Merged Ultimate List‎ (forums.lanik.us)
hpHosts’ Ad and tracking servers‎ (hosts-file.net)
MVPS HOSTS‎ (winhelp2002.mvps.org)
DEU: EasyList Germany‎ (forums.lanik.us)
EU: Prebake - Filter Obtrusive Cookie Notices‎ (github.com)
RUS: BitBlock List (Дополнительная подписка фильтров)‎ (forums.lanik.us)
RUS: RU AdList (Дополнительная региональная подписка)‎ (forums.lanik.us)

**Comment by reek** [comment]
Hi,

Remove NoScript and Install Greasemonkey + AakScript
See: https://github.com/reek/anti-adblock-killer#instruction
