### ISSUE TITLE
sportdeutschland.tv

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1015]
https://github.com/gorhill/uBlock/issues/1346

http://sportdeutschland.tv/vbl/tv-beitrag-vilsbiburg-vs-koepenick
http://imgur.com/Ciff4JQ

Mozilla Firefox 44.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
Hi,

Try this
<code>@@||sportdeutschland.vidibuscloud.net/themes/sportdeutschland-623/javascripts/lib/my_ad_integration.js$script</code>

**Comment by xxcriticxx** [comment]
nope still detects it

**Comment by reek** [comment]
because you use Peter Lowe’s Ad server list

**Comment by reek** [comment]
try this
<code>@@||ad.de.doubleclick.net$xmlhttprequest,domain=sportdeutschland.tv</code>

**Comment by xxcriticxx** [comment]
this works if i turn off Peter Lowe’s Ad server list‎

@@||sportdeutschland.vidibuscloud.net/themes/sportdeutschland-623/javascripts/lib/my_ad_integration.js$script

**Comment by reek** [comment]
Ok, try
<code>@@||ad.71i.de/global_js/$script,domain=sportdeutschland.tv</code>

**Comment by xxcriticxx** [comment]
nope found ad block

**Comment by reek** [comment]
Remove Peter Lowe’s Ad server list

**Comment by xxcriticxx** [comment]
lol

**Comment by reek** [comment]
I let you find a solution, because the addition of these three rules work with me.

**Comment by reek** [comment]
why you close issue ?

**Comment by xxcriticxx** [comment]
because you posted 3 solutions that work

**Comment by reek** [comment]
ok, I'll close when I would have done the update

2016-02-09 17:03 GMT+01:00 xxcriticxx <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
