### ISSUE TITLE
[NEWS] Google just yanked an Android ad blocker from the Google Play Store

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1016]
http://www.businessinsider.com/google-removes-adblock-fast-2016-2

http://www.engadget.com/2016/02/03/google-pulls-samsung-backed-ad-blocker/

https://github.com/rocketshipapps/adblockfast

**Comment by reek** [comment]
I'm not surprised, they did the same thing with the app ABP

**Comment by xxcriticxx** [comment]
Adblock Fast returns to Google Play a week after being pulled

http://www.businessinsider.com/adblock-fast-returns-to-google-play-2016-2
