### ISSUE TITLE
dasolo.org

### ISSUE THREAD

**Issue by riccardosimo** [reek/anti-adblock-killer#1018]
1. www.dasolo.org
2. http://imgur.com/ZNxwZBO
3. Firefox
4. Greasemonkey
5. Adblock plus
6. EasyList

**Comment by giampi75** [comment]
Same issue for me

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by giampi75** [comment]
Thanks a lot

g.

**Comment by dmaglio** [comment]
don't works...

**Comment by giampi75** [comment]
Don't work since 3 or 4 days

**Comment by dmaglio** [comment]
@reek please, reopen issue

**Comment by reek** [comment]
@giampi75 
@dmaglio 
No detected, please take screenshot

**Comment by riccardosimo** [comment]
I have no problem :D thank you reek <3 you're the best

**Comment by reek** [comment]
@giampi75
@dmaglio
it seems to be only detected by chrome

**Comment by giampi75** [comment]
![dasolo](https://cloud.githubusercontent.com/assets/17108055/14568952/1bcbaf60-033c-11e6-91c7-5496a5d184ac.jpg)

**Comment by reek** [comment]
@giampi75 
Thanks

**Comment by reek** [comment]
@giampi75 
I see that you are also using Ghostery, be careful as this can prevent Aak to function well,

**Comment by giampi75** [comment]
With Ghostery desactivated I've the same message

**Comment by dmaglio** [comment]
if i add ```@@||adscale.de/getads.js$image,domain=dasolo.org``` anti adblock is disabled

**Comment by reek** [comment]
@dmaglio 
right

**Comment by giampi75** [comment]
I add this to the script, but where?

**Comment by dmaglio** [comment]
In "my filtering" section

Il 15 aprile 2016 22:17:10 CEST, giampi75 <notifications@github.com> ha scritto:
>I add this to the script, but where?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/reek/anti-adblock-killer/issues/1018#issuecomment-210625292

-- 
Davide Maglio
Ingegnere Informatico,
p: +39 3480725133
a: via A. D'Andrea, 22, Castromediano (LE)
e: dmaglio@gmail.com

tw: https://twitter.com/dmaglio
li: https://it.linkedin.com/in/davidemaglio82

**Comment by reek** [comment]
@giampi75 
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by giampi75** [comment]
Yes, it works! Thanks a lot to reek et grazie mille a dmaglio

**Comment by dmaglio** [comment]
don't work anymore.... :-1:

**Comment by giampi75** [comment]
![dasolo2](https://cloud.githubusercontent.com/assets/17108055/14581152/ef46b774-03e4-11e6-9b9b-eed472031c2d.jpg)

**Comment by reek** [comment]
@dmaglio 
it's ok for me, see https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
