### ISSUE TITLE
outlook.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1022]
i don't know how we going to do this since this is my email provider

http://imgur.com/iQTgTT9

Mozilla Firefox 44.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by Giwayume** [comment]
From what I see this message isn't blocking any functionality, so this is easy. Just hide it.
```
#owaadbar {
  display: none !important;
}

**Comment by xxcriticxx** [comment]
where do i add this ublock or greasemonkey 

need some instruction please

**Comment by reek** [comment]
@xxcriticxx 
<code>outlook.com###owaadbar</code>

**Comment by xxcriticxx** [comment]
nope still there

**Comment by reek** [comment]
@xxcriticxx
<code>outlook.live.com###owaadbar</code>

**Comment by xxcriticxx** [comment]
yep this one works

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
