### ISSUE TITLE
wallpapermania.eu

### ISSUE THREAD

**Issue by mskadu** [reek/anti-adblock-killer#1023]
Hello,

I have subscribed to your list on abp as suggested. However, the following URL continues to show a anti-adblock modal dialog

http://www.wallpapermania.eu/wallpaper/beautiful-autumn-cover-hundreds-of-leaves-on-the-path

Appreciate your work and you spending your time to help us all :+1:

**Comment by mskadu** [comment]
Sorry forgot to add

http://imgbox.com/RzOnDvwh
Google Chrome (latest)
Adblockplus
- Adblock Warning Removal List Last updated at 3:37:30 PM on 2/10/2016
- EasyList Last updated at 9:45:39 AM on 2/6/2016
- AakList (Anti-Adblock Killer) Last updated at 8:49:42 AM today

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Solution:
<code>@@||wallpapermania.eu/assets/js/ads.js$xmlhttprequest</code>

**Comment by mskadu** [comment]
Added to Adblockplus custom filters - until they come through your own file. And it works like a prompt. Many thanks for the prompt fix.

**Comment by reek** [comment]
:smile:

**Comment by mskadu** [comment]
sure...  I am assuming you will close this issue when you are ready? As far as I am concerned, this is done and dusted.

**Comment by reek** [comment]
I would close issue when the AakList will be updated.

2016-02-11 17:53 GMT+01:00 MK <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
