### ISSUE TITLE
zeusnews.it

### ISSUE THREAD

**Issue by tmptmptmptmp** [reek/anti-adblock-killer#1024]
http://www.zeusnews.it/n.php?c=23948
http://imgbox.com/gegCsGa
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + Adblock warning removal list + AakList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by tmptmptmptmp** [comment]
Troubles with it reek?

**Comment by reek** [comment]
No, I already have the solution :smile:

**Comment by tmptmptmptmp** [comment]
Nice. So, should we wait till the next release to see it?

**Comment by reek** [comment]
Yes

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by tmptmptmptmp** [comment]
It works thanks :)
