### ISSUE TITLE
cheminots.net

### ISSUE THREAD

**Issue by SpecialTerminator** [reek/anti-adblock-killer#1025]
http://www.cheminots.net/forum/
https://imgur.com/BfItAwb
Mozilla Firefox 44.0.1 (on GNU/Linux)
Greasemonkey
Adblock Plus
Liste FR EasyList + Adblock Warning Removal List + EasyList Germany + AakList + Malware Domains + Prebake Filters Obstructive Cookie Notices

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
