### ISSUE TITLE
lepoint.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1027]
Hi, 
on `http://www.lepoint.fr/`

```
@@||lepoint.fr/static/js/publicite.js$script
@@||foglio.basilic.io/ad/basilic.adsense.js$script
```

![lepoint.fr](http://i.imgur.com/Cs0WeJ4.png)

Thanks!

#1035

**Comment by reek** [comment]
Ok, thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Need an update https://forums.lanik.us/viewtopic.php?f=91&t=30548#p95844

**Comment by reek** [comment]
Ok, I'll fix it.
Rule: `@@||lepoint.fr/publicite/validation/block/pub.js$script,~third-party`

**Comment by reek** [comment]
done
