### ISSUE TITLE
gamingroom.tv

### ISSUE THREAD

**Issue by Keopha** [reek/anti-adblock-killer#103]
gamingroom.tv/*
http://imgur.com/SH0bgA2
Google Chrome
Tampermonkey
Adblock + & Adblock
http://imgur.com/iyRhyRy

So here is the problem, okay it block adblocker, but i think the site is detecting it because I lose connexion to the chat everytime i use the anti adblock killer :/

**Comment by chway** [comment]
Hi, after adding the following line in my whitelist:

@@||ad4.liverail.com^$xmlhttprequest,domain=gamingroom.tv

I don't lose the connexion with the chat and still no ads.
I hope it can help.

**Comment by reek** [comment]
HI,

Thanks, I will add

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
