### ISSUE TITLE
rte.ie

### ISSUE THREAD

**Issue by DECEiFER** [reek/anti-adblock-killer#1030]
http://rte.ie/player

Detection present when playing videos. The damn commercials are too long!

Stats:
Google Chrome
Tampermonkey
uBlock Origin / Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,

Try <code>@@||bs.serving-sys.com/crossdomain.xml$object-subrequest,domain=rte.ie</code>

**Comment by DECEiFER** [comment]
Hi Reek,

Absolutely fantastic - it works! What's the logic behind that address, is that the CDN, and would you happen to be using Wireshark to pick these things up? It's been awhile since I've went packet sniffing!

Thank you very much.

What are the odds on this being added to "the list" so that everyone else using the service can enjoy it ad-free?

**Comment by reek** [comment]
Hi,

:smile: not need Wireshark, just look what the blocked resources

of course I'll add it to AakList.

See you
Reek

**Comment by DECEiFER** [comment]
D'oh, of course. I tend to overcomplicate things.

Thank you very much for your help. Great success!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
