### ISSUE TITLE
jyllands-posten.dk

### ISSUE THREAD

**Issue by klausenbusk** [reek/anti-adblock-killer#1031]
http://jyllands-posten.dk/debat/breve/ECE8432147/hvor-er-barnets-ret/
Mozilla Firefox
I don't use any "script manager".
uBlock Origin
EasyList + 10 others. Tried with just EasyList + this list, same result.

Unblocking http://jyllands-posten.dk/js/ads.js seems to fix it.
![screen shot 2016-02-12 at 08 11 25](https://cloud.githubusercontent.com/assets/1080056/13000891/4a1a56fe-d160-11e5-978c-0fc55ec9d68f.png)

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
