### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by ankitarmani** [reek/anti-adblock-killer#1032]
www.bild.de
http://imgur.com/2N2UYql
Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by IDKwhattoputhere** [comment]
Why did you close? The site doesn't work like I said here: https://github.com/reek/anti-adblock-killer/issues/817#issuecomment-179509301

**Comment by reek** [comment]
Its killed for me

**Comment by ankitarmani** [comment]
I closed the ticket because I saw a duplicate.

**Comment by ankitarmani** [comment]
Just for info: its working fine with Chrome.
