### ISSUE TITLE
afreesms.com

### ISSUE THREAD

**Issue by sachinsuyash** [reek/anti-adblock-killer#1033]
http://www.afreesms.com
https://imgur.com/J4TKa5k
Google Chrome
Tampermonkey
uBlock
AdBlock Warning Removal List+EasyList+EasyPrivacy+Malware Domain List+AakList+PeteLowe'sAdServerList

Note- Happens when you try sending the message after typing it.

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by uBlock-user** [comment]
for uBO, add - `afreesms.com##script:inject(abort-on-property-read.js, blockAdBlock)`
