### ISSUE TITLE
lepoint.fr

### ISSUE THREAD

**Issue by Francois-dag** [reek/anti-adblock-killer#1035]
is boring by now ...

Cheers.

FD

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by SMed79** [comment]
screenshot: http://i.imgur.com/EypmTXy.png
`@@||lepoint.fr/html/pub/publicite.js$script`
https://hg.adblockplus.org/listefr/rev/20583b7a828d

**Comment by reek** [comment]
Ok, thanks Med :+1:

**Comment by Francois-dag** [comment]
tahnx a lot !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
