### ISSUE TITLE
shencomics.com

### ISSUE THREAD

**Issue by Mrhohoho** [reek/anti-adblock-killer#1036]
http://www.shencomics.com/archives/621073    

http://www.shencomics.com/

Screenshot : It loads Just Blank page
http://imgur.com/Z1LC51z

Win7, Chrome with adblock with AdBlock custom filters + EasyList + AakList (Anti-Adblock Killer)
+ Adblock Warning Removal list (removes warnings about using ad blockers)

Using Tempermonkey

This site is used by main site 'marumaru.in' (which is not a problem) to link each of it's manga.
I wrote the Ex page 'www.shencomics.com/archives/621073' which is blocking adblock
and it seems their domain page 'www.shencomics.com' blocks adblock either.
 but main issue is blocked adblock at subpages of /archives/ folders.

thx.

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Try this rule
<code>@@||adr.realclick.co.kr/favicon.ico$subdocument,image,domain=shencomics.com</code>

**Comment by Mrhohoho** [comment]
Works like a charm.
thx

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
