### ISSUE TITLE
filespace.com

### ISSUE THREAD

**Issue by yushhh** [reek/anti-adblock-killer#1037]
http://filespace.com/958lwhpt8gzi
https://imgur.com/p3LTdqm
Firefox 44.0.2
Greasemonkey 3.6
uBlock Origin 1.6.0
Adblock Warning Removal List + Anti-Adblock Killer | Reek + EasyList + Peter Lowe's Ad server list + EasyPrivacy + Malware Domain List + Malware domains + AakList

And same link, but with these browser specs:
Safari 6.1.6
Tampermonkey 4.0
uBlock Origin 0.9.5.2
Adblock Warning Removal List + Anti-Adblock Killer | Reek + EasyList + Peter Lowe's Ad server list + EasyPrivacy + Malware Domain List + Malware domains + AakList

Note: Happens when you click the blue Slow Speed Download button.

**Comment by reek** [comment]
Hi, 

Ok, I'll kill it

**Comment by maynak00** [comment]
**try with:**(custom filter)
>@@||filespace.com$elemhide
filespace.com#@##ads-top
filespace.com#@##ads-right

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
