### ISSUE TITLE
free-steam-giveaways.com

### ISSUE THREAD

**Issue by pitichampi** [reek/anti-adblock-killer#1039]
http://www.free-steam-giveaways.com
http://i.imgur.com/Lv8GIHC.png
Safari
Tampermonkey
Adblock (getadblock)
EasyList + AakList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by maynak00** [comment]
**try this:**(custom filter)
>free-steam-giveaways.com#@##adsense

*thanks @MajkiIT for #@##adsense*

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
