### ISSUE TITLE
cnx-software.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1042]
reek can you please look at this again adblock is back 

https://github.com/reek/anti-adblock-killer/issues/937

**Comment by Giwayume** [comment]
Try this
`cnx-software.com##img[src="/pic/support_cnx-software.png"]`

**Comment by xxcriticxx** [comment]
yep that works

**Comment by maynak00** [comment]
same filter @Giwayume 
>||www.cnx-software.com/pic/support_cnx-software.png

**or another custom filter:**
>@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=cnx-software.com
www.cnx-software.com###aswift_0
www.cnx-software.com###aswift_0_anchor
www.cnx-software.com###aswift_0_expand

**Comment by Giwayume** [comment]
@maynak00 
That is not the same. My filter hides the image element. Yours prevents the image from loading. In your case either the image alt text will show or you will see a broken image icon in Firefox (undesirable).

**Comment by reek** [comment]
@Giwayume 
@maynak00 
Thanks för solutions

**Comment by fabiobarao94** [comment]
this works too 
www.cnx-software.com/pic/*.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
