### ISSUE TITLE
mangahen.com

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#1043]
http://www.mangahen.com/sonna_mirai_wa_uso_de_aru/74/
http://i.imgur.com/o6zirSE.png
Firefox 42
uBlock Origin 1.6.0
EasyList, Peter Lowe's Ad Server List, AAK List

This is caused by an inline script block.

Hides the message (arbitrary)
```
.wpm_pag p[style*="color:#000;font-size:22px;border:1px solid red;"] {
        display: none;
}
```
Shows the page
```
.manga-page {
        display: block !important;
}
```

**Comment by maynak00** [comment]
**try with:(temporary solution)**
>@@||mangahen.com$elemhide
www.mangahen.com##.adblock
www.mangahen.com##.adsbygoogle

**Comment by Giwayume** [comment]
+1 for simplicity
`mangahen.com#@#.afs_ads`

**Comment by SMed79** [comment]
Element hiding rules (**##.adblock** & **##.adsbygoogle**) will have no effect with **$elemhide** on main site which it is applied.

Adblock Plus users should use : **$generichide**
```
@@||mangahen.com^$generichide
mangahen.com##.adblock
mangahen.com##.adsbygoogle
```

* https://adblockplus.org/en/filters#advanced (Type options > elemhide)
* [https://adblockplus.org/development-builds/new-filter-options-generichide...](https://adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock) (new filters)

+10 for simplicity ;-)

**Comment by reek** [comment]
I agree for simplicity :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
