### ISSUE TITLE
rte.ie/player

### ISSUE THREAD

**Issue by germaloney11** [reek/anti-adblock-killer#1044]
http://www.rte.ie/player/ie/show/the-late-late-show-68/10529826
http://imgur.com/hGhrlzT
Google Chrome
AdBlock
EasyList + AakList

**Comment by germaloney11** [comment]
Fixed it
@@||bs.serving-sys.com/crossdomain.xml$object-subrequest,domain=rte.ie

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1030
