### ISSUE TITLE
tv3.ie/3player

### ISSUE THREAD

**Issue by germaloney11** [reek/anti-adblock-killer#1045]
http://www.tv3.ie/3player/show/573/102557/0/The-People%27s-Debate-with-Vincent-Browne
http://imgur.com/XRAdyak
Google Chrome
AdBlock
EasyList + AakList

**Comment by Giwayume** [comment]
I have to say they've got a pretty solid ad solution. All integrated into flash and random URLs. Tough to crack.

**Comment by germaloney11** [comment]
That sucks :(

Do you know if there's a beginners guide to finding and filtering unblocked ads as I would love to be able to contribute?

**Comment by Giwayume** [comment]
It's all based on general knowledge of web technologies: Javascript, CSS, HTML. Additionally all adblockers share a common filter syntax which is what AakList uses.
