### ISSUE TITLE
exrapidleech.info

### ISSUE THREAD

**Issue by kepalmer** [reek/anti-adblock-killer#1046]
http://www.exrapidleech.info/sample.html
I keep getting redirected to below page:

For support us maintain the service please disable ads blocking on our site, turn on popup on our site
Contact support@exrapidleech.info if you need more help
Your web browser is verified, you can access the site.Click here.
Contact us with this screenshot if you had problem 

The changelog says you killed this anti-adblock in jan? It came back to life. :(

**Comment by Giwayume** [comment]
Modifications for the existing script:
```
exrapidleech_info : {
      // by: Alexander255
      // patch: http://pastebin.com/Q664diQ2
      // issue: https://github.com/reek/anti-adblock-killer/issues/830
      // issue: https://github.com/reek/anti-adblock-killer/issues/777
      // issue: https://github.com/reek/anti-adblock-killer/issues/745
      // issue: https://github.com/reek/anti-adblock-killer/issues/729
      // issue: https://github.com/reek/anti-adblock-killer/issues/573
      host : ['exrapidleech.info'],
      onStart : function () {

        // 2015.12.07: http://pastebin.com/aEJ0rGtj
        Object.defineProperty(Aak.uw, 'dec_pid', {
          value : 383865
        });

        Object.defineProperty(Aak.uw, 'bdvbnr_pid', {
          value : 383865
        });

        Aak.addStyle('#blckviddiv {width:0px;height:0px;visibility:hidden;overflow:hidden;}');
        
        Aak.addScript(function () {
          var frame;
          frame = document.createElement('iframe');
          frame.src = 'http://bdfrm.bidvertiser.com/sakjfklwqerjlkjas';
          frame.id = 'bdv';
          frame.style = 'position:absolute; top:-9999px;';
          document.documentElement.appendChild(frame);
          frame = document.createElement('iframe');
          frame.src = 'http://www.example.com/';
          frame.id = 'bdvi';
          frame.style = 'display:none';
          document.documentElement.appendChild(frame);
        });

      }
    },
```

**Comment by reek** [comment]
@kepalmer 
Ok, I'll fix it

@Giwayume 
Well done :+1:

**Comment by kepalmer** [comment]
Thanks @Giwayume. The modifications work for me :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
