### ISSUE TITLE
downloads.codefi.re

### ISSUE THREAD

**Issue by munblocked** [reek/anti-adblock-killer#1048]
http://downloads.codefi.re/autoprime/LG/LG_G4/H811/H81120i/H81120i_00_0201.kdz
http://imgur.com/oRgUUkg
Google Chrome v.48.0.2564.109 m
Tapermonkey v3.12.58
uBlock Origin v.1.5.6
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**(custom filter)
>@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=downloads.codefi.re

**optional:**
>downloads.codefi.re###spo
downloads.codefi.re###spo2

**Comment by jgenender** [comment]
Well the veil can be removed with this filter:

www.wired.com##DIV#veil

Ok... well if I manually pull out the no-scroll, then I can scroll the page just peachy.  There seems to be a 5-10 second delay before some code activates the no-scroll.  Would be great to have it so its just blocked... so far I have not been able to do it...

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
