### ISSUE TITLE
derstandard.at

### ISSUE THREAD

**Issue by Ottobaer** [reek/anti-adblock-killer#105]
http://derstandard.at
http://imgur.com/bcqXYLX
Firefox
Greasemonkey
Adblock Edge
Adblock Warning Removal List 
Easylist Germany + Easylist 
Anti-Adblock Killer | Filters for Adblockers

**Comment by fwinest-JediThug** [comment]
Hi, the site now replaces images in all articles with this message:

![snapshot7](https://cloud.githubusercontent.com/assets/2891973/10894107/d20f2674-81ac-11e5-8825-14745f5c9432.png)

Could you please take a look at this again and open this issue?

**Comment by alexander255** [comment]
Cannot reproduce this. What lists/browser/addons/etc do you use?

**Comment by fwinest-JediThug** [comment]
ublock origin
easylist + deu
ublock filters
firefox 41.0.2
anti-adblock killer

**Comment by alexander255** [comment]
Some observations:

 * Affects only the primary page image gallery
 * Is only shown to returning visitors (cookie >30 Minutes?)

**Comment by alexander255** [comment]
Ok, I've figured out the mechanism they use for determining whether a person is a return visitor or not.
I'll provide an AAK script to fix.

**Comment by alexander255** [comment]
Fixed! This script should work: http://pastebin.com/raw.php?i=r7Q4DrfB

Rational for using script: The cookies injected by the site script are read by the image server and are used to actively replace the article picture (server-side).

@fwinest-JediThug You will need to use AAKScript, as updating/stripping parts of cookies is not something that an (uBlock) filter list can do.

**Comment by reek** [comment]
@alexander255 
Thank you for the fix

**Comment by fwinest-JediThug** [comment]
@alexander255 works like a charm, thank you!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Unrepentant-Atheist** [comment]
Just block cookies from derstandard.at
