### ISSUE TITLE
player.utv.ie/

### ISSUE THREAD

**Issue by germaloney11** [reek/anti-adblock-killer#1050]
http://player.utv.ie/programme/love-and-marriage
http://imgur.com/ttEyWEP
Google Chrome
AdBlock
EasyList + AakList

Volume controls/Fast forward options/Play and Pause panel also get removed when AdBlock is detected.

**Comment by Giwayume** [comment]
Does it happen when you visit the page or start a video? I'm not getting it. Also most of the videos say they're unavailable, probably due to my IP.

**Comment by germaloney11** [comment]
It's weird because when I visit it on my laptop that message doesn't show up and the videos plays without ads, however the media controls disapear when AdBlock is enabled.

But on my other laptop it shows the AdBlock detected message and ads are enabled when using AdBlock. I downloaded ABP to see if it was different on that and when using ABP it shows the AdBlock detected message.

If you're able to use an Irish VPN you should be able to see what I'm talking about.

**Comment by Giwayume** [comment]
Those two extensions probably have different filter lists installed by default. Maybe also try ublock just to see if that works for you. They have a bunch of filter list suggestions in their settings.
