### ISSUE TITLE
settlersonlinemaps.com

### ISSUE THREAD

**Issue by Adhater** [reek/anti-adblock-killer#1051]
Link: http://settlersonlinemaps.com/fastsim.php?MapaID=47&LangCode=2
Screenshot: http://imgbox.com/cZKsBNlG
Browser: Google Chrome Version 47.0.2526.106 m
Script manager: Tampermonkey
Adblocker: uBlock Origin
Filterists: uBlock filters + AakList

**Comment by jgenender** [comment]
Add:

`settlersonlinemaps.com##DIV#prb`

As a custom filter...

**Comment by Adhater** [comment]
Thanks, much appreciated!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
