### ISSUE TITLE
cityam.com

### ISSUE THREAD

**Issue by rossng** [reek/anti-adblock-killer#1054]
cityam.com does not seem to be working. I'm using uBlock Origin with EasyList, EasyPrivacy, Ablock Warning Removal List, Anti-Adblock Killer, Peter Lowe's Ad Server list, Malware Domain List, Malware domains.

[This is the code that appears to be doing it](https://gist.github.com/rossng/bb09335065ad61c779b8).

[Example page](http://www.cityam.com/234734/google-for-gifs-startup-giphy-raises-55m-valuing-search-platform-and-gif-creator-tool-at-300m)

![Screenshot](http://i.imgur.com/B7dQt5o.png?1)

**Comment by xxcriticxx** [comment]
you got user scripts installed?

show us your setup + link to the story

**Comment by IDKwhattoputhere** [comment]
http://www.cityam.com/234734/google-for-gifs-startup-giphy-raises-55m-valuing-search-platform-and-gif-creator-tool-at-300m

Seems to have been fixed now in EasyList by allowing a bunch of tracking and advertising scripts to run. Not great but it works.

@rossng Update your filter lists. Also disable any other blocking extensions like Ghostery, Disconnect and such.

**Comment by SMed79** [comment]
also see https://forums.lanik.us/viewtopic.php?f=64&p=87377#p87373

**Comment by reek** [comment]
@rossng 
See instruction: https://github.com/reek/anti-adblock-killer#instruction
