### ISSUE TITLE
noticiasautomotivas.com.br

### ISSUE THREAD

**Issue by Caf4** [reek/anti-adblock-killer#1055]
I was getting a page saying that the site www.noticiasautomotivas.com.br was blocked because I was using an adblock. They are using blockadblock.com.

I'm using Firefox 44.0.2, and looking at the debugger window of Firefox, I saw a message stating that it blocked a google analytics javascript.

I disabled the tracking blocking from Firefox and, reloading the page, it now didn't detect the adblock extension I'm using (uBlock Origin). The page loaded without any ads.

So maybe more people are having this issue because of the Firefox blocking, not because anti-adblock-killer is not working.

**Comment by IDKwhattoputhere** [comment]
Try `
noticiasautomotivas.com.br##script:inject(bab-defuser.js)`.

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
