### ISSUE TITLE
linkshrink.net 

### ISSUE THREAD

**Issue by mozkan007** [reek/anti-adblock-killer#1056]
Hi I am using Ublock origin 1.6.0 with latest Aak, Easylist, Peter Lowe's Ad Server List filters on Google Chrome 48 but linkshrink.net is blocking adblocker and shows a warning to disable adblocker.

http://imgur.com/H9SQt5b

**Comment by Giwayume** [comment]
Clickable -> http://linkshrink.net/7GLbtA

I'm not getting the "please disable adblock" message. Can you follow the [report guide](https://github.com/reek/anti-adblock-killer/wiki/Report-Guide)?

**Comment by mozkan007** [comment]
Yes I tried your link and other linkshrink.net links I did not get any warning.It seems this was a paltry error.The problem is completely solved.You can close the topic.Thank you for your attention.

**Comment by reek** [comment]
@mozkan007 
Please read instruction
https://github.com/reek/anti-adblock-killer#instruction
