### ISSUE TITLE
videomega.tv (filmyiseriale.tv)

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1057]
Solution
@@&ad_$script,domain=videomega.tv (many domains and urls)

can you eliminate waiting for movie?

**Comment by Giwayume** [comment]
Here is AakScript for removing the countdown:
```
    filmyiseriale_tv : {
      host : ['filmyiseriale.tv'],
      onIdle : function () {
        var scripts = document.getElementsByTagName('script');
        for (var i=0, il=scripts.length; i<il; i++) {
          var scriptHtml = scripts[i].innerHTML;
          if (scriptHtml.indexOf('function agatka') > -1) {
            var redirectLink = scriptHtml.match(/location\.href\s\=\s\"(.*?)"/g)[0];
            window.location.href = redirectLink.substring(redirectLink.indexOf('"')+1, redirectLink.lastIndexOf('"'));
          }
        }
      }
    },
```
Method: loops through inline script tags on the page searching for the "agatka" function which redirects to the video. Sniffs the redirect link from it and redirects immediately.

**Comment by Giwayume** [comment]
Nevermind, I found a solution:
```
    filmyiseriale_tv : {
      host : ['filmyiseriale.tv'],
      onIdle : function () {
        var scripts = document.getElementsByTagName('script');
        for (var i=0, il=scripts.length; i<il; i++) {
          var scriptHtml = scripts[i].innerHTML;
          if (scriptHtml.indexOf('function agatka') > -1) {
            
            function navigateToUrl(url) {
                var f = document.createElement("FORM");
                f.action = url;
                var indexQM = url.indexOf("?");
                if (indexQM>=0) {
                    // the URL has parameters => convert them to hidden form inputs
                    var params = url.substring(indexQM+1).split("&");
                    for (var i=0; i<params.length; i++) {
                        var keyValuePair = params[i].split("=");
                        var input = document.createElement("INPUT");
                        input.type="hidden";
                        input.name  = keyValuePair[0];
                        input.value = keyValuePair[1];
                        f.appendChild(input);
                    }
                }
                document.body.appendChild(f);
                f.submit();
            }
            
            var redirectLink = scriptHtml.match(/location\.href\s\=\s\"(.*?)"/g)[0];
            redirectLink = redirectLink.substring(redirectLink.indexOf('"')+1, redirectLink.lastIndexOf('"'));
            navigateToUrl(redirectLink);
            
          }
        }
      }
    },
```

@reek 
Is there an existing Aak function similar to navigateToUrl that keeps the page referrer? You can't use `window.location.href` in this case because that sends an empty referrer which blocks the video. If not, I think navigateToUrl is a candidate to become `Aak.navigate` or something similar.

**Comment by MajkiIT** [comment]
@Giwayume thanks it's work. 
@reek Do you add this script to AAK?

**Comment by reek** [comment]
I'll try, I'll let you know

**Comment by Giwayume** [comment]
@reek 
I tried creating a link element but it wasn't sending the referrer in Firefox. Have you tested it?

**Comment by Giwayume** [comment]
That's working for me. I don't know why I had trouble using a link element before.

I found a case with footlocker where it's failing, but I think that's the website's fault.
http://www.filmyiseriale.tv/filmonline/1346/plan-doskonaE582y-inside-man.html

**Comment by reek** [comment]
@Giwayume 
yes, it's a bug with them, because the link is probably dead

**Comment by MajkiIT** [comment]
@Giwayume  and @reek thanks for yours help.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
