### ISSUE TITLE
noticiasautomotivas.com.br

### ISSUE THREAD

**Issue by diegoweb** [reek/anti-adblock-killer#1058]
http://www.noticiasautomotivas.com.br/
http://i.imgur.com/qbuFG8I.png
Google Chrome
Tampermonkey
Adblock / uBlock Origin
EasyList + AakList + Adblock Warning Removal list

**Comment by SMed79** [comment]
please see https://github.com/reek/anti-adblock-killer/issues/1006#issuecomment-179951869

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1055

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
