### ISSUE TITLE
massdj.org

### ISSUE THREAD

**Issue by TheFinalCut83** [reek/anti-adblock-killer#1060]
http://massdj.org/
http://i.imgur.com/au0X2PR.jpg
Firefox 44.0.2
uBlock Origin 1.6.1
Greasemonkey
EasyList, RU AdList, Adblock Warning Removal List‎, AakList

``` javascript
        $(document).ready(function() {
            setTimeout(function() {
                blocked = false;
                if (typeof(window.google_ad_output) == 'undefined' || typeof(Window.goog_content) == 'undefined') {
                    blocked = true;
                }
                if (blocked == true) {
                    $('#sus').html('<center><h2 style="color:#FF0000;font-size:32px">ATTENTION !!! DISABLE ADBLOCKER</h2><br></h2><a style="color:#FF0000;font-size:24px" href="javascript:window.location.reload();" onclick="window.location.reload();"><b>Click here to reload the page when you have deactivated your Adblocker, Ghostery.<br></b></a></center>');
                }
            }, 1000);
        });

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
