### ISSUE TITLE
backin.net

### ISSUE THREAD

**Issue by knzudgt** [reek/anti-adblock-killer#1061]
http://backin.net/s/streams.php?s=5ieirf25j7c6
http://imgbox.com/AfDKcKoP
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList + Peter Lowe’s Ad server list‎

```javascript
	 var ahei = $("#diva").height();
	 if (ahei < 10) {
	   document.getElementById('divd').style.display = 'block';
	   document.getElementById('hideadb').style.display = 'none';
	 }

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
