### ISSUE TITLE
abysstream.com

### ISSUE THREAD

**Issue by knzudgt** [reek/anti-adblock-killer#1062]
http://cineblog01.pw/HR/go.php?id=36950
http://imgbox.com/TpxrTkFv
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList + Peter Lowe’s Ad server list‎

The first link redirects to abysstream.com.
The corresponding abysstream url changes at every access.

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by fabiobarao94** [comment]
Add this to your filter list
@@||abysstream.com/ads.js

**Comment by knzudgt** [comment]
Many thanks fabiobarao94!

**Comment by fabiobarao94** [comment]
you're welcome

**Comment by reek** [comment]
@fabiobarao94 
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
