### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by HanSolo80** [reek/anti-adblock-killer#1063]
http://bild.de
http://imgur.com/D4jOBdv
Google Chrome
Tampermonkey
uBlock Origin
EasyList + Anti-Adblock Killer | Reek‎

**Comment by IDKwhattoputhere** [comment]
Use the search:
https://github.com/reek/anti-adblock-killer/issues/1032
https://github.com/reek/anti-adblock-killer/issues/817#issuecomment-179509301

**Comment by reek** [comment]
its killed for me

**Comment by IDKwhattoputhere** [comment]
@reek That's odd. It's not killed for me with the setup I linked. In Firefox however it works fine.

**Comment by reek** [comment]
@HanSolo80 
Go to option -> 3rd-party filters and uncheck <code>Parse and enforce cosmetic filters.</code>

**Comment by IDKwhattoputhere** [comment]
Yes, I tried that. See here https://github.com/reek/anti-adblock-killer/issues/817#issuecomment-179509301

**Comment by reek** [comment]
which lists used you ?

**Comment by IDKwhattoputhere** [comment]
Never mind. Ghostery was causing the issue. Seems like Ghostery does cosmetic filtering too. Sorry for the confusion.

**Comment by reek** [comment]
Ok

2016-02-21 20:59 GMT+01:00 IDKwhattoputhere <notifications@github.com>:
