### ISSUE TITLE
cekresi.com

### ISSUE THREAD

**Issue by aryacebe** [reek/anti-adblock-killer#1064]
Please add http://cekresi.com/ to the list. Thanks.

Spec:
Google Chrome 48.0.2564.109 m
Tampermonkey 3.12.58
AdBlock 2.50
EasyList + Adblock Warning Removal list  + AakList (Anti-Adblock Killer)
Screenshot: http://imgur.com/siZCzaw

Even I've paused the adblock for all sites, it site keeps asking me to deactivate the adblock.

**Comment by Giwayume** [comment]
Add this to your custom filters
`cekresi.com##.pleasehideadblkuc`

**Comment by reek** [comment]
@aryacebe 
Ok, I'll kill it

@Giwayume 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
