### ISSUE TITLE
New Way To Block Adblockers HELP Web site http://blockadblock.com/

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#1065]
Help please 
google chrome adblock plus

![image](https://cloud.githubusercontent.com/assets/15664251/13187505/4c40c650-d743-11e5-8025-c8138f7c8486.png)

i get this message

**Comment by fabiobarao94** [comment]
<script type="text/javascript"  charset="utf-8">
// Place this code snippet near the footer of your page before the close of the /body tag
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}(';j N=\'\',28=\'1O\';1y(j i=0;i<12;i++)N+=28.R(X.1z(X.1v()*28.F));j 2w=7,2k=\'2p\',2S=\'2p\';D[\'\'+N+\'\']=(B(){j e={e$:\'1O+/=\',46:B(t){j s=\'\',d,o,a,c,l,r,n,i=0;t=e.n$(t);1C(i<t.F){d=t.10(i++);o=t.10(i++);a=t.10(i++);c=d>>2;l=(d&3)<<4|o>>4;r=(o&15)<<2|a>>6;n=a&63;z(2u(o)){r=n=64}S z(2u(a)){n=64};s=s+O.e$.R(c)+O.e$.R(l)+O.e$.R(r)+O.e$.R(n)};H s},1c:B(t){j n=\'\',d,l,s,c,o,a,r,i=0;t=t.1i(/[^A-47-48-9\\+\\/\\=]/g,\'\');1C(i<t.F){c=O.e$.1G(t.R(i++));o=O.e$.1G(t.R(i++));a=O.e$.1G(t.R(i++));r=O.e$.1G(t.R(i++));d=c<<2|o>>4;l=(o&15)<<4|a>>2;s=(a&3)<<6|r;n=n+K.M(d);z(a!=64){n=n+K.M(l)};z(r!=64){n=n+K.M(s)}};n=e.t$(n);H n},n$:B(e){e=e.1i(/;/g,\';\');j n=\'\';1y(j i=0;i<e.F;i++){j t=e.10(i);z(t<1p){n+=K.M(t)}S z(t>45&&t<44){n+=K.M(t>>6|3Z);n+=K.M(t&63|1p)}S{n+=K.M(t>>12|2x);n+=K.M(t>>6&63|1p);n+=K.M(t&63|1p)}};H n},t$:B(e){j i=\'\',t=0,n=41=1n=0;1C(t<e.F){n=e.10(t);z(n<1p){i+=K.M(n);t++}S z(n>42&&n<2x){1n=e.10(t+1);i+=K.M((n&31)<<6|1n&63);t+=2}S{1n=e.10(t+1);2P=e.10(t+2);i+=K.M((n&15)<<12|(1n&63)<<6|2P&63);t+=3}};H i}};j r=[\'43==\',\'49\',\'4a=\',\'4h\',\'4i\',\'4j=\',\'4g=\',\'4f=\',\'4b\',\'4c\',\'4d=\',\'4e=\',\'3Y\',\'3X\',\'3J=\',\'3K\',\'3L=\',\'3I=\',\'3H=\',\'3D=\',\'3E=\',\'3F=\',\'3G==\',\'3M==\',\'3N==\',\'3U==\',\'3V=\',\'3W\',\'3T\',\'3S\',\'3O\',\'3P\',\'3Q\',\'3R==\',\'4k=\',\'4l=\',\'4O=\',\'4P==\',\'4Q=\',\'4N\',\'4M=\',\'4I=\',\'4J==\',\'4K=\',\'4L==\',\'4R==\',\'3C=\',\'4S=\',\'4Z\',\'51==\',\'52==\',\'4Y\',\'4X==\',\'4T=\'],v=X.1z(X.1v()*r.F),y=e.1c(r[v]),A=y,Q=1,p=\'#4U\',o=\'#4V\',g=\'#4W\',f=\'#4H\',w=\'\',u=\'4G!\',b=\'4s 4t 4u 4r\\\'4q 4m 4n 21 2l. 4o\\\'s 4p.  4v 4w\\\'t?\',h=\'4D 4E 4F-4C, 4B 4x\\\'t 4y 4z O 4A 53.\',m=\'I 2V, I 37 35 34 21 2l.  33 38 39!\',t=0,c=0,a=\'3d.3c\',d=0,W=n()+\'.3b\';B s(e){z(e)e=e.1E(e.F-15);j n=k.20(\'2M\');1y(j i=n.F;i--;){j t=K(n[i].2T);z(t)t=t.1E(t.F-15);z(t===e)H!0};H!1};B l(e){z(e)e=e.1E(e.F-15);j t=k.3a;x=0;1C(x<t.F){1f=t[x].1k;z(1f)1f=1f.1E(1f.F-15);z(1f===e)H!0;x++};H!1};B n(){j t=\'\',e=\'1O\';1y(j n=0;n<30;n++)t+=e.R(X.1z(X.1v()*e.F));H t};B i(e){z(D.3B==1){3v.3u(e)}};H{2o:B(t,o){z(3t k.G==\'3s\'){H};j i=\'0.1\',o=A,e=k.V(\'1m\');e.11=o;e.8.1d=\'1w\';e.8.17=\'-1a\';e.8.P=\'-1a\';e.8.16=\'1l\';e.8.U=\'3f\';j s=k.G.2d,r=X.1z(s.F/2);z(r>15){j n=k.V(\'26\');n.8.1d=\'1w\';n.8.16=\'1g\';n.8.U=\'1g\';n.8.P=\'-1a\';n.8.17=\'-1a\';k.G.3x(n,k.G.2d[r]);n.Z(e);j a=k.V(\'1m\');a.11=\'29\';a.8.1d=\'1w\';a.8.17=\'-1a\';a.8.P=\'-1a\';k.G.Z(a)}S{e.11=\'29\';k.G.Z(e)};d=3y(B(){z(e){t((e.1Y==0),i);t((e.1W==0),i);t((e.1B==\'2s\'),i);t((e.1x==\'2q\'),i);t((e.1r==0),i)}S{t(!0,i)}},1T)},1D:B(n,l){z((n)&&(t==0)){i(\'3r: 1U 1V 1R 1X 1u 1t\');t=1;D[\'\'+N+\'\'].1M();D[\'\'+N+\'\'].1D=B(){H}}S{j c=e.1c(\'3q\'),r=k.3i(c);z((r)&&(t==0)){z(2k==\'2O\'){i(\'1Q: 1U 1V 1R 1X 1u 2R 1t.\');j d=\'3l=\';d=e.1c(d);z(s(d)){i(\'1Q: 3p 2E 3o-3n.\');z(r.1s.1i(/\\s/g,\'\').F==0){i(\'1Q: 3w 1u 1t.\');D[\'\'+N+\'\'].1M()}}};t=1}S{z(t==0){z(2S==\'2O\'){j o=\'3h==\';o=e.1c(o);i(\'3j: 1U 1V 1R 1X 1u 2R 1t. 2Y ???  2X 2E 2W 2Z. 32 2G 3g 3e 21 3z 2G 24...\');j a=k.V(\'2M\');a.1j(\'2K\',\'1P/3k\');a.1j(\'2T\',o);a.3m=B(){D[\'\'+N+\'\'].1M()};t=1;z(!s(o)){k.20(\'24\')[0].Z(a)};r=0;D[\'\'+N+\'\'].1D=B(){H}}}}}},1M:B(){z(c==1){j Y=2m.3A(\'2b\');z(Y>0){H!0}S{2m.6z(\'2b\',(X.1v()+1)*1T)}};j y=\'6A==\';y=e.1c(y);z(!l(y)){j v=k.V(\'6y\');v.1j(\'6x\',\'6v\');v.1j(\'2K\',\'1P/6w\');v.1j(\'1k\',y);k.20(\'24\')[0].Z(v)};6B(d);k.G.1s=\'\';k.G.8.13+=\'L:1g !14\';k.G.8.13+=\'1o:1g !14\';j E=k.2J.1W||D.2L||k.G.1W,A=D.6C||k.G.1Y||k.2J.1Y,r=k.V(\'1m\'),x=n();r.11=x;r.8.1d=\'2c\';r.8.17=\'0\';r.8.P=\'0\';r.8.U=E+\'1h\';r.8.16=A+\'1h\';r.8.2A=p;r.8.1S=\'6H\';k.G.Z(r);j s=\'<a 1k="6I://6G.6F"><2v 11="2r" U="2N" 16="40"><2I 11="2n" U="2N" 16="40" 6D:1k="6E:2I/6K;6t,6j+6k+6i+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+q+54+6h+6f/6g/6l/6m/6r/6s+/6q/6p+6n/6o+6J/73/76/72/75/78/77+6Z/6P+6Q+6O+6N+70+6M/6S+6X/6Y+6T/6U+6L+6V+6W+6R/71+74/6u/6d/5r+5s+5q/5p+5m+5n+5o+E+5t/5u/5z/5A/5y/5x/+5v/5w++5l/5k/5a+5b/6e+59+58==">;</2v></a>\';s=s.1i(\'2r\',n());s=s.1i(\'2n\',n());j i=k.V(\'1m\');i.1s=s;i.8.1d=\'1w\';i.8.1q=\'2t\';i.8.17=\'2t\';i.8.U=\'55\';i.8.16=\'56\';i.8.1S=\'2i\';i.8.1r=\'.6\';i.8.2h=\'2g\';i.57(\'5c\',B(){a=a.5d(\'\').5i().5j(\'\');D.2z.1k=\'//\'+a});k.1A(x).Z(i);j t=k.V(\'1m\'),T=n();t.11=T;t.8.1d=\'2c\';t.8.P=A/7+\'1h\';t.8.5h=E-5g+\'1h\';t.8.5e=A/3.5+\'1h\';t.8.2A=\'#5f\';t.8.1S=\'2i\';t.8.13+=\'J-1L: "5B 5C", 1N, 1H, 1I-1J !14\';t.8.13+=\'5Z-16: 61 !14\';t.8.13+=\'J-1e: 5Y !14\';t.8.13+=\'1P-5X: 5U !14\';t.8.13+=\'1o: 5V !14\';t.8.1B+=\'2C\';t.8.2U=\'1l\';t.8.5W=\'1l\';t.8.62=\'2a\';k.G.Z(t);t.8.66=\'1g 6b 6c -6a 69(0,0,0,0.3)\';t.8.1x=\'2y\';j w=30,Q=22,W=18,C=18;z((D.2L<2D)||(67.U<2D)){t.8.2Q=\'50%\';t.8.13+=\'J-1e: 68 !14\';t.8.2U=\'5T;\';i.8.2Q=\'65%\';j w=36,Q=27,W=22,C=22};t.1s=\'<2B 8="1b:#5S;J-1e:\'+w+\'1F;1b:\'+o+\';J-1L:1N, 1H, 1I-1J;J-1K:5I;L-P:19;L-1q:19;">\'+u+\'</2B><2F 8="J-1e:\'+Q+\'1F;J-1K:5J;1b:\'+o+\';L-P:19;L-1q:19;">\'+b+\'</2F><5H 8=" 1B: 2C;L-P: 0.2H;L-1q: 0.2H;L-17: 23;L-2e: 23; 2f:5G 5D #5E; U: 25%;"><p 8="J-1L:1N, 1H, 1I-1J;J-1K:2j;J-1e:\'+W+\'1F;1b:\'+o+\';">\'+h+\'</p><p 8="L-P:5F;"><26 5K="O.8.1r=.9;" 5L="O.8.1r=1;"  11="\'+n()+\'" 8="2h:2g;J-1e:\'+C+\'1F;J-1L:1N, 1H, 1I-1J; J-1K:2j;2f-5Q:2a;1o:19;5R-1b:\'+g+\';1b:\'+f+\';1o-17:1l;1o-2e:1l;U:60%;L:23;L-P:19;L-1q:19;" 5P="D.2z.5O();">\'+m+\'</26></p>\'}}})();k.G.8.1x=\'2y\';z(k.1A(\'1Z\')){k.1A(\'1Z\').8.1x=\'2s\';k.1A(\'1Z\').8.1B=\'2q\'};5M(\'D[\\\'\\\' + N + \\\'\\\'].2o(D[\\\'\\\' + N + \\\'\\\'].1D, D[\\\'\\\' + N + \\\'\\\'].5N)\',2w*1T);',62,443,'||||||||style|||||||||||var|document||||||vr6|||||||||if||function||window||length|body|return||font|String|margin|fromCharCode|KADKQXtCsKis|this|top||charAt|else||width|createElement||Math||appendChild|charCodeAt|id||cssText|important||height|left||10px|5000px|color|decode|position|size|thisurl|0px|px|replace|setAttribute|href|60px|DIV|c2|padding|128|bottom|opacity|innerHTML|blocked|are|random|absolute|visibility|for|floor|getElementById|display|while|EepEtvNRtt|substr|pt|indexOf|geneva|sans|serif|weight|family|ZrFDcwBvZT|Helvetica|ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789|text|case2|says|zIndex|1000|standard|bait|clientWidth|ads|clientHeight|babasbmsgx|getElementsByTagName|ad||auto|head||div||MGSOeUAjgD|banner_ad|15px|babn|fixed|childNodes|right|border|pointer|cursor|10000|300|aDefOne|blocker|sessionStorage|FILLVECTID2|bab|no|none|FILLVECTID1|hidden|30px|isNaN|svg|WtKCWMYxiY|224|visible|location|backgroundColor|h3|block|640|Adsense|h1|to|5em|image|documentElement|type|innerWidth|script|160|yes|c3|zoom|NOT|aDefTwo|src|marginLeft|understand|is|No|Maybe|found|||Attempting|Let|my|disabled||have|me|in|styleSheets|jpg|kcolbdakcolb|moc|Google|468px|add|Ly9zdGF0aWMuZG91YmxlY2xpY2submV0L2luc3RyZWFtL2FkX3N0YXR1cy5qcw|querySelector|case3|javascript|Ly9wYWdlYWQyLmdvb2dsZXN5bmRpY2F0aW9uLmNvbS9wYWdlYWQvanMvYWRzYnlnb29nbGUuanM|onerror|exists|pre|And|aW5zLmFkc2J5Z29vZ2xl|case1|undefined|typeof|log|console|Ads|insertBefore|setInterval|code|getItem|consolelog|YWRzZXJ2ZXI|QWRGcmFtZTQ|QWRMYXllcjE|QWRMYXllcjI|QWRzX2dvb2dsZV8wMQ|QWRGcmFtZTM|QWRGcmFtZTI|QWQ3Mjh4OTA|QWRBcmVh|QWRGcmFtZTE|QWRzX2dvb2dsZV8wMg|QWRzX2dvb2dsZV8wMw|RGl2QWRB|RGl2QWRC|RGl2QWRD|QWRJbWFnZQ|RGl2QWQz|RGl2QWQy|QWRzX2dvb2dsZV8wNA|RGl2QWQ|RGl2QWQx|QWQzMDB4MjUw|QWQzMDB4MTQ1|192||c1|191|YWQtbGVmdA|2048|127|encode|Za|z0|YWRCYW5uZXJXcmFw|YWQtZnJhbWU|YWQtZm9vdGVy|YWQtY29udGFpbmVy|YWQtY29udGFpbmVyLTE|YWQtY29udGFpbmVyLTI|YWQtbGI|YWQtbGFiZWw|YWQtaGVhZGVy|YWQtaW1n|YWQtaW5uZXI|QWREaXY|QWRCb3gxNjA|using|an|That|okay|re|you|It|looks|like|Who|doesn|can|keep|making|site|we|income|But|without|advertising|Welcome|FFFFFF|YWRiYW5uZXI|YWRBZA|YmFubmVyYWQ|IGFkX2JveA|YWRCYW5uZXI|YmFubmVyX2Fk|QWRDb250YWluZXI|Z2xpbmtzd3JhcHBlcg|YWRUZWFzZXI|YWRfY2hhbm5lbA|YmFubmVyaWQ|c3BvbnNvcmVkX2xpbms|EEEEEE|777777|adb8ff|b3V0YnJhaW4tcGFpZA|Z29vZ2xlX2Fk|YWRzbG90||cG9wdXBhZA|YWRzZW5zZQ|awesome|sAAADMAAAsKysKCgokJCRycnIEBATq6uoUFBTMzMzr6urjqqoSEhIGBgaxsbHcd3dYWFg0NDTmw8PZY2M5OTkfHx|160px|40px|addEventListener|gkJocgFtzfMzwAAAABJRU5ErkJggg|3eUeuATRaNMs0zfml|uJylU|dEflqX6gzC4hd1jSgz0ujmPkygDjvNYDsU0ZggjKBqLPrQLfDUQIzxMBtSOucRwLzrdQ2DFO0NDdnsYq0yoJyEB0FHTBHefyxcyUy8jflH7sHszSfgath4hYwcD3M29I5DMzdBNO2IFcC5y6HSduof4G5dQNMWd4cDcjNNeNGmb02|click|split|minHeight|fff|120|minWidth|reverse|join|Kq8b7m0RpwasnR|u3T9AbDjXwIMXfxmsarwK9wUBB5Kj8y2dCw|j9xJVBEEbWEXFVZQNX9|1HX6ghkAR9E5crTgM|0t6qjIlZbzSpemi|E5HlQS6SHvVSU0V|bTplhb|x0z6tauQYvPxwT0VM1lH9Adt5Lp|F2Q|MjA3XJUKy|SRWhNsmOazvKzQYcE0hV5nDkuQQKfUgm4HmqA2yuPxfMU1m4zLRTMAqLhN6BHCeEXMDo2NsY8MdCeBB6JydMlps3uGxZefy7EO1vyPvhOxL7TPWjVUVvZkNJ|QhZLYLN54|e8xr8n5lpXyn|14XO7cR5WV1QBedt3c|BNyENiFGe5CxgZyIT6KVyGO2s5J5ce|CGf7SAP2V6AjTOUa8IzD3ckqe2ENGulWGfx9VKIBB72JM1lAuLKB3taONCBn3PY0II5cFrLr7cCp|UIWrdVPEp7zHy7oWXiUgmR3kdujbZI73kghTaoaEKMOh8up2M8BVceotd|Arial|Black|solid|CCC|35px|1px|hr|200|500|onmouseover|onmouseout|setTimeout|bab_elementid|reload|onclick|radius|background|999|45px|center|12px|marginRight|align|16pt|line||normal|borderRadius||||boxShadow|screen|18pt|rgba|8px|14px|24px|pyQLiBu8WDYgxEZMbeEqIiSM8r|Uv0LfPzlsBELZ|fn5EREQ9PT3SKSnV1dXks7OsrKypqambmpqRkZFdXV1RUVHRISHQHR309PTq4eHp3NzPz8|Ly8vKysrDw8O4uLjkt7fhnJzgl5d7e3tkZGTYVlZPT08vLi7OCwu|enp7TNTUoJyfm5ualpaV5eXkODg7k5OTaamoqKSnc3NzZ2dmHh4dra2tHR0fVQUFAQEDPExPNBQXo6Ohvb28ICAjp19fS0tLnzc29vb25ubm1tbWWlpaNjY3dfX1oaGhUVFRMTEwaGhoXFxfq5ubh4eHe3t7Hx8fgk5PfjY3eg4OBgYF|sAAADr6|iVBORw0KGgoAAAANSUhEUgAAAKAAAAAoCAMAAABO8gGqAAAB|1BMVEXr6|v792dnbbdHTZYWHZXl7YWlpZWVnVRkYnJib8|PzNzc3myMjlurrjsLDhoaHdf3|cIa9Z8IkGYa9OGXPJDm5RnMX5pim7YtTLB24btUKmKnZeWsWpgHnzIP5UucvNoDrl8GUrVyUBM4xqQ|ISwIz5vfQyDF3X|ejIzabW26SkqgMDA7HByRAADoM7kjAAAAInRSTlM6ACT4xhkPtY5iNiAI9PLv6drSpqGYclpM5bengkQ8NDAnsGiGMwAABetJREFUWMPN2GdTE1EYhmFQ7L339rwngV2IiRJNIGAg1SQkFAHpgnQpKnZBAXvvvXf9mb5nsxuTqDN|b29vlvb2xn5|aa2thYWHXUFDUPDzUOTno0dHipqbceHjaZ2dCQkLSLy|v7|base64|kmLbKmsE|stylesheet|css|rel|link|setItem|Ly95dWkueWFob29hcGlzLmNvbS8zLjE4LjEvYnVpbGQvY3NzcmVzZXQvY3NzcmVzZXQtbWluLmNzcw|clearInterval|innerHeight|xlink|data|com|blockadblock|9999|http|MgzNFaCVyHVIONbx1EDrtCzt6zMEGzFzFwFZJ19jpJy2qx5BcmyBM|png|QcWrURHJSLrbBNAxZTHbgSCsHXJkmBxisMvErFVcgE|uWD20LsNIDdQut4LXA|1FMzZIGQR3HWJ4F1TqWtOaADq0Z9itVZrg1S6JLi7B1MAtUCX1xNB0Y0oL9hpK4|CXRTTQawVogbKeDEs2hs4MtJcNVTY2KgclwH2vYODFTa4FQ|RUIrwGk|qdWy60K14k|UADVgvxHBzP9LUufqQDtV|KmSx|iqKjoRAEDlZ4soLhxSgcy6ghgOy7EeC2PI4DHb7pO7mRwTByv5hGxF|I1TpO7CnBZO|h0GsOCs9UwP2xo6|UimAyng9UePurpvM8WmAdsvi6gNwBMhPrPqemoXywZs8qL9JZybhqF6LZBZJNANmYsOSaBTkSqcpnCFEkntYjtREFlATEtgxdDQlffhS3ddDAzfbbHYPUDGJpGT|0nga14QJ3GOWqDmOwJgRoSme8OOhAQqiUhPMbUGksCj5Lta4CbeFhX9NN0Tpny|BKpxaqlAOvCqBjzTFAp2NFudJ5paelS5TbwtBlAvNgEdeEGI6O6JUt42NhuvzZvjXTHxwiaBXUIMnAKa5Pq9SL3gn1KAOEkgHVWBIMU14DBF2OH3KOfQpG2oSQpKYAEdK0MGcDg1xbdOWy|EuJ0GtLUjVftvwEYqmaR66JX9Apap6cCyKhiV|YbUMNVjqGySwrRUGsLu6|uI70wOsgFWUQCfZC1UI0Ettoh66D|VOPel7RIdeIBkdo|oGKmW8DAFeDOxfOJM4DcnTYrtT7dhZltTW7OXHB1ClEWkPO0JmgEM1pebs5CcA2UCTS6QyHMaEtyc3LAlWcDjZReyLpKZS9uT02086vu0tJa|szSdAtKtwkRRNnCIiDzNzc0RO|HY9WAzpZLSSCNQrZbGO1n4V4h9uDP7RTiIIyaFQoirfxCftiht4sK8KeKqPh34D2S7TsROHRiyMrAxrtNms9H5Qaw9ObU1H4Wdv8z0J8obvOo|Lnx0tILMKp3uvxI61iYH33Qq3M24k|0idvgbrDeBhcK|wd4KAnkmbaePspA'.split('|'),0,{}))

</script>

**Comment by fabiobarao94** [comment]
[script they use.txt](https://github.com/reek/anti-adblock-killer/files/138622/script.they.use.txt)

**Comment by reek** [comment]
Already killed install AakScript, see instruction

**Comment by fabiobarao94** [comment]
Ok thanks, i turn on my tampermonkey script, i was testing in another web site that i can't pass because detects
here is the link http://lolsy.tv/4089-najlepsze-sekundowe-filmiki-czesc-10.html?all

the message is 
![image](https://cloud.githubusercontent.com/assets/15664251/13188158/9ab4a834-d747-11e5-9262-b8377a22908d.png)

it's not that i want that web site its that i want to help people with the same problem

**Comment by reek** [comment]
I have already planned to add <code>lolsy.tv</code>

**Comment by fabiobarao94** [comment]
thank you for your assistance, and all the people you help i would love to donate, for your help and your adblock killer, where can i do that

**Comment by reek** [comment]
Well, any contribution is welcome :smile:
https://github.com/reek/anti-adblock-killer#donate
