### ISSUE TITLE
selipuquoe.com

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1066]
https://github.com/gorhill/uBlock/issues/1389#issuecomment-186388057

**Comment by reek** [comment]
I have a blank page

**Comment by flyingzebras** [comment]
selipuquoe.com is added in an iframe created for example on http://jeu.info/ by this script http://dtf.goyavelab.com/dtct.js the trick is used exactly to avoid using an exception filter and eventually using a super-general exception filter which can enable ads on other sites. This main selipuquoe.com is used to detect if you block ads on your browser... (load only an pixel image 1x1).

all domains http://pastebin.com/raw/sJ9aaCX9

Try these filters on http://jeu.info/uphill-rush-6.html

@@||dtf.goyavelab.com/dtct.js$script
@@||selipuquoe.com^$image,~third-party
@@||infojeu.com/*.js?$script,third-party
@@||adnxs.com^$domain=jeu.info
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=jeu.info

**Comment by reek** [comment]
Already killed by AakScript <code>jeu.info</code>

**Comment by SMed79** [comment]
@flyingzebras the `goyavelab` trick is already killed by AakScript (see https://github.com/gorhill/uBlock/issues/1340)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by flyingzebras** [comment]
@reek What was added that is related to this issue?

**Comment by reek** [comment]
@flyingzebras 
https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L4041

**Comment by flyingzebras** [comment]
@reek Thank you!
