### ISSUE TITLE
onmeda.de

### ISSUE THREAD

**Issue by cpzruk123** [reek/anti-adblock-killer#1067]
http://www.onmeda.de/
http://imgur.com/RfrmsfT
Browsers: Firefox 44.0.2 
uBlock Origin
uBlock filters‎,   Anti-Adblock Killer | Reek‎, EasyList‎, EasyPrivacy‎m, Anti-ThirdpartySocial, Fanboy’s Annoyance List‎,Fanboy’s Social Blocking List‎, DEU: EasyList   ##Germany‎

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Thubb** [comment]
Does not work for me. Still getting the Adblocker message.

FF 45.0.1, Greasmonkey, uBlock Origin 1.6.5, AakList activated and updated, script version 9.4 installed.

When adding this filer:

onmeda.de##script:contains(adblocker)

to my own filter list the adblock message is gone.

**Comment by reek** [comment]
Ok, I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Thubb** [comment]
Seems to work fine now!

Thanks
