### ISSUE TITLE
gamersglobal.de

### ISSUE THREAD

**Issue by cpzruk123** [reek/anti-adblock-killer#1068]
http://www.gamersglobal.de/preview/dirt-rally-konsole?page=0,1
http://imgur.com/IwA85GO
Browsers: Firefox 44.0.2
uBlock Origin
uBlock filters‎, Anti-Adblock Killer | Reek‎, EasyList‎, EasyPrivacy‎m, Anti-ThirdpartySocial, Fanboy’s Annoyance List‎,Fanboy’s Social Blocking List‎, DEU: EasyList ##Germany‎

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by maynak00** [comment]
**try with:**(custom filter)
>@@||gamersglobal.de/wbg/www/delivery/spcjs.js$script

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
