### ISSUE TITLE
auto.cz

### ISSUE THREAD

**Issue by dmpe** [reek/anti-adblock-killer#1071]
Hello, 
Hey, can we try to kill this somehow ? Really terrible. 

http://www.auto.cz/
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

Thanks. 

![atuto](https://cloud.githubusercontent.com/assets/1799661/13197485/3ef6f918-d7ef-11e5-85e2-6487c506f9a2.PNG)

![atut2o](https://cloud.githubusercontent.com/assets/1799661/13197520/681b9e42-d7f0-11e5-8e48-78c42a5595b2.PNG)

**Comment by Giwayume** [comment]
Custom filter 
`auto.cz###abdiv,#blackdim`

**Comment by reek** [comment]
@dmpe 
Ok, I'll kill it

@Giwayume 
Thanks

**Comment by dmpe** [comment]
@Giwayume thanks! @reek - should i close this ?

**Comment by reek** [comment]
@dmpe 
No, I would do it at the appropriate time

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
