### ISSUE TITLE
creativeuncut.com

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#1072]
http://www.creativeuncut.com/gallery-30/hots-heaven-vs-hell.html
http://www.creativeuncut.com/int/interstitial.html?return_url=http://www.creativeuncut.com/gallery-01/dis-laharl1.html
http://i.imgur.com/owFSbdW.png
http://i.imgur.com/giEi3gr.png
Firefox 42
uBlock Origin 1.6.0
EasyList, Peter Lowe's Ad Server List, AAK List

There's an anti adblock message on individual image viewing pages, also a countdown when entering the site.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, but not the countdown.

**Comment by Giwayume** [comment]
What's your general rule for when removing countdowns is in the scope of AAK? It was done for #1057 but not here.

**Comment by reek** [comment]
There is not one, since it is not Aak to do it, therefore I will not add the rule.#1057

So you could create a user script

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
