### ISSUE TITLE
sport1.de

### ISSUE THREAD

**Issue by himself85** [reek/anti-adblock-killer#1075]
http://www.sport1.de/fussball/champions-league/2016/02/juventus-turin-fc-bayern-live-im-tv-stream-ticker-und-radio
http://imgbox.com/D8WjDkC9
http://imgbox.com/UtyqnAM6
Chrome
Tampermonkey
uBlock
uBlock filters‎, Anti-Adblock Killer | Reek‎, EasyList‎, EasyPrivacy‎m, Anti-ThirdpartySocial, Fanboy’s Annoyance List‎,Fanboy’s Social Blocking List‎, DEU: EasyList ##Germany‎

**Comment by maynak00** [comment]
temporary solution: 
>sport1.de##.lp_mwi_dialog-overlay--is-active.lp_mwi_dialog-overlay

**Comment by himself85** [comment]
It doesn't help in my Chrome's uBlock.
What is wrong?

**Comment by reek** [comment]
@himself85 
Ok, I'll kill it

**Comment by bunducafe** [comment]
@maynak00 : Where would you put that temporary solution in? I looked at the uBlock options but cannot find any field where I could paste that in.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by bunducafe** [comment]
Hi reek!

It seems, that sport1.de has changed the code, because the script is not blocking the site anymore. Could you reopen the topic or just have a look into that in order to kill it again?

Your help would very much appreciated.

Thanks.

**Comment by SMed79** [comment]
@bunducafe check https://forums.lanik.us/viewtopic.php?p=95103&hilit=sport1.de#p95094

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
