### ISSUE TITLE
nu.nl

### ISSUE THREAD

**Issue by laslingerland** [reek/anti-adblock-killer#1076]
http://www.nu.nl/
http://s21.postimg.org/sx2h2dg3b/nu_nl_adblock_detected.png
Google Chrome 48.0.2564.116 m
Tampermonkey 9.2
AdBlock
AakList

**Comment by maynak00** [comment]
**try with:**(custom filter)
>@@||nu.nl/static/js/advertising.js$script

**Comment by laslingerland** [comment]
I tried, but it makes no difference. I've added your custom filter to AdBlock > Customize > Manually edit your filters. Both at the top as at the bottom. There are more filters for nu.nl, but I've also tried it by removing all the other filters. So it also doesn't work if your custom filter is the only filter in my options.

**Comment by reek** [comment]
@laslingerland 
maynak00 rule seems to be good

**Comment by reek** [comment]
@laslingerland 
See: https://github.com/reek/anti-adblock-killer#help

**Comment by patricksevat** [comment]
I think this has to do with the video content supplier Kijk.nl, so it's not from Nu.nl.
In the link below you'll see the exact same anti-adblock message

For example [this video](http://embed.kijk.nl/video/7MmCFpxbpmrC?autoplay=1&consent=true) is embedded on [this Nu.nl Champions League video](http://www.nu.nl/13283/video/bayern-munchen-juventus-4-2.html) (you'll have to click on a video).

If you open console, you'll see two objects outputted one of which contains "adblocker: true" variable.

Clicking on the source of that message you can find
`if (gotAdBlocker) {
                ga('send', 'event', 'adblocker', 'blocked', 'yes', 0, {'nonInteraction': 1});
            }`
in the source code.

Hope this helps.

PS: I've also checked for Ghostery interference with no luck

**Comment by reek** [comment]
@patricksevat 
even if I add kijk.nl to whitelist, I am anti-adblock message. I have no solution yet

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
