### ISSUE TITLE
debridnet.com

### ISSUE THREAD

**Issue by monsieurbourbaki** [reek/anti-adblock-killer#1077]
Hi,

As per Issue #836 I have added @@||tags.h12-media.com/load.js$script,domain=debridnet.com
to no avail.

Chrome Version 50.0.2638.0 canary (64-bit)
Taper Monkey 3.12.58 
AdBlockPlus
Filter List - AakList (Anti-Adblock Killer)‎, EasyList, AdBlock Warning Removal

Thanks in advance,
b

**Comment by monsieurbourbaki** [comment]
Apologies.

Turns out another chrome extension was at fault.

**Comment by reek** [comment]
This isn't an error on your part, they changed the file, this is the filter for the block.
<code>||debridnet.com/b2.js$script</code>

**Comment by monsieurbourbaki** [comment]
thanks so much,
b

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by xhamid** [comment]
it's not work

**Comment by reek** [comment]
@xhamid 
they constantly change their anti-adblock

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by xhamid** [comment]
it's not work

**Comment by reek** [comment]
@xhamid 
I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
