### ISSUE TITLE
ruleporn.com

### ISSUE THREAD

**Issue by liracobopu** [reek/anti-adblock-killer#1079]
ruleporn.com
http://imgur.com/uQZfGma
Google Chrome
uBlock Origin 1.6.2
uBlock Filters + EasyList + EasyPrivacy + Prebake + Adblock Warning Removal List + AAKList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by maynak00** [comment]
**try with:**(custom filter)
>ruleporn.com#@##adsense

**Comment by liracobopu** [comment]
That works! Thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
