### ISSUE TITLE
pencurimovie.cc

### ISSUE THREAD

**Issue by izzuddinfz** [reek/anti-adblock-killer#108]
anti adblock still working on this site.
![screenshot from 2014-12-07 14 39 47](https://cloud.githubusercontent.com/assets/7141230/5330257/ed258864-7e1e-11e4-99f9-5b84759437b7.png)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Anti-AdBlock Killer has been updated ! Changelog

Step 1: Update : Anti-AdBlock Killer - Userscript
Step 2: Update : Anti-AdBlock Killer - Filters for Adblockers

Do not forget to donate, review, share, follow and add to favorites.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
