### ISSUE TITLE
darkstars.org

### ISSUE THREAD

**Issue by D4RKS0ULST3ALER** [reek/anti-adblock-killer#1080]
**Hi**

I have an issue with _darkstars.org_
![help](https://cloud.githubusercontent.com/assets/17470544/13314957/3595eb06-dba8-11e5-9a5b-b59e7338e709.PNG)
Mozilla firefox, Greasemonkey, Adblock+ as you can see, and Anti adblock reek is enabled.
(If you can too, make me an uridium hack, thx very much)
THX

**Comment by reek** [comment]
Hi
Ok, I'll kill it

**Comment by D4RKS0ULST3ALER** [comment]
Just tell me when you finish

**Comment by reek** [comment]
Of course :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by D4RKS0ULST3ALER** [comment]
Thx
