### ISSUE TITLE
tracker-free.com

### ISSUE THREAD

**Issue by mohabhassan** [reek/anti-adblock-killer#1082]
https://tracker-free.com/dashboard/
http://i.imgur.com/NkLN3py.png
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList + Adblock Warning Removal List(https://easylist-downloads.adblockplus.org/antiadblockfilters.txt)

**Comment by reek** [comment]
I need your username / password.
send me here http://reek.github.io/anti-adblock-killer/#contact

**Comment by mohabhassan** [comment]
There is a register button on the top right of the site.
That's obvious :3.

**Comment by reek** [comment]
I know but I have to install the app while I do not want.
Otherwise I can not help you, you can always change the password.

**Comment by mohabhassan** [comment]
Ok sorry for the extremly late reply, I could create you a dummy account but I think u would search for this:
```html
<!-- No Pub -->
<div id="responsiveNoPub" data-backdrop="static" data-keyboard="false" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				<center><u><h1 style="color:red;">Warning! </h1></u><br/>
				<h3>Thank you disable your ad blocker or subscribe to a premium offer!</h3><br/>
				<a href="premium.php" type="button" class="btn btn-primary btn-lg">
				View offers!</a>
			</div>
			</div>
		</div>
	</div>
</div>
<!-- No Pub -->
```
```javascript
<script` type="text/rocketscript">
		$(document).ready ( function() { 
			setTimeout(
			  function() 
			  {
				if ($('.myAds').css('display') == "none") {
					$.ajax({
						type: "POST",
						url: "scripts/isPremium.php",
						success: function(msg) {
							if(msg != "ok") {
								$('#responsiveNoPub').modal();
							}
						}
					});
				}

				else if (document.getElementsByTagName("iframe").item(0) == null)
				{
					console.log(document.getElementsByTagName("iframe"));
					$.ajax({
						type: "POST",
						url: "scripts/isPremium.php",
						success: function(msg) {
							if(msg != "ok") {
								$('#responsiveNoPub').modal();
							}
						}
					});
				}
			  }, 3000);

		})
	</script>
```
If u still need one, I am here.

**Comment by reek** [comment]
Ok, try this rule
<code>mobile-tracker-free.com#@#.myAds</code> or <code>mobile-tracker-free.com##.modal</code>

**Comment by reek** [comment]
send me the account with this form, so I can test
https://reek.github.io/anti-adblock-killer/#contact

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
