### ISSUE TITLE
Ublock origin link at http://reeksite.com/anti-adblock-killer/#filterlist is incorrect 

### ISSUE THREAD

**Issue by Foiled56** [reek/anti-adblock-killer#1084]
The link to uBlock Origin at http://reeksite.com/anti-adblock-killer/#filterlist is incorrect. It links to uBlock rather than uBlock Origin. uBlock origin is a newer fork of uBlock.

**Comment by reek** [comment]
Hi,
I know, I'll fix it soon

Thanks

**Comment by gorhill** [comment]
I consider `ublock.org` to be a scam site -- i.e. seeking financial gains using misrepresentation. The sooner this is fixed the better.

**Comment by reek** [comment]
Done, sorry for the mistake.
