### ISSUE TITLE
link.tl

### ISSUE THREAD

**Issue by muhasturk** [reek/anti-adblock-killer#1087]
http://link.tl/pHIz
Google Chrome Stable
uBlock Origin
Tampermonkey

because of following page
http://link.tl/adblock.php

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
