### ISSUE TITLE
Linkbucks ( Zatnawqy.net )

### ISSUE THREAD

**Issue by ihateads77** [reek/anti-adblock-killer#1091]
http://www.zatnawqy.net/Cq3Fm
http://i.imgur.com/HBFaWq5.png
FF 44.0.2
Ublock Origin with default lists

tl;dr it'll just countdown and stay on 0

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
