### ISSUE TITLE
On sites where I have adblock disabled, it shows a popup telling me to re-subscribe to the filterlist

### ISSUE THREAD

**Issue by lahwran** [reek/anti-adblock-killer#1092]
and then when I click "disable this message", it takes me to a page on the github site where it says "anti-adblock not installed", which it definitely is, considering that I just got there from a button it injected into a page. wat?

**Comment by reek** [comment]
Hi,

This is normal, since by disabling adblock you disable AakList.
Going [here](http://reek.github.io/anti-adblock-killer/#settings) and uncheck the option <code>Check AakList subscription</code> and save.

**Comment by lahwran** [comment]
I do not see that option there. I see "Anti-Adblock Killer is not installed or active, see instructions.".

**Comment by reek** [comment]
Your configuration please.
<pre>Your browser
Your script manager
Your adblocker
Your filterlists</pre>

**Comment by lahwran** [comment]
- Chrome (Version 48.0.2564.82 (64-bit), mac)
- I don't know what you mean by script manager, unless you're asking whether I'm using an extension to manage userscripts, which I'm not, I just have it loaded directly by chrome
- https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom
- [no acceptable ads](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt), [easylist](https://easylist-downloads.adblockplus.org/easylist.txt), [adblock warning removal list](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt), [fanboy's annoyances](https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt), [aaklist](https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt)

these are my custom filters:

```
@@|https://trydesignlab.com/web-design-course/enroll/|$document
github.com##DIV[class="new-user-avatar-cta"]
www.facebook.com##DIV[id="appsNav"][class="homeSideNav"]
www.amazon.com##DIV[id="gw-desktop-herotator"][class="a-section a-spacing-none gw-desktop-herotator-ready"]
www.nexusmods.com##A[href="http://www.nexusmods.com/starbound/users/supporter/"]
stackoverflow.com##A[href="http://careers.stackoverflow.com"]
www.labnol.org##IMG[class="aligncenter"]
www.quora.com##DIV[id*="modal_signup_wrapper"]
agar.io##IMG[id="blocker"]
www.rescuetime.com##DIV[id="footer"]
www.amazon.com##DIV[class="a-section feed-carousel-viewport"]
www.amazon.com##DIV[class="billboardRowWrapper"]
www.amazon.com##DIV[class="a-section as-title-block"]
www.amazon.com##DIV[class="sidekick"]
www.amazon.com##DIV[class="bestsellers"]
www.amazon.com##DIV[id="rhf"][class="copilot-secure-display"]
www.amazon.com##DIV[class="huc-upsell-big-face-box-inner"]
www.reddit.com##SPAN[class="next-suggestions"]
www.theatlantic.com##DIV[class="blocker-message"]
sitenable.com##DIV[id="abpnote"]
www.facebook.com##DIV[id="pagelet_trending_tags_and_topics"][class="pagelet"]
play.google.com##DIV[class="explicit"]
@@||mnky.es/$document
medicalxpress.com##SECTION[class="notice"]
us-mg5.mail.yahoo.com##SPAN[class="newsbadge newsfeed-msg-badge"]
www.facebook.com##UL[class="fbChatOrderedList clearfix"]
imgur.com##DIV[class="captions best-captions"]
imgur.com##DIV[class="new-panel"]
imgur.com##DIV[id="comments-container"][class="comments-initialized"]
imgur.com##DIV[class="next-prev"]
imgur.com##DIV[id="top-comments"][class="left-column"]
www.readability.com##SECTION[class="who-to-follow "]
www.readability.com##UL[class="recommendation-list"]
```

other extensions I have that mess with most pages I'm on, without explicit user request to do so:
- ghostery

**Comment by reek** [comment]
You must install Tampermonkey and remove ghostery.
See instructions: https://github.com/reek/anti-adblock-killer#instruction

**Comment by reek** [comment]
and delete the user script installed natively

**Comment by lahwran** [comment]
uh, wtf? why no ghostery?

**Comment by reek** [comment]
For Ghostery can prevent the proper functioning of Adblock.and AntiAdbKiller

Next time read before disturb me for anything.
