### ISSUE TITLE
abovetopsecret.com

### ISSUE THREAD

**Issue by bmxrider0779** [reek/anti-adblock-killer#1093]
http://www.abovetopsecret.com/index.php
http://imgur.com/wfYEWkv
Mozilla Firefox
Greasemonkey
Adblock Plus
Easylist + AakList

``` javascript
function detect() {
  var iframe = document.createElement("iframe");
  iframe.height = "1px";
  iframe.width = "1px";
  iframe.id = "ads-text-iframe";
  iframe.src = "http://www.abovetopsecret.com/ads.html";
  document.body.appendChild(iframe);
  setTimeout(function () {
    var iframe = document.getElementById("ads-text-iframe");
    if (iframe.style.display == "none" || iframe.style.display == "hidden" || iframe.style.visibility == "hidden" || iframe.offsetHeight == 0) {
      //alert("Adblock is blocking ads on this page");
      $('nav').addClass('hide');
      $('#admsg').removeClass('hide');
      $('#admsg').addClass('show');
      var anchors = document.getElementsByTagName("a");
      for (var i = 0; i < anchors.length; i++) {
        anchors[i].onclick = function () {
          return (false);
        };
      }
      iframe.remove();
    } else {

      iframe.remove();
    }
  }, 100);
}

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
