### ISSUE TITLE
new.naturalbd.com

### ISSUE THREAD

**Issue by Fazlul7** [reek/anti-adblock-killer#1095]
http://new.naturalbd.com/
http://i67.tinypic.com/2h3mtu1.jpg
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
