### ISSUE TITLE
seoghoer.dk

### ISSUE THREAD

**Issue by klausenbusk** [reek/anti-adblock-killer#1096]
http://www.seoghoer.dk/wild/tiaarige-kiera-ofrede-sit-liv-redde-legekammerater
Mozilla Firefox
uBlock Origin
EasyList + some others

Blocking http://allercdn.net/randomurl.js seems to fix it.
![screen shot 2016-03-01 at 23 13 32](https://cloud.githubusercontent.com/assets/1080056/13443836/3d967424-e003-11e5-83ec-3d651bb6362b.png)

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
