### ISSUE TITLE
8muses.com

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#1099]
https://github.com/gorhill/uBlock/issues/1440#issue-137983676

Tested myself with same result:
https://www.8muses.com/album/8muses-comics
![](https://cloud.githubusercontent.com/assets/16030872/13475674/875e5e0c-e0c4-11e5-9e25-629c70c9a2ca.png)
Chrome 48
Tampermonkey 3.12.58
uBlock Origin 1.6.2
Default filter lists + AakList

``` javascript

// detect
(function(){
  var test = document.createElement('div');
  test.innerHTML = '&nbsp;';
  test.className = 'adsbox';
  document.body.appendChild(test);
  window.setTimeout(function() {
    if (test.offsetHeight === 0) {
       $(window).trigger('adblock');
    }
    test.remove();
  }, 100);
})();

// when detected
$(window).on('adblock', function () {
	var array = [ 'attached cage', 'avatar cage', 'banana cage', 'cage smash', 'cage snow', 'cage the white', 'cat cage', 'et cage', 'evil cage', 'full cage', 'knocking cage', 'merciful cage', 'nicolas oz', 'rebel cage', 'ribcage', 'smart cage', 'space cage', 'swan cage', 'trump cage', 'yoda cage' ];	
	$('.ad').each(function (i, e) {
		var variable = Math.floor(Math.random() * 10) + 1;
		$(e).html("<a href='http://removeadblock.com/www.8muses.com'><img src='" + "//www.8muses.com/data/web/img/cage/thumbnail/" + array[ variable ] + ".jpg" + "'/><span class='title' style='color: white; font: 16px/24px Open Sans, sans-serif;font-weight: 700;'>" + array[ variable ] + "</span></a>");
	});
});

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
