### ISSUE TITLE
canalplus.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#110]
Bonjour Reek,

Site: http://www.canalplus.fr/c-divertissement/c-le-petit-journal/pid6811-eric-et-quentin.html

to block ads i have add 
@@||bobodise.com^*^adv_partner^$object-subrequest
@@||schneevonmorgen.com^*^adv_partner^$object-subrequest
canalplus.fr#@##AdArea

The problem is that an element hiding whitelist like #@##AdArea will not properly work in Firefox we need to disable the rule. 

Other than that they will continue changing that elment and the "detection" from schneevonmorgen.com and bobodise.com (always switch to other generic filters that block those requests). 

liste fr forum http://forums.lanik.us/viewtopic.php?f=91&t=19828&p=64140#p64044

elment and the detection found on http://tinyurl.com/l8ls8yf represented "testhide".

any way to skip this this detection using Greasemonkey + Anti-Adblock Killer script ?

Screenshot: 
- http://www.imabox.fr/a4/140812036dVVVpB21.png
- http://www.imabox.fr/a4/1408120363QTWv032.png

Mozila Firefox 34.0.5
Adblock Plus 2.6.6
Greasemonkey 2.3
Adblock Plus 7.6
Filters: EasyList + Liste FR + Liste AR + Anti-Adblock Killer

Thank you.
SMed79

**Comment by MajkiIT** [comment]
@SMed79 

Can you check now? I don't any notification.
