### ISSUE TITLE
upvast.com

### ISSUE THREAD

**Issue by DarKWinGTM** [reek/anti-adblock-killer#1102]
Link : http://upvast.com/arkm0498cca9
Screen : http://i.imgur.com/yEUNJxv.jpg
Browser : Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0 ID:20160123151951 CSet: 9b79adf82b132f5e1fcfee4813a47b5b38bd7521
Extensions : Greasemonkey , Ublock
Userscript : AntiAdblock_Killer v9.3
Filter : -

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by DarKWinGTM** [comment]
Updated informasions you need

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by DarKWinGTM** [comment]
Changed info

Userscript : AntiAdblock_Killer v9.3
Filter : -

**Comment by DarKWinGTM** [comment]
When support for this site ?

**Comment by reek** [comment]
add this rule
<code>@@||upvast.com/pop.js$script</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
