### ISSUE TITLE
theguardian.com

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#1107]
http://www.theguardian.com/uk-news
http://i.imgur.com/Pt1va8d.png
Firefox 42
Greasemonkey
ublock origin
AAK Script + List

There's an orange donation block at the top and a pink bar at the bottom that appears only for adblock users.

**Comment by Giwayume** [comment]
`theguardian.com##.js-adblock-sticky,.site-message--adblock-message`

**Comment by reek** [comment]
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
