### ISSUE TITLE
dlh.net

### ISSUE THREAD

**Issue by nikisby** [reek/anti-adblock-killer#1108]
1. Links: http://www.dlh.net/ and http://www.dlh.net/en/steam-keys.html
2. Screenshots: [before](http://i.imgur.com/PuheJsF.png) and [after](http://i.imgur.com/x8ZExQQ.png)
3. Browser: Chrome
4. Script manager: Tampermonkey
5. Adblocker: uBlock Origin
6. Filterlists: EasyList + RU AdList + Peter Lowe’s + uBlock filters‎ + AakList

Solution:
`@@||dlh.net/ads.html$subdocument,domain=www.dlh.net`

Thanks for a great script.

**Comment by reek** [comment]
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
