### ISSUE TITLE
3dsthem.es

### ISSUE THREAD

**Issue by Favna** [reek/anti-adblock-killer#1109]
1. URL to website: https://3dsthem.es/
2. [Screenshot with adblocker](http://i.imgur.com/7Qawca5.png) // [Screenshot without adblocker](http://i.imgur.com/xQlqvEn.jpg)
3. Browser: Chrome
4. Script Manager: Tampermonkey
5. Adblocker: Adblock Plus
6. Filter lists:
 - Adblock Warning Removal List
 - Malware Domains 
 - Fanboy's Social Blocking List 
 - EasyPrivacy 
 - EasyList Dutch+EasyList 
 - AakList (Anti-Adblock Killer) 

Personal filters:

```
@@||core.adprotected.com^$domain=kissanime.com

@@||kissanime.com/ads/*$subdocument

@@||kissanime.com/ads/adprotect300.aspx

dubbedanimehd.org###spots

facebook.com###GroupsRHCSuggestionSection

||kissanime.com/Scripts/jquery.allofthelights-min.js

||kissanime.com/ads/*

||n4g.com/general/IndieMonthSideBarWidget?one=True&hideuntilday1=true

||st.chatango.com/h5/gz/r1105151218/id.html

||st.chatango.com/h5/gz/r1119151706/id.html

||www4.yourshoutbox.com/shoutbox/sb.php?key=472650890
```

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by MrSherlockHolmes** [comment]
Hmm.. I'll see what I can do.

**Comment by MrSherlockHolmes** [comment]
How about:
`3dsthem.es##div[style*="width: 728px"]`

**Comment by Favna** [comment]
That partially did it @MrSherlockHolmes . Now only this shows up

![2016-03-06_14-36-06](https://cloud.githubusercontent.com/assets/4019718/13554470/cd2fc646-e3a8-11e5-8d4a-b609b9650909.jpg)

Which I have blocked with `3dsthem.es##div[style="text-align:center;"]`

**Comment by reek** [comment]
@MrSherlockHolmes 
This is not a good rule, let me do it.

**Comment by ErmanSayin** [comment]
;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
