### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by markrhenz** [reek/anti-adblock-killer#1110]
https://kissanime.to/Anime/Boku-dake-ga-Inai-Machi/Episode-009?id=123360
http://i.imgur.com/cc7jHTs.png
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,
It's killed for me with AakScript
See: https://github.com/reek/anti-adblock-killer#help

**Comment by Giwayume** [comment]
I've had this problem before. For some reason I needed to re-install AAK and it worked fine.
