### ISSUE TITLE
thomas-n-ruth.com

### ISSUE THREAD

**Issue by MrSherlockHolmes** [reek/anti-adblock-killer#1111]
1. Link: http://www.thomas-n-ruth.com/adblock-user-block.html
2. Screenshot: [with adblock](http://i.imgur.com/fQ97QpZ.png)
3. Browser: Mozilla Firefox
4. Script Manager: Greasemonkey
5. Adblocker: Adblock Plus
6. Filter Lists: Adblock Warning Removal List, EasyList, Malware Domains, AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by MrSherlockHolmes** [comment]
Thanks.
Please tell me when you're done ;)

**Comment by reek** [comment]
of course

**Comment by MrSherlockHolmes** [comment]
I think this works:
`document.getElementById("download").innerHTML = "<a title=\"Block Adblock Users ZIP download link\" href=\"file-manager/download.php?id=71\" target=\"_blank\">Block Adblock Users ZIP</a>";`
Perhaps you could find a way to make that a bit more filter-y.

**Comment by reek** [comment]
I have already found a solution

**Comment by MrSherlockHolmes** [comment]
Cool :package:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
