### ISSUE TITLE
Computerworld.com.au

### ISSUE THREAD

**Issue by Lazza** [reek/anti-adblock-killer#1113]
This website, both with AAK in uBlock Origin + Greasyfork and without that, redirects the user.

Article URL:

    http://www.computerworld.com.au/article/595113/how-microsoft-learned-stop-worrying-love-open-source/

Redirecting to:

    http://www.computerworld.com.au/adblock/?dest=/article/595113/how-microsoft-learned-stop-worrying-love-open-source/&check_ad_block=true

The check is done by scripts whose URL contains `idg_gpt`. These include:

    # in the first URL
    http://cdn.computerworld.com.au/compressor-staticfiles/adsmin/idg_gpt_pipeline_generated.js?release=2016030416
    # in the second one
    http://cdn.computerworld.com.au/compressor-staticfiles/adsmin/idg_gpt.js?release=20160304162701

I decided to add the following filter to my ad blockers and it works:

    ||cdn.computerworld.com.au/*idg_gpt*.js$script,important

**Comment by reek** [comment]
Hi,
Ok, thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
