### ISSUE TITLE
lol.moa.tw

### ISSUE THREAD

**Issue by TonyRL** [reek/anti-adblock-killer#1114]
English
http://lol.moa.tw/summoner/show/ko?lang=en_US

1. all search result, eg: http://lol.moa.tw/summoner/show/ahq_GreenTea
2. Screenshot with Adblock on: http://i.imgur.com/8Ufpnk6.png
2.1 Adblock off: http://i.imgur.com/Ox3L4dO.png
3. Firefox 44.0.2
4. Greasemonkey
5. Adblock Plus
6. filterlists: Adblock Warning Removal List, EasyList China+EasyList, AakList (Anti-Adblock Killer), Prebake - Filter Obtrusive Cookie Notices

Possible js that detect adblock: http://lol.moa.tw/Javascript/bs_index/?zh_TW
MoaObj.ad.*

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by aledefreitas** [comment]
### Possible solution
Just patch this function:

```javascript
MoaObj.ad.hasAdblock=function(){var ad=$('ins.adsbygoogle:first')[0];return(ad&&ad.innerHTML.replace(/\s/g,'').length==0);}
```

with 

```javascript
MoaObj.ad.hasAdblock = function() {
    return false;
}
```

**Comment by reek** [comment]
@aledefreitas 
thank you, but I have already found a solution

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by TonyRL** [comment]
Thank for your time updating aak list.
But the ads is blocked but the site knows i blocked their ads and it is not going to function well
(what is strange is that, AAK does working sometimes[10%])

i have tried disable other lists and only switched on EasyList China+EasyList and AakList with Greasemonkey(Anti-Adblock Killer | Reek 9.4 only 1 script), the problem still exists

http://lol.moa.tw/summoner/show/ko?lang=en_US#
2. Screenshot: http://i.imgur.com/klXsjOD.png
3. Firefox 45.0.1
4. Greasemonkey
5. Adblock Plus
6. filterlists: Adblock Warning Removal List, EasyList China+EasyList, AakList (Anti-Adblock Killer), Prebake - Filter Obtrusive Cookie Notices

hope you can look into it ;)

**Comment by reek** [comment]
I'll see if I find another solution

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by TonyRL** [comment]
thanks for the update and yes it works :+1:

**Comment by anelafar** [comment]
hey dude why in sites :
http://www.elmoslsal.com/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D9%86%D9%8A%D9%86-2/

http://codeclan.altervista.org/

http://antiblock.org/?p=v3&demo

PLEASE FIX ANNOYING

Please enable / Bitte aktiviere JavaScript!
Veuillez activer / Por favor activa el Javascript![ ? ]
==============================================

Si prega di attivare i Javascript! / Please turn on Javascript!
Javaskripta ko calu karem! / Bitte schalten Sie Javascript!
S'il vous plaît activer Javascript! / Por favor, active Javascript!
Qing dakai JavaScript! / Qing dakai JavaScript!
Пожалуйста включите JavaScript! / Silakan aktifkan Javascript!

**Comment by reek** [comment]
@anelafar 
http://enable-javascript.com/

do you use NoScript ?

**Comment by bourne9** [comment]
@anelafar 
He can't fix an issue which is underlying your browser. Check if java script is enabled and if any extension is messing with or not.
