### ISSUE TITLE
atdhe domains (jupako.uk)

### ISSUE THREAD

**Issue by rum0r** [reek/anti-adblock-killer#1116]
http://atdhe.ru/ - click on any stream whatsoever.
http://imgur.com/ekWYg1s
Chrome
Tampermonkey
 uBlock filters
 uBlock filters – Badware risks‎  (github.com)
 uBlock filters – Experimental‎  (github.com)
 uBlock filters – Privacy
 uBlock filters – Unbreak‎
Ads (5)
 Adblock Warning Removal List‎ (forums.lanik.us)
 Anti-Adblock Killer | Reek‎  (github.com)
 EasyList‎ (forums.lanik.us)
 EasyList without element hiding rules‎ (forums.lanik.us)
 Peter Lowe’s Ad server list‎ (pgl.yoyo.org)
Privacy (2)
 Basic tracking list by Disconnect‎
 EasyPrivacy‎ (forums.lanik.us)
 Fanboy’s Enhanced Tracking List‎ (forums.lanik.us)
Malware domains (3)
 Malvertising filter list by Disconnect‎
 Malware Domain List‎ (malwaredomainlist.com)
 Malware domains‎ (www.malwaredomains.com)
Custom (1)
 AakList (Anti-Adblock Killer)‎

http://imgur.com/ekWYg1s

**Comment by reek** [comment]
which channel ?

**Comment by rum0r** [comment]
@reek As in what channel on that website? if so, I believe it happens on all of them. Otherwise, I'm sorry what kind of channel do you mean?

Thanks!

**Comment by F4z** [comment]
http://atdhe.so/soccer/watch-hull-city-vs-arsenal-8ajfk
http://atdhe.so/soccer/watch-zapresic-vs-hajduk-split-8ajeh
http://atdhe.so/soccer/watch-al-hadd-vs-altyn-asyr-8ajeg
http://atdhe.so/soccer/watch-real-madrid-vs-roma-8ajgk

Try this:
`@@||jupako.uk/ads.php$subdocument`

To hide ads from player:
`jupako.uk###over-small`
`jupako.uk###over-large`

To block popups when you click on links [here](http://atdhe.so/soccer):
`||atdhe.*/new/pu.js$script`

**Comment by reek** [comment]
@F4z 
Thanks for rules.

**Comment by rum0r** [comment]
@F4z thanks! seems to work so far, though I'm seeing different pages currently than I'm used to. I'll update if I have any more issues.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rum0r** [comment]
This workaround unfortunately doesn't stop them, they have found a way around it.

**Comment by reek** [comment]
@rum0r 
I'll try to fix

**Comment by rum0r** [comment]
@reek thanks for all your hard work!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
