### ISSUE TITLE
bakersfield.com

### ISSUE THREAD

**Issue by liracobopu** [reek/anti-adblock-killer#1117]
#657
bakersfield.com
http://imgur.com/XjKb5Uz
Google Chrome
uBlock Origin 1.6.2
uBlock Filters + EasyList + Prebake + Adblock Warning Removal List + AAKList

Solution:
@@||googletagservices.com/tag/js/gpt.js$script,domain=bakersfield.com

**Comment by MrSherlockHolmes** [comment]
Sounds good. I'm guessing @reek is currrently occupied.

**Comment by reek** [comment]
@liracobopu 
I see nothing.

**Comment by MrSherlockHolmes** [comment]
Same, now.

**Comment by liracobopu** [comment]
I purged the cache and updated all filters. The anti-adblock popup still only disappears for me if I add this filter: `@@||googletagservices.com/tag/js/gpt.js$script,domain=bakersfield.com`

**Comment by reek** [comment]
@liracobopu 
Ok, I'll add it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
