### ISSUE TITLE
mrkindy.com

### ISSUE THREAD

**Issue by MrSherlockHolmes** [reek/anti-adblock-killer#1118]
```
Website: https://mrkindy.com/ad-block-detect-nasty-ad-blockers/
Screenshot: http://i.imgur.com/44ZLss3.png/
Browser: Mozilla Firefox
Script Manager: Greasemonkey
AdBlock: Adblock Plus
Filterlists: Malware Domains, AakList, EasyList, Adblock Warning Removal List
```

Try: `##div[class*="kill-adblock-container"]`

Thanks.

**Comment by reek** [comment]
Hi,
Ok, thanks.

**Comment by mrkindy** [comment]
Hi,
Can I Help You :) ?

**Comment by mrkindy** [comment]
Hi,
Can I Help You :) ?

**Comment by mrkindy** [comment]
Hi,
Can I Help You :) ?

**Comment by mrkindy** [comment]
Hi,
Can I Help You :) ?

**Comment by reek** [comment]
@mrkindy 
Yes :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
