### ISSUE TITLE
cccam-server.info + call-share.ddns.net

### ISSUE THREAD

**Issue by JSPAS** [reek/anti-adblock-killer#112]
http://imgur.com/1QJa6MK
used
https://getadblock.com/
 chrome
tampermonkey.net/

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
