### ISSUE TITLE
olympiakos-live.gr

### ISSUE THREAD

**Issue by entproject** [reek/anti-adblock-killer#1120]
http://olympiakos-live.gr/streaming/Olympiakos-Kavala

https://www.dropbox.com/s/ysvskz6t8tkm5tu/adblock2.bmp?dl=0

Google Chrome 

Tampermonkey

Ublock Origin

All default ublock lists( aaklist+easylist+...)

**Comment by MrSherlockHolmes** [comment]
```
olympiakos-live.gr##p[style^="background:rgba(0,0,0,0.9);"]
```
removes the writing.
```
olympiakos-live.gr##div#blo
```
works for a second, and then gets hidden. Hmm...
Also,it seems to be a gif! :P

**Comment by entproject** [comment]
if i disable cosmetic filtering i don't the disable adblock message

**Comment by MrSherlockHolmes** [comment]
Could I have a screenshot of that - I don't really understand.

**Comment by entproject** [comment]
https://www.dropbox.com/s/ydajpcslxl1fx93/adblock3.bmp?dl=0

screenshot with cosmetic filtering disabled (from ublock options)

**Comment by MrSherlockHolmes** [comment]
Ooh - however, you are still blocking with uBlock & tampermonkey seems on. If you turn them off, see if there is no message.

**Comment by entproject** [comment]
What message do you mean?

This is a ss with everything off
https://www.dropbox.com/s/404zt9lkg0598dj/adbl4.bmp?dl=0

**Comment by MrSherlockHolmes** [comment]
I mean, there isn't anything saying you have adblock on when you disable everything, right?

**Comment by entproject** [comment]
yes that's right.

**Comment by MrSherlockHolmes** [comment]
so, with my protection ideas, what are the problems [ie, everything enabled.]

**Comment by entproject** [comment]
everything enabled (including cosmetic filtering)

with the first filter
`olympiakos-live.gr##p[style^="background:rgba(0,0,0,0.9);"]`

I get this adblock message (this is different from the first one, from my first post)
https://www.dropbox.com/s/a3wokyvn7zobh5g/Screenshot%202016-03-07%2000.20.29.png?dl=0


the second filter
`olympiakos-live.gr##div#blo`
hides the video stream window totally (i get only audio)

**Comment by F4z** [comment]
Try this:
`olympiakos-live.gr#@#.afs_ads`

Additionally:
`olympiakos-live.gr###p2`
`olympiakos-live.gr###pp`
`olympiakos-live.gr###pp2`
`olympiakos-live.gr###h2`

**Comment by entproject** [comment]
These worked great
thanks!

**Comment by MrSherlockHolmes** [comment]
Yey! Thanks @F4z! I'm going to properly learn how to filter things, now :P

**Comment by entproject** [comment]
@MrSherlockHolmes 

I think you are kidding :) thanks for all your efforts +1:

**Comment by reek** [comment]
@F4z 
Well done !

@entproject 
Ok, I'll kill it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
