### ISSUE TITLE
coolsoft.altervista.org

### ISSUE THREAD

**Issue by katsusand** [reek/anti-adblock-killer#1124]
http://coolsoft.altervista.org/en
Google Chrome
Tampermonkey
Ublock Origin

All default ublock lists( aaklist+easylist+...)+ABP-Japanefe filter

**Comment by maynak00** [comment]
screenshot ?
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by katsusand** [comment]
OKOK screenshot.
http://imgur.com/hT3Hsu9

...and anti-noscript.
</div>
  </div>

</div>
<div id="block-block-10" class="block block-block last even">

      
  <div class="content">
    <div id="jsWarn">
	<div class="warnImg"><img alt="warning" src="/images/disable_noscript_eng.png" /></div>
	<div class="warnText">
		<h2>Warning, JavaScript is disabled!</h2>
		<p>JavaScript is not available, maybe because you disabled it globally into your browser settings or you are using an addon like <a href="https://addons.mozilla.org/it/firefox/addon/noscript/" target="_blank">NoScript</a>.</p>
		<p><strong>We do not have any dangerous JavaScript running here.</strong><br />
			Please enable JavaScript; if you&#39;re using NoScript this image will help you adding CoolSoft to your whitelist.</p>
		<p>Thanks for your comprehension and enjoy CoolSoft.</p>

**Comment by reek** [comment]
@katsusand 
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SephirothWS** [comment]
@reek Using uBlock Origin & Anti Adblock Killer this issue has resurfaced.
