### ISSUE TITLE
pcworld.co.nz

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1126]
Hi, 
`||pcworld.co.nz/*pipeline$script`
on `http://www.pcworld.co.nz/article/590690/yes-can-overclock-cheap-intel-skylake-chips/`
redirect to `/adblock/?dest=` 
sc: http://i.imgur.com/XafzicJ.png

Thanks

**Comment by reek** [comment]
thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
