### ISSUE TITLE
mangas.zlx.com.br

### ISSUE THREAD

**Issue by rafaelsetti** [reek/anti-adblock-killer#1127]
test : https://mangas.zlx.com.br/ler-saint-seiya-the-lost-canvas---meiou-shinwa-gaiden-online/capitulo-88/91965-quartel-canvete#/!page10
http://i.imgur.com/TUyCU9M.png (your Adblock is enabled )
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
try <code>@@||mangas.zlx.com.br^$elemhide</code>

**Comment by rafaelsetti** [comment]
how ?

**Comment by rafaelsetti** [comment]
how ?

**Comment by reek** [comment]
in adblock options <code>custom filters</code>

**Comment by rafaelsetti** [comment]
didn't work

**Comment by rafaelsetti** [comment]
...

**Comment by reek** [comment]
try these rules
<code>@@||mangas.zlx.com.br^$generichide</code>
<code>@@||mangas.zlx.com.br^$genericblock</code>
