### ISSUE TITLE
Automatic installation of Userscripts fails Greasemonkey

### ISSUE THREAD

**Issue by Hanshans0815** [reek/anti-adblock-killer#1128]
Automatic installation of Step 3: UserScript (https://github.com/reek/anti-adblock-killer#step-3-userscript) fails on Greasemonkey 3.7 / Firefox 44.0.2, because Greasemonkey seems not to recognize the URL as it own filetype (.user.js). The .js-File opens in playtext in a new browser tab. 
The installation of other scripts of different websites works when i just click on the link. 

Downloadling and reopening the .js-file works and can be installed. A refresh (F5) of the opened .js-plaintext-website forced to install the script, too.

Perhaps it might be a problem with the |-character in the URL...?
Anti-Adblock Killer | Reek.user.js
Or is the redirect of tinyurl.com a problem for Greasemonkey?

**Comment by reek** [comment]
Hi,

Indeed, it does not work the first time, I'll delete tinyurl links, thanks.

**Comment by reek** [comment]
Done !
