### ISSUE TITLE
Disabling ad blocking message

### ISSUE THREAD

**Issue by lukjan32** [reek/anti-adblock-killer#1129]
If you can turn off the video ads, tampermonkey Anti-Adblock Killer | Reek in order not to appear an error message blocking ads?

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by lukjan32** [comment]
I do not quite understand?

**Comment by reek** [comment]
the guide is nevertheless clear, what is your problem ?

**Comment by lukjan32** [comment]
I do not know how to do it? I'm green in these matters.

**Comment by reek** [comment]
begins by giving me the website address and your configuration

**Comment by lukjan32** [comment]
addresses on all pages with videos
