### ISSUE TITLE
girlstory.kr

### ISSUE THREAD

**Issue by Kaorw** [reek/anti-adblock-killer#1130]
http://girlstory.kr/girlstory15

cannot bypass adblock detector

**Comment by Kaorw** [comment]
http://girlstory.kr/girlstory15

http://imgur.com/a/ssgd6

Chrome

Adblock

Easylist
AdBlock Custom filters
fanboy-Korean
Adblock Warning Removal list (removes warnings about using ad blockers)
AakList (Anti-Adblock Killer)
malwaredomains
fanboy-annoyance

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
