### ISSUE TITLE
hdmovie14.net

### ISSUE THREAD

**Issue by jzielke-nli** [reek/anti-adblock-killer#1133]
http://hdmovie14.net/watch/supergirl-2015-season-1-putlocker-hd-full-movie#player_wraper
http://i.imgur.com/tfhNyyZ.png
Google Chrome
Greasemonkey
uBlock
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**(custom filter)
>185.63.252.176#@#div[id^="MarketGid"]

adblock message source: http://185.63.252.176/player/60d47c299010cb7543c91e02be3953a759ceac5b
Easylist ##div[id^="MarketGid"]

**Comment by reek** [comment]
@jzielke-nli 
Ok, I'll kill it, thanks.

@maynak00 
Thanks for rule :+1:

**Comment by jzielke-nli** [comment]
Already added? Because it's still there...

**Comment by MrSherlockHolmes** [comment]
You'll have to wait until it's closed, I think :package:

**Comment by reek** [comment]
@jzielke-nli 
it will only be closed when I have updated

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
