### ISSUE TITLE
ria.ru

### ISSUE THREAD

**Issue by wsmith1** [reek/anti-adblock-killer#1136]
http://ria.ru/trend/8March_celebration_04032016/

shows full screen message "ОБНАРУЖЕНО БЛОКИРОВАНИЕ РЕКЛАМЫ НА САЙТЕ"

https://imgur.com/KAoavVB

Vivaldi browser (Chromium)

uBlock Origin, cosmetic filters enabled

EasyList, Peter Lowe’s Ad server list‎ (pgl.yoyo.org), Adblock Warning Removal List,  Anti-Adblock Killer (Reek‎)

This element hiding rule seems to fix the issue:

```
ria.ru##.antiblock
```

**Comment by MrSherlockHolmes** [comment]
Again. Brilliant! :P

**Comment by reek** [comment]
@wsmith1 
Ok, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
