### ISSUE TITLE
wstream.video

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1137]
Hi, 
on `http://wstream.video/wk7a45m2u2pi` → http://i.imgur.com/XXnYPWN.png

`@@||ads.ad-center.com/smart_ad/display?$subdocument,domain=wstream.video`

Thanks!

**Comment by MrSherlockHolmes** [comment]
Great! :package: Well done! :P

**Comment by reek** [comment]
@SMed79 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
