### ISSUE TITLE
www.sweclockers.com

### ISSUE THREAD

**Issue by Delvar77** [reek/anti-adblock-killer#1138]
http://www.sweclockers.com/test/21839-snabbtest-grafikprestanda-i-tom-clancys-the-division
![capture](https://cloud.githubusercontent.com/assets/17744046/13635892/f69f3810-e5fe-11e5-9456-d874ab63e469.JPG)
Chrome
Tampermonkey
Adblock
Aaklist

**Comment by reek** [comment]
@Delvar77 
Ok, I'll kill it, thanks.

@MrSherlockHolmes 
Well done !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
