### ISSUE TITLE
net.hr

### ISSUE THREAD

**Issue by Malacinjo** [reek/anti-adblock-killer#1139]
http://net.hr/
http://imgur.com/mEESX3e
Chrome
Tampermonkey
AdBlock and AdBlock Plus
EasyList + AakList - default list subscribed on http://reek.github.io/anti-adblock-killer/
(https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt)

**Comment by reek** [comment]
HI,
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
**try with:**(custom filter)
>net.hr#@#.reklama

**Comment by Malacinjo** [comment]
No more ads :) Thank you very much!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
