### ISSUE TITLE
joyreactor.cc

### ISSUE THREAD

**Issue by kalmoth** [reek/anti-adblock-killer#1140]
http://joyreactor.cc/best
http://imgur.com/Mp6joxh
Mozilla Firefox
Greasemonkey
Adblock Plus
Easylist + RuAdList + AakList

**Comment by MrSherlockHolmes** [comment]
Try: `joyreactor.cc##div#sidebar`

**Comment by kalmoth** [comment]
Works! Thanks.

**Comment by MrSherlockHolmes** [comment]
You're welcome ;) @reek, could we add this?

**Comment by reek** [comment]
@MrSherlockHolmes 
Yes, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
