### ISSUE TITLE
serve.netsh.org

### ISSUE THREAD

**Issue by Neillll** [reek/anti-adblock-killer#1141]
https://serve.netsh.org/pub/ipv4-hosts/
https://serve.netsh.org/pub/ipv6-hosts/
Chrome
Adblock Plus
Adguard AdBlocker
uBlock Origin
EasyList+EasyList China+EasyPrivacy+AakList
![default](https://cloud.githubusercontent.com/assets/10258176/13696811/c10da258-e7a3-11e5-83bd-96c3ceb04657.png)

**Comment by MajkiIT** [comment]
try this rule
@@|https://serve.netsh.org/pub/*/ads.js$xmlhttprequest

**Comment by Neillll** [comment]
Not work

**Comment by maynak00** [comment]
**try with:**
>@@||serve.netsh.org/pub/*/ads.js$xmlhttprequest
serve.netsh.org#@#.adsbygoogle
@@||ads.google.com/adserver/adlogger_tracker.json$subdocument,domain=serve.netsh.org
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=serve.netsh.org
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$script,domain=serve.netsh.org

**optional:**
>serve.netsh.org###aswift_0
serve.netsh.org###aswift_0_anchor
serve.netsh.org###aswift_0_expand

**Comment by Neillll** [comment]
@maynak00 
Adblock Plus 
https://serve.netsh.org/pub/ipv4-hosts/
![1](https://cloud.githubusercontent.com/assets/10258176/13726360/d684fc74-e8fe-11e5-8f37-ddd245130747.png)

uBlock Origin
https://serve.netsh.org/pub/ipv6-hosts/
![2](https://cloud.githubusercontent.com/assets/10258176/13726362/eb9f078a-e8fe-11e5-84ef-de49f09d5b78.png)

**Comment by maynak00** [comment]
tested with uBlock Origin(enable/check in settings page:Hide placeholders of blocked elements):
https://serve.netsh.org/pub/ipv4-hosts/
https://serve.netsh.org/pub/ipv6-hosts/

**custom filters:**
>@@||serve.netsh.org/pub/*/ads.js$xmlhttprequest
@@||ads.google.com/adserver/adlogger_tracker.json$subdocument,domain=serve.netsh.org
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=serve.netsh.org
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$script,domain=serve.netsh.org
serve.netsh.org#@#.adsbygoogle
serve.netsh.org###aswift_0
serve.netsh.org###aswift_0_anchor
serve.netsh.org###aswift_0_expand
serve.netsh.org###aswift_1
serve.netsh.org###aswift_1_anchor
serve.netsh.org###aswift_1_expand
serve.netsh.org###aswift_4
serve.netsh.org###aswift_4_anchor
serve.netsh.org###aswift_4_expand
serve.netsh.org###aswift_5
serve.netsh.org###aswift_5_anchor
serve.netsh.org###aswift_5_expand

**results:**
**ipv4-hosts:** http://i.imgbox.com/fPereYks.png
**ipv6-hosts:** http://i.imgbox.com/zzyTnnQW.png

**Comment by Neillll** [comment]
@maynak00  thank you :)

**Comment by reek** [comment]
this rule just enough
<code>@@||serve.netsh.org/pub/*/ads.js$xmlhttprequest</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
