### ISSUE TITLE
debridnet.com/livedebrid.com

### ISSUE THREAD

**Issue by monsieurbourbaki** [reek/anti-adblock-killer#1142]
Hi,

As per Issue #1077 (sorry this is the correct issue)

Chrome Version 50.0.2638.0 canary (64-bit)
Taper Monkey 3.12.58 
AdBlockPlus
Filter List - AakList (Anti-Adblock Killer)‎, EasyList, AdBlock Warning Removal

As suggested I've updated both Anti-Adblock Killer and Filter lists.

thanks again,
b

**Comment by reek** [comment]
HI,
Ok, I'll kill it, thanks.

**Comment by monsieurbourbaki** [comment]
thanks so much
mon. b

**Comment by monsieurbourbaki** [comment]
just updated issue with correct #1077

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
