### ISSUE TITLE
tweaktown.com

### ISSUE THREAD

**Issue by Zaxx420** [reek/anti-adblock-killer#1144]
http://www.tweaktown.com/ 
http://imgur.com/8sgCTmc
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by MrSherlockHolmes** [comment]
Hm... which page did you go to, which redirected you to this page? Or rather, what link did you press to get to this? I have a feeling they had that there, but it no longer worked because of AAK, so only people without AAK will have that problem.

**Comment by Zaxx420** [comment]
The orig link

http://www.tweaktown.com/

I get redir wiith aak on...if I disable adblock it loads...with shitloads of ads.

**Comment by Zaxx420** [comment]
url of adblock msg...

http://www.tweaktown.com/sp/index.html

**Comment by MrSherlockHolmes** [comment]
@Zaxx420 Wierd. I don't get that.

**Comment by MrSherlockHolmes** [comment]
@Zaxx420 Oh wait. There are ads. I used `||tweaktown.com/zyx?*` and it suddenly blocked me. We might need @reek to add a fake AakScript ad.

**Comment by Zaxx420** [comment]
Its a shame...Tweaktown is a great pc review site...gotten REALLY popular over the last year. Always had some ads...no biggie...then a few months ago while visiting my entire browser window grays out and up pops a huge ad. Since then its gotten worse and worse as popularity grew. I know ads are a must...but full page, screen dimming popups...no, sorry.

**Comment by MrSherlockHolmes** [comment]
I'll see what I can do - this domain is definitely frustrating! :package:

**Comment by reek** [comment]
@Zaxx420 
Try these rules
<pre>
tweaktown.com##[id*="_ADB_"]
@@||tweaktown.com/zyx?p=
</pre>

**Comment by Zaxx420** [comment]
I'm a noob w/ scripts...how do I add the rule?

**Comment by reek** [comment]
@Zaxx420 
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by Zaxx420** [comment]
done but didn't help...
where are we getting tweaktown.com/zyx?* from? 

I get redirected when I go to www.tweaktown.com if abp is on.

It redirs to the 'ad blocked detected' msg here http://www.tweaktown.com/sp/index.html

It used to load ok but without images...then after a few weeks it began redirecting to the 'ad blocker detected' screen. Maybe it's a graduated response? If you are not getting redirected with abp on when u go to tweaktown.com, check to see if you are missing the images in the news stories...with a red banner at the top bitching about abp.

**Comment by reek** [comment]
@Zaxx420 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by SMed79** [comment]
@Zaxx420 clean you browser cache & cookies and use only [Adblock Plus](https://forums.lanik.us/viewtopic.php?f=62&t=26102) or uBo no use antivirus plugin, [ghostery](http://tinyurl.com/k54jcu6), disconnect, adguard or other crap ...

add also: 
```
tweaktown.com##.flite-mask
tweaktown.com##.flite-ad
||tweaktown.com/zyx?$media
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Zaxx420** [comment]
Spoke too soon...page loaded the first time but when I clicked an article it redird to http://www.tweaktown.com/sp/index.html

It works when I clear cookies/cache then restart FF...but only for the first page load.

Was told to 'add' these lines...

tweaktown.com##.flite-mask
tweaktown.com##.flite-ad
||tweaktown.com/zyx?$media

Where and how exactly? I'm a noob with scripts...

**Comment by Zaxx420** [comment]
Been messin round....wiping cookies doesnt seem to matter. If I clear the cache AND restart FF, I get one successful page load b4 it starts redirecting me.

**Comment by SMed79** [comment]
@Zaxx420 Disable all extensions, keep only your adblock plus then test again.

**Comment by Zaxx420** [comment]
will try...

now that tweaktown has been added in the last update...does it work for you? Do u get redirected? Even when you clk on an article to read?

**Comment by Zaxx420** [comment]
disabled everything except abp and greasemonkey....still get redir when abp is enabled.

Tried disabling cookies for tweaktown.com....no difference...

**Comment by SMed79** [comment]
No redirection here.

**Comment by Zaxx420** [comment]
ok...now THAT screws with my head. If you have abp turned and your not getting the nag screen, I'm totally stumped.

Do you get redir if u disable the aabk script?

**Comment by SMed79** [comment]
> Do you get redir if u disable the aabk script?
No!

**Comment by Zaxx420** [comment]
mk....went digging in the abp filter settings. seen some hits on a tweaktown entry in 'ad blocking rules'. Figured I'd try unticking it and bingo!...i'm now blocking tweaktown ads without getting redirected!

Dunno the hows or whys but that's ok...lol

Here's the entry that borked me.

http://imgur.com/jzjiE2y


Big thanks to everyone for putting up with another 'noob in distress'...much appreciated.

5-spot donation going in next payday...

**Comment by Zaxx420** [comment]
Wired.com has a nag/block that doesn't show until you clk on an article then start scrolling down.
Enabled GM and AAK...problem solved. Nice.

**Comment by SMed79** [comment]
@Zaxx420 
> 5-spot donation going in next payday...

reek will really appreciate.

> Wired.com has a nag/block

Yes, already killed by AKK Script see → https://github.com/reek/anti-adblock-killer/issues/1049

Btw, create new thread for each site ([report guide](https://github.com/reek/anti-adblock-killer/wiki/Report-Guide)) also not post duplicate to avoid confusion and provide better continuity and tracking use search [/issues?utf8=✓&q=wired.com](https://github.com/reek/anti-adblock-killer/issues?utf8=✓&q=wired.com) before posting and paste on same thread if there is already one.

**Comment by Zaxx420** [comment]
Sry...was just mentioning wired off-hand...assumed it had been scripted.

**Comment by reek** [comment]
@SMed79 
thank you for helping @Zaxx420 

@Zaxx420 
Glad to see you knew solve this problem :smile:

If you want to know a little more about filters.
https://github.com/reek/anti-adblock-killer/wiki

**Comment by brunoamancio** [comment]
![tweaktown](https://cloud.githubusercontent.com/assets/3150473/21267593/50750556-c3ab-11e6-9e12-e63e5d50e366.png)
