### ISSUE TITLE
dict.leo.org

### ISSUE THREAD

**Issue by gitgetgot** [reek/anti-adblock-killer#1145]
Version: 9.3
AakScript: true
AakList: true
Browser: Firefox
ScriptManager: Greasemonkey
uBlock Origin

https://dict.leo.org/ende/index_en.html
![screenclip](https://cloud.githubusercontent.com/assets/974980/13717041/202429f2-e7df-11e5-9abb-cb70752a4ba5.png)

**Comment by MrSherlockHolmes** [comment]
Try: `leo.org##div.floatRight.p.tf1`

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
