### ISSUE TITLE
channel4.com

### ISSUE THREAD

**Issue by jefro108** [reek/anti-adblock-killer#1146]
![image](https://cloud.githubusercontent.com/assets/12976435/13717995/a4168450-e7dd-11e5-8cde-4b0bc42892bb.png)
http://www.channel4.com/programmes/my-first-tattoo/on-demand/62922-010?msg_id=DM18565&nl_bid=602772434
http://imgbox.com/WGaKkJhx

Latest version of Google Chrome on Mac OS X 10.10.5
Tampermonkey 
uBlock Origin only with Privacy Badger and Glimmer Blocker. 
I've updated to the latest version of Anti-Adblock Killer Script and List. They are both enabled. 
I disabled Privacy Badger and Glimmer Block and the same result. 
Javascript is enabled. 
No duplicates of Anti-Adblock Killer Script or List.
Adblock Warning Removal List‎ (forums.lanik.us)
 Anti-Adblock Killer | Reek‎  (github.com)
 EasyList‎ (forums.lanik.us)
 Peter Lowe’s Ad server list‎ (pgl.yoyo.org)
AakList (Anti-Adblock Killer)‎

Are you aware of this as an issue or could it be something I have set wrong?

**Comment by jefro108** [comment]
Just saw that this is a duplicate. Sorry. But I wasn't expecting to have to go so far down the list to find it.

Tried adding @@||ak.http.anno.channel4.com^$object-subrequest into the uBlock options > My Filters but no joy.

**Comment by reek** [comment]
I have no solution

**Comment by MrSherlockHolmes** [comment]
@reek :(

**Comment by jefro108** [comment]
Thanks for getting back and thanks for all your work though :)
