### ISSUE TITLE
xtube.com

### ISSUE THREAD

**Issue by tv1mdb** [reek/anti-adblock-killer#1147]
The scripts now breaks xtube's flash content, adding a transparent flash full browser tab after the first click on any page.

http://www.xtube.com/
Chrome
Tampermonkey
uBlock Origin

**Comment by maynak00** [comment]
**try with:**(custom filter)
>@@||cdn.engine.phn.doublepimp.com/pu.swf$object,domain=xtube.com

**Comment by reek** [comment]
@tv1mdb 
Report it to EasyList
