### ISSUE TITLE
dinostream.pw (cinestrenostv.tv)

### ISSUE THREAD

**Issue by limewire** [reek/anti-adblock-killer#1148]
![sd](https://cloud.githubusercontent.com/assets/17796457/13722316/060c0ab2-e820-11e5-8d7f-b14015323b81.png)
http://cinestrenostv.tv/canales/nacionales/holliwood.php
Chrome
Tampermonkey
Adblock
Aaklist + EasyList

**Comment by maynak00** [comment]
**try with:**(custom filters)
>@@||pubted.com/pops/adBlockCheck/adblock.js$script,domain=cinestrenostv.tv
dinostream.pw#@#.afs_ads

**Comment by limewire** [comment]
![sd22222222222](https://cloud.githubusercontent.com/assets/17796457/13725943/dbb1a8a0-e890-11e5-9ab0-33a0c9c449b6.png)

Hi maynak, i put your code in AB Custom Filters without luck, i think that maybe the problem is that EasyList whitelisted this line:
`@@||cinestrenostv.tv/reproductores/adblock.js`

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by limewire** [comment]
Thank you Reek! :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
