### ISSUE TITLE
vtomske.ru

### ISSUE THREAD

**Issue by Rkol** [reek/anti-adblock-killer#1149]

**Comment by MrSherlockHolmes** [comment]
Hmph. The first problem - at least for me, is the `filter` attribute. In Firefox, you cannot do `object.style.filter = "none";` to get rid of the greyscale, which is actually spelt `grayscale`, by the way. Any solutions, anyone?

**Comment by MrSherlockHolmes** [comment]
Yey! I think using `$(".grayscale").css("filter", "none");`, a bit of JQuery, solves the `grayscale`. Then, you can use `vtomske.ru##div.top-notice-text` as a filter rule, to get rid of the top bit. `vtomske.ru##div.bunner`, too, lets you get rid of a few ads. The rest is pretty easy. I'll add them later...

**Comment by reek** [comment]
@Rkol 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by MrSherlockHolmes** [comment]
@reek, again, I'll do it for you...
```
http://news.vtomske.ru
http://i.imgur.com/l5cDi2n.png [before solve]
http://i.imgur.com/pMvzeUi.png [after solve]
Mozilla Firefox
Greasemonkey
Adblock Plus
Malware Domains, EasyList, Aak, EasyPrivacy, Adblock Warning List
```

**Comment by reek** [comment]
@MrSherlockHolmes 
thank you, but you have let @Rkol do,

**Comment by Rkol** [comment]
I checked. In Mozilla Firefox this works. but unfortunately it does not work in Google Chrome.

**Comment by MrSherlockHolmes** [comment]
@reek sure ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
