### ISSUE TITLE
sports.ru

### ISSUE THREAD

**Issue by corpz** [reek/anti-adblock-killer#115]
http://www.sports.ru
http://www.sports.ru/videogallery/1025725043.html?video_id=1025725206
Chrome
Tampermonkey
Adblock Plus
EasyList + Anti-Adblock Killer

**Comment by gsmetal** [comment]
[Adblock Warning Removal List](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt) has this line for sports.ru and it seems to work in adblock and as custom filter in ublock:
`@@||sports.ru^*/adfox.$xmlhttprequest`

**Comment by reek** [comment]
@gsmetal 

Thanks for your help

See you soon
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by gsmetal** [comment]
Hi, this line doesn't help anymore :(
