### ISSUE TITLE
net.hr

### ISSUE THREAD

**Issue by crvenooki** [reek/anti-adblock-killer#1150]
http://net.hr/
http://imgur.com/zFbqgVo
Chrome
Tampermonkey
Adblock Plus
EasyList + AakList
AdBlock
Adblock custom + EasyList + antiadblockfilters + FanboyAnnoyances + AakList

**Comment by MajkiIT** [comment]
add this rule net.hr#@#.reklama

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1139

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
