### ISSUE TITLE
www.hackingwithswift.com

### ISSUE THREAD

**Issue by ecnepsnai** [reek/anti-adblock-killer#1151]
https://www.hackingwithswift.com/example-code/libraries/how-to-parse-json-using-swiftyjson
http://i.imgur.com/LrxGnfE.png
Google Chrome
TamperMonkey
uBlock Origin
uBlock Filters + EasyList + AdServer List + Malware Domains

**Comment by ecnepsnai** [comment]
Site loads: https://www.hackingwithswift.com/js/adsbygoogle.js:

```javascript
var areAdsDisplayed = true;
```

Then tests if that connection was successful:
```javascript

    if(window.areAdsDisplayed === undefined ) {
      $('pre').text('Oops! You appear to have an ad blocker enabled.\n\nThe adverts on this site are small and unintrusive,\nbut they help fund my work and without them I cannot\ngive these tutorials away for free.\n\nIf you do not want to view ads, please buy the\ne-book from https://gum.co/hws-book-pack – it\nincludes every project as a downloadable,\nad-free package.\n\nIf you want to carry on reading here, you will\nneed to disable your ad blocker then reload the\npage in order to see this source code.\n\nI\'m sorry that I have to do this, but please\nunderstand that it costs me money to host these\ntutorials, so when you block my adverts I am literally\npaying for you to learn. That is simply not fair, and\nI hope you will add an exception to your ad blocker\nfor this site.\n\nQuestions? Comments? Tweet me: @twostraws');
    }
```

**Comment by MrSherlockHolmes** [comment]
@ecnepsnai: Therefore this should work: `@@hackingwithswift.com/js/adsbygoogle.js`

**Comment by reek** [comment]
@ecnepsnai 
Ok, I'll kill it, thanks.

@MrSherlockHolmes 
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
