### ISSUE TITLE
prem.link

### ISSUE THREAD

**Issue by Kara-ism** [reek/anti-adblock-killer#1152]
Hello **Reek**,
The version 9.3 of Anti-Adblock-Killer has been detected with prem.link at 2016/03/13,and here's the screen-shot of this occurrence.
<img width="456" alt="default" src="https://cloud.githubusercontent.com/assets/9511279/13727671/94661d04-e936-11e5-864f-30c2506b9d76.PNG">
Thank you!
Opera Stable 35.0.2066.92
μblock Origin 1.6.4 with μBlock filters & EasyList ‎& Anti-Adblock Killer & Adblock Warning Removal List‎ & Fanboy’s Enhanced Tracking List‎.
‎μMatrix 0.9.3.4 with Dan Pollock’s hosts file & hpHosts’s Ad and tracking servers & Long-lived malware domains & Malware Domain List & MVPS HOSTS & Peter Lowe’s Ad server list‎.
TamperMonkey beta 3.13.4956

**Comment by reek** [comment]
Hi,
Ok, I'll fix it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Kara-ism** [comment]
@reek 
Hi,It started to ban users with Ad-blockers again.
I've pretty sure that lists and scripts are both latest version.
(Script v.9.4 & AakList 2016/04/05 GMT)

**Comment by reek** [comment]
@Kara-ism 
I'll fix it again

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
