### ISSUE TITLE
[NEWS] Google May Be Flagging Adblock Users, Denying YouTube Access

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1153]
http://www.thespeaker.ca/technology/google-may-be-flagging-adblock-users-denying-youtube-access/

https://www.reddit.com/r/technology/comments/4a1yl/google_may_be_flagging_adblock_users_denying/

https://www.reddit.com/r/youtube/comments/4a3zmh/google_may_be_flagging_adblock_users_denying/

https://adblockplus.org/forum/viewtopic.php?f=10&t=44403sid=70e5a148a4b4fec6de3b340478396db8

**Comment by maynak00** [comment]
my custom filter: @@||static.doubleclick.net/instream/ad_status.js$script,domain=youtube.com
but I have no problem with or without filter
