### ISSUE TITLE
ge-map-overlays.appspot.com

### ISSUE THREAD

**Issue by wsmith1** [reek/anti-adblock-killer#1154]
```
Mozilla Firefox
uBlock Origin
all uBlock filters
Adblock Warning Removal List‎
AAK
EasyList
Peter Lowe’s Ad server list‎
EasyPrivacy
```

https://imgur.com/bC7ppcs

fixed with

```
@@||ge-map-overlays.appspot.com/files/js$script,first-party
```

**Comment by reek** [comment]
Ok, thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
