### ISSUE TITLE
appdn.net

### ISSUE THREAD

**Issue by Afkjson** [reek/anti-adblock-killer#1155]
http://appdn.net/2016/03/inet-2-1.html
http://i.imgbox.com/8F7MjA6u.png
Chrome / Safari
Tampermonkey
uBlock Origin 1.6.4 / uBlock 0.9.5.2
EasyList + AakList + AdBlock warning + hpHosts

Website uses https://github.com/nicjansma/adblock-detector.js

Thank you for your great work, reek!

**Comment by wsmith1** [comment]
appdn.net is using adBuddy+ (AdBlocker Detection) by NetfunkDesign (https://wordpress.org/plugins/adbuddy-adblocker-detection/) . It was mentioned in #310.

**Comment by maynak00** [comment]
**try with:**(custom filter)
>||appdn.net/*/adblock-detector.min.js$script

**Comment by reek** [comment]
@Afkjson 
Already killed by AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
