### ISSUE TITLE
Make logging to the console optional

### ISSUE THREAD

**Issue by hyatt03** [reek/anti-adblock-killer#1156]
I'm a web developer, and I love logging to the console. I find it kinda annoying that I see output from AAK in the log, so I would love to see that become optional in the settings, or something of the like.

**Comment by reek** [comment]
Hi,
You can disable the logs here.
https://reek.github.io/anti-adblock-killer/#settings

I'll change the default value to false

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by hyatt03** [comment]
@reek Awesome! Thank you!
