### ISSUE TITLE
tweaktown.com

### ISSUE THREAD

**Issue by BrainDedd** [reek/anti-adblock-killer#1157]
http://www.tweaktown.com
http://imgur.com/TjP1gij
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by BrainDedd** [comment]
Shows up when you block tweaktown.com/zyx

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/1144

**Comment by BrainDedd** [comment]
Thanks. Didn't see that one. :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
