### ISSUE TITLE
perk.tv

### ISSUE THREAD

**Issue by richesse** [reek/anti-adblock-killer#1158]
Would really appreciate it if you could include perk.tv.

Thank you & Cheers!

**Comment by maynak00** [comment]
**https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**

**try with:**(custom filter)
>@@||perk.tv/adsense.php$xmlhttprequest

**Comment by reek** [comment]
Can't help you
<code>Sorry, Perk.tv isn't available in your area yet.
Stay tuned!</code>
