### ISSUE TITLE
di.se

### ISSUE THREAD

**Issue by Fredro** [reek/anti-adblock-killer#1159]
http://www.di.se
http://i.imgur.com/PAFwTRz.png
Google Chrome
Tampermonkey
ublock origin
EasyList + anti-adblock killer list

**Comment by Fredro** [comment]
possible to remove by adding these, but the scrollbar is not shown, need to remove "overflow: hidden" from <html>

`di.se###header_overlay
di.se###message_modal`

**Comment by maynak00** [comment]
**try with:**(custom filter)
>@@||di.se/oas/js/analys/ads.js$script

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by Fredro** [comment]
made no difference with that filter

**Comment by reek** [comment]
@Fredro 
the problem comes from uBlock, which does not apply the exception to rule <code>@@||di.se^$elemhide</code> as it should

**Comment by SMed79** [comment]
```
@@||di.se/oas/js/analys/ads.js?*
||di.se/Oas/js/burt/banner.js?*
||login.di.se/check-paywall?*
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
