### ISSUE TITLE
openload.us

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1160]
http://openload.us/caramel-color-wikipedia-the-free-encyclopedia.html

http://imgur.com/3zHpw8d

Mozilla Firefox 45
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MrSherlockHolmes** [comment]
Yeah, just another blockadblock.

**Comment by reek** [comment]
HI,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
