### ISSUE TITLE
ekstrabladet.dk

### ISSUE THREAD

**Issue by hchr** [reek/anti-adblock-killer#1161]
http://ekstrabladet.dk/sport/haandbold/mulles-svenske-veninde-ja-vi-er-et-par/5995581

Loads when reading articles
Block this script:
http://ekstrabladet.dk/template/v5-6/shared/js/modules/usercommunication/usercommunication.js

**Comment by SMed79** [comment]
for the anti-adblock : 
`@@||adtech.de/dt/common/postscribe.js$script,domain=ekstrabladet.dk`
source: https://forums.lanik.us/viewtopic.php?f=62&t=29140

**Comment by hchr** [comment]
>for the anti-adblock :
>@@||adtech.de/dt/common/postscribe.js$script,domain=ekstrabladet.dk

Doesn't work in uBlock Origin, when inserted in My filters.

**Comment by reek** [comment]
add this rule
<code>||ekstrabladet.dk/template/*/shared/js/modules/usercommunication/$script</code>

**Comment by KingWAR10CK** [comment]
Im kinda new here.

I got adblock plus and anti adblock killer.
How do i assign that script? Tried finding a tutorial on google, but couldnt find any.

**Comment by hchr** [comment]
> add this rule
> ||ekstrabladet.dk/template/*/shared/js/modules/usercommunication/$script

Works, thankyou

**Comment by SMed79** [comment]
@KingWAR10CK follow these instructions https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by KingWAR10CK** [comment]
Your so helpful mate! thanks

I changed to ublock origin. Its a lot better :)

Thanks for your kind help!

2016-03-16 17:56 GMT+01:00 Med <notifications@github.com>:

> @KingWAR10CK <https://github.com/KingWAR10CK> follow these instructions
> https://adblockplus.org/forum/viewtopic.php?f=2&t=42013
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/reek/anti-adblock-killer/issues/1161#issuecomment-197422741>
>



-- 
Med venlig hilsen

Frederik Jørgensen
Bygvænget 2, 2. TV.
2750, Ballerup
Tlf: 53828240

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
