### ISSUE TITLE
jeja.pl

### ISSUE THREAD

**Issue by sbb1987** [reek/anti-adblock-killer#1163]
jeja.pl
http://imgur.com/ifmKsl0
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**(custom filter)
>jeja.pl#@##bottomAd

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
