### ISSUE TITLE
www.prosieben.tv

### ISSUE THREAD

**Issue by Jonnesjogy** [reek/anti-adblock-killer#1164]
I have problem with this website. Sadly it won't stop adverts popping up although I have adblock plus!
How can I fix it?
![adverts 2](https://cloud.githubusercontent.com/assets/17865306/13799302/4ac1c934-eb1e-11e5-9946-33bfd3c000ab.PNG)
![adverts](https://cloud.githubusercontent.com/assets/17865306/13799303/4ac3cd4c-eb1e-11e5-8a33-ef90bfa646ce.PNG)

**Comment by reek** [comment]
Report to https://forums.lanik.us
