### ISSUE TITLE
animevf.tv

### ISSUE THREAD

**Issue by ciborge** [reek/anti-adblock-killer#1165]
exemple : http://animevf.tv/boruto-naruto-the-movie-complet-vostfr/

http://i.imgur.com/3Fn4rfv.png

Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList + every fucking thing i can click on in ublock.

**Comment by ciborge** [comment]
But as always a little "right-click" and "hide this shit" and you can go on with your life.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
