### ISSUE TITLE
cda-online.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1166]
http://cda-online.pl/slow-west/
![zrzut2](https://cloud.githubusercontent.com/assets/11302675/13826089/0f8e473c-ebb6-11e5-9cd6-f422d120088b.jpeg)

**Comment by reek** [comment]
Ok, I'll kill it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
