### ISSUE TITLE
64.237.43.94 (semprot.com)

### ISSUE THREAD

**Issue by aryacebe** [reek/anti-adblock-killer#1168]
For example: http://64.237.43.94/showthread.php/1163855-Cangcuter-Fans-Club-amp-(Spy-Mania)
SS: http://imgur.com/22ZmqaA

Spec:
Google Chrome 49.0.2623.87 m
Tampermonkey 3.12.58
uBlock Origin 1.6.4

Filter:
uBlock filters‎
uBlock filters – Badware risks‎
uBlock filters – Privacy‎
uBlock filters – Unbreak
Adblock Warning Removal List
Anti-Adblock Killer | Reek 9.3
EasyList‎
Peter Lowe’s Ad server list‎
Malvertising filter list by Disconnect‎
Fanboy’s Annoyance List‎
Fanboy’s Social Blocking List‎
IDN: ABPindo‎

The site give the red warning message to deactivate my adblock, please kill it. Thanks.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
**try with:**(custom filters)
**for antiadblock:**
`@@||gambar123.com/js/show_ads.js$script,domain=64.237.43.94`

**for other ads:**
`64.237.43.94###sukasekalicrot_side_left`
`64.237.43.94###sukasekalicrot_side_right`
`64.237.43.94##.sukasekalicrot_floating_banner_top`
`64.237.43.94##.sukasekalicrot_floating_banner_bottom`
`64.237.43.94###yayaya_nav`
`||gambar123.com/pic/what/*.gif`

**Comment by aryacebe** [comment]
thanks @maynak00 , it works :D

**Comment by reek** [comment]
@maynak00 
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by bebaspuas20241** [comment]
siap jadi menantu

www,nobokep,my,id

**Comment by caripurel2024** [comment]
cukup cukup

www,nobokep,my,id

**Comment by maunyagitu2024** [comment]
stop jongkok

www,flavaofc,com

**Comment by dirgahayutni2024** [comment]
prabowosiapkan yangterbaik

www,flavaofc,com

**Comment by overthemoonnew** [comment]
​​bang abis shooting squid game?

www,kontenterabox,com
