### ISSUE TITLE
hdmovie14.net

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#1169]
http://hdmovie14.net/watch/titanic-1997-putlocker-hd-full-movie#player_wraper
http://i.imgur.com/1q1zk3Y.png
Mozilla Firefox 42
Greasemonkey
Ublock Origin
EasyList + AakList + AakScript

All movies show a green anti-adblocker messages and do not load. A red message appears on top to select a different server...

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/1133

**Comment by Giwayume** [comment]
Huh. I used the search before I opened this, wonder why it didn't show up.
