### ISSUE TITLE
rtlxl.nl

### ISSUE THREAD

**Issue by pjottrr** [reek/anti-adblock-killer#117]
link: http://www.rtlxl.nl
every available video here gets black and white. 

img: http://imgur.com/kcCIva9

Your browser: firefox
Your script manager greasemonkey
Your adblocker abp
Your filterlists all of the actions described on your website: ( https://greasyfork.org/en/scripts/735-anti-adblock-killer-reek) 

so what happens is, they detect adblocker, and ask to enable ads. if not the content will only be played in black and white. 
I.ve tested the adblock detection killer on multiple other sites and there it works fine. 

I hope you can find a solution. 
If you need a dutch ip, just contact me , i'll set it up :) 
translation of the text in the image: 
"
ADBLOCKER DETECTED
without advertisement income there is no RTL XL. 
so turn off your adblocker for a collorfull experience
"

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
