### ISSUE TITLE
Inline-Script Ad Killer project wanted

### ISSUE THREAD

**Issue by davidhedlund** [reek/anti-adblock-killer#1170]
The filter Fanboy’s Annoyance List‎ found in uBlock Origin (for example) hides this top message in google.com "We've detected you're using an older version of Chrome. Update to stay secure".

However, a side effect when Fanboy’s Annoyance List‎ do so is that it also breaks the layout in google.com by putting the menubar ("All Shopping Images Videos News MoreSearch tools") behind the search bar leaving it unreachable.

It appears to me that Google have set up scripts to create this problem purposely.

Blockers that utilize the ad blocking filter EasyList (originally Adblock Plus, now also uBlock Origin (uBO), etc) will block ad JavaScript files, in rare case uBO will add JS injection against inline-scripts. Consider to start a new project to fix this, I have not researched if other such projects exist so please have a look.

**Comment by MrSherlockHolmes** [comment]
I'll have a look at this problem. Thing is, google will keep changing it. Google knows that it can never truly stop adblock, but it can make life harder for adblockers.

**Comment by IDKwhattoputhere** [comment]
Have you reported this to @ryanbr (aka Fanboy) [here](https://forums.lanik.us/viewforum.php?f=64)?

**Comment by Giwayume** [comment]
I've set a user agent string to Chrome 27 and I'm not getting that message.

**Comment by Giwayume** [comment]
The menu bar is **supposed** to be under the search bar. Google frequently changes the websites they have control over and this has nothing to do with adblock.

**Comment by davidhedlund** [comment]
@IDKwhattoputhere No, I haven't contact him, he'll see it now however.

**Comment by davidhedlund** [comment]
@Giwayume I meant behind, not under. I corrected the issue in the first message. Thanks.
