### ISSUE TITLE
www.embedupload.com

### ISSUE THREAD

**Issue by Loriaes** [reek/anti-adblock-killer#1174]
http://www.embedupload.com/?d=7FASOUAVZZ
http://imgur.com/O4nKlNC
Mozilla Firefox
Greasemonkey
Adblock Plus
Adblock Warning Removal List + EasyList + AakList

**Comment by maynak00** [comment]
**try with:**
(tested with chromium-ublock origin)
`@@||embedupload.com^$elemhide`
`embedupload.com###ads_leaderboard`

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1173

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
