### ISSUE TITLE
The New Yorker - newyorker.com

### ISSUE THREAD

**Issue by AgentRev** [reek/anti-adblock-killer#1177]
http://www.newyorker.com/books/page-turner/the-irish-novel-thats-so-good-people-were-scared-to-translate-it

The article is absent from the page, due to being wrapped in a div with the class "ad-container", which is blocked by "EasyList Liste FR"‎; disabling the latter allows the article to show. The site appears to be running on WordPress.

There's also this event showing up in uBlock's logger, but not sure if relevant:

> http\://event.condenastdigital.com/images/event.gif?e0_id=www.newyorker.com%2F**blocked_pageview**&e0_ec=**adblock**&e0_env=dart&e0_sc=new&e0_tit=Firefox%2C45.0&e0_url=http%3A%2F%2Fwww.newyorker.com%2Fbooks%2Fpage-turner%2Fthe-irish-novel-tha...

Windows 10
Firefox 45.0 x64
uBlock Origin 1.6.2
Anti-Adblock Killer | Reek 9.3

**Comment by reek** [comment]
HI,
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
problem: Static filter ##.ad-container found in: FRA: EasyList Liste FR

**try with:**
`newyorker.com#@#.ad-container`
(not necessary if disabled: FRA: EasyList Liste FR)

**Comment by AgentRev** [comment]
Yes, I already said that in my initial description...

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
