### ISSUE TITLE
freetuts.net

### ISSUE THREAD

**Issue by x0rm3r** [reek/anti-adblock-killer#1179]
http://freetuts.net/*.html
http://i.imgur.com/qSWum2f.png
Chrome + Firefox
uBlock Origin
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**
`@@||freetuts.net/*/adsense.js$script`

**optional**(not for antiadblock):
`||freetuts.net/public/theme/aff/*$image`

**Comment by reek** [comment]
@x0rm3r 
Ok, I'll kill it, thanks.

@maynak00 
Thanks :+1:

**Comment by x0rm3r** [comment]
Not really!

It still appears

![freetuts.net](http://i.imgur.com/iXkTn1r.png)

**Comment by reek** [comment]
@x0rm3r 
It's ok for me, see help
https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
