### ISSUE TITLE
onemanga.me

### ISSUE THREAD

**Issue by TetraSky** [reek/anti-adblock-killer#118]
previous topic > https://github.com/reek/anti-adblock-killer/issues/109#issue-51233799

This was fixed 2 weeks ago, but it is once again preventing access, saying to whitelist in adblock.
![capture](https://cloud.githubusercontent.com/assets/7884915/5516631/f5f87f92-8877-11e4-9f2b-a6c39c922845.JPG)
Cannot view the "manga" without disabling adblock or whitelisting the site

Firefox 34.0
Adblock Edge
Fanboy + Easylist Merged Ultimate List
Adblock Warning Removal List
Anti-Adblock Killer, greasemonkey script.

http://www.onemanga.me/shokugeki_no_soma/
http://www.onemanga.me/shokugeki_no_soma/99/

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
