### ISSUE TITLE
20minutes.fr

### ISSUE THREAD

**Issue by Rosilana** [reek/anti-adblock-killer#1180]
http://www.20minutes.fr/

![anti-adblock-killer](https://cloud.githubusercontent.com/assets/17963744/13904710/6ef3f596-eea9-11e5-855a-fc7d6a674ad8.png)
Coucou !

I use for the first time your anti-adblock killer. It's awesome ! But your script don't kill www.20minutes.fr. Why ? Thank you for your help !

**Comment by reek** [comment]
Hi,

Which adblock lists and extensions you use ?

Try add this rule
<code>@@||20mn.fr/bundles/etnatracking/js/adblock.js$script</code>

**Comment by SMed79** [comment]
Hi, 
i can not reproduce, i think **adblock.js** is used only for tracking.

**Comment by Rosilana** [comment]
Hi !

Thank you for your help !

I'm sorry for my late reply ( i use google translate aie).  Reek i use Adblock 2.53, google (docs, sheets, slides...), Internet download Manager, LiveReload, TamperMonkey, The Great Suspender, Wikiwand.

I'm newbie. Where should i put @@||20mn.fr/bundles/etnatracking/js/adblock.js$script ?

Thank you for your great kindness

**Comment by SMed79** [comment]
Bonjour, 

- [AdBlock](https://getadblock.com/) button > Options > CUSTOMIZE tab and copy/past the filter suggested by reek.
- [Adblock plus](https://adblockplus.org/) follow these instructions → https://adblockplus.org/forum/viewtopic.php?f=2&t=42013
- [ublock0]() button > dashboard > my filters and copy/past the filter then click apply.

Si non vous pouvez s'exprimer en français :-)

**Comment by Rosilana** [comment]
Merci beaucoup !

Vous êtes génial !

**Comment by SMed79** [comment]
@Rosilana pour les autres médias https://forums.lanik.us/viewtopic.php?f=91&t=29253

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
