### ISSUE TITLE
hdmovie14.net

### ISSUE THREAD

**Issue by AdHelper** [reek/anti-adblock-killer#1182]
https://goo.gl/NO3ufH

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/1133

**Comment by reek** [comment]
@AdHelper 
Next time read report gide

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
