### ISSUE TITLE
nicoblog.org

### ISSUE THREAD

**Issue by TenaciousJ728** [reek/anti-adblock-killer#1184]
http://nicoblog.org/strategy-guide/final-fantasy-x-2-bradygames-official-strategy-guide/
http://i.imgur.com/4OvWXZT.jpg
Chrome
Tampermonkey
Adblock Plus
Reek's AAK + All default ABP lists

Note: "Disable Adblock to see download links" string replaces adfly links.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ronnyikhwan** [comment]
ok,, i see..... [http://nicoblog.co/strategy-guide/final-fantasy-x-2-bradygames-official-strategy-guide/](url)

**Comment by RetroGameTalk** [comment]
@ronnyikhwan So are you making any money of your scamy site? You registered nicoblog.co and nicoblog.me and who knows what else, is the money flowing in buddy? Did it worth it?
@reek thanks for the effort on denying the real nicoblog of any revenue you are an MVP yourself.
