### ISSUE TITLE
mkvcinemas.com / newhdmovie24.com / sports4u.tv / mamahd.com

### ISSUE THREAD

**Issue by MehulHardy** [reek/anti-adblock-killer#1185]
http://www.mkvcinemas.com/
http://newhdmovie24.com/

 poping up to disable adblock

http://sports4u.tv/channel/sky-sports-2/ (asking to disable ad block during buffer)

**Comment by maynak00** [comment]
**https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**

**try with:**
`mkvcinemas.com#@#.afs_ads`
`newhdmovie24.com#@#.afs_ads`
optional: `newhdmovie24.com###yllix_slider`
`sports4u.tv#@##adblock`

**Comment by SMed79** [comment]
- https://forums.lanik.us/viewtopic.php?f=62&t=29278
- https://forums.lanik.us/viewtopic.php?f=62&t=29279
- https://forums.lanik.us/viewtopic.php?f=62&t=29280

**Comment by reek** [comment]
@MehulHardy 
Ok, I'll kill it, but next time create new issue for each website

**Comment by SMed79** [comment]
```
hdcast.org###notice
hdcast.org###ads
mamahd.com###html3
mamahd.com###ad_overlay
@@||mamahd.com^$generichide
```

**Comment by MehulHardy** [comment]
Thanks guys.. and sorry it was my first post, next time i ll post as per your rules.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
