### ISSUE TITLE
lemonde.fr

### ISSUE THREAD

**Issue by SpecialTerminator** [reek/anti-adblock-killer#1186]
http://www.lemonde.fr/
https://imgur.com/uqXnv4y
Mozilla Firefox 45.0 (on GNU/Linux)
Greasemonkey
Adblock Plus
Liste FR EasyList + Adblock Warning Removal List + EasyList Germany + AakList + Malware Domains + Prebake Filters Obstructive Cookie Notices

NOTE : This page http://www.lemonde.fr redirect to http://www.lemonde.fr/modele-economique/ (screenshot getting on this redirect page)

PS : Sorry for my bad english, i am speek french.

**Comment by maynak00** [comment]
**try with:**
`@@||lemonde.fr/*/advertisingbanner.js$xmlhttprequest`

**Comment by SpecialTerminator** [comment]
it seem work good.

(sorry for my bad english)

**Comment by Francois-dag** [comment]
Yes it works , thanx !

**Comment by D4m1en** [comment]
Yes, I confirm this is the solution.

**Comment by reek** [comment]
@maynak00 
Well done !

**Comment by SMed79** [comment]
if change:
`@@||lemonde.fr^$xmlhttprequest`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by marcosbdm** [comment]
I guess they found a workaround because it doesn't work anymore...
Is AAK still working for you on lemonde.fr ?

Mozilla Firefox 45.0 (on GNU/Linux)
Greasemonkey
Adblock Plus
Adblock Warning Removal List + Liste FR EasyList + AakList

**Comment by Francois-dag** [comment]
with ghostery it works, without unfortunately not.

**Comment by mapx-** [comment]
add this filter
`@@||kameleoon.com^$xmlhttprequest,domain=lemonde.fr`
