### ISSUE TITLE
lefigaro.fr

### ISSUE THREAD

**Issue by SpecialTerminator** [reek/anti-adblock-killer#1187]
http://www.lefigaro.fr/actualite-france/2016/03/21/01016-20160321ARTFIG00003-le-gouvernement-veut-renforcer-la-prevention-de-la-radicalisation.php
https://imgur.com/UvaRv4J
Mozilla Firefox 45.0 (on GNU/Linux)
Greasemonkey
Adblock Plus
Liste FR EasyList + Adblock Warning Removal List + EasyList Germany + AakList + Malware Domains + Prebake Filters Obstructive Cookie Notices

**Comment by D4m1en** [comment]
Solution: add

@@||a.f1g.fr/build/2/adsense.js$script,domain=www.lefigaro.fr

**Comment by maynak00** [comment]
**try with:**
`@@||a.f1g.fr/*/adsense.js$script,domain=lefigaro.fr`

**Comment by reek** [comment]
@D4m1en 
@maynak00 
Well done, thanks.

**Comment by SMed79** [comment]
```
@@||lefigaro.fr^$generichide
@@||smartadserver.com^$script,domain=lefigaro.fr
@@||f1g.fr^$script
||outbrain.com^
lefigaro.fr##A[href*="/click"]
```
https://forums.lanik.us/viewtopic.php?f=91&t=29255

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
