### ISSUE TITLE
europe1.fr

### ISSUE THREAD

**Issue by SpecialTerminator** [reek/anti-adblock-killer#1188]
http://www.europe1.fr/economie/la-liberalisation-des-autocars-a-cree-900-emplois-en-cinq-mois-2698408
https://imgur.com/t7Xgdst
Mozilla Firefox 45.0 (on GNU/Linux)
Greasemonkey
Adblock Plus
Liste FR EasyList + Adblock Warning Removal List + EasyList Germany + AakList + Malware Domains + Prebake Filters Obstructive Cookie Notices

**Comment by maynak00** [comment]
try with:
`@@||a.f1g.fr/*/adsense.js$script,domain=lefigaro.fr`

**Comment by SpecialTerminator** [comment]
It's work for lefigaro.fr

Propably mismatch post on bug ticket europe1.fr or lefigaro.fr

Sorry for my bad english.

**Comment by maynak00** [comment]
@SpecialTerminator, yes, you're right. I posted in wrong page. sorry(I will post in lefigaro.fr page). for my test, no adblocker detected message on page.

*Static filter ||cdn-analytics.ladmedia.fr^ found in:EasyPrivacy*

**try with:**
`||cdn-analytics.ladmedia.fr^`
or enable **EasyPrivacy** filter

**Comment by reek** [comment]
@maynak00 
Let me do, I'll create a rule in AakScript

@SpecialTerminator 
Ok, I'll kill it, thanks.

**Comment by SMed79** [comment]
`europe1.fr#@#.text_ads`
or
`||cdn-analytics.ladmedia.fr^`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
