### ISSUE TITLE
lexpress.fr

### ISSUE THREAD

**Issue by f1kadelick** [reek/anti-adblock-killer#1189]
http://www.lexpress.fr/

Most of french newspaper are using this script since 2016-03-21

Chrome Version 49.0.2623.87 m (64-bit) on Windows 10 64 bits
Ghostery for Chrome version 5.4.11
Tanpermonkey with Anti-Adblock Killer 9.3
AdBlock Version 2.53
EasyList + Personnalized Filters AdBlock + French filters

![me7kn9wn](https://cloud.githubusercontent.com/assets/17983587/13919345/c8d3975e-ef64-11e5-9c62-4e8eab6d6e7e.jpg)

**Comment by maynak00** [comment]
**try with:**
`@@||lexpress.fr/*/ads.css$stylesheet`

**Comment by SMed79** [comment]
```
lexpress.fr#@#.partner
lexpress.fr#@#.block_partner
@@||lexpress.fr^$generichide
@@||static.lexpress.fr^$script
@@||smartadserver.com^$domain=lexpress.fr
@@||lexpress.fr^$stylesheet
```
https://forums.lanik.us/viewtopic.php?f=91&t=29261

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
