### ISSUE TITLE
rtl.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1192]
Hi, 
on `http://www.rtl.fr/` http://i.imgur.com/z8EOjrY.png
`||rtl.fr/alerte$xmlhttprequest`

Merci.

**Comment by reek** [comment]
Ok, thanks

**Comment by SMed79** [comment]
Sorry, issue to play video/audio file https://forums.lanik.us/viewtopic.php?f=91&t=29267#p89781
new rule `rtl.fr#@##bottomAd`

**Comment by reek** [comment]
Ok

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
