### ISSUE TITLE
oneplay.tv (cinestrenostv.tv)

### ISSUE THREAD

**Issue by limewire** [reek/anti-adblock-killer#1193]
![ciddddddddddddddddp](https://cloud.githubusercontent.com/assets/17796457/13941057/5fd39aca-efc2-11e5-9d54-9bdb3d0423aa.png)

http://bit.ly/1ReWDzt

Chrome
Tampermonkey
Adblock
Aaklist + EasyList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by limewire** [comment]
Thank you Reek!!! :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
