### ISSUE TITLE
filesisland.com

### ISSUE THREAD

**Issue by ZARIOH** [reek/anti-adblock-killer#1195]
hi
![sans titre](https://cloud.githubusercontent.com/assets/12816451/13944540/52189036-f006-11e5-8e00-0ccbc11da425.png)

http://filesisland.com/vf7sp7nil50b

thanks

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
**try with:**
`@@||filesisland.com/*/ads.js$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
