### ISSUE TITLE
clubic.com

### ISSUE THREAD

**Issue by ciborge** [reek/anti-adblock-killer#1196]
http://prntscr.com/ailpab

Example : [Clubic](http://www.clubic.com/mag/culture/actualite-800596-bluray-aacs-enhanced-contournement-anticopie.html)

Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList + every fucking thing i can click on in ublock.

**Comment by SMed79** [comment]
No issue with `Adblock plus` try to add (uBlock O) :
`@@||clubic.com/js/publicite.js`

**Comment by ciborge** [comment]
Nope. dont work.

**Comment by reek** [comment]
@ciborge 
try add this rule
<code>||clubic.com/assets/js/6f34f4c.js$script</code>

**Comment by SMed79** [comment]
@ciborge (_sorry i have edit my first message_) work with Adblock Plus http://i.imgur.com/kWfaTHW.png
@reek No anti-adblock message but block also images http://i.imgur.com/yA2aT4B.png

**Comment by SMed79** [comment]
@ciborge try with uBo:
```
@@||clubic.com^$elemhide
@@||ww691.smartadserver.com/diff/js/smart.js$domain=clubic.com
@@||webedia-fr.nuggad.net/rc$domain=clubic.com
@@||cstatic.weborama.fr/wam/wfpd.min.js$domain=clubic.com
@@||rtax.criteo.com/delivery/rta/rta.js$domain=clubic.com
@@||ww84.smartadserver.com/config.js$domain=clubic.com
@@||js.revsci.net/gateway/gw.js$domain=clubic.com
@@||asset.pagefair.com/adimages/adsense.js$domain=clubic.com
```

**Comment by reek** [comment]
@SMed79 
I have no problem with my rule

@ciborge
Can you check

**Comment by ciborge** [comment]
@reek 
it works.

**Comment by grostire** [comment]
Thank you reek, it works great :-)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
