### ISSUE TITLE
canShowAds

### ISSUE THREAD

**Issue by TJFJefroy** [reek/anti-adblock-killer#1197]
I now you already killed canRunAds, but canShowAds is still working and for example promptfile.com is using it.

**Comment by reek** [comment]
Hi,
Thanks, I'll add rule for this

**Comment by SMed79** [comment]
`http://www.promptfile.com/l/6ABEFE3592-FA344D1015`
i am still redirected to `/adblock.php` unless I added `@@||promptfile.com^$script`

**Comment by TJFJefroy** [comment]
Use my version i added the canshowads killer.

**Comment by Theotech6** [comment]
@TJFJefroy I'm extremely new to this and know almost nothing. If you've been able to fix it, can you maybe walk me through the steps of how to set it up so it starts working with promptfile?

Thanks in advance

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
