### ISSUE TITLE
afreesms.com

### ISSUE THREAD

**Issue by spacedingo** [reek/anti-adblock-killer#120]
Go to http://www.afreesms.com and click on "send free SMS"
or
go to http://www.afreesms.com/freesms/

Adblock message: http://i.imgur.com/vBkVT0a.jpg

Used Chrome + Ublock (with anti-adblock-killer list) and also Firefox + Ghostery

Thanks and all the best

**Comment by SystemRevolution** [comment]
Posible solution:
`xajax_adBlock=function(){return false;}`
It must run just after the script on line 22 (function declared on line 26) to fake the adblock-radar result.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
`@@||166.62.118.104/adv.php?xadb=$script,third-party`

**Comment by reek** [comment]
Thanks Med

**Comment by SMed79** [comment]
`@@/adv.php?xadb=$script,third-party,domain=afreesms.com`

**Comment by reek** [comment]
@SMed79 
Ok, thanks

**Comment by uBlock-user** [comment]
for uBO - `afreesms.com##script:inject(abort-on-property-read.js, blockAdBlock)`
