### ISSUE TITLE
goldenmoustache.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1200]
Hi, 

on `http://www.goldenmoustache.com/` sc: http://i.imgur.com/AXYQ4Hu.png

`goldenmoustache.com##IFRAME[mozallowfullscreen="true"]` 

more info https://forums.lanik.us/viewtopic.php?f=91&t=29258

Thanks!

**Comment by reek** [comment]
Thanks Med

**Comment by SMed79** [comment]
`||goldenmoustache.com/wp-content/themes/golden-moustache/js/libs/modernizr-`

**Comment by reek** [comment]
Ok :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
