### ISSUE TITLE
nouvelobs.com

### ISSUE THREAD

**Issue by thiegaillard** [reek/anti-adblock-killer#1201]
Hello,
the news site of "Nouvel Observateur" http://tempsreel.nouvelobs.com/ displays the following message
![adbblock](https://cloud.githubusercontent.com/assets/18032943/13990707/90de8cac-f115-11e5-9aeb-b5c3eecf1345.jpg)
Thank you in advance for your help

**Comment by reek** [comment]
Hi,
Ok, I 'll kill it, thanks.

**Comment by maynak00** [comment]
**try with:**
`@@||googleadservices.com/pagead/conversion.js$script,domain=tempsreel.nouvelobs.com`

**Comment by thiegaillard** [comment]
I have a problem : this filter does not work

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
