### ISSUE TITLE
leparisien.fr 

### ISSUE THREAD

**Issue by thiegaillard** [reek/anti-adblock-killer#1202]
a new site with an anti-adblock Message 
![adbblock](https://cloud.githubusercontent.com/assets/18032943/13993186/94b72ece-f11f-11e5-8263-8832c7ee6ed3.jpg)
Example
http://www.leparisien.fr/faits-divers/une-habitante-de-sevran-ces-tueurs-ca-pourrait-etre-nos-voisins-23-03-2016-5652747.php#xtref=https%3A%2F%2Fwww.google.fr
Kill this !
Thanks

**Comment by reek** [comment]
Hi,
It's already killed by AakList, see instruction or help
https://github.com/reek/anti-adblock-killer#instruction
https://github.com/reek/anti-adblock-killer#help

**Comment by SMed79** [comment]
Limitation 5 articles for adblocker users.
http://i.imgur.com/X9ZXztN.png
http://i.imgur.com/yb0b2Vr.png

add:
`||leparisien.fr/espace-securise/shield/read-article/*?fingerprint=`

**Comment by reek** [comment]
@SMed79 
thanks
