### ISSUE TITLE
vgtv.no

### ISSUE THREAD

**Issue by DevonX** [reek/anti-adblock-killer#1203]
http://www.vgtv.no/#!/video/123791/alenepappa
http://i.imgur.com/RlDekvT.png
Google chrome
Tampermonkey
adblock plus + Ghostery
EasyList + AakList (Anti-Adblock Killer) + Adblock Warning Removal List

**Comment by maynak00** [comment]
**try with:**
`@@||adtech.de^$script,domain=vgtv.no`
tested with uBlock Origin in Chromium

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by bakagringo** [comment]
@@||no-vg.videoplaza.tv/proxy/distributor/ helps get rid of the preload ads. (Blocked some servers in addition to this, so dunno if this alone is enough). The .vgtvadvert block from the latest AakList messes up the site however.

http://www.vgtv.no/#!/video/124522/lastebilens-dashbord-kamera-filmet-da-alt-gikk-galt
https://i.imgur.com/pB1rdBZ.png
Mozilla Firefox
Greasemonkey
uBlock Origin 
EasyList + AakList (Anti-Adblock Killer) + Malware Domains + EasyPrivacy +  Anti-ThirdpartySocial + uBlock filters.
