### ISSUE TITLE
6play.fr

### ISSUE THREAD

**Issue by iscreamcoke** [reek/anti-adblock-killer#1204]
http://www.6play.fr/

Unable to watch shows.

https://imgur.com/olvQjqR

example : http://www.6play.fr/capital-p_860/Ma-maison-ma-mine-d-or--c_11557562

Thank you

**Comment by MrSherlockHolmes** [comment]
Funnily enough, I just clicked some random buttons, and it doesn't block me. I'll take a look, though.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
