### ISSUE TITLE
crunchyroll.com

### ISSUE THREAD

**Issue by iRoxor** [reek/anti-adblock-killer#1206]
http://www.crunchyroll.com/gate/episode-22-the-empress-in-slaves-clothing-692653 (example, any video will do)
http://i.imgur.com/KYrF8Tn.png
Google Chrome Version 49.0.2623.87 m
Tampermonkey
Adblock Plus
AdBlock custom filters + EasyList + Adblock Warning Removal list + Antisocial filter list + EasyPrivacy + Fanboy's Annoyances + Malware protection + AakList (Anti-Adblock Killer)

**Comment by maynak00** [comment]
**try with:**
`@@||crunchyroll.com/*/ads_enabled_flag.js$script`

**Comment by reek** [comment]
@iRoxor 
Ok, I'll kill it

@maynak00 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
