### ISSUE TITLE
Forbes.com

### ISSUE THREAD

**Issue by mskadu** [reek/anti-adblock-killer#1208]
www.forbes.com/sites/timworstall/2015/12/06/finally-someone-does-something-sensible-finland-to-bring-in-a-universal-basic-income/
http://imgur.com/MfGASQV
Google Chrome
TamperMonkey
EasyList + Adblock Warning Removal List + AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Hi,
Already killed by AakScript, see instruction

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
