### ISSUE TITLE
bfmtv.com

### ISSUE THREAD

**Issue by f6fvy** [reek/anti-adblock-killer#1209]
http://www.bfmtv.com/politique/prix-humour-politique-5-nouvelles-petites-phrases-preselectionnees-961655.html
http://prnt.sc/ajc6vx
Mozilla Firefox 45.0.1
Greasemonkey
uBlock Origin
AakList + many others, including EasyList

Thanks !

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
**try with:**
`@@||bfmtv.com/*/advertising.png$image`

**Comment by f6fvy** [comment]
Very good. Thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
