### ISSUE TITLE
manga9.com

### ISSUE THREAD

**Issue by TokcDK** [reek/anti-adblock-killer#121]
Just try to see any manga on this site. Same message as for this issue - https://github.com/reek/anti-adblock-killer/issues/118

**Comment by SystemRevolution** [comment]
This script can revert the anti-adblock script on manga9.
`document.querySelector('.manga-page').style.cssText='max-width: 940px;'; //To show the manga page`
`document.querySelector('.wpm_pag p').remove(); //To remove the adblodk message`

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
