### ISSUE TITLE
wurst-client.tk

### ISSUE THREAD

**Issue by Bluscream** [reek/anti-adblock-killer#1210]
https://www.wurst-client.tk/news/2016-03-18-Wurst-3-0pre1/
![https://i.gyazo.com/9b385c318842d8d7b873f1a963eb1d80.png](https://i.gyazo.com/9b385c318842d8d7b873f1a963eb1d80.png)
Google Chrome: 49.0.2623.87 (Official Build) m (32-bit)
Tampermonkey: v4.0.5145
[AdblockPlus Dev Channel](https://chrome.google.com/webstore/detail/adblock-plus-development/ldcecbkkoecffmfljeihcmifjjdoepkn)
AakList + many others, including EasyList

Thanks !

``` javascript
$(function () {
  $('[data-toggle="tooltip"]').tooltip();
  $('[data-toggle="popover"]').popover();

  // AntiAdBlock
  var ad = $('[data-ad-client="ca-pub-5218363098774955"]');
  if (!ad.length)
    return;
  if (ad.css('display') === 'none') {
    ga('send', 'event', "adblock", "enabled");
    $('.post-content').html("Turn off AdBlock.");
  } else
    ga('send', 'event', "adblock", "disabled");
});

**Comment by reek** [comment]
Hi,
Already killed by AakList

**Comment by Bluscream** [comment]
It does block the site content after 1 second for me.

**Comment by Bluscream** [comment]
I just updated my AakList and still nothing.

**Comment by reek** [comment]
Ok, give me more informations
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Bluscream** [comment]
You are a f*cking genious :3 Thank you very much =3
