### ISSUE TITLE
mrpiracy.xyz

### ISSUE THREAD

**Issue by marcojoao** [reek/anti-adblock-killer#1211]
For registed members it blocks.
![sem titulo](https://cloud.githubusercontent.com/assets/13734465/14034776/51e78666-f21e-11e5-9667-d34d120ad726.jpg)

**Comment by reek** [comment]
Hi,
Already killed by AakList, see instruction

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
