### ISSUE TITLE
merlininkazani.com

### ISSUE THREAD

**Issue by ultrayer6** [reek/anti-adblock-killer#1212]
http://www.merlininkazani.com/index.asp
http://imgur.com/znoyFHa
Google Chrome
Tampermonkey
AdBlock
AakList + many others, including EasyList

**Comment by reek** [comment]
Hi,
Already killed by AakList, see instruction or help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
`||merlininkazani.com/images/helpus.jpg$image`
**or**
`merlininkazani.com###reklam`
**or**
`merlininkazani.com###helpus_300`
**optional:**
`||adocean.pl/*/ad.js$script,domain=merlininkazani.com`
`merlininkazani.com###mrln-banner`
`merlininkazani.com###banner_728`
`merlininkazani.com###billboard_banner`
`merlininkazani.com###billboard_kapat`
