### ISSUE TITLE
opensnow.com

### ISSUE THREAD

**Issue by jocamero** [reek/anti-adblock-killer#1216]
https://opensnow.com/dailysnow/colorado
http://i.imgur.com/Qwhvqoy.png
Apple Safari 9.1 (OS X 10.11.4)
NinjaKit
AdBlock
EasyList + AakList + AbBlock custom filters + Adblock Warning Removal list + Malware protection + Fanboy's Annoyances + Antisocial filter list

**Comment by reek** [comment]
Hi,
Try with tampermonkey extension and removes Ninjakit
https://safari.tampermonkey.net/tampermonkey.safariextz

**Comment by jocamero** [comment]
Working now.  Thanks!
