### ISSUE TITLE
sports.fr

### ISSUE THREAD

**Issue by kiya974** [reek/anti-adblock-killer#1217]
please, can you update your soft with this website :
http://www.sports.fr/

Thank you
Kiya

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, but next time read report guide.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by kiya974** [comment]
Thank you, i will test 

Envoyé de mon iPhone
