### ISSUE TITLE
Issue from Dailymotion

### ISSUE THREAD

**Issue by sunghlin** [reek/anti-adblock-killer#1218]
Hi 

I found a issue of using anti-adblock-killer in DailyMotion. I have tested this in uBlock Origin and AdBlock Plus. 

When I apply this filter, the advertisement will be blocked, but this is still an advertisement layer covering the video content. This cover has an advertisement label at the bottom, and you cannot seek the time. I check the log. I found only "@@||ad4.liverail.com^$xmlhttprequest" is from anti-adblock-killer. Is there any way for me to solve this issue instead of disabling the filter?

Thanks,

**Comment by reek** [comment]
Hi,

I will restrict the application of this rule, thank you

See you
Reek

2016-03-26 1:46 GMT+01:00 Sung-Han Lin <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
