### ISSUE TITLE
avmoo.com

### ISSUE THREAD

**Issue by ihcnab** [reek/anti-adblock-killer#1219]
site:
http://avmoo.com/

sc:
http://imgur.com/fmCvnEc

Mozilla Firefox 45.0.1
Greasemonkey 3.7
Adblock Plus 2.7.2
AakList + EasyList China + EasyList

Thanks in advance :D

**Comment by reek** [comment]
HI,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
