### ISSUE TITLE
sc2casts.com

### ISSUE THREAD

**Issue by akachewbaca** [reek/anti-adblock-killer#1220]
http://sc2casts.com/
http://imgur.com/biezbMw
Google Chrome
Greasemonkey
Adblock Plus

**Comment by Shakos** [comment]
I am not getting a popup on Chrome (only using uBlock origin). 
On Firefox I can't get past it (uBlock origin + Greasemonkey). Disabled all other extensions.

**Comment by akachewbaca** [comment]
Thanks for the comment -- I tried chrome with only uBlock origin and all other extensions disabled and still received the same message, interesting.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
