### ISSUE TITLE
rte.ie

### ISSUE THREAD

**Issue by M-111** [reek/anti-adblock-killer#1221]
http://www.rte.ie/player/gb/live/7/
http://imgur.com/dmolre3
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

Has been mentioned before, but old rule <code>@@||bs.serving-sys.com/crossdomain.xml$object-subrequest,domain=rte.ie</code> doesn't seem to do anything any more, thanks.

https://github.com/reek/anti-adblock-killer/issues/1030

**Comment by SMed79** [comment]
Hi,
to avoid confusion and provide better continuity and tracking use [**search**](https://github.com/reek/anti-adblock-killer/issues?utf8=%E2%9C%93&q=rte.ie) and post on same thread if there is already one.

```
@@||bs.serving-sys.com^*crossdomain.xml$object-subrequest,domain=rte.ie
@@||pubads.g.doubleclick.net/gampad/ads?$object-subrequest,domain=rte.ie
```
https://forums.lanik.us/viewtopic.php?f=62&t=29368

Duplicate to https://github.com/reek/anti-adblock-killer/issues/1044 https://github.com/reek/anti-adblock-killer/issues/1030 https://github.com/reek/anti-adblock-killer/issues/370

**Comment by reek** [comment]
@M-111 
Ok, I'll fix ir, you could simply reopen the problem #1030

@SMed79 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
