### ISSUE TITLE
dl.free.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1222]
Hi,
`http://dl.free.fr/getfile.pl?file=/wTUtfyDn` sc: http://i.imgur.com/j1kziqi.png

```
@@||cpm1.affiz.net/tracking/ads_video$script,domain=pltform.springstreetads.com
@@||cpm1.affiz.net/tracking/ads_video/api/getinfos.php?$script,domain=pltform.springstreetads.com
```
Thanks!

**Comment by reek** [comment]
thanks, only the first rule is enough.

**Comment by SMed79** [comment]
> only the first rule is enough.

Redundancy :-P

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Please check https://forums.lanik.us/viewtopic.php?f=62&t=30560

**Comment by reek** [comment]
@SMed79
Already killed by AakList
