### ISSUE TITLE
sadeempc.com

### ISSUE THREAD

**Issue by ultrayer6** [reek/anti-adblock-killer#1223]
I know, I know... This site has already in list. But it must renew its protection.
"I've disabled my ad blocker." button works for five seconds and the site gives warning again.
 
http://www.sadeempc.com/
http://imgur.com/iFrBank
Google Chrome
Tampermonkey
AdBlock
EasyList + AakList

**Comment by ultrayer6** [comment]
If you want to see this alert, a bit of a wait when you enter the site. Just a few seconds.

**Comment by reek** [comment]
It's killed by AakScript, update it.

**Comment by Kalpit1** [comment]
I'm still getting this message.
Updated the filter just now.

Screenshot: http://imgur.com/Lf85AOJ
Browser: Firefox 45.0.1 (Windows 8.1)
Adblock Plus
Filters: Easylist, AakList(Anti-Adblock Killer)

**Comment by reek** [comment]
@Kalpit1 
https://github.com/reek/anti-adblock-killer#instruction
