### ISSUE TITLE
dlh.net

### ISSUE THREAD

**Issue by Degitalord** [reek/anti-adblock-killer#1224]
https://www.dlh.net/de/steam-keys.html

They don't allow me to see the Steam Keys when using UBlock Origin. I already using using ur script still no use. Pls fix

Message I say "We've detected that you're using some adblocking software. Please turn it off to get FREE keys!"

**Comment by SMed79** [comment]
try:
`@@||www.dlh.net/ads.html`

**Comment by reek** [comment]
@Degitalord 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
