### ISSUE TITLE
thailande-fr.com

### ISSUE THREAD

**Issue by Pascal30540** [reek/anti-adblock-killer#1225]
Hello,
![antiadblock](https://cloud.githubusercontent.com/assets/18102883/14066687/bd759d94-f450-11e5-890c-ee8fcd4d56d4.jpeg)
Firefox Kubuntu
GreaseMonkey
Anti-AdBlock Killer Reek

Thanks

**Comment by SMed79** [comment]
Hi, 
**thailande-fr.com** not thaïlande.fr

try:
`@@||thailande-fr.com^$generichide`
or 
`@@||thailande-fr.com^$elementhide`

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by thaizest** [comment]
Hello, for me it's does not block it. Did you add it ?

**Comment by SMed79** [comment]
@thaizest keep only one adblocker, disable all other blocking addons / extensions (antivirus plugin, [ghostery](https://www.technologyreview.com/s/516156/a-popular-ad-blocker-also-helps-the-ad-industry/), disconnect, adguard ...) and test again.

if still not work see report guide https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced
you can also submit an ABP issue report https://adblockplus.org/en/getting_started#false-negatives

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
