### ISSUE TITLE
8muses.com - NSFW

### ISSUE THREAD

**Issue by AgentRev** [reek/anti-adblock-killer#1226]
### NSFW - PORN

Here is a relatively SFW link for testing, refresh until you hit the adblock page:
https://www.8muses.com/picture/9194/akabur-comics/zombie-attack/1

This website blocks most of the pages roughly half of the time, displaying this neat little message:

![8muses anti-adblock](http://i.imgur.com/YmnidvS.png)

---
Windows 10
Firefox 45.0 x64
uBlock Origin 1.6.2
Anti-Adblock Killer | Reek 9.4

**Comment by MrSherlockHolmes** [comment]
AakList has already got a filter for this: `8muses.com#@#.adsbox` Try that, and then get AakList as well as AakScript again, maybe.

**Comment by reek** [comment]
@AgentRev 
Ok, I'll fix it, thanks

**Comment by AgentRev** [comment]
@MrSherlockHolmes: You're right, AakList seems to fix it... I thought I had it enabled, but for some reason it wasn't. Thanks.

**Comment by gregori** [comment]
Interesting.. testing here it doesn't seem to work.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by bourne9** [comment]
@reek, not fixed. Randomly still happens.

I have used this filter to stop from loading that thumbnail page - `||8muses.com/data/web/img/`
