### ISSUE TITLE
BFM TV

### ISSUE THREAD

**Issue by iscreamcoke** [reek/anti-adblock-killer#1227]
http://www.bfmtv.com/

###pane-content > .header-fixed > .container > .col-xs-12.center.margin-bottom.margin-topx2.padding.clearfix.bg-color-1.color-txt-1.geste

Thank you !

Chrome Mac OSX
TamperMonkey
Anti-AdBlock Killer Reek

**Comment by SMed79** [comment]
update your filter lists https://github.com/reek/anti-adblock-killer/issues/1209

**Comment by reek** [comment]
Already added, thanks
