### ISSUE TITLE
it.blastingnews.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1229]
Hi,
on `http://it.blastingnews.com/politica/2016/03/video/ecco-perche-donald-trump-non-sara-presidente-degli-stati-uniti-001923427.html`

sc: http://i.imgur.com/dkqzWWG.png

`@@||srs.blastingnews.com/js/adv/_compiled.js$script`
Thanks!

**Comment by reek** [comment]
Thanks !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
