### ISSUE TITLE
4shared.com

### ISSUE THREAD

**Issue by SystemRevolution** [reek/anti-adblock-killer#123]
http://www.4shared.com/get/oO0sFoWD/Audacity__Full_.html (or any download page)
http://snag.gy/c26Lp.jpg
Google Chrome
Tampermonkey
getadblock.com (AdBlock)
ireelevant

Hi!
I'm not here for send an issue, I'm here to send an script to solve the 1000 seconds countdown on 4shared, caused by use of any ad blocker.
The script is designed to work with unique dependence on jQuery (which is included on 4shared pages) and you can include in your script if you want.
The script is this:
`$("#downloadDelayTimeSec").text(20); // To show 20 on display.`
`$("#secondsLeft").val(20); // 4shared use this input-hidden for the count-down offuscation.`
`Events.fireEvent("change.seconds.left", 20); // Unknown purposes, but nessesary.`
`$("body").removeClass("jsBlockDetect"); // Hide "Disable AdBlodk" messages`

**Comment by reek** [comment]
HI,

thank you , I'll see if I can add

See you soon
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
