### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by Bluscream** [reek/anti-adblock-killer#1230]
http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html
![https://i.gyazo.com/67279eabd51e625ec74694c98ae8b42b.png](https://i.gyazo.com/67279eabd51e625ec74694c98ae8b42b.png)
Google Chrome: 49.0.2623.108 (Official Build) m (32-bit)
Tampermonkey: v4.0.5145
[AdblockPlus Dev Channel](https://chrome.google.com/webstore/detail/adblock-plus-development/ldcecbkkoecffmfljeihcmifjjdoepkn)
AakList + many others, including EasyList

Thanks !

![https://i.gyazo.com/9b8974da811b970013243e673047ef85.png](https://i.gyazo.com/9b8974da811b970013243e673047ef85.png)

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/817#issuecomment-162607404

**Comment by Bluscream** [comment]
Thanks but there is no such option in ABP.

![https://gyazo.com/6f1496a1fbc303315e1e5c2f71c5bed2](https://i.gyazo.com/6f1496a1fbc303315e1e5c2f71c5bed2.png)

**Comment by reek** [comment]
it's killed for me, see https://github.com/reek/anti-adblock-killer#help
