### ISSUE TITLE
iptvcanales.com

### ISSUE THREAD

**Issue by sigtus** [reek/anti-adblock-killer#1231]
Webpage: http://iptvcanales.com/
Screenshot: https://i.imgur.com/bvBOcrq.png
Browser: Firefox 45.0.1
Script manager: Greasemonkey 3.7
Adblocker: uBlock Origin 1.6.6
Filterlists: AAK, EasyPrivacy, Adguard, Peter Lowe, Fanboy, Malware Domain List, Anti Third Party Social, Annoyance List, Dan Pollock, iplogger, uBlock+

**Comment by sigtus** [comment]
Seems like the solution might be this filter:
`iptvcanales.com#@#.afs_ads`
It worked like a charm.

**Comment by reek** [comment]
Ok, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
