### ISSUE TITLE
btaia.com

### ISSUE THREAD

**Issue by thelastfantasy** [reek/anti-adblock-killer#1233]
Sample url:
http://www.btaia.com/magnet/detail/hash/6D2D94550F36856F7578EBB6678C0ADBE68AC1F4
![](http://pic.ffsky.net/images/2016/03/28/075d249579d4452bb2e210bd1899c1dd.png)

**Comment by TraderStf** [comment]
block: (note there is no dot after www) then empty cache!
http://creative.wwwpromoter.com
mediaessence.net
cdn.directrev.com

**Comment by thelastfantasy** [comment]
how to block? in uBlock Origin or the hosts file or somewhere?

**Comment by thelastfantasy** [comment]
It seems it's my fault, I added wrong rules into uBlock Origin,
`@@||http://www.btaia.com/*.js$script,domain=www.btaia.com`
Now it's deleted and everything is ok.

**Comment by reek** [comment]
I'll kill it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
