### ISSUE TITLE
01net.com

### ISSUE THREAD

**Issue by mswebmaster** [reek/anti-adblock-killer#1235]
Hi,

http://www.01net.com/

![01netablck](https://cloud.githubusercontent.com/assets/5772030/14086855/8cf0592a-f527-11e5-9e42-dd5c1c9cba2d.png)

Chromium v49
Tampermonkey
Adblock Plus
EasyList + AakList

This filter worked for me : `01net.com##.geste`

**Comment by SMed79** [comment]
Salut, 
`@@||01net.com/ressources/img/header/advertising.png`
ou
`bfmtv.com##.geste`

**Comment by reek** [comment]
@SMed79 
Thanks

@mswebmaster 
Ok, Ill kill, it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
