### ISSUE TITLE
freevaluator.com

### ISSUE THREAD

**Issue by FatKiwi** [reek/anti-adblock-killer#1236]
https://www.freevaluator.com/domain-name-generator

[caused by https://www.freevaluator.com/components/com_freevaluator/assets/js/check.js]

Screenshot: http://imgur.com/OHGihVf

TamperMonkey + Chrome
Greasemonkey + Firefox

**Comment by MrSherlockHolmes** [comment]
Try: `@@freevaluator.com/components/com_freevaluator/assets/js/check.js`

**Comment by SMed79** [comment]
`||freevaluator.com^*/js/check.js`

**Comment by reek** [comment]
@SMed79 
Thanks

@FatKiwi 
Ok, I'll kill it, thanks
:

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/eaf4d7246403

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
