### ISSUE TITLE
Stream-Foot.tv

### ISSUE THREAD

**Issue by Boeak** [reek/anti-adblock-killer#1237]
http://www.stream-foot.tv/

Le message anti-adblock apparait aléatoirement sur le lecteur vidéo.

Firefox 45

Ublock 1.6.6

Filtre EasyList + Liste FR‎ + Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by reek** [comment]
Please add screenshot and channel url, thanks

**Comment by Boeak** [comment]
http://www.zupimages.net/viewer.php?id=16/13/84pz.png

**Comment by reek** [comment]
Already killed by AakScript, see instruction
