### ISSUE TITLE
anisubsia.com

### ISSUE THREAD

**Issue by exodius48** [reek/anti-adblock-killer#1240]
http://anisubsia.com/
http://i.imgur.com/FA8MXwd.png
Mozilla Firefox
Greasemonkey
uBlock Origin
uBlock Filter, Adblock Warning Removal List‎, Anti-Adblock Killer | Reek‎, EasyList‎, Peter Lowe’s Ad server, Malvertising Filter, etc.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by exodius48** [comment]
@reek Hi, could you kill fuckadblock.js?
For example this link https://userscloud.com/cuirizstsqra
When i click "download (4.1mb)" , it redirects to 

data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD53aW5kb3cubG9jYXRpb249Imh0dHBzOi8vdXNlcnNjbG91ZC5jb20vY3Vpcml6c3RzcXJhIjs8L3NjcmlwdD48L2JvZHk+PC9odG1sPg==

Then i check, it has command script 

>  <script>
        //var fuckAdBlock = false;
		function adBlockDetected() {			 
			 //Have ad block
			 $$('btn_download').disabled=true;$$('btn_download').style.display='none';
			 alert("You must disable AdBlock to start the Free download!");
			 //var alert_content;
			 ///document.getElementById("add_text").innerHTML = alert_content;//"You must disable AdBlock and refresh to start Free download!";	
		}
		function adBlockNotDetected() {
			 //Do not have ad block
		}
</script>
<script src="https://userscloud.com/fuckadblock.js"></script>
<script>
     // fuckAdBlock = new FuckAdBlock();					
	  if(typeof fuckAdBlock === 'undefined') {
			adBlockDetected();
      } 

</script> 

That site does not have pop up to disable adblock.

**Comment by reek** [comment]
@exodius48 
AakScript already kill Fab

**Comment by reek** [comment]
@exodius48 
I know uBO makes a Fab lock, trying to authorize

**Comment by exodius48** [comment]
@reek so this is caused uBO can't handle AAK Script?

**Comment by reek** [comment]
I just tested and I can download the file without any problem with Chrome & uBlock Origin.& Aak

**Comment by exodius48** [comment]
Its strange, i still can't download with firefox also on my chrome too, always redirect to on 1st time

data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD53aW5kb3cubG9jYXRpb249Imh0dHBzOi8vdXNlcnNjbG91ZC5jb20vY3Vpcml6c3RzcXJhIjs8L3NjcmlwdD48L2JvZHk+PC9odG1sPg==

After redirect to it, i can download easily. So where is the problem?

**Comment by reek** [comment]
To kill popunder report it to EasyList

This rule kill it, but only with Firefox + uBo
<code>userscloud.com##script:contains(eval(function(p,a,c,k,e,d))</code>

**Comment by exodius48** [comment]
Wow,, that rule works great bro. 
I'll report it, now waiting for anisubsia killed by you. :laughing:

**Comment by reek** [comment]
Rule for anisubasia
<code>anisubsia.com###de13</code>

**Comment by exodius48** [comment]
You're very fast.. hats off to you. :smile: 
It works, please include it on next AAK update.

**Comment by Reoldyk** [comment]
@reek   sorry if I come join this conversation, but how you find this rule.
`userscloud.com##script:contains(eval(function(p,a,c,k,e,d))`

because solidfiles.com have same problem.

data:text/html;base64,PGh0bWw+PGJvZHk+PHNjcmlwdD53aW5kb3cubG9jYXRpb249Imh0dHA6Ly93d3cuc29saWRmaWxlcy5jb20vdi9NckducHhBajR3WnpaIjs8L3NjcmlwdD48L2JvZHk+PC9odG1sPg==
http://www.solidfiles.com/v/MrGnpxAj4wZzZ

sorry for my bad english.

**Comment by reek** [comment]
@exodius48 
Of course

@Reoldyk 
Try it, but only with Firefox + uBO
solidfiles.com##script:contains(eval(function(p,a,c,k,e,d))

**Comment by Reoldyk** [comment]
thanks, it work.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
