### ISSUE TITLE
firstrows.ru (rimladi.com)

### ISSUE THREAD

**Issue by WangChristopherS** [reek/anti-adblock-killer#1243]
http://firstrows.ru/basketball/washington-wizards-at-golden-state-warriors-frs13016c?l=3494414495

![screen shot 2016-03-29 at 8 34 27 pm](https://cloud.githubusercontent.com/assets/18157533/14131218/06c6347e-f5ee-11e5-890e-c97fd2dfdc1e.png)
Please kill this on link above. It is pretty much prevalent First Row Sports and/or other variants. Thank you. Main website: http://firstrows.ru

**Comment by WangChristopherS** [comment]
http://firstrows.ru is the main link. Sorry for the confusion.

**Comment by WangChristopherS** [comment]
Screenshot: filesystem:chrome-extension://fdpohaocaechififmbbbbbknoalclacl/temporary/screencapture-firstrows-ru-basketball-washington-wizards-at-golden-state-warriors-frs13016c-1459308334072.png

**Comment by reek** [comment]
Hi,
Ok, Ill kill it, thanks.

**Comment by reek** [comment]
Related: https://greasyfork.org/forum/discussion/8975/firstrows-ru

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
