### ISSUE TITLE
tut.by

### ISSUE THREAD

**Issue by Onrut** [reek/anti-adblock-killer#1244]
tut.by

Opera 33.0
Tampermonkey beta
Adblock Plus
Adblock Warning Removal List + RuAdList+EasyList + AakList (Anti-Adblock Killer) + EasyList + Adware filters + Fanboy's Social Blocking List + I don't care about cookies + Malware Domains + Prebake - Filter Obtrusive Cookie Notices + Spam404

![anti-adblick](https://cloud.githubusercontent.com/assets/18121321/14133558/f01932b0-f658-11e5-8ff0-dcfd68e90a75.jpg)

**Comment by Onrut** [comment]
Window anti adblok appears periodically.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
