### ISSUE TITLE
scambiofile.info

### ISSUE THREAD

**Issue by ricki122** [reek/anti-adblock-killer#1246]
http://www.scambiofile.info/browse.php?cat=1
http://i.imgur.com/JG85Me7.png
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

P.S.: ad block is not detected on the main page (scambiofile.info) but it's detected as soon as you do a research on the website.

**Comment by reek** [comment]
Ok, I'll kill it, there is problem with their database, I'll try later

**Comment by ricki122** [comment]
Appreciate it, thanks :)

**Comment by maynak00** [comment]
**try with:**
`@@||scambiofile.info/js/ads.js$script`

**Comment by ricki122** [comment]
Any news on the website? It still detects the adblock.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ricki122** [comment]
Hey, just wanted to let you know that for some reason, the websites recognize adblock again now. (it was working after the update)

**Comment by X01X012013** [comment]
@ricki122 
Lock "iExist" to true. 
You can use my temporary solution until it is added to Aak: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by reek** [comment]
Ok, I'll fix it, thanks

**Comment by ricki122** [comment]
Thanks again :)

**Comment by mapx-** [comment]
add
@@||scambiofile.info/*ad$script

**Comment by reek** [comment]
done
