### ISSUE TITLE
www.fullstuff.net

### ISSUE THREAD

**Issue by p4pergoat** [reek/anti-adblock-killer#1247]
http://www.fullstuff.net/digidna-imazing-1-5-5-incl-patch-latest/
http://prntscr.com/alykwb
Google Chrome
uBlock Origin
My Filter lists: http://prntscr.com/alyl8c

Anti-Adblock is not triggered on the mainpage fullstuff.net, but only on the subpages for each individual program/apk/movie etc.

EDIT: It seems like my Anti-Adblock Killer does not even work at all (for any site). I have tried disabling all personal filters. Any idea why? I have tried with a different browser too.

**Comment by reek** [comment]
You must use TamperMonkey with AakScript, see instruction
