### ISSUE TITLE
robotcoingame.com

### ISSUE THREAD

**Issue by p4pergoat** [reek/anti-adblock-killer#1248]
http://www.robotcoingame.com (message appears)
http://www.robotcoingame.com/faucet (You still have to enter BTC address/email, click "Start" and then "Attack for the popup to trigger)

http://prntscr.com/am1xjb (this is for http://www.robotcoingame.com)
http://prntscr.com/am00zy (this is for http://www.robotcoingame.com/faucet)

Google Chrome
Tampermonkey
uBlock Origin

http://prntscr.com/am1vnk (Easylist + AakList + Adblock Warning Removal List + Peter Lowe's Ad server list + some others)

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
