### ISSUE TITLE
bmw-club.cz

### ISSUE THREAD

**Issue by Worldik** [reek/anti-adblock-killer#1251]
http://www.bmw-club.cz/
![](http://www.bmw-club.cz/graphics/navigation/adblock-disable.png)
Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
**try with:**
`bmw-club.cz#@#.reklama`

**Comment by Worldik** [comment]
Thank you @reek & @maynak00 :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
