### ISSUE TITLE
appdn.net

### ISSUE THREAD

**Issue by worldsdream** [reek/anti-adblock-killer#1252]
http://appdn.net/
http://i.imgur.com/kZvPSZs.png
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

in Firefox it works good

**Comment by worldsdream** [comment]
example: 
http://appdn.net/2016/03/supertab-2-0-1.html

scroll a bit down

**Comment by reek** [comment]
Hi,
I'll see it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
