### ISSUE TITLE
cbsnews.com

### ISSUE THREAD

**Issue by sirkan35** [reek/anti-adblock-killer#1253]
http://www.cbsnews.com/news/donald-trump-calls-brussels-a-hellhole/
http://i.imgur.com/5IpsFXi.png
Google Chrome
Tampermonkey
Adblock Plus
Adblock Warning Removal List, EasyList, AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Hi,

I'll try to kill it, can you test these rules
<pre>
@@||b.ifmnwi.club^$xmlhttprequest,image,domain=cbsnews.com
@@||adserver.adtechus.com/pubapi/3.0/$xmlhttprequest,domain=cbsnews.com
@@||pubads.g.doubleclick.net/gampad/ads$object-subrequest,domain=cbsnews.com
</pre>

**Comment by sirkan35** [comment]
Killed it, thanks!

**Comment by reek** [comment]
Good

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
