### ISSUE TITLE
foerderland.de

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1254]
Hi, 
on `http://www.foerderland.de/` sc: http://i.imgur.com/IxXrAWe.png
```
@@||foerderland.de^$generichide
||foerderland.de/*/sponsor
||foerderland.de/fileadmin/user_upload/coolstuff.jpg
```

https://forums.lanik.us/viewtopic.php?f=90&t=29458

Thanks!

**Comment by reek** [comment]
thanks
