### ISSUE TITLE
rockfile.eu

### ISSUE THREAD

**Issue by giampi75** [reek/anti-adblock-killer#1256]
Site: rockfile.eu
http://rockfile.eu/bxviw1gp3wps.html
uBlock origin
Cyberfox 45
Greasemonkey
Easylist+Aaklist

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by MrSherlockHolmes** [comment]
Would it just be to make a fake iframe, if you don't mind me asking?

**Comment by reek** [comment]
@MrSherlockHolmes 
that's what I planned to do :smile:

**Comment by maynak00** [comment]
@reek, I tested and no adblocker detected message from page (I can download. adblocker enabled)
http://rockfile.eu/bxviw1gp3wps.html
after waittime: http://*.rfservers.eu:182/d/*/rpds.s0br3n4t0r4L.BD.Dub.01.01.mp4

**Comment by giampi75** [comment]
I agree: yersteday I had un announcement "disable your ad blocker", 
today I didn't have. I don't know why.
Thanks for your attention. I will monitor the site

Best regards

G.M.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
