### ISSUE TITLE
file4go.net

### ISSUE THREAD

**Issue by Ronam22** [reek/anti-adblock-killer#1258]
"Disable adblock" message loads a few seconds after you try to download anything.
example link: http://www.file4go.net/r/16d7892849111737686c
Google Chrome
Tampermonkey
Adblock Plus
Easy List + Aak List

Could you please kill it?
Thanks in advance.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
