### ISSUE TITLE
nowdownload.ec

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#1259]
http://www.nowdownload.ec/dl/c03c751e7bea6
http://imgur.com/0ALckHF
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it

**Comment by maynak00** [comment]
**try with:**
`@@||nowdownload.ec/banner.php$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
