### ISSUE TITLE
next-episode.net

### ISSUE THREAD

**Issue by zmasterar** [reek/anti-adblock-killer#1262]
Hi,
on http://next-episode.net/ 
screenshot: http://i.imgur.com/8huWCnV.png (need to be logged in)
Browser: Mozilla Firefox
Script manager: Greasemonkey
Adblocker: Adblock Plus
Filterlists: EasyList + AakList

I was able to remove with the following filter
`next-episode.net##td[style="padding-left: 20px;padding-right: 10px;"]>div`
it's not the more robust filter, but it doesn't have classes or ids, and where there are ids, they are randomly generated.

**Comment by reek** [comment]
I have this message

![capture](https://cloud.githubusercontent.com/assets/3474011/14226335/d634aab2-f8df-11e5-980f-0c1584ee6bae.PNG)

**Comment by zmasterar** [comment]
In the home page when logged in? I just tried with chrome, same setup except tampermonkey, and i'm having the same popup

**Comment by reek** [comment]
For popup try this
<code>next-episode.net###rundown</code>

**Comment by zmasterar** [comment]
That didn't work for me

**Comment by reek** [comment]
I need more information
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
