### ISSUE TITLE
popmech.ru

### ISSUE THREAD

**Issue by TheFinalCut83** [reek/anti-adblock-killer#1263]
Main page "freezing" and refused to loading pages by scrolling down. 
![clipboard 1](https://cloud.githubusercontent.com/assets/16985985/14226931/b255a046-f8f9-11e5-9d75-a442b4892a88.jpg)
To reproduce: Firefox 46.0b6 (also Waterfox 44.0.3), latest stable uBO/ABP (it doesn't matter, bug appears in both cases), latest stable NoScript, latest Greasemonkey and latest Anti-Adblock Killer script. Either "temporarily allow all this page" in NoScript or disabling Greasemonkey (or Aak script itself) is help. It is odd, but in Palemoon 26.1.1 with Greasemonkey 1.15.1 (it is latest for PM due to older FF code) bug doesn't appear.

**Comment by reek** [comment]
remove NoScript

**Comment by TheFinalCut83** [comment]
I've foreseen this. On the Noscript forum said that is your script is to blame, you said that i must remove Noscript. That's ok, i actually blame no one. The problem isn't widespread and too small to dig into it. Sorry for the inconvenience, i think that topic may be closed.

**Comment by reek** [comment]
Removing NoScript does it solve your problem ?

**Comment by TheFinalCut83** [comment]
You are right, just disable Noscript resolves the problem, but disabling Aak when Noscript is enabled resolves it too. I'm not ready to sacrifice Noscript for that site, sorry =) I'll just allow scripts temporarily, i'm rarely read this site anyway.

**Comment by reek** [comment]
I added popmech.ru to the exclusion list, tell me if it works with both activated
https://gist.github.com/reek/dc234ea9687056bd99fe (click raw)

**Comment by TheFinalCut83** [comment]
I've manually added aakdev script from zip in Waterfox and yes, exclusion works fine!

**Comment by reek** [comment]
:smile: I will add to the next version

**Comment by TheFinalCut83** [comment]
Many thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
