### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by limewire** [reek/anti-adblock-killer#1266]
![https openload co embed uc3mpyhry1w](https://cloud.githubusercontent.com/assets/17796457/14231751/853f564e-f965-11e5-8c74-abe5f7c25bfc.png)

http://bit.ly/1RSEk3o

Chrome
Tampermonkey
Adblock
Aaklist + EasyList

Seems that EasyList are whitelisting a lot of websites.

**Comment by reek** [comment]
its killed for me, tested on Firefox and Chrome, see help

**Comment by SMed79** [comment]
@limewire You need also **AakScript** https://github.com/reek/anti-adblock-killer#step-3-userscript
Btw, why you post a short link **bit.ly** ?
