### ISSUE TITLE
thailande-fr.com

### ISSUE THREAD

**Issue by thaizest** [reek/anti-adblock-killer#1267]
Hello,
On this website it does not work.
Im on safari
Adblock+reeklist
tampermonkey

http://imgur.com/2pW2QUl

On forum lanik.us they suggest to block:
CODE: SELECT ALL
@@||thailande-fr.com^$generichide
But why this user script does not the job ? I think they simply use the most famous antiadblock script: http://blockadblock.com/adblocking/ 

thank you

**Comment by reek** [comment]
Duplicated: https://github.com/reek/anti-adblock-killer/issues/1225

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
