### ISSUE TITLE
hahasport.me

### ISSUE THREAD

**Issue by DelpheniX** [reek/anti-adblock-killer#1268]
http://hahasport.me/ (I watch football)
http://imgbox.com/OeLzBJsN (The warning doesn't appear on all streams)
Chrome
Tampermonkey 
uBlock Origin
EasyList+AakList

**Comment by reek** [comment]
add channel url, which appears warning

**Comment by DelpheniX** [comment]
the stream end after the match finish so its useless to get a url it would show nothing. Just wait for a match from main competition(liga,premier league,etc...) to start and you will see the message.

**Comment by reek** [comment]
i'm redirected to http://bets.thesportstream.com/wolfsburg-real-madrid/

**Comment by DelpheniX** [comment]
there are many streams for one match, some redirect to the site above or others that don't show the warning. You have to check other links on the page to see it.

**Comment by reek** [comment]
it's good I could detect, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
