### ISSUE TITLE
tusoft.org

### ISSUE THREAD

**Issue by BioBrayan** [reek/anti-adblock-killer#1270]
http://tusoft.org/
http://i.imgur.com/2sU9rgg.png
Google Chrome 49.0.2623.110
Tampermonkey 4.0.10
uBlock Origin 1.6.6
Anti-Adblock Killer
EasyList‎
Peter Lowe’s

totalmente bloqueada la página imposible de visualizar espero su ayuda de antemano gracias

**Comment by reek** [comment]
Hi,
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
