### ISSUE TITLE
www.larioja.com

### ISSUE THREAD

**Issue by gmilazzo** [reek/anti-adblock-killer#1277]
http://www.larioja.com/
http://imgur.com/4NnuwC3
Mozilla Firefox
Greasemonkey
Adblock Plus
Adblock Warning Removal List + EasyList + Filtros Nauscopicos + AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by gmilazzo** [comment]
Thank you very much!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
