### ISSUE TITLE
smashingmagazine.com

### ISSUE THREAD

**Issue by koboltzz** [reek/anti-adblock-killer#1278]
https://www.smashingmagazine.com/
http://abload.de/img/2016-04-06_19h08_001wkdg.png
Mozilla Firefox
Greasemonkey
ublock origin
EasyList + AakList

New method is growing: https://codepo8.github.io/detecting-adblock/

**Comment by reek** [comment]
Hi,
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
