### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1279]
I got this message when I surfed pornhub.com: "Loading ..."

This is the HTML output I wish you to investigate:

```
<html><head><script type="text/javascript"><!--
function leastFactor(n) {
 if (isNaN(n) || !isFinite(n)) return NaN;
 if (typeof phantom !== 'undefined') return 'phantom' if (typeof module !== 'undefined' && module.exports) return 'node' if (n==0) return 0;
 if (n%1 || n*n<2) return 1;
 if (n%2==0) return 2;
 if (n%3==0) return 3;
 if (n%5==0) return 5;
 var m=Math.sqrt(n);
 for (var i=7;i<=m;i+=30) {
  if (n%i==0)      return i;
  if (n%(i+4)==0)  return i+4;
  if (n%(i+6)==0)  return i+6;
  if (n%(i+10)==0) return i+10;
  if (n%(i+12)==0) return i+12;
  if (n%(i+16)==0) return i+16;
  if (n%(i+22)==0) return i+22;
  if (n%(i+24)==0) return i+24;
 }
 return n;
}
function go() {
 var p=1890904264395; var s=3073674874; var n;
if ((s >> 3) & 1) p+=/*
*13;
*/80161086*/*
else p-=
*/4;/*
p+= */else 	p-=/*
else p-=
*/58043909*	4;/*
else p-=
*/if ((s >> 10) & 1)p+=/* 120886108*
*/95643316*13;/*
*13;
*/else /*
*13;
*/p-=
183411229*
11;	if ((s >> 11) & 1)/*
*13;
*/p+=/* 120886108*
*/79792731*
12;/*
p+= */else p-=/*
p+= */92901218*	12;/*
else p-=
*/if ((s >> 8) & 1)	p+=/*
*13;
*/79115181*	11;	else 
p-=/*
*13;
*/59938616*/*
*13;
*/9;/* 120886108*
*/if ((s >> 6) & 1)	p+=	216668124*/*
p+= */9;/*
p+= */else /* 120886108*
*/p-=/*
else p-=
*/105237300*/* 120886108*
*/7;/*
p+= */ p-=5979037452;
 n=leastFactor(p);
{ document.cookie="RNKEY="+n+"*"+p/n+":"+s+":3345009889:1";
  document.location.reload(true); }
}
//--></script></head>
<body onload="go()">
Loading ...
</body>
</html>
```

**Comment by reek** [comment]
I have nothing, take screenshot

**Comment by flyingzebras** [comment]
Cannot you see the HTML that I posted above?

**Comment by reek** [comment]
No anti-adblock message

**Comment by wifiextender** [comment]
In order to view the wanted video without turning Javascript ON, do this:

![1](https://cloud.githubusercontent.com/assets/4725121/15275065/2a5f9030-1ac2-11e6-9362-68f792248cbb.png)

![2](https://cloud.githubusercontent.com/assets/4725121/15275067/2a667512-1ac2-11e6-9532-9c1a229a77dd.png)

![3](https://cloud.githubusercontent.com/assets/4725121/15275069/2a6e67ae-1ac2-11e6-9131-b9b5f5b5f404.png)

Only allow the video to be whitelisted, the html5 player that's built-in in the browser browser will take care of playing it
 
![4](https://cloud.githubusercontent.com/assets/4725121/15275066/2a6345f4-1ac2-11e6-8f6a-501a53c326b3.png)

Noscript options:

![5](https://cloud.githubusercontent.com/assets/4725121/15275068/2a6d7e52-1ac2-11e6-8b0a-9a3e5b5e3a3f.png)

**Comment by reek** [comment]
@flyingzebras 
Fixed by AakList

@wifiextender 
Thank you, but no need

**Comment by reek** [comment]
@flyingzebras 
it seems that if one uses uBO, the rule does not work, due to a rule of uBO.

**Comment by flyingzebras** [comment]
@reek I'm glad that you found the cause of this bug.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Xyncgas** [comment]
Also blocking pornhub's ad can be done on network level by routing the domain of the sources of those ads to a blackhole using DNS or some other methods
