### ISSUE TITLE
dz-android.com

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#1280]
Hi, Adblock message blocks the text content on the website above (screenshot)
Used link: http://www.dz-android.com/hightech-nvidia-devoile-son-nouveau-gpu-gp100-sous-larchitecture-pascal/
Firefox+Greasemonkey+Aak+Easylist
Thanks
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14330859/61941702-fc3a-11e5-9d8f-7bdf37293c93.png)

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
