### ISSUE TITLE
online.anidub.com Fail :(

### ISSUE THREAD

**Issue by despicere** [reek/anti-adblock-killer#1282]
In http://online.anidub.com on block ABP/uBO fail content, view only off blocker :(
Pls, need a script blocker defining adblok!

screenshot http://goo.gl/EqhCM9

**Comment by reek** [comment]
it's ok for me.

please give me
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by despicere** [comment]
sorry, problem in https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt

**Comment by reek** [comment]
Ok, I close
