### ISSUE TITLE
debrid.us

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1283]
Hi, 
anti adblock redirection on : 
```
http://debrid.us/
http://debrido.com/
http://getdebrid.com/
http://debridfast.com/
```
filter: 
`|http://$script,domain=debridfast.com|getdebrid.com|debrido.com|debrid.us`

https://github.com/reek/anti-adblock-killer/issues/447 https://github.com/reek/anti-adblock-killer/issues/769 https://github.com/reek/anti-adblock-killer/issues/1241

Thanks!

**Comment by reek** [comment]
thank you, but I have something else planned
