### ISSUE TITLE
nrj.fr

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#1286]
Hi, 
Adblock redirect page on nrj.fr (screenshot)
Used link: http://www.nrj.fr/webradios
Firefox 45+Ublock Origin+Greasemonkey+Easylist+Aak
Thanks
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14391536/770e417c-fdb4-11e5-9336-961ac7514a15.png)

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
