### ISSUE TITLE
tab spawned to allow once|always ..etc ... more time please

### ISSUE THREAD

**Issue by stiinky** [reek/anti-adblock-killer#1289]
Please give options to increase the time of the prompt before the tab self closes.

Additionally provide somewhere on tampermonkey dashboard to interact with approvals/whitelist after spawned tab closes.  

Chromium 48.0.2564.103 (64-bit)
tampermonkey 4.0.10
OSX 10.9.5

**Comment by reek** [comment]
I do not see what you mean, can you make a screenshot

**Comment by maynak00** [comment]
Please try:
Tampermonkey settings>Security>@connect mode: Select "Off" or "Disabled"

https://forum.tampermonkey.net/viewtopic.php?f=17&t=1725&p=5350#p5345
https://forum.tampermonkey.net/viewtopic.php?t=1594

**Comment by reek** [comment]
I'll add the metablock below to fix it
<code>// @connect *</code>

https://greasyfork.org/fr/forum/discussion/7853/devs-tampermonkeys-upcoming-support-of-connect-may-break-scripts-with-gm-xmlhttprequest

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
