### ISSUE TITLE
workupload.com

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#1290]
Apparently they recently added add block detection. 
Example: http://workupload.com/file/zSWf2jy

**Comment by reek** [comment]
Hi, Ok I'll kill it

**Comment by maynak00** [comment]
**try with:**
`workupload.com#@#.adBlock`

**Comment by xyzzy-xyzzy** [comment]
That appears to work.  Thanks.

Reek are you still going to handle this?  Should I close this issue now?

**Comment by reek** [comment]
@xyzzy-xyzzy 
I would close when I would update

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
