### ISSUE TITLE
bachtrack.com

### ISSUE THREAD

**Issue by JonasInNYC** [reek/anti-adblock-killer#1291]
https://bachtrack.com/notice-using-ad-blocker?destination=%2F
Safari
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**
`bachtrack.com#@##adblock1`
`bachtrack.com#@##adblock2`
`bachtrack.com#@##adblock4`
**or**
`bachtrack.com##.ad-takeover-surround`
`bachtrack.com##.ad-takeover-vis.ad-takeover-overlay`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
