### ISSUE TITLE
themarker.com / haaretz.co.il

### ISSUE THREAD

**Issue by benibraz** [reek/anti-adblock-killer#1292]
http://www.themarker.com/markets/1.2909720

The link redirects to this:
http://www.themarker.com/hblocked?returnTo=http%3A%2F%2Fwww.themarker.com%2Fmarkets%2F1.2909720

![screenshot 2016-04-10 15 53 57](https://cloud.githubusercontent.com/assets/18378816/14410304/e7b9e0c6-ff34-11e5-8d72-6450649170b0.png)

occurs for each article I open on site.
Thanks.

**Comment by reek** [comment]
HI,
No detected for me, but can you add test this rule
<code>||themarker.com^*adblockutil.js$script</code>

https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by benibraz** [comment]
I checked it out, it blocks only from my country's ISPs, it's not detected for me using Hola!
I added the rule and still not working.

Thanks anyway for your work!

**Comment by reek** [comment]
what is your country ?

**Comment by benibraz** [comment]
Israel

**Comment by ilanerukh** [comment]
same in www.haaretz.co.il

**Comment by reek** [comment]
for themarker.com
<pre>
@@||tpc.googlesyndication.com/simgad/*$xmlhttprequest,domain=themarker.com
</pre>

or 

<pre>
||themarker.com/tm/js/resp/header_scripts/internal/util/z_adblockutil.js$script,domain=themarker.com
||odb.outbrain.com/utils/get?*adblck=$script,domain=themarker.com
</pre>

or both

**Comment by ilanerukh** [comment]
Works on themarker, doesn't work on Haaretz.

**Comment by reek** [comment]
what is the filter works ?

**Comment by ilanerukh** [comment]
After removing the filters themarker still works fine and not detected for me. in haaretz.co.il I still get blocked with and without the filters.

**Comment by reek** [comment]
try this beta (click raw)
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by ilanerukh** [comment]
Works great for me. Thanks.

**Comment by reek** [comment]
:smiley:

**Comment by benibraz** [comment]
Yes, works perfectly. 

Thank you!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Adiel-Sharabi** [comment]
Still loading the ad-block page after few pages (second for me) 
At url - http://www.themarker.com/wallstreet/1.4108590 
Thanks!
