### ISSUE TITLE
sc2casts.com

### ISSUE THREAD

**Issue by J913B** [reek/anti-adblock-killer#1294]
Hello! Sc2casts.com has changed their code yet again to display this popup:

"You are getting this popup because you're using Adblock (or something similar)
Not liking ads and prefering a cleaner experience is very understandable, but advertising helps fund the support and development of SC2Casts and keeps it running and daily updated.

For ads-free experience, please check out SC2Casts Premium - for the price of 2 movie tickets a year, this will remove the ads and will give you awesome new functionality which will only get better (and more expensive for new members). Already Premium? Click here to sign in.

Another option is to simply whitelist SC2Casts in your Adblock - see how here. Make sure you whitelist in all your ad-blocking extensions. Ads here are minimal, non-obtrusive and safe.

Thank you!"

Found this script to combat it: http://www.codejuggle.dj/how-to-fight-anti-adblock/ but I'm not sure how to add it to my filters. Thanks!

**Comment by reek** [comment]
see: https://github.com/reek/anti-adblock-killer/issues/1232#issuecomment-208010538

**Comment by J913B** [comment]
Sorry for the duplicate! That worked. Thank you.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
