### ISSUE TITLE
superanimes.com

### ISSUE THREAD

**Issue by MaxLucio528** [reek/anti-adblock-killer#1295]
Can you guys make this site don´t block the videos because of adblock? I use the Anti-Adblock Killer and it works, but on this site it doesn´t work, so please do this for me and this will help a lot of brazilians too.
Link: http://www.superanimes.com/koutetsujou-no-kabaneri/episodio-1
Browser: Google Chrome
Script Manager: Tampermonkey
Adblocker: Adblock
Filterlist: My filterlists have AakList (Anti-Adblock Killer)
Image:
![gfgfgfg](https://cloud.githubusercontent.com/assets/18402849/14448058/bb4f95d2-003b-11e6-9131-5f4e652eac4a.PNG)

**Comment by reek** [comment]
Ok, but add this https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by maynak00** [comment]
**try with:**
`||superanimes.com/img/alert-video.jpg`
`superanimes.com##.video-alerta`

**Comment by reek** [comment]
@MaxLucio528 
Ok, I'll kill it

@maynak00 
Not good because <code>superanimes.com##.video-alerta</code> conflicts with <code>@@||superanimes.com^$elemhide</code>, I'll kill it with AakScript

**Comment by MaxLucio528** [comment]
Thank you.

**Comment by MaxLucio528** [comment]
@reek 
Something wrong happened... The Anti-Adblocker started to work again in my browser, do you know why? I made a test to see if it was working, but after I made the test (The test was disabling the Anti-Adblock Killer and then enable it again) the Anti-Adblocker appeared again.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
