### ISSUE TITLE
mp3skull.is

### ISSUE THREAD

**Issue by oFAYYo** [reek/anti-adblock-killer#1296]
https://mp3skull.is/
http://imgur.com/2BmuefU
Mozilla Firefox
Greasemonkey
Adblock Plus
Liste FR + EasyList

**Comment by reek** [comment]
Hi,
Ok I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**
`||mp3skull.is/*/FAB.js$script`
or
`mp3skull.is###fab-over`
`mp3skull.is###fab`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
