### ISSUE TITLE
marketwatch.com

### ISSUE THREAD

**Issue by theclamman** [reek/anti-adblock-killer#1297]
http://www.marketwatch.com/
http://imgbox.com/znxt4aXo
Mozilla Firefox
Greasymonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,
No detected

**Comment by jgenender** [comment]
Noe... EasyList update isn't doing it.  Its setting an activation to a lightbox div.

<div style="overflow-y:hidden;" class="lightbox active">

The "active" is what shows it.

Looks like code is in http://sts3.wsj.net/bucket-a/maggie/static/js/scripts-23000635fa.min.js

**Comment by jgenender** [comment]
This fixes it, although the first line is overkill and the code is probably a more elegant approach.  Add this to your custom/Myfilters:

marketwatch.com##.lightbox.active
marketwatch.com##.container--bannerAd

**Comment by reek** [comment]
I think I found a solution

**Comment by jgenender** [comment]
It appears that there are 4 UI items that can happen and they appear to happen when you restart your browser.  The code seems to support that fact.  After much hacking, these filters seems to do it all for now without overkill:

```
marketwatch.com##.container--bannerAd
marketwatch.com##.col--ad
marketwatch.com##div.lightbox.active[style^="overflow-y:hidden"]
marketwatch.com##div[style^="position:absolute;top:0;left:0;right:0;padding-bottom:10px;background:#f7f7f7;z-index:100"]
marketwatch.com##div[style^="position:fixed;bottom:0;left:0;right:0;padding-bottom:10px;background:#f7f7f7;border-top:solid 1px #dedde2;z-index:1000;"]
marketwatch.com##div[style^="overflow-y:hidden;font-size:14px;line-height:21px;z-index:10020;background-color:rgba(45,45,50,0.6);width:100%;height:100%;position:fixed;top:0;left:0;color:white;"]

```

Again, I guess the Aakscript would be a more elegant solution, but hacking around with it, I was unable to make it fully work without the adblock screen (the full one) flashing.  I need to see how reek does it. ;-)  Until then, the above seems to do it for now.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by jgenender** [comment]
Reek... the cookie set works for the most part but you need to add this to the filters to make it complete:
`marketwatch.com##.container--bannerAd`
There is still an empty ad banner at the top and the above fixes it.

**Comment by reek** [comment]
try this
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by jgenender** [comment]
So far so good.. this one looks like it works...

**Comment by theclamman** [comment]
This is working great so far, thank you!
