### ISSUE TITLE
www.litv.tv

### ISSUE THREAD

**Issue by ch50329** [reek/anti-adblock-killer#1299]
https://www.litv.tv/vod/drama/content.do?id=VOD00039000
https://imgur.com/ztvd4Da
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList

**Comment by reek** [comment]
Hi,
Ok, I'll try to kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by 1298348** [comment]
hi, 
Anti adblock for this site failed again 
can you fix it up ! Thanks a lot!!

**Comment by reek** [comment]
sorry can't fix it
