### ISSUE TITLE
kbb.com

### ISSUE THREAD

**Issue by freiermuth** [reek/anti-adblock-killer#1300]
http://www.kbb.com/
http://imgur.com/hefJbpK
Google Chrome
Tampermonkey
Adblock Plus
EasyList, AakList

**Comment by maynak00** [comment]
Static filter @@||kbb.com/js/advert.js found in: EasyList
no antiadblock message for my test.

**Comment by SMed79** [comment]
No issue http://i.imgur.com/HuzfWdx.png

**Comment by reek** [comment]
@freiermuth 
No detected, see https://github.com/reek/anti-adblock-killer#help

**Comment by M0eman** [comment]
http://www.kbb.com/
http://imgur.com/wxNycSO
Safari
Tampermonkey
Adblock Plus
AakList, EasyList

**Comment by reek** [comment]
@M0eman 
I still have no messages /:

**Comment by derenma** [comment]
Not fully tested for site functionality!!!  This contains the call-back timers for the advert .js, at least.

My ABP Filter:
kbb.com/combine/siteJsTop/*

**Comment by M0eman** [comment]
Disabled Adblock.  
Enabled (and applied AAK, EasyList on) uBlock.

It works! 
Thank you all.

**Comment by SMed79** [comment]
@M0eman Not use multiple adblockers at the same time.

**Comment by M0eman** [comment]
**@SMed79**  Multiple adblockers were not used at the same time.  Edited post to read "Installed uBlock".  AdBlock does not work for Kbb on my system, but uBlock does.
