### ISSUE TITLE
cnbeta.com

### ISSUE THREAD

**Issue by kcschan** [reek/anti-adblock-killer#1301]
For example:
http://www.cnbeta.com/articles/491855.htm

anti-adblock-killer is partially working except several elements:

![a](https://cloud.githubusercontent.com/assets/7920206/14467640/dad4e078-010e-11e6-8531-7358db7115af.JPG)
![b](https://cloud.githubusercontent.com/assets/7920206/14467647/df1a6680-010e-11e6-91b4-3cb6c304f80b.JPG)

**Comment by kcschan** [comment]
configuration:

Google Chrome stable 49
ublock origin (easylist + easylist China + Aak list)
Aak on TamperMonkey

**Comment by kcschan** [comment]
The content currently gets hidden with Aak on, or script blocked.

**Comment by reek** [comment]
I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
