### ISSUE TITLE
sheekyforums.com

### ISSUE THREAD

**Issue by jasuka** [reek/anti-adblock-killer#1302]
http://sheekyforums.com/
http://imgur.com/RyqIDqt
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**

**Comment by reek** [comment]
@jasuka 
Ok, I'll kill it, thanks

@maynak00 
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
