### ISSUE TITLE
rockfile.eu

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#1303]
Hi, Anti Adblock used on http://rockfile.eu (Screenshot)
Tested link: http://rockfile.eu/lglwnnhaphxz.html
Firefox 45+Greasemonkey+Ublock Origin+Aak+Easylist
Thanks.
![sans titre](https://cloud.githubusercontent.com/assets/10789454/14468592/40fdeae8-00d8-11e6-9d4b-b19d87f760c7.png)

**Comment by SMed79** [comment]
Hi, 
add: 
```
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=rockfile.eu
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=rockfile.eu
```

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1256

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
