### ISSUE TITLE
animmex.co

### ISSUE THREAD

**Issue by Xeraser** [reek/anti-adblock-killer#1304]
https://www.animmex.co/
They think they can stop us.. https://i.gyazo.com/d865ed12f276a6e67bc4f164c8f10c00.png
Seriously tho, if I'm not gonna be able to watch Top Gear then I'm gonna be f*cking mad.

**Comment by SMed79** [comment]
Hello, 

add: 
`@@||animmex.co^$generichide`
or
`@@||animmex.co^$elemhide`

**Comment by Xeraser** [comment]
How and where do I add them, exactly ? Never done this before, sorry.

**Comment by SMed79** [comment]
Adblock plus http://i.imgur.com/1N4Nhat.gif
Adblock http://i.imgur.com/n13Auf2.gif

**Comment by Xeraser** [comment]
Thanks a lot. May I ask what you use to record Gifs ? I doubt those are from Gyazo.

**Comment by maynak00** [comment]
@SMed79 thanks for the filters.
for ublock origin tested with @@||animmex.co^$elemhide
do you have a solution for?:
"Place your ad here
Loading..."
###MarketGidPreloadC49234
###MarketGidScriptRootC49234
already blocked completely: mgid.com

**Comment by SMed79** [comment]
@Xeraser 
> I tried both and they don't work.

Clear cache and cookie and test, if not work disable all other extensions, keep only your adblocker then test again.

> what you use to record Gifs ?

- gtk-recordMyDesktop http://recordmydesktop.sourceforge.net/
- Convert OGV to GIF `$ ffmpeg -i input.ogv -pix_fmt rgb24 output.gif`
- Bart's Bash Script Uploader http://imgur.com/tools

@maynak00 
`animmex.co##DIV[id^="MarketGid"]`

**Comment by reek** [comment]
@SMed79 
@maynak00 
thanks, but I'll opt for another solution

@Xeraser 
Ok, I'll kill it, thanks

**Comment by Xeraser** [comment]
Just wanted to say that it works now, thanks again @SMed79

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by shoffing** [comment]
Doesn't work anymore...is it possible to get a workaround?

**Comment by SMed79** [comment]
try (_temporary solution_):
```
@@|https://$image,domain=animmex.co
@@||animmex.co^$generichide
```

**Comment by shoffing** [comment]
That worked! Thanks :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Mirror sites:
```
animmex.co
animmex.com
animmex.net
animmex.org
animmex.pw
animmex.website
animmex.space
finalelite.com
onitube.com
```

**Comment by reek** [comment]
@SMed79 
thanks, but already killed generically by AakScript

**Comment by UnknownKings** [comment]
Using ublock origin, still pops up.

**Comment by reek** [comment]
@UnknownKings 
Killed by AakScript, see instruction

**Comment by UnknownKings** [comment]
@reek 
Not following, Im using AakScript on ublock origin and it still pops up.

**Comment by SMed79** [comment]
@UnknownKings Disable others installed extensions and test again.

**Comment by UnknownKings** [comment]
@SMed79 Still not working.

**Comment by SMed79** [comment]
Try a test: use [firefox portable](http://portableapps.com/apps/internet/firefox_portable), follow AaK [instructions](https://github.com/reek/anti-adblock-killer#instruction) and test again.

**Comment by reek** [comment]
@UnknownKings 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced
