### ISSUE TITLE
While this is not an issue, please take a look at this new anti-adblock.

### ISSUE THREAD

**Issue by Xeraser** [reek/anti-adblock-killer#1306]
It's called "Block Adblock" (how original) and it's from some attention-seeking company called Futuremedia. (again, how original) cause a few sites recently started using it. Here's the link, take a look at the script and see if you can somehow bypass it. http://blockadblock.com/

And for the love of god or whoever, do NOT look at the news section unless you want to cringe HARD.

**Comment by reek** [comment]
Hi,
I am already aware, but I have to treat each case.
Do you know of sites that use "Block Adblock" ?

**Comment by Watilin** [comment]
This is interesting indeed. Looks to be quite the challenge.

At first it looks we could manage to block their inline script rather easily using `beforescriptexecute`. The hard part begins with browsers that ~~are stupid~~ don’t support this event.

Here is a semi-deobfuscated version of their inline script with default settings. Basically, this is the result of the `(p, a, c, k, e, r)` function, and what’s passed to `eval`. I added comments to the intersting points:
https://gist.github.com/Watilin/af75e0a2e82a2efb384bde9c7b41dec8

So we see several things:

1. The script uses randomly-generated variable names, which seems at first a good strategy against static analysis. But when we look closer…

2. It’s inline and uses no wrapper functions, thus all of its variables fall in the `window` context. This includes fixed-name variables such as `aDefOne` and `aDefTwo`, and also `c1` and `c2`– which are in a lower scope and might be global by accident (the original instruction is `var n = c1 = c2 = 0;` which actually doesn’t declare `c1` nor `c2`).

3. It uses a timer. We can still, at last resort, rely on a good old “kill all timers in the page”, but there are good chances that it would break other functionalities. We better choose another plan.

4. It uses `eval`. We could hook all calls to `eval` and perform static analysis against arguments passed to it. But this might cause unneeded overhead, as many sites use packer or isogram functions for genuine purposes.

5. It adds an object to `window` that has an unpredictible name, yet contains a function with a fixed name, `bab`. We are able to detect this and override it. This is, in my opinion, the cleaner way at the moment, but it may also be easy for BlockAdblock devs to eliminate this flaw.


Here are the tests I did on the `blockadblock.com` domain:
https://gist.github.com/Watilin/6af887579e9d9a64bf64edff2074b034

**Comment by Xeraser** [comment]
What's more interesting is just how far this company's willing to go to force us to disable our Adblockers. I posted this issue on Reddit ( r/adblock ) a few days ago and some guy said that they have a right to make us disable our Adblocks. Why was he even there ? Who knows.

Anyway, I remember seeing some british news and some hackintosh-related site using something very similar 2 months ago or so but I can't remember the names, sorry.

**Comment by Watilin** [comment]
Well, one can expect to find a reasonable amount of trolls on /r/adblock.

**Comment by Xeraser** [comment]
True, true. I think that sites DO have a right to ASK US to disable our Adblockers IF and only IF their content is actually good. I'd disable my Adblock on a Youtube channel I enjoy (and that actually deserves the money) rather than some guy's stupid blog/site I know nothing about and I'm most likely never gonna use again.

**Comment by Watilin** [comment]
That’s exactly what I read some times ago, a french blogger who said “thank you to block us from accessing your content, now we can realize it’s not worth it”. [The link](http://www.canardpc.com/bloquez-moi-bloquez-moi.html) if you can read french.

**Comment by Xeraser** [comment]
I'd read it if I could. I studied French in middle school but I'm afraid I forgot everything I learned as soon as I got into high school. But yeah, anyway.. Sites that make you pay to hide ads (animmex, nexusmods and so on) are even worse. Animmex asks for 15 dollars a month (or year, can't be bothered to check) and 50 dollars if you want a lifetime membership. Just.. no. No. Absolutely NO. And I hate those banners that say stuff like "hey if you don't disable your adblocker then the site's gonna die/nobody's gonna be able to pay for it". If those were actually true then the site would already be DEAD. (See nexusmods, gamedebate and such)

The worst one I've seen so far is something like "hey if you don't disable your adblocker then our cats are gonna starve to death"

That's the worst thing I've ever heard. It almost made me disable adblock. Almost. I realized that unless they don't care about their cats dying.. they're gonna feed them anyway. 

.. at least they aren't as bad as TV ad breaks.  This IS just a rant but I'm really pissed off to be honest.

**Comment by Watilin** [comment]
I totally agree, and this is why I put so much effort into finding workarounds. That, and because I have fun doing so :P

**Comment by tekdoc** [comment]
Here's a site that's using BlockAdBlock:

[http://www.pizzamaking.com/forum/](url)

**Comment by Watilin** [comment]
I’m glad to confirm that all 4 tests from my gist successfully worked on pizzamaking.com :)
You may copy it for your own use as soon as right now, or wait for Reek to pass by here and to add it to the next version of Anti Adblock Killer.

**Comment by reek** [comment]
@Watilin 
Une règle existe déjà dans AakScript, oû j'ai hacké la fonction <code>setTimeout</code> mais comme je crains que cela puisse causer des problèmes sur certains sites, je l'applique seulement aux site utilisant <code>BlockAdBlock</code>
https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L4158

@tekdoc 
Thanks, I'll kill it.

**Comment by Watilin** [comment]
@Reek C’est dommage de répertorier à la main les sites utilisant BlockAdblock, ça rend ton script moins efficace à l’échelle du Web tout entier. Il faut attendre que quelqu’un signale le site, et les gens ne pensent pas toujours à signaler, ne savent pas comment faire, ou ont juste la flemme.

Je pense que tu peux appliquer ta règle à tous les sites avec un risque vraiment minimal. C’est peu probable qu’une fonction autre que BAB utilise la chaîne `'bab_elementid'`. Au pire, tu peux rajouter d’autres tests pour diminuer encore le risque ;)

**Comment by reek** [comment]
@Watilin 
@Xeraser 
I found a generic solution that will kill <code>BlockAdblock</code> :smile:

**Comment by sirib** [comment]
Hi reek, what is the solution.
can you check that with abcmalayalam.com

**Comment by reek** [comment]
@sirib 
I will publish a new version in a few minutes

**Comment by reek** [comment]
Done !
