### ISSUE TITLE
srnk.co

### ISSUE THREAD

**Issue by evetaku** [reek/anti-adblock-killer#1308]
http://srnk.co/i/kuEGV

http://i.imgur.com/gVDqqRY.png
Mozilla Firefox 45.0.1
greasemonkey 3.7
uBlock Origin 1.6.8 + adblock Plus 2.7.2
EasyList‎

Thanks you

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by SMed79** [comment]
Duplicate https://github.com/reek/anti-adblock-killer/issues/944 https://github.com/reek/anti-adblock-killer/issues/951 https://github.com/reek/anti-adblock-killer/issues/1178

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
