### ISSUE TITLE
hdonline.vn

### ISSUE THREAD

**Issue by hongnv55** [reek/anti-adblock-killer#131]
http://hdonline.vn
https://lh5.googleusercontent.com/-iefs2KlGQJ4/VLjWVmfme6I/AAAAAAABDSI/KSncBeICGLw/s0/Screen%252520Shot%2525202015-01-16%252520at%2525204.png
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
HI,

I do not Understand Vietnamese and I do not see the message of warning

**Comment by reek** [comment]
Nolution for the moment.
