### ISSUE TITLE
formel1.de

### ISSUE THREAD

**Issue by alexx1982** [reek/anti-adblock-killer#1310]
http://www.formel1.de/
http://imgur.com/4K9GAyV
Mozilla Firefox
Greasemonkey
Adblock Plus
AakList + EasyList + Malware Domains + Spam404 + Liste AR + Adblock Warning Removal List

This website loads without advertisements first... then after a few seconds the ads are placed like shown on the screenshots. Latest Adblock Plus + Filters used.
Edit: it seems to make a difference in Firefox between "Private Mode" and normal mode. On normal mode the ads are sometimes not displayed. On "Private Mode" the ads are always displayed.

**Comment by SMed79** [comment]
Hi, 
subscribe to **EasyList Germany** and test again https://adblockplus.org/subscriptions
report unblocked adverts on easylist forum https://forums.lanik.us/viewforum.php?f=90

**Comment by alexx1982** [comment]
Does not work on "private mode". The ads are still shown after 1-2 seconds. I was already using EasyList Germany but my list was too long to mention all individual filters. So I now uploaded a photo with all the filters I use:

Here is my complete filter list: (sorry should have done this earlier)...
http://imgur.com/5Pz0XrS

**Comment by SMed79** [comment]
Sorry, i cant help (cannot reproduce), seek assistance on easylist forum.
Btw, too much filter lists is not recommended, keep only those that are needed.

**Comment by reek** [comment]
You should report the bug to the developers of ABP
https://issues.adblockplus.org

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
