### ISSUE TITLE
mp3skull

### ISSUE THREAD

**Issue by addihockey10** [reek/anti-adblock-killer#1311]
Need to block these :
mp3skull.is###fab
mp3skull.is###fab-over

from [mp3skull.is](url)

**Comment by maynak00** [comment]
https://github.com/reek/anti-adblock-killer/issues/1296

**Comment by reek** [comment]
@addihockey10 
thanks

**Comment by maynak00** [comment]
mp3skull.vg
`||mp3skull.*/fab/FAB.js$script`
or
`mp3skull.vg###fab-over`
`mp3skull.vg###fab`

**Comment by reek** [comment]
@maynak00 
thanks, I'll add it

**Comment by reek** [comment]
done
