### ISSUE TITLE
www.socketloop.com

### ISSUE THREAD

**Issue by labrat0** [reek/anti-adblock-killer#1312]
https://www.socketloop.com/tutorials/golang-how-to-validate-url-the-right-way
http://imgur.com/Gxty1qQ
Chrome
Tampermonkey
AdBlock
EasyList+AakList+AdBlock custom filters+Adblock Warning Removal list+Malware protection

**Comment by SMed79** [comment]
Adblock plus add:
```
socketloop.com##.adsbygoogle
@@||socketloop.com^$generichide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=socketloop.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=socketloop.com
```

Adblock / uBo
```
@@||socketloop.com^$elemhide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=socketloop.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=socketloop.com
```

**Comment by labrat0** [comment]
@SMed79 Thanks for the reply, but it seems that after applying the rule on Adblock, the content is still hidden:
After applying the rule and with adblock ON:
http://imgur.com/pI2IbuE

With Adblock OFF
http://imgur.com/SqTdRPS

Comparison
http://imgur.com/a/MD3OG

**Comment by SMed79** [comment]
try to add also:
`@@||dqyh85as8dx8d.cloudfront.net/show_ads_epmads.js$script,domain=socketloop.com`

test with Adblock Plus ON http://i.imgur.com/Hvm2V3g.png

**Comment by labrat0** [comment]
@SMed79  It works great! Thank you very much for your patience and help!

**Comment by labrat0** [comment]
@SMed79  https://www.socketloop.com/references/golang-compress-gzip-newreader-function-example
But this one still hides the content
http://imgur.com/3kXlUMO


These are the rules I have

@@||socketloop.com^$elemhide
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=socketloop.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=socketloop.com
@@||dqyh85as8dx8d.cloudfront.net/show_ads_epmads.js$script,domain=socketloop.com

**Comment by labrat0** [comment]
@SMed79 Never mind, it is fixed after changed to 
@@||*.cloudfront.net/show_ads_epmads.js$script,domain=socketloop.com

Again, thank you so much for your time and help. 
This site has been annoying me for so long!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by bourne9** [comment]
Not working again, the message appears, even though you fixed it Reek. Apparently, the owner has modified the detection.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
