### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by air720boarder** [reek/anti-adblock-killer#1313]
wired.com

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by alphagame** [comment]
![capture](https://cloud.githubusercontent.com/assets/18489466/14571739/bc211cee-02ff-11e6-903f-9c648aa17772.PNG)

http://www.wired.com/2016/04/videogames-ai-learning/
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,
Thanks, already killed by AakScript, see instruction or help

**Comment by benmorrow** [comment]
I still see the message on Wired :( 

![screen shot 2016-04-27 at 5 59 41 pm](https://cloud.githubusercontent.com/assets/5604/14872509/deaf02d4-0ca1-11e6-8a8a-f96f8e8236d2.png)

**Comment by dikiaap** [comment]
@benmorrow For my browser has no problem. It seem like use cookies, just wait few second. And refresh again.

**Comment by reek** [comment]
@benmorrow 
Try with another Browser

**Comment by bourne9** [comment]
Try chrome and firefox, and I loaded the same page. No anti adblocker message. So it's on your side. Swap browsers, update filters lists, update AAK and see what happens.

**Comment by benmorrow** [comment]
@reek @dikiaap @bourne9 Ok so, after some testing, here's are my results... 

I could not replicate the issue on Chrome or Firefox, so it seems that it is limited to Safari.

I deleted Tampermonkey and Adblock Plus from Safari. I cleared all history and cookies. I emptied caches. 

Then I reinstalled Tampermonkey and Adblock Plus and resubscribed to the script and the list. I still see the issue, so I'm thinking that something is wrong with the way Safari works.

As a side note, the message doesn't always appear in Safari on wired.com. When it does, the message is triggered by scrolling down the page. You also have to scroll like you are reading the content. Scrolling quickly to the end of the page is not sufficient to trigger the message. So if anyone else wants to test this, I recommend:

1. Click http://www.wired.com/2016/04/even-n00bs-can-rock-magic-instruments-new-guitar/
2. Scroll slowly down the page like you're reading it
3. If you reach the end, click on one of the related articles
4. Scroll slowly down the new page
5. You should see the message

These steps trigger the message for me in Safari.

**Comment by bourne9** [comment]
@benmorrow Thanks for the feedback, ben. I knew it had to do with Safari. So this clears this up. This seems like a bug with Safari. You should report this to the development team there, that way they will do something about it and it might get fixed in the future versions. For the time being, I recommend you stay on Chrome or Firefox or Opera as these are the only 3 browsers I recommend to anyone.

By the way, AdBlock Plus and Adblock are easly prone to adblocking detection compared to uBlock Origin, so if I were you, I would rather use uBO instead of those two.
