### ISSUE TITLE
crackhex.com

### ISSUE THREAD

**Issue by Abyade** [reek/anti-adblock-killer#1315]
Hi,
Adblock redirect page on www.crackhex.com/(screenshot) BlockAdblock
Used link: http://www.crackhex.com/
Firefox 45+Ublock Origin+Greasemonkey+Easylist+Aak
Thanks in advance
![crack](https://cloud.githubusercontent.com/assets/8308071/14521099/07f65a5e-0228-11e6-989d-c5dd2b2756fd.jpg)

**Comment by SMed79** [comment]
Hi, 

adblock **plus** add:
`@@||crackhex.com^$generichide`

other adblockers add:
`@@||crackhex.com^$elemhide`

**Comment by reek** [comment]
OK, I'll kill it

**Comment by Abyade** [comment]
Already active, where i can add the ligne by Smed79
Thx in advance

**Comment by SMed79** [comment]
> where i can add the ligne

example here https://forums.lanik.us/viewtopic.php?f=62&t=29790&p=91541#p91539

**Comment by Abyade** [comment]
Thx Smed it's work thx a lot dude

**Comment by Abyade** [comment]
thx mister Reek it's working good

**Comment by bourne9** [comment]
@SMed79 Thanks, but that trick doesn't seem to work for - pizzamaking.com/forum/

They're also using the same script from BlockAdBlock, so I tried what you suggested for cracklehex and the the script still loads and appears. Why ?

**Comment by SMed79** [comment]
@bourne9 creat new issue for each site, see → https://github.com/reek/anti-adblock-killer/issues/1326

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
