### ISSUE TITLE
di.se

### ISSUE THREAD

**Issue by JonasNo** [reek/anti-adblock-killer#1319]
di.se likes to play the cat and mouse game.
Please don't click on the close button too quickly. As you did last time.

Link page contains anti-adblock
http://www.di.se/artiklar/2015/5/15/nu-byggs-rosa-huset--men-i-fel-land/?allakommentarer=&p=NaN

One screenshot
Host screenshot on: Imgur or Imgbox
http://imgur.com/WI2JDne

Your browser
Chrome Version 49.0.2623.112 m

Your script manager
Tampermonkey 4.0.25
dhdgffkkebhmkfjojejmpbldmpobfkfo

Your adblocker
Adblock Plus 1.11
cfhdojbkjhnklbpkdaibdccddilifddb

Your filterlists
ilter lists:
EasyList - https://easylist-downloads.adblockplus.org/easylist.txt
Fanboy's Annoyance List - https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
EasyPrivacy - https://easylist-downloads.adblockplus.org/easyprivacy.txt
Fanboy's Social Blocking List - https://easylist-downloads.adblockplus.org/fanboy-social.txt
Fanboy's Swedish - https://secure.fanboy.co.nz/fanboy-swedish.txt
AakList (Anti-Adblock Killer) - https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

**Comment by SMed79** [comment]
Duplicate to https://github.com/reek/anti-adblock-killer/issues/1159

**Comment by reek** [comment]
Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
