### ISSUE TITLE
readms.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#132]
Go to readms.com, click on a chapter and you'll see the anti-Adblock warning to the left of the manga pages.

readms.com###reader-sky

**Comment by reek** [comment]
Hi,

Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by anonsubmitter** [comment]
Is readms.com##.message-ld.pull-right also covered by this update? (This notice is located on top of the main page.)
