### ISSUE TITLE
izzylaif.com

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#1320]
http://izzylaif.com/en/
![putin](https://cloud.githubusercontent.com/assets/18214146/14551296/6a9f50da-02d1-11e6-839c-9e120d22636e.PNG)
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by SMed79** [comment]
add:
`@@||izzylaif.com/en/js/ad$script,~third-party`

**Comment by reek** [comment]
@adreporter 
Ok, I'll kill it, thanks.

@SMed79 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
