### ISSUE TITLE
game4free.nl

### ISSUE THREAD

**Issue by marvinarets** [reek/anti-adblock-killer#1321]
Script doesn't work on game4free.nl, please add this.
That script kan be killed by pressing Escape.

**Comment by maynak00** [comment]
**Report Guide:**https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**try with:**
`game4free.nl#@##adsense`

**Comment by reek** [comment]
@marvinarets 
Ok, I'll kill it, thanks

@maynak00 
Thanks

**Comment by marvinarets** [comment]
@maynak00 where to add that?
game4free.nl#@##adsense

**Comment by reek** [comment]
@marvinarets 
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
