### ISSUE TITLE
spieletipps.de

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#1322]
http://www.spieletipps.de/
![](https://cloud.githubusercontent.com/assets/16030872/14561572/78f462ec-0317-11e6-809d-8bcf02817754.png)
Chrome 49
Tampermonkey 3.12.58
uBlock Origin 1.6.8
Default + EasyList Germany + `||spieletipps.de/sp/`

When blocking their ads with the filter above or with `||spieletipps.de/js/sp_recovery.js` they will claim their site is broken by an adblocker.

**Comment by SMed79** [comment]
Hi, 
temporarily try these fiilters https://forums.lanik.us/viewtopic.php?f=90&t=29586&hilit=spieletipps.de#p91494

**Comment by reek** [comment]
@IDKwhattoputhere 
try these rules
<pre>
spieletipps.de##[id*="_ADB_"]
@@||spieletipps.de/sp/?p=
</pre>

**Comment by IDKwhattoputhere** [comment]
@SMed79 Thanks. Still leaves some black, clickable background sometimes but at least no animated banners or autoplay video & audio.

@reek Sadly didn't do anything. Ads still all there.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
