### ISSUE TITLE
computerworlduk.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1323]
Hi, 

![computerworlduk.com](http://i.imgur.com/1VHi3kg.png)

on `http://www.computerworlduk.com/operating-systems/windows-server-2016-what-expect-in-microsofts-latest-windows-server-operating-system-3623167/`

source → https://forums.lanik.us/viewtopic.php?f=62&t=29786

Thanks.

**Comment by Lazza** [comment]
The website checks for certain elements:

```javascript
            gnc: ["http://ib.adnxs.com/seg?add=5015431&t=1"],
            abp: ["http://ib.adnxs.com/seg?add=4878592&t=1"],
            wld: ["http://ib.adnxs.com/seg?add=4878598&t=1"]
```

Also, it checks for the height of Google Adsense iframes. The easiest workaround would be to remove class `.r3z-hide` from paragraphs (via JS) or blocking the custom font (via filters):

    http://www.computerworlduk.com/assets/redacted/redacted-script-bold.woff2

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by gbdrbob** [comment]
This doesn't seem to be working for me with the latest update (9.6), perhaps they implemented a countermeasure? Removing r3z-hide manually still seems to work though.

**Comment by reek** [comment]
@gbdrbob 
he seems to have a problem with chrome/opera, I'll fix that

**Comment by reek** [comment]
@gbdrbob 
Try this version https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by gbdrbob** [comment]
That seems to work fine

**Comment by reek** [comment]
@gbdrbob 
Great :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
