### ISSUE TITLE
fullmatchesandshows.com

### ISSUE THREAD

**Issue by seanc6441** [reek/anti-adblock-killer#1324]
1) http://www.fullmatchesandshows.com/2016/04/14/liverpool-vs-borussia-dortmund-highlights-full-match/

2) 
![2016-04-16](https://cloud.githubusercontent.com/assets/18493241/14578311/8ea64366-037c-11e6-930f-4dbf03d6ee0b.png)

3) Google Chrome

4) Tampermonkey

5) AdBlock Plus

6) EasyList + AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by seanc6441** [comment]
Hi,

I don't know if this request has been completed yet but I'm still getting my ad block blocked on this site.

Thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
