### ISSUE TITLE
pizzamaking.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1326]
Hi, 
on `http://www.pizzamaking.com/forum/` (https://github.com/reek/anti-adblock-killer/issues/1315#issuecomment-210865494)

```
@@||pizzamaking.com^$generichide
@@|http://$image,third-party,domain=pizzamaking.com
@@||pagead2.googlesyndication.com^$script,domain=pizzamaking.com
```
Thanks!

**Comment by bourne9** [comment]
Still loads, not working :(

**Comment by SMed79** [comment]
Your browser, script manager, adblocker, filterlists ?
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide#require

**Comment by bourne9** [comment]
Chrome, ublock origin and all the 3rd party filterscripts are activated and subscribted by default

Also the script is located at pizzamaking.com/forum/ and not at the homepage of pizzamaking.com

**Comment by SMed79** [comment]
**$generichide** is only for adblock plus 
`https://adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock`
`https://github.com/gorhill/uBlock/issues/967`

uBo add: 
`@@||pizzamaking.com^$elemhide`

**Comment by bourne9** [comment]
Yes, I did add $elemhide instead of generichide and it still doesn't stop.

**Comment by reek** [comment]
@bourne9 
I will publish tomorrow a new version that removes it

@SMed79 
I eliminate <code>BlockAdBlock</code> with <code>AakScript</code>, so no need you post a solution with filters, thanks

**Comment by bourne9** [comment]
@reek That would be really great if you can kill BlockAdBlock script universally ONCE and FOR ALL, so  you won't need to add websites to the list every now and then, just the script and it will be dead wherever it is used.

**Comment by SMed79** [comment]
@bourne9 reek said here https://github.com/reek/anti-adblock-killer/issues/1306#issuecomment-210872128 « _this can cause problems on some sites_ ».

**Comment by bourne9** [comment]
@SMed79 That's unlikely that it will actually break the website, besides if it does happen he can always undo it and go back to manually killing the sites, either way he will find a way.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
