### ISSUE TITLE
satcesc.com

### ISSUE THREAD

**Issue by Feguar** [reek/anti-adblock-killer#1327]
http://satcesc.com/web/futbol-en-la-television-guia-semanal-de-transmisiones/
http://imgur.com/n4ELawv
Chrome
Tampermonkey
Adblock
AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by SMed79** [comment]
add:
`@@||satcesc.com/web/futbol-en-la-television-guia-semanal-de-transmisiones/banner.gif?`
or
`@@||satcesc.com^$image,~third-party`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
