### ISSUE TITLE
www.360haven.com

### ISSUE THREAD

**Issue by Crrream** [reek/anti-adblock-killer#1330]
http://www.360haven.com/
Firefox
GreaseMonkey
Adblock Plus
Malware Domains, Fanboy Annoyance, Adblock Warning Removal, AaakList, EasyPrivacy+EasyList

Using the new BlockAdblock.

**Comment by bourne9** [comment]
<code>
@@||360haven.com^$elemhide
@@.jpg|$image,domain=360haven.com
@@.ico|$image,domain=360haven.com
</code>

**Comment by bourne9** [comment]
Add that your custom filters list in your adblocker in the meantime.

**Comment by bourne9** [comment]
`test`
`test`

**Comment by reek** [comment]
@Crrream 
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
