### ISSUE TITLE
workupload.com

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#1334]
I am not sure what happened but I updated AakList, saw that workupload.com#@#.adBlock was added as discussed in issue #1290, and retried the example link:

 http://workupload.com/file/zSWf2jy

But now workupload is again complaining about ad blockers.  Maybe something changed there to combat the filter. 

I don't know if this has anything to do with what I am seeing but when I updated AakList I saw a indication that some filters were disabled.  Indeed workupload.com#@#.adBlock was disable I think because I had previously added to my own custom filters.  I deleted it from my custom filters and reenabled AakList's.  All appears ok.  But I thought I should mention this anyhow.

**Comment by maynak00** [comment]
**try with:**
`workupload.com###sad`

**Comment by reek** [comment]
@xyzzy-xyzzy 
Ok, I'll fix it, but next time reopen https://github.com/reek/anti-adblock-killer/issues/1290

**Comment by xyzzy-xyzzy** [comment]
Ok workupload.com###sad seems to fix it again.  Thanks maynak00 and reek.

As for reopening a closed issue, I thought it was you (or maybe it was on one of the other github sites) that preferred to have a new issue even for revisiting at previously closed issue.  At least that's what I was thinking when I created this thread as a new issue.  I apologize then for not reopening #1290.

**Comment by xyzzy-xyzzy** [comment]
Well so much for workupload.com###sad :-(  Those workupload a-holes are getting on my nerves!

Here's an example that I think is specifically checking for this kind of block.

http://workupload.com/file/FA8qt5j

It seems obvious that whoever manages workupload is monitoring this site.

**Comment by reek** [comment]
@xyzzy-xyzzy 
It's killed by AakScript

**Comment by xyzzy-xyzzy** [comment]
I downloaded the aakdev.user.js beta script.  Dragged it onto my FF browser window to install it.  It installed.  Went to http://workupload.com/file/FA8qt5j.  But I see *no change* in behavior. :-(

**Comment by reek** [comment]
@xyzzy-xyzzy 
they have changed, but I'll fix it

**Comment by xyzzy-xyzzy** [comment]
Any progress with this?  

Just in case things changed here's a fresh link:

https://workupload.com/file/UUNw3x8

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
