### ISSUE TITLE
marketwatch.com

### ISSUE THREAD

**Issue by jgenender** [reek/anti-adblock-killer#1335]
#1297 fixes most of this, but this needs to be added to the filter to make it complete:

`marketwatch.com##.container--bannerAd`

There is still an empty ad banner at the top and the above fixes it.

**Comment by jgenender** [comment]
Actually the pop ups still happen on the other pages when you navigate.  Please see my filters in #1297 which seem to block all the anti-adblocking.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
