### ISSUE TITLE
20minutes.fr

### ISSUE THREAD

**Issue by f6fvy** [reek/anti-adblock-killer#1337]
http://www.20minutes.fr/
Mozilla Firefox 45.0.2
Greasemonkey
uBlock Origin
EasyList + AakList (among others)

Thanks !

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/1180

**Comment by f6fvy** [comment]
The proposed rule is working on uBlock Origin. Thanks !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
