### ISSUE TITLE
jkpan.com

### ISSUE THREAD

**Issue by thelastfantasy** [reek/anti-adblock-killer#1338]
http://www.jkpan.com/file-96323.html
Click the left one of the 3 green links, and the anti-adblock layer will appear in the popub tab.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by thelastfantasy** [comment]
http://www.jkpan.com/file-96323.html
![](http://pic.ffsky.net/images/2016/04/19/25bee7c7adc3bcbc3be5d0c1cafcd408.gif)
Browser: firefox 45.0.2 32bit
Script manager: Greasemonkey
Adblocker: uBlock Origin
Filterlists: anti-adblock-killer is added and enabled

**Comment by maynak00** [comment]
**try with:**
without CHN and JPN filters:
`jkpan.cc#@#.adsbygoogle`

with CHN: EasyList China (中文)‎ (abpchina.org), JPN: ABP Japanese filters (日本用フィルタ)‎:
`@@||pos.baidu.com$script,domain=jkpan.cc`
`jkpan.cc#@#.adsbygoogle`

**Comment by thelastfantasy** [comment]
@maynak00 Sorry it does not work. But I got another way just to block the layer.
`www.jkpan.cc###g207`

**Comment by reek** [comment]
@thelastfantasy 
No detected
