### ISSUE TITLE
videowood.tv 

### ISSUE THREAD

**Issue by glodar** [reek/anti-adblock-killer#1339]
http://videowood.tv/video/h9jl
http://i.imgur.com/JQniqAT.png
Mozilla Firefox 45.0.2
Greasemonkey
Adblock Plus
EasyList + Disable Malware + AakList 

Thank you for your work, this is best script, thank you again.

**Comment by reek** [comment]
Hi,
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**
`@@||videowood.tv^$elemhide`

**Comment by bourne9** [comment]
No need to add ^, this will do the job - `@@||videowood.tv^$elemhide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
