### ISSUE TITLE
link.tl

### ISSUE THREAD

**Issue by sonisgunu** [reek/anti-adblock-killer#1340]
https://link.tl/
Google Chrome
Tampermonkey
Adblock
AakList
http://link.tl/adblock.php
http://prntscr.com/au4cw9

**Comment by maynak00** [comment]
**try with:**
`@@||ads.wordego.com/a.js$script,domain=link.tl`

**Comment by reek** [comment]
ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
