### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#1341]
They are smart , opensubtitles.org is always finding new ways to bypass adblock now they use the script ajax.cloudflare to load ads into the web site, and of course the adblock can't block them, they can pass trough adblock, so as i wanted to help you guys and the team of anti-adblock-kiler i decided to reveal their new way 

![image](https://cloud.githubusercontent.com/assets/15664251/14642556/c42e0cd0-0642-11e6-8ec6-915e91f7b09c.png)

i guess is this code that is doing that
![image](https://cloud.githubusercontent.com/assets/15664251/14642921/5bd6724c-0644-11e6-9bd2-60b4d6fade74.png)

i've tried to bypass this using adblock to block the script but i can't the only way that i've found to block this preventing the ads appearing is using the extension scriptsafe that blocks that script 
like this
![image](https://cloud.githubusercontent.com/assets/15664251/14642987/9b7966d4-0644-11e6-8cdc-d6f584eb6b3d.png)

and i wanted to help in some way, to block this using adblock filters, so if you can help please, add here the code

**Comment by bourne9** [comment]
Nope, no ads here. Your "adblock" is outdated, remove it and install uBlock Origin from Chrome Web Store. Whatever they're doing, nothing can bypass uBO ;)

**Comment by fabiobarao94** [comment]
my adblock version is 2.56

**Comment by bourne9** [comment]
Well, get uBO. Regardless of the version, adblock and no other adblocker will ever be as powerful as uBO. Either way, this topic doesn't belong here as this repo is about reporting websites who force you to disable ur adblocker with their adblock detector so the script for that can be killed via AAK.

**Comment by fabiobarao94** [comment]
yes i use Anti adblock killer filter list in my adblock and i use tampermonkey with anti adblock killer and extension scriptsafe as well

**Comment by fabiobarao94** [comment]
i use adblock because i can edit my filter list and when a website is presenting an ad in a video such as dropvideo that was on in 2015 i can use programmer tool from chrome to visualize what is the ad, then manually block adding the code on adblock filter, but in ublock it's different a little more complicated, that's why i use adblock and not ublock

**Comment by reek** [comment]
@fabiobarao94 
please report ads here https://forums.lanik.us/
