### ISSUE TITLE
FAQMOZILLA.ORG

### ISSUE THREAD

**Issue by sxit07** [reek/anti-adblock-killer#1343]
http://faqmozilla.org
![screenshot](https://cloud.githubusercontent.com/assets/18562965/14659292/dc75656a-069a-11e6-9927-748f37293a45.jpg)
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList + ABP X Files

**Comment by SMed79** [comment]
add:
```
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=faqmozilla.org
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=faqmozilla.org
```

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by sxit07** [comment]
Thank you very much!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
