### ISSUE TITLE
Can i install this anti adblock killer in Wordpress site

### ISSUE THREAD

**Issue by ustechera** [reek/anti-adblock-killer#1344]
hello, Can i install this anti adblock killer in my Wordpress site , if possible please guide me , i saw an example : http://antiblock.org/?p=v3&demo    this url , 
help me. thanks in advance.

note: adblock plugin must be ask to visitor "please disable adblock" - like popup , because my website adsense revene already low , now adsense revenue NIL , if incase this plugin is doesn't support the wordpress plotform please suggest me any other plugin , thanks for your help.

**Comment by reek** [comment]
what is your website ?

**Comment by ustechera** [comment]
ustechera.com

**Comment by reek** [comment]
Now read this https://github.com/reek/anti-adblock-killer#about

**Comment by ustechera** [comment]
thankyou. @reek
