### ISSUE TITLE
Haaretz.co.il

### ISSUE THREAD

**Issue by ilanerukh** [reek/anti-adblock-killer#1346]
www.haaretz.co.il
http://i.imgur.com/pRMf59O.png
Chrome
uBlock origin

Articles proceed to  disable adblocker page.
Thank you very much :)

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1292#issuecomment-212530660

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
