### ISSUE TITLE
mrpiracy.club

### ISSUE THREAD

**Issue by Rootzpower** [reek/anti-adblock-killer#1347]
Hi,

MrPiracy change domain.
Old domain mrpiracy.xyz will redirect do mrpiracy.club

That change of domain broke code.

Can you fix it please?
Thanks :)
![mrpiracy](https://cloud.githubusercontent.com/assets/15384112/14682909/e1048d38-071f-11e6-804d-d076f041cc09.png)

**Comment by maynak00** [comment]
**try with:**
`@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=mrpiracy.club,script`

**Comment by SMed79** [comment]
add: 
```
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=mrpiracy.club
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=mrpiracy.club
```
@maynak00 without adding `/show_ads_impl.js` the page never stop loading.

**Comment by reek** [comment]
Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
