### ISSUE TITLE
Semprot.com

### ISSUE THREAD

**Issue by codercell** [reek/anti-adblock-killer#1349]
For example: http://www.semprot.com/showthread.php/1174762-ada-yang-kenal
SS: http://imgur.com/Qfcl3vl

Spec:
Opera 36.0
Violentmonkey
Adblock Plus

Filter:

Anti-Adblock Killer | Reek 9.5
EasyList‎
IDN: ABPindo‎

The site give the red warning message to deactivate my adblock, please kill it. Thanks.

**Comment by reek** [comment]
Ok, I'll fix it

**Comment by codercell** [comment]
ok thanks reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by kitagas20241** [comment]
bagus obed

www,nobokep,my,id

**Comment by langsungpanas2024** [comment]
au ah

www,nobokep,my,id

**Comment by maunyagitu2024** [comment]
cosplay bu

www,flavaofc,com

**Comment by dirgahayutni2024** [comment]
AlwaysToYouHannie

www,flavaofc,com

**Comment by overthemoonnew** [comment]
kartu dapet crit

www,kontenterabox,com
