### ISSUE TITLE
Are all anti-Adblock elements you get reports of blocked?

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#135]
Do you block all anti-Adblock elements you encounter or do you have a set of guidelines like Adblock Warning Removal List (https://easylist.adblockplus.org/blog/2013/05/10/anti-adblock-guide-for-site-admins) that allows small, non-intrusive anti-Adblock notices?
I'm asking since I know of some small non-intrusive anti-Adblock elements that I would report if you accept them.

**Comment by reek** [comment]
HI,

Yes, you can report me, but create a new issue.

See you soon
Reek

**Comment by anonsubmitter** [comment]
Ok, thanks.
