### ISSUE TITLE
Add Multiup.org

### ISSUE THREAD

**Issue by liberodark** [reek/anti-adblock-killer#1352]
Hello,

Please add Multiup.org.

Cordialy

http://www.multiup.org/

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by bourne9** [comment]
Nope, it doesn't have any adblock detection script.

**Comment by liberodark** [comment]
is working thank

**Comment by bourne9** [comment]
It was just you, nothing was done at AAK.
