### ISSUE TITLE
exrapidleech.info

### ISSUE THREAD

**Issue by evetaku** [reek/anti-adblock-killer#1353]
http://www.exrapidleech.info
http://prnt.sc/avbui3
Mozilla Firefox 45.0.2
Greasemonkey 3.7
AdBlock Plus 2.7.2 + uBlock Origin 1.6.8
Anti-Adblock Killer | Reek 9.5 + EasyList‎ 
Please kill it. Thank you

**Comment by reek** [comment]
Hi,
Ok, I'll fix it

**Comment by bourne9** [comment]
Filter - `exrapidleech.info/classes/_300x200.ads.js$script`

**Comment by bourne9** [comment]
Why the thumbs down reek ? Is it not working ?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
