### ISSUE TITLE
voici.fr

### ISSUE THREAD

**Issue by liberodark** [reek/anti-adblock-killer#1354]
Hello,

Please add Voici.fr.

Cordialy

**Comment by bourne9** [comment]
Would you bother to read that and post in that format - https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md before posting ? That way we can check what's actually happening.

**Comment by SMed79** [comment]
add:
`@@||www.voici.fr/ads.js|$xmlhttprequest`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
