### ISSUE TITLE
CinemaBlend.com

### ISSUE THREAD

**Issue by damnnative** [reek/anti-adblock-killer#1358]
http://www.cinemablend.com/new/Green-Lantern-Corps-Movie-May-Have-3-Green-Lanterns-Here-What-We-Know-126597.html
http://i.imgur.com/Sh2vgK4.jpg
Chrome 50 (latest)
Tampermonkey (latest) + Aak script
AdBlock Plus (latest) + EasyList, EasyPrivacy, AakList

**Comment by bourne9** [comment]
same as the one I reported #1357

**Comment by bourne9** [comment]
@damnnative 

Add this filter - `@@||cinemablend.com^$elemhide`

**Comment by MarkTheFucker** [comment]
`@@||cinemablend.com$elemhide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
