### ISSUE TITLE
imgclick.net

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#1359]
Example:
http://imgclick.net/pkgaontdfhz4/bfe2ae3a6e1d.jpg.html
http://i.imgur.com/igtxhaQ.png

They have an adblock bait script, needs an exception rule:

`@@||imgclick.net/jss/show_ads.js`

**Comment by reek** [comment]
Thanks :+1:

**Comment by Crardogg** [comment]
Hi I am still seeing this
[http://imgclick.net/7gtqvd95t7xm/b9200419b4c9.jpeg.html](url)
[https://imgur.com/v9L4Hwv](url)
Mozilla Firefox
Greasemonkey
Adblock Plus
Ablock Warning Removal List + EasyList + EasyPrivacy + Disable Malware + AakList (Anti-Adblock Killer)

I could be doing something wrong as I have tried adding that exception rule and still see this

**Comment by reek** [comment]
@Crardogg 
https://github.com/reek/anti-adblock-killer/wiki/Add-filter
https://github.com/reek/anti-adblock-killer#help

**Comment by Crardogg** [comment]
@reek Thank you it look liked EasyList was interfering with it

**Comment by bourne9** [comment]
@Crardogg That's because they changed the address of the adblock checking script

add this - `@@||salefiles.com/xxx/show_ads.js$script`

The first filter is no longer going to work. 

They're also running FuckAdBlock made by sitexw and it loads too so if you want to block that too, then add this along with - `||imgclick.net/jss/blockadblock.js$script`

Easylist has got nothing to do with this.

**Comment by reek** [comment]
@bourne9 
Well seen

**Comment by bourne9** [comment]
@reek Thanks. I think the owner saw the easylist thread about imgclick.net and changed the address, so to make the filter not work for us and added FuckAdBlock on top of that because he thinks that we won't be able to block that and that way he can troll us lol, lame attempt I say.

**Comment by Crardogg** [comment]
@bourne9 Thanks that worked! I can allow EasyList to use all filters now

**Comment by IDKwhattoputhere** [comment]
Couldn't AakScript set values like `adblock = false` on all sites as a preventative method? Sorry if this is a stupid question. :confused:

**Comment by bourne9** [comment]
No, that wouldn't work, because not all websites use adblock as a "variable" for checks. First they prevent the check from running and then set the value.

**Comment by reek** [comment]
@IDKwhattoputhere 
yes it is possible but a rule adblock do the job

**Comment by IDKwhattoputhere** [comment]
@reek I see, that makes sense. Just thought it would help in those cases where you didn't yet add a filter. Just an idea anyways.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
