### ISSUE TITLE
hdzog.com

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#1362]
I'm seeing those filters:
`@@/advertisement*.js$script`
`@@/advert.js$script,domain=~adultmult.tv`
And I'm wondering if maybe a filter like `@@/advertising.js$script` or `@@/js/advertising.js$script` should be added.
https://github.com/reek/anti-adblock-killer/search?q=advertising.js&type=Issues&utf8=%E2%9C%93
Seems to be used quite often.

Example:
NSFW
`http://www.hdzog.com/videos/89169/alone-with-busty-teen-nekane/`
https://cloud.githubusercontent.com/assets/16030872/14761068/ae2b8bcc-0955-11e6-9bcb-80c45f376b32.png
Chrome 50
Tampermonkey 3.12.58
uBlock Origin 1.6.8
Default + EasyList Germany + AAKList
The site doesn't block adblockers but displays ads for the users.
Solution: `@@/advertising.js$script,domain=hdzog.com`
Also `hdzog.com##a[href="/cs/cumlouder/"]` if the single left over banner should be removed.

Feel free to close if not of interest.

**Comment by reek** [comment]
Ok, Ill add it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
