### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by Jackie1999** [reek/anti-adblock-killer#1364]
http://www.vvvvid.it
http://imgur.com/wrCRCgp
Opera
Violentmonkey
Adblock Plus
EasyList + AakList

**Comment by SMed79** [comment]
Try these rules https://forums.lanik.us/viewtopic.php?f=96&t=29982&hilit=vvvvid.it#p92152

**Comment by Jackie1999** [comment]
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
