### ISSUE TITLE
tv4play.se

### ISSUE THREAD

**Issue by Svenskunganka** [reek/anti-adblock-killer#1365]
http://www.tv4play.se/program/maria-wern?video_id=3294813
http://i.imgur.com/oIz7k7N.png
Google Chrome
Native
uBlock Origin
EasyList + Aaklist + Adblock Warning Removal List + Peter Lowe's Ad server list

**Comment by bourne9** [comment]
Add this filter `@@||cdn.videoplaza.tv/contrib/se-tv4/advertisement.js$script` and it should start streaming.

**Comment by Svenskunganka** [comment]
@bourne9 Hey, thank you, but unfortunately that doesn't seem to work, console doesn't tell that it's being blocked and can't see it in the network requests either. Any clue?

**Comment by bourne9** [comment]
@Svenskunganka Well that's the only java script which checks for adblock so that should do the job and I'm not receiving the blockage like you're since videoplaza and videoplaza1 domains are not being here.

**Comment by Svenskunganka** [comment]
It is indeed there now that I check again, but for some reason the overlay for the video doesn't disappear and I've got no sound. That filter is also in my EasyList.

**Comment by bourne9** [comment]
It's probably the geolock which I'm facing too.

**Comment by davidhedlund** [comment]
https://github.com/reek/anti-adblock-killer/issues/1464
