### ISSUE TITLE
game-debate.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1366]
http://www.game-debate.com/games/index.php?g_id=6181&game=0%20A.D.

http://imgur.com/u5wYRsS

Mozilla Firefox 45.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by SMed79** [comment]
The site has limited functionality ?

**Comment by xxcriticxx** [comment]
ok smart
