### ISSUE TITLE
passimtv.xyz

### ISSUE THREAD

**Issue by ilanerukh** [reek/anti-adblock-killer#1369]
Windows 10
Chrome
Origin + aak
http://www.passimtv.xyz/

Thank you.

**Comment by bourne9** [comment]
add this filter - `@@||shukitv.ucoz.com/script/ads.js$script`

**Comment by ilanerukh** [comment]
Thanks. Works.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
