### ISSUE TITLE
listamais.com.br

### ISSUE THREAD

**Issue by Sitolino** [reek/anti-adblock-killer#1370]

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by bourne9** [comment]
no adblock detected, post some proof along with the intended format.

**Comment by Sitolino** [comment]
http://imgur.com/UkQf6o8
Google Chrome 49.0.2623.112 m
Tampermonkey
Adblock 
EasyList + AakList (http://imgur.com/3dmlREZ)

**Comment by bourne9** [comment]
It appears as if you haven't installed AAK script, the list will not work alone, you also need to install AAK script.

**Comment by Sitolino** [comment]
http://imgur.com/pzL3AGg
AAK script is installed on Tampermonkey?

**Comment by bourne9** [comment]
Yes like that way and you're still receiving that notification ? That is strange, because I'm using uBlock Origin with all the 3rd party filters and I'm not receiving anything at all here.

**Comment by Sitolino** [comment]
Very strange, still it does not work.

**Comment by Sitolino** [comment]
Apparently the site uses this application to http://siteapps.com/app/adblock_analytics_and_protector-126.

Can it be something related to language (pt-br)?

**Comment by bourne9** [comment]
try this filter `@@||||www.listamais.com.br/Resources/js/advert.js$script` and see if it stops.

**Comment by bourne9** [comment]
If that doesn't work then try this one - `||257298.a.siteapps.com/257298.js$script`

**Comment by Sitolino** [comment]
I got the lock through the AdBlock, using masking div's
`listamais.com.br##div[id="bg_block"]`
`listamais.com.br##div[id="adblmsg"]`



But when looking for what was releasing advert.js noticed this line in AAK.

![image](https://cloud.githubusercontent.com/assets/18661643/14792745/206fb5d0-0af2-11e6-9f63-6875c8aded06.png)
![image](https://cloud.githubusercontent.com/assets/18661643/14792771/38d5678c-0af2-11e6-930b-7bbb5df9b2ce.png)

Apparently this is what was releasing the lock.

**Comment by bourne9** [comment]
what do you mean releasing the lock ? and did the filter I posted worked ?

**Comment by Sitolino** [comment]
With manual filter
`@@||||www.listamais.com.br/Resources/js/advert.js$script`
and enabled AAK did not work because the AAK offers the exception rule
`@@/advert.js$script,domain=~adultmult.tv`

When I turn off the AAK, manual rule passes and block /js/advert.js, but does not solve the problem.

With manual filter
`||257298.a.siteapps.com/257298.js$script`
It works

**Comment by bourne9** [comment]
So the last filter I posted worked ? Fucking great!

**Comment by Sitolino** [comment]
`||257298.a.siteapps.com/257298.js$script`
Yes it worked!

**Comment by bourne9** [comment]
Took me some time but I did find out, have fun :+1:  This will work in the meantime untill reek adds this in his AAK Script :+1:

**Comment by Sitolino** [comment]
Great, ty :+1:

**Comment by reek** [comment]
@bourne9 
thanks for rule

@Sitolino 
I'll add it to AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by emstriker** [comment]
the issue with the website www.listamais.com.br are returned, but I Added  a custom list with 👍 https://www.listamais.com.br/Resources/js/bootstrap.min.js
https://www.listamais.com.br/Resources/js/ads.js
and solved  my problem, maybe is usefull to anyone.
