### ISSUE TITLE
snacktv.de

### ISSUE THREAD

**Issue by koboltzz** [reek/anti-adblock-killer#1371]
http://www.t-online.de/tv/tv-highlights/pro7sat1/id_77651060/ekelhafte-entdeckung-bei-baumfaellarbeiten.html
http://abload.de/img/2016-04-25_19h30_01ytsux.png
Mozilla Firefox
Greasemonkey
ublock origin
EasyList + AakList

**Comment by bourne9** [comment]
add - `@@||player.snacktv.de/js/ads.js$script`

**Comment by bourne9** [comment]
@reek, That filter  I posted removed the adblock warning message, but apparently the video doesn't play, so I want you to check this out yourself and find the correct filter

**Comment by reek** [comment]
@bourne9 
Video plays for me and rule is good

**Comment by bourne9** [comment]
@reek 

![](https://i.gyazo.com/8bd9a5910f0b52d6eff3184c873664a5.png)

That's what happens with this filter on my screen

**Comment by koboltzz** [comment]
If reek is able to play the video, bourne9 and me don't, then there must be a conflicting rule somewhere.

**Comment by bourne9** [comment]
Doesn't matter to me though as I was only trying to help you kobo, I don't visit these websites ever, so I hope it works out for you.

**Comment by reek** [comment]
Try only EasyList and AakList

**Comment by koboltzz** [comment]
Interstingly, this linked video doesn't play at all, not in IE11 and Edge (without anything blocked with hosts file or thridparty app) and not Firefox only with AakList. All other videos seems to play well. How did you manage to play this linked video?

**Comment by bourne9** [comment]
Well then it seems the video is fucked up itself, though how I wonder how reek was able to play himself

**Comment by reek** [comment]
I just added the rule, try update Adobe Flash Player

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
