### ISSUE TITLE
imgclick.net

### ISSUE THREAD

**Issue by Opzon** [reek/anti-adblock-killer#1372]
Windows 8.1
Chrome
Tampermonkey
ublock orgin
AakList... I have tons of filters on :/ so here is a picture of what I have enabled http://i.imgur.com/Kg7NA7H.png
http://i.imgur.com/h84GTe3.png this is the picture from imgclick
Orginally put incorrect link lol... mawh bad.

**Comment by bourne9** [comment]
post in the appropriate format and the domain itself is for sale ???

**Comment by Opzon** [comment]
@bourne9 derp... posted wrong link. Will update in correct format, sorry.

**Comment by bourne9** [comment]
@Opzon already reported  here - #1359 and apparently patched too, update your AAK script and all your filters as I dont see the adblock message anymore.

After updation if you're still seeing that message then add this filter - `@@||imgclick.net/jss/show_ads.js`

**Comment by reek** [comment]
@Opzon 
https://github.com/reek/anti-adblock-killer/issues/1359

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
