### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by sas46** [reek/anti-adblock-killer#1373]
https://www.vvvvid.it/adblock.html
http://imgur.com/KIdJYBi
Google Chrome
Tampermonkey
AakList

**Comment by reek** [comment]
Duplicated: https://github.com/reek/anti-adblock-killer/issues/1364

**Comment by bourne9** [comment]
Those morons have geo blocked me, so I can't look up what shit they're inserting

**Comment by sas46** [comment]
Just tell me how and I'll grab some data for you

**Comment by reek** [comment]
@sas46 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by reek** [comment]
@sas46 
Have you tried these rules https://github.com/reek/anti-adblock-killer/issues/1364#issuecomment-213875879

**Comment by bourne9** [comment]
That would be complicated since I would have to tell you to grab and that and would cause lots of back and forth messages and confirmations, instead checkout the already listed thread reek posted #1364 as this thread is a duplicate.

**Comment by sas46** [comment]
Thank you very much, @reek found the working solution

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
