### ISSUE TITLE
www.euroman.dk

### ISSUE THREAD

**Issue by PhpSriptKiddie** [reek/anti-adblock-killer#1374]
www.euroman.dk
Version: 9.5 
AakScript: true 
AakList: true 
Browser: Chrome Version 49.0.2623.112 (64-bit)
ScriptManager: Tampermonkey

**Comment by bourne9** [comment]
add `||egmontassets.net/random.js$script`

**Comment by PhpSriptKiddie** [comment]
Most likely a stupid question, but how do I add that?

**Comment by bourne9** [comment]
Add as a custom filter inside your adblocker.

**Comment by bourne9** [comment]
@reek egmontassets.net is a new anti adblocker domain, so if you wanna block the entire domain instead of just the .js, you might as well do that.

**Comment by maynak00** [comment]
`@@||euroman.dk/*/adsense.js$script`
(complete url: http://www.euroman.dk/App_Themes/v3Common/js/adsense.js)
but not need because:
Static filter `@@||euroman.dk^$elemhide` found in:EasyList
also for clean page(not for antiadblock):
`euroman.dk##.topbanner-bg`
`euroman.dk##.banner-block`
`euroman.dk##.label-annonce`

**Comment by bourne9** [comment]
That static filter doesn't work, already tested.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
