### ISSUE TITLE
titlovi.com

### ISSUE THREAD

**Issue by streger** [reek/anti-adblock-killer#1376]
http://titlovi.com/
http://imgur.com/HUokXbT
Google Chrome
uBlock Origin
Lists: http://imgur.com/Nmckddk

p.s. class id has new hash name with every load

**Comment by bourne9** [comment]
Hmmm, this domain is also using FuckAdBlock made by sitexw and a small adblock detection script. 

Remove the custom AAKList in your filters as AAKlist by Reek is already added by uBO by default and having TWICE will cause it to not work as intended.

I'm not seeing that adblock message like you in the imgur pic as FuckAdBlock is already killed by AAK.

So update your AAK list filter list and script and remove the custom one at the bottom which is the same as AntiAdblockKiller by Reek at the top.

**Comment by streger** [comment]
Okay, I've removed custom lists, and updated all other. Tried to clean load the site, but the antiadblock warning still appears. 
I've also now tried the same in Firefox with uBlock Origin and same think happens.

Do I need to install the script in Greasymonkey if I use uBlock Origin?

**Comment by bourne9** [comment]
No TamperMonkey works perfectly here and I don't see the message.

**Comment by streger** [comment]
I found the culprit for showing it. First I disabled all my extensions except uBlock just to be sure. That wasn't the problem.

Then I went through the uBlock Origin lists disabling them one by one, and the culprit is Easylist. It makes the anti-adblock message appear. Problem is that that is the main list. I can't disable it.
Any suggestions?

**Comment by bourne9** [comment]
Well EasyList can't be the culprit as I have it activated too, but like I said AAK kills it. I'm beginning to think that you don't have AAKScript installed. 

Have you installed TamperMonkey ? 

If not then follow this - https://github.com/reek/anti-adblock-killer#step-1-scriptmanager

Then have you install AAK Script ? Without Script the filter list wont work alone.

If not then follow this - https://github.com/reek/anti-adblock-killer#step-3-userscript

Once you do all these steps, let me know.

**Comment by streger** [comment]
I didn't had AAKScript installed in Tampermonkey, and when I enable it, it works with EasyList enabled. That's why I asked before for Greasymonkey (meaning Tampermonkey) - my bad ;) 
That being said, you can close this issue.

But, if I disable Tampermonkey extension and disable EasyList in uBlock Origin it still blocks the warning. So, as a follow up questions, what is going on there? Is it possible to have this working without Tampermonkey and with maybe removing some of filters from EasyList?

**Comment by bourne9** [comment]
GreaseMonkey is for Firefox only. For Chromium based browsers, you need TamperMonkey.

Secondly, I do not know, but apparently it seems once blocked via the script, it remains blocked even after removing it. It might work for you, but other websites will detect your adblocker instantly.

AAK is for those websites only and for running AAK you need to have Script Manager like TamperMonkey installed and enabled. Why do you want to remove filters ? You do realise the MORE filters you remove, the MORE you're prone to receiving ads/malware/popups/ raping redirects and some nasty viruses onto your device.

If I were you, I would say activate each and ever 3rd party filter in the list. The more activated they are, the more safer your device is.

**Comment by streger** [comment]
Okay, thanks!

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
