### ISSUE TITLE
Add new supported aak: Ghostery

### ISSUE THREAD

**Issue by dikiaap** [reek/anti-adblock-killer#1377]
I have been testing aak with **Ghostery** and that's work.
Should I create PR and adding **Ghostery** to the list?

**Comment by bourne9** [comment]
remove ghostery it has nothing to do with uBlock or AAK.

**Comment by dikiaap** [comment]
@bourne9 why? any reason for that?

**Comment by bourne9** [comment]
@dikiaap because you don't need it when you have uBlock + AAK, they're the perfect combo.

**Comment by dikiaap** [comment]
@bourne9 I don't have uBlock and another adblocker, only ghostery and AAK are installed.

**Comment by Giwayume** [comment]
@dikiaap 
That's part of your problem. Half of AAK is its ad filters that run on uBlock or Adblock Plus etc. You're missing a lot of anti blocking solutions if you don't have uBlock installed with AAK List.

**Comment by dikiaap** [comment]
Ok yeah. Ghostery has not working well with AAk.
I close this issues.
