### ISSUE TITLE
exrapidleech.info

### ISSUE THREAD

**Issue by MUFTAKiS** [reek/anti-adblock-killer#1378]
how to stop this site from redirect me forever to verification?!!

**Comment by bourne9** [comment]
duplicate #1353

**Comment by MUFTAKiS** [comment]
i need to contact reek privately how to do that?!

**Comment by MUFTAKiS** [comment]
is there someone here answer me??!!

**Comment by MUFTAKiS** [comment]
where are you reek?!! it been a long time waiting to fix this site!! is there someone know how to fix this?!!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MUFTAKiS** [comment]
still redirect me to the same damn verification my god did you test before publish?!!!
