### ISSUE TITLE
comptoir-hardware.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#138]
Hi, 
on hxxp://www.comptoir-hardware.com 

Anti-adblock warning banners load from /edi/* and "rick rolled" video clip loaded from dailymotion.com

Screenshot: http://i.imgbox.com/l04sQ8nu.png

Mozila Firefox 34.0.5
Adblock Plus 2.6.7
Greasemonkey 2.3

EasyList + Liste FR + Liste AR + Anti-Adblock Killer

Thank you.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
