### ISSUE TITLE
clinefree.com detect adblock

### ISSUE THREAD

**Issue by FrancYescO** [reek/anti-adblock-killer#1380]
http://www.clinefree.com/
http://i.imgur.com/BKWJ3eU.png
Chrome
Tampermonkey
uBlock Origin
(uBlock default config)  uBlock filters‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎

**Comment by bourne9** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by FrancYescO** [comment]
Updated.

**Comment by bourne9** [comment]
and on which page is that appearing ?

Secondly, try this filter - `||clinefree.com/advertisement.js$script`

**Comment by FrancYescO** [comment]
was on full page, now its gone, good find ;)

**Comment by reek** [comment]
Killed by AakList, see instruction
