### ISSUE TITLE
wstream.video

### ISSUE THREAD

**Issue by FrancYescO** [reek/anti-adblock-killer#1382]
#http://wstream.video/ddd6u557gl43

http://wstream.video/sr87q5yko7ja
http://wstream.video/bjrchafcibki

http://i.imgur.com/oEdKy3G.png
Chrome
Tampermonkey
uBlock Origin
(uBlock default config + Anti-Adblock Killer | Reek‎) uBlock filters‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎

**Comment by SMed79** [comment]
add these filters https://forums.lanik.us/viewtopic.php?f=64&t=28985&hilit=wstream.video#p89670

**Comment by reek** [comment]
@FrancYescO 
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
