### ISSUE TITLE
http://backin.net/

### ISSUE THREAD

**Issue by FrancYescO** [reek/anti-adblock-killer#1383]
http://backin.net/hpst2wy55xd7
http://i.imgur.com/19o3RK7.png
Chrome
Tampermonkey
uBlock Origin
(uBlock default config + Anti-Adblock Killer | Reek‎) uBlock filters‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎

**Comment by bourne9** [comment]
Try these `@@||rivcash.com^$script,domain=backin.net
||bc.vc^$domain=backin.net
||cloudflare.com^$domain=backin.net
|http://$popup,domain=backin.net
`

**Comment by FrancYescO** [comment]
seems that they still able to detect, or at least 80% of the time (sometime i reloaded the page and they havent blocked me with no config changes)

**Comment by bourne9** [comment]
Sorry, these work sometime and sometime they don't, still not the perfrect filters I guess

**Comment by FrancYescO** [comment]
it's probably something related to cookie or some sort of session...

i just clicked the link up there and no anti-adblock banner appeared than after a page reload they are ever able to detect it

**Comment by reek** [comment]
@FrancYescO 
I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
