### ISSUE TITLE
telephoneannuaire.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1384]
Hi, 
on `http://www.telephoneannuaire.fr/` 
sc: http://i.imgur.com/ERkjdzF.png

```
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=telephoneannuaire.fr
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=telephoneannuaire.fr
```

Thanks!

**Comment by bourne9** [comment]
`||www.telephoneannuaire.fr/resources/amz4.jpg$image`

**Comment by SMed79** [comment]
@bourne9 already blocked by **liste FR** ([07e242a13f06/liste_fr.txt#l3703](https://hg.adblockplus.org/listefr/file/07e242a13f06/liste_fr.txt#l3703)).

**Comment by bourne9** [comment]
@SMed79 Then why does it still load ?

**Comment by reek** [comment]
thanks Med

**Comment by reek** [comment]
Done
