### ISSUE TITLE
games.tiscali.cz

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1385]
Hi;

`@@||bbcdn.go.cz.bbelements.com/bb/bb_one2n.$script,domain=tiscali.cz`

on `http://games.tiscali.cz/`
see https://forums.lanik.us/viewtopic.php?f=62&t=30105

Thanks!

**Comment by bourne9** [comment]
`@@||tiscali.cz^$generichide`

^^Isn't that working? or does the bbc one works now ?

**Comment by reek** [comment]
Done, thanks
