### ISSUE TITLE
atdhe.se

### ISSUE THREAD

**Issue by marco-c** [reek/anti-adblock-killer#1386]
http://atdhe.se/soccer/stream-g26e7-vitesse-vs-utrecht
http://imgur.com/ezGG1K4
Mozilla Firefox
No script manager
AdBlock Plus
EasyList + AakList

**Comment by marco-c** [comment]
https://reports.adblockplus.org/b4dcec09-870c-45ae-9735-96d64a26c4e7

**Comment by bourne9** [comment]
Filter - `||stopadblock.info$subdocument`

**Comment by bourne9** [comment]
AAK list is useless without AAK script which can only be installed by TamperMonkey a script manager install that, that's why AAK will never work for you like this. Read the installation guide.

**Comment by reek** [comment]
@marco-c 
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by marco-c** [comment]
I'm still seeing issues on this page, http://atdhe.top/soccer/watch-germany-vs-slovakia-639jg, which redirects to http://block.streams.tv/.
