### ISSUE TITLE
videowood.tv

### ISSUE THREAD

**Issue by FrancYescO** [reek/anti-adblock-killer#1388]
http://videowood.tv/embed/ziy1
http://i.imgur.com/Ugmi3wl.png

Chrome
Tampermonkey
uBlock Origin
(uBlock default config + Anti-Adblock Killer | Reek‎) uBlock filters‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎

**Comment by bourne9** [comment]
Duplicate #1339

**Comment by MarkTheFucker** [comment]
`@@||videowood.tv$elemhide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
