### ISSUE TITLE
spoiler.net

### ISSUE THREAD

**Issue by ZeroGravity83** [reek/anti-adblock-killer#1389]
URL: https://www.spoiler.net/
Screenshot: http://i.imgur.com/EmnvVLf.png
Browser: Google Chrome
Script Manager: Tampermonkey
Adblocker: uBlock Origin
Filter lists: Easy List, uBlock filters‎, Anti-Adblock Killer | Reek, Peter Lowe’s Ad server list, Easy Privacy, Adblock Warning Removal List‎

**Comment by SMed79** [comment]
`spoiler.net#@#.banner-ad`

**Comment by bourne9** [comment]
^^The bottom one won't remove the placeholder for the banners, so that's pointless, use the above two.

**Comment by reek** [comment]
@ZeroGravity83 
Ok, I'll kill it, thanks

**Comment by Giwayume** [comment]
@SMed79 This project is to remove all anti-adblocking messages, invasive or not.

**Comment by SMed79** [comment]
@Giwayume These filters I suggested does not work for you?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
