### ISSUE TITLE
turkanime.tv

### ISSUE THREAD

**Issue by 4DEATH** [reek/anti-adblock-killer#139]
http://www.turkanime.tv/
http://i.imgur.com/ocEwxFS.png
Waterfox 35 (Firefox)
Greasemonkey
µBlock + Disconnect
µBlock filters + Easylist + Peter Lowe’s Ad server list + EasyPrivacy +  Malware Domain List‎ + Fanboys Turkish

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

I do not see the message, can you give me a link on which the message appears

**Comment by 4DEATH** [comment]
Other than forum, every page gives same message (and thats the annoying part). From homepage ( http://www.turkanime.tv/ ) to any anime page ( http://www.turkanime.tv/anime-bolum/Gintama-8-Bolum ).

I just tested: If I disable µBlock, no ads (Since disconnect also blocks ads) nor warning shown. Tested with Adblock Plus, same results. So its most likely detects adblock plugins. I added site to whitelist for µBlock, everything looks perfect(no ads, no warning). Thanks for making me test (lol) and thanks for script!

**Comment by reek** [comment]
Try remove
Peter Lowe’s Ad server list
Fanboys Turkish

**Comment by 4DEATH** [comment]
Tried it, still shows warning.

**Comment by reek** [comment]
Ok
