### ISSUE TITLE
themarysue.com/

### ISSUE THREAD

**Issue by AdBlockAshley** [reek/anti-adblock-killer#1390]
http://www.themarysue.com/glaad-studio-responsibility-2016/
http://i.imgur.com/TH7Xp6A.png
Google Chrome
Tapermonkey
Adblock Plus
Adblock Warning Removal List + EasyList + AakList

**Comment by bourne9** [comment]
Try this `themarysue.com##.cointent-gumshoe`

or

`@@||themarysue.com$elemhide`

**Comment by SMed79** [comment]
@AdBlockAshley Add: 
`||themarysue.com^$third-party`

**Comment by reek** [comment]
@bourne9 
@SMed79 
thanks

**Comment by MarkTheFucker** [comment]
`@@||themarysue.com$generichide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
