### ISSUE TITLE
http://zekamashi.net/

### ISSUE THREAD

**Issue by katsusand** [reek/anti-adblock-killer#1391]
http://zekamashi.net/201605-event/e-1-zensen/comment-page-1/ (Japanese page)
ublock origin+AAbkiller+aaklist
http://imgur.com/hIvWFTz

**Comment by bourne9** [comment]
Page doesn't seem to load for me, so try this - `@@||zekamashi.net$elemhide`

**Comment by reek** [comment]
No detected

**Comment by katsusand** [comment]
I think detects only Japanese filter.
https://adblock-plus-japanese-filter.googlecode.com/hg/html/subscribe.html
(Main filter and element-hide filter)
And Japanese fuck-adblock custom for WP.
I added ublock's whitelist and blocking ads on editing hosts. Thanks.

**Comment by bourne9** [comment]
No you were not supposed to whitelist the site damnit! Those filters I gave you, you were supposed to add them in My Filters section in settings in uBO

**Comment by reek** [comment]
Can you copy and paste message in screenshot, thanks

**Comment by katsusand** [comment]
(JAPANESE)
このサイトは広告費により運営されています。
広告ブロックを無効にしてください。

(Translation)
This website is managed by affiliate money.
Please disable adblock.

**Comment by reek** [comment]
I unable to find it in the source code.

I need the data mentioned below, thanks
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by katsusand** [comment]
Sorry. seems to be removed from server :(
no ##blockOverlay.blockUI (hit on last week.)
Source Code: http://paste2.org/ztPJLsUw
Extensions: ublockOrigin, Tampermonkey
Userscripts: Anti-Adblock Killer 
Blocked Resources: http://imgur.com/oEiKbLS

**Comment by MarkTheFucker** [comment]
`@@||zekamashi.net$elemhide`

**Comment by katsusand** [comment]
Thanks.
I'll close this issue.
