### ISSUE TITLE
canalwp.com

### ISSUE THREAD

**Issue by JulianoRossi3l** [reek/anti-adblock-killer#1392]
http://www.canalwp.com/
Screen: http://prntscr.com/azorls

FireFox (+Adblock Plus, +uBlock, +Greeasemonkey Anti-adblock Killer)

I wanted to learn how to solve these issues.
Thank you for now!

**Comment by bourne9** [comment]
Filter - `@@||canalwp.com$elemhide` - uBlock Origin

Filter - `@@||canalwp.com$generichide` - ABP

Remove uBlock or AdBlock Plus, running both will only harm you.

**Comment by reek** [comment]
@JulianoRossi3l 
Ok, I'll kill it, thanks

**Comment by MarkTheFucker** [comment]
`@@||canalwp.com$elemhide`

**Comment by JulianoRossi3l** [comment]
thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
