### ISSUE TITLE
[Fixed. Please ignore.] https://kissanime.to/

### ISSUE THREAD

**Issue by Quavelen** [reek/anti-adblock-killer#1394]
Edit: Nevermind. I obtained the script from the old ''userscript'' archive. It was out of date, and had errors within the coding. The version was like, 7.5 or something. The current one, obtain from this Github works properly. 

Sorry about this. I've never used Github before, so I'm really nooby to its functions and whatnot.

**Comment by bourne9** [comment]
kissanime, kisscartoon and sisters were fixed ;)

**Comment by reek** [comment]
@Quavelen 
Ok, no worries
