### ISSUE TITLE
q.gs

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#1398]
http://q.gs/A6gxF
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/15022069/32d43770-122a-11e6-9018-3cf1f8ca393c.PNG)
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by bourne9** [comment]
Update your AAK script and AAK list to the latest version, the website runs FuckAdBlock by sitexw which has already been patched.

**Comment by reek** [comment]
@adreporter 
Try with ABP

**Comment by adreporter** [comment]
Is there a solution for uBlock Origin?

**Comment by reek** [comment]
Try https://greasyfork.org/fr/scripts/4881-adsbypasser
