### ISSUE TITLE
narcity.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1400]
Hi,
sc: http://i.imgur.com/c9mWD2H.png
`@@||cdn.narcity.com/montreal/wp-content/themes/$script`
on `http://www.narcity.com/montreal/le-labyrinthe-exterieur-geant-pres-de-montreal-ou-tu-dois-absolument-aller-cet-ete/`

Thanks!

**Comment by bourne9** [comment]
That will only work for Montreal folder based blogs, you should be adding these for the whole site to work

`@@||cdn.narcity.com/toronto/wp-content/themes/narcity-theme/legal/ads.advert.js$script`
`@@||cdn.narcity.com/montreal/wp-content/themes/narcity-theme/legal/ads.advert.js$script`
`@@||cdn.narcity.com/vancouver/wp-content/themes/narcity-theme/legal/ads.advert.js$script`

**Comment by reek** [comment]
Thanks guys

**Comment by SMed79** [comment]
`@@||cdn.narcity.com/*/wp-content/themes/ad$script`
