### ISSUE TITLE
hey dude please check

### ISSUE THREAD

**Issue by anelafar** [reek/anti-adblock-killer#1401]
http://www.elmoslsal.com/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D9%86%D9%8A%D9%86-2/
http://codeclan.altervista.org/
http://antiblock.org/?p=v3&demo

**Comment by bourne9** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by SMed79** [comment]
@anelafar install **Greasemonkey** (firefox) or **Tampermonkey** and add the AakScript.
See Instruction https://github.com/reek/anti-adblock-killer#instruction
Also not forgot subscribe to 
- **AakList** http://reek.github.io/anti-adblock-killer/#filterlist
- **Liste AR** https://adblockplus.org/subscriptions (to block adverts on arabic websites).
