### ISSUE TITLE
VGTV.no, minmote.no

### ISSUE THREAD

**Issue by bakagringo** [reek/anti-adblock-killer#1402]
http://www.vgtv.no/#!/video/82612/se-hva-som-skjer-naar-mathias-filmer-kveiten
http://imgur.com/keFgFaB
Mozilla Firefox
Greasemonkey
Ublock Origin
EasyList + AakList

Added a few lines to fix some site design issues on vgtv where the video would be shown as a minature version when using Aaklist.
Also added minmote.no (Owned by vg.no) to the list to get rid of their  "disable adblock" message. 
   

http://pastebin.com/p6n4brxr

**Comment by bourne9** [comment]
Your screenshot doesn't show any evidence of anti adblock. So what is it exactly ?

**Comment by bakagringo** [comment]
For vgtv.no, the original script/adblock filter bugs up the website style.
For minmote.no and anti-adblock message element is displayted.

Screenshot for the pages without the suggested addons. 
http://imgur.com/a/wEaiR

The pastebin links shows how I tried to solve the "issues" as a suggestion, and the initial screenshot shows vgtv.no after that is implemented.

**Comment by bourne9** [comment]
Oh, okay.

 reek will fix the vg.no site's video appearance. 

For minmote - `minmote.no###advert-skyscraperleft_1
minmote.no###advert-skyscraperright_1
minmote.no##.share-facebook.share-link
minmote.no##.share-twitter.share-link
minmote.no##.adblock-info.advert-horseshoe`

**Comment by bakagringo** [comment]
Ok. Thanks.

**Comment by reek** [comment]
@bakagringo 
thanks I'll test

**Comment by MarkTheFucker** [comment]
minmote.no - `@@||acdn.adnxs.com/ast/ast.js$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
