### ISSUE TITLE
schoener-wohnen.de

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1403]
Hi, 
`http://www.schoener-wohnen.de/einrichten/38924-rtkl-der-grosse-loft-ratgeber`
→ http://i.imgur.com/PKgPq3k.png

`||connectormwi.laterpay.net^$third-party`

Thanks!

**Comment by bourne9** [comment]
filter - `@@||schoener-wohnen.de$elemhide`

or

filter - `||laterpay.net`

**Comment by reek** [comment]
thanks

**Comment by MarkTheFucker** [comment]
`@@||schoener-wohnen.de$elemhide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
