### ISSUE TITLE
zarabiajnaokazjach.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1404]
http://i.imgur.com/Cq5q3Oe.png
zarabiajnaokazjach.pl#@##adsense

**Comment by bourne9** [comment]
Filter - `@@||zarabiajnaokazjach.pl$elemhide`

**Comment by MajkiIT** [comment]
I tested zarabiajnaokazjach.pl#@##adsense and it's Ok.

**Comment by bourne9** [comment]
and I tested my own and that works too, you can use mine as an alternative.

**Comment by SMed79** [comment]
`@@||zarabiajnaokazjach.pl^$generichide`

**Comment by MarkTheFucker** [comment]
`@@||zarabiajnaokazjach.pl$elemhide`

**Comment by reek** [comment]
thanks guys

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
