### ISSUE TITLE
mrpiracy.club inline javascript detect deleted elements

### ISSUE THREAD

**Issue by daiquirimelao** [reek/anti-adblock-killer#1405]
I'm found a funny one, there's this site, for example: http://mrpiracy.club/filme.php?imdb=tt2978102

That blocks adblocker with this:

```
<script type="text/javascript"><!--
if(document.getElementsByTagName("iframe").item(0) == null)
{
    document.write("</div><div class='main-separator'></div><div class='content-box' style='width: 100%;padding-top: 20px;text-align: center;font-family: Tahoma;font-size: 16px;color: #545457;'>Parece que está a bloquear a publicidade. Desativa o AdBlock para continuar<br /><br /><span style='font-size:15px'>Desculpe mas dessa maneira não poderá ter acesso ao conteúdo,
.... );
	document.getElementById("deleted").remove();
	document.getElementById("deleted").remove();
}
</script>
```

I tired to block it with mrpiracy.club#script:contains(document.getElementsByTagName) but no success.

**Comment by bourne9** [comment]
Duplicate #1347

**Comment by SMed79** [comment]
Add:
```
||mrpiracy.club/images/*.gif
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=mrpiracy.club
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=mrpiracy.club
```

**Comment by reek** [comment]
@daiquirimelao 
Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
