### ISSUE TITLE
cbsnews.com

### ISSUE THREAD

**Issue by WangChristopherS** [reek/anti-adblock-killer#1406]
http://www.cbsnews.com/news/california-drought-blackhawk-homeowner-association-ordered-beautify-green-lawns/

![screen shot 2016-05-07 at 11 45 52 am](https://cloud.githubusercontent.com/assets/18157533/15093940/b61e0d1e-144a-11e6-8ad1-4508675e294a.png)

Please get rid of this. Thank you.

**Comment by bourne9** [comment]
Duplicate #1253

Also this- https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md

**Comment by SMed79** [comment]
@WangChristopherS try:
```
@@|http://$xmlhttprequest,domain=cbsnews.com
@@|http://$image,domain=cbsnews.com
@@||pubads.g.doubleclick.net^$object-subrequest,domain=cbsnews.com
```

**Comment by reek** [comment]
@SMed79 
Thanks

@WangChristopherS 
I'll add rules to AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
