### ISSUE TITLE
https://kissanime.to

### ISSUE THREAD

**Issue by Tartusi** [reek/anti-adblock-killer#1407]
Hi,

https://kissanime.to/Anime/Durarara-Dub/Episode-001?id=47963
anti-adblock starts after 2s (setTimeout('DoDetect1()', 2000);)

Maybe a better way exist but I block it by this way (can't remove the page there is some useful js):

www.kissanime.to##script:contains(DoDetect1)

**Comment by bourne9** [comment]
Update AAK Script and AAK Filterlist, Already patched - #1394

**Comment by reek** [comment]
Thanks, but already killed by AakScript.
