### ISSUE TITLE
SYNTAX ERROR LINE 652: "EVAL CAN BE HARMFUL"

### ISSUE THREAD

**Issue by zz1z** [reek/anti-adblock-killer#1408]
When running syntax check on ver 9.5, gives error:

SYNTAX ERROR LINE 652: "EVAL CAN BE HARMFUL"

line 652:
return (/function[(][pm],[au],[cn],[kg],[e],[dr][)]/.test(source)) ? eval(source.trim().replace('eval(', '(').replace(';return p}', ';return p;}')) : false;

Not sure how severe it is?

**Comment by bourne9** [comment]
Why are you running syntax check in the first place and for what purpose

**Comment by reek** [comment]
@zz1z 
I know but this is not an error.
