### ISSUE TITLE
iosworld.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1409]
solution
@@/plugins/ad-blocking-detector/assets/js/advertisement.min.js$script,domain=iosworld.pl

**Comment by bourne9** [comment]
Care to post a screenshot for once ?

Filter - `iosworld.pl##.ad-custom-size.ad`

**Comment by MajkiIT** [comment]
It's not problem to me. I always report issue and solution like this. Something has change?

**Comment by bourne9** [comment]
You don't follow the format made by reek, so it irks me. The format for posting issues was made for a reason. It won't kill you if you post the issue with the solution in a proper format and not like this. I hope you will understand.

**Comment by SMed79** [comment]
Add:
`/ad-blocking-detector/*`

**Comment by MarkTheFucker** [comment]
`@@||iosworld.pl/plugins/ad-blocking-detector/assets/js/advertisement.min.js$script`

**Comment by reek** [comment]
Thanks guys

**Comment by reek** [comment]
it already has a rule about it
https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt#L122
