### ISSUE TITLE
vizer.tv

### ISSUE THREAD

**Issue by VPagani** [reek/anti-adblock-killer#1411]
http://vizer.tv/serie-The-Walking-Dead.html
https://i.snag.gy/VDlRnh.jpg
Google Chrome 50.0.2661.94 (64-bit)
Tampermonkey
Adblock
EasyList + AakList

**Comment by bourne9** [comment]
@VPagani 

Filtr - `@@||http://vizer.tv/js/ads.js$script`

**Comment by reek** [comment]
I'll kill it, thanks

**Comment by MarkTheFucker** [comment]
`vizer.tv##.adBlockDetected`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
