### ISSUE TITLE
alphahistory.com

### ISSUE THREAD

**Issue by 123467890** [reek/anti-adblock-killer#1412]
http://alphahistory.com/nazigermany/hello-adblock-user/
[image](https://cloud.githubusercontent.com/assets/19258484/15102980/de42de44-155a-11e6-8025-57229828f4ac.png)
Google Chrome
Tampermonkey
Ublock Origin
Aak list +easylist +easyprivacy

**Comment by bourne9** [comment]
Filter - `||googlesyndication.com`

**Comment by SMed79** [comment]
Add: 
`@||alphahistory.com^$generichide`

**Comment by reek** [comment]
@123467890 
Ok, I'll kill it, thanks

**Comment by MarkTheFucker** [comment]
`@@||alphahistory.com$elemhide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
