### ISSUE TITLE
www.vg.no

### ISSUE THREAD

**Issue by dooniem** [reek/anti-adblock-killer#1413]
http://www.vgtv.no/#!/video/127514/the-staircase-2-the-last-chance
http://imgur.com/8CJXUf5
Google Chrome
Tampermonkey
uBlock Origin
ublock filters - badware risks + anti-Adblock Killer | Reek + EasyList + Peter Lowe's Ad server list + EasyPrivacy + Malware Domain List + Fanboy's Social Blocking List + AakList (Anti-Adblock Killer)

**Comment by SMed79** [comment]
Hi, 
try to add:
`@@||acdn.adnxs.com/ast/ast.js$script,domain=vgtv.no`

**Comment by bourne9** [comment]
Add this `@@||svp.vgc.no/web/vgtv/js/web-60546dba32.js$script`

**Comment by dooniem** [comment]
Thanks for replying!
I added your code to "My filters" in uBlock Origin. Not sure if that's the right place? :worried: 
Though it seems the web page don't recognize my adblocker, I still get 2 "video ads" before the actual video starts. Maybe this is outside the scope of this support forum and outside of what anti-adblock-killer is supposed to do. But maybe you have the knowledge I don't have?

**Comment by sveip** [comment]
Tried to add  `@@||acdn.adnxs.com/ast/ast.js$script,domain=vgtv.no` to my custom filters in ABP, but it did not make a difference.

**Comment by SMed79** [comment]
@sveip keep only your adblocker / blocking extension enabled and test againe.

**Comment by sveip** [comment]
Same behavior @reek. Tried to adjust the filter, but no luck.

2016-06-14 22:24 GMT+02:00 Med <notifications@github.com>:

**Comment by simonkaspersen** [comment]
I also have this issue. ABP and this script. 
It just ruins the page when having it active, and present big blue banners if not

**Comment by SMed79** [comment]
The filter i posted is to remove the anti adblock (red background) and not the video ad.
https://forums.lanik.us/viewtopic.php?f=62&t=32005

**Comment by reek** [comment]
@SMed79  thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
