### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by mozkan007** [reek/anti-adblock-killer#1414]
URL: http://www.spaste.com/go/yIOPs9
Screenshot: http://imgur.com/HuYTBk1
Browser: Google Chrome v50
Script Manager: None
Adblocker: uBlock Origin v1.7.2
Filter lists: Easy List, uBlock filters‎, Anti-Adblock Killer | Reek, Peter Lowe’s Ad server list, Easy Privacy, Adblock Warning Removal List (All filtesr are updated)

Hi.I am getting a warning that to disable the ad-blocker after I confirmed the captcha.Thanks.

**Comment by bourne9** [comment]
You need to install TamperMonkey Script Manager chrome extension and then install AAK script, obviously AAK list will not work without AAK Script and you need Tampermonkey for executing the script.

**Comment by mozkan007** [comment]
But until now this filter was working like a clockwork on spaste.com despite not installed any script manager.Also AAK filter still working on the other sites.

**Comment by bourne9** [comment]
I dont know how it worked w/out TamperMonkey but's it's not supposed to.
Also the static filter will work without TamperMonkey, so that must be it.

https://github.com/reek/anti-adblock-killer#instruction
Follow the steps and install it.

**Comment by reek** [comment]
Already killed by AakList
