### ISSUE TITLE
tv3play.no not working and updated ads in player

### ISSUE THREAD

**Issue by iNFaMoUZGaming** [reek/anti-adblock-killer#1415]
When using anti-adblock the play won't load at all and it detect ublock, I can't find a way around this, help? 

http://www.tv3play.no/programmer/paradise-hotel/732208?autostart=true

Here's an episode

**Comment by reek** [comment]
please rad report guide

**Comment by SMed79** [comment]
check also https://forums.lanik.us/viewtopic.php?f=62&t=29140

**Comment by bourne9** [comment]
features FuckAdBlock hmmm

**Comment by bakagringo** [comment]
Does it work at all for you? Even with all forms of adblock off it doesn't load videos here.

**Comment by reek** [comment]
@iNFaMoUZGaming 
Sorry, the problem is caused by AakScript, I'll add an exception

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
