### ISSUE TITLE
papewall.com

### ISSUE THREAD

**Issue by krunox123** [reek/anti-adblock-killer#1417]
https://www.papewall.com/ (all page to be precise)
http://imgur.com/t8XbYSC
Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by MarkTheFucker** [comment]
`@@||papewall.com$generichide
@@.jpg|$image,domain=papewall.com
@@.ico|$image,domain=papewall.com`

**Comment by krunox123** [comment]
@MarkTheFucker I've tried that too like a few hours ago, but it won't work.

**Comment by MarkTheFucker** [comment]
works fine here on uBlock

**Comment by krunox123** [comment]
@MarkTheFucker It's my first time using ublock, am I doing it right? http://imgur.com/36LVbCH

**Comment by MarkTheFucker** [comment]
for uBlock it is `$elemhide` instead of `$generichide` and **disable** or **uninstall** AdBlock Plus if you're using uBlock now

**Comment by krunox123** [comment]
@MarkTheFucker but it still work though :open_mouth:

Thanks.

**Comment by MarkTheFucker** [comment]
uBlock offers AdBlock Plus compatibility with custom filters so adblock plus filters will work too I guess ;)

**Comment by reek** [comment]
@krunox123 
I'll kill it, thanks

**Comment by krunox123** [comment]
@reek Thanks :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
