### ISSUE TITLE
ouest-france.fr

### ISSUE THREAD

**Issue by Francois-dag** [reek/anti-adblock-killer#1418]
today ouest-france.fr as started to invite users to disable adblock.

Cheers.

**Comment by MarkTheFucker** [comment]
`@@||ouest-france.fr/sites/all/themes/base/js/adblock.js$script`

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Francois-dag** [comment]
thanx a lot !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
