### ISSUE TITLE
Godt.no

### ISSUE THREAD

**Issue by bakagringo** [reek/anti-adblock-killer#1419]
Same as vg.no
http://www.godt.no/#!/oppskrift/7534/Asiatisk+risnudelsalat+med+reker&xtor=CS1-2-7534[Asiatisk+risnudelsalat+med+reker]
http://imgur.com/kcUDrXV
Mozilla Firefox
Greasemonkey
Ublock Origin
EasyList + AakList

**Comment by MarkTheFucker** [comment]
`@@||acdn.adnxs.com/ast/alpha/0.3.5/ast.js$script`

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
