### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by DBGulp** [reek/anti-adblock-killer#1421]
http://www.spaste.com/p/?c=C2sfIR1972
http://imgur.com/1C6GUFi
Mozilla Firefox & Google Chrome
No script manager
uBlock Origin - both browsers
Same filters - both browsers
uBlock filters‎, uBlock filters – Badware risks, uBlock filters – Privacy‎, uBlock filters – Unbreak‎, Adblock Warning Removal List‎, Anti-Adblock Killer | Reek‎, Peter Lowe’s Ad server list‎, Basic tracking list by Disconnect‎, EasyPrivacy‎, Fanboy’s Enhanced Tracking List‎, Malvertising filter list by Disconnect‎, Malware Domain List‎. Malware domains‎, Malware filter list by Disconnect‎, Fanboy’s Annoyance List,
Fanboy+Easylist-Merged Ultimate List‎

No problem yesterday. Today, I submit the captcha and briefly see the links then the adblock warning. AakList is enabled and up to date under 3rd-party filters - uBO for both browsers.

**Comment by reek** [comment]
You must install TamperMonkey and AakScript to kill FuckAdblock Script

**Comment by DBGulp** [comment]
Thank you!
