### ISSUE TITLE
mmm.dk

### ISSUE THREAD

**Issue by Darkspider47** [reek/anti-adblock-killer#1422]
http://mmm.dk
http://i.imgur.com/eFaFh86.png
Google Chrome
Tampermonkey
Adblock
AakList

**Comment by MarkTheFucker** [comment]
try - `@@||mmm.dk$elemhide`

**Comment by Darkspider47** [comment]
Where do i add it? can't find anything under filterlist

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
