### ISSUE TITLE
Can Not Able to watch Wrestling Issue 

### ISSUE THREAD

**Issue by ameliawarner1992** [reek/anti-adblock-killer#1424]
Can Not Able to watch Wrestling Issue Adblock not wotking
[http://watchwrestling.in/sports/wwe/](http://watchwrestling.in/sports/wwe/)
https://imgur.com/viQpet9
Mozilla Firefox
Greasemonkey
Adblock Plus
Ablock Warning Removal List + EasyList + EasyPrivacy + Disable Malware + AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
what video, because I have no anti-adblock message ?

**Comment by ameliawarner1992** [comment]
now working fine here too .......
