### ISSUE TITLE
folha.uol.com.br

### ISSUE THREAD

**Issue by JulianoRossi3l** [reek/anti-adblock-killer#1425]
http://www1.folha.uol.com.br/paywall/adblock.shtml?http://www1.folha.uol.com.br/
Screen: http://prnt.sc/b34o9y

FireFox (+Adblock Plus, +Greeasemonkey Anti-adblock Killer)

Thank you for now!

**Comment by reek** [comment]
Duplicated: https://github.com/reek/anti-adblock-killer/issues/1396

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
