### ISSUE TITLE
http://www.inc.com

### ISSUE THREAD

**Issue by WangChristopherS** [reek/anti-adblock-killer#1431]
![screen shot 2016-05-13 at 7 59 13 am](https://cloud.githubusercontent.com/assets/18157533/15251983/c5fb67b4-18e0-11e6-8995-68885523b7a8.png)

I disable Adblock and the article shows. I enable Adblock and it shows this screen. Please kill this. Thank you.

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**
`@@||inc.com//js/ads.js$xmlhttprequest`
`inc.com#@#.WideAdContainer`
`inc.com#@#.padvertlabel`
**or**
`@@||inc.com^$elemhide`
`@@||inc.com//js/ads.js$xmlhttprequest`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
