### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by marco-c** [reek/anti-adblock-killer#1432]
http://www.spaste.com/p/?c=wKJ4q22587
Mozilla Firefox
No script manager
AdBlock Plus
EasyList + AakList

**Comment by reek** [comment]
install Greasemonkey + AakScript

**Comment by marco-c** [comment]
Which kinds of websites can't be blocked by a filter and need a user script?

**Comment by reek** [comment]
it depends on the mechanism used
