### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by Sphincone** [reek/anti-adblock-killer#1434]
Test with this: http://www.spaste.com/p/?c=qax9mp9725

![chrome_2016-05-14_19-36-28](https://cloud.githubusercontent.com/assets/8825262/15268277/150366a2-19fb-11e6-81c0-294e28c4aea9.png)

They are using adsBlockerDetected function in js.

**Comment by reek** [comment]
Already killed by AakList

**Comment by Sphincone** [comment]
@reek Already using AakList in uBlock Origin but it's not working. Possibly they are using a new function?

**Comment by reek** [comment]
it's ok for me with uBlock, see https://github.com/reek/anti-adblock-killer#help

**Comment by Sphincone** [comment]
@reek Do I need to enable it in ublock and install the script via tampermonkey at the same time?

**Comment by reek** [comment]
Yes

**Comment by dh33r4j** [comment]
@reek I have it enabled in ublock and I continue to face the same issue. Could it be due to the other filters I use? http://imgur.com/dOc2UCG

**Comment by reek** [comment]
@dh33r4j 
Maybe, try only EasyList, AakList and EasyPrivacy or check https://github.com/reek/anti-adblock-killer#help

**Comment by RZeroX** [comment]
I tried using only easylist and AakList on ublock Origin but it doesn't seem to work it say disable your adblock.

**Comment by RZeroX** [comment]
@reek 
I tried using only easylist and AakList on ublock Origin but it doesn't seem to work it say disable your adblock.

**Comment by reek** [comment]
@dh33r4j 
Maybe, try only EasyList, AakList and EasyPrivacy or check https://github.com/reek/anti-adblock-killer#help

**Comment by maynak00** [comment]
site catch adblocker after correct captcha
**please add this:**
`||spaste.com/themes/site/fuckadblock.js$script,important`
*added ",important" for block (skipping @@||spaste.com^$script)
problem: Static filter @@||spaste.com^$script found in:EasyList

**Comment by reek** [comment]
@maynak00 
report to https://forums.lanik.us/

**Comment by maynak00** [comment]
@reek  , thanks. reported to EasyList official forum.
**fixed with:**
`@@||spaste.com^$generichide`
`||taboola.com^$domain=spaste.com`
*source: https://forums.lanik.us/viewtopic.php?f=62&t=30971

**Comment by reek** [comment]
@maynak00 
Thanks, I'll add it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
