### ISSUE TITLE
rte.ie/player

### ISSUE THREAD

**Issue by conndarcy** [reek/anti-adblock-killer#1435]
http://www.rte.ie/player/ie/

It works fine for normal ads on the site, doesn't work for the video ads. The screenshot shows what happens when you try to play a video.

http://i.imgur.com/oCgPdYr.png

Google Chrome
TamperMonkey
uBlock Origin
EasyList + AakList

**Comment by Giwayume** [comment]
I am able to reproduce in Chrome, however nothing is blocked in Firefox.

**Comment by Giwayume** [comment]
Are video ads infrequent on this site? I've clicked on 10 videos and I haven't encountered that message in your screenshot.

**Comment by conndarcy** [comment]
Turns out it's not ublock that was causing it, it was ghostery. It works fine with ghostery disabled.
