### ISSUE TITLE
sc2casts.com

### ISSUE THREAD

**Issue by msuces** [reek/anti-adblock-killer#1436]
Doesn't work on Opera. Tried both Tampermonkey and Violentmonkey.

I'm a new user, but I don't think it was something wrong with my configuration because I did the same steps and managed to get it to work on Chrome. Both my Opera and Chrome are new installs (no other extensions).

**Comment by reek** [comment]
Ok, I'll fix it, but next time read report guide

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
