### ISSUE TITLE
3dsthem.es

### ISSUE THREAD

**Issue by m2pt5** [reek/anti-adblock-killer#1437]
Has a particularly persistent anti-adblock script in the main.js that the site uses for just about everything, if it detects either of the ad banner blocks are removed (which contain text with obnoxiously huge box-shadow css if the ads are blocked), it wipes the page and replaces it with a big whiny message.

**Comment by ErmanSayin** [comment]
boo hoo

**Comment by lewisje** [comment]
I saw these three uBlock Origin rules floating around 4chan's /hbg/ thread that might work:

    3dsthem.es###adblockpls
    ||3dsthem.es/js/ads.js$script,first-party,important
    @@||3dsthem.es/js/ads.js

If you use a lesser ad-blocker that lacks support for `$important`, consider this near-equivalent:

    3dsthem.es###adblockpls
    @@||3dsthem.es/js/ads.js$~script,third-party

**Comment by m2pt5** [comment]
The page's main.js seems to be set so that it blanks the page and throws up the big "please disable your adblocker" message if 'adblockpls' is removed from the page, ads.js appears to be nothing but a single var declaration, and removing/resizing/replacing the #pw_adbox_77830_5_0 doesn't work either. The adblock checker is right near the top of the /js/main.js.

**Comment by reek** [comment]
@m2pt5 
@lewisje 
https://github.com/reek/anti-adblock-killer/issues/1433#issuecomment-219288933

**Comment by reek** [comment]
Patched (Raw to install)
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by usagirei** [comment]
Someone tried to patch it again, two times today so far, and failed to do so.

He'll try to detect if the setInterval was tampered with, so the above fix won't work now.

Here's my usescript specific for it so far: [Userscript](https://gist.github.com/usagirei/57494db176cb9ecab73fc20af3103f46)

**Comment by reek** [comment]
@usagirei 
Well done :+1:
