### ISSUE TITLE
Ilta-Sanomat

### ISSUE THREAD

**Issue by samunufrik** [reek/anti-adblock-killer#1438]
This is a Finnish newspaper (yellow news). Their videos don't work because of Adblock Killer scripts.

See for instance the video on top of this page: http://www.iltasanomat.fi/sm-liiga/art-2000001164876.html

The red text at the top of where the video is supposed to be means "Please disable your adblocker to see the video".

Chrome
Greasemonkey
Ublock
EasyList + AakList (+ a bunch of others)

**Comment by reek** [comment]
add this rule
<code>@@||adserver.adtech.de/?advideo/*$xmlhttprequest,domain=iltasanomat.fi</code>
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
