### ISSUE TITLE
forum.kooora.com

### ISSUE THREAD

**Issue by JSPAS** [reek/anti-adblock-killer#1439]
If enable uBlock Origin Disconnect
http://i.imgur.com/9OjHNiY.png
if disable uBlock Origin Disconnect
http://i.imgur.com/IZpqlDc.png
Chrome
Tampermonkey
uBlock Origin
Disconnect

**Comment by Giwayume** [comment]
I am able to reproduce in Chrome, however nothing is blocked in Firefox.

**Comment by reek** [comment]
Try rule
<code>@@||partner.googleadservices.com/gpt/pubads_impl_*.js$script,domain=forum.kooora.com</code>

https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by JSPAS** [comment]
Still not work

**Comment by reek** [comment]
Disable Disconnect

**Comment by SMed79** [comment]
Already fixed by **Liste AR** (القائمة العربية لمانع الشرائط الإعلانية) [8 months ago](https://hg.adblockplus.org/listear/rev/69f7d3acd775), now just remove disconnect and subscribe to easyprivacy and Liste AR from: http://adblockplus.org/subscriptions

**Comment by JSPAS** [comment]
Still not work

**Comment by SMed79** [comment]
> Still not work

No issue here http://i.imgur.com/PrJxQ7R.png try to reset your browser to default settings.

**Comment by JSPAS** [comment]
i delete uBlock Origin and add it again work thank for help

**Comment by SMed79** [comment]
Filter pushed from [Liste AR](https://hg.adblockplus.org/listear/rev/eead2b13aa46) to [Easylist](https://github.com/easylist/easylist/commit/3b840a4b8396ea2236f46ccc6d2c2786623f8d93).

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
