### ISSUE TITLE
8muses.com

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#1440]
Javascript detects adblocker and sets a cookie.
http://i.imgur.com/LUCFuai.png

Once you refresh the page the server detects the "session5" cookie was modified and sends you this HTML directly.
http://i.imgur.com/6UwgwzW.png

It looks like the existing script needs to be updated. `var` should be added before `_setTimeout`. I'm not entirely sure why this breaks without it.

Fix:
```
_8muses_com : {
        // issue: https://github.com/reek/anti-adblock-killer/issues/1226
        // issue: https://greasyfork.org/forum/discussion/8515
        // issue: https://github.com/reek/anti-adblock-killer/issues/1099
        // issue: https://greasyfork.org/en/forum/discussion/6407
        // source: http://pastebin.com/bMNDxecs
        host : ['8muses.com'],
        onStart : function () {
          Aak.addScript(function() {
            var _setTimeout = window.setTimeout;
            window.setTimeout = function (fn, delay) {
                if (fn.indexOf("$(window).trigger('adblock');") > -1) {
                  return;
                }
                _setTimeout.apply(fn, delay);
            };
          });
        }
      },
```

**Comment by reek** [comment]
I understand why the v9.6 is executed in strict mode, thank you this will allow me to make a small revision of the code

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
