### ISSUE TITLE
filechoco.com

### ISSUE THREAD

**Issue by tejuu** [reek/anti-adblock-killer#1441]
The website www.filechoco.com is able to detect my adblocker even with the greasefork extension.
![filechoco](https://cloud.githubusercontent.com/assets/19390236/15291790/51175894-1b9d-11e6-8328-c3538bbaadc5.png)

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
