### ISSUE TITLE
hentaihaven.org

### ISSUE THREAD

**Issue by baka-bukakke** [reek/anti-adblock-killer#1442]
hentaihaven.org is messed up when accessed, I'm using google chrome browser and tampermonkey, everything else is updated. pls fix sir

![hentaihaven org_](https://cloud.githubusercontent.com/assets/19391888/15294708/ef1cf14e-1bbf-11e6-99ad-493487bd712f.png)

**Comment by SMed79** [comment]
Links to **X** Rated sites or sites containing Adult content should contain a **NSFW** in the subject.

**Comment by reek** [comment]
@baka-bukakke 
No problem for me

**Comment by maynak00** [comment]
@reek , adblocker detected for my test
![2016-05-17_103013](https://cloud.githubusercontent.com/assets/6183830/15314463/9c6ff5ee-1c1a-11e6-8cd7-f1d78b0ac02f.png)

@baka-bukakke , **try with:**
`@@||hentaihaven.org/*/adshow.js`

**Comment by baka-bukakke** [comment]
@maynak00 can you teach me how to use that sir?

**Comment by reek** [comment]
@maynak00 
killed by AakScript <code>var canRunAds=true;</code>

**Comment by reek** [comment]
@baka-bukakke 
Your adblocker and filterlists

Have you created custom filters ?

**Comment by baka-bukakke** [comment]
@reek my filter list "easy list" seems to be the one causing the messy layout of the site, disabling it will just show the ads. I'm just gonna use the old 9.5 version. Can you pls make backup of the versions before

**Comment by reek** [comment]
@baka-bukakke 
Code -> Branch master -> Tags and select version.

It's all the same strange that you have this layout and not me.

Here is my config: Firefox, Greasemonkey, Adblock Plus with EasyList, AakList, EasyPrivacy.

**Comment by baka-bukakke** [comment]
@reek must be my fvcking chrome, when I tested it on my firefox everything worked just fine

**Comment by reek** [comment]
@baka-bukakke  Ok, I close issue
