### ISSUE TITLE
ew.com

### ISSUE THREAD

**Issue by damnnative** [reek/anti-adblock-killer#1444]
Chrome 50
Tampermonkey + Aak
Adblock Plus + Aak

URL:
http://www.ew.com/article/2015/03/12/last-man-earth-video-outtakes-reveal-hilarious-difficulties-shooting-fox-comedy

Videos detect adblocking

http://i.imgur.com/nhMg1Ca.png

**Comment by SMed79** [comment]
@damnnative Content expired here http://i.imgur.com/lslbaZh.png
From where you are browsing this website?
