### ISSUE TITLE
vipbox.nu

### ISSUE THREAD

**Issue by jesterpaul** [reek/anti-adblock-killer#1448]
Hi team,

http://www.vipbox.nu/

the site listed in subject (formerly vipleague) is detcting anti-adblock again (constant arms race, I know)  

Details:

Browser Mozilla Firefox ERS 45.1.1 (Mac OS X)
Extensions: Greasemonkey, Adblock Plus. Adblock Plus pop-up addon, Diagnostics for Adblock Plus, Disable anti-adblock.
Scipts: anti-adblock killer |  Reek 9.6
Filter lists: EasyList + AakList
Screenshot: http://imgur.com/BCkpzZS

Same issue with latest Chrome Browser using Tapermonkey and the same scripts and list subscriptions as I have on FF

**Comment by reek** [comment]
Ok, I'll add it, thanks.

**Comment by jesterpaul** [comment]
Using the above extensions and scripts on Chrome this site now also adds a banner stating Ublock has been detected (I am not using Ublock)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
