### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by OneEyeDoll** [reek/anti-adblock-killer#1449]
http://imgur.com/X4UPu4G
Greasemonkey

**Comment by Giwayume** [comment]
I can't even see the website. It appears some geo blocking is involved.

![screenshot from 2016-05-18 18-14-01](https://cloud.githubusercontent.com/assets/4075314/15376673/7ade24a4-1d24-11e6-9e12-9cf1a1c75238.png)

**Comment by skull1** [comment]
you should solve the geo block with an italian proxy

**Comment by OneEyeDoll** [comment]
I'm with an italian connetion.

**Comment by reek** [comment]
Geolock
