### ISSUE TITLE
smashboards.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#145]
http://smashboards.com/threads/does-the-3ds-version-have-the-same-feel-as-the-wii-u-version.384736/

smashboards.com###noticeMain

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by anonsubmitter** [comment]
Hmm. It looks like the "We know you don't like ads. Why not buy premium?" banner at the bottom of the thread only shows up for Adblock users. Could you add that to the filter as well?

smashboards.com##DIV[style="position: relative; min-height: 90px; margin-bottom: 10px;"]
or
smashboards.com##DIV[align="center"]

^ Both of these work, but maybe the first one is better since it's more specific and less likely to block other content if the site were to update it's layout? I don't know, I'll let you decide.

**Comment by reek** [comment]
Done
