### ISSUE TITLE
ksl.com

### ISSUE THREAD

**Issue by rixt3r862** [reek/anti-adblock-killer#1450]
https://www.ksl.com/myAds/listing-classified
Chrome
TamperMonkey
ABP
Only filtering: cbs, forbes, hulu

![ksladblock](https://cloud.githubusercontent.com/assets/19433443/15365930/57414ebc-1cdf-11e6-8563-541a7a5a64e0.jpg)

**Comment by Giwayume** [comment]
Requires a login.

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by maynak00** [comment]
**Problem:** Static filter /myads/* found in: EasyList
**Try with:**
`@@||ksl.com/myAds/*`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
