### ISSUE TITLE
pcgames-download.net

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1451]
Hi, 
`http://pcgames-download.net/`  » http://i.imgur.com/WZRgHGx.png

`@@||jsc.mgid.com^*/pcgames-download.net$script,domain=pcgames-download.net`

Thanks.

**Comment by reek** [comment]
I'll fix it, thanks

**Comment by Avigoku** [comment]
thanks bro, i need this.,it is working.
