### ISSUE TITLE
nrj.fr

### ISSUE THREAD

**Issue by JulienS3** [reek/anti-adblock-killer#1452]
Hello,

On the website [http://www.nrj.fr/](http://www.nrj.fr/)

When you load the page, it work well. But when you click on a webradio or the play button bellow, the page is dark because an ad is supposed to load, and the radio start after the add. But with adblock, and adblock killer, it kill the anti-addblock, but the ad doesn't load, so the radio never play on.

<img src=http://puu.sh/oXHf0.jpg></img>

Without adblock

<img src=http://puu.sh/oXHip.jpg></img>

Thanks !

**Comment by SMed79** [comment]
@JulienS3 please try these filters: 
```
nrj.fr###preroll
nrj.fr##[class^="modal"]
```

**Comment by JulienS3** [comment]
Hi,
When do I add this option ? In user exclusion, inclusion ?
I've tried all, and it still doesn't work.

<img src="http://puu.sh/p1kOZ.png"></img>

**Comment by JulienS3** [comment]
Hi,

Okay, i've added it to my filter list but it still doesn't work
I've tried in tampermonkey in all the filters of Anti Adblock Killer but nothing happened. 
<img src="http://puu.sh/p1o0b.png"></img>

**Comment by SMed79** [comment]
Try using firefox.

**Comment by reek** [comment]
@JulienS3 
Report to https://forums.lanik.us/
