### ISSUE TITLE
wsj.com

### ISSUE THREAD

**Issue by Drflash55** [reek/anti-adblock-killer#1454]
http://www.wsj.com/
http://i.imgur.com/9wxvIo8.png
Google Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by Giwayume** [comment]
This will hide the overlay.

`wsj.com##.lightbox`

Don't know if they're using it for anything non-ad related.

**Comment by reek** [comment]
@Drflash55 
Ok, I'll kill it, thanks

@Giwayume 
instead I will block this <code>||online.wsj.com/javascript/abm.js$script</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
