### ISSUE TITLE
epicurious.com

### ISSUE THREAD

**Issue by locustcox** [reek/anti-adblock-killer#1455]
http://www.epicurious.com/recipes/food/views/pad-thai-380593

**Comment by Giwayume** [comment]
I don't see a problem.

https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by locustcox** [comment]
Sorry, I forgot to specify: The anti-adblock script doesn't load until you
scroll down.

**Comment by Giwayume** [comment]
I see it now. Had to switch to chrome.

**Comment by Giwayume** [comment]
It looks like they're only using the `.tp-modal` styles for the adblocking modal, and not for their other modals like login/signup. It can likely be hidden safely. 

```
      epicurious_com : {
        host : ['epicurious.com'],
        onStart : function() {
          Aak.addStyle(".tp-modal-open { overflow: visible; } .tp-modal,.tp-backdrop { display: none; }");
        }
      },
```

**Comment by locustcox** [comment]
Ah, I see. Appreciate it!

**Comment by reek** [comment]
@Giwayume :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
