### ISSUE TITLE
nbc.com

### ISSUE THREAD

**Issue by Zerauskire** [reek/anti-adblock-killer#1456]
http://www.nbc.com/saturday-night-live/video/may-7-brie-larson/3027736?fe=1
http://imgur.com/qj77YfY
Google Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by Giwayume** [comment]
I've got the same setup as you and I'm not getting that message. Does it appear before the video starts or during one of the advertisement breaks?

**Comment by Zerauskire** [comment]
It appears from the start just like the screenshot I posted and then the video starts in the background while that message sits on top as a transparent overlay (like a watermark). I can see through it but the message stays on top. I can use the extension "dynamite" to remove the overlay so it's not really that big of a deal. I just thought I'd report it. 

It doesn't happen on all videos of NBC. Just some. Maybe I have another extension causing this to be detected this way? I do have a flashblock extension but I did try disabling it. Maybe I'll try disabling all my extensions and try again.

**Comment by Giwayume** [comment]
Can you can provide a CSS selector for the overlay?

**Comment by reek** [comment]
@Zerauskire 
Try these rules
<pre>
! check adblock
@@||nbcudigitaladops.com/hosted/pubads.js$script,domain=nbc.com
</pre> 
or 
<pre>
! hide overlay
nbc.com##.video-player__overlay.video-player__overlay--pause
nbc.com##.video-player__overlay.video-player__overlay--mute
</pre>

@Giwayume 
The first rule should nevertheless be good but do not work for me, I have to completely disable ABP, the code that adds overlay is here. https://paste2.org/w489KfGW line: 46520
