### ISSUE TITLE
linkdecode.com

### ISSUE THREAD

**Issue by DjDiabolik** [reek/anti-adblock-killer#1458]
Example of link:
http://www.linkdecode.com/?maemoaZsYGKYmp%2BXpJaWn2GVoKBhkqqhnZSgmGOfop1q

It's a android app....... I obtain the warning for not use ADBlock and i can't see the counter from 10 to 0 for download starting.

I need to disable ADBlock Plus for obtain the download start.........

Please add this site........

I have the AntiBlock Script 9.6 added on GreaseMonkey and the latest and upgraded filter installed..... 

Thanks in advance...

**Comment by DjDiabolik** [comment]
here for screenshot:
http://i.imgur.com/M9izcy7.png

When i disable ABP the page it's the same but after some seconds i can see the download counter left and download start... whit ADB Active no count appears........

**Comment by maynak00** [comment]
please follow this first: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
no antiadblock detected message for me(Chromium+uBlock Origin+Tampermonkey Beta)
off-topic: also skipped to last with script: AdsBypasser (https://adsbypasser.github.io/)

**Comment by DjDiabolik** [comment]
> please follow this first: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
no antiadblock detected message for me(Chromium+uBlock Origin+Tampermonkey Beta)
off-topic: also skipped to last with script: AdsBypasser (https://adsbypasser.github.io/)

I have followed the report guide............ i have insert the screenshot..... and i have put my info about browser........ and i have explain what's append on this link:
You don't see any antiadblock........but when ABP it's active there's no download countdown start.... for obtain the download i need to disable ABP.

I have tryed whit firefox 46.0.1 + GreaseMonkey & script 9.6

Ando also on latest version of Chrome + Tampermonkey whit same result... no download countdown when ABP it's active for linkdecode.com.....

**Comment by DjDiabolik** [comment]
Otherwise i have installed the Adsbypasser full and now i obtain the zippyshare or the download link immediatelly! Great suggestion.........

**Comment by reek** [comment]
@DjDiabolik 
add rule <code>linkdecode.com#@#.adsbygoogle</code>
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by DjDiabolik** [comment]
Also great sugggestion after adsbypasser :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
