### ISSUE TITLE
https://mangastream.zlx.com.br/

### ISSUE THREAD

**Issue by rafaelsetti1** [reek/anti-adblock-killer#1459]
http://imgur.com/nvYLcn8
Greasemonkey
uBlock Origin

the message appears only on pages like this: https://mangas.zlx.com.br/ler-bleach-online/capitulo-674/97604-scansproject#/!page10

only press > arrow key for the message show up

**Comment by reek** [comment]
sorry, the site redirects no Brazilians users to http://www.aliancaproject.com.br/
