### ISSUE TITLE
mathportal.org

### ISSUE THREAD

**Issue by SmartManoj** [reek/anti-adblock-killer#1460]
http://www.mathportal.org/calculators/solving-equations/quadratic-equation-solver.php

**Comment by Giwayume** [comment]
Filters:
`mathportal.org/temp/blocked/blockedCounter.php`
`mathportal.org###noSenseCalculatorTop`

**Comment by reek** [comment]
@Giwayume 
Thanks for rules

@SmartManoj 
Ok, I'll kill it, but next time read report guide

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
