### ISSUE TITLE
vrank.org

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1461]
Hi, 

http://i.imgur.com/PEvtkPK.png
https://forums.lanik.us/viewtopic.php?f=62&t=30502

`@@||vrank.org^$script`

Thanks.

**Comment by reek** [comment]
thank you, but this rule seems to me more appropriate
<code>||vrank.org/go/adblock_detect$subdocument</code>

**Comment by SMed79** [comment]
Good catch ! or more generic : 
`/adblock_detect|$subdocument`
