### ISSUE TITLE
yourlifeupdated.net

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#1462]
http://www.yourlifeupdated.net/
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/15451422/2808838c-1fc2-11e6-98fe-e0593dc656cb.PNG)
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by SMed79** [comment]
Subscribe to EasyList Italy and test again.
https://forums.lanik.us/viewtopic.php?f=96&t=30191&hilit=yourlifeupdated.net

**Comment by reek** [comment]
@adreporter 
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
