### ISSUE TITLE
Dplay: it.dplay.com, dplay.se, dplay.dk

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1463]
[dplay.com](http://dplay.com) (owned by Discovery) lists these domains which all detect blockers:
* [it.dplay.com](http://it.dplay.com)
* [dplay.se](http://dplay.se)
* [dplay.dk](http://dplay.dk)

The above domains offer the following channels (also broadcasted on the Swedish terrestrial network):
* Kanal 5
* Kanal 9
* Kanal 11
* Eurosport 1
* Discovery

Incompatible blockers
* Privacy Badger

**Comment by reek** [comment]
Thanks, I'll kill it

**Comment by SMed79** [comment]
Fixed on easylist https://hg.adblockplus.org/easylist/rev/8bce71ec877a

**Comment by flyingzebras** [comment]
@SMed79 Great!

**Comment by flyingzebras** [comment]
I cannot use dplay

**Comment by flyingzebras** [comment]
@reek An update on the situation: I cannot use any of the Dplay sites with uBlock Origin enabled.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
