### ISSUE TITLE
tv4play.se

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1464]
http://www.tv4play.se/program/nyhetsmorgon?video_id=3382912

[TV4 Play](http://tv4play.se) is the brand used for the video on demand service offered by the TV4 Group, the company that owns TV4, the largest commercial Swedish television network that broadcast on the terrestrial network.

tv4play.se channel TV4, but not the other channels on the website, is gratis but commercial without Premium account, and the site detect blockers to enforce ads.

Detected blockers
* uBlock Origin

**Comment by reek** [comment]
create an account and send me
https://reek.github.io/anti-adblock-killer/#contact

**Comment by flyingzebras** [comment]
@reek You do not need an account to play non-premium video streams like Nyhetsmorgon (meaning Morning news).

**Comment by reek** [comment]
no anti-adblock detected and I can't skip the videos ads

**Comment by flyingzebras** [comment]
@reek Did not http://www.tv4play.se/program/dropinbeauty?video_id=3302332 detect uBlock Origin for you?

**Comment by reek** [comment]
he asks me to register
![capture](https://cloud.githubusercontent.com/assets/3474011/15577410/bd5f0bb6-235c-11e6-82fe-e1bec02077bd.PNG)

**Comment by flyingzebras** [comment]
@reek Yes me too. This was not the case for the same videos last week. Let me come back.

**Comment by flyingzebras** [comment]
@reek This required login is new. Do you have an account or do you still want me to make one for you?

**Comment by reek** [comment]
no, I have not been able to create one, which you can create one for me, thank you

**Comment by davidhedlund** [comment]
@reek What message do you get?

**Comment by davidhedlund** [comment]
@reek Can you please open this issue?

**Comment by davidhedlund** [comment]
https://github.com/reek/anti-adblock-killer/issues/1365

**Comment by reek** [comment]
> Inloggningen misslyckades

**Comment by reek** [comment]
Sorry no solution

**Comment by davidhedlund** [comment]
@reek 
> Inloggningen misslyckades

Translates to "Login failed"


You can set "Fixed location" for Location Guard to use tv4play.se from your country.

**Comment by davidhedlund** [comment]
@reek Seems like they have removed the block detection.

**Comment by reek** [comment]
so much the better :smile:

**Comment by flyingzebras** [comment]
@reek tv4play.se started to 


> Kan ej spela upp
> 
> Du har Adblocker installerat och vi kan inte spela upp programmet. Skaffa TV4 Play Premium så tittar du utan reklamavbrott, eller så kan du stänga av Adblocker.

Translation:

>Can not play back

>You have AdBlocker installed and we can not play the program. Get TV4 Play Premium to look without commercial breaks, or you can turn off AdBlocker.

**Comment by flyingzebras** [comment]
@reek So can you please re-open this issue?

**Comment by flyingzebras** [comment]
@reek Here is the JS script that detect the blocker: http://cdn.videoplaza1.tv/contrib/se-tv4/aab/pulse-custom-svm-plugin.min.js

**Comment by mapx-** [comment]
I get no anti adblocking issue on this link
http://www.tv4play.se/program/nyhetsmorgon?video_id=3382912

**Comment by flyingzebras** [comment]
And this: https://www.tv4play.se/assets/play_man-747da1072d22cca969dfd5437c3f3e9dfadbb2806992a91edc7427f6f9e90068.js

**Comment by flyingzebras** [comment]
@mapx- You have to block the ads with this:

! tv4play.se reklam - https://github.com/ryanbr/fanboy-adblock/issues/20
||videoplaza1.tv^$third-party

**Comment by flyingzebras** [comment]
@reek Did you evaluate my solution?: https://github.com/reek/anti-adblock-killer/issues/1464#issuecomment-250237213

**Comment by WildS0ft** [comment]
http://www.tv4.se/gilla-tv/
http://www.tv4play.se/program/nyhetsmorgon (scroll down to "Senaste klippen" and choose any)
http://www.fotbollskanalen.se/video/
http://www.koket.se/video
These all belong to the same concern (The TV4-Group) and uses the same advertisements and videoplayer. To see any of these clips on either site **requires no account**.

Please consider reopening this issue @reek and have another look.

**Comment by flyingzebras** [comment]
@WildS0ft I copied your text and placed in the top post to make it even more clear. Thanks.

**Comment by flyingzebras** [comment]
https://github.com/EFForg/https-everywhere/issues/4881

**Comment by WildS0ft** [comment]
@flyingzebras looks good. [Sfanytime.com](http://sfanytime.com) isn't part of the TV4-Group though and I don't see any advertisements there either, so what gives?  =)

**Comment by flyingzebras** [comment]
@WildS0ft I don't know what to do. "SF Anytime cooperates with their sister company TV4 AB around their VOD service TV4 Anytime." - https://en.wikipedia.org/wiki/SF_Anytime

**Comment by WildS0ft** [comment]
@flyingzebras It's a Video On Demand (VOD) service that rents out movies. I just checked the site without any Ad-Block and I couldn't see any ads on the site or in any of the trailers. Their player also requires the Microsoft Silverlight plug-in which leads me to conclude that they don't use the same player as the TV4-Group. I'm not prepared to rent a movie just to check if it has advertisements in it. I don't follow why you would include SF Anytime unless you get ads in their videos. Do you have any ads in your rented movies or on the site that I missed?

Regarding the SF and TV4 cooperation, that's so payed customers with TV4 Premium can watch movies **on the TV4Play site** supplied by [SF Anytime](http://sfanytime.com/) and [C More](http://www.cmore.se/). And if you are paying for premium, you have no ads on TV4 to begin with.

So I again, I have no idea why you'd include SF Anytime in this issue. Unless I'm missing something here ;)

**Comment by flyingzebras** [comment]
@WildS0ft Good arguments, I removed it.

**Comment by WildS0ft** [comment]
I got a little carried away here and realized this might not be the right place to discuss this either, since this is an **Anti-Adblock-Killer** and not an **AdBlocker**, and as @reek previously stated:

> no anti-adblock detected and I can't skip the video ads

We first have to manage to block the ads and then come back to this issue if we get presented with an Anti-Adblocker.

**Comment by flyingzebras** [comment]
@WildS0ft Please read https://github.com/reek/anti-adblock-killer/issues/1464#issuecomment-250237213 it explain that AAK List is involved.

**Comment by WildS0ft** [comment]
> @WildS0ft Please read #1464 (comment) it explain that AAK List is involved.

@flyingzebras I stand corrected, I completely missed your comment there.

Adding the filter `@@||videoplaza1.tv^$third-party` does indeed produce an Anti-Adblock message.

**Comment by flyingzebras** [comment]
@WildS0ft 

> Adding the filter @@||videoplaza1.tv^$third-party

Don't you mean `||videoplaza1.tv^$third-party` (no whitelist @@)

**Comment by WildS0ft** [comment]
@flyingzebras It's getting very late... =P

**Comment by flyingzebras** [comment]
@WildS0ft Its morning in Internet Activism time.

**Comment by flyingzebras** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/20

**Comment by flyingzebras** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/59

**Comment by flyingzebras** [comment]
@WildS0ft I added this to the top:

**> AAK List must be companioned with AAK Script. Just adding the AAK List will just interrupt the video playing so it should not be added to EasyList.**

**Comment by flyingzebras** [comment]
@reek Can you please read https://github.com/reek/anti-adblock-killer/issues/1464#issue-156134491 ?

**Comment by KristofferSmedlund** [comment]
This solution doesn't seem to be working, Might open issue again? @reek
