### ISSUE TITLE
MTG: tv3play.se, tv6play.se, tv8play.se, tv10play.se

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1465]
Modern Times Group (MTG) is a Swedish digital entertainment company. They stream Swedish channel programs on these domains that are also broadcasted on the Swedish terrestrial network (https://en.wikipedia.org/wiki/Template:Television_in_Sweden):

MTG owns Viasat so in addition to the below listed channels they also stream contents Viacom Music and Entertainment Group channel MTV and Comedy Central.

uBlock Origin issues:
* TV3, [TV3 Play](http://tv3play.se) - http://www.tv3play.se/program/safecrackers
* TV6, [TV6 Play](http://tv6play.se) - http://www.tv6play.se/program/safecrackers
* TV8, [TV8 Play](http://tv8play.se) - http://www.tv8play.se/program/safecrackers
* TV10, [TV10 Play](http://tv10play.se) - http://www.tv10play.se/program/safecrackers

**Comment by reek** [comment]
Already killed by AakScript

**Comment by flyingzebras** [comment]
@reek Thank you. Yes it works for me.

**Comment by flyingzebras** [comment]
@reek I cannot use any of the sites with Firefox 46.0.1 and Privacy Badger 1.7.0.

**Comment by reek** [comment]
Remove it
https://github.com/reek/anti-adblock-killer#help

**Comment by flyingzebras** [comment]
@reek I want to use Privacy Badger. Cannot you make it undetected?

**Comment by reek** [comment]
Sorry, no

2016-05-28 12:13 GMT+02:00 flyingzebras <notifications@github.com>:

**Comment by flyingzebras** [comment]
@reek Is this a bug that I should report to Privacy Badger or is it just hard to make undetected?

**Comment by reek** [comment]
Try Disable Privacy Badger for this site or report to Privacy Badger

**Comment by flyingzebras** [comment]
https://github.com/EFForg/privacybadgerfirefox/issues/774

**Comment by flyingzebras** [comment]
@reek Can you please re-open this issue (see top post)?

**Comment by reek** [comment]
@flyingzebras 
I'll fix http://www.tv3play.se/program/blasningen, but can't others because content geolocked

**Comment by reek** [comment]
test: https://gist.github.com/reek/dc234ea9687056bd99fe (raw to install)

**Comment by flyingzebras** [comment]
@reek Works for me. By the way, I updated the list again at the top. Appears that all domains stream the same content. Can be good to know.

**Comment by reek** [comment]
Good

2016-06-01 16:44 GMT+02:00 flyingzebras <notifications@github.com>:

**Comment by flyingzebras** [comment]
@reek As said, how soon will this fix be part of https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by flyingzebras** [comment]
https://github.com/reek/anti-adblock-killer/issues/1940
