### ISSUE TITLE
www.planetatvonlinehd.com

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1467]
Google Chrome
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/1471#issuecomment-220932534

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
