### ISSUE TITLE
youpeliculasweb.com

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1471]
http://youpeliculasweb.com/
Google Chrome
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by SMed79** [comment]
Hi, 
u need to install a [ScriptManager](https://github.com/reek/anti-adblock-killer#step-1-scriptmanager) and add [AaKiller](https://greasyfork.org/en/scripts/735-anti-adblock-killer-reek) userscript.
Same thing for your others posts https://github.com/reek/anti-adblock-killer/issues/1467 / https://github.com/reek/anti-adblock-killer/issues/1468 / https://github.com/reek/anti-adblock-killer/issues/1469 / https://github.com/reek/anti-adblock-killer/issues/1470.
