### ISSUE TITLE
tustoons.blogspot.com

### ISSUE THREAD

**Issue by Masterwe** [reek/anti-adblock-killer#1473]
http://www.tustoons.com/

anti adblock in the page always detect adblock, adblock plus or ublock origin and immediately redirect from http://is-arquitectura.es/wp-content/uploads/2015/02/desactivar-Adblock-Safari.jpg

**Comment by Giwayume** [comment]
Do you have Aak script installed?

https://github.com/reek/anti-adblock-killer#instruction

**Comment by Masterwe** [comment]
Yes, Aak script installed,  Anti-adblock killer work in any web, but it does not work only in tustoons.blogspot.com

http://www.hophost.net/images/235killer.jpg
http://www.hophost.net/images/414killers.jpg

The script still very very good.. Tank you!!

**Comment by reek** [comment]
@Masterwe 
Already killed by AakList, see instructions

**Comment by Masterwe** [comment]
I appreciate the quick response, but the page still blocking anti adblock killer.

**Comment by reek** [comment]
@Masterwe 
https://github.com/reek/anti-adblock-killer#help
