### ISSUE TITLE
[Request] http://kingofshrink.com

### ISSUE THREAD

**Issue by evetaku** [reek/anti-adblock-killer#1476]
Please support : 
1. http://kingofshrink.com/
2  http://prnt.sc/b8mczd
3. Mozila Firefox 46.0.1
4. Greasemonkey 3.8
5. AdBlock Plus 2.7. +  uBlock Origin 1.7.0
6. EasyList +  AakList 

Thanks

**Comment by reek** [comment]
Already killed  by AakScrit

Don't use two Adblockers
