### ISSUE TITLE
Kissanime.to again

### ISSUE THREAD

**Issue by AronaxAE** [reek/anti-adblock-killer#1477]
The anti-adblock killer is rip again for kissanime.to

It keeps saying to disable ads. Just thought I would give you a heads up.

**Comment by reek** [comment]
Your config, see guidelines, thanks

**Comment by AronaxAE** [comment]
I have done everything that the instructions says to do. I have had this active whilst using Kissanime and it has stopped working since the domain change,

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
@SMed79 can you test, thanks

**Comment by SMed79** [comment]
@reek 

Adblock plus (Easylist, Liste AR, Liste FR, Easyprivacy & Anti-adblock killer filter)

Firefox + Greasemonkey > **No anti adblock** http://i.imgur.com/4E1pxLD.png
Chromium + Tampermonkey > **No anti adblock** http://i.imgur.com/twlSQg3.png

I also tested using Adblock & µBo > No issue.
- http://i.imgur.com/uyPClVx.png
- http://i.imgur.com/tBTgxbD.png

Here a test without Anti adblock killer > http://i.imgur.com/vrewXT7.png

 @AronaxAE Try [Firefox portable](http://portableapps.com/apps/internet/firefox_portable) or [chrome portable](http://portableapps.com/apps/internet/google_chrome_portable), install your **Adblocker** (subscribe to [AaK filter list](https://github.com/reek/anti-adblock-killer#step-2-filterlist)) + install [script manager](https://github.com/reek/anti-adblock-killer#step-1-scriptmanager) (add [AaK script](https://greasyfork.org/fr/scripts/735-anti-adblock-killer-reek)) then test again and see what happens.

**Comment by reek** [comment]
@AronaxAE 
this confirms what I thought, you must install AakScript

**Comment by AronaxAE** [comment]
@SMed79 I have done all of that and when I go on an anime, the ad does not show, but the little "hide" button is still there where they used to be, rip me I guess, thanks for trying to help.

**Comment by AronaxAE** [comment]
@reek @SMed79 I am the biggest moron alive, my Tampermonkey itself was not enabled, sorry for wasting your guys time and thanks for this, its awesome! <3

**Comment by reek** [comment]
Ok, I close
