### ISSUE TITLE
investors.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1478]
Hi, 
`/ibd-block-adblocker/*`

added an anti-adblock overlay http://i.imgur.com/z2dG9kb.png

Thanks!

**Comment by reek** [comment]
thanks

**Comment by WangChristopherS** [comment]
Where and how do you add this?

**Comment by reek** [comment]
@WangChristopherS 
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
