### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by veluria** [reek/anti-adblock-killer#1479]
For example: http://myanimelist.net/anime/31404/Netoge_no_Yome_wa_Onnanoko_ja_Nai_to_Omotta
uBlock Origin, Tampermonkey, Chrome

![screenshot from 2016-05-26 22-20-38](https://cloud.githubusercontent.com/assets/1119538/15588837/2074c80c-2390-11e6-943e-2956d5f363ad.png)
![screenshot from 2016-05-26 22-20-44](https://cloud.githubusercontent.com/assets/1119538/15588838/2075589e-2390-11e6-80c3-033e55af472b.png)

**Comment by 1010101010101** [comment]
Had to pick around 10x invisible frame box after you remove the 3x rectangles on one single banner.

**Comment by Reoldyk** [comment]
i dont see this problem,
FF 46
Greasemonkey 3.8
uBlock Origin 1.7.0
Anti-Adblock Killer | Reek 9.6 script + filter

![netoge no yome wa onnanoko ja nai to omotta- - myanimelist net 2016-05-27 15-49-54](https://cloud.githubusercontent.com/assets/4547317/15603044/c2083a4a-2422-11e6-8a5a-ca93a329759c.png)

**Comment by maynak00** [comment]
no antiadblock message for me too.
but empty unnecessary places on page and I blocked with:
`myanimelist.net##._unit`

**Comment by reek** [comment]
@veluria 
No detected, see https://github.com/reek/anti-adblock-killer#help
