### ISSUE TITLE
zive.cz

### ISSUE THREAD

**Issue by R3gi** [reek/anti-adblock-killer#148]
Hello,
I've just installed Your extension/script. It doesn't work on zive.cz. It seems they are using Social Locker + maybe something else.
Test URL: http://doupe.zive.cz/clanek/hospodskou-hudbu-z-dragon-age-inquisition-si-muzete-stahnout-zadarmo
Screenshot: http://i.imgur.com/S3O7KK3.jpg
Script: http://doupe.zive.cz/Client.Scripts/jquery.onp.sociallocker.1.7.6.js

I am using integrated Adblock Plus for Maxthon browser (v4.4.4.900) and ViolentMonkey extension for userscipts.
Browser main page:  http://www.maxthon.com/
ViolentMonkey extension:
http://extension.maxthon.com/detail/index.php?view_id=1680&category_id=
https://github.com/gera2ld/Violentmonkey-mx
My filters: EasyList Czech and Slovak
Thanks!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
