### ISSUE TITLE
investors.com

### ISSUE THREAD

**Issue by WangChristopherS** [reek/anti-adblock-killer#1480]
![screen shot 2016-05-26 at 5 32 10 pm](https://cloud.githubusercontent.com/assets/18157533/15594158/0e083dfc-2368-11e6-8f63-0b749139ba73.png)

This message is so haha not funny and pisses me off. Please kill this now.

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/1478

**Comment by WangChristopherS** [comment]
How do I do that?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
