### ISSUE TITLE
cnn.com

### ISSUE THREAD

**Issue by Zaxx420** [reek/anti-adblock-killer#1481]
CNN just added 15 sec commercials to the beginning of any video that you watch. If abp is enabled no videos will load or play. I don't mind the commercials much...just don't want to be forced to disable abp.
Dunno if it's doable...

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by Zaxx420** [comment]
Page: www.cnn.com
ScrSht: Nothing to SS. No aabp text...videos just will not load or play if abp is enabled.
Browser: FF 46.0.1
Script Mgr: GreaseMonkey
Blocker: Adblock Pro
Lists: Adblock Warning Removal List, EasyList,, AakList

Tia guys...

**Comment by reek** [comment]
http://edition.cnn.com/2016/05/28/football/real-madrid-champions-league-atletico/index.html
the video is loading without problems

**Comment by reek** [comment]
report it to https://forums.lanik.us/
