### ISSUE TITLE
azulyblanco.co

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1483]
![](http://image.noelshack.com/fichiers/2016/21/1464310693-2016-05-26-21h56-55.png)
http://azulyblanco.co/streamr?id=3
Google Chrome
Adblock Plus
Tampermonkey
EasyList + Anti-Adblock Killer |

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**
`azulyblanco.co#@##adblock`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
