### ISSUE TITLE
Up2stream.com

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1484]
![](http://image.noelshack.com/fichiers/2016/21/1464311035-2016-05-26-22h03-16.png)
http://www.vudumov.com/rape-zombie-lust-of-the-dead-2012-full-movie-online-watch-hdfree/
Google Chrome
Adblock Plus
Tampermonkey
EasyList + Anti-Adblock Killer |

**Comment by reek** [comment]
error from up2stream or file removed
