### ISSUE TITLE
teledeporteonlinetv.org (teledeporteonline.pw)

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1485]
![](http://image.noelshack.com/fichiers/2016/21/1464311319-2016-05-26-22h07-23.png)
http://teledeporteonlinetv.org/index.php?ver=23
Google Chrome
Adblock Plus
Tampermonkey
EasyList + Anti-Adblock Killer |

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
