### ISSUE TITLE
firstsrowsports.eu

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1486]
![](http://image.noelshack.com/fichiers/2016/21/1464311521-2016-05-26-22h11-04.png)
http://firstsrowsports.eu/soccer/first-atletico-mineiro-vs-gremio-row6a4875
Google Chrome
Adblock Plus
Tampermonkey
EasyList + Anti-Adblock Killer |

**Comment by reek** [comment]
Ok, I'll kill it, thanks

2016-05-27 3:12 GMT+02:00 xDarkARG <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
