### ISSUE TITLE
DMAX.DE

### ISSUE THREAD

**Issue by AlexandaL** [reek/anti-adblock-killer#1489]
DMAX.DE
http://www.dmax.de/adblocker/
![capture](https://cloud.githubusercontent.com/assets/17528944/15606649/d3be2f48-240d-11e6-9bf0-a2b43a2a6a44.PNG)
Browser: VIVALDI 1.1.453.59
 with Tampermonkey 
 and Adblock Plus
 (EasyList 
  EasyList Germany
  AakList (Anti-Adblock Killer))

**Comment by reek** [comment]
Can you test this rule.?
<code>@@||adm.fwmrm.net/p/release/latest-JS/adm/prd/AdManager.js$script,domain=dmax.de</code>
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by AlexandaL** [comment]
Tested.
Works perfektly.
Site is still usable and does no longer detect adblocking.

**Comment by reek** [comment]
Great :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
