### ISSUE TITLE
www.forbes.com

### ISSUE THREAD

**Issue by Drflash55** [reek/anti-adblock-killer#1490]
http://www.forbes.com/ redirects to http://www.forbes.com/forbes/welcome/ (__If you're able to access forbes, refresh and it will redirect you...__)
*not able to get image at this time*
Google Chrome
AdBlock
EasyList + AakList

**Comment by SMed79** [comment]
You have to install **ScriptManager** + **AaK Script**  https://github.com/reek/anti-adblock-killer#instruction

**Comment by Drflash55** [comment]
Sorry, thought I had it installed, but I was using a school computer when I found this out, which didn't have it on...
Forbes' anti-adblock seems to be removed actually...

Closing issue.
