### ISSUE TITLE
link.tl

### ISSUE THREAD

**Issue by maxpayne-x** [reek/anti-adblock-killer#1492]
that web site is redricect to adblock.php page . Please fix it.

http://link.tl/EtpG

http://i.imgur.com/yVRaPLz.png

Google Chorome 

Tampermonkey 

EasyList + AakList

**Comment by reek** [comment]
Ok, I'll fix it, thanks

**Comment by maxpayne-x** [comment]
thanks you for all

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
