### ISSUE TITLE
[Request] http://kingofdown.com/downloader/

### ISSUE THREAD

**Issue by evetaku** [reek/anti-adblock-killer#1493]
please this one 
http://kingofdown.com/downloader/

sorry yesterday for my request http://kingofshrink.com

its true is http://kingofdown.com/downloader/

**Comment by maynak00** [comment]
no antiadblock detected for me
**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**

**Comment by reek** [comment]
Already killed by AakScript, see instructions
