### ISSUE TITLE
MTG Radio sites

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1495]
MTG Radio is part of the Modern Times Group (MTG). MTG is the largest commercial radio (commercial radio) in northern Europe. In Sweden MTG Radio stations RIX FM, Bandit Rock, Lugna Favoriter, Power Hit Radio och Radio 1. MTG is P4 Radio Hele Norge, which is the largest nationwide commercial radio station in Norway.

uBlock Origin blocked from
* [Bandit Rock](http://play.bandit.se/live)
* [Lugna Favoriter](http://play.lugnafavoriter.com/live) - Blocked by uBlock Origins [logger](https://github.com/gorhill/uBlock/wiki/The-logger)
* [RIX FM](http://play.rixfm.se/live)

Broken sites
* [Radio 1](http://play.radio1.se/live) - Broken even with no blocker used. Reported to Radio 1.

No issues
* [P4 Radio Hele Norge](http://www.p4.no/)
* [Power Hit Radio (Svensk Version) ](http://www.ilikeradio.se/kanaler/powerhitradio/)
* [Power Hit Radio (Estnisk Version)](http://power.tv3.ee/)
* [Power Hit Radio (Lettisk Version)](http://powerhitradio.tv3.lt/)* [STAR FM](http://www.ilikeradio.se/kanaler/starfm/)

**Comment by reek** [comment]
I can't do anything for Radio 1 because it's a mistake the player

**Comment by flyingzebras** [comment]
![screenshot from 2016-05-29 17 36 41](https://cloud.githubusercontent.com/assets/11916082/15634440/f3245f76-25c3-11e6-9d6e-f5c902d8ec4a.png)

@reek What is the misstake?

**Comment by reek** [comment]
because even without adblock, there is this message

**Comment by flyingzebras** [comment]
@reek Thank you. I will report this to the site admins.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by flyingzebras** [comment]
@reek Thank you.
