### ISSUE TITLE
exrapidleech

### ISSUE THREAD

**Issue by MUFTAKiS** [reek/anti-adblock-killer#1496]
still redirect me to the same verification!

**Comment by reek** [comment]
I'll fix it, thanks

**Comment by MUFTAKiS** [comment]
tnx to you too ^_^

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
