### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by Abyade** [reek/anti-adblock-killer#1497]
Hi,
Adblock redirect page on http://adf.ly/1ahAxl (screenshot) BlockAdblock
Used link: [http://adf.ly/1ahAxl](url)
Firefox 45+Ublock Origin+Greasemonkey+Easylist+Aak
Thanks in advance
![adf](https://cloud.githubusercontent.com/assets/8308071/15630275/b879e426-2533-11e6-9dde-8908135b54a4.jpg)

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Abyade** [comment]
Thx Reek can you put here the manulaly add thx in advance
Best regards

**Comment by reek** [comment]
filters
<pre>
@@||redirecting.ws/?*$subdocument,domain=adf.ly
@@||s*-adfly.com/show.php?*$subdocument,domain=adf.ly
adf.ly#@##bottom
</pre>
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by Abyade** [comment]
Thx Mister reek you can lock the post ^^

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by noakei** [comment]
still not working for me, chrome + ublock origin

**Comment by reek** [comment]
@noakei 
https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ScorpionIbm** [comment]
I'm on chrome 57 and this still happens with adfly 
using tampermonkey and latest version of both the script and filter
