### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by bspieg** [reek/anti-adblock-killer#1498]
Hi there,
bild.de seems to not work anymore. I tried it within a fresh profile in Chrome.

Using Chrome Version 51.0.2704.63 beta-m + uBlock Origin + Latest Tampermonkey AakScript.

http://reek.github.io/anti-adblock-killer/#settings shows my configuration:

> Version: 9.6 
> AakScript: true 
> AakList: true 
> Browser: Chrome 
> ScriptManager: Tampermonkey

Here you can see my uBlock Origin configuration: http://imgur.com/a/bb2qo

Every page on http://www.bild.de/ links to: http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html --> http://imgur.com/voDvxs2

Thanks for fixing

**Comment by reek** [comment]
Hi,

uBO options -> 3rd-party filters -> uncheck <code>Parse and enforce cosmetic filters</code>

**Comment by bspieg** [comment]
Somehow didn't work. Maybe Ill just use bild.de without Adblocker then, it's not the biggest deal for me.

**Comment by reek** [comment]
Ok, their anti-adblock is a bit capricious, take a look at the other issues, this can be help.
https://github.com/reek/anti-adblock-killer/issues?q=bild

**Comment by bspieg** [comment]
Yes it seems their filter really is capricious.
I don't have Ghostery installed.
Disabling Easylist didnt help neither.
Unchecking "Parse and enforce cosmetic filters" neither.

---
And just as I wanted to Submit my comment, I retried a few times, clearing the cache inbetween, somehow it works now. I really don't get it. I'll monitor whether it keeps on working...

Thanks as of now.

**Comment by barthramsay** [comment]
See my comment here https://github.com/reek/anti-adblock-killer/issues/817#issuecomment-161957888 This needs to be added for Chrome (discovered this in December already, it's a Chrome specific problem):

I will repeat it here:

```
~bild.de##.fullBanner;
~bild.de##.powerplace;
~bild.de##.subchannelBanner1_1;
~bild.de##.subchannelBanner1_2;
~bild.de##.ads
~bild.de##.cbErotikContentbar15
~bild.de##.contentbar
~bild.de##.eyecatcher
~bild.de##.footerbar
~bild.de##.jetzt_aufnehmen
~bild.de##.rectangle
~bild.de##.servicelinks
~bild.de##.tea-rectangle
~bild.de##.txe
~bild.de##.yield
~bild.de##.adspecial
```

**Comment by bspieg** [comment]
Thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by wakkabakkamakka** [comment]
unfortunately the filter @@||bild.de^$elemhide leads to the social buttons resurfacing on bild.de
see issue https://forums.lanik.us/viewtopic.php?f=62&t=31471 (where is was told to report here)

maybe there is a way to not unblock the social buttons but still defeat the anti adblock mechanism?

**Comment by reek** [comment]
@wakkabakkamakka 
Not possible
