### ISSUE TITLE
kiplinger.com

### ISSUE THREAD

**Issue by jimmythesuperstar** [reek/anti-adblock-killer#1499]
http://prntscr.com/b9sotc

![kiplinger](https://cloud.githubusercontent.com/assets/16974495/15633673/ac33fe60-2581-11e6-938d-41a9e195ee64.png)

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
no antiadblock message for me.
**but try with:**
`@@||kiplinger.com/*/adblock.js$script`

**Comment by jimmythesuperstar** [comment]
I tried adding it to My Filters in Ublock, it didn't work, the add from above popped up again.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
