### ISSUE TITLE
cenapaliw.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#1500]
https://cenapaliw.pl/

solution
cenapaliw.pl#@#div[id^="div-gpt-ad"]
@@||googletagservices.com^$domain=cenapaliw.pl
@@||googleadservices.com^$domain=cenapaliw.pl
cenapaliw.pl#@#iframe[id^="google_ads_iframe"]

**Comment by reek** [comment]
thanks
