### ISSUE TITLE
[Request] http://fastrapidleech.com

### ISSUE THREAD

**Issue by evetaku** [reek/anti-adblock-killer#1505]
This's on 1 site : free , premium and vip
http://fastrapidleech.com/
http://fastrapidleech.com/free/
http://fastrapidleech.com/premium/
http://fastrapidleech.com/vip/
http://image.prntscr.com/image/7d6ee944e981404c84f4596b5bd9b0b4.png

Mozilla Firefox 
Greasemonkey
Adblock Plus + ublock origin
EasyList + AakList 

Please kill it. Thank you very much

**Comment by reek** [comment]
I'll kill it, but don't use two ad-blockers

**Comment by evetaku** [comment]
what's better Adblock Plus or ublock origin ?

**Comment by evetaku** [comment]
im just use Adblock Plus now

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
