### ISSUE TITLE
cloud.jasaku.net

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#1506]
http://www.cloud.jasaku.net/cloud/downloads.php?id=Image/PowerISO

displays this:
_Notice:
please disable adblock of browser used to start the actual download your files_

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
@reek, not posible at the moment. because: "This domain name expired on 2016-06-01 07:42:12 
Click here to renew it."

**Comment by reek** [comment]
@maynak00 
I found the solution before it expires

**Comment by callmenemo491** [comment]
it looks to be up and running at this moment...

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
