### ISSUE TITLE
gamestar.de Video

### ISSUE THREAD

**Issue by wurzelpete** [reek/anti-adblock-killer#1508]
Example:
http://www.gamestar.de/videos/specials,20/klartext-zu-mikrotransaktionen-in-overwatch,88796.html

Regular Video starts loading, then after a couple of seconds gets removed and a commercial gets blended in instead.

Mozilla Firefox
Greasemonkey
uBlock Origin
Anti-Adblock Killer | Reek‎, EasyList‎ (forums.lanik.us), Peter Lowe’s Ad server list‎

**Comment by reek** [comment]
report video ads to https://forums.lanik.us/

**Comment by ErikSteiner** [comment]
I don't see any advertisements, but I have the issue of wurzelpete, too.
So the main issue is, that you start watching a video, the first few seconds will be played. Then the video will reset and will load a complete DIFFERENT player. So first you were able to watch the video, changing the quality etc.. The new player will not have such features and the video will be displayed in the worst quality available. The switching of the player can only be avoided by turning off Adblock and that is a very bad option. So im my opinion it is very clear that this behavior is related to an anti-adblock-script and could be solved on your side here.

**Comment by reek** [comment]
this mechanism appears to work only with German users.
I'll try to find a solution and I would do you test

**Comment by reek** [comment]
test: https://gist.github.com/reek/dc234ea9687056bd99fe (raw to install)

**Comment by ErikSteiner** [comment]
Cool! It is working now. I had at first one issue with uMatrix that blocked a script so the player still changed during the first few seconds. Now after altering uMatrix, all videos load correctly with the correct player that allows changes to the quality. Are you still needing some logs or something that I could provide?

**Comment by reek** [comment]
no

**Comment by ErikSteiner** [comment]
What a pity. Two days later it isn't working anymore. I used the raw install and it was working until today. The player is switching again, it is like someone looks here at github to update this commercial s**t.

**Comment by wurzelpete** [comment]
sorry for my late reply, the test you posted took care of the issue!
I did not have the mentioned parse and enforce cosmetic filters checked.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
