### ISSUE TITLE
viki.com

### ISSUE THREAD

**Issue by goorman0** [reek/anti-adblock-killer#151]
Link - http://www.viki.com/videos/1059498v-mischievous-kiss-2-love-in-tokyo-episode-8
Screenshot - http://imgur.com/qCSPWTU
Browser - Chrome
Script Manager - Tampermonkey
AdBlocker - AdBlock
Filter Lists -  jsbin.com, jsfiddle.net, reeksite.com

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
