### ISSUE TITLE
freegameserverhost.com

### ISSUE THREAD

**Issue by ChristoCoder** [reek/anti-adblock-killer#1512]
keeps redirecting me to http://freegameserverhost.com/adblock.html

**Comment by reek** [comment]
Ok, I'll kill it, but read report guide

**Comment by maynak00** [comment]
Static filter @@/advertisement*.js$script found in: Anti-Adblock Killer | Reek
on page: http://freegameserverhost.com/adblock.html
"No AdBlock Plus detected! Thanks for truly supporting our site. You are one step closer to your free server!"
but redirecting to adblocker detected page.
**try with:**
`freegameserverhost.com#@#.adsbygoogle`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
