### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by juozapyne** [reek/anti-adblock-killer#1513]
Does not work on 15min.lt open any article and scroll through it

http://www.15min.lt
https://i.imgur.com/zIE0xNN.jpg
Chrome
Tampermonkey
Adblock 
Acceptable Ads (recommended)updated 19 hours ago
AdBlock custom filters (recommended)updated 3 days ago
EasyList (recommended)
Adblock Warning Removal list (removes warnings about using ad blockers)
One custom: http://sites.google.com/site/mantasmalcius/Home/AdBlockPlusLithuania.txt

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by SMed79** [comment]
`@@||15min.lt/js/ads/`

https://github.com/reek/anti-adblock-killer/issues/1525

**Comment by Krad-dono** [comment]
They have somekind "adblock" test page to check "if you're free of adblock software" - http://www.15min.lt/kaip-isjungti-reklamos-blokavima

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by juozapyne** [comment]
Adds is back again

**Comment by reek** [comment]
I'll fix it

**Comment by tosiara** [comment]
There are many duplicates of 15min.lt, so I'll comment here as this one is the oldest.

The anti-adblock script is now embedded into 15min.lt web page:
```
<script>
	(function() {
		window.__adblock_config = {
			slug: 'austeja-usaviciute',
			eventName: 'AdblockDetect',
			route: window.ROUTE
		};

		var holder = document.getElementById('adblock-content'),
			video = document.getElementById('adblock-video-item'),
			buttons_after = parseInt(video.getAttribute('data-buttons-after')) || 0;

		$(video).on('play', function() {
			$(holder).addClass('adblock-playing').removeClass('adblock-ended adblock-paused');

			if (video.currentTime <= buttons_after) {
				$(holder).find('.adblock-author').removeClass('show-author');

				setTimeout(function() {
					$(holder).find('.adblock-author').addClass('show-author');

					setTimeout(function() {
						$(holder).addClass('adblock-show');
					}, (buttons_after - video.currentTime) * 1000);
				}, 50);

			} else {
				$(holder).addClass('adblock-show');
			}
		}).on('pause', function() {
			$(holder).removeClass('adblock-show adblock-playing adblock-ended').addClass('adblock-paused');
		}).on('ended', function() {
			$(holder).removeClass('adblock-show adblock-playing adblock-paused').addClass('adblock-ended');
		});

		$(holder).on('click', '#play-button ', function() {
			try {
				video.play();
			} catch (e) {
				$(holder).addClass('adblock-playing');
				$(holder).addClass('adblock-show');
			}
			gaEvent('AdblockDetect', 'austeja-usaviciute', 'play');
		}).on('click', '.btn-replay', function() {
			video.play();
			gaEvent('AdblockDetect', 'austeja-usaviciute', 'button_reload');
		});
	})();
</script>
```

**Comment by tosiara** [comment]
To see what happens:
1. Open any article, like, this one http://www.15min.lt/mokslasit/straipsnis/technologijos/15min-paaiskina-kas-yra-pokemon-go-del-kurio-isprotejo-pasaulis-646-654449
2. Slowly scroll to the bottom
3. At some point page is hovered by huge banner saying that you have Adblock and must watch video

**Comment by reek** [comment]
@tosiara 
thank you, I have already planned to patch it

**Comment by juozapyne** [comment]
Hi. Any update on this one?

**Comment by X01X012013** [comment]
@juozapyne 
By locking `__adblock_config`, the block video doesn't show anymore. 
You can use this script while waiting for Aak to update (Aak updates every 3-4 weeks)
https://x01x012013.github.io/AdBlockProtector/

**Comment by X01X012013** [comment]
This website uses a customized FuckAdBlock, it can be countered the same way.

@juozapyne Aak updates every 3-4 weeks, you can use my script while waiting: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by juozapyne** [comment]
It looks that it works. Thank you ;-)
