### ISSUE TITLE
Consider to add Privacy Badger to Supported Adblockers

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1515]
Privacy Badger is a good [complement](https://github.com/gorhill/uBlock/issues/827#issuecomment-153800693) to uBlock Origin. However, Privacy Badger is not listed under "Supported Adblockers" at https://github.com/reek/anti-adblock-killer. @reek have [https://github.com/reek/anti-adblock-killer/issues/1465#issuecomment-222355028](told me) that he cannot make Privacy Badger undetected. I suggest that he give this a new chance as it would make a great contribution to the free software community.

Examples of Privacy Badger detected sites: [Dplay](https://github.com/reek/anti-adblock-killer/issues/1463) sites

**Comment by reek** [comment]
I'm sorry but I will not add it because it does not add AakList

**Comment by flyingzebras** [comment]
@reek What does not add AakList?

**Comment by flyingzebras** [comment]
> Reek's Akk Script requires a [scriptmanager](https://github.com/gorhill/uBlock/issues/1681#issuecomment-223155730)

**Comment by flyingzebras** [comment]
@IDKwhattoputhere There are no anti-Privacy Badger killer.

**Comment by IDKwhattoputhere** [comment]
@reek can't add PB to the supported adblockers because PB doesn't use filter lists. They can't "give this a new chance". The software is incompatible with the concept of AakList.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Thank you for explaining this to me. A separate project should be initiated but I don't have knowledge or time for it.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Did you understand that I meant that Privacy Badger should be compatible with AAK Script, not AAK List?

**Comment by IDKwhattoputhere** [comment]
No, thanks, I'm not interested. I don't even use PB because uBO is plenty.

> Did you understand that I meant that Privacy Badger should be compatible with AAK Script, not AAK List?

That makes even less sense. AakScript shouldn't be used without AakList. And again, @reek can't make AakScript compatible with PB. You could use a scriptmanager with AakScript but AakList still couldn't be used.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere No it makes even more sense since a script must be done to undetect PB.

**Comment by IDKwhattoputhere** [comment]
You can't just "undetect" a blocking extension. There's no one size fits all here. Someone would have to write a code snippet for every website blocking PB. It's much easier to use it in combination with uBO + AakList + scriptmanager with AakScript and switch PB off when a website blocks access.

**Comment by flyingzebras** [comment]
> Someone would have to write a code snippet for every website blocking PB.

I'm aware of that. That is why I reported Dplay sites [earlier](https://github.com/reek/anti-adblock-killer/issues/1515#issue-157930023).

**Comment by IDKwhattoputhere** [comment]
And Dplay sites are now working with PB while they weren't before? Impossible since a change in EasyList doesn't affect PB.

**Comment by flyingzebras** [comment]
>And Dplay sites are now working with PB while they weren't before?

No.

**Comment by IDKwhattoputhere** [comment]
Yes, I see.

**Comment by flyingzebras** [comment]
>Yes, I see.

Can you use dplay.se with PB or do you mean that you understand me?

It's hard to know because sometimes you communicate in a pessimistic way.

**Comment by IDKwhattoputhere** [comment]
:smile: I meant I understand what you said. Can't use the site.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere the Dplay sites are the only ones that I know refuse to load content with PB in use. They must use some sort of detection to do that. So Dplay can be used as a reference to the new PB blocking problem.

**Comment by IDKwhattoputhere** [comment]
I don't think they're aiming for PB specifically but simply that PB picked up the tracking domains that were also blocked in EasyList. Most sites just install ABP since it has the largest userbase and then try to find a way to block it.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Perhaps you are right. I will have a new later today. Thank you for the info.

**Comment by flyingzebras** [comment]
@IDKwhattoputhere 

https://github.com/EFForg/privacybadgerfirefox/issues/774

https://github.com/EFForg/privacybadgerfirefox/issues/776

**Comment by flyingzebras** [comment]
https://github.com/EFForg/privacybadgerfirefox/issues/774

https://github.com/EFForg/privacybadgerfirefox/issues/776
