### ISSUE TITLE
AAK not part of uBlock Origin

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#1517]
How easy would it be to integrate Anti-Adblock Killer in uBlock Origin?

**Comment by reek** [comment]
Enable AakList

**Comment by flyingzebras** [comment]
I think you misunderstood, I want to know what it would to take to make a bundle software consisting of:
* uBO
* AAK Killer
* AAK List

The goal would of course to enabled AAK by default.
