### ISSUE TITLE
Doesn't work with palermotoday.it

### ISSUE THREAD

**Issue by NessunoIM** [reek/anti-adblock-killer#1519]
Site: www.palermotoday.it
![pt](https://cloud.githubusercontent.com/assets/19640640/15719897/57aed8de-2832-11e6-9d43-8e9955dbbea0.png)
Mozilla Firefox 46.0.1
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by AndreaGiardini** [comment]
Update all the blocklists

**Comment by NessunoIM** [comment]
Grandeeeeee! <3

**Comment by AndreaGiardini** [comment]
Please close the issue :)
