### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by isantolin** [reek/anti-adblock-killer#1522]
Wired forces to disable the Adblock

http://www.wired.com/2015/11/clive-thompson-10/

Blocking that script
http://www.wired.com/assets/load?scripts=true&c=1&load%5B%5D=jquery-sonar,wpcom-lazy-load-images,outbrain,blockadblock,tracking,ads,wired,wp-embed&ver=1464808848

Unlocks the content

**Comment by reek** [comment]
thanks but already killed by AakScript

**Comment by reek** [comment]
your configuration ?

**Comment by isantolin** [comment]
- uBlock with Easylist and Aak List up to date

![sem titulo](https://cloud.githubusercontent.com/assets/264640/15753730/06890e72-28cb-11e6-866e-4459228c6748.png)

**Comment by reek** [comment]
Install Tampermonkey + Aakscript
