### ISSUE TITLE
sport1.de

### ISSUE THREAD

**Issue by Xebtria** [reek/anti-adblock-killer#1523]
http://www.sport1.de/
http://i.imgur.com/7gbkrMC.png
Chrome 50.0.2661.102
Tampermonkey 4.0.69
ublock Origin 1.7.2
Default Lists from ublock + AAK: http://i.imgur.com/3CuZD3L.png

**Comment by reek** [comment]
Duplicated: https://github.com/reek/anti-adblock-killer/issues/1075

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
