### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by irmantasaud** [reek/anti-adblock-killer#1525]
http://15min.lt
http://imgur.com/MHuZWmQ
Google Chrome
Tampermonkey
Adblock 
EasyList + AakList

To find adblocker blocker open any article and scroll down a bit, you will see same image. I found code in every page once you search for adblocker in view-source: page, it should be on line 1700-1800 somewhere there. Thanks for your help, if you will make this possible I will donate to you for your hard work.

**Comment by AlgirdasFunGuide** [comment]
+1

**Comment by bugac** [comment]
+1
http://i.imgur.com/KVIYg3H.jpg

**Comment by reek** [comment]
already reported

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
