### ISSUE TITLE
erotica-blog-fan.tumblr.com

### ISSUE THREAD

**Issue by Wexnaoz** [reek/anti-adblock-killer#1526]
http://antiblock.org/?d=2.3___%23BANNER_160x600

http://imgur.com/WdJFURc

Google Chrome
Tampermonkey
uBlock Origin 1.7.2
Easylist + AaKList

**Comment by reek** [comment]
ok, I'll kill it, thanks

**Comment by SpiderDead** [comment]
It's de code `<strong id="j19b"><p>Please disable your ad blocker!<br>Bitte deaktiviere Deinen Werbeblocker!<br>Veuillez désactiver votre bloqueur de publicité!<br>Por favor, desactive el bloqueador de anuncios!<br><a href="http://antiblock.org/?d=2.3___%23BANNER_160x600">antiblock.org</a> <i>v2.3</i></p></strong>` What needs to get killed.

**Comment by reek** [comment]
@SpiderDead 
I know

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
