### ISSUE TITLE
videomega.tv

### ISSUE THREAD

**Issue by JohnMiller9898** [reek/anti-adblock-killer#1527]
1.http://www.filmovizija.studio/movie/run-all-night-2015-video_c4471eb87.html
![capture](https://cloud.githubusercontent.com/assets/13141946/15750073/4149fdc2-28e5-11e6-90cf-ac2d24d8a29e.JPG)
3.Chrome
4.Tampermonkey
5.AdBlock Plus
6.Easy List, AakList

**Comment by reek** [comment]
Ok, I'll fix it, thanks

**Comment by NjegosVujovic** [comment]
yes pls it got quite annoying

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
