### ISSUE TITLE
kodilive.eu

### ISSUE THREAD

**Issue by NessunoIM** [reek/anti-adblock-killer#1528]
Site: http://kodilive.eu/

![zzzzkokoko](https://cloud.githubusercontent.com/assets/19640640/15766758/71c32e12-2942-11e6-87eb-8a289eb09385.png)
Mozilla Firefox 46.0.1
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Ih,
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
