### ISSUE TITLE
deadline.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1529]
Hi, 
when you block ads on `deadline.com` from subdomains (cdn2. & cdn3.) you get redirection to anti-adblock page http://i.imgur.com/xJ1owoZ.png

Thank you.

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by ktchong** [comment]
Using Still not working uBlock Origin.  Deadline.com does not even allow me to selectively disable adblock for just their website.  They want me to disable adblock completely for everything.  Asshole.

**Comment by reek** [comment]
@ktchong 
Install AakScript, see instruction

**Comment by uBlock-user** [comment]
@ktchong add - `deadline.com##script:inject(abort-on-property-write.js, _sp_)`

**Comment by Raavizz** [comment]
> @ktchong : Asshole.

Stop your drama / insulting / bad words.
