### ISSUE TITLE
psarips.com

### ISSUE THREAD

**Issue by axarad** [reek/anti-adblock-killer#153]
Please add support for www.psarips.com
Thaks for your great work!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by JukeboxJezabel** [comment]
psarips.com is blocking again. TIA

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
<blockquote class="Quote" rel="reek">Closed</blockquote>
site online.
µBlock 0.8.7.0
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com)
Chromium Version 42.0.2306.0 (64-bit)
Tampermonkey BETA 3.11.4552

http://i.imgbox.com/zma35zdD.png
with inspect element:
"<div id="no_ads" style="position: fixed; opacity: 1; z-index: 11000; left: 33%; margin-left: -116px; top: 100px; display: block;">
				<h1>PLEASE HELP US BY DISABLING YOUR ADBLOCK SOFTWARE</h1>
				<p>We've detected that you are using an AdBlock software which is preventing the page from fully loading. We hate ads as much as you do. But unfortunately that's the only option to keep this site going on. We work hard on the site, so we don't think some ads bother you that much. Please add psarips.com to your ad blocking whitelist or disable your adblocking software, Then refresh this page</p>
				<div id="msg_buttons">
								
				</div>
</div>"

EDIT: added to custom filters: <code>#anti_block_overlay</code>
and removed message and background clickable, and no shadow.
EDIT2: not working again.

**Comment by reek** [comment]
Website is down

**Comment by maynak00** [comment]
http://www.isitdownrightnow.com/psarips.com.html
"Psarips.com is UP and reachable.
The website is probably down just for you..."
http://i.imgbox.com/YBdCnNfK.png

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Administrator>ping psarips.com

Pinging psarips.com [176.10.37.81] with 32 bytes of data:
Reply from 176.10.37.81: bytes=32 time=106ms TTL=50
Reply from 176.10.37.81: bytes=32 time=696ms TTL=50
Reply from 176.10.37.81: bytes=32 time=105ms TTL=50
Reply from 176.10.37.81: bytes=32 time=105ms TTL=50

Ping statistics for 176.10.37.81:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 105ms, Maximum = 696ms, Average = 253ms

**Comment by bakelal** [comment]
yeah website is up and running...

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
please fix. also please follow adblockplus forum psarips topic.
popups and message: Please Disable Ad-Block To Continue.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
