### ISSUE TITLE
idnes.cz (subdomains)

### ISSUE THREAD

**Issue by multibestia** [reek/anti-adblock-killer#1531]
on the page http://*.idnes.cz/ is new anti adblock
Can you block?

http://sport.idnes.cz/
http://kraje.idnes.cz/
http://kultura.zpravy.idnes.cz/
http://ekonomika.idnes.cz/
http://bydleni.idnes.cz/
http://technet.idnes.cz/
http://ona.idnes.cz/
http://revue.idnes.cz/
http://auto.idnes.cz/

**Comment by multibestia** [comment]
http://*.idnes.cz/

http://kraje.idnes.cz/
http://kultura.zpravy.idnes.cz/
http://ekonomika.idnes.cz/
http://bydleni.idnes.cz/
http://technet.idnes.cz/
http://ona.idnes.cz/
http://revue.idnes.cz/
http://auto.idnes.cz/

**Comment by multibestia** [comment]
|http://1gr.cz/*.js

**Comment by reek** [comment]
Already reported, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
