### ISSUE TITLE
la-cosa.it

### ISSUE THREAD

**Issue by genox87** [reek/anti-adblock-killer#1532]
http://www.la-cosa.it/2016/05/04/manlio-di-stefano-sosteniamo-rousseau/

http://imgur.com/BlrKUna

Google Chrome
uBlock Origin
Easylist + AaKList

**Comment by DeeSnow97** [comment]
Seems like it's the usual F*ckAdBlock rebranded as CADetect ([source](http://www.la-cosa.it/wp-content/themes/lacosa_2015/js/cadetect.js))

**Comment by reek** [comment]
Yes, but I'll kill it :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
