### ISSUE TITLE
oneplay.tv

### ISSUE THREAD

**Issue by t5622h** [reek/anti-adblock-killer#1534]
![adblock_oneplay](https://cloud.githubusercontent.com/assets/19736231/15790288/8a4fed9c-299e-11e6-8c03-26147c7e830c.png)

[http://oneplay.tv/ver/canal/5/ver-canal-National%20Geographic-en-vivo-gratis.html](http://oneplay.tv/ver/canal/5/ver-canal-National%20Geographic-en-vivo-gratis.html)

Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
