### ISSUE TITLE
stadt-bremerhaven.de

### ISSUE THREAD

**Issue by koboltzz** [reek/anti-adblock-killer#1535]
http://stadt-bremerhaven.de/
https://abload.de/img/2016-06-03_23h25_374la61.png
Mozilla Firefox
Greasemonkey
ublock origin
EasyList + AakList

**Comment by SMed79** [comment]
Add: 
`/wp-content/plugins/deadblocker/*`

**Comment by reek** [comment]
@koboltzz 
Ok, I'll kill it

@SMed79 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
