### ISSUE TITLE
movies.hdviet.com

### ISSUE THREAD

**Issue by pchoanganh** [reek/anti-adblock-killer#154]
http://movies.hdviet.com/phim-mot-thoi-chong-qua-the-humbling.html
http://awesomescreenshot.com/0294b901e6
Mozila Firefox (OSX)
Greasemonkey
Adblock Plus
Anti-Adblock Killer

**Comment by pchoanganh** [comment]
Proxy vietnam

**Comment by pchoanganh** [comment]
If you do not find the proxy in Vietnam. You can email me at any time for free, and I will confirm favorable time, I can send you to your teamviewer check. Thanks
Email: web@pchoanganh.info
Best regards!

**Comment by reek** [comment]
Hi,

Ok, I will contact you when I have a little more time

See you soon
Reek

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/51
