### ISSUE TITLE
tweaktown.com - again...

### ISSUE THREAD

**Issue by Zaxx420** [reek/anti-adblock-killer#1542]
Look as tho they've gotten around AAK somehow. This is a great hardware site...BUT it has some of the most intrusive ads and methods anywhere.
Link: http://www.tweaktown.com/sp/index.html
ScrSht: http://imgur.com/2p6muzS
Browser: Firefox
Script Mgr: Greasemonkey
Blocker: ABP
Lists: Adblock Warning Removal List, Easy List, Aak List

**Comment by reek** [comment]
Ok, I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rum0r** [comment]
@reek unfortunately they have found a way around it again.

**Comment by reek** [comment]
@rum0r 
Killed for me

**Comment by Zaxx420** [comment]
looks good 4 me....0 adz no redir

**Comment by Jason010767** [comment]
Your solutions doesn't work for me unforunately.
But I found a simple way to block them.
Just block xyz.tweaktown.com with your host file.
It is stupid, but most importantly, IT WORKS.
