### ISSUE TITLE
diarioinformacion.com

### ISSUE THREAD

**Issue by NnIiTtoO** [reek/anti-adblock-killer#1549]
Hi, when I visit this online newspaper [diarioinformacion.com](http://www.diarioinformacion.com), I am having problems with anti-adblock.
Viewing the source code of the web, I found this script:

`<script type="text/javascript" src="http://www.diarioinformacion.com/elementosWeb/js/ads.js"></script><script type="text/javascript">if(document.getElementById("ads_control")!= undefined){document.write("<script>_gaq.push(['_trackEvent','Adblock','Unblocked','false',,true]);</sc"+"ript>");}else{document.write("<script>_gaq.push(['_trackEvent','Adblock','Blocked','true',,true]);</sc"+"ript>");}</script>
</div>`

I think it may be the cause, but I have no idea how I can block it using a custom filter.

Can you help me? Thank you.

**Comment by reek** [comment]
Duplicated
