### ISSUE TITLE
diarioinformacion.com

### ISSUE THREAD

**Issue by NnIiTtoO** [reek/anti-adblock-killer#1550]
Hi, when I visit this online newspaper [diarioinformacion.com](http://www.diarioinformacion.com), I am having problems with anti-adblock.
Viewing the source code of the web, I found this script:

`<script type="text/javascript" src="http://www.diarioinformacion.com/elementosWeb/js/ads.js"></script><script type="text/javascript">if(document.getElementById("ads_control")!= undefined){document.write("<script>_gaq.push(['_trackEvent','Adblock','Unblocked','false',,true]);</sc"+"ript>");}else{document.write("<script>_gaq.push(['_trackEvent','Adblock','Blocked','true',,true]);</sc"+"ript>");}</script>
</div>`

I think it may be the cause, but I have no idea how I can block it using a custom filter.

Can you help me? Thank you.

My Settings:

Screenshot: [Antiadblock in diarioinformacion.com](http://s2.subirimagenes.com/privadas/previo/thump_2371513captura.png)
Browser: Chrome
Script manager: I only have JavaSwitcher plugin for chrome.
Adblocker: Adblock & uBlock
Lists: EasyList, Antiadblock killer, Fanboy, Easylist Spanish. uBlock Filters, Antimalware domains.

**Comment by reek** [comment]
Ok, I'll kill it, don't use two Ad-Blockers

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by NnIiTtoO** [comment]
hi, thanks for your help.

there are more inssues in [diairoinformacion.com](http://www.diarioinformacion.com)

is necessary block this js files too.

`http://www.diarioinformacion.com/elementosWeb/js/ads.js
http://estaticos00.diarioinformacion.com/elementosWeb/js/portada*.js
http://estaticos00.diarioinformacion.com/elementosWeb/js/seccion_not*.js
http://estaticos02.diarioinformacion.com/elementosWeb/js/seccion_not*.js`

**Comment by reek** [comment]
No need killed by AakScript

**Comment by NnIiTtoO** [comment]
I cant't install script file doing double click, windows show me a error. How can i install?

**Comment by reek** [comment]
See instruction

**Comment by NnIiTtoO** [comment]
Hello , I installed Tampermonkey and I 'm using the userscript you've shown me . everything is working perfectly . thank you very much
