### ISSUE TITLE
myanimelist.net

### ISSUE THREAD

**Issue by Raijukami2** [reek/anti-adblock-killer#1551]
On MAL there is a antiadblock which your script handles well, BUT the space occupied is still in use so it looks funny. It looks like it is hidden instead of not displayed.

Without the anti-adblock-killer:
http://imgur.com/p5o4Gt0
With the anti-adblock-killer (script/list) enabled:
http://imgur.com/WRhZQXk

Firefox, greasemonkey, ublock origin with the AaK list activated.

**Comment by reek** [comment]
add this rule
<code>myanimelist.net##._unit</code>

**Comment by Raijukami2** [comment]
Well, that was simple enough. Just added that to my filters in uBlock and the problem was solved. Thank you.

**Comment by reek** [comment]
:smile:
