### ISSUE TITLE
topserialy.sk

### ISSUE THREAD

**Issue by viktorjezekcz** [reek/anti-adblock-killer#1552]
Killer doesn't work on topserialy.sk. _The website is in Slovak only_.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by viktorjezekcz** [comment]
Oh sorry.

1. **Link page contains anti-adblock:** for example http://bit.ly/1tdG8ga
2. **One screenshot:** https://ctrlv.cz/xXzX
3. **My browser:** Google Chrome and Mozilla Firefox in the newest version
4. **My script manager:** Tampermonkey in Chrome and Greasemonkey in Firefox
5. **My adblocker:** AdBlock Plus v1.12 in Chrome and AdBlock Plus v2.7.3 in Firefox
6. **My filterlists:** https://ctrlv.cz/72LK (Chrome) and https://ctrlv.cz/dV6X (Firefox)

**Comment by reek** [comment]
Already killed by AakScript

**Comment by viktorjezekcz** [comment]
Thank you very much.
