### ISSUE TITLE
photo.programme-tv.net

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1553]
Hi;

http://photo.voici.fr/quand-les-stars-en-montrent-trop-la-voiture-le-piege-absolue-9728#daisy-lowe-171570

`||photo.programme-tv.net/js/main-`

![anti-adblock-killer
](http://i.imgur.com/5C6IX52.png)

Thanks!

**Comment by reek** [comment]
Thanks, but I prefer add an AakScript rule

**Comment by reek** [comment]
Updated
