### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by skull1** [reek/anti-adblock-killer#1555]

**Comment by skull1** [comment]
page: www.vvvvid.it
screenshot: http://imgur.com/QGRUBad
browser: google chrome
adblock plus
EasyList + AakList

**Comment by skull1** [comment]
if can help, i found this script that works on my browser: 
`window.vvvvid.cab2 = function (k, n)
{
  var o = this;
  o.isAdBlockActive = false;
  if (n)
    n(false);
};

window.MPVastLoader.adbTot = -1337;`

**Comment by Robotex** [comment]
> window.MPVastLoader.adbTot = -1337; 

That line is old and doesn't fix the anti adblock completely
