### ISSUE TITLE
codefi.re

### ISSUE THREAD

**Issue by dnut** [reek/anti-adblock-killer#1557]
http://downloads.codefi.re/autoprime/LG/LG_G3/LS990/LS990ZVB_00-LS990ZVC_00_update.zip

> Ad Blocker Detected
> 
> Hello there! We've noticed that you're using an Ad Blocker like AdblockPlus and you don't have Acceptable Advertisements enabled (or you're blocking Google Ads).
> 
> Blocking advertisements hurts publishers like us,
> since it costs us money to provide service to you.
> 
> Would you consider disabling your Ad Blocker or whitelisting *.codefi.re/* and reloading this page so you can download your file?
> 
> Please click here to read more about why blocking advertisements on our site prevents us from providing the best service to you.
> 
> If you've enabled Acceptable Ads and are still unable to download your file, try whitelisting this site or refreshing the page while holding SHIFT.

**Comment by reek** [comment]
Already killed by AakList
