### ISSUE TITLE
l2topzone.com

### ISSUE THREAD

**Issue by junpet** [reek/anti-adblock-killer#1559]
> Adblock Detected
> 
> You Are Using Ad Block Plus or some other advert blocking software! Our site relies on advertising for revenue! Please add our website to your ad blocking whitelist or disable ad blocking when you visit our website. Thank you!

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by junpet** [comment]
Sorry!
[http://i.imgur.com/zzV7gkl.png](http://i.imgur.com/zzV7gkl.png)
Latest Nightly (50.0a1 (2016-06-07))
Greasemonkey
Adblock Plus
Adblock Warning Removal List, EasyList, Malware Domains, Fanboy's Social Blocking List, EasyPrivacy, Fanboy's Annoyance List, hufilter, Aaklist

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**(temporary solution)
`l2topzone.com###adblockmessage`
`l2topzone.com##.in.fade.modal-backdrop`

**Comment by junpet** [comment]
Thank you, @maynak00 !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by junpet** [comment]
Thank you!
