### ISSUE TITLE
Hebrew site anti-add block

### ISSUE THREAD

**Issue by exx8** [reek/anti-adblock-killer#1560]
Haaretz site, for example here:
http://www.haaretz.co.il/news/world/america/us-election-2016/1.2969652
![default](https://cloud.githubusercontent.com/assets/8540180/15882278/c7e953f0-2d45-11e6-97ef-2e1aaa1f95e5.PNG)

**Comment by reek** [comment]
No detected

**Comment by exx8** [comment]
sorry, this was an article for premium only.
Here's one that is opened for all:
http://www.haaretz.co.il/blogs/sadna/1.2969870

**Comment by reek** [comment]
still nothing, please 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by exx8** [comment]
Link page contains anti-adblock
http://www.haaretz.co.il/news/politics/1.2972901
One screenshot: attached at the first post.
Your browser:
google chrome 51
Your script manager: ha?
Your adblocker: adblock 2.59
Your filterlists:
easylist
עברית (hebrew)
Aak list

Thanks!

**Comment by reek** [comment]
Already killed by AakScript, see instruction
