### ISSUE TITLE
[Off topic]: Anti-Geo location project suggestion

### ISSUE THREAD

**Issue by davidhedlund** [reek/anti-adblock-killer#1561]
I could not hide my location with Firefox add-on [Location Guard](https://github.com/chatziko/location-guard/issues/19) to browse [Hulu](http://www.hulu.com/).

I suggest that you start a Anti-Geo Location script project.

what do you think about it @reek?

**Comment by davidhedlund** [comment]
https://github.com/chatziko/location-guard/issues/19

**Comment by reek** [comment]
thank you, but I'm not interested, the most effective way is to use a VPN.

**Comment by davidhedlund** [comment]
@reek Ok, thank you anyway.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)
