### ISSUE TITLE
variety.com support please

### ISSUE THREAD

**Issue by prech** [reek/anti-adblock-killer#1563]
It looks like [Variety.com](http://variety.com/) has now added the the same anti-Adblock mechanism to Deadline.com :/ A very familiar googletag or "GPT" Javascript

If we could update the rules to include Variety, it'd be much appreciated!

**Comment by maynak00** [comment]
do you have a screenshot? (**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide** )
*not detected antiadblock for me (tested in Chromium with uBlock Origin+Tampermonkey on http://variety.com/ and http://deadline.com/)

**Comment by prech** [comment]
Thanks for your help, but it looks like the recent 6/6 update (release 9.7) fixed things. It now supports both Variety and Deadline
