### ISSUE TITLE
www.lesechos.fr

### ISSUE THREAD

**Issue by Francois-dag** [reek/anti-adblock-killer#1565]
![lesechos](https://cloud.githubusercontent.com/assets/8970219/15942092/3bd64fc8-2e83-11e6-815c-e83bf8246345.PNG)

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by SMed79** [comment]
@reek more details https://forums.lanik.us/viewtopic.php?f=91&t=30898

**Comment by Francois-dag** [comment]
So we seems to be killed, fortunately there is a cost for sites. To morrow I will try to trace what happens
with wireshark, I will let you know how it works.

**Comment by Francois-dag** [comment]
A page request contains a link to /adblock/index.php 
get rid of it would be sufficient ??

GET /adblock/index.php?xt_page=ce_qu_il_reste_a__faire_pour_redresser_les_retraites HTTP/1.1
Host: www.lesechos.fr
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://www.lesechos.fr/economie-france/social/0211023193889-retraites-un-besoin-de-financement-ramene-a-4-milliards-en-2020-2006016.php
Cookie: pw201606=NQ%3D%3D%7C46af2e2f73c0ef86de38b2f11c87f974; xtvrn=$542199$; xtan542199=-; xtant542199=1; __utma=245155992.594538919.1465017717.1465811842.1465896764.7; __utmz=245155992.1465017717.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); echosCookiePermit=1; __utmb=245155992.5.10.1465896764; __utmc=245155992; lastpage=%2Feconomie-france%2Fsocial; country_code=FR; UrlStack=a%3A3%3A%7Bi%3A0%3Bs%3A135%3A%22http%3A%2F%2Fwww.lesechos.fr%2Feconomie-france%2Fsocial%2F0211023193889-retraites-un-besoin-de-financement-ramene-a-4-milliards-en-2020-2006016.php%22%3Bi%3A1%3Bs%3A121%3A%22http%3A%2F%2Fwww.lesechos.fr%2Fmonde%2Fetats-unis%2F0211026924471-orlando-de-nouvelles-informations-emergent-sur-le-tueur-2006272.php%22%3Bi%3A2%3Bs%3A135%3A%22http%3A%2F%2Fwww.lesechos.fr%2Feconomie-france%2Fsocial%2F0211023193889-retraites-un-besoin-de-financement-ramene-a-4-milliards-en-2020-2006016.php%22%3B%7D; UrlStackDateMaj=20160614114552; returnTuto=http://www.lesechos.fr/economie-france/social/0211023193889-retraites-un-besoin-de-financement-ramene-a-4-milliards-en-2020-2006016.php; __utmt=1
Connection: keep-alive

HTTP/1.1 200 OK
Date: Tue, 14 Jun 2016 09:45:52 GMT
Server: Apache
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 1387
Keep-Alive: timeout=1, max=99
Connection: Keep-Alive
Content-Type: text/html

**Comment by Francois-dag** [comment]
In the meantime I've blocked all cookies from this site and now I get "Bienvenue ! ...." for each
click, boring but it works !

**Comment by M3T4LL1C4** [comment]
Try to add this filter, it works for me:
lesechos.fr##script:contains(checkAdBlock)

**Comment by Francois-dag** [comment]
yes, it works, thanx a lot !
So, the solution is 
- add this filter
- from time to time get rid of all cookies from lesechos.fr

Cheers.

**Comment by M3T4LL1C4** [comment]
Yes,
you can also block the cookies and add these filters:
lesechos.fr##.paywall-fx > .container
lesechos.fr###cookiemenu

to remove the messages about the cookies

**Comment by SMed79** [comment]
> to remove the messages about the cookies

or subscribe **Fanboy Annoyances List** https://www.fanboy.co.nz/

**Comment by Francois-dag** [comment]
subscribed, great !

**Comment by ac171** [comment]
Works for me with this rule : www.lesechos.fr pics-news.lesechos.com * allow

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
