### ISSUE TITLE
bakersfield.com rules removal

### ISSUE THREAD

**Issue by liracobopu** [reek/anti-adblock-killer#1566]
Looks like bakersfield.com rules (#1117, #657) are no longer needed as suitable rules were added to [EasyList](https://hg.adblockplus.org/easylist/rev/0facd64c5710).

I've been testing bakersfield.com on Google Chrome, Safari, and Firefox for Android and haven't ran into any issues with AAKList disabled.

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
done
