### ISSUE TITLE
Please support https://www.8muses.com/

### ISSUE THREAD

**Issue by zevelorgani** [reek/anti-adblock-killer#1568]
Please support https://www.8muses.com/
It keeps displaying anti-adblock pages

Thank you!

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by liracobopu** [comment]
The solution from https://adblockplus.org/forum/viewtopic.php?f=2&t=44586 works for me. I'll just fill out the report guide for you @zevelorgani 

8muses.com (Click through a few pages and the adblocker will come up)
http://imgur.com/Rvg2fwK
Google Chrome
uBlock Origin
uBlock Filters + EasyList + Adblock Warning Removal List + AAKList + Fanboy Cookies

Solution:
`@@||8muses.com^$generichide`

**Comment by reek** [comment]
Already killed by AakScript

**Comment by liracobopu** [comment]
@reek What about those running AAKList? I find I only need
`@@||8muses.com^$generichide`
to kill the anti-adblocker with uBlock Origin.

**Comment by reek** [comment]
@liracobopu 
I do not like to use this rule, as it disables many other rules
