### ISSUE TITLE
allmusic.com

### ISSUE THREAD

**Issue by osfp** [reek/anti-adblock-killer#1569]
http://www.allmusic.com/

![](http://i.imgur.com/Tp8qNU6.png)

Chrome
Tampermonkey
uBlock Origin
uBlock filters + Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek + EasyList‎

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by maynak00** [comment]
**try with:** (temporary solution)
@@||asset.pagefair.com/adimages/adsense.js$script,domain=allmusic.com
@@||asset.pagefair.net/ads.min.js$script,domain=allmusic.com

**Comment by osfp** [comment]
Thanks a lot.

**Comment by xiconet** [comment]
Hello
Same problem here. I use adblock latitude (for palemon). Where should I put these filters?

**Comment by reek** [comment]
@xiconet 
https://github.com/reek/anti-adblock-killer/wiki/Add-filter

**Comment by xiconet** [comment]
Thanks for the tip. Unfortunately the allmusic site still detects an adblocker (maybe the "freebox" one). However I found that using https somehow eludes detection

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by EverEve** [comment]
Hello, sorry if this issue is already closed but currently I have the same problem and the AAK List doesn't allow the loading of allmusic.com.

Thanks.

**Comment by xiconet** [comment]
Hello
In fact I still haven't found a way to use allmusic.com without completely blocking their javascript. grrr...
Shame on me and on those who want to force users to eat disgusting ads.
And thanks to "reek" of course.
