### ISSUE TITLE
imgsicily.it

### ISSUE THREAD

**Issue by vavavr00m** [reek/anti-adblock-killer#1570]
Link page contains anti-adblock - imgsicily.it

One screenshot - 
![image](https://cloud.githubusercontent.com/assets/4675132/15984174/b4304010-2ff4-11e6-9633-d303cc1de7d4.png)

Your browser - Chrome on W7

Your script manager - Tampermonkey Beta

Your adblocker - uBlock Origin

Your filterlists:
![image](https://cloud.githubusercontent.com/assets/4675132/15984040/ed2db466-2fee-11e6-966d-1534a8c6705a.png)
![image](https://cloud.githubusercontent.com/assets/4675132/15984037/cd54dc64-2fee-11e6-9dfe-4a411c64f934.png)

Issue: Aaklist alone doesn't have an issue on the site itself but some of the active filterlists are detected by adblock killer on imgsicily.it. 

Temporary fix: To circumvent this, I have added the following to myfilters:
imgsicily.it##.sweet-overlay
imgsicily.it##.visible.showSweetAlert.sweet-alert

Please fix/add this.

**Comment by maynak00** [comment]
or **try with:**
`||imgsicily.it/dist/sweetalert`

**Comment by reek** [comment]
I have no message, but I will add @maynak00 rule

**Comment by vavavr00m** [comment]
@reek It just pops up if it's an image URL. @maynak00 nailed it anyway. Thanks to both of you!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
