### ISSUE TITLE
v3.co.uk

### ISSUE THREAD

**Issue by ragues** [reek/anti-adblock-killer#1571]
v3.co.uk
![v3](https://cloud.githubusercontent.com/assets/11560131/15967076/eaf9990c-2f1d-11e6-9c6d-f05fd37673c7.jpg)
AakList

**Comment by reek** [comment]
No detected

**Comment by ragues** [comment]
Further examples:
http://www.v3.co.uk/v3-uk/news/2460942/bruce-schneier-governments-have-a-stark-lack-of-expertise-in-iot-security
http://www.v3.co.uk/v3-uk/news/2461196/googles-week-tensorflow-ios-alphago-ai-and-flying-cars

**Comment by reek** [comment]
Nothing

**Comment by graingert** [comment]
@reek it's definitely blocking adblock users.

**Comment by graingert** [comment]
@reek looks like pagefair.com

**Comment by reek** [comment]
pagefair already blocked by AakList

**Comment by reek** [comment]
See https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
Now detetected, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
