### ISSUE TITLE
avon.com.br

### ISSUE THREAD

**Issue by anewuser** [reek/anti-adblock-killer#1572]
This static filter in AakList is preventing images from avon.com.br to load:

    ||s3-sa-east-1.amazonaws.com^$third-party

Sample page: http://www.avon.com.br/categoria/avon-kids

**Comment by maynak00** [comment]
**try with:**
`@@||s3-sa-east-1.amazonaws.com$image,domain=avon.com.br`
`@@||google-analytics.com/analytics.js$script,domain=avon.com.br`

**Comment by reek** [comment]
@anewuser 
I'll remove it, thanks

**Comment by reek** [comment]
done
