### ISSUE TITLE
adf.ly yet again :-(

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#1573]
It was working was last fixed until tonight.  Now it gets to the countdown page, sits there for a few seconds, starts the countdown (5, 4, 3...), and then posts a dialog complaining about ad blockers.

Examples:
[http://adf.ly/1b4arW](http://adf.ly/1b4arU)
[http://adf.ly/1b4arW](http://adf.ly/1b4arW)

And here's another link that doesn't explicitly point to adf.ly but shows the same behavior:
[http://q.gs/ACAoA](http://q.gs/ACAoA)

FWIW, all these links are coming from links on [this site](http://2ddl.ag/category/tv-shows/).  But caution, this site is full of redirects to spam/malware pages.  Spam blockers like ADB mitigate that crap somewhat but not entirely.

**Comment by maynak00** [comment]
**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**
*not detected for me.(also tested with and without AdsBypasser.nothing detected)

**Comment by reek** [comment]
@xyzzy-xyzzy 
`adf.ly` killed for me, 
`q.gs` I'll kill it

**Comment by xyzzy-xyzzy** [comment]
Are you guys saying you _cannot_ reproduce the problem?  If so I wonder if this may have anything to do with using Firefox 47.0 because this started about the same time I had also switch to it.  Since I always keep backups of my profiles I'll drop back to 46.0.1 and see what happens there.

Stay tuned...

**Comment by reek** [comment]
@xyzzy-xyzzy 
See: https://github.com/reek/anti-adblock-killer#help

**Comment by xyzzy-xyzzy** [comment]
You may have replied while I was updating my previous post.  So just in case read it again.

**Comment by xyzzy-xyzzy** [comment]
Another piece of info.

**Comment by xyzzy-xyzzy** [comment]
Sorry, pushed wrong button.  

I was going to say that although my full profile is behaving somewhat different that the clean profile test I just discovered that in my full profile, if I _disable_ ADB for adf.ly, then apparently the countdown is suppressed and I to the the desired page.  Counter intuitive and really confusing.

**Comment by xyzzy-xyzzy** [comment]
As indicated above, adsbypasser appears to have a fix for the adf.ly problem ([#1080](https://github.com/adsbypasser/adsbypasser/issues/1080)) in [#1099](https://github.com/adsbypasser/adsbypasser/pull/1099).  It appears to be working so I will close this issue here.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
