### ISSUE TITLE
streaminporn.com & gaypornmasters.com

### ISSUE THREAD

**Issue by ximigami** [reek/anti-adblock-killer#1574]
http://streaminporn.com     http://gaypornmasters.com
http://i.imgur.com/U8vqhrX.png    http://i.imgur.com/JrUzO2F.png
chrome
tampermonkey
uBlock Origin
EasyList + Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek‎ 

the 2 sites seem like using the same anti-adblock

**Comment by maynak00** [comment]
#NSFW
**try with:**
`streaminporn.com#@##adsense`
`gaypornmasters.com#@##adsense`

**Comment by reek** [comment]
@ximigami 
Ok, I'll kill it

@maynak00 
thanks for rules :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
