### ISSUE TITLE
desktopsolution.org

### ISSUE THREAD

**Issue by marcomg** [reek/anti-adblock-killer#1575]
http://desktopsolution.org
http://postimg.org/image/dt2mso3x7/
Mozilla Firefox 47.0
Greasemonkey
uBlockOrigin
EasyList + Anti-Adblock Killer | Reek‎

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by maynak00** [comment]
**try with:**(temporary solution)
`desktopsolution.org##.blockOverlay.blockUI`
`desktopsolution.org##.blockPage.blockMsg.blockUI`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
