### ISSUE TITLE
miuipro.ru

### ISSUE THREAD

**Issue by exodius48** [reek/anti-adblock-killer#1576]
http://miuipro.ru/rommgr/device_view/468
http://image.prntscr.com/image/d89884a2f7d849bc974a579fddbf127d.png
Firefox 47.0 x86
Greasemonkey
uBlock Origin
AAK List, ABP Indo, EasyList, Spam404, MVPS HOSTS,  hpHosts’ Ad and tracking servers‎, etc

#Pop up show up when i click download button#

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
