### ISSUE TITLE
thewizardsmanse.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1583]
Hi, 

![anti-adblock-killer](http://i.imgur.com/ERXlXom.png)

on `http://www.thewizardsmanse.com/multiple-app-accounts-using-bluestacks/`

add: 
`/wp-content/plugins/ad-block-defender/*`

Thanks!

**Comment by reek** [comment]
thanks :+1:

**Comment by reek** [comment]
done
