### ISSUE TITLE
english-subtitles.club

### ISSUE THREAD

**Issue by grovtor** [reek/anti-adblock-killer#1584]
redirects to http://www.english-subtitles.club/adblock?ref=http://www.english-subtitles.club/search?idf=&s=Akta+Manniskor+s02e01

Chromium 51.0.2704.79 (64-bit)
Tampermonkey
Ublock Origin 

![blockingadblockingfails_seealsoproxomitron](https://cloud.githubusercontent.com/assets/19899857/15997725/2ecbdb20-30ec-11e6-833a-dd9bea2d42af.png)

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
