### ISSUE TITLE
ekstrabladet.dk

### ISSUE THREAD

**Issue by hchr** [reek/anti-adblock-killer#1586]
This also removes comments from fyre.com, so avoid if you need those comments.

They have change to a new anti add block script.

With uBlock, eighter of this removes it:
||ekstrabladet.dk/nationen/*/*$inline-script,first-party,important
||ekstrabladet.dk/template/*/shared/js/build/every.page.min.js?v=$script,first-party,important

**Comment by reek** [comment]
Thanks, I'll fix it

**Comment by hchr** [comment]
Hi reek
I added this to my report:
This also removes comments from fyre.com, so avoid if you need those comments.

**Comment by reek** [comment]
I'll kill it with AakScript.

**Comment by moensted** [comment]
i fixed the issue with ekstrabladet.dk by adding:
`ekstrabladet.dk##div[style*="99799"]`
in uBlock Origin

**Comment by reek** [comment]
done
