### ISSUE TITLE
jyllands-posten.dk

### ISSUE THREAD

**Issue by bipsendk** [reek/anti-adblock-killer#1587]
http://jyllands-posten.dk
http://imgbox.com/aQtVo60M
Google Chrome
Tampermonkey
uBlock Origin
AakList

**Comment by SMed79** [comment]
Add:
`jyllands-posten.dk/js/ads.js`

**Comment by reek** [comment]
@bipsendk 
Already killed by AakList

@SMed79 
Bad rule
