### ISSUE TITLE
infojobs.com.br

### ISSUE THREAD

**Issue by victorwss** [reek/anti-adblock-killer#1588]
The site http://www.infojobs.com.br/ is using an adblock killer.

![screenshot](https://cloud.githubusercontent.com/assets/4574568/16052023/a163d9d8-3238-11e6-816a-f9caa3ec9cdd.png)

I am using Google Chrome and have uBlock Origin.

I am using most of the default uBlock filters, including EasyList and Anti-Adblock Killer | Reek list.

**Comment by SMed79** [comment]
Can't reproduce !

**Comment by Giwayume** [comment]
You need to install the user script.

**Comment by victorwss** [comment]
The anti-Adblock page seems to load only after you log in the site. So, you must either create an account or already have one to get the anti-adblock page. Anyway, you can see that near the end of the http://stc.infojobs.com.br/generate/scriptsV3/generate/default-min.js file there is a webUI.Utils.StopAdBlock function which may eventually redirect to this page ("/nopublicity.aspx"). It seems to decide if the user should be redirected if the value of the "usip" field found in document.cookie is smaller than 5. I don't know yet how the "usip" value is setted, but I guess that it maybe the number of loaded ads or something related to that.

**Comment by victorwss** [comment]
By the way, I have tampermonkey installed.

**Comment by reek** [comment]
@victorwss 
I'll try to kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
