### ISSUE TITLE
Keep losing list subscription

### ISSUE THREAD

**Issue by Dragnier** [reek/anti-adblock-killer#1589]
At least once a week I have to re-subscribe. No idea what is causing this, but I'm glad it lets me know the sub is missing so I can.

**Comment by SMed79** [comment]
Hi, 
. backup/save your bookmarks, password.
. reset your browser settings ([/how-to-reset-your-web-browser-to-its-default-settings/](http://www.howtogeek.com/171924/how-to-reset-your-web-browser-to-its-default-settings/))
. installer an adblocker (ex: [Adblock Plus](https://adblockplus.org/), Adblock or uBo).
. add AaK list and AaK script https://github.com/reek/anti-adblock-killer#instruction

**Comment by jrussell999** [comment]
I'm having this issue too. It pops up a window saying "It appears you have not subscribed", then I go here: https://reek.github.io/anti-adblock-killer/#filterlist
Then I click Subscribe, then it goes to my chrome Adblock Plus Options, where everything looks like it is already subscribed, already added, and I have no idea what, if any, changes I am supposed to be making here.
I think the creator of this needs to write the instructions more clearly.

**Comment by xxcriticxx** [comment]
i think only affects chrome browser

**Comment by reek** [comment]
you can disable it
http://reek.github.io/anti-adblock-killer/#settings

> this can occur when uBO option `Parse and enforce cosmetic filters` is unchecked
