### ISSUE TITLE
https://www.vvvvid.it

### ISSUE THREAD

**Issue by Blelle** [reek/anti-adblock-killer#1590]
This site is using an adblock killer. Just try to watch a video

Please, fix this 

https://www.vvvvid.it

The message says that "my browser or my antivirus probably have an adblock system. Because VVVVID is a legal platform we suggest you to disable the adblock before continuing with the vision"

![immagine](https://cloud.githubusercontent.com/assets/17627130/16063075/b864b0f8-3297-11e6-8f9c-dd41434f44c3.png)

**Comment by reek** [comment]
Sorry, can't help you, content geolocked
