### ISSUE TITLE
dragcave.net

### ISSUE THREAD

**Issue by SystemRevolution** [reek/anti-adblock-killer#1591]
http://dragcave.net/
https://i.snag.gy/35FZwh.jpg
Google Chrome *Canary*
Tampermonkey
Ublock (The original, not the **uBlock Origin** one)
EasyList + AakList + EasyPrivacy

Adding this to the filter list we can avoid the aparition of the ad.
```
||static.dragcave.net/cache/js/a/^
##._w_4
```
![Comparation of filter](https://cloud.githubusercontent.com/assets/5545243/16068848/bdaa2d42-3286-11e6-88f8-1b87a66dfbc1.png)

Hope this make this awesome userscript better.

**Comment by maynak00** [comment]
uBlock Origin+Chromium+AakList+EasyList+EasyPrivacy+Tampermonkey+AAKScript
adblocker not detected.
![2016-06-15_123201](https://cloud.githubusercontent.com/assets/6183830/16074911/55c324bc-32f5-11e6-8f36-7ad73487c234.png)

**Comment by reek** [comment]
@SystemRevolution 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
