### ISSUE TITLE
deviantart.com

### ISSUE THREAD

**Issue by rcmero** [reek/anti-adblock-killer#1592]
This one is quite annoying. It takes up the entire bottom of the screen.

![sem titulo](https://cloud.githubusercontent.com/assets/5708421/16083911/a5d12184-330e-11e6-853d-e6efd3eddb9b.png)

URL: http://www.deviantart.com/
Browser: Firefox
Script manager: Greasemonkey
Adblocker: uBlock Origin
Filterlists: [Fanboy+Easylist-Merged Ultimate List‎](https://www.fanboy.co.nz/r/fanboy-ultimate.txt) + AakList

**Comment by Giwayume** [comment]
Filter:
`deviantart.com###block-notice`

**Comment by reek** [comment]
@rcmero 
Ok, I'll kill it

@Giwayume 
Thanks

**Comment by karma12gaming** [comment]
I had the same issue. Thanks for the filter.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
