### ISSUE TITLE
fullmatchesandshows.com

### ISSUE THREAD

**Issue by digitalchet** [reek/anti-adblock-killer#1593]
This site blocks the video pane, but invokes pop-under windows when AdBlock is disabled.

http://www.fullmatchesandshows.com/2016/06/15/copa-america-highlights-15th-june-2016/

![2016-06-16_111419](https://cloud.githubusercontent.com/assets/1274045/16103415/cfb956e4-33bb-11e6-87f5-72ebfaccea2b.png)

**Comment by Giwayume** [comment]
I'm not getting the message, can play video just fine.

**Comment by reek** [comment]
already killed by AakList
