### ISSUE TITLE
NSFW jizzman.com

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#1594]
`http://jizzman.com/`
![](https://cloud.githubusercontent.com/assets/16030872/16115083/4827500a-33c5-11e6-9bad-8620b0649d60.png)
Chrome 51
Tampermonkey 4.0.69
uBlock Origin 1.7.2
Default filterlists

Proposed solution: `/ad-blocking-advisor/*`

**Comment by reek** [comment]
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
