### ISSUE TITLE
lesechos.fr / lesechos.com

### ISSUE THREAD

**Issue by maxxyme** [reek/anti-adblock-killer#1595]
On this French news website, once you have read 8 articles for free, the rest is blocked.

e.g.
http://www.lesechos.fr/politique-societe/politique/0211031691160-interdiction-des-manifestations-satisfaction-a-droite-interrogations-a-gauche-2006720.php
only a few words are displayed, the rest is removed and replaced by an anti-adblock banner (see screenshot below)

![screenshot-www lesechos fr 2016-06-16 13-37-41](https://cloud.githubusercontent.com/assets/60419/16115488/99d901e4-33c7-11e6-9431-610c789fbd94.png)

**Comment by Giwayume** [comment]
```
      lesechos_fr : {
        host : ['lesechos.fr'],
        onStart : function() {
          Aak.addScript(function() {
            Object.defineProperty(window, "checkAdBlock", {
              value: function() {},
              configurable: false,
              writable: false
            });
          });
        }
      },
```

**Comment by Giwayume** [comment]
lesechos.com redirects to lesechos.fr, so that should be the title of the issue.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
