### ISSUE TITLE
NY Post

### ISSUE THREAD

**Issue by k808a** [reek/anti-adblock-killer#1596]
https://nypost.com/2016/06/16/gators-routinely-removed-from-lagoon-where-toddler-was-attacked/
Mozilla Firefox 47.0
Greasemonkey
uBlock Origin
AakScript/AakList
![screen shot 2016-06-16 at 1 45 23 am](https://cloud.githubusercontent.com/assets/10523356/16115732/abc4466a-3364-11e6-81f9-cd4513d00214.png)

**Comment by Giwayume** [comment]
What fools for relying on the global scope.
```
      nypost_com : {
        host: ['nypost.com'],
        onStart : function() {
          Aak.addScript(function() {
            window._sp_ = window._sp_ || {};
            window._sp_.config = window._sp_.config || {};
            Object.defineProperty(window._sp_.config, "content_control_callback", {
              value: function() {},
              writable: false,
              configurable: false
            });
          });
        }
      },
```

**Comment by reek** [comment]
@k808a 
Ok, I'll kill it, thanks

@Giwayume 
thanks

**Comment by Ineluctable** [comment]
Confirmed here as well.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
