### ISSUE TITLE
jc-mp.com

### ISSUE THREAD

**Issue by DirtyDan9613** [reek/anti-adblock-killer#1597]
Link To The Page -> https://www.jc-mp.com/forums/

[ScreenShot](http://imgur.com/QZzwlKI)

Browser
FireFox

Script Manager
GreaseMonkey

Adblocker
Ublock Origin

FilterList
EasyList + AakList

**Comment by Giwayume** [comment]
Script to stop detection:
```
      jc_mp_com : {
        host : ["jc-mp.com"],
        onStart : function() {
          Aak.addStyle('.adsense {width: 1px; height: 1px; visibility: hidden; display: block; position: absolute;}');
        }
      },
```

**Comment by reek** [comment]
@DirtyDan9613 
Ok, I'll kill it.

@Giwayume 
Thanks for rule :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
