### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by Nerijusas** [reek/anti-adblock-killer#1598]
[Link1](http://www.15min.lt/naujiena/aktualu/lietuva/kokiu-gerimu-pakuotes-priims-naujieji-taromatai-atmintine-tiems-kurie-turi-ka-atnesti-56-575569
)
[Link2](http://www.15min.lt/sportas/naujiena/futbolas/a-lyga-klaipedos-atlantas-vejasi-lyderius-24-642201)

Mozilla Firefox
Greasemonkey
uBlock Origin
AakList+Easylist

[ScreenShot1](https://i.gyazo.com/79b5eda4b8e557b58382526cfcc9fb4d.jpg)
[ScreenShot2](https://i.gyazo.com/8768c79ee4428cad336536202e9594bc.jpg)

**Comment by SMed79** [comment]
Use the search before posting & If your topic already exists post in the old topic.

Duplicate https://github.com/reek/anti-adblock-killer/issues/432 https://github.com/reek/anti-adblock-killer/issues/1513 https://github.com/reek/anti-adblock-killer/issues/1525

**Comment by Nerijusas** [comment]
sorry :(

**Comment by SMed79** [comment]
See if helps https://forums.lanik.us/viewtopic.php?f=101&t=30727&hilit=15min.lt

**Comment by reek** [comment]
@Nerijusas 
I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
