### ISSUE TITLE
channel4.com

### ISSUE THREAD

**Issue by unabatedshagie** [reek/anti-adblock-killer#16]
http://www.channel4.com/programmes/the-secret-life-of-students/4od#3719760
http://i.imgur.com/I1UAn4X.png
Chrome (35.0.1916.153 m)
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by SevereOverfl0w** [comment]
This would definitely be a handy addition.

**Comment by reek** [comment]
Hi,

Sorry, no solution

**Comment by SevereOverfl0w** [comment]
Ever? Or just as you cannot debug due to geolock?

**Comment by reek** [comment]
No, due to cross-domain protection and flash player

2015-02-20 23:58 GMT+01:00 SevereOverfl0w <notifications@github.com>:

**Comment by SevereOverfl0w** [comment]
That's a shame :( Okay. I did wonder if that was it.
