### ISSUE TITLE
www.isramedia.net

### ISSUE THREAD

**Issue by OrBin** [reek/anti-adblock-killer#1603]
http://www.isramedia.net/
http://i.imgur.com/E5lRmhP.png
Google Chrome
No Script manager
uBlock Origin
Using many of the filterlists suggested by uBlock, including anti-adblock-killer and EasyList Hebrew‎.

The solution should be:
`www.isramedia.net###xxxxxvc0897`

**Comment by maynak00** [comment]
@reek, without aakscript, no antiadblock message.with aakscript adblocker detected

**Comment by reek** [comment]
@OrBin 
Already killed by AakScript, see instrunctions
