### ISSUE TITLE
gamestar.de

### ISSUE THREAD

**Issue by AetherMcLoud** [reek/anti-adblock-killer#1605]
www.gamestar.de still shows quite a lot of ads, and the video player shows ads too, especially strange on linked youtube videos which too will show an ad in front of the video.

Also, for videos that use the built in site player, with uBlock Origin and AAK the player will switch to a low-resolution player that shows the anti-adblock banner. With adblock off, the player UI is black instead of white, and it will show HD videos.

Example of low rez video player with uBlock and AAK on: https://i.imgur.com/l6zIWEQ.jpg
The low rez player is a flash plugin by default, when disabling flash in Chrome, it switched to a HTML5 low rez player so that didn't help either. The HD player is always HTML5 I think.

Same site with uBlock off, showing the default HD player: https://i.imgur.com/G9UJ5Bl.jpg

Site for that video: http://www.gamestar.de/videos/e3,106/the-legend-of-zelda-breath-of-the-wild,89161.html

The default site, www.gamestar.de shows the "please disable adblock" banner in the middle like this: https://i.imgur.com/K2E2sdU.jpg

Example of ads still going thru uBlock and AAK, also a embedded youtube video playing an ad: http://i.imgur.com/SPShSgi.jpg

Link for that example: http://www.gamestar.de/news/vermischtes/3274493/star_wars.html

I really hope this is fixable, because the site has good content but the ads are getting more annoying each day.

**Comment by reek** [comment]
if AakScript 9.7 does not work, I have no alternative to offer
