### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by p4pergoat** [reek/anti-adblock-killer#1606]
http://www.multiup.org/en/download/c79639596669f02b9aeddc82b024744a/K8M38VSK8aM3H3VC.mkv

http://image.prntscr.com/image/01867a0107294b38a9056df03277b6ce.png (Press "Download" button. Note that this is not my file, I found it in google)

Google Chrome
Tampermonkey
uBlock Origin

http://prntscr.com/am1vnk (Easylist + AakList + Adblock Warning Removal List + Peter Lowe's Ad server list + some others)

**Comment by maynak00** [comment]
tested with all your filters.not detected(aakscript enabled). **solution**: install Aakscript
or try with: `@@||163.172.29.124/pop.js$script,domain=multiup.org`

**Comment by p4pergoat** [comment]
Thanks, the filter work!
I already had Aakscript enabled in Tampermonkey btw.

**Comment by reek** [comment]
@p4pergoat 
I'll fix it, thanks

@maynak00 
Thanks for rule

**Comment by leonsylvers** [comment]
Damn, doesn't work with Aakscript and/or with @@||163.172.29.124/pop.js$script,domain=multiup.org on My Filters in uBlock

**Comment by reek** [comment]
@leonsylvers 
it works, see help https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
