### ISSUE TITLE
ekstrabladet.dk

### ISSUE THREAD

**Issue by Daneguy** [reek/anti-adblock-killer#1609]
Anti-Adblock Killer stopped working on entire site a week ago. Must disable

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by LindaLawton** [comment]
http://ekstrabladet.dk/
http://imgur.com/1xv7qxk
chrome 
Tamper monkey
adblock plus 
EasyList + AakList

**Comment by Daneguy** [comment]
Thanks for posting answer, LindaLawton

Same with Firefox

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
