### ISSUE TITLE
socketloop.com

### ISSUE THREAD

**Issue by xDinomode** [reek/anti-adblock-killer#1614]
A website is using blockadblock.com and I've followed the tutorial but it still doesn't work.

**Comment by Giwayume** [comment]
You need to tell us what website.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by xDinomode** [comment]
[https://socketloop.com](https://socketloop.com)

![image](http://i.imgur.com/dc6LM95.png)

* Mozilla Firefox 

* Greasemonkey

* Ublock Origin 

* AaKList

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
