### ISSUE TITLE
http://www.strikeout.me

### ISSUE THREAD

**Issue by khrwani** [reek/anti-adblock-killer#1618]
http://www.strikeout.me/

![screenshot-www strikeout me 2016-06-20 19-06-20](https://cloud.githubusercontent.com/assets/15929813/16206952/5500a044-371a-11e6-8d9e-e682e03f7375.png)

*Firefox 47.0
*Greasemonkey
*Adblock Plus
*Adblock warning removal list - Malware domains - Aaklist anti adbocl killer - Facebook annoyance  blocker - Ruadlist+easylist -  listeAr+listFr+Easylist

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
