### ISSUE TITLE
Doesn't work on http://www.dasolo.org

### ISSUE THREAD

**Issue by NessunoIM** [reek/anti-adblock-killer#1620]
Site:http://www.dasolo.org/

![ddaaaaaa](https://cloud.githubusercontent.com/assets/19640640/16234100/bc5e6c74-37d0-11e6-8871-979f7758fc9b.png)

After clicking ok...

![daso](https://cloud.githubusercontent.com/assets/19640640/16214891/283ebdd2-375d-11e6-9333-3b3612353c9b.png)

Mozilla Firefox 47
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by giampi75** [comment]
I cannot confirm: for me, all is ok (identical configuration)

**Comment by NessunoIM** [comment]
Solved! The problem was Ghostery.
