### ISSUE TITLE
diymediahome.org

### ISSUE THREAD

**Issue by itprotj** [reek/anti-adblock-killer#1621]
Doesn't work on

https://diymediahome.org/an-better-alternative-to-mcebuddy/

![2016-06-21_17-10-38](https://cloud.githubusercontent.com/assets/7754695/16220911/1e9c0cf0-37d3-11e6-99ca-82f0d11dbdb4.jpg)

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
