### ISSUE TITLE
lesechos.fr

### ISSUE THREAD

**Issue by xy2iii** [reek/anti-adblock-killer#1622]
www.lesechos.fr

![a](http://imgur.com/AcHr1EA.png)

Firefox Nightly 50.0a1
Greasemonkey
uBlock Origin
 AakList

**Comment by reek** [comment]
I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
