### ISSUE TITLE
thesimsresource.com

### ISSUE THREAD

**Issue by Quilava7728** [reek/anti-adblock-killer#1625]
http://www.thesimsresource.com/
https://imgur.com/xrwBvY7
Chrome
Tampermonkey
ublock origin
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by mapx-** [comment]
@@||glam.com^$script,domain=thesimsresource.com

**Comment by Quilava7728** [comment]
I'm not really sure where to put it just yet, but thank you so much! :)

**Comment by Quilava7728** [comment]
Ah, okay. Thank you again! :D

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
