### ISSUE TITLE
play.tv3.lt (tv3play)

### ISSUE THREAD

**Issue by nevaldas** [reek/anti-adblock-killer#1627]
http://play.tv3.lt/programos/svotai
https://i.imgur.com/pbq0V2y.png
Chrome 51.0.2704.103 m
Tampermonkey
Adblock plus
EasyList + AdBlockPlusLithuania + AakList

**Comment by Nerijusas** [comment]
yes please fix this :+1:

**Comment by reek** [comment]
Ok, I'll try to kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
