### ISSUE TITLE
tsviewer.com

### ISSUE THREAD

**Issue by Bluscream** [reek/anti-adblock-killer#1629]
https://www.tsviewer.com/index.php?page=ts_viewer&ID=1085722
![image](https://cloud.githubusercontent.com/assets/3318223/16281387/7a73e8b2-38c4-11e6-847a-4854aa5c389e.png)
Microsoft Edge
Adguard
AakScript + AakList

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Bluscream** [comment]
> Do not forget to donate, review, share, follow and add to favorites.

Sounds like a YouTube kiddy :D

**Comment by reek** [comment]
@Bluscream :smile:
