### ISSUE TITLE
Does this add-on allow the blocking of pop-out ad's?

### ISSUE THREAD

**Issue by AronaxAE** [reek/anti-adblock-killer#1630]
So on the website http://www.projectwatchfree.tv/ when I click somewhere it pops out another tab with an ad on it, is that fixable though this?

Also there are ads on this page anyway which can also be removed.

**Comment by Giwayume** [comment]
This addon isn't for removing ads, it's for removing messages (and adblock prevention measures) that tell you or force you to turn off your adblocker. You should go to the easylist forums if some ads are escaping your adblocker.

**Comment by reek** [comment]
@AronaxAE 
Report to https://forums.lanik.us/
