### ISSUE TITLE
itsupportguides.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1632]
Hi, 

![anti-adblock-killer](http://i.imgur.com/3Ix3oOK.png)

`itsupportguides.com##.adblock_wrapper`

`https://www.itsupportguides.com/windows-10/windows-10-`
https://forums.lanik.us/viewtopic.php?f=64&t=31164

Thanks!

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
done
