### ISSUE TITLE
ekstrabladet.dk

### ISSUE THREAD

**Issue by zomper** [reek/anti-adblock-killer#1634]
www.eb.dk
www.ekstrabladet.dk
http://prntscr.com/bkgrqy
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by maynak00** [comment]
duplicate https://github.com/reek/anti-adblock-killer/issues/1609

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by zomper** [comment]
ing.dk and eb.dk still see killer

best regards, nice  project love it
--------------------------------------------
On Wed, 7/6/16, reek <notifications@github.com> wrote:

 Subject: Re: [reek/anti-adblock-killer] ekstrabladet.dk (#1634)
 To: "reek/anti-adblock-killer" <anti-adblock-killer@noreply.github.com>
 Cc: "zomper" <kasper111@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Wednesday, July 6, 2016, 7:13 PM
 
 Hi,
 
 Anti-AdBlock Killer has been updated ! Changelog
 
 Step 1: Update
 : UserScript
 Step 2: Update
 : FilterList
 
 Do not forget to donate, review, share, follow and add to
 favorites.
 
 See you
 Reek
 
 https://github.com/reek/anti-adblock-killer/
 
 https://twitter.com/antiadbkiller
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mapx-** [comment]
for ing.dk, add this filter to ABP
@@||ing.dk/*ad$script

for eb.dk, see:
https://forums.lanik.us/viewtopic.php?p=95928#p95928

eventually (if does not work) install the last dev build of ABP for firefox (which fixes on old bug with hiding filters):
https://adblockplus.org/en/development-builds#installation

**Comment by zomper** [comment]
oki, thx - it worked! 

can u fix pol.dk too?

www.pol.dk (www.politiken.dk)

best wishes
--------------------------------------------
On Tue, 7/26/16, mapx- <notifications@github.com> wrote:

 Subject: Re: [reek/anti-adblock-killer] ekstrabladet.dk (#1634)
 To: "reek/anti-adblock-killer" <anti-adblock-killer@noreply.github.com>
 Cc: "zomper" <kasper111@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, July 26, 2016, 3:06 PM
 
 for ing.dk, add this filter to
 ABP
 
 @@||ing.dk/*ad$script
 
 for eb.dk, see:
 
 https://forums.lanik.us/viewtopic.php?p=95928#p95928
 
 eventually (if does not work) install the last dev build
 of ABP for firefox (which fixes on old bug with hiding
 filters):
 
 https://adblockplus.org/en/development-builds#installation
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mapx-** [comment]
add

@@||politiken.dk/*ad$script

**Comment by zomper** [comment]
thx it works, - i think i got the clue now :-D
--------------------------------------------
On Fri, 7/29/16, mapx- <notifications@github.com> wrote:

 Subject: Re: [reek/anti-adblock-killer] ekstrabladet.dk (#1634)
 To: "reek/anti-adblock-killer" <anti-adblock-killer@noreply.github.com>
 Cc: "zomper" <kasper111@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, July 29, 2016, 11:47 AM
 
 add
 
 @@||politiken.dk/*ad$script
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
