### ISSUE TITLE
noticias.uol.com.br

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1635]
Hi, 
http://i.imgur.com/RvvyrMN.png
`http://noticias.uol.com.br/`
`@@||jsuol.com.br/c/detectadblock/adframe.js`

Thanks!

(www1.folha.uol.com.br https://github.com/reek/anti-adblock-killer/issues/1396)

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
done
