### ISSUE TITLE
realgm.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1636]
Hi, 
when adblock detected they inject new ads (for **gpt_sp** script) http://i.imgur.com/Or3GyO5.png
`http://basketball.realgm.com/wiretap/242408/Lakers-To-Aggressively-Pursue-Hassan-Whiteside`

https://forums.lanik.us/viewtopic.php?p=97149#p97149

Thanks!

**Comment by mapx-** [comment]
working filters
@@||realgm.com^$genericblock
@@||realgm.com^$generichide
||sp.realgm.com^$domain=basketball.realgm.com
||googlesyndication.com^$domain=basketball.realgm.com
basketball.realgm.com##[id^="google_ads_iframe"]

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
