### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by jonasthambert** [reek/anti-adblock-killer#1639]
js injected to all pages.

![Image](http://i.imgur.com/YRpHo6D.png)

**Comment by aussieskinhead** [comment]
Same issue for me as with the OP.

**Comment by dmo1111** [comment]
same, how should i fix it?

**Comment by githubfun** [comment]
I don't have this problem. i use ublock origin however.

**Comment by jonasthambert** [comment]
Using ublock origin also on Chrome, one computer is fine the other isn't.

**Comment by maynak00** [comment]
**try with:**
@@||investing.com/js/ads.js$script

**Comment by jonasthambert** [comment]
Seems to work, thanks ;)

**Comment by mattofomaha** [comment]
maynak00 can you explain where and how to place it "@@||investing.com/js/ads.js$script" please.

**Comment by dmo1111** [comment]
go to options, add own filter, then paste and press the button. viola!

**Comment by reek** [comment]
@maynak00 
thanks

**Comment by mattofomaha** [comment]
Thank you dmo1111, but neither the adblock plus nor greasemonkey have "add own filter" in the options, only the closest thing is "filter preferences" in adblock plus which lets you add filter subscriptions and when I place it there it doesn't do anything.

**Comment by jonasthambert** [comment]
mattofomaha: Use uBlock Origin

**Comment by mattofomaha** [comment]
jonasthambert: Thank you, it worked on Firefox but was pain in the neck to get the charts showing, didn't show the adblock warning but chart was not showing either chart area was coming up blank finally I managed through browser history opened an older page with private browsing view and copy and paste it to bookmarks very strange way but now it's showing the chart fine. Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by BrianFX** [comment]
I'm seeing these pop-ups for the first time ever today (running Chrome & uBlock Origin). Googled, found this, installed precisely per the instructions, and the pop-ups are not going away. Anyone else having issues with blocking the script/pop-up as of today?

**Comment by X01X012013** [comment]
@BrianFX I have not seen any pop ups, are you sure you installed both Aak List and Aak Script?

**Comment by mattofomaha** [comment]
@BrianFX  me to I am seeing the pop-up on investing.com today first time since I installed Aak on uBlock Origin with Greasemonkey and @X01X012013 yes I checked both Aak list and Aak script still there and works fine for other sites.

**Comment by X01X012013** [comment]
@mattofomaha Hum, I did get a gray screen without anything on it, I clicked once and it's gone. After that I am not getting anything. It can be a uBlock Origin's problem, I'm using AdBlock Plus and that website works perfectly fine.

**Comment by mattofomaha** [comment]
@X01X012013 Thank you, what browser do you use? I use Firefox and used Adblock Plus before but with the script I got no pop ups but the chart area was coming blank what ever I tried didn't work then to be able to add user comment in to my filters section as suggested above "@@||investing.com/js/ads.js$script" I changed to uBlock Origin and it was working fine just today pop up started showing again.

**Comment by X01X012013** [comment]
@mattofomaha I use Opera, AdBlock Plus, and Tampermonkey. I have Aak and my custom script installed. This website is not covered in my custom script so it will not activate. I can see everything perfectly fine, charts, videos, texts, no pop ups. http://i.imgur.com/lfjbbIE.png

**Comment by mattofomaha** [comment]
@BrianFX Thank you for the info and going through all that trouble I appreciate. I never tried Opera, I guess you are a Mac user. From the link you captured I can't see any live price chart showing, if you go this link can you see the interactive price chart in the middle of the page? http://www.investing.com/commodities/crude-oil-advanced-chart

**Comment by X01X012013** [comment]
@mattofomaha That chart is working just fine. And I am a Windows user, the PC that I am using is built by myself, in case you are wondering what that OEM logo is. It is a clean Windows without any blow-ware. 
http://imgur.com/tfkVNEL

**Comment by mattofomaha** [comment]
@X01X012013 thanks again, I know what you mean by Mac is being too expansive besides that it's to inquisitive for me and don't let me do anything I want to do my way :) I used to build computers for living long time ago don't bother any more :) I don't know what's the difference btw PPAPI and NPAPI flash so I guess I should look into that

**Comment by SMed79** [comment]
`@@||static.doubleclick.net/instream/ad_status.js$domain=investing.com`
https://adblockplus.org/forum/viewtopic.php?f=1&t=47287

https://bpaste.net/show/05b9f1d29eee >> `http://glocdn.investing.com/js/main-1.11.79.min.js`

**Comment by mattofomaha** [comment]
@SMed79 Thank you, where do you insert the code Greasemonkey or Adblock Plus?
