### ISSUE TITLE
Crunchyroll.com

### ISSUE THREAD

**Issue by LvsLight** [reek/anti-adblock-killer#1640]
http://static.ak.crunchyVersion:roll.com/versioned_assets/supporting-anime.42c71a24.mp4

Version: 9.7 
AakScript: true AakList: 
true Browser: Chrome 
ScriptManager: Tampermonkey 
Adblocker: Adblock

http://prntscr.com/bli9is

http://www.crunchyroll.com/gintama/episode-263-two-brothers-620089?t=0

Please update the script! THANKS!

**Comment by maynak00** [comment]
**try with:**
`@@||crunchyroll.com/*/ads_enabled_flag*.js$script`

**Comment by LvsLight** [comment]
sorry, idk what to do with that xD

**Comment by LvsLight** [comment]
Where do i put that code??!!

**Comment by reek** [comment]
thanks @maynak00

**Comment by LvsLight** [comment]
@reek What do i do with that: @@||crunchyroll.com/*/ads_enabled_flag*.js$script      or did you already update, i checked it works now thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
