### ISSUE TITLE
esradio.libertaddigital.com

### ISSUE THREAD

**Issue by basuraespacial** [reek/anti-adblock-killer#1642]
Hi all, the details following the guide are below:

http://esradio.libertaddigital.com/fonoteca/2016-06-27/prensa-economica-podemos-iu-bajan-un-36-en-madrid-102319.html (and similar pages in the same subdomain, audio player blocked by AntiAdblock script in the website)
http://i.imgur.com/m8lIgWj.png
Google Chrome 51.0.2704.103
Tampermonkey 4.0.69
Adguard AdBlocker 2.3.8
EasyList + AakList

Would appreciate help identifying the script to be blocked or an update for the filter, thank you!!

**Comment by maynak00** [comment]
**try with:**
`@@||libertaddigital.com/js/ads.js$script`
**or**
`libertaddigital.com##.reveal-modal-bg`
`libertaddigital.com###bloqueador`

**Comment by basuraespacial** [comment]
Thanks for the fast reply maynak00.

I tried adding the three lines above to Adguard, and the pop-up disappeared.
However the audio is still not playable. Any additional advice is appreciated.

**Comment by reek** [comment]
@basuraespacial 
Ok, I'll kill it, thanks

**Comment by basuraespacial** [comment]
Ok, so here's a workaround I've found:

- Load the website with Adguard enabled (including the filters suggested above by maynak00)
- Disable Adguard
- Play the content

Does anyone else have any idea about what else I could do to avoid manually disabling Adguard?

Thanks in advance.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
