### ISSUE TITLE
proplanta.de

### ISSUE THREAD

**Issue by 0n3-70uch** [reek/anti-adblock-killer#1643]
http://www.proplanta.de/Agrar-Wetter/Deutschland/
http://imgur.com/qXGKB51
Google Chrome
51.0.2704.106 (64-bit)
Tampermonkey
Adblock
AakList

Thanks for this nice tool :-)

**Comment by maynak00** [comment]
**try with:**(temporary solution)
`proplanta.de#@#.searchad`
`proplanta.de#@#.adsbygoogle`
`proplanta.de#@##mainAd`
`proplanta.de#@##bottom_ad`
`proplanta.de#@##ad_img`
`proplanta.de#@##ad_728_90`
`proplanta.de#@##adDiv`
`proplanta.de#@##Ads_BA_SKY`
`proplanta.de###BODYHINTERGRUND > .adsbygoogle`

**Comment by 0n3-70uch** [comment]
Thanks

**Comment by reek** [comment]
@0n3-70uch 
Ok, I'll kill it, thanks

@maynak00 
Thanks :+1:

**Comment by 0n3-70uch** [comment]
Perfect. Thank you.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
