### ISSUE TITLE
Dcode.fr

### ISSUE THREAD

**Issue by Felina-Lain** [reek/anti-adblock-killer#1651]
http://www.dcode.fr/
Chrome
TamperMonkey
Adblock
easylist + aak list

Try to use any of the dcode page and use it a few times and it gives you a white pop-up saying to deactivate adblock. I tried block it manually but it's still coming back.

**Comment by reek** [comment]
no detected

**Comment by Felina-Lain** [comment]
what does that means? does it mean you couldn't detect the problem, or reek couldn't detect the ad?

**Comment by reek** [comment]
I have no message, you can make a screenshot

**Comment by Felina-Lain** [comment]
Nevermind, I found it... at least I haven't had the message in a while so I think I found it, I added this to my blocking list
www.dcode.fr##DIV[id="yb5d"]
and it seems to work
thanks anyway :)

**Comment by reek** [comment]
weird, I do not find this element, I will add still your solution, thank you
