### ISSUE TITLE
mil.ink

### ISSUE THREAD

**Issue by BioBrayan** [reek/anti-adblock-killer#1652]
http://mil.ink/l/3ief
http://fs5.directupload.net/images/160630/potqggi5.png

Google Chrome 51.0.2704.106 
uBlock Origin 1.7.6
EasyList‎
EasyPrivacy
AakList (Anti-Adblock Killer)‎ 9.7

resolver el captcha cerrar la página volverla a abrir y verás cómo se activa el anti Adblock

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
