### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by r0h1n** [reek/anti-adblock-killer#1653]
http://timesofindia.indiatimes.com/blocked.cms
https://imgur.com/7wwDdIt
Mozilla Firefox
Greasemonkey
UBlock Origin
EasyList + Peter Lowe's Adserver List + AakList

**Comment by wiseguy100** [comment]
Check if you have admuncher and disable it.

**Comment by ghitesh** [comment]
Times Of India implemented anti-adblock only today

All links are redirecting to http://timesofindia.indiatimes.com/blocked.cms

Sample link.
http://timesofindia.indiatimes.com/india/Busted-IS-cell-wanted-to-plant-beef-at-temple-spark-riots-during-Ramzan/articleshow/52980868.cms

Mozilla Firefox
Greasemonkey
Anti-Adblock Killer | Reek
AakList (Anti-Adblock Killer) +  Adblock Warning Removal List + EasyList  (In that sequence)

**Comment by r0h1n** [comment]
Nope, don't have admuncher installed.

**Comment by the-solipsist** [comment]
Here's the JS (minified) that checks for ad-blockers:
http://timesofindia.indiatimes.com/detector/minify-1.cms

**Comment by ghitesh** [comment]
> http://timesofindia.indiatimes.com/detector/minify-1.cms
@the-solipsist  Thanks. I added the above URL as custom block and site is working fine now.

**Comment by wiseguy100** [comment]
How do you add as a custom block ? Please give us the steps.

**Comment by ghitesh** [comment]
I added it as custom Filter URL in adblock plus. 

Steps:
Click ABP Icon -> Filter Preferences -> Custom Filter -> Add Filter ( on extreme right) 

<img src=http://i.imgur.com/WoEf6JC.png" />

It should be something similar for other adblock.

**Comment by ghitesh** [comment]
The URL which should be blocked is now updated to http://timesofindia.indiatimes.com/detector.cms

**Comment by bharatkrishna** [comment]
How do I add this to AdBlock in Chrome?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by msravi** [comment]
hindustantimes.com also has an adblock detector:
Example page: 
http://www.hindustantimes.com/india-news/sheila-dikshit-named-congress-cm-candidate-in-up/story-5HpmgHnmglBfSiYgqUyBeP.html

And here's the checkAdBlocker() function: 
http://www.hindustantimes.com/res/js/ht-modified-script.js

**Comment by reek** [comment]
@msravi 
See: https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672

**Comment by msravi** [comment]
Yes, thank you. That works.

**Comment by piyushgarg** [comment]
Disable the Javascript on this page like this. Then there will be no ad block warning, works on most of the news sites. Good for only content reading.
![image](https://cloud.githubusercontent.com/assets/246124/17475580/52432090-5d79-11e6-870e-090595d8942d.png)

**Comment by reek** [comment]
done
