### ISSUE TITLE
bhaskar.com

### ISSUE THREAD

**Issue by qbswzz** [reek/anti-adblock-killer#1656]
http://www.bhaskar.com/news-ep/KZHK-thousands-of-shiva-lingas-in-the-shamala-river-news-hindi-5361980-PHO.html

this is not working here it blocks entire page

**Comment by SMed79** [comment]
@qbswzz https://forums.lanik.us/viewtopic.php?f=62&t=31290

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
