### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by mash2u** [reek/anti-adblock-killer#1657]
http://timesofindia.indiatimes.com/world/uk/Brexit-campaign-leader-Boris-Johnson-wont-run-for-leadership-of-UKs-Conservative-Party/articleshow/52990884.cms
take you here:  http://timesofindia.indiatimes.com/blocked.cms
http://imgur.com/GNgX193
Google Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
