### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by kamalahluwalia** [reek/anti-adblock-killer#1659]
http://timesofindia.indiatimes.com/
http://www.hindustantimes.com/
http://www.ndtv.com/
Firefox
Tampermonkey
Adblock plus
EasyList + AakList
![anti-adblock killer](https://cloud.githubusercontent.com/assets/20236078/16511581/65ee0574-3f6f-11e6-8969-c971d36ba089.jpg)

**Comment by maynak00** [comment]
**hindustiantimes try with:**
`@@||hindustantimes.com/*/ads.js$script`

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/1672#issuecomment-230386581

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by kamalahluwalia** [comment]
Thanks for your efforts reek, greatly appreciated.
But suggested way is not working efficiently, it works for a day or just few clicks intermittently.

**Comment by reek** [comment]
@kamalahluwalia 
Try https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672
