### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by technode7** [reek/anti-adblock-killer#1660]
http://www.ndtv.com/welcome
http://imgur.com/a/GSpGV
Safari
Tampermonkey
Adblock
EasyList + AakList

**Comment by vishwassharma** [comment]
I dont know api enough to write a filter but sure i can help. Here is what ndtv is doing in checking if adblocker is present or not
```javascript
var canRunAds = true;

function checkIfNoAds() {
    if (canRunAds) {
        (function() {
            var e = document.createElement("img");
            e.height = "1";
            e.width = "1";
            e.style.display = "none";
            e.async = true;
            e.src = "http://drop.ndtv.com/test/__utm.gif";
            (document.getElementsByTagName("head")[0] || document.getElementsByTagName("body")[0]).appendChild(e);
            ifrm = document.createElement("IFRAME");
            ifrm.setAttribute("src", "http://drop.ndtv.com/test/nogano.html?v=%2Fvideo%2Flive%2Fchannel%2Fndtv24x7%3Fpfrom%3Dhome-topnavigation2016");
            ifrm.style.width = 1 + "px";
            ifrm.style.height = 1 + "px";
            document.body.appendChild(ifrm);
        })()
    }
}

window.onload = checkIfNoAds;

var N = 0x29 + 0x921 + 0x3712;

canRunAds = true;
window.setTimeout(function() {
    var T = document.getElementById(N);
    if (T.offsetHeight !== 0 && T.style.display != 'none') {
        canRunAds = false;
    }
    T.remove();
    if (canRunAds == true) {
        window.location = 'http://www.ndtv.com/welcome';
    }
}, 100);
```

**Comment by mapx-** [comment]
just update easylist

**Comment by Ntweat** [comment]
Updated EasyList still not working

**Comment by ramakay** [comment]
I think it now uses this

<div id="16476" class="ad300" style="height:1px;width:1px;">&nbsp;</div><script>canRunAdsN = true;var N = 0x29 + 0x921 + 0x3712;window.setTimeout(function() {var T = document.getElementById(N);if (T.offsetHeight !== 0 && T.style.display != 'none') {canRunAdsN = false;}T.remove();if(canRunAdsN == true){window.location = 'http://www.ndtv.com/request';} }, 100);</script> 

The div id `16476` is the value of Variable `N` - Not sure if it changes per page. The only static variable is a className of  `ad300`

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
@vishwassharma 
:+1:

**Comment by Ntweat** [comment]
It is killed.. Thanks @reek

**Comment by technode7** [comment]
It works fine with AdblockPlus but not working with Adblock. Anyway thanks @reek

**Comment by technode7** [comment]
Well, its back again :( i think they changed their tactics.

**Comment by Ntweat** [comment]
NDTV has come with a new detection script

Add to solve :

`@@||ads.rubiconproject.com/*^$script`

Already solved
