### ISSUE TITLE
Mid-day.com

### ISSUE THREAD

**Issue by navjotjsingh** [reek/anti-adblock-killer#1661]
Doesn't work on Mid-day.com and several other Indian News websites.

**Comment by maynak00** [comment]
**try with:**
`@@||mid-day.com/*/ads.js$script`

**Comment by Nam3less79** [comment]
thanks mayank it worked. It was just creating unnecessary irritation.

**Comment by reek** [comment]
@maynak00 
thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
