### ISSUE TITLE
eurosolidaire.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#1665]
Hi, 

`http://www.eurosolidaire.com/faire-un-micro-don-gratuitement.php`
```
@@||eurosolidaire.com^$generichide
@@||googleads.g.doubleclick.net/favicon.ico$domain=eurosolidaire.com
```

(https://github.com/reek/anti-adblock-killer/issues/1664)

Thanks.

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
done
