### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by Splinterjke** [reek/anti-adblock-killer#1666]
http://blockadblock.com
https://puu.sh/pMuiX/df22c2fed8.png
Google Chrome 52.0.2743.49 beta-m (64-bit)
Tampermonkey
Adblock Plus
Adblock Warning Removal List+RuAdList+EasyList+AakList (Anti-Adblock Killer)

**Comment by mapx-** [comment]
see the filters here:
https://forums.lanik.us/viewtopic.php?p=93294#p93294

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by malimM** [comment]
@reek I see an update was released four days ago, but it doesn't counter blockadblock.com.

**Comment by reek** [comment]
yes, because I have not had time to patch it, but it will be done.

2016-07-11 13:45 GMT+02:00 mustaqim <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
