### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by phone8588** [reek/anti-adblock-killer#1672]
Clicking anywhere on the homepage indiatimes.com leads to a disable adblock page - http://www.indiatimes.com/blocked.html

**Comment by rnavaneethan** [comment]
Below rule will fix for indiatimes.com. Would be nice to be included in next update.

```
! anti adblocker changes
! var window.canRun = true;
@@||indiatimes.com/ads.cms$script
```

**Comment by SMed79** [comment]
Fixed by easylist https://forums.lanik.us/viewtopic.php?p=97537#p97537

**Comment by aseemgautam** [comment]
I added the above to ublock origin my filters. Does not seem to work.

**Comment by rnavaneethan** [comment]
@aseemgautam It is still working fine for me in both indiatimes & economictimes. What URL it's not working? Not sure about mobile site though.

**Comment by aseemgautam** [comment]
Any url. Do you use adblock plus?

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=97616&#p97616

**Comment by aseemgautam** [comment]
@SMed79 purged and updated filters in uBlockOrigin. In custom filter - AAKList is checked.
![filters](https://cloud.githubusercontent.com/assets/3583020/16564075/37337eb0-4223-11e6-92b7-9072d6f36354.png)
Not working.

**Comment by SMed79** [comment]
Remove these custom filters & add only: 
`||hindustantimes.com/res/js/ht-script.js`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rnavaneethan** [comment]
Thanks @reek . Is related pull request also can be closed?

[Related pull request](https://github.com/reek/anti-adblock-killer/pull/1677)
