### ISSUE TITLE
Timesofindia.com and Hindustantimes.com

### ISSUE THREAD

**Issue by surpeet** [reek/anti-adblock-killer#1673]
Hi, will greatly appreciate it if you can add the sites in the attached screenshots to the list. Thanks a lot!
 
Details:
http://antiblock.org/?p=v3&demo
Google Chrome
Tampermonkey
Ublock Origin
AakList
<img width="1153" alt="screen shot 2016-07-01 at 11 14 50 pm" src="https://cloud.githubusercontent.com/assets/20244996/16526032/d0acedea-3fe1-11e6-8d2a-7ae8a86b516d.png">
<img width="1150" alt="screen shot 2016-07-01 at 11 15 46 pm" src="https://cloud.githubusercontent.com/assets/20244996/16526033/d0b96b10-3fe1-11e6-9f09-42e6b0a9e045.png">

**Comment by surpeet** [comment]
Solved by adding EasyList - https://easylist.github.io/

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/1672#issuecomment-230386581

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by prasannjeet** [comment]
Hello Reek,

Looks like Hindustan Times stopped working again. Check this link:
http://www.hindustantimes.com/other-sports/budhia-singh-the-marathon-boy-lost-in-the-streets-of-odisha/story-7C2i9KpVoCCrYtwwIbxzuI.html

![lo](https://cloud.githubusercontent.com/assets/1756270/17099177/50ebb40a-5284-11e6-8943-375d7aaa5696.PNG)

Can you check the problem? Thanks.

**Comment by mapx-** [comment]
just add this filter in your adblocker
@@||hindustantimes.com^$script,domain=hindustantimes.com

**Comment by prasannjeet** [comment]
Thanks a lot! It works now :)


*Thanks and Regards,*

*Prasannjeet Singh*
