### ISSUE TITLE
Indian sites - blocking adblockers

### ISSUE THREAD

**Issue by phone8588** [reek/anti-adblock-killer#1674]
From the various issues posted in last couple hours, it seems like Indian sites have coordinated an anti- ad blocker move - or are they using one vendor, which pulled a new trick out of the hat?

**Comment by maverick0193** [comment]
Yup i have seen that on many news sites and it all happened within the same day.

**Comment by reek** [comment]
I'll take care of it

**Comment by phone8588** [comment]
Thanks for the fix - worked fine till yesterday. New twist this morning - on some web pages - the anti-adblock page now appears only when one tries to scroll through the page. Please see example page - http://timesofindia.indiatimes.com/india/SCs-Arunachal-verdict-is-third-legal-setback-for-Modi-government/articleshow/53195522.cms

**Comment by reek** [comment]
@phone8588 
https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672
