### ISSUE TITLE
A nasty site forces me to disable my Adgurad ad-blocker to use that site. 

### ISSUE THREAD

**Issue by kuttan85** [reek/anti-adblock-killer#1675]
The URL below:
http://www.speakingtree.in/discussions/trending 

Wont allow to browse the site unless I disable the AdGuard.

I enabled both the Anti-Adblock Killer | Reek and  Adblock Warning Removal List resulted in failure.

Note that http://www.speakingtree.in itself is accessible with adblocker enabled but the site wont allows to access http://www.speakingtree.in/discussions/trending page until adblocker disabled for that page.

The Ad-blocker remove prompt page is added
![crap](https://cloud.githubusercontent.com/assets/20246337/16528791/9ba0e520-3fdc-11e6-8f6a-b856d8d8e937.PNG)

My AdGuard ad-blocker settings page added:
![spp](https://cloud.githubusercontent.com/assets/20246337/16528876/1ab731f2-3fdd-11e6-8b82-d6b97f42618a.PNG)

Hoping for a fix at the earliest
Thanking you in advance

**Comment by mapx-** [comment]
add
||speakingtree.in/detector.cms
or
@@||speakingtree.in^$generichide

**Comment by kuttan85** [comment]
Thank you so much for the help.....

**Comment by reek** [comment]
fixed by EasyList
