### ISSUE TITLE
indiatimes.com

### ISSUE THREAD

**Issue by amogh79** [reek/anti-adblock-killer#1676]
http://timesofindia.indiatimes.com/
http://imgur.com/7dsdfUd
Google chrome
Greasemonkey
Adblock Plus
EasyList + AakList

Go to http://timesofindia.indiatimes.com/ and click any link of that page, if adblock is enabled you are automatically directed to http://timesofindia.indiatimes.com/blocked.cms

Please fix this.

**Comment by SMed79** [comment]
I think already fixed by easylist https://forums.lanik.us/viewtopic.php?p=97537#p97537

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
