### ISSUE TITLE
up2stream.com ad changed

### ISSUE THREAD

**Issue by ken-hk** [reek/anti-adblock-killer#1678]
The ad is now a popunder, please update the rule:
`@@/BTVQRA6OS11SO6ARQVTB/pop.php$script,domain=up2stream.com`
to:
`@@/BTVQRA6OS11SO6ARQVTB/popunder.php$script,domain=up2stream.com`
Tested today (2016-07-02)
Thank you!

Ken

**Comment by reek** [comment]
Ok, I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ken-hk** [comment]
Tested today with latest updates, successfully played up2stream videos.
Thank you!

Ken
