### ISSUE TITLE
narcity.com

### ISSUE THREAD

**Issue by mosswalker** [reek/anti-adblock-killer#1679]
Someone said to post sites that reek does not work on so work arounds happen. I dont know if this is true but ill post this one anyway. narcity.com

**Comment by maynak00** [comment]
**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**
**try with:**
`@@||narcity.com/*/ads.advert.js$script`

anti-adblock source:
http://cdn.narcity.com/toronto/wp-content/themes/narcity-theme/legal/ads.advert.js
ADBLOCK_NOT_PRESENT = true;

**Comment by reek** [comment]
@maynak00 
thanks

@mosswalker 
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
