### ISSUE TITLE
folha.uol.com.br

### ISSUE THREAD

**Issue by tharsim** [reek/anti-adblock-killer#1680]
http://www1.folha.uol.com.br/o-melhor-de-sao-paulo/restaurantes-bares-e-cozinha/2016/06/1784612-saiba-como-escolher-o-corte-ideal-de-carne-para-a-sua-receita.shtml
http://imgur.com/m2myL4W
Google Chrome
Tampermonkey
Adblock Plus
AakList + EasyList + Malware Domains + EasyPrivacy

**Comment by maynak00** [comment]
**try with:**
`@@||folha.uol.com.br/*/publicidade.ads.js$script`
andti-adblock: http://static.folha.uol.com.br/paywall/js/1/publicidade.ads.js

**Comment by matheussampaio** [comment]
@maynak00 That works for me.

**Comment by reek** [comment]
@tharsim 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
