### ISSUE TITLE
sports.ndtv.com

### ISSUE THREAD

**Issue by shivasundar** [reek/anti-adblock-killer#1683]

**Comment by mapx-** [comment]
already fixed
https://forums.lanik.us/viewtopic.php?p=97538#p97538

**Comment by madeforonlyyou** [comment]
Still shows adblock warning

**Comment by shivasundar** [comment]
Just checked this - shows warning. Hope there is a way to do all domains of the primary website. viz. *.ndtv.com.

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/1660

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ssrb19** [comment]
@reek @mapx- Whatever you said solves all pages on ndtv.com except sports.ndtv.com. It never opens a link and goes back to the homepage.

**Comment by smed79** [comment]
@ssrb19 Did you try https://forums.lanik.us/viewtopic.php?p=110948#p110948

**Comment by ssrb19** [comment]
@SMed79 I did try, but to no avail

**Comment by smed79** [comment]
Example page? Firefox or chrome? Screenshot?

PS: _Be sure using only **one** adblocker._

**Comment by ssrb19** [comment]
I do use only one ad blocker - AdBlock on Chrome. This redirects to sports.ndtv.com after a couple of seconds.

https://sports.ndtv.com/cricket/ms-dhoni-surprises-jammu-and-kashmir-cricketers-with-dressing-room-visit-1666771?pfrom=home-cricket
