### ISSUE TITLE
happytrips.com

### ISSUE THREAD

**Issue by nikhilashish** [reek/anti-adblock-killer#1684]
http://www.happytrips.com/goa/travel-guide/things-to-do-in-goa-when-youre-travelling-with-kids/gs40902319.cms

is being redirected to

http://www.happytrips.com/blocked.cms

**Comment by maynak00** [comment]
**try with:**(temporary solution)
`happytrips.com#@#.text_ads`
`happytrips.com#@#.text_ad`
`happytrips.com#@#.textAd`
`happytrips.com#@#.text-ads`
`happytrips.com#@#.text-ad-links`
`happytrips.com#@#.text-ad`
`happytrips.com#@#.pub_728x90`
`happytrips.com#@#.pub_300x250m`
`happytrips.com#@#.pub_300x250`
`happytrips.com#@#.ad_v2`
`happytrips.com#@#.ad`
`happytrips.com#@##backgroundPopup`

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
