### ISSUE TITLE
lasprovincias.es

### ISSUE THREAD

**Issue by NnIiTtoO** [reek/anti-adblock-killer#1685]
1. URL - [lasprovincias.es](http://www.lasprovincias.es/comunitat/201607/03/gilet-pueblo-20160703000120-v.html)
2. Screnshot - [Screenshot](http://s2.subirimagenes.com/imagen/previo/thump_9616187captura.png)
3. Browser - Chrome
4. ScriptManager - Tampermonkey
5. Adblocker- uBlock Origin
6. Filters:
   uBlock Filters
   Adblock Warning Removal List
   Anti-Adblock Killer Reek
   EasyList
   Peter Lowe's Ad server list
   Easy Privacy
   Malware domain list
   Malware domains
   Easylist Spanish

Thanks for your job!

**Comment by maynak00** [comment]
**try with:**
`@@||lasprovincias.es/*/adfrm.js$script`
var Vocento = Vocento || {};
Vocento.checkAdBlock =  1;

**Comment by NnIiTtoO** [comment]
working. thanks !!!

**Comment by reek** [comment]
@NnIiTtoO 
Ok, I'll kill it, thanks

@maynak00 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
