### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by jeetensheth** [reek/anti-adblock-killer#1687]
http://www.ndtv.com/welcome
http://imgur.com/sbJFzFQ
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by maynak00** [comment]
duplicate: https://github.com/reek/anti-adblock-killer/issues/1660

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rahilpathan** [comment]
http://sports.ndtv.com/football/news/260695-euro-2016-final-eder-s-goal-for-portugal-beats-france-to-win
try opening this link.. I am still getting an error to disable ad block

**Comment by rahilpathan** [comment]
I solved it myself just disabled tampermonkey and it doesn't bother now !

**Comment by rahilpathan** [comment]
Hey I found one more website where ad blocker gets detected.. Reek pls fix
http://timesofindia.indiatimes.com/sports/boxing/Vijender-Singh-beats-Kerry-Hope-to-clinch-WBO-Asia-Pacific-title/articleshow/53244952.cms

**Comment by reek** [comment]
@rahilpathan 
See: https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
