### ISSUE TITLE
eenadu.net

### ISSUE THREAD

**Issue by prathapdodla** [reek/anti-adblock-killer#1688]
This popula region news website asking to disable Ads and here is the link of the request page.

http://www.eenadu.net/welcome.html

**Comment by maynak00** [comment]
**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**
**try with:**
`@@||eenadu.net/ads.js$script`
 var RunAds = true;

**Comment by Karbi123** [comment]
How and where to use @@||eenadu.net/ads.js$script
var RunAds = true;

**Comment by reek** [comment]
@maynak00 
thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
