### ISSUE TITLE
aternos.org

### ISSUE THREAD

**Issue by Bluscream** [reek/anti-adblock-killer#1689]
https://aternos.org/server/
![Screenshot](http://image.prntscr.com/image/870e87015f4340de9d1929205a7171f0.png)
Browser: Microsoft Edge
AdBlocker: AdGuard 6.1.236.1160 BETA
Filter Lists:
![Filterlists](https://i.gyazo.com/39dff410000715075266c5f51e212a3d.gif)
Custom Filters:
![Custom Filters](http://image.prntscr.com/image/0b25d0849c0f48feae5d7b99a7260744.png)

**Comment by maynak00** [comment]
**try with:**

**Comment by Bluscream** [comment]
Will try that, thanks :)

**Comment by Bluscream** [comment]
Works like a charm, thanks :)
@reek Requesting to add these.

**Comment by Bluscream** [comment]
@maynak00 i've just seen that one message remains:
![image](https://cloud.githubusercontent.com/assets/3318223/16566912/1bc933cc-4219-11e6-8148-8820decb4555.png)

**Comment by reek** [comment]
Ok, I'll add it, thanks

**Comment by maynak00** [comment]
@Bluscream sorry, not tested with account. now created temporary account for test.
updated comment: https://github.com/reek/anti-adblock-killer/issues/1689#issuecomment-230243456

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
