### ISSUE TITLE
generation-nt.com

### ISSUE THREAD

**Issue by Quezako** [reek/anti-adblock-killer#1690]
Hello,
I can't manage to block adblock-killer here:

http://www.generation-nt.com/
http://imgur.com/ohjULvt
Mozilla Firefox
Greasemonkey
tested with:
Adblock Plus EasyList OR uBlock Origin

**Comment by maynak00** [comment]
No antiadblock detected. Report Here(EasyList Forum): https://forums.lanik.us/viewforum.php?f=62

**Comment by Quezako** [comment]
My bad.
I've seen a div called "adblock-unloader-937258" and I was thinking it was an anti-adlock script or something. But it is generated by AdBlock itself.

**Comment by maynak00** [comment]
maybe antiadblock but no message:adblocker detected,disable to continue etc.also I see similar ads without adblocker
data:image/gif;base64,

**Comment by SMed79** [comment]
@maynak00 already reported [?f=91&t=31394](https://forums.lanik.us/viewtopic.php?f=91&t=31394) but this will be fixed by AaK script (**phoenix_goyavelab**).
- https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L4582
- https://github.com/gorhill/uBlock/issues/1340

**Comment by SMed79** [comment]
@maynak00 already reported [?f=91&t=31394](https://forums.lanik.us/viewtopic.php?f=91&t=31394) but this will be fixed by AaK script (**phoenix_goyavelab**).
```
https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L4582
https://github.com/gorhill/uBlock/issues/1340
```

**Comment by gorhill** [comment]
> Adblock Plus EasyList OR uBlock Origin

It's fixed in uBlock Origin, just force an update of _uBlock filters_.

**Comment by Quezako** [comment]
Thanks a lot! :)
