### ISSUE TITLE
speisa.com

### ISSUE THREAD

**Issue by dh33r4j** [reek/anti-adblock-killer#1692]
They are using blockadblock script.
http://speisa.com/modules/articles/index.php/item.2929/norway-starts-deporting-afghans.html

Browser: Firefox 46.0
Adblocker: uBlock Origin
Filterlists: EasyList + uBlock List + EasyPrivacy + Peter Lowe’s Ad server list‎ + Malware Domain List‎ + AakList

**Comment by reek** [comment]
Already killed by AakScript, see instruction
