### ISSUE TITLE
http://derstandard.at/

### ISSUE THREAD

**Issue by widarr** [reek/anti-adblock-killer#1693]
Screenshots: http://imgur.com/a/BHs9x
(Some Images and the comment rating function are blocked for adblock users)
Browser: Firefox 46.0
Script manager: Greasemonkey
Adblocker: uBlock Origin
Filterlists: EasyList + uBlock List + EasyPrivacy + Peter Lowe’s Ad server list‎ + Malware Domain List‎  + AakList

**Comment by reek** [comment]
Already killed by AakScript
