### ISSUE TITLE
www.somersetcountygazette.co.uk

### ISSUE THREAD

**Issue by stevep4** [reek/anti-adblock-killer#1694]
http://www.somersetcountygazette.co.uk/
http://imgur.com/QYVTD97
Google Chrome (51.0.2704.106 m)
Tampermonkey (4.0.69)
AdBlock (3.0.7)
AakList & EasyList

**Comment by jonasthambert** [comment]
Try custom filter:
somersetcountygazette.co.uk##div[class="ad-blocker-warning"]

**Comment by stevep4** [comment]
Thanks Jonas, that seems to work a treat. :-)

**Comment by reek** [comment]
@jonasthambert 
thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
