### ISSUE TITLE
xmovies8.org

### ISSUE THREAD

**Issue by Botuts** [reek/anti-adblock-killer#1695]
[The problem is that the video does not play, it's just a black screen. I believe the anti ad-blocker killer is blocking the video along with the anti-ad blocker.]

Example URL: https://xmovies8.org/watch?v=Zootopia_2016#video=t_Lqpod88Z9lZ56ikxmbfum624R6NRrhKuDk8mlinBc
Screenshot: http://imgur.com/QqaumjT
Browser: Google Chrome Version 52.0.2743.60 beta-m (64-bit)
Tampermonkey
uBlock Origin
Filters:

uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Unbreak‎
Anti-Adblock Killer | Reek‎
EasyList
Peter Lowe’s Ad server list‎
EasyPrivacy‎
Malware Domain List‎
Malware domains
AakList (Anti-Adblock Killer)

**Comment by gorhill** [comment]
Solution: `@@||xmovies8.org/js/showads.js$xmlhttprequest`.

**Comment by reek** [comment]
@gorhill 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
