### ISSUE TITLE
jagran.com / bhaskar.com

### ISSUE THREAD

**Issue by beingtech** [reek/anti-adblock-killer#1697]
Example 
1-  Open jagran.com and click on any news article.
      http://www.jagran.com/news/national-cabinet-reshuffle-today-may-see-inductions-from-up-and- other-states-14262973.html?src=p1

2- Open http://www.bhaskar.com/ and open any article
http://www.bhaskar.com/news-ht/UT-DEL-HMU-NEW-modi-cabinet-reshuffle-news-hindi-5365527-PHO.html

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
