### ISSUE TITLE
businesstoday.in

### ISSUE THREAD

**Issue by kamal-github** [reek/anti-adblock-killer#1698]
not working for http://www.businesstoday.in/

**Comment by maynak00** [comment]
**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**
**try with:**
`businesstoday.in###adbocker_alt`

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by kamal-github** [comment]
http://timesofindia.indiatimes.com/tech/tech-news/NaMo-Twitter-gives-orange-tick-badges-to-active-users/articleshow/53168010.cms 

Not working for this too. :(

**Comment by maynak00** [comment]
@kamal-github https://github.com/reek/anti-adblock-killer/issues/1653

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
