### ISSUE TITLE
dota-trade.com

### ISSUE THREAD

**Issue by leodelacruz** [reek/anti-adblock-killer#170]
http://dota-trade.com/

http://image-tpb.com/upload/big/2015/02/03/54d02a70c6369.png

![untitled](https://cloud.githubusercontent.com/assets/8390315/6013086/fb769238-ab36-11e4-816c-0710d68effb0.png)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
