### ISSUE TITLE
hindustantimes.com

### ISSUE THREAD

**Issue by aks0854** [reek/anti-adblock-killer#1700]
http://www.hindustantimes.com/india-news/pm-modi-expands-council-of-ministers-javadekar-elevated/story-yuAynMzlS2DqBNDp2H0SXP.html
http://imgur.com/q24ivQI
firefox
Greasemonkey
Ublock origin
easylist +aaklist by reek

**Comment by SMed79** [comment]
Use search, geez.
https://github.com/reek/anti-adblock-killer/issues/1672#issuecomment-230386581

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Ntweat** [comment]
It is back on Hindustan Times

<img width="1359" alt="screen shot 2016-07-11 at 3 02 42 am" src="https://cloud.githubusercontent.com/assets/1205924/16722371/168b327a-4714-11e6-9782-6a0f9ac2bda7.png">

**Comment by rambocop** [comment]
hindustantimes was again blocked this morning ,other sites work fine.hey reek plz look into this issue

**Comment by mapx-** [comment]
just add this filter
@@||hindustantimes.com^$script

**Comment by mapx-** [comment]
check also (when you need a filter, a fix) the easylist forum
http://forums.lanik.us/

**Comment by rambocop** [comment]
thank you but how do you add this filter ?can you explain more ?

**Comment by mapx-** [comment]
for ABP:
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

for ubo: dashboard, then my filters

**Comment by rambocop** [comment]
thanks a lot worked

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
