### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by eternalthinker** [reek/anti-adblock-killer#1703]
http://timesofindia.indiatimes.com/city/chennai/FIR-against-Chennai-student-for-throwing-dog-from-terrace/articleshow/53061875.cms
http://imgur.com/KwHRh1e
Google Chrome
TamperMonkey
Adblock Plus
EasyList + AakList

(Same result with Mozilla Firefox)

**Comment by shivasundar** [comment]
This was okay on Saturday. They may have found a way :-(

**Comment by surpeet** [comment]
Do this: https://github.com/reek/anti-adblock-killer/issues/1673
It works.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
