### ISSUE TITLE
hulkusc.com

### ISSUE THREAD

**Issue by dc250g** [reek/anti-adblock-killer#1704]
http://www.hulkusc.com/watch-msnbc-live-streaming/
http://imgur.com/2n0OqdL
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by mapx-** [comment]
`@@|https://$xmlhttprequest,domain=hulkusc.com
`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
