### ISSUE TITLE
maharashtratimes.indiatimes.com

### ISSUE THREAD

**Issue by amogh79** [reek/anti-adblock-killer#1705]
http://maharashtratimes.indiatimes.com/maharashtra/mumbai-news/strainth-to-msrdc/articleshow/53067821.cms (many links on http://maharashtratimes.indiatimes.com contain anti adblock and another site from same guys http://timesofindia.indiatimes.com are blocking)

http://imgur.com/d6cq9zi

Google chrome

Greasemonkey

Adblock plus

Adblock warning removal list, Easylist, Aak List

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by hsagar** [comment]
Only http://maharashtratimes.indiatimes.com/ main page does not have anti adblock. All the links to the stories have anti adblock and it is activating after 3-4 seconds. 
e.g. http://maharashtratimes.indiatimes.com/business/business-news/emplyee-of-small-company-to-get-pf/articleshow/53494468.cms This story link does have a anti adblock. 

It looks like this site was missed in this commit.
https://github.com/reek/anti-adblock-killer/commit/7a3aa14b08522f06a78ae37a1ea239340cc95af9

**Comment by amogh79** [comment]
Looks like indiatimes is back with their ugly adblocker warning. Any gurus out there can you please help?

**Comment by mapx-** [comment]
try these filters

https://github.com/reek/anti-adblock-killer/issues/1879#issuecomment-237923375

**Comment by reek** [comment]
done
