### ISSUE TITLE
ndtv.com / indiatimes.com

### ISSUE THREAD

**Issue by Jaden-J** [reek/anti-adblock-killer#1706]
These sites block Adblock Plus
http://www.ndtv.com
http://timesofindia.indiatimes.com

When one clicks on any of the news story links they are redirected to anti adblock page.
![ndtv- please turn off your ad blocker in order to continue 2016-07-06 13-26-13](https://cloud.githubusercontent.com/assets/6412804/16606716/87035f54-437d-11e6-9820-44efbd33852f.png)
![the times of india- latest news india world business news cricket sports bollywood 2016-07-06 13-27-06](https://cloud.githubusercontent.com/assets/6412804/16606717/870b64d8-437d-11e6-8b5d-b70e2a38c00e.png)

**Comment by SMed79** [comment]
Use search before posting ... If your topic already exists then feel free to post in the old topic.

duplicate: 
- https://github.com/reek/anti-adblock-killer/issues/1659 https://github.com/reek/anti-adblock-killer/issues/1660 https://github.com/reek/anti-adblock-killer/issues/1667 https://github.com/reek/anti-adblock-killer/issues/1683 https://github.com/reek/anti-adblock-killer/issues/1687 https://github.com/reek/anti-adblock-killer/issues/1699
- https://github.com/reek/anti-adblock-killer/issues/1672 https://github.com/reek/anti-adblock-killer/issues/1657 https://github.com/reek/anti-adblock-killer/issues/1701

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Jaden-J** [comment]
Thank you for updating for times of india and india times. 
NDTV still blocks the adblock.

**Comment by reek** [comment]
@Jaden-J
see https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672

**Comment by b-sridhar** [comment]
@reek, there seems to be a problem with ndtv again, unable to view any of the articles on the webpage. Tried blocking an inline script: `www.ndtv.com##script:contains(getNoTopLatestNews)`, but it did not help.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
