### ISSUE TITLE
happy-hack.ru

### ISSUE THREAD

**Issue by mikhaXD** [reek/anti-adblock-killer#1707]
Opera
Latest ABP + updated scripts list.

alwasy have adblock detected =(

**Comment by jonasthambert** [comment]
Try custom filter:
happy-hack.ru##div[style*="100000"]
happy-hack.ru##div[style*="1px"]

Can probably be optimized. Works using Chrome + uBlock Origin.

**Comment by maynak00** [comment]
**try with:**
`@@||admitad.com/*/advert.js$script,domain=happy-hack.ru`
`@@||7-link.ru/advert.js$script,domain=happy-hack.ru`
`||happy-hack.ru/*/poo.js$script`
`||skin-maker.ru$domain=happy-hack.ru`
`happy-hack.ru###admitad-cookie-check-popup`
`happy-hack.ru###admitad-checker-popup-cont`
`happy-hack.ru##.admitad-checker-popup-bg`

**Comment by mikhaXD** [comment]
Thanks a lot! Works!

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
