### ISSUE TITLE
skins4virtual.com

### ISSUE THREAD

**Issue by Bluscream** [reek/anti-adblock-killer#1708]
http://skins4virtual.com/2016/01/18/skin-virtualdj-8-single-deck/
![Screenshot](http://image.prntscr.com/image/1052e950153e42a5bc41b9bc328991d5.png)
**Browser:** Microsoft Edge
**AdBlocker:** AdGuard 6.1.236.1160 BETA
**Filter Lists:**
![Filterlists](https://i.gyazo.com/39dff410000715075266c5f51e212a3d.gif)

**Comment by maynak00** [comment]
**try with:**
`skins4virtual.com#@#.afs_ads`
**or**
`skins4virtual.com##.ui-front.ui-widget-overlay`
`skins4virtual.com##.ui-resizable.ui-front.ui-corner-all.ui-widget-content.ui-widget.ui-dialog`

**Comment by reek** [comment]
Already killed by AakList

**Comment by Bluscream** [comment]
Not for me.
![Uploading image.png…]()

**Comment by reek** [comment]
@Bluscream 
Try add @maynak00 rules

**Comment by Bluscream** [comment]
Why don't you implement it by default?

**Comment by reek** [comment]
I'll add the rules of @maynak00, but it should work without

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
