### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by iDanny1212** [reek/anti-adblock-killer#1710]
https://www.vvvvid.it/adblock.html
http://imgur.com/6dF1jPo
Google Chrome
Tampermonkey
Adblock Plus
[Adblock Warning Removal List
EasyList Italy+EasyList
AakList (Anti-Adblock Killer)
Adware filters
Fanboy's Annoyance List
Fanboy's Social Blocking List
I don't care about cookies
Malware Domains
Prebake - Filter Obtrusive Cookie Notices
RuAdList+EasyList]

**Comment by reek** [comment]
Sorry, no solution
