### ISSUE TITLE
divyabhaskar.co.in

### ISSUE THREAD

**Issue by fenil147** [reek/anti-adblock-killer#1711]
http://bollywood.divyabhaskar.co.in/news-htn/ENT-BNE-salman-khans-movie-sultan-leaked-online-producers-denied-5366500-PHO.html
http://imgur.com/iLvFIqh
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**
`@@||bhaskar.com/*/ads.js$script`

**Comment by Ntweat** [comment]
@@||bhaskar.com/*/ads.js$script  

Works.. Tested

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
