### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by mirek11** [reek/anti-adblock-killer#1716]
Google Chrome
Tampermonkey
uBlock origin
EasyList + AakList
![15min lt](https://cloud.githubusercontent.com/assets/20332562/16643691/ae73ebec-441f-11e6-8e37-cf4ac56d1691.JPG)

**Comment by juozapyne** [comment]
Fixed in #1513 but it's back again :-(

**Comment by reek** [comment]
I'll fix it @juozapyne

**Comment by Ntweat** [comment]
Add this

`||s2.15cdn.lt/static/js/1467887798/1689225443.js$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
