### ISSUE TITLE
indiatoday.intoday.in

### ISSUE THREAD

**Issue by gotitbro** [reek/anti-adblock-killer#1720]
## ### Anti AdBlock Killer Reek is not working on http://indiatoday.intoday.in/.

**Source Code:** https://gist.github.com/anonymous/dec87c8bc1a52e727ef34d58f15da46d

**Original URI:** http://indiatoday.intoday.in/story/easy-to-grow-easy-to-sell-broom-growers-in-meghalaya-reap-the-benefits/1/243486.html

**Extensions:** AdBlock, IDM Integration Module, Tampermonkey, Unlimited Free VPN - Hola

**Userscripts:** Anti-Adblock Killer

**Blocked Resources:** http://imgur.com/BRFg93w

**Comment by H0A1** [comment]
IN umatrix turn off media2.intoday.in it will work perfectly ,also turn off adblock when u r using umatrix for adblocking

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Ntweat** [comment]
stop gap to stop ads

`||media2.intoday.in^*$script`

Will stop ads on Business today and India today

**Comment by gotitbro** [comment]
@Ntweat Thanks for that I was just wondering why it was showing the warning after the whole page had completely loaded.

**Comment by ssrb19** [comment]
They have a new anti-ad block detection script now.

**Comment by mapx-** [comment]
add in your adblocker and test it
@@||intoday.in^$elemhide

**Comment by ghajini** [comment]
not working @mapx- 
![screenshot 20](https://cloud.githubusercontent.com/assets/20338483/17186112/7f2fcf76-5451-11e6-8046-9feb9457163b.png)

http://aajtak.intoday.in/story/chinese-transgression-in-chamoli-uttarakhand-itbp-sent-report-to-mha-1-880048.html

**Comment by mapx-** [comment]
it's working fine for me in ABP and ubo, what filter lists are you using ?
(disable all other blocking extension)

**Comment by mapx-** [comment]
add also (probably you are using easyprivacy too)
@@||vizury.com^$domain=intoday.in

**Comment by ghajini** [comment]
using ublock origin

**Comment by ghajini** [comment]
this banner not blocked
<a href="http://axp.zedo.com/asw/ads4/c?a=2557985;x=2441;g=78;c=821002195,821002195;i=2;n=821;s=5;1=8;2=1;tg=1469643822;vr=4;m=4095;w=16;os=21;ct=9;u=xtThOy8BS-WObt6RpEOcSQ**~072516;z=0.4713569044464313;ainfo=;csv=1;dct=2067;dmf=;dvm=;dsr=;djs=2063;dhs=2065;q=;ctg=zSample%3A53;osn=Windows;osv=10.0;brn=Chrome;brv=50;pu=http%3A%2F%2Faajtak.intoday.in%2Fstory%2Flokpal-and-lokayukta-amendment-bill-2016-gets-passed-by-lok-sabha-1-880065.html;k=http://www.thelallantop.com/?utm_source=ReadNewsBanner&amp;utm_medium=Websitebanner&amp;utm_campaign=Lallantop" target="_blank" onmouseover="window.status=&quot; Ad powered by ZEDO&quot;; return true;" onmouseout="window.status=&quot;&quot;; return true;"><img width="300" height="250" src="http://d13.zedo.com/OzoDB/f/1/2557985/V4/300x250B.jpg" border="0" alt="Click Here!" title="Click Here!"></a>

**Comment by ghajini** [comment]
sorry for trouble but these news sites frustrating

**Comment by prasannjeet** [comment]
@ghajini check this link: https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672 this will fix it for you. Fixed for me.

**Comment by SMed79** [comment]
`@@||media2.intoday.in/indiatoday/resources/js/ads.js$script`

**Comment by reek** [comment]
done
