### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by glennsamuel32** [reek/anti-adblock-killer#1722]
http://timesofindia.indiatimes.com/india/Hizbul-Mujahideen-terrorist-Burhan-Wani-killed-in-JK-encounter/articleshow/53121685.cms

http://timesofindia.indiatimes.com/sports/tennis/wimbledon-2016/Raonic-upsets-Federer-to-reach-Wimbledon-final/articleshow/53120106.cms

http://timesofindia.indiatimes.com/world/us/Dallas-attack-Snipers-kill-5-police-officers-Obama-calls-it-despicable-attack/articleshow/53116596.cms

http://timesofindia.indiatimes.com/india/Indian-1st-woman-to-get-bravery-at-sea-award/articleshow/53123842.cms
1.  http://i68.tinypic.com/foxzl.jpg
2.  Chrome
3.  Greasemonkey
4.  Adblock Plus
5.  EasyList + AakList
6.  Ghostery

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
