### ISSUE TITLE
player.pl - if site cannot connect with ads servers, then blocking video stream

### ISSUE THREAD

**Issue by FadeMind** [reek/anti-adblock-killer#1724]
Polish site with video stream content require connnect with domains:
```
tvn.hit.gemius.pl
tvn.adocean.pl
tvn2.adocean.pl
```
When site cannot do this, then show this:
https://imgur.com/VBCUmPF

Only disabling uBlock Origin do job but ads are displayed:
```
http://player.pl/seriale-online/kryminalni-odcinki,6/odcinek-1,okularnik,S01E01,101.html?atpl#play
```

Google Chrome
uBlock Origin

**Comment by reek** [comment]
Already killed by AakScript

**Comment by xxcriticxx** [comment]
@FadeMind zapraszam do projektu https://github.com/MajkiIT/polish-ads-filter/issues
