### ISSUE TITLE
timesofindia.indiatimes.com *

### ISSUE THREAD

**Issue by Vacon1** [reek/anti-adblock-killer#1725]
Here what is happening is when we are opening this website " http://timesofindia.indiatimes.com " the website opens normally with zero scripts. But once we click on a headline and we go into detail of the story/article then the script successfully is bypassing the "Anti-Ad-Block killer" script somehow and saying please disable your "Ad Block Plus" plugin. I tried this on "Safari" browser as well as "Opera" browser.They are not working properly.Chrome looks like its working fine for now.

1) Opera Browser
2) Safari browser 
3) Ad Block Plus

Please try to access the script which the agency is using and try to block the hoard of scripts.I doubt that they are already using multiple scripts. Anyway thanks for making a great and useful script !!

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Vacon1** [comment]
Why is no one fixing this ? I still have this problem !! Oh man ? please try to do it fast please !

**Comment by amogh79** [comment]
Me to still have the problem. Looks like the assholes at times of india are coming up with new ways to go past anti-adblock killer. Now they have put a div and set the opacity of the div which is getting set by some script. Can't delete the style element of the content div

**Comment by reek** [comment]
they use different methods to detect adblock, but I'm working on it

**Comment by saptarshidebnath** [comment]
@reek Thanks. in advance. I am monitoring this thread !!

**Comment by Ntweat** [comment]
@reek you rock man ..

**Comment by reek** [comment]
@Ntweat thanks :smile:

**Comment by Ntweat** [comment]
@reek 

I think timesofindia is using this function to block. I don't know how it is working

`function blockedit(){
    if(!window.$ || !window.$.fn){
        setTimeout(blockedit,1000);
        return;
    }
    var customize = function(browser){
        var t = $('li[data-browser="'+ browser +'"]');
        t.parent().prepend(t);
        $('[data-val="browsername"]').html(' - ' + browser).show();
    };
    
    var expandAccordion = function(browser){
        var btn = $('[data-browser="'+ browser +'"]').find('.accordion');
        btn.toggleClass('exp').siblings('.panel').slideToggle(600);
        customize(browser);
    };
    
    var detectBrowser = function() { 
       if(navigator.userAgent.indexOf("Chrome") != -1 ){
            expandAccordion('Chrome');
        }
        else if(navigator.userAgent.indexOf("Safari") != -1){
            expandAccordion('Safari');
        }
        else if(navigator.userAgent.indexOf("Firefox") != -1 ){
            expandAccordion('Firefox');
        }
        else if((navigator.userAgent.indexOf("MSIE") != -1 ) || (navigator.userAgent.indexOf("Trident") != -1 ) ){
          expandAccordion('IE'); 
        }  
        else {
           console.log('Unknown browser');
        }
    };
    
    var bindEvents = function(){
        $('.browsers').on('click', '.accordion', function(){ 
            $(this).toggleClass('exp').siblings('.panel').slideToggle(600);
        });
        
        $('[data-action="refresh"]').on('click', function(){
            window.location.reload();
        });
    };
    
        bindEvents();
        detectBrowser();
    $( document ).ready(function() {
        $('.cvs_wdt a').attr('href','/');
        $("ul.articles").hide();
    });
    $("ul.articles").hide();
}())`

**Comment by amogh79** [comment]
@reek any break through on getting around these assholes at times of india?

**Comment by Ntweat** [comment]
Temporary stop gap fix. Till @reek figures it out


`@@||timesofindia.indiatimes.com^*$script`


Warning: This will stop all scripts from running on the site (which includes the anti-ad block script). So any other useful script will also be blocked.

**Comment by Vacon1** [comment]
How to use this temporary fix ? Can you help us in detail

**Comment by Ntweat** [comment]
@Vacon1  add the line to your filters

**Comment by tabish4448** [comment]
I have checked it on firefox with tampermonkey beta and it didn't stopped any other script all are working fine for different websites and
it is working for articles under Sports section:
http://timesofindia.indiatimes.com/sports/india-in-west-indies-2016/top-stories/Virat-Kohli-has-created-a-positive-environment-in-the-side-Amit-Mishra/articleshow/53159010.cms

But not for articles under Top Stories section
http://timesofindia.indiatimes.com/top-stories/India-v-Pakistan-Crickets-biggest-rivalry/articleshow/49450278.cms?utm_source=TOInewHP_TILwidget&utm_medium=ABtest&utm_campaign=TOInewHP

**Comment by Ntweat** [comment]
Working..!! 
Remove everything after the  **?**

It is a stop gap solution so you will have to be creative :)

<img width="1434" alt="screen shot 2016-07-11 at 2 22 23 pm" src="https://cloud.githubusercontent.com/assets/1205924/16741835/0fc1c1de-4773-11e6-900d-89c0f4f4cee0.png">

**Comment by tabish4448** [comment]
:) Yeah working after removing tail of url.

**Comment by tabish4448** [comment]
Check it out: http://timesofindia.indiatimes.com/sports/football/top-stories/Portugal-win-Euro-2016-thanks-to-Eders-extra-time-goal/articleshow/53145547.cms

![007](https://cloud.githubusercontent.com/assets/20391995/16743097/44f29120-47c4-11e6-8666-ceb12dabf3c7.png)

**Comment by Ntweat** [comment]
Ha ha I have a solution but it is not clean. It will block all scripts. The videos won't play
use at your own risk

`||$script,domain=indiatimes.com`

**Comment by Ntweat** [comment]
For this site they have hidden it pretty well

**Comment by Ntweat** [comment]
I know how to fix it.. Problem is that even if you block the divs.. It still changes the opacity of the article to less. 
<img width="452" alt="screen shot 2016-07-11 at 5 07 05 pm" src="https://cloud.githubusercontent.com/assets/1205924/16746781/fa3b3dba-4789-11e6-97fa-af41a1d73f49.png">

If the 0.04 can become 1 it will be solved

**Comment by reek** [comment]
versions below, should patch all Indian sites that have been reported to me, in case of problems or new anti-adblock, let me know.

AakScript
https://gist.github.com/reek/dc234ea9687056bd99fe/raw/eafba5a847380ec940681aaf179250d49fcb0790/aakdev.user.js

AakList Temporary (add this list manualy)
https://gist.github.com/reek/292ed06433b4cfc07bc94cb4fec4adbe/raw/797ba57783df9e73d1b408c716198ffe1343eb33/aaktmp.list.txt

**Comment by Ntweat** [comment]
Hey @reek 
It doesnt work 
url tried: http://timesofindia.indiatimes.com/india/Zakir-Naiks-speeches-contradictory-wont-be-easy-to-charge-him-say-experts/articleshow/53163582.cms

I re-installed the script and I added the AAKAList 

<img width="1194" alt="screen shot 2016-07-11 at 7 25 39 pm" src="https://cloud.githubusercontent.com/assets/1205924/16750125/589e5e9c-479d-11e6-8426-60eead0c70e7.png">

<img width="1422" alt="screen shot 2016-07-11 at 7 26 59 pm" src="https://cloud.githubusercontent.com/assets/1205924/16750138/7b5b438c-479d-11e6-9907-1d9a04cfe138.png">

**Comment by reek** [comment]
@Ntweat 
Fixed, force update of AakList (Temporary)

**Comment by Ntweat** [comment]
Still the same @reek

**Comment by reek** [comment]
@Ntweat 
Install: https://gist.github.com/reek/dc234ea9687056bd99fe/raw/eafba5a847380ec940681aaf179250d49fcb0790/aakdev.user.js

**Comment by Ntweat** [comment]
@reek 
Done. Still no success. 
1. Deleted the script.
2. Installed it again. 
3. Refreshed the Temporary script a few times

**Comment by reek** [comment]
Tested on Chrome & Firefox and its ok

**Comment by reek** [comment]
@Ntweat 
https://gist.github.com/reek/dc234ea9687056bd99fe (click raw for install Script)
https://gist.github.com/reek/292ed06433b4cfc07bc94cb4fec4adbe (copy raw url add it to AB)

**Comment by Ntweat** [comment]
@reek 
Thanks 
That worked!!!!

**Comment by reek** [comment]
:smile: :smile: :smile:

**Comment by tabish4448** [comment]
Well Done @reek I have removed all manual filters for individual sites and it's working really well.
Thanks!

**Comment by amogh79** [comment]
@reek what do you mean by the following

https://gist.github.com/reek/292ed06433b4cfc07bc94cb4fec4adbe (copy raw url add it to AB)

please assist

**Comment by reek** [comment]
@amogh79 
https://github.com/reek/anti-adblock-killer/wiki/Add-or-update

**Comment by amogh79** [comment]
Thanks :)

**Comment by Vacon1** [comment]
@reek Well now Times of India website again blocking your new scripts man :( :( Look into a permanent "MASTER FIX" , anyway ur doing great 💯

**Comment by Ntweat** [comment]
@Vacon1 it is working for me. 
Give the link where it is blocking

**Comment by Vacon1** [comment]
@reek  Check this link once , is it working fine for you ? 
http://timesofindia.indiatimes.com/city/vijayawada/articlelist/47293740.cms

**Comment by Ntweat** [comment]
@Vacon1 
Yup all good no ads

**Comment by Vacon1** [comment]
Try once again @Ntweat i am unable to access that link at all :(

**Comment by Ntweat** [comment]
<img width="1432" alt="screen shot 2016-07-12 at 2 12 30 pm" src="https://cloud.githubusercontent.com/assets/1205924/16778192/da1fadd4-483a-11e6-9a31-263f80312187.png">

**Comment by Vacon1** [comment]
weird, everything works except this news for me. Ok i will skip that article :)

**Comment by reek** [comment]
@Vacon1 
both killed

**Comment by nitin-b** [comment]
Appreciate your work on this..

Unfortunately, it is not working on timesofindia.indiatimes.com:
Example pages where it is not working:
http://timesofindia.indiatimes.com/india/Rahul-Gandhi-targets-PM-Modi-over-SC-verdict-on-Arunachal/articleshow/53188782.cms
http://timesofindia.indiatimes.com/world/rest-of-world/Taiwan-sends-warship-to-South-China-Sea-after-ruling/articleshow/53189750.cms

It seems on any user action (such as scroll) the ad-blocker installed message pops up and disables the page from browsing.

**Comment by Ntweat** [comment]
@nitin-b 

I am trying to reproduce the block. I am not getting blocked. 
I scrolled up and down, waited 5 mins, clicked everywhere on page, pressed a few keys. It still did not block me. 

Tell what are you using
I tested on
Chrome
AdblockPlus + Tamper monkey

**Comment by phone8588** [comment]
![image](https://cloud.githubusercontent.com/assets/12768082/16820430/f1440494-491e-11e6-92e0-7f2ceb17a4a3.png)

I am using chrome and even after using the latest Aaklist version getting the screen above when trying to scroll through the web page. But when I added @@||indiatimes.com/*_js_ads/ads/*.cms$script  the webpage began opening but is slower than usual to scroll.

**Comment by Vacon1** [comment]
@reek eenadu.net , hindustantimes.com are yet again blocking us !! Have a look once. As soon as we click on news boom it says remove ad block @Ntweat

**Comment by tabish4448** [comment]
No @Vacon1 it's working perfectly.

![image](https://cloud.githubusercontent.com/assets/20391995/16828931/d525270e-49ad-11e6-87bd-ae4bd9aced7a.png)

![image](https://cloud.githubusercontent.com/assets/20391995/16828938/e6ffddde-49ad-11e6-8c81-438d2fd076dc.png)

**Comment by nitin-b** [comment]
@reek 
Thanks for responding. I am using Firefox.
I have setup Greasemonkey, and 'Anti adblock killer | Reek', all updated.

In addition to timesofindia.indiatimes.com, issue is also on other websites when opened from Firefox:
Another news website http://www.ndtv.com/ is also blocking the adblock plus.
Example page: http://www.ndtv.com/chennai-news/2-women-commit-suicide-at-iit-madras-campus-1431236

**Comment by tabish4448** [comment]
@nitin-b I don't like firefox because it's real slow but to check script of @reek I have checked it and it's working perfectly in firefox too. maybe you should use tampermonkey instead of greasemonkey.

![image](https://cloud.githubusercontent.com/assets/20391995/16830074/15c91a4c-49b6-11e6-910c-d921e34fd7ee.png)
![image](https://cloud.githubusercontent.com/assets/20391995/16830081/29392f18-49b6-11e6-8930-2235374e24b5.png)
![image](https://cloud.githubusercontent.com/assets/20391995/16830091/3d8b9546-49b6-11e6-8ef5-5d7f575b685d.png)

**Comment by sagrawal3** [comment]
@reek Please note that the TOI Web Page (including news article) opens fine, but once you start SCROLLING, it detects the AdBlocker and shows the Blocked Page. I am using Tampermonkey, Chrome and AdBlock.
I was trying to access the following URL: http://timesofindia.indiatimes.com/india/DGCA-warns-2-IndiGo-pilots-for-taking-selfies-in-cockpit/articleshow/53213555.cms


![issue](https://cloud.githubusercontent.com/assets/13911069/16849903/7acbfe78-49b1-11e6-8de5-392997376d22.jpg)

**Comment by tabish4448** [comment]
@sagrawal3 working here. have you applied the fixes that @reek posted above?

![0011](https://cloud.githubusercontent.com/assets/20391995/16853149/ab94e812-4a24-11e6-81bd-ec6c8e4a50d0.png)

**Comment by sagrawal3** [comment]
@reek @tabish4448 I can confirm its working now. However, I am installed ABP (earlier it was AdBlock), Chrome, Tampermonkey. Thanks a lot for your help!

**Comment by nitin-b** [comment]
Still having issues on Firefox, Tampermonkey, ABP. 

Earlier I tried Firefox, Greasemonkey, ABP.

Example link: http://timesofindia.indiatimes.com/india/Punes-gold-shirt-businessman-murdered/articleshow/53222716.cms

**Comment by anpr22** [comment]
link: http://www.hindustantimes.com/patna/

Chrome, Tampermonkey, ublock origin

I followed all the steps above but still not working.

**Comment by X01X012013** [comment]
@anpr22 The scripted solution works for all these websites, just define "canRun" to true: 
`unsafeWindow.canRun = true;`
If you do now know how to create your own Userscript, you can use this while waiting Aak script to be updated: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by anpr22** [comment]
@X01X012013  thanks , installing AdBlockProtector script worked :) I don't know how to define "canRun" to true. 

Now websites are opening faster and not hanging due to too many ads. Thanks

**Comment by X01X012013** [comment]
@anpr22 You will need to create a Userscript and grant unsafeWindow, then inside the anonymous function, define canRun like in normal JavaScript, but to unsafeWindow instead of window. 

If you still don't understand, it's fine, just use the script that I wrote.

**Comment by amogh79** [comment]
@reek times of india has again started detecting ad blocker, can you please fix the issue. Here is the URL
http://timesofindia.indiatimes.com/india/Rajnath-to-visit-Pakistan-for-Saarc-meet/articleshow/53424810.cms

**Comment by X01X012013** [comment]
OK, even my script stopped working on this site... They are trying hard... I will have a look.

**Comment by Ntweat** [comment]
@X01X012013 

I just stopped all scripts on their site..

Let them do anything now 💃

**Comment by X01X012013** [comment]
@Ntweat Fixed! Update my script to 1.0.53 and you should not see that screen again :smile:

**Comment by Ntweat** [comment]
@X01X012013 How?

**Comment by X01X012013** [comment]
@Ntweat What do you mean?

**Comment by Ntweat** [comment]
@X01X012013  What was the fix ?

**Comment by amogh79** [comment]
I am still getting the stupid adblock warning div on http://timesofindia.indiatimes.com/india/Facing-death-threat-from-Kejriwal-and-his-men-alleges-sacked-AAP-minister/articleshow/53437702.cms. I updated the script but its still not working.

**Comment by X01X012013** [comment]
@Ntweat It was to lock "_0x89ff" to an empty string using Userscript. 

@amogh79 
I am not getting the block message. 
![screenshot](http://i.imgur.com/wFWz8rC.png)
Can you show me your Tampermonkey script list? It should look like this: 
![screenshot](http://i.imgur.com/M1m5u0h.png)

**Comment by amogh79** [comment]
For me it looks the other way round. Adblock Protector is on the top followed by Anti-adblock killer. Does that matter?

**Comment by X01X012013** [comment]
@amogh79 If Aak is # 1 then it's OK, otherwise no. And also the version will matter too. If you have a screenshot, I can check it for you.

**Comment by amogh79** [comment]
![image](https://cloud.githubusercontent.com/assets/12402030/17226508/6d73860a-54cf-11e6-9b8d-dcd6ea751759.png)
Attached is the screenshot

**Comment by X01X012013** [comment]
@amogh79 You got the right version. Ideally you should install my script last but it shouldn't matter on this website. 
Which browser and AdBlocker are you using? What are the custom lists in your AdBlocker?

**Comment by mapx-** [comment]
other user tried the filters above and it works for him
https://github.com/reek/anti-adblock-killer/issues/1832

**Comment by amogh79** [comment]
@X01X012013 attached is my adblock custom list

![image](https://cloud.githubusercontent.com/assets/12402030/17228674/97731268-54d9-11e6-9926-74ae32bdb0e6.png)

**Comment by X01X012013** [comment]
@amogh79 Try #1832 first, if that doesn't work, I will need to see your custom list that looks like this: 
![screenshot](http://i.imgur.com/wNoqHRi.png)

**Comment by amogh79** [comment]
1832 works. I am pretty sure the ugly suckers at t i m e s o f i n d i a are following threads here and coming up ways to re-enable it.

**Comment by X01X012013** [comment]
Aak is quite known, but generally web masters will not follow threads here and adjust their system because a change that is not properly tested can cause the site to stop working, and that can cause big loss. But there are always crazy people and people who like to live on the edge.

**Comment by amogh79** [comment]
@X01X012013 yes I concur with that and last not the least thanks a ton for your help :+1:

**Comment by amogh79** [comment]
Ugly timesofindia is back with their ugly banner, any tweaks or fixes guys?

**Comment by X01X012013** [comment]
@amogh79 I patched my script earlier today, try to update it to 1.0.58 and see if that helps.

**Comment by mapx-** [comment]
or try
https://github.com/reek/anti-adblock-killer/issues/1879#issuecomment-237923375

**Comment by abhinavbom** [comment]
currently surviving with @@||indiatimes.com/*ad$script,domain=indiatimes.com
works for me in Chrome.

**Comment by Jaden-J** [comment]
@reek Indian Express blocks adblock
'http://indianexpress.com/adblocker/'
![adblocker the indian express](https://cloud.githubusercontent.com/assets/6412804/17607816/85803e4e-606b-11e6-99bc-5f0799fd76c4.png)

Please update the script for Indian Express

**Comment by X01X012013** [comment]
@Jaden-J `setReadOnly("RunAds", true);`
I will patch it into my script.

**Comment by mapx-** [comment]
for indianexpress ==> https://github.com/reek/anti-adblock-killer/issues/1916#issuecomment-239160564

**Comment by Vacon1** [comment]
Nope , none of your scripts are working on Indian Express , please update

Tried on Safari - Opera - Chrome

**Comment by X01X012013** [comment]
@Vacon1 I just tested, my script works fine for me, if you have a link where it doesn't work, please let me know.

**Comment by amogh79** [comment]
Looks like few pages on indiatimes.com are still displaying the obnoxious adblocker warning. Can anybody please help?

http://timesofindia.indiatimes.com/india/The-China-Pakistan-Economic-Corridor-10-key-points/listshow/53720516.cms

**Comment by mapx-** [comment]
working filters

```
indiatimes.com##div[id^=google_ads_iframe]
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
indiatimes.com##div[id^=div-gpt-ad]
@@||timesinternet.in^$script,domain=indiatimes.com
```

**Comment by amogh79** [comment]
Bingo thanks and middle finger to people at the indiatimes

**Comment by Nam3less79** [comment]
@reek, can you please check mumbaimirror.com too as its blocking now.

**Comment by mapx-** [comment]
did you test these filters ?
https://forums.lanik.us/viewtopic.php?p=103405#p103405

**Comment by Nam3less79** [comment]
@Mapx it didnt work for mumbai mirrror. Any new scripts.

**Comment by mapx-** [comment]
use only 1 blocking extension / addon (disable ghostery, disconnect, ...)

**Comment by Nam3less79** [comment]
@mapx- care to explain more. I am using adblocker with custom filters for various scripts and also anti-reek. Please advise. doesnt work for mumbaimirror.com

**Comment by amogh79** [comment]
Times of India is again been a pain in the wrong place, this url is blocking adblocker
http://timesofindia.indiatimes.com/india/Surgical-strikes-PM-Modi-will-decide-whether-the-footage-should-be-made-public-or-not-MoS-Hansraj-Ahir-says/articleshow/54699666.cms

Any help will be highly appreciated.

**Comment by mapx-** [comment]
try 
```
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script
```

**Comment by amogh79** [comment]
Still not working. Check out this page

http://timesofindia.indiatimes.com/world/pakistan/Pakistan-would-move-towards-China-Russia-as-US-is-declining-power/articleshow/54708689.cms

**Comment by amogh79** [comment]
Thanks its working, I messed up when applying filters

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Raavizz** [comment]
> @amogh79 : assholes

Stop your drama / insulting / bad words.
