### ISSUE TITLE
citationmachine.net

### ISSUE THREAD

**Issue by nguyenvuky** [reek/anti-adblock-killer#1726]
They asked me to turn off both of AB and ABP to continue.

I'm using Chrome, Tampermonkey, AB+ABP.

**Comment by jonasthambert** [comment]
Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
#BlockAdblock

Unable to reproduce with uBlock + Ghostery

**Comment by nguyenvuky** [comment]
Picture: http://i.imgur.com/8ukLP9o.png
Google Chrome
Tampermonkey
Adblock and AdblockPlus
Aaklist and default ones.

note: this website allow user to make 2 citations without ads, after that it makes the popup requiring users to disable adblock.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
