### ISSUE TITLE
playlivenewz.com

### ISSUE THREAD

**Issue by pbuonin** [reek/anti-adblock-killer#1727]
http://goo.gl/99t6Z6
http://i.imgur.com/dnYVU58.png
chrome/vivaldi browsers
tampermonkey
ublock origin
adblock warning removal list
anti-adblock killer reek
easy list
peter lowe's ad server list

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?p=98188&hilit=playlivenewz.com#p98188

**Comment by pbuonin** [comment]
Thanks much.

Best Regards,
Pat Buonincontri

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
