### ISSUE TITLE
businesstoday.in

### ISSUE THREAD

**Issue by gotitbro** [reek/anti-adblock-killer#1728]
### Anti AdBlock Killer Reek is not working on  http://www.businesstoday.in/

**Source Code:** http://paste2.org/BfCOgmU8

**Original URI:** http://www.businesstoday.in/technology/news/will-ship-freedom-251-phones-from-tomorrow-ringing-bells/story/234717.html

**Screenshot of Webpage**: http://imgbox.com/wu8OE4mF

**Extensions:** AdBlock, IDM Integration Module, Tampermonkey, Unlimited Free VPN - Hola

**Userscripts:** Anti-Adblock Killer

**Blocked Resources:** http://imgbox.com/NtYCV8X8

@reek Please look in to it.

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by ghajini** [comment]
using above script block some essential thing
www.businesstoday.in/technology/news/how-publishers-may-go-beyond-ad-revenues-instead-of-blocking-content/story/234526.html
![screenshot 17](https://cloud.githubusercontent.com/assets/20338483/17152693/884a2efa-5396-11e6-8e38-89bdce3a9863.png)
![screenshot 17](https://cloud.githubusercontent.com/assets/20338483/17152692/8848c088-5396-11e6-86d6-a6d823b4e1a8.png)

**Comment by mapx-** [comment]
```
@@||businesstoday.in^$generichide
@@||zedo.com/asw^$script,domain=businesstoday.in
@@||zedo.com/jsc/d2/fo.js$domain=businesstoday.in
@@||zedo.com/client/xp1/fmos.js$domain=businesstoday.in
```

**Comment by ghajini** [comment]
not working
http://www.businesstoday.in/sectors/telecom/bharti-airtel-q1-earnings-dips-31-pc-to-rs-1462-cr/story/235510.html
![screenshot 19](https://cloud.githubusercontent.com/assets/20338483/17184480/0ecf2666-544a-11e6-88ac-7f28be4a6e64.png)

**Comment by mapx-** [comment]
add
```
@@||businesstoday.in^$generichide
businesstoday.in##IMG[src*="zedo.com"]
@@||zedo.com^$domain=businesstoday.in
@@||vizury.com^$domain=businesstoday.in
```

**Comment by ghajini** [comment]
stoped working now above scripts @mapx- 
http://www.businesstoday.in/sectors/telecom/vodafone-offers-free-10-min-time-for-dropped-calls/story/235831.html
also i noted generichide script is not loaded when i open logger
![screenshot 28](https://cloud.githubusercontent.com/assets/20338483/17447618/19346ba0-5b6d-11e6-89d8-cbc97680c8cf.png)

**Comment by mapx-** [comment]
simple fix: disable javascript for that site

otherwise, try these filters:

```
@@||businesstoday.in^$generichide
@@*$script,domain=businesstoday.in
```

**Comment by ghajini** [comment]
what a headache of this site......... why not included in easylist or any fix

**Comment by mapx-** [comment]
if you are using chrome is very simple to disable javascript (click at the left of the address, then in the options block javascript for the site)

**Comment by ghajini** [comment]
thanx i understand...but disabling jscript completely is worth????
your help is appreciated & thanx again

**Comment by X01X012013** [comment]
@ghajini I think the settings only apply to that domain.

**Comment by ghajini** [comment]
blocking xp1.zedo.com turns site towards antiadblocking

**Comment by mapx-** [comment]
you have to block JS only for the site above

**Comment by ghajini** [comment]
ok 
thanx

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
