### ISSUE TITLE
zahitvstation.com

### ISSUE THREAD

**Issue by techDogg** [reek/anti-adblock-killer#1729]
![zahitv](https://cloud.githubusercontent.com/assets/18693982/16710368/9bb35638-45f9-11e6-97b6-9132dbfd8b02.png)

Anti-adblock isnt working on www.zahitvstation.com.
after a few moments a page pops up saying you have adblock enabled. tried with the 
aaklist filterlist using adblockplus, adblock, privacybadger and ublock. restarted browser.

link is http://www.zahitvstation.com/watch-cnn-usa-live also tried various links on this domain.
script manager = Tampermonkey
browser = Chrome Version 51.0.2704.103 m

still nogo. tks

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Ntweat** [comment]
Add this filter

`janjuaplayer.com###video_ads_overdiv
@@||zahitvstation.com^$generichide
@@|http://$image,third-party,domain=zahitvstation.com`

**Comment by techDogg** [comment]
Is this to be added to my adblockers customized filters list? or to the tampermonkey antiadblock killer script?
Will the antiadblocker killer script be updated to include this filter?

Sorry first time using the anti adblocker fixes. 

And thank you for your service and time.

**Comment by reek** [comment]
@techDogg 
https://gist.github.com/reek/dc234ea9687056bd99fe (raw for install)

**Comment by techDogg** [comment]
/happydance! Works like a charm! Did raw install. 
After minutes still no popup. Many thanks! Will continue to use and follow.
Recommend!

**Comment by hao19** [comment]
I still get the blockadblock screen even when subscribed to the aaklist but the blockadblock screen disappears after using the raw install. Can you copy the filters from the raw install into the aaklist so that we don't need to install a separate extension in order to use the raw install

**Comment by reek** [comment]
@hao19 
`@@||zahitvstation.com^$generichide`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
