### ISSUE TITLE
nana.co.il

### ISSUE THREAD

**Issue by roded** [reek/anti-adblock-killer#173]
http://10tv.nana10.co.il
http://imgbox.com/nisyul8m
Chrome
Tampermonkey
Adblock Plus

Adblock Warning Removal List
EasyList
Anti-Adblock Killer | Filters for Adblockers

```
nana10_co_il : {

      host : ['.nana10.'],

      onLoad : function () {

 		Aak.addStyle("#advert-tracker { height: 1px !important; }");

      }

    }
```

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
