### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by dipankar2308** [reek/anti-adblock-killer#1731]
http://timesofindia.indiatimes.com/world/rest-of-world/This-guy-used-a-frequent-flyer-loophole-to-take-a-60000-trip-in-a-first-class-suite-on-Emirates-heres-what-it-was-like/articleshow/51730463.cms
Chrome on Mac OS X
![screen shot 2016-07-09 at 11 13 16 pm](https://cloud.githubusercontent.com/assets/16604453/16709318/d6637cf0-462a-11e6-9c66-3de13a6484e2.png)
Ad Blocker Plus for Chrome

**Comment by Ntweat** [comment]
I think you need to update your lists

<img width="1440" alt="screen shot 2016-07-10 at 12 26 50 am" src="https://cloud.githubusercontent.com/assets/1205924/16711665/139aade6-4635-11e6-95b7-3a83b84212ec.png">

**Comment by Vacon1** [comment]
Nope !! Its still blocking us even after update. Not working.

**Comment by reek** [comment]
I'll fix it

**Comment by glennsamuel32** [comment]
@reek 

http://timesofindia.indiatimes.com/

It is still being blocked...a few links may work...but most get blocked now...

[IMG]http://i65.tinypic.com/2mnrme0.jpg[/IMG]

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
