### ISSUE TITLE
vipbox.nu (zoomtv.me)

### ISSUE THREAD

**Issue by jesterpaul** [reek/anti-adblock-killer#1732]
Screenshot:  http://imgur.com/V6W2s8q
Browser:  Chrome Version 51.0.2704.106 (64-bit) (Deb Linux)
Tapermonkey
Adblock Plus
EasyList + AakList

**Comment by jesterpaul** [comment]
Switching ti UBlock origin. Same result

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by jesterpaul** [comment]
Noticed on Mac OS X Chrome, Tapermonkey, Ublock Origin, EasyList + AakList also detected, but now they are picking it up across their sites.

New image: http://imgur.com/UT7Yxwx

**Comment by reek** [comment]
@jesterpaul 
enable Tampermonkey
