### ISSUE TITLE
q.gs (adf.ly)

### ISSUE THREAD

**Issue by ghajini** [reek/anti-adblock-killer#1733]
http://q.gs/A9cNn
antiadblock killer not working

**Comment by Ntweat** [comment]
Be a little patient 

Here is your direct link (Adblock was working)
https://91139afd9f8fdb869f329c57c4b04f7901c26a12.googledrive.com/host/0BwZSL9XNADsQQ2RaRktqNTNQbzA/BRS_Gross_Anatomy_8th_edition_medibos.blogspot.com.pdf

**Comment by ghajini** [comment]
![screenshot 4](https://cloud.githubusercontent.com/assets/20338483/16714703/edc66df8-46e8-11e6-9a83-1d659aa7bc72.png)

**Comment by Ntweat** [comment]
Update your lists.. 
It is working.. 
I pasted the direct link too ..

**Comment by ghajini** [comment]
aak kist showing 0 used out of 2006

**Comment by Ntweat** [comment]
<img width="1440" alt="screen shot 2016-07-10 at 12 27 15 pm" src="https://cloud.githubusercontent.com/assets/1205924/16714718/bf6462ac-4699-11e6-9056-102bbd88eb43.png">

**Comment by ghajini** [comment]
not working still same

**Comment by reek** [comment]
@ghajini 
already killed by AakList otherwise try AdsBypasser https://greasyfork.org/fr/scripts/4881-adsbypasser

**Comment by ghajini** [comment]
![screenshot 5](https://cloud.githubusercontent.com/assets/20338483/16714802/0e8ed6da-46ec-11e6-97f3-751b7ee7978f.png)
also not working with firefox

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by ghajini** [comment]
is issue solvable

**Comment by reek** [comment]
@ghajini 
it is to you, to find out why it does not work with you, see https://github.com/reek/anti-adblock-killer#help

**Comment by ghajini** [comment]
ok i found, issue is with ublock origin and not adblock plus

**Comment by ghajini** [comment]
can you reproduce bug with ublock origin

**Comment by reek** [comment]
it's ok

**Comment by ghajini** [comment]
![image](https://cloud.githubusercontent.com/assets/20338483/17817809/12d25bae-665e-11e6-8f90-f8ff2c8570a4.png)
stopped working @reek 
http://q.gs/A9cNn
https://adf.ly/672863/gow1ps2

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
