### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by sunilgc0** [reek/anti-adblock-killer#1734]
Browser: Chrome
Using aka list with tampermonkey
http://timesofindia.indiatimes.com/world/middle-east/IS-territory-shrinks-12-since-start-of-2016-Report/articleshow/53141112.cms

**Comment by Ntweat** [comment]
Read the issues before posting. 
Duplicate.
TimesofIndia, Businesstoday, are using a different method to block adblock 
Issue #1725

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
