### ISSUE TITLE
vipleague.ch / vipleague.sx (zoomtv.me)

### ISSUE THREAD

**Issue by schn1tt3r** [reek/anti-adblock-killer#1735]
vipleague.ch
vipleague.sx

http://i.imgur.com/alpVT8n.png

Mozilla Firefox
Greasemonkey
Adblock Plus
AakList  (reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt)

**Comment by schn1tt3r** [comment]
EDIT: Duplicate

**Comment by reek** [comment]
Ok, I'll kill it, thansk

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
