### ISSUE TITLE
afdah.tv / timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by tabishishaq** [reek/anti-adblock-killer#1738]
http://afdah.tv/
http://timesofindia.indiatimes.com/sports
http://imgbox.com/4cUTtvq4
http://imgbox.com/bJRqYxzI
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by Ntweat** [comment]
Duplicate. TimesofIndia, Businesstoday, are using a different method to block adblock 
Read Issue #1725

**Comment by tabish4448** [comment]
and what about afdah.tv ?

**Comment by Ntweat** [comment]
Add this to your filter list

`@@||yourjavascript.com^$script,domain=afdah.tv`

**Comment by tabish4448** [comment]
It Worked! Thanks
now I am looking forward to #1725 for TimesofIndia and Businesstoday.

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by Ntweat** [comment]
Temporary stop gap fix 

#1725#issuecomment-231798999

**Comment by glennsamuel32** [comment]
@reek @Ntweat 

http://timesofindia.indiatimes.com/

It is still being blocked...a few links may work...but most get blocked now...

http://oi65.tinypic.com/2mnrme0.jpg

**Comment by Ntweat** [comment]
@glennsamuel32 

I tested on around 25 links. It works

Paste link where it woesnt work

**Comment by glennsamuel32** [comment]
@reek @Ntweat 

LOL !!!  which website are you on :)

http://timesofindia.indiatimes.com/india/After-SC-verdict-in-his-favour-Nabam-Tuki-takes-charge-as-Arunachal-CM/articleshow/53197231.cms

http://timesofindia.indiatimes.com/india/SCs-Arunachal-verdict-is-third-legal-setback-for-Modi-government/articleshow/53195522.cms

http://timesofindia.indiatimes.com/top-stories/Kohli-boost-for-Duleep-Trophy-this-year/articleshow/53196337.cms

http://timesofindia.indiatimes.com/world/uk/David-Cameron-orders-Indian-spicy-food-for-last-supper-as-UK-PM/articleshow/53198204.cms

http://timesofindia.indiatimes.com/world/rest-of-world/Taiwan-sends-warship-to-South-China-Sea-after-ruling/articleshow/53189750.cms

http://timesofindia.indiatimes.com/india/Governor-cant-embroil-in-political-thicket-says-Supreme-Court/articleshow/53195873.cms

http://timesofindia.indiatimes.com/india/Thulla-remark-Delhi-high-court-stays-Arvind-Kejriwals-appearance-in-trial-court/articleshow/53189674.cms

http://i66.tinypic.com/2h5vh9u.jpg

**Comment by Ntweat** [comment]
@glennsamuel32 

I clicked all the links.
All are working fine. 
Can't upload all screenshots. (Example below) 
Are you sure you have tried: https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672

If this doesnt work try: https://github.com/reek/anti-adblock-killer/issues/1753#issuecomment-232341798

Tell the browser and plugins used. 
I tested on Chrome, AdBlockPlus and TamperMonkey 

Example of it working:
<img width="1302" alt="screen shot 2016-07-13 at 3 03 35 pm" src="https://cloud.githubusercontent.com/assets/1205924/16816205/019f15fe-490b-11e6-9ce0-bbdd89a98cf9.png">

**Comment by glennsamuel32** [comment]
@reek @Ntweat 

 #1725 works perfectly !!!

I was blindly following directions on the website...

Thank you all for making my day !!!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
