### ISSUE TITLE
eenadu.net

### ISSUE THREAD

**Issue by tabishishaq** [reek/anti-adblock-killer#1741]
http://www.eenadu.net/homeinner.aspx?category=home&item=break147

Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

![008](https://cloud.githubusercontent.com/assets/20391995/16743555/6db13862-47c6-11e6-81b6-7eb7aa42d7ba.png)

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
