### ISSUE TITLE
graffica.info

### ISSUE THREAD

**Issue by kdh164** [reek/anti-adblock-killer#1742]
Anti Adblock Killer not working there

**Comment by maynak00** [comment]
**Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide**
**try with:**
`graffica.info#@#.afs_ads`
**or**
`graffica.info##.ui-front.ui-widget-overlay`
`graffica.info##.ui-resizable.ui-front.ui-corner-all.ui-widget-content.ui-widget.ui-dialog`
**same filter: issue 1708 skins4virtual.com**

**Comment by reek** [comment]
Already killed by AakList

**Comment by unaef** [comment]
Not work for me <a href="http://imgbox.com/oJnLN3mW" target="_blank"><img src="http://4.t.imgbox.com/oJnLN3mW.jpg" alt="image host"/></a>

<a href="http://imgbox.com/7LcRCW8N" target="_blank"><img src="http://4.t.imgbox.com/7LcRCW8N.jpg" alt="image host"/></a>

**Comment by maynak00** [comment]
@reek, antiadblock message come after 8-10 seconds
problem: xmlhttprequest http://graffica.info/hsTKgt81

**try with:**
`||graffica.info^$xmlhttprequest`
no need: https://github.com/reek/anti-adblock-killer/issues/1742#issuecomment-231888405

**Comment by unaef** [comment]
Now it worked! 

<a href="http://imgbox.com/dVN2basS" target="_blank"><img src="http://5.t.imgbox.com/dVN2basS.jpg" alt="image host"/></a>

But without [#1742 (comment)](https://github.com/reek/anti-adblock-killer/issues/1742#issuecomment-231888405) not works

Thanks

**Comment by reek** [comment]
Now I have message, I'll kill it

**Comment by X01X012013** [comment]
Disable setTimeout() will work too.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by unaef** [comment]
http://graffica.info renovates AdBlockBlocker!!

This does not work now:
_||graffica.info^$xmlhttprequest
graffica.info##.ui-front.ui-widget-overlay
graffica.info##.ui-resizable.ui-front.ui-corner-all.ui-widget-content.ui-widget.ui-dialog_

![captura de pantalla 2017-05-03 a las 20 38 10](https://cloud.githubusercontent.com/assets/20425984/25675922/7e341fe8-3040-11e7-9cbb-7503e172f49d.png)

**Comment by jspenguin2017** [comment]
@unaef Can't reproduce. Waited a minute and scrolled up and down. 
![image](https://cloud.githubusercontent.com/assets/7283682/25677490/64907ef2-3003-11e7-8988-ac2a5d64a0e3.png)

**Comment by jspenguin2017** [comment]
Looks like it doesn't always block you, I had to refresh a couple times. 
This should work for now...
`||axiomaticalley.com^$domain=graffica.info`

**Comment by unaef** [comment]
Now it's working!
Thanks,

**Comment by jspenguin2017** [comment]
If you want to be more future-proof, use these: 
```
*$script,third-party,domain=graffica.info
@@||grafficainfo.disqus.com^$domain=graffica.info
@@||connect.facebook.net^$domain=graffica.info
@@||disquscdn.com^$domain=graffica.info
@@|https://disqus.com/next/config.js$domain=graffica.info
```
