### ISSUE TITLE
androidsage.com

### ISSUE THREAD

**Issue by mileskjeller** [reek/anti-adblock-killer#1743]
Site: http://blockadblock.com [Site for Blocker also runs the blocker]
Originally noticed on http://www.androidsage.com/2016/06/04/install-moto-g4-apps-on-any-motorola-device-camera-file-manager-command-center-gallery
Screenshot: http://i.imgur.com/b1oVJf8.png
Google Chrome
uBlock Origin [Privacy Badger (Disabled), Pi-Hole DNS Running on Network]
uBlock Filters, Anti-Adblock Killer, EasyList, Easy Privacy, Malware Domains

**Comment by Ntweat** [comment]
It has been solved.

Step 1. https://gist.github.com/reek/dc234ea9687056bd99fe (click raw for install Script)
Step 2. https://gist.github.com/reek/292ed06433b4cfc07bc94cb4fec4adbe (copy raw url add it to AB)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
