### ISSUE TITLE
pokemonizle.net

### ISSUE THREAD

**Issue by StANDby007** [reek/anti-adblock-killer#1745]
http://pokemonizle.net/
http://imgur.com/L2YwR84
Google Chrome
Github
Adblock Plus
EasyList + AakList

**Comment by maynak00** [comment]
**try with:**
`pokemonizle.net#@##adsense`

**Comment by reek** [comment]
@StANDby007 
Ok, I'll kill it

@maynak00 
Thanks for rule :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
