### ISSUE TITLE
litv.tv

### ISSUE THREAD

**Issue by 1298348** [reek/anti-adblock-killer#1746]
Hi, issue #1299 failed again 
https://www.litv.tv/vod/drama/content.do?id=VOD00039000
https://imgur.com/ztvd4Da
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList

**Comment by reek** [comment]
Sorry no solution

**Comment by X01X012013** [comment]
`getAdBlock:function(){var a=document.createElement("div");a.setAttribute("id","ads");document.body.appendChild(a);return document.getElementById("ads")?!1:!0}`

Disable generic filters might help.

**Comment by X01X012013** [comment]
This website has Geo Lock.
