### ISSUE TITLE
Dawn.com

### ISSUE THREAD

**Issue by tabishishaq** [reek/anti-adblock-killer#1747]
http://www.dawn.com/news/1270350/bernie-sanders-endorses-former-rival-hillary-clinton-for-us-president

Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

![a](https://cloud.githubusercontent.com/assets/20391995/16775488/42e6b9cc-487a-11e6-87ba-6c699d0b930c.png)

**Comment by maynak00** [comment]
**try with:**
`dawn.com##.adblocker-modal`
`dawn.com##.soft--bottom > .adblocker-overlay`
`dawn.com##.adblock-alert.text--center.one-whole`
**or**
`dawn.com#@#div[id^="div-gpt-ad"]`
`dawn.com#@#.widget-adsense`
`dawn.com#@#.soft-half--top.soft-half--sides`
`dawn.com#@#.radWrapper`
`dawn.com#@#.ad__wrapper`
`dawn.com#@#.ad--top-leaderboard`
`dawn.com#@#.ad`
`dawn.com#@#.text_ads`
`dawn.com#@#.text_ad`
`dawn.com#@#.textAd`
`dawn.com#@#.text-ads`
`dawn.com#@#.text-ad-links`
`dawn.com#@#.text-ad`
`dawn.com#@#.pub_728x90`
`dawn.com#@#.pub_300x250m`
`dawn.com#@#.pub_300x250`
`dawn.com##.widget-adsense.theme.widget`
`dawn.com##.ad__wrapper.radWrapper`

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by X01X012013** [comment]
This website use a homemade FuckAdBlock, maybe we can use a homemade FuckFuckAdBlock to counter it.

**Comment by reek** [comment]
@awaisi 
@X01X012013 
Or use Aak function
```` javascript
      fab_dawn_com : {
        // issue: https://github.com/reek/anti-adblock-killer/issues/1747
        host : ['dawn.com'],
        onStart : function () {
          Aak.fakeFuckAdBlock('detectAdBlock', 'DetectAdBlock');
        }
      },

**Comment by awaisi** [comment]
Thanks reek. That works too. Can you merge/add this to the main script?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
