### ISSUE TITLE
eclypsia.com

### ISSUE THREAD

**Issue by ThePierrezou** [reek/anti-adblock-killer#175]
<a href='http://pix.toile-libre.org/upload/original/1423007443.png'><img src='http://pix.toile-libre.org/upload/thumb/1423007443.png' /></a>
http://www.eclypsia.com/en/eclypsiatv
Firefox
µblock with Anti adblock killer easy list easy privacy and many other lists.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
