### ISSUE TITLE
eenadu.net

### ISSUE THREAD

**Issue by rajaschava** [reek/anti-adblock-killer#1756]
www.eenadu.net

Chrome 51.0.2704.103 m
AdBlock
TamperMonkey
AakList (Anti-Adblock Killer)

When you click on any new link the page opens but immediately redirected to 'Anti adblock' page requesting to disable the adblock.

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by rajaschava** [comment]
Hi,

I am still seeing the adblock killer page for this website.

1. open eenadu.net
2. click on any news link (sorry, its in a foreign language)
3. Wait for the page to load with news
4. In few seconds it redirects to the adblock killer page
http://www.eenadu.net/welcome.html

I got the latest ani ad block killer txt file. Could you please let me know
what i am missing?

Regards,
Raja Chava

**Comment by mapx-** [comment]
add this filter in your adblocker

`@@||eenadu.net/*ad$script`

**Comment by rajaschava** [comment]
Awesome, it worked. Thank you so much.

**Comment by ravi6603** [comment]
thanks

**Comment by reek** [comment]
done update aaklist
