### ISSUE TITLE
economic times

### ISSUE THREAD

**Issue by ghajini** [reek/anti-adblock-killer#1758]
http://economictimes.com/tech/internet/google-says-anti-privacy-effort-has-delivered-2-billion/articleshow/53193257.cms
advising me to block adblock

**Comment by Ntweat** [comment]
@ghajini follow reporting guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

Link does not exist
<img width="1285" alt="screen shot 2016-07-13 at 2 48 28 pm" src="https://cloud.githubusercontent.com/assets/1205924/16815735/fd1d82ec-4908-11e6-93c7-1da86068a7fd.png">

**Comment by ghajini** [comment]
Site might have remove link

**Comment by X01X012013** [comment]
I can go in economictimes.com without problem. You might want to take a screenshot and update the URL.

**Comment by reek** [comment]
no detected
