### ISSUE TITLE
trovesaurus.com / dogefaucet.com

### ISSUE THREAD

**Issue by jspenguin2017** [reek/anti-adblock-killer#1770]
https://www.trovesaurus.com/
http://imgur.com/vp5Y6Bo
Opera
Tampermonkey
AdBlock Plus
1. EasyList 2. EasyList China 3. AdBlock Warning Removal List 4. AakList

`trovesaurus.com##div#blocked`
I'm not sure how to deal with the button, we can always remove it with userscript when page loads. 

---

http://www.dogefaucet.com/
http://imgur.com/teOl6G2

`@@dogefaucet.com/initializr/js/ads.js`

**Comment by reek** [comment]
Thanks
