### ISSUE TITLE
CBS Show doesnt play video, gives Warning for using adblocker

### ISSUE THREAD

**Issue by sunilgc0** [reek/anti-adblock-killer#1774]
http://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/Csanv5ylMEIRzoPvlgMDYPpbJ9TIM1kq/the-late-show-7-15-2016-charlie-rose-gayle-king-norah-o-donnell-deray-mckesson-bonnie-mcfarlane-/

Using Chrome with tampermonkey

Thanks

**Comment by X01X012013** [comment]
I haven't got any AdBlock related message, but a Geo Lock message...

**Comment by sunilgc0** [comment]
Attaching screeshot
![capture](https://cloud.githubusercontent.com/assets/13044205/16903254/b5908d8c-4c3e-11e6-8b22-d70a54ceac42.PNG)

**Comment by X01X012013** [comment]
OK, I clicked another video and it doesn't have Geo Lock, and I get the same screen. I'll go have a look, I'll update this message later.

**Comment by sunilgc0** [comment]
Wow thanks for taking look and making these notes and analysis. I appreciate it :). OK, let him have a look

**Comment by lassekongo83** [comment]
One of the scripts: http://c5255dfbeaf8de918c73-c9552ca9f9dab9ffb917d11bd7154762.r70.cf5.rackcdn.com/tbd5CRSAuXb104cCvylq.min.js
Blocking this or using uBO inline blocking in Firefox will remove the adblock message, but it will instead display the following message: "The video you have requested is unavailable or has expired." :-/

**Comment by X01X012013** [comment]
Yea, Flash players can be quite solid. I was thinking if we replace XHR so it returns a blank image / string, but couldn't get it to work yet... I'm not sure if Flash uses XHR...

**Comment by reek** [comment]
Sorry no solution, geolocked

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=98874#p98874
