### ISSUE TITLE
kissanime.com

### ISSUE THREAD

**Issue by Pandiisop** [reek/anti-adblock-killer#178]
http://kissanime.com/ (video: http://kissanime.com/Anime/Selector-Spread-WIXOSS/Episode-001 ~23secs its ask me to turn off adblock)
http://i.gyazo.com/8fa650b012ac0e7ea7278e8491de34a9.png
Google Chrome
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

edit: forgot to add Request tag sorry >w<
edit2: Added Request in title since I don't know how to add them normally

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
