### ISSUE TITLE
reuters.com

### ISSUE THREAD

**Issue by imagefighter** [reek/anti-adblock-killer#1782]
http://www.reuters.com/news/world
//reuters.tv/images/favicon.ico
Chrome for Windows 
Tampermonkey
Adblock

![image](https://cloud.githubusercontent.com/assets/20517963/16916414/c1ca2f7c-4cca-11e6-8288-87e7cc70b9af.png)
![image](https://cloud.githubusercontent.com/assets/20517963/16916653/f13dbb6a-4ccb-11e6-9cf9-b711d40bf732.png)
![image](https://cloud.githubusercontent.com/assets/20517963/16916768/b38c0dca-4ccc-11e6-8716-dbb61462440a.png)

**Comment by X01X012013** [comment]
Defining "RTV_ad_render" as an empty function will prevent the message from showing up... and kill the video with it... I need to have a closer look...

**Comment by mapx-** [comment]
add
```
@@||reuters.com^$elemhide
@@||reuters.tv$subdocument,domain=reuters.com
```

**Comment by reek** [comment]
done
