### ISSUE TITLE
lasprovincias.es/

### ISSUE THREAD

**Issue by jmp9292** [reek/anti-adblock-killer#1785]
http://www.lasprovincias.es/politica/201607/18/negocia-mesa-congreso-solo-20160718114241-rc.html
Script failing to kill adblock detector.

**Comment by X01X012013** [comment]
`unsafeWindow.Vocento = { checkAdBlock: 1 };`
If you do now know how to create your own Userscript, you can use this while waiting for Aak to update: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by jmp9292** [comment]
so where i need to add

unsafeWindow.Vocento = { checkAdBlock: 1 };

**Comment by applesam** [comment]
Install Tempermonky Beta  >>>>>>>use this   https://x01x012013.github.io/AdBlockProtector/ Install This  script

**Comment by X01X012013** [comment]
@jmp9292 You need to create a Userscript and add that line, if you do not understand, just install this script: https://x01x012013.github.io/AdBlockProtector/
The fix is included.

**Comment by mapx-** [comment]
or add directly this filter
@@||lasprovincias.es/*ad$script

**Comment by reek** [comment]
done
