### ISSUE TITLE
Indian websites

### ISSUE THREAD

**Issue by maxbluestack** [reek/anti-adblock-killer#1787]
http://www.mid-day.com/
http://www.hindustantimes.com
http://timesofindia.indiatimes.com
http://www.ndtv.com/

Firefox 47.0.1
Adblock plus 2.7.3
aaklist 07/19
tampermonkey beta (with reek userscript)

**Comment by applesam** [comment]
use this.>>https://x01x012013.github.io/AdBlockProtector/  install  this script

**Comment by X01X012013** [comment]
http://www.hindustantimes.com and http://timesofindia.indiatimes.com are covered in my script. 

http://www.ndtv.com/ and http://www.mid-day.com/ seems to work fine for me (they are not covered in my script, probably covered in Aak).

**Comment by maxbluestack** [comment]
Thanks, X01X012013.
The homepage for ndtv.com and mid-day.com work fine. But if you click on any of the news link, the content is blocked. Could you kindly check?

@applesam, i'll test and let know how it goes.

**Comment by maxbluestack** [comment]
timesofindia - Works
ndtv - Is broken
mid-day - Works
Hindustantimes - Works

**Comment by X01X012013** [comment]
@maxbluestack For both ndtv and mid-day, I clicked into a random article and it works fine, video plays too. If you have a link to a page that doesn't work, it will be great.

**Comment by maxbluestack** [comment]
NDTV - http://www.ndtv.com/india-news/exclusive-in-kargil-war-india-was-minutes-away-from-bombing-pak-bases-1433345?pfrom=home-lateststories

timesofindia redirects few traffic to domain indiatimes.com and those are broken
http://timesofindia.indiatimes.com/city/bengaluru/Karnataka-is-the-superstar-in-Kabalis-new-don/articleshow/53283678.cms

**Comment by X01X012013** [comment]
@maxbluestack Sorry, I'm not getting anything. http://imgur.com/a/HwhvX As you can see in these images, those websites work perfectly fine for me. 
Can you provide a screenshot of the block screen that you see?

**Comment by maxbluestack** [comment]
Please find the screenshot
http://imgur.com/a/l88dD

Let me know if you need me to collect further logs that will assist your analysis.

**Comment by X01X012013** [comment]
@maxbluestack I can see in my console that Aak was activated on that site. http://i.imgur.com/Ku4VvQX.png Are you sure that you have Aak Script properly installed into Tampermonkey?

**Comment by maxbluestack** [comment]
I believe AAK is installed properly into Tampermonkey. But tampermonkey in itself does not have options to see what is installed (like ADB does)

http://imgur.com/UkFmppP

**Comment by X01X012013** [comment]
@maxbluestack Click on Tampermonkey icon, second last of the left colon, click on it, make sure Aak is turned on. The screen should look like this: http://i.imgur.com/YF6tqAx.png

**Comment by maxbluestack** [comment]
Here is the request info
http://imgur.com/PefjcoZ

**Comment by X01X012013** [comment]
@maxbluestack That looks good. What rule lists do you have on AdBlock Plus?

**Comment by maxbluestack** [comment]
Here you go
http://imgur.com/Qt8HqH6

**Comment by X01X012013** [comment]
@maxbluestack Disable Facebook filter, if that doesn't work, I ran out of solution, it can be a Firefox issue.

**Comment by maxbluestack** [comment]
@X01X012013 , I have re-installed Firefox and I have gone with ublock origin instead of ABP.
Everything works fine. You can go ahead and mark this as resolved.

Off-topic, do you know what script blocker should I use on Android + firefox combination? Tampermonkey and greasemonkey are un-supported.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
