### ISSUE TITLE
times of india new blocking unable to open

### ISSUE THREAD

**Issue by prathameshrk** [reek/anti-adblock-killer#1788]
Hi check this link, i am unable to bypass  this website even after installing the script and adding filter list. The page opens, but the moment I try to scroll down, they show the anti adblock popup : http://timesofindia.indiatimes.com/india/Silent-Sidhu-keeps-everyone-guessing-as-Congress-too-opens-its-doors/articleshow/53290257.cms

**Comment by X01X012013** [comment]
http://timesofindia.indiatimes.com is covered in my script, you can use it while waiting for Aak to update: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by prathameshrk** [comment]
Another one, economic times also blocking, X01X012013, your script won't work. The page loads properly, when I scroll down, the anti-adbocker comes up. I noticed that the moment I scroll down it pops up. Check this link http://economictimes.indiatimes.com/news/economy/policy/25-years-of-reforms-attack-neo-illiberalism-to-herald-true-liberalisation-says-sa-aiyar/articleshow/53310256.cms

**Comment by X01X012013** [comment]
@prathameshrk I will use wildcard to match the domain, the rule now apply to *.indiatimes.com
Update to 1.0.40 will fix economictimes.indiatimes.com, if it is still not working, please let me know.

**Comment by prathameshrk** [comment]
thanks, it's working. btw I keep on discovering new websites which have blocked adblockers. Don't these people understand that instead of disabling the adblocker we will stop using their site! Anyways the ones which I discovered are : ndtv.com, indiatoday.intoday.in

**Comment by X01X012013** [comment]
@prathameshrk They pay less electricity fee if there is less traffics. 
ndtv.com is working fine, I will have a look on the other one.

**Comment by Ntweat** [comment]
@X01X012013 

NDTV has come with a new detection script

Add  to solve : 

`@@||ads.rubiconproject.com/*^$script`

**Comment by glennsamuel32** [comment]
@X01X012013 @Ntweat

Here we go again...was working fine until yesterday...
The news site seems to have updated their blockers...

[http://timesofindia.indiatimes.com/business/india-business/Union-Cabinet-approves-key-changes-to-GST-Bill-drops-1-additional-tax/articleshow/53420179.cms](url)
[http://timesofindia.indiatimes.com/india/Arvind-Kejriwal-PM-Modi-BJP-may-kill-me/articleshow/53417443.cms](url)
[http://timesofindia.indiatimes.com/sports/rio-2016-olympics/india-in-olympics-2016/wrestling/NADA-adjourns-hearing-Narsinghs-fate-to-be-known-on-Thursday/articleshow/53419256.cms](url)

Using these scripts and AdBlockProtector...
https://gist.github.com/reek/dc234ea9687056bd99fe (click raw for install Script)
https://gist.github.com/reek/292ed06433b4cfc07bc94cb4fec4adbe (copy raw url add it to AB)

Thanks for helping !!

**Comment by mapx-** [comment]
add these filters
```
@@||indiatimes.com^$generichide
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
```

**Comment by Ntweat** [comment]
@mapx- 

Its not working..
Keep scrolling up and down.. 
30 secs it will block you

**Comment by mapx-** [comment]
add also
@@$image,domain=indiatimes.com

**Comment by glennsamuel32** [comment]
@mapx- @Ntweat 

Sorry but not working after adding all those filters, just as Ntweat said...

**Comment by Ntweat** [comment]
@glennsamuel32 

Final weapon 💃 

Block all scripts on indiatimes.com (will block videos from playing too)

`||$script,domain=indiatimes.com`

**Comment by Ntweat** [comment]
@glennsamuel32 

Better solution
Install this

https://x01x012013.github.io/AdBlockProtector/

**Comment by glennsamuel32** [comment]
@Ntweat 

This worked --- ||$script,domain=indiatimes.com
Thanks !!! I don't care much for videos so it's fine :+1: 
And I already installed the AdBlockProtector...

**Comment by Ntweat** [comment]
@glennsamuel32 

You will never face problems with indiatimes.com if you use that..
It kills all scripts on the domain :)

**Comment by prathameshrk** [comment]
@Ntweat @X01X012013 Hi I am using that script (by X01X012013), but times of India is still blocking me, how is it possible? and those filters are to be added in Adblocker or in script? (sorry I am a mech guy & don't know much). Please help.

**Comment by X01X012013** [comment]
@prathameshrk Hi, update my script to 1.0.53 or higher will fix this issue.

**Comment by glennsamuel32** [comment]
@X01X012013 

I updated your script and deleted all the previous custom filters...
The website works well again !!! Thanks !!!

Is there a way to get the videos to work ?
If using Adblock, the videos don't play...

**Comment by X01X012013** [comment]
@glennsamuel32 Hi there, videos works fine for me: 
![screenshot](http://i.imgur.com/OFhxURO.png)
Try to remove custom filters that may affect videos.

**Comment by prathameshrk** [comment]
ToI has come up with some new script I guess, the anti adblock popup is coming again... it's better to disable js for toi I guess...

**Comment by glennsamuel32** [comment]
I moved to uBlock Origin---added the warning removal list and Adblock killer list in uBlock settings...
And it works without a hitch straight off the bat !!
I don't even have Tampermonkey now and everything works fine...
Kudos to everyone involved !!!

**Comment by glennsamuel32** [comment]
[http://i66.tinypic.com/15rjlah.jpg](url)

Videos still don't work though...

**Comment by mapx-** [comment]
```
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
