### ISSUE TITLE
mangabee.co

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#179]
![](http://i.imgur.com/AkiTcmD.png)

http://www.mangabee.co/Naruto_bee/548/
Google Chrome
Tampermonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by alexander255** [comment]
Working script: http://pastebin.com/Ae63fQ8z

**Comment by reek** [comment]
Hi,

thank you, I will adapt to AAK

See you soon
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
