### ISSUE TITLE
strikeout.co (new)

### ISSUE THREAD

**Issue by th10287** [reek/anti-adblock-killer#1792]
Different from old anti-adblock, now found on player.
http://www.strikeout.co/baseball/394900/1/cincinnati-reds-vs-atlanta-braves-live-stream-online.html
^^or any of the streams from the main page http://www.strikeout.co/
http://imgur.com/a/f2Hz6

Google Chrome 51.0.2704.103 m
Tampermokey
AdBlock
Lists: http://imgur.com/a/i3WWo

**Comment by X01X012013** [comment]
Try the solution here: #1784
