### ISSUE TITLE
www.geekzone.co.nz

### ISSUE THREAD

**Issue by r0bbienz** [reek/anti-adblock-killer#1794]
Using Ublock Origin they blank the whole screen when using a adblock with tampermonkey running your script

**Comment by X01X012013** [comment]
It is running normally for me. Do you have a screenshot?

**Comment by r0bbienz** [comment]
Hi - thanks for looking into it - Im using Chrome

![image](https://cloud.githubusercontent.com/assets/20566970/17008723/1472fa36-4f48-11e6-81c0-d51be67d1be4.png)

![image](https://cloud.githubusercontent.com/assets/20566970/17008736/2b494490-4f48-11e6-822d-7092a16bb159.png)

**Comment by X01X012013** [comment]
Hum, it can be a uBlock Origin's issue, the webpage works fine for me with Opera, AdBlock Plus, and Tampermonkey. 
![screenshot](http://i.imgur.com/g2SM1g9.png)

**Comment by r0bbienz** [comment]
Thanks anyway - I think it's coming from the easylist 3rd party filter.  These guys are very anti ad blockers so thought they stepped it up

Thanks
