### ISSUE TITLE
http://ay.gy/1abJeN (adfly link)

### ISSUE THREAD

**Issue by vikeyev** [reek/anti-adblock-killer#1795]
http://i.imgur.com/WmUsu6o.png

Browser: Firefox
Script Manager: Greasemonkey
Ad blocker: Ublock Origin
Filter lists: Anti-Adblock Killer | Reek‎,  EasyList‎, AakList

**Comment by X01X012013** [comment]
Website like this only has one job: prevent AdBlockers to work. Their JS has some serious top tier obfuscation, even after Unminify, it is still not human readable... http://i.imgur.com/3OCjJVF.png

**Comment by vikeyev** [comment]
Thanks XO1

**Comment by reek** [comment]
use https://greasyfork.org/fr/scripts/4881-adsbypasser
