### ISSUE TITLE
livenewschat.eu / zahitvstation.com

### ISSUE THREAD

**Issue by BuddyT** [reek/anti-adblock-killer#1797]
http://www.livenewschat.eu/politics/

http://www.zahitvstation.com/watch-msnbc-live 

Both use BlockAdBlock

**Comment by X01X012013** [comment]
The first one works fine for me. 
The second one is the updated Block AdBlock that has a big weak point: needs eval(). All we need to do is remove eval() and it's dead. 

I added the second site to this script, you can use it while waiting for Aak to update: 
https://x01x012013.github.io/AdBlockProtector/
For the first site, I am not getting anything, make sure that you have properly installed Aak Script.

**Comment by BuddyT** [comment]
Thanks. The AdBlockProtector script fixed both sites for me.

**Comment by X01X012013** [comment]
@BuddyT I checked my webpage and found out that the first site was already covered in my script XD Sorry for the misinformation...

**Comment by mapx-** [comment]
for the first add these filters
@@|https://*ad$image,domain=livenewschat.eu
@@|http://*ad$image,domain=livenewschat.eu
||taboola.com^

**Comment by mapx-** [comment]
for the second:

@@|http://*ad$image,domain=zahitvstation.com

**Comment by reek** [comment]
Already fixed by Easylist
