### ISSUE TITLE
seriesbang.net/

### ISSUE THREAD

**Issue by wikilayn** [reek/anti-adblock-killer#180]
http://www.seriesbang.net/serie/revenge
http://i.imgur.com/sSOiVNn.png
Mozilla Firefox 35.0.1
Greasemonkey
µBlock 0.8.6.0
Fanboy+Easylist-Merged Ultimate List + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Already killed.
