### ISSUE TITLE
aktualne.cz

### ISSUE THREAD

**Issue by shaarkys** [reek/anti-adblock-killer#1800]
http://www.aktualne.cz/

<div id="adb-campaign" style="position:fixed;bottom:0;left:0;right:0;background:#ca372c;padding:1em 1em 0.5em;color:white;z-index:10000000000000000;font-size:initial;text-align:center;font-weight:bold;line-height: 1.42;"><div style="margin:0 auto;width:960px;max-width:100%;"><img src="//i0.cz/bbx/aktualne/img/logo-small.png" style="margin:0 1em 2em 0;float:left;"><img id="adb-campaign-hide" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZlcnNpb249IjEuMSIgaGVpZ2h0PSIyMCIgd2lkdGg9IjIwIj48bGluZSB4MT0iMSIgeTE9IjEiIHgyPSIxOSIgeTI9IjE5IiBzdHlsZT0ic3Ryb2tlOiNmZmY7c3Ryb2tlLXdpZHRoOjIiIC8+PGxpbmUgeDE9IjE5IiB5MT0iMSIgeDI9IjEiIHkyPSIxOSIgc3R5bGU9InN0cm9rZTojZmZmO3N0cm9rZS13aWR0aDoyIiAvPjwvc3ZnPg==" alt="zavřít" style="cursor:pointer;float:right;vertical-align:top;margin:1em 0 3.5em 1em;" height="20" width="20">Váš prohlížeč blokuje reklamu. Příjmy z ní nám umožňují nabízet obsah zdarma. Podpořte nás a nástroj pro blokování na Aktuálně.cz vypněte. Děkujeme.<br><a href="http://www.aktualne.cz/podporte-nas-a-nepouzivejte-na-aktualnecz-nastroje-pro-bloko/r~f4a51fb4474911e6a77e002590604f2e/" style="padding:0.5em 1em;display:inline-block;color:inherit;text-decoration:none;text-transform:uppercase;border:1px solid white;border-radius:3px;font-size:80%;margin-top:1em;">Více informací</a></div></div>

Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add this filter
@@|http://i0.cz/*.js|

**Comment by X01X012013** [comment]
Or we can define the variable ourselves: 
`unsafeWindow.adb_campaign = { test_pass: true };`

**Comment by reek** [comment]
not detected, probably fixed by easylist
