### ISSUE TITLE
mid-day.com

### ISSUE THREAD

**Issue by NaveenBoggarapu** [reek/anti-adblock-killer#1801]
http://www.mid-day.com/articles/turkey-purges-15200-education-workers-over-failed-coup/17453151

**Comment by mapx-** [comment]
add this filter
@@||www.mid-day.com$script,domain=mid-day.com

**Comment by X01X012013** [comment]
`unsafeWindow.canRun = true;`

**Comment by reek** [comment]
@mapx- 
@X01X012013 
thanks for rules
