### ISSUE TITLE
root.cz

### ISSUE THREAD

**Issue by shaarkys** [reek/anti-adblock-killer#1802]
http://www.root.cz/clanky/prace-s-rastrovymi-obrazky-v-knihovne-openvg/

http://imgur.com/a/pzVmS

Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

> <div class="adblock-message__content"> <h2 class="adblock-message__header"> <span class="adblock-message__icon--sad adblock-message__icon"> <svg class="svg-icon__content" width="22.469" height="22" viewBox="0 0 22.469 22" xmlns="http://www.w3.org/2000/svg"> <defs> <style> .svg-icon-class--fill-rule--evenodd { fill-rule: evenodd; } </style> </defs> <path id="icon_emoticon_sad" class="svg-icon-class--fill-rule--evenodd" d="M747.773,1105A11,11,0,1,0,759,1116,11.125,11.125,0,0,0,747.773,1105Zm0,20.52A9.527,9.527,0,1,1,757.5,1116,9.633,9.633,0,0,1,747.773,1125.52Zm0-8.85a5.856,5.856,0,0,0-5.489,3.69,0.724,0.724,0,0,0,.429.95,0.755,0.755,0,0,0,.974-0.42,4.417,4.417,0,0,1,8.172,0,0.755,0.755,0,0,0,.7.47,0.652,0.652,0,0,0,.272-0.05,0.725,0.725,0,0,0,.429-0.95A5.856,5.856,0,0,0,747.773,1116.67Zm-3.763-1.41a1.905,1.905,0,1,0-1.945-1.9A1.922,1.922,0,0,0,744.01,1115.26Zm7.526-3.81a1.905,1.905,0,1,0,1.945,1.91A1.924,1.924,0,0,0,751.536,1111.45Z" transform="translate(-736.531 -1105)"></path> </svg> </span> Že vy si v prohlížeči blokujete reklamy? </h2> <ul class="adblock-message__feedback"> <li class="adblock-message__feedback__item"> <p class="adblock-message__link-wrap--left adblock-message__link-wrap"><strong>Vypněte prosím AdBlock</strong> alespoň při brouzdání na Root.cz. Bez příjmů z reklam to neutáhneme.</p> <p class="adblock-message__link-wrap--center adblock-message__link-wrap"> <a class="adblock-message__link" href="/redakce/proc-neblokovat-reklamu/"> <span class="adblock-message__icon--happy adblock-message__icon"> <svg class="svg-icon__content" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="22.4px" height="22px" viewBox="0 0 22.4 22" style="enable-background:new 0 0 22.4 22;" xml:space="preserve"> <g id="icon_emoticon_happy"> <path d="M11.2,0C5.2,0.1,0.3,5.2,0.5,11.2S5.6,22.1,11.7,22c6-0.1,10.8-5,10.8-11C22.4,4.9,17.4-0.1,11.2,0z M11.2,20.5c-5.3-0.1-9.4-4.5-9.3-9.7C2,5.5,6.4,1.4,11.6,1.5c5.2,0.1,9.3,4.3,9.3,9.5C20.9,16.3,16.5,20.6,11.2,20.5z"></path> <path d="M7.5,10.3C7.5,10.3,7.5,10.3,7.5,10.3L7.5,10.3c1.1,0,1.9-0.9,1.9-1.9S8.4,6.4,7.4,6.5c0,0,0,0,0,0 c0,0,0,0,0,0c-1,0-1.9,0.9-1.9,1.9C5.5,9.4,6.4,10.3,7.5,10.3z"></path> <path d="M15,6.4C15,6.4,15,6.4,15,6.4c-1.1,0-1.9,0.9-1.9,1.9c0,1.1,0.9,1.9,1.9,1.9c1,0,1.9-0.9,1.9-1.9 C16.9,7.3,16.1,6.4,15,6.4z"></path> <path d="M16.3,12.5C16.3,12.5,16.3,12.5,16.3,12.5L16.3,12.5c-0.4-0.2-0.8,0-1,0.4c-0.9,2.3-3.5,3.3-5.7,2.4 c-1.1-0.4-2-1.3-2.4-2.4c-0.2-0.4-0.6-0.6-1-0.4c-0.4,0.1-0.6,0.6-0.4,1c0,0,0,0,0,0c1.2,3,4.7,4.5,7.7,3.2 c1.5-0.6,2.6-1.8,3.2-3.2C16.9,13,16.7,12.6,16.3,12.5z"></path> </g> </svg> </span> <span class="adblock-message__link__content">Jak a proč vypnout AdBlock</span> </a> </p> </li> <li class="adblock-message__feedback__item"> <p class="adblock-message__link-wrap--left adblock-message__link-wrap">A nebo nás podpořte! <strong>Reklamy vám z Root.cz zmizí</strong>, dostanete e‑book zdarma a můžeme zajít i na pivo.</p> <p class="adblock-message__link-wrap--center adblock-message__link-wrap"> <a class="adblock-message__link" href="/podporte/"> <span class="adblock-message__icon--happy adblock-message__icon"> <svg class="svg-icon__content" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="22.4px" height="22px" viewBox="0 0 22.4 22" style="enable-background:new 0 0 22.4 22;" xml:space="preserve"> <g id="icon_emoticon_happy"> <path d="M11.2,0C5.2,0.1,0.3,5.2,0.5,11.2S5.6,22.1,11.7,22c6-0.1,10.8-5,10.8-11C22.4,4.9,17.4-0.1,11.2,0z M11.2,20.5c-5.3-0.1-9.4-4.5-9.3-9.7C2,5.5,6.4,1.4,11.6,1.5c5.2,0.1,9.3,4.3,9.3,9.5C20.9,16.3,16.5,20.6,11.2,20.5z"></path> <path d="M7.5,10.3C7.5,10.3,7.5,10.3,7.5,10.3L7.5,10.3c1.1,0,1.9-0.9,1.9-1.9S8.4,6.4,7.4,6.5c0,0,0,0,0,0 c0,0,0,0,0,0c-1,0-1.9,0.9-1.9,1.9C5.5,9.4,6.4,10.3,7.5,10.3z"></path> <path d="M15,6.4C15,6.4,15,6.4,15,6.4c-1.1,0-1.9,0.9-1.9,1.9c0,1.1,0.9,1.9,1.9,1.9c1,0,1.9-0.9,1.9-1.9 C16.9,7.3,16.1,6.4,15,6.4z"></path> <path d="M16.3,12.5C16.3,12.5,16.3,12.5,16.3,12.5L16.3,12.5c-0.4-0.2-0.8,0-1,0.4c-0.9,2.3-3.5,3.3-5.7,2.4 c-1.1-0.4-2-1.3-2.4-2.4c-0.2-0.4-0.6-0.6-1-0.4c-0.4,0.1-0.6,0.6-0.4,1c0,0,0,0,0,0c1.2,3,4.7,4.5,7.7,3.2 c1.5-0.6,2.6-1.8,3.2-3.2C16.9,13,16.7,12.6,16.3,12.5z"></path> </g> </svg> </span> <span class="adblock-message__link__content">Chci se stát podporovatelem</span> </a> </p> </li> </ul> <a class="adblock-message__close" href="/?do=adblockMessage-close"> <span class="adblock-message__icon--close adblock-message__icon"> <svg class="svg-icon__content" width="22.1px" height="22.1px" viewBox="0 0 22.1 22.1" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet"> <path d="M21.8,0.3c-0.4-0.4-1.2-0.4-1.6,0l-9.1,9.1L2,0.3c-0.4-0.4-1.2-0.4-1.6,0s-0.4,1.2,0,1.6l9.1,9.1l-9.1,9.1 c-0.4,0.4-0.4,1.2,0,1.6c0.2,0.2,0.5,0.3,0.8,0.3S1.7,22,2,21.8l9.1-9.1l9.1,9.1c0.2,0.2,0.5,0.3,0.8,0.3s0.6-0.1,0.8-0.3 c0.4-0.4,0.4-1.2,0-1.6l-9.1-9.1L21.8,2C22.2,1.5,22.2,0.8,21.8,0.3z"></path> </svg> </span> <span class="element-blind-user">Zavřít</span> </a> </div>

**Comment by X01X012013** [comment]
This website works fine for me, are you sure you properly installed Aak Script? 
![screenshot](http://i.imgur.com/SPFPlyz.png)

**Comment by mapx-** [comment]
add 
``
@@||root.cz^$generichide
root.cz##.adLeaderboard
``

However, you are using the specific list EasyList Czech and Slovak + Easylist. 
You should report directly at http://adblock.sk/forum

**Comment by shaarkys** [comment]
Thank you, however the Anti-Adblock banner is showing up randomly, that's why I included also the code and screenshot. Btw, should it be really reported to http://adblock.sk/forum when it is report of "anti-adblock" measures ? Sorry if I misunderstood it then.

**Comment by mapx-** [comment]
sure, you can report it at their forum.

**Comment by reek** [comment]
@shaarkys 
Killed for me by AakScript
