### ISSUE TITLE
Dailymotion.com

### ISSUE THREAD

**Issue by gZaVia** [reek/anti-adblock-killer#1803]
New ad-block detection from dailymotion with a message:
(in French): 
"Oups! Il semblerait que quelque chose bloque ce contenu. Assurez-vous que votre connexion fonctionne, et essayez de désactiver vos bloqueurs de publicité."

(English translation):
"Oops! It seems that something is blocking that content. Make sure your connection is working and try disabling your ad blockers."

Many videos involved, here's one:

http://www.dailymotion.com/video/x4jty8p_jean-luc-melenchon-a-cuba-le-front-de-mer-pour-changer-du-front-de-gauche-le-billet-de-charline_fun

Using:
Adblock Plus 1.12.1 with AakList 
Anti-Adblock Killer | Reekv9.8
Tampermonkey 4.0.69

**Comment by X01X012013** [comment]
Sorry, I am not getting any block screen, can you provide a screenshot and steps to make the block screen show? 
![screenshot](http://i.imgur.com/hIO5ly4.png)

**Comment by gZaVia** [comment]
Step is just click on the vid.
Here is the snapshot :
![capture d ecran 2016-07-21 a 17 43 06](https://cloud.githubusercontent.com/assets/20580964/17029233/bf91d6c2-4f6a-11e6-80ed-434aef930e33.png)

I believe the block is within this script element:
<script>
        function onEndScreenAction(event)
        {
            var videoId = (event.detail.videoId !== undefined ? event.detail.videoId : event.detail.id);
            window.location.href = '/video/' + videoId;
        }
        function onReportIssueRequested(event)
        {
            var config  = event.detail.config === undefined ? {} : event.detail.config;
            var techno  = event.detail.techno === undefined ? 'html5' : event.detail.techno;
            var videoId = (event.detail.videoId !== undefined ? event.detail.videoId : event.detail.id);

            DM_WidgetV3.get
            (
                '/pageitem/player/report?id=' + videoId,
                'popup',
                DM_Request.getRequestURI(),
                { techno: techno, config: JSON.stringify(config) },
                null,
                'POST'
            );
        }

        try
        {
            if (!window.playerV5)
            {
                var buildPlayer = function (PV5config)
                {
                    window.playerV5 = dmp.create(document.getElementById('player'), PV5config);
                    window.playerV5.addEventListener('endScreenAction', onEndScreenAction);
                    window.playerV5.addEventListener('apiready', function()
                    {
                        return typeof onPlayerV5Ready == 'function' ?
                            onPlayerV5Ready('player')
                            : false;
                    });
                    window.playerV5.addEventListener('reportIssueRequested', onReportIssueRequested);

                    // dispatch event for embed used on dailymotion.com
                    if (location.host.match(/dailymotion.com/) && location.search.replace('?', '').split('&').indexOf('enableApi=1') !== -1)
                    {
                        DM_DispatchEvent.dispatch(parent, 'dm_pv5_embed_ready', { player: window.playerV5 });
                    }
                };

                                    buildPlayer({"context":{"admin":false,"as_number":"AS3215","client_embedder":"","client_type":"website","cookie_root_domain":".dailymotion.com","cookie_setter_template_url":"http:\/\/www.dailymotion.com\/cookie\/:cookieName?value=:cookieValue","country":"FR","dependencies":{"flash":{"estat":"\/\/static1.dmcdn.net\/playerv5\/estat.35aad99f69.swf","player":"\/\/static1.dmcdn.net\/playerv5\/dmp.8f0878ec5e.swf","sdk_liverail":"http:\/\/vox-static.liverail.com\/swf\/v4\/admanager.swf","xiti":"\/\/static1.dmcdn.net\/playerv5\/xiti.3b66c41e30.swf"},"html":{"hapyak":"\/\/hapyak.dmcdn.net\/js\/hapyak.js","sdk_liverail":"http:\/\/cdn-static.liverail.com\/js\/LiveRail.AdManager-1.0.js"}},"device":{"type":"tablet","ua_family":"Safari mobile","ua_name":"Safari mobile 9.0","os_family":"iOS","os_name":"iOS 9"},"dmvk":"5790c352b443c","ed_endpoint":"http:\/\/pebed.dm.gg","embedder":"http:\/\/www.dailymotion.com\/video\/x4jty8p_jean-luc-melenchon-a-cuba-le-front-de-mer-pour-changer-du-front-de-gauche-le-billet-de-charline_fun","env":"prod","features":{},"gatekeepers":["PV5_AD_PAUSE","PV5_ANTI_ADBLOCK","PV5_EVENT_BUS_STREAMING","PV5_EVENT_BUS_STREAMING_HTML5","PV5_HTML5_FIRST","PV5_MIDROLLS_DESKTOP","PV5_MIDROLLS_MOBILE","PV5_MSE_CHROME_ANDROID5","PV5_MSE_CHROME_DESKTOP","PV5_MSE_EDGE_DESKTOP","PV5_MSE_FIREFOX_DESKTOP","PV5_MSE_HLS","PV5_MSE_IE_DESKTOP","PV5_VR_360"],"http_x_requested_with":"","integration":"inline","locale":"fr","metadata_template_url":"http:\/\/www.dailymotion.com\/player\/metadata\/video\/:videoId?embedder=http%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx4jty8p_jean-luc-melenchon-a-cuba-le-front-de-mer-pour-changer-du-front-de-gauche-le-billet-de-charline_fun&integration=inline","onsite":true,"pinba_url":"http:\/\/tofu.dmcdn.net\/track\/","player_version":"v-0.0.645-rc1","reader_has_history":true,"reader_id":null,"referer":"http:\/\/www.dailymotion.com\/fr","report_issue_url":"http:\/\/www.dailymotion.com\/pageitem\/player\/report?popup=1","s_server_time":"17:57-Thursday","secure":false,"translations":{"accessibility":{"Advertisement":"Publicit\u00e9","Advertisement: %time% remaining":"Publicit\u00e9 : %time% restant","Cast to your TV":"Envoyer vers votre t\u00e9l\u00e9vision","Chromecast remote status":"Statut de la Chromecast","Close":"Fermer","Close the share panel":"Fermer le panneau de partage","Control video playback":"G\u00e9rer la lecture vid\u00e9o","Dailymotion partner watermark":"Logo partenaire Dailymotion","Enter fullscreen":"Passer en mode plein \u00e9cran","Exit fullscreen":"Quitter mode plein-\u00e9cran","Fewer controls":"Moins de param\u00e8tres","Get embed code":"Obtenir le code d'int\u00e9gration","Increase size":"Agrandir","Live video":"Vid\u00e9o en direct","Live video: %count% viewers":"Vid\u00e9o en direct : %count% spectateurs","More controls":"Plus de param\u00e8tres","Pause video":"Mettre la vid\u00e9o en pause","Play":"Regarder","Play %title% on %device%":"Lire %title% sur %device%","Play video":"Regarder la vid\u00e9o","Primary control bar":"Barre de contr\u00f4le principale","Reduce size":"R\u00e9duire","Replay video":"Regarder la vid\u00e9o \u00e0 nouveau","Report playback issue":"Signaler un probl\u00e8me","Seek bar":"Barre de navigation","Share":"Partager","Share on %service%":"Partager sur %service%","Share panel":"Panneau de partage","Skip to video":"Passer la publicit\u00e9","Stop video":"Arr\u00eater la lecture","The current highlight\/theme colour combination on the video player might create accessibility problems.\\nSee: http:\/\/leaverou.github.io\/contrast-ratio\/%highlight%-on-%background%":"The current highlight\/theme colour combination on the video player might create accessibility problems.\\nSee: http:\/\/leaverou.github.io\/contrast-ratio\/%highlight%-on-%background%","Time elapsed \/ Video duration":"Temps pass\u00e9 \/ Dur\u00e9e de la vid\u00e9o","Time elapsed: %time%":"Temps pass\u00e9 : %time%","Toggle the quality menu":"S\u00e9lectionner le menu des qualit\u00e9s","Toggle the speed menu":"S\u00e9lectionner le menu vitesse ","Toggle the subtitles menu":"S\u00e9lectionner le menu des sous-titres","Utility dock":"Utilitaires","Video duration: %duration%":"Dur\u00e9e de la vid\u00e9o : %duration%","Video owner: %owner%":"Cha\u00eene : %owner%","Video shortlink":"Permalien de la vid\u00e9o","Video title: %title%":"Titre de la vid\u00e9o : %title%","Volume":"Volume","Watch %title%":"Regarder %title%","Watch later":"Regarder plus tard","Watch on Dailymotion.com":"Regarder sur dailymotion.com"},"ads":{"Advertisement":"Publicit\u00e9","Advertisement: {COUNTDOWN} seconds":"Publicit\u00e9 : {COUNTDOWN} secondes","Skip in %time%":"Passer la publicit\u00e9 dans %time%","Skip in {COUNTDOWN} seconds":"Passer la publicit\u00e9 dans {COUNTDOWN} secondes","Skip to video":"Passer la publicit\u00e9"},"badge":{"%count% viewers":"%count% spectateurs","Live":"En direct"},"chromecast":{"Another video is playing on %device%":"Une autre vid\u00e9o est d\u00e9j\u00e0 en cours de lecture sur %device%","Connecting to %device%":"Connexion en cours sur %device%","Paused on %device%":"En pause sur %device%","Play now":"Lire la vid\u00e9o","Playing on %device%":"Lecture en cours sur %device%","Replay ? %device%":"Replay ? %device%"},"default":{"%hours% hours, %minutes% minutes, %seconds% seconds":"%hours% heures, %minutes% minutes, %seconds% secondes","%hours% hours, %seconds% seconds":"%hours% heures, %seconds% secondes","%hours%h %minutes%m %seconds%s":"%hours%h %minutes%m %seconds%s","%hours%h %seconds%s":"%hours%h %seconds%s","%minutes% minutes, %seconds% seconds":"%minutes% minutes, %seconds% secondes","%minutes%m %seconds%s":"%minutes%m. %seconds%s","%seconds% seconds":"%seconds% secondes","%seconds%s":"%seconds%s","360&deg; video":"vid\u00e9o \u00e0 360&deg;","Click and drag":"Cliquez et faites glisser","Tap and slide":"Appuyez et faites glisser","Tilt and rotate":"Inclinez et faites tourner","Unsupported browser, <a href='%url%' target='_blank'>learn more<\/a>":""},"endscreen":{"Cancel autoplay":"Cancel autoplay","Next video:":"Prochaine vid\u00e9o :","Related videos":"Vid\u00e9os recommand\u00e9es","Replay":"Revoir","by %owner%":"par %owner%"},"error":{"An unexpected error has occured.":"Une erreur inattendue est survenue.","Bang!":"Bang !","Blop!":"Blop !","Calling `%method%` method right after `apiready` is not recommended.\\n":"","Calling `%method%` method right after `apiready` is not recommended.\\nAre you sure you don't want to use the `%parameter%` parameter instead?\\nSee: https:\/\/developer.dailymotion.com\/player#player-parameters":"","Looks like something is blocking this content.<br>Make sure your connection is working and try disabling any ad blockers.":"Il semblerait que quelque chose bloque ce contenu. <br> Assurez-vous que votre connexion fonctionne et essayez de d\u00e9sactiver vos bloqueurs de publicit\u00e9.","Looks like we can't play this video in this browser.":"Il semblerait que cette vid\u00e9o ne puisse pas \u00eatre lue dans ce navigateur. ","Oh no!":"Mince alors !","Oops!":"Oups","Password-protected videos aren't supported in this browser.":"Les vid\u00e9os prot\u00e9g\u00e9es par un mot de passe ne sont pas compatibles avec ce navigateur.","Please update your browser or try a different one.":"Merci de mettre \u00e0 jour votre navigateur ou d'en essayer un autre.","Sorry!":"D\u00e9sol\u00e9 !","Whack!":"Argh !","Whoops!":"Oups ! ","You need Adobe Flash to watch this video in this browser. You can download it from <a target=\"_blank\" href=\"https:\/\/get.adobe.com\/flashplayer\/\">adobe.com<\/a>.":"You need Adobe Flash to watch this video in this browser. You can download it from <a target=\"_blank\" href=\"https:\/\/get.adobe.com\/flashplayer\/\">adobe.com<\/a>.","You need to upgrade your Adobe Flash Player to watch this video. You can download it from <a target=\"_blank\" href=\"https:\/\/get.adobe.com\/flashplayer\/\">adobe.com<\/a>.":"You need to upgrade your Adobe Flash Player …</script>

**Comment by gZaVia** [comment]
Appears to be related to Chrome.
I just tried Safari, in which a page reload removes the ad.

**Comment by reek** [comment]
I have no message

**Comment by gZaVia** [comment]
No longer since script 9.9
