### ISSUE TITLE
Doesnt work here http://economictimes.indiatimes.com/

### ISSUE THREAD

**Issue by goldsmit409** [reek/anti-adblock-killer#1806]
It does not work on any articles like http://economictimes.indiatimes.com/markets/stocks/news/looking-for-future-thalaivas-of-dalal-street-top-analysts-bet-on-these-10-stocks/articleshow/53332788.cms

thanks

**Comment by mapx-** [comment]
add
@@||indiatimes.com/*ad$script,domain=indiatimes.com
