### ISSUE TITLE
economictimes.indiatimes.com

### ISSUE THREAD

**Issue by mskadu** [reek/anti-adblock-killer#1807]
http://economictimes.indiatimes.com/news/politics-and-nation/mps-attack-bhagwant-mann-for-posting-video-on-parliament/articleshow/53326812.cms
http://economictimes.indiatimes.com/blocked.cms
Google Chrome 51.0.2704.106 m (64-bit)
Tampermonkey v4.1
AdBlockPlus
EasyList + Adblock Warning Removal List + AakList

**Comment by mapx-** [comment]
add
@@||indiatimes.com/*ad$script,domain=indiatimes.com

**Comment by mskadu** [comment]
Looks like these guys are getting wiser at walking around AAK filters.

http://timesofindia.indiatimes.com/india/Ms-Shobhaa-De-kindly-run-on-hockey-pitch-for-60-minutes-Viren-Rasquinha-former-hockey-captain-hits-back/articleshow/53613866.cms
http://imgur.com/a/vOOOe
Google Chrome 51.0.2704.106 m (64-bit)
Tampermonkey v4.1
AdBlockPlus
EasyList + Adblock Warning Removal List + AakList

**Comment by mapx-** [comment]
the filters above still working

**Comment by mskadu** [comment]
You mean to say you cannot see the block message my screenshot shows (line #2)?

**Comment by mapx-** [comment]
yes. If you are using not only ABP, disable all other blocking extensions.

**Comment by mskadu** [comment]
Ok, I have now disabled TamperMonkey and Blur - the only two extensions I know are blocking. As my [new screenshot](http://imgur.com/a/u0g0i) will show - my result is unchanged :-1:

**Comment by mapx-** [comment]
- keep only ABP enabled, disable all other extensions, test again.
- did you add the filters above on separate rows in your custom filters ?

**Comment by mapx-** [comment]
:O you didn't add the filters above ?

**Comment by mskadu** [comment]
No, should I be?

**Comment by mapx-** [comment]
I wrote; "add ..."

It's about filters you have to add as custom ones.

**Comment by mskadu** [comment]
Yess! That seems to work. But will they not come in as a part of the AAK list? Or have they yet to do so? Also where does tampermonkey fit into all of this?

Thanks again. :+1:

**Comment by mapx-** [comment]
it's only my fix :) 

Reek probably will do his part (in AAK script or AAK list)

**Comment by mskadu** [comment]
Ohhh, the original filter was 18+ days ago. Wonder when it will make it to the actual list :8ball:

**Comment by reek** [comment]
done
