### ISSUE TITLE
backin.net

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#1809]
http://backin.net/qsj9x6hhuuch
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/17060679/65aafe74-502b-11e6-8d6d-4cdc02d1ad1d.PNG)
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by mapx-** [comment]
try these filters
```
@@||rivcash.com/en/customBanner.js.php?*$domain=backin.net
||rivnetwork.com^$domain=backin.net
```

**Comment by reek** [comment]
Ok, I'll fix it, thanks
