### ISSUE TITLE
haxoff.com

### ISSUE THREAD

**Issue by SBI-boy** [reek/anti-adblock-killer#1811]
https://haxoff.com/
http://imgur.com/kuaruam
Mozilla Firefox
Greasemonkey
uBLock origin

This blockadblock script is like cancer, hope you can find a generic solution
BTW this site has an anoying subscribe box that popups all the time if you can get rid of it, it will be appreciated too
http://imgur.com/V9XReQo
thanks
:S

**Comment by X01X012013** [comment]
BlockAdBlock seem to update right after Aak updates, there is really not much we can do other than temporary workaround. 
You can try:
`@@||haxoff.com^$generechide`
If that doesn't work, you can use my script that has the temporary workaround: disable eval().
https://x01x012013.github.io/AdBlockProtector/

**Comment by mapx-** [comment]
for the subscribe box try this filter
||haxoff.com/wp-content/plugins/elegant-subscription-popup/

I get no blockadblock crap

**Comment by X01X012013** [comment]
@mapx- The BlockAdBlock screen show after a few seconds (configurable), so you got to wait a little bit before it shows.

**Comment by mapx-** [comment]
yep, I waited for minutes (2 browsers, 2 adblockers), nothing here. I haven't accepted the notifications stuff.

**Comment by SBI-boy** [comment]
THANKS FOR THE HELP, i'll try everything you said to me
