### ISSUE TITLE
www.okgoals.com/

### ISSUE THREAD

**Issue by arkyos77** [reek/anti-adblock-killer#1812]
www.okgoals.com/
https://i.imgur.com/698fUg1.jpg
Mozilla Firefox 47.0.1
Greasemonkey
Adblock Plus
Adblock Warning Removal List + EasyList Italy + EasyList + RuAdList + AakList
- AdBlock Protector

Regards.

**Comment by X01X012013** [comment]
```
@@adsbygoogle.js$domain=okgoals.com
@@okgoals.com^$generichide
```

**Comment by arkyos77** [comment]
Thanks.

**Comment by mapx-** [comment]
it seems it's enough (I waited for 30 seconds)
@@||okgoals.com^$generichide

**Comment by reek** [comment]
fixed by easylist

**Comment by mapx-** [comment]
`@@||s3.amazonaws.com/html5player.gamezone.com/video-ad-unit.js`
