### ISSUE TITLE
likesforinsta.com

### ISSUE THREAD

**Issue by mittwz** [reek/anti-adblock-killer#1813]
http://likesforinsta.com/page/adblock
http://prntscr.com/bwfvkt
Google Chrome
Adblock
EasyList + AakList ( http://prntscr.com/bwfvvl )

**Comment by mapx-** [comment]
add this filter
@@||likesforinsta.com^$generichide

**Comment by mittwz** [comment]
How add manual filters? *-*

**Comment by mapx-** [comment]
for ABP
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

I don't know for your adblock (personalizar ?)

**Comment by mapx-** [comment]
try:
AdBlock button > Options > CUSTOMIZE tab.

**Comment by mittwz** [comment]
Yeah, its ok now ty
http://prntscr.com/bwfxy1

**Comment by reek** [comment]
I think the anti adblock script was deleted
