### ISSUE TITLE
bhaskar.com not working

### ISSUE THREAD

**Issue by ghajini** [reek/anti-adblock-killer#1815]
link=
http://bollywood.bhaskar.com/news-ht/ENT-BNE-box-office-report-kabali-first-day-collection-news-hindi-5379507-PHO.html
![screenshot 11](https://cloud.githubusercontent.com/assets/20338483/17079798/2eadc1a0-5138-11e6-8528-c3e2c568901a.png)

your browser=
opera 38.0.2220.41 

script manager= tampermonkey stable
your adblocker= adblocker plus

filter list=
adblock warning removal list
easylist
aak list(anti-adblock killer)

issue persistent on firefox and chrome

**Comment by mapx-** [comment]
add this filter
@@||bhaskar.com/*ad$script

**Comment by ghajini** [comment]
isn't there any permanent fix, like on all other sites antiadblock killer works
thanks anyway...

**Comment by mapx-** [comment]
there are no permanent fixes
however you can add directly
@@||bhaskar.com^$script

at least this trick wont be used anymore

**Comment by ghajini** [comment]
so no need of antiadblock killer and tampermonkey a/c to your script

**Comment by mapx-** [comment]
add it in ABP as custom filter

sure, reek can add it to his script, but the fix is very simple in this case

**Comment by ghajini** [comment]
ok

**Comment by applesam** [comment]
If I remember right, these are getting into Aak soon, but while waiting, you can use this: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by mapx-** [comment]
who is using an adblocker can use the filter indicated above
@@||bhaskar.com^$script

**Comment by apacheindian** [comment]
Hi, I am using these filters from Adblock website:

@@||timesofindia.indiatimes.com/toi_js_ads/ads/ve-1.cms$script
@@||indiatimes.com^$generichide
@@||hindustantimes.com^$script
@@||amarujala.com^$generichide
@@||amarujala.com/*ad$script
@@||mensxp.com^$generichide
@@||indiatimes.com/*ad$script,domain=indiatimes.com
@@||bhaskar.com/*ad$script
indiatimes.com#@#div[id^="div-gpt-ad"]
||hindustantimes.com/_js/browser-detect.min.js,BlockerScript.js
||media.mensxp.com/resources/theme_migration/js/detector.min.js?*
/browser-detect.min.js*
||hindustantimes.com/res/js/ht-script.js

**Comment by applesam** [comment]
apacheindian       your list not working with   this web                     http://bollywood.bhaskar.com/news-bf3/ENT-TV-balika-vadhu-wrap-up-party-news-hindi-5380858-PHO.html

**Comment by mapx-** [comment]
@applesam, the necessary filter is already above
@@||bhaskar.com^$script

**Comment by apacheindian** [comment]
@applesam:  I do not know why it is not working for you. Try mapx's filter.
