### ISSUE TITLE
thefreedictionary.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1818]
http://imgur.com/a/PkbPS

Google Chrome 51.0.2704.106m
Tampermonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by X01X012013** [comment]
Try: 
`thefreedictionary.com##div[style="padding:10px 10px;font-size:1.1rem"]`

**Comment by xxcriticxx** [comment]
element picker gives me this 

###w1 > .w2 > div:nth-of-type(1) > div

**Comment by X01X012013** [comment]
Hum, maybe uBlock Origin works differently.

**Comment by xxcriticxx** [comment]
both of them work

**Comment by reek** [comment]
fixed by easylist
