### ISSUE TITLE
pregen.net

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#182]
Go to pregen.net/blog/ and a dialogue window will pop up saying "Disable any AdBlock or suck Add-on/Extension! Otherwise You may face Theseforums Redirection Loop!". If the warning hasn't popped up, clicking on either HOME or the site's logo should make it pop up.

This should block it:
||pregen.net/cpsess.php

**Comment by reek** [comment]
HI,

No problem detected

**Comment by anonsubmitter** [comment]
I still get the Adblock warning. Try visiting the site again. Should I take a screenshot of it?

**Comment by reek** [comment]
Hi,

Yes take  screenshot, thanks

**Comment by anonsubmitter** [comment]
* http://pregen.net/blog/
* https://i.imgur.com/JYOUXts.png
* Firefox 35.0.1
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.8
  * Malware Domains
  * Spam404
  * EasyList
  * Fanboy's Annoyance List
  * Prebake
  * Block-EU-Cookie-Shit-List
  * Adblock Warning Removal List (disabled so that the Adblock warning will appear)
  * Anti-Adblock Killer
  * EasyPrivacy
  * Fanboy's Enchanced Tracking List
* This might be useful as well: https://forums.lanik.us/viewtopic.php?f=62&t=20932#p66783

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Fixed by EasyList Forum
