### ISSUE TITLE
watchseries-online.la

### ISSUE THREAD

**Issue by Ntweat** [reek/anti-adblock-killer#1822]
Hi
watchseries has come with a new way for ads.
It will open a new page for link you clicked and will redirect the old page to an ad. 
For this reason I cant show a screenshot. 
Example link:  http://watchseries-online.la/category/masterchef-australia
Click on a link

PS It does not redirect always. Sometimes it does not. 

Scripts: ABP + TamperMonkey

**Comment by X01X012013** [comment]
I clicked over 10 links, refreshed the page a few times, and I never saw the behavior that you described. Is there a specific link that I should click?

**Comment by Ntweat** [comment]
It happens sometimes.. Not always..
Will update screenshot where it redirects me.

**Comment by mapx-** [comment]
unfortunately ABP does not manage for now such redirect, ubo is working fine.

**Comment by X01X012013** [comment]
If I can pin down the offending function, I might be able to disable it using Userscript.

**Comment by reek** [comment]
nothing detected
