### ISSUE TITLE
fullstuff.co

### ISSUE THREAD

**Issue by MehulHardy** [reek/anti-adblock-killer#1828]
https://fullstuff.co/
![untitled](https://cloud.githubusercontent.com/assets/17978165/17208436/5c410a86-54d6-11e6-8ec3-08b83c4f5594.png)
Chrome
EasyList + AakList

**Comment by mapx-** [comment]
add this filter in your adblocker
@@||fullstuff.co^$generichide

**Comment by MehulHardy** [comment]
Thanks it worked !
