### ISSUE TITLE
Ndtv again

### ISSUE THREAD

**Issue by Y-1** [reek/anti-adblock-killer#1833]
Worked fine until today, already tried filter update:

http://www.ndtv.com/india-news/bluster-no-substitute-for-statistics-arun-jaitley-advises-rahul-gandhi-1437500?pfrom=home-lateststories

http://imgur.com/a/GDgHC

Google Chrome

Adblock

Easylist + Aaklist

**Comment by mapx-** [comment]
try these filters
```
@@||ndtv.com^$elemhide
@@||zedo.com^$script,domain=ndtv.com
```

**Comment by Y-1** [comment]
Nope, didn't work.

**Comment by X01X012013** [comment]
Hum, I am not getting any block screen: 
![screenshot](http://i.imgur.com/zDlhNlX.png)

**Comment by mapx-** [comment]
add also
@@||ads.rubiconproject.com$script,domain=ndtv.com

**Comment by Y-1** [comment]
Success! Awesome, thanks.
