### ISSUE TITLE
litv.tv

### ISSUE THREAD

**Issue by Kara-ism** [reek/anti-adblock-killer#1835]
Hello Reek,
The version 9.8 of Anti-Adblock-Killer has been detected with litv.tv at 2016/07/29,and here's the screen-shot of this occurrence.
![default](https://cloud.githubusercontent.com/assets/9511279/17237024/53e7bfe2-5580-11e6-8247-29a52f083931.PNG)
Thank you!
Opera Stable 38.0.2220.41
μblock Origin 1.7.6 with μBlock filters & EasyList ‎& Anti-Adblock Killer & Adblock Warning Removal List‎ & Fanboy’s Enhanced Tracking List‎.
‎μMatrix 0.9.3.4 with Dan Pollock’s hosts file & hpHosts’s Ad and tracking servers & Long-lived malware domains & Malware Domain List & MVPS HOSTS & Peter Lowe’s Ad server list‎.
TamperMonkey 4.1.5231

Here's the link: https://www.litv.tv/vod/drama/content.do?brc_id=root&id=VOD00049914

**Comment by mapx-** [comment]
try reporting to
http://abpchina.org/forum/

**Comment by reek** [comment]
nothing detected

**Comment by Kara-ism** [comment]
@reek The notice of it detects turns into an image like this, instead of the previous one.
![player_adblock_background 1](https://cloud.githubusercontent.com/assets/9511279/20677142/1271dffe-b5cd-11e6-8d70-80030a86ff83.jpg)
