### ISSUE TITLE
youku.com

### ISSUE THREAD

**Issue by Home-213** [reek/anti-adblock-killer#1836]
youku.com still detects adblocker (ublock on chrome), please fix

**Comment by mapx-** [comment]
no issue here for example:
http://v.youku.com/v_show/id_XMTY2MTY0NTAxMg==.html?f=23572141&from=y1.3-idx-beta-1519-23042.230727-223466.2-1

specific page where you get the anti message ? screenshot ? filter lists used in ubo ?
