### ISSUE TITLE
Please Convert This Tool To An Addon

### ISSUE THREAD

**Issue by esotericDisciple** [reek/anti-adblock-killer#184]
Seeing that greasemonkey seems to have died, with just about every userscript and the addon itself breaking Firefox, and that the successors (Scriptish, etc) have all died along with it, this tool should be converted into a standalone add-on for Firefox.

**Comment by reek** [comment]
Hi,

No, because it gave me more work because I should make an addon for each browser..

**Comment by Watilin** [comment]
@esotericDisciple
> Seeing that greasemonkey seems to have died

and

> the successors (Scriptish, etc) have all died along with it

Where do you get these assertions from?
