### ISSUE TITLE
snesfun.com

### ISSUE THREAD

**Issue by MamaLuigi9000** [reek/anti-adblock-killer#1840]
snesfun.com
https://gyazo.com/0c28105ddedb861d548a45f6004a1729
Google Chrome
Tampermonkey
uBlock Origin
AakList and Easylist

**Comment by mapx-** [comment]
I get no anti adblocking message

anyway, try adding this filter in ubo

@@||snesfun.com^$script

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
