### ISSUE TITLE
www.gogi.in

### ISSUE THREAD

**Issue by traitor123** [reek/anti-adblock-killer#1841]
http://www.gogi.in/
http://imgur.com/a/RRq2C
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add these filters in ubo
```
@@||gogi.in^$generichide
@@||oriel.io^$xmlhttprequest,domain=gogi.in
```

**Comment by traitor123** [comment]
Thanks, worked perfectly. This can be closed. :+1:

**Comment by mapx-** [comment]
you opened it, just close it :)

**Comment by reek** [comment]
done
