### ISSUE TITLE
http://www.aranzulla.it/

### ISSUE THREAD

**Issue by marcomg** [reek/anti-adblock-killer#1842]
http://www.aranzulla.it/locked-firefox.php?p=907517&fabm=file&rnd=0.01358437631878362
https://postimg.org/image/8mmphrgnb/
Mozilla Firefox
Greasemonkey
Ublock origin
EasyList + AakList

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1619#issuecomment-236294982

**Comment by NessunoIM** [comment]
Use YesScript

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
