### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by kiesa2** [reek/anti-adblock-killer#1844]
Hello i have problem adblock antikiller not updating 24 days and not working in Lithuania news sites example www.15min.lt not working.I use ublock origin and tampermoneky.Broswer google chrome latest.Why adblock anikiller script support is end?Or script creator Reek now summer holidays?

**Comment by mapx-** [comment]
add and test these filters
```
@@||15min.lt^$generichide
@@||15min.lt/js/ads
```

**Comment by kiesa2** [comment]
thanks working now 15min.lt not detecting adblock

**Comment by mapx-** [comment]
you can report lithuanian filter issues here:
https://forums.lanik.us/viewforum.php?f=101

**Comment by reek** [comment]
done
