### ISSUE TITLE
Videomega.tv

### ISSUE THREAD

**Issue by CalleHD** [reek/anti-adblock-killer#1845]
On this site by clicking on this video, it shows that you must disable your Adblocker.

Could you fix it?

**Comment by mapx-** [comment]
search first for such issues on easylist forum (fix already there since ..months) http://forums.lanik.us/
anyway, add these filters to your adblocker:
```
@@||adnostri.com^$domain=videomega.tv
@@||adv4biz.com^$domain=videomega.tv
```

**Comment by mapx-** [comment]
and put NSFW in the title, it's porn

**Comment by CalleHD** [comment]
ok

**Comment by mapx-** [comment]
ok ...what ? did you test the filters above ?

**Comment by reek** [comment]
host is down
http://www.isitdownrightnow.com/Videomega.tv.html
