### ISSUE TITLE
Ndtv.com

### ISSUE THREAD

**Issue by gotitbro** [reek/anti-adblock-killer#1846]
# Anti AdBlock Killer Reek is not working on http://www.ndtv.com/

**Source Code:** https://paste2.org/et5Hx9Ke

**Original URI:** http://www.ndtv.com/world-news/pushed-by-xi-jinping-reformed-peoples-liberation-training-hard-to-win-wars-1438231

**Screenshot:** http://i.imgur.com/ywaNXp1.png

**Extensions:** AdBlock, IDM Integration Module, Tampermonkey

**Userscripts:** Anti-Adblock Killer, AdBlock Protector

Also not working on other subdomains like: gadgets.ndtv.com
## Update

Working fine with these filters^

```
@@||ndtv.com^$elemhide
@@||zedo.com^$script,domain=ndtv.com
@@||ads.rubiconproject.com$script,domain=ndtv.com
@@||ndtv.com^$script,domain=ndtv.com
```

_^Credit to fellow EasyList member **intense**._

**Comment by Y-1** [comment]
#1833 Okay got fixed a couple of days back. However again the same problem:

http://www.ndtv.com/opinion/why-kejriwal-believes-modi-could-have-him-eliminated-1438154

http://imgur.com/a/4h4Bt

Google chrome

Tampermonkey

Aaklist+Easylist+Adblock Protector+ filters in #1833

**Comment by mapx-** [comment]
add also

@@||ndtv.com^$script,domain=ndtv.com

**Comment by Y-1** [comment]
Ok solved again, just to summarize the current manual filters which work are:

@@||ndtv.com^$elemhide
@@||zedo.com^$script,domain=ndtv.com
@@||ads.rubiconproject.com$script,domain=ndtv.com
@@||ndtv.com^$script,domain=ndtv.com

**Comment by Y-1** [comment]
Thanks to mapx.

**Comment by Ntweat** [comment]
Update this

http://X01X012013.github.io/AdBlockProtector/

**Comment by vishwassharma** [comment]
Or check this
https://github.com/reek/anti-adblock-killer/pull/1895

**Comment by reek** [comment]
done
