### ISSUE TITLE
Oddly enough I can view this page, but if I click "Here" the target page is blocked via redirect

### ISSUE THREAD

**Issue by l3eta** [reek/anti-adblock-killer#1847]
http://www.takwing.idv.hk/tech/virtual/virtual_leopard/index.html

I will not include an image as I'm too lazy to go and upload one as it seems rather pointless at a "scripting" stand point. 

I'm using Adblock Plus and NoScript (Doubt this is important but could be) on Firefox
I had just "installed" your anti-adblocker and try to see if it would work and it didn't change anything.

Other Info:

Adblock Plus Version: 2.7.3
Firefox Version: 47.0

**Comment by mapx-** [comment]
add this filter in ABP (custom filter)

@@||cpalead.com$script,domain=takwing.idv.hk

**Comment by l3eta** [comment]
Nope. Didn't do it. I assume add as in going into filter prefs -> Custom Filters -> Add Filter -> Rule as what you posted, correct?

**Comment by mapx-** [comment]
I tested the filter in 2 adblockers, 2 browsers. It's ok here.
Be sure you aren't using any other blocking addon in FF and the filter is exactly as above (@@ ...)

**Comment by mapx-** [comment]
Disable Noscript for that site.

**Comment by l3eta** [comment]
Man that favorite things though. I'll give it a try.

**Comment by l3eta** [comment]
It gave me a Javascript disabled page. https://www.cpalead.com/nojava.php?pub=71195

**Comment by l3eta** [comment]
Also it seems that it will load the site, but then all of a sudden it goes to cpalead.

**Comment by mapx-** [comment]
Did you disable NoScript ? keep only ABP.
