### ISSUE TITLE
itechpost.com

### ISSUE THREAD

**Issue by sorathia82** [reek/anti-adblock-killer#1848]
-http://www.itechpost.com/articles/23062/20160729/dragon-ball-super-news-rumors-leaked-artwork-reveals-black-gokus.htm
-http://imgur.com/OurVEEf
-Chrome
-IDM, tampermonkey, remove taboola, Adblock, Adblock plus
-Easylist+Aaklist

**Comment by mapx-** [comment]
1. keep only 1 adblocker (ABP ), remove the other 1
2. add these filters
```
@@||brassyobedientcotangent.com/ads/.adplacement=
@@||itechpost.com^$generichide
```

Anyway, such issues have to reported in easylist forum and not here:
http://forums.lanik.us/

**Comment by sorathia82** [comment]
(1) Where to add these filters ?
(2) Sorry I didnt knew, what to report where.
So what should be reported, like what kind of issues

**Comment by mapx-** [comment]
in ABP ==> how to add custom filters:
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

in easylist forum: http://forums.lanik.us/
for your future filter issues (other than anti adblocking), open a new thread,. provide page where happens, explain the steps to get the issue, eventually add a screenshot.
