### ISSUE TITLE
sport.tvp.pl

### ISSUE THREAD

**Issue by osfp** [reek/anti-adblock-killer#1849]
http://sport.tvp.pl/26343768/kapustka-potwierdza-zagram-w-leicester-city

![](http://i.imgur.com/rMCMmLn.png)

Chrome
Tempermonkey
uBlock Origin
uBlock filters + EasyList + AakList

**Comment by mapx-** [comment]
add this filter in ubo

@@||tvp.pl/*ad

**Comment by osfp** [comment]
@mapx- 
Thanks a lot.

**Comment by xxcriticxx** [comment]
already reported to polish forum 

https://github.com/MajkiIT/polish-ads-filter/issues/1148

@@||s.tvp.pl/files/tvplayer/*/advertisement.gif$image

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
