### ISSUE TITLE
mrlev12.tv

### ISSUE THREAD

**Issue by ThePierrezou** [reek/anti-adblock-killer#185]
http://mrlev12.tv/live
Firefox 35.0.1
µblock with easy list + anti-adblock killer and others lists
Thanks.

**Comment by reek** [comment]
Hi,

Screenshot please

**Comment by ThePierrezou** [comment]
I can't do it i think, the streamer need to be online for get "Please disable adblock etc"
Sorry for this but now i can't do it :(

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
