### ISSUE TITLE
blocked ad after filter enabled

### ISSUE THREAD

**Issue by shaharukhs** [reek/anti-adblock-killer#1850]
http://www.happytrips.com/blocked.cms

![screenshot 91](https://cloud.githubusercontent.com/assets/16479669/17272455/5ae13c94-56b4-11e6-93d0-a22803fc7fb3.png)

---

http://indiatoday.intoday.in/

![screenshot 92](https://cloud.githubusercontent.com/assets/16479669/17272470/a2277802-56b4-11e6-8749-a6ed7ba3e4f4.png)

![screenshot 93](https://cloud.githubusercontent.com/assets/16479669/17272484/08f34606-56b5-11e6-8bb4-c5ede5a7845f.png)

Google Chrome

Adblock

Easylist+Aaklist

**Comment by mapx-** [comment]
test these filters
```
intoday.in#@#.right-ad
@@||happytrips.com^$script
```

**Comment by mapx-** [comment]
now add
`@@||intoday.in/*ad$script`

**Comment by shaharukhs** [comment]
not working

This is how my filter
![untitled](https://cloud.githubusercontent.com/assets/16479669/17649384/f78b6ecc-6251-11e6-945a-ea50818916ad.png)

**Comment by mapx-** [comment]
add
```
intoday.in#@#a[href*=".zedo.com/"]
intoday.in#@#.right-ad
@@||zedo.com^$image,domain=intoday.in
```

**Comment by shaharukhs** [comment]
Still No Luck

![screenshot 2016-08-18 12 01 34](https://cloud.githubusercontent.com/assets/16479669/17764221/a2c83e78-653b-11e6-9698-5a8decf5d4d4.png)
![screenshot 2016-08-18 12 01 56](https://cloud.githubusercontent.com/assets/16479669/17764222/a386db58-653b-11e6-8370-e97dc284145d.png)

**Comment by mapx-** [comment]
they already changed, add also:
`@@||media2.intoday.in/indiatoday$script`

**Comment by reek** [comment]
done
