### ISSUE TITLE
vipleague.se

### ISSUE THREAD

**Issue by Sally0808** [reek/anti-adblock-killer#1851]
The anti adblocker no longer works on vipleague.se. Was hoping for another work around.

**Comment by Sally0808** [comment]
http://i.imgur.com/0zmkALq.png

**Comment by mapx-** [comment]
Did you see anti adblocking merssages ? I see only some ads not blocked

**Comment by mapx-** [comment]
for the ads add these filters in your adblocker:
vipleague.me##[class^="vip_"]
vipleague.se##[class^="vip_"]

**Comment by reek** [comment]
you must report ads to easylist
