### ISSUE TITLE
swagbucks.com

### ISSUE THREAD

**Issue by MamaLuigi9000** [reek/anti-adblock-killer#1852]
swagbucks.com
https://gyazo.com/f6270b2802c6c037479dbba3448e4384
Google Chrome
Tampermonkey
uBlock Origin
AakList and Easylist

**Comment by mapx-** [comment]
Does not happen on the main page without logging in. Provide test account.

**Comment by MamaLuigi9000** [comment]
Nevermind I just put this and it stopped the message from popping up.
`@@||swagbucks.com^script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
