### ISSUE TITLE
linkdrop.net

### ISSUE THREAD

**Issue by Thatanos** [reek/anti-adblock-killer#1853]
i was using soulreaperzone.com to download some anime...
it uses linkdrop.net as url shortener
Then this message appeared...
![untitle2](https://cloud.githubusercontent.com/assets/20753695/17276642/835922ec-5761-11e6-8c69-4118df4375e6.png)

**Comment by mapx-** [comment]
add (and test) this filter in your adblocker
@@*$image,domain=linkdrop.net

**Comment by Thatanos** [comment]
tested and it doesn't work... :(

**Comment by Thatanos** [comment]
I just found a temporary solution...
I just need to open another tab and wait for 5 seconds and quickly click the skip ads button...
Anyways hope it'll be fixed soon...

**Comment by mapx-** [comment]
You are using a lot of blocking extensions:

keep only ABP with the filters above, dosable / remove the others (avira, adblock)

**Comment by Thatanos** [comment]
still doesn't work though...

**Comment by Thatanos** [comment]
I've disable the other extensions and keep tampermonkey... it still show the same result...
but I found this site by clicking the instaling your anti-adblocker word... http://blockadblock.com/
it seems this site also detect my adblocker

**Comment by mapx-** [comment]
for blockadblock
https://github.com/reek/anti-adblock-killer/issues/1799#issuecomment-234210055

**Comment by Thatanos** [comment]
I tried to put it in my filter but it say unknown genericfilter...
how do I solve this

**Comment by mapx-** [comment]
in ABP ? what version ? what chrome version ?

**Comment by Thatanos** [comment]
i think I used an old ver... im gonna update it...
ABP: 1.8.12
Chrome: 51.0.2704.103

**Comment by mapx-** [comment]
indeed. The current one is 1.12.1

**Comment by mapx-** [comment]
This is the reason $generichide was not recognized for linkdrop (filter already in easylist)

**Comment by Thatanos** [comment]
Thanks... it works now...
