### ISSUE TITLE
http://www.aranzulla.it/

### ISSUE THREAD

**Issue by DjDiabolik** [reek/anti-adblock-killer#1856]
It's possible to add this site ?

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=96902#p96902

**Comment by mapx-** [comment]
simple solution: disable javascript in your browser ==> you'll be able to read aranzulla pages.

**Comment by DjDiabolik** [comment]
Yeah.... but so many site use Javascript........... it's possible to disable this only for this host ?

**Comment by mapx-** [comment]
sure you can.

for example in chrome, go to:
chrome://settings/contentExceptions#javascript

and add an entry for aranzulla with "block"

**Comment by mapx-** [comment]
in firefox use YesScript or NoScript 

https://addons.mozilla.org/firefox/addon/yesscript/
https://addons.mozilla.org/en-US/firefox/addon/noscript/

**Comment by DjDiabolik** [comment]
Yeah... great suggestion... i thinks i can try after........

**Comment by DjDiabolik** [comment]
mmmm... read about noscript. It's allow script only for site i trust. It's no the best... i need the exact reverse feature.. block script only for site i choose :)

**Comment by mapx-** [comment]
"NoScript allows blacklisting. Just select "Allow script globally (dangerous)", then use "Forbid ..."

**Comment by DjDiabolik** [comment]
mmmmmmmmm... ok. I stay to try to found an alternative for moment because i know only this site apply this feature.......

**Comment by DjDiabolik** [comment]
Look... same suggestion on official forum of firefox:
https://support.mozilla.org/it/questions/954712

https://support.mozilla.org/it/questions/777033

**Comment by mapx-** [comment]
see also
https://addons.mozilla.org/en-US/firefox/addon/toggle-js/

**Comment by DjDiabolik** [comment]
mmmmmmmmm... i have installed yesscript for the moment it's best solution.....

**Comment by DjDiabolik** [comment]
I also partecipad on easyscript official forum.... if it's fixable i can uninstall this addons.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
