### ISSUE TITLE
http://www.ndtv.com/world-news/give-them-a-bloody-nose-xi-pressed-for-stronger-south-china-sea-response-1438652?pfrom=home-topstories

### ISSUE THREAD

**Issue by shailee2807** [reek/anti-adblock-killer#1857]

**Comment by X01X012013** [comment]
This site is covered in my script: 
https://x01x012013.github.io/AdBlockProtector/
You can use it until Aak updates.

`setReadOnly("getNoTopLatestNews", function () { });`

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1846#issuecomment-236380957
