### ISSUE TITLE
independent.co.uk

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#1858]
http://www.independent.co.uk/life-style/gadgets-and-tech/gaming/pokemon-go-update-apk-ios-latest-new-features-footstep-counter-avatar-safety-warnings-0-31-0-what-a7164931.html

Pop-up appears, with text:
"We've noticed that you are using an ad blocker."

**Comment by mapx-** [comment]
add 

independent.co.uk##.adblock-modal.adblock

**Comment by callmenemo491** [comment]
looks to be ok...

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
