### ISSUE TITLE
al.ly

### ISSUE THREAD

**Issue by BioBrayan** [reek/anti-adblock-killer#1859]
Google Chrome 52.0.2743.82 m
Adguard for Windows 6.1.249.1233 Beta
——————————————————
English Filter v1.0.90.43
German Filter v1.0.26.66
Spanish/Portuguese Filter v1.0.86.28
EasyList Italy Filter v1.0.62.72
Wiltteri Filter v1.0.1.69
Polski filter v1.0.4.41
——————————————————
Tampermonkey v4.1
AdsBypasser 5.57.0
Anti-Adblock Killer 9.8
AntiAdware 1.41.1
——————————————————
http://al.ly/2bPo4
http://fs5.directupload.net/images/160801/9eea2gsi.png

Delen fin a este script malicioso gracias

**Comment by Eva850** [comment]
This site uses blockadblock, try this rule, it works for me.
@@||al.ly^$generichide

**Comment by reek** [comment]
done
