### ISSUE TITLE
happy-hack.ru

### ISSUE THREAD

**Issue by SilentWarrior1** [reek/anti-adblock-killer#1860]
problem site: http://happy-hack.ru
-http://imgur.com/a/94bLq
-Pale Moon (26.2.2)
-Greasemonkey
-Adblock Latitude
-RuAdlist+EasyList

**Comment by mapx-** [comment]
add this filter in your adblocker

@@||7-link.ru/2/poprotator.js$domain=happy-hack.ru

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
