### ISSUE TITLE
pcbolsa.com

### ISSUE THREAD

**Issue by Julian1984** [reek/anti-adblock-killer#1861]
Hi!
URL: www.pcbolsa.com

Google Chrome
Tampermonkey
uBlock Origin
AakList and Easylist

All latest versions.
Thanks.

**Comment by mapx-** [comment]
add this filter in ubo
@@||pcbolsa.com/*ad$script

**Comment by Julian1984** [comment]
Added and working. 

Thanks! Close the issue if you want.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
