### ISSUE TITLE
lg-firmware-rom.com

### ISSUE THREAD

**Issue by ThisIsEasss** [reek/anti-adblock-killer#1862]
http://lg-firmware-rom.com/download/lg-d325-lgflashtool_1-8-and-lgd325_20140311_lgflashv160-dll/
http://imgur.com/a/4sY0f

Mozilla Firefox 47.0.1
Greasemonkey
AdBlockPlus
Ad filtering: ABPindo + EasyList + AakList

**Comment by mapx-** [comment]
add this filter in ABP

@@||jb51.net/*ad$script,domain=lg-firmware-rom.com

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
