### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by manguszta** [reek/anti-adblock-killer#1867]
http://www.investing.com/currencies/usd-huf
http://imgur.com/a/mOnrr
Google Chrome
Tampermonkey
AdBlock
AakList

**Comment by manguszta** [comment]
exact same thing with:
Google Chrome
Tampermonkey
AdBlock Plus
AakList + EasyList

**Comment by mapx-** [comment]
does it happen only logged in ?

try these filters:

```
@@||investing.com^$generichide
@@||static.doubleclick.net/instream/ad_status.js
```

if still happens, keep only ABP enabled, see the indications here:
https://adblockplus.org/forum/viewtopic.php?f=10&t=43791

select only the blocked items then post the screenshot with these ones

**Comment by manguszta** [comment]
Thx for the quick respond!
I don't use this site with an account, only as a visitor.
AdBlock manages to hide that main Anti-AdBlock popup, AdBlock Plus cannot. (I tried the filters in both)
I had to manually block that darker mask ("generalOverlay.displayNone.darker"). Plus, I cannot scroll the page, still. The strangest thing: anti-adblock popup keeps on popping up WITHOUT using AdBlock and/or AdBlock Plus.

AdBlock: http://imgur.com/a/YYob4
AdBlock Plus: http://imgur.com/a/JHH92

**Comment by mapx-** [comment]
Did you disable all other extensions ? keep only ABP enabled.
I can't reproduce the issue using only easylist + aak list (even without the custom filters above)

**Comment by manguszta** [comment]
Okay, it works now. After turning off "Disconnect" addon. I've never considered it as an adblocker.
I think I should make an exception in Disconnect addon.

**Comment by mapx-** [comment]
it's completely useless disconnect (and ghostery too), you can do the same things using easyprivacy list.

**Comment by manguszta** [comment]
thanks for the tip!
