### ISSUE TITLE
itv.com

### ISSUE THREAD

**Issue by derpenxyne** [reek/anti-adblock-killer#1868]
http://www.itv.com/hub/coronation-street/1a0694a8959

![capture](https://cloud.githubusercontent.com/assets/2372654/17349447/b8327828-5915-11e6-9793-e783756270fe.PNG)

Chrome
uBlock Origin
uBlock filters + EasyList + Peter Lowe’s Ad server list‎

**Comment by derpenxyne** [comment]
Apologies for my ignorance, but what logger are you referring to?

**Comment by mapx-** [comment]
while on itv page, click ubo icon, to the right of "on this page" you'll see t icons: the first is the picker, the second "open the logger"

then refresh itv page and all the page requests will be saved in that logger

**Comment by derpenxyne** [comment]
Ah - neat! Here you go:
http://pastebin.com/FW3AWFE5

**Comment by mapx-** [comment]
Did you post on pastebin all the pages in logger ?

**Comment by mapx-** [comment]
add this filter in ubo, test it:

`@@||tom.itv.com/itv/count/$object,domain=itv.com`

**Comment by derpenxyne** [comment]
Yes that's all the log showed, only 1 page -- still shows the message unfortunately!

**Comment by mapx-** [comment]
with the filter above I get no message.

**Comment by derpenxyne** [comment]
If I try a different episode, for example:
http://www.itv.com/hub/coronation-street/1a0694a8955

It shows the message. Here's the log:
http://pastebin.com/ksLC9qbg

**Comment by mapx-** [comment]
add also
`@@||tidaltv.com/ILogger.aspx$object,domain=itv.com`

**Comment by derpenxyne** [comment]
That works but then the ads are no longer blocked, tricky one!

**Comment by mapx-** [comment]
yes, the video ads aren't blocked anymore, but it's an old issue,

**Comment by reek** [comment]
@mapx- 
thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
