### ISSUE TITLE
apkmos.com

### ISSUE THREAD

**Issue by swathigrate** [reek/anti-adblock-killer#1871]
http://apkmos.com/
http://imgbox.com/wG3NNspZ
Mozilla Firefox 48.0 beta&
Greasemonkey 3.9 Beta1
Adblock Plus 2.7.3 
EasyList + AakList + AdBlock Warning removal list 

please sir ... try to solve this problem ...
thanks you sir

**Comment by lassekongo83** [comment]
If you switch to uBlock Origin instead of Adblock Plus it may already be in one of the filters. If not:
`apkmos.com##script:contains(p,a,c,k,e,d)`
Should fix it, but only with Firefox and uBlock Origin.

**Comment by mapx-** [comment]
@swathigrate,
add this filter in ABP

`@@||apkmos.com/^$generichide`

how to add custom filters:
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by swathigrate** [comment]
**@mapx** 
Thanks dude ,,, It is  working ,,

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
