### ISSUE TITLE
http://timesofindia.indiatimes.com/

### ISSUE THREAD

**Issue by apjvarun** [reek/anti-adblock-killer#1873]
http://timesofindia.indiatimes.com/sports/rio-2016-olympics/india-in-olympics-2016/miscellaneous/10-reasons-why-India-can-double-its-London-tally-at-Rio-Olympics/articleshow/53534752.cms

Google Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1832#issuecomment-236011440

**Comment by ankitpise** [comment]
http://maharashtratimes.indiatimes.com/MT-LIVE-UPDATE/liveblog/53532815.cms?utm_source=facebook.com&utm_medium=referral&utm_campaign=MahadAccident040816

**Comment by mapx-** [comment]
@ankitpise, did you try the filters indicated above ?

**Comment by apjvarun** [comment]
thanks
