### ISSUE TITLE
clubic.com

### ISSUE THREAD

**Issue by MisterFa** [reek/anti-adblock-killer#1876]
http://www.clubic.com/video/
clic on any video

Firefox 48
Greasemonkey / Anti-Adblock Killer
Adblock Plus / EasyList + AakList +Adblock Warning Removal List
Noscript

![Uploading With Grease Monkey On.PNG…]()
![Uploading Without Grease Monkey On.PNG…]()

**Comment by reek** [comment]
Hi,

I think adblock blocks a script that prevents the loading of the video, report it to adblock, because I do not see any anti-adblock message

https://forums.lanik.us/
