### ISSUE TITLE
kjanime.net

### ISSUE THREAD

**Issue by BioBrayan** [reek/anti-adblock-killer#1877]
Google Chrome 52.0.2743.116 m
Adguard for Windows 6.1.251.1269
——————————————————
English Filter v1.0.90.43
Spanish/Portuguese Filter v1.0.86.28
——————————————————
Tampermonkey v4.1
AdsBypasser 5.57.0
Anti-Adblock Killer 9.8
AntiAdware 1.41.1
——————————————————
http://kjanime.net/link/68747470733a2f2f7777772e73656e6473706163652e636f6d2f66696c652f71336f707a75
http://fs5.directupload.net/images/160805/lxwzw4et.png

Delen fin a este script malicioso gracias

**Comment by mapx-** [comment]
add in your adblocker:
```
@@||kjanime.net/*ad$script
```

**Comment by BioBrayan** [comment]
Excellent work thank you very much

**Comment by reek** [comment]
Already fixed by AakList
