### ISSUE TITLE
loksatta.com

### ISSUE THREAD

**Issue by tabishishaq** [reek/anti-adblock-killer#1878]
http://www.loksatta.com/maharashtra-news/no-helmet-no-fuel-decision-1279713/
Google Chrome
Tampermonkey
Aaklist + AakList (Temporary)

![image](https://cloud.githubusercontent.com/assets/20391995/17438298/86e64a06-5b3b-11e6-9a4f-38f630572a6d.png)

**Comment by mapx-** [comment]
add in your adblocker
```
@@||loksatta.com/*/ads$script
```

**Comment by tabish4448** [comment]
Thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
