### ISSUE TITLE
timesofindia.com

### ISSUE THREAD

**Issue by timepas00** [reek/anti-adblock-killer#1879]
timesofindia still blocking adblocker ... 
![screen shot 2016-08-05 at 11 38 06 pm](https://cloud.githubusercontent.com/assets/20864332/17446342/7c559e0e-5b66-11e6-9064-6300b7f2a1e3.png)

**Comment by mapx-** [comment]
```
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
```

**Comment by X01X012013** [comment]
Or `setReadOnly("_0x89ff", "");`

You can use my script while waiting for Aak to update: 
https://x01x012013.github.io/AdBlockProtector/

**Comment by timepas00** [comment]
added both of your suggestions but issue still persists .. indiatimes is blocking adblocker

**Comment by timepas00** [comment]
where i have to set setReadOnly("_0x89ff", "");

**Comment by X01X012013** [comment]
@timepas00 Wait, they changed the blocking mechanism AGAIN, let me have a look...

**Comment by timepas00** [comment]
ok

**Comment by mapx-** [comment]
the filters above are still working, keep only one blocking extension.

**Comment by X01X012013** [comment]
Now the function is renamed... `setReadOnly("_0x17a5", "");`
I will update my script. Go to https://x01x012013.github.io/AdBlockProtector/ to instructions on how to use it.

**Comment by timepas00** [comment]
hello Mapx .. thanks for your comments .. i have added only one customized filter and added all of the above which you have written but no success

**Comment by timepas00** [comment]
hello X01X012013 ... i updated the user script and its working at this moment for indiatimes .. but failing for ndtv -- http://movies.ndtv.com/hollywood/how-rotten-tomatoes-became-scapegoat-for-frustrated-suicide-squad-fans-1440760?pfrom=home-moviehp_hollywood

**Comment by timepas00** [comment]
hi mapx .. i m using only adblocker plus extension firefox 47.0.1 and adblock plus 2.7.3

**Comment by timepas00** [comment]
hello mapx .. in my adblock plus i go to filter preference .. then click custom filter and in new extension group and then all above lines in one go and not as separate lines

**Comment by mapx-** [comment]
oh, install trhe last dev build from (fixing a problem with hiding filters)
https://adblockplus.org/en/development-builds#installation

**Comment by mapx-** [comment]
no, you have to add them on separate rows

**Comment by timepas00** [comment]
hmm the dev build is not getting installed stating connection failure

**Comment by X01X012013** [comment]
Since my script works, just use that for now. I'll update it when it stops working the next time. 
I'll have a look at ndtv.

**Comment by timepas00** [comment]
great n many thanks

**Comment by reek** [comment]
done
