### ISSUE TITLE
phonandroid.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#188]
Hello, 
on hxxp://www.phonandroid.com/
sc: http://i.imgbox.com/0IK43K7a.png
filter: 
@@/wp-content/plugins/adblock-notify-by-bweb/js/show_ads.js

**Comment by reek** [comment]
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
