### ISSUE TITLE
Gamestar.de

### ISSUE THREAD

**Issue by Symbai** [reek/anti-adblock-killer#1880]
http://www.gamestar.de/videos/quakecon-2016-johannes-entdeckt-die-groesste-lan-der-usa,89756.html

Video doesn't play because adblocker is detected:
http://i.imgur.com/3cmlA0x.png

//edit: Doesn't work with Chrome and Ublock filter list (there is no Aaklist as stated in the readme, but I've checked this anti-adblock-killer script.) But video plays fine using tampermonkey and the script for tampermonkey.

**Comment by mapx-** [comment]
just tested (ABP + firefox + easylist + easy germany), video still running.
if you are using other blocking addons / extensions, disable them, keep only 1 adblocker.

**Comment by reek** [comment]
@Symbai 
Yes you must use AakScript to ill it
