### ISSUE TITLE
Better Stop Adblock

### ISSUE THREAD

**Issue by rcmero** [reek/anti-adblock-killer#1882]
![image](https://cloud.githubusercontent.com/assets/5708421/17448924/e320e656-5b4e-11e6-8588-b991ff4a3bfd.png)

This one is a generic anti-adblocker plugin, I believe it is for WordPress. It's not in the currently supported anti-adblockers so I am reporting it here. 

This anti-adblocker was encountered by me on [this site](http://tudodownloadpt-pt2.com/), and it is one of those sites that requires an adblocker to access, as it dumps you fifty different ads, including ten different redirects to adf.ly, as soon as you access the homepage.

Tested with uBlock Origin on Google Chrome, EasyList is enabled.

**Comment by mapx-** [comment]
add this filter in your adblocker

`tudodownloadpt-pt2.com##[id^="bsa"]`

**Comment by rcmero** [comment]
This one is more of a generic anti-adblocker--i.e. it's a plugin site
admins add. If you look at the README file for this repository you can see
that this already detects several anti-adblockers.

Thanks for the filter though, that'll come in handy.

>

**Comment by reek** [comment]
Killed by AakScript
