### ISSUE TITLE
Times Of India

### ISSUE THREAD

**Issue by nmabhinandan** [reek/anti-adblock-killer#1884]
http://timesofindia.indiatimes.com/tech/tech-news/Reliance-Jio-fuels-price-war-Airtel-Vodafone-cut-data-prices/articleshow/53565506.cms?utm_source=facebook&utm_medium=referral&utm_campaign=TOITech

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1879#issuecomment-237923375

**Comment by nmabhinandan** [comment]
:+1:
