### ISSUE TITLE
Le Parisien

### ISSUE THREAD

**Issue by zorro3210** [reek/anti-adblock-killer#1885]
A big white box on leparisien
ex: http://www.leparisien.fr/sports/rio-2016-zero-medaille-pour-la-france-apres-24-heures-comme-en-2008-et-2012-07-08-2016-6020921.php

**Comment by mapx-** [comment]
for normal filter (french) issues you should post directly on easylist forum (french section):
https://forums.lanik.us/viewforum.php?f=91

**Comment by mapx-** [comment]
probably you are talking about the outbrain crap:
add this filter
leparisien.fr##.outbrain__main

**Comment by zorro3210** [comment]
Any help how to add filter please?
thanks

**Comment by zorro3210** [comment]
It does not work :(

**Comment by mapx-** [comment]
- explain where is that space
- browser (version) ?
- adblocker (version) ?
- filter lists enabled in your adblocker ?

**Comment by zorro3210** [comment]
After recheck of some parameters it seems to work;. thanks

**Comment by mapx-** [comment]
Great ! ;) you should close the issue.
