### ISSUE TITLE
mindgames.com / htmlgames.com

### ISSUE THREAD

**Issue by applesam** [reek/anti-adblock-killer#1887]
![snapshot](https://cloud.githubusercontent.com/assets/20497954/17463448/43dccf4c-5ce3-11e6-8be7-47a195f4fed3.jpg)
http://www.htmlgames.com/game/Cookie+Monster
and
http://www.mindgames.com/game/Brain+Workout

please fix this

**Comment by mapx-** [comment]
try these filters

```
@@||imasdk.googleapis.com/js/sdkloader/*$domain=htmlgames.com
@@||imasdk.googleapis.com/js/sdkloader/*$domain=mindgames.com
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
