### ISSUE TITLE
hotslogs.com

### ISSUE THREAD

**Issue by jw140120** [reek/anti-adblock-killer#1889]
https://www.hotslogs.com/Sitewide/HeroDetails
http://imgur.com/a/Ndb1S
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

Thank you in advance for your time!

**Comment by lassekongo83** [comment]
Try the following filter: `@@||d3pkae9owd2lcf.cloudfront.net/mb105.gz.js`

**Comment by jw140120** [comment]
Thank you Lassekongo, that worked swell!

**Comment by rickyars** [comment]
I tried adding as a custom filter but I'm still being redirected. Am I doing something wrong?

**Comment by mapx-** [comment]
use only 1 adblocker no other blocking extension

**Comment by rickyars** [comment]
turns out this solutions doesn't work if you have Ghostery running. once i disabled Ghostery the filter worked. thanks.

**Comment by cicuz** [comment]
Is the proposed solution to whitelist the whole thing? Because that wouldn't really be a solution....

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
