### ISSUE TITLE
rdio.com

### ISSUE THREAD

**Issue by RetroOptics** [reek/anti-adblock-killer#189]
http://www.rdio.com/
http://i.imgur.com/OnYucQA.png
Google Chrome 40.0.2214.111 64-bit Windows
Tampermonkey (recently updated)
Adblock (updated)
Anti-Adblock Killer

-Thomas

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
No problem detected

**Comment by reek** [comment]
Try
https://github.com/reek/anti-adblock-killer#help

**Comment by reek** [comment]
https://greasyfork.org/en/forum/discussion/4116/http-www-rdio-com
