### ISSUE TITLE
Disable Adblock

### ISSUE THREAD

**Issue by GroBeNope** [reek/anti-adblock-killer#1890]
![capture-20160808-134412](https://cloud.githubusercontent.com/assets/20899360/17471459/70c1f290-5d6e-11e6-9669-88415f932133.png)
[http://hanimesubth.blogspot.com/?zx=f3e228040521b539](http://hanimesubth.blogspot.com/?zx=f3e228040521b539)

**Comment by mapx-** [comment]
add these filters
```
@@||hanimesubth.blogspot.co.uk^$generichide
@@.png#$domain=hanimesubth.blogspot.co.uk
hanimesubth.blogspot.co.uk###g207
```

**Comment by reek** [comment]
Already killed by AakScript
