### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by GroBeNope** [reek/anti-adblock-killer#1891]
#![capture-20160808-134847](https://cloud.githubusercontent.com/assets/20899360/17471508/f740ac76-5d6e-11e6-9637-ddd1187d6074.png)
[http://adf.ly/1cS54W](http://adf.ly/1cS54W)

**Comment by mapx-** [comment]
try this fix
https://forums.lanik.us/viewtopic.php?p=98414#p98414

**Comment by reek** [comment]
@GroBeNope 
use https://greasyfork.org/fr/scripts/4881-adsbypasser

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
