### ISSUE TITLE
http://www.rlslog.net/

### ISSUE THREAD

**Issue by traitor123** [reek/anti-adblock-killer#1892]
http://www.rlslog.net/
http://imgur.com/a/UByn2
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

Unable to block these ads.

**Comment by mapx-** [comment]
add:
```
||thaez4sh.com^
||code.jquery.com$domain=rlslog.net
```
https://adblockplus.org/forum/viewtopic.php?p=156757#p156757

**Comment by traitor123** [comment]
damn! you're good @mapx-  :+1:  :+1:
