### ISSUE TITLE
tr.investing.com & www.investing.com

### ISSUE THREAD

**Issue by SubZero5** [reek/anti-adblock-killer#1893]
Ad Block Popup is shown at page load at http://tr.investing.com/ & http://www.investing.com/

**Comment by vitalif** [comment]
This is easy to fix by adding `window.google_ad_status = 1;`

Even like this:

```// ==UserScript==
// @name           No Anti-AdBlock on investing.com
// @description    Remove Anti-AdBlock popup on investing.com
//
// @run-at         document-end
// @include        http://*.investing.com/*
// @include        https://*.investing.com/*
// ==/UserScript==

window.google_ad_status = 1;```

**Comment by CodeSlinger69** [comment]
I added that script to TamperMonkey, no luck.  Still getting the "We've noticed you're using an ad blocker" non-dismissable popup on investing.com.

**Comment by vitalif** [comment]
Hm.. it works in greasemonkey

**Comment by mapx-** [comment]
try this filter

@@||doubleclick.net/instream/ad_status.js

**Comment by SubZero5** [comment]
Added to custom filters @mapx- ;)
Thank you!

**Comment by CodeSlinger69** [comment]
Ah, that's embarrassing.  Once I deleted the investing.com cookies, both @vitalif and @mapx- solutions work fine.

**Comment by vijayaraghavanramanan** [comment]
@@||doubleclick.net/instream/ad_status.js

isn't working for me (Chrome)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
