### ISSUE TITLE
http://tinyurl.com/h4bzk94

### ISSUE THREAD

**Issue by atineo** [reek/anti-adblock-killer#1899]
http://tinyurl.com/h4bzk94
http://imgur.com/a/o3tJ6
Chrome
Tampermonkey
Ublock Origin
EasyList + AakList

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1889#issuecomment-238145484

**Comment by atineo** [comment]
Working, thanks!
