### ISSUE TITLE
an1me.se

### ISSUE THREAD

**Issue by ManosZ** [reek/anti-adblock-killer#190]
http://an1me.se/corpse-party-tortured-souls/ova-002/
![capture1](https://cloud.githubusercontent.com/assets/11014255/6202551/a1345012-b4fa-11e4-835c-0ee3c672687b.PNG)
Google Chrome
Tampermonkey
Adblock Plus
from jsbin.com

p.s This happens on every video i m trying to watch on this site and not only on this one

**Comment by alexander255** [comment]
Anti-ad defeater script: http://pastebin.com/RvAimcH9

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Thanks Alex ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
