### ISSUE TITLE
http://tv3play.tv3.ee/sisu/padjaklubi/735171?autostart=true&collection=426

### ISSUE THREAD

**Issue by Fluden** [reek/anti-adblock-killer#1900]
Screen stays white and text "Program could not be loaded" can be seen, when clicked in the middle. It's same with every video on that site.
Chrome Version 51.0.2704.103 m
Tampermonkey
AdBlock
Reek Anti-Adblock Killer list
![e58f3da6e5184a3a51cf555acfec8c1a](https://cloud.githubusercontent.com/assets/20929082/17519634/749140aa-5e55-11e6-9248-f36e326f349f.png)
![60731c3c710d643a7bee677650523ade](https://cloud.githubusercontent.com/assets/20929082/17519641/7a66d7ce-5e55-11e6-9cca-4d761d04e700.png)

**Comment by SMed79** [comment]
If you disable your adblock the video play?

**Comment by Fluden** [comment]
If I just use adblock, it knows I'm using it.
![99583928f4977a01caca2380c1a4677f](https://cloud.githubusercontent.com/assets/20929082/17561001/d3e45df8-5f2c-11e6-914d-1fe9b50b3ac1.png)
If I turn adblock and Anti-Adblock Killer off, I can watch it with ads.

**Comment by mapx-** [comment]
you can add:

```
@@||tv3.ee^$generichide
@@||5d406.v.fwmrm.net/ad/p/1?$object,domain=tv3play.tv3.ee
@@||5d3e9.v.fwmrm.net/ad/l/1?rnd=$object,domain=tv3play.tv3.ee
@@||adm.fwmrm.net/p/MTG_Live/Video2AdRenderer.swf$object,domain=tv3play.tv3.ee
```
but the video ads will be also visible

**Comment by reek** [comment]
killed by version 9.9
