### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by MrTal** [reek/anti-adblock-killer#1901]
Link page contains anti-adblock: http://timesofindia.indiatimes.com/ (only in report):
http://timesofindia.indiatimes.com/sports/rio-2016-olympics/india-in-olympics-2016/hockey/Rio-2016-India-mens-hockey-team-beat-Argentina-2-1/articleshow/53621147.cms
One screenshot: http://prntscr.com/c3l1rq
Your browser: Goole chrome
Your script manager: Tampermonkey
Your adblocker: adblock, adblock plus
Your filterlists: AakList (Anti-Adblock Killer),Adblock Warning Removal List

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1807#issuecomment-234556392

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
