### ISSUE TITLE
Dailymotion Ads

### ISSUE THREAD

**Issue by Lemonadez** [reek/anti-adblock-killer#1902]
How to block that video ads? Any filter for it?

I updated all my filter already. annoying 20 second ads. trivago crap -.- Using Chrome.

http://www.pinoy1tv.me/64876/born-for-you-august-9-2016-dailymotion-hd

http://image.prntscr.com/image/892b65364a51453db5c5fe014a1be400.png

**Comment by SMed79** [comment]
Try these filtres [/viewtopic.php?f=62&t=28765#p99979](https://forums.lanik.us/viewtopic.php?f=62&t=28765#p99979) (the result is not guaranteed).
