### ISSUE TITLE
minecraftbuildinginc.com

### ISSUE THREAD

**Issue by BlakeKillough** [reek/anti-adblock-killer#1906]
http://minecraftbuildinginc.com/category/buildings/house/
http://imgur.com/a/LBT4k
Chrome
Greasemonkey
Adblock
EasyList + AakList

_ADDITIONAL INFO_
-This is the website selling anti adblocking service for this particular website "http://blockadblock.com/"

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=32001

**Comment by reek** [comment]
ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
