### ISSUE TITLE
Times of India Still recognising and blocking Adblock Plus on Moz FF

### ISSUE THREAD

**Issue by ThisIsSubu** [reek/anti-adblock-killer#1909]
http://bit.ly/2aL0Mha - Page that recognizes / block ad block 
http://imgur.com/gallery/6wXaL - Image of Block 
Mozilla firefox - my browser 
Adblock Plus - 
AskList + EasyList + Adblock warning removal list - all updated 10 aug 2016

Screen shot of the blocked page
![screenshot - 10_08_2016 14_13_35](https://cloud.githubusercontent.com/assets/20946564/17550158/a867a27a-5f04-11e6-856c-a0e09ee44812.png)

Screen shot of how my Adblock Plus preferences are set up / updated 
![screenshot - 10_08_2016 14_14_13](https://cloud.githubusercontent.com/assets/20946564/17550174/b9f72c4a-5f04-11e6-8274-8b71b449ed85.png)

thanks a ton
regards

**Comment by mapx-** [comment]
already tried ? : https://github.com/reek/anti-adblock-killer/issues/1807#issuecomment-234556392

**Comment by ThisIsSubu** [comment]
You are an amazing person Mapx !! you replied so fast !

this is what I have tried so far 

1. **I think i've added the specific exemptions that you mentioned** 
* Screen shot enclosed (Request : Could u please check that I've done it right ! )
* Do I have to just copy paste the lines you have mentioned (i.e. - example @@||partner.googleadservices.com^$domain=indiatimes.com) ? 
or 
* **should I add $elemhide at the end of each of these lines**  (i.e. ) @@||partner.googleadservices.com^$domain=indiatimes.com$elemhide ? 
![screenshot - 10_08_2016 15_54_56](https://cloud.githubusercontent.com/assets/20946564/17552761/cc7b2944-5f12-11e6-958e-efb1cc72b439.png)

2. **I've disabled all filters except AakList**
![screenshot - 10_08_2016 15_55_40](https://cloud.githubusercontent.com/assets/20946564/17552771/e686f912-5f12-11e6-9470-a94ecca4d842.png)

3. I'm unable to use Imgur as I'm new to that site and the site is placing minimum time restrictions to post further content :-(   . so posted all images inline here 

4. the AakList is updated some 3 hours ago you can see this on the screen shot as well

Hope I have answered your questions

thanks again

best regards
Subu

**Comment by mapx-** [comment]
use only my filters (remove the last 3)
use easylist + aak list

if still does not work install the last dev build of ABP in firefox from: https://adblockplus.org/en/development-builds#installation

test again

**Comment by ThisIsSubu** [comment]
* ///use only my filters (remove the last 3)///
Done. Screen shot below 
![screenshot - 10_08_2016 16_16_57](https://cloud.githubusercontent.com/assets/20946564/17553249/ea177a0e-5f15-11e6-9d9d-ba5551e84a2e.png)

* //use easylist + aak list//
done !
![screenshot - 10_08_2016 16_18_03](https://cloud.githubusercontent.com/assets/20946564/17553274/06936ce2-5f16-11e6-8471-de57c2da92b9.png)

* ////if still does not work i////
yes., above did not work 

* ////install the last dev build of ABP in firefox from: https://adblockplus.org/en/development-builds#installation///
So I went on to install latest ABP from link you gave + deleted all history and re-started and tried to access a TOI page http://bit.ly/2biuNDv

still I'm blocked :-( 

![screenshot - 10_08_2016 16_20_59](https://cloud.githubusercontent.com/assets/20946564/17553383/946d4c18-5f16-11e6-8b0d-af669b1166d0.png)

thanks and best regards
subu

**Comment by ThisIsSubu** [comment]
do you think moving to Google chrome is easier than doing all this on FF ? or is that independant of browsers

**Comment by mapx-** [comment]
keep only ABP enabled, disable all other addons, test again (using easylist, aak list, my filters)

**Comment by ThisIsSubu** [comment]
getting blocked at http://timesofindia.indiatimes.com/india/Kudankulam-Nuclear-Power-Plant-dedicated-to-nation-five-more-1000MW-units-to-be-set-up/articleshow/53635266.cms
as well

**Comment by ThisIsSubu** [comment]
you said .//// keep only ABP enabled, disable all other addons/// 

isn't that the opposite of  ////using easylist, aak list, my filters///

#confused !

**Comment by ThisIsSubu** [comment]
with all three list enabled 
http://timesofindia.indiatimes.com/business/india-business/Raghuram-Rajan-says-attacks-on-him-abominable-was-open-to-extension/articleshow/53635645.cms
gets blocked

**Comment by ThisIsSubu** [comment]
with only AakList and Easylist enabled (meaning adb,lock warning removal list ) disabled,

**Comment by mapx-** [comment]
I 'm talking about all other add-ons to be disabled ! (not about the filter lists easylist, aak, ...)

to see the add-ons, click in menu. tools, add-ons

**Comment by ThisIsSubu** [comment]
with these filter preferences 
![screenshot - 10_08_2016 16_54_24](https://cloud.githubusercontent.com/assets/20946564/17554254/1f8b2bae-5f1b-11e6-9570-2a4f215de82f.png)

and these customer filters 
![screenshot - 10_08_2016 16_55_05](https://cloud.githubusercontent.com/assets/20946564/17554278/3430557a-5f1b-11e6-96f5-fccb95a594f8.png)

this page gets blocked http://timesofindia.indiatimes.com/business/india-business/Raghuram-Rajan-says-attacks-on-him-abominable-was-open-to-extension/articleshow/53635645.cms

and looks like this 
![screenshot - 10_08_2016 16_55_59](https://cloud.githubusercontent.com/assets/20946564/17554307/53a80920-5f1b-11e6-9d0f-ef1eb3c83a1c.png)

**Comment by ThisIsSubu** [comment]
* disabled ALL other add ons / extensions expect ADB (luckily I had just 1 or 2 more left)

* Still get blocked as in sample below on this page http://timesofindia.indiatimes.com/sports/rio-2016-olympics/news/aquatics/Rio-2016-Sealed-with-a-kiss-as-Michael-Phelps-makes-it-21-golds/articleshow/53629060.cms

* what happens is that initially the page loads as can be seen here 
![screenshot - 10_08_2016 17_38_01](https://cloud.githubusercontent.com/assets/20946564/17555604/362125e8-5f21-11e6-9660-13e060669b78.png)

* but when I scroll down or when I refresh page TOI blocks !
![screenshot - 10_08_2016 17_38_50](https://cloud.githubusercontent.com/assets/20946564/17555634/4ecb3a02-5f21-11e6-85f9-0b8b442278f1.png)

* so something that happens at the time of refreshing the browser or during scroll down makes TOI pages realise that I run ad blocker

* my / user experience is unchanged in spite of change in settings ! or should I say this doesn't seem to have anything with settings 

* here is what I have as filter preferences 
![screenshot - 10_08_2016 17_40_03](https://cloud.githubusercontent.com/assets/20946564/17555716/a4dc47e2-5f21-11e6-9e8f-b5cf491e39b9.png)

* and custom preferences
![screenshot - 10_08_2016 17_41_33](https://cloud.githubusercontent.com/assets/20946564/17555735/b57b6da8-5f21-11e6-8fa5-1b47341bdd2f.png)


Ps : Sorry I seem to have posted this response in a wrong thread so corrected it now !

**Comment by ThisIsSubu** [comment]
Repeating same reply in both threads (sorry that other thread was un intentional) 

* complete removal (NOT just disable but complete removal ) of ADB removes TOI blocks
* same proxy, hosts, machine etc 
* screen shot of TOI page with shitty adverts and no block enclosed
![screenshot - 10_08_2016 18_13_19_ver001](https://cloud.githubusercontent.com/assets/20946564/17556985/873f67e6-5f26-11e6-91da-15fd3076b6d3.png)

**Comment by mapx-** [comment]
still using only ABP, [submit an issue report](https://adblockplus.org/en/getting_started#problems) and then post here the report link.

**Comment by ThisIsSubu** [comment]
further update
* uninstalled FF, re installed FF meaning lost all history, adons etc etc (did this intentionally)
* re-installed ADB development build from https://adblockplus.org/en/development-builds
* specifically for FF here : https://addons.mozilla.org/downloads/latest-beta/adblock-plus/adblockplus-devbuild.xpi
* did **not** add any other filter lists, just went with the native ADB development version 
* TOI isn't nagging me !!! :-) :-) at least so far :+1: !!!
* sample pages here (see no advert and multiple screen shots with scroll down ) 
![screenshot - 10_08_2016 18_22_31](https://cloud.githubusercontent.com/assets/20946564/17557239/77c5f6ee-5f27-11e6-8e1b-cb40d3035df6.png)
![screenshot - 10_08_2016 18_23_11](https://cloud.githubusercontent.com/assets/20946564/17557256/80ea4450-5f27-11e6-932a-c564bd022f5a.png)
* I am adding this comment here so that it will add to the knowledge base
* so probably the best is to uninstall FF and re start fresh with just ADB, dev. build ?
regards
Subu

**Comment by mapx-** [comment]
and without my custom filters ?

**Comment by ThisIsSubu** [comment]
* will continue testing and update
* i'm completely new to Github, created an account today, just because of this ADB problem
* loving the ease of using and simplicity here (github) 
* Long live all those who helped me , esp. mapx !! and Github 
regards
subu

**Comment by ThisIsSubu** [comment]
///// and without my customer filters ? ///
**No* custom filters at all 
![screenshot - 10_08_2016 18_26_05](https://cloud.githubusercontent.com/assets/20946564/17557377/fd8fec58-5f27-11e6-9d0e-bf950a3247d9.png)

**Comment by ThisIsSubu** [comment]
these are the filter lists - again standard as on 10 Aug 2016
![screenshot - 10_08_2016 18_27_29](https://cloud.githubusercontent.com/assets/20946564/17557406/24baf58e-5f28-11e6-857d-aaa19fa9036c.png)

**Comment by mapx-** [comment]
very strange, without the custom filters I get the nag screen.

**Comment by ThisIsSubu** [comment]
more TOI pages without nag & without advert
![screenshot - 10_08_2016 18_28_50](https://cloud.githubusercontent.com/assets/20946564/17557460/5c43931c-5f28-11e6-92ee-f1f0a495503d.png)
![screenshot - 10_08_2016 18_28_57](https://cloud.githubusercontent.com/assets/20946564/17557465/608e94e4-5f28-11e6-9fef-7fafae9d21f6.png)

**Comment by ThisIsSubu** [comment]
working quite well so far...small un obtrusive
![screenshot - 10_08_2016 18_31_13_ver001](https://cloud.githubusercontent.com/assets/20946564/17557592/d141834a-5f28-11e6-9595-c3eb6f178f44.png)
 adverts go thru, big and nasty ones blocked !!

**Comment by ThisIsSubu** [comment]
Thanks, kudos and great to see how all of you in the community like mapx responded to the nagging / bullying !! 

regards
Subu

**Comment by mapx-** [comment]
are you sure ABP is not disabled ? the ABP icon is still red ?

**Comment by ThisIsSubu** [comment]
YES !! :+1:

**Comment by ThisIsSubu** [comment]
Raghuram to our rescue again !! :-) 

![screenshot - 10_08_2016 18_41_27](https://cloud.githubusercontent.com/assets/20946564/17557936/19142906-5f2a-11e6-88e7-463b6a35090f.png)

![screenshot - 10_08_2016 18_41_16](https://cloud.githubusercontent.com/assets/20946564/17557942/1d718dea-5f2a-11e6-8841-e142a48bb8be.png)

**Comment by ThisIsSubu** [comment]
In the message above , I've taken full screen shots with the ABP red visible on the screen shots !!

**Comment by ThisIsSubu** [comment]
other unrelated TOI pages also working fine 

![screenshot - 10_08_2016 18_47_12](https://cloud.githubusercontent.com/assets/20946564/17558209/e505d640-5f2a-11e6-9fcc-3d463f6a3315.png)

**Comment by ThisIsSubu** [comment]
TOI nag re started today !! Probably they updated something overnight !! aaargh !!

Filters etc : 

![screenshot - 11_08_2016 09_32_57](https://cloud.githubusercontent.com/assets/20946564/17579449/b2b32360-5fa6-11e6-9054-8c4b87ec615e.png)

![screenshot - 11_08_2016 09_32_50](https://cloud.githubusercontent.com/assets/20946564/17579451/bfbad454-5fa6-11e6-9fa2-84b81bfad7fe.png)

Nag screen : 
![screenshot - 11_08_2016 09_32_26](https://cloud.githubusercontent.com/assets/20946564/17579454/c62a37bc-5fa6-11e6-853d-a5aa680e8e94.png)

**Comment by ThisIsSubu** [comment]
dear mapx

updated 11 / Aug 2016

Once again the nag started appearing today

I've tried with your setup (i.e.) changed everything just now, but still the nag won't go away !!

Nag on page : http://tinyurl.com/hujdugm

Using FF 48 
![screenshot - 11_08_2016 10_06_44](https://cloud.githubusercontent.com/assets/20946564/17579947/54b83dae-5fab-11e6-9d6c-7ed29377b025.png)

Nag looks like this 
![screenshot - 11_08_2016 10_07_16](https://cloud.githubusercontent.com/assets/20946564/17579953/659e1742-5fab-11e6-9bdd-0fb0987032d1.png)

Latest ADB plus downloaded and installed few min ago , from http://tinyurl.com/he5s263

your filters updated, from Github, screen shot below 
![screenshot - 11_08_2016 10_20_31](https://cloud.githubusercontent.com/assets/20946564/17580136/411eb5c8-5fad-11e6-8faa-fb9da43fa00d.png)

your customer filters alone are in place 
![screenshot - 11_08_2016 10_21_53](https://cloud.githubusercontent.com/assets/20946564/17580154/75012556-5fad-11e6-86e1-5f912daef872.png)

TIA for your help

I'm also posting this as an update to this thread

regards
subu

**Comment by ThisIsSubu** [comment]
^^ in continuation of above

Other nag pages : 
http://tinyurl.com/zbvfovh
http://tinyurl.com/hff44so

in some pages like this http://tinyurl.com/jrt4lpe the nag appears on part of the screen . screen shot below 

![screenshot - 11_08_2016 10_26_15](https://cloud.githubusercontent.com/assets/20946564/17580287/8955c42a-5fae-11e6-94fe-7894878f338e.png)

best regards
subu

**Comment by mapx-** [comment]
still working for me

```
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
```

tested on http://timesofindia.indiatimes.com/city/mumbai/Police-say-Zakir-Naik-got-60cr-in-3-years-from-abroad/articleshow/53643032.cms

it's something wrong in your system

**Comment by brar6119** [comment]
In chrome, it is possible to block javascript completely on certain websites by adding exceptions. 

For this, Open chrome and type in address bar : chrome://settings/contentExceptions#javascript

Hostname Pattern : **http://timesofindia.indiatimes.com**
Behaviour : **Block**

After blocking javascript on the website, you can read all articles without any problem.

**Comment by reek** [comment]
done
