### ISSUE TITLE
TOI still blocking Ad block plus after adding your filter lines, Moz FF + Aaklist + Easylist + Adblock list

### ISSUE THREAD

**Issue by ThisIsSubu** [reek/anti-adblock-killer#1910]
TOI page that finds my Adblock : http://bit.ly/2aL0Mha

Screen shot of Adblock : enclosed to this message, Imgur placing time limits !! :-( 
![screenshot - 10_08_2016 14_26_15](https://cloud.githubusercontent.com/assets/20946564/17550577/ac7902f8-5f06-11e6-9832-7326262e2f8c.png)

Mozilla FF
Adblock Plus
AakList + Easylist + adblock removal warning list

**Comment by ThisIsSubu** [comment]
* disabled ALL other add ons / extensions expect ADB (luckily I had just 1 or 2 more left)

* Still get blocked as in sample below on this page http://timesofindia.indiatimes.com/sports/rio-2016-olympics/news/aquatics/Rio-2016-Sealed-with-a-kiss-as-Michael-Phelps-makes-it-21-golds/articleshow/53629060.cms

* what happens is that initially the page loads as can be seen here 
![screenshot - 10_08_2016 17_38_01](https://cloud.githubusercontent.com/assets/20946564/17555604/362125e8-5f21-11e6-9660-13e060669b78.png)

* but when I scroll down or when I refresh page TOI blocks !
![screenshot - 10_08_2016 17_38_50](https://cloud.githubusercontent.com/assets/20946564/17555634/4ecb3a02-5f21-11e6-85f9-0b8b442278f1.png)

* so something that happens at the time of refreshing the browser or during scroll down makes TOI pages realise that I run ad blocker

* my / user experience is unchanged in spite of change in settings ! or should I say this doesn't seem to have anything with settings 

* here is what I have as filter preferences 
![screenshot - 10_08_2016 17_40_03](https://cloud.githubusercontent.com/assets/20946564/17555716/a4dc47e2-5f21-11e6-9e8f-b5cf491e39b9.png)

* and custom preferences
![screenshot - 10_08_2016 17_41_33](https://cloud.githubusercontent.com/assets/20946564/17555735/b57b6da8-5f21-11e6-8fa5-1b47341bdd2f.png)

**Comment by ThisIsSubu** [comment]
even a simple click on the page to scroll down, or a mouse roll makes TOI realise that I run ADB and TI blocks me

**Comment by mapx-** [comment]
strange, I can click, scroll .. all fine for me. 
If you disabled all other addons, well, I don't know.
Are you using by chance some HOSTS with blocking rules file ?
Or your antivirus has some web shields ON ?

If you disable completely ABP, do you still get the nag screen ?

**Comment by ThisIsSubu** [comment]
complete removal of ADB removes the block !!
Same proxy, hosts etc etc 
screen shot (with adverts) enclosed 
![screenshot - 10_08_2016 18_13_19_ver001](https://cloud.githubusercontent.com/assets/20946564/17556918/41cc8572-5f26-11e6-8e3d-e9d98b85a8df.png)

**Comment by ThisIsSubu** [comment]
please visit https://github.com/reek/anti-adblock-killer/issues/1909 for a more detailed discussion on this issue.... I'm closing this issue, requesting readers to visit above link. thanks to all those who helped
