### ISSUE TITLE
goalsarena.org

### ISSUE THREAD

**Issue by abysas** [reek/anti-adblock-killer#1914]
http://www.goalsarena.org/en/video/european-cups/09-08-2016-real-madrid-sevilla-uefa-super-cup.html
https://postimg.org/image/ctgxxt0d1/
Mozilla Firefox
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add in ABP:

@@||goalsarena.org^$generichide

**Comment by abysas** [comment]
Works! Thank you!
