### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by rammanokar** [reek/anti-adblock-killer#1916]

**Comment by mapx-** [comment]
add this filter in your adblocker

@@||financialexpress.com$script,domain=indianexpress.com

**Comment by Y-1** [comment]
Seems like indianexpress joins the game. Thanks to mapx for a quick fix.

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=32059

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
