### ISSUE TITLE
fullstuff.co

### ISSUE THREAD

**Issue by supervirus5** [reek/anti-adblock-killer#1917]
https://blockadblock.com/
http://puu.sh/qy3iX.png
Google Chrome V  52.0.2743.166 m (64 bit)
Tamper Monkey
Adblock Plus + AdBlock (Running Both at the same time)
EasyList,Malware Domains,EasyPrivacy,AakList(Anti-Adblock Kiler)

**Comment by mapx-** [comment]
1. don't use 2 adblockers. Never ! keep ABP.
2. add the filters here
https://github.com/reek/anti-adblock-killer/issues/1799#issuecomment-236997275

**Comment by supervirus5** [comment]
Hmm that's weird let me explain after adding the filters successfully into my ABP I could browse blockadblock.com with no problems at all but other hosts still tells me to disable adblock "blockAdBlock js" here is an example : https://fullstuff.co/hotspot-shield-elite/

So your filters works only on blockadblock.com host and doesn't work for others.

**Comment by mapx-** [comment]
sure, you asked a fix for blockadblock site

**Comment by mapx-** [comment]
for fullstuff add:
`@@||fullstuff.co^$generichide`

**Comment by mapx-** [comment]
for filters you can also search easylist forum: forums.lanik.us

fullstuff had a fix there from 28 july
https://forums.lanik.us/viewtopic.php?p=99290#p99290

**Comment by supervirus5** [comment]
this is kinda strange, why are we editing/adding filters to ABP although AntiAdblock Killer should be the one who helps with this step ? I mean is it going to be updated or is there a more practical way of adding a generic filter to all hosts ?

**Comment by mapx-** [comment]
There are different things. Sure, aak is helping a lot of users, but also easylist contains a lot of such filters.
There is no general solution to anti adblocking, no "generic" filter.

**Comment by supervirus5** [comment]
I mean a generic filter for all hosts which uses a specific anti ad-block script like 

any website uses blockadblock.com must all have something in common that we should be able to block.

**Comment by mapx-** [comment]
yep, as you can see on the blockadblock site you have to add more filters, instead on fullstuff only the generichide filter. 
Probably for some anti-adblocking tricks Reek (aak) can find a generic modality for more sites.

**Comment by supervirus5** [comment]
@mapx- what about this website 
http://linkdrop.net/XWKE9

what filters should i use, i tried generic hide and it didn't work.

**Comment by mapx-** [comment]
add

```
@@*$image,domain=linkdrop.net
||lkrcapch.com^
||zptncsir.com^
```

the last 2 filters are for popups
however, the first filter was already proposed time ago on easylist forum (so you could always search there for other sites)
https://forums.lanik.us/viewtopic.php?p=99542#p99542

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
