### ISSUE TITLE
http://gelbooru.com/

### ISSUE THREAD

**Issue by drthundercritic** [reek/anti-adblock-killer#1918]
Adblock block access to use search filter unless adblock is disabled.
But anti-adblock didn't do anything and can't unblock search filter access while adblock is on, please help.

**Comment by mapx-** [comment]
add this filter in your adblocker (don't use 2 adblockers !)

`gelbooru.com#@#center > div[style*="overflow:"]`

**Comment by drthundercritic** [comment]
I'm using adblock plus, sorry if I'm being dumb here but Gelbooru still doesn't unblock the search filter...
http://imgur.com/a/CAu1Z

**Comment by mapx-** [comment]
it works fine for me using that filter (chrome, firefox + ABP)
Did you also update easylist ?
Keep only 1 blocking extension (ABP), test again. Or disable all other extensions see if works.

**Comment by mapx-** [comment]
you mean this search:
![search1](https://cloud.githubusercontent.com/assets/10303732/17618377/bcf47cf0-607f-11e6-9787-23f016b812c0.PNG)

**Comment by Recchan** [comment]
@mapx- 

> But anti-adblock didn't do anything
It's not an issue for this github then? You might get better assistance in ABP's forums. Did you try removing all the filters and adding them one by one?

**Comment by mapx-** [comment]
the issue it's anti adblocking stuff: it can be fixed using filters (99% of these issues can be simply fixed using the filters) and only a few need some advanced userscripting.

well, thanks for "You might get better assistance in ABP's forums", did you watch those forums ? :)

**Comment by drthundercritic** [comment]
@Recchan 
Sorry for wrong understanding. Actually, what I'm trying to say is Gelbooru removed search images feature if I turn on the ABP. But the GitHub Anti-Adblock killer can't un-remove the missing search images feature...

**Comment by kowith337** [comment]
Maybe it's an issue from Easylist or other 3rd party lists?
I've reported to ryanbr/fanboy-adblock#30
Before report, I use these code below, more details in my issue reference.
`gelbooru.com##center div[style="width:1000px; overflow:hidden;"]`
`gelbooru.com##.sidebar iframe`
`||gelbooru.com$media`
`||gelbooru.com/*_loader`
`@@||gelbooru.com/images^$media`
Then use uBlock0 to block all third party domains, still work perfect and search bar still appear.
I've tested again by purge EasyList (also Fanboy Ultimate) and found search bar still exist.

**Comment by drthundercritic** [comment]
@kowith337 Thanks but I think it's fixed (glitched?) now...
Hope it will not returned as Anti-Adblock feature.
