### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by cubenity** [reek/anti-adblock-killer#192]
http://player.pl/seriale-online/szkola-odcinki,2395/odcinek-65,S00E65,36253.html
http://imgur.com/2Q7UmsH
Google Chrome
Tampermonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Sorry, no solution

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/293

**Comment by MajkiIT** [comment]
I find this... Could you see this?

http://kemsan.webd.pl/scripts/playerpl.js

**Comment by reek** [comment]
@MajkiIT 
thank you I'll test

**Comment by MajkiIT** [comment]
I hope it will help.

**Comment by reek** [comment]
@MajkiIT 
I could not test but I'll add it to AakScript

**Comment by MajkiIT** [comment]
Can you give me same beta script and than I will test it?

**Comment by reek** [comment]
@MajkiIT 
Beta: https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by MajkiIT** [comment]
Unfortunately it is not working. Thank you for your help.

**Comment by MajkiIT** [comment]
I find fix.... https://www.youtube.com/watch?v=Q24rqrNCe9g see scripts under film on yt. I see that work.

**Comment by reek** [comment]
Have you tested this solution ?

with me it does not work :/

1. go to http://player.pl/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=2.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id=34555&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920
2. copy result to http://paste2.org/

I need to know whether the video link appears in you

**Comment by MajkiIT** [comment]
I tested It and it works. 
http://paste2.org/715G6P3d

If I want see this video http://player.pl/seriale-online/szpital-odcinki,1171/odcinek-1,S00E01,17652.html I see ads.

If I use script:
javascript:(function(){var%20n=document.location.href.split(/[.,]/);%20var%20xmlhttp=new%20XMLHttpRequest();xmlhttp.open('GET','/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=2.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id='+n[n.length-2]+'&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920',false);xmlhttp.send();%20var%20o%20=%20eval('('+xmlhttp.responseText+')');var%20s=o.item.videos.main.video_content[0].url;var%20m=s.match(/:\/\/(?:www\.)?(.[^/]+)(.*)/);var%20xmlhttp=new%20XMLHttpRequest();xmlhttp.open('GET',m[2],false);xmlhttp.send();document.location.href=xmlhttp.responseText;})();

I new tab I see link http://n-2-10.dcs.redcdn.pl/dcs/o2/tvnplayer/vod/13_400_18010_0001/TV_MP4/b584756a-1358-4cac-a0ad-0bb6d3a27931/tv_mp4_928000.mp4?salt=AB84635189E0A58EE87F0EAC8AEBD783&token=7929A04D6BDC7D7FD169BD3CF3B98410510B30A3488D8F0EC56EDB1BFE7438297E70BA384726E6E10A68E2D94779DBA444D2A26FA0E582249728BC1BC3F3E3B9A3CBDE5506D72B1C58FC06C8E1F1948B797865FB918A7D0AEFE2BB946F9A0F0BF505CC529A64884A2A087963C4D05A2FB4F391878CFE8BD02FF8F331318AF16C4A3C4D6AB33EAF04E0BF194704C94544 

Maybe do you want use my pc by teamviewer.

**Comment by reek** [comment]
Ok, test this beta (press raw for install)
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by MajkiIT** [comment]
It works :D . I have big screen with video, but it's not a problem. Random I have screen like this https://www.dropbox.com/s/uhqilklzvhggqlr/adblock16.png?dl=0 and then I must add rule to adblock/ublock ==> player.pl###vod and then notification disapear.

**Comment by reek** [comment]
Great, I would also add this rule to AakList

**Comment by MajkiIT** [comment]
Thank's a lot. When you publish new script and filters?

**Comment by reek** [comment]
Probably next week

**Comment by MajkiIT** [comment]
Ok, thank you again.

**Comment by MajkiIT** [comment]
Hi Reek, I think that you can close this issue. Yesterday you fix it.

**Comment by reek** [comment]
@MajkiIT 
Thank you for reminding it to me I had forgotten
