### ISSUE TITLE
auto-motor-und-sport.de

### ISSUE THREAD

**Issue by alexara** [reek/anti-adblock-killer#1920]
#### URL

`http://www.auto-motor-und-sport.de/news/audi-setzt-auf-rotationsdaempfer-1230371.html?block=1`
#### System
- FF 48.0
- uBlock Origin 1.8.4 (Filter lists:  default + Anti-Adblock Killer | Reek filter list + EasyList Germany )
- all other addons deactivated for testing
#### Issue

Anti adblock overlay and text encrypted
#### Screenshot

![auto-moto-sport-adblock](https://cloud.githubusercontent.com/assets/13819719/17621079/3e8aca74-6091-11e6-8157-44cfc53deb8c.png)

**Comment by alexara** [comment]
Possible solution for uBlock Origin: 
`auto-motor-und-sport.de##script:contains(FuckAdBlock)`

Be aware to remove "block=1" from the URL:
`http://www.auto-motor-und-sport.de/news/audi-setzt-auf-rotationsdaempfer-1230371.html`

**Comment by mapx-** [comment]
filter available for all adblockers
`@@||auto-motor-und-sport.de/werb.gif`

**Comment by reek** [comment]
already killed

**Comment by Jusix** [comment]
None of the two solutions works for me...

EDIT: `@@||auto-motor-und-sport.de/werb.php` seems todo the trick now

**Comment by mapx-** [comment]
add
```
@@|https://$image,domain=auto-motor-und-sport.de,third-party
@@/ad_bomb/*
@@||auto-motor-und-sport.de^$script
```
