### ISSUE TITLE
thehomestyle.co

### ISSUE THREAD

**Issue by 64bitguy** [reek/anti-adblock-killer#1921]
![www thehomestyle co](https://cloud.githubusercontent.com/assets/21000857/17640253/8ba7f338-60c1-11e6-97e3-ec7af9c0f9fb.png)

**Comment by SMed79** [comment]
add these filters: https://forums.lanik.us/viewtopic.php?f=62&t=32062

**Comment by 64bitguy** [comment]
Thanks!  

I even keyword searched for the url and still didn't find it... Sigh..must have gone wrong somewhere.. Appreciate the save!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
