### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by savinay4u** [reek/anti-adblock-killer#1922]
Please resolve this issue asap. 

This is the first link 

[(http://indianexpress.com/article/entertainment/movie-review/rustom-movie-review-akshay-kumar-ileana-d-cruz-star-rating-2970018/)]

This is the second link

[http://bollywood.bhaskar.com/news-hf/ENT-BNE-johnny-lever-birthday-home-inside-photos-news-hindi-5394727-PHO.html]

In this second link, website bypasses the killer scripts and detects the adblock plus. 

Please help me in this .

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=32059&hilit=indianexpress.com
https://forums.lanik.us/viewtopic.php?f=62&t=31290&hilit=bhaskar.com#p98839

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
