### ISSUE TITLE
indianexpress

### ISSUE THREAD

**Issue by Vacon1** [reek/anti-adblock-killer#1924]
When we go to this site and try to click on an article, it says you have ad-block and remove it.Please get me a solution please.

http://indianexpress.com

**Comment by SMed79** [comment]
/!\ use search https://github.com/reek/anti-adblock-killer/issues/1916
see https://forums.lanik.us/viewtopic.php?f=62&t=32059

**Comment by Vacon1** [comment]
Not working , tried on Opera - Safari - Chrome !!

Please update scripts !!

**Comment by sorathia82** [comment]
add this in adblock option->custom filter
@@||financialexpress.com$script,domain=indianexpress.com


Source :
https://justpaste.it/x8ps

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=101777#p101777

**Comment by reek** [comment]
Ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
