### ISSUE TITLE
rlsbb.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#193]
Near the top of rlsbb.com: rlsbb.com##H3

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

And making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by anonsubmitter** [comment]
* http://www.rlsbb.com/
* https://i.imgur.com/6sBoPSS.png
* Firefox 35.0.1
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.8
  * Malware Domains
  * Spam404
  * EasyList
  * Fanboy's Annoyance List
  * Prebake
  * Block-EU-Cookie-Shit-List
  * Adblock Warning Removal List
  * Anti-Adblock Killer
  * EasyPrivacy
  * Fanboy's Enchanced Tracking List

**Comment by maynak00** [comment]
www.rlsbb.com###contentArea > .information
optional (remove Become a VIP): www.rlsbb.com###contentArea > .entry.post:nth-of-type(4)

**Comment by anonsubmitter** [comment]
The "Become a VIP" part isn't really an Adblock notice though. But if reek wants to remove that whole box the "element code" is rlsbb.com##.information

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
