### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by namemenas** [reek/anti-adblock-killer#1931]
It is possible to open articles on 15min.lt, but after scrolling down the article screen overlay appears with message "you are using ad-blocker, we want your cash".

Examples:
http://www.15min.lt/sportas/naujiena/kita/simona-krupeckaite-ketvirtfinalyje-laimejo-pirma-kova-26-669771
http://www.15min.lt/sportas/naujiena/vandens-sportas/bresta-konfliktas-lietuvos-plaukimo-federacijos-vadovas-t-kucinskas-pazere-priekaistu-r-meilutytes-treneriui-863-669721

**Comment by mapx-** [comment]
add these filters in your adblocker

```
@@||15min.lt^$generichide
@@||15min.lt/js/ads
15min.lt###adocean_message
```

**Comment by namemenas** [comment]
Added, but it doesn't help.

**Comment by mapx-** [comment]
you have to use only 1 adblocker or other blocking extension (no ghostery, disconnect, ...)

what browser, adblocker are you using ?

**Comment by namemenas** [comment]
It doesn't work with disabled ghostery and kaspersky protection. 

Firefox 47, Adblock Plus 2.7.3.

**Comment by mapx-** [comment]
try installing the last dev build of ABP for firefox and test again
https://adblockplus.org/en/development-builds#installation

**Comment by namemenas** [comment]
It works with dev build of ABP and enabled ghostery.

It does not works with enabled Kaspersky Internet Security, even if I disable Kaspersky Protection add-on.

**Comment by aweiiy** [comment]
Ok I know a way how to bypass it. Add this to filters: abp://subscribe/?location=http://margevicius.lt/easylistlithuania.txt&title=EasyList%20Lithuania

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
