### ISSUE TITLE
politiken.dk

### ISSUE THREAD

**Issue by jd2806** [reek/anti-adblock-killer#1933]
![adblock](https://cloud.githubusercontent.com/assets/20338978/17713290/6c1606d6-63fa-11e6-9a43-2ec67d2edecf.png)

Safari
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add this filter in ABP
`@@||politiken.dk/*ad$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
