### ISSUE TITLE
strikeout.co

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#1934]
some ads are no longer blocked on strikeout.co

http://imgur.com/a/k1f61

Tamper monkey 
AAK list

**Comment by mapx-** [comment]
add these filters in your adblocker

```
||bpasyspro.com^
|http://*.aspx?y=$popup,domain=strikeout.co
||nfniziqm.com^
```

However, it works in firefox, chrome + ABP and ubo + ubo websocket companion.

**Comment by jeepy321** [comment]
thanks also i got an ad on the main vipleague.se homepage
http://imgur.com/a/4MsG7

**Comment by mapx-** [comment]
the filter above
||bpasyspro.com^

should block the ads on vipleague too
browser ? adblocker ? (versions ?)

**Comment by jeepy321** [comment]
chrome 52.0.2743.116 adblock plus 1.12.1

**Comment by mapx-** [comment]
as I told you above: you need the last dev build of ABP, see link above.

**Comment by jeepy321** [comment]
Ok thanks
