### ISSUE TITLE
http://www.5278bbs.com/forum.php

### ISSUE THREAD

**Issue by chiwodio** [reek/anti-adblock-killer#1935]
http://www.5278bbs.com/forum.php
http://imgur.com/a/6y56V
google chrome
tampermonkey
adblock

AdBlock 自訂過濾清單 +
EasyList +
中文 +
Adblock Warning Removal list (removes warnings about using ad blockers) +
EasyPrivacy (隱私保護) +
Fanboy's Annoyances (blocks in-page pop-ups, social media and related widgets, and other annoyances) +
反社群網站過濾器 （社群網站的按鈕會被自動過濾掉）+
惡意軟體防護 +
AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
