### ISSUE TITLE
tvgratuite.blogspot.com/

### ISSUE THREAD

**Issue by sam5335** [reek/anti-adblock-killer#1936]
/tvgratuite.blogspot.com/

**Comment by mapx-** [comment]
test this filter
`@@||pagead2.googlesyndication.com^$domain=tvgratuite.blogspot.com`

**Comment by sam5335** [comment]
this filter doesn't work. I have this message " L accès a ce site vous est temporairement interdit car vous bloquez les publicités" and after I'm redirected to  "http://lutteadblock.blogspot.com/2014/11/page-datterissage.html"

**Comment by sam5335** [comment]
I Think that the function jabbahud() should be disabled

**Comment by reek** [comment]
Can't help you
`Only guest readers have access to this blog`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
