### ISSUE TITLE
emuparadise.me

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#1937]
http://www.emuparadise.me/Super_Nintendo_Entertainment_System_(SNES)_ROMs/Super_Mario_World_(USA)/35787-download

http://imgur.com/a/j4PT2

Google Chrome 51.0.2704.106m
Tampermonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
