### ISSUE TITLE
yafud.pl

### ISSUE THREAD

**Issue by bartekmad** [reek/anti-adblock-killer#1938]
http://www.yafud.pl/
http://i.imgur.com/wyvNdFy.jpg
Google Chrome
Tampermonkey
Adblock
AakList + EasyList

**Comment by mapx-** [comment]
add these filters

```
@@||yafud.pl^$generichide
yafud.pl###adsense_banner_top
```

**Comment by bartekmad** [comment]
works, thanks;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
