### ISSUE TITLE
http://www.australianfrequentflyer.com.au

### ISSUE THREAD

**Issue by FatBoyNotSoSlim** [reek/anti-adblock-killer#1939]
**URL**
http://www.australianfrequentflyer.com.au/community/virgin-australia-velocity/new-va-fare-structure-77594.html
Uses https://blockadblock.com/

**IMG**
http://i.imgur.com/vSfTMlW.png

**Browser / OS**
Google Chrome on Mac OS X

**Script Manager**
Tampermonkey

**Adblocker**
uBlock Origin

**Lists**
 Adblock Warning Removal List‎ (forums.lanik.us)
 Anti-Adblock Killer | Reek‎  (github.com)
 EasyList‎ (forums.lanik.us)
 Peter Lowe’s Ad server list‎ (pgl.yoyo.org)

**Comment by mapx-** [comment]
add in ubo this filter
`@@||australianfrequentflyer.com.au^$generichide`

**Comment by FatBoyNotSoSlim** [comment]
Works a charm, many thanks.
