### ISSUE TITLE
New rules for some sites

### ISSUE THREAD

**Issue by isantolin** [reek/anti-adblock-killer#1947]
www.abchoy.com.ar##div#cacho-overlay
www.abchoy.com.ar##div#cacho-popup
www.abchoy.com.ar/publicidades/*
www.eldiariodetandil.com/contenido/publicidades/*
www.tandildiario.com/*banner*
www.lavozdetandil.com.ar/publicidades/*
nuevaeranet.com.ar/publicidades*
www.deportetandilense.com.ar/publicidades*

**Comment by mapx-** [comment]
You should report all these sites to easylist spanish forum:
https://forums.lanik.us/viewforum.php?f=103

**Comment by isantolin** [comment]
Uff. Sorry
