### ISSUE TITLE
www.juegosparaplaystation.com

### ISSUE THREAD

**Issue by xDarkARG** [reek/anti-adblock-killer#1949]
http://www.juegosparaplaystation.com/2015/01/god-of-war.html

**Comment by mapx-** [comment]
add in your custom filters

```
@@||juegosparaplaystation.com^$generichide
@@.png#$domain=juegosparaplaystation.com
```

if does not work provide details about browser, adblocker, filter lists

**Comment by xDarkARG** [comment]
funciona bien pero como haces para crear esos filtros algun tutorial que enseñe asi no molesto tanto y los saco yo

**Comment by mapx-** [comment]
read
https://adblockplus.org/en/filters

**Comment by reek** [comment]
fixed by easylit
