### ISSUE TITLE
ruutu.fi Adblock warning

### ISSUE THREAD

**Issue by Antsa92** [reek/anti-adblock-killer#1950]
Videos on ruutu.fi are blocked as long as the viewer uses an ad blocker and an Adblock warning is displayed. Sample page: http://www.ruutu.fi/video/2411224

**Comment by mapx-** [comment]
Did you test the filters here: https://forums.lanik.us/viewtopic.php?p=85493#p85493  ??
I see you posted in that thread.

**Comment by Antsa92** [comment]
Yes im tryed but not work. Can that add to Adblock Warning Removal List?

**Comment by reek** [comment]
no detected
