### ISSUE TITLE
www.climatempo.com.br

### ISSUE THREAD

**Issue by mauriciocolli** [reek/anti-adblock-killer#1954]
Using fuckAdblock, just block:
http://www.climatempo.com.br/climatempo/climatempo/js/vendor/blockblock.js

EasyList + Aak

**Comment by mapx-** [comment]
add these filters in your adblocker

```
@@||climatempo.com.br/*ad$script
||partner.googleadservices.com$script,domain=climatempo.com.br
@@||climatempo.com.br^$generichide
```

**Comment by reek** [comment]
fixed by easylist
