### ISSUE TITLE
blogs.timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by Y-1** [reek/anti-adblock-killer#1955]
http://blogs.timesofindia.indiatimes.com/talkingturkey/worrying-signs-tensions-between-morocco-and-mauritania-bad-for-north-africa/

http://imgur.com/a/zk4kj

Adblock

Chrome

TamperMonkey

Easylist+Aaklist+Adblock Protector+Filters:
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
@@||financialexpress.com$script,domain=indianexpress.com

Issue:
Page loads fine. The block message originates when I scroll the page.

**Comment by mapx-** [comment]
add

```
indiatimes.com##div[id^=google_ads_iframe]
indiatimes.com##div[id^=div-gpt-ad]
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script
```

**Comment by Y-1** [comment]
Success. Thanks to mapx for continued support for various issues.
