### ISSUE TITLE
https://www.zatnawqy.net

### ISSUE THREAD

**Issue by salgado1000** [reek/anti-adblock-killer#1956]
ublockorigin is detected

**Comment by mapx-** [comment]
it works fine here, tested: http://www.zatnawqy.net/Cy23f
what filters are enabled  ? did you update your lists ?

**Comment by salgado1000** [comment]
in ublock i have every filter updated and i use almost every filter disponible without regions and social

**Comment by mapx-** [comment]
I added every list without regions, every ublock list, working fine here.
Disable all other blocking extensions and test again.

**Comment by mapx-** [comment]
Did you enable  MVPS HOSTS ?

**Comment by salgado1000** [comment]
the problem was mvps hosts ty
