### ISSUE TITLE
www.publicleech.xyz

### ISSUE THREAD

**Issue by Linden10** [reek/anti-adblock-killer#1958]
http://www.publicleech.xyz/
http://i.imgur.com/FaZzcEu.png
Google Chrome
Tampermonkey
Adblock for Chrome
EasyList + AakList

I was using this site just fine until this happened.

BlockAdblock comes up after a few seconds on the site.
Observing the inspect window, the "banner-ad" div tag pops
up just a few seconds after the site is loaded and when it's
blocked by adblock, that screen comes up.

**Comment by mapx-** [comment]
add these filters in AB

```
@@||publicleech.xyz^$generichide
|http://$script,domain=publicleech.xyz
@@||publicleech.xyz^$script
@@||cloudflare.com^$domain=publicleech.xyz
@@.ico$domain=publicleech.xyz
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
