### ISSUE TITLE
kissanime.com

### ISSUE THREAD

**Issue by MuLTiGuY** [reek/anti-adblock-killer#196]
http://kissanime.com/Anime/Kiseijuu-Sei-no-Kakuritsu/Episode-019?id=87100
http://imgur.com/u0oxHxZ
Mozilla Firefox / Google Chrome (I tested both)
Adguard built-in extension manager
Adguard
Adguard filters + Anti adblock killer | Reek

P.S 
I think antiblock.org updated their stuff, so maybe that's why.

**Comment by reek** [comment]
Hi,

You need use Greasemonkey (Firefox) or Tampermonkey (Chrome)

AAK dont work with AdGuard
