### ISSUE TITLE
8muses.com

### ISSUE THREAD

**Issue by Metapod1331** [reek/anti-adblock-killer#1960]
https://www.8muses.com/ nsfw

http://i.imgur.com/EUH17FN.jpg
Firefox 48.0.1
GreaseMonkey 3.9
Adblock Plus + Noscript
EasyList + AakList

As of a few days ago every other screen is that Adblock warning screen. This was also the case when I tested the site in Chrome with only Adblock Plus, tampermonkey, AAK, and the same lists enabled

**Comment by mapx-** [comment]
try these filters

```
@@||8muses.com^$generichide
@@||ads.exoclick.com^$domain=8muses.com
```

eventually disable noscript if does not work

**Comment by Metapod1331** [comment]
Adding that second filter (already had the first one)  and a little tweaking seem to have done the trick. Thank you  

Anyone else having this problem I had to add those two filters above, allow exoclick.com in NoScript, and disable tracking protection in Firefox

**Comment by reek** [comment]
I'll fix it again

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
