### ISSUE TITLE
It does not work on any of the following news websites.

### ISSUE THREAD

**Issue by shashankitsoft** [reek/anti-adblock-killer#1961]
Reek - anti-adblock-killer does not work at all on any of the following news websites. Below sites detects adblock plus even if  reek anti-adblock-killer enabled, and so they block the contents, not able to read without adding these sites in whitelist of the adblock plus.

timesofindia.indiatimes.com
ndtv.com
hindustantimes.com
indianexpress.com
khabar.ndtv.com
indiatoday.intoday.in
navbharattimes.indiatimes.com
rediff.com

Following sites also detect adblock's presence, even if reek anti-adblock-killer enabled.
irctc.co.in
aircel.com
speedtest.net

**Comment by mapx-** [comment]
indiatimes: https://forums.lanik.us/viewtopic.php?p=101024#p101024

**Comment by mapx-** [comment]
ndtv: https://forums.lanik.us/viewtopic.php?p=100969#p100969

**Comment by mapx-** [comment]
indianexpress, update easylist should work

**Comment by mapx-** [comment]
intoday: add these filters
```
intoday.in#@#a[href*=".zedo.com/"]
intoday.in#@#.right-ad
@@||zedo.com^$image,domain=intoday.in
indiatoday.intoday.in###aswift_0
indiatoday.intoday.in###aswift_2
@@||media2.intoday.in^$script
```

**Comment by mapx-** [comment]
hindustantimes:
`@@||hindustantimes.com^$script`

**Comment by shashankitsoft** [comment]
Thanks @mapx-  for the awesome solutions worked for most sites. :)

hindustantimes filter and indianexpress after updating easylist still not working.
timesofindia.indiatimes.com worked but navbharattimes.indiatimes.com not working.

Kindly, make some solutions for these rest too.

A suggestion: Reek team should have an online documentation for filters for some common sites, and update filter codes as when needed, reported and fixed. Will be useful for all your users.

Thanks.

**Comment by mapx-** [comment]
indianexpress add the filters here:
https://forums.lanik.us/viewtopic.php?p=101777#p101777

hindustantimes: add these filters
```
@@||hindustantimes.com^$generichide
@@||partner.googleadservices.com^$script,domain=hindustantimes.com
@@||doubleclick.net^$script,domain=hindustantimes.com
```

indiatimes add these filters

```
indiatimes.com##div[id^=google_ads_iframe]
indiatimes.com##div[id^=div-gpt-ad]
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script
```

**Comment by shashankitsoft** [comment]
Thanks again for the solutions. :)
Indiatimes worked.

```
The following filter:
@@||hindustantimes.com^$generichide 
has an error: 
Unknown option 'generichide' in filter '@@||hindustantimes.com^$generichide'
```

Similar error came for NDTV filter, while saving it, I had to remove  'generichide' line and saved rest part. 


**Any tutorial to guess about the command and filter to write on our own for different sites,** rather than asking for specific sites? **An online documentation of syntaxes with their explanations and examples to write filters** for sites will be great help, how to do.

Anyways, your reek plugin and solutions are great @mapx- Keep it up!

**Comment by mapx-** [comment]
$generichide keyword is supported by ABP firefox / chrome, AB chrome (from version 3). 
Probably you are using some old version.

About filters:
https://adblockplus.org/en/filters
https://adblockplus.org/en/filter-cheatsheet

**Comment by shashankitsoft** [comment]
Amazing support @mapx- :))
Thanks, I updated ABP to latest 3.1.1. (I was at 2.5.x which was not showing updates, uninstalled and then reinstalled latest)

Also thanks for the links, will study these to learn in time.  Keep up the good work!

**Comment by mapx-** [comment]
you are using AB and not ABP :)
(however AB is using ABP engine so ... you could use it directly because the last issues are fixed / new features are first added in ABP.

ABP: https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb

and never use 2 adblockers !

**Comment by reek** [comment]
done
