### ISSUE TITLE
http://www.visionfansub.com.br/episodios/25/diamond-no-ace/

### ISSUE THREAD

**Issue by Ronam22** [reek/anti-adblock-killer#1963]
http://www.visionfansub.com.br/download/92/url37/diamond-no-ace/
http://i.imgur.com/ssxgVA8.png
Chrome
Tampermonkey
Adblock
Easylist and AakList (Anti-Adblock Killer)

Trying to download something redirect to a "turn off adblock"

**Comment by mapx-** [comment]
add this filter
`@@||jogosincriveis.com/*ad$script`

**Comment by Ronam22** [comment]
Thanks for the help

**Comment by reek** [comment]
already killed by AakList
