### ISSUE TITLE
thevideobee.to 

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#1965]
ads before pressing proceed to video 
have anti adblock killer enabled 
example link 
https://thevideobee.to/nt17ixpzplkf.html

**Comment by mapx-** [comment]
https://adblockplus.org/forum/viewtopic.php?p=157438#p157438

**Comment by jeepy321** [comment]
thanks

**Comment by ghajini** [comment]
turn on no popup in ublock origin
