### ISSUE TITLE
Times Of India website

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [reek/anti-adblock-killer#1966]
Have tried using many filters referred here. Works for most Indian media sites except Times of India: timesofindia.indiatimes.com

Anyone has been able to crack this?

My filters with Adblock Plus is: 

@@||financialexpress.com$script,domain=indianexpress.com
@@||indiatimes.com^$generichide
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=timesofindia.indiatimes.com
@@||hindustantimes.com^$script
@@||zedo.com^$image,domain=intoday.in
@@||media2.intoday.in^$script
@@||ndtv.com^$elemhide
@@||zedo.com^$script,domain=ndtv.com
@@||ndtv.com^$script,domain=ndtv.com
@@||ads.rubiconproject.com$script,domain=ndtv.com
intoday.in#@#a[href_=".zedo.com/"]
intoday.in#@#.right-ad
indiatoday.intoday.in###aswift_0
indiatoday.intoday.in###aswift_2
||taboola.com^
indiatimes.com##div[id^=google_ads_iframe]
indiatimes.com##div[id^=div-gpt-ad]
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/_ad$script

**Comment by mapx-** [comment]
working filters (for me) in ABP for firefox or ABP for chrome

```
indiatimes.com##div[id^=google_ads_iframe]
indiatimes.com##div[id^=div-gpt-ad]
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script
```

tested page:
http://timesofindia.indiatimes.com/sports/rio-2016-olympics/Telangana-ministers-offer-A-better-coach-for-Sindhu-to-win-gold-in-2020/articleshow/53808954.cms

**Comment by vijayaraghavanramanan** [comment]
Not for me :-(

http://i.imgur.com/lANXsOv.png

**Comment by mapx-** [comment]
disable all other blocking addons, keep only ABP. (disable also tampermonkey temporarily to test the issue)

**Comment by vijayaraghavanramanan** [comment]
Many thanks. Tried it but TOI still detected ABP. 

(I am using Chrome 52 on Windows 8/ABP/Tampermonkey/Reek).

**Comment by reek** [comment]
done
