### ISSUE TITLE
paris.onvasortir.com

### ISSUE THREAD

**Issue by Lanvin2219** [reek/anti-adblock-killer#1968]
http://paris.onvasortir.com/ovsadblock.php
http://imgur.com/5bYMQP0
Google Chrome
Tampermonkey (AAK script activated)
uBlock Origin v1.8.5.100 (AAK subscribed)
EasyList (66559) + AAK (2009) + Adblock Warning Removal List (212) + Peter Lowe's Ad server list (2367)

**Comment by mapx-** [comment]
add this filter
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=onvasortir.com`

**Comment by Lanvin2219** [comment]
Thanks a lot, it works !

**Comment by Orion2222** [comment]
Hi, very interested by this answer, but where do you add the filter ? I am using Adblock Plus, uBlock Origin, GreaseMonkey, etc. Where to add the line ? Thanks a lot !

**Comment by mapx-** [comment]
don't use 2 adblockers or other blocking extensions (for example remove ghostery - easyprivacy list replaces it in any adblocker)

for ABP see how to add custom filters: https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

if instead you decide to keep ubo: right click ubo icon, options, "my filters"

**Comment by Orion2222** [comment]
Thanks, mapx. I have Adblock plus on Firefox, and UBO on Cyberfox. I already tried to add the filter in ABP (http://image.noelshack.com/fichiers/2016/34/1471965181-filtre.jpg), but I always get the http://paris.onvasortir.com/ovsadblock.php page when I load the site. I am going to try also with UBO.

**Comment by mapx-** [comment]
for firefox try the last dev build 
https://addons.mozilla.org/downloads/latest-beta/adblock-plus/adblockplus-devbuild.xpi

**Comment by Orion2222** [comment]
Same problem with UBO and Cyberfox : http://image.noelshack.com/fichiers/2016/34/1471966333-ubo.jpg
I will try installing Chrome and ABP on a virtual machine and see if it works.

**Comment by Orion2222** [comment]
It works on the VM using Chrome. Thanks a lot, mapx !

**Comment by Lanvin2219** [comment]
Tu peux enfin aller sur OVS tranquillement :p

**Comment by bluesangel** [comment]
Ca ne marche pas pour moi  / It does not work for me. 
Ils ont modifié leur détecteur ? Did they adpat their adblock killer ?

**Comment by mapx-** [comment]
these filters still work (be sure 2 add 2 filters and not only 1)
also, use only 1 blocking extension, not other like ghostery, disconnect, anti banner ...
```
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=onvasortir.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=onvasortir.com
```

**Comment by bluesangel** [comment]
Thanks maxp!  I undertand now : for some (unknown) reason, the access is not working in private browsing - but is ok in normal window. Real strange !

**Comment by mapx-** [comment]
if in chrome be sure to check "allow in incognito" for your adblocker

**Comment by bluesangel** [comment]
I use for Firefox - I'm aware of the issue with extensions with Chrome . Normally there is nothing to change on Firefox. Quite strange!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Lanvin2219** [comment]
I think it doesn't work anymore
