### ISSUE TITLE
onvasortir.com

### ISSUE THREAD

**Issue by Dusteuh** [reek/anti-adblock-killer#1970]
http://montpellier.onvasortir.com/ovsadblock.php
http://imgur.com/uqJhgX9
Google Chrome
Tampermonkey
Adblock Plus
Adblock Warning Removal List + Liste FR+EasyList + EasyPrivacy + Fanboy's Social Blocking List + AakList (Anti-Adblock Killer)

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1968#issuecomment-241433047

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Lanvin2219** [comment]
Hello,
Is it only me or it doesn't work anymore ?
