### ISSUE TITLE
Times of India

### ISSUE THREAD

**Issue by jatsir96** [reek/anti-adblock-killer#1972]
http://timesofindia.indiatimes.com/tech/tech-news/Reliance-Industries-warns-COAI-of-legal-action/articleshow/53814328.cms
Chrome
Tapermonkey
Adblock Plus
EasyList + AakList
![screenshot 185](https://cloud.githubusercontent.com/assets/14803451/17864903/951b3e8a-68bd-11e6-8bb6-c944cdd4e428.png)

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1966#issuecomment-241375428

**Comment by ghajini** [comment]
use only one adblocker
you can use ublock origin

**Comment by reek** [comment]
done
