### ISSUE TITLE
topserialy.sk again

### ISSUE THREAD

**Issue by viktorjezekcz** [reek/anti-adblock-killer#1976]
**Link page contains anti-adblock:** for example http://bit.ly/1tdG8ga
**One screenshot:** https://ctrlv.cz/xXzX
**My browser:** Google Chrome and Mozilla Firefox in the their newest version
**My script manager:** Tampermonkey in Chrome and Greasemonkey in Firefox
**My adblocker:** AdBlock Plus v1.12 in Chrome and AdBlock Plus v2.7.3 in Firefox
**My filterlists:** https://ctrlv.cz/72LK (Chrome) and https://ctrlv.cz/dV6X (Firefox)

Anti adblock Killer doesn't work on topserialy.sk again,

**Comment by mapx-** [comment]
I get this message

```
Ľutujeme, ale nachádzate sa v oblasti, z ktorej je sledovanie videí
z bezbečnostných dôvodov zablokované.
Pre prístup k videám sa prosím zaregistrujte (bezplatne).
```

anyway, see if this filter does help you:
`@@||topserialy.sk^$script`

**Comment by koboltzz** [comment]
mapx-
You do some nice work here (of course big respect for reek (especially) and X01X012013 too).
What do you think about 
1. put your filter suggestions in a new ruleset everybody can apply in ubo
2. I will create a new filter.txt and publish it if you agree

**Comment by mapx-** [comment]
well, for filters the main place would be easylist forum: http://forums.lanik.us/ where I published (under other nickname) all these filters too and ... 90% of them are then included (by the authors) in easylist

**Comment by koboltzz** [comment]
Yeah I saw someone 'intense' there ;)
I was thinking about the missing 10%, filling the gap between Aaklist and easylist.

**Comment by mapx-** [comment]
for the filters still out of easylist could be used the "ublock filters" list / uAssets
https://github.com/uBlockOrigin/uAssets/issues

**Comment by koboltzz** [comment]
Yes that's right but even there are things like
`indiatimes.com##div[id^=google_ads_iframe]
indiatimes.com##div[id^=div-gpt-ad]
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script`
not uptodate.
Thank you for your work never the less and keep on :)

**Comment by mapx-** [comment]
oh, indian sites ...well, gorhill already added specific workarounds for ubo (userscripts ...) for many of them

**Comment by koboltzz** [comment]
Well, as far as I know ublock do not apply double filter.
YOUR filter suggestions added by me here [https://raw.githubusercontent.com/koboltzz/filterlist/master/anti-adblock-killer-filters-koboltzz.txt](url)
This and easylist+uassets uptodate, result is 49 of 50 are used. Therefore 49 entries are missing in easylist and uassets.

**Comment by viktorjezekcz** [comment]
@koboltzz:

>  YOUR filter suggestions added by me here https://raw.githubusercontent.com/koboltzz/filterlist/master/anti-adblock-killer-filters-koboltzz.txt

Page not found.

**Comment by koboltzz** [comment]
Check your Browser adress bar after selecting my link. You will see github is not linking correctly. 
Solution : Just copy my link text and paste it in your adress bar or ublock and it will work.

**Comment by viktorjezekcz** [comment]
Thank you for your help. Video playing is now working with activate adblock again.

**Comment by reek** [comment]
I'll fix it
