### ISSUE TITLE
Zmovies - Microsoft warnings and other popups

### ISSUE THREAD

**Issue by Silrak** [reek/anti-adblock-killer#1980]
Z movies has many sites under its belt that host and provides ability to stream movies. Many of which numerous pop ups, and take control of the browser in some instance. Most can be blocked but the one that is most bothersome is the Microsoft fraud advert that will control the browser and continueously reopen depite "do not allow page to create new dialog". Please visit the site zmovies.tw and go around the different links to see about which you can fix. 

Thanks.

**Comment by mapx-** [comment]
probably you mean zmovie.tw and not zmovieS.tw

add this filter see if helps, otherwise provide more specific pages / links

`||iu1xoe7o.com^`

**Comment by Silrak** [comment]
Hi thanks. How and where do I add the filter please? Also, it is across all the sites pretty much (in excess of 20 sites). Varying pop ups and the microsoft alert. I can give all links and issues but going to some movies in these sites with your settings, might be better, and be most efficient way to resolve the issue in one foul swoop, as they could all be blocked by one code for example? 

Please note most of these links worked in the past, most ads were able to beblocked maybe until adblock was removed from google play, and I used to be able to click the red x hide the ads button and watch the movie. This is no longer the case. These same adds are else where on the net, ie putlocker etc. Also, The links I provide are just for one movie, but for the sites holding the movie most ads are the same.


Lastly would you consider an option to block being asked for location from these sites or in general from chorme/websites? Thanks.


Anyway, http://www.zmovie.tw/search is the big issues on movie redirects. There is an invisible page that causes a pop up, and on links to movie databases from zmovies there is more pop ups on first click on the site. 
Sites include but not limited to the following: 

http://vidshark.ws/rc.php?Id=f785929fd90cbcc4a73836f5fdeea34c (see images if not closed window proper way more pop up)
![image](https://cloud.githubusercontent.com/assets/21222984/18230645/c96432d2-72e5-11e6-998b-44afd05e2585.png), 

from http://neovid.me/play/74a86b286f67274e96fd42602f827f11/ there was atleast 5 unique pop ups, and no way to proceed to the movie ( I could in the past) http://fillyourpockets.co/makemoney/1/?ept2=f04fc751-a73f-4d2a-a2dd-df32cfb0bec7. 

Hawk hd link has a grunggo add overlay, cannot see how to close it and unique pop ups > http://intl.7112629.com/REI495slmAU.html.

There is more than 15 more sites to try and maybe more, it depends on the video etc. I imagine if you can somehow resolve the issue above in general it could be resolved accross the board. Also I will try to add the filter once I know how. 


Version: 9.8 
AakScript: true 
AakList: true 
Browser: Chrome 
ScriptManager: Tampermonkey

http://hdwide.co/pc/33027e6b22dc8b19/ (is inactive and you cannot proceed to the movie via human verification which might not be your issue - it used to work (my two addblocks are disabled and the page was refreshed). The same problem from storm video (http://stormvid.co/pc/13c2409a74ff5336/) but it opened http://bngzz.exclusiverewards.7113837.com/?sov=2774399647&hid=hpjlhpnltpvljxjp&redid=35817&gsid=68&campaign_id=29&id=XNSX.-r35817-t68.
.

**Comment by Silrak** [comment]
P.s I run adblock, adblock plus and anti adblock killer. The first two used to be more than enough. These sites and more online have definately changed the way they navigate adblocks. I'm so FN sick of C***S online with rediculous nonsense ads like on these sites. Thanks for all the help and attention to the matter.

**Comment by mapx-** [comment]
how to add the custom filters for ABP:
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

Never use 2 adblockers, only 1 (ABP).

**Comment by mapx-** [comment]
for zmovie add:
```
about:blank$popup,domain=zmovie.tw
||watch?key=$popup
```

**Comment by mapx-** [comment]
for neovid:
```
||neovid.me^$script
||windows.net^$domain=neovid.me
neovid.me###overlayVid
@@||neovid.me/swfobject.js
```

**Comment by mapx-** [comment]
hdwide:

```
||hdwide.co^$script
@@||hdwide.co/swfobject.js
hdwide.co###overlayVid
about:blank$popup,domain=hdwide.co
||windows.net^$domain=hdwide.co
```

**Comment by mapx-** [comment]
stormvid.co
```
||stormvid.co^$script
@@||stormvid.co/swfobject.js
stormvid.co###overlayVid
about:blank$popup,domain=stormvid.co
||windows.net^$domain=stormvid.co
```
