### ISSUE TITLE
bangaloremirror.com

### ISSUE THREAD

**Issue by glennsamuel32** [reek/anti-adblock-killer#1981]
http://www.bangaloremirror.com/blocked.cms

It is now the turn of Bangalore Mirror to screw us !!!
Times of India is still blocked with @reek script...

**Comment by mapx-** [comment]
add these filters

```
@@||bangaloremirror.com/*ad$script
@@||partner.googleadservices.com^$domain=bangaloremirror.com
@@||clmbtech.com^$script,domain=bangaloremirror.com
@@||crwdcntrl.net^$script,domain=bangaloremirror.com
@@||bangaloremirror.com^$generichide
@@$image,domain=bangaloremirror.com
@@||timesinternet.in^$script,domain=bangaloremirror.com
@@||timestrends.indiatimes.com$script
@@||b.scorecardresearch.com/beacon.js$script,domain=timesofindia.indiatimes.com
@@||b.scorecardresearch.com/beacon.js$script,domain=bangaloremirror.com
```

for indiantimes 
https://forums.lanik.us/viewtopic.php?p=101220#p101220

**Comment by glennsamuel32** [comment]
Muchos gracias amigos !!!
Works perfectly with uBlock :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
