### ISSUE TITLE
politiken.dk

### ISSUE THREAD

**Issue by varmemester** [reek/anti-adblock-killer#1982]
http://www.politiken.dk
http://imgur.com/7WHG8Dd
Chrome
Tampermonkey BETA
Easylist+AakList

**Comment by mapx-** [comment]
use search:
see
https://github.com/reek/anti-adblock-killer/issues/1933#issuecomment-240215958

or use search directly on easylist forum:
https://forums.lanik.us/viewtopic.php?p=100595#p100595

**Comment by varmemester** [comment]
Thx 👍

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
