### ISSUE TITLE
NSFW  http://gaybeeg.info/

### ISSUE THREAD

**Issue by jcmags91** [reek/anti-adblock-killer#1986]
http://gaybeeg.info/
![image](https://cloud.githubusercontent.com/assets/21250571/17988108/1b2f8e3c-6af2-11e6-8c01-be5b167d8efb.png)
Chrome
Tamper Monkey
ABP
Easylists

Can get the pop-up away but links to download are not active

**Comment by mapx-** [comment]
add NSFW in the title for such terrible pages

add this filter
`gaybeeg.info##.msc-confirm`

**Comment by mapx-** [comment]
for such sites add in the title NSFW !

add these filters in your adblocker
```
@@||gaybeeg.info^$generichide
@@||exoclick.com^$script,domain=gaybeeg.info
|http://$script,domain=gaybeeg.info
@@||gaybeeg.info^$script
```

**Comment by jcmags91** [comment]
Thanks for the reply, these filters did not work and other suggestions

**Comment by mapx-** [comment]
adblocker ?
browser (version)?
filter lists enabled in your adblocker ?

Don't use more blocking extensions, only your adblocker (no ghostery, no disconnect, no anti banner ...)

**Comment by jcmags91** [comment]
Adblock plus
Google chrome 52.0.2743.116
Easylists
No other extentions

**Comment by mapx-** [comment]
```
@@||exoclick.com^$script,domain=gaybeeg.info
@@||gaybeeg.info^$generichide
@@||netdna-storage.com^$generichide
@@||s3.amazonaws.com^$domain=gaybeeg.info
||azeozrjk.com^
||cloudfront.net/_$domain=gaybeeg.info
||negdrvgo.com^
@@||popads.net^$script,domain=gaybeeg.info
@@||popcash.net^$script,domain=gaybeeg.info
```

**Comment by jcmags91** [comment]
Working now, thanks so much

**Comment by reek** [comment]
already killed by AakScript
