### ISSUE TITLE
http://www.business-standard.com/

### ISSUE THREAD

**Issue by Y-1** [reek/anti-adblock-killer#1988]
http://www.business-standard.com/article/economy-policy/maharashtra-govt-proposes-subsidy-for-onion-farmers-116082600541_1.html

http://imgur.com/a/VFaOd

Adblock

Chrome

TamperMonkey

Easylist+Aaklist+Adblock Protector

**Comment by mapx-** [comment]
add
`@@||business-standard.com/*ad$script`

**Comment by Y-1** [comment]
Thanks! Do you have any idea about when these websites (Times of India, Indiatimes etc) will be taken care of in the reek script and we wouldn't have to add manual filters for them everytime?

**Comment by mapx-** [comment]
No idea ... only Reek could respond.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
