### ISSUE TITLE
mp3juices.cc 

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#1989]
ad comes through on homepage  says download play now
![screen shot 2016-08-26 at 4 03 40 pm](https://cloud.githubusercontent.com/assets/21069588/18022792/b58e3230-6ba6-11e6-8506-14adb5f3d617.png)

**Comment by mapx-** [comment]
`@@||mp3juices.cc/*ad$script`

**Comment by jeepy321** [comment]
thanks

**Comment by matthew-asuncion** [comment]
Most free music sites have alot of annoying ads / popups but I use [MP3Skulls](https://mp3skulls.li/) due to less ads and better bitrate.
