### ISSUE TITLE
tv3play.no

### ISSUE THREAD

**Issue by krize604** [reek/anti-adblock-killer#199]
Link: http://www.tv3play.no/programmer/luksusfellen/556737?autostart=true
Screenshot: http://i.imgur.com/L0psk1Q.jpg
    Your browser Firefox 35.01
    Your script manager Greasemonkey 2.3
    Your adblocker AdbLock Plus 2.6.7
    Your filterlists: Easylist, RuAd-Easylist, Abp-Indo Easylist, Antiadblock killer, Norsk adblockliste, Adblock warning removal list.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by krize604** [comment]
Yeah i will consider a donation, but it was closed no solution ? It looks like the exact same setup as the already fixed tv3play.se ? Thanks and greetings

**Comment by reek** [comment]
Hi,
I can not help you because I have the following message "Programmet är blockerat från att visas från denna geografiska position".

**Comment by n0rpan** [comment]
Hi Reek! If i donate for a couple of month with: https://unlocator.com/channel/tv3-norge/ would you take a closer look? Thanks! (Unlocator makes it possible to watch tv3play.no from anywhere in the world)

**Comment by reek** [comment]
Hi,

Yes, it will allow me possibly to find a solution
You can send to http://reeksite.com/contact.php

Regards
Reek

**Comment by n0rpan** [comment]
Hi!
Subscription sent!
Thanks.

**Comment by reek** [comment]
Hi,

@n0rpan 
I tried to find a solution but I have not succeeded , the only solution is to allow the video ad

Here are the rules to add in your adblocker
<code>@@||5d3e9.v.fwmrm.net/ad/l/1*$object-subrequest,domain=tv3play.no</code>
<code>@@||5d404.v.fwmrm.net/ad/p/1$object-subrequest,domain=tv3play.no</code>
<code>@@||adm.fwmrm.net/p/MTG_Live/ExternalHTMLAdRenderer.swf$object-subrequest,domain=tv3play.no</code>
<code>@@||adm.fwmrm.net/p/MTG_Live/Video2AdRenderer.swf$object-subrequest,domain=tv3play.no
</code>

Thank you for sharing unlocator.com

Regards
Reek
