### ISSUE TITLE
Timesofindia on android

### ISSUE THREAD

**Issue by sangalaviral** [reek/anti-adblock-killer#1990]
Example url :http://m.timesofindia.com/city/delhi/No-money-for-refunds-says-Parsvnath/articleshow/53880132.cms

Redirects to blocked.cms

**Comment by ghajini** [comment]
just use ublock origin on firefox for android
@gorhill is actively developing ublock origin

https://github.com/uBlockOrigin/uAssets/issues/104

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
