### ISSUE TITLE
Youwatch

### ISSUE THREAD

**Issue by hanjo42** [reek/anti-adblock-killer#1991]
Hi,
Aak don't work on youwatch. or maybe i don't know how to use it. i have the last version of grease monkey and the script Aak activated and up to date & Adblock + with the Aak list all activated and up to date. but youwatch always detect me

**Comment by mapx-** [comment]
add these filters
```
@@||smed79.info/js/
||zidor.info^
smed79.info###iframebanner
||smed79.info/prope.html$popup
||smed79.info/moda1.html$popup
```

**Comment by hanjo42** [comment]
i must add this a the end of : " anti-adblock-killer-filters.txt " and load it ?

**Comment by mapx-** [comment]
no, just add those filters in your custom filters

**Comment by hanjo42** [comment]
ok thanks

**Comment by hanjo42** [comment]
it doesn't work

**Comment by mapx-** [comment]
use only 1 blocking extension (1 adblocker, no ghostery, disconnect, anti banner ...)
what adblocker are you using ? (version)
filter lists ?
browser ? (version)

**Comment by hanjo42** [comment]
"No script" & "Https Everywhere" must be deactivated ?
 My blocker is Adblock plus (last version) with "A.A.K List" & "Liste Fr + Easy List".
And I use Firefox 48.0.2

**Comment by mapx-** [comment]
disable NoScript or whitelist youwatch / smed79 in NoScript.
If still does not work, keep only ABP enabled and add 1 by 1 the other addons to find the culprit.

**Comment by hanjo42** [comment]
Ok Thanks,  I'll keep you informed .
bye

**Comment by hanjo42** [comment]
i've deactivated all extension except adblock & greasemonkey and i does not work. adblock is detected

**Comment by mapx-** [comment]
yes, because they replaced smed79 by rienlol

add
```
@@||rienlol.info/js/
||zidor.info^
rienlol.info###iframebanner
||rienlol.info/prope.html$popup
||rienlol.info/moda1.html$popup
```

when you see the new hostname in the address line you can just replace with the new one

**Comment by reek** [comment]
Hi,

Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
