### ISSUE TITLE
al.ly

### ISSUE THREAD

**Issue by petarster** [reek/anti-adblock-killer#1996]
Please check this http://al.ly/Kxu6X --> http://al.ly/static/fuckadblock.min.js
its not bl.ocked
http://i.imgur.com/NxXK1sa.png

can you update this because they are going 1 step ahead of us

**Comment by X01X012013** [comment]
The screenshot looks like BlockAdblock...

**Comment by SMed79** [comment]
**ally** see > https://forums.lanik.us/viewtopic.php?p=98106&hilit=al.ly#p98106

**Comment by reek** [comment]
done
