### ISSUE TITLE
jetetroll.com

### ISSUE THREAD

**Issue by Ke0zom** [reek/anti-adblock-killer#200]
Link page contains anti-adblock : http://www.jetetroll.com/
Screenshot : http://i.imgbox.com/exWVD7kX.jpg
Browser : Google Chrome
Script manager : Tampermonkey
Adblocker : Adblock Plus
Filterlists :
- Adblock Warning Removal List
- Anti-Adblock Killer
- EasyPrivacy
- Fanboy's Social Blocking List
- Liste FR+EasyList
- Malware Domains

Thanks

**Comment by alexander255** [comment]
This is a bug in EasyList and has been reported at https://forums.lanik.us/ (post are unfortunately not public before being moderated).
In the meantime you can open the AdBlock filter options, select "Liste FR+EasyList", search for the filter `###adsense` and disable it.

**Comment by alexander255** [comment]
Fixed upstream: https://forums.lanik.us/viewtopic.php?f=91&t=21152 and https://hg.adblockplus.org/listefr/rev/5fabcb6d913f

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Ke0zom** [comment]
Oh yeah.. Really thanks !!!
