### ISSUE TITLE
360haven.com

### ISSUE THREAD

**Issue by Player701** [reek/anti-adblock-killer#2000]
1. http://www.360haven.com/forums/register.php
2. http://imgur.com/a/eL4mH
3. Firefox 47.0.1
4. Tampermonkey
5. uBlock Origin 1.9.2
6. AakList + EasyList + Peter Lowe's Ad Server List + RU AdList

The anti-adblock warning appears after passing captcha verification. Sometimes it can appear in other cases literally out of nowhere; exact actions that cause it have not been determined.

**Comment by uBlock-user** [comment]
`@@||ads.360haven.com/Adserver/js/gshowad.js`

**Comment by Player701** [comment]
Thanks, but it doesn't seem to change anything.

(I have also made sure that I have all other extensions except Tampermonkey and uBlock disabled)

**Comment by mapx-** [comment]
just disable ubo when register the account and then enable again ubo and add:
`@@||360haven.com/*ad`

**Comment by Player701** [comment]
Well, disabling the ad blocker kind of defeats the purpose of this project, but at least I have been able to register this way. Still hoping this issue will be addressed in the future. Thanks.

**Comment by mapx-** [comment]
when you want to register a new account on that forum does not help.

**Comment by uBlock-user** [comment]
It's triggering here you mean - http://www.360haven.com/forums/register.php?do=checkdate ?

**Comment by mapx-** [comment]
I mean if you follow all the steps for registering (after the captcha thing) you'll get the anti adblocking message. You have to whitelist a lot of elements (even subdocument stuff), so ... it's useless because after registering all will work using only:

`@@||360haven.com/*ad$script`

**Comment by uBlock-user** [comment]
Hmmm, lets wait for reek to come up for a better fix, he doesn't seem to be active lately.

**Comment by mapx-** [comment]
sure, I'm talking only about normal filters. However, for the guys already with registered accounts the simple filter above is the necessary fix.

**Comment by gorhill** [comment]
If you are using uBO, use:

    360haven.com##script:inject(bab-defuser.js)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
