### ISSUE TITLE
http://www.lasprovincias.es

### ISSUE THREAD

**Issue by eXPerience83** [reek/anti-adblock-killer#2003]
http://www.lasprovincias.es/sucesos/201608/28/desaparecida-chica-anos-valencia-20160828213535.html
http://imgur.com/a/N8IOe
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by mapx-** [comment]
use search:
https://github.com/reek/anti-adblock-killer/issues/1785#issuecomment-234491019

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
