### ISSUE TITLE
www.business-standard.com

### ISSUE THREAD

**Issue by gauravsaini** [reek/anti-adblock-killer#2008]

**Comment by uBlock-user** [comment]
Add - `@@||bsmedia.business-standard.com/include/_mod/site/adblocker/$script`

**Comment by mapx-** [comment]
use search:
https://github.com/reek/anti-adblock-killer/issues/1988#issuecomment-242858851

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
