### ISSUE TITLE
http://www.ndtv.com/

### ISSUE THREAD

**Issue by vikramn89** [reek/anti-adblock-killer#2009]

**Comment by mapx-** [comment]
add the filters here:
https://forums.lanik.us/viewtopic.php?p=100969#p100969

**Comment by anirbandd** [comment]
@mapx- this is added to my filters. 
it isnot working. can you please suggest?

**Comment by mapx-** [comment]
the last filters in that thread still working
https://forums.lanik.us/viewtopic.php?p=102789#p102789

If still does not work for you, provide info: browser, adblocker, filter lists, example link.

**Comment by reek** [comment]
done
