### ISSUE TITLE
forum.lolesporte.com

### ISSUE THREAD

**Issue by marcusbataglia** [reek/anti-adblock-killer#201]
http://forum.lolesporte.com/aovivo/
http://i.imgur.com/kTbOL5N.jpg
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by alexander255** [comment]
This script should fix it: http://pastebin.com/raw.php?i=7HGR6t1z

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/197
