### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghajini** [reek/anti-adblock-killer#2010]
www.business-standard.com
i used this one script
@@||business-standard.com/*ad$script

now on
http://hindi.business-standard.com
still detecting ad blocker
though i used above script

**Comment by mapx-** [comment]
add

```
business-standard.com#@##ad468
business-standard.com#@##wideAdd
business-standard.com#@##rightadpat
business-standard.com#@##adSense
business-standard.com#@##adsense
business-standard.com#@##outsideAds
business-standard.com#@##ad_160x160
business-standard.com#@##adrect
business-standard.com#@##adsIfrme4
@@||business-standard.com/*ad$script
@@||hindi.business-standard.com/images/$image
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
