### ISSUE TITLE
15min.lt

### ISSUE THREAD

**Issue by aweiiy** [reek/anti-adblock-killer#2013]
http://www.15min.lt/verslas/naujiena/bendroves/rekordine-bauda-apple-privalo-sumoketi-13-mlrd-euru-663-675835
https://gyazo.com/b3270e39fdcb2566a8f14dac35cf8c22
Chrome
Tampermonkey
AdBlock
EasyList + AakList

**Comment by aweiiy** [comment]
just scroll down and you will see

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1931#issuecomment-240100379

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
