### ISSUE TITLE
golem.de

### ISSUE THREAD

**Issue by veekoon** [reek/anti-adblock-killer#2016]
http://www.golem.de - any news 
http://i.imgur.com/KAc6sdO.png
Chrome
uBlock+
Subscribed lists: http://i.imgur.com/HcwZPVM.png

**Comment by SMed79** [comment]
No anti adblock for me !

try:
```
||ecruos.golem.de^
golem.de##script:contains(formatted)
```

**Comment by veekoon** [comment]
Nope, that does not fix it. 
What kind of setup do you have? Maybe you've got an additional list that I'm not subscribing or maybe it's a setting thing with my uBlock+.

**Comment by SMed79** [comment]
> What kind of setup do you have?

- http://i.imgur.com/dNweyTJ.png
- http://i.imgur.com/wQ3F2Yv.png

(Without any custome filters).

**Comment by veekoon** [comment]
Seems like it was my own fault.
Had 
`||ecruos.golem.de/$subdocument`
in my filters and golem was able to block me.
