### ISSUE TITLE
http://gadgets.ndtv.com/telecom/news/reliance-jio-plans-revealed-voice-calls-and-roaming-free-rs-50-for-1gb-data-1453073

### ISSUE THREAD

**Issue by Degitalord** [reek/anti-adblock-killer#2018]
http://gadgets.ndtv.com/telecom/news/reliance-jio-plans-revealed-voice-calls-and-roaming-free-rs-50-for-1gb-data-1453073

http://i.imgur.com/YgSlT3o.jpg

Google Chrome

Ublock + Anti ad block

Tampermonkey

EasyList + AakList

**Comment by mapx-** [comment]
add these filters
`@@||ndtv.com^$generichide
@@||zedo.com^$script,domain=ndtv.com
@@||ndtv.com^$script,domain=ndtv.com
@@||ads.rubiconproject.com$script,domain=ndtv.com
||taboola.com^
`

**Comment by savinay4u** [comment]
Thankyou so much MapX...... It works !!

**Comment by reek** [comment]
done
