### ISSUE TITLE
ogmcdownload.com

### ISSUE THREAD

**Issue by DieterHolvoet** [reek/anti-adblock-killer#202]
http://ogmcdownload.com/download-enough-items-mod-minecraft/
https://imgur.com/6IQ9841
Google Chrome
Tampermonkey
µBlock
Anti-Adblock Killer | Reek‎, EasyList‎, Peter Lowe’s Ad server list‎, EasyPrivacy‎, Malware Domain List‎, Malware domains‎:, Malware domains (long-lived)‎, Spam404‎, EU: Prebake - Filter Obtrusive Cookie Notices‎, NLD: EasyList Dutch‎,

**Comment by xDarkARG** [comment]
utiliza Adblock Plus

**Comment by alexander255** [comment]
Working script: http://pastebin.com/s5nfrPWU (identical to `forum.lolesporte.com`)

**Comment by alexander255** [comment]
These rules also work:

    ogmcdownload.com##body > .ui-widget-overlay:nth-last-child(2)
    ogmcdownload.com##body > .ui-dialog:last-child

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
