### ISSUE TITLE
exrapidleech.com

### ISSUE THREAD

**Issue by sanGtH** [reek/anti-adblock-killer#2023]
Hello Reek,
http://exrapidleech.info detects Anti AB killer 9.8. After solving capcha, again and again
you will be redirected to this page (screen) : 
http://img15.imagevenue.com/img.php?image=85859_exrapid_prob_122_598lo.jpg
Firefox 40
Anti AB killer 9.8
Ublock Origin 1.9.4
AAKlist

**Comment by SMed79** [comment]
Hi, 
could you please describe exactly how reproduce?

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
