### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by jfeilbach** [reek/anti-adblock-killer#2029]
Example link: http://www.wired.com/2016/09/stop-putting-raw-ginger-marinade-cookout-pro-tips/
Screenshot: http://i.imgur.com/3Mx0Yhx.png
Safari 9.1.3
AAK
Adblock Plus 1.12.1
Filter lists
------------
Adblock Warning Removal List
Enabled EasyList
EasyPrivacy+EasyList
Adware filters
Fanboy's Annoyance List
I don't care about cookies
Fanboy's Social Blocking List
Prebake - Filter Obtrusive Cookie Notices
AakList (Anti-Adblock Killer)

**Comment by mapx-** [comment]
1. remove easylist (already included in easylist + easyprivacy)
remove social list (already included in annoyances list)

2. add the filters here:
https://forums.lanik.us/viewtopic.php?p=100458#p100458

**Comment by jfeilbach** [comment]
@mapx- Worked. Thank you for sorting out my mess. I appreciate your help.
