### ISSUE TITLE
business-standard.com

### ISSUE THREAD

**Issue by varunagarwal1** [reek/anti-adblock-killer#2030]
List of Sites blocking ads

http://www.business-standard.com/article/technology/samsung-announces-swap-for-galaxy-note-7-with-galaxy-s7-variants-116090300216_1.html

www.hindustantimes.com

http://timesofindia.indiatimes.com/

![image](https://cloud.githubusercontent.com/assets/19989216/18227036/c5485148-7235-11e6-8b84-5b4e5409c679.png)

**Comment by SMed79** [comment]
Use search before posting !
- https://github.com/reek/anti-adblock-killer/issues?utf8=✓&q=indiatimes.com
- https://github.com/reek/anti-adblock-killer/issues?utf8=%E2%9C%93&q=hindustantimes.com
- https://github.com/reek/anti-adblock-killer/issues?utf8=%E2%9C%93&q=business-standard.com

See: 
- https://forums.lanik.us/viewtopic.php?f=62&t=31285&p=101220&hilit=indiatimes.com#p101220
- https://forums.lanik.us/viewtopic.php?f=62&t=31600&p=102061&hilit=hindustantimes.com#p102061
- https://forums.lanik.us/viewtopic.php?f=62&t=32342&p=101388&hilit=business+standard.com#p101388

**Comment by reek** [comment]
I'll kill it, thanks

**Comment by varunagarwal1** [comment]
reek - Please dont kill as none of the solutions have worked. All above sites and few more continue to detect adblockers and refuse to work until adblocker is disabled.

**Comment by mapx-** [comment]
"kill" means fixing in aak :D

**Comment by varunagarwal1** [comment]
@mapx- Thanks for the lingo :-)
@reek - Thanks for all the help you have been doing. It is incredible to have you here for us. Honestly, ALL sites have refused to take responsibility for malware served along with other issues while expecting us to open our systems for them to make money. See this tweet even after which they refuse to own responsiblity - https://twitter.com/originalvarun/status/778660852899598336

**Comment by reek** [comment]
@varunagarwal1 
I plan to fix the problem with AakScript and not with AB filters

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
