### ISSUE TITLE
thecomeback.com

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#2032]
pop up that says dont block our ads  comes up after you
![screen shot 2016-09-03 at 4 52 07 pm](https://cloud.githubusercontent.com/assets/21069588/18228198/db021fc6-71f6-11e6-96b7-3910e2e15f77.png)
 click an article
http://thecomeback.com/ncaa/ohio-state-student-earns-everyone-an-a-with-epic-ball-toss-from-balcony.html

**Comment by mapx-** [comment]
add
`@@||thecomeback.com^$generichide`

**Comment by jeepy321** [comment]
thanks
