### ISSUE TITLE
thesimsresource.com not working

### ISSUE THREAD

**Issue by otterbatch** [reek/anti-adblock-killer#2037]
It was working a week or so ago, and I tried two different browsers. Is it an issue only on my end? It shows up when trying to download anything.

**Comment by mapx-** [comment]
test these filters
```
||gadcreatives.mode.com^
@@||glam.com^$script,domain=thesimsresource.com
@@||pagead2.googlesyndication.com^$script,domain=thesimsresource.com
@@||servedbyopenx.com^$script,domain=thesimsresource.com
```

**Comment by otterbatch** [comment]
Working now. Thanks a ton! :D

**Comment by otterbatch** [comment]
I made a mistake closing this too early, haha. It worked for one download and now it's being detected again. RIP

**Comment by mapx-** [comment]
link ?

**Comment by otterbatch** [comment]
Alright, hopefully I got it now. I think I'm just an idiot who didn't set up the filters correctly lol (I'm new to this, oops). It's working consistently now so far, so this will be the last time I close this issue. :P Sorry for the trouble and thanks again!
