### ISSUE TITLE
diep.io

### ISSUE THREAD

**Issue by lamran** [reek/anti-adblock-killer#2039]
The game diep.io made a change today that prevents you from entering the sandbox game mode if you have adblock enabled.

Chrome
Tampermonkey
uBlock Origin
EasyList + AAK

**Comment by lamran** [comment]
Filters from smed79 from the EasyList forum:

'''
@@||diep.io/advertisement.js$script
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=diep.io
'''

**Comment by gorhill** [comment]
Try `@@||diep.io^$script,~third-party`.

**Comment by reek** [comment]
fixed by easylist
