### ISSUE TITLE
Report guide update suggestion: Tracker blocking add-ons section

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#204]
Do you think it would be a good idea to add a section to the report guide for mentioning tracker blocking add-ons such as Privacy Badger, Disconnect, Ghostery, Blur and TrackerBlock? These add-ons can affect pages' layout and functionality.

**Comment by reek** [comment]
Already in help section
https://github.com/reek/anti-adblock-killer#help

**Comment by anonsubmitter** [comment]
Oh sorry, I did not notice that.
