### ISSUE TITLE
Cannot assign to read only property 'adblock2' of object '#<Window>'

### ISSUE THREAD

**Issue by g2178716** [reek/anti-adblock-killer#2040]
`Execution of script 'Anti-Adblock Killer | Reek' failed! Cannot assign to read only property 'adblock2' of object '#<Window>'
`

The Chrome JavaScript console error above appears when visiting [this (NSFW) URL](http://javhub.net/play/1828af526/570b5fa305f706074483cfda/SW-138-Women-Love-A-Man-Smells-Manager-Smell!-?Application-Group-Application-Group-Also-Put-Her-Pants-My-Pants-To-The-Laundry)

The page has this script:

```
<script type="text/javascript">
        (function () {
            var ca = document.createElement('script');
            ca.type = 'text/javascript';
            ca.async = true;
            var s = document.getElementsByTagName('script')[0];
            ca.src = 'http://serve.popads.net/checkInventory.php';
            ca.onerror = function () {
                setTimeout(function () {
                    $('.embed-player').attr('src', "/adblock.html")
                }, 8000);
            }
            s.parentNode.insertBefore(ca, s);
        })();
    </script>
```

and another one further down that is probably related:

```
        function adBlockDetected() {
            $('#block').modal({
                'backdrop': 'static',
                'keyboard': false,
            })
        }
        if (window.canRunAds === undefined) {
            adBlockDetected()
        }
```

The upper script is updating the `src` attribute of an iframe which contains the video player:

```
<iframe src="https://example.com" frameborder="0" class="embed-player" scrolling="no" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" rel="nofollow"></iframe>
```

After the `src` attribute is updated asynchronously by the first script above a warning message appears asking to turn off Adblock if you want to use the site.

**Comment by reek** [comment]
fixed by easylist
