### ISSUE TITLE
windowsxlive.net

### ISSUE THREAD

**Issue by dh33r4j** [reek/anti-adblock-killer#2042]
Adblock Detection
http://www.windowsxlive.net
Browser: Opera
Ublock Orgin all updated
only basic filters

**Comment by dh33r4j** [comment]
Adding
||http://www.windowsxlive.net/wp-content/plugins/wp-adblock-dedect
to 'My Filters' helps

**Comment by mapx-** [comment]
`||windowsxlive.net/*adblock$script`

**Comment by dh33r4j** [comment]
Thanks, But then the download section of the page has another detection

http://www.thememypc.net/macos-ux-pack/

**Comment by mapx-** [comment]
yes, other site, add
```
@@||thememypc.net^$generichide
@@||pagead2.googlesyndication.com^$script,domain=thememypc.net
```

**Comment by dh33r4j** [comment]
Perfect!
