### ISSUE TITLE
issue with timesofindia.com ... aak now working

### ISSUE THREAD

**Issue by timepas00** [reek/anti-adblock-killer#2044]
![screen shot 2016-09-05 at 6 33 01 pm](https://cloud.githubusercontent.com/assets/20864332/18249285/03ec6ab8-739b-11e6-91d2-bac16177e8dd.jpg)

**Comment by timepas00** [comment]
hello team can u pls check

**Comment by mapx-** [comment]
did you try these filters ?
https://forums.lanik.us/viewtopic.php?p=101220#p101220

what adblocker are you using ?

**Comment by timepas00** [comment]
adblocker is 2.7.3 ... 

yes above filters r added 

e.g. page -- http://timesofindia.indiatimes.com/world/An-Airbnb-hosts-sleazy-confession-horrifies-renters/articleshow/54019603.cms

**Comment by mapx-** [comment]
did you install the last dev build as indicated ?

**Comment by piyushgarg** [comment]
see the comment
[https://github.com/reek/anti-adblock-killer/issues/1653#issuecomment-238187439]

**Comment by harsha5500** [comment]
Hi,

For me adding the list in the above site into ABP worked! Thank you!

**Comment by timepas00** [comment]
How did you add it share your steps pls

**Comment by mapx-** [comment]
how to add filters in ABP
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by harsha5500** [comment]
@timepas00 

Select "options" in the ad-block plus addons.
Choose "Add your own filters"
At the bottom, there is "Edit as raw text". Click that.
Copy paste the list of filters shared above there and save.
And it works.

**Comment by mapx-** [comment]
@harsha5500, @timepas00 asked for ABP 2.7.3 (firefox). He has the answer in the link above.

**Comment by reek** [comment]
done
