### ISSUE TITLE
http://www.javadecompilers.com/

### ISSUE THREAD

**Issue by TypeV** [reek/anti-adblock-killer#2046]
For some reason, this website has a really good anti-adblock system. I don't know how they do it, but even disabling all adblockers and blocking the connections with the hosts file is not working. (The website that hosts the image is s1.2mdn.net)
What I do now is I block the doubleclick website, but I still see the ad.

**Comment by mapx-** [comment]
use these filters
https://forums.lanik.us/viewtopic.php?p=100655#p100655

**Comment by reek** [comment]
Killed by AakScript
