### ISSUE TITLE
op.gg

### ISSUE THREAD

**Issue by yoker88** [reek/anti-adblock-killer#2047]
http://op.gg/
http://imgur.com/a/033hi
Google Chrome
Tampermonkey
Adblock Plus + Adblock
Aaklist + facebook annoyances blocker + EasyList

**Comment by mapx-** [comment]
- never use 2 adblockers or other blocking extensions (no ghostery, disconnect ..)
- remove AB, keep only ABP
- add this filter
`@@||op.gg^$generichide`

**Comment by yoker88** [comment]
Thanks, I deleted AB. I added that filter on ABP and it worked, thank you!
