### ISSUE TITLE
uptostream.com no more blocked

### ISSUE THREAD

**Issue by Xoxorgne** [reek/anti-adblock-killer#2049]
Hello
Uptostream (uptobox subdomain) is no more unblock with anti-adblock-killer, it says 

> We are sorry but we had to block adblock since they totaly destroy the website by disabling ALL the javascript (disable quality selection, subtitle ...)
> Disable adblock and everything will work as it should.
> If you want to complain adblock, contact here : https://forums.lanik.us/viewforum.php?f=91

**_For example this link : http://uptostream.com/so3cf7a8jc0r_**

Can you add it to the next update or tell us how to unblock it with adblock activated ?
Thank you very much

**Comment by mapx-** [comment]
add this filter
`@@||uptobox.com^$script,domain=uptostream.com`

**Comment by SMed79** [comment]
https://forums.lanik.us/viewtopic.php?f=91&t=32576

**Comment by Xoxorgne** [comment]
Thank you very much ! :)

**Comment by reek** [comment]
fixed by easylist

**Comment by ghajini** [comment]
not working
https://uptostream.com/ura6mpdrbkji

**Comment by smed79** [comment]
@ghajini https://github.com/reek/anti-adblock-killer/issues/2049#issuecomment-244808823 / [viewtopic.php?p=105805#p105805](https://forums.lanik.us/viewtopic.php?p=105805#p105805)
