### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by animeloverx** [reek/anti-adblock-killer#205]
- After login on http://www.vvvvid.it/ any episode starts of anime ( example anime:
http://www.vvvvid.it/#!show/238/death-parade ) you are redirected to http://www.vvvvid.it/adblock.html
- http://imgbox.com/0WuxagBd
- Mozilla Firefox 35.0.1
- Greasemonkey 2.3 [script: Anti-Adblock Killer | Reek 7.7 (Execute First) + AdsBypasser 5.16.0]
- Adblock Plus 2.6.7
- Adblock Warning Removal List + EasyList Italy+EasyList + Malware domains + Fanboy's Social Blocking List + EasyPrivacy + Anti-Adblock Killer | Filters for Adblockers

Thanks for your time and for the script... :)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://greasyfork.org/en/forum/discussion/3287/vvvvid-it-http-www-vvvvid-it-adblock-html?locale=en

**Comment by Robotex** [comment]
I made the pull request https://github.com/reek/anti-adblock-killer/pull/282 for this issue

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
See https://github.com/reek/anti-adblock-killer/issues/513#issuecomment-129198855

**Comment by raffybest94V01** [comment]
no more work =( vvvvid have bypass this, update pls ?

**Comment by justBorn** [comment]
is not a fix, but an alternative solution :)
https://github.com/justBorn/vvvvid-skip-adv

**Comment by raffybest94V01** [comment]
thanks very much

2016-05-12 17:33 GMT+02:00 Alessandro Francia <notifications@github.com>:

**Comment by Robotex** [comment]
That's a nice solution for skipping ads without completely removing them :)
However I just found it simpler using the userscript KAADIVVVV and have never worry about turning off adblock again
