### ISSUE TITLE
http://indiatoday.intoday.in/

### ISSUE THREAD

**Issue by rammanokar** [reek/anti-adblock-killer#2050]
http://indiatoday.intoday.in/technology/story/jio-gets-competition-bsnl-to-launch-broadband-plan-at-less-than-re-1-per-gb/1/756918.html
http://imgur.com/a/nEHQ1
Chrome
Tampermonkey 
Adblock Plus
EasyList + AakList

**Comment by X01X012013** [comment]
This website was patched a while ago in my script: 
https://x01x012013.github.io/AdBlockProtector/

You can use it while waiting for Aak to update.

**Comment by ghajini** [comment]
update aak list for indian sites by reek
https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672

**Comment by reek** [comment]
done
