### ISSUE TITLE
lequipe.fr

### ISSUE THREAD

**Issue by nebelnic** [reek/anti-adblock-killer#2051]
block again today. 

Mozilla Firefox 48.0.2 (on OSX
![capture d ecran 2016-09-06 a 11 05 14](https://cloud.githubusercontent.com/assets/22024274/18267933/cadecc16-7421-11e6-94ff-ecb124c25e3a.png)
)
Greasemonkey
Adblock Plus
Liste FR EasyList + AakList + 

![Uploading Capture d’écran 2016-09-06 à 11.05.14.png…]()

**Comment by mapx-** [comment]
add these filters
```
@@||lequipe.fr^$generichide
@@|http://$script,image,domain=lequipe.fr
```

**Comment by GitteHubber** [comment]
using chrome, ublock and AAK i could manage to remove it with this single filter:

`||lequipe.fr/v6/js/*`

But it's removing all article pictures on the site (mapx filters the same)

![untitled](https://cloud.githubusercontent.com/assets/22026521/18271698/c934bc60-7433-11e6-8dc6-30f6129ad407.jpg)

**Comment by mapx-** [comment]
use only my filters no other custom filter for lequipe
provide example page without images (my filters are whitelisting elements, surely dont block anything !)

**Comment by GitteHubber** [comment]
That's what i did, only your filters:

![untitled](https://cloud.githubusercontent.com/assets/22026521/18272192/cfec51a0-7436-11e6-8b50-5d2a35065b86.jpg)

**Comment by mapx-** [comment]
example link ?

**Comment by GitteHubber** [comment]
It's the main page of l'equipe.

**Comment by mapx-** [comment]
no issues here, I get all the pics ok.
I use easylist, Liste FR, aak, easyprivacy, ublock filters.

disable / remove all other blocking extensions, re-test

**Comment by mapx-** [comment]
be sure you dont block something using advanced user / dynamic filtering

**Comment by nebelnic** [comment]
Works fine for me. 
thank you very much!

**Comment by GitteHubber** [comment]
Did all that actually, but it didnt help. However, exported my other custom rules and reset ublock completly to default and it works now fine. Did surely oversee something i guess :) 

However, thanks!

**Comment by SMed79** [comment]
An alternative working filter for Adblock plus 
`lequipe.fr##[-abp-properties='z-index: 999999;']`

**Comment by mapx-** [comment]
better filters
```
@@||lequipe.fr^$generichide
|https://$script,domain=lequipe.fr
@@||apis.google.com^$script,domain=lequipe.fr
```

**Comment by nebelnic** [comment]
mapx:
I  (try to) set up filters as you advice: 
![capture d ecran 2016-09-07 a 09 27 17](https://cloud.githubusercontent.com/assets/22024274/18303390/325c09ce-74dd-11e6-8e8a-8dc239979fd0.png)
but still have a bit of ad:
![capture d ecran 2016-09-07 a 09 26 55](https://cloud.githubusercontent.com/assets/22024274/18303411/48fc06ca-74dd-11e6-944c-1939e8567a4c.png)

thx!

**Comment by mapx-** [comment]
better filters means ...replacing the old ones, use only 
```
@@||lequipe.fr^$generichide
|https://$script,domain=lequipe.fr
@@||apis.google.com^$script,domain=lequipe.fr
```

**Comment by nebelnic** [comment]
Thx!!

**Comment by valentinhav27** [comment]
Thx so much !

**Comment by Afonsopirex** [comment]
Oh my god dude dumbass, its just block the elements and reload the page.

**Comment by Damn3d** [comment]
Hi and thanks for the script but it doesn't work correctly :/
I have no images, same in last version.

Thanks !

**Comment by mapx-** [comment]
the filters above still working for me
https://github.com/reek/anti-adblock-killer/issues/2051#issuecomment-245198513

don't use other blocking addons / extensions, keeps only 1 adblocker + the filters above

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Damn3d** [comment]
Hi reek, thanks for the update. Problem still present on l'equipe.fr
![cadecc16-7421-11e6-94ff-ecb124c25e3a](https://cloud.githubusercontent.com/assets/22372482/20382334/b582b658-acab-11e6-8384-4282b63967e8.png)

**Comment by mapx-** [comment]
```
@@||lequipe.fr^$generichide
|https://$script,domain=lequipe.fr,third-party
@@||connect.facebook.net^$domain=lequipe.fr
@@||apis.google.com^$script,domain=lequipe.fr
```
