### ISSUE TITLE
wikihow.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#2052]
http://www.wikihow.com/Make-Cabbage-Juice

http://imgur.com/a/jHyc3

Mozilla Firefox 48.0.2
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka (www.certyficate.it)

**Comment by mapx-** [comment]
add
```
@@||wikihow.com^$generichide
@@||pad1.whstatic.com/extensions/wikihow/adblock_notice/fuckadblock.js$script,domain=wikihow.com
```

**Comment by xxcriticxx** [comment]
yes this works thx
