### ISSUE TITLE
shink.in

### ISSUE THREAD

**Issue by zki63687** [reek/anti-adblock-killer#2056]
like this link: http://shink.in/54A25
Chrome
adblock plus
EasyList China+EasyList

**Comment by mapx-** [comment]
add this filter in ABP
`@@||shink.in^$generichide`

**Comment by zki63687** [comment]
Thank you.

**Comment by hohien3199** [comment]
> add this filter in ABP
@@||shink.in^$generichide

How to add filter in ABP ? Can you guide me :D
