### ISSUE TITLE
eune.op.gg

### ISSUE THREAD

**Issue by Ravenghost** [reek/anti-adblock-killer#2058]
http://eune.op.gg/
http://i.imgur.com/XjLq7OW.png
Chrome
Tampermonkey
uBlock Origin
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2047#issuecomment-244800478

**Comment by Ravenghost** [comment]
Thanks adding
@@||op.gg^$generichide
filter worked. How does the filter creating works? can i make a filter on my own if i stumble on another website?

**Comment by mapx-** [comment]
the filter above is dedicated to that domain op.gg

sure, you can always create your own filters or use the filters other persons provide on various support channels.
