### ISSUE TITLE
http://www.citationmachine.net/

### ISSUE THREAD

**Issue by Spear99** [reek/anti-adblock-killer#2059]
http://www.citationmachine.net/
http://imgur.com/a/gYWMA
Google Chrome
Tampermonkey
Adblock
Aaklist

**Comment by mapx-** [comment]
use the filters here:
https://forums.lanik.us/viewtopic.php?p=97203#p97203

**Comment by Spear99** [comment]
Perhaps a dumb question but how do I add those filters? I'm familiar with adding a filter list via URL but he provided the actual code for the filter, which I can't find out where to save.

**Comment by mapx-** [comment]
adblock chrome: "AdBlock button > Options > CUSTOMIZE tab ==> paste there the filters
adblock plus chrome /firefox:  https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by reek** [comment]
already Killed by aakScript
