### ISSUE TITLE
satoshiquiz.com

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#206]
http://satoshiquiz.com/
http://i.imgur.com/7Pl2sNU.png
Google Chrome
N/A
uBlock
EasyList + Anti-Adblock Killer

Additional information:
The popup only shows if you are logged into an account.
A rule that I have found is:
@@/ads.js$script,domain=satoshiquiz.com

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Injust** [comment]
I don't think you understand :)
I already found a rule that works, just please verify and add to your Anti-Adblock Killer.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
