### ISSUE TITLE
javhdonline.com

### ISSUE THREAD

**Issue by rapidsharr** [reek/anti-adblock-killer#2060]
Adblock detection at http://javhdonline.com
It is Japanese p0*nsite. Any workarounds?

uBlock Orgin with default lists and AAK
firefox browser.

**Comment by mapx-** [comment]
(search easylist forum)
here the fix:
https://forums.lanik.us/viewtopic.php?p=85477#p85477

**Comment by rapidsharr** [comment]
Thanks @mapx- 
Do they get added to easylist or AAK list when they are posted in forums?

**Comment by mapx-** [comment]
unfortunately not all the filters. So, just use them as custom filters.

**Comment by reek** [comment]
already killed by AakScript
