### ISSUE TITLE
"mylastad", unblockable, disables scrolling.

### ISSUE THREAD

**Issue by Jason010767** [reek/anti-adblock-killer#2063]
[http://i.imgur.com/LS2AIsN.png](url)
[http://i.imgur.com/Kb0fZhg.png](url)

[http://www.thecountrycaller.com/14993-amd-launches-7th-generation-a-series-apus-with-oem-systems/](url)
[https://www.mylastad.com/](url)

From what I saw, they track your mouse and display a pop-up when your pointer leaves the webpage area.

Unblockable with adblock plus's block element feature and anti-adblock-killer with everything perfectly setup.

My adblock plus fliters:
EasyList
EasyPrivacy
EasyList China+EasyList
ABPindo+EasyList
Bulgarian list+EasyList
EasyList Czech and Slovak+EasyList
EasyList Dutch+EasyList
EasyList Germany+EasyList
EasyList Hebrew+EasyList
EasyList Italy+EasyList
EasyList Lithuania+EasyList
Latvian List+EasyList
Liste AR+Liste FR+EasyList
Liste FR+EasyList
ROList+EasyList
RuAdList+EasyList
AakList (Anti-Adblock Killer)

My own fliters:
||betterallfrees.com/templates/allfree/images/download_torrent.gif
RED3Xm.jpg
||lh3.googleusercontent.com/-Zu-yEcWSthg/UAw3XbmhTSI/AAAAAAAAADc/snfIcnbTGao/s128/adblockdetected.png
||st.deviantart.net/promotions/
searchSelect
||typeracer.com/dynamic_content/typing_game_ab_test_c_336x280.html?t=370436185
||fusiongameworks.net/images/pleasedontblock.png
302_s.jpg
203_s.jpg
105_s.jpg
204_s.jpg
304_s.jpg
||source.pixiv.net/common/images/stamp/stamps/
207_s.jpg
404_s.jpg
205_s.jpg
||goo.gl/CGHVVo
se.bota.png
http://www.rlslog.net/
betterallfrees.com##.alert
terraria.gamepedia.com###atflb
##.banner-wrap
mega64roms.blogspot.hk###g207
wiiuiso.com##.latestust
sh.st##.KTFg
##.recirculation-rail.module.group-FANDOM_TOPIC.recirculation-unit
##.start-wikia
##.wikia-logo-container.table-cell
##.cell-link.top-level
##.global-footer
###WikiaFooter
##.WikiaFooter.notoolbar
###WikiaBarWrapper
##.WikiaBarWrapper
###eaftsaxmiasuekbhtfysehhdongynq
##.alulfpiejixjexdtkjgvptavspdepd_1
tomshardware.com###eaftsaxmiasuekbhtfysehhdongynq
tomshardware.com##.alulfpiejixjexdtkjgvptavspdepd_1
deviantart.com##.overhead-promo-a
winaero.com##div[style="text-align:center;margin:20px 0;\a     margin: 1.42857142857rem 0;"]
##.chevron
###searchSelect
##.search-select
en.wikipedia.org##.frbanner-message
en.wikipedia.org##.frbanner-form-container
en.wikipedia.org###frbanner-main
en.wikipedia.org###frbanner-nag
creepypasta.wikia.com##img[src="http://vignette2.wikia.nocookie.net/creepypasta/images/0/0c/3d7fd3a8e4106ea2ff9114e43b98c1b7.jpg/revision/latest/scale-to-width-down/288?cb=20150618173614"]
play.typeracer.com##.adblockWarning
play.typeracer.com##.gwt-HTML
play.typeracer.com##.newSouthWidget
fusiongameworks.net##div[style="position:relative; margin:0 auto; padding:4px 0px; width:728px; height:90px;"]
##.wds-global-footer.wds-is-en
creepypasta.wikia.com##img[src="http://vignette2.wikia.nocookie.net/creepypasta/images/3/32/IdolServices.jpg/revision/latest/scale-to-width-down/220?cb=20150209225058"]
mega.nz##.button.download-button.red.with-megasync.down-arrow.white-txt
mega.nz##.ads-left-block
mega.nz##.products-slides-block.products-laptop.active
mega.nz##.ads-right-block
mega.nz##.st-main-bottom
discordapp.com##.notice
sin6.web.fc2.com###fc2_ad_container
gamepedia.com###siderail
###siderail
gamepedia.com###atflb
hdmovie2k.co###\38 RcPm
hdmovie2k.co##.login-popup
hdmovie2k.co###mask
mc-market.org##.adblock_detector.adblock_notice
dropbox.com###upsell-bubble
dropbox.com##.sub-nav.chat-bubble.header-bubble.upsell-bubble
knowyourmeme.com###main_navigation
forbes.com###xKcKuRl_0
forbes.com##.mheSrBbQ
forbes.com###qukhIIn_0
forbes.com##.bbOVxdpV
forbes.com###yBfGePYRe_0
forbes.com##.ASTFFGr
forbes.com###WLAJFVOwvw_0
forbes.com##.KiBzVOJ
###ymyOENp_0
##.eMaaWj
###rTHpotiXmxb_0
##.qScWzNX
###donatebox
###pYqAcUHS_0
##.WTbXbS
###DnefWb_0
##.vFcoMkvTZs
###RyyMEfcLQKZ_0
##.nsbgNYbDl
###fbs-ad-rail-article-0
##.fbs-ad-rail.clearfix
###blwUnqeJ
##.top-fbs-ad.top-fbs-ad-article.ng-isolate-scope.VwWgCixEa
###top-fbs-ad-article-sticky-0
##.top-fbs-ad-sticky.ng-scope.ng-isolate-scope
##.circ-link.ng-binding.ng-scope
creepypasta.wikia.com##img[src="http://vignette4.wikia.nocookie.net/creepypasta/images/e/e3/Bloody.heart_.jpg/revision/latest/scale-to-width-down/180?cb=20120501005307"]
mg.mail.yahoo.com###yui_3_16_0_ym19_1_1472961905184_1687
mg.mail.yahoo.com###yui_3_16_0_ym19_1_1472961905184_1264
mg.mail.yahoo.com##.videopane
mg.mail.yahoo.com###yui_3_16_0_ym19_1_1472961905184_1642
mg.mail.yahoo.com##.empty-folder-submsg2
hk.yahoo.com##.Mb-12.Lh-23.Pos-r.Ov-h
settings.yahoo.com###yui_3_18_1_1_1472962110498_245
settings.yahoo.com##.D\(b\).C\(\#fff\)\!.Pstart\(4px\).Td\(n\)\!.Td\(u\)\!\:h.Fz\(13px\)
facebook.com###u_jsonp_3_0
facebook.com##._4-u2._5v6e.cardRightCol._4-u8
mg.mail.yahoo.com###yui_3_16_0_ym19_1_1472962571564_1744
mg.mail.yahoo.com##.D\(b\).C\(\#fff\)\!.Pstart\(4px\).Td\(n\)\!.Td\(u\)\!\:h.Fz\(13px\)
us.yahoo.com###yui_3_18_0_6_1472962624497_939
us.yahoo.com##.js-stream-item-wrap.Pos\(r\).Pt\(12px\).Pb\(17px\)
us.yahoo.com###yui_3_18_0_6_1472962624497_1514
us.yahoo.com##.js-stream-item-wrap.Pos\(r\).Py\(12px\)
us.yahoo.com##.Col3-stack
us.yahoo.com###yui_3_18_0_6_1472962624497_1495
us.yahoo.com##.C\(\#fff\).Pstart\(4px\).Td\(n\)\!.Td\(u\)\!\:h.Fz\(13px\)
us.yahoo.com###applet_p_50000173
us.yahoo.com##.M-0.js-applet.streamv2.Zoom-1.Mb-20
us.yahoo.com###uh-search-promo
us.yahoo.com##.W\(122px\).Fz\(12px\).Ta\(c\).Fl\(end\).M\(0\).H\(40px\).P\(0\).C\(\#020e65\).C\(\#0078ff\)\:h.C\(\#0078ff\)\:f.Fw\(b\).Bd\(n\).Trs\(\$searchPromoTransition\).D\(n\)--sm1170.rapidnofollow
us.yahoo.com###set-homepage
us.yahoo.com##.D\(ib\).Py\(8px\).Px\(0px\)
us.yahoo.com###yui_3_18_0_6_1472962624497_2106
us.yahoo.com##.P\(2px\).js-hpset-btn.hpset.hpset-gradient.Lh\(1\.6em\).H\(100\%\).hpsetbox
facebook.com##._5f4c
google.com.hk###_eEe
google.com.hk##.logo-subtext
creepypasta.wikia.com##img[src="http://vignette1.wikia.nocookie.net/creepypasta/images/d/d2/Eye-macros-human-eye2.jpg/revision/latest/scale-to-width-down/180?cb=20120408184134"]
danbooru.donmai.us###upgrade-account-notice
youtube.com###premium-yva-close
youtube.com##.yt-uix-close
thecountrycaller.com##.impo-b-list
@@||cloudfront.net/*ad$script,domain=rlslog.net
@@||tomshardware.com^$generichide
@@||s3.amazonaws.com/inject_ads/advertisement.js
@@||rlslog.net^$generichide

**Comment by mapx-** [comment]
test these filters
```
@@||thecountrycaller.com^$generichide
@@||comeadvertisewithus.com/ads/.adplacement=
thecountrycaller.com#@#.modal-backdrop
thecountrycaller.com#@#.modal
||thecountrycaller.com^$script
```

**Comment by mapx-** [comment]
you should also keep only 1 easylist and remove all the combo list (for example Latvian List+EasyList)
and subscribe directly only the regional lists from https://adblockplus.org/en/subscriptions

(you have a lot of redundant easylist in the combo lists)

**Comment by Jason010767** [comment]
Ok, I tested these, didn't work. Scrolling still gets disabled.
"Trending" section with ad links still show up.

What are the regional lists from adblockplus?

**Comment by Jason010767** [comment]
Wait! It worked. I guess I didn't refresh. then.

**Comment by mapx-** [comment]
as I said , for example this is regional list "Latvian List"
If you don't need such lists, remove all of them, keep only easylist, easyprivacy, AAK

remove all your custom filters, keep only easylist, AAk, easyprivacy, test again
browser version ?
ABP version ?

**Comment by mapx-** [comment]
ok ,... see if you need all those lists. If you don't need them your navigation will be will suffer (very slow)

**Comment by Jason010767** [comment]
About my custom filters, there are some other elements I wanted to block.
Like the Red button from Mega, which downloads their application.
As for the other regional lists, I dunno, I just saw them in adblock plus's settings and decided to add them.
Whats the differences between Easylist and the other easylitsts?

**Comment by mapx-** [comment]
ok, keep your custom filters.

if you live in Romania you need easylist + rolist, otherwise remove it, keep only easylist (if you live in an english language country)

no differences, it's the same easylist loaded "n" times.

**Comment by Jason010767** [comment]
Thanks for helping!
