### ISSUE TITLE
timesofindia.com

### ISSUE THREAD

**Issue by nromil** [reek/anti-adblock-killer#2064]
http://timesofindia.indiatimes.com/world
http://imgur.com/i9dWRKO
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by mapx-** [comment]
add in ubo these filters

```
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script
```

**Comment by ghajini** [comment]
http://timesofindia.indiatimes.com/world
moving animations seen,,,,how to block them
![screenshot 35](https://cloud.githubusercontent.com/assets/20338483/18358305/0f1acbb8-7612-11e6-9865-d0014db8953c.jpg)

**Comment by mapx-** [comment]
add
`indiatimes.com##[data-callback="setAutoplayAds"]`

**Comment by ghajini** [comment]
thank you....also live channel not working with abp ,reek list and script
with https://github.com/reek/anti-adblock-killer/issues/1725#issuecomment-231913672  using
![screenshot 36](https://cloud.githubusercontent.com/assets/20338483/18359022/95e6c8c4-7615-11e6-8356-eb0bd2d574d3.png)

**Comment by mapx-** [comment]
enable flash (it seems working only in flash)

**Comment by ghajini** [comment]
thanx...in my mind chrome based browsers flash is inbuilt,opera don't have...
working

**Comment by gorhill** [comment]
> EasyList + AakList

Did you disable _uBlock filters_? If so, **do not disable** _uBlock filters_, this list contains anti-blocker filters which render unnecessary whitelisting ad servers.

**Comment by anirbandd** [comment]
@nromil please test with this as well: 

@@||indiatimes.com/*/ads.cms$script

**Comment by mapx-** [comment]
`@@||indiatimes.com/*ad`

**Comment by reek** [comment]
done
