### ISSUE TITLE
Kiplinger popup prevents viewing site with adblocker installed

### ISSUE THREAD

**Issue by jhnmdahl** [reek/anti-adblock-killer#2065]
Page is http://www.kiplinger.com/slideshow/retirement/T051-S000-common-social-security-myths/index.html

config is Firefox 48.0.2
anti-adblock killer 9.8 script on greasemonkey

**Comment by mapx-** [comment]
test this filter
`||cointent.com^`

**Comment by Afonsopirex** [comment]
just block the element using adblock dude
