### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by glennsamuel32** [reek/anti-adblock-killer#2066]
http://indianexpress.com/article/sports/badminton/pv-sindhu-pulela-gopichand-felicitated-in-mumbai-3017198/

Indian Express back with a vengence !!!
Waiting for @reek to work his magic :)

**Comment by mapx-** [comment]
add this filter in your adblocker
`@@||indianexpress.com^$script`

**Comment by aquitaine** [comment]
@mapx- are the edits you make here going into the AAKList ? Wondering if it can just auto download into my browser.

**Comment by mapx-** [comment]
only if Reek adds the filters to AAK :)

**Comment by ghajini** [comment]
@@||indianexpress.com/*ad$script

**Comment by aquitaine** [comment]
@ghajini how do you figure out the regex for the adblock checker? Could you point me to some docs?

**Comment by anirbandd** [comment]
@glennsamuel32 use this: 
@@||indianexpress.com/*/ads_js.js$script

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
