### ISSUE TITLE
leveldown

### ISSUE THREAD

**Issue by TheLordMania** [reek/anti-adblock-killer#2068]
leveldown.fr has an anti adblock, and that show them to the people who have one: 

![image](https://cloud.githubusercontent.com/assets/22083846/18362934/33d6cac4-7608-11e6-834e-ab2c05d46f83.png)

"It seems that something is blocking that content. Make sure your connection is working and try disabling your ad blockers."

using chrome
- adblock
- tampermonkey
- Anti-Adblock Killer

**Comment by mapx-** [comment]
add these filters
```
@@||leveldown.fr^$generichide
@@||liverail.com$image,domain=leveldown.fr
```

**Comment by TheLordMania** [comment]
@mapx- If your filters dont block pubs, i dont see the interest to applict this filters i dont want have a lot of fuck.... pubs ^^
