### ISSUE TITLE
Les echos

### ISSUE THREAD

**Issue by zorro3210** [reek/anti-adblock-killer#2072]
Ad visible on lesechos.
Example: http://www.lesechos.fr/politique-societe/politique/0211274026303-impot-sur-le-revenu-sapin-annonce-une-baisse-pour-5-millions-de-menage-en-2017-2026188.php
Thanks for the help

![image](https://cloud.githubusercontent.com/assets/8364468/18387219/a645cd1a-769b-11e6-9767-979ca64299e6.png)

**Comment by mapx-** [comment]
add these filters
```
@@||ads.videoadex.com/jw/advertisement.js?*
@@||lesechos.com^$script
```

**Comment by reek** [comment]
already fixed
