### ISSUE TITLE
http://www.cpu-world.com/

### ISSUE THREAD

**Issue by vonkez** [reek/anti-adblock-killer#2075]
http://www.cpu-world.com/
http://i.imgur.com/dD7uav3.png
Google Chrome
uBlock
I use AakList, EasyList and hosts file created with this scrpit https://github.com/zant95/hBlock

also site enables anti-adblock after few pages

**Comment by Afonsopirex** [comment]
add the filters:                                                                                                                                             cpu-world.com###AB_W7
cpu-world.com##.ab_w7
and done ;D
