### ISSUE TITLE
crococoin.com

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#208]
http://crococoin.com/
http://i.imgur.com/5yrKDM9.png
Google Chrome
N/A
uBlock
EasyList + Anti-Adblock Killer

**Comment by Injust** [comment]
Author of the site and the structure of the site is similar or the same as the site referenced in issue #209.

**Comment by alexander255** [comment]
Anti-Adblock script: http://pastebin.com/CCuurpJG (yes, this is indeed the same as #209 )

**Comment by Injust** [comment]
Could you explain to me what the script you put does? Am I supposed to use it to kill the site's anti-AdBlock, or is it what the site is using to block AdBlock?

**Comment by alexander255** [comment]
The script is mainly for @reek ;-) I'm just helping out by providing working anti-blocking scripts...

But you can also use it until it gets added into Anti-AdBlock Killer:

 1. Open the pastebin.com page linked above
 2. Click on the *RAW* link above the script
 3. Press `Ctrl`+`A` and `Ctrl`+`C` to copy the script
 4. Add the script to your script manager:
  * Tampermonkey/Chrom(ium):
    1. Click on the menu button and select `Settings`
    2. Go to the `Extensions` page
    3. Next to the `Tampermonkey` entry click on `options`
    4. In Tampermonkey's top panel click on the first icon (with the green addition symbol)
    5. Click into the text area
    6. Press `Ctrl`+`A` and `Ctrl`+`V` to paste script
    7. Click on the save icon above the text area
  * Greasemonkey/Firefox:
    1. Click on the menu button and select `Add-ons`
    2. Select the entry `User scripts` on the left side of the content window
    3. Click on `New user script...` link towards the top-right of the page
    4. In the opened dialog press the `Use script from clipboard.` button

You obviously need a script manager for this, this page WILL NOT work with only an adblocker!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Thanks Alex ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
