### ISSUE TITLE
pokemon-vortex.com

### ISSUE THREAD

**Issue by MaxLucio528** [reek/anti-adblock-killer#2080]
I´m having trouble with the game Pokemon Vortex because I cannot play when I use Adblock, and the Anti -Adblock Killer don´t work on this site, so if you can kill this for me I´ll be grateful.

Link: http://zeta.pokemon-vortex.com/dashboard.php
Browser: Google Chrome
Script Manager: Tampermonkey
Adblocker: Adblock
Filterlist: My filterlists have AakList (Anti-Adblock Killer)

Image:

![imagem](https://cloud.githubusercontent.com/assets/18402849/18411659/2f609614-7752-11e6-9c7c-76bc8cd4c2fb.png)

**Comment by mapx-** [comment]
needing account, however add this filter in AB, see if works
`@@||pokemon-vortex.com^$generichide`

**Comment by MaxLucio528** [comment]
It worked, thank you!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
