### ISSUE TITLE
 lequipe.fr

### ISSUE THREAD

**Issue by valentinhav27** [reek/anti-adblock-killer#2081]
Hello, 

The anti adblock killer doesn't work on this page : www.lequipe.fr

I added this filter on ABP : @@||lequipe.fr/*ad$script but there's no effect.. 

Thank for you help

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2051#issuecomment-245198513

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
