### ISSUE TITLE
Btvsports

### ISSUE THREAD

**Issue by 2n2u** [reek/anti-adblock-killer#2083]
http://www.btvsports.site
When trying to watch a stream, it doesn't let Fullscreen since it detects adblock

Opera
TamperMonkey
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add these filters in ABP
```
@@||btvsports.site^$generichide
btvsports.site###i41c
```

**Comment by reek** [comment]
already killed by aakscript
