### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by guibuche** [reek/anti-adblock-killer#2086]
The anti adblock killer script/Reek launched thanks to Tamper Monkey does not work on this website page : http://www.investing.com/charts/real-time-futures-charts
![image](https://cloud.githubusercontent.com/assets/22130458/18417140/d154a4bc-7827-11e6-86ff-3cd3cb357717.png)

Thanks

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1893#issuecomment-239084491

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
