### ISSUE TITLE
financialexpress.com

### ISSUE THREAD

**Issue by ravi6603** [reek/anti-adblock-killer#2087]
http://www.financialexpress.com
is there any syntax for antiblocking

**Comment by mapx-** [comment]
add this filter
`@@||indianexpress.com^$script,domain=financialexpress.com`

**Comment by ravi6603** [comment]
when i will get update of antiadblock

**Comment by mapx-** [comment]
just add the filter above in your custom filters (of your adblocker)

**Comment by ravi6603** [comment]
i am asking for rest of sites  like hindu, ndtv etc

**Comment by mapx-** [comment]
you were asking for financialexpress
for the rest do search the repository:
for example search for ndtv:
https://github.com/reek/anti-adblock-killer/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20ndtv

**Comment by reek** [comment]
Ok, I'll kill it thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
