### ISSUE TITLE
www.sport247.live Not working

### ISSUE THREAD

**Issue by koqekoqe4** [reek/anti-adblock-killer#2088]
http://imgur.com/a/ukPJn

Chrome
Tampermonkey
Adblock + Ublock
EasyList + AakList
AAk 9.8

Do you have a any idea ?

Thank you !

**Comment by mapx-** [comment]
add these filters in AB
```
@@||medianetworkinternational.com/*ad$script
||adshell.net^$popup
||tags2.adshell.net^
```

**Comment by koqekoqe4** [comment]
Yes !

It's working...for the moment !

Thank you !
