### ISSUE TITLE
http://uploadrocket.net/

### ISSUE THREAD

**Issue by WiseSilverWolf** [reek/anti-adblock-killer#2090]
The website still detects im using an ad blocker and slows the download speeds 50x slower than normal when you click on "click for free download"

http://uploadrocket.net/h7rhepyhxls1.htm
http://uploadrocket.net/br0sp9czbedi.htm
http://imgbox.com/YeLTq082
Google Chrome 53.0.2785.101 (64 Bit)
TamperMonkey 
uBlock Origin 
EasyList + Anti-Adblock Killer (Reek) + Peter Lowe's Ad Server List
![antiadblockmessage](https://cloud.githubusercontent.com/assets/22137175/18421198/c5c7963e-7851-11e6-9469-fe7aecbad0d9.JPG)

**Comment by mapx-** [comment]
add
`@@||uploadrocket.net^$generichide`

**Comment by WiseSilverWolf** [comment]
> add
@@||uploadrocket.net^$generichide

I added that line of code to uBlock Origin > Options > My Filters

Its still giving me that message at the bottom of the page saying that my download will be slowed by 50x because im using an ad blocker.

**Comment by Afonsopirex** [comment]
Witch anime do u watch, im otaku too

**Comment by mapx-** [comment]
add
```
@@||uploadrocket.net^$generichide
@@||uploadrocket.net/*ad$script
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=uploadrocket.net
```

**Comment by xyzzy-xyzzy** [comment]
I confirm the reported problem for a uploadrocket link I just tried:

http://uploadrocket.net/x3d7mrjl4iqz/Talking.Dead.S05E27.720p.HDTV.x264-aAF.mkv.html

But I can also happily confirm the above three mapx rules solved the problem. Let's see how long this lasts.

Thanks mapx.

**Comment by WiseSilverWolf** [comment]
> add
@@||uploadrocket.net^$generichide
@@||uploadrocket.net/*ad$script
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=uploadrocket.net

Awesome! that fixed it, huge thanks mapx-

> Witch anime do u watch, im otaku too

Any type thats entertaining but this isnt really the place to discuss anime, check out myanimelist.net if you want to discuss anime.

**Comment by reek** [comment]
updated
