### ISSUE TITLE
AdReclaim, Unblockable w/ "Block Elements" from Adblock Plus and Reek's Anti AdBlock Killer

### ISSUE THREAD

**Issue by Jason010767** [reek/anti-adblock-killer#2091]
https://www.adreclaim.com/
http://www.mobipicker.com/intel-skylake-xeon-v5-specs-heres-expect/
http://www.universityherald.com/articles/39951/20160908/amd-esports-ready-7th-generation-apu-powered-boards-hp-lenovo-systems-35-65-watt-provides-multiple-excavator-cores.htm

[http://i.imgur.com/Ublb0e2.png](url)

Unblockable, with Anti-Adblock-Killer perfectly setup.

Subscribed fliters:
Adblock Warning Removal List
EasyList
EasyPrivacy
AakList (Anti-Adblock Killer)

**Comment by mapx-** [comment]
@Jason010767 , remove all those custom filters from your post, it's not readable.
Then, you have a lot of wrong filters, random filters, even entire pages (rlslog).

add this filter
`@@||mobipicker.com^$generichide`

However, this isnt the place for such requests, report other filter issues (not anti adblocking stuff) directly at easylist forum: http://forums.lanik.us/
