### ISSUE TITLE
Indian Express (Re-direction)

### ISSUE THREAD

**Issue by Degitalord** [reek/anti-adblock-killer#2093]
http://indianexpress.com/article/delhi/aap-suspends-devendra-sehrawat-from-primary-membership/

http://i.imgur.com/ZymCrJZ.jpg (redirects to link mentioned in image)

Google Chrome
Tampermonkey
Ublock Origin
EasyList + AakList

**Comment by mapx-** [comment]
add this filter
`@@||indianexpress.com/*ad$script`

**Comment by ghajini** [comment]
@mapx- 
do you have any suggestion on 
https://github.com/uBlockOrigin/uAssets/issues/139

**Comment by anirbandd** [comment]
@mapx- please confirm before suggesting. this is not a solution.

**Comment by ronnieadams** [comment]
@mapx- Its not working anymore.

**Comment by mapx-** [comment]
add
`@@||expressbpd.com$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
