### ISSUE TITLE
the-watch-series.to

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#2096]
ads on the-watch-series.to
http://imgur.com/a/ds4WG?third_party=1
http://the-watch-series.to/episode/south_park_s14_e9.html

**Comment by SMed79** [comment]
1. provide more information (browser & version ? filter lists ? adblocker ?)
2. for unblocked ads report at easylist forum https://forums.lanik.us/

3. for popup add these filters https://forums.lanik.us/viewtopic.php?f=62&t=30630&p=103062#p103062

**Comment by jeepy321** [comment]
it seems to have gone aways

**Comment by SMed79** [comment]
see also https://adblockplus.org/forum/viewtopic.php?p=158473&hilit=the-watch-series.to#p158473
