### ISSUE TITLE
http://gadgets.ndtv.com 

### ISSUE THREAD

**Issue by pmaguire13** [reek/anti-adblock-killer#2097]
http://gadgets.ndtv.com/games/news/sega-does-what-nintendont-tells-fans-keep-making-good-stuff-1457849
https://imgur.com/gV0ODJL
Google Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2018#issuecomment-244144767

**Comment by pmaguire13** [comment]
Thank you @mapx-  that worked :)

**Comment by reek** [comment]
done
