### ISSUE TITLE
Avaxhome.co

### ISSUE THREAD

**Issue by skanskan** [reek/anti-adblock-killer#2098]
http://www.avaxhome.co/
https://imgur.com/a/sqHbQ
Chrome 52.0
Tampermonkey
uBlock
EasyList + AakList + uBlock

**Comment by mapx-** [comment]
add these filters in ubo
```
@@||avaxhome.co^$generichide
@@|http://$image,domain=avaxhome.co
```

**Comment by skanskan** [comment]
PLease, could you give me a little bit more details on where and how to do it, thanks?

**Comment by mapx-** [comment]
you are using ubo, right ? You have to know how to add custom filters (right click ubo icon, click "my filters" tab, add the filter)

**Comment by skanskan** [comment]
I thought I had to do it on Tampermonkey or modifying something at anti-adblock-killer.

Anyway I think it doesn't work.

I've copied 

@@||avaxhome.co^$generichide
@@|http://$image,domain=avaxhome.co

inside the uBlock -> My filters section

but the problem is the same.
I think avaxome detects I'm using an adblocker and complains about that.

**Comment by mapx-** [comment]
It's working fine in ubo (you are using ublock origin, right ? version 1.9.4 ? )
Did you click "apply changes" after adding the 2 filters ?

Disable all other blocking extensions: ghostery, disconnect, other adblocker

**Comment by skanskan** [comment]
Yes I'm using origin origin  1.9..4 and yes, I've applied the changes.
and I've tried with Tempermoney enabled and also with it disabled.
I'm using Anti adblock killer from Tempermonkey.
https://imgur.com/a/MURQ8
https://imgur.com/a/HbCo2
https://imgur.com/a/WwzD3

**Comment by mapx-** [comment]
What other lists are you using in ubo ?
Also, you should open the logger, refresh the site, then save / copy all you see there on a site like http://pastebin.com/

then post here the pastebin link

**Comment by uBlock-user** [comment]
simply add this - avaxhome.co##script:inject(bab-defuser.js)

uBO already has a working blockadblock defuser js, inject it on all sites with BAB script.

**Comment by skanskan** [comment]
Now it works, thanks.
Should I also keep 
@@||avaxhome.co^$generichide
@@|http://$image,domain=avaxhome.co
?

**Comment by uBlock-user** [comment]
> Should I also keep 

No need remove them all. Whenever you come across any BlockAdBlock site simply add the domain name to that existing filter I posted here like this, newdomain.name,avaxhome.co##script:inject(bab-defuser.js)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
