### ISSUE TITLE
Easybib adblock

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#2099]
http://www.easybib.com/cite/edit/1473818497_57d8af8147de00.48343718
http://imgur.com/a/6MHNw
only allows 2 ad free citations than makes u pay unless u disable

**Comment by SMed79** [comment]
try to add:
`@@||media.easybib.com/*ad$script`

**Comment by jeepy321** [comment]
that pop up still comes up after every page you go on  have to hit the x every time

**Comment by SMed79** [comment]
Provide more infos (browser version ? filter lists ? adblocker ?) & how to reproduce ?

**Comment by jeepy321** [comment]
works perfect thanks

**Comment by Vinupaji** [comment]
How to bypass the ad block thing?
I am new to this, explain please?

**Comment by smed79** [comment]
@Vinupaji can you please guide me how can i reproduce ?
