### ISSUE TITLE
Confirming software needed; switched to uBlock

### ISSUE THREAD

**Issue by jaylitten** [reek/anti-adblock-killer#2102]
Sorry ... just a question; not an "issue." 

Is Tampermonkey (Chrome) or Greasemonkey (Firefox) needed if I'm using uBlock Origin? I just switched to uBlock & noticed **Anti-Adblock Killer | Reek** is an option in the "3rd-party filters" tab.

Thank you.

**Comment by uBlock-user** [comment]
That's the filter list, not the java script from reek which is also needed. Although it's your choice if you don't want to install AAK.

**Comment by SMed79** [comment]
Yes, u need the **filters list** and the **user script** https://github.com/reek/anti-adblock-killer#instruction
