### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [reek/anti-adblock-killer#2105]
Doesn't seem to work on investing.com, which is detecting my Adblock Plus and not showing content. Anyone has an idea?

**Comment by uBlock-user** [comment]
Update your Easylist filter or add this `@@||investing.com^*/ads.js`

**Comment by vijayaraghavanramanan** [comment]
Thanks. Did both. Site Still detecting adblock plus.

**Comment by uBlock-user** [comment]
Doesn't detect on uBO, so something's wrong on your side.

**Comment by rodyan** [comment]
Detection is inside this script : http://glocdn.investing.com/js/main-1.15.XX.js
Blocking this script works, but there are many other functions inside.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
