### ISSUE TITLE
Issues with playwire players

### ISSUE THREAD

**Issue by photoelephant** [reek/anti-adblock-killer#2106]
Using uBlock on Chrome with easylist and aaklist

The playwire players on the following websites detect adblocker
fullmatchesandshows.com
goalsarena.org

http://i.imgur.com/2et51as.png

**Comment by mapx-** [comment]
goalsarena: see if still works: https://github.com/reek/anti-adblock-killer/issues/1914#issuecomment-238862846

**Comment by photoelephant** [comment]
I tried but it doesn't work anymore

**Comment by mapx-** [comment]
for fullmatchesandshows, add this filter see if works for you
`@@||html5player.gamezone.com/ads.js`

**Comment by mapx-** [comment]
the same filter works also for goalsarena

**Comment by photoelephant** [comment]
It works on both sites, thanks a lot!

**Comment by uBlock-user** [comment]
For all sites - `@@||playwire.com^$generichide`

**Comment by uBlock-user** [comment]
General rule of thunk for playwire players is whitelist element hiding of the domain on which playwire player is used, simple.

**Comment by ayyazdaniaryan** [comment]
@mapx- New user here, and quick question: How can I add the filter you mentioned above? Thanks!

**Comment by mapx-** [comment]
ABP: https://adblockplus.org/forum/viewtopic.php?f=2&t=42013
ubo, click ubo icon, options, "my filters" tab

**Comment by dorkix** [comment]
@mapx-  i have added `@||html5player.gamezone.com/ads.js` in my filters but there is still a message: "You're using an ad blocker.
To view this video, please disable your ad blocker for our site.

Select your browser plugin to view instructions:"

**Comment by mapx-** [comment]
`@@/html5player.gamezone.com/ads.js`

**Comment by LPrento** [comment]
Adblock says "Failed to fetch this filter" when I try and add the above into the custom filter list.
Is there something else we need to do?

**Comment by mapx-** [comment]
adblocker ? browser ?

**Comment by LPrento** [comment]
The AdBlock extension on chrome

**Comment by mapx-** [comment]
try ABP or ubo

**Comment by LPrento** [comment]
ABP with the script works! thank you!
