### ISSUE TITLE
animmex.net, animmex.space

### ISSUE THREAD

**Issue by q1k** [reek/anti-adblock-killer#2107]
please take care of the detection
thanks
https://www.animmex.net/

**Comment by mapx-** [comment]
try this filter
`@@|https://*.ico$image`

**Comment by uBlock-user** [comment]
`@@||animmex.net^$elemhide`

**Comment by q1k** [comment]
With that it is able to play the video, but as soon as I click it opens a new tab which is immediately closed, so I end up on the next tab.

**Comment by uBlock-user** [comment]
> With that, it is able to play the video. But as soon as I click, it opens a new tab which is immediately closed

Not here, it must be some popup filter or a popunder filter causing the current tab to be closed on your side.

As for animex.space, use this - `animmex.*##script:inject(bab-defuser.js)`

**Comment by q1k** [comment]
> Not here, it must be some popup filter or a popunder filter causing the current tab to be closed on your side.
> As for animex.space, use this - animmex.*##script:inject(bab-defuser.js)

I made a manual update of the lists, and now it doesn't open a new page.

As for that filter, it doesn't work.

**Comment by uBlock-user** [comment]
Are you on uBO ? That's for uBO only. 

If you're using ABP, then `@@||animmex.*^$generichide`

**Comment by uBlock-user** [comment]
`http://www.animmex.co/
http://www.animmex.com/
https://www.animmex.net/
https://www.animmex.org/
https://www.animmex.online/
https://www.animmex.website/
https://www.animmex.xyz/
https://www.animmex.tech/
https://www.animmex.info/
https://www.animmex.site/
https://www.animmex.space/
https://www.animmex.co.uk/
https://www.animmex.club/
http://www.animmex.press/`

**Comment by q1k** [comment]
OK that's quite a lot domains. And all of them seem to work with and without the www part.

**Comment by uBlock-user** [comment]
Most of them are clones, simply use the last filter I posted and that will take care of them.

**Comment by q1k** [comment]
I actually had to add these 2:
```
@@|https://*.ico$image
@@||animmex.*^$generichide
```

**Comment by uBlock-user** [comment]
Yeah good keep them. Add new domains as you come across more BAB scripts.

**Comment by reek** [comment]
killed by Aakscript
