### ISSUE TITLE
www.ketubanjiwa.com

### ISSUE THREAD

**Issue by rigaz29** [reek/anti-adblock-killer#2108]
get blocked from ketubanjiwa
http://www.ketubanjiwa.com/2016/09/pes-2017-settings-exe-for-check-specifications.html

**Comment by mapx-** [comment]
add this filter
`||ketubanjiwa.com/wp-content/uploads/*.js?ver=1.9.2`

**Comment by uBlock-user** [comment]
This one does the job too - `@@||ketubanjiwa.com^$elemhide`

**Comment by reek** [comment]
fixed by easylist
