### ISSUE TITLE
psarips.com

### ISSUE THREAD

**Issue by bakelal** [reek/anti-adblock-killer#211]
http://psarips.com/
http://s24.postimg.org/ql090xbol/Capture.png
Cyberfox
Greasemonkey
Adblock Plus
EasyList + Fanboy +Easy Privacy +Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/153
