### ISSUE TITLE
tf2center.com/lobbies

### ISSUE THREAD

**Issue by piluke** [reek/anti-adblock-killer#2110]
https://i.imgur.com/qPw8zmH.png
Mozilla Firefox
No script manager
uBlock Origin
uBlock Filters + uBlock Badware Risks + uBlock Privacy + uBlock Unbreak + Adblock Warning Removal List + Anti-Adblock Killer + Easylist + Peter Lowe's Ad Server List + Easy Privacy + Malware Domain List + Malware Domains

I enabled all of the above filters from uBlock's preferences.
The site redirects from https://tf2center.com/lobbies to https://tf2center.com/adblock whenever I have my adblocker enabled.

**Comment by uBlock-user** [comment]
`@@||tf2center.com/assets/javascript/advert.js`

**Comment by piluke** [comment]
Nope, doesn't work

**Comment by uBlock-user** [comment]
Yes, it does. It's from the AAK script. Works perfectly here no redirections.

**Comment by piluke** [comment]
If I disable Easylist and Peter Lowe's Ad Server List, I don't get redirected. The only problem is that ads still appear. With either of them enabled I get redirected.

**Comment by uBlock-user** [comment]
That's weird, check which filters are being applied from Easylist and Peter Lowe's.

**Comment by reek** [comment]
already killed see help section

**Comment by lwizchz** [comment]
I still can't get it to work but using a host file adblocker works with this site.
