### ISSUE TITLE
cinemablend.com

### ISSUE THREAD

**Issue by reunicorn** [reek/anti-adblock-killer#2112]
http://www.cinemablend.com/games/1532409/how-you-can-purchase-the-pokemon-go-plus-accessory-when-its-available-again
http://imgur.com/QvuM5S8
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by uBlock-user** [comment]
`@@||cinemablend.com^$elemhide`

**Comment by mapx-** [comment]
like here: https://github.com/reek/anti-adblock-killer/issues/2106#issuecomment-247343209

for other 2 sites 
fullmatchesandshows.com
goalsarena.org

**Comment by reunicorn** [comment]
That fixed it, thank you very much!
