### ISSUE TITLE
Youtube.com - blackscreen

### ISSUE THREAD

**Issue by Christley** [reek/anti-adblock-killer#2113]
https://www.youtube.com/watch?v=xveDEFe0aMU
http://i.imgur.com/aWK1Ijj.png
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList + Adblock Warning Removal List

it doesnt matter which video i watch. they're all black when watching them. the sound works, the thumbnails in the timeline displays. just the image of the video doesnt. if i disable the script in greasemonkey the video works fine again and there's no blackscreen.

**Comment by uBlock-user** [comment]
Works perfectly fine here, something's up on your end.

**Comment by reek** [comment]
all fine, see https://github.com/reek/anti-adblock-killer#help
