### ISSUE TITLE
www.dallasnews.com

### ISSUE THREAD

**Issue by eleazar6** [reek/anti-adblock-killer#2114]
http://www.dallasnews.com/business/retail/20160914-amazon-just-opened-pop-up-stores-in-arlington-san-antonio-11-other-states.ece
http://imgur.com/a/ZRJJW
Google Chrome 49.0.2623.112 m
Tampermonkey
uBlock Origin
Easylist & AAK (Reek)

**Comment by mapx-** [comment]
add this filter
`@@||npttech.com/advertising.js$script,domain=dallasnews.com`

**Comment by eleazar6** [comment]
I'm new to this.. do I add this to the uBlock Origin "My Filters" tab?

**Comment by mapx-** [comment]
yes, exactly

**Comment by eleazar6** [comment]
Thanks! That page's ads bring my ancient WinXP machine to a crawl.

**Comment by reek** [comment]
fixed by easylist
