### ISSUE TITLE
cinemablend.com

### ISSUE THREAD

**Issue by damnnative** [reek/anti-adblock-killer#2116]
http://www.cinemablend.com/television/1556969/one-supergirl-character-wont-be-so-happy-to-see-superman

https://s10.postimg.org/uysw9tb89/yeaboi.png

Chrome, latest
ABP, EasyList, EasyPrivacy, AakList
Tampermonkey, latest with Aak Script

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2112
