### ISSUE TITLE
Youwatch

### ISSUE THREAD

**Issue by hanjo42** [reek/anti-adblock-killer#2120]
Hi,
I Have installed the AAK Script, it work perfectly for some sites. 
But a the begining if I had searched for a script who block the detection of my Ad Blocker it's for a streaming site who use mainly Youwatch.
So if someone has a technique for youwatch i praise you to give it to me.
Or If it need a patch or a new script i'll make a donnation to the author of this script

**Comment by hanjo42** [comment]
Thanks

**Comment by uBlock-user** [comment]
no link no help

**Comment by Ntweat** [comment]
https://x01x012013.github.io/AdBlockProtector/   install this..

**Comment by reek** [comment]
Hi,

Ok, I'll fix it

**Comment by hanjo42** [comment]
thanks :) 

----- Mail original -----

De: "reek" <notifications@github.com> 
À: "reek/anti-adblock-killer" <anti-adblock-killer@noreply.github.com> 
Cc: "hanjo42" <johan.guerra@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 7 Novembre 2016 19:20:52 
Objet: Re: [reek/anti-adblock-killer] Youwatch continue to detect my Ad blocker (AdBlock+) (#2120) 



Hi, 

Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
