### ISSUE TITLE
8muses not working ... again ..

### ISSUE THREAD

**Issue by swathigrate** [reek/anti-adblock-killer#2121]
www.8muses.com and http://apkmos.com/ 
http://imgbox.com/wG3NNspZ
Mozilla Firefox 48.0 beta7
Greasemonkey 3.9 Beta2
Adblock Plus 2.7.3
EasyList + AakList + AdBlock Warning removal list 

now  i'm facing  a small issue ...when  open the site ,, showing  *_Disable ad blocker *_  
 that time i'm  refresh the page ...   after the  refresh  working very nicely ,,, 

> @mapx- given this  and  add to  ABP
>  @@||apkmos.com^$generichide   

please fix  this 
thanks you

**Comment by mapx-** [comment]
apkmos is working for me using generichide filter
8muses is working with the current easylist

if still does not work install the last dev build of ABP for firefox: 
https://addons.mozilla.org/downloads/latest-beta/adblock-plus/adblockplus-devbuild.xpi

**Comment by swathigrate** [comment]
thanks for reply @mapx-  
apkmos and 8muses r   working  fine  now ...

**Comment by uBlock-user** [comment]
They were already working fine, your adblocker must be acting up

**Comment by swathigrate** [comment]
hello  @mapx-  and @uBlock-user 

today also i checked  8muses.com/ ... some times  it's working fine  and  sometime not ...

after refresh ,,, it'l work ...
![untitled](https://cloud.githubusercontent.com/assets/14991260/18663229/40016642-7f3b-11e6-9156-55d792abf2a1.JPG)

**Comment by mapx-** [comment]
no issues for me

**Comment by mapx-** [comment]
use only 1 blocking addon (disable / remove ghostery, disconnect ..)

**Comment by swathigrate** [comment]
HELLO SIR ,

THANKS FOR  REPLY 
I'D ONLY ONE  BLOCKING ADDON ... 

THANKS YOU 
![de](https://cloud.githubusercontent.com/assets/14991260/18743021/b84047d2-80d4-11e6-83b0-f459fced1c23.jpg)

**Comment by rjkpa** [comment]
Remove Adblocker for youtube and adblock plus also, switch to uBlock Origin and you won't have this trouble.

**Comment by reek** [comment]
I'll fix it again

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
