### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by ZeroXFFF1** [reek/anti-adblock-killer#2122]
http://kissanime.to/Anime/Mob-Psycho-100/Episode-006?id=129046
http://i.imgur.com/wWc04WT.png
Google Chrome
Tampermonkey
uBlock Origin
Easylist+aaklist + Anti-Adblock Killer | Reek‎

The detection rate isn't 100%, and I think it might have something to do with pausing the stream or bringing up a different tab while the stream is running.

**Comment by mapx-** [comment]
see
https://github.com/reek/anti-adblock-killer/issues/2118#issuecomment-247806049

**Comment by uBlock-user** [comment]
Already patched on ublock origin via this filter -`kissanime.to##script:inject(kissanime-defuser.js)`

**Comment by reek** [comment]
killed by aakscript
