### ISSUE TITLE
mumbaimirror.indiatimes.com

### ISSUE THREAD

**Issue by ghajini** [reek/anti-adblock-killer#2127]
http://mumbaimirror.indiatimes.com/news/india/Navy-divers-brave-rough-seas-for-12-hrs/articleshow/54412321.cms

ublock origin 1.9.4
chrome

**Comment by mapx-** [comment]
```
@@||partner.googleadservices.com^$domain=indiatimes.com
@@||clmbtech.com^$script,domain=indiatimes.com
@@||crwdcntrl.net^$script,domain=indiatimes.com
@@||chartbeat.com^$domain=indiatimes.com
@@||indiatimes.com^$generichide
@@$image,domain=indiatimes.com
@@||ads.pubmatic.com^$script,domain=indiatimes.com
@@||timesinternet.in^$script,domain=indiatimes.com
@@||indiatimes.com/*ad$script
```

**Comment by ghajini** [comment]
these wil lbe in easylist, am i right?

**Comment by uBlock-user** [comment]
Just add this rule `||timesofindia.indiatimes.com/ads_native_js/version-9.cms$script`

**Comment by reek** [comment]
ok, I'll kill it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
