### ISSUE TITLE
rutube.ru

### ISSUE THREAD

**Issue by StVol33** [reek/anti-adblock-killer#213]
http://rutube.ru/video/70ac00eb4d940ec3244344dc7b7105e4/
Mozilla Cyberfox
µBlock
EasyList + Anti-Adblock Killer | Filters for Adblockers
![2015-02-27_00-04-10](https://cloud.githubusercontent.com/assets/11031379/6401909/cec0f864-be14-11e4-9101-7756450307e0.png)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
No problem found

**Comment by StVol33** [comment]
Sorry for not a complete description of the problem: it is necessary to choose  " лучшее"!
![2015-02-27_11-07-55](https://cloud.githubusercontent.com/assets/11031379/6409224/7c5a9f3c-be71-11e4-99b3-0cde9dc97084.png)

**Comment by reek** [comment]
https://greasyfork.org/forum/discussion/3316/rutube-ru-again

**Comment by F4z** [comment]
I know that it is old issue, but it is still open, I think that I found solution for that, but would be nice if someone could test it, for me it works:
@@||ad4.liverail.com/?$object-subrequest,domain=rutube.ru
@@||vox-static.liverail.com/swf/v4/$object-subrequest,domain=rutube.ru

**Comment by StVol33** [comment]
F4z, 
I'm sorry , but I is not working !

**Comment by reek** [comment]
@F4z 
Works for me just with this rule
<pre>@@||ad4.liverail.com/?LR_PUBLISHER_ID=$object-subrequest,domain=rutube.ru</pre>

**Comment by StVol33** [comment]
F4z
These filters work if I change my russian IP by  ZenMate

**Comment by Alexey71** [comment]
Please fix rutube
