### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by Pablete1234** [reek/anti-adblock-killer#2134]
blockadblock.com
https://i.imgur.com/FJQD8Up.png
Chromium
Tampermonkey
Adblock plus
Easylist

At first the page loads without any ads, but after a couple of seconds, the pop up appears and page gets removed, i've seen other pages using the script

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/1799#issuecomment-236997275

**Comment by never93489** [comment]
Is there not facility in the greasemonkey menu for adding something for users to perform one-click reporting?
