### ISSUE TITLE
Bhaskar.com

### ISSUE THREAD

**Issue by savinay4u** [reek/anti-adblock-killer#2136]
My previous problem had been resolved by you people. Thankyou so much. But I didn't find my previous request, it is not their. Did REEK removed the script for dainik bhaskar ????

Now again we are facing the problem with dainik bhaskar. Please resolve it as soon as possible. 

Link :-

http://www.bhaskar.com/news-ht/NAT-NAN-modi-govt-in-action-after-uri-attack-news-and-updates-news-hindi-5421561-PHO.html

**Comment by mapx-** [comment]
add the filters here (easylist forum)
https://forums.lanik.us/viewtopic.php?p=103461#p103461

**Comment by reek** [comment]
done
