### ISSUE TITLE
Lexpress.fr detects adblocker

### ISSUE THREAD

**Issue by dotixx** [reek/anti-adblock-killer#2139]
http://www.lexpress.fr
http://imgur.com/a/P2Yhs
Opera
TamperMonkey
Opera built-in adblocker
AakList

**Comment by mapx-** [comment]
add
```
@@||lexpress.fr^$generichide
@@||foglio.basilic.io^$script
@@||static.lexpress.fr/*ad
```

**Comment by dotixx** [comment]
@mapx- where should I add this, please ?

**Comment by mapx-** [comment]
your custom filters in opera adblocker
