### ISSUE TITLE
dl-protect.com

### ISSUE THREAD

**Issue by JBey4you** [reek/anti-adblock-killer#214]
http://www.dl-protect.com/7D6FC1E8
http://i.imgur.com/SnoHAG8.jpg
Google Chrome
Greasemonkey
uBlock or Adblock (same result)
Anti-Adblock Killer | Reek‎, EasyList‎, Peter Lowe’s Ad server list‎, EasyPrivacy‎, Dan Pollock’s hosts file‎,  MVPS HOSTS‎, EasyList Liste FR‎

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

This is not an anti adblock

try just this lists
Anti-Adblock Killer | Reek‎
EasyList‎,
EasyList Liste FR‎
