### ISSUE TITLE
Anti-Adblock

### ISSUE THREAD

**Issue by alexdahlmandrm** [reek/anti-adblock-killer#2140]
1)http://seekingalpha.com/article/4007587-5-millennial-friendly-etf-investing-ideas
2)Attached: ![anti-adblock](https://cloud.githubusercontent.com/assets/20130553/18717703/fc0c6b0a-7fdd-11e6-838d-05c9ee4ccdbd.PNG)
3)Chrome: Version 53.0.2785.116 m
4)Tampermonkey
5)uBlock Origin
6)https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
 My filters‎ : 0 used out of 0
**X**  uBlock filters‎ : 958 used out of 959purge cache
**X** uBlock filters – Badware risks‎  (github.com): 7 used out of 7
 uBlock filters – Experimental‎  (github.com): 0 used out of ?
**X**  uBlock filters – Privacy‎ : 50 used out of 50
**X** uBlock filters – Unbreak‎ : 113 used out of 114purge cache
Ads (3)
 Adblock Warning Removal List‎ (forums.lanik.us): 0 used out of ?purge cache
**X** Anti-Adblock Killer | Reek‎  (github.com): 2,009 used out of 2,009purge cache
**X** EasyList‎ (forums.lanik.us): 67,427 used out of 67,502purge cache
 EasyList without element hiding rules‎ (forums.lanik.us): 0 used out of ?
 **X**Peter Lowe’s Ad server list‎ (pgl.yoyo.org): 2,364 used out of 2,364purge cache
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
