### ISSUE TITLE
olweb.tv and ontvfree2.me

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#2144]
link http://www.olweb.tv/comedy-central
link:http://ontvfree2.me/watch/comedy-central-usa-live
http://imgur.com/a/qS6sa 
http://imgur.com/a/lXPwX
cant view live stream with adblocker on

**Comment by mapx-** [comment]
```
@@||ontvfree2.me^$generichide
@@||olcdn.net$script
```

**Comment by jeepy321** [comment]
thanks
