### ISSUE TITLE
01net.com

### ISSUE THREAD

**Issue by Nico3d3** [reek/anti-adblock-killer#2148]
I visited this page http://www.01net.com/actualites/firefox-49-est-la-voici-ses-principales-ameliorations-1039404.html and I was welcomed with a message asking to disable my AdBlock even with Reek killer script.

**Comment by maynak00** [comment]
**try with:**
`@@||static.bfmtv.com/ressources/js/ads.js$script,domain=01net.com`

**Comment by reek** [comment]
done
