### ISSUE TITLE
lachainemeteo.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#215]
Hi, 
site: hxxp://france.lachainemeteo.com/meteo-france/previsions-meteo-france-0.php
sc: http://img15.hostingpics.net/pics/323310Capture.png
script: http://www.lachainemeteo.com/js/lachainemeteo.js

source: https://forums.lanik.us/viewtopic.php?f=91&t=21174

Thank you.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Problem to load : MES FAVORIS MÉTÉO
sc: http://i.imgur.com/R529Kte.png
Try with : 
lachainemeteo.com##[style^="width: 100%; height: 3"]:last-child
https://hg.adblockplus.org/listefr/rev/e310fe80fb38

**Comment by reek** [comment]
Hi,

Ok, I'll try to find another solution.

**Comment by SMed79** [comment]
anti-adblock now added to body http://pastie.org/private/5ezzzzwqhcndmeji84cjsa

**Comment by SMed79** [comment]
@@||ww691.smartadserver.com^$domain=lachainemeteo.com
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=lachainemeteo.com

**Comment by reek** [comment]
Thanks SMed ;)

**Comment by reek** [comment]
Your rules are no longer valid, but I have corrected the problem.

**Comment by SMed79** [comment]
Maybe because the code change every day :-/
you can remove this filter: 
@@||lachainemeteo.com/js/lachainemeteo.js$script
https://hg.adblockplus.org/listefr/rev/fe4e80d6054a#l1.12

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
