### ISSUE TITLE
go.wolfram-client.tk (adf.ly)

### ISSUE THREAD

**Issue by TypeV** [reek/anti-adblock-killer#2158]
This site prevents me from using an ad-blocker there.
For example: http://go.wolfram-client.tk/10371505/wolfram-7-0-1-download
Also, this site automatically opens a pop-up when you click "go". Any way to stop these?

**Comment by mapx-** [comment]
try these filters
```
@@||wolfram-client.tk^$generichide
||cloudfront.net$domain=go.wolfram-client.tk
@@||static.adf.ly/static/image/ad_top_bg2.png
s1-adfly.com##[src^="http://clkfeed.com/adServe/"]
```

**Comment by TypeV** [comment]
Wow thanks!
Also, do you have any idea of any TamperMonkey scripts or extensions to stop the pop-ups ads? Its ok if you don't respond because you have already done more than enough 😄

**Comment by mapx-** [comment]
Today there are a lot of ways the popups get through the pages. So, better report those pages, your system details (browser, adblocker). For popups report those pages directly to easylist forums: http://forums.lanik.us/

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
