### ISSUE TITLE
academia.edu

### ISSUE THREAD

**Issue by katemilty** [reek/anti-adblock-killer#216]
The analytics/hits counter on Academia.edu is being blocked by this list. Academia.edu is a free social network for academics.
Ex page: http://team.academia.edu/KateMiltenberger

Browser: Chrome
Adblocker: µblock
Filterlists: [Anti-Adblock Killer | Reek‎ (githubusercontent.com): 742 used out of 797]
![block_ _dashboard](https://cloud.githubusercontent.com/assets/7738350/6424487/ed7fa980-beaf-11e4-9509-a5f012876b03.png)

This is one of two causing the issue. Determined via testing with µblock filters.

Screenshots:
With your filter enabled:
![with_privacy_blocker](https://cloud.githubusercontent.com/assets/7738350/6424444/795f554c-beae-11e4-84d4-a3aab5cce8e1.png)

Without the filter:
![without_privacy_blocker](https://cloud.githubusercontent.com/assets/7738350/6424448/8497401e-beae-11e4-9624-780391b1919a.png)

**Comment by reek** [comment]
Hi,

The problem does not come from aaklist but the EasyPrivacy list,
but I can add a rule to resolve the problem.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
