### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by badri77** [reek/anti-adblock-killer#2161]
i still see : your ad blocker is on! even after installing your script using script manager extension for chrome browser

**Comment by mapx-** [comment]
Where did you see that message ? Which page ?

**Comment by badri77** [comment]
Www.indianexpress.com and any link after that

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2093#issuecomment-246465758

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
