### ISSUE TITLE
naasongs.com / ndtv.com/reviews / fullstuff.co

### ISSUE THREAD

**Issue by kullurumanoj** [reek/anti-adblock-killer#2164]
http://naasongs.com 

http://gadgets.ndtv.com/reviews 

https://fullstuff.co 

Opera
Adblock Plus--EasyList + AakList  
Adblock--AakList

**Comment by rjkpa** [comment]
`@@||naasongs.com^$elemhide`

`@@||ndtv.com^$elemhide`

`@@||fullstuff.co^$elemhide`

**Comment by kullurumanoj** [comment]
Could you help me where to add these lines. Please I am new to this.

**Comment by mapx-** [comment]
use only one adblocker.

for ABP see how to:
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

and replace $elemhide with $generichide

($elemhide in ubo means $generichide in ABP / AB)

**Comment by rjkpa** [comment]
elemhide and generichide both work in ABP, so either of them.

**Comment by kullurumanoj** [comment]
http://naasongs.com/eedu-gold-ehe-2016.html

The above script is not working bro

**Comment by mapx-** [comment]
add
```
@@||nsongs.com^$generichide
@@||naasongs.com^$generichide
@@|http://*adv$image,domain=naasongs.com|nsongs.com
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
