### ISSUE TITLE
flashback.org

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#217]
* flashback.org###top-banner-container
* https://www.flashback.org/
* https://i.imgur.com/b4TzPPk.png
* Firefox 35.0.1
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.8
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
