### ISSUE TITLE
Adf.ly

### ISSUE THREAD

**Issue by vitaprimo** [reek/anti-adblock-killer#2171]
http://adf.ly/1dzZ4X
![screen shot 2016-09-26 at 06 37 15](https://cloud.githubusercontent.com/assets/18566096/18834648/61757944-83b4-11e6-9906-5be09550b0d5.png)
Apple Safari Version 10.0.1 (12602.2.7)
Tampermonkey
1. Adblock Plus & AdBlock, 2. Adblock Plus only, 3. AdBlock only
AakList

**Comment by LaBlazer** [comment]
`@@||static.adf.ly/static/image/ad_top_bg2.png
s1-adfly.com##[src^="http://clkfeed.com/adServe/"]`

**Comment by mapx-** [comment]
from 
https://github.com/reek/anti-adblock-killer/issues/2158#issuecomment-249390305

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
