### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by vpandey-rms** [reek/anti-adblock-killer#2189]
http://indianexpress.com/adblocker/
http://imgur.com/a/8od5W
Google Chrome
Tampermonkey
Adblock Plus
AakList

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2093#issuecomment-246465758

**Comment by ronnieadams** [comment]
@mapx- Not working anymore

**Comment by mapx-** [comment]
`@@||expressbpd.com$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
