### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by cae2029** [reek/anti-adblock-killer#2190]
http://br.investing.com/
http://imgur.com/a/uBeUW
Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by rjkpa** [comment]
already patched, force update Easylist

**Comment by cae2029** [comment]
Still detecting Adblock Plus

**Comment by rjkpa** [comment]
Add this - `@@||investing.com^*/ads.js`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
