### ISSUE TITLE
http://www.lequipe.fr/

### ISSUE THREAD

**Issue by Giljulien** [reek/anti-adblock-killer#2195]

**Comment by M3T4LL1C4** [comment]
Add these filters:
@@||ayermaury.dorrancebonsecour.com/$image,domain=www.lequipe.fr
@@||nazlinispeaks.roosebeckseaforth.com/$image,domain=www.lequipe.fr

**Comment by mapx-** [comment]
or
https://github.com/reek/anti-adblock-killer/issues/2051#issuecomment-245194185

**Comment by Giljulien** [comment]
Thank's a lot !




Sent with SndLatr for Gmail<https://api.thetopinbox.com/track/v2/go?id=2001>

2016-09-30 18:30 GMT+02:00 mapx- <notifications@github.com<mailto:notifications@github.com>>:

or
#2051 (comment)<https://github.com/reek/anti-adblock-killer/issues/2051#issuecomment-245194185>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
