### ISSUE TITLE
toolslib.net

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#220]
A while ago I reported elements on https://toolslib.net/downloads/finish/1/ to EasyList (https://forums.lanik.us/viewtopic.php?f=62&t=20345) and it seems like the list contributor who handled the report found an anti-Adblock element on the page as well: https://hg.adblockplus.org/antiadblockfilters/rev/ec4e16847e65

I can't see where that element is and I have no more information to provide. Sorry.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
