### ISSUE TITLE
http://zfilm-hd.net/

### ISSUE THREAD

**Issue by BanHammerYKT** [reek/anti-adblock-killer#2200]
![snap4](https://cloud.githubusercontent.com/assets/5725779/19010289/cdd913fe-87b8-11e6-86ad-a53abcc025ac.png)

**Comment by mapx-** [comment]
test these filters
```
@@||capricornus.cc^$domain=yallaneliera.com
@@||zfilm-hd.net/templates/Default/regger/js/popup.js
```

**Comment by BanHammerYKT** [comment]
Yes, it works
![snap4](https://cloud.githubusercontent.com/assets/5725779/19012788/2c8df1b2-87fa-11e6-9376-6efd347c5494.png)

**Comment by BanHammerYKT** [comment]
@mapx- 
problem come back
filters not works
> @@||capricornus.cc^$domain=yallaneliera.com
> @@||zfilm-hd.net/templates/Default/regger/js/popup.js

![2](https://cloud.githubusercontent.com/assets/5725779/21087438/1e20cfd0-c069-11e6-9e4a-1e859a6f3b57.png)

**Comment by mapx-** [comment]
try
```
@@||zfilm-hd.net/templates/Default/regger/js/popup.js
@@||neutralen.nl^$domain=yallaneliera.com
```

**Comment by BanHammerYKT** [comment]
@mapx- 
WoW how you do that?
and a... how disable ads timer?
thnx
