### ISSUE TITLE
http://gadgets.ndtv.com/

### ISSUE THREAD

**Issue by malonehedges** [reek/anti-adblock-killer#2202]
http://gadgets.ndtv.com/apps/features/tim-cook-on-how-artificial-intelligence-is-enriching-apple-865872

Very simple anti-adblocking technique, fixed manually by removing `display: none;` from the article body.

**Comment by SMed79** [comment]
search before posting ... https://github.com/reek/anti-adblock-killer/issues/2018#issuecomment-244144767

**Comment by reek** [comment]
done
