### ISSUE TITLE
Had issues with this site before... NSFW

### ISSUE THREAD

**Issue by pmaguire13** [reek/anti-adblock-killer#2209]
Site : http://milfzr.com/
Screenshot : http://imgur.com/c1un6lc
Browser : chrome
Script manager : Tampermonkey
Type of adblock : Adblock 
Filterlists : EasyList, Adblock Warning Removal list, AakList 

I have had the same issue with this site a while ago, it was fixed, and then its doing it again... persistent fuckers won't give up

**Comment by mapx-** [comment]
**add NSFW in the subject line for porn sites** 

add this filter
`@@||milfzr.com^$generichide`

**Comment by pmaguire13** [comment]
Thank you, and sorry about the NSFW thing, I fixed it
