### ISSUE TITLE
fapxl.com

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#2211]
NSFW

`http://fapxl.com/video/3364067/one-cock-for-two-hot-girls-satisfaction`
https://cloud.githubusercontent.com/assets/16030872/19046953/18b0fe76-89a0-11e6-8ed3-d05b5835e2d9.png
Google Chrome 53.0.2785.116
Tampermonkey 4.1.10
uBlock Origin 1.9.10
Default + AakList

`/blockadblock.js$script` in AakList let's the video player disappear.

**Comment by ghost** [comment]
Doesn't seem to be an issue anymore. Video displays fine.
