### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by savinay4u** [reek/anti-adblock-killer#2237]
Please check this out ....

http://gadgets.ndtv.com/mobiles/news/honor-8-doctor-strange-limited-edition-handset-announced-1472825

Please give the filter for this site !!

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2018#issuecomment-244144767

**Comment by reek** [comment]
done

**Comment by ssrb19** [comment]
@reek @mapx- tried all of these. none work since today morning:
@@||ndtv.com^$elemhide
@@||zedo.com^$script,domain=ndtv.com
@@||ndtv.com^$script,domain=ndtv.com
@@||ads.rubiconproject.com$script,domain=ndtv.com
@@/adv$script,domain=ndtv.com
||taboola.com^
@@||gadgets360.com^$script,domain=ndtv.com

**Comment by positive5** [comment]
ndtv.com is not working with any of existing scripts.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
