### ISSUE TITLE
hackintosh.zone / hackintosh.computer

### ISSUE THREAD

**Issue by kamild1996** [reek/anti-adblock-killer#2239]
1. http://www.hackintosh.zone/file/810-nireshs-yosemite-with-amd-intel-iso-usb/
2. Just writes in plain text: "Please disable your adblock and script blockers to view this page"
3. Vivaldi
4. Tampermonkey
5. uBlock Origin
6. By default: uBlock Filters, EasyList, Peter Lowe’s Ad server list‎, Anti-Adblock Killer, AakList

**Comment by mapx-** [comment]
add this filter
`@@||hackintosh.zone/*ads$script`

**Comment by kamild1996** [comment]
Works for hackintosh.zone, thank you!
There's also hackintosh.computer. The message above is gone, but with adblock enabled, the page shows yet another notification. http://imgur.com/nGdqxMl
Additionally, the page wants you to share their page to show the content if adblock is enabled.
Example: http://www.hackintosh.computer/?p=7

**Comment by mapx-** [comment]
add
```
@@||hackintosh.computer^$generichide
@@||hackintosh.computer/*ad$script
```

**Comment by kamild1996** [comment]
Thanks, the message is gone although it still asks for sharing the article.

**Comment by mapx-** [comment]
add also
`hackintosh.computer##.onp-sl`

**Comment by kamild1996** [comment]
It got removed, but the article is still not shown. http://imgur.com/C0ioD1a

**Comment by mapx-** [comment]
ok, add all these filters
```
@@||hackintosh.computer^$generichide
@@||hackintosh.computer/*ad$script
@@||pagead2.googlesyndication.com^$script,domain=hackintosh.computer
hackintosh.computer##.adscenter
hackintosh.computer###googleads
```

**Comment by kamild1996** [comment]
All seems fine now, thank you @mapx- !

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
