### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by Zreh** [reek/anti-adblock-killer#224]
www.apkmirror.com

http://i.imgur.com/I1C4ygi.png
Chrome
Tampermonkey
Adblock (getadblock.com)
EasyList + AdBlock Warning Removal list (removes messages about using AdBlock) +Anti-Adblock Killer

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by pranav-prakash** [comment]
Seemed to have stopped working, at least on my end. Can anyone else confirm?

**Comment by reek** [comment]
Hi,

Please, your configurations and requests blocked.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by pranav-prakash** [comment]
Sorry, my bad -- forgot to install the tampermonkey script. Please close.

**Comment by archon810** [comment]
Fuck both of you.

**Comment by RoneyThomas** [comment]
Does donating money support any of the blocked website???

**Comment by Richie97** [comment]
ಠ_ಠ

**Comment by archon810** [comment]
@RoneyThomas Of course not.

**Comment by Burnergames** [comment]
I do love how you ask for donations on your software that makes sure that websites dont get money that they actually earned. 
I'll be sure to ask for donations the next time I release a pirated game, or give someone stolen goods, or some other shit along those lines.

**Comment by RoneyThomas** [comment]
@Burnergames +1

**Comment by kcschan** [comment]
@Burnergames 
@RoneyThomas 

You guys are recommended to get educated, with the Philosophy part of the ublock origin:
"That said, it's important to note that using a blocker is NOT theft. Don't fall for this creepy idea. The ultimate logical consequence of blocking = theft is the criminalisation of the inalienable right to privacy."

https://github.com/gorhill/uBlock

**Comment by Burnergames** [comment]
@kcschan
I'm fairly sure I didn't say it was theft. I said "I do love how you ask for donations on your software that makes sure that websites dont get money that they actually earned." Followed by providing a few instances where the entire internet would call me out for doing something similar - ads inherently remove the price of a website being used, and while I won't go into the general 'to adblock or not to adblock' debate, you are asking users of your software to pay you for helping them make sure that the creators of various websites dont have an ability to get money, which when looked at in that form, seems substantially worse than just blocking ads. 

Go ahead with the adblock, I have friends that have very bad internet and need adblock, but don't ask for money from that. Or at the least suggest donating to the site that you're blocking ads on.

**Comment by kcschan** [comment]
@Burnergames 
It is moral to
"you are asking users of your software to pay you for helping them make sure that the creators of various websites don't have an ability to get money"

not to
"let websites pay for a whitelist".

Because the users are the other half participating the game, who have the same rights as content provider, choosing what to see(provide) and what not to see(provide). Then everyone can sit down and make a fair agreement, as both sides possess Carrot and Stick.

**Comment by Burnergames** [comment]
@kschan
Here's the thing. Yes you and the provider have the same rights. And that's
fine and all. But you are literally asking for people to directly provide
you with money for creating software that has the inherent purpose of
making sure that people who request that you deal with small boxes of
information that the majority of users are not affected by, despite the
fact that it the method of advertisements requires exactly $0.00 to maybe
$0.000000001 per page visit. And if that isn't at least being a little bit
of an - pardon my language but this is the most logical word that comes to
mind - asshole. Now I'm aware if the fact that github repos cost money. But
there are literally thousands of other ways to make the $1 needed for this
repo. So really donations can't be justified. And again, if donations are
going to be requested, at the least provide people with a link to donate to
the website that they're blocking ads from.

And no the "its legal thus I should do it" argument doesn't work. Ever. So
scrap that one real quick.

**Comment by Richie97** [comment]
Repos only cost money if they're private

**Comment by maynak00** [comment]
site detecting adblocker without inline script blocking.
**my custom filter:**
>||www.apkmirror.com$inline-script,domain=www.apkmirror.com

**are there another/better filter ?**

**Comment by Raavizz** [comment]
> @Burnergames : asshole.

Stop your drama / insulting / bad words.
