### ISSUE TITLE
http://gadgets.ndtv.com/

### ISSUE THREAD

**Issue by Drflash55** [reek/anti-adblock-killer#2245]
http://gadgets.ndtv.com/games/news/is-nintendo-duo-the-official-name-of-the-nintendo-nx-1473277
Content is blocked by the site detecting the AdBlocker.
_Image cannot be provided at this time_
Google Chrome
Tampermonkey
AdBlock
EasyList + AakList

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2018#issuecomment-244144767

**Comment by reek** [comment]
done
