### ISSUE TITLE
cwtv.com Ad Blocker detected

### ISSUE THREAD

**Issue by BushTrocity** [reek/anti-adblock-killer#2248]
Full site URL http://www.cwtv.com/shows/the-flash.

**Comment by mapx-** [comment]
see
https://forums.lanik.us/viewtopic.php?p=105252#p105252

**Comment by mapx-** [comment]
```
@@||secure.footprint.net^$domain=cwtv.com
@@||pubads.g.doubleclick.net^$domain=cwtv.com
@@/crossdomain.xml$domain=cwtv.com
@@||$script,domain=cwtv.com
@@||images.cwtv.com^
@@||vindicosuite.com^$object-subrequest,domain=cwtv.com
@@||rtr.innovid.com^$domain=cwtv.com
```

**Comment by BushTrocity** [comment]
Added the filers to my list but it doesn't work

**Comment by mapx-** [comment]
be sure you aren't using other blocking extensions / addons.

**Comment by BushTrocity** [comment]
I'm using Chrome with uBlock Origin. I have Tampermonkey but it is off and still doesn't work. Am i doing something wrong?

**Comment by mapx-** [comment]
tested your link right now in ubo, all fine here.
Did you add correctly the filters above ? (7 filters ==> 7 rows)

**Comment by mapx-** [comment]
keep ubo filters + easylist + easyprivacy, disable all other lists (if any)

**Comment by BushTrocity** [comment]
That did it! Thanks for your help!
