### ISSUE TITLE
vgtv.no

### ISSUE THREAD

**Issue by f903242** [reek/anti-adblock-killer#225]
http://www.vgtv.no/#!/video/108948/verdens-farligste-jobb
http://i.imgbox.com/4Lv56y7o.png
Mozilla Firefox 35.0.1
AdBlock Plus 2.6.7
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Translate please.

**Comment by krize604** [comment]
It just says on top "Ad 1/2: Your Video Starts in 19 seconds", this is when playing videos ...

They also got another check which appears around the edges (when using Adblock Plus), all ads are removed but it detects the Ad Block is running: http://imgbox.com/gallery/edit/pbi5qYnO7c/4Wwba17aPbuwZ8CK (Just one box appears, to enable ads again ( The Skru på Annonser button).

**Comment by reek** [comment]
No solution

**Comment by kristofferR** [comment]
Here's a fork of this project that is supposed to fix vgtv.no:

https://github.com/ColdIce1/anti-adblock-killer

**Comment by reek** [comment]
¨Thanks kristofferR

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
