### ISSUE TITLE
crackberry.com using Admiral blocker

### ISSUE THREAD

**Issue by gizmo21** [reek/anti-adblock-killer#2250]
http://crackberry.com/      seems to use Admiral Adblock-Killer https://getadmiral.com/
http://i.share.pho.to/a7b496ca_o.png
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by mapx-** [comment]
add
```
@@||crackberry.com^$generichide
@@.ico$domain=crackberry.com
```
