### ISSUE TITLE
xavierstuder.com

### ISSUE THREAD

**Issue by Bryfon** [reek/anti-adblock-killer#2251]
https://www.xavierstuder.com/
http://imgur.com/a/njA1Z
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList + List FR

Many thanks!

**Comment by mapx-** [comment]
add
`@@||xavierstuder.com^$generichide`

if does not work install the last dev build of ABP
https://addons.mozilla.org/downloads/latest-beta/adblock-plus/adblockplus-devbuild.xpi

**Comment by Bryfon** [comment]
It Works! thanks!
