### ISSUE TITLE
autosport.com

### ISSUE THREAD

**Issue by denydias** [reek/anti-adblock-killer#2259]
http://www.autosport.com/
[Screenshot](https://cloud.githubusercontent.com/assets/948202/19410331/b9ca37b4-92bf-11e6-8f5b-053265817a75.png)
Chromium 53.0.2785.92
Tampermonkey
uBlock₀
My filters‎ + uBlock filters‎ + uBlock filters – Badware risks + uBlock filters – Privacy + uBlock filters – Unbreak‎ + Anti-Adblock Killer | Reek‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Malware domains‎ + Malware domains (long-lived)

**Comment by mapx-** [comment]
add
`@@||autosport.com^$generichide`

**Comment by denydias** [comment]
Tks,, @mapx-. Any chance this could be merged to the main rules or can I just close the issue?

**Comment by denydias** [comment]
Using as custom filter. No further action needed.
