### ISSUE TITLE
cnet.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#226]
* http://www.cnet.com/videos/toughest-smartphones/
* https://i.imgur.com/d3zlktW.png
* Firefox 36.0
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.8
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

Videos on cnet.com have a countdown from 6 to 1 and then never start, even if I disable Adblock Edge. I'm not sure if this is an anti-Adblock measure, but it may very well be.

**Comment by reek** [comment]
No problem for me

**Comment by anonsubmitter** [comment]
It's weird though that I still have the problem even with Adblock Edge and Privacy Badger disabled.
