### ISSUE TITLE
uol.com.br

### ISSUE THREAD

**Issue by denydias** [reek/anti-adblock-killer#2260]
http://www.uol.com.br/
[Screenshot](https://cloud.githubusercontent.com/assets/948202/19410347/3d9ce726-92c0-11e6-941d-e32acddc0d18.png)
Chromium 53.0.2785.92
Tampermonkey
uBlock₀
My filters‎ + uBlock filters‎ + uBlock filters – Badware risks + uBlock filters – Privacy + uBlock filters – Unbreak‎ + Anti-Adblock Killer | Reek‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Malware domains‎ + Malware domains (long-lived)

**Comment by mapx-** [comment]
`@@||uol.com.br^$generichide`

**Comment by denydias** [comment]
Tks,, @mapx-. Any chance this could be merged to the main rules or can I just close the issue?

**Comment by mapx-** [comment]
just close it, use it as custom filter

**Comment by denydias** [comment]
Already did. Thanks.
