### ISSUE TITLE
dailyacc.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#227]
* dailyacc.com###c5ff
* http://www.dailyacc.com/2015/03/x17-rapidgatornet-premium-accounts.html
* https://i.imgur.com/1GA5ZBn.png
* Firefox 36.0
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.8
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

**Comment by reek** [comment]
Already Killed.
