### ISSUE TITLE
prem.link

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#2274]
http://prem.link/dl.php?id=851127
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/19447007/d99d2cc6-949b-11e6-9033-9d469fcb866f.PNG)
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

I get this message after clicking on "Close" and "I'm not a robot". Please help.

**Comment by mapx-** [comment]
https://github.com/reek/anti-adblock-killer/issues/2022#issuecomment-244331328

or search (and report) directly at easylist forum
https://forums.lanik.us/viewtopic.php?p=102060#p102060

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
