### ISSUE TITLE
https://upl.one/5Rh

### ISSUE THREAD

**Issue by marcussacana** [reek/anti-adblock-killer#2281]

**Comment by mapx-** [comment]
test this filter
`@@||upl.one/*ad$script`

**Comment by marcussacana** [comment]
not works :/

**Comment by mapx-** [comment]
working fine, tested in 2 browsers, 2 adblockers + easylist
use only 1 adblocker not other blocking extensions / addons

**Comment by marcussacana** [comment]
yep, using only adblock works.
