### ISSUE TITLE
Anti-Adblock Killer need your help to keep your Ad-Blocker active

### ISSUE THREAD

**Issue by davidhedlund** [reek/anti-adblock-killer#2287]
This is exactly the 500th open issue at this writing, a clear indicator that it need a few extra contributors.

I think that AdBlockPlus team may be interested in the killer as the popularity for Adblock Plus will decline otherwise. Most video on demand websites owned by TV companies use Adblock scripts. Therefore AdBlockPlus team should help in the development of the killer or add similar functionality to their addon. 

I don't know JavaScript but I invite people that do know how to program it to contribute with pull requests.

**Comment by davidhedlund** [comment]
[mylabel:help wanted](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Ahelp wanted%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by Alexx999** [comment]
Well, given that original author isn't active in last few months - it'll be quite tricky to get those MRs in (and update people who have this installed)

**Comment by davidhedlund** [comment]
@Alexx999 Do you know if someone have forked AAK yet?

**Comment by Giwayume** [comment]
We have enough contributors, thing is Reek needs a few repository admins who can publish releases while he takes a vacation.

**Comment by davidhedlund** [comment]
Good idea @Giwayume. What do you say about that @reek?

**Comment by davidhedlund** [comment]
@reek Can you please label this issue "Help wanted"?

**Comment by davidhedlund** [comment]
[AAK-Cont](https://gitlab.com/xuhaiyang1234/AAK-Cont/issues) is the new fork.
