### ISSUE TITLE
http://poker.cardplayer.com

### ISSUE THREAD

**Issue by scoundrila** [reek/anti-adblock-killer#2289]
http://poker.cardplayer.com (and http://poker.cardplayer.com/forbidden)
http://i.imgur.com/BPjKIZ6.png
Mozilla Firefox
Greasemonkey
Adblock Plus
Adblock Warning Removal List + ListeFR+EasyList + AakList + Fanboy's Annoyance List

It happens when playing poker (it's free but it's necessary to subscribe or to log in via facebook).
When logged in, you automatically arrive in the lobby. Click on the register green button in the "Level 1 - Start Here" free tournament, for instance, and less than one or two minutes after you started playing, you will be redirected automatically to http://poker.cardplayer.com/forbidden, which contains the image of the screenshot.

It's really annoying, and I've tried everything : 
-Greasemonkey with Anti Adblock Killer with Adblock Plus having AakList
-Adblock Warning Removal List
-RefControl set to block ref information for that website
-uBlock Origin
-Using Firefox in private mode
-Using latest Opera with embeded adblocker

It's always the same result.

Thanks for your help

**Comment by mapx-** [comment]
try these filters 
```
@@||cardplayer.com^$generichide
@@||ads.tijuana.nlop.com^$script,domain=cardplayer.com
@@||ads.nlop.com^$script,domain=cardplayer.com
@@||browser.nlop.com/adv/advertisement.swf
```

**Comment by scoundrila** [comment]
It's working great, thanks, you're the boss !

**Comment by scoundrila** [comment]
Works great with ABP, but I tried with uBlock Origin, and it doesnt work.

Yet, I followed the instructions (https://github.com/reek/anti-adblock-killer#instruction) and I added those 4 filters above in "My Filters". In entered the four of them in one block and applied them together, I think it's the way it works.

Anyway, it's not like I need ubo, but I thought it could be lighter than ABP maybe.

**Comment by scoundrila** [comment]
Okay, I finally solved it.
In UBO settings, the first checkbox you can tick is called "hide placeholders of blocked elements".
I just unselected it and it did the trick. Leaving it selected makes ubo beeing detected by the website.

**Comment by scoundrila** [comment]
I suppose there is no way to not hide placeholders only for a specific website, since this is what seems to trigger the anti adblocker ?
Anyway, on Firefox, I don't seem to tell the difference when surfing on the internet with that checkbox checked and without ? Placeholders never appear. Maybe they do on other browsers ?

**Comment by mapx-** [comment]
you could in ubo click ubo icon, and click "toggle cosmetic filters for this site" button.

**Comment by scoundrila** [comment]
It's the small eye button, right ? I tried it, but it doesn't work.
