### ISSUE TITLE
binbox.io

### ISSUE THREAD

**Issue by yigido** [reek/anti-adblock-killer#229]
Hello,

I am using your latest list but on this site http://binbox.io/67pGp#TZPhxqM0
after I entered the captcha, site warns me to "close your adblocker"
This is inform to you.

Thanks,
yigido

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by yigido** [comment]
Hey,

Thank you. I am a engineering student right now and I have no proper income :) 
When I got my first salary, do not worry your paypal in my donation list.

Sincerely,

**Comment by reek** [comment]
HI,

Ok, no worries.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
