### ISSUE TITLE
financialexpress.com

### ISSUE THREAD

**Issue by gurmohanb** [reek/anti-adblock-killer#2290]
Hi, 
     When we open financialexpress.com then a message shows "Your adblocker is on". Please add financialexpress.com in anti-adblocker list. Thanks

**Comment by mapx-** [comment]
add the filter
`@@||expressbpd.com/*ad$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
