### ISSUE TITLE
bitcoinker.com

### ISSUE THREAD

**Issue by RaporLoLpro** [reek/anti-adblock-killer#230]
http://bitcoinker.com/
http://i.imgur.com/mmBekZr.jpg
Google Chrome
TamperMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

Adblock warning only appears after you submit an email(you can use any) then solve the captcha and press claim.

**Comment by reek** [comment]
You need use aak script, please stop report killed website, thanks

**Comment by RaporLoLpro** [comment]
Sorry, but i don't get it, am i doing something wrong? Cause i have a list of 40 sites some of them are listed in Anti adblock killer list and blocking does work for them but this doesnot work for this one.

**Comment by reek** [comment]
Sorry I got you confused with "anonsubmitter", I'll see if I can do, thanks

**Comment by reek** [comment]
bitcoinker.com is ok for me try use Firefox

**Comment by smilzoboboz** [comment]
I guess it's not working anymore, tried to take a look at source/scripts of bitcoinker.com but I'm not good with this stuff.
Tried with both firefox and chromium.

**Comment by reek** [comment]
@smilzoboboz 
I will take a look

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
