### ISSUE TITLE
mac-torrent-download.net

### ISSUE THREAD

**Issue by amithiel** [reek/anti-adblock-killer#2304]
link: http://trdirect.mac-torrent-download.net/2589850/mac-os-x-el-capitan-10114
screen: https://i.imgbox.com/ZpLhUd8p.png
Chrome Version 54.0.2840.71 (64-bit)
Tampermonkey 4.1.10
ublock origin 1.9.10 (all filters updated)
easylist + Peter Lowes ad server list + easyprivacy + malware domain list + malware domains + aaklist

**Comment by mapx-** [comment]
add these filters
```
@@||mac-torrent-download.net^$generichide
@@||fungetbag.info/popunder.gif
@@||static.adf.ly^$domain=mac-torrent-download.net
```
