### ISSUE TITLE
paycheckcity.com

### ISSUE THREAD

**Issue by jtmunn** [reek/anti-adblock-killer#2307]
http://www.paycheckcity.com/calculator/welcome

Google Chrome
Tampermonkey
Adblock
EasyList + AakList

All help is appreciated =)

**Comment by mapx-** [comment]
they broke their own site: even disabling the adblocker the site still shows that message.

**Comment by jtmunn** [comment]
it does that to me as well, that's until I close all Chrome windows and load it up again - which leads me to believe they are storing that setting in local cache? Interestingly, even with F12 Dev. tools open and the caching turned off, does the same thing - requires me to close all tabs and re-open.

**Comment by mapx-** [comment]
well, it's your link wrong ...

add this filter
`@@||paycheckcity.com^$generichide`

**Comment by jtmunn** [comment]
Awesome, you got it. Thanks very much =)
