### ISSUE TITLE
[ request flashX ]

### ISSUE THREAD

**Issue by evetaku** [reek/anti-adblock-killer#2317]
www.flashx.tv/qjqmdte1yejj.html
http://prnt.sc/czg13o
mozilla 49.02
greasemonkey
addblock
EasyList

**Comment by mapx-** [comment]
report in easylist forum in the dedicated thread
https://forums.lanik.us/viewtopic.php?f=62&t=33054&p=106107&hilit=flashx#p106107

**Comment by evetaku** [comment]
@mapx-  they are not give me any answer ✌️

**Comment by mapx-** [comment]
```
@@||adcity.tech/ads/ad_forum_
@@||flashx.tv/*ad$script
```

**Comment by reek** [comment]
updated
