### ISSUE TITLE
gadgets.ndtv.com

### ISSUE THREAD

**Issue by Degitalord** [reek/anti-adblock-killer#2318]
http://gadgets.ndtv.com/games/reviews/the-elder-scrolls-v-skyrim-special-edition-review-1479289

Problem: If u turn on the adblock you can't see the contents of the site. If you turn off the adblock you'll see the contents + ads on the site.
With Adblock: http://i.imgur.com/sIclVTi.jpg
Without Adblock:  http://i.imgur.com/lksJGOG.jpg

Google Chrome
Tampermoney
Ublock Origin
Easylist+ Aaklist

**Comment by mapx-** [comment]
test this filter
`@@||gadgets360.com/*ad$script`

**Comment by reek** [comment]
done
