### ISSUE TITLE
moondoge.co.in

### ISSUE THREAD

**Issue by RaporLoLpro** [reek/anti-adblock-killer#232]
moondoge.co.in
http://i.imgur.com/iCpIzNE.jpg
Google Chrome
TamperMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

Adblock warning appears right after you do the claim.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

I will add the ability to donate via dogecoin

See you soon
Reek

**Comment by RaporLoLpro** [comment]
Thank you, i will donate surely donate if i managed Anti-adblock-killer to work with these sites that i have reported :+1:

**Comment by RaporLoLpro** [comment]
Hey, mate, please take a look at http://moonbit.co.in also, you said it was already killed but it wasnot.
This site is similliar to one that i was requested above but it was not "Already killed" as you said :)
It probably has the same mechanism of blocking, since it only detects the adblock after you do the CLAIM. Please check it on more time please.
Thanks in advance.

**Comment by reek** [comment]
I'll recheck

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
