### ISSUE TITLE
adf.ly is asking me to disable adBlock

### ISSUE THREAD

**Issue by WillyTheHoe** [reek/anti-adblock-killer#2320]
I know this has already been posted, and developer said it was fixed but it's not.. or maybe it's not working anymore....
please help i'm sick of this website hahaha

**Comment by WillyTheHoe** [comment]
okay nevermind I found the solution, in case someone is wondering;
I added this to the filters list of adblock:

@@||static.adf.ly/static/image/ad_top_bg2.png
s1-adfly.com##[src^="http://clkfeed.com/adServe/"]

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
