### ISSUE TITLE
http://comunidadiptv.org

### ISSUE THREAD

**Issue by Tronen** [reek/anti-adblock-killer#2321]
http://comunidadiptv.org/bloqueado/
Google chrome
Tampermonkey
Adblock Plus
EasyList + AakList
![sin titulo](https://cloud.githubusercontent.com/assets/23109668/19789112/471931a0-9cad-11e6-986e-227bb246dec5.jpg)

**Comment by mapx-** [comment]
add this filter
`@@||comunidadiptv.org^$generichide`

**Comment by Tronen** [comment]
Thanks mapx-, it works
