### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by dnut** [reek/anti-adblock-killer#2322]
http://www.last.fm/
https://i.imgur.com/tb7QgJ4.png
Chromium
Tampermonkey
AdBlock
AakList + Malware Domains (adblock) + AdBlock custom filters + Easylist + EasyPrivacy + Enhanced Trackers List + Annoyances + Malware protection (fanboy)

**Comment by mapx-** [comment]
did you search the issues ?
https://github.com/reek/anti-adblock-killer/issues/2213#issuecomment-256689879

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
