### ISSUE TITLE
TimesofIndia

### ISSUE THREAD

**Issue by aashutoshm** [reek/anti-adblock-killer#2323]
Anti-Adblock Killer script does not work on http://timesofindia.indiatimes.com/.
http://timesofindia.indiatimes.com/india/52-Indians-among-61-indicted-by-US-for-role-in-call-centre-scam/articleshow/55105257.cms
![capture](https://cloud.githubusercontent.com/assets/23113996/19796322/20600044-9d01-11e6-8523-65521b941ad9.PNG)

Chrome
uBlock Origin
Tampermonkey
Easylist+AakList

**Comment by mapx-** [comment]
add
`@@||indiatimes.com/*ad`

**Comment by volviq** [comment]
duplicate to #2064

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
