### ISSUE TITLE
pclab.pl

### ISSUE THREAD

**Issue by skip850** [reek/anti-adblock-killer#2324]
http://pclab.pl/art71676.html
![chrome_2016-10-28_12-02-07](https://cloud.githubusercontent.com/assets/13948709/19802979/abf55cda-9d06-11e6-8ff2-edb05b57ff4a.png)

**Comment by mapx-** [comment]
test these filters (I cannot reproduce your issue)
```
@@||pclab.pl^$generichide
@@||pclab.pl/*ad$script
```

**Comment by skip850** [comment]
thanks a lot.
