### ISSUE TITLE
Add rule for www.sueddeutsche.de

### ISSUE THREAD

**Issue by Enkidu70** [reek/anti-adblock-killer#2331]
http://www.sueddeutsche.de
http://imgur.com/a/UgrRs
Mozilla Firefox (latest)
Greasemonkey
Adblock Plus
EasyList (German) + AakList

**Comment by mapx-** [comment]
add
`@@||sueddeutsche.de^$generichide`

**Comment by Enkidu70** [comment]
Tnx! Will this rule now added to Aaklist or do I have to do something else!?

**Comment by mapx-** [comment]
add it in your custom filters in ABP
https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by lorro88** [comment]
@@||sueddeutsche.de^$generichide

doesnt work for me

**Comment by mapx-** [comment]
```
@@||sueddeutsche.de/*ad
@@||sueddeutsche.de^$generichide
```

**Comment by Enkidu70** [comment]
Tnx! Rule is working very well!
