### ISSUE TITLE
bassfaucet.com

### ISSUE THREAD

**Issue by RaporLoLpro** [reek/anti-adblock-killer#234]
http://bassfaucet.com/
http://i.imgur.com/7eT1L8U.jpg
Google Chrome
TamperMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

Picture is the same to another faucet that i reported(dancefaucet.com), faucets are similiar but not the same, both have this issue.

**Comment by reek** [comment]
Already killed.
