### ISSUE TITLE
Userscloud

### ISSUE THREAD

**Issue by SBI-boy** [reek/anti-adblock-killer#2342]
Some userscloud files are not possible to download on uploaders request

example url: https://userscloud.com/ctj41kx7k3fc
message returned: The publisher of this file doesnt allow adblock, please disable and Reload
thanks

**Comment by mapx-** [comment]
`@@||userscloud.com^$generichide`

https://forums.lanik.us/viewtopic.php?p=106026#p106026

**Comment by SBI-boy** [comment]
thanks, it worked

**Comment by giampi75** [comment]
I confirm: it works
