### ISSUE TITLE
AAK not working on link drop?

### ISSUE THREAD

**Issue by forvy** [reek/anti-adblock-killer#2344]
example link: http://linkdrop.net/xarI0
screenshot: [http://imgur.com/a/WjtRe](url)
browser: chrome | firefox
adblocker: adblock | adblockplus
filterlist: easylist + aak [both same]

**Comment by mapx-** [comment]
add
`@@/^((?!.*\.(popads.net|xxyafiswqcqz|hhwqfmqyqoks)\W?).)*$/$script,domain=linkdrop.net`

**Comment by forvy** [comment]
thanks it works
