### ISSUE TITLE
https://onhax.me/

### ISSUE THREAD

**Issue by MehulHardy** [reek/anti-adblock-killer#2345]
https://onhax.me/

Whole site gets blocked when using adblock

(I'm using Chrome+AdBlock+Tampermonkey+Anti adblock)

![untitled](https://cloud.githubusercontent.com/assets/17978165/19957105/b98d451c-a1b9-11e6-8411-c6bdf7d71364.png)

**Comment by mapx-** [comment]
add
`@@||onhax.me^$generichide`

**Comment by MehulHardy** [comment]
Thanks
