### ISSUE TITLE
https://news.liveurlifehere.com/in/

### ISSUE THREAD

**Issue by kartikbilla007** [reek/anti-adblock-killer#2347]
Unable to bypass adblock detection!
Link: https://news.liveurlifehere.com/in/
![adblock](https://cloud.githubusercontent.com/assets/16859254/19958599/231e52a4-a166-11e6-82c6-8f5f7a0da6c9.png)

**Comment by mapx-** [comment]
add this filter in your adblocker
`@@||liveurlifehere.com^$generichide`

**Comment by kartikbilla007** [comment]
Thanks "mapx" you're awesome!
