### ISSUE TITLE
Thesaurus.com

### ISSUE THREAD

**Issue by MisterMustafa** [reek/anti-adblock-killer#2349]
Page loads for a few seconds, and then redirects to this page:

http://www.thesaurus.com/why-am-i-seeing-ads

**Comment by MisterMustafa** [comment]
It seems to have righted itself. If anybody fixed this, thanks :)

**Comment by RaymondWise** [comment]
I'm running into this now

![thes](https://cloud.githubusercontent.com/assets/5232353/20685373/bedbd85c-b579-11e6-9ca0-c33cf8ceaddf.png)

**Comment by qhostwritten** [comment]
Still happening for me on Chromium 57 with uBlock Origin and Tampermonkey

**Comment by nyanpasu64** [comment]
Thesaurus.com uses "content_control_callback" anti-adblock. It needs to be added into the list of sites.
