### ISSUE TITLE
www.blockadblock.com

### ISSUE THREAD

**Issue by Atamasy** [reek/anti-adblock-killer#2354]
I've been dealing with this site and sites that use this script. Previously, I've used AAK and other forms of script blocking including but not limited to NoScript or similar. It wasn't until last week that I looked at their code they supply. It's a mixture of ASCII, base64 and RegEx to obfuscate what it's doing. It's a messy slurry and it took me a while to pick it apart. It injects a script. After doing more research, it seems any domain name can be added to a custom filter list using:

`samplepage.com##script:inject(bab-defuser.js)`

Doing this kills the detection on their site and any site using their code. However, I presume there are methods of assigning a unique ID to each visitor in the form of a cookie or LSO, unless flash storage is denied through Flash Global Settings and or flash plugin disabled.

Any chance of pushing a permanent fix?  Currently, I've found it on a few tech sites, some file lockers and other not-so-popular sites. This is currently the only anti-adblocker I've found that managed to get around AAK or UB/UBO's extensive lists.

**Comment by X01X012013** [comment]
Actually, simply replace built-in function `eval` and filter some keywords from arguments passed in is enough to stop blockadblock.

**Comment by Atamasy** [comment]
Interesting. So is there any hope for the future without having to modify personal lists or rely on another list? I loaded up the site in Vivaldi and went to dev tools and looked at the net monitor and spotted what the encoding breaks down as. One of the injections sniffs out any form of adblock with IF statements and then has a fallback. It's clever code but not too clever. And unless I'm mistaken, it borrows tracking data set by google analytics and uses that to "mark" each users. Though I can't think of the point behind that. Is there any point? Additionally, they're using a mechanism of Turn Off the Lights and going against the grain of what TOFTL's GPL 2.0 license. All around very scummy.

**Comment by X01X012013** [comment]
Do you mean a really generic anti-detection system? That would be really hard since every website use slightly different method to detect AdBlockers. Most websites customize their scripts, so a generic BlockAdblock blocker wouldn't work on all websites using BlockAdblock. 

I do have a submission system: https://github.com/X01X012013/AdBlockProtector/issues
I'm not sure what's wrong with `uploads.to`, if you can open an issue with more detailed information, I would be able to add it into my script.

**Comment by mapx-** [comment]
filters for uploads.to

```
@@||uploads.to^$generichide
@@||adworld.tech^$domain=uploads.to
||cloudfront.net$script,domain=uploads.to
```
