### ISSUE TITLE
indianexpress.com

### ISSUE THREAD

**Issue by ravi6603** [reek/anti-adblock-killer#2356]
http://indianexpress.com/article/india/india-news-india/maharashtra-11-arrested-for-raping-minor-in-private-school-in-buldhana-3736695/

**Comment by mapx-** [comment]
search the issues
https://github.com/reek/anti-adblock-killer/issues/2189#issuecomment-255022445

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
