### ISSUE TITLE
AdF.ly now blocks AdBlock

### ISSUE THREAD

**Issue by Sheiklan** [reek/anti-adblock-killer#2358]
<img width="688" alt="adf ly" src="https://cloud.githubusercontent.com/assets/23268842/20023283/5bac5e5c-a2df-11e6-9650-82abcf9e59c4.PNG">

Mirror: **http://q.gs/**

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
