### ISSUE TITLE
youwatch.org

### ISSUE THREAD

**Issue by rayman89** [reek/anti-adblock-killer#2360]
The webpage detects that you have adblock and if you allow the script that detects it adpop.js then the video player also detects that you have adblock and then the webpage spams you opening like 5 popups and showing you a video on how to disable adblock.

Example Link http://ahzahg6ohb.com/x05cpo82douo

**Comment by mapx-** [comment]
add these filters
```
@@||ahzahg6ohb.com/js/*
||ahzahg6ohb.com^$popup
||ahzahg6ohb.com/play72/popout.js
|http://$xmlhttprequest,domain=ahzahg6ohb.com
```

**Comment by rayman89** [comment]
thank you

**Comment by reek** [comment]
Hi,

Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
