### ISSUE TITLE
politiken.dk

### ISSUE THREAD

**Issue by kj-schmidt** [reek/anti-adblock-killer#2363]
1) http://politiken.dk/
2) http://imgur.com/a/mQW6u
3) Google chrome
4) Tampermonkey
5) Addblock plus
6) Adblock Warning Removal List, EasyList, AakList (Anti-Adblock Killer)

**Comment by mapx-** [comment]
search the issues:
https://github.com/reek/anti-adblock-killer/issues/1634#issuecomment-236139726

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
