### ISSUE TITLE
onhax.me

### ISSUE THREAD

**Issue by aryacebe** [reek/anti-adblock-killer#2369]
https://onhax.me/
http://imgur.com/sd9W6oP
Chrome
Tampermonkey
uBlock Origin
EasyList + AakList + uBlock filters + EasyPrivacy + Malware domains +Dan Pollock +IDN: ABPindo

Please kill it, thanks

**Comment by mapx-** [comment]
https://forums.lanik.us/viewtopic.php?p=106799#p106799

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
