### ISSUE TITLE
Inc.com

### ISSUE THREAD

**Issue by WangChristopherS** [reek/anti-adblock-killer#2370]
![screen shot 2016-11-06 at 8 14 39 pm](https://cloud.githubusercontent.com/assets/18157533/20046369/bc376b98-a45d-11e6-87cd-9db7a18e431e.png)

What do I do? This is because of Adblock/Adblock Plus.

**Comment by mapx-** [comment]
try these filters
```
@@||inc.com/*ad
@@||inc.com^$generichide
```

**Comment by WangChristopherS** [comment]
Works like a charm! Thanks!
