### ISSUE TITLE
Uploads.to

### ISSUE THREAD

**Issue by arvietabz** [reek/anti-adblock-killer#2377]
https://uploads.to/d4y42ro4h5as
http://imgur.com/a/Lwqdv
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add the filters:
```
@@||uploads.to^$generichide
||cloudfront.net$script,domain=uploads.to
@@||adgarden.tech^$script
```

https://forums.lanik.us/viewtopic.php?p=107227#p107227

**Comment by arvietabz** [comment]
Thank you! It worked :)
