### ISSUE TITLE
AETV.com  Still having issue in chrome where it detects the blocker- I*ISSUE SOLVED

### ISSUE THREAD

**Issue by zsquared24** [reek/anti-adblock-killer#2380]
I have been trying everything people give me but nothing seems to work.  Most of the channels work fine but still having the problem with this one.

@@||aetv.com^$generichide
@@*$image,domain=aetv.com
@@||budgetedbauer.com$domain=aetv.com
@@||history.com^$generichide
@@*$image,domain=history.com
@@||budgetedbauer.com$domain=history.com
@@||discoverygo.com^$generichide
@@*$image,domain=discoverygo.com
@@||budgetedbauer.com$domain=discoverygo.com
@@||tlc.com^$generichide
@@*$image,domain=tlc.com
@@||budgetedbauer.com$domain=tlc.com
@@||global.ssl.fastly.net/ad/$domain=aetv.com
@@||npttech.com/advertising.js$script,domain=aetv.com

**Comment by zsquared24** [comment]
I found the problem added a couple more filters and updated some things is there any way to delete this issue thread

**Comment by kartikbilla007** [comment]
![1](https://cloud.githubusercontent.com/assets/16859254/20130571/d87a041a-a614-11e6-8b8a-7107d34ff6eb.jpg)

**Comment by zsquared24** [comment]
Thanks I thought that meant to close the issue you were looking at like a
window

**Comment by OverlordQ** [comment]
Can you at least say what the fix was instead of just running off?

**Comment by iPherian** [comment]
I'm looking to make adblock work on this site too. So if the OP could detail how he fixed it that would be good.
