### ISSUE TITLE
http://www.kbb.com/

### ISSUE THREAD

**Issue by kartikbilla007** [reek/anti-adblock-killer#2382]
http://www.kbb.com/ detecting adblock!

**Comment by mapx-** [comment]
add these filters
```
@@/adblock.js$domain=kbb.com
@@||kbb.com^$domain=kbb.com
```

**Comment by kartikbilla007** [comment]
I still see it detects
![1](https://cloud.githubusercontent.com/assets/16859254/20130492/5b78753c-a614-11e6-831d-4026b2b8ae35.jpg)
![2](https://cloud.githubusercontent.com/assets/16859254/20130497/60c36bc8-a614-11e6-9a72-808111dd9b71.jpg)

**Comment by kartikbilla007** [comment]
![1](https://cloud.githubusercontent.com/assets/16859254/20130537/a37270a4-a614-11e6-8099-2f452ad4c500.jpg)

**Comment by mapx-** [comment]
tested in chrome / firefox + ABP, all fine here (using easylist + the filters above)

are you usign some other blocking extension (ghostery, disconnect..) ?

**Comment by kartikbilla007** [comment]
no I am not, it doesn't work :(

**Comment by reek** [comment]
Not detected

**Comment by FredFlintstoneLOL** [comment]
See https://github.com/reek/anti-adblock-killer/issues/2596 which worked for me. Chrome with ABP.
