### ISSUE TITLE
onhax.me [Mainly blockadblock.com]

### ISSUE THREAD

**Issue by ether8888** [reek/anti-adblock-killer#2384]
Browser: Firefox 49.0.2
Greasemonkey 3.9
AdBlock Plus
Filter List: Adblock Warning Removal List+Easylist+Aaklist
Problem Site: https://onhax.me/
Screenshot: http://imgur.com/Gj7dShP

Would you please check this issue.

Thanks
Ether

**Comment by mapx-** [comment]
add
`@@||onhax.me^$generichide`
