### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by shivindernarr** [reek/anti-adblock-killer#2394]
ndtv website is able to block adblock. Below is the link:
http://www.ndtv.com/india-news/people-voted-against-black-money-says-pm-narendra-modi-1624846
<img width="466" alt="capture" src="https://cloud.githubusercontent.com/assets/19361549/20244382/4a19394a-a9a5-11e6-87c7-67d690c34717.PNG">

**Comment by reek** [comment]
Hi,
Ok, I'll fix it, thanks

**Comment by b-sridhar** [comment]
@reek the following filter with uBlock seems to work for now: `||www.ndtv.com$inline-script,domain=www.ndtv.com`. Figured out how to identify and apply the filter with uBlock Logger. Thanks for all the support.

**Comment by reek** [comment]
@b-sridhar 
this filter only works with firefox+ublock

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
