### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by mbierman** [reek/anti-adblock-killer#2396]
http://www.ndtv.com/ was not successful. It asked me to turn off my ad blocker. 

http://www.ndtv.com/world-news/donald-trump-wants-to-live-only-part-time-in-white-house-report-1624823 was the exact page. 

![image](https://cloud.githubusercontent.com/assets/1205471/20248980/dd675b38-a9a4-11e6-8286-901aea36eaeb.png)

**Comment by reek** [comment]
I'll fix it soon

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ssrb19** [comment]
Thanks a lot @reek
