### ISSUE TITLE
www.business-standard.com

### ISSUE THREAD

**Issue by armling** [reek/anti-adblock-killer#2402]
ublock origin doesnt seem to work here:

http://www.business-standard.com/

Thank you for visiting
logo
You seem to have an Ad Blocker on.
You now have the option of muted advertisements if you go "Premium".
Discover the power of rich & exclusive content - Go Premium Now. 
Already a Premium Member ? Login Now.
Click here to know how to turnoff the adblocker

**Comment by maynak00** [comment]
**try wit:**
`@@||business-standard.com/*/banner.js$script`
`@@||business-standard.com/*/ads.js$script`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
