### ISSUE TITLE
adf.ly

### ISSUE THREAD

**Issue by BioBrayan** [reek/anti-adblock-killer#2405]
Google Chrome  54.0.2840.99 m (64-bit)
http://adf.ly/qYI0R
Adguard for Windows Beta 6.1.281.1494
Filtro para inglés
Filtro para español/portugués
EasyList
EasyPrivacy
Easylist Spanish	
Adblock Warning Removal List	
Anti-Adblock Killer | Reek
__________________________________________________________________________________________________________________	
Tampermonkey 4.1.10
AdsBypasser 5.60.6
Anti-Adblock Killer | Reek 9.9
AntiAdware 1.41.3
__________________________________________________________________________________________________________________
http://adf.ly/qYI0R
https://i.imgbox.com/mKW3IaN4.png

advert blocking browser extension

**Comment by reek** [comment]
I'll fix it thanks

**Comment by BioBrayan** [comment]
Ok waiting for a solution thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
