### ISSUE TITLE
http://sport.gentside.com

### ISSUE THREAD

**Issue by Camiyo** [reek/anti-adblock-killer#2408]
http://sport.gentside.com/bodybuilding/le-cote-obscur-de-la-musculation-montre-par-le-bodybuilder-steve-cook_art53675.html?utm_source=fb&utm_medium=cpc&utm_campaign=lsvcombat#
http://imgur.com/a/fKILI
Mozilla Firefox
Greasemonkey
Ublock Origin
EasyList + AakList

By advance, thank you !

**Comment by mapx-** [comment]
add
`@@||gentside.com*ad$xmlhttprequest`

**Comment by Camiyo** [comment]
Nice !!! Thanks you mapx !!! :)  :+1:
