### ISSUE TITLE
NSFW http://www.5299.tv

### ISSUE THREAD

**Issue by darknils** [reek/anti-adblock-killer#2411]
http://www.5299.tv/forum-47-1.html

Firefox 49.0.2
Greasemonkey 3.9
  Anti-Adblock Killer 10
uBlock Origin 1.9.16
    Adblock Warning Removal List‎ 
    EasyList
    Peter Lowe’s Ad server list‎
 CHN: CJX's Annoyance List‎
 CHN: EasyList China
 DEU: EasyList Germany

**Comment by SMed79** [comment]
@darknils when you post a p0rn site add **NSFW** in the subject.
