### ISSUE TITLE
ndtv.com

### ISSUE THREAD

**Issue by mskadu** [reek/anti-adblock-killer#2418]
http://www.ndtv.com/india-news/many-in-bjp-are-bachelors-ramdev-on-notes-ban-in-peak-wedding-season-1626955?fb
http://imgur.com/a/ATiFH
Chrome Version 54.0.2840.99 m (64-bit)
uBlock Origin v1.9.16
Filters enabled (too many to list): http://imgur.com/a/X9Tqt

note: I have already looked through #2396

**Comment by X01X012013** [comment]
Do you have AAK script installed?

**Comment by uBlock-user** [comment]
`@@||s3.amazonaws.com/khachack/ima3.js^$script`

**Comment by mskadu** [comment]
Yes, i do. Please see the filters screenshot. It's the 8th blue coloured item from the top. And thank you.

**Comment by X01X012013** [comment]
@mskadu That is AAK list, not AAK script.

**Comment by uBlock-user** [comment]
This won't end with that filter, as soon as they see it bypasse, they will keep up the charade and introduce another way to break it again, so this will go on. You can do this too if you can mind the file which is supposed to blocked or white-listed(in ndtv.com's case) and white-list or block as appropriate.

**Comment by mskadu** [comment]
In which case, no I don't have the script installed.

**Comment by siriuspal** [comment]
I have tested on Chrome, Windows, with AAK script. Gets rid of the anti-adblock.
