### ISSUE TITLE
lequipe.fr

### ISSUE THREAD

**Issue by Giljulien** [reek/anti-adblock-killer#2421]
http://www.lequipe.fr/Directs/
![image](https://cloud.githubusercontent.com/assets/22545001/20436514/c8d1eaa2-adb0-11e6-9ad3-bcfd4d7cd68f.png)
Navigateur : Chrome
Gestionnaire de script : Tampermonkey
Ad blocker : U Block Origin
Filtres ; UBlock filters +  Anti-Adblock Killer + EasyList‎
![image](https://cloud.githubusercontent.com/assets/22545001/20436379/5705fae4-adb0-11e6-8c83-ab37ec7ab339.png)

**Comment by M3T4LL1C4** [comment]
Blocking `https://idalia.assariaburdine.com` currently works, but they often change their anti adblock code

**Comment by Giljulien** [comment]
Merci beaucoup ! :+1:
