### ISSUE TITLE
forum.pac-rom.com

### ISSUE THREAD

**Issue by boris768** [reek/anti-adblock-killer#243]
Google Chrome
TamperMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

And making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
