### ISSUE TITLE
mangahost.net

### ISSUE THREAD

**Issue by InitialDet** [reek/anti-adblock-killer#2443]
all images got removed because adblock is detected
http://imgur.com/a/IKRAx
http://mangahost.net/

Google Chrome
Adblock plus
EasyList + AakList

same problem as before
https://github.com/reek/anti-adblock-killer/issues/558

**Comment by smed79** [comment]
Continue in the same thread >> https://github.com/reek/anti-adblock-killer/issues/558#issuecomment-262432482 & (see  [how to add custom filters](https://adblockplus.org/forum/viewtopic.php?f=2&t=42013))

**Comment by InitialDet** [comment]
Same problem again
https://puu.sh/xcZJg/5180574e41.png
