### ISSUE TITLE
linkdrop.net

### ISSUE THREAD

**Issue by deeparora9414** [reek/anti-adblock-killer#2447]
http://linkdrop.net/AblRd
http://imgur.com/a/UQldf
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList
![screenshot 234](https://cloud.githubusercontent.com/assets/23583833/20609474/fe26bb7c-b2b2-11e6-949b-5df05ecf39c1.png)

**Comment by smed79** [comment]
add:
`@@/^((?!.*\.(popads.net|xxyafiswqcqz|hhwqfmqyqoks)\W?).)*$/$script,domain=linkdrop.net`

https://forums.lanik.us/viewtopic.php?p=106868#p106868

**Comment by deeparora9414** [comment]
I am a complete Biginer. Please tell me what i am supposed to do with this
code.
Can't You add these codes in an Update of Adblock Plus, Or Easylist.

If this is already added in the  Easylist. Then why the EAsylist is not
working.

these lists are added in My adblock plus & updated, Shown in attachment.
 But these not working.

**Comment by deeparora9414** [comment]
Thanks a lot. I add filters. It works.

**Comment by Rendy8891** [comment]
@deeparora9414 how? 
i add "@@/^((?!.*\.(popads.net|xxyafiswqcqz|hhwqfmqyqoks)\W?).)*$/$script,domain=linkdrop.net" on my adblock filter and it still doesn't work

**Comment by mapx-** [comment]
add in your custom filters:
`@@/^((?!cpmstar.com|popads.net|mgid.com|oclasrv.com|wwwpromoter.com|onclickads.com|.js).)*$/$script,third-party,domain=linkdrop.net`

**Comment by Rendy8891** [comment]
thanks, it works now.

**Comment by deeparora9414** [comment]
Anti adblock-killer is not working on "sznpaste.net"

this is sample link.    -       "http://sznpaste.net/5E9ttlDP"

please tell me how to fix this.

**Comment by mapx-** [comment]
add in your adblocker
```
@@/^((?!cpmstar.com|popads.net|popcash|mgid.com|oclasrv.com|wwwpromoter.com|onclickads.com|www.).)*$/$script,third-party,domain=sznpaste.net
@@||sznpaste.net^$generichide
@@|http://$image,domain=sznpaste.net,third-party
```

**Comment by deeparora9414** [comment]
thanks. It worked.
