### ISSUE TITLE
brest.lachainemeteo.com

### ISSUE THREAD

**Issue by reportmeteo** [reek/anti-adblock-killer#245]
http://brest.lachainemeteo.com/meteo-france/ville/previsions-meteo-brest-764-0.php
![la chaine meteo](https://cloud.githubusercontent.com/assets/11455860/6635275/5d48f906-c964-11e4-9756-e20b6732ff15.JPG)

![my config](https://cloud.githubusercontent.com/assets/11455860/6635321/fcddaa48-c964-11e4-81c5-cfe1b4c5fd39.JPG)
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reportmeteo** [comment]
Hello,

 

New problem whith the french popular site http://brest.lachainemeteo.com/

Anti-adblock-killer does not work anymore : no more image (please, see attached) + the site asks me to disable my adblock.

 

Thank you in advance. (I make a donation today.)

 

RM
