### ISSUE TITLE
gktoday.in

### ISSUE THREAD

**Issue by asjoshi80** [reek/anti-adblock-killer#2453]
http://currentaffairs.gktoday.in/month/current-affairs-november-2016
https://cloud.githubusercontent.com/assets/24205539/20647951/99e57428-b4bf-11e6-926c-3d0319562164.png
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by mapx-** [comment]
add
`@@||gktoday.in^$generichide`

**Comment by asjoshi80** [comment]
Thanks a lot! Working perfect!!
