### ISSUE TITLE
andiim3.com

### ISSUE THREAD

**Issue by prorokrak** [reek/anti-adblock-killer#2464]
http://andiim3.com/?q=com.riversoft.android.mysword
![andiim_com](https://cloud.githubusercontent.com/assets/3586285/20727010/18d23e60-b678-11e6-8f09-372c04371446.PNG)

Firefox 50
Tapermonkey
AdBlock Plus
EasyList
Czech List
Easylit Czech and Slovak filter for AdBlock and Adblock Plus
Adblock Warning Removal List
AakList (Anti-Adblock Killer)
AakList (Temporary)

**Comment by mapx-** [comment]
add
```
@@||andiim3.com^$generichide
@@||pagead2.googlesyndication.com^$script,domain=andiim3.com
```

**Comment by prorokrak** [comment]
Thanks a lot. I did it and it helped.
However, I also needed to deactivate Ghostery addon. When it was active, I still got the Deactivate Adblock message.

**Comment by mapx-** [comment]
ghostery is useless, just add easyprivacy to your lists in ABP.
