### ISSUE TITLE
http://www.aranzulla.it

### ISSUE THREAD

**Issue by frank7y** [reek/anti-adblock-killer#2467]

**Comment by darkbasic** [comment]
Works fine here, can you please point to an example of page which fails?

**Comment by rayset** [comment]
http://www.aranzulla.it/come-cambiare-ip-917562.html after a few seconds if you scroll down.

**Comment by darkbasic** [comment]
No, it doesn't... Do you use latest version of Anti-Adblock killer?

**Comment by darkbasic** [comment]
By the way I don't think that anyone smart enough to know of Anti-Adblock killer would ever need to read Aranzulla's blog :)

**Comment by rayset** [comment]
I guess it is not working for me then? Freshly installed on opera (I did
reset the browser and disable opera default adblock).is there any way to
test it? The test on the readme just tells me something in German about
JavaScript.

**Comment by roccodm** [comment]
Not working using chromium Version 53.0.2785.143 Built on Ubuntu , running on LinuxMint 17 (64-bit), Tampermonkey, ABP and the latest anti-adblock scripts. The warning message appears after 6/10 secs.

Maybe this could be the code to be studied:
`<div id="bHunDkKi" class="GLUeox"><div class="CLLAP"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAB+CAMAAADY4yX9AAAApVBMVEUAAADSAxvQAxzaEiX/SEjRAhvRAhvQAhvRAhzRBBzWCRzXDSPRAhvRAhvRAxvRAhvRAhvRAhzRAxvRBBvTBB3TBh7TBx/iJyfRAhzRAhvRAhvSBB3RAxvSAx3VCyHaFyvSBBzRAhvRAxvRAxvRAxvSAxzSBx7RAxvRAxvRBBzSAxzSAxzUBR3RAhzRAxvVCCLRAhzSAhvTAxzSBR7SAxzRAxzQAhuwrMVHAAAANnRSTlMAk68NA/Zx/OWEGhLv6r544NzEi0YpJQb52NA5s0sWCkDMyLibZSGmoZBfUTTUqh5+aFswVrXnaYdeAAAF0ElEQVRo3tTXfZOpYBgG8CsllUNeQiRaoqX1Evb+/h/tnHnuaVKbczarZ+b8/mIG1xj3G/x/vMYhGkE6VaE/XHMJqbSkQ6x3g0T+gTKDAJIEA8pbf0ACh2PzPj3US4tXVK7roD7LzZQyTdNSWpR5u2iohWV26E50AjD6pDuG3carac6xlauna2mlNd89vJJ17tG9ufe42qZ6G6+h+fMW3WsUuyfo0j33GODnPMWge63oWvaqOeX0hh8/S90ZlPNraKHcWGlSTt+84imaN+xR3jRZ4rG2bRRfXz17mzR+UV6r4eMftFuXCjrR3sI3tWOlT0V9e4Hv2JoGFR12joq/O/nnRo++cKPg+SZg06PtLFCwHF89Z38Oux0q092oqGahr6iMsVbsveNdxxMRG7bosYFu4Rlje0aPuUMN2NEjzfnGwvPG+tqlR3TAoFL9nTPBT6lxaFCpN6CsEt6TMV7lqh9L6rUHNPOjqWv6bbyaFQ8H+Zw+wIOiZbzNFd3faqiLNvb1cD0zWtzbAPfQDbLoIm+WFtcGspgibwXwL29DFoXnA8CNPoQsEZ9OAC+UELLweRgBDfHgCFl4jCtAyJsAlal6mExQGZ/mJjDkEVY9d0pEAw1VddJZbacjrCJ+3wVV8QDZAxcelajq+Fw3qCQEgEfCBBVxUSqoaEuCBbRJGEkKdnjVA+mWiCUF67x4gXR02ZKCeWLOsyp5lxTMg3IHpI28khRspG0MJNxPcoJVEvyszmghJfgj7aGsswIpwRcSlgCguXyDSAk27wf0gD9CQnBhCXNZzyQEZ7tJiPnAVSUEj0jwIFgk+BKCE57UEzA+NE0JwRGfmIWnEoL5Kw7zG8Nd1h58IiEujJOg9uBLYUhq/E/uXHtwyOOjuKu6tQf3ixtY505u1xmcdfHtywW2rzn4zEWsInPgg6TmYD6y1l+XhqvWGjwmISnZz5dag20SrJJT6Fhr8KrsuFN4ei9rDD5R2R3tkBDXGKyX/mX53budbicLA2EAnjYgyKKiBRQVi1ut1bZfl/f+L+07J6Fy2lJIIPj8dDlDdJKZBI09kdfdBc5zelbe4VsvnQWeo3zH8g6urxj4kWQdxMgc+injT9iGWr/4jyS5ohDd0i87xfRyPAABU0ytJf3CzHxBk7Xfjm9SxTOXkfFnsUREXbjH3yX/hA7P+J6rJk0iVi+X9IsscWOdSu2KGaXbobJ1j0Wl8BjpthcDzmpS/pV026L6NH7lqwx5PrAXoVxdmopl2qgr1UOSEJoA/JQk3NS2dEzUKJ9RvUm+4aznmPniUbsAo6+1SBxQv6yn4uLMF41l8QTOjiVaXzxoDDyGzBnLygY31xb4A1xiULUjuLWuwHEA7o5qGAm4N02Bh+A+pQuY71K1B6laFolstUKqt4DUcW5PqmEZQL4njKZS30o8LmuhyguelyrsJjFidb/6eF3W9mVK+9/4jHxVausWakcNc0tyCshNTTMiWY/g7JTaiEz5YpdjI3AbaiFOwGWG6t2h8qqn+rFN30nFJH/XiZpaNrv2OAMXMGrG8cEtSFHkgdsY1MQqa5yfb2gzm5/BWffNm3DsSF0fLTYH7Axuqn7VHxAGBjWx98H5e1JzMsEFLjVzPwUXpKQi8sF5ITW1g3B2Sd7LCJy1pOZuIKwZyUoDCENqwdhAGKxIjptAOFArbA3hM5aLu4awMKgd9wxhwKhemhSfUFtOAGHt1ufVDELGqL29DeHsULXQhjBzSYfQhxBEVOV0eZ1DWhQj8e6qqooJYeaQLvsAgtWjPxgT5DKX9HHOyB3K09XdIDdmpJObIZeE9Ns8QG6zIr3YArlpj36I+xZy25h0M/r4MnC+516GIgU6UKQtzGExMDaZokj6bpxsfAmWJByLx2YRdSVd4GL8ZFB8THBxYNShnYmL2cTGhf9E3dqPUWaRUteMnoef/CNdg3tjgcuZfUZXEn5+/6vXFb1vRZZ5jyFdmdtLzPVuRU39B5Q8APrwDOKrAAAAAElFTkSuQmCC" alt=""><h2>Attenzione: Articolo bloccato</h2><p>Per leggere l'articolo, abilita Javascript o disabilita il tuo Adblock.</p>	<p><a href="/locked-no-script.php?p=917562&fabm=noscript" class="lagbVy" rel="nofollow">Leggi le istruzioni per sbloccare l'articolo</a></div></div>`

**Comment by mapx-** [comment]
```
@@||rnzll.it^
@@|http://$image,domain=aranzulla.it
```

**Comment by darkbasic** [comment]
Works flawlessly here (latest Chromium on Archlinux).

**Comment by Judymorale** [comment]
I use Chrome.
CTRL + SHIFT + I
Click un the last DIV in BODY section and untick "z-index: 99999;"
![image](https://cloud.githubusercontent.com/assets/11021386/25233143/15f77a22-25de-11e7-98ce-e4a37a4142ae.png)

The Overlay DIV is disappeared

**Comment by DjDiabolik** [comment]
I don't have understand how i need to do........ i have the same exact setup on Firefox and on Chrome (same filter for ADB and same script for Tamper e Grease / Monkey loaded) but on firefox all working and on Chrome all articles it's be blocked after about 10 seconds.

Apparently all working only if i disable the reeksite script from Tampermonkey....... it's normal ?

*OH yeah......EDIT*
Apparently the workaround suggested by @Judymorale it's working... on chrome last dev i need to disable the Z-Index also in 75% and on 100% value.... but it's need to do this every time you need to read an article and every time you open a different article.

It's a workaround.......not a solution..........................

**Comment by giampi75** [comment]
![aranz](https://cloud.githubusercontent.com/assets/17108055/25373261/3d898116-2999-11e7-9f79-ecaf49bd308a.jpg)
