### ISSUE TITLE
http://www.ispazio.net/abbiamo-rilevato-che-utilizzi-adblocker

### ISSUE THREAD

**Issue by darkbasic** [reek/anti-adblock-killer#2471]
Detects ad blocker and shows this page instead of the content.

**Comment by mapx-** [comment]
add
`@@||ispazio.net^$generichide`

**Comment by darkbasic** [comment]
Uhm... I can't reproduce it anymore but I don't see such a rule into latest anti-adblock-killer-filters.txt: https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt

Maybe some of my other filters already added a rule. Closing.
