### ISSUE TITLE
Integrated with ublock origin ?

### ISSUE THREAD

**Issue by seba2282** [reek/anti-adblock-killer#2472]
Hello :) Is anti-adblock-killer integrated with ublock origin ? I see filter anti adblock kiiller in section ads, but I ask, because I don't know.

**Comment by danielle-mustillo** [comment]
There are two parts to this ad blocker. Follow the instructions found here http://reek.github.io/anti-adblock-killer/#userscript

**Comment by seba2282** [comment]
It is interested. If you will look on filters for ublock origin, there is here in position ads filtr name anti-adblock killer (github.com) | reek. With and without this script from link over, ublock origin protects me the same. :)
