### ISSUE TITLE
Use a VPN / proxy for diagnosing geoblocked sites

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#248]
I see that there are some issues that you have been unable to fix due to the sites being geoblocked. I just wanted to suggest that you could try VPNs or proxys to get around those geoblocks. Extensions such as [Hola](http://hola.org/), [ZenMate](https://zenmate.com/) and [Modify Headers](https://addons.mozilla.org/firefox/addon/modify-headers/) could be useful. (Modify Headers isn't a proxy or VPN though.)

**Comment by reek** [comment]
Hi,

I know, but a good VPN with many countries is expensive. Also I do not
guarantee success in unlocking all

Reek

2015-03-15 20:23 GMT+01:00 anonsubmitter <notifications@github.com>:

**Comment by anonsubmitter** [comment]
Try Hola and see if it gets the job done.

>Hola is a freemium web and mobile application which claims to provide a faster, private and more secure Internet. It provides a form of virtual private network services to its users through a peer-to-peer network. It also uses peer-to-peer caching. When a user accesses certain domains that are known to use geo-blocking, the Hola application redirects the request to go through the computers and internet connections of other users in non-blocked areas, thereby circumventing the blocking.
[Wikipedia](https://en.wikipedia.org/wiki/Hola_%28VPN%29)

**Comment by anonsubmitter** [comment]
VPN Gate could maybe work: http://www.vpngate.net/en/
It's a free volunteer driven service with proxy servers in quite a few countries.

**Comment by reek** [comment]
Hi,

Thank you, I'd try it

2015-11-17 13:23 GMT+01:00 anonsubmitter <notifications@github.com>:
