### ISSUE TITLE
AutoEvolution is detecting ad-blocker

### ISSUE THREAD

**Issue by yochaigal** [reek/anti-adblock-killer#2487]
http://www.autoevolution.com detects adblocker; no way around it. 
ublock + tampermonkey. Aaaklist enabled & updated.

![screenshot_2016-12-05_18-57-52](https://cloud.githubusercontent.com/assets/817479/20907514/c39a8520-bb1c-11e6-95b5-82bc906c5531.png)

**Comment by uBlock-user** [comment]
can't reproduce, no aab found.

**Comment by mapx-** [comment]
add
```
@@||autoevolution.com^$generichide
@@/ad-400.js$domain=autoevolution.com
```

**Comment by yochaigal** [comment]
This worked. Thank you.
