### ISSUE TITLE
GameZone.com detecting adblock in their video player

### ISSUE THREAD

**Issue by cvax** [reek/anti-adblock-killer#2488]
http://www.gamezone.com/news/doom-campaign-length-revealed-3433570

Their video player is detecting Adblock Plus. See screenshot below.

![untitled](https://cloud.githubusercontent.com/assets/3292738/20908816/6b8b7430-bb0c-11e6-89ef-39c7caaf5e6f.png)

Using Chrome with Adblock Plus with Tampermonkey and AAK.
Using EasyList and AakList.

**Comment by uBlock-user** [comment]
Add - `@@||s3.amazonaws.com/html5player.gamezone.com/video-ad-unit.js$script`
