### ISSUE TITLE
fit.sh

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#249]
Bonjour, 
anti-adblock on hxxp://fit.sh/1w9
sc: http://i.imgur.com/ctvZnza.png
source: 

Merci.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
https://hg.adblockplus.org/listefr/rev/1b1bf7115787

**Comment by SMed79** [comment]
reBonjour, 
```
@@||c.ad6media.fr/l.js$domain=fit.sh
```
2nd filter to add if not if you click on "SKIP>>" redirection go to null ...

issue: https://forums.lanik.us/viewtopic.php?f=91&t=21618#p68166
