### ISSUE TITLE
video-download.online

### ISSUE THREAD

**Issue by 2drui** [reek/anti-adblock-killer#2493]
https://video-download.online/
http://imgbox.com/fs157rZZ
Mozilla Firefox
Greasemonkey
uBlock Origin
All filters enabled

**Comment by mapx-** [comment]
try this filter
`||cdndoge.xyz/lib/sweetalert/`

if does not work provide example page

**Comment by 2drui** [comment]
I used the "blocking object" function in the context menu before expose my issue here and it has hide the annoyance but when I clicked on the dowload button it does nothing.
The same with your filter.
I try disabling all my addons (maybe one of them are involved) but it not resolve anything.
An exmple page will not give more informations as I know, you have the link in the first message. Maybe I don't understand very well, my english is not very good.
However thanks for the help.

**Comment by mapx-** [comment]
I asked an example page where I can click the download button. On the main page you provided there is no download button.

**Comment by 2drui** [comment]
Hi, sorry.
There is a download link but you should enter something to download.
And if I cannot click the download button, ever if I insert something to dl, the page wouldn't change and the address is still the same than the one I give you in the first message: https://video-download.online/
Try with this Bandcamp link of a free release : http://vulpianorecords.bandcamp.com/album/aldebaran
Regards

**Comment by mapx-** [comment]
ok, test these 2, should work
```
||cdndoge.xyz/lib/sweetalert/
@@||video-download.online/*ad
```

**Comment by 2drui** [comment]
It's working, great!
Thanks for the good job.
Cheers.
