### ISSUE TITLE
rapidgrab.pl

### ISSUE THREAD

**Issue by adreporter** [reek/anti-adblock-killer#2496]
http://rapidgrab.pl/
![przechwytywanie](https://cloud.githubusercontent.com/assets/18214146/20946035/83485df6-bc09-11e6-96e2-286fb4f60dab.PNG)
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by mapx-** [comment]
add
```
@@||rapidgrab.pl^$generichide
@@ads$image,domain=rapidgrab.pl
```
