### ISSUE TITLE
topbbcnews.com

### ISSUE THREAD

**Issue by avatarium** [reek/anti-adblock-killer#2500]
chrome/adblock/tampermonkey

for example here:
topbbcnews.com/contact/

![b572725564dd4bac9497009854463c07](https://cloud.githubusercontent.com/assets/15238099/20986390/d06c2350-bcc8-11e6-87f5-07fc860c9324.png)

**Comment by mapx-** [comment]
add
`@@||topbbcnews.com^$generichide`
