### ISSUE TITLE
pornovau.com

### ISSUE THREAD

**Issue by mozkan007** [reek/anti-adblock-killer#2505]
Hi, 
When I open a video in this site, it requests to disable ad-blocker.Thanks.

[http://imgbox.com/6LB6t0lv](url)
Chrome v55 x64
Tampermonkey v4.2
Ublock Origin v1.10.0
Ublock Origin default filters and AakList

**Comment by mapx-** [comment]
add
`@@||pornovau.com/*ad`

**Comment by mozkan007** [comment]
It works.Thanks.

**Comment by uBlock-user** [comment]
correct filters
`@@||dfcdn.net^$domain=pornovau.com`
`@@||pornovau.com/player/player_ads.html$subdocument,first-party`
`||$third-party,domain=pornvau.com`
