### ISSUE TITLE
thebitcoinsheep.com

### ISSUE THREAD

**Issue by RaporLoLpro** [reek/anti-adblock-killer#251]
http://www.thebitcoinsheep.com
http://i.imgur.com/YFFBT1b.jpg
Google Chrome/Mozilla Firefox
TamperMonkey/GreeseMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

This site will works only by accesing it from USA IP, please use any USA proxy if possible.

**Comment by alexander255** [comment]
Accessed it from European IP, no problems...

Anti-block script: http://pastebin.com/2SUwGQSp

Filter rule (hides inline "this service depends on ads" notice):

    thebitcoinsheep.com##.col-md-6 font[size="5"] > font[color="white"] > font[color="white"][size="3"]

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
