### ISSUE TITLE
faucetofamerica.com

### ISSUE THREAD

**Issue by RaporLoLpro** [reek/anti-adblock-killer#253]
http://faucetofamerica.com
http://i.imgur.com/fnuTOHw.jpg
Google Chrome/Mozilla Firefox
TamperMonkey/GreeseMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

This site will works only by accesing it from USA IP, please use any USA proxy if possible.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
