### ISSUE TITLE
usafaucet.tk

### ISSUE THREAD

**Issue by RaporLoLpro** [reek/anti-adblock-killer#254]
usafaucet.tk
http://i.imgur.com/al1yZju.jpg
Google Chrome/Mozilla Firefox
TamperMonkey/GreeseMonkey
Adblock Plus
EasyList + Anti-Adblock Killer + Default Adblock Filters

This site will works only by accesing it from USA IP, please use any USA proxy if possible.
I appreciate your work and have donated you about 300k satoshis, thanks for recent fixes :+1: 
By the way, please check this ones also
btc-gratis.com
btcgratis.com
I have already reported them but it looks like they have improved their anti-adblock feature, your pretty script doesnot seem to be working on them at this moment, could you take a look at them one more time? 
Thanks in advance!

**Comment by reek** [comment]
btc-gratis.com and btcgratis.com are ok.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
