### ISSUE TITLE
wired.com

### ISSUE THREAD

**Issue by n3IVI0** [reek/anti-adblock-killer#2541]
Link page: https://www.wired.com/2016/12/heres-lacroix-addictive/all/1
Browser: Google Chrome
Script Manager: Tampermonkey
Adblocker: uBlock Origin

Filters:

uBlock Filters
Malvertising Filter List by Disconnect
Fanboy+Easylist-Merged Ultimate List‎
AakList
Facebook Annoyances Blocker

**Comment by mapx-** [comment]
https://adblockplus.org/forum/viewtopic.php?p=162914#p162914

**Comment by n3IVI0** [comment]
That's from 2011. It no longer works. I am using uBlock Origin. I pasted it under My Filters and hit apply. Still getting blocked at wired.com.

**Comment by mapx-** [comment]
- it's from yesterday
- disable ublock privacy to get them working

**Comment by n3IVI0** [comment]
That works. uBlock Privacy was the issue. Thank you.

**Comment by uBlock-user** [comment]
It's patched at uAssets, you can enable uBlock Privacy again.
