### ISSUE TITLE
http://www.theweek.co.uk

### ISSUE THREAD

**Issue by tobytteh** [reek/anti-adblock-killer#2552]
_We noticed you are using an ad blocker.
To access our site we ask you to either disable your ad blocker or whitelist The Week._

Image: https://i.imgur.com/vCNdR6X.png

Using uBlock Origin with Anti-Adblock-Killer list (+ Adblock Warning Removal List, EasyList, Fanboy’s Annoyance/Social).

**Comment by mapx-** [comment]
add
```
@@||theweek.co.uk^$generichide
@@||ad.doubleclick.net^$image,domain=theweek.co.uk
@@||fastly.net$domain=theweek.co.uk
```

**Comment by tobytteh** [comment]
Worked perfectly, thanks for the quick response!

**Comment by uBlock-user** [comment]
add

`||$third-party,domain=theweek.co.uk`
