### ISSUE TITLE
usatoday adblock popup

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#2558]
![screen shot 2016-12-18 at 5 17 24 pm](https://cloud.githubusercontent.com/assets/21069588/21298435/f2c8635c-c545-11e6-9372-4987fcb885ba.png)

pops up when opening an article 
http://www.usatoday.com/story/travel/advice/2016/11/06/retargeting-online-ads/93282408/

**Comment by uBlock-user** [comment]
add

`||$third-party,domain=usatoday.com`
`@@||gannett-cdn.com^$image,stylesheet,domain=usatoday.com`

**Comment by mapx-** [comment]
add
```
@@||fastly.net$domain=usatoday.com
@@||ad.doubleclick.net^$image,domain=usatoday.com
```

**Comment by jeepy321** [comment]
thanks
