### ISSUE TITLE
streaming-foot.info

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#256]
Bonjour,

![streaming-foot.info-anti-adb](https://cloud.githubusercontent.com/assets/1873139/6743049/8e7565d8-ce95-11e4-877d-2024c4b379ed.png)

on ://www.streaming-foot.info/?page=live&id=7043&name=streaming-river-plate-juan-aurich

Merci.

**Comment by reek** [comment]
No message
