### ISSUE TITLE
chicagotribune.com

### ISSUE THREAD

**Issue by cvbmilani** [reek/anti-adblock-killer#2567]
- http://www.chicagotribune.com/news/nationworld/ct-ghost-shark-captured-on-camera-20161217-story.html
- http://imgur.com/a/TVbjG
- Mozilla Firefox
- Greasemonkey
- Adblock Plus
- EasyList + AakList

**Comment by mapx-** [comment]
add these filters in ABP
```
@@||chicagotribune.com^$generichide
@@|http://$image,domain=chicagotribune.com,third-party
chicagotribune.com##.trb_gptAd
chicagotribune.com##.trb_header_adBanner_combo
```

**Comment by cvbmilani** [comment]
Fixed. Thanks
