### ISSUE TITLE
kissanime.com

### ISSUE THREAD

**Issue by Voyadexon** [reek/anti-adblock-killer#257]
kissanime.com filter is not working anymore.

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

And making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SyntacticSyntax** [comment]
I have this problem too so I will help with the issue.

One example: http://kissanime.com/Anime/Oreca-Battle/Episode-050?id=97087
http://i.imgur.com/VqU9vJS.png
Internet Explorer 11
Adguard
Adguard
English filter + Spyware filter + Anti-Adblock Killer

While Anti-adblock Killer is enabled, the video player within KissAnime disappears. It's in every episodes.

**Comment by reek** [comment]
HI,

No support: Internet Explorer 11 + Adguard

I recommand to use Firefox and Adblock Plus
https://github.com/reek/anti-adblock-killer#instruction

Regards
Reek
