### ISSUE TITLE
ville-ideale.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#258]
Bonjour, 
https://forums.lanik.us/viewtopic.php?f=91&t=21672
```
@@||criteo.com/delivery/ajs.php?$script,domain=ville-ideale.com
@@||pagead2.googlesyndication.com/pagead/$script,domain=ville-ideale.com
```

**Comment by reek** [comment]
Hi,

This simple filter does not it enough?
<pre>
ville-ideale.com###sp
</pre>

**Comment by SMed79** [comment]
Nice catch, reek! Thanks!
https://hg.adblockplus.org/listefr/rev/acbf221476d6

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Changed to ###espace i have restor my filtres https://hg.adblockplus.org/listefr/rev/3505f699ceea

**Comment by reek** [comment]
Ok

2015-03-24 22:49 GMT+01:00 Med <notifications@github.com>:

**Comment by SMed79** [comment]
https://hg.adblockplus.org/listefr/rev/28dba47f512c#l1.48

**Comment by SMed79** [comment]
`ville-ideale.com##DIV#enc[style="display: block;"]`

**Comment by reek** [comment]
Ok, thanks

2015-05-17 20:51 GMT+02:00 Med <notifications@github.com>:

**Comment by SMed79** [comment]
`ville-ideale.com###antyp`

**Comment by reek** [comment]
Thanks, Med, I will also add a rule on AakScript to counter even if the id of the element changes.

**Comment by reek** [comment]
I'll add a rule also notre-planete.info

**Comment by SMed79** [comment]
Le demande de désactiver les bloqueurs de publicités pour donner ou noter des avis.
`@@||notre-planete.info/medias/pub_300x250.png`

**Comment by reek** [comment]
@SMed79 
Merci :+1:
