### ISSUE TITLE
happy-hack.ru

### ISSUE THREAD

**Issue by COOLak** [reek/anti-adblock-killer#2582]
http://happy-hack.ru/

With the adblocker this website shows a black screen saying "Please disable AdBlock" instead of any page: http://imgur.com/a/Gx9YW
Browser: Firefox 50.1.0
Adblocker: Adblock Plus with the subscriptions "AdBlock warning removal list", "RuAdList+EasyList", "Aaklist (Anti-AdBlock Killer)"
Script manager: GreaseMonkey with the script "Anti-Adblock Killer | Reek" 10.0.

**Comment by mapx-** [comment]
add
`@@||kody-smaylikov.ru/10/popunder.js`

**Comment by COOLak** [comment]
Thanks, that was it.

**Comment by uBlock-user** [comment]
add

`||$third-party,script,domain=happy-hack.ru`
