### ISSUE TITLE
http://sc2casts.com/

### ISSUE THREAD

**Issue by greatjim** [reek/anti-adblock-killer#2583]
This page has another nasty adblocker. Sorry I am not into web technologies and cannot help here.
http://sc2casts.com/

Maybe someone sees through this.

**Comment by mapx-** [comment]
add this filter
`@@||pagead2.googlesyndication.com^$script,domain=sc2casts.com`

**Comment by mapx-** [comment]
or
```
sc2casts.com##[style="display:none"] + DIV > DIV:first-child + DIV[class]
sc2casts.com##DIV[style="display:none"] + DIV > DIV:first-child > [class]
```

**Comment by greatjim** [comment]
Wow thank you! Works perfect :)
