### ISSUE TITLE
harrypotter.wikia.com and maybe other wikia sites

### ISSUE THREAD

**Issue by mleyen** [reek/anti-adblock-killer#2584]
Link (example): http://harrypotter.wikia.com/wiki/For_the_Greater_Good
Screenshot: [Imgur](http://i.imgur.com/Zefihh1.png) (shows both the message and its DOM as reported by Firebug)
Browser: Firefox
Script manager: Greasemonkey
Adblocker: Adblock Plus
Lists: EasyList+FR, AakList

Message has a randomly generated class name which changes on every page load, making it hard to block by ID. Closing the message causes it to reappear on the next page as well.

**Comment by uBlock-user** [comment]
add

`/abtesting/`

**Comment by mleyen** [comment]
Thank you!
