### ISSUE TITLE
http://www.androidcentral.com

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#2586]
http://www.androidcentral.com gets detected.

**Comment by uBlock-user** [comment]
add 
````
#@#.adunit
#@#.block-mbn-offers
````

**Comment by mapx-** [comment]
add
```
androidcentral.com#@#.block-mbn-offers
androidcentral.com#@#.adunit
```

**Comment by purevertigo** [comment]
where do I add it to?

**Comment by mapx-** [comment]
in adblocker custom filters
ABP:
how to ==> https://adblockplus.org/forum/viewtopic.php?f=2&t=42013
ubo: options, my filters

**Comment by purevertigo** [comment]
Thanks! and Merry Christmas.
