### ISSUE TITLE
imore repatched

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#2587]
http://www.imore.com has been repatched and finds ablocker.

**Comment by mapx-** [comment]
add
`imore.com#@#.adunit`

**Comment by uBlock-user** [comment]
add

````
#@#.adunit
#@#.block-mbn-offers
````

**Comment by purevertigo** [comment]
where do I add it to?

**Comment by uBlock-user** [comment]
in my filter/custom filters based on your adblocker

**Comment by purevertigo** [comment]
Thanks! and Merry Christmas!
