### ISSUE TITLE
tuxboard.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#259]
Hi reek, 

```
@@||esprit-click.com/check.js?ad_ids=$script
```
check if adblock is enabled to display an alternative ads [728x90](http://i.imgur.com/ShL0cGW.png) & [300x25](http://i.imgur.com/I2gsSfE.png)

on hxxp://www.tuxboard.com/

Thanks!

**Comment by reek** [comment]
Hi,

Yes i have ads try this
<pre>
tuxboard.com##.pubMixte + DIV[style^="background:;"]
tuxboard.com##.pubMixte
tuxboard.com##.pub728-90 + DIV[style^="background:;"]
tuxboard.com##.pub728-90
</pre>

**Comment by SMed79** [comment]
i have no ads !

**Comment by SMed79** [comment]
```
@@||esprit-click.com/*.js|$script,third-party
```
