### ISSUE TITLE
fan-de-cinema.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#260]
Hi, 
on hxxp://www.fan-de-cinema.com/
sc: http://i.imgur.com/SVOAJpg.png

```
@@||c.ad6media.fr/l.js$domain=fan-de-cinema.com
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
