### ISSUE TITLE
http://www.sozcu.com.tr/

### ISSUE THREAD

**Issue by safaktrgt** [reek/anti-adblock-killer#2600]
http://www.sozcu.com.tr/
Block adblocker
this is a news website

**Comment by uBlock-user** [comment]
`@@/js/ads.js$domain=sozcu.com.tr`

uBO alternative - `sozcu.com.tr##script:inject(abort-on-property-read.js, canRunAds)`

**Comment by mapx-** [comment]
`@@||sozcu.com.tr/*ads`

see the dedicated thread on easylist forum:
https://forums.lanik.us/viewtopic.php?f=62&t=29664
