### ISSUE TITLE
prevention.com

### ISSUE THREAD

**Issue by g2178716** [reek/anti-adblock-killer#2608]
"Ad blocker detected" - "Please enter your email or disable your adblocker"

http://www.prevention.com/health/health-concerns/heart-attack-7-signs-youre-having-heart-attack

**Comment by jeepy321** [comment]
[https://github.com/reek/anti-adblock-killer/issues/2574](url)

**Comment by jeepy321** [comment]
[2574](https://github.com/reek/anti-adblock-killer/issues/2574)
