### ISSUE TITLE
mmm.dk

### ISSUE THREAD

**Issue by lmandrup** [reek/anti-adblock-killer#261]
http://www.mmm.dk
http://i.imgur.com/Xax1aDc.png
Google Chrome v41.0.2272.101 m (64-bit)
Tampermonkey
AdBlock
Anti-Adblock Killer

**Comment by reek** [comment]
Hi,

I dont have this message. 

The message appears there on all the pages mmm.dk ?

**Comment by reek** [comment]
Hi,

With no response from you and have not found any anti-adblock I'll end this issue.

Regards
Reek
