### ISSUE TITLE
washingtonian.com

### ISSUE THREAD

**Issue by sethgoldin** [reek/anti-adblock-killer#2613]
https://www.washingtonian.com
![screen shot 2016-12-29 at 1 05 42 pm](https://cloud.githubusercontent.com/assets/4632977/21550391/8df33454-cdc7-11e6-877f-cb9b44a622db.png)
Google Chrome
Adblock Plus
AakList (Anti-Adblock Killer) & EasyList

**Comment by uBlock-user** [comment]
`@@/ads.js$domain=washingtonian.com`

**Comment by sethgoldin** [comment]
Great, that worked! Thanks!
