### ISSUE TITLE
La Nueva España

### ISSUE THREAD

**Issue by iXergi** [reek/anti-adblock-killer#2615]
http://i.imgur.com/wVKdAS2.jpg

.- http://www.lne.es
.- Google Chrome
.- anti-adblock Killer
.- Ublock Origin
.- AakList

**Comment by mapx-** [comment]
add this filter in ubo, see if works
`@@||lne.es/*ads`

**Comment by iXergi** [comment]
Filter Don't work.

**Comment by mapx-** [comment]
oh, try this:
`@@||lne.es/*ads`

**Comment by iXergi** [comment]
Great! Thanks!!!

**Comment by uBlock-user** [comment]
add - `lne.es##script:inject(abort-on-property-read.js, pr_okvalida)
`

**Comment by iXergi** [comment]
Ok, awesome!!
`lne.es##script:inject(abort-on-property-read.js, pr_okvalida)`
That filter also works
