### ISSUE TITLE
now.ru

### ISSUE THREAD

**Issue by Juggernaut99** [reek/anti-adblock-killer#262]
http://www.now.ru/item/series/Rossiyskie/Zakon_kammenih_dzhunglej_266248
http://i.imgur.com/XWz2kGK.jpg
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers
--
Only low quality video is available until Adblock Plus is turned off.
![now ru](https://cloud.githubusercontent.com/assets/11616400/6784722/7701a8c6-d192-11e4-9778-01ba299f09b0.jpg)

**Comment by reek** [comment]
No solution

**Comment by F4z** [comment]
http://www.now.ru/item/movies/none/Magor_seriya_1_7395539

I know that it is old issue, but it is still open, I think that I found solution for that, but would be nice if someone could test it, for me it works:
@@|http://adsrv.gpm-digital.com/crossdomain.xml$object-subrequest,domain=rutube.ru
@@|http://adsrv.gpm-digital.com/$object-subrequest,domain=rutube.ru
@@|http://adv.gpm-digital.com/crossdomain.xml$object-subrequest,domain=rutube.ru
@@|http://adv.gpm-digital.com/*now.ru*$object-subrequest,domain=rutube.ru

**Comment by MajkiIT** [comment]
Hi, F4z

I test your solution and it works. 
My configuration:
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

**Comment by reek** [comment]
@F4z 
I believe not that it works because your filters are for rutube

**Comment by F4z** [comment]
Because frame/video player is from rutube.ru http://i.imgur.com/CzQ9urv.jpg

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/213#issuecomment-111755620
