### ISSUE TITLE
soulreaperzone.com 

### ISSUE THREAD

**Issue by Melancholy192** [reek/anti-adblock-killer#2620]
I cant download any animes because of blockadblock script,Pls help me.I have aldy stopped all of my adblock but still cant past that 
![fking adblock](https://cloud.githubusercontent.com/assets/24860304/21580470/5f83e5d0-d026-11e6-8b85-19d8eec8d72c.png)

**Comment by ghost** [comment]
add

`linkdrop.net##script:inject(bab-defuser.js)`

**Comment by Melancholy192** [comment]
i'm sorry.how to add this script?i am a newbie.

**Comment by ghost** [comment]
Open My Filters/Custom Filters and paste that there.

**Comment by Melancholy192** [comment]
![gfdgdf](https://cloud.githubusercontent.com/assets/24860304/21581311/8833f3fa-d05b-11e6-8124-86797ed6872d.png)

**Comment by mapx-** [comment]
you cannot use the filter above (it's only for ubo users).

**Comment by Melancholy192** [comment]
err i see.ok then i try ubo.thanks

**Comment by mapx-** [comment]
linkdrop or soulreaperzone ?

**Comment by Melancholy192** [comment]
i cant download animes from soulreaperzone cuz of that blockadblock link.It keep blocking although i have disabled all.the links from soulreaperzone website

**Comment by mapx-** [comment]
which is the download link ?

**Comment by Melancholy192** [comment]
all of the links after they use blockadblock script. 
![adblo](https://cloud.githubusercontent.com/assets/24860304/21581349/64db69cc-d05d-11e6-846d-46c996730add.png)

**Comment by mapx-** [comment]
just post the link ! not the image

**Comment by Melancholy192** [comment]
http://linkdrop.net/dYfmlA

**Comment by mapx-** [comment]
you could use this filter in your current AB
`@@/^((?!cpmstar.com|popads.net|mgid.com|oclasrv.com|wwwpromoter.com|onclickads.com|www.).)*$/$script,third-party,domain=linkdrop.net`

**Comment by mapx-** [comment]
above you published a pic about sznpaste, so provide a link also for it

**Comment by Melancholy192** [comment]
it's working now.thanks alot sir.
