### ISSUE TITLE
Not working in http://udemycoursedownloader.com

### ISSUE THREAD

**Issue by harryqt** [reek/anti-adblock-killer#2627]
The anti-adblock does not working inhttp://udemycoursedownloader.com.
Please look into it.

**Comment by mapx-** [comment]
add this filter in your adblocker
`@@||udemycoursedownloader.com^$generichide`

**Comment by harryqt** [comment]
**Thank you. It's worked. 👍**

**Comment by uBlock-user** [comment]
`udemycoursedownloader.com##script:inject(setTimeout-defuser.js, _creatBait, 1)`
