### ISSUE TITLE
aetv.com blocks ad blocker

### ISSUE THREAD

**Issue by Zanroth** [reek/anti-adblock-killer#2629]
http://www.aetv.com/shows/leah-remini-scientology-and-the-aftermath/season-1/episode-1
Firefox 50.1.0
Greasemonkey 3.9
Adblock Plus 2.8.2
AakList (Anti-Adblock Killer)
EasyList
![a e blocks ad blocker](https://cloud.githubusercontent.com/assets/19828021/21595517/e75bd0ec-d0eb-11e6-84f9-9d7cca3d969d.jpg)

**Comment by mapx-** [comment]
try this filter (the first anti adb message gone, but after that I have the provider stuff)
`@@||fastly.net$domain=aetv.com`

**Comment by Zanroth** [comment]
Hey it works thank you for quick fix.
