### ISSUE TITLE
hulu.com

### ISSUE THREAD

**Issue by blackout37** [reek/anti-adblock-killer#263]
currently only supports a bypass through their block system through 1 ad which is the Verizon one. page must be refreshed until this ad is an option and then it can bypass the system

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

And making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
