### ISSUE TITLE
https://cmacapps.com/

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#2631]
Doesn't work on this site

**Comment by mapx-** [comment]
add
`@@||cmacapps.com^$generichide`

**Comment by uBlock-user** [comment]
`@@||cmacapps.com^$elemhide`

**Comment by ghost** [comment]
Sorry new to this where do i add these codes?

**Comment by mapx-** [comment]
custom filters in your adblocker
use generichide, elemhide is blocking any other hiding filter (it works only in ubo)

**Comment by ghost** [comment]
I added the codes and erased my chrome browser cookies and i still get that annoying adblock, is the only one that i can't get rid off

![region capture 1](https://cloud.githubusercontent.com/assets/24884355/21602290/5e30db08-d160-11e6-9906-0a6792f747f8.png)
![region capture 2](https://cloud.githubusercontent.com/assets/24884355/21602291/5e324c18-d160-11e6-8377-ad355a22d654.png)

**Comment by mapx-** [comment]
- use only the generichide filter
- use only 1 blocking extension (ABP)

**Comment by ghost** [comment]
doesn't work, i really dislike this company https://blockadblock.com we need to stop them once and for all... so many websites are using there services!

**Comment by mapx-** [comment]
disable all other extensions, keep only ABP + generichide filter + easylist, test again

**Comment by ghost** [comment]
Thank you so much mapx- it work after uninstalling my the rest of my extension... then i started to reinstall one by one and found out that my winscribe vpn extension was triggering the BlockAdblock.

So I can use the same technique with other sites with the same BlockAdblock?

**Comment by mapx-** [comment]
not for all, there are variations. For the most it's enough a generichide filter.

**Comment by ghost** [comment]
OK! I can't thank you enough for the help!

**Comment by uBlock-user** [comment]
Avoid using any VPN based extensions, they will always break the filters.
