### ISSUE TITLE
http://beelink.in/

### ISSUE THREAD

**Issue by Dijir** [reek/anti-adblock-killer#2634]
![](http://image.prntscr.com/image/a95f82a5e76b403ebfc0a800c3292d5d.png)

**Comment by Dijir** [comment]
>         if (!document.getElementById('xd') || document.getElementById('xd').style.display.indexOf('none') > -1 || document.getElementById('xd').className != '') {
>             v = true
>         } else if (!document.getElementById('zd') || document.getElementById('zd').style.visibility == 'hidden') {
>             v = true
>         } else if (document.getElementById('zd').clientHeight == 0) {
>             v = true
>         }
>         if (z && z.parentNode) {
>             z.parentNode.removeChild(z)
>         }
>         if (x && x.parentNode) {
>             x.parentNode.removeChild(x)
>         }
>         if (v === true) {
>             ShowAdbblock()
>         }

**Comment by mapx-** [comment]
try this filter in your adblocker
`@@||advert.popunder.ru^$domain=beelink.in`

**Comment by uBlock-user** [comment]
add `beelink.in##script:inject(noeval.js)`

**Comment by Dijir** [comment]
Thanks!
