### ISSUE TITLE
xiaopan.co

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#264]
http://xiaopan.co/forums/community/support/
http://i.imgbox.com/dhUnlr9h.png
Chromium Version 43.0.2343.0 (64-bit)
uBlock 0.9.2.1 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy‎
Tampermonkey BETA 3.11.4615 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

message source:
"<div class="xenOverlay" style="z-index: 9999; top: 74.1px; left: 366.5px; position: fixed; display: block;"><div class="errorOverlay"><h2 class="heading">Your attention is required</h2><div class="baseHtml errorDetails">Our system has detected that an "AdBlocker" is installed in your browser. In settings, select "Don't run pages on this domain" Logged in members can dismiss this message. Or go VIP to disable the message. You may not be aware, this site supports itself through advertising to pay for hosting. Thanks.</div></div></div>"

temporary solution:
xiaopan.co##body > .xenOverlay:nth-of-type(6) > .errorOverlay
xiaopan.co##body > .xenOverlay:nth-of-type(7) > .errorOverlay
xiaopan.co##body > .xenOverlay:nth-of-type(13) > .errorOverlay
xiaopan.co##body > .xenOverlay:nth-of-type(94) > .errorOverlay
xiaopan.co##body > .xenOverlay:nth-of-type(14) > .errorOverlay
xiaopan.co##body .errorOverlay
xiaopan.co###exposeMask
**type number changing time to time.

current setup
xiaopan.co##body .errorOverlay
xiaopan.co###exposeMask

type number changing time to time.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
