### ISSUE TITLE
Does not work on whosampled.com [solved]

### ISSUE THREAD

**Issue by andreis** [reek/anti-adblock-killer#2642]
[URL](http://www.whosampled.com/sample/263347/Freddie-Gibbs-Madlib-Knicks-The-Ovations-Louis-Williams-I-Care-for-You/)

![screen shot 2017-01-05 at 11 59 27 am](https://cloud.githubusercontent.com/assets/1249760/21676535/9a3a7142-d33e-11e6-9a33-29e6f93fc295.png)

**Comment by uBlock-user** [comment]
add ``whosampled.com##script:inject(abort-on-property-read.js, WS.isOverlayActive)``
