### ISSUE TITLE
uploadrocket (again)

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#2648]
I guess uploadrocket.net changed their interface for the new year.  

Try,  http://uploadrocket.net/cowa6lsj86j2

Then click the "Click for free download button" button near the bottom.  That's when things go wrong.

Just in case, the source page for this link is:

http://scene-rls.com/outrageous-acts-of-science-s07e05-game-changers-720p-web-dl-aac2-0-h264-plaid/

I'm mentioning that because another download site referenced from this page, uploading.site, seems little strange too.   But enough clicks on this one does get you to a captcha.

**Comment by mapx-** [comment]
add
@@||uploadrocket.net/advertising/ads.js
javascript:$popup,domain=uploadrocket.net

however, click "slow download"

**Comment by xyzzy-xyzzy** [comment]
Seems to work.  Weird but acceptable behavior though.  First click on "slow download" has no visible effect.  Second click causes a couple of window flashes.  Then it takes a couple more clicks to get to the capcha. :)  But, hey, it works, thanks.

I'm not that fluent in this stuff, so to save me some googling, what does the snail icon mean next to that second rule (javascript:$popup,domain=uploadrocket.net) in the ABP filter list?

**Comment by mapx-** [comment]
the snail icon indicates a (theoretically) slow filter

**Comment by xyzzy-xyzzy** [comment]
That's what I suspected.  So does this slow _all_ filter processing down (which would concern me) or for this case, just filter processing on uploadrocket (which is fine)?

**Comment by mapx-** [comment]
sure, it's only focused on that site

**Comment by xyzzy-xyzzy** [comment]
Ok, thanks for the help and info.  I'll close this issue now.

**Comment by uBlock-user** [comment]
By snail icon if you mean `@@` that's a whitelisting directive and it doesn't slow down or anything like that.

**Comment by xyzzy-xyzzy** [comment]
No.  I didn't mean the leading double "at" characters on a rule.  I meant an actual icon of a snail, complete with a body, two antennae, and a shell on its back  :-)  It is drawn in the "slow filters" column (column title is a "!").  If you want to see it for yourself enter the second rule mentioned earlier.  You can always delete the rule back out.

**Comment by uBlock-user** [comment]
> It is drawn in the "slow filters" column.........................

What are you talking about ? You must be on ABP or another generic adblocker, otherwise there's no such thing as "slow filters" or "slow columns" in Easylist. uBO doesn't have anything like that and is vastly efficient when compared to ABP or any other generic adblockers.

**Comment by xyzzy-xyzzy** [comment]
I use ABP instead of uBO.  Why?  Because I also use [Element Hiding Helper for Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/elemhidehelper/).  There's [one site](https://www.macupdate.com/) I use a lot (in fact it's my home page) and it plasters its page with all sorts of annoying garbage I want to suppress.  

Would uBO still allow use of Element Hiding Helper?  I never bothered trying the experiment.  Or if not is there some equivalent element hiding technique?

**Comment by mapx-** [comment]
@xyzzy-xyzzy, no, ubo is using other specific tool which unfortunately is not friendly as EHH and it cannot manage the filters at EHH's level. Otherwise ubo is a good adblocker.

@uBlock-user , if you didn't use ABP in firefox you know nothing about its features. Why discussing about things you didn't use in first person ?

**Comment by xyzzy-xyzzy** [comment]
Well this discussion finally got me to check the answer to this question myself (EHH for uBO) and some [googling](https://www.google.com/search?q=element+hiding+and+ublock+origin&ie=utf-8&oe=utf-8) led me to uBO's [Element Picker](https://github.com/gorhill/uBlock/wiki/Element-picker) which I guess is uBO's approximation to EHH.

**Comment by mapx-** [comment]
the element picker is like "block element" in ABP for chrome, I mean not so many possibilities to create / manage hiding filters.

**Comment by xyzzy-xyzzy** [comment]
Ok.  I was going to go back and edit my last post to say ABP + EHH + the three geasemonkey scripts + the various filter list are doing their jobs of taming most web pages I use so I really don't have much incentive to "reinvent the wheel" (so to speak) and replacing ABP.

By the way the three greasmonkey scripts I was referring to are: Anti-Adblock Killer, AdsBypasser, and AntiAdware.
