### ISSUE TITLE
The Globe and Mail

### ISSUE THREAD

**Issue by dXtrmn8r** [reek/anti-adblock-killer#2649]
[http://www.theglobeandmail.com/life/horoscopes/jan-6-your-daily-horoscope/article33442293/](http://www.theglobeandmail.com/life/horoscopes/jan-6-your-daily-horoscope/article33442293/)
![image](http://i.imgur.com/iZ4Q9Ix.jpg)
Opera + Chrome
Tampermonkey
Adblock
EasyList + AakList

**Comment by mapx-** [comment]
try this filter (in your AB)
`@@||theglobeandmail.com^$generichide`

**Comment by dXtrmn8r** [comment]
`generichide`/`elemhide` worked. thanks!

please update filters accordingly

**Comment by uBlock-user** [comment]
No need for `$generichide` if you're using `$elemhide`, both do the same. Just use either one of those.

**Comment by mapx-** [comment]
@uBlock-user , read https://github.com/reek/anti-adblock-killer/issues/2641#issuecomment-270858309

"both do the same" only in ubo

**Comment by uBlock-user** [comment]
@mapx- yes, I did. Care to cite a source ?
