### ISSUE TITLE
usatoday.com

### ISSUE THREAD

**Issue by rischconsulting** [reek/anti-adblock-killer#2652]
See, e.g. http://www.usatoday.com/picture-gallery/sports/nfl/2014/01/23/one-great-photo-from-every-super-bowl-in-history/4777097/

Screenshot here: https://drive.google.com/file/d/0B52JQfIXbSs-dXNoYzFEaFBtNG8/view?usp=drivesdk

Mozilla Firefox
Greasemonkey
uBlock
EasyList + AakList

**Comment by mapx-** [comment]
I cannot reproduce the issue, however try the filters here:
https://forums.lanik.us/viewtopic.php?p=110259#p110259

**Comment by rischconsulting** [comment]
Hmmm. I tried the filters in my filters (both different suggestions), to no avail. The first time I loaded there was no message, but when I clicked the first slideshow item, it came up, and has come back up since.  

If you aren't seeing it, are you running these filters? Could my blur anti-tracking be messing with this?

**Comment by mapx-** [comment]
oh, just disable all other blocking extensions / addons and test again (I tested the site using only easylist)

**Comment by rischconsulting** [comment]
Nevermind - cleared cookies and it all worked.

**Comment by uBlock-user** [comment]
`||$third-party,domain=usatoday.com`
`@@||gannett-cdn.com^$image,stylesheet,domain=usatoday.com`

**Comment by rischconsulting** [comment]
Thanks, I implemented
