### ISSUE TITLE
bitvisits.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#266]
http://www.bitvisits.com/
http://i.imgbox.com/kicrr4DK.png
Chromium Version 43.0.2345.0 (64-bit)
uBlock 0.9.2.1 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy‎
Tampermonkey BETA 3.11.4615 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

message:"<div class="alert-box adBlockMessage">
                    <h4>Ad Blocker Detected</h4>
                    <p>Oh no! We've detected that your browser is using an ad blocking plugin :(</p>
                    <p>BitVisits.com relies heavily on displaying ads to our users. This is how we are able to keep the site running and keep offering you this service. We try to make this process less annoying by displaying relevant ads that we think you may like.</p>
                    <p><strong>Please consider disabling any ad blocking software before continuing. If you don't, some features of the site will be unusable.</strong></p>
                    <p>Thanks,<br>
                    The BitVisits Team</p>
                    
                    <div class="formFooter align-center">
                        <a href="#" class="button blue adblockModal-close">I'll disable any adblocking plugins. I promise!</a>
                    </div>
                </div>"

www.bitvisits.com###adblockModal > .column-container > .col-centered.one-half.column > .adBlockMessage.alert-box
www.bitvisits.com###adblockModal

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
