### ISSUE TITLE
No longer working on http://theglobeandmail.com

### ISSUE THREAD

**Issue by DaTechNinja** [reek/anti-adblock-killer#2662]
The script no longer kills the anti-adblock message on The Globe and Mail site.

Here is my solution, feel free to include it in your project: https://github.com/DaTechNinja/globe-and-mail-anti-adblock-killer

**Comment by uBlock-user** [comment]
or you could simply use the set of filters posted below

````
||$third-party,domain=theglobeandmail.com
@@||theglobeandmail.ca^$domain=theglobeandmail.com
````

There's no need for AAK anymore, all websites can be patched via filters such as those with your adblockers.

**Comment by DaTechNinja** [comment]
Ah, good to know. Thanks for the info @uBlock-user
