### ISSUE TITLE
AlobaidiDetectAdBlock

### ISSUE THREAD

**Issue by hdf** [reek/anti-adblock-killer#2663]
This site: http://www.katholisches.info/
Checks if this variable exists: window.AlobaidiDetectAdBlock
and if not, than redirects to a "Disable your AdBlocker page."

This variable is defined thus:
var AlobaidiDetectAdBlock=true;
in a locally linked file:
http://www.katholisches.info/tawato/plugins/detect-adblock/js/ads.js

So, 2 options:
Add /detect-adblock/ to exception list on blocking,
or
let's define AlobaidiDetectAdBlock ourselves.

I'm not sure how anti-adblock-killer works, so not sure which approach would be a better fit.
Am I reporting this in the wrong place?

**Comment by mapx-** [comment]
should be ok the exception
`@@||katholisches.info^*ads$script`

**Comment by mapx-** [comment]
already reported on easylist germany forum:
https://forums.lanik.us/viewtopic.php?f=90&t=34998

**Comment by hdf** [comment]
Thank you, but how do I add this to Anti Adblock Killer again?

**Comment by mapx-** [comment]
just use the filter in your custom filters (in your adblocker)

**Comment by hdf** [comment]
Ok, it works, thank you. So this isn't the sort of thing that anti-adblock-killer
 is going to handle?

**Comment by mapx-** [comment]
well, - IMO - AAK should serve only in very complex cases and not when a simple filter can fix the issue.

**Comment by uBlock-user** [comment]
add `@@/js/ads.js$domain=katholisches.info`

AAK is hardly in active development, you can wait for it to patch this or you can simply patch it yourself by adding that filter.

**Comment by ghost** [comment]
Hi, I have an issue with a wordpress page that uses this plug in: 
[Detect AdBlock](https://wordpress.org/plugins/detect-adblock/)

To disable this, I tried with the following configuration with good results (until now):
UBlock control panel> My filters> add:
`@@||**^*ads$script`
And in the anti-adblock-killer user options I added the following at the included sites:
`@@||**^*ads$script`
