### ISSUE TITLE
cryptospout.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#268]
https://cryptospout.com/faucet/hourly_bitcoin_faucet.html
http://i.imgbox.com/kytvAPUM.png
Chromium Version 43.0.2345.0 (64-bit)
uBlock 0.9.2.1 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy‎
Tampermonkey BETA 3.11.4615 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

message:"<strong>ADBLOCK DETECTED REDUCED REWARD PENATLY! Please unblock ads for cryptospout.com (I PROMISE THEY ARE NOT INVASIVE) to get the full reward from the faucet</strong>"

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
