### ISSUE TITLE
Einthusan ad block won't work

### ISSUE THREAD

**Issue by penta11** [reek/anti-adblock-killer#2694]
https://einthusan.tv/launcher/?lang=hindi
http://imgur.com/a/5PUi3
Google Chrome
Tampermonkey
Adblock and adblock plus--both
Easylist+Aaklist on both of them.

**Comment by mapx-** [comment]
1. **it's wrong keeping 2 adblockers**, use only ABP (AB is using ABP engine)

2. after removing AB add these filter in ABP
```
@@||einthusan.tv^$generichide
@@||imasdk.googleapis.com^$domain=einthusan.tv
```

**Comment by penta11** [comment]
Thanks for that info mapx. I have disabled AB. Also, got rid of the problem by adding these filters. Thanks!

**Comment by freakheart** [comment]
Thanks mapx.. I have added your filters and now its fine.

**Comment by amixpal** [comment]
@freakheart Did the filter work for you?

**Comment by ssrb19** [comment]
Stopped working
