### ISSUE TITLE
http://alt-torrent.com/

### ISSUE THREAD

**Issue by SBI-boy** [reek/anti-adblock-killer#2699]
I think they are using a sophisticated anti-adblock method, please get rid of it
ss: http://imgur.com/a/sNe3u
example url: http://alt-torrent.com/movie/the-mermaid-2016-720p-lat.html
user/pass: anti-adblock:anti-adblock

Firefox x64 (latest stable)
uBlock Origin (latest stable)
Greasemonkey (latest stable)

**Comment by mapx-** [comment]
you should provide a test account

**Comment by uBlock-user** [comment]
add - `@@/js/ads.js$domain=alt-torrent.com`

**Comment by SBI-boy** [comment]
@mapx- read carefully the 1st post 

> user/pass: anti-adblock:anti-adblock

 😄 

@uBlock-user it's working, many thanks

**Comment by IvoUrrutia** [comment]
Not work for me
