### ISSUE TITLE
play.tv (playtv.fr)

### ISSUE THREAD

**Issue by reek** [reek/anti-adblock-killer#27]
Hi,

I'll post soon a solution against the anti-adblock of play.tv

See you soon
Reek

**Comment by F4z** [comment]
I know that it is old issue, but it is still open, I think that I found solution for that, but would be nice if someone could test it, for me it works:
@@||ad4.liverail.com/?LR_$object-subrequest,domain=play.tv|playtv.fr

**Comment by reek** [comment]
@F4z 
It don't work for me, did you test all channels ?

**Comment by F4z** [comment]
Hi,
I test it on about 10 channels, and it works for me. http://i.imgur.com/LwSwhDe.png
Which channels did you test?
Maybe it depends on region?
For example this in this issue https://github.com/reek/anti-adblock-killer/issues/213 my "soltuion" works for me if I have my own IP from Poland, but if I change IP using VPN program to Russia IP it dosen't work.

**Comment by reek** [comment]
Hi,

I have test "Arte BFMTV, Equipe21 iTELE", It seems to work during the first visit but after that does not work any more

**Comment by F4z** [comment]
Yes, you are right, I also have message about AdBlock on BFMTV.
I had a problem to found Arte, Equipe21 and iTELE, I found but in Poland these channels don't work.
I changed my IP to IP from France and after that, these channels works ok.
For Equipe21 and iTELE I hadn't any problem, but for Arte I had message "Pour profiter de la télévision en illimité, connectez-vous ou abonnez-vous, c'est gratuit ! (26 secondes)", so if I good understand this, after 30 seconds this channel is only for (free) registered users.
I tested most of channels (probably all but some channels had problem with loading, but without adblock these channels also didn't work) and I had a problem with two channels only, with BFMTV and iFilm, on this channels I have message about AdBlock.


So maybe this help, I know that not always all of them are needed but with this filtres for me all channels work:
<pre>@@||/*playtv$object-subrequest,domain=play.tv|playtv.fr
@@|http://ads.stickyadstv.com/crossdomain.xml$object-subrequest,domain=play.tv|playtv.fr
@@|http://ads.stickyadstv.com/www/delivery$object-subrequest,domain=play.tv|playtv.fr
@@||bid.g.doubleclick.net/$object-subrequest,domain=play.tv|playtv.fr
@@||bs.serving-sys.com/crossdomain.xml$object-subrequest,domain=play.tv|playtv.fr
@@||bs.serving-sys.com/BurstingPipe/adServer.bs$object-subrequest,domain=play.tv|playtv.fr
@@||ad*.liverail.com/?LR_$object-subrequest,domain=playtv.fr
@@||ad.doubleclick.net/crossdomain.xml$object-subrequest,domain=playtv.fr
@@||ad.doubleclick.net/$object-subrequest,domain=playtv.fr</pre>

**Comment by reek** [comment]
@F4z 
I am going to add your filters, that will be better that that without

**Comment by F4z** [comment]
It looks like I have made mistake in the first filter - https://github.com/gorhill/uBlock/issues/997#issuecomment-170918790
Can you fix it?
Sorry :/

**Comment by reek** [comment]
ok
