### ISSUE TITLE
hdonline.vn

### ISSUE THREAD

**Issue by asdy13** [reek/anti-adblock-killer#270]
this web kill my adblock

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

And making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

With no response from you and have not found any anti-adblock I'll end this issue.

Regards
Reek
