### ISSUE TITLE
mangamap.com

### ISSUE THREAD

**Issue by RijndaeI** [reek/anti-adblock-killer#272]
http://www.mangamap.com/Attack_on_Titan3/67/19/
http://i.imgur.com/DF1ptKZ.png
Chrome 41
Chrome's native script manager
uBlock
Easylist + uBlock filters + AntiAdblock Killer

-------------------------------------------------------------------------
Already blocked AntiAdblock message by using element hiding (www.mangamap.com###sct_content > .con > .mng_rdr.wpm_pag > div:nth-of-type(2) > p)
But it just hides the message, doesn't show the content, checked source and it seems to add "display: none" to "manga-page" class whenever adblock is activated, i tried to remove it manually (http://i.imgur.com/L4hH5Yl.png) which actually worked (http://i.imgur.com/m4PPXn7.png), but im not skilled enough to make it work automatically.
Greetings and sorry for my english.

**Comment by gorhill** [comment]
@RijndaeI For what it's worth, I use default-deny, and just by disabling 1st-party scripts for the site, I got rid of the warning, and I could navigate to other pages through the drop down list without any problem:

![a](https://cloud.githubusercontent.com/assets/585534/6881412/ce6c9968-d534-11e4-9f2a-83d95377b26a.png)

I do not know the site enough to know whether important functionalities are broken, but it did look like it worked fine to me.

**Comment by RijndaeI** [comment]
@gorhill Thanks for your reply
By disabling 1st party scripts actually gets rid of the message and shows the image, however by doing so arrow keys navigation also gets disabled (you can use left-right keys to navigate to previous-next page).
Is there a way to get that feature back?
Thanks again

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
