### ISSUE TITLE
hackintosh.zone

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#2727]
https://www.hackintosh.zone/
http://imgur.com/a/vBh30
Browser: Google Chrome Latest
Adblocker: AdBlock
Script Manager: Tampermonkey
Filterlists: AakList

**Comment by mapx-** [comment]
visit easylist forum, you'll get a lot of fixes there:
https://forums.lanik.us/viewtopic.php?p=111364#p111364
```
@@/^((?!googlesyndication|adsystem).)*$/$script,third-party,domain=hackintosh.zone
@@||$xmlhttprequest,image,domain=hackintosh.zone,third-party
@@||cdn.hackintosh.zone/ads/ads.js
```

**Comment by ghost** [comment]
Thanks.

**Comment by ghost** [comment]
This forum is awesome dude! No need to write here for problems just search in this forum then you are ready to go!

**Comment by ghost** [comment]
How did you find some sites' code that this site doesn't have?

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2657
