### ISSUE TITLE
q.gs

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#2728]
http://q.gs/C1KOC
![image](https://cloud.githubusercontent.com/assets/14945598/22178597/b6c5ed70-e043-11e6-84b1-f96a5e707b71.png)

**Comment by uBlock-user** [comment]
can't reproduce

**Comment by ghost** [comment]
What do you mean?

**Comment by ghost** [comment]
OK AdsBypasser fixed it.
