### ISSUE TITLE
toutgagner.com

### ISSUE THREAD

**Issue by zuifon** [reek/anti-adblock-killer#2733]
Sample : http://toutgagner.com/jeux-concours/termines-semaine-prochaine.html?page=8

10 secondes block message on every page
http://imgur.com/KE050b5

Chrome 55.0.2883.87
Adguard
FR List
Adblock Warning Removal List
Anti Adblock Killer Reek

**Comment by mapx-** [comment]
add
```
@@||toutgagner.com^$generichide
@@||toutgagner.com/*ads
```

**Comment by uBlock-user** [comment]
add  `@@||toutgagner.com^$elemhide`
