### ISSUE TITLE
allmyvideos.net

### ISSUE THREAD

**Issue by zowyck** [reek/anti-adblock-killer#274]
http://allmyvideos.net/s5cnxidnfcjm
http://m86.imgup.net/112ab.png
Google Chorme
TamperMonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers
![1](https://cloud.githubusercontent.com/assets/11727283/6907425/3aaa8986-d6f3-11e4-923d-4714a8b3af11.png)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Do you still displayed message ?

**Comment by zowyck** [comment]
Hi not, Maybe the page is testing this system at different times, this moment work fine

**Comment by reek** [comment]
Ok, let me know when the message will appear

**Comment by zowyck** [comment]
http://allmyvideos.net/7ipzcplxp8yw
Hour 10:30PM universal time UTC 0
back block

**Comment by reek** [comment]
ok, I'll take a look

**Comment by Wasdsensei** [comment]
Another link: http://allmyvideos.net/embed-wrw54xqz95c5.html

I think allmyvideos was only doing this for certain links at first, but they seem in full swing with it now.

**Comment by reek** [comment]
@Wasdsensei 
Nothing

**Comment by Wasdsensei** [comment]
@reek
Should clarify that with adblock disabled, it plays a video on allmyvideos.net, otherwise it redirects to a pay-per-view site at movieflix.to.

**Comment by reek** [comment]
@Wasdsensei 
I'll try to skip it
