### ISSUE TITLE
http://www.ramleague.net/

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#2741]
http://www.ramleague.net/threads/ddos-any-csgo-server.5240/
![image](https://cloud.githubusercontent.com/assets/14945598/22215900/a5966bfc-e1a5-11e6-938e-8bcfc6452b01.png)

**Comment by mapx-** [comment]
`||ramleague.net/js/xenforo/xenforo.js`

**Comment by ghost** [comment]
Ok it worked but still show this "Do not use BLOCK ADS" message
![image](https://cloud.githubusercontent.com/assets/14945598/22218231/9f8491ae-e1ae-11e6-876f-5b0f330eeeea.png)

**Comment by ghost** [comment]
And where are you find these codes please?

**Comment by mapx-** [comment]
for example using ABP in firefox (it has "blockable items list" where you can see what is blocked, you can create filters etc). Also, use EHH (firefox, element hiding helper, helps creating hiding filters). And finally, examining the page code.

Sure, AB (or ABP in chrome or ubo in chrome / firefox) has its own tools but not friendly as ABP in firefox.

**Comment by ghost** [comment]
I understand thank you.

**Comment by mapx-** [comment]
add also
`ramleague.net##DIV.fixmeup:first-child + DIV:last-child`

**Comment by ghost** [comment]
Now it is completely adless. Thanks so much.

**Comment by uBlock-user** [comment]
add - `/rellect^$script`

**Comment by ghost** [comment]
Thanks uBlock-user it fixed the empty add bar
