### ISSUE TITLE
marca.com

### ISSUE THREAD

**Issue by nenesio** [reek/anti-adblock-killer#2756]
marca.com (all pages)
chrome
uBlock Origin
EasyList + uBlock filters ‎+ AakList

http://imgbox.com/oZAQXS5Q

![marca](https://cloud.githubusercontent.com/assets/25374167/22347975/58729340-e3e0-11e6-8a74-0272ad49afcc.PNG)

**Comment by uBlock-user** [comment]
add - `||$third-party,script,domain=marca.com`

**Comment by nenesio** [comment]
this work, thanks

**Comment by eXPerience83** [comment]
this blocks more than needed, impeding the web work correctly:
add - ||$third-party,script,domain=marca.com

for now, this is better:
@@||marca.com^$generichide

**Comment by nenesio** [comment]
this is better:
`@@||active.cache.el-mundo.net/js/advertisement.js`

**Comment by eXPerience83** [comment]
@@||active.cache.el-mundo.net/js/advertisement.js **has no effect** adblock warning appears again. only solution is:
@@||marca.com^$generichide

**Comment by nokai** [comment]
Dont work
