### ISSUE TITLE
Streamcloud adds tab cycle

### ISSUE THREAD

**Issue by ErrorUser-not-found** [reek/anti-adblock-killer#2757]
When you push on play and ad-blocker is used streamcloud open a new tab with adds and refres the page.
And that error turn cycle as you keep using ad-block, if you disable ad-block the video starts normal.
Example:  http://streamcloud.eu/5c5m45cjeegd

**Comment by mapx-** [comment]
try these filters
```
@@||meta.streamcloud.eu/serve.php?*$script
@@||pagead2.googlesyndication.com^$domain=streamcloud.eu
```

**Comment by ErrorUser-not-found** [comment]
didnt work

**Comment by ErrorUser-not-found** [comment]
ty it works

**Comment by uBlock-user** [comment]
uBO - `streamcloud.eu##script:inject(noeval.js)
`
