### ISSUE TITLE
urlchecker.org

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#276]
http://urlchecker.org/
http://i.imgbox.com/6Qylx4no.png
Chromium Version 43.0.2350.0 (64-bit)
uBlock 0.9.2.3 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎
Tampermonkey BETA 3.11.4623 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

message: "<div class="alert alert-danger" id="ads_notify">
                
                <button type="button" class="close" data-dismiss="alert" data-toggle="tooltip" data-placement="left" title="" aria-hidden="false" data-original-title="Please donate to remove all advertisment ">x</button>

                <i class="fa fa-thumbs-o-down"></i> <strong> Oh man! You're blocking one of my jazzy adverts and full function of website :'(</strong><br>
                <p>If you like the site and can spare a few pennies, please consider making a tiny donation. It'll make my life so much easier and you get to feel awesome too!
                </p>
            </div>"

urlchecker.org###ads_notify

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
