### ISSUE TITLE
Not working on this web site

### ISSUE THREAD

**Issue by reuveng60** [reek/anti-adblock-killer#2764]
https://www.weather2day.co.il/zefat-webcam

**Comment by mapx-** [comment]
add in your adblocker
```
@@||weather2day.co.il^$generichide
@@.png#$domain=weather2day.co.il
```

**Comment by uBlock-user** [comment]
add - `@@||weather2day.co.il^$elemhide`

or

add - `weather2day.co.il##script:inject(setTimeout-defuser)`

**Comment by reuveng60** [comment]
Thanks. Working now.
