### ISSUE TITLE
nordjyske.dk

### ISSUE THREAD

**Issue by uBlock-user** [reek/anti-adblock-killer#2768]
ABP - `/bundles/js?v=^$script`

uBO - `nordjyske.dk##script:inject(abort-on-property-read.js, NordjyskeGetIsLoggedIn)`

**Comment by smed79** [comment]
`@@||nordjyske.dk^$generichide`

https://forums.lanik.us/viewtopic.php?f=62&t=35252

**Comment by uBlock-user** [comment]
Yes, that will do too as an alternative.
