### ISSUE TITLE
linkbucks

### ISSUE THREAD

**Issue by lagun** [reek/anti-adblock-killer#277]
http://www.yyv.co/By83v
http://postimg.org/image/j72weohvf/
Google Chorme
adguard
adguard
English filter,Spyware filter,EasyPrivacy,Anti-Adblock Killer | Reek

**Comment by reek** [comment]
HI,

I dont use AdGuard, try Adblock Plus

**Comment by reek** [comment]
Hi,

Try this useful userscript "adsbypasser" to skip cash links.
https://adsbypasser.github.io/
