### ISSUE TITLE
animmex.net

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#2770]
please help to support:
https://www.animmex.net/video/8353/family-guy-s06e01

**Comment by mapx-** [comment]
add this filter in your adblocker
`@@/^((?!cpmstar.com|popads.net|mgid.com|oclasrv.com|wwwpromoter.com|onclickads.com|.js).)*$/$script,third-party,domain=animmex.net`

**Comment by uBlock-user** [comment]
Already patched by Easylist, force update your filters.

**Comment by callmenemo491** [comment]
hi @mapx- @uBlock-user 
thanks for the info, since Easylist has done it...
i'll force update my filters.

**Comment by mapx-** [comment]
just add the filter above, there are some requests not patched by easylist.
