### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by nicolaasjan** [reek/anti-adblock-killer#2774]
[https://blockadblock.com/search-adblock-filters.php](url)
Cyberfox 51.0.1
Greasemonkey
uBlock Origin
Adblock Warning Removal List
AakList
Fanboy+Easylist-Merged Ultimate List
Prebake - Filter Obtrusive Cookie Notices
EasyList Dutch
Anti-Facebook List
I don't care about cookies

![screenshot blockadblock com](https://cloud.githubusercontent.com/assets/14093220/22404084/a2971e14-e629-11e6-8a7f-43c2a518d9ea.png)

Lists updated today, but somehow this anti-adblocker works...
It injects the infamous fuckadblock.js script.
When I turn uBlock off, it still does not work, because of NoScript.

**Comment by uBlock-user** [comment]
add - `blockadblock.com##script:inject(bab-defuser.js)`

**Comment by nicolaasjan** [comment]
It seems to work, but only with NoScript turned off...

**Comment by uBlock-user** [comment]
Uninstall NoScript, uBO is not compatible and will cause issues.

**Comment by nicolaasjan** [comment]
Hmm... That is quite a rigorous step to take for me, as I rely on NoScript as an important line of defense.
Whenever I encounter some problem, I just (temporarily) disable it on that site or I enable just scripts from one or more domains.
But thanks for your suggestion; I will investigate further :)

**Comment by uBlock-user** [comment]
uBO can cover for NoScript and does more. You don't need NoScript if you're using uBO and they're not compatible unfortunately. You don't have much of a choice here. You can install uMatrix as a replacement for NoScript, uMatrix is from the same author that wrote uBO.

**Comment by nicolaasjan** [comment]
Thanks,
Is it necessary to completely uninstall NoScript, or can I just set it to allow scripts globally then (in order to still have some basic protection from it) ?
I will try uMatrix, but does it not interfere with uBlock Origin?

**Comment by uBlock-user** [comment]
> or can I just set it to allow scripts globally then (in order to still have some basic protection from it) ?

That will do too if you don't want to unistall. Though I'm unsure what protection will it provide if it's excluded globally.

>  but does it not interfere with uBlock Origin?

Normally no. It might block something which is not blocked by uBO, but you can rectify it quickly from the popup panel. If you're used to NoScript, uMatrix is same but acts like a firewall and offers privacy features and not just limited to blocking javascripts.

**Comment by nicolaasjan** [comment]
I am trying uMatrix now in a separate profile with only uBlock and no other addons.
I see that it blocks all scripts except from the domain itself.
Is there a way to default to blocking scripts from the domain, like NoScript does?

**Comment by uBlock-user** [comment]
Open `chrome-extension://ogfcmafjalglgifnmanfmnieipoejdcf/dashboard.html#user-rules` 

Click on Edit under Temporary Rules

Copy and paste `* 1st-party script block`

Save and click Commit to make it permanent.

**Comment by nicolaasjan** [comment]
Thanks, it works!
By the way, I use Cyberfox; a Firefox fork, so I had to open:
`chrome://umatrix/content/dashboard.html#user-rules`

**Comment by uBlock-user** [comment]
My bad, I don't use Firefox or its derivatives, so I had Chromium in mind 👍
