### ISSUE TITLE
Exame.Abril

### ISSUE THREAD

**Issue by brunobca** [reek/anti-adblock-killer#2776]
http://exame.abril.com.br/blog/primeiro-lugar/brasil-supply-vai-entrar-em-recuperacao-judicial/

![anti adblock](https://cloud.githubusercontent.com/assets/25422039/22408192/a442c2fc-e653-11e6-814b-16021f805c8a.png)

**Comment by mapx-** [comment]
add in your adblocker
`@@||abril.com.br^$generichide`

**Comment by uBlock-user** [comment]
cannot reproduce, force update your filters.
