### ISSUE TITLE
Torrentdosfilmes

### ISSUE THREAD

**Issue by brunobca** [reek/anti-adblock-killer#2777]
http://www.torrentdosfilmes.com/amor-amizade-2017-torrent-bluray-720p-1080p-dublado-dual-audio-5-1-download/

![anti adblock](https://cloud.githubusercontent.com/assets/25422039/22408229/76df9e56-e654-11e6-81dc-2bac03f360a2.png)

**Comment by mapx-** [comment]
add in your adblocker (for anti adblocking + popups)
```
@@||torrentdosfilmes.com^$generichide
@@.png#$domain=torrentdosfilmes.com
|http://$script,domain=torrentdosfilmes.com,third-party
```

**Comment by uBlock-user** [comment]
uBO
````
torrentdosfilmes.com##script:inject(overlay-buster.js)
torrentdosfilmes.com##script:inject(popads.net.js)
