### ISSUE TITLE
cloud.mail.ru

### ISSUE THREAD

**Issue by ridvanaltun** [reek/anti-adblock-killer#278]
open: http://prntscr.com/6o5tj6
close: http://prntscr.com/6o5u2x

**Comment by reek** [comment]
Hi,

I'll add an exception for cloud.mail.ru

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
