### ISSUE TITLE
http://moeni.net/%EB%8F%84%EA%B2%80%EB%82%9C%EB%AC%B4-%ED%95%98%EB%82%98%EB%A7%88%EB%A3%A8/

### ISSUE THREAD

**Issue by msconfig1** [reek/anti-adblock-killer#2782]
http://moeni.net/%EB%8F%84%EA%B2%80%EB%82%9C%EB%AC%B4-%ED%95%98%EB%82%98%EB%A7%88%EB%A3%A8/
![k-011](https://cloud.githubusercontent.com/assets/25456870/22466008/adf1a8a4-e801-11e6-9a42-77e9d7b58bfa.png)

Click on "XX화" then
"광고가 싫으십니까?(…) Adblock 설정에서 (…)"
massage is output.

Chrome 54 64-bit
Tampermonkey
uBlock Origin
EasyList
AakList

i add

@@||moeni.net^$generichide
@@||realclick.co.kr^$domain=moeni.net

but isn't working

**Comment by mapx-** [comment]
`@@||moeni.net/*ad$xmlhttprequest`

**Comment by msconfig1** [comment]
but when i click xx 화 is dosen't work again

**Comment by mapx-** [comment]
```
@@||moeni.net^$generichide
@@||moeni.net/*ad$xmlhttprequest
@@||widerplanet.com^$domain=moeni.net
@@||clickmon.co.kr^$script,domain=moeni.net
```

**Comment by msconfig1** [comment]
wow thank's
