### ISSUE TITLE
onepiece-mx.net

### ISSUE THREAD

**Issue by reek** [reek/anti-adblock-killer#279]
http://www.onepiece-mx.net/lecture-en-ligne/one_piece/782
http://www.onepiece-mx.net/lecture-en-ligne/adblock.jpg

**Comment by Robotex** [comment]
I'm not sure how to cherry-pick a commit from github's website for a pull request, but this code does the work https://github.com/Robotex/anti-adblock-killer/commit/74bda422fe563b3bede29b7ca32156c6c062aff5

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
