### ISSUE TITLE
http://moeni.net/

### ISSUE THREAD

**Issue by msconfig1** [reek/anti-adblock-killer#2798]
http://moeni.net/%EB%8F%84%EA%B2%80%EB%82%9C%EB%AC%B4-%ED%95%98%EB%82%98%EB%A7%88%EB%A3%A8/

![adf1a8a4-e801-11e6-9a42-77e9d7b58bfa](https://cloud.githubusercontent.com/assets/25456870/22598120/b90affee-ea75-11e6-9906-455fea35434b.png)

If i click "XX화" then i couldn't see the video and these message showed up

"광고가 싫으십니까? 하지만 이 사이트는 유지비용이 광고수입으로 충당되고 있습니다.

Adblock 설정에서 이 도메인을 빼주시거나 잠시꺼주시길 부탁드립니다."

Chrome 56.0.2924.87  64-bit
Tampermonkey
uBlock Origin
EasyList
KOR: Korean Adblock List‎
KOR: YousList
AakList 

three day ago i added

@@||moeni.net^$generichide
@@||realclick.co.kr^$domain=moeni.net
@@||moeni.net/*ad$xmlhttprequest
@@||moeni.net^$generichide
@@||moeni.net/*ad$xmlhttprequest
@@||widerplanet.com^$domain=moeni.net
@@||clickmon.co.kr^$script,domain=moeni.net

these code and it was worked  properly, 
but today it isn't working again 

perhaps the site manager have been updated today :(
halp me

**Comment by uBlock-user** [comment]
submit this issue at Easylist forum

**Comment by mapx-** [comment]
add
```
@@||moeni.net^$generichide
@@||realclick.co.kr^$domain=moeni.net
@@||moeni.net/*ad$xmlhttprequest
@@||moeni.net^$generichide
@@||moeni.net/*ad$xmlhttprequest
@@||widerplanet.com^$domain=moeni.net
@@||clickmon.co.kr^$script,domain=moeni.net
@@||moeni.net/ad.php?*
```

**Comment by msconfig1** [comment]
tx
