### ISSUE TITLE
vivo.sx

### ISSUE THREAD

**Issue by vinctux** [reek/anti-adblock-killer#280]
http://vivo.sx/c07efa3ab8
http://imgbox.com/nmJlZZmu

Opera 28.0.1750.48
uBlock 0.9.2.3 + Tampermonkey 3.11.4600 (https://openuserjs.org/scripts/reek/Anti-Adblock_Killer_Reek + https://openuserjs.org/scripts/legnaleurc/AdsBypasser + https://greasyfork.org/en/scripts/2600-跳过网站等待-验证码及登录) + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎

    <div id="alert-throttle" class="alert alert-warning"><center><i class="fa fa-exclamation-triangle" style="font-size: 18px; top: 2px; margin-right: 10px;"></i>You are using <abbr title="The AdBlock browser extension filters advertising on websites">AdBlock</abbr>. Stream <b>150% faster without AdBlock</b> by deactivating it on vivo.sx to obtain full speed and support our service.</center></div>
		<div style="width: 728px; margin: -10px auto 10px;" align="center">
				<script type="text/javascript">var adParams = { p: '56612348', size: '728x90', serverdomain: 'adplexmedia' };</script>
				<script type="text/javascript" src="//cdn.adplxmd.com/adplexmedia/tags/xbanner/xbanner.js?ap=1300"></script>
		</div>

vivo.sx###alert-throttle

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
