### ISSUE TITLE
Newsquest Sites detecting ublock using inline script and adblock event listener

### ISSUE THREAD

**Issue by dataclear** [reek/anti-adblock-killer#2811]
1. http://www.dailyecho.co.uk/news/15074556.UPDATE_AND_PHOTOS__Motorway_blocked_after_crash_involving_lorry__van_and_car/
(or any of the newsquest news websites http://www.newsquest.co.uk/our-titles/)
2. http://imgur.com/a/k4PVa
3. Chrome 56
4. Tampermonkey
5. uBlock Origin
6. EasyList + AakList

**Comment by uBlock-user** [comment]
add `dailyecho.co.uk##script:inject(abort-on-property-write.js, _sp_)`

This will also work for the rest of the websites in the same network, just add their names separated with a comma.

**Comment by dataclear** [comment]
Works perfectly, appreciate your time.
