### ISSUE TITLE
ay.gy

### ISSUE THREAD

**Issue by criscabellos** [reek/anti-adblock-killer#2827]
New adf.ly link that has also been blocking adblock and uBlock.

**Comment by uBlock-user** [comment]
force update your filters.

**Comment by criscabellos** [comment]
Ok. I did that.

What I found is that if I reload the page several times, one time it shows me the Skid Ad button letting me click on it. But most of the time it just stops at 1 second and shows me a page about me using an ad block.

I use both uBlock and AdBlock Plus at the same time. Is it a problem to have both working at the same time?

**Comment by uBlock-user** [comment]
Yes, uninstall Adblock Plus. Only keep uBlock Origin and nothing else.

**Comment by criscabellos** [comment]
:(

Done that. Restarted browser. Still showing message about me having uBlock active.

![image](https://cloud.githubusercontent.com/assets/25688076/22831234/60eff7b6-ef88-11e6-8aeb-64c2c6e3fb65.png)

**Comment by uBlock-user** [comment]
I cannot reproduce that.

Try - `@@||s1-adfly.com/show.php$subdocument,domain=adf.ly|j.gs|q.gs|ay.gy`

**Comment by criscabellos** [comment]
Sorry for the late reply.

Now it is working fine. Thanks a lot.
