### ISSUE TITLE
KissAnime and KissCartoon domains changed

### ISSUE THREAD

**Issue by darkmorpher** [reek/anti-adblock-killer#2828]
_

**Comment by uBlock-user** [comment]
AAK is outdated and no longer updated. Force update all your adblocker filters.

**Comment by jspenguin2017** [comment]
Hi, I put it into my script, version 5.10: 
https://x01x012013.github.io/AdBlockProtector/
I have AAK integrated into my script and list, so I don't need to fight outdated AAK code with more code. 
I'm still working on a sync tool for AAK Script, currently it is done manually. List sync is automated. 

Here is the commit for this change: https://github.com/X01X012013/AdBlockProtector/commit/ced1ec9b3de64cd0c97ae34c0ff166009a235278
