### ISSUE TITLE
tutorial for me to find how to block?

### ISSUE THREAD

**Issue by samerali2** [reek/anti-adblock-killer#2829]
http://www.thewindowsclub.com/tools-tweak-privacy-settings-windows-10

is my problem, however, is there a way to understand how to
find out WHAT to block?
thanks :D

**Comment by uBlock-user** [comment]
depends on your adblocker on how to block and what you can block

**Comment by samerali2** [comment]
ad-block ... not plus!

**Comment by samerali2** [comment]
btw, wwhen I "enter reader view" in firefox, it removes the "anti adblock"

**Comment by uBlock-user** [comment]
add - `||$third-party,script,domain=thewindowsclub.com`

**Comment by samerali2** [comment]
how in God's name did u get that :(
I was fingering (inspect (ctrl+shift+I)) ALL night yesterday with ought luck :'( 
wizard u

**Comment by samerali2** [comment]
I'll close this if I do not get an answer, but that fixed it :D

**Comment by uBlock-user** [comment]
There are multiple solutions for the anti adblock script used for the website, the one I posted is the only one that will work for your adblocker.

**Comment by samerali2** [comment]
yes, but how did u find out? do u use inspect and look at what get's loaded of scripts??
just very curious :)

**Comment by uBlock-user** [comment]
I use uBO's logger.

**Comment by samerali2** [comment]
a million thanks, I think I am good for now, just installed uBO, I'll use that along with ghostery for now :D
