### ISSUE TITLE
anti adblock killer with apache2 and nginx 

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#2830]
hello hope you'r fine i search if there are an idéés with nginx config 

i think with shell script but i don't now or redirect to the page of adblocker 
like 404 403 503 501 redirect 
than'kss

**Comment by uBlock-user** [comment]
????

**Comment by ghost** [comment]
configuration wiith sevrer browser !!!

**Comment by uBlock-user** [comment]
Can't understand what you're saying, please use proper English.

**Comment by ghost** [comment]
if there are a configuration with web server like apache2 , nginx etc !! 
thank's
