### ISSUE TITLE
Windows Club Ads

### ISSUE THREAD

**Issue by Taurean75** [reek/anti-adblock-killer#2834]
http://www.thewindowsclub.com/metadefender-chrome-extension-scan-files-before-downloading
Mozilla Firefox
Greasemonkey
uBlock
EasyList + AakList

![windows club](https://cloud.githubusercontent.com/assets/8365855/22859215/b4baa790-f089-11e6-95d0-5f7f9e9cd227.jpg)

**Comment by uBlock-user** [comment]
search before you post, already posted more than once.
