### ISSUE TITLE
sherdog ad being shown

### ISSUE THREAD

**Issue by jeepy321** [reek/anti-adblock-killer#2836]
http://www.sherdog.com/fighter/Germaine-de-Randamie-41745
ad being shown
adblock plus
![screen shot 2017-02-11 at 9 25 47 pm](https://cloud.githubusercontent.com/assets/21069588/22859881/d249e444-f0a0-11e6-9f37-8a8f5da08628.png)

**Comment by uBlock-user** [comment]
nothing to do with AAK. I suggest you report ads at easylist forum.
