### ISSUE TITLE
MARCA

### ISSUE THREAD

**Issue by mariomsg1** [reek/anti-adblock-killer#2843]
WEB
www.marca.com

anti adblock activated, and working fine.

**Comment by smed79** [comment]
I cannot reproduce, try to add these filters https://forums.lanik.us/viewtopic.php?p=104300#p104300
for the ads add `||91.116.142.114/iframe` ([viewtopic.php?p=113206#p113206](https://forums.lanik.us/viewtopic.php?p=113206#p113206))

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2756#issuecomment-275525996

**Comment by smed79** [comment]
You know... Breaking the site it's not a solution...
e.g. `http://videos.marca.com/v/0_6fb9ke3i-mercedes-maybach-g-650-landaulet?count=0`

**Comment by mariomsg1** [comment]
Ok, Thanks

**Comment by uBlock-user** [comment]
Broken sites can be mended with an exception filter, so it is a solution, you know and very preferable compared to how you guys `abuse` exception filters for every little thing. Yours is not a solution, period.

For the sake of argument, my filter doesn't break the video, it's broken already by other filter lists, so do some research before playing the blame game and embarrassing yourself every other time.

**Comment by alvr** [comment]
Try to use `||active.cache.el-mundo.net/js/fma1475575200.js$script`. It's working for me.
