### ISSUE TITLE
linkcrypt.ws

### ISSUE THREAD

**Issue by boomann** [reek/anti-adblock-killer#286]
http://linkcrypt.ws/dir/9613f70v1d2f9xt
http://imgbox.com/1XJngO9v
Mozila Firefox
Greasemonkey
uBlock
EasyList + Anti-Adblock Killer | Filters for Adblockers
EasyPrivacy
Adblock Warning Removal List‎
EasyList without element hiding rules
Fanboy’s Enhanced Tracking List
Malware Domain List‎ (malwaredomainlist.com)
Malware domains
Spam404‎ (spam404bl.com)
Fanboy+Easylist-Merged Ultimate List‎ (fanboy.co.nz)
hpHosts’s Ad and tracking servers‎ (hosts-file.net)

**Comment by reek** [comment]
Hi,

Already fixed by Easylist or AAK script
