### ISSUE TITLE
Yellowbridge.com

### ISSUE THREAD

**Issue by dmo580** [reek/anti-adblock-killer#287]
* http://www.yellowbridge.com/chinese/chinese-dictionary.php (Only after you search something in the dictionary)
* http://i.imgur.com/Iflrc2u.png
* Mozilla Firefox 37.0.1
* uBlock 0.9.3.0
* uBlock Filters, uBlock Filters - Privacy, Anti-Adblock Killer | Reek, Easylist, EasyPrivacy, Malware Domain List

**Comment by reek** [comment]
Hi,

No problem detected

**Comment by dmo580** [comment]
I just opened a new Chrome Incognito Window with only uBlock and tried again. You need to search for something (try searching "test" on the English to Chinese box for example). You get a translation, and then after a few seconds, you get redirected to an adblock warning.

Here's the sequence of events as I captured it in my Imgur album: https://imgur.com/a/yH62D

Also, I did include a screencap of my uBlock filters, which were most recently updated right before this test. Please let me know if I'm doing something wrong in selecting too many filters.Sorry! We couldn't save your comment. Please try again.

**Comment by reek** [comment]
Hi,

I have no problem with this configuration
Firefox
Adblock Plus (easylist, easyprivacy, aaklist)
Greasemonkey (aakscript)

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#help

**Comment by dmo580** [comment]
Thank you for your help. I did not know we had to install a Greasmonkey Script. I had thought uBlock's subscription to your lists is sufficient to provide anti-adblock abilities. With the combination of subscription to the list via uBlock AND the Greasmonkey script here I have no issues

Consider the issue resolved.

**Comment by reek** [comment]
Ok
