### ISSUE TITLE
Ivoox

### ISSUE THREAD

**Issue by Macafyc** [reek/anti-adblock-killer#2870]
link: http://www.ivoox.com/escuchar-radio-online_sr_f_1.html
screenshot: http://imgur.com/Ni9Kyov
Mozilla Firefox 49.0.2
uBlock Origin
EasyList

Playing any radio pops up the image and a 20 seconds adblock audio.

Thanks

**Comment by uBlock-user** [comment]
add
````
ivoox.com##script:inject(setTimeout-defuser.js, checkAdBlocker)
ivoox.com###adContainer
ivoox.com##.publi_waiting

**Comment by Macafyc** [comment]
Thanks uBlock-user, but then appears a new button to close:

<a href="http://imgur.com/0Waghjc"><img src="http://i.imgur.com/0Waghjc.png" title="source: imgur.com" /></a>

**Comment by uBlock-user** [comment]
Yes, that button is necessary. If you kill it, the radio won't play, so you will have to close it manually once everytime. It's by-design.
