### ISSUE TITLE
https://einthusan.tv/adblocker/

### ISSUE THREAD

**Issue by freakheart** [reek/anti-adblock-killer#2871]
https://einthusan.tv/adblocker/

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2694

**Comment by Kermittt401** [comment]
add this to your customize ablock in adblock options


@@||einthusan.com^$generichide
@@||einthusan.tv^$generichide
@@||imasdk.googleapis.com^$domain=einthusan.com|einthusan.tv

**Comment by freakheart** [comment]
Thanks Kermittt401.. I have added your filters and now its fine.
