### ISSUE TITLE
blogs.sapib.ca

### ISSUE THREAD

**Issue by Keith94** [reek/anti-adblock-killer#2872]
https://blogs.sapib.ca/apps/mkvcleaver/mkvcleaver-downloads/

The website detects "uBlock Origin" and displays a message:

> Hello There !
> 
> Looks like you're using an Ad Blocker ! You won't be able to download any files here like that.
> 
> Please add this site to the white list of your Ad Blocker and reload the page.
> 
> Thank you.

**Comment by jspenguin2017** [comment]
Update: it is weaker than I thought, just lock `Abd_Detector` to an empty function and done. 
I added it into version 6.12 of my script: https://x01x012013.github.io/AdBlockProtector/

Or this rule would work, but looking at the file name, the owner might change the name regularly...
`||blogs.sapib.ca/apps/wp-content/plugins/agreeable-button/assets/js/e843cd0f.js?ver=4.7.2`

**Comment by Keith94** [comment]
That works, thanks.

**Comment by uBlock-user** [comment]
add - `sapib.ca##script:inject(abort-on-property-read.js, Abd_Detector)`
