### ISSUE TITLE
urlex.org

### ISSUE THREAD

**Issue by Keith94** [reek/anti-adblock-killer#2873]
http://urlex.org/

Expanding a URL gives this error message:

> Urlex.org is a non-profit project expanding millions of URLs per month for free.
> Please disable your ad blocker
> so we can continue collecting a few cents for keeping up our unique and fast service, that is eating up tons of expensive bandwidth.
> Thank you!

**Comment by jspenguin2017** [comment]
Hum, looks like we need a hack for this. 
```JavaScript
a.crashScript("project expanding millions of URLs");
```
This is added to version 6.13 of my script: https://x01x012013.github.io/AdBlockProtector/

&nbsp;

Or you can try this rule: 
`@@||urlex.org^$generichide`

**Comment by Keith94** [comment]
I tried the script, but if you click 'Expand' it shows the same message and redirects back to the original page.

**Comment by uBlock-user** [comment]
just add - `@@||urlex.org^$generichide` and you won't see it anymore.

or add - `urlex.org##script:inject(setTimeout-defuser.js, a(b))`

**Comment by Keith94** [comment]
Got it, thanks.

**Comment by jspenguin2017** [comment]
@uBlock-user 
Hum, for some reason I couldn't block setTimeout() with Userscript fast enough, I'll add the disable generichide rule to my List. 👍
