### ISSUE TITLE
http://gelbooru.com/

### ISSUE THREAD

**Issue by drthundercritic** [reek/anti-adblock-killer#2874]
The search bar removed while uBlock is on.
Even I'm using Anti-Adblock-Killer, the search bar still disables unless I disable uBlock.
Please help.
[http://i.imgur.com/FB1CUU7.png](url)

**Comment by uBlock-user** [comment]
Nothing to do with uBlock

It had a bad cosmetic filter from Easylist which blocks it. Add - `gelbooru.com#@#div[style*="margin-bottom:"]` and report it to Easylist forums - https://forums.lanik.us/

**Comment by drthundercritic** [comment]
I think it's fixed already.
Anyway, thank you.
