### ISSUE TITLE
firstonetv.eu

### ISSUE THREAD

**Issue by azedlal12** [reek/anti-adblock-killer#2879]
Hi
Adblock detected on https://www.firstonetv.eu/Live/France/Discovery-Channel-122

![adblock](https://cloud.githubusercontent.com/assets/24457065/23227116/454fed22-f938-11e6-9e38-97a7f98a5f44.JPG)

**Comment by jspenguin2017** [comment]
~~Try this? 
`@@||firstonetv.eu$xmlhttprequest,domain=www.firstonetv.eu`~~

**Comment by uBlock-user** [comment]
uBO - `firstonetv.eu##script:inject(noeval.js)`

**Comment by uBlock-user** [comment]
Lock the variable called `AdFuckBlock`

uBO - `firstonetv.eu##script:inject(abort-on-property-write.js, AdFuckBlock)`

**Comment by jspenguin2017** [comment]
Lock `blocked` also works... Yea their code is too global.

**Comment by azedlal12** [comment]
Yes , its OK !
Thank you
