### ISSUE TITLE
https://www.firstonetv.eu/

### ISSUE THREAD

**Issue by NessunoIM** [reek/anti-adblock-killer#2894]
Example: https://www.firstonetv.eu/Live/Italy/Top-Calcio-24-49

Firefox 64bit latest version
Greasemonkey
Adblockplus
AakList

![firt](https://cloud.githubusercontent.com/assets/19640640/23345254/57a0cfcc-fc8b-11e6-8fc4-ebe354a7c739.png)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2879

Remove AAK and install Adblock Protector Script

**Comment by NessunoIM** [comment]
What are the differences between AAK and APS?

**Comment by uBlock-user** [comment]
AAK is no longer updated and outdated, reek abandoned the project of his own volition. While APS is actively developed and the dev responds on time, not to mention the script is heavily optimised.
