### ISSUE TITLE
vipleague.se

### ISSUE THREAD

**Issue by siuside** [reek/anti-adblock-killer#290]
Doesn't seem to work on this streaming site.

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

And making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/297

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by andrew0** [comment]
Is there any way to update this to add strikeout.co? I believe it's the same thing as vipleague.se, just a different domain.

**Comment by reek** [comment]
Hi,

indeed, it is the same system, too bad you have it report it now, because it's been a few hours since I released a new version, you need to wait a few days before I made a new update, if you have other domains using the same system tell me.
