### ISSUE TITLE
last.fm

### ISSUE THREAD

**Issue by edelstone** [reek/anti-adblock-killer#2901]
http://i.imgur.com/m4XLFsI.png
Google Chrome
N/A
AdBlock
EasyList + Adblock Warning Removal list + Acceptable Ads + AakList

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2213#issuecomment-256689879

**Comment by pedrocleis** [comment]
@uBlock-user it's a different issue

EDIT: https://puu.sh/wwwQg/6255b03cff.png

**Comment by edelstone** [comment]
Not an issue anymore.
