### ISSUE TITLE
fredcasters.com

### ISSUE THREAD

**Issue by warthog3** [reek/anti-adblock-killer#2905]
https://www.fredcasters.com/song/jimmy-eat-world-last-christmas-studio-version-itunes-mp3-torrent/
Google Chrome
Tampermonkey
uBlock Origin
Easylist

http://i.imgur.com/l6OzDtk.png

**Comment by uBlock-user** [comment]
add - `fredcasters.com##script:inject(setTimeout-defuser.js, an_message_display)`

or

add - `/wp-content/uploads/*.js`

**Comment by warthog3** [comment]
Thanks
