### ISSUE TITLE
animmex.net

### ISSUE THREAD

**Issue by dXtrmn8r** [reek/anti-adblock-killer#2910]
https://www.animmex.com/video/1233/top-gear-uk-s06e06
http://i.imgur.com/RzQDtb1.jpg
Chrome/Opera
AdBlock
AAK + EasyList + solution [here](https://github.com/reek/anti-adblock-killer/issues/2573)

Uses BlockAdBlock

edit: Solution [here](https://github.com/reek/anti-adblock-killer/issues/2573) doesn't work

**Comment by uBlock-user** [comment]
Already patched by Easylist, force update all your filters.

**Comment by dXtrmn8r** [comment]
Not working

**Comment by uBlock-user** [comment]
Remove AAK, works fine here.

**Comment by dXtrmn8r** [comment]
Still not working

http://i.imgur.com/mnhwhu5.jpg
http://i.imgur.com/zUUot16.jpg

**Comment by uBlock-user** [comment]
AdBlock Protector Script will only work on uBlock Origin, I suggest you switch to uBO and remove Adblock because of its limitations.

**Comment by dXtrmn8r** [comment]
Switched to uBO on Opera with AAK list and script off.
[After using these settings](http://i.imgur.com/Q5GlPww.jpg), [site doesn't load the video at all](http://i.imgur.com/Z2dO95u.jpg)

**Comment by uBlock-user** [comment]
add - 
````
animmex.*##script:inject(bab-defuser.js)
@@||4553t5pugtt1qslvsnmpc0tpfz5fo.xyz^$inline-script
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(bab-defuser.js)
````
and and make sure all your filters are upto date on uBO.

**Comment by dXtrmn8r** [comment]
All working. Thank you!

**Comment by dXtrmn8r** [comment]
above filters don't work for animmex.tv: https://www.animmex.tv/video/1387/top-gear-uk-s18e01

Can you patch them?

**Comment by uBlock-user** [comment]
They work fine for all animmex websites, that's why I used `animmex.*` instead of `animmex.net`

![](https://i.gyazo.com/8aed3ca5254518096b75d2553090647f.png)

Something's wrong on your end, you will have investigate that yourself.

**Comment by dXtrmn8r** [comment]
Not for [this one](http://i.imgur.com/hVkkfRV.jpg)

Edit: this one is a hit and miss. Tried refreshing a few times
Edit 2: Also, what the hell did they add on that blank space above the video?

**Comment by uBlock-user** [comment]
Remove all extensions except uBO and try again.

**Comment by dXtrmn8r** [comment]
Done. Also cleared cache, and working

Edit: If you saw the gap between video and title though (whitespace for ads). uBO blocks this box on *.com but not on *.tv. Targeting this element prompts BlockAdBlock

**Comment by uBlock-user** [comment]
> Targeting this element prompts BlockAdBlock

Not on my end. add - `animmex.*###M148617ScriptRootC75329`

BlockAdBlock cannot be prompted by that element because `bab-defuser.js` kills it, somehow the filters I gave you are not being applied on that domain for some reason I don't know.

I'm using Chromium though.
