### ISSUE TITLE
gamecopyworld.eu

### ISSUE THREAD

**Issue by Keith94** [reek/anti-adblock-killer#2911]
http://www.gamecopyworld.eu/games/pc_dead_space_3.shtml#Dead%20Space%203:%20Awakened%20DLC%20v20170227%20[MULTI5]%20Fixed%20Files

At this link click on the blue save icon next to "File Archive [4.0 MB] - Origin Version". Then click "MIRROR 01".

![firefox_2017-03-03_11-29-32](https://cloud.githubusercontent.com/assets/5490615/23566119/643f21b6-0005-11e7-84d4-8aa85a92beea.png)

**Comment by uBlock-user** [comment]
Install AdBlock Protector Script and remove AAK, it will bypass adf.ly links.

@X01X012013 Add `gamecopyworld.click` to the domains list in the script.

**Comment by jspenguin2017** [comment]
Test link: http://rd1.gamecopyworld.click/OrPg

@uBlock-user 
This domain is added to Adfly domain list.
