### ISSUE TITLE
Blockadblock

### ISSUE THREAD

**Issue by andrewxyxyxy** [reek/anti-adblock-killer#2912]
https://blockadblock.com/ and http://arenavision.in
uBlock Origin
EasyList+AakList

![av](https://cloud.githubusercontent.com/assets/26189057/23581079/03af44d4-010e-11e7-912e-78b3d35de26a.png)

![bladbl](https://cloud.githubusercontent.com/assets/26189057/23581080/03df7d66-010e-11e7-9c27-631cdd0f1bb1.png)

**Comment by andrewxyxyxy** [comment]
now it works!

**Comment by uBlock-user** [comment]
Cannot reproduce.

just incase it happens again - `blockadblock.com,arenavision.in##script:inject(bab-defuser.js)`

**Comment by anarki999** [comment]
Add these 4 lines to your uBlock myfilter to fix it =D

```
||*blockadblock*.*/*$inline-script
||*.*/*blockadblock*/*$inline-script
||*.*/*blockadblock*/*
||*blockadblock*.*/*
||*.*/*/blockadblock.js$script
```
