### ISSUE TITLE
hollaforums.com

### ISSUE THREAD

**Issue by XeidiDent** [reek/anti-adblock-killer#2914]
http://hollaforums.com/thread/11976582/video-games/squenix-looking-for-drm-stronger-than-denuvo.html
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList
![antiadblocker](https://cloud.githubusercontent.com/assets/23062575/23588062/6be8f76a-0196-11e7-8839-7fc2b66e8f6c.jpg)

**Comment by uBlock-user** [comment]
add - `@@||hollaforums.com^$elemhide`

**Comment by XeidiDent** [comment]
Thanks. Solved.
