### ISSUE TITLE
Problem with 15min.lt

### ISSUE THREAD

**Issue by triumfas** [reek/anti-adblock-killer#2915]
Opening an article and reading it - article disappears. I think it's new "feature" by 15min.lt.

**Comment by uBlock-user** [comment]
cannot reproduce.

**Comment by triumfas** [comment]
Open any bigger article and slowly scroll down till the end of it. It should disappear. I can reproduce it on multiple computers with google chrome.

**Comment by uBlock-user** [comment]
Already did, and no it doesn't happen. It's a filter issue on your end. Force update all filters and if that doesn't work then add - `||$third-party,script,domain=15min.lt`

**Comment by triumfas** [comment]
Had to reinstall ublock origin. After that articles does not disappear. Thanks!
