### ISSUE TITLE
Adblock not working with Animmex

### ISSUE THREAD

**Issue by SuitYourself** [reek/anti-adblock-killer#2919]
Just letting you know the anti adblocker blocker is failing a lot with this site: https://www.animmex.com/

In case you didn't already know. :)

**Comment by SuitYourself** [comment]
https://blockadblock.com/#12514 is the creator of the block adblock, so that's a good site to test your anti blocker on. :)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2910#issuecomment-283957126

**Comment by uBlock-user** [comment]
Already patched by Easylist. Make a habit of force updating your filters every 24 hours.

**Comment by SuitYourself** [comment]
I do. I have updated. It still does not work. Patch has failed then.

I even just forced an update right now, in case I missed it, and still not working.

**Comment by uBlock-user** [comment]
Something's wrong on your end. You will have to investigate that by yourself. By the way those filters I posted are for uBO only. If you're using generic adblocker, post here - http://forums.lanik.us/

**Comment by SuitYourself** [comment]
Um.. ok then.... first time I've ever had an issue.

Using latest chrome browser Version 58.0.3000.4
Using Tapermonkey 4.2.7 with latest Anti-Adblock Killer | Reek 10.0
Using Adblock Plus with two filters:

×   Enabled Adblock Warning Removal List Last updated at 8:03:56 PM today
×   Enabled EasyList Last updated at 8:03:58 PM today

Removed EasyList and re-added EasyList again.

Still same results. 

I doubt highly it is my fault, but I have re-installed absolutely everything, with everything updated and still the same results.

But thank you for your prompt reply. Appreciated.

**Comment by uBlock-user** [comment]
Use uBO, ABP is useless against BlockAdBlock. Can't help you any further if you're not on uBO, sorry.

**Comment by SuitYourself** [comment]
uBO, ok I'll switch it over. I thought it was the same blocker, my bad.

This is one of the later links which is blocking, https://www.animmex.tv/video/27975/trolls-2016 in case you want to test on your end. 

Going to grab uBo now. Cheers mate :)

**Comment by SuitYourself** [comment]
Is this the one you mean: https://www.ublock.org/
Ah nope, there's an origin version. uBlock₀ Grabbing that one now.

**Comment by uBlock-user** [comment]
This one - https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en

Once installed force update all the filters and then add the filters I posted here - https://github.com/reek/anti-adblock-killer/issues/2910#issuecomment-283957126

**Comment by SuitYourself** [comment]
Ok, that's the one I got now. Updated everything. Uninstalled Adblock, and just using uBO now.

![image1](https://cloud.githubusercontent.com/assets/25052021/23652948/70b99876-0376-11e7-9b4e-f61a68e4944a.png) Getting this now

**Comment by uBlock-user** [comment]
add -
 ````
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz##script:inject(abort-on-property-read.js, _gunggo)
4553t5pugtt1qslvsnmpc0tpfz5fo.xyz###babasbmsgx
````

**Comment by SuitYourself** [comment]
That did the trick!

You're a legend. Thank you so much.
Do you have a place I can donate to say thanks. :)

**Comment by uBlock-user** [comment]
add this too - `animmex.*###M148617ScriptRootC75329`

**Comment by SuitYourself** [comment]
Once again, thank you! 
I did not even know about this uBO. Another convert here!

**Comment by uBlock-user** [comment]
add this also - `animmex.*##a[href^="https://forum.animmex.com/viewtopic.php"]`
