### ISSUE TITLE
vg.no & e24.no

### ISSUE THREAD

**Issue by simonkaspersen** [reek/anti-adblock-killer#292]
Link page contains anti-adblock
http://www.vg.no/
http://e24.no/

One screenshot
http://imgur.com/aN6KdwU

Your browser
Google Chrome on OS X

Your script manager
Tampermonkey

Your adblocker
Adblock

Your filterlists
Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by kristofferR** [comment]
Could you also enable this for e24.no? They use the same anti-adblock code as vg.no does, so it should be very easy.

**Comment by reek** [comment]
Hi,

What is your config ?

**Comment by reek** [comment]
I have no message on vg.no. but e24.no yes

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by simonkaspersen** [comment]
It seems that the banner is still present in Chrome og OS X. Can it be a bug or is it something I have done wrong? Have loaded inn all scripts again

**Comment by reek** [comment]
Try this beta version:
https://gist.github.com/reek/dc234ea9687056bd99fe/raw/d5c4d95635b9f29f6ac8170fd3bc51091dc8c7d3/aakdev.user.js

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by aleksanderwaagr** [comment]
There is still a white container at the top where the ad/anti-ad was. I'm not sure if the responsibility of removing it is on Adblock or AAK, but in case it is AAK, the fix is to add 
```javascript
Aak.removeElement('#ad-wallpaperTop');
```
Btw I love this project and just donated a small amount to show my support.

**Comment by reek** [comment]
HI,

Normally, one would add adblock rules, but as a EasyList allow all hidden elements, we will use a rule AakScript to remove these items.

PS: Thanks for fix and donation :+1: 

Regards
Reek

**Comment by reek** [comment]
@aleksanderwaagr 
I think we can do even more simple.
I tried on vg.no and e24.no and it seems ok

<pre>
    vg_e24_no : {
      // issue: https://github.com/reek/anti-adblock-killer/issues/292
      host : ['vg.no', 'e24.no'],
      onStart : function () {
	    // Add this rule, because EasyList allow all hidden elements.
        Aak.addStyle(".ad { display: none; }");
      },
    },
</pre>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
