### ISSUE TITLE
Can't Open Hotmail Outlook attachments 

### ISSUE THREAD

**Issue by brettstoner** [reek/anti-adblock-killer#2929]
Windows` 7, Chrome 56.0.2924.87, TamperMonkey 4.2.7, AdBlock Plus, Easy list and AAK list.

When anti-adblock killer script is turned on it prevents outlook attachments from opening in hotmail. 

![error](https://cloud.githubusercontent.com/assets/26289806/23732180/968ddf98-043f-11e7-8c21-b442eaeb2a8f.jpg)

**Comment by uBlock-user** [comment]
Remove the script then, it's buggy, outdated and no longer in development.

**Comment by brettstoner** [comment]
Ok thank you.
