### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by marek45** [reek/anti-adblock-killer#293]
http://player.pl/seriale-online/szpital-odcinki,1171/odcinek-225,S00E225,30059.html
https://www.dropbox.com/s/p7v82n8e4978boy/adblock.png?dl=0
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers + http://www.certyficate.it/adblock/adblock.txt

I think that is problem with this:
http://tvn.adocean.pl/ad.xml?aocodetype=1/predur=240/postdur=300/mid1dur=240/mid2dur=240/mid3dur=240/overdur=2000/key=wypadki,choroby,lekarze,sor,pacjenci,izba_przyjec,serial_medyczny,przypadki_medyczne/tvn_vod_trailer=0/tvn_player_website=new/midcnt=2/tvn_vod_serie=szpital/tvn_vod_season=0/tvn_vod_prepremiere=0/tvn_vod_episode=225/tvn_vod_wonid=14_400_18010_0225/tvn_vod_category=100,101/tvn_vod_traffic_category=kobieta/tvn_collection=69,77,89,130/tvn_content_source=tvn/tvn_price=no/tvn_zone=tvn/tvn_player_type=kinowy/id=zeOb3_LRSL3Bnfg15ylC7tH60MVPXMMAN8DTNtpnaE3.V7/tvn_vod_embed=0/tvn_terminal=24/tvn_page=seriale_online_szpital_odcinki_1171_odcinek_225_s00e225_30059_html/tvn_login=no/tvn_driver=1

this is whitelist. Maciek

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by marek45** [comment]
The same problem is in easy list... but thank you for your help.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/192

**Comment by reek** [comment]
I have no solution, you must allow video ads

**Comment by krzysztofhanzel** [comment]
Still nothing?

**Comment by reek** [comment]
No
![capture2](https://cloud.githubusercontent.com/assets/3474011/7184995/8b15a926-e460-11e4-8de7-ac4cd8f347f7.PNG)

**Comment by marek45** [comment]
Tray use this proxy servers. http://www.proxynova.com/proxy-server-list/country-pl/

**Comment by marek45** [comment]
Hello. Can we help you?

**Comment by reek** [comment]
Hi,

Yes, try to find a solution by enabling or disabling certain rules in order to find a solution

**Comment by marek45** [comment]
I try to do something, but It's hard for my.
If I use ony this filter http://www.certyficate.it/adblock/adblock.txt
and disable this: 
pl##.tvn-advertisement
||adocean.pl^$domain=ekstraklasa.tv|itvn.pl|player.pl|ttv.pl|tvn.pl|tvn24.pl|tvn24bis.pl|tvn7.pl|tvnplayer.pl|tvnstyle.pl|tvnturbo.pl
*.adocean.pl*
I see ads on video but no warning about adblock.

**Comment by reek** [comment]
sometimes it is the only solution :disappointed_relieved:
