### ISSUE TITLE
video.corriere.it

### ISSUE THREAD

**Issue by tomdan95** [reek/anti-adblock-killer#2930]
at the beginning of the last week; video.corriere.it the video site of a well know italian newspaper (corriere della sera) has start to block all the video for adblock users; no warning message the video just don't start. a screenshot for exaple:
<img width="1278" alt="schermata 2017-03-09 alle 15 33 53" src="https://cloud.githubusercontent.com/assets/23356063/23754819/a7b4c274-04de-11e7-9c64-573e527f4c76.png">

**Comment by uBlock-user** [comment]
or it's just broken ? Report to the webmaster and see what he has to say about it.

**Comment by tomdan95** [comment]
@uBlock-user no, with adblock turned off it works fine and the news paper director has already said that it is something done on purpose

**Comment by jspenguin2017** [comment]
Hum... works fine for me...
![image](https://cloud.githubusercontent.com/assets/7283682/23764123/99ebf7f4-04b9-11e7-92d9-e23749f5398b.png)

**Comment by tomdan95** [comment]
@X01X012013 now i have tried with different browser (firefox) and it works; with chrome sill not working (with adb on). probably there some list that me and my friend have that dosen't work.
i have check the article that my friend sowed to me and was for another news paper repubblica.it
sinice the issues was affecting two people  i thinked that was a global issues, so i have reported it.
but i guess i was wrong. sorry for the time. thanks for the help
