### ISSUE TITLE
www.androidcentral.com

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#2932]
"It looks like you're using an adblocker.

Adblockers make us sad. We use ads to keep our content happy and free. Please support us by whitelisting us. You can report badly behaved ads by clicking/tapping the nearby 'Advertisement' text."

**Comment by uBlock-user** [comment]
Disable cosmetic filtering on ABP

uBO - `androidcentral.com##script:inject(setTimeout-defuser.js, checkBlocked)`

**Comment by purevertigo** [comment]
How do I disable cosmetic filtering?

**Comment by purevertigo** [comment]
But that still doesn't tell me how to disable cosmetic filtering.

**Comment by purevertigo** [comment]
OK. Since UBO seems to be getting more love from people I am going to attempt to switch from ABP. Hopefully it proves a better decision. 

FYI the fix above doesn't work with uBO either.

**Comment by purevertigo** [comment]
*UPDATE*

Since installing uBO I have tweaked settings and website is now blocked-unblocked.

thanks for all the help with this users.
