### ISSUE TITLE
http://www.windowscentral.com/

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#2936]
It looks like you're using an adblocker.

Adblockers make us sad. We use ads to keep our content happy and free. Please support us by whitelisting us. You can report badly behaved ads by clicking/tapping the nearby 'Advertisement' text.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2935#issuecomment-285855341

**Comment by purevertigo** [comment]
Doesn't tell me how to do that though.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2935#issuecomment-285864553

**Comment by purevertigo** [comment]
Thanks anyways but nothing mentioned in the documentation.

Hopefully someone else can help with this matter.

**Comment by uBlock-user** [comment]
try - `@@||$elemhide,domain=windowscentral.com|androidcentral.com|imore.com`

**Comment by purevertigo** [comment]
OK. Since UBO seems to be getting more love from people I am going to attempt to switch from ABP. Hopefully it proves a better decision. 

FYI the fix above doesn't work with uBO either.

**Comment by purevertigo** [comment]
*UPDATE*

Since installing uBO I have tweaked settings and website is now blocked-unblocked.

thanks for all the help with this users.
