### ISSUE TITLE
chip.de

### ISSUE THREAD

**Issue by CrescentEclipse** [reek/anti-adblock-killer#2937]
http://www.chip.de/news/FritzOS-6.83-fuer-die-FritzBox-7490-Das-bringt-das-neue-Update_110425709.html

Mozilla Firefox
Greasemonkey
Adblock Plus
Adblock Warning Removal List + EasyList Germany + EasyList + AakList

If you disable all scripts from chip.de the site does not show this page below:

![chip de anti-adblock](https://cloud.githubusercontent.com/assets/25794343/23823343/a5ed4460-0660-11e7-9c13-6bae7a6c94b0.png)

**Comment by uBlock-user** [comment]
add - `||contributor.google.com/scripts/`

**Comment by uBlock-user** [comment]
@X01X012013 same case as `comicbook.com`

**Comment by CrescentEclipse** [comment]
Great, it works! Thank you :)
Hm, is there a way to block the ads in the videos itself, too?

**Comment by uBlock-user** [comment]
report any unblocked ads on Easylist forum - https://forums.lanik.us/viewforum.php?f=62

**Comment by CrescentEclipse** [comment]
OKay, I will. Thank you again.

**Comment by jspenguin2017** [comment]
@uBlock-user Yep, same code. Added to Script 6.91.
