### ISSUE TITLE
github.com (anti-adblock-killer)

### ISSUE THREAD

**Issue by marek45** [reek/anti-adblock-killer#294]
https://github.com/reek/anti-adblock-killer/issues/293
https://www.dropbox.com/s/8o3y9tk183khnnr/adblock2.png?dl=0
Mozila Firefox
Greasemonkey
Ublock
EasyList + Anti-Adblock Killer | Filters for Adblockers + http://www.certyficate.it/adblock/adblock.txt

I can't update title of my issue.

**Comment by reek** [comment]
Hi,

Thank you, I forgot to add a rule to exclude aak on gh.

See you
Reek

**Comment by reek** [comment]
Added !
