### ISSUE TITLE
Los Angeles Times

### ISSUE THREAD

**Issue by giampi75** [reek/anti-adblock-killer#2944]
![lat](https://cloud.githubusercontent.com/assets/17108055/23831199/8e245bcc-071c-11e7-90ae-e23d5a8ac939.jpg)

**Comment by uBlock-user** [comment]
Already patched, force update your filters.

**Comment by giampi75** [comment]
I did force update, but nothing change Fierfox 52.0 Windows 10

**Comment by Astrokat** [comment]
I've been getting this periodically in Chrome for months. It's what first triggered me to look for extensions for AdBlock Plus and found this site. The LA Times is unreadable without an ad blocker, so many popups and autoplay videos, and pages take forever to load.

I have the latest version (7:16am today). Are there any logs or anything I can post here, to help?

**Comment by Astrokat** [comment]
Never mind, just found the fix here: https://github.com/reek/anti-adblock-killer/issues/2513

**Comment by giampi75** [comment]
Yes it works, Astrokat. Thanks a lot
