### ISSUE TITLE
dirtstyle.tv

### ISSUE THREAD

**Issue by bugreport0** [reek/anti-adblock-killer#295]
http://dirtstyle.tv/stream/1219339/Sexy-Latina-Babe-Twerking-In-Pink-Thong
https://i.imgur.com/zVpRXQ2.jpg
Firefox
Adblock Plus
Fanboy+Easylist-Merged Ultimate List, Anti adblock killer

Rules like these make the videos watchable
||dirtstyle.tv/img/adblock.jpg
dirtstyle.tv##.lightbox

**Comment by reek** [comment]
Hi,

Thanks for rules and butt dance, added :+1:
