### ISSUE TITLE
repubblica.it

### ISSUE THREAD

**Issue by dexoro** [reek/anti-adblock-killer#2953]
as shown, repubblica.it (video section) is preventing the video from loading.

ublock origin 1.11.4 (but also with adbp is the same)
tampermonkey + anti adblock killer reek
aaklist enable in ublock.

test url   
http://video.repubblica.it/edizione/roma/roma-il-cinghiale-corre-a-perdifiato-su-via-baldo-degli-ubaldi/269163/269597?ref=RHPPBT-BS-I0-C4-P5-S1.4-T1

![immagine](https://cloud.githubusercontent.com/assets/26430469/23941151/098e0680-0968-11e7-99ac-165badaf6b95.png)

**Comment by uBlock-user** [comment]
Nuking `wt_adblock` works perfectly.

Add - `repubblica.it##script:inject(abort-on-property-write.js, wt_adblock)`

**Comment by dexoro** [comment]
working perfectly.
thank you

**Comment by GaHub** [comment]
> Nuking `wt_adblock` works perfectly.
> 
> Add - `repubblica.it##script:inject(abort-on-property-write.js, wt_adblock)`

Hi, where do I add this line exactly? I tried both MyFilters and MyRules without luck. Thank you
