### ISSUE TITLE
slideplayer.org

### ISSUE THREAD

**Issue by alexander255** [reek/anti-adblock-killer#296]
Hi there Reek :-)

Example URL (wait 5 seconds for it to appear): http://slideplayer.org/slide/2/
Anti-AdBlock script: http://pastebin.com/nxb8jtr8

You might need to force-refresh (Ctrl+F5) for the changes from the script to take effect...

Have a nice day!

**Comment by reek** [comment]
Thanks Alex :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by alexander255** [comment]
Hi there, thanks for merging!

I have an update of that script that circumvents the "share to download" code of this page and grants direct access to the downloadable file. Is this still in the scope of AAK?
Script is available for review here: http://pastebin.com/bApPxTaT

PS: The script was based on this BTW: http://pastebin.com/SLujpd7U ;-)

**Comment by reek** [comment]
Hi Alex,

No, the goal is to remove aah anti adblock and advertisements, You should post it on greasefork it surely will help more users.

See you
Reek

**Comment by reek** [comment]
Re

Could you help me find a solution for the site playtv.fr.

Thanks
Reek

**Comment by alexander255** [comment]
Hi there!

ad 1)
The point is that, if a site forces me to log in with/share on some "social" site in order access some content, I wouldn't go looking on some userscript site for a workaround, I would either bite the bullet (=fake profile) or just click on the little X next to the page title in the tab bar ;-) .
Adding one such script to fix *most* of these sites is definitely OK, but having to do it *every time*...? That basically the reason there is ONE Anti-AdBlock-Killer script killer instead of ~150 (one for each site), right?
Since the download feature is pretty much useless without this (just like most AntiAdblocking pages are without AAK), I definitely think that this is something that is in AAK's scope!

ad 2)
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide ;-)
...
No, seriously: Hasn't bug #27 been closed for a while? Whenever I go to that page (even in my testbrowser without any protection), I always end up with this:
![Screenshot](https://cloud.githubusercontent.com/assets/246386/7123500/b958e860-e222-11e4-8766-760de688a129.png)
Does that site require flash by any chance? At what point is the error shown?

With best regards,
Alexander
