### ISSUE TITLE
http://www.ps4news.com/

### ISSUE THREAD

**Issue by luizfm99** [reek/anti-adblock-killer#2966]
http://i.imgur.com/nvLP4NE.jpg
Mozilla Firefox
uBlock Origin
EasyList + AakList

**Comment by uBlock-user** [comment]
@X01X012013 Need your help here, this one's using CSS

**Comment by jspenguin2017** [comment]
Looks like BlockAdBlock. `a.filter("eval");`

**Comment by uBlock-user** [comment]
In addition to BlockAdBlock, there's another CSS block, open the source page and see for yourself. I have already patched the BAB and but the CSS one needs to be patched too.

**Comment by okiehsch** [comment]
I use that site sometimes
`ps4news.com##script:inject(noeval.js)`
`ps4news.com##body > *[id^="blockblock"]:style(visibility: visible !important; display: block !important;)`
`ps4news.com##table[id^='blockblock']`
works for me.

**Comment by uBlock-user** [comment]
Yep the last two filters were the one that kill it nicely! Thanks.

**Comment by jspenguin2017** [comment]
@okiehsch Awesome. Thanks.
