### ISSUE TITLE
hdbox.ws

### ISSUE THREAD

**Issue by azedlal12** [reek/anti-adblock-killer#2972]
Hi
adblock detected on https://hdbox.ws/fr/news/43-ip-tv-kanaly.html
![adb](https://cloud.githubusercontent.com/assets/24457065/24052008/4c8638ae-0b34-11e7-843a-8e0964d23815.JPG)

**Comment by uBlock-user** [comment]
add - `@@||hdbox.ws^$generichide`

**Comment by Macafyc** [comment]
µBO add: `hdbox.ws##script:inject(setTimeout-defuser)`

**Comment by azedlal12** [comment]
Thank you
it works
