### ISSUE TITLE
New Huffington Post and AOL anti-adblock

### ISSUE THREAD

**Issue by wkdpower** [reek/anti-adblock-killer#2975]
Both Huff Post and AOL have inserted similar adblocking code that isn't currently being blocked, and isn't easily added using cosmetic filters due to element tags being randomly generated. 

Using Firefox 52, UBlock Origin, Reek Anti-Adblock Killer filter list.

http://www.huffingtonpost.co.uk/
![HuffPost](http://i.imgur.com/ZwejjlC.jpg)

http://www.aol.co.uk/
![AOL](http://i.imgur.com/QhzIJgg.jpg)

**Comment by uBlock-user** [comment]
`aol.*,huffingtonpost.*##script:inject(abort-on-property-write.js, _sp_)`

**Comment by wkdpower** [comment]
Awesome, thanks.
