### ISSUE TITLE
shink.in

### ISSUE THREAD

**Issue by ahmedtds** [reek/anti-adblock-killer#3004]
example url: http://shink.in/mXBdV

Firefox and ublock origin last versions. Filters are up-to-date (default filters + reek filter)
greasemonkey and anti-adblock-killer up-to-date
only anti-adblock-killer and ublock origin active (no adsbypasser or another adblocker)

**Comment by uBlock-user** [comment]
Patched by Easylist.

**Comment by ahmedtds** [comment]
I still see "Please disable Adblock" text. Everything is up-to-date as I said.

**Comment by uBlock-user** [comment]
Force update your filters and remove all cache and site data for that website.

**Comment by ahmedtds** [comment]
I did everything you said. Still same.

**Comment by uBlock-user** [comment]
Add `@@||shink.in^$generichide` in your custom filter/my filters.
