### ISSUE TITLE
animesync

### ISSUE THREAD

**Issue by SvSlazer18** [reek/anti-adblock-killer#3007]
**Domain:**
`www.animesync.tk`

**Image:**
`http://imgur.com/a/mfrIl`

**Lists:**
_AakList_
_EasyList_

**Browser:**
_Firefox_

**Adblocker:**
_Adblock Plus (EN)_

**Handler:**
_GreaseMonkey_

**Comment by uBlock-user** [comment]
add - `animesync.tk##.modal-adblock`

**Comment by SvSlazer18** [comment]
Works. Thanks.
