### ISSUE TITLE
gamezhero.com

### ISSUE THREAD

**Issue by agfgelee** [reek/anti-adblock-killer#3008]
Google Chrome
ublock origin
default filters + reek filter
example URL: http://www.gamezhero.com/games/seaboom

I can't play the game  because of Adblock message.

**Comment by uBlock-user** [comment]
@X01X012013 `a.readOnly("ads", function ( ) { });` removes the anti adblock but the game doesn't intialize. Does it require flash player to be installed ?

**Comment by jspenguin2017** [comment]
OK I'll have a look.

**Comment by uBlock-user** [comment]
Btw can you kill the ad timer ? That's an annoyance too.

**Comment by jspenguin2017** [comment]
The solution for the block screen is added to Script. The 30 seconds countdown needs to be fixed. And the game does require Flash.

**Comment by uBlock-user** [comment]
Yes, indeed. except for the countdown everything is in order, thanks!

**Comment by uBlock-user** [comment]
@X01X012013 The patch for killing the `adbull.me` countdown also works for this domain. I suggest you use the same.

```javascript
if (a.domCmp(["gamezhero.com"])) {
    a.readOnly("ads", true);
    const _setInterval = a.win.setInterval;
    a.win.setInterval = function (func) {
        return _setInterval(func, 10);
    };
}
```

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks for the report, I'll have a look. If this `setInterval`patch works for many domains, I might want to properly implement it to the Core library.

**Comment by uBlock-user** [comment]
So far it has, so if you can make it generic without it causing any performance downside, that will be great.

**Comment by jspenguin2017** [comment]
@uBlock-user Compare to the inefficiency from boosting `setInterval`, the performance hit from making it part of the Core library is negligible.

**Comment by jspenguin2017** [comment]
The fix is added to Script, you'll still see the countdown, but it ticks 50 times faster. 
With the library function, this is actually more efficient, since it only boost related code.

**Comment by agfgelee** [comment]
Thank you!

**Comment by uBlock-user** [comment]
You will need to use AdBlockProtector Script and not AAK, remove AAK.

**Comment by agfgelee** [comment]
Sorry, but I noticed faster countdown doesn't work anymore.

Google Chrome
uBlock Origin
uBlock Protector (Extension and List)
EasyList + Adblock Warning Removal List​
URL Flash not needed, just in case: http://www.gamezhero.com/games/poing

**Comment by jspenguin2017** [comment]
I'll investigate when I got time.

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by agfgelee** [comment]
Thanks!
