### ISSUE TITLE
vipleague.tv

### ISSUE THREAD

**Issue by marketfire** [reek/anti-adblock-killer#301]
http://jp.vipleague.tv/
http://i.imgur.com/rsl0HT8.png
google chrome
Tampermonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

Additional Info:
using Release 7.9 (April 11, 2015)
vipleague.se and vipleague.me are redirected to vipleague.tv.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Install this beta version to test
https://gist.github.com/reek/dc234ea9687056bd99fe/raw/cd94f04e682f643cdb79b6d3c6942a168cfe883f/aakdev.user.js

See you
Reek

**Comment by marketfire** [comment]
thanks reek!

**Comment by Sally0808** [comment]
This no longer works.  Any new work arounds?
