### ISSUE TITLE
http://www.imore.com

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#3013]
"It looks like you're using an adblocker."

**Comment by uBlock-user** [comment]
Already patched!!

**Comment by uBlock-user** [comment]
add

```
||$third-party,domain=imore.com
@@||$stylesheet,image,font,media,domain=imore.com
@@||youtube.com/embed^$third-party
@@||ytimg.com/yts^$third-party
@@||googlevideo.com^
```

**Comment by purevertigo** [comment]
tried to update but 'update now' is greyed out. why is this?

**Comment by uBlock-user** [comment]
Add those filters, I realised that the blog is now adding third party crapware for detection. Forcing update won't help this time.

**Comment by purevertigo** [comment]
thanks!
