### ISSUE TITLE
http://imprezzer.com

### ISSUE THREAD

**Issue by ve3** [reek/anti-adblock-killer#3018]
This website (http://manager.co.th) is using imprezzer.com ad and this script ([http://imprezzer.com/js/imprezzer2.js](http://imprezzer.com/js/imprezzer2.js)) contain something like anti-ad blocker.

For example: [http://manager.co.th/Around/ViewNews.aspx?NewsID=9600000031527](http://manager.co.th/Around/ViewNews.aspx?NewsID=9600000031527) 
If you open this page with ad block turn on it will becomes white page after page loaded.

Please add **imprezzer.com** and **ads.imprezzer.com** to the list.

Thank you.

**Comment by uBlock-user** [comment]
add - `||$third-party,script,domain=manager.co.th`

**Comment by ve3** [comment]
Huh?? I'm not sure but the anti-ad blocker domain is imprezzer.com and ads.imprezzer.com NOT manager.co.th

**Comment by uBlock-user** [comment]
That filter is futureproofing against all third-party anti adblock shit, not just `imprezzer.com`

**Comment by uBlock-user** [comment]
Also add - `@@||$stylesheet,image,domain=manager.co.th` so to unbreak any breakage caused by blocking all third-party shit.

**Comment by ve3** [comment]
This breaks all 3rd party websites such as instagram or youtube embedded

**Comment by uBlock-user** [comment]
Ah, nevermind then, remove those filters and add `||imprezzer.com^$domain=manager.co.th`
