### ISSUE TITLE
kissanime.com

### ISSUE THREAD

**Issue by asf95** [reek/anti-adblock-killer#302]
http://kissanime.com/Anime/Zetsuen-no-Tempest/Episode-01?id=42
http://i.imgur.com/UJKZEUg.png
Google Chrome
Tampermonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
HI,

Tested with Firefox and Chrome and that's ok.

**Comment by asf95** [comment]
I am so dumb. 

sry i forgot to remove exception from javascript. 

Now it works fine. Thx for ur effort. 

Really appreciate u guy's work, absolutely love these scripts ^^ :+1:

**Comment by reek** [comment]
Ok, thanks :blush:
