### ISSUE TITLE
flashx.tv adblock detection

### ISSUE THREAD

**Issue by LS4WT** [reek/anti-adblock-killer#3025]
Anti Adblock Killer doesn't seem to be reliable bypassing the flashx.tv anti adblock.

It worked once, but since then it doesn't work anymore. 
Running latest Google Chrome with
latest uBlock (with EasyList, AAK Filters and the filters below:)
`||flashx.tv/js/code.js`
`flashx.tv##script:inject(abort-on-property-write.js, jQuery.adblock)`
`||$third-party,popup,popunder,domain=flashx.tv`
TamperMonkey (with AAK only)

Doesn't work after completely clearing cache and cookies. Nor does it work in Incognito mode running ublock and aak.
(And just because apparently a full link is needed: 
https://www.flashx.tv/embed.php?c=oxa04kjnee8n)

**Comment by uBlock-user** [comment]
It's buggy, don't use it.

Previous thread - https://github.com/uBlockOrigin/uAssets/issues/294

**Comment by LS4WT** [comment]
You're referring to?
