### ISSUE TITLE
tgo-tv.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#303]
Hi,
on `http://tgo-tv.com/watch/live-tv/abc-live-stream.html` >  **Stream 3**

![anti-adblock tgo-tv.com](http://i.imgur.com/Q0pUtUW.png)

source: https://forums.lanik.us/viewtopic.php?f=62&t=22181

Merci.

**Comment by reek** [comment]
Thanks Med ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
