### ISSUE TITLE
undeniable.info

### ISSUE THREAD

**Issue by Aurani** [reek/anti-adblock-killer#3036]
Can't access any information on this site and instructed to turn off adblock.
[Example page](http://undeniable.info/pz/wiki/recipelist.php?wherein=0&pn=1&cat=0&type=0&SEARCH=0)
[Blocked message](http://i.imgur.com/xzBzbcP.png)
Waterfox 52.0.1
Greasemonkey
uBlockO 1.11.4 (uBlock filters: Filters, Badware risks, Privacy, Unbreak, Adblock Warning Removal List, Anti-Adblock Killer, EasyList without element hiding rules, EasyPrivacy, Malvertising filter list by Disconnect, Malware Domain List, Malware domains, Malware domains (long-lived), Malware filter list by Disconnect, Peter Lowe's Ad and tracking server list)

**Comment by uBlock-user** [comment]
Remove AAK and install Adblock Protector Script.

@X01X012013

```javascript
if (a.domCmp(["undeniable.info"])) {
    a.bait("div", "#testadblock");
}
```

**Comment by jspenguin2017** [comment]
Added to Script 😄 
Thanks.

**Comment by Aurani** [comment]
Alright, I can view the page just fine now, I hope my other sites will still function using this setup.

**Comment by jspenguin2017** [comment]
Don't worry, rules are applied only to related domains, and if something breaks, please let me know by opening an issue here: https://github.com/X01X012013/AdBlockProtector/issues
