### ISSUE TITLE
alientube.co

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#304]
* http://alientube.co/
* alientube.co###adblockContainer
* https://i.imgur.com/3TZqyik.png
* Firefox 37.0.1
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.9
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

**Comment by reek** [comment]
Hi,

Thanks Anon :+1:

**Comment by reek** [comment]
Added !
