### ISSUE TITLE
ProBoard

### ISSUE THREAD

**Issue by vinctux** [reek/anti-adblock-killer#305]
Problem found on every forum on domains: *.proboard.com, *.freeforums.net, *.boards.net
(See https://www.proboards.com/forum-directory for whole list of all public forums)

	<script type="text/javascript">
		$(window).load(function() {
			var topAd = $('#top-ad-banner');
			if (topAd.prop('scrollHeight') < 90) {
				var elemText = '<div id="support-message"><b>Please consider supporting this website by disabling your ad-blocker.<br />' +
			               'This website does not use audio ads, popups, or other annoyances. Thank you!</b></div>'
				var newElem  = $(elemText);
				newElem.insertAfter(topAd);

				var css = '<style type="text/css">#support-message { display: block !important; height: auto !important; width: 728px !important;' +
				          'text-align: center !important; margin: 0 auto 10px !important;}</style>';
				$("head").append(css);
			}
		});
	</script>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Added !
