### ISSUE TITLE
Local Guardian Sites

### ISSUE THREAD

**Issue by jackyaz** [reek/anti-adblock-killer#3050]
www.croydonguardian.co.uk

Love your local news?
Please turn off your ad-blocker.
Did you know that advertising supports local journalism and promotes local businesses? Find out how to turn off your ad-blocker.

**Comment by uBlock-user** [comment]
`croydonguardian.co.uk###__nq__hh`

**Comment by jackyaz** [comment]
Sorry, bit of a newbie, where do I put this? I'm using AdBlock plus if that helps? Thanks!

**Comment by jackyaz** [comment]
Nvm switched to uBlock and it works! Thanks

**Comment by uBlock-user** [comment]
Custom Filters or My Filters.

**Comment by uBlock-user** [comment]
For uBlock Origin, add - `croydonguardian.co.uk##script:inject(abort-on-property-write.js, _sp_)`

**Comment by uBlock-user** [comment]
Also only run uBlock Origin and not ABP together, running both will cause and create conflicts within the browser.

**Comment by jackyaz** [comment]
Yes been meaning to ditch ABP for a while, now done. Custom filter works thank you!
