### ISSUE TITLE
pagefair.com.

### ISSUE THREAD

**Issue by vinctux** [reek/anti-adblock-killer#306]
Discovered this script from https://pagefair.com. Not directly Anti-Adblock, but tracking user's activity with AB's for companies, that think AB is the cause of loosing profit through blocked ad-networks. It could de facto build up to a separate network, best knowing how to defeat AAB.

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
        <script type="text/javascript">
            (function() {
                function async_load(script_url){
                    var protocol = ('https:' == document.location.protocol ? 'https://' : 'http://');
                    var s = document.createElement('script'); s.src = protocol + script_url;
                    var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
                }
                bm_website_code = 'E8F7F1F883254010';
                jQuery(document).ready(function(){async_load('asset.pagefair.com/measure.min.js')});
                jQuery(document).ready(function(){async_load('asset.pagefair.net/ads.min.js')});
            })();
        </script>

More info can be obtained through their web portal with login credentials found here: http://bugmenot.com/view/pagefair.com

**Comment by reek** [comment]
HI,

Thank you, I'll block this spying.

**Comment by reek** [comment]
Added !
