### ISSUE TITLE
thewindowsclub.com

### ISSUE THREAD

**Issue by kamild1996** [reek/anti-adblock-killer#3079]
Example link: http://www.thewindowsclub.com/disable-data-execution-prevention
Browser: Opera
Script manager: Tampermonkey
Adblocker: uBlock Origin
Filters: uBlock's defaults + AakList

Screenshot: http://imgur.com/fbw4Bts

**Comment by uBlock-user** [comment]
add `thewindowsclub.com##script:inject(setTimeout-defuser.js)`

**Comment by harryqt** [comment]
@uBlock-user The following does not work in ABP, what should I use for ABP?

**Comment by Eclipse-Computing** [comment]
Also can confirm that this does not work under uBlock Origin

**Comment by lain566** [comment]
@Eclipse-Computing yes, Works! 👍  
added in Adblock Protector list

**Comment by uBlock-user** [comment]
Patched in uBlock Filters, force update your filters.

**Comment by kamild1996** [comment]
It's working now, thank you!
