### ISSUE TITLE
Youwatch.org

### ISSUE THREAD

**Issue by limacezzz** [reek/anti-adblock-killer#308]
http://youwatch.org/embed-y21wsd565ntx-600x380.html
http://s15.postimg.org/m232vql5n/report.png
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

To ease your job, i just created an adblock plus filter to disable that : 
(full style blocking, sorry for this...)

youwatch.org##div[style^="width:600px;height:400px;text-align:center;padding:10px;-webkit-box-shadow:0015px1pxrgba(0,0,0,0.2);box-shadow:0015px1pxrgba(0,0,0,0.2);-webkit-border-radius:8px;border-radius:8px;z-index:999999;background-color:#f1f1f1;position:absolute;left:50%;top:0;margin-left:-300px;display:none;}p.adbuddy-p{color:rgba(0,0,0,0.5);margin:10px010px;font-size:18px;font-weight:200;line-height:1.6em;}#adbuddy-no-adb-suggestions{margin-top:35px;color:#ccc;}#adbuddy-donebutton{-moz-box-shadow:inset0px1px0px0px#bbdaf7;-webkit-box-shadow:inset0px1px0px0px#bbdaf7;box-shadow:inset0px1px0px0px#bbdaf7;background:-webkit-gradient(linear,lefttop,leftbottom,color-stop(0.05,#79bbff),color-stop(1,#378de5));background:-moz-linear-gradient(centertop,#79bbff5%,#378de5100%);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff',endColorstr='#378de5');background-color:#79bbff;-webkit-border-top-left-radius:0px;-moz-border-radius-topleft:0px;border-top-left-radius:0px;-webkit-border-top-right-radius:0px;-moz-border-radius-topright:0px;border-top-right-radius:0px;-webkit-border-bottom-right-radius:0px;-moz-border-radius-bottomright:0px;border-bottom-right-radius:0px;-webkit-border-bottom-left-radius:0px;-moz-border-radius-bottomleft:0px;border-bottom-left-radius:0px;text-indent:0;border:1pxsolid#84bbf3;display:inline-block;color:#ffffff!important;font-family:CourierNew;font-size:15px!important;font-weight:bold;font-style:normal;height:45px;line-height:45px;width:131px;text-decoration:none;text-align:center;text-shadow:1px1px0px#528ecc;margin-top:-15px!important;}#adbuddy-donebutton:active{position:relative;top:1px;}#adbuddy-stopadblock{width:230px;height:auto;}#adbuddy-overlay{min-width:100%;min-height:100%;position:fixed;top:0px;bottom:0px;left:0px;right:0px;background-color:rgba(0,0,0,0.8);z-index:9000;display:none;"]

**Comment by reek** [comment]
Hi,

Your filter does not work because EasyList has rules that allows it. I'll see if I can find another solution

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by limacezzz** [comment]
thanks you ! and nice job !

2015-04-14 21:44 GMT+02:00 reek <notifications@github.com>:

**Comment by limacezzz** [comment]
ow sorry, but that's not working...

2015-04-14 22:03 GMT+02:00 Nicolas Paillard <nicopaille1@gmail.com>:

**Comment by reek** [comment]
have you updated aaklist ?

**Comment by reek** [comment]
I'll see if I can find another solution

**Comment by reek** [comment]
be sure to remove personal rules you have created

**Comment by limacezzz** [comment]
that is the first thing i have done. This anti adblock is strange, it
doesn't work at every time...

2015-04-15 1:38 GMT+02:00 reek <notifications@github.com>:

**Comment by reek** [comment]
Install 
https://gist.github.com/reek/dc234ea9687056bd99fe/raw/e79fb700ae0e0b8275a64ad84c600c880fdfbd7f/aakdev.user.js

**Comment by limacezzz** [comment]
It seems that's working, thanks.

2015-04-15 2:42 GMT+02:00 reek <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
