### ISSUE TITLE
http://urle.co

### ISSUE THREAD

**Issue by MrLuckyAdBlock** [reek/anti-adblock-killer#3084]
Example link: http://urle.co/7k2s
Browser: Firefox
Script manager: Greasemonkey
Adblocker: Adblock Plus
Filters: Adblock Plus's Filters (along with a few from the web) + AakList

**Comment by uBlock-user** [comment]
add - `@@||urle.co^$generichide`

**Comment by MrLuckyAdBlock** [comment]
Thanks, much appreciated.
