### ISSUE TITLE
miniminiplus.pl

### ISSUE THREAD

**Issue by seba2282** [reek/anti-adblock-killer#3087]
Firefox Android / PC with Ublock Origin extension.

On PC Videos don't play. On Android Example video shows me full screen popup with ads and I can't disable it.

**Comment by uBlock-user** [comment]
remove AAK

**Comment by seba2282** [comment]
I haven't aak list as special filters. I use integrated filter reek antiblock killer in UBO.

**Comment by uBlock-user** [comment]
remove it it's buggy and no longer maintained.

**Comment by seba2282** [comment]
It is in filters in UBO. I turn off it ? Understand good ? And my problem fix after ?

**Comment by jspenguin2017** [comment]
We have a solution: https://github.com/jspenguin2017/AdBlockProtector/issues/129

Install: https://jspenguin2017.github.io/AdBlockProtector/

**Comment by seba2282** [comment]
I installed. Do you know, will Protector be integrated with Adblockers (UBO , ADB/ADB+, Adquard, etc), when and will autors Adblockers remove Anti Adblock Killer from Adblockers filters ? Sorry my questions. 

In last time Android FF + UBO doesn't block ads how on desktops/laptops versions. MiniMiniPlus.pl shows me iritation ads (popups). Why ? Alltime UBO in FF Android blocked generally all.

**Comment by jspenguin2017** [comment]
@seba2282 

My project is designed for uBO, so chances are it won't be integrated into other ad blockers. The author of uBO is not willing to replace AAK because he thinks Reek will be back. An issue was opened in uBO repository: https://github.com/gorhill/uBlock/issues/2438

uBO for Android FireFox sometimes don't save settings properly, so double check your settings to make sure it is saved. Also, you will need a script host to use the solution for `miniminiplus.pl`, Tampermonkey works for desktop / laptop, USI should work for Android.

**Comment by seba2282** [comment]
@jspenguin2017 But usi for Android doesn't work, because normally without Protector UBO for FF doesn't block ads and I have big popups. The same with usi and protector. On PC UBO blocks all and videos don't play. With tampermonkey and protector, films on miniminiplus.pl don't play.

**Comment by jspenguin2017** [comment]
I don't really think that website is designed for mobile, if it doesn't work on PC, please provide a test link.

**Comment by seba2282** [comment]
@jspenguin2017 I wrote, doesn't work on Android. On PC is ok :)

**Comment by jspenguin2017** [comment]
Well, my project isn't tested for Android yet. I'll test it sometimes this summer.

**Comment by seba2282** [comment]
@jspenguin2017 Your script will not help, because same Android ubo doesn't block ads the same how PC ubo. :) I think it.

**Comment by jspenguin2017** [comment]
uBO on Android works for most websites for me... We'll see.

**Comment by seba2282** [comment]
@jspenguin2017 So please look on miniminiplus.pl/filmy . After few looking videos, you will see big popup on Android. Please test it. I use all filters without reek killer and ignore cosmetic filters and have this problem with popups 2-3 months actually.

**Comment by jspenguin2017** [comment]
Hum... It works on PC, I'll test on android sometime this summer. No ETA. Our player patcher may not work natively on Android... 
![image](https://cloud.githubusercontent.com/assets/7283682/25294049/b35e2b46-269a-11e7-9894-18d6360812df.png)

**Comment by seba2282** [comment]
Try the same on Firefox Android + ubo. On PC if you disable protector, films don't play. On Android without scripts in ff + ubo films don't blocked and you see popups. Try Android and believe me. Ubo should block playing films with ads, but doesn't.

**Comment by jspenguin2017** [comment]
@seba2282 
Obviously it won't play, that's why my project exist. For Android, I'll test it when the time comes.

**Comment by seba2282** [comment]
@jspenguin2017 Please make two tests. Turn off temporally protector connect with miniminiplus.pl/filmy try turn few films (on PC). 

Next the same test for Android but skip section with protector. And write me, what do you see on PC and on Android. 

:)

**Comment by jspenguin2017** [comment]
That is not a supported configuration, it does not work and it's out of my control. 
As I said, I'll test Android this summer.

**Comment by seba2282** [comment]
@jspenguin2017 Is it true, FF has a bugged webextensions and Protector in ubo doesn't work ?

**Comment by jspenguin2017** [comment]
@seba2282 It works for me, try Chrome.

**Comment by seba2282** [comment]
@jspenguin2017 on Firefox ? We speak about integrated in filters not separetly script. I tried on MS Edge and video was blocked. After refresh video worked. So, more working, sometimes not working.

**Comment by jspenguin2017** [comment]
@seba2282 Our solution is script based.

**Comment by seba2282** [comment]
https://github.com/jspenguin2017

**Comment by seba2282** [comment]
@jspenguin2017 Do you speak about integrated filter, what it is now in ubo ?

**Comment by seba2282** [comment]
Sorry, I am mobile and paste all adress site earlier.

**Comment by jspenguin2017** [comment]
@seba2282 No, I don't have plan in making a filter solution.

**Comment by seba2282** [comment]
![screenshot_2017-05-16-21-13-08](https://cloud.githubusercontent.com/assets/16944478/26124056/6b7224c6-3a7d-11e7-9546-0932839576ad.png)

Do you see ? UBO has integrated list as filter. Is it all or must I installed nothing ?

**Comment by jspenguin2017** [comment]
Try USI. 
The List is there, but the solution is in Script.

**Comment by seba2282** [comment]
I tried on Android FF, didn't work. UBO detected by sites. On PC and Tampermonkey and worked medium. There are sites, what detecting adblockers with killers or protectors. So I think it is all blocking adblock blockers in beta testing actually. Sorry my opinion. Maybe future all will can block all ads. Project super adblock is ready but we don't know, when we will can use it. :)

**Comment by jspenguin2017** [comment]
Please let me know if you find sites that are not working on PC. We'll fix them.

**Comment by seba2282** [comment]
@jspenguin2017 I have question. About Android. I use FF + UBO and few months have a problem with ads on minimini+. If I used example FF under than version 50, minimini+ blocked normally. FF 50+, I see popups   with lego, nuzzles, smerfs and etc. I try more exclussions blocked or allowed in users filters and it is back. Can you help ? Our polish filters developers have the same. And we can't block ir.

**Comment by jspenguin2017** [comment]
@seba2282 It works fine on Chrome. I don't offer support for FireFox.

**Comment by seba2282** [comment]
@jspenguin2017 MS Edge will support in future or not ?  You know, how chrome is on Android. Any extensions yet. On PC generally use MS Edge. I don't like Chrome.

**Comment by jspenguin2017** [comment]
@seba2282 I will only support a single setup, which will be one I use. I don't have time to test on multiple setups.

**Comment by jspenguin2017** [comment]
Also, all our core contributors are using uBO on Chrome or Chromium, so unfortunately it'll be a bit hard for you to find help with MS Edge. But good luck anyway...

**Comment by seba2282** [comment]
@jspenguin2017 hmmm... Reek works all time for ubo or not ?

**Comment by jspenguin2017** [comment]
I don't know.

**Comment by seba2282** [comment]
@jspenguin2017 Can you look on miniminiplus.pl/filmy, but with ff android + ubo and write me, how I can fix for user filters ? I see all time big popups and I testing more exclussions @@|| or || and I can't fix.

**Comment by jspenguin2017** [comment]
No. I said before, I don't offer support for that.

**Comment by seba2282** [comment]
@jspenguin2017 I know. Protector not supported on different browsers than chrome/chromium. But I asked about rule in user's filters for ubo, because I want only blocked​ this popups in ff Android + ubo. Are you specialist in it?

**Comment by jspenguin2017** [comment]
Go ask it here: https://github.com/uBlockOrigin/uAssets/issues

**Comment by seba2282** [comment]
Ok. So thanks for help.
