### ISSUE TITLE
http://ally.sh

### ISSUE THREAD

**Issue by MrLuckyAdBlock** [reek/anti-adblock-killer#3089]
Example link: http://ally.sh/hUgtD
Browser: Firefox
Script manager: Greasemonkey
Adblocker: Adblock Plus
Filters: Adblock Plus's Filters (along with a few from the web) + AakList

Error: Please Disable AdsBypasser

Even when AdsBypasser is disabled error still appears.
Added @@||ally.sh^$generichide and still not going away.

**Comment by uBlock-user** [comment]
@jspenguin2017 cant this be bypassed with AdsBypasser solution ?

**Comment by jspenguin2017** [comment]
I don't think so... it has reCaptcha, and as far as I know, AdsBypasser don't have solution for sites using reCaptcha...

**Comment by ghajini** [comment]
this is blockadblock....
script is here `https://github.com/sitexw/FuckAdBlock/blob/v4.x/fuckadblock.js`
`http://ally.sh/static/fuckadblock.min.js`

do we have generic protection against `Blockadblock/Fuckadblock`

**Comment by jspenguin2017** [comment]
@ghajini Yes, we do, but surprisingly it's not caught in the generic protectors...

**Comment by uBlock-user** [comment]
Already caught and patched by uBO - https://i.gyazo.com/8d00201cd0bc2082400a631ad173c0a5.png

**Comment by jspenguin2017** [comment]
@uBlock-user Are you sure that works? I just updated all my filters, and it still doesn't work.

**Comment by uBlock-user** [comment]
Ofcourse it doesn't work, I never said it works. My response was directed to @ghajini 's  post.

They have another script which is detecting adblocker mistakenly for adsbypasser or something like that.

**Comment by okiehsch** [comment]
````
||p207208.clksite.com^$subdocument,redirect=noopframe,domain=ally.sh
@@||ally.sh^$generichide
````
works on my end.

**Comment by kyyu** [comment]
@okiehsch

Thanks

**Comment by MrLuckyAdBlock** [comment]
@okiehsch 
`||p207208.clksite.com^$subdocument,redirect=noopframe,domain=ally.sh`

Adblock Plus shows "Unknown filter option" error with above code.

Can you write a code that works with Adblock Plus?

**Comment by jspenguin2017** [comment]
@MrLuckyAdBlock I don't think Adblock Plus has redirect functionality, so I don't think it would be possible to rewrite the rule for Adblock Plus.

**Comment by uBlock-user** [comment]
ABP is very basic, you will have to whitelist few ad-servers connections for that website to get it working, that's the only way.
