### ISSUE TITLE
kwejk.pl

### ISSUE THREAD

**Issue by krzysztofhanzel** [reek/anti-adblock-killer#309]
http://m.kwejk.pl
http://imgur.com/HX28DJc
Opera 28.0
Tampermonkey 3.11.4600
Adblock Plus
Adblock Warning Removal List + EasyList + EasyPrivacy + Anti-Adblock Killer | Filters for Adblockers + Polish Adblock filters

**Comment by vinctux** [comment]
kwejk.pl##.aoverlay
	kwejk.pl##.aoverlay-over
	kwejk.pl###adinfo

Are the main causes, but there is also this inline script:

	var orgPutBan = putBan;
	putBan = function(number){
		if(localStorage.getItem('wasadblocked') == 1)
		{
			var notallowed = [1,19];
			if(notallowed.indexOf(number) == -1)
			{
				orgPutBan(number);
			}
		}
		else {
			orgPutBan(number);
		}
	}

which checks if the users already visited the AAB message via a cookie named 'adletter_v2' which contains the value '1'.
Simply blocking just the previous mentioned first two layers ('.overlay' and '.overlay-over') isn't a suitable solution, as the content is hidden when blocking.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@vinctux

thank you, I'll watch it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
