### ISSUE TITLE
Telegraph.co.uk again

### ISSUE THREAD

**Issue by captainplastic** [reek/anti-adblock-killer#3094]
http://www.telegraph.co.uk/news/2017/04/17/china-russia-dispatch-ships-shadow-donald-trumps-armada-approaches/
http://imgbox.com/YdsjVtb8
Chrome
Tampermonkey
Adblock
Adblock Custom Filters + Easylist +Adblock Warning Removal List + AakList

Something's happened to make the previous solution [#2491] no longer work. Any help greatly appreciated!

**Comment by uBlock-user** [comment]
Can't reproduce. Force update your filters and remove all cache and cookies.

**Comment by captainplastic** [comment]
Hi I've tried that and I'm still getting the same message pop up. I'm in the UK and perhaps the message is specific to UK visitors?

**Comment by lain566** [comment]
add `@@||telegraph.co.uk^$generichide`

**Comment by captainplastic** [comment]
Brilliant! Works a treat! Many thanks.
