### ISSUE TITLE
aranzulla.it tecnogalaxy.it

### ISSUE THREAD

**Issue by matteopoma** [reek/anti-adblock-killer#3096]

**Comment by uBlock-user** [comment]
`||aranzulla.it^$inline-script` and `/wp-content/uploads/*.js`

**Comment by DjDiabolik** [comment]
I don't have understand... how i need to add this exactly ?? On ADB ?? On reeksite script ?? If yes how i need to do ?

*EDIT*
Found a workaround........ possibly i add to "User Exclusions" in preferences of script this:
`*aranzulla*`

Now i can read all article whitout block................ it's need to fix on next version of reeksite script ?

**Comment by matteopoma** [comment]
on reek script

2017-04-22 3:29 GMT+02:00 David XXX <notifications@github.com>:

**Comment by DjDiabolik** [comment]
i need to put in a specific line or part ?
