### ISSUE TITLE
How to subscribe to Aaklist when using Opera?

### ISSUE THREAD

**Issue by FrogFan** [reek/anti-adblock-killer#3097]
I've installed Anti-Adblock Killer using Tampermonkey in Opera.  Aak nags me to subscribe to Aaklist every couple days, but I can't figure out how to subscribe.  I'm using the Opera's built-in ad blocker.

Thanks for any help.

**Comment by uBlock-user** [comment]
You cannot. Opera doesn't offer any such functionality.

**Comment by FrogFan** [comment]
Thanks for the quick response.  For the record, Aak has done a good job bypassing any ad-block killers I've encountered since installing it, so I'll continue to keep it installed until it doesn't work anymore, and I'll disable its "check for subscription" option.
