### ISSUE TITLE
More Anti-AdBlock Wordpress Plugins

### ISSUE THREAD

**Issue by vinctux** [reek/anti-adblock-killer#310]
So, I found several new (not yet added as I saw or at least not visible mentioned) AAB WP plugins:
- [x] Better Stop Adblock (https://wordpress.org/plugins/better-stop-adblock/)
- [ ] Adblock Notify by b*web (https://wordpress.org/plugins/adblock-notify-by-bweb/)
- [ ] adBuddy+ (AdBlocker Detection) by NetfunkDesign (https://wordpress.org/plugins/adbuddy-adblocker-detection/)
- [ ] BAN - Blocked Ads Notifier Lite (https://wordpress.org/plugins/blocked-ads-notifier-lite/)

The first two (Better Stop Adblock and Adblock Notify) are operating via script. All scripts are located in the traditional ```/asset/js/``` folder. These should be all:
```
    [ ] an-admin-scripts.js
    [ ] an-detect.min.js
    [ ] an-scripts.js
    [ ] an-scripts.min.js
    [x] bsa-script-doctype.js
    [x] bsa-script-no-doctype.js
```
The third one (adBuddy+) is operating via CSS. In this case blocking will not help, because disallowing the specific ```##.adbuddy-protected``` class would lead to unaccessibility and unfunctionality of the webpage.

The fourth (BAN) is even more complex - it's operating as a freemium plugin, where the basic is simmilar to that of adBuddy+'s, but the premium features are making headaches: it involves class randomization (see http://imgbox.com/FHgX9mvS).

Thant's all I found. I hope it helps.
vinctux

**Comment by reek** [comment]
@vinctux

thank you, I'll watch it
