### ISSUE TITLE
ovar.io

### ISSUE THREAD

**Issue by ZfsrGhS953** [reek/anti-adblock-killer#3105]
https://www.ovar.io/
http://i.imgur.com/bJ1kUsC.png
Google Chrome
Tampermonkey
Adblock Plus
Adblock Warning Removal List + RuAdList+EasyList + AakList (Anti-Adblock Killer)

**Comment by uBlock-user** [comment]
@jspenguin2017, the notice appears when you click on Scout, Tank and Ghost

**Comment by jspenguin2017** [comment]
Hum... uBO isn't logging anything...

**Comment by uBlock-user** [comment]
> uBO isn't logging anything...

What does that mean ? I ran the logger and it logs as expected.

**Comment by jspenguin2017** [comment]
Oh, I mean it isn't logging anything interesting... Nothing in the logger seems to be the cause of the detection.

**Comment by uBlock-user** [comment]
add - `||imasdk.googleapis.com^$third-party,badfilter`

That patches the issue on my end.

**Comment by uBlock-user** [comment]
Open the console and you will find some information regarding adblocking.

**Comment by uBlock-user** [comment]
It's blocking right click context menu for this reason too.

**Comment by uBlock-user** [comment]
Anti adblock code is hidden here - http://static.miniclipcdn.com/js/sdk/v1.3/miniclip.js

**Comment by jspenguin2017** [comment]
@uBlock-user I think it's Unity engine that is blocking context menu, sometimes the game needs right click. I don't think `||imasdk.googleapis.com^$third-party` is a bad filter, the script blocked is "Interactive Media Ads Software Development Kit", we just need to white list it for this specific domain.

**Comment by jspenguin2017** [comment]
OK, this fixes it: `@@||imasdk.googleapis.com^$third-party,domain=ovar.io`

**Comment by uBlock-user** [comment]
> I don't think ||imasdk.googleapis.com^$third-party is a bad filter`

It has broke few things on other websites notably so I had to whitelist that domain out of necessity to un-break the website, hence my suggestion to `$badfilter` it.

**Comment by jspenguin2017** [comment]
@uBlock-user 
In that case we need a skeleton placeholder, not just allow the whole SDK to come in.

**Comment by uBlock-user** [comment]
Yeah, it appears it makes video-ad request to third-party ad-servers. In that case we shouldn't white-list it completely.

**Comment by uBlock-user** [comment]
@jspenguin2017 Could you please test this filter `|blob:$domain=ovar.io` and check if it breaks anything ? Remove the exception filter I posted and add that.

**Comment by jspenguin2017** [comment]
@uBlock-user I think those are part of Unity engine... I'll test it later.

**Comment by uBlock-user** [comment]
That blob based URI is the one initiating ads and checking for anti adblock.
