### ISSUE TITLE
plej.tv

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#311]
http://plej.tv/watch#TVP1HD
https://www.dropbox.com/s/xhosgzgzjvq1xw4/adblock4.png?dl=0
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

I have this message
Aby otworzyło się okienko logowania, musisz mieć odblokowane, wszelkie "popoup blokery", musisz zezwolić na wyskakujące okienka...

**Comment by marek45** [comment]
yes I have the same message on new pc. Page and you see my message.

**Comment by reek** [comment]
Hi,

yes, I see your message but once neutralized, I see this
![capture1](https://cloud.githubusercontent.com/assets/3474011/7184926/2215cf8c-e460-11e4-8edd-4986d5e3b430.PNG)

**Comment by marek45** [comment]
please, refresh page, then you see another message.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
