### ISSUE TITLE
blog.adamantbarbell.com

### ISSUE THREAD

**Issue by tofof** [reek/anti-adblock-killer#3110]
https://blog.adamantbarbell.com/1901/the-best-adjustable-dumbbells-ironmaster-vs-powerblock-vs-selecttech/
http://i.imgur.com/zH0hS84.png
Chrome 57.0.2987.133 (64-bit)
Tampermonkey 4.2.7
uBlock Origin v1.12.1

Filters used:
Adguard Annoyances Filter
Adguard Social Media Filter
EasyList
EasyPrivacy
Fanboy+Easylist-Merged Ultimate List
Fanboy’s Annoyance List
Fanboy’s Enhanced Tracking List
Fanboy’s Social Blocking List
hpHosts’ Ad and tracking servers
Anti-Adblock Killer | Reek

**Comment by uBlock-user** [comment]
add - `/wp-content/uploads/*.js`
