### ISSUE TITLE
https://www.gadgetdaily.xyz/gnome-vs-kde/

### ISSUE THREAD

**Issue by RayBB** [reek/anti-adblock-killer#3115]
https://www.gadgetdaily.xyz/gnome-vs-kde/
http://imgur.com/a/W3Zqf
Google Chrome
Tamper Monkey
Ublock Origin
EasyList + AakList

**Comment by uBlock-user** [comment]
page won't load.

**Comment by RayBB** [comment]
It's still loading fine for me.
The part that's blocking the page is:

    <div class="kill-adblock-container kill-adblock-2 kill-adblock-hide" style="display: block;">
    <div class="kill-adblock-body">
                <span class="close-btn">×</span>
                        <img src="https://www.gadgetdaily.xyz/wp-content/plugins/kill-adblock//images/logo.png">
                <div class="kill-adblock">The ads on this site help keep the content free of charge. Please add <strong>www.gadgetdaily.xyz</strong> to your ad blocking whitelist or disable your adblocking software.<br><br>You can also support us by <a href="http://www.imaginesubs.co.uk/subscribe-to-gadget?offerCode=WEB100" target="_blank">subscribing to our magazine.</a></div>
    </div>
</div>

**Comment by uBlock-user** [comment]
Try - `gadgetdaily.xyz###kill-adblock-container` or `gadgetdaily.xyz##.kill-adblock-container`
