### ISSUE TITLE
danslescoulisses.com/fr/

### ISSUE THREAD

**Issue by jehabs** [reek/anti-adblock-killer#313]
* http://www.danslescoulisses.com/fr/
* First screenshot normal page with internet explorer
* http://i.imgbox.com/41w7Stu7.png
* Second with text
* http://imgbox.com/alocfiTc
* Mozila Firefox
* Greasemonkey
* Adblock Edge But i think it same think for adblok Plus
* Liste FR + EasyList

**Comment by jehabs** [comment]
* https://addons.mozilla.org/fr/firefox/addon/adblock-edge/
* First screenshot normal page with internet explorer
* http://i.imgbox.com/41w7Stu7.png
* Second with text
* http://imgbox.com/alocfiTc
* Mozila Firefox
* Greasemonkey
* Adblock Edge But i think it same think for adblok Plus
* Liste FR + EasyList

**Comment by reek** [comment]
Hi,

It semblerais a filter blocks a style sheet, I will correct, thank you for reporting.

See you
Reek

**Comment by reek** [comment]
Hi,

Fixed, update AakList.

See you
Reek

**Comment by jehabs** [comment]
Hi, 
thank you for your assistance. It just misses correcting the images on the right side and all would be perfect.Just in bottom of WEBRADIO it misses the images. http://imgbox.com/lSwXQxlf

You will immediately see the difference with the first screenshot.
 http://i.imgbox.com/41w7Stu7

Thank you very much for your speed. If, I can help you, made me sign.

**Comment by reek** [comment]
Hi,

If I allow the filter to mask this element, there will be anti- adblock message.

**Comment by jehabs** [comment]
ok is correct thank you.
