### ISSUE TITLE
comicbook.com

### ISSUE THREAD

**Issue by Zhangsun321** [reek/anti-adblock-killer#3130]
chrome
tampermonkey
ublock origin

http://prntscr.com/f0dsxn
http://prntscr.com/f0dt9s

screen shot of my lists used page

ty

**Comment by uBlock-user** [comment]
add - `comicbook.com##script:inject(abort-on-property-read.js, stop)`

**Comment by Zhangsun321** [comment]
ty... works perfect.. sorry for the double post.. my other acct got flagged'

**Comment by Zhangsun321** [comment]
notes for comicbook.com users.  you may need to disable some extensions to get it to work

**Comment by Trespass3r** [comment]
The Psych Movie article is what sent me here, but it is happening on the entire domain. I only have UBO and TamperMonkey running as extensions. I am subscribed to the correct lists and added the custom filter `comicbook.com##script:inject(abort-on-property-read.js, stop)` but the element is still not being blocked.

**Comment by purseuswow** [comment]
I've done the same steps as well and having issues with the popup element on the page.

**Comment by uBlock-user** [comment]
The filter works fine on my side, so something is stopping it from being applied on yours.
