### ISSUE TITLE
https://dlwordpress.com

### ISSUE THREAD

**Issue by harryqt** [reek/anti-adblock-killer#3135]
Website : https://dlwordpress.com
uBlock Origin v1.12.1

**Comment by uBlock-user** [comment]
add - `/wp-content/uploads/*.js`

**Comment by harryqt** [comment]
@uBlock-user Added. But does not work. :(

**Comment by uBlock-user** [comment]
Press the refresh button and remove all cache and site data. You're expected to do this everytime you add a new filter.

**Comment by harryqt** [comment]
@uBlock-user http://prntscr.com/f0loz0
Kindly check the screenshot, have I done it right? I'm new at uBlock Origin.
BTW, I'm using Reek Anti Adblock Killer too.

**Comment by uBlock-user** [comment]
Copy paste **what I posted here** and remove the filter you added.

**Comment by harryqt** [comment]
@uBlock-user Thanks. it worked. I had to restart Chrome to get it worked. 
BTW, can you please tell me how you figure out which one to block? I hate to post a new thread in github every time.

**Comment by sharmazac** [comment]
Website : http://nulledthemes.a1techtips.com/
All wordpress themes and plugins
