### ISSUE TITLE
comicbook.com

### ISSUE THREAD

**Issue by Zhangsun321** [reek/anti-adblock-killer#3139]
the posted fixes work for the main page... yes

doesnt work on its sub pages
http://comicbook.com/marvel/
http://comicbook.com/starwars/
comicbook.com##script:inject(abort-on-property-read.js, stop)
is the script line i have    chrome ublock origin tampermonkey
ty

**Comment by uBlock-user** [comment]
Nope, works on the entire domain, disable all extensions and only keep uBO enabled and then try again. The issue is on your end, the filter is created to cover the entire domain.
