### ISSUE TITLE
bitzfree.com

### ISSUE THREAD

**Issue by Blahx** [reek/anti-adblock-killer#314]
http://bitzfree.com
http://imgur.com/THZIS0v - with ads
http://imgur.com/7gabEsP - anti adblock
Google Chrome
Tampermonkey
Adblock Plus
EasyList + Adblock Warning Removal List + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Blahx** [comment]
Hello,

I tested the the update and while the warning does not appear any more, the functionality is still disabled. In main page for example, The clicking on Double Mining several times makes the page reload and does nothing (normally the hash will be doubled on second try).

I have also make a small donation for your efforts.

Best Regards.

**Comment by reek** [comment]
Hi,

I'll look at it more closely.

Thanks for donation
Reek

**Comment by reek** [comment]
i have to see this
http://bitzfree.com/btc2x_128.png

**Comment by reek** [comment]
Install: https://gist.github.com/reek/dc234ea9687056bd99fe/raw/48fd83b181d93971cec71df7899e171d5555fd0f/aakdev.user.js

And update AakList

**Comment by Blahx** [comment]
Hmm there's no change on the Double Mining.

**Comment by reek** [comment]
it's good for me, when I click two or three times on the button
![capture](https://cloud.githubusercontent.com/assets/3474011/7475832/3debd0f0-f34a-11e4-83fc-b7a3bde3c814.PNG)

**Comment by Blahx** [comment]
Hmm.. I have just tried restarting my pc, reinstalling the userscript and Aaklist  and.. I am seeing the anti adblock warning again. On the hindsight though, if I off everything and let the ads load, then turn on everything  again, the double mining works now. (previously that would'nt have worked)

**Comment by Blahx** [comment]
I have  just checked and it only happens with https://gist.github.com/reek/dc234ea9687056bd99fe/raw/48fd83b181d93971cec71df7899e171d5555fd0f/aakdev.user.js

If I reinstall back http://tinyurl.com/mvpl5ku , it is back to just page refreshing but no anti adblock warning.

**Comment by reek** [comment]
Disable AakScript and use only AakList

**Comment by Blahx** [comment]
With only Aaklist, I still see the anti adblock warning.

**Comment by reek** [comment]
Hi,

Take screenshot of filters used on bitzfree.com

**Comment by Blahx** [comment]
Just Easylist and Aaklist.
I tried testing with a new account with the same settings, just with the filterlists, and it works. No warning, double mining enable after a few tries.
But when I which back to my account, the anti adblock warning appears. :/

**Comment by reek** [comment]
it's weird.

**Comment by reek** [comment]
Hi,

Give me the list of blocked resources.
https://github.com/reek/anti-adblock-killer/wiki/Additional-Informations

**Comment by Blahx** [comment]
I cant seem to figure out how to do this with ABP on Chrome. I am tempted to switch to uBlock after how lightweight it is while having the same results, would it be a problem if I switch and give you the list?

**Comment by reek** [comment]
Hi,

You cant see because its impossible
Yes, you can switch to uBlock

**Comment by Blahx** [comment]
http://imgur.com/z6QGl3I

**Comment by reek** [comment]
Try allow qadservice.com
<code>@@||ads.qadservice.com/t$script</code>

**Comment by Blahx** [comment]
That did not work
http://imgur.com/dYizZAP

**Comment by reek** [comment]
<code>
@@||adpdx.com^$image,subdocument,domain=bitzfree.com
@@||adk2.co^$image,subdocument,domain=bitzfree.com
@@||adhexa.com^$image,subdocument,domain=bitzfree.com
@@||adshexa.com^$image,subdocument,domain=bitzfree.com
@@||adnxs.com^$image,subdocument,domain=bitzfree.com
@@||cdnads.com^$image,subdocument,domain=bitzfree.com
@@||padsdel.com^$image,subdocument,domain=bitzfree.com
@@||padstm.com^$image,subdocument,domain=bitzfree.com
@@||rhtag.com^$image,subdocument,domain=bitzfree.com
</code>

**Comment by Blahx** [comment]
ditto
http://imgur.com/TXUHI3v

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
