### ISSUE TITLE
Site: https://www.theatlantic.com/

### ISSUE THREAD

**Issue by jcanfield** [reek/anti-adblock-killer#3146]
After following the instructions, running Chrome _58.0.3029.81 (Official Build) (64-bit)_ on MacOS, sites like _The Atlantic_ still block adblockers. You can even turn it off, access the site, then turn it back on-- it jumps you back to https://www.theatlantic.com/please-support-us/?next=https%3A%2F%2Fwww.theatlantic.com%2Ftechnology%2Farchive%2F2014%2F08%2Fthe-first-pop-up-ad%2F376053%2F#seen.

**Comment by uBlock-user** [comment]
add 

```
||cdn.theatlantic.com/assets/*/vendors.min*.js$script
/s_code
```

**Comment by jcanfield** [comment]
Thanks for the quick reply, damn quick =) 

Gotcha. I was browsing the source for the script that was blocking the ad-blocker-- guess I just missed that. Thanks again.
