### ISSUE TITLE
sharewareonsale.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#315]
http://sharewareonsale.com/
link for testing 30 sec. waittime(not real page but working for testing): http://sharewareonsale.com/checkout/order-received/1234567?key=wc_order_1234567abc123
http://i.imgbox.com/m1tsXUAE.png or http://i.imgbox.com/a1CFLZhD.png
Chromium Version 44.0.2373.0 (64-bit)
uBlock Origin 0.9.4.2 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎
Tampermonkey BETA 3.11.4630 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

message:
"<section id="main" class="col-left"> <article class="post-6 page type-page status-publish hentry"> <section class="entry"><script>/*<![CDATA[*/document.write('<style>.woocommerce{display:none}</style>');document.write('<div class="cac-loading"></div>');/*]]>*/</script><style>.woocommerce{display:none}</style><div id="tmp"><div style="float: left; padding-right: 10px; padding-bottom: 5px;"><a href="http://sharewareonsale.com/wp-content/uploads/2015/04/SoSbot_download_256px.png"><img class="alignleft size-full wp-image-2473202" src="http://sharewareonsale.com/wp-content/uploads/2015/04/SoSbot_download_256px.png" alt="SoSbot_download_256px" width="256" height="190"></a></div><h1>You are blocking ads :-(</h1>
We bring you daily free giveaways; we need money from ads to survive. Without ads there would be no SharewareOnSale -- there would be no daily free giveaways. <em><strong>Please unblock ads for SharewareOnSale to support us.</strong></em><br><br>

Once you unblock ads, click the blue link below and you won't ever see this message again. If you don't want to unblock ads, you will need to wait until the timer below hits zero to get your free giveaway.<br><br>
<h1><div class="countdown-message">Unblock ads or wait: <span class="ad_countdown">30</span>...</div></h1>
<p style="float: right;"><a href="#" id="ad_verify" style="float:right;">I have unblocked ads, let me download now!</a></p></div><p><span style="color: #ffffff;"></span></p><script type="text/javascript" async="" src="http://sharewareonsale.com/?top_ten_id=6&amp;top_ten_blog_id=1&amp;activate_counter=11"></script></section> </article></section>"

or

"<section id="main" class="col-left"> <article class="post-6 page type-page status-publish hentry"> <section class="entry"><script>/*<![CDATA[*/document.write('<style>.woocommerce{display:none}</style>');document.write('<div class="cac-loading"></div>');/*]]>*/</script><style>.woocommerce{display:none}</style><div id="tmp"><div style="float: left; padding-right: 10px; padding-bottom: 5px;"><a href="http://sharewareonsale.com/wp-content/uploads/2015/04/SoS_eye.png"><img class="alignleft size-full wp-image-2473276" src="http://sharewareonsale.com/wp-content/uploads/2015/04/SoS_eye.png" alt="SoS_eye" width="256" height="183"></a></div>
<h1>Are you a good person?</h1>
Good people unblock ads. You should unblock ads for SharewareOnSale -- it is the right thing to do. You are a good person, right?<br><br>

Once you unblock ads, click the blue link below and you won't ever see this message again. If you don't want to unblock ads, you will need to wait until the timer below hits zero to get your free giveaway.<br><br>
<h1><div class="countdown-message">Unblock ads or wait: <span class="ad_countdown">8</span>...</div></h1>
<p style="float: right;"><a href="#" id="ad_verify" style="float:right;">I have unblocked ads, let me download now!</a></p></div><p><span style="color: #ffffff;"></span></p><script type="text/javascript" async="" src="http://sharewareonsale.com/?top_ten_id=6&amp;top_ten_blog_id=1&amp;activate_counter=11"></script></section> </article></section>"

**Comment by reek** [comment]
Hi,

I have nothing

**Comment by maynak00** [comment]
still block message.60 sec. waittime.
"<section id="main" class="col-left"> <article class="post-6 page type-page status-publish hentry"> <section class="entry"><script>/*<![CDATA[*/document.write('<style>.woocommerce{display:none}</style>');document.write('<div class="cac-loading"></div>');/*]]>*/</script><style>.woocommerce{display:none}</style><div id="tmp"><div style="float: left; padding-right: 10px; padding-bottom: 5px;"><a href="http://sharewareonsale.com/wp-content/uploads/2015/03/SoS_stop.png"><img class=" size-full wp-image-2468945 alignleft" src="http://sharewareonsale.com/wp-content/uploads/2015/03/SoS_stop.png" alt="SoS_stop" width="256" height="256"></a></div>
<h1>Stop blocking ads (please)</h1>
Ashraf aka Mr. Boss commands you to stop blocking ads on SharewareOnSale.<br><br>

Once you unblock ads, click the blue link below and you won't ever see this message again. If you don't want to unblock ads, you will need to wait until the timer below hits zero to get your free giveaway.<br><br>
<h1><div class="countdown-message">Unblock ads or wait: <span class="ad_countdown">60</span>...</div></h1>
<p style="float: right;"><a href="#" id="ad_verify" style="float:right;">I have unblocked ads, let me download now!</a></p></div><p><span style="color: #ffffff;"></span></p><script type="text/javascript" async="" src="http://sharewareonsale.com/?top_ten_id=6&amp;top_ten_blog_id=1&amp;activate_counter=11"></script></section> </article></section>"

**Comment by reek** [comment]
Nothing, copy source code past on http://paste2.org/

**Comment by reek** [comment]
Try just EasyList + EasyPrivasy + AakList

**Comment by maynak00** [comment]
**how can I block with adblock plus or ublock origin? or can you add to Anti-Adblock Killer (AAK)?**

<code>http://cdn2.sharewareonsale.com/wp-content/plugins/checkout-ad-checker/assets/js/adblock.js?a4d60c?ver=1.0</code>
<code>http://cdn.sharewareonsale.com/wp-content/plugins/checkout-ad-checker/assets/css/cac-styles.css?a4d60c?ver=4.2.2</code>
<code>http://cdn2.sharewareonsale.com/wp-content/plugins/checkout-ad-checker/assets/js/cac-shortcode-scripts.js?a4d60c?ver=1.0</code>
<code>http://cdn.sharewareonsale.com/wp-content/plugins/checkout-ad-checker/assets/images/spinner.gif</code>
<code>http://sharewareonsale.com/wp-content/plugins/checkout-ad-checker/assets/js/adblock.js?_=TIMESTAMP</code>

**my temporary solution:** http://i.imgbox.com/HdkWyrD6.png
**ads still blocked. no waittime or adblock notice*

**Comment by reek** [comment]
Try add this rule
<pre>@@||sharewareonsale.com/wp-content/plugins/checkout-ad-checker/assets/$script,stylesheet,image</pre>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
