### ISSUE TITLE
graffica.info renovates AdBlock Blocker!!

### ISSUE THREAD

**Issue by unaef** [reek/anti-adblock-killer#3164]
http://graffica.info

This does not work now:
_||graffica.info^$xmlhttprequest
graffica.info##.ui-front.ui-widget-overlay
graffica.info##.ui-resizable.ui-front.ui-corner-all.ui-widget-content.ui-widget.ui-dialog_

Google Chrome
Tampermonkey
AdBlock
EasyList + Adblock Warning Removal List + AakList

![captura de pantalla 2017-05-03 a las 20 38 10](https://cloud.githubusercontent.com/assets/20425984/25676152/4b81e87c-3041-11e7-9da5-0b4bea4b4912.png)

**Comment by uBlock-user** [comment]
add - `||axiomaticalley.com^`
