### ISSUE TITLE
tek.no - blocking images

### ISSUE THREAD

**Issue by simonkaspersen** [reek/anti-adblock-killer#317]
Link page contains anti-adblock
www.tek.no

One screenshot
http://imgur.com/QNqoA7d

Your browser
Google Chrome on OS X and windows

Your script manager
Tampermonkey

Your adblocker
Adblock

Your filterlists
Anti-Adblock Killer | Filters for Adblockers

The scripts is blocking something in the scriptfile that loads images.
"Uncaught TypeError: Cannot read property 'selectImages' of undefined"

**Comment by reek** [comment]
Hi,

Thank you for the report, I'll fix it

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
