### ISSUE TITLE
desitvforum.net

### ISSUE THREAD

**Issue by qd123** [reek/anti-adblock-killer#318]
Hey, i am using Mozilla Firefox and install Greasemonkey in it
i am using " anti-adblock-killer "  and i got disappointed because it won't do it's job.

i usually use this playwire for watching videos's, as i gave you the link below. i get annoying ads while using " anti-adblock-killer "
http://desitvforum.net/tv-shows/alians-ke-saath-sbs-ki-tea-party-badi-door-se-aaye-hain/

Thanks and regard's
Qd

**Comment by vinctux** [comment]
Hi,

Do you get ads or anti-adblock popups/banners? Because Anti-Adblock-Killer is a userscript that aim to block anti-adblock annoyances, not ads (that's what AdBlock, AdBlock Plus, uBlock Origin, etc. are for).

Hope it helps ;)

**Comment by reek** [comment]
Hi,

As stated vinctus, if your problem relates to the ads, you must install a adblocker.
https://adblockplus.org/
