### ISSUE TITLE
https://4downfiles.org/mplyo3txvri9

### ISSUE THREAD

**Issue by harryqt** [reek/anti-adblock-killer#3193]
uBlock + EasyList + Chrome

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by harryqt** [comment]
uBlock Origin

**Comment by uBlock-user** [comment]
@jspenguin2017 Countdown timer of 15 secs is present.

JS - https://4downfiles.org/js/countdown.js

**Comment by harryqt** [comment]
@uBlock-user You could not reproduce because you had "Adblocker Protector" enabled.
After installing the Adblocker Protector scripts, it's seems to working.. 👍  
But 15 sec waiting is there, [adsbypasser](https://github.com/adsbypasser/adsbypasser) seems to fail that bypass.

**Comment by jspenguin2017** [comment]
@uBlock-user Because I'm doing maintenance on the Core, I can't update Script now. I think this would work: `a.timewarp("setTimeout", /^1000$/);`

**Comment by uBlock-user** [comment]
@Dibbyo456 I cannot reproduce even if I disable APS. 

@jspenguin2017 website is serving a blank page now, cannot test.

**Comment by uBlock-user** [comment]
@jspenguin2017 `a.timewarp("setTimeout", /^1000$/);` works fine. Consider this patched and add the solution.

**Comment by jspenguin2017** [comment]
@uBlock-user I'll do that after v7.

**Comment by jspenguin2017** [comment]
@uBlock-user Countdown validated on server side...

**Comment by uBlock-user** [comment]
@jspenguin2017  Countdown no longer validated with `a.timewarp("setTimeout", a.matchMethod.stringExact, "1000");`

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/198#issuecomment-304454529
