### ISSUE TITLE
hirtv.hu

### ISSUE THREAD

**Issue by kovacsattila-hun** [reek/anti-adblock-killer#3194]
http://hirtv.hu/videok/181197
http://i.imgur.com/AAAU8PA.png
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by uBlock-user** [comment]
add - `@@||mno.hu^$elemhide`

**Comment by kovacsattila-hun** [comment]
No work this rule!

![hirtv](https://cloud.githubusercontent.com/assets/19515287/26024422/075b5a24-37d1-11e7-8a60-47879e6b68f3.png)

**Comment by kovacsattila-hun** [comment]
No work this rule, but it works:

`video.mno.hu#@#.goAdverticum`

**Comment by uBlock-user** [comment]
My bad, it's `@@||hirtv.hu^$elemhide`
