### ISSUE TITLE
kwejk.pl

### ISSUE THREAD

**Issue by marek45** [reek/anti-adblock-killer#320]
kwejk.pl
https://www.dropbox.com/s/xxtknhcl66zucx8/adblock5.png?dl=0
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers+http://www.certyficate.it/adblock/adblock.txt+http://www.certyficate.it/adblock/adblock_cookies.txt

Your filter @@||kwejk.pl^$elemhide on Anti-Adblock Killer whitelist rule ##div#cookies-politics so the information about cookies is displayed.

**Comment by reek** [comment]
Hi,

it is not possible otherwise I have to create a lot of filters and in addition the message cookie does not interfere with navigation

**Comment by marek45** [comment]
This problem is only in adblock plus on uBlock is not any problem.
