### ISSUE TITLE
http://urle.co/

### ISSUE THREAD

**Issue by tbs** [reek/anti-adblock-killer#3204]
Testcase: http://urle.co/3xZYaD

Adguard + any browser + Reek filter, etc..

Website message:

"Please disable Adblock to see the captcha box to proceed to the destination page."

![image](https://cloud.githubusercontent.com/assets/768954/26038262/cd3c441a-38da-11e7-9b42-80f1e36bde0b.png)

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26041067/81a63274-38e7-11e7-8eac-36ad09db8310.png)
Fixed by https://jspenguin2017.github.io/AdBlockProtector/

**Comment by uBlock-user** [comment]
Either use APS or add the filter -https://github.com/reek/anti-adblock-killer/issues/3084#issuecomment-293895007

Also as a reminder, please do NOT open a new issue without searching the issue tracker.

**Comment by tbs** [comment]
I did, but default Github search filter is for open issues, my bad, had to clear the field to find closed one.

Thanks for the feedback,
