### ISSUE TITLE
http://techdracula.com/

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#3206]

**Comment by uBlock-user** [comment]
Filter - `/wp-content/uploads/*.js`

@jspenguin2017

**Comment by jspenguin2017** [comment]
Eh, that's too aggressive
Maybe `/wp-content/uploads/*.js$domain=techdracula.com`?

**Comment by jspenguin2017** [comment]
WordPress upload folder contains files that the blog owner uploaded, it is unwanted in this case but may not be the case on other websites. So I added domain restriction.

**Comment by purevertigo** [comment]
Doesn't work with ubo

**Comment by jspenguin2017** [comment]
You may need to clear the cache, otherwise the script can be loaded from disk and uBO can't block that.

**Comment by uBlock-user** [comment]
On a second thought, an even more less aggressive filter can be used - `@@||techdracula.com^$elemhide`

**Comment by jspenguin2017** [comment]
@uBlock-user The anti adblock script is the only script that is served from the upload folder I think, `elemhide` sometimes has side effects.

**Comment by uBlock-user** [comment]
> anti adblock script is the only script that is served from the upload folder

Yes, that's why I blocked all scripts from that folder in `wp-content`. In this case `$elemhide` works fine as the classes that're being used for detection are not being inserted anymore.

**Comment by uBlock-user** [comment]
@jspenguin2017 Yet another working filter -`techdracula.com##script:inject(setTimeout-defuser.js, an_message_display)`

**Comment by jspenguin2017** [comment]
@uBlock-user Yea, that is a better filter 👍

**Comment by uBlock-user** [comment]
The script is WP anti adblock script so I already have few solutions in mind knowing the script, it's named Adblocker Notify.

**Comment by purevertigo** [comment]
I'm not sure what's going on, nothing is working. sorry.

**Comment by jspenguin2017** [comment]
What is not working? Can you provide a test link? 
![image](https://cloud.githubusercontent.com/assets/7283682/26087909/084069b6-39b1-11e7-86d9-e7b45efe8c47.png)

**Comment by purevertigo** [comment]
I get this
Adblocker detected! Please set 'Don't Run Pages On This Domain'

**Comment by jspenguin2017** [comment]
I can't reproduce it, can you provide test link and screenshot?

**Comment by purevertigo** [comment]
It might be my fault.

As I'm using uBO, none of your suggestions worked @jspenguin2017 but the fix of . @@||techdracula.com^$elemhide from @uBlock-user worked.

thanks

**Comment by uBlock-user** [comment]
All of the solutions posted by me above work for uBO as they're uBO centric. The issue is on your end, clear your cache and browsing history and start applying them one by one.
