### ISSUE TITLE
http://www.clubic.com/

### ISSUE THREAD

**Issue by relsah** [reek/anti-adblock-killer#3208]
Adblock detected.

Website : www.clubic.com

Firefox + Greasemonkey 3.11 + Anti-Adblock Killer Up-to-date + Adblock Plus

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017 can you ?

**Comment by relsah** [comment]
Sorry,
After check my installation with
https://jspenguin2017.github.io/AdBlockProtector/
All is blocked now!

Sorry.
Thanks

**Comment by uBlock-user** [comment]
Okay, the anti adblock script is third-party. Filter - `||tiptonvillepylesville.com^$third-party`
