### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by campones** [reek/anti-adblock-killer#321]
Do you realize people have to pay their hosting ??  

You probably think you like the web when actually you don't support it at all.. by the opposite

**Comment by vinctux** [comment]
Do you realize that this should not be user's concern at all? Yes, I agree, it's hard to run any hosting cheap and yes, there are people using ad networks as their only revenue income, but at the end, it's the user decision if (s)he will use an AdBlocker (and also Anti-AdBlocker) or not.
This is a very debated theme on the Internet and should not be posted as an "Issue" to the Anti-AdBlock-Killer system. This is a issue between end-users and providers, not AABK.

**Comment by reek** [comment]
@campones 
Yes hosting at a price, but it's up to you to vary your income or change the economic model.

This has harmed the web is sites that abuse the advertising and constant tracking done by advertising agencies.
