### ISSUE TITLE
vipleague.me

### ISSUE THREAD

**Issue by EmaPa88** [reek/anti-adblock-killer#322]
Link of the page: http://www.vipleague.me/
Screenshot: http://i.imgur.com/54EqdlT.png
Browser: Mozilla Firefox
Script manager: Greasemonkey
Adblocker: Adblockplus
Filterlists: Easylist, Easylist italy, Easylist privacy, facebook annoyances blocker, AakList

It worked well until this afernoon. Sometimes i had the message to disable adblock plus, but it disappeared after refreshing the page.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Install this beta version to test
https://gist.github.com/reek/dc234ea9687056bd99fe/raw/cd94f04e682f643cdb79b6d3c6942a168cfe883f/aakdev.user.js

See you
Reek

**Comment by EmaPa88** [comment]
Hi. 
I've installed the beta. No message anymore on the homepage, it appears again when i choose an event to see and it disappear if i reload the page.
It worked in this way in the last 3 days when i watched an event on the website.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by adrian5** [comment]
Hello. I'm having problems with this same website (vipleague.me) giving me an anti-adblock message. I recently switched from AdBlock Plus, which did hide the message.

Now I'm using **uBlock Origin** on _Firefox 41_ with your "Anti-Adblock Killer | Reek‎" filter list. It shows 1,241 used entries. I'm not using any script managers. The screen looks the same as OP's screenshot. If you need any more information, let me know. Thanks!

**Comment by reek** [comment]
Hi,

you need use AakScript, read instructions

**Comment by adrian5** [comment]
Thank you, I totally missed that they are complementary. Unfortunately, with the script active, the site goes into an endless loading loop, but maybe that's something that cannot be easily fixed. It appears to try loading _data.adlooxtracking.com_.
