### ISSUE TITLE
[Solved] Rarbg

### ISSUE THREAD

**Issue by Teezton** [reek/anti-adblock-killer#3229]
Seems like rarbg have some on click action, 

How to reproduce:

1. Enter [here](https://rarbgmirror.com/torrents.php)
2. Click Top 10
3. An Ad/White screen will apear

[This](https://vimeo.com/218340291) is what happens.

**Comment by uBlock-user** [comment]
It's a popunder when you click on any white space on the website. It's cookie based. Remove cache and cookies for this website and then add -

Filter - `rarbgmirror.com##script:inject(abort-on-property-read.js, open)`

@jspenguin2017

**Comment by uBlock-user** [comment]
This [script](https://rarbgmirror.com/fnmgtrvqluhioc.js) is causing the popunders.
