### ISSUE TITLE
vipleague.sx

### ISSUE THREAD

**Issue by tdbb** [reek/anti-adblock-killer#323]
http://www.vipleague.sx/
http://imgur.com/AI4y7ax
Chrome
Tampermonkey
Adblock plus
Easy list and Anti adblock killer

I posted this earlier but they updated there site already I'm pretty sure all the other vipleague sites they have updated as well.

**Comment by tdbb** [comment]
I'm just going to post there duplicate sites as well since they are essentially the same thing as they have the exact same layout and disable adblock message.

Vipleague.se
vipbox.sx/
vipbᴏx.tv

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://bc.vc/NRzHOf">Update</a> : Anti-AdBlock Killer - Userscript<br>Step 2: <a href="http://bc.vc/jGFxOb">Update</a> : Anti-AdBlock Killer - Filters for Adblockers<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
