### ISSUE TITLE
[GER] wiwo.de has an anti adblock script

### ISSUE THREAD

**Issue by Xebtria** [reek/anti-adblock-killer#3231]
http://i.imgur.com/u41g21f.png

I have reek installed on ublock (amongst others), but wiwo.de does not work. I do not visit them regularly so I can't tell since when this is the case. 

example url:

http://www.wiwo.de/politik/deutschland/klatschspalte-hoert-auf-euch-feministinnen-zu-nennen/19819374.html?share=mail

gets forwarded to

http://www.wiwo.de/impressum/nutzungshinweise/blocker/?callback=%2Fpolitik%2Fdeutschland%2Fklatschspalte-hoert-auf-euch-feministinnen-zu-nennen%2F19819374.html

**Comment by uBlock-user** [comment]
Can't reproduce.


Anti adblock script

```javascript
if(typeof iqd_mode === 'undefined')  {
	eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('0(2.8&&3 2.9===\'4\'){7 1(){0(3 c===\'4\'){5.b=a(2.8)+\'?i=\'+h(5.d)}}0(3 6!==\'4\'){6.g(7(){1()}).f()}e{1()}}',19,19,'if|bye|hcf_userconfig|typeof|undefined|location|blockAdBlock|function|cgi_adb_redirect_url|cgi_adb_granting_product|decodeURIComponent|href|IQD|pathname|else|check|onDetected|encodeURIComponent|callback'.split('|'),0,{}))
}
```

@jspenguin2017 can you reproduce ?

**Comment by uBlock-user** [comment]
Try - `wiwo.de##script:inject(noeval.js)`

**Comment by jspenguin2017** [comment]
Nope, can't reproduce neither.

**Comment by Xebtria** [comment]
@uBlock-user 

    wiwo.de##script:inject(noeval.js)
works. no overlay anymore, thanks :)
