### ISSUE TITLE
https://www.purposegames.com/

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#3236]
https://www.purposegames.com/
http://imgbox.com/upVCrZ5Z
Mozilla Firefox
I am not using a script manager
uBlock Origin

Useful information:
Filter: ||www.purposegames.com/js/helper.min.js$script,first-party
They use a minified version of BlockAdBlock in a file called "helper.min.js": https://www.purposegames.com/js/helper.min.js
Blocking the JavaScript file using the filter above lets you browse the website without being redirected to https://www.purposegames.com/adblock.

**Comment by uBlock-user** [comment]
Can't reproduce.
