### ISSUE TITLE
https://www.spineuniverse.com

### ISSUE THREAD

**Issue by tobytteh** [reek/anti-adblock-killer#3243]
https://www.spineuniverse.com

![Screenshot showing anti-adblock notice](https://i.imgur.com/TcCLC0H.png)

Chrome (58.0.3029.110) on Windows 10
uBlock Origin
EasyList + Anti-Adblock Killer + EasyPrivacy

**Comment by tobytteh** [comment]
Funnily enough, the first time it worked to simply click "Continue to Site", but now it redirects me to that notice each time.

**Comment by uBlock-user** [comment]
add - `||$third-party,script,domain=spineuniverse.com`
