### ISSUE TITLE
www.up-4ever.com

### ISSUE THREAD

**Issue by moh9090** [reek/anti-adblock-killer#3251]
https://www.up-4ever.com/nzd5cmdaccdg
http://imgur.com/a/VrWet
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

PS: anti-adblocker message appears even I disabled uBlock extension completely.

**Comment by Zhangsun321** [comment]
can't reproduce
switch to 
https://jspenguin2017.github.io/uBlockProtector/

**Comment by uBlock-user** [comment]
Install uBlockProtector.

**Comment by moh9090** [comment]
Thanks. 
It's working now
