### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by Xebtria** [reek/anti-adblock-killer#3254]
this german page shows me this currently: http://i.imgur.com/BI1NjJm.png

it used to work, since today it shows the above. the page is shown for a split second, then it switches to this.

I use ublock with this anti-adblock-killer.
I already use these custom filters for ublock for bild.de:

    @@||bild.de^$elemhide
    @@||smartadserver.com/diff/*/partners/$domain=bild.de
    @@||smartadserver.com/diff/*/smartad.js$domain=bild.de
    @@||sascdn.com^$domain=bild.de,script

and it used to work until yesterday, and since today it stopped working and shows the above thing instead.

**Comment by lain566** [comment]
Is fixed, update `uBlock filters
`https://github.com/uBlockOrigin/uAssets/commit/fa08b61d09dfd5047ba6a9bc2bdd1a9e4f29905b ,https://github.com/uBlockOrigin/uAssets/issues/426

**Comment by Xebtria** [comment]
thanks, works again!

**Comment by uBlock-user** [comment]
Remove those filters as they're not needed any longer.

**Comment by Xebtria** [comment]
indeed. removed them, site still works without ads. thanks!
