### ISSUE TITLE
coderexample.com

### ISSUE THREAD

**Issue by http403** [reek/anti-adblock-killer#3260]
https://coderexample.com/restful-api-in-lumen-a-laravel-micro-framework/
http://imgur.com/a/1aWUq
Vivaldi 1.9
Violentmonkey
uBlock Origin
uBlock Filters + uBlock Filters - Badware risks + uBlock filters - privacy + ublock filters - unbreak + AAK + easylist + malware domains + peter lowe's ad and tracking server list + easylist china

**Comment by uBlock-user** [comment]
Filter - `coderexample.com##script:inject(setTimeout-defuser.js, an_message_display)`

@jspenguin2017

**Comment by http403** [comment]
It worked beautifully, thanks!
