### ISSUE TITLE
https://shinden.pl

### ISSUE THREAD

**Issue by skip850** [reek/anti-adblock-killer#3266]
Can't watch video's on site.
On left ublock, on right site without u
![chrome_2017-06-03_22-30-04](https://cloud.githubusercontent.com/assets/13948709/26756892/7625c91c-48ac-11e7-8c46-b7de9eae36f4.png)
block.

https://shinden.pl/external-video/34848-shingeki-no-kyojin-2nd-season/view/158820

**Comment by uBlock-user** [comment]
@jspenguin2017 can you reproduce it ?

**Comment by jspenguin2017** [comment]
I don't see any of the listing, the table only has a header. Doesn't work with uBO off neither.

**Comment by uBlock-user** [comment]
I see likewise.

**Comment by skip850** [comment]
@uBlock-user @jspenguin2017 
If i understand , you dont see this?
https://streamable.com/brhkd

**Comment by jspenguin2017** [comment]
Nope. 
![image](https://cloud.githubusercontent.com/assets/7283682/26763108/275f1d84-490a-11e7-9fc7-52196c901e50.png)

**Comment by jspenguin2017** [comment]
NVM, it works now. https://shinden.pl/external-video/49827-alice-to-zouroku/view/158913

**Comment by jspenguin2017** [comment]
```JavaScript
    var handlerAddBlock = function(f){
        
        console.log('!c');
        f = function(i, el){
            $(el).css('background', 'transparent').html('<img src="/assets/skins/1/img/abp.png" height="22" alt="Nie dla AddBlocka" /> <a href="//forum.shinden.pl/index.php?threads/problemy-z-odtwarzaczami.18974/#post-425464">Jak odblokowaÄ</a> <img src="/assets/skins/1/img/abp.png" height="22" alt="Nie dla AddBlocka" />')
        };
        
        $('.change-video-player:hidden').parent().each(f);
        if(typeof window.shinden_ads == "undefined" || typeof FuckAdBlock == "undefined") {
            $('.change-video-player').parent().each(f);
        }
    }
```

**Comment by jspenguin2017** [comment]
Huh, it tries to callback to `crunchyroll.com`, but receives empty response... This script rule gets rid of the detection: 
```JavaScript
if (a.domCmp(["shinden.pl"])) {
    a.readOnly("shinden_ads", true);
}
```

Update: NVM, it requires Flash, I think this rule fixes it.

**Comment by jspenguin2017** [comment]
The `5.2` seconds countdown can't be skipped, or server will drop the request.

**Comment by skip850** [comment]
@jspenguin2017 
It's fine. thanks

**Comment by uBlock-user** [comment]
@skip850 Yes I don't. With the new test link, I was able to reproduce.
