### ISSUE TITLE
kingofdown

### ISSUE THREAD

**Issue by ghajini** [reek/anti-adblock-killer#3279]
http://kingofdown.com/
antiadblock
Ublock origin

**Comment by Giwayume** [comment]
This project is no longer maintained. [Please report at AAK-Cont](https://gitlab.com/xuhaiyang1234/AAK-Cont/issues).

**Comment by uBlock-user** [comment]
Can't reproduce.

Provide a proper test link.

**Comment by ghajini** [comment]
@uBlock-user above is proper link(homepage)
![img_20170608_201015](https://user-images.githubusercontent.com/20338483/26934279-91ca534e-4c86-11e7-87af-e1215c345a64.JPG)
Firefox for Android

Ublock origin 1.12.4
Usi
Ublock protector script and list

**Comment by uBlock-user** [comment]
Patched in uBlock Protector Script but FF and Usi is not supported by the Script so it will not work for you.

**Comment by ghajini** [comment]
Sorry don't have choice apart from using smartphone...Thank you

**Comment by uBlock-user** [comment]
add `kingofdown.com##script:inject(setTimeout-defuser.js)`

**Comment by ghajini** [comment]
That's not working..........
Also I don't see any filter/script in ublock protector for that domain

**Comment by uBlock-user** [comment]
@ghajini It works perfectly fine. Remove all cache and site data and then try again. Either the issue lies with your setup or with FF WebExtensions.

> I don't see any filter/script in ublock protector for that domain

That's because it's patched as a generic solution.
