### ISSUE TITLE
rmprepusb.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#328]
Hi, 

![http://i.imgur.com/IKvZIHf.png] (http://i.imgur.com/IKvZIHf.png)
on http://www.rmprepusb.com/tutorials/make_pe3

**Comment by reek** [comment]
Hi,

Thanks Med !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
