### ISSUE TITLE
dofuspourlesnoobs.com

### ISSUE THREAD

**Issue by Bagu** [reek/anti-adblock-killer#3284]
URL : http://www.dofuspourlesnoobs.com/la-chasse-aux-chasseurs.html
![dofuspourlesnoobs com](https://user-images.githubusercontent.com/41675/27010701-e486d44c-4eaa-11e7-9bf9-cc83e0d90b41.jpg)
https://www.noelshack.com/2017-23-7-1497180836-dofuspourlesnoobs-com.jpg

Mozilla Firefox
uBlock Origin

Base filters + french easylist + malwares lists
This happen after 15-20 seconds

**Comment by uBlock-user** [comment]
dofuspourlesnoobs.com##script:inject(bab-defuser.js)

**Comment by uBlock-user** [comment]
`dofuspourlesnoobs.com##script:inject(bab-defuser.js)`

**Comment by Bagu** [comment]
Work fine ;)
