### ISSUE TITLE
openpli.org

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#329]
Hi reek, 
on `http://forums.openpli.org/topic/16329-vuduo-webinterface-add-on/`

![openpli.org](http://i.imgur.com/w3Vmgfd.png)

Thanks for fix!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
