### ISSUE TITLE
http://www.sidereel.com

### ISSUE THREAD

**Issue by guzmelek** [reek/anti-adblock-killer#3290]
http://www.sidereel.com/tv-shows/better-call-saul
Chrome
Tempermonkey
Adblock 
EasyList + AakList
reek/anti-adblock-killer

**Comment by uBlock-user** [comment]
patched in uBlockProtector so either use AAK-Cont or remove ABP and use uBO + uBlockProtector.

**Comment by guzmelek** [comment]
Thanks!
Notification getting removed by "AAK-Cont Userscript" (not by "AAK-Cont Filter For AdBlock"
However, it also kills video itself, not only notification. 

Trying uBO + uBlockProtector combo now

**Comment by guzmelek** [comment]
uBO + uBlockProtector works like a charm! Thanks guys, impressively quick reply and resolution!
