### ISSUE TITLE
comicbook.com manages to block

### ISSUE THREAD

**Issue by elaine-jackson** [reek/anti-adblock-killer#3292]
So while trying to read [http://comicbook.com/gaming/2017/06/13/pokemon-game-confirmed-in-development-for-nintendo-switch/](url) I was blocked.

```
Browser: Safari
Extensions: Adblock Plus (list installed), Tampermonkey (script installed)
```

Could the script/list be updated to resolve this issue?

**Comment by uBlock-user** [comment]
patched in uBlockProtector so either use AAK-Cont or remove ABP and use uBO + uBlockProtector.

**Comment by elaine-jackson** [comment]
I switched to uBlockProtector :)
