### ISSUE TITLE
www.gentecheesisterealmente.com not blocked

### ISSUE THREAD

**Issue by zabi94** [reek/anti-adblock-killer#3293]
<http://www.gentecheesisterealmente.com/>
---
Google Chrome
Tampermonkey
Adblock plus
Easy List (+Italy) + Malware Domains + Easyprivacy + aaklist

**Comment by uBlock-user** [comment]
either use AAK-Cont and remove AAK or remove ABP and AAK and install uBO + uBlockProtector.

Filter - `gentecheesisterealmente.com##script:inject(abort-on-property-read.js, admaniastchk)`

@jspenguin2017

**Comment by Giwayume** [comment]
999th issue since Reek left!

**Comment by jspenguin2017** [comment]
Party for 1000th is coming soon 😆

**Comment by uBlock-user** [comment]
1000th already came @jspenguin2017 🤣 

https://github.com/reek/anti-adblock-killer/issues/3294
