### ISSUE TITLE
washingtonpost.com articles still detect ad blocker

### ISSUE THREAD

**Issue by jmseaton** [reek/anti-adblock-killer#3294]
Example URL: https://www.washingtonpost.com/world/national-security/special-counsel-is-investigating-trump-for-possible-obstruction-of-justice/2017/06/14/9ce02506-5131-11e7-b064-828ba60fbb98_story.html

The root page does not detects ad blockers, but the articles do.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jmseaton** [comment]
I just tried again and it's not being blocked.  Strange.  Closing.
