### ISSUE TITLE
onvasortir.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#330]
Hi, 
on `http://paris.onvasortir.com/`

```
@@||onvasortir.com/publicite.html?
@@||onvasortir.com/fuckadblock.js
@@||onvasortir.com^$elemhide
```

Thanks!

**Comment by mederel** [comment]
Works on nice.onvasortir.com too.
Nicely found!

**Comment by reek** [comment]
Hi,

Thanks, Med :smile: 

See you
Reek

**Comment by reek** [comment]
Hi,

The next version will disable any site using fuckadblock

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
```
@@||ww62.smartadserver.com/config.js?$script,domain=onvasortir.com
@@|http://r.sascdn.com/diff/js/smart.js$script,domain=onvasortir.com
```

**Comment by reek** [comment]
Hi,

Thanks Med :+1:

**Comment by SMed79** [comment]
Another update: `@@||onvasortir.com^$script`
https://hg.adblockplus.org/listefr/rev/38d6d0516d2b

**Comment by reek** [comment]
Thanks
