### ISSUE TITLE
breaks twine stories

### ISSUE THREAD

**Issue by erisdev** [reek/anti-adblock-killer#3300]
any time i try to open a twine story it spits up this error and usually fails to actually load anything. i figured out that the error is coming from this userscript and disabling it fixes the problem.

```
Uncaught TypeError: Cannot read property 'cssRules' of null
    at Window.onIdle (eval at E_c (:3:221), <anonymous>:5210:39)
    at <anonymous>:2:398
    at p (eval at exec_fn (:1:108), <anonymous>:42:248)
    at Object.t [as fn] (eval at exec_fn (:1:108), <anonymous>:47:316)
    at eval (eval at exec_fn (:1:108), <anonymous>:48:73)
```
<details>
<summary>full stack trace</summary>
<pre>
onIdle @ VM1161:5210
(anonymous) @ VM1123:2
p @ VM1160:42
t @ VM1160:47
(anonymous) @ VM1160:48
setTimeout (async)
(anonymous) @ VM1123:2
c.safeWindow.(anonymous function) @ VM1123:8
P.e.addEventListener @ VM1160:48
onEvent @ VM1161:1015
(anonymous) @ VM1161:5651
handlerEvents @ VM1161:5518
blockDetect @ VM1161:5773
initialize @ VM1161:105
(anonymous) @ VM1161:5780
tms_06a7844e_889c_4faa_afe2_01e7b211dfbe @ VM1161:5782
(anonymous) @ VM1123:2
Aak.name @ VM1161:3
(anonymous) @ VM1161:4
(anonymous) @ VM1161:5783
(anonymous) @ VM1123:2
E_c @ VM1123:3
E @ VM1160:59
create @ VM1160:68
e @ VM1160:16
run @ VM1160:16
(anonymous) @ VM1160:69
(anonymous) @ VM1123:2
b @ VM1123:2
(anonymous) @ VM1160:69
(anonymous) @ VM1160:69
TM_back @ VM1160:70
(anonymous) @ VM1160:70
(anonymous) @ VM1123:2
exec_fn @ VM1123:1
(anonymous) @ VM1123:11
aa @ VM1123:9
e @ content.js:6
send @ content.js:8
next @ content.js:13
(anonymous) @ content.js:26
(anonymous) @ content.js:24
sendResponseAndClearCallback @ VM1107 extensions::messaging:366
messageListener @ VM1107 extensions::messaging:398
EventImpl.dispatchToListener @ VM1100 extensions::event_bindings:388
publicClassPrototype.(anonymous function) @ VM1106 extensions::utils:149
EventImpl.dispatch_ @ VM1100 extensions::event_bindings:372
EventImpl.dispatch @ VM1100 extensions::event_bindings:394
publicClassPrototype.(anonymous function) @ VM1106 extensions::utils:149
dispatchOnMessage @ VM1107 extensions::messaging:339
</pre>
</details>

[minimal twine that triggers this issue](https://github.com/reek/anti-adblock-killer/files/1082546/anti-adblock-killer-killer.html.zip).

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development.

**Comment by erisdev** [comment]
seriously? it doesn't say that anywhere. is there a replacement?

**Comment by uBlock-user** [comment]
Yes, seriously. Unless you're living under a rock, you would know Reek left months ago. Issues are piling up. Project is dead.

Replacement ? Depends. If you're using uBlock Origin, then uBlockProtector is recommended or use AAK-Cont.

**Comment by erisdev** [comment]
no need to be rude my dude. i don't have time or energy to closely follow the development of every little thing i use.

anyways thanks for the recs. ublock protector looks dece

**Comment by uBlock-user** [comment]
> no need to be rude

Not being rude, but rather answering the argument you made where you questioned what I said and I quote

>  it doesn't say that anywhere.

If you don't have time or energy to closely follow the development, then you shouldn't question my response either and if you do, don't take it personally. My response is based on the argument you made, so it will always be blunt.
