### ISSUE TITLE
urbeez.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#331]
Hi, 
on `http://alger.urbeez.com/`

```
@@||urbeez.com^$elemhide
@@||urbeez.com/fuckadblock.js
@@||urbeez.com/publicite.html?
```

Thanks!

**Comment by reek** [comment]
Hi,

Thanks, Med :smile: 

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Another update: `@@||urbeez.com^$script`
https://hg.adblockplus.org/listefr/rev/2bceb507cc0b

**Comment by reek** [comment]
Thanks
