### ISSUE TITLE
Admiral not being blocked

### ISSUE THREAD

**Issue by roshkins** [reek/anti-adblock-killer#3311]
Link page contains anti-adblock
http://www.addictivetips.com/windows-tips/how-to-disable-automatic-driver-installation-in-windows-vista/
One screenshot
https://gyazo.com/e09d277ac989a0ad7a4ec33c6c84eef0

Your browser
Chrome Version 59.0 64-bit
Your script manager
TamperMonkey
Your adblocker
uBlock Origin
Your filterlists

uBlock filterlist backup:
,
  "userSettings": {
    "advancedUserEnabled": false,
    "alwaysDetachLogger": false,
    "autoUpdate": true,
    "cloudStorageEnabled": false,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "externalLists": "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "ignoreGenericCosmeticFilters": false,
    "largeMediaSize": 50,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "tooltipsDisabled": false,
    "webrtcIPAddressHidden": false
  },
  "selectedFilterLists": [
    "user-filters",
    "assets.json",
    "public_suffix_list.dat",
    "ublock-resources",
    "ublock-filters",
    "ublock-badware",
    "ublock-privacy",
    "ublock-unbreak",
    "easylist",
    "easyprivacy",
    "malware-0",
    "malware-1",
    "plowe-0",
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt"
  ],
  "hiddenSettingsString": "assetFetchTimeout 30\nautoUpdateAssetFetchPeriod 120\nautoUpdatePeriod 7\nignoreRedirectFilters false\nignoreScriptInjectFilters false\nmanualUpdateAssetFetchPeriod 2000\npopupFontSize unset\nsuspendTabsUntilReady false\nuserResourcesLocation unset",
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nlocalhost\nloopconversation.about-scheme\nmighty-river-43632.herokuapp.com\nmoz-extension-scheme\nopera-scheme\nvivaldi-scheme\nwww.fandango.com\nwww.reddit.com",
  "dynamicFilteringString": "behind-the-scene * 3p-frame noop\nbehind-the-scene * 3p noop",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": "",
  "filterLists": {
    "assets/user/filters.txt": {
      "off": false
    },
    "assets.json": {
      "off": false
    },
    "assets/thirdparties/publicsuffix.org/list/effective_tld_names.dat": {
      "off": false
    },
    "assets/ublock/resources.txt": {
      "off": false
    },
    "assets/ublock/filters.txt": {
      "off": false
    },
    "assets/ublock/badware.txt": {
      "off": false
    },
    "assets/ublock/privacy.txt": {
      "off": false
    },
    "assets/ublock/unbreak.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "off": false
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "off": false
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "off": false
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "off": false
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "off": false
    },
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "off": false
    },
    "assets/ublock/experimental.txt": {
      "off": true
    }
  }
}

**Comment by uBlock-user** [comment]
Filter `||$third-party,script,domain=addictivetips.com`

**Comment by roshkins** [comment]
Thank you!
