### ISSUE TITLE
androidpolice.com

### ISSUE THREAD

**Issue by nabeelio** [reek/anti-adblock-killer#3312]
full screen

site: androidpolice.com
Chrome 58.0.3029.110
manager: tampermonkey
adblocker: ublock origin + ghostery
lists: easylist + aaklist + anti-adblock(reek) + adblock removal warning list

**Comment by nabeelio** [comment]
<img width="1605" alt="screen shot 2017-06-20 at 12 33 03 pm" src="https://user-images.githubusercontent.com/99736/27347126-0d40602c-55b5-11e7-8802-ef375bab14eb.png">

**Comment by nabeelio** [comment]
Looks like it's originating from `2enm.com`, not sure who that belongs to

**Comment by uBlock-user** [comment]
Already patched on uBO, force update your uBlock filters and remove Ghostery.

**Comment by nabeelio** [comment]
Thanks
