### ISSUE TITLE
https://temp-mail.org/

### ISSUE THREAD

**Issue by SBI-boy** [reek/anti-adblock-killer#3314]
# Hi, I'm seeing this anoying warning when I try to read an incoming email, please fix it

![ver_mensaje_-_17-06-21](https://user-images.githubusercontent.com/13672854/27416234-b631cb40-56d1-11e7-834d-592ea355f96b.png)

# thanks

**Comment by SBI-boy** [comment]
Just installed https://xuhaiyang1234.gitlab.io/AAK-Cont/index.html and fixed the issue

**Comment by uBlock-user** [comment]
Can't reproduce.
