### ISSUE TITLE
http://netdna-storage.com

### ISSUE THREAD

**Issue by hatplay** [reek/anti-adblock-killer#3317]
http://netdna-storage.com/f/bUZUm8nr/LE-DakotaPayne-DevinFranco-ShawnReeve.mp4.html

![image](https://user-images.githubusercontent.com/27808164/27485767-a429b706-5860-11e7-8b63-5c81c7dcabc8.png)

Chrome
None
uBlock Origin
EasyList + AakList + Adblock Warning Removal List + uBlock Protector List

The link contains four steps pestered by ads before reaching the download page. Sometimes the first step page doesn't have the anti-adblock warning, but the following steps page will.

**Comment by uBlock-user** [comment]
@jspenguin2017 Is it still patched or they bypassed ?

**Comment by jspenguin2017** [comment]
Seems to work for me...

**Comment by jspenguin2017** [comment]
oh just kidding

**Comment by jspenguin2017** [comment]
Looks like they have a server side check... let me have a look...

**Comment by jspenguin2017** [comment]
OK, it's fixed in developer preview... 
![image](https://user-images.githubusercontent.com/7283682/27488446-50049428-57f4-11e7-90c7-c498fc288bd5.png)

**Comment by hatplay** [comment]
@jspenguin2017 , Thank you! But what am I supposed to do? Sorry for my newbie question...

**Comment by jspenguin2017** [comment]
Instructions are here: https://jspenguin2017.github.io/uBlockProtector/
You need to uninstall AAK, or there may have undefined behavior.

**Comment by hatplay** [comment]
Thank you! It works!
