### ISSUE TITLE
simply-debrid.com

### ISSUE THREAD

**Issue by mirkr** [reek/anti-adblock-killer#332]
https://simply-debrid.com/
http://i.imgur.com/Xh3ooqc.png
Google Chrome 42.0.2311.90 (64-bit)
Tampermonkey
uBlock Origin 0.9.4.4
My filters:
ITA: ABP X Files‎ (dropboxusercontent.com)
ITA: EasyList Italy‎ (adblockplus.org)
uBlock filters‎ 
uBlock filters – Privacy‎
Adblock Warning Removal List‎ 
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com)
EasyList‎ (adblockplus.org)
Peter Lowe’s Ad server list‎ (yoyo.org)
EasyPrivacy‎ (adblockplus.org)
Malware Domain List‎ (malwaredomainlist.com)
Malware domains

Thank you for your hard work :)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you soon<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by mirkr** [comment]
Thank you so much, I think I love you <3

**Comment by reek** [comment]
Thanks :grinning:
