### ISSUE TITLE
Watchfree.to ->secure.link/windscribe

### ISSUE THREAD

**Issue by techDogg** [reek/anti-adblock-killer#3320]
Can you/anyone help with this please? thanks!
Using AB, ABP, Privacy Badger, and AntiAdblock Killer.

From **watchfree.to**
Whenever I click on the link in the column with the yellow box, it takes me first to a page with windscribe site with url https://secure.link/(VERY LONG URL) before I can click another link to continue to the video website. The 2nd image below shows the page that pops up first before I can continue to the actual linked page. Is there a way to avoid this "secure.link" page all together? I am not using any windscribe addons and it appears to be hardcoded by the watchfree.to site. It happens regardless of browser used and started within the last 2ish weeks. Thanks... 
What I've tried... I tried blocking the overlay, tried adding manual filters to AB and ABP, and tried manual block using Privacy Badger.
**Image 1** 
![image](https://user-images.githubusercontent.com/18693982/27512398-7233a980-590c-11e7-8652-f03374589845.png)

**Image 2** 
![image](https://user-images.githubusercontent.com/18693982/27512407-b7595dc0-590c-11e7-8db8-7d3d597f6131.png)

**Comment by uBlock-user** [comment]
not an anti adblock issue, post on Easylist forums for cosmetic filters.

**Comment by techDogg** [comment]
Roger! thanks...
