### ISSUE TITLE
Adf.ly

### ISSUE THREAD

**Issue by Symbai** [reek/anti-adblock-killer#3324]
Detects adblocker:
http://i.imgur.com/uFbr5hu.png

Firefox 54.0
Ublock Origin 1.13.0

Example url:
http://adf.ly/564553/spbdc-512-mc17

Filterlists:
Fanboy
Reek
EasyPrivacy
EasyList
Ublock (all except experimental)

**Comment by uBlock-user** [comment]
redirects to `q.gs`

@jspenguin2017, wasn't this patched by aggressive Adfly skipper ?

**Comment by jspenguin2017** [comment]
@uBlock-user It properly skip the page for me...

**Comment by jspenguin2017** [comment]
@uBlock-user BTW, Adfly links have a IP bonded 10 seconds enforced cooldown, if the page has a timer in the middle, then you have to wait that. It will refresh automatically then bypassed like normal.

**Comment by uBlock-user** [comment]
@jspenguin2017 Doesn't work for me. I'm stuck at `q.gs`

**Comment by uBlock-user** [comment]
No visible timer here - http://q.gs/564553/bdcraft-redirect

That's the page where I get stuck

**Comment by jspenguin2017** [comment]
When I click the original link, it goes right though... 
The new link seems to be using another variable name...

**Comment by jspenguin2017** [comment]
OK, the timer doesn't show with uBO off, so I think it's just broken. I'm not sure how did you get to that page, but this linke: http://adf.ly/564553/spbdc-512-mc17 works for me.

**Comment by uBlock-user** [comment]
> The new link seems to be using another variable name...

Which new link ?

**Comment by uBlock-user** [comment]
The timer doesn't appear with uBO on either. 

I visit https://adf.ly/564553/spbdc-512-mc17 and I get to http://q.gs/564553/bdcraft-redirect there and stops and then if I click on red X at the extreme right corner, I get to the destination link.

**Comment by uBlock-user** [comment]
Console on q.gs link - https://i.gyazo.com/4dd29c1376556b2525a00aa8c9e5ae8d.png

**Comment by jspenguin2017** [comment]
@uBlock-user Are you sure that's the right destination? It says error on the page. With the `adf.ly` link, I get a download.

**Comment by uBlock-user** [comment]
@jspenguin2017 That's what I get on my end. How do you get a download ?

**Comment by uBlock-user** [comment]
Is this the destination link right  - > http://bdcraft.net/problem-occured ?

**Comment by jspenguin2017** [comment]
It sends me to http://bdcraft.net/download/?z=Sphax%20PureBDcraft%20512x%20MC17

**Comment by jspenguin2017** [comment]
It seems to require `adf.ly` referrer... You can use `curl` to fake the header...

**Comment by uBlock-user** [comment]
Yeah forget it, it's pointless, something is screwing it up on my end.

**Comment by Symbai** [comment]
Hm for me the timer will not appear. Using Ublock log I can see adfly redirect me to a fallover url. Then after some time the timer starts by 5 seconds. When reaching 1 second it stops and it shows me the adblock detect message. Is there any log or something I can provide?

**Comment by jspenguin2017** [comment]
@Symbai Sorry, we were a bit off topic... I don't have a solution for Firefox.

**Comment by ghajini** [comment]
Need to allow `ajax.googleapis.com` at start page then things go right..... Also @jspenguin2017  in your list `advert.js` is allowed?

**Comment by jspenguin2017** [comment]
`advert.js` is whitelisted as part of AAK's generic anti-bait. I don't see why that matters as the bypasser will be triggered before the document even has a `<body>`.

**Comment by jspenguin2017** [comment]
I'm not sure what sites will be affected if I remove those filters... I'll restrict them to first party.

**Comment by jspenguin2017** [comment]
There are way too many rules in the original AAK and I can't clean all of them up, so we'll have to stay with some whitelists...

**Comment by uBlock-user** [comment]
> Need to allow ajax.googleapis.com at start page then things go right

That doesn't make any difference here. I already had the domain whitelisted, but still remains broken on my end.

**Comment by ghajini** [comment]
Try Firefox/chrome with VPN and `googleapis` whitelisted

**Comment by jspenguin2017** [comment]
@ghajini No, with my bypasser, you can block everything, except the main document and inline script.

**Comment by uBlock-user** [comment]
Again, VPN won't make any difference either, it's not GeoLocked. Please don't make any guesses here unless you know the cause.

**Comment by uBlock-user** [comment]
The destination domain is Geo-Locked apparently. They are trolling visitors based on their location. Changing location to US and it works.

**Comment by ghajini** [comment]
@uBlock-user Iam not guessing anything...my antivirus plugin and my ISP blocks scripts on this adf.ly related website......
Many antiviruses out there blocks scripts on this page due to pups 
See here...
https://github.com/uBlockOrigin/uAssets/issues/107


I have all relevant info abt this and thus I decided to skip page of adf.ly in ublock protector

**Comment by uBlock-user** [comment]
@ghajini whitelisting googleapis was a guess on your part and it didn't work on my end because whitelisting them or not there is no change in the issue I'm facing and you did the same thing again, but fortunately the second guess worked out and it was Geo-Lock that was trolling me rather.

**Comment by ghajini** [comment]
That's not guess actually.....iam fine with my guesses what you call....

**Comment by uBlock-user** [comment]
Well apparently you have a different definition of guesswork then, otherwise I stand with mine.
