### ISSUE TITLE
onvasortir.com

### ISSUE THREAD

**Issue by Dusteuh** [reek/anti-adblock-killer#333]
http://montpellier.onvasortir.com/ovsadblock.php
http://i.imgur.com/NHEWkZK.png
Google Chrome
Tampermonkey
Adblock Plus
Adblock Warning Removal List, Liste FR+EasyList, AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Dusteuh** [comment]
All is up to date for me, but the website still detect adblock. What should I do ?

**Comment by Dusteuh** [comment]
http://montpellier.onvasortir.com/ovsadblock.php
http://i.imgur.com/4cvoIve.png

**Comment by reek** [comment]
Try again to update AakList and click on the link below
http://montpellier.onvasortir.com/

**Comment by Dusteuh** [comment]
Thank you, after a chrome reboot and an update that works !
