### ISSUE TITLE
Ideal.es

### ISSUE THREAD

**Issue by antonio8909** [reek/anti-adblock-killer#3338]
![captura](https://user-images.githubusercontent.com/5004766/27803306-1fc3e722-6029-11e7-8326-52da0d8d6231.PNG)
Google Chrome
Tampermonkey
AAK-Cont Userscript For AdBlock
Ads Skipper
Anti-Adblock Killer | Reek

Adblock
Adblock Plus
Ublock

**Comment by uBlock-user** [comment]
Remove Adblock, Adblock PLus and only keep uBlock Origin, running multiple adblockers will cause this to happen. Also Remove AAK and Ads-Skipper and only keep AAK-Cont.

Filter - `||vocento.com/adblock-detector/`

@jspenguin2017

**Comment by antonio8909** [comment]
Hi @uBlock-user 

Ads-Skipper is for adf.ly so I can't disable it.

Thanks for your support. It worked! :)

**Comment by jspenguin2017** [comment]
@antonio8909 uBlock Protector can bypass Adfly too. AAK-Cont can as well, but it is not very reliable.

**Comment by uBlock-user** [comment]
Use uBlock Protector and remove any and all such scripts, you don't need those given your setup uBP will serve you better.
