### ISSUE TITLE
movie-box.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#334]
http://www.movie-box.pl/195/Nie-ma-bata-na-Polaka.html
Mozila Firefox
Greasemonkey ( scripts beta version from https://github.com/reek/anti-adblock-killer/issues/300) )
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers 

On this page scripts from Greasemonkey remove video. If I disable Greasemonkey then I have notification to disable adblock.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
