### ISSUE TITLE
www.laverdad.es

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#3345]
Hello, in this Spanish newspaper, I get an anti adblock.
Adblock: ublock
Browser: Google Chrome
uBlock List: Ublock filters, ublockfliters privacy, ublock filters unbreak, adblock warning removal list, anti-adblock killer reek, easylit, ublock protector list, easyprivacy, malware domains list, malware domains, EasyList Spanish.
Screenshot: https://ibb.co/maWSaF

Anyone can help me? thanks

**Comment by uBlock-user** [comment]
add - `/adblock-detector/`

**Comment by ghost** [comment]
Hello, how do i have to add that in ublock origin?

**Comment by ghost** [comment]
Okey fixed blocking this `http://www.laverdad.es/adblocker/layer.html`
