### ISSUE TITLE
http://www.clubedohardware.com.br/

### ISSUE THREAD

**Issue by InitialDet** [reek/anti-adblock-killer#3348]
http://www.clubedohardware.com.br/

![screnshot](http://i.imgur.com/cJ05UAq.png)

Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by uBlock-user** [comment]
`clubedohardware.com.br##script:inject(overlay-buster.js)`

same as #3330 

@jspenguin2017 adding the domain to the existing solution should kill it.

**Comment by jspenguin2017** [comment]
I'm going with the CSS solution as `overlay-buster` makes the screen flashes.

**Comment by uBlock-user** [comment]
Yes that's what I meant, add it to the CSS solution.
