### ISSUE TITLE
career.guru99.com

### ISSUE THREAD

**Issue by mahmoudkandeel** [reek/anti-adblock-killer#3352]
career.guru99.com

https://career.guru99.com/top-22-linq-interview-questions/

http://imgur.com/a/clG64

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
@jspenguin2017 can you ?

**Comment by jspenguin2017** [comment]
`||a.optnmstr.com^`

**Comment by uBlock-user** [comment]
Might as well block the entire domain via `||optnmstr.com^$third-party`

It doesn't have a homepage and is only used for loading anti adblock script.

**Comment by jspenguin2017** [comment]
Not just anti-adblock, also overlay and other nags. Their homepage is here: http://optinmonster.com/
