### ISSUE TITLE
runnersworld.com

### ISSUE THREAD

**Issue by colmoneill** [reek/anti-adblock-killer#3354]
http://www.runnersworld.com/run-matters/junk-miles-thats-rubbish
http://imgur.com/8XSFdKF
Mozilla Firefox
Greasemonkey
Adblock Plus
AakList

![](http://imgur.com/8XSFdKF)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
`@@||runnersworld.com^*ads.`

**Comment by colmoneill** [comment]
@uBlock-user were you able to reproduce then?

**Comment by uBlock-user** [comment]
Obviously not, I merely provided the whitelisted filter since you're on ABP, it's already patched on uBO.

**Comment by colmoneill** [comment]
Ok thanks @uBlock-user
