### ISSUE TITLE
voxnow.de

### ISSUE THREAD

**Issue by razzor1984** [reek/anti-adblock-killer#336]
Hello,
the tv ad-clips arnt blocked anymore. When you start a Flash clip @voxnow.de you get at the start a smal ad and then after every 15 - 20 minutes. Im not sure what they changed. A few months ago it worked great, but now its broken :(

Example link: http://www.voxnow.de/auto-mobil/automesse-shanghai.php?container_id=204189&player=1&season=0

Best regards 
Razzor

**Comment by reek** [comment]
Hi,

Unfortunately, I did not find a solution.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
