### ISSUE TITLE
goalsarena.org

### ISSUE THREAD

**Issue by alepsrt** [reek/anti-adblock-killer#3365]
Not working with video in goalsarena:
"To view this video, please disable your ad blocker for our site."

http://www.goalsarena.org/en/video/friendly/11-07-2017-lugano-ac-milan-friendly.html
http://oi67.tinypic.com/349e3x0.jpg
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

More info: 
@@/html5player.gamezone.com/ads.js
@@||amazonaws.com$script,domain=goalsarena.org
@@||goalsarena.org^$generichide
won't work.

**Comment by uBlock-user** [comment]
@jspenguin2017 badfilter from Easylist - `/\.com\/[0-9]{2,9}\//$third-party,xmlhttprequest` breaks zeus player.

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development use AAK-Cont and report there.

**Comment by alepsrt** [comment]
Install from here: https://xuhaiyang1234.gitlab.io/AAK-Cont/index.html
And issues: https://gitlab.com/xuhaiyang1234/AAK-Cont/issues

Thanks.

Just for info, the video is not loaded.

**Comment by uBlock-user** [comment]
> Just for info, the video is not loaded.

because of this filter I mentioned in https://github.com/reek/anti-adblock-killer/issues/3365#issuecomment-314687415 That broke the player.

**Comment by jspenguin2017** [comment]
That is a generic filter, I can't just override it, I added an exception for this domain.

**Comment by uBlock-user** [comment]
It's a bad filter added 3 days ago by Easylist and `$badfilter` works if that's what you meant. It's too generic and will break unintended things. Also not just a generic one, but a bad generic regex.

**Comment by uBlock-user** [comment]
Nvm gorhill marked it bad - https://github.com/uBlockOrigin/uAssets/commit/b5404072e3f60b95a18ae0e75348d16217834cf8

**Comment by jspenguin2017** [comment]
It's up to him, I won't be overriding generic filters. https://github.com/easylist/easylist/commit/936980d97cf0e10ce4a21ba4b8e279f736eb0564

**Comment by jspenguin2017** [comment]
Well, that badfilter rule is outdated... https://github.com/easylist/easylist/commit/936980d97cf0e10ce4a21ba4b8e279f736eb0564

**Comment by uBlock-user** [comment]
It doesn't matter either way you will have to whitelist and unbreak it every now and then, given how nonrestrictive it is.
