### ISSUE TITLE
cleveland.com

### ISSUE THREAD

**Issue by Lologrampersand** [reek/anti-adblock-killer#3368]
[http://cleveland.com](http://cleveland.com)
[http://imgur.com/7TlGQDK](http://imgur.com/7TlGQDK)
Google Chrome
TamperMonkey
uBlock Origin v1.13.2
EasyList + uBlock Protector

Reproducible after cycling through any article>Home 3-4 times at most.

**Comment by uBlock-user** [comment]
```
/mms-client.js
/messaging.js
```

@jspenguin2017

**Comment by Lologrampersand** [comment]
Thank you!
