### ISSUE TITLE
https://swissadspaysfaucet.com/facuet

### ISSUE THREAD

**Issue by Linden10** [reek/anti-adblock-killer#3375]
https://swissadspaysfaucet.com/faucet/
http://i.imgur.com/kGQFou1.png

Google Chrome (+Firefox)
Tampermonkey (+Greasemonkey on FF)
uBlock Origin (Adblock Plus on FF)
Easylist + AakList + Adblock Warning Removal List (Same on both FF and Chrome)

When you visit the faucet page, the site automatically redirects to:
https://swissadspaysfaucet.com/faucet/blocker

It happens on both FF and Chrome with the same lists.

**Comment by uBlock-user** [comment]
Anti adblock script


```javascript
var adBlockEnabled = false;
    var testAd = document.createElement('div');
    testAd.innerHTML = '&nbsp;';
    testAd.className = 'adsbox';
    document.body.appendChild(testAd);
    window.setTimeout(function() {
      if (testAd.offsetHeight === 0) {
        adBlockEnabled = true;
      }
      testAd.remove();
      if(adBlockEnabled == true)
        window.location = 'https://swissadspaysfaucet.com/faucet/blocker';
    }, 100);
```

**Comment by uBlock-user** [comment]
`swissadspaysfaucet.com##script:inject(abort-on-property-read.js, adBlockEnabled)`

@jspenguin2017

**Comment by Linden10** [comment]
Been working great to this day!
Closing.

**Comment by Linden10** [comment]
Been working great to this day!
Closing this issue.
