### ISSUE TITLE
https://bonusbitcoin.co/faucet

### ISSUE THREAD

**Issue by Linden10** [reek/anti-adblock-killer#3377]
https://bonusbitcoin.co/faucet
http://i.imgur.com/d4UtuLy.png

Google Chrome
Tampermonkey
uBlock Origin
AakList + Easylist + Adblock Warning Removal List

When you attempt to claim on the site, you get that message.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
does it require an account ?

**Comment by Linden10** [comment]
Requires an account, yes.
Should be easy to make one.

The message appears when you're logged in and about to claim your free bitcoins.

**Comment by uBlock-user** [comment]
I'm not going to make one as I don't have any use there. Provide an account yourself.

**Comment by Linden10** [comment]
how can I contact you privately?
I'll provide my account with temp password for you to test.

**Comment by Linden10** [comment]
Actually here's an fake account I made just for you:

"As promised, edited out login details after everything is done!"

**Comment by jspenguin2017** [comment]
This looks like zapVM and linkVM, let me try that solution

**Comment by jspenguin2017** [comment]
There must be a better way, but since I already have the zapVM solution code there... 
![image](https://user-images.githubusercontent.com/7283682/28384794-2901456c-6c83-11e7-9c7b-97c874a0803d.png)

**Comment by jspenguin2017** [comment]
I need a solid generated code execution (CSP bypassing) framework. All I have to do is patch that `adBlocked: false`... I don't want to paste like 50 lines of code for that...

**Comment by jspenguin2017** [comment]
Not perfect, but good enough. I probably would need it later anyway.

**Comment by jspenguin2017** [comment]
I tested it 3 times, seems to work for me. Thanks for the test account. 

I'll leave zapVM and linkVM as is, the code won't be much shorter with the runtime.

**Comment by uBlock-user** [comment]
Thanks for the account.

Patched in uBP.

Once you solve the recapcha, you should see this - 

https://i.gyazo.com/75b64967e08ff51e070f45040f9faf20.png

**Comment by uBlock-user** [comment]
@jspenguin2017 Can something be done about the 15 mins claim timer seen here - 

https://i.gyazo.com/3c2f529c41511b7eb06c673c7098f011.png

**Comment by jspenguin2017** [comment]
That is enforced on server side, as you will see the same timer when you refresh.

**Comment by Linden10** [comment]
Okay, everything's been working out great for the past few days!
Thanks and now closing the issue (until something happens in the future...)
