### ISSUE TITLE
onvasortir.com

### ISSUE THREAD

**Issue by Noruas** [reek/anti-adblock-killer#338]
Doesn't block onvasortir.com script anymore.

**Comment by reek** [comment]
Hi,

Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Try Update AakList

**Comment by SMed79** [comment]
@Noruas https://github.com/reek/anti-adblock-killer/issues/330#issuecomment-98453178
