### ISSUE TITLE
http://animeflv.me/*

### ISSUE THREAD

**Issue by elixs** [reek/anti-adblock-killer#3382]
http://animeflv.me/*
example : http://animeflv.me/Ver/68842/rewrite-moon-and-terra-2017/episodio-4/
Google Chrome
TamperMonkey
Adblock Plus 1.13.3
EasyList +Adblock Warning Removal List + AakList
![block](https://user-images.githubusercontent.com/23102267/28374335-6c3fde30-6c72-11e7-9e33-688742bb14be.png)

**Comment by elixs** [comment]
With uBlock Origin worked fine.

**Comment by uBlock-user** [comment]
Can't reproduce.
