### ISSUE TITLE
captchme.com

### ISSUE THREAD

**Issue by joihn** [reek/anti-adblock-killer#339]
hello

I can't see the captcha on this site because it detect my adblock

https://freedom-ip.com/compte.php
https://freedom-ip.com/forum/login.php

screenshot
http://postimg.org/image/uu81vn5tj/

chrome/tampermonkey/adblock

my filter
http://postimg.org/image/s2b9xd69p/

apparently you already worked for this website, but it doesn't work anymore
https://github.com/reek/anti-adblock-killer/issues/219

thanks for your work :)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
