### ISSUE TITLE
cwtv.com

### ISSUE THREAD

**Issue by WizardShotTheFood** [reek/anti-adblock-killer#340]
http://www.cwtv.com/shows/the-flash/the-trap/?play=1a214b68-6df9-44de-8577-994139263c69
http://imgur.com/4XB0eGk
Google Chrome
Tampermonkey
uBlock
EasyList

**Comment by reek** [comment]
Hi,

I can not help you because the content is geo locked

**Comment by WizardShotTheFood** [comment]
Well, I'm not sure if it'll help any, but the adblocker message appears to be produced by the following bit of inline Javascript:

$(document).ready(function() {
   if (typeof CLAPI != 'undefined') {
		CLAPI.IsAdBlocking(function(isAdBlocking, hasAdBlocked) {
			// respond to ad block state
			//console.log('IsAdBlocking ' + isAdBlocking); console.log('hasAdBlocked ' + hasAdBlocked);
			if (isAdBlocking) {
			    $('#videocontainerwrap').html("<h4><p>Oops, you have an ad blocker enabled!</p><p>To watch this episode, please disable it and refresh the page.</p></h4>");
		    }
		});
	}    
});

**Comment by reek** [comment]
Hi,

I'll see if I can find a solution and I would do the test yourself

**Comment by WizardShotTheFood** [comment]
I'll be happy to test out any possible solutions you come up with.

**Comment by reek** [comment]
Hi,

Can you test beta ?
https://gist.github.com/reek/dc234ea9687056bd99fe/raw/86b217606f6f3163517b846d93aaa625cc8a036d/aakdev.user.js

**Comment by WizardShotTheFood** [comment]
No change; guess that would have been a bit too easy. I poked around further and found an extremely unindented bit of JavaScript, though. It does appear to have multiple references to ads and/or the blocking thereof, so I'm going to guess that's where the important stuff is happening.

http://images.cwtv.com/inc/js/videolib-2.0.1.js

**Comment by reek** [comment]
Try Firefox + Greasemonkey

For Chrome you must use Tampermonkey

**Comment by reek** [comment]
New beta: https://gist.github.com/reek/dc234ea9687056bd99fe/raw/2065cf476cadb5bb8f591f186f087cbb1be18637/aakdev.user.js

**Comment by WizardShotTheFood** [comment]
Hmm, okay, looks like the problem is unique to Chrome and not Firefox; new beta doesn't work in the former either, but isn't needed at all for the latter. Might be limits on what all Chrome can actually strip out right now, perhaps.

**Comment by WizardShotTheFood** [comment]
(And I had Tampermonkey installed on Chrome the whole time, not Greasemonkey. Sorry about that.)

**Comment by reek** [comment]
try add this rule ||dzxxxg6ij9u99.cloudfront.net/wb.js$script,domain=cwtv.com

**Comment by WizardShotTheFood** [comment]
That did the trick. Thanks.

**Comment by reek** [comment]
Great, rule added to AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
