### ISSUE TITLE
Add "Tampermonkey" for Firefox on the instruction page

### ISSUE THREAD

**Issue by davidhedlund** [reek/anti-adblock-killer#3400]
https://github.com/reek/anti-adblock-killer#instruction says:

> Instruction
> Step 1: ScriptManager
> 
>     Firefox: Greasemonkey or Scriptish (Not supported/Addon has been discontinued)
>     Chrome: Tampermonkey or Native (Not supported)
>     Opera: Tampermonkey or Violentmonkey
>     Safari: Tampermonkey or NinjaKit
>     Edge: Tampermonkey
> 
>     Note: After installation (which requires restarting your browser), you are now ready to install userscripts.

I tried the [test](http://tinyurl.com/qecfa7w) page and can confirm that Tampermonkey works with Firefox. So can you please update https://github.com/reek/anti-adblock-killer#instruction by replacing:

> Firefox: Greasemonkey or Scriptish (Not supported/Addon has been discontinued)

with

> Firefox: Tampermonkey or Greasemonkey

By the way, [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/?src=search) is now "Compatible with Firefox 57+" so this is of extra importance now.

**Comment by davidhedlund** [comment]
I tried the [test](http://tinyurl.com/qecfa7w) page and can confirm that Tampermonkey works with Firefox. So can you please update https://github.com/reek/anti-adblock-killer#instruction by replacing:

> Firefox: Greasemonkey or Scriptish (Not supported/Addon has been discontinued)

with

> Firefox: Tampermonkey or Greasemonkey

By the way, [Tampermonkey](https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/?src=search) is now "Compatible with Firefox 57+" so this is of extra importance now.

**Comment by uBlock-user** [comment]
This project is dead. AAK-Cont is the successor.

**Comment by davidhedlund** [comment]
@uBlock-user Official link to AAK-Cont please.

**Comment by uBlock-user** [comment]
https://xuhaiyang1234.gitlab.io/AAK-Cont/
