### ISSUE TITLE
Ad a separate repo for core issues

### ISSUE THREAD

**Issue by davidhedlund** [reek/anti-adblock-killer#3401]
uBlock Origin have its own uAssets repository for URL's. I suggest that you open a repo for Core issues for AAK.

**Comment by davidhedlund** [comment]
Examples

URL issues
* [businessinsider.com ](https://github.com/reek/anti-adblock-killer/issues/3398)
* [leakedearly.gdn](https://github.com/reek/anti-adblock-killer/issues/3397)

Core issues:
* [Add "Tampermonkey" for Firefox on the instruction page](https://github.com/reek/anti-adblock-killer/issues/3400)
* [Typo on Aak.intoString() method](https://github.com/reek/anti-adblock-killer/issues/3378)

**Comment by uBlock-user** [comment]
and who's going to do that ? This project was abandoned by reek since 9 months. This whole project is dead.

**Comment by davidhedlund** [comment]
@uBlock-user Why have no one forked it yet then?

**Comment by uBlock-user** [comment]
https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by davidhedlund** [comment]
@uBlock-user Thank you!
