### ISSUE TITLE
carambatv.ru

### ISSUE THREAD

**Issue by TagerW** [reek/anti-adblock-killer#343]
Hello dear developers.
The site karamba.tv there are many different video. When you open any of them can not watch the video as 720p, 240p is available only ...
//http://carambatv.ru/humor/wasted/amerikanets-v-shoke/

http://imgur.com/xZkg0j4

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by TagerW** [comment]
Very quickly you answer - I am pleased !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
