### ISSUE TITLE
rookie.com.pl

### ISSUE THREAD

**Issue by stronkmen** [reek/anti-adblock-killer#344]
http://rookie.com.pl
http://i.imgur.com/rn6IA83.jpg
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Easy Privacy + Fanboy's Social Blocking List + AakList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by stronkmen** [comment]
antiadblock still shows up :(

**Comment by reek** [comment]
force update of AakList
