### ISSUE TITLE
wowebook.org

### ISSUE THREAD

**Issue by grzglo** [reek/anti-adblock-killer#345]
http://www.wowebook.org/
http://imgur.com/yFnQHLL
Mozilla Firefox 37.0.2
Scriptish 0.1.11
Adblock Plus
EasyList

**Comment by maynak00** [comment]
no message with uBlock Origin+Tampermonkey Beta+Chromium latest x64.
http://i.imgbox.com/x8NqoCwF.png

**Comment by reek** [comment]
Hi,

You need install Greasemonkey (Scriptish contains bugs)
https://github.com/reek/anti-adblock-killer#step-1-script-manager-install

See you
Reek
