### ISSUE TITLE
shorte.st

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#346]
Hello, 
an anti-adblock detect and bypasse adblocker on `http://sh.st/h4Ilk`
```
http://static.shorte.st/js/packed/smeadvert-intermediate-ad.js?v1.22.2
http://static.shorte.st/js/packed/redirect-blocker-intermediate-ad.js?v1.22.2
```
```
        var imageData = "data:image/png;base64,/9j/4AAQSkZJRgAB..............."; 
        app.adsBlockerDetector(function() {
            ga('send', 'event', 'antyadblock', 'adblock_detected', 'bestsellers_500_500', {'nonInteraction': 1});
            ga('set', 'dimension8', 'adblockdetected');
            var div = document.createElement('div');
            div.setAttribute(
                'style',
                    "width: 100%;" +
                    "text-align: center;"
            );
            var anchor = document.createElement('a');
            anchor.setAttribute('href', "http://bit.ly/1JUng7u");
            anchor.setAttribute('target', "_blank");
            bean.on(anchor, "click", function(){
                ga('send', 'event', 'antyadblock', 'ad_clicked', 'bestsellers_500_500');
            });
            var img = document.createElement('img');
            img.setAttribute('style', "border: none;");
            img.setAttribute('src', imageData);
            anchor.appendChild(img);
            div.appendChild(anchor);
            document.body.insertBefore(div, document.getElementById('fb-root'));
        });
```

**Comment by maynak00** [comment]
using with AdsBypasser + uBlock Origin= no message and skipping fast(needs some seconds but no countdown)
https://adsbypasser.github.io/
browser: Chromium x64

**Comment by SMed79** [comment]
@maynak00 I already know about **[AntiAdware](https://github.com/HandyUserscripts/AntiAdware)** and use it but unfortunately you can not inform all **AakList** users !

**Comment by reek** [comment]
Hi,

I detected a bug that prevented the display of the skip button, caused by AakScript.
Use Adsbypasser pending correction AakScript

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
