### ISSUE TITLE
mobilevids.org

### ISSUE THREAD

**Issue by BigRigAssassin** [reek/anti-adblock-killer#347]
http://imgbox.com/R7bKmDFd
Google Chrome
Tampermonkey
ABP
-EasyList
-AakList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Already killed, try update AakList or https://github.com/reek/anti-adblock-killer#help
