### ISSUE TITLE
worldofgnome.org

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#348]
Hi, 
on `http://worldofgnome.org/kororaa-17-what-fedora-should-be/`
```
worldofgnome.org#@#.google-ad
worldofgnome.org#@##wog-300x250-ads
```
![worldofgnome.org] (http://i.imgur.com/0iQYh0G.png)

Thanks!

**Comment by reek** [comment]
Hi,

Thanks Med :+1:

**Comment by reek** [comment]
Added !
