### ISSUE TITLE
www.dilidili.wang

### ISSUE THREAD

**Issue by f32y** [reek/anti-adblock-killer#3483]
A Chinese animation website

**Comment by f32y** [comment]
http://www.dilidili.wang/newjs/main.js

```js
    $.ajax({
    url: "http://static.jfrft.com/js/main_list.js",
    dataType: "script"
    }).done(function(){   
        $.ajax({
            url: "http://static.jfrft.com/js/main_video.js",
            dataType: "script"
            }).fail(function(){
                document.body.innerHTML='<h2 id="adb-contant">WHATEVER</h2>';
            });
    }).fail(function(){
        document.body.innerHTML='<h2 id="adb-contant">WHATEVER</h2>';
    });
```

**Comment by uBlock-user** [comment]
Filter - `dilidili.wang##script:inject(abort-on-property-read.js, $.ajax)`

**Comment by f32y** [comment]
It works :)
Thank you

**Comment by f32y** [comment]
uBlock element picker won't work with this filter...

**Comment by uBlock-user** [comment]
Works fine.

**Comment by uBlock-user** [comment]
![](http://i.imgur.com/WdfKvgu.png)

**Comment by jspenguin2017** [comment]
I thought that filter breaks thumbnails... ? #3388

**Comment by f32y** [comment]
select an element and click the "Create" button  the element picker won't disappear but becomes transparent. If I refresh the page, the element I picked appears again.

![](http://i.imgur.com/edc8S1h.jpg)

**Comment by uBlock-user** [comment]
I never mentioned `$.ajax` there, did I ? Also apparently, no thumbnails were broken on my end.

**Comment by uBlock-user** [comment]
The thumbnails issue comes from the http:// protocol version of the site which causes connection reset. Use https:// and an error will appear click on proceed anyway and the thumbnails load fine and the connection reset issue doesn't appear in the console.

**Comment by uBlock-user** [comment]
> select an element and click the "Create" button the element picker won't disappear but becomes transparent. If I refresh the page, the element I picked appears again.

Nothing to do with the filter, I can reproduce it after removing the filter, so either the website is screwed up or it is doing on purpose or a bug in uBO itself.

**Comment by uBlock-user** [comment]
FYI it's patched by uBlock Protector, so if you're on Chrome, install that extension and remove that filter.

**Comment by f32y** [comment]
I installed both Anti Adblock-killer and uBlock Protector and everything works fine. Thank you.

**Comment by jspenguin2017** [comment]
That might cause conflict, don't use the original AAK.
