### ISSUE TITLE
A question about filters

### ISSUE THREAD

**Issue by gomoku** [reek/anti-adblock-killer#3484]
WORK:
```
$popup
$script
exampleurl1.com$popup 
exampleurl1.com$script
$script,domain=exampleurl1.com|exampleurl2.com
```

DON'T WORK:
```
exampleurl1.com,exampleurl2.com$script
exampleurl1.com,exampleurl2.com$popup
$popup,domain=exampleurl1.com|exampleurl2.com
```

The same happens on:
both FF54.0.1 & Opera 46
both AdBLock Plus 2.9.1 & uBlock Origin 1.13.8
Windows 7 SP1 64bit

Why are some of the filters not working?
Are the filters working for you?

**Comment by uBlock-user** [comment]
The second way is wrong and not a supported syntax. Use the working way.

**Comment by gomoku** [comment]
1) I've used that "wrong" syntax because I've found it in uBlock filters:
`*$popup,third-party,domain=nowvideo.ag|nowvideo.co` 
so I guess it is working, but if not, so why is it even present in uBlock filters then?, 

2) But if is working, so why is not working this one then:
`*$popup,domain=exampleurl1.com|exampleurl2.com` ?

3) And if you say that's wrong, so why this one is working then?:
`*$script,domain=exampleurl1.com|exampleurl2.com`

As for the current solution I see this one is working: `exampleurl1.com$popup,domain=exampleurl2.com|exampleurl3.com`
but I would like to know answers for the questions above.

EDIT: this is odd because `*$popup,domain=exampleurl1.com|exampleurl2.com` is working now,
but I tried both in the past:
```
 $popup,domain=exampleurl1.com|exampleurl2.com
*$popup,domain=exampleurl1.com|exampleurl2.com
```
 and none of them was working. 

So why these ones (without *):
`$script,domain=exampleurl1.com|exampleurl2.com` 
`$script`
`$popup`
are even working?

**Comment by jspenguin2017** [comment]
I am working on a project that will show you the internals of a filter, I almost have network filter parser working, I added a bunch of logs so you know what uBO changes and what are equivalent. 

https://github.com/jspenguin2017/uLint
https://github.com/jspenguin2017/uLint/blob/master/ubo-engines/static-network-debug.js

&nbsp;

Now to answer your question: 

`exampleurl1.com,exampleurl2.com$script` creates a `FilterPlain` that looks for `exampleurl1.com,exampleurl2.com` in urls, so it will match `https://example.com/js/exampleurl1.com,exampleurl2.com/example.js`, which is not exactly what you want. To fix it: `/^https?:\/\/exampleurl(?:1|2)\.com(?:\/|:)/$script`, although this might not be a format that you are looking for either, but it does allow you to combine the filters, and it might be slightly faster than two filters, but it will be a huge pain to maintain later on. 

`$popup,domain=exampleurl1.com|exampleurl2.com` creates a `FilterOriginHitSet` which wraps `FilterTrue`, so it will block all popup on those (exampleurl1.com and exampleurl2.com) domains, I'm not sure what you are testing, it won't block popup to those domain, only from.

**Comment by jspenguin2017** [comment]
`*$script,domain=exampleurl1.com|exampleurl2.com` will, again, create a `FilterOriginHitSet` which wraps `FilterTrue`. So it will block all scripts on those domains. 

uBO does sometimes throw out filters that it judge too slow, and it is done silently which could be frustrating, I will expose all internal operations in uLint. 

uBO has a pretty bad wiki, a lot of stuff are missing, I heard they are in patch notes, but there are like 170 patches and it's kind of a pain to go over all of them. I'm just reading uBO source code to figure out how it parses stuff, I'm almost done with static network filter, next step is cosmetic / scriptlet filter and main controller which handles choosing the right parser and removing comments.

**Comment by uBlock-user** [comment]
BY "wrong" I meant these filters

```
exampleurl1.com,exampleurl2.com$script
exampleurl1.com,exampleurl2.com$popup
```

The third one should work.

**Comment by uBlock-user** [comment]
You have got too many questions which are causing me the confusion now, so I will answer the first three only.

1) The first one is a valid syntax and should work and works for me, if it's not working for you, investigate and try to reproduce it, and in case you're able to reproduce at will then open an issue at the uBO repo.

2) Same as 1)

3) Because it's valid and I never said that it's wrong. You posted the working ones and you posted the not working ones, the first two not working ones are invalid, so there you go.

**Comment by uBlock-user** [comment]
You either do this way - `||exampleurl1.com^$popup`  and  `||exampleurl2.com^$popup`

OR

`||$popup,domain=exampleurl1.com|exampleurl2.com`

This will also do `$popup,domain=exampleurl1.com|exampleurl2.com`

Same for all other `$type` directives.

**Comment by uBlock-user** [comment]
Also there' s hardly any detailed documentation on this in the wiki, so you will have to learn and experiment by yourself.

**Comment by uBlock-user** [comment]
FYI, this is not uBO support issue tracker, you're better off asking it here - https://github.com/uBlockOrigin/uAssets/issues with any further questions.

**Comment by gomoku** [comment]
_**LAST TIME EDITED 09.08.2017 09:08 CEST**_

@jspenguin2017

**1.) :white_check_mark: ████████████████████████████████████████████████████████████**
First issue:
**A**
> `exampleurl1.com,exampleurl2.com$script` creates a FilterPlain that looks for `exampleurl1.com,exampleurl2.com` in urls, so it will match `https://example.com/js/exampleurl1.com,exampleurl2.com/example.js`, which is not exactly what you want. To fix it: `/^https?:\/\/exampleurl(?:1|2)\.com(?:\/|:)/$script`, although this might not be a format that you are looking for either, but it does allow you to combine the filters, and it might be slightly faster than two filters, but it will be a huge pain to maintain later on.

I've been misleaded by this: https://adblockplus.org/filters#elemhide_domains which allows `url1.com,url2.com` instead of (/ together with?) `,domain=url1.com|url2.com` but it seems it applies only to element hiding and not to regular filters. BAH!. I understand now, `$script,domain=` should be used, if want to block all scripts on given domains. I understand now, `exampleurl1.com,exampleurl2.com$script` works, but by searching for the whole phrase: `exampleurl1.com,exampleurl2.com` (including comma) , not for two phrases `exampleurl1.com` and/or `exampleurl2.com` independently. So that explains why `exampleurl1.com$script` has worked,  while `exampleurl1.com,exampleurl2.com$script` hasn't, I just should use `domain=` instead, if I want to search for multiple domains independently.

**B**
Thanks to your lessons,  I've converted not working idea:
:red_circle: `alpha1.com,beta2.pl$popup,domain=gamma3.com|delta4.pl`
which is an element consisting of element hiding syntax + regular filter syntax
to a working RegExp soultion:
✔️ _check_mark: `/alpha1.com|beta2.pl/$popup,domain=gamma3.com|delta4.pl`

:smiley:

**C**
BTW `:white_check_mark:` github emoji is broken on FF, so that's why I've put another one `:white_check_mark:` byside, which works on FF, but I more like `:white_check_mark:`
Hmm. After today's upgrading from FF 54.0.1 to FF 55 (which forces a browser restart), `:white_check_mark:` github emoji is working. So I don't know if the emoji has been fixed by the update or by the restart.

So the first issue is explained.

**2.) :white_check_mark: ████████████████████████████████████████████████████████████**
Now the second issue:

> `$popup,domain=exampleurl1.com|exampleurl2.com` creates a FilterOriginHitSet which wraps FilterTrue, so it will block all popup on those (`exampleurl1.com` and `exampleurl2.com`) domains, I'm not sure what you are testing, it won't block popup to those domain, only from.

Yes, it has to block 'only from', but the problem is that it sometimes wasn't. Before I've  created the issue here, I've tested many times both: `$popup,domain=exampleurl1.com|exampleurl2.com` or `*$popup,domain=exampleurl1.com|exampleurl2.com` (which I understand now is just the same)
and it just didn't work, but now it is magically working.  But now thanks to your explanation, I understand that magic:

> uBO does sometimes throw out filters that it judge too slow, and it is done silently which could be frustrating, I will expose all internal operations in uLint.

So the second issue is explained.

**3.) :white_check_mark: ████████████████████████████████████████████████████████████**
And now the third one:

> `*$script,domain=exampleurl1.com|exampleurl2.com` will, again, create a FilterOriginHitSet which wraps FilterTrue. So it will block all scripts on those domains.

Yes I know, the sense of my question was not why it even works (at all), but why it even works while `$popup,domain=exampleurl1.com|exampleurl2.com` doesn't, but it (`$popup`) as seen, basically/now does for me (and just sometimes "magically" not), so the question is no longer valid.

So the third issue is explained.

**4.) :white_check_mark: ████████████████████████████████████████████████████████████**
Now the fourth "issue":

> uBO has a pretty bad wiki, a lot of stuff are missing, I heard they are in patch notes, but there are like 170 patches and it's kind of a pain to go over all of them. I'm just reading uBO source code to figure out how it parses stuff, I'm almost done with static network filter, next step is cosmetic / scriptlet filter and main controller which handles choosing the right parser and removing comments.

> @uBlock-user : Also there' s hardly any detailed documentation on this in the wiki, so you will have to learn and experiment by yourself.

Yep, that's why I've came here and asked several questions, because I've not found all the answers in the wiki / filters manual. Of course some of the questions are just my incomprehension.

So the fourth "issue" is explained.

**5.) :white_check_mark: ████████████████████████████████████████████████████████████**
And the last thing:

> uBO does sometimes throw out filters that it judge too slow, and it is done silently which could be frustrating, I will expose all internal operations in uLint.

Is it the same issue what was @xuhaiyang1234 talking about here?:
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/1#note_30861859

> @xuhaiyang1234: BTW, I used to support FireFox in uBlock Protector as it is pretty caught up with the syntax, like Chrome, but for some reason, uBlock Origin doesn't really work in FireFox and some rules don't take effect.

Thanks @jspenguin2017 for your time and explanations.

**6.) :white_check_mark: ████████████████████████████████████████████████████████████**

@uBlock-user 

As for your 1st and 3rd new comments: OK. 
**A**
As for your 2nd new comment: 

It didn't work for me, so I thought it's wrong. But as seen it is "magically" working now, but if I reproduce again when it doesn't work I'll open an issue, anyway I think @jspenguin2017 has at least partially "explained" why it sometimes just doesn't work.

**B**
As for your 5th new comment: 

I know, sorry, just forgot about uAssets tracker, 
BTW FYI This is not spam tracker, you're better off using edit button?

Thanks @uBlock-user for your time and explanations.

**7.) :white_check_mark: ████████████████████████████████████████████████████████████**
And the last thing (mainly out of curiosity), why don't You guys use edit button to combine several comments?

**Comment by jspenguin2017** [comment]
> Is it the same issue what was @xuhaiyang1234 talking about here?: https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/1#note_30861859

No, that's not it, Firefox CSP is broken and breaks `$xmlhttprequest,redirect=` rules. When uBO throw out rules, it throws out on every supported browsers. Safari version may throw out more. 

Chromium is not perfect either: https://bugs.chromium.org/p/chromium/issues/detail?id=749236#c5
There are some design issues in Blink and now it's kind of hard to allow `data:` URI from extensions to bypass CSP. Although hard coding the resource in manifest can work, it also gives web pages a way to scan for installed extensions. The name of the files can be randomized on each compile though, it's still something to think about. 

> And the last thing (mainly out of curiosity), why don't You guys use edit button to combine several comments? 

It gets too long, I usually combine comments.

**Comment by gomoku** [comment]
Thanks, I have some last questions, how to combine into a single line:

a) `/alpha.com|beta.pl/`
b) `/alpha.com|beta.pl/$popup,popunder`

**Comment by uBlock-user** [comment]
> And the last thing (mainly out of curiosity), why don't You guys use edit button to combine several comments?

Because then it becomes like this - https://github.com/reek/anti-adblock-killer/issues/3484#issuecomment-320948005 

I can't read that wall of text and nobody will if you keep adding it up.

> BTW FYI This is not spam tracker, you're better off using edit button? 

Posting in multiple comments with new information is NOT spam as you would think so, and makes it easy to differentiate which one to reply, on Github specifically. I'm not sure if that's your rebuttal or a counter argument.

Just because there's no info on the wiki, doesn't mean you have to open the issue here automatically, uAssets is there, you should open there first and if that doesn't help then you can try other things like asking here, that was the whole point.

**Comment by gomoku** [comment]
_**LAST TIME EDITED 10.08.2017 09:09 CEST**_

Thanks for the explanations to You both.

**1.) :white_check_mark: ████████████████████████████████████████████████████████████**
> I can't read that...

True, sorry, I've edited and improved my post, can You read it now? I can improve it more if You want. So assuming a fact that the improved version is readable and easy to differentiate, what is Your argument now?

**2) :white_check_mark: ████████████████████████████████████████████████████████████** 
> I'm not sure if that's your rebuttal or a counter argument.

The second one, because I didn't even consider Your statement to be an attack, but if You are suggesting that it was an attack, which required a rebuttal, feel free to.

**3) :white_check_mark: ████████████████████████████████████████████████████████████** 
> Just because there's no info on the wiki, doesn't mean you have to open the issue here automatically, uAssets is there, you should open there first and if that doesn't help then you can try other things like asking here, that was the whole point.

You don't have to repeat that twice, coz I've already answered: 

> I know, sorry, just forgot about uAssets tracker,

**_Added:_** 
**4) :white_check_mark: ████████████████████████████████████████████████████████████** 
I see uBlock-user not replying due to lack of arguments?..., so I'm closing the discussion.

**_Added:_** 
**5) :white_check_mark: ████████████████████████████████████████████████████████████** 
After I've closed the discussion, he has started trolling me with his thumbs down emojis, so I've replied to him:

> @uBlock-user: I'm not sure if that's your rebuttal or a counter argument.

Looking at the thumbs down emoji from you, instead of a counter argument/ an answer, it is clear now who is making a rebuttal here and is behaving like a child/hater.

**_Added 11.09.2017 12:12 CEST:_**
**6) :white_check_mark: ████████████████████████████████████████████████████████████** 
As seeing another thumb down emoji from you I can just add: haters gonna hate/trolls gonna troll.

**_Added 12.09.2017 08:30 CEST:_**
**7) :white_check_mark: ████████████████████████████████████████████████████████████** 
I've seen an another thumb down emoji from you for no reason there: https://github.com/gorhill/uBlock/issues/3007#issuecomment-328650417
I've also noticed also a laugh emoji. These are your arguments. At child level.

**_Added 13.09.2017 22:30 CEST:_**
**8) :white_check_mark: ████████████████████████████████████████████████████████████** 
I see another emoji from you, an icecream emoji this time, you are just trying to make me looks funny like a fool, but it's you who is a a clown here with your emojis, I think that you collect Pokemons at home

**_Added 14.11.2017:_**
**9) :white_check_mark: ████████████████████████████████████████████████████████████** 
I see that @uBlock-user has removed the evidence - removed his comment in which he was harassing/trolling me, the comment above this comment: https://github.com/reek/anti-adblock-killer/issues/3484#issuecomment-321011787, this way, he does the same what EasyList's forum admins did (they hid the whole thread), he deliberately changes the discussion to his advantage by hidding his own comments that were awkward for him.

**Comment by gomoku** [comment]
A placeholder for github's trolls's collection of Pokemons (personal-directed abusive emojis/links **not supported by any arguments**):

@uBlock-user 's
- the one above
- 2 from https://github.com/gorhill/uBlock/issues/3007#issuecomment-328650417
- 1 from https://github.com/gorhill/uBlock/issues/3012#issuecomment-329110528
- the three below

Current total count of the collected Pokemons: 7 (+ the second as much as these, but favoring my opponents)

@Fuj- 's
- https://github.com/gorhill/uBlock/issues/3012#issuecomment-329149656 (the link)

@GianniGi 's
- https://github.com/gorhill/uBlock/issues/2968#issuecomment-326933928

The more their emotional reactions, the bigger collection gets .

**Comment by Fuj-** [comment]
Your understanding of the term 'troll' is surpassed in comedy only by your interpretation of 'constructive criticism'. You are an arrogant, self-important choleric with social intelligence of a baked potato. The links you kindly provided are testament to that. The fact you present them thinking they prove something else just goes to show how distorted your perception is. When I suggested you have a personality disorder, I wasn't trying to offend or make fun of you, I was just telling it like it is. Try to see it and change or prepare to stay forever alone and bitter, locked in your private reality, in constant conflict with the world.

**Comment by gomoku** [comment]
But what is your problem, lets state some facts:
1) You've spammed the issue tracker with a duplicated issue, because You are to lazy or too egoistic, to put your contribution, to use a search function before creating an issue, and thus to save everone's time, because you've been oriented to get an easy and fast answer (fish). And that is a lack of recpect for other people's time. (you have then later stated that you have spent your time writing the issue to help us, but I would rather say that you've wanted to help yourself first of all, and you've helped us just by the way)
2) I've rightly criticized you for that.
3) You've agreed with my critique, and have stated that you should dig more before creating an issue, which has confirmed that I've been right, and thus that my reprimand/lesson has came handy.

And there should be the end of the story, but:

4) you've got upset and have started emotionally to write out different things at me, finally not being a doctor, you've posted a link to wiki describing the disorder.

Since when an constructive critique (which you've agreed with) is an disorder? 
Isn't more disorder:
- your and @GianniGi's behaviour described by me at 1 + emojis/wiki links/harassing
- @uBlock-user's behaviour - emojis/harassing, 
- lanik & mapx - locking threads/banning/trolling/avoiding answers to unconfortable questions (https://github.com/reek/anti-adblock-killer/issues/2752)
- @xuhaiyang1234 locking thread when losing discussion (https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/142)
- @MajkiIT  trolling/ignoring/closing or locking thread/avoiding answers to unconfortable questions when losing discussion (https://github.com/MajkiIT/polish-ads-filter/pull/3953)
- @gorhill - locking threads/banning/not even answering to quesstions/no counter-arguments + not taking any action against uBlock-user who was harassing me by emojis + and at the same time blaming me instead just due to a constructive critique of some duplicate issues spammers.

?

And where are the answers/counter-arguments? I see only a disorder there...every time I've expected an answer/argument I've got a wall of disorder reactions like described above, but for some unknown reasons noone care/talks about these.

And if your pasting wiki links to disorder isn't an insult, it also won't be an insult if I say that you should go to a psychiatrist to cure your excessive emotions and to stop write out different things at me.

Also for example @Photon89 doesn't take a constructive criticique as an attack, and even thanks for the hint: #2947 (comment)

Also for example @jspenguin2017's reaction/reply to my question:

> @gomoku: And the last thing (mainly out of curiosity), why don't You guys use edit button to combine several comments?

> @jspenguin2017: It gets too long, I usually combine comments.

He also has just simply answered.

So @Photon89 and @jspenguin2017 are examples of mentally healthy persons, which have no emotional problems, unlike some other peoples here like You, @uBlock-user and @GianniGi who in the case of constructive critique or a simple question gets upset and begin to harass the person who criticized them. If you can't defend against constructive critique / simple questions, in a different way than I've described in the middle of the comment, that's your problem. I'm only interested in a substantive conversation, no disorder (not  supported by arguments) at my side, no:
- emotions
- avoiding answers/counter-arguments/giving evasive answers
- locking threads/banning
- harassing/trolling
- emojis/wiki links

It's not me who do such disorder things, all of this above are some kinds of a physical force due to lack of arguments, I would suggest looking at yourself.

**Comment by Fuj-** [comment]
My horrible crime was submitting a duplicate bug report, to which you replied with a rude, angry outburst, and it's not even your tracker. And now again you call me lazy and fail to understand that filing a bug report is a contribution on its own, that I was trying to help and didn't expect any kind of answer or a quick fix, that I did look too see if the issue had already been reported, and that mistakenly submitting a duplicate doesn't constitute a spammer and doesn't warrant the kind of reaction you displayed. No one is waging a campaign against you, people are simply reacting. I would've been long gone but you kept tagging me in your rants and branded me a troll. Trolling is not my idea of fun and you're a too easy target anyway. You're ridiculously oversensitive and irritable but you keep projecting and saying others are emotional. You think you're being harassed when you are the one who is ill-mannered and confrontational. We are all prone to having skewed perception and double standards but with you it's extreme, difficult to comprehend even. My diagnosis was correct and like I said, problems with other people will never end for you. Me, I'm done here, you have one less 'troll' to worry about, but I'm sure someone will fill in before too long.

**Comment by gomoku** [comment]
**1) :white_check_mark: ████████████████████████████████████████████████████████████** 

> @Fuj- : rude, angry outburst, ridiculously oversensitive and irritable

Neither angry nor robust nor ridiculously oversensitive nor irritable, how do you know my emotions via internet, via text? That's just your wrong interpretation/assumption/guess/lack of distance to critique. Maybe a bit rude tone, yes, but just because your spam behaviour hasn't been nice too, so I've just replied the same way, if that was too hard for you, you might always go cry to your mum.

> @Fuj- :not even your tracker

Neither your, to spam it.

> @Fuj- :No one is waging a campaign against you

Neither me is waging a campaign against anyone,  I'm simply reacting too

> @Fuj- : that filing a bug report is a contribution on its own,

Really? Did you really have such honorable intentions? Or just saying like that to have a line of defense? I can quote myself with a little modification:

> @gomoku: you have then later stated that you have spent your time writing the issue to help/contribute us, but I would rather say that you've wanted to help yourself to fix your own problem first of all, and you've helped/contributed us just by the way, if you would not have your own issue with uBO, to fix, would you even come to contribute...? I came to uBlock tracker just because I've had some issues, if I wouldn't have any issues with uBO, probably I wouldn't even come there, basing on such simple fact, it's really hard to believe in your honorable intentions and that they are not just a line of defence.

Anyway, in the case of me, since I already came to uBO's tracker to fix my own issues with uBO, I'd to stay longer on uBlock Origin tracker, to help not only myself but also everybody but I've been banned by @gorhill, but I will not cry because of that.

> @Fuj- :I would've been long gone but you kept tagging me in your rants and branded me a troll. 
 
I wouldn't need to tag you, if you woudn't start to talk different things at me, like my health etc.
The whole situation wouldn't even happen, if you wouldn't spam the tracker.
And you wouldn't spam the tracker, if you would use a search function.

> @Fuj- : Trolling is not my idea of fun and you're a too easy target anyway. 

That is funny, because it's rather me who can say so about you, and you even haven't finished the conversation with me yet, nor proved anything, but you're already making such statements, as you've won, best to praise yourself.

> @Fuj- : you are the one who is ill-mannered and confrontational

Again: read what I've replied to you about your "angry outburst:" accusations. If you spam, do not expect thanks.

> @Fuj- : My diagnosis was correct and like I said, problems with other people will never end for you. Me, I'm done here, you have one less 'troll' to worry about, but I'm sure someone will fill in before too long.

Ok, Mr Doctor.

**_Added 14.11.2017:_**
**2) :white_check_mark: ████████████████████████████████████████████████████████████** 
I see that @uBlock-user has removed the evidence - removed his comment in which he was harassing/trolling me, the comment above this comment: https://github.com/reek/anti-adblock-killer/issues/3484#issuecomment-321011787, this way, he does the same what EasyList's forum admins did (they hid the whole thread), he deliberately changes the discussion to his advantage by hidding his own comments that were awkward for him.

**Comment by gomoku** [comment]
@uBLock-user: I see that you've removed the evidence - removed your comment in which you were harassing/trolling me, the comment above this comment: https://github.com/reek/anti-adblock-killer/issues/3484#issuecomment-321011787, this way, you do the same what EasyList's forum admins did (they hid the whole thread), you deliberately change the discussion to your advantage by hidding your own comments that were awkward for you, that way you're showing how hard troll-bitch you are.
