### ISSUE TITLE
bitcoiner.net & litecoiner.net

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#349]
http://i.imgur.com/54tQ4Iy.png
Google Chrome
N/A
uBlock
EasyList

Filter will also apply to Bitcoiner.net's sister site, Litecoiner.net

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Injust** [comment]
Hi, the sites are being blocked again, because the author updated the site.

Thanks.

**Comment by reek** [comment]
Hi,

Its ok for me, have you installed AakScript ?

**Comment by Injust** [comment]
Just installed it, it's working now. Thanks!
