### ISSUE TITLE
trafictube.ro

### ISSUE THREAD

**Issue by vasileion** [reek/anti-adblock-killer#350]
http://www.trafictube.ro/mata-certa/
http://i.imgur.com/U09lCk1.jpg
Google Chrome
TamperMonkey
Adblock
EasyList + Romanian

**Comment by maynak00** [comment]
try disabling Romanian filter.
uBlock Origin + ROU: RO-LIST (modified)‎: http://www.trafictube.ro/pare/ (adblock detected page)
uBlock Origin without ROU: RO-LIST (modified)‎: http://www.trafictube.ro/mata-certa/ (adblock not detected)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
