### ISSUE TITLE
uptobox.com

### ISSUE THREAD

**Issue by axarad** [reek/anti-adblock-killer#351]
Hi;
Uptobox.com has started today showing a new AdBlock Notification
its powered by"Adunblock.com"
Here is a link for example: http://uptobox.com/l53olbk7pzho
Hope you can fix it
Thank you very much for your time
![snap1](https://cloud.githubusercontent.com/assets/10789454/7496852/b297acd4-f40e-11e4-950d-89a7712b70a8.jpg)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by axarad** [comment]
Still not working after update!
PS: Adblock notification is not shown immediately, in fact I'm being redirected to it in 2sec after the page is loaded (if I don't click create download link)
I hope you did understand me
Thank you so much for your valuable time!

**Comment by reek** [comment]
Hi,

I have to make a change in the script, I would get tested

See you
Reek

**Comment by axarad** [comment]
Got, thanks!

**Comment by vinctux** [comment]
@reek I analyzed AdUnblock a bit... Here are my conclusions:
* They work on PHP, WordPress, Joomla, IPB, Ruby on Rails
* PHP code for websites:
```php
<?php
$aub_cache_file = 'adunblock/cache.html';
$aub_cache_time = 21600;
$ctx = stream_context_create(array('http' => array('timeout' => 3)));
if (file_exists($aub_cache_file) && (time() - $aub_cache_time < filemtime($aub_cache_file))) {
  $aub_html = file_get_contents($aub_cache_file);
} else {
  $aub_html = @file_get_contents('http://adunblock.com/code/bb955c95805ad5bdc8d0fd21eaaaedd9.html', 0, $ctx);
  if (!$aub_html) $aub_html = @file_get_contents($aub_cache_file);
  file_put_contents($aub_cache_file, $aub_html);
}
echo $aub_html;
?>
```
* [WordPress Plugin](http://adunblock.com/adunblock_wp_plugin.zip)
* [Joomla Plugin](http://adunblock.com/adunblock_joomla_plugin.zip)

In general, if `http://adunblock.com/code/*.html` is blocked it should solve all depending issues - it's universal. If it's blocked, the working of this function is improperly (because it can't retrieve the code script via the ID), and the functionality of AdUnblock is drastic low:
```php
function add_adunblock_code() {
  $code = get_transient('code_adunblock');
  $adunblock_id = get_option('adunblock_id');
  $ctx = stream_context_create(array('http' => array('timeout' => 3)));
  if (!$code) {
    $code = @file_get_contents("http://adunblock.com/code/$adunblock_id.html", 0, $ctx);
    if (!$code)
      $code = get_transient('code_adunblock_lt');
    else
      set_transient('code_adunblock_lt', $code, 14 * 86400);
    set_transient('code_adunblock', $code, 6 * 3600);
  }
  echo $code;
}
```
I hope it helps.

**Comment by reek** [comment]
@vinctux 
thank you, and I know adunblock, i already have a solution for adunblock but I just have to change a setting for this working again.

**Comment by reek** [comment]
AakScript Beta: https://gist.github.com/reek/dc234ea9687056bd99fe/raw/05e3ab3cacd914cbdad13059bef4f93556d6e994/aakdev.user.js

**Comment by axarad** [comment]
Tried AakScript Beta, no Adblock notification but is not working properly yet, the page gets in a nonstop loading loop!

**Comment by reek** [comment]
Hi,

Tested with Firefox and Chrome its ok.
Try update ABP lists

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
