### ISSUE TITLE
Adblock detected in jdownlader2premiums.blogspot.com

### ISSUE THREAD

**Issue by simoconfa** [reek/anti-adblock-killer#3513]
As you can see in the image, adblock is detected in https://jdownlader2premiums.blogspot.com/
![immagine](https://user-images.githubusercontent.com/8224154/29592460-64d74ece-87a4-11e7-8fc7-57aecfa23d5c.png)

**Comment by simoconfa** [comment]
Solved by adding these filters:


```
||jdownlader2premiums.blogspot.com/*noscript
||jdownlader2premiums.blogspot.com/*script
jdownlader2premiums.blogspot.com##i
```

If anyone knows better filters, would be appreciated since I am new to filters

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Just add `blogspot.*###g207`

**Comment by simoconfa** [comment]
If I use only your filter, it is not working...

**Comment by uBlock-user** [comment]
Works for me fine. If you're on Chrome, remove AAK and install uBlockProtector.

**Comment by simoconfa** [comment]
Which browser, which extension and which filter list do you use? I use firefox with ADB plus  with adblock warning removal list, easy list and obv anti-adblock killer

**Comment by uBlock-user** [comment]
I use uBO, Chromium 62 and all FLs provided by uBO. Anyways you're on FF, so use AAK-Cont instead of AAK.

**Comment by uBlock-user** [comment]
Remove the previous filter I posted and add this instead - `@@||blogspot.*^$generichide`

It's reliable and works always.

**Comment by simoconfa** [comment]
Thanks, it was so easy, but I did not think trying it eheheh
I will use AAK-Cont!
