### ISSUE TITLE
Adblock detected in cutwin.com

### ISSUE THREAD

**Issue by simoconfa** [reek/anti-adblock-killer#3515]
Adblock is detected in cutwin.com
example: https://cutwin.com/123
How should be:
![immagine](https://user-images.githubusercontent.com/8224154/29605974-11cf5976-87ed-11e7-83ab-e064e61d26f3.png)
How it is:
![immagine](https://user-images.githubusercontent.com/8224154/29606005-27257648-87ed-11e7-9ac7-a9bc09ce88a7.png)
As you can see, when adblock is detected the captcha box disappears.
More in particular `<div class="col-md-12">` content is modified by these two scripts: [https://pastebin.com/7Uetu8KD](url) and [https://pastebin.com/c9JFDZ65](url) which are visible in `<footer>` section.
In the second one there is a function called `checkAdblockUser()` it would be nice injecting in it (but I don't know how hehe)
If you kill the script, captcha box is not displayed, so you cannot go on.
I tried inserting <a href="https://github.com/jspenguin2017/uBlockProtector/issues/328#issuecomment-311031635">these</a> filters without success

**Comment by uBlock-user** [comment]
Can't reproduce.

If you're on Chrome, remove AAK and install uBlockProtector. It's patched there. For other browsers, use AAK-Cont.

**Comment by uBlock-user** [comment]
If you're willing to whitelist, then you can use this on your current configuration - 

`@@/js/ads.js,$domain=cutwin.com`

**Comment by simoconfa** [comment]
Thank you so much. Now working!

**Comment by simoconfa** [comment]
Not working anymore... Using AAK-Cont with FF

**Comment by simoconfa** [comment]
Solved using Tampermonkey instead of Greasemonkey

**Comment by uBlock-user** [comment]
Works just fine, you did something on your end, or it's pulling from the old cache. Nothing's changed.

https://cutwin.com/js/ads.js

That's the script that gets whitelisted by https://github.com/reek/anti-adblock-killer/issues/3515#issuecomment-324325094
