### ISSUE TITLE
rapidrar.com

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#352]
rapidrar.com site can detect that I have ad blocking enabled.

**Comment by maynak00** [comment]
Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by xyzzy-xyzzy** [comment]
https://greasyfork.org/en/scripts/735-anti-adblock-killer-reek
http://rapidrar.com/zyk8mix7gzqo
Firefox 37.0.2 (on Mac OS 10.6.7)
Greasemonkey
Adblock Plus
Adblock Warning Removal List + EasyList + Fanboy's Social Blocking List + EasyPrivacy + AakList

Adblock warning plus countdown timer,  Clicking "Free" doesn't work.  I believe this behavior occurs with AntiAdware script installed.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://greasyfork.org/fr/forum/discussion/4145/x

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
