### ISSUE TITLE
game-state.com

### ISSUE THREAD

**Issue by as2330** [reek/anti-adblock-killer#353]
http://www.game-state.com/
imgbox.com/zhLQkZal
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList+RU AdList

**Comment by SystemRevolution** [comment]
Reek, this filter seems to solve it.
`www.game-state.com##DIV[class="ho_ads"]`

**Comment by maynak00** [comment]
@SystemRevolution thanks.
but some adblock detected message on page
block image
||static.game-state.com/images/main/alert/replacement/quadrato_grande.png
or block box completely
www.game-state.com###contents > div:nth-of-type(5) > div:nth-of-type(1)
using with uBlock Origin

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@SystemRevolution
@maynak00 

Thanks, guys.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
