### ISSUE TITLE
http://adshorte.com

### ISSUE THREAD

**Issue by xNekom** [reek/anti-adblock-killer#3538]
This web detects AdBlock

**Comment by uBlock-user** [comment]
bait - https://adshorte.com/js/ads.js

@jspenguin2017

**Comment by jspenguin2017** [comment]
I thought that is patched a long time ago. Got a real test link?

**Comment by jspenguin2017** [comment]
http://adshorte.com/Xau4fP works for me.

**Comment by uBlock-user** [comment]
Their shrinking functionality doesn't work for me as it says `Invalid user` for some reason.

**Comment by uBlock-user** [comment]
Was it patched ?

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/339

**Comment by uBlock-user** [comment]
Ah yes, so can you reproduce ?

**Comment by jspenguin2017** [comment]
No.
