### ISSUE TITLE
generatorlinkpremium.com

### ISSUE THREAD

**Issue by SystemRevolution** [reek/anti-adblock-killer#354]
http://generatorlinkpremium.com/ (after post a download request)
http://img.ctrlv.in/img/15/05/07/554b336721dcb.png
Google Chrome
Tampermonkey
Betafish adblock (getadblock.com)
EasyList + AakList

Hi there!
I'm posting this to send the following filters that improve the browsing experience.

```
@@||generatorlinkpremium.com/js/ads.js$script
generatorlinkpremium.com##.thirdsky
generatorlinkpremium.com##.secondsky
```
The first line is only to allow the loading of the "easter egg" that allows the download speed, the other two lines are for aesthetically clean page.

The real code behind **ads.js** is:
```
$(document).ready(function() {

    var normal = $('#normal').attr('href') + "&h=1";
	$('#quick').attr('href', normal);
	$('#quick').attr('title', 'Download this file with a faster download speed');
	$('#quick').css( 'cursor', 'pointer' );
	
}); 
```
As you can see, there is not any ad in this script, the name is just to its load get blocked by the ad blockers

**Comment by reek** [comment]
Hi,

Thanks, good job :+1: 

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
