### ISSUE TITLE
http://www.thewindowsclub.com

### ISSUE THREAD

**Issue by phreich9** [reek/anti-adblock-killer#3559]
http://www.thewindowsclub.com/kernel-security-check-failure-windows
https://imgur.com/a/LQQFp
Opera
Greasemonkey
Adblock
EasyList + AakList

I just installed greasemonkey and your script, then restarted my browser.  Yes, your script is activated in greasemonkey.  I then tried to access the webpage again, but got the same result (ad-blocker detected).

There seems to be an anti-adblock program running called "Admiral" that gets by the script.

Good luck!

**Comment by phreich9** [comment]
whoops, just noticed that this has been reported before.  Please disregard.  I will add to the active issue.

**Comment by uBlock-user** [comment]
Can't reproduce.
