### ISSUE TITLE
Anti-adblock detected on https://animes-mangas-ddl.net/

### ISSUE THREAD

**Issue by funkilleur** [reek/anti-adblock-killer#3564]
when you refresh https://animes-mangas-ddl.net/ some times its redirect you to another page that said Anti-adblock detected  or an add pop up

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by funkilleur** [comment]
the protection they use https://blockadblock.com/#24639

**Comment by uBlock-user** [comment]
uBO - `animes-mangas-ddl.net##script:inject(bab-defuser.js)`

**Comment by funkilleur** [comment]
thank you it work.
