### ISSUE TITLE
softpedia.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#357]
* http://www.softpedia.com/get/Multimedia/Video/Video-Players/VideoLAN-Client.shtml
* softpedia.com##DIV[style="color:#900;font-family:'museo_slab',serif;font-size: 20px; line-height:27px; padding: 20px;"]
* https://i.imgur.com/kBEJDyP.png
* Firefox 37.0.2
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.9
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you soon
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
