### ISSUE TITLE
http://www.business-standard.com anti-adblock killer not working

### ISSUE THREAD

**Issue by wokeaf** [reek/anti-adblock-killer#3574]
[Example link](http://www.business-standard.com/article/economy-policy/we-could-have-managed-liquidity-better-says-raghuram-rajan-117091100920_1.htmll)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by wokeaf** [comment]
@uBlock-user, strange...any suggestions what else I could try? You clicked on the example link right? Not just the Home Page?

**Comment by uBlock-user** [comment]
Yes, I'm on uBlock Origin and I don't see any anti adblock. Also you haven't bothered to provide details  enlisted in the [template](https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md#require) which is the reason I couldn't offer you any suggestive filters specific to the adblocker you use.

**Comment by uBlock-user** [comment]
Nvm 

uBO - `business-standard.com##script:inject(abort-on-property-read.js, isBannerActive)`

ABP/Adblock -  `@@/ad/banner.js$domain=business-standard.com`

**Comment by wokeaf** [comment]
@uBlock-user, sorry, I did not go through that section. 

Screenshots: https://imgur.com/a/QNp3n
Google Chrome
Script Manager: I don't think I am using one
uBlock Origin
Filter lists: the ones pre-selected by uBlock Origin

Hey, I edited my post to remove Firefox because I just noticed there is no Anti-Adblock Killer | Reek option in the Ads section of the uBlock dashboard. How do I add it to uBlock Firefox? I can then check if it's the same with Firefox.

**Comment by wokeaf** [comment]
Okay, so by following the instructions, Step 1, Step 2, Step 3, I was able to get it to work on Firefox.

But why doesn't it work in chrome when I have these two options selected? https://u.teknik.io/SH0PC.png

Do you always have to install it as per the instructions? Just selecting Anti-Adblock Killer | Reek in Chrome seemed to work on other sites.

I didn't realize there was a purpose to AakList (Anti-Adblock Killer).

Okay, so it's working on Chrome as well, but again by following the instructions to add AakList to uBlock, then to install TamperMonkey, and then to install the User Script.

Even if I deselect Anti-Adblock Killer | Reek in the Ads section of uBlock Origin it still works. So what is the point of that option? I thought the whole point of that option was to use this without having to install a Script Manager. Really confusing.

**Comment by uBlock-user** [comment]
AAK is no longer updated and abandoned so gorhill removed AAKList from third-party filters tab, since you're on uBO as well, I suggest you use uBlock Protector OR switch to AAK-Cont. The filters I posted work well and are expected to work on every browser. Also remove AAK completely.

**Comment by wokeaf** [comment]
Sorry, where are the filters you posted? And when you say remove AAK completely, do you mean the custom URLs? What is the process for complete removal? Thanks for letting me know about uBlock Protector and AAK-Cont. Which one do you personally use?

Also I believe Protector and Cont are not available for FF?

Hi, I found some useful information on this [page](https://malwaretips.com/threads/ublock-protector-extension-for-chrome-and-anti-adblock-killer-continued.73400/).

Hope it helps anyone else passing through here. 

I suppose I should go ahead and close this issue. Thanks for your assistance and getting back so quickly.
Are you involved with the development of this project?

**Comment by uBlock-user** [comment]
Filters - https://github.com/reek/anti-adblock-killer/issues/3574#issuecomment-328780296

No I mean remove AAK script if you have it installed in TM or VM and deactivate AAKList filterlist if it's still activated. I suggest uBlock Protector since you're using uBlock Origin like me and yes it's for Chromium/Chrome only. For FF you may use AAK-Cont.

I'm only involved with uBlock Protector as a volunteer for suggesting anti adblock filters on the issue tracker.

**Comment by wokeaf** [comment]
Gotcha...well I'm all sorted out here. Got Protector on Chrome and Cont on FF. Both are working great. I didn't have to use those filters from above. Thanks again.
