### ISSUE TITLE
arconaitv.co

### ISSUE THREAD

**Issue by g2178716** [reek/anti-adblock-killer#3582]
arconaitv.co blocks use of the site if it detects an adblocker.

How to work around this?

http://www.arconaitv.co/

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017

**Comment by g2178716** [comment]
It loads this page:

http://www.arconaitv.co/adblocker.php

when you go here:

http://www.arconaitv.co/

**Comment by uBlock-user** [comment]
uBO - `arconaitv.co##script:inject(abort-on-property-read.js, canRunAds)`

ABP/Adblock - `@@/ads.js$domain=arconaitv.co`

**Comment by g2178716** [comment]
Nailed it. Thanks dude!

**Comment by jspenguin2017** [comment]
It is caught in generic solutions.

**Comment by uBlock-user** [comment]
I know but this guy is not running uBlock Protector so I left a filter based solution for him and others.
