### ISSUE TITLE
kissanime.com

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#359]
* http://kissanime.com/Anime/RWBY/_Black-Trailer?id=52421
 * The Adblock warning seems to appear in videos between 20 and 40 seconds in.
* https://i.imgur.com/RcCZ2dS.png
* Firefox 37.0.2
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.9
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

**Comment by reek** [comment]
Hi,

This is normal, you have not installed AakScript while now assure you that it does not work with AakScript, before reporting.

In case you could not understand AakScript removes Anti-Adblock filters that can not.

I appreciate your help, but it would be more efficient if you was AakScript.

See you
Reek
