### ISSUE TITLE
No Longer Maintained!?

### ISSUE THREAD

**Issue by Mactastic1-5** [reek/anti-adblock-killer#3594]
Is this still maintained?

**Comment by uBlock-user** [comment]
No.

**Comment by graciecat** [comment]
@uBlock-user Do you know this officially? Or is it just that reek has been non-responsive lately?

**Comment by uBlock-user** [comment]
There's NO official statement.  Reek abandoned this project since November 2016 and not a single update has been made since that time, uBlock Protector/AAK-Cont is the successor.

**Comment by marcussacana** [comment]
https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by Mactastic1-5** [comment]
I already got the link, but why do I need the extension when Ublock Origin includes the filter in the list and it’s active?

**Comment by nitrocode** [comment]
Thanks @uBlock-user . I guess I was wasting my time on the issues page. Might be worth it to write an automated bot that comments on every new issue to say use Nano-Defender with AAK-Cont instead.
