### ISSUE TITLE
ogmods.net

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#360]
http://ogmods.net/home/DownloadFile?Id=OGYT09A
http://i.imgbox.com/3H7rA0UN.png
Chromium x64
Tampermonkey BETA
uBlock Origin
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎
"<font id="data" style="font-size: x-large; font-weight: bold; color: #5555FF">Advertising seems to be blocked in your browser.
Please notice that advertising helps me to host my site.
 So please disable AdBlock on this site, if you want to download this file</font>"

EDIT: temporary fix: http://i.imgbox.com/9Qk9QnYv.png
*temporary because not working always.

**Comment by MajkiIT** [comment]
Please update all filters (Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎) after that I haven't any notifications.

**Comment by reek** [comment]
@MajkiIT 
it's because I have already killed, if it did not work.

@maynak00 
Thanks for reporting

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
