### ISSUE TITLE
mashable.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#3600]
http://mashable.com/2016/08/11/facebook-adblock-plus-ads/
https://images.imgbox.com/83/77/ghGtNzml_o.png
Chrome 61.0.3163.91 (Official Build) (64-bit)
uBlock Origin (uBlock filters – Unbreak, Adblock Warning Removal List, EasyList, EasyPrivacy, Peter Lowe’s Ad and tracking server list, TUR: Adguard Turkish Filter, AAK-Cont Filter For uBlock Origin, uBlock Protector List)
Violentmonkey 2.8.9 (AAK-Cont Userscript For uBlock Origin, AdsBypasser)

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017

**Comment by uBlock-user** [comment]
Try `mashable.com##script:inject(noeval-if.js, adblock)`

**Comment by maynak00** [comment]
@uBlock-user thanks, its working

**Comment by jspenguin2017** [comment]
Can't reproduce...

**Comment by jspenguin2017** [comment]
But OK, I'll add the rule, as I do see their sketchy encoded payload.
