### ISSUE TITLE
sharecash.org

### ISSUE THREAD

**Issue by AmperAndSand** [reek/anti-adblock-killer#361]
1. Link page which contains anti-adblock:  
http://www.update-lollipop.org/mp3-0/lenovo-a536-6674.html  
http://www.cwm-twrp-recovery.club/mp3-0/lenovo-a536-6674.html  
Redirects to: http://widget.sharecash.org/adblock.php  
2. Screenshot: [![][1]][1]  
3. Browser: Firefox 37.0.2
4. Script manager: GreaseMonkey
5. Adblocker: uBlock
6. Filterlists: Fanboy Ultimate List (EasyList + EasyPrivacy + Fanboy Annoyances List), AakList

  [1]: https://i.imgur.com/gK49UfV.png

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by AmperAndSand** [comment]
@reek Thanks. The anti-adblock is now being blocked.
