### ISSUE TITLE
Business Insider

### ISSUE THREAD

**Issue by cvbmilani** [reek/anti-adblock-killer#3610]
http://www.businessinsider.com/mongodb-files-for-ipo-2017-9
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by cvbmilani** [comment]
Open a few pages in the site and scroll down the articles. After awhile it blocks you.

**Comment by uBlock-user** [comment]
I already did and it doesn't happen because it's patched by a uBO filter on uBO. I don't have any filters for ABP.

**Comment by cvbmilani** [comment]
Ok, replaced ABP with uBlock. uBlock solved the problem. Thanks.
