### ISSUE TITLE
http://animeheaven.eu

### ISSUE THREAD

**Issue by w4tadrag** [reek/anti-adblock-killer#3619]
Test link: http://animeheaven.eu/watch.php?a=Hunter%20x%20Hunter%202011%20Dubbed&e=68

Screenshot : https://i.gyazo.com/80b330befb97bed1c937fb27a4128b73.png

 Chrome, 
Ublock Origin, 
Tampermonkey, 
AakList
EasyList

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/71f9c88d4c923912ff212ff2dc4061aca4c47741

**Comment by w4tadrag** [comment]
@jspenguin2017 thanks for posting it, but I don't know what I'm supposed to do with codes you posted as I am new to this.

**Comment by w4tadrag** [comment]
nvm somehow got it to work. thanks for your help
