### ISSUE TITLE
naekranie.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#362]
http://naekranie.pl/
https://www.dropbox.com/s/jv4em4hyjoif4xm/adblock8.png?dl=0
Mozila Firefox
Greasemonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

I block this, by this rule naekranie.pl##.inner .

**Comment by reek** [comment]
Hi,

Thanks :+1: 

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
Thanks.

See you
Majki
