### ISSUE TITLE
ruutu.fi

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#3620]
http://www.ruutu.fi/video/3100435
https://i.imgur.com/oFTAJyi.jpg
Chrome
Tampermonkey
uBlock Origin

uBlock filters
EasyList
AakList
Adblock Warning Removal List
EasyPrivacy
Peter Lowe's Ad and tracking server list

**Comment by uBlock-user** [comment]
@jspenguin2017

Try- 

```
@@||7caa2.v.fwmrm.net^$script,domain=ruutu.fi
ads^$media,domain=ruutu.fi
```

**Comment by uBlock-user** [comment]
Whitelisting that script straight up pulls video ads, so need to add the second filter for all video based ads.

**Comment by ghost** [comment]
That did the trick, thanks.

**Comment by uBlock-user** [comment]
That's the workaround, not the solution FYI. It might pull ads which are unforseen on my end.

**Comment by ghost** [comment]
Alright. Haven't seen any ads so far from what I've tested.

**Comment by jspenguin2017** [comment]
@uBlock-user Added an ads request loopback, still have to white list the file in uBO though.

**Comment by jspenguin2017** [comment]
Someone who watch `ruutu.fi` is using Extension but not List. You MUST install both Extension and List, otherwise, you'll get unwanted side effect.
