### ISSUE TITLE
Add in header info when you change version of filters

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#363]
Hi, Can you add in header info when you change version of filters? Maybe date or version like 8.0.1 ? This help somethimes in troubleshooting. This of course is only my opinion. That's for your work. 

See you
Majki

**Comment by reek** [comment]
Hi,

I do not because I might forget, but you can see when was published the last update here
![capture](https://cloud.githubusercontent.com/assets/3474011/7555156/1a5e13da-f743-11e4-8ebc-75ca7c378f4f.png)

**Comment by MajkiIT** [comment]
Ok thanks.
