### ISSUE TITLE
https://reviveheroes.com/

### ISSUE THREAD

**Issue by Twydude** [reek/anti-adblock-killer#3631]
https://reviveheroes.com/
![](https://i.imgur.com/P6lqW40.png)
Waterfox
Greasemonkey
uBlock Origin
uBlock Filters + EasyList + AakList

**Comment by uBlock-user** [comment]
Cannot reproduce.

`/cdn-cgi/apps/head/$first-party,script`

@jspenguin2017

**Comment by jspenguin2017** [comment]
It's taken care of by a generic rule.
