### ISSUE TITLE
turbogenerator.info

### ISSUE THREAD

**Issue by axarad** [reek/anti-adblock-killer#364]
Hi,
Please fix turbogenerator.info, it redirects to this url: http://tiny-paste.com/public/images/adblock.png
and shows the picture below
Mozila Firefox
Greasemonkey
Adblock Edge
EasyList + Anti-Adblock Killer | Filters for Adblockers
Thank you!
![adblock](https://cloud.githubusercontent.com/assets/10789454/7555912/db0fcdb6-f753-11e4-8d7d-e5876face785.png)

**Comment by maynak00** [comment]
Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
