### ISSUE TITLE
http://rus.delfi.ee

### ISSUE THREAD

**Issue by DewFill** [reek/anti-adblock-killer#3646]
don't work at this site 
http://rus.delfi.ee

Version: 10 
AakScript: true 
AakList: true 
Browser: Chrome 
ScriptManager: Tampermonkey

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017

**Comment by jspenguin2017** [comment]
`rus.delfi.ee###ab--notification-ribbon`

**Comment by atsmiller** [comment]
Seems to be same issue (same site anyway).
http://m.delfi.ee (http://m.delfi.ee/article.php?id=59048626)
Screenshot: https://imgur.com/c9t5x5r (translation added :-) )
Firefox 56.0 (64-bit; mac)
Adblock Plus 2.9.1 (updated today)
Greasemonkey 3.17
Anti-Adblock Killer Reek 10.0 (updated today)
