### ISSUE TITLE
Please use more sane commit messages

### ISSUE THREAD

**Issue by nyuszika7h** [reek/anti-adblock-killer#365]
Your commit messages which say `-` are horribly undescriptive, and very hard to click because of the extremely short commit message. You can't really fix it without force pushing and breaking things for everyone who cloned the repo and made changes, but please start using better commit messages. It really takes very little effort.

**Comment by underyx** [comment]
+1

**Comment by reek** [comment]
Hi,

OK, I am going to make an effort.

See you
Reek
