### ISSUE TITLE
adultmult.tv

### ISSUE THREAD

**Issue by trufanov-nok** [reek/anti-adblock-killer#366]
http://adultmult.tv/as/adventure_time.html
http://imgur.com/x9u4K1y
Mozilla Firefox on Kubuntu 15.x
Greasemonkey
uBlock
EasyList + AakList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by trufanov-nok** [comment]
Deal, but It doesn't work for some reason.
I'm using FF 38 under Kubuntu 15.04
I've installed  Greasemonkey 3.2 . I've installed the only one script into it - Anti-Adblock Killer | Reek. 
I'm able to find adultmult.ru domain in the script text if I open it to edit via Greasemonkey settings. SO it shall be up to date.

As for step 2 - I've permitted this subscription for my uBlock 0.9.1.0.1-signed. I've reseted its settings and enabled Anti-adblock | Reek filter list then updated it. uBlock says it uses 4 073 from 4 096 filter entries.
AakList (Anti-Adblock Killer)‎ is listed in user filters as 'used  0 from 4096' if I disable `Anti-adblock | Reek filter list ` then it becomes 3986 of 4096. Anyway I can't see domain in filter list so step 2 might be irrelevant for me.

With both uBlock and Greasemonkey enabled the problem still reproducible (with both lists from step 2).

**Comment by reek** [comment]
Hi,

There seems be a problem I am going to correct

**Comment by reek** [comment]
Press raw for install
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by trufanov-nok** [comment]
Yes, now it works.

2015-06-14 2:51 GMT+04:00 reek <notifications@github.com>:

> Press raw for install
> https://gist.github.com/reek/dc234ea9687056bd99fe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reek/anti-adblock-killer/issues/366#issuecomment-111758217>
> .
>



-- 
With best regards,
Alexander Trufanov

**Comment by reek** [comment]
Good :)

2015-06-14 9:25 GMT+02:00 Alexander Trufanov <notifications@github.com>:

**Comment by mopeLantebyx** [comment]
doesn't work once again

**Comment by trufanov-nok** [comment]
@mopeLantebyx still works for me..

**Comment by reek** [comment]
me too

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by trufanov-nok** [comment]
And now I see what @mopeLantebyx meant.They really do some counter-measures. The anti-adblock isn't working for new videos only (ones that marked with premiere/премьера keyword). For old pages or new episodes of existing series the anti-adblock still works.  
The example of new video which is blocked could be found here:
http://adultmult.tv/other/pacman.html
The red dotted-line rectangle is a placeholder with text "You must disable ad blocker to make videoplayer appear".

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
