### ISSUE TITLE
20min.ch

### ISSUE THREAD

**Issue by permanentlyinsane** [reek/anti-adblock-killer#3667]
On 20min.ch images can not be properly maximized.

With anti-adblock-killer enabled
![20min-0](https://user-images.githubusercontent.com/32911837/31738337-98737028-b44a-11e7-83ed-d6607a1edcbc.JPG)

With anti-adblock-killer disabled
![20min-1](https://user-images.githubusercontent.com/32911837/31738344-a10dc5ee-b44a-11e7-9e14-8885f8f5472b.JPG)

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development.

**Comment by permanentlyinsane** [comment]
I see, Thanks.

What about Tampermonkey? I'm slightly confused now.

It seems that uBlock apparently blocks that adblock message from showing up now.

**Comment by uBlock-user** [comment]
> What about Tampermonkey?

What about it ? 

Yes it's patched in uBO.

**Comment by permanentlyinsane** [comment]
Is Tampermonkey useless?

**Comment by uBlock-user** [comment]
Depends on you. If you _**don't**_ have any user-scripts to run, then it's useless to have it instead.

**Comment by permanentlyinsane** [comment]
I got it. Thanks.
