### ISSUE TITLE
vgtv.no

### ISSUE THREAD

**Issue by bakagringo** [reek/anti-adblock-killer#367]
http://www.vgtv.no/#!/video/112128/episode-5-kasim-baeder-2 -preload ads on every video bypassing adblock
http://i.imgur.com/uN5GPDl.png?1
Mozilla Firefox
GreaseMonkey
Adblock Edge
EasyPrivacyEasyList + Aaklist + Malware Domains list
Other Plugins: Disconnect

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by NChief** [comment]
Does not work?
http://www.vgtv.no/#!/video/114654/roskilde-2015-kygo-feber-og-nakenloep
http://i.imgur.com/dAILeDD.png
Chrome
tampermonkey
µBlock origin
Default filters + Aaklist

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by techpulse** [comment]
Don't work. http://i.imgur.com/XHF2gVZ.png

**Comment by reek** [comment]
@techpulse 
its ok for me, try update AakLiar

**Comment by bakagringo** [comment]
Doesn't work for me either. version, 8.4, adblock filter just updated. Source: Github

**Comment by techpulse** [comment]
Same here, it's updated and not working..

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Extended

**Comment by techpulse** [comment]
http://paste2.org/z1bgD0dM
