### ISSUE TITLE
avgle.com

### ISSUE THREAD

**Issue by agfgelee** [reek/anti-adblock-killer#3672]
I can't watch the video with this message shown.

https://avgle.com/video/43588/%E3%82%B7%E3%83%B3-%E8%82%89%E4%BE%BF%E5%99%A8%E3%81%93%E3%82%8C%E3%81%8F%E3%81%97%E3%82%87%E3%82%93%E6%94%B9-%E3%83%A6%E3%83%8B%E3%83%83%E3%83%88%E3%83%90%E3%82%B9%E7%9B%A3%E7%A6%81%E5%A5%B3%E5%AD%90%E6%A0%A1%E7%94%9F%E3%83%AC%E3%82%A4%E3%83%97-%E5%AE%AE%E5%B4%8E%E3%81%82%E3%82%84-case025-arbb-044
https://i.imgur.com/LaCjcgb.jpg
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AAK-Cont Filters

**Comment by uBlock-user** [comment]
Can't reproduce.

@jspenguin2017

**Comment by jspenguin2017** [comment]
```
! === NSFW! avgle.com
avgle.com##div:has(:scope > div#blocked-if)
avgle.com###aoverlay
```

**Comment by agfgelee** [comment]
Thanks.
I installed uBlock Protector Extension, AAK-Cont Userscript For uBlock Origin, and uBlock Protector List, then it works.
Can I remove AdBlock Protector Script and AdBlock Protector list?

**Comment by jspenguin2017** [comment]
You just need uBlock Protector (Extension and List), you can remove the ancient AdBlock Protector as well as AAK-Cont.

**Comment by agfgelee** [comment]
OK. Thank you very much.

**Comment by dreamscape91** [comment]
that fileter does not work anymore @jspenguin2017 any solution?

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/817
