### ISSUE TITLE
not working on play.tv3.lt

### ISSUE THREAD

**Issue by jonmei** [reek/anti-adblock-killer#3679]
Google Chrome
Tampermonkey
Adblock
EasyList + AakList

browser: 
![image](https://user-images.githubusercontent.com/6714244/31959040-4b28a78c-b8fc-11e7-93af-4760cc7d8522.png)

console output: 

![image](https://user-images.githubusercontent.com/6714244/31959137-90f1cd34-b8fc-11e7-97ac-7d4b058535fc.png)

**Comment by uBlock-user** [comment]
@jspenguin2017 wasn't this patched ?

**Comment by jspenguin2017** [comment]
@uBlock-user I'm pretty sure it's patched, unless they changed it. Can you reproduce the problem?

**Comment by uBlock-user** [comment]
Yes.

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/31972663-ed5cf814-b8de-11e7-9693-7f9acf4b4eec.png)

**Comment by uBlock-user** [comment]
specific test link ?

**Comment by jspenguin2017** [comment]
`https://play.tv3.lt/programos/x-faktorius/885139?autostart=true`

**Comment by jonmei** [comment]
what kind of adblock extension you use? (im using https://getadblock.com/)

**Comment by uBlock-user** [comment]
Install uBlock Protector and then whitelist - 
`@@||playapi.mtgx.tv/*/adinfo?video=*^$xmlhttprequest,domain=play.tv3.lt`

**Comment by jonmei** [comment]
thanks, guys. It works fine only with uBlock Origin + uBlock Protector (adBlock disabled) and with 
```
@@||playapi.mtgx.tv/*/adinfo?video=*^$xmlhttprequest,domain=play.tv3.lt
```
addition to „My Filters“ which are in uBlock Origin settings. :)

**Comment by jspenguin2017** [comment]
I recommend you to install uBlock Protector List instead of adding the integration filter yourself.

**Comment by jonmei** [comment]
Actually, I've tried to install, but got:  uBlock Protector -  ListFailed, not a valid filters list

**Comment by uBlock-user** [comment]
Remove Adblock, only keep uBlock Origin and add uBlock Protector List as a custom filter via 3rd party filters tab.
