### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by Yuav** [reek/anti-adblock-killer#368]
Hides article when ad block enabled: https://www.tek.no/artikler/googles-autobiler-har-vaert-i-elleve-ulykker-pa-seks-ar/189543

https://i.imgur.com/H3io0RU.png?1

Mozilla Firefox
GreaseMonkey
Adblock Plus
EasyList + Adblock Warning Removal List + Aaklist

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
