### ISSUE TITLE
givemesome.tips

### ISSUE THREAD

**Issue by Darkknight33** [reek/anti-adblock-killer#369]
http://givemesome.tips/about/hackintosh/nireshs-yosemite-with-intel-amd-installation-instructions-160/
http://imgur.com/itooeiC
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
