### ISSUE TITLE
rte.ie

### ISSUE THREAD

**Issue by oopled** [reek/anti-adblock-killer#370]
http://www.rte.ie/player/ie/live/7/
http://imgur.com/bDmCK6O
Google Chrome
Tampermonkey
Adblock plus
Easylist + aaklist

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Sorry, geolocked content for me.

**Comment by MajkiIT** [comment]
https://www.dropbox.com/s/r6kobmm6amh7uvc/adblock10.png?dl=0
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

I don't see any notifications.

**Comment by MajkiIT** [comment]
@oopled 
Hi, do you still see this notification. 2 months ago EasyList add exclude to filters?

**Comment by reek** [comment]
I close issue, soved by easyslist
