### ISSUE TITLE
Anti Adsblock script make CKeditor 5 broken.

### ISSUE THREAD

**Issue by newz** [reek/anti-adblock-killer#3709]
Link page contains anti-adblock (not anti-adblock but make page broken)
https://docs.ckeditor.com/ckeditor5/latest/examples/builds/classic-editor.html

Screenshot
https://imgur.com/a/9elgY

Your browser
Chrome Lasted, Firefox Lasted

Your script manager
Tamper Monkey 4.4

Your adblocker
uBlock Origin 1.14.12

Your filterlists
Default + Anti Adsblock

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development.
