### ISSUE TITLE
jumbofile.net

### ISSUE THREAD

**Issue by anonsubmitter** [reek/anti-adblock-killer#371]
* Sample pages: https://www.google.com/#q=site:jumbofile.net
* jumbofile.net###s4a0
* I almost got infected with adware the first time I navigated through the page and stumbled across the Adblock warning, so I won't risk infecting my computer for a screenshot. Sorry.
* Firefox 37.0.2
* No script manager, I don't use the AAK script.
* Adblock Edge 2.1.9
 * Malware Domains
 * Spam404
 * EasyList
 * Fanboy's Annoyance List
 * Prebake
 * Block-EU-Cookie-Shit-List
 * Adblock Warning Removal List
 * Anti-Adblock Killer
 * EasyPrivacy
 * Fanboy's Enchanced Tracking List

**Comment by reek** [comment]
Stop report if you don't use AakScript

**Comment by anonsubmitter** [comment]
Sorry. I don't use the AAK script since I would have to install a script manager add-on and I don't want to clutter my Firefox installation with add-ons that I would barely use.
I'll stop reporting. Or would it be ok to submit reports as long as the domain in question isn't in anti-adblock-killer.user.js?

**Comment by reek** [comment]
As you do not install aakscript, I prefer that you do not report
