### ISSUE TITLE
freebitco.in and freedoge.co.in

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#372]
https://freebitco.in and https://freedoge.co.in
http://i.imgur.com/G1eVMBC.png
Google Chrome 64-bit
Tampermonkey
µBlock

Now that you are using AakScript, could you implement something to remove the ugly grey boxes where the advertisements used to be?

Thanks.

**Comment by reek** [comment]
Hi,

No because this is used to detect adblocker

**Comment by Injust** [comment]
And for your information, it's possible to block the ads and bypass the adblocker detection.
Here are the filters for both sites. Feel free to use them.

freebitco.in##.row-collapse > .columns.large-12 > .columns.push-3.small-7.large-9 > div:nth-of-type(7) > center > .ad-img
freebitco.in##.row-collapse > .columns.large-12 > .columns.small-7.large-9 > div:nth-of-type(7) > center > .ad-img
freebitco.in##.row-collapse > .columns.large-12 > .fbtc_left_sky.ad-img.columns.pull-9.small-5.large-3
freebitco.in##.row-collapse > .columns.large-12 > .fbtc_left_sky.ad-img.columns.small-5.large-3
freedoge.co.in##.row-collapse > .columns.large-12 > .columns.small-7.large-9 > div:nth-of-type(6) > center > .ad-img
freedoge.co.in##.row-collapse > .columns.large-12 > .fbtc_left_sky.ad-img.columns.small-5.large-3
