### ISSUE TITLE
seansik.tv

### ISSUE THREAD

**Issue by F4z** [reek/anti-adblock-killer#374]
For example http://seansik.tv/film/43771

Only with uBlock: http://i.imgur.com/fx5uLjG.png
uBlock + Tampermonkey (with Anti-Adblock Killer | Reek script): http://i.imgur.com/5ZVJc2d.png
(button to play video is not clickable)

Google Chrome 42.0.2311.152 m
Tampermonkey
uBlock Origin 0.9.7.0
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎
(When I disable Tampermonkey and in uBlock I disable EasyList filtr it works properly.)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
I find solution:
@@|http://myao.adocean.pl/ad.xml$xmlhttprequest,domain=seansik.tv

**Comment by F4z** [comment]
Thank you for answer.
Now with only uBlock and with my filters I don't need add any rules, I think that rules from AakList are sufficient now.

But with uBlock + Tampermonkey I need to add a rule from MajkIT
@@|http://myao.adocean.pl/ad.xml$xmlhttprequest,domain=seansik.tv
and also this rule
@@|http://myao.adocean.pl/__/ad.xml$xmlhttprequest,domain=seansik.tv
and now it works fine.

Thank you for help.

**Comment by MajkiIT** [comment]
On my PC I add only rule witch I add here. I can't see your second url.
https://www.dropbox.com/sh/wllsqp79y2dylym/AABIrx2426UMgRgs5oFEYeRva?dl=0

**Comment by F4z** [comment]
Screenshot from uBlock logger: http://i.imgur.com/8EUI0tE.png

**Comment by MajkiIT** [comment]
Ok thank's a lot. I will check it tomorrow.

**Comment by reek** [comment]
Disable AakScript and Update AakList

**Comment by MajkiIT** [comment]
I want to use AakScript, because I hate this ads https://github.com/reek/anti-adblock-killer/issues/300 . If I add rule @@|http://myao.adocean.pl/ad.xml$xmlhttprequest,domain=seansik.tv and @@|http://myao.adocean.pl/__/ad.xml$xmlhttprequest,domain=seansik.tv I haven't any problem. Of course I have:
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

**Comment by reek** [comment]
Hi,

It's temporary until I post Version 8.2.

Meanwhile add this meta block -> http://tinyurl.com/23y3gs
<code>// @exclude http*://seansik.tv/*</code>

See you
Reek

**Comment by MajkiIT** [comment]
For me OK.

**Comment by MajkiIT** [comment]
HI,
Today once again not be able to start movies on seansik.tv. This time I  add a rule:
@@| http: //go.goldbachpoland.bbelements.com/please/showit$xmlhttprequest,domain=seansik.tv

**Comment by MajkiIT** [comment]
Close this report. Page closed.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
