### ISSUE TITLE
DI.FM keeps telling to disable AdBlocker even disabled.

### ISSUE THREAD

**Issue by tipar** [reek/anti-adblock-killer#3747]
https://www.di.fm/about-blockers
https://imgur.com/a/utM2K (whole page)
Mozilla Firefox Quantum 57 (64 bits)
Greasemonkey
Adblock Plus (disabled)
**Filters**:
-_Normals_:
Adblock Warning Removal List
AakList
-_Advanced_:
Adblock Warning Removal List
Easylist
EasyPrivacy
Fanboy's Social Blocking List

The thing is before Quantum I had no problems but since yesterday I update to FQ I am having this problem. I have the grey icon of ABP but Di.fm keeps telling me to disable it and just plays a song each time I reload the page. The Anti-Adblock Killer | Reek from Greasemonkey is active, though. By the way, I have searched for the problem but I could not find it, sorry if I am duplicating issues. Regards.

**Comment by uBlock-user** [comment]
Can't reproduce.

URL - https://www.di.fm/indiebeats

`di.fm##.premium-upsell`

@jspenguin2017

**Comment by tipar** [comment]
> Can't reproduce.

URL - https://www.di.fm/indiebeats

di.fm##.premium-upsell

@jspenguin2017

Can you please explain yourself? I do not understand what do you mean.

**Comment by jspenguin2017** [comment]
@uBlock-user I thought this was fixed.

**Comment by uBlock-user** [comment]
If you say so, I don't remember atm.

**Comment by tipar** [comment]
So? No fix?

**Comment by tipar** [comment]
I have been experimenting and I have found that the problem was [Greasemonkey being not compatible](https://www.greasespot.net/2017/09/greasemonkey-4-for-users.html). With Tapermonkey (at least in Mozilla 57 Quantum) seems to work fine.
