### ISSUE TITLE
annuaire-bleu.net

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#375]
Hi,
on `http://www.annuaire-bleu.net/`
```
<img src="http://pagead2.googlesyndication.com/pagead/" width="0" height="0" border="0" alt="adblocktest" id="adblocktest" />

<script type="text/javascript">
function adblockblock() {
        document.location.href='nopub.html';
}
function adblocktest(testnumber) {
        abbitem=document.getElementById('adblocktest');
        if(!abbitem){
                adblockblock();
        } else if (abbitem.style.display == 'none' | abbitem.style.visibility == 'hidden'){
                adblockblock();
        } else if (testnumber!=1){
                setTimeout(function(){adblocktest(1);},4000);
        }
}
function doadblocktest(){
        if(adblocktest_orig_onload){adblocktest_orig_onload();}
        setTimeout(adblocktest,1000);
}
adblocktest_orig_onload=window.onload?window.onload:false;
window.onload=doadblocktest;
</script>
```

Thanks!

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
`@@||pagead2.googlesyndication.com/pagead/$image,domain=annuaire-bleu.net`

**Comment by reek** [comment]
Thank you, i forgot to add "domain=annuaire-bleu.net"

**Comment by reek** [comment]
Fixed !
