### ISSUE TITLE
xemvtv.net (flash broken)

### ISSUE THREAD

**Issue by hoangdreamer** [reek/anti-adblock-killer#377]
Chrome browser it too lag and flash is broken when i turn on aak user script

**Comment by reek** [comment]
Hi,

Ok, I'll add an exception for xemvtv.net

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
