### ISSUE TITLE
https://alcodistillers.ru/forum/

### ISSUE THREAD

**Issue by drobsf** [reek/anti-adblock-killer#3772]
https://alcodistillers.ru/forum/
Mozilla Firefox
Tampermonkey
Ublock Origin
EasyList + AakList

![33455916-9feadd22-d62e-11e7-8448-60dee6e36e03](https://user-images.githubusercontent.com/14965060/33470735-f4a23508-d67a-11e7-98d2-795913b1fcbe.png)

**Comment by uBlock-user** [comment]
`alcodistillers.ru##script:inject(abort-on-property-read.js, adblock)`

**Comment by drobsf** [comment]
Thank you!!
