### ISSUE TITLE
apkmirror.com

### ISSUE THREAD

**Issue by sachinsuyash** [reek/anti-adblock-killer#378]
The site still detects adbock.
Here's an example.
http://imgur.com/tE36lo5

**Comment by MajkiIT** [comment]
I don't see any notfications.

**Comment by sachinsuyash** [comment]
What setup are you using?

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

Sorry :)

**Comment by reek** [comment]
@sachinsuyash 
Your config please

**Comment by sachinsuyash** [comment]
Sorry here it is.
Google Chrome
Greasemonkey
uBlock
AdBlock Warning Removal List+EasyList+EasyPrivacy+Malware Domain List+AakList+PeteLowe'sAdServerList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SystemRevolution** [comment]
Hi Reek, here a *posible* solution:
By create and install the following userscript, the problem was gone.
```
// ==UserScript==
// @name         put-title
// @match        http://www.apkmirror.com/apk/*
// @run-at       document-end
// ==/UserScript==

e=document.querySelector('.gooWidget > .adsbygoogle');
for(var i=0;i<10;i++){
 var span=document.createElement('span');
 e.appendChild(span);
}
```
The secret is on `doCheck` function (declarated and queued on each apk page).
Good Luck!

**Comment by sachinsuyash** [comment]
I installed the script manually and can confirm it works.

**Comment by reek** [comment]
@SystemRevolution 
Thank you, even if I have already found the solution.

**Comment by reek** [comment]
@SystemRevolution 
I appreciate your help, but it would be more useful for me if you could find a solution to the requests with the label "geo lock" or "no solution", because all the others I already took care. Thank you

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
