### ISSUE TITLE
mojevideo.sk

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#379]
Hi, 
on `http://www.mojevideo.sk `
```
@@||pagead2.googlesyndication.com/pagead/show_ads.js$domain=mojevideo.sk
mojevideo.sk#@##video_ad
```
from https://adblockplus.org/forum/viewtopic.php?f=2&t=31142

Regards,
Med

**Comment by MajkiIT** [comment]
I have geo lock.
https://www.dropbox.com/s/dxy0srs2m77wcrz/adblock12.png?dl=0

**Comment by Bob90Lee** [comment]
the answer on that geo lock is "7"

**Comment by MajkiIT** [comment]
Add rules witch write  SMed79. It works.

**Comment by Bob90Lee** [comment]
thanks, I confirm that it works

**Comment by reek** [comment]
Thanks again Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
