### ISSUE TITLE
online.dramacafe.in

### ISSUE THREAD

**Issue by bilaltrr** [reek/anti-adblock-killer#380]
http://www.online.dramacafe.in/
http://i.imgur.com/HKvTnCw.png?1
Google Chrome
Native
Adguard Adblocker
EasyList + Liste AR + Anti-Adblock Killer | Reek

**Comment by MajkiIT** [comment]
I don't see any ads. Maybe install AakList Scripts.

Mozila Firefox
Greasemonkey + AakList Scripts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#instruction

**Comment by reek** [comment]
Remove Adguard and install Adblock or Adblock Plus or uBlock Origin

**Comment by bilaltrr** [comment]
Removed adguard, installed ublock origin. Problem solved! Thanks a lot

**Comment by reek** [comment]
Great, Dontt forget to donate, review, share, follow and add to favorites.
