### ISSUE TITLE
kisscartoon.me

### ISSUE THREAD

**Issue by Aireno** [reek/anti-adblock-killer#381]
http://kisscartoon.me/Cartoon/The-Incredibles-2004/Movie?id=1982
http://i.imgur.com/oNnl3X4.png
Google Chrome
Tampermonkey
Adblock Plus
Easylist + Adblock Warning Removal List + Disable Malware + Aaklist

**Comment by MajkiIT** [comment]
I haven't any notifications.

Mozila Firefox
Greasemonkey + AakList Scripts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@MajkiIT 
I have Message

**Comment by MajkiIT** [comment]
Sorry Reek, I do not understand you. What sort of message you have had?

**Comment by reek** [comment]
http://i.imgur.com/oNnl3X4.png

**Comment by MajkiIT** [comment]
Ok thanks. I thought you were angry for my comments.

**Comment by SystemRevolution** [comment]
The following userscript solves the problem:
```
// ==UserScript==
// @name         anything
// @match        http://kisscartoon.me/Cartoon/*
// @run-at       document-end
// ==/UserScript==

isBlockAds=false
```
Greetings

**Comment by rayman89** [comment]
I tried that script and didn't work for me but adding this exceptions to adblock did

@@||kisscartoon.me/ads/*$subdocument
@@||chango.com^$image,domain=kisscartoon.me
@@||kisscartoon.me/Scripts/jquery.allofthelights-min.js

**Comment by reek** [comment]
Hi,

I'll post a solution in the coming days, you just wait a little.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)
