### ISSUE TITLE
https://www.freecoursesonline.us/ (uBlock Origin) 

### ISSUE THREAD

**Issue by exodia6666** [reek/anti-adblock-killer#3810]
Firefox
Tampermonkey
uBlock
Aaklist + EasyList + Default list

Link:
https://www.freecoursesonline.us/

If Adblock is detected, it will block completely.
![capture](https://user-images.githubusercontent.com/10230139/33769655-96d33510-dc5d-11e7-91f8-fc7433681b6e.JPG)

**Comment by uBlock-user** [comment]
`freecoursesonline.us##script:inject(bab-defuser.js)`

**Comment by exodia6666** [comment]
work great.
