### ISSUE TITLE
mojevideo.sk

### ISSUE THREAD

**Issue by Bob90Lee** [reek/anti-adblock-killer#382]
http://www.mojevideo.sk/video/23d13/ked_rodinke_tucniakov_zomrie_mlada.html
http://imgur.com/MIv8ur3
Safari 8.0.6 on OSX 10.10.3
NinjaKit
AdBlock
AdBlock filter, EasyList, Čeština a Slovenčina, Antisocial filter list, Aak List

**Comment by MajkiIT** [comment]
Duplicated https://github.com/reek/anti-adblock-killer/issues/379

**Comment by MajkiIT** [comment]
Close this issue.
