### ISSUE TITLE
AakList notifications without anti-adblock-killer installed

### ISSUE THREAD

**Issue by paradonym** [reek/anti-adblock-killer#3826]
I haven't anti-adblock-killer installed, because once Google has disabled it due to malware problems I think... So I uninstalled the chrome extension.
Until then I regularily get a notification that I haven't subscribed to an Adblock-list called "AakList" - so it seems that thhe chrome extension hasn't been uninstalled completely. 

I currently use an Adblocker blocking the ads on network layers behind the browser on a network-driver-basis, so technically anything running in the browser actually can't see which lists or filtering rules I currently use.

How do I remove the residues left over after the uninstallation forced by Google from all Chrome users after the malware incident?
I haven't subscribed to this "AakList" and I won't subscribe to it, simply because it links back to a chrome extension which had a malware incident.

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development.

**Comment by paradonym** [comment]
This has already been happened automatically. Google disabled the extension on all Chrome-using PCs with an explicit warning when the user tries to re-activate - so I uninstalled it already.

**Comment by paradonym** [comment]
AAK has been active in my Windows adblocker. It's now removed.
