### ISSUE TITLE
zeperfs.com

### ISSUE THREAD

**Issue by nicolas-goudry** [reek/anti-adblock-killer#383]
http://www.zeperfs.com/perfs.php?Action=Duel
http://imgur.com/i1Icjc3
Google Chrome 42.0.2311.152 (on laptop)
Tampermonkey
Adblock Plus
EasyList + AakList (from github)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SystemRevolution** [comment]
This filter solves the problem:
@@http://www.zeperfs.com/adsbygoogle.js
If you view the script, there is only one line (var AdsOK = true;) and allowing it, the rest occurs itself.
Greetings.

**Comment by SystemRevolution** [comment]
This filter solves the problem:
`@@http://www.zeperfs.com/adsbygoogle.js`
If you view the script, there is only one line (`var AdsOK = true;`) and allowing it, the rest occurs itself.
Greetings.

**Comment by reek** [comment]
@SystemRevolution 
Thank you, even if I have already found the solution.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by nicolas-goudry** [comment]
Thanks a lot,

Keep the good work, I'll consider a donation in a few days !

See you.

**Comment by reek** [comment]
Hi,

Ok, thanks :smile:
