### ISSUE TITLE
digitalspy.com

### ISSUE THREAD

**Issue by meson1** [reek/anti-adblock-killer#3832]
aak seems to be failing to block the following anti-adblock:

link: http://www.digitalspy.com/

screenshot: ![](https://i.imgur.com/xDZTL9F.png)

browser: Chrome
scriptmanager: Tampermonkey
adblocker: Adblock Plus
filterlists:
https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/malwaredomains_full.txt
https://easylist-downloads.adblockplus.org/fanboy-social.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

All lists updated today (Dec 24, 2017 at 10:36 UTC)

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development.

**Comment by uBlock-user** [comment]
Post here - https://forums.lanik.us/viewtopic.php?f=62&t=6052&p=24561&hilit=digitalspy.com#p24561

It's patched in uBO.

**Comment by meson1** [comment]
Thanks.  I'll take a look.

**Comment by meson1** [comment]
I've installed uBO and uBO Extra.  Adblock counter measures on digitalspy.com are now history.

Many many thanks.  And I wish you all the best in this festive midwinter season.
