### ISSUE TITLE
moonbit.co.in

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#384]
http://moonbit.co.in/
http://i.imgur.com/RNPEgxr.jpg
Google Chrome 64-bit
Tampermonkey
uBlock

**Comment by reek** [comment]
Tested and its ok

**Comment by Blahx** [comment]
Try do the first claim, wait 5 mins (min waiting time), do another claim. It always shows up from then onwards.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Injust** [comment]
Right now, I've experimented with uBlock's dynamic filters, and I've been using these to bypass the anti-AdBlock detection, but they leave behind ugly placeholders.
I believe you might be able to remove the placeholders using userscripts as reek has done before, but I don't know how to do it myself.

The filters are:
moonbit.co.in googlesyndication.com * allow
moonbit.co.in moonbit.co.in * allow

**Comment by greatwolf** [comment]
Here's the solution I found, moonbit.co.in uses a custom adb detection. It uses a a hidden `<input>` tag where the field is a `true` or `false` depend if adblocker is present. My solution is to just remove that node altogether.

Here's the tampermonkey script I'm using:

    function adblock_checker()
    {
        // var target_tag = document.getElementById("AB");
        var target_tag = document.getElementById("E442Dv");
        console.log(target_tag);
        target_tag.remove();
    }

    window.onload = adblock_checker;

    setInterval(adblock_checker, 3000);

The elementId was formerly `AB` but the author of the faucet recently changed it to `E442Dv`. There may be a smarter way to detect this but for now this work for me.

**Comment by reek** [comment]
@greatwolf 
thank you, I had already detected this change

**Comment by Injust** [comment]
Please update this in the userscript, as I believe that the solution has been found.

**Comment by Injust** [comment]
By the way, the ID has been changed from E442Dv to eCC5h.

**Comment by reek** [comment]
@Injust 
Beta: https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by Injust** [comment]
@reek You still need to remove the moonbit.co.in filters fron the filter list. They are displaying placeholders.

**Comment by Injust** [comment]
@reek Please remove the moonbit.co.in filters from the filter list.

**Comment by reek** [comment]
@Injust 
ok, I would delete

**Comment by Injust** [comment]
@reek I just want to know, when do you update the filter list and the userscript? Is it on a schedule?

**Comment by greatwolf** [comment]
When are you incorporating this change into the main? The normal script install still only refers to the version with `#AB` only.

**Comment by Injust** [comment]
From what I can see, the userscript hasn't been updated for at least a month now...

**Comment by reek** [comment]
Hi,

Sorry, not too much the time and many requests, I am going to try to publish a new version in the next days.

See you
Reek

**Comment by Injust** [comment]
Just to make things easier for you, there are now three the script needs to block: #AB, #eCC5h, and #E442Dv.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
