### ISSUE TITLE
aftenposten.no

### ISSUE THREAD

**Issue by LarsErikOsterud** [reek/anti-adblock-killer#385]
Non of the ads warning filters take the norwegian anti-adblock warning.
Go to http://www.aftenposten.no and see "Skru på annonser" boxes all over :-(
More and more norwegian sites use this system to ask us to turn off ad-blocking.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
