### ISSUE TITLE
vg.no & aftenposten.no & bt.no & aftenbladet.no & fvn.no

### ISSUE THREAD

**Issue by LarsErikOsterud** [reek/anti-adblock-killer#386]
http://www.aftenposten.no/
![ad-block-aftenposten](https://cloud.githubusercontent.com/assets/12529644/7728954/6b4d1706-ff12-11e4-99ff-b7163aa4e597.jpg)
Firefox Nightly 40.0a1 (same on other browsers)
No script manager 
uBlock (same with ABP)
Easlylist + NOR Norsk Adblockliste

Additional info and my finding about the anti-ad method:

Found a way to counter-block the anti-ads ads.
They use a random class-name, so I had to use the style to identify.
All the Schibsted owned papers in Norway use this anti-ads method.

These filers work. My as they use only style they are not that good.
My I'm not an expert on this. Maybe you can make them better :-)

vg.no,aftenposten.no,bt.no,aftenbladet.no,fvn.no##[style="left: auto; position: relative; right: auto; width: 100%; height: 150px; margin-top: 0px; background-image: none; cursor: pointer;"]
vg.no,aftenposten.no,bt.no,aftenbladet.no,fvn.no##[style="right: -180px; left: auto; cursor: pointer;"]
vg.no,aftenposten.no,bt.no,aftenbladet.no,fvn.no##[style="cursor: pointer;"]

http://vg.no
http://aftenposten.no
http://bt.no
http://aftenbladet.no
http://fvn.no

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/385

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
