### ISSUE TITLE
next-episode.net

### ISSUE THREAD

**Issue by Jarusz** [reek/anti-adblock-killer#3865]
https://next-episode.net/
https://i.imgur.com/INPTS0W.png
firefox
ublock origin
nano defender
i turned on most of the lists

the only way to turn off the anti adblock on next episode (at least for me) is to set this bar to red here:
https://i.imgur.com/UR1ODWJ.png
but it also disables other scripts which i dont want to be disabled, such as - adding or removing episodes from my list
so is there a way around this?
i wasnt using adblock on NE, but i was getting that antiadblock popups from time to time, so if i get it anyways i thought id just block them...

**Comment by uBlock-user** [comment]
`next-episode.net##script:inject(set-constant.js, canRunAds, true)`

**Comment by Jarusz** [comment]
doesnt do anything

**Comment by uBlock-user** [comment]
Bypass the browser cache and reload the page

**Comment by Jarusz** [comment]
still doesnt do anything

**Comment by uBlock-user** [comment]
Can't reproduce it.

**Comment by Jarusz** [comment]
so theres no way to enable certain scripts (like the one i mentioned above) with that red bar enabled?

**Comment by uBlock-user** [comment]
I don't get what you get. Also you didn't bother to mention that you need an account. 

I get a different msg which I'm able to fix by breaking `window.google_jobrunner` variable. Something's wrong on your side. Force update all your filters and see if that helps.

**Comment by Jarusz** [comment]
sorry i didnt know its important about the account, unfortunetly nothing helps, but thanks for trying anyways, ive also read other issues about next episode, and thier solutions did not help either,

the only thing i dont understand is, ublock with the nano defender should block that antiadblock script just by itself, without me pressing red bars etc... but it doesnt
