### ISSUE TITLE
saikoanimes.net

### ISSUE THREAD

**Issue by DaniranS** [reek/anti-adblock-killer#387]
http://saikoanimes.net
Google Chrome (v. 42.0.2311.152)
Tampermonkey
Adblock Plus
EasyList + AakList (from github)

**Comment by reek** [comment]
Hi,

I have this message

<code>
Estamos em Manutenção
Desculpe pela inconveniência.
Nosso site está passando por manutenção programada.
Obrigado por sua compreensão.
</code>

**Comment by DaniranS** [comment]
Try again.

**Comment by DaniranS** [comment]
![image](https://cloud.githubusercontent.com/assets/12533338/7734628/6be0f078-ff05-11e4-9f7d-7d4bc2a0a66d.png)

**Comment by reek** [comment]
Already suppoted tested witn Firefox and Chrome, try update AakList

Why you use two Adblocker ? Have you add AakList on Adblock and Adblock Plus ?

**Comment by DaniranS** [comment]
Adblock Plus.
