### ISSUE TITLE
https://www.bytesloader.com/

### ISSUE THREAD

**Issue by khld** [reek/anti-adblock-killer#3872]
https://www.bytesloader.com/
![image](https://user-images.githubusercontent.com/10477539/35460139-280bb844-02e3-11e8-8026-6f92f89ffe21.png)

Google chrome
Tampermonkey
uBlockorigin
EasyList + AakList

**Comment by uBlock-user** [comment]
`bytesloader.com##script:inject(bab-defuser.js)`
