### ISSUE TITLE
tusmangas.net

### ISSUE THREAD

**Issue by pajaroenmano32** [reek/anti-adblock-killer#389]
![](http://i.imgur.com/A6T87MM.png)

http://tusmangas.net/i/manga-online/fairy-tail/436/1
Google Chrome
Tampermonkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SystemRevolution** [comment]
Solved by 2 required steps:
1. Add to the filter list:
`http://tusmangas.net/ama/oso.js$domain=tusmangas.net`
2. Run the following script
`$('#adsense').attr('id','')`

The filter removes the oso.js script to avoid code replace (and miss the img code). The script removes the "adsense" id to avoid AdBlock software to make it invisible (and reveal it :smile: )

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
