### ISSUE TITLE
not work on opera built-in adblocker !!

### ISSUE THREAD

**Issue by ilyasine** [reek/anti-adblock-killer#3891]
not work on opera built-in adblocker
![opera snapshot_2018-02-05_234518_apkmos com](https://user-images.githubusercontent.com/34688076/35834631-939d24d8-0ace-11e8-88a7-161ee27c3afd.png)

**Comment by uBlock-user** [comment]
Remove AAK, it's dead and no longer in development.

**Comment by ilyasine** [comment]
Is there an alternative ?
