### ISSUE TITLE
hdkinoteatr.com

### ISSUE THREAD

**Issue by kingsoft95** [reek/anti-adblock-killer#390]
http://www.hdkinoteatr.com/
http://imgur.com/FDzOJQg
google chrome 
tampermonkey
×   Enabled Adblock Warning Removal List Last updated at 11:20:32 AM today
×   Enabled EasyList Last updated at 11:20:32 AM today
×   Enabled RuAdList+EasyList Last updated at 7:23:46 PM today
×   Enabled ROList+EasyList Last updated at 7:25:14 PM today
×   Enabled AakList (Anti-Adblock Killer) Last updated at 7:37:42 PM today

**Comment by reek** [comment]
Hi,

I have nothing, try just Easylist and AakList

**Comment by kingsoft95** [comment]
hi ,tried the same ....try this video....http://www.hdkinoteatr.com/fantasy/727-harry-potter-and-the-deathly-hallows-part-1.html      if you have adblock you can't watch them in high quality

**Comment by reek** [comment]
Hi,

I need more informations
https://github.com/reek/anti-adblock-killer/wiki/Additional-Informations

**Comment by kingsoft95** [comment]
http://paste2.org/0VgZ2xgs

Adblock Plus 1.8.12
Google Docs 0.9
Google Sheets 1.1 
Google Slides 0.9
Office Editing for Docs, Sheets & Slides 104.1064.1131  
OkTools 2.8.2(disabled)
Tampermonkey 3.10.109

just anti adblock killer

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
