### ISSUE TITLE
coolgames.com

### ISSUE THREAD

**Issue by nitrocode** [reek/anti-adblock-killer#3902]
http://www.coolgames.com/en/bubble-academy.html

![coolgames](https://i.imgur.com/T9wpwQH.png)
```
Google Chrome
Tamper Monkey
uBO
uBlock Filters - Badware risks
uBlock Filters - Privacy
```

I added exceptions in uBO and it still detects adblock. How do they do it?

```
http://www.coolgames.com/images/ads_pattern.png
http://video-static.tunnl.com/js/ads.js?v=501
```

Funny, `ads.js?v=501` only returns this [value from SO](https://stackoverflow.com/a/20505898):

```
var canRunAds = true;
```

Interesting. In `game.js`, the code that detects it is:

```
            var a = null;
            try {
                google && (a = !1)
            } catch (e) {
                a = !0
            }
            if (!0 === d.gamedata.disablepreroll || a)
                a ? e(d.el.gameIframeContainer).css("background-color", "#fda110").html('<div id="block-warning"><p></p>') : (e(d.el.gameIframeContainer).removeClass("displayingPreroll"),
                d.createGameIframe());
            else {
```

Stepping through, I see `google` object wasn't instantiated and threw a null pointer which caused `a` to be true which then overwrites the html with the `block-warning` css to display the adblock image.

After setting `a` to false right before it checks for that value, it tries to load the game but not before it says: "You can continue playing your game after the following message" and has an infinite loader which never loads the game...

uBO is smart enough to redirect these 2 urls:

```
http://www.googletagservices.com/tag/js/gpt.js
https://www.google-analytics.com/analytics.js
```

but it doesn't redirect this js and I think that may be the culprit.

```
https://imasdk.googleapis.com/js/sdkloader/ima3.js
```

Thank you

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Try `coolgames.com##script:inject(set-constant.js, adBlockDetected, noopFunc)`

**Comment by nitrocode** [comment]
Thanks. jspenguin2017 was nice enough to solve this for me in NanoDefender https://github.com/NanoAdblocker/NanoDefender/issues/25

**Comment by uBlock-user** [comment]
Don't need an extension for that, just add that filter in uBO and you're good to go.
