### ISSUE TITLE
youtubeproxy.info

### ISSUE THREAD

**Issue by axarad** [reek/anti-adblock-killer#391]
Hi, Please add support for this website
url: http://youtubeproxy.info/
Greasemonkey+Aakiller
Ublock Origin
Aaklist+Easylist
![untitled](https://cloud.githubusercontent.com/assets/10789454/7768974/36a0b5fa-0078-11e5-87b8-d718a5e12a6f.png)
Source code: https://gist.github.com/axarad/42ce09cfd2f96361fafb
Thank you!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by axarad** [comment]
Source code: https://gist.github.com/axarad/42ce09cfd2f96361fafb

**Comment by MajkiIT** [comment]
In my opinion solutions is:

youtubeproxy.info##.rbx-middle.rbx-rt
youtubeproxy.info##.rbx-holder
@@|http://pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=youtubeproxy.info
youtubeproxy.info###aswift_2
youtubeproxy.info##.shbx

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
