### ISSUE TITLE
kisscartoon.me

### ISSUE THREAD

**Issue by rayman89** [reek/anti-adblock-killer#392]
Could you add support to this site?  The site loads properly at the beginning but after a few seconds the video player (either the flash or html5) gets blocked.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/381

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)

**Comment by rayman89** [comment]
Thanks. It's working.
