### ISSUE TITLE
https://www.rottentomatoes.com/search/?search=the%20resident

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#3920]

**Comment by uBlock-user** [comment]
?

**Comment by purevertigo** [comment]
When clicking that page for that site. I get  this. 
![screen shot 2018-02-23 at 01 52 34](https://user-images.githubusercontent.com/6506461/36545154-6329e20c-183c-11e8-96e3-39fe255f9d20.jpg)

**Comment by uBlock-user** [comment]
Something's blocking `cdnjs.cloudflare.com` on your end. I can't reproduce it.

try `@@||cdnjs.cloudflare.com/ajax/libs/$script,domain=rottentomatoes.com`

**Comment by purevertigo** [comment]
Thanks for the help. It seems to have fixed itself.

**Comment by uBlock-user** [comment]
Must be a bad filter.
