### ISSUE TITLE
http://www.atresplayer.com/television/

### ISSUE THREAD

**Issue by artisan69** [reek/anti-adblock-killer#3922]
Chrome + tampermonkey
Can't be enlisted

**Comment by uBlock-user** [comment]
for uBO - `atresplayer.com##script:inject(setTimeout-defuser.js, n.check)`

**Comment by artisan69** [comment]
thanks mate but I don't know what to do with that line. Do I have to insert it... where?
I just tried on ABP adding that line you gave to me but problem keeps.
Thank you.

**Comment by artisan69** [comment]
finally instaled ublock and worked just great. Thanks dude.
