### ISSUE TITLE
bolha.com

### ISSUE THREAD

**Issue by lencc** [reek/anti-adblock-killer#393]
bolha.com

The website is similar to eBay.
Problem: only when I try to enlarge picture within any individual listing, the enlarged picture does not show up. Instead, I can only see the white area:

![example](https://cloud.githubusercontent.com/assets/10838136/7774303/84c9373e-00aa-11e5-8088-eea40e221156.png)

I hope you can do anything about it, because I don't want the whole website (www.bolha.com) to be whitelisted.

Mozilla Firefox
uBlock Origin
My filters: Adblock Warning Removal List, Anti-Adblock Killer | Reek, EasyList, Peter Lowe's Ad server list

Thank you!

**Comment by reek** [comment]
HI,

The problem is not caused by Aak

You can fix it with this rule
<code>@@||bolha.com/js/gemius_.js$script</code>

or report it to https://forums.lanik.us/

Regards
Reek
