### ISSUE TITLE
www1.fmovies.se

### ISSUE THREAD

**Issue by Camris** [reek/anti-adblock-killer#3933]
www1.fmovies.se

Chrome
AdBlockPro
Tampermonkey
EasyList + AakList

**Comment by uBlock-user** [comment]
whats the issue ?

**Comment by Camris** [comment]
![blap](https://user-images.githubusercontent.com/31575235/36932705-8179681c-1ecd-11e8-9691-3a10b30dbe25.jpg)

**Comment by uBlock-user** [comment]
`fmovies.*##.hidden-xs.alert-warning.alert`

**Comment by Camris** [comment]
I have added it, but still cannot play the videos unless ABP is turned off. Here is link https://www1.fmovies.se/film/the-foreigner.920qm

**Comment by uBlock-user** [comment]
I can play it. Bad filter from Easylist perhaps. Report it to them.

**Comment by Camris** [comment]
Okies. Thanks for your help :D
