### ISSUE TITLE
writing.com (again)

### ISSUE THREAD

**Issue by CruaverVoidDrake** [reek/anti-adblock-killer#394]
I keep getting their "disable adblocker" request thing. If they didn't show such stupid ads I would just disable it but they do.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
