### ISSUE TITLE
Login Samsung account not working when Anti-Adblock Killer is active

### ISSUE THREAD

**Issue by ElenaPower** [reek/anti-adblock-killer#3957]
Hello,

MacOS Sierra 10.12.6, with Safari (or Chrome) and Tempermonkey with activated Anti-Adblock Killer.

I have to deactivate Anti-Adblock Killer when I want to login at:
accounts.samsung.com

I can type in email, password and click captcha but when I clock on login nothing happens when Anti-Adblock Killer is active.

Regards

**Comment by ElenaPower** [comment]
Sorry just saw it is mentioned before...

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice
