### ISSUE TITLE
 http://www.shqiptvlive.net/ 

### ISSUE THREAD

**Issue by ItsBeno** [reek/anti-adblock-killer#3959]
FireFox 
UBO
http://www.shqiptvlive.net/p/supersport-2-live.html

https://screenshots.firefox.com/SKu1w85hGLA0J3qs/www.shqiptvlive.net 

I've made same topic another time but the site has updated their script so i need help to kill it

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/reek/anti-adblock-killer/issues/3217

Nothing's changed, old solution still works.

**Comment by ItsBeno** [comment]
Yeah just i had write it wrong so thank you again !
