### ISSUE TITLE
stern.de

### ISSUE THREAD

**Issue by mf720** [reek/anti-adblock-killer#3962]
https://www.stern.de/tv/entstellt-durch-ex-freund--wie-vanessa-muenstermann-den-saeure-angriff-verarbeitet-7915934.html

![bildschirmfoto_2018-03-30_08-47-20](https://user-images.githubusercontent.com/37924252/38127655-716f6f2c-33f7-11e8-8bd9-41b09f4cc9dd.png)

Firefox 59.01 64 bit on Debian Linux
Greasemonkey
Ublock Orgin
EasyList germany + AakList

Also installed privacy Badger and Disconnect - but no change when I disable both and do a complete reload of the site - so I assume not hindering the AAK

Thank you + Regards MF

**Comment by uBlock-user** [comment]
Already patched by uBlock Origin, force update all your filters. Remove AAK too, it's abandoned.

**Comment by mf720** [comment]
Thank You!
