### ISSUE TITLE
https://www.techradar.com/

### ISSUE THREAD

**Issue by purevertigo** [reek/anti-adblock-killer#3963]
![screen shot 2018-03-31 at 22 46 47](https://user-images.githubusercontent.com/6506461/38162886-6f505226-3535-11e8-9842-0e3ec40202ff.jpg)

**Comment by uBlock-user** [comment]
Can't reproduce.

You may try `techradar.com##script:inject(abort-on-property-read.js, _sp_)`

**Comment by purevertigo** [comment]
Might have been fixed already. Thanks anyways.
