### ISSUE TITLE
https://apkmos.com

### ISSUE THREAD

**Issue by B4rabbas** [reek/anti-adblock-killer#3968]
hello the script don't work with this site
https://apkmos.com

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice

**Comment by KiLL4FuNK** [comment]
uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

**Comment by B4rabbas** [comment]
Oh I didn't notice the project is discontinued, my bad.
