### ISSUE TITLE
bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com

### ISSUE THREAD

**Issue by greatwolf** [reek/anti-adblock-killer#397]
This uses a simliarly named `show_ads.js` as #376 

 - |robcoins.eu
 - |elenabitco.in
 - |freebetco.in
 - |qoinfaucet.com
 - printmoney.info

The easy fix is to append them to the end of

    @@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com

**Comment by reek** [comment]
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
