### ISSUE TITLE
last.fm displaying anti-adblock ad after user-logon

### ISSUE THREAD

**Issue by GintokiHub** [reek/anti-adblock-killer#3971]
last.fm displaying anti-adblock ad after user-logon

if you need more details please hit me up

**Comment by GintokiHub** [comment]
https://a.safe.moe/FWD8Qla.jpg

**Comment by uBlock-user** [comment]
Follow the [template](https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md#require) and edit your post accordingly.
