### ISSUE TITLE
wpolityce.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#398]
http://wpolityce.pl/polityka/245707-studio-wyborcze-ruchu-kontroli-wyborow-prowadza-stankiewicz-reszczynski-skowronski-transmisja
https://www.dropbox.com/s/r9tfxt52ou3scyk/adblock14.png?dl=0
Mozila Firefox
Greasemonkey + AakList Scripts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ without element hiding rules+ Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

solution
@@|http://razem.tv/Scripts/InsysPlayer.v0.1.0/adTest.png$image,domain=razem.tv

**Comment by reek** [comment]
Thanks

**Comment by MajkiIT** [comment]
Me on 2 computers it works...
https://www.dropbox.com/s/soyn02uin4kdp2q/adblock15.png?dl=0

What you see?

**Comment by reek** [comment]
I need allow element hiding

**Comment by MajkiIT** [comment]
Ok thank you.

**Comment by reek** [comment]
I'll add your filter anyway

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
