### ISSUE TITLE
https://www.dplay.no/videoer/thomas-giertsen-helt-perfekt/like-barn-leker-best

### ISSUE THREAD

**Issue by MrDemocracy** [reek/anti-adblock-killer#3982]
<img width="618" src="https://imgur.com/YuuVeya.png">

- Browser: Google Chrome
- Script Manager: Tampermonkey
- AdBlocker: uBlock Origin
- Filters:
Adguard Base Filters
Adguard Annoyances
Adguard English Filter
[Norwegian Filter List](https://raw.githubusercontent.com/uBlockAdmin/uBlock/master/assets/thirdparties/home.fredfiber.no/langsholt/adblock.txt)
AakList

**Comment by uBlock-user** [comment]
Follow the [template](https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md#require) and edit your post accordingly.

**Comment by MrDemocracy** [comment]
I've updated my post.

**Comment by uBlock-user** [comment]
Add `@@||fwmrm.net/ad/g/1?$domain=dplay.no`

**Comment by MrDemocracy** [comment]
Thank you :)
