### ISSUE TITLE
https://a-o.ninja

### ISSUE THREAD

**Issue by KochamLolitki** [reek/anti-adblock-killer#3983]
eg: https://a-o.ninja/anime/black-bullet/1
https://imgur.com/a/0QBiU
Google Chrome
tampermonkey
Ublock origin
Easy + aak + ublock filters + malware domains

**Comment by uBlock-user** [comment]
https://github.com/MajkiIT/polish-ads-filter/commit/3ede54f92aa4d381235bfc4a36b7c19a12add815

**Comment by KochamLolitki** [comment]
Thanks you're the best <3
