### ISSUE TITLE
https://www.svd.se/

### ISSUE THREAD

**Issue by Fredricz** [reek/anti-adblock-killer#3985]
https://www.svd.se/
https://imgur.com/a/b5tJX
Google Chrome
TamperMonkey
Adblock Plus
EasyList + AakList

**Comment by uBlock-user** [comment]
Follow the [template](https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md#require) and edit your post accordingly.

**Comment by Fredricz** [comment]
Ty, better? :)

**Comment by uBlock-user** [comment]
https://forums.lanik.us/viewtopic.php?f=62&t=39845&p=131758&hilit=svd.se#p131758

**Comment by KiLL4FuNK** [comment]
uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

**Comment by Fredricz** [comment]
Worked by installning uBlock instead of adblock.... Thanks

**Comment by Fredricz** [comment]
Install uBlock and remove adblock
