### ISSUE TITLE
Kiss Manga is detecting adblockers now

### ISSUE THREAD

**Issue by ZeroXFFF1** [reek/anti-adblock-killer#3988]
http://kissmanga.com/

No Reek AAK
![image](https://user-images.githubusercontent.com/15783773/38966529-b8dddda4-4350-11e8-9af1-1fcd4cbcf5c9.png)

With updated Reek AAK
![image](https://user-images.githubusercontent.com/15783773/38966664-6da09baa-4351-11e8-94e4-6538f334a3a2.png)

The site they are buying this service from is https://blockadblock.com/

**Comment by uBlock-user** [comment]
patched in uBlock, force update uBlock Filters
