### ISSUE TITLE
sharecash.org

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#399]
Hi,
on `http://www.update-lollipop.org/mp3-0/lenovo-a536-6674.html`

![http://i.imgur.com/gK49UfV.png](http://i.imgur.com/gK49UfV.png)

source: https://forums.lanik.us/viewtopic.php?f=62&t=22703

Thanks!

**Comment by reek** [comment]
Already solved

**Comment by SMed79** [comment]
Thanks!
