### ISSUE TITLE
sport.wp.tv & komediowo.pl & pudelek.tv

### ISSUE THREAD

**Issue by FrancisPL** [reek/anti-adblock-killer#40]
http://sport.wp.tv/i,Sonda-WP-Mateusz-Mika,mid,1547094,index.html#m1547094 please block ads before movie
www.komediowo.pl (no video - information about adblock)
Mozila Firefox 31
Scriptish
Adblock Plus 2.6.4
EasyList  Without Element hiding + Anti-Adblock Killer | Filters for Adblockers + Polish list 
https://raw.githubusercontent.com/adblockpolska/Adblock_PL_List/master/adblock_polska.txt
http://i.imgur.com/lxVdReE.png
Block ads before movie in http://www.pudelek.tv

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/300

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
