### ISSUE TITLE
nowtv.de Fix

### ISSUE THREAD

**Issue by hoshie** [reek/anti-adblock-killer#400]
Hi Reek,

the german rtl group has consolidated their VOD services from different sites to one single site.

The new domain is nowtv.de

You just need to add the domain to Line 2548

I've already changed and tested it locally - works perfectly:
```javascript
host : ['voxnow.de', 'rtl-now.rtl.de', 'rtl2now.rtl2.de', 'n-tvnow.de', 'superrtlnow.de', 'rtlnitronow.de', 'nowtv.de'],
```
Hint: Leave the other domains (i.e. voxnow.de) in the script because deep in the source code they sometimes still link to the other domains. I think when their system runs for a couple of months only nowtv.de is needed.

Thanks,
hoshie

**Comment by hoshie** [comment]
Update: it looks like it was working for 10 minutes but sometimes i can see still ads in between of the video parts. 

@reek Maybe you can have a look with your expert knowledge.

**Comment by reek** [comment]
Sorry, no solution and no time
