### ISSUE TITLE
9anime.is adblock detected ublock origin

### ISSUE THREAD

**Issue by koaie** [reek/anti-adblock-killer#4005]
https://www4.9anime.is/watch/one-piece.ov8/m60v6p
https://i.imgur.com/TYl0awZ.png
running grease monkey
windows 10
firefox 56
all filters are on and updated

**Comment by uBlock-user** [comment]
Disable cosmetic filtering and try..

**Comment by koaie** [comment]
just tried , still doesnt work?

**Comment by uBlock-user** [comment]
wait for 5 seconds before clicking play on the video, a smiley box should appear in the extreme right corner of the player and then click play

**Comment by koaie** [comment]
disabled cosmetic filters in Default behavior
enabled "Ignore generic cosmetic filters" in my filters
same thing , still cannot watch with ublock origin enabled 
i dont see a smiley box pops up tho.

**Comment by uBlock-user** [comment]
> I dont see a smiley box pops up tho.

That's why, unless a smiley box pops up, you won't be able to watch.

**Comment by koaie** [comment]
what am i doing wrong?

**Comment by officiallyzaid** [comment]
same problem

**Comment by RaitaroH** [comment]
Yeah, same problem. If anything 9anime is a pain to keep without ads.

For the people who care here is what I hide:
```
! 11/15/2017, 5:44:30 PM https://9anime.is/watch/mahoutsukai-no-yome.046k/8l3kp3
9anime.is##.ads.toggler.mbtn.item

! 11/15/2017, 9:23:04 PM https://9anime.is/watch/mahoutsukai-no-yome.046k/4v4pv7
9anime.is##.alert-warning.alert

! 11/15/2017, 9:23:28 PM https://9anime.is/watch/mahoutsukai-no-yome.046k/4v4pv7
9anime.is##.text-center.widget-body > div:nth-of-type(2)

! 11/26/2017, 7:45:54 PM https://9anime.is/watch/mahoutsukai-no-yome.046k/0ov4j5
9anime.is##.pa

! 2/2/2018, 9:16:29 PM https://9anime.is/watch/darling-in-the-franxx.rv5n/m4np3p
9anime.is###sidebar

! 4/21/2018, 9:25:15 PM https://www4.9anime.is/watch/golden-kamuy.qjlj/93p7nn
www4.9anime.is##div[style*="height:768px"]
```
Check the last one for the newest addition to their ads. Very annoying.


Also uMatrix:
```
9anime.is * media allow
9anime.is ajax.googleapis.com * allow
9anime.is bebi.com * block
9anime.is cloudflare.com * allow
9anime.is connect.facebook.net * block
9anime.is facebook.net * block
9anime.is fonts.googleapis.com * allow
9anime.is googleusercontent.com * allow
9anime.is mc.yandex.ru * inherit
9anime.is oloadcdn.net * allow
9anime.is openload.co * allow
9anime.is openload.co frame allow
9anime.is platform.twitter.com * block
9anime.is rapidvideo.com * allow
9anime.is syndication.twitter.com * block
9anime.is twitter.com * block
9anime.is www.rapidvideo.com frame allow
9anime.is yandex.ru * block
```
I am always amazed just how much crap can be on one site at once. Is quite amazing. Also I love who they say they only have banners, no popups and yet disabling uMatrix just for a bit I got like 10 popups that closed right after.

**Comment by uBlock-user** [comment]
patched. Force update uBlock Filters.
