### ISSUE TITLE
onet.pl + subdomains

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#401]
People on this portal use this script to detect adblock "lib.onet.pl/s.csr/adp/adp.js"

**Comment by reek** [comment]
I would add a rule to block it

**Comment by MajkiIT** [comment]
Ok thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
