### ISSUE TITLE
https://developers.google.com/machine-learning/crash-course/ml-intro

### ISSUE THREAD

**Issue by rpennellcccs** [reek/anti-adblock-killer#4010]
https://developers.google.com/machine-learning/crash-course/ml-intro
Google auto detect my adblocker even used Nano adblocker along with Nano defender and I can't see video, hope @uBlock-user will fixed it.
Webpage screenshot:
![fireshot capture 1 - introduction to machine learning i m_ - https___developers google com_machi](https://user-images.githubusercontent.com/20731270/39296809-75426306-4974-11e8-98b7-ed55cfc925a9.png)

**Comment by uBlock-user** [comment]
`developers.google.com##.warning`

It's not detecting, just offering a warning which can be hidden with the above rule. Unfortunately blocking of google-analytics's script is causing the player not to appear. Need to add `developers.google.com` to the _Unbreak_ list.

@okiehsch
