### ISSUE TITLE
adblock detected on https://www.atresplayer.com/

### ISSUE THREAD

**Issue by artisan69** [reek/anti-adblock-killer#4016]
Ublock + chrome

**Comment by uBlock-user** [comment]
force update uBlock Filters.

**Comment by artisan69** [comment]
Thanks mate, forced the update but anti-adblock still pops up.

**Comment by uBlock-user** [comment]
@okiehsch

**Comment by okiehsch** [comment]
`@@||adpass.atresmedia.com/*/adjs.js$domain=atresplayer.com`

**Comment by artisan69** [comment]
Thanks!! It works.
