### ISSUE TITLE
Yahoo Whitelist Pop-up

### ISSUE THREAD

**Issue by p1nkyy** [reek/anti-adblock-killer#4017]
I'm on Firefox & ABP.

Screenshot is kinda like below but in English. When I tried to access my Yahoo, the pop-up doesn't appear.

https://i.imgur.com/pKW5Xrb.png

**Comment by uBlock-user** [comment]
for ABP filters post on Easylist website.

**Comment by KiLL4FuNK** [comment]
uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4
