### ISSUE TITLE
Kisscartoon.net

### ISSUE THREAD

**Issue by YamiryuuZero** [reek/anti-adblock-killer#403]
http://kisscartoon.me/Cartoon/The-SpongeBob-Movie-Sponge-Out-of-Water/Movie-HD?id=54794 (All domains under http://kisscartoon.me/Cartoon/[X] have anti-AdBlock scripts that bypass anti-adblock-killer) 
![adblock](https://cloud.githubusercontent.com/assets/12602946/7803677/194aa16c-032c-11e5-8280-8c5c9c0c6c6e.jpg)
Vivaldi Browser 1.0.178.2 (Developer Build) 
Tampermonkey 3.10.109
AdBlock 2.33
No filter list applied

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/381

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)
