### ISSUE TITLE
Dallas News anti-adblock

### ISSUE THREAD

**Issue by Wrench69** [reek/anti-adblock-killer#4032]
67.0.3396.40 beta (64-bits)
uBlock
Easylist, Malware domains
![dallasnews](https://user-images.githubusercontent.com/31038127/39910688-adeb73ac-54f8-11e8-9613-710b70718459.jpg)

https://www.dallasnews.com/news/dallas-police/2018/05/10/much-nra-convention-presidents-visit-cost-dallas-police

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jaredheath** [comment]
This is easy to  reproduce for me

https://www.dallasnews.com/business/technology/2018/05/30/air-antenna-gets-120-channels-free-broadcast-tv 

does it today.

**Comment by Wrench69** [comment]
It doesn't anymore, the problem is solved!

**Comment by uBlock-user** [comment]
Please close this issue then.

**Comment by Wrench69** [comment]
Closed
