### ISSUE TITLE
palimas.com

### ISSUE THREAD

**Issue by hennihau** [reek/anti-adblock-killer#404]
http://palimas.com/adblock.php
Opera,  Chrome
Tampermonkey
Adblock Plus
Filterlists : Anit Adblock Killer | Reek
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js

Easylist

Screen: http://i.imgur.com/ou0ia4n.png

**Comment by reek** [comment]
Hi,

Its a fake porn site.
