### ISSUE TITLE
vg.no

### ISSUE THREAD

**Issue by LarsErikOsterud** [reek/anti-adblock-killer#405]
http://vg.no
![vg-anti-ad](https://cloud.githubusercontent.com/assets/12529644/7822800/43299764-03f8-11e5-9c01-807330d63b0f.jpg)
Mozilla Firefox
<no script>
uBlock
Anti-Adblock-killer + EasyList + NOR

Seems like vg.no has a variant of the methode you fixed.
Still use the same random style sections. But this one has no style parameters.
So I can't remove it by any filtering on style content.
Also it seems to change (reload a couple of time, some times it shows, sometime not).

Also I found that the newspapers I reported earlier (that you fixed) keep shuffelig the style tags.
So that too block all the anti-ad-filters you have to split up the style mateches like this:

vg.no,aftenposten.no,bt.no,aftenbladet.no,fvn.no##[style*="left: auto;"][style*="position: relative;"][style*="right: auto;"][style*="width: 100%;"][style*="height: 150px;"][style*="margin-top: "]
vg.no,aftenposten.no,bt.no,aftenbladet.no,fvn.no##[style*="right: -180px;"][style*="left: auto;"]
vg.no,aftenposten.no,bt.no,aftenbladet.no,fvn.no##[style="cursor: pointer;"]

But the trikcest is the one at vg.no with no style and random class name :-(

**Comment by reek** [comment]
HI,

The problem probably comes from EasyList who authorized all hidden elements, 

try disable manualy filter <code>@@||www.vg.no^$elemhide</code> or disable NORlist

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
