### ISSUE TITLE
www4.9anime.is

### ISSUE THREAD

**Issue by lukexj** [reek/anti-adblock-killer#4050]
Im getting this message when i try to play a video

"Please disable AdBlock then try again.
If you want to watch anime in high quality without ads,
just get a subscription in premium anime site.
Thanks for your supporting!"
https://i.imgur.com/DJ3eqNG.png

Tampermonkey
Mozilla Firefox
uBlock Origin

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/issues/2333
