### ISSUE TITLE
http://watchtheoffice.online

### ISSUE THREAD

**Issue by 19971999** [reek/anti-adblock-killer#4058]
Site is using BlockAdblock
https://imgur.com/k0YUeA5
Chrome 66.0.3359.181
uBlock Origin
Tampermonkey
Anti-Adblock killer 10
Aak list

Thanks!

**Comment by uBlock-user** [comment]
`watchtheoffice.online##script:inject(bab-defuser.js)`

**Comment by 19971999** [comment]
Perfect thanks
