### ISSUE TITLE
t3n.de

### ISSUE THREAD

**Issue by alexander255** [reek/anti-adblock-killer#406]
This site does not require disabling the ad blocker (or RequestPolicy in this case), it just repurposes the free banner space for some "disable please" message. Just in case this is in scope for AAK...

These filters fix this page:

    t3n.de##.abContentMsg
    t3n.de##.adb

http://t3n.de/news/snapchat-wert-kolumne-595389/
![Screenshot](http://i.imgur.com/BYMv6Ij.png?1)
Mozilla Firefox
Greasemonkey
Adblock Edge + RequestPolicy
EasyList Germany + Fanboy's Annoyance + AakList + Private

**Comment by reek** [comment]
Ok, thanks !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
