### ISSUE TITLE
https://www.obi.de

### ISSUE THREAD

**Issue by Lonermax** [reek/anti-adblock-killer#4060]
Hey,

the search function don't work anymore with the script enabled.

![obi](https://user-images.githubusercontent.com/2746287/40649287-cf3042ae-6330-11e8-8428-7743051ca2d4.png)

Solution: `/^https?:\/\/www\.obi\.de.*$/` works fine for _**>me<**_
Chrome
uBlock origin
Tampermonkey

Sincerely

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued
