### ISSUE TITLE
Doesn't work on http://techmantium.com/10-great-notepad-colour-schemes/#

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [reek/anti-adblock-killer#4062]
Actually doesn't work neither on the test page.

Mozilla Firefox 60.0.0.1
Greasemonkey / Reek 10.0
Ublock origin
EasyList + AakList

https://i.imgur.com/3ywQD2Z.png
https://i.imgur.com/h5JX95r.jpg

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

post on https://github.com/uBlockOrigin/uAssets/issues

**Comment by Vulgaris-Viridis** [comment]
Oh, what a pity.. Is there an alternative that you know of? Thanks anyway.

**Comment by Vulgaris-Viridis** [comment]
Thank you.
