### ISSUE TITLE
It doesn't work on http://www.chimica-online.it/

### ISSUE THREAD

**Issue by pk50s** [reek/anti-adblock-killer#4063]
http://www.chimica-online.it/
https://imgur.com/CBCgNrZ
Firefox 60.0.1 (64 bit) on windows 7
Greasemonkey

These are my filters:
uBlock Origin
uBlock filters​​​​​5.868 usati su 5.922​​
uBlock filters – Badware risks​ ​​​​11 usati su 11​​
uBlock filters – Privacy​​​​​93 usati su 97​​
​​uBlock filters – Resource abuse​​​​​136 usati su 259​​
​​uBlock filters – Unbreak​​​​​426 usati su 439​​
EasyList​ ​​​​82.256 usati su 82.
EasyPrivacy​ ​​​15.015 usati su 15.062​​
​​Malware Domain List​​​​​1.116 usati su 1.131​​
Malware domains 2.330 usati su 22.330​​
Peter Lowe’s Ad and tracking server list​ ​​​​2.638 usati su 2.639​​
ITA: EasyList Italy​ ​​​​4.440 usati su 4.440​​​​

I have done this test ( http://tinyurl.com/qecfa7w ) and it failed

Thank you

**Comment by uBlock-user** [comment]
Follow the [template](https://github.com/reek/anti-adblock-killer/blob/master/CONTRIBUTING.md#require) and edit your post accordingly.

**Comment by pk50s** [comment]
@uBlock-user Done, thank you

**Comment by uBlock-user** [comment]
`@@||chimica-online.it^$elemhide`

**Comment by pk50s** [comment]
@uBlock-user  sorry, what does it means?

**Comment by uBlock-user** [comment]
Add it in My Filters.

**Comment by pk50s** [comment]
Thank you, if it happens again with some other websites what can i do?

**Comment by uBlock-user** [comment]
Report there - https://github.com/uBlockOrigin/uAssets/issues

**Comment by pk50s** [comment]
Okay thank you
