### ISSUE TITLE
Does not work on volkskrant.nl

### ISSUE THREAD

**Issue by GintokiHub** [reek/anti-adblock-killer#4067]

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

**Comment by GintokiHub** [comment]
thanks for the update, appreciate it, 
do you know of any replacement?

**Comment by uBlock-user** [comment]
No, just stick to using uBlock Origin and report any anti adblock issues  on uAssets - https://github.com/uBlockOrigin/uAssets/issues

**Comment by GintokiHub** [comment]
ok will do thank you,
This can be closed as far as I am aware

**Comment by uBlock-user** [comment]
I can't close it, close it yourself.
