### ISSUE TITLE
wtfbit.ch

### ISSUE THREAD

**Issue by FstJosh** [reek/anti-adblock-killer#407]
Anti-Adblock on the following sites : 
 * http://hackintosh.zone/
 * http://wtfbit.ch/
 * http://givemesome.tips/

Brings up image saying to disable Adblock.
Also shows this text, "If it doesn't work disable ADBlock completely, Click Try Again, Enable ADBlock, Add This website to Exceptional List"

On any browser.

**Comment by reek** [comment]
Hi,

Please made a request for each website
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

For http://wtfbit.ch/ solution is |http://cdn.wtfbit.ch/wp-admin/external.js?606484$script,domain=wtfbit.ch
On http://givemesome.tips/ I don't see any notification.

**Comment by reek** [comment]
@MajkiIT 
wttbit.ch: this is one possible solution
givemesome.tips: has already been added

**Comment by MajkiIT** [comment]
I'm sorry I wanted to help.

**Comment by reek** [comment]
@MajkiIT 
No worries

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
