### ISSUE TITLE
not working on site

### ISSUE THREAD

**Issue by unclelala** [reek/anti-adblock-killer#4076]
not working on this site       https://nolfgirl.net/Unityhq/forums/

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

uBO - `nolfgirl.net##script:inject(set-constant.js, adblock, false)`

**Comment by 3bsa** [comment]
`@@/*_adframe.js$script,domain=nolfgirl.net`

**Comment by unclelala** [comment]
thanks for the info guys
