### ISSUE TITLE
Please add https://soft98.ir

### ISSUE THREAD

**Issue by Mahd78** [reek/anti-adblock-killer#4078]
It's an Iranian website that I use it and recently I can't view download link
Site ask me to disable my adblock plugin

**Comment by robin98** [comment]
Yeah, Check it!
I think they are using a very advanced ad-block killer method!

**Comment by Mahd78** [comment]
Oops I forgot that website won't allow non iranian IP enter
So I don't think you can do any thing. please remove this

**Comment by robin98** [comment]
Nooo! They can use proxy, or just change the ip address in http header!
or they can ask us to send them a copy of the site elements.

**Comment by Mahd78** [comment]
that's good

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

**Comment by Mahd78** [comment]
That's sad
