### ISSUE TITLE
https://hexafile.net

### ISSUE THREAD

**Issue by What-Zit-Tooya** [reek/anti-adblock-killer#4094]
1. https://hexafile.net/nXex5
2. https://imgur.com/fxBF0nl
3. Mozilla Firefox 
4. Greasemonkey
5. uBlock Origin
6. EasyList, uBlockFilter, EaseyPrivacy, Malware domain list, hpHosts, MVPS HOSTS, Regions Language (ara, RU, IDN, JPN, KOR)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

Force update uBlock Filters.

**Comment by What-Zit-Tooya** [comment]
@uBlock-user Solved

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/84580704/120067332-9ea82300-c083-11eb-896c-9139fb35dce2.png)

**Comment by What-Zit-Tooya** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/84580704/120067332-9ea82300-c083-11eb-896c-9139fb35dce2.png)

![1](https://user-images.githubusercontent.com/9832875/120090041-b2a66000-c129-11eb-8189-85c63eaee7f8.png)
