### ISSUE TITLE
Sankakucomplex.com

### ISSUE THREAD

**Issue by Sezuel** [reek/anti-adblock-killer#4095]
![untitled](https://user-images.githubusercontent.com/40340940/41510672-bc083d02-721d-11e8-8683-a0dc2dce43da.png)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

**Comment by KiLL4FuNK** [comment]
use @Sezuel

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

**Comment by Sezuel** [comment]
@KiLL4FuNK thanks ... appears to have fixed my issue by using that addon instead
