### ISSUE TITLE
Question regarding uBlock Origin + uMatrix

### ISSUE THREAD

**Issue by thwaller** [reek/anti-adblock-killer#4097]
I was wondering if uMatrix running in addition to uBlock Origin would or might cause issues with anti-adblock-killer. I did read the direction and uMatrix is not listed as one of the problematic ones to look for, and I know is says to only use one adblocker. Where it is a bit unclear is if uMatrix is considered an adblocker here or not.. I mean it is, but it is not. I assume people here will understand what I am saying and asking. If not, let me know for more clarification and explanation.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

uMatrix is a browser firewall, that is all.

**Comment by thwaller** [comment]
LOL! ... on the missed discontinuation. I would agree on your answer though, a firewall. I will remove this.

I wonder.... how/why was this userscript updated 60 days ago? Regardless, that is the info I relied upon as how current.

**Comment by thwaller** [comment]
I wonder.... how/why was this userscript updated 60 days ago? Regardless, that is the info I relied upon as how current.
