### ISSUE TITLE
heavenly-blue.net

### ISSUE THREAD

**Issue by grandprx** [reek/anti-adblock-killer#410]
http://heavenly-blue.net/1878867 (or other document)

Mozilla Firefox
uBlock
Anti-Adblock-killer + EasyList

what should appear
http://i.imgur.com/YEJiyMP.png
with adblock (and their adblock detection)
http://i.imgur.com/7weAv40.png

using following filter seems to kill it
>@@||heavenly-blue.net^$elemhide

thank you for maintaining this list

**Comment by reek** [comment]
Hi,

Ok, thanks !

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
