### ISSUE TITLE
Kisscartoon.me

### ISSUE THREAD

**Issue by Felina-Lain** [reek/anti-adblock-killer#411]
http://i.imgur.com/oU5gdOe.png?1
Chrome 43.0.2357.81 m
Tampermonkey
Adblock

AakList (Anti-Adblock Killer)
4shared
EasyList (recommandé)

Note: it was working perfectly fine a couple days ago, and it started being annoying today, the website probably upgraded their stuff

**Comment by reek** [comment]
Duplicated: https://github.com/reek/anti-adblock-killer/issues/381

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)

**Comment by Felina-Lain** [comment]
Dev' version work perfectly fine! thanks ^^
