### ISSUE TITLE
Not working with player.americadigital.com.ar

### ISSUE THREAD

**Issue by freddre** [reek/anti-adblock-killer#4111]
`http://player.americadigital.com.ar/` is using this anti adblock script:
`http://iframe.statics.space/magma/stable/libs/blockadblock.min.js`

I'm unable to block it.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki/AAK-Dead-and-Discontinued

**Comment by KiLL4FuNK** [comment]
use @fredsif

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4
