### ISSUE TITLE
filmovizija.in

### ISSUE THREAD

**Issue by selena5222222** [reek/anti-adblock-killer#412]
Hello, I am using Anti-Adblocker which stopped functioning for website Filmovizija : 

1.  www.filmovizija.com

2.  http://imgbox.com/XEbpmVIK

3. My browser is Google Chrome.

4. Tampermonkey is my script manager.

5. Adblock Plus is the Adblocker.

6. Filters : Aaklist & Easylist.

I have done as said in instructions. Anti Adblocker was working perfectly last thursday, since monday it is not working.

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey + AakList Scripts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

For me, solution is |http://www.filmovizija.in/parent.js?_$xmlhttprequest,domain=filmovizija.in , but interesting is also |http://www.filmovizija.in/popads-adblock.js$script,domain=filmovizija.in .

**Comment by selena5222222** [comment]
Thank you for the responce, sadly this isnt my solution cause Im not using Firefox, it blocks my laptop constantly, not even 6GB of ram memory on win 7 64 bit didnt make it work properly for some reason so Im not using it at all.
But anyway thank you for the help.
 


     MajkiIT <notifications@github.com> schrieb am 13:30 Freitag, 29.Mai 2015:
   

 Mozila Firefox
Greasemonkey + AakList Scripts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter For me, solution is |http://www.filmovizija.in/parent.js?_$xmlhttprequest,domain=filmovizija.in , but interesting is also |http://www.filmovizija.in/popads-adblock.js$script,domain=filmovizija.in . —

**Comment by MajkiIT** [comment]
But rule is universal. Insert this rule to Adblock. Settings ==> own filters ==> blocking rules

**Comment by reek** [comment]
Hi Selena,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
