### ISSUE TITLE
kozaczek.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#414]
Hi,
kozaczek.pl##.bpopup-adblc-modal-box
kozaczek.pl##.__b-popup1__.b-modal

on kozaczek.pl
https://www.dropbox.com/s/iwd0qwyqppx48l6/adblock18.png?dl=0

The same on http://www.zeberka.pl/
MajkiIT

**Comment by MajkiIT** [comment]
Solution is @@|http://www.kozaczek.pl/js/ads.js$script,domain=kozaczek.pl and @@|http://www.zeberka.pl/js/ads.js$script,domain=zeberka.pl

**Comment by reek** [comment]
@MajkiIT 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
