### ISSUE TITLE
kissanime.com

### ISSUE THREAD

**Issue by x3nit** [reek/anti-adblock-killer#415]
- http://kissanime.com/Anime/Shokugeki-no-Souma/Episode-009?id=109878 (for example)
- http://i.imgur.com/eukVAju.png (after like 10-15 sec)
- Google Chrome
- Dont know what this is (sorry if im dumb)
- I try with adblock/ABP/uBlock no one works
- http://i.imgur.com/Oqgonf0.png

**Comment by reek** [comment]
You need use AakScript.
