### ISSUE TITLE
not working for www.rmdown.com

### ISSUE THREAD

**Issue by eromoe** [reek/anti-adblock-killer#4155]
I am udinh ublock origin,  get warning at

http://www.rmdown.com/link.php?hash=1831385108ac59700ee2cf32305584a567a82cf8ed0

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice

**Comment by eromoe** [comment]
@uBlock-user Do you have any substitutes to recommend ?

**Comment by KiLL4FuNK** [comment]
use @eromoe

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4
