### ISSUE TITLE
Help :( Animeflv

### ISSUE THREAD

**Issue by Tou-u** [reek/anti-adblock-killer#4159]
Not work in https://animeflv.net/ver/49487/island-1

![captura](https://user-images.githubusercontent.com/43365564/45667450-908e6000-baef-11e8-8bcb-d5a5079d7be6.PNG)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice

**Comment by KiLL4FuNK** [comment]
use @rodrignacio

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4
