### ISSUE TITLE
Not working on Next-Episode.net

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#4168]
Doesn't block the warnings on next-episode.net

I use uBlock Origin to block the warnings but they reappear every time I revisit the site.

**Comment by KiLL4FuNK** [comment]
What other extensions do you use?
ami do not show me anything

**Comment by ghost** [comment]
Backspace to go Back
Checker Plus for Gmail™
Death To _blank
Disable Download Bar
DuckDuckGo Privacy Essentials
Google Translate
Hover Zoom
HTTPS Everywhere
LastPass: Free Password Manager
MEGA
Poper Blocker
Pushbullet
SimpleExtManager
Stylus
Tampermonkey
uBlock Origin
uBlock Origin Extra

**Comment by KiLL4FuNK** [comment]
update filters

![2018-10-18_19h27_30](https://user-images.githubusercontent.com/36675858/47187876-27775380-d30c-11e8-9149-81c7a318d7b0.png)

you delete these extensions 
then try again


Poper Blocker
DuckDuckGo Privacy Essentials

**Comment by ghost** [comment]
I disabled those Extensions and updated uBlock Origin. Still doesn't remove adblock warning.

Here are the Tampermonkey scripts I have installed:
AAK-Cont For uBlock Origin
Anti-Adblock Killer | Reek
RARBG - Add Direct Torrent Link

![capture](https://user-images.githubusercontent.com/6305400/47188491-df513480-d2fd-11e8-80d3-c03c14bc6079.JPG)

**Comment by KiLL4FuNK** [comment]
first I recommend you delete Anti-Adblock Killer | Reek 



This project has been abandoned & discontinued by @reek since November 2016, please uninstall the userscript/filterlist and everything associated with this project and

https://github.com/reek/anti-adblock-killer/wiki#notice



deactivate all extensions  leave only ublock origin and then try again



ami do not show me anything

![2018-10-18_19h57_39](https://user-images.githubusercontent.com/36675858/47188958-a5d5f480-d310-11e8-9e5b-a1ed92f218ad.png)

**Comment by ghost** [comment]
I removed all Reek content. Still has an adblock warning.

I disabled all Extensions except uBlock and uBlock Extra and it didn't show a warning.

I don't know what is causing the issue. I even tried disabling each Extension one-by-one and it always showed the warning. I assume it is a conflict between two Extensions or conflicting Settings. I am using the latest version of Slimjet.

**Comment by uBlock-user** [comment]
obligated FYI - https://github.com/reek/anti-adblock-killer/wiki#notice

**Comment by ghost** [comment]
The adblock warning doesn't appear unless you have an account and are logged in. So you won't see it if you are an anonymous visitor to the site.
