### ISSUE TITLE
Not Working on xiaomitoday.com

### ISSUE THREAD

**Issue by washere** [reek/anti-adblock-killer#4169]
Not Working on xiaomitoday.com

Thanks for the superb work, loving it. :)

**Comment by KiLL4FuNK** [comment]
use @washere

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

**Comment by washere** [comment]
@KiLL4FuNK 

I stopped using uBlock and it's variations. It creates many probelms in all sorts of areas. As many of us have experienced.

It is not worth the problems it causes.

**Comment by washere** [comment]
Nano adblocker fixed it for the above site and also makeuseof.com site.

Highly recommended, I think development is still ongoing too:

https://jspenguin2017.github.io/uBlockProtector/

https://github.com/NanoAdblocker/NanoCore#nano-adblocker-core

https://chrome.google.com/webstore/detail/nano-adblocker/gabbbocakeomblphkmmnoamkioajlkfo/related
