### ISSUE TITLE
comics-sanctuary.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#417]
Hi, 
on `http://www.comics-sanctuary.com/`

![comics-sanctuary.com](https://cloud.githubusercontent.com/assets/1873139/7896948/9552c7fa-06c2-11e5-93d0-78fa14532e30.png)

Thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
