### ISSUE TITLE
Not working against mockingbird.js

### ISSUE THREAD

**Issue by austinhuang0131** [reek/anti-adblock-killer#4170]
[This repo](https://github.com/retargetly/mockingbird) is another adblock detector. I encountered it on [this site](https://www.canadianunderwriter.ca/).

I am using uBlock Origin w/ Tampermonkey. The script is loaded locally according to my console (The remote version is blocked by 1host).

**Comment by austinhuang0131** [comment]
nvm

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice
