### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#419]
http://vod.pl/filmy/polskie-gowno-zwiastun-premiera-19-06/ytbgnf
https://www.dropbox.com/s/wcmnkc3cwlv2t0q/adblock19.png?dl=0
Mozila Firefox
Greasemonkey + Anti-Adblock-scipts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

When Anti-Adblock-scipts are enable then I haven't play button. Then I disable then it's ok.

**Comment by reek** [comment]
Ok, I'll exlude

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
