### ISSUE TITLE
Javascript needs to be disabled?

### ISSUE THREAD

**Issue by ShalokShalom** [reek/anti-adblock-killer#4198]
I just installed this tool and run the test in the instructions. It recommends to disable JS, otherwise it will not work. Why?

**Comment by CaptainFrosty** [comment]
No one is going to answer you. This project is abandoned. Not sure why doesn't just close the repo.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice
