### ISSUE TITLE
trakt.tv

### ISSUE THREAD

**Issue by JimmyRecard** [reek/anti-adblock-killer#420]
https://trakt.tv/shows/supernatural/ and https://trakt.tv/shows/game-of-thrones (and any link matching https://trakt.tv/shows/*)
https://i.imgur.com/e1a1sPL.png
Google Chrome Version 43.0.2357.81 m (current stable)
N/A (Chrome Native Extension)
uBlock
Adblock Warning Removal List‎ +  Anti-Adblock Killer | Reek‎ + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Fanboy's Enhanced Tracking List‎ + Fanboy’s Annoyance List‎

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
**my temporary solution:**
**for top and bottom notice:**
<code>trakt.tv###huckster-desktop-top</code>
<code>trakt.tv###huckster-desktop-bottom</code>

**for top and bottom. but 1 line:**
<code>trakt.tv###huckster-desktop-wrapper</code>

from main page:
you have Disconnect extension. I dont know your another extensions releated.
*"Check if one of these extensions is problematic (Disable Anti-Adblock 3.1, Ghostery, Online Security Avast, Donotrackme, Privacy Badger, Disconnect, Blur, TrackerBlock, Kaspersky Anti-Banner, Freebox (Anti-pub), No Script)."*

**Comment by reek** [comment]
@maynak00 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
