### ISSUE TITLE
Need a filter to block the https://ebonus.gg/ adblock message

### ISSUE THREAD

**Issue by kaioloureiro** [reek/anti-adblock-killer#4203]
The Anti-Adblock killer isn't working with this message on https://ebonus.gg/
I need a filter to block it manually
![image](https://user-images.githubusercontent.com/22198551/50579823-a79f5680-0e2f-11e9-829f-20a6c74ed33c.png)

**Comment by KiLL4FuNK** [comment]
use @kaiohpj

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/


uBlock Origin Microsoft Edge

https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

**Comment by kaioloureiro** [comment]
> use @kaiohpj
> 
> uBlock Origin Google Chrome
> 
> https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es
> 
> uBlock Origin Mozilla Firefox
> 
> https://addons.mozilla.org/es/firefox/addon/ublock-origin/
> 
> uBlock Origin Opera
> 
> https://addons.opera.com/es-419/extensions/details/ublock/
> 
> uBlock Origin Microsoft Edge
> 
> https://www.microsoft.com/en-us/store/p/ublock-origin/9nblggh444l4

Already tried. Tried Aak-Conti too but no success

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice

**Comment by KiLL4FuNK** [comment]
What extensions do you use? @kaiohpj

**Comment by kaioloureiro** [comment]
> What extensions do you use? @kaiohpj

Currently I'm using Adblock. Already tried to use Adblock Plus, uBlock Origin, Nano, etc.. The message from this specific website keeps appearing to me.

**Comment by uBlock-user** [comment]
report on uAssets then repository then.

**Comment by KiLL4FuNK** [comment]
show a capture of the page that part specifies the message appear ? @@kaiohpj

first use a blocker only do not mix several then disable the antivirus or any blocking extension

to report problems of uBlock Origin report here 

> https://github.com/uBlockOrigin/uAssets/issues

![2019-01-05_09h31_49](https://user-images.githubusercontent.com/36675858/50724513-37adfc00-10cd-11e9-9a2a-5d22e1b481fb.png)

**Comment by Chetan7575** [comment]
Use adguard.

**Comment by hdpc2015** [comment]
> Use adguard.

adguard don't work!!!!!!!!!

**Comment by Chetan7575** [comment]
I check your site with adguard. I dont face adblock warning issue.

**Comment by hdpc2015** [comment]
> I check your site with adguard. I dont face adblock warning issue.

Are you sure? Have you tried in this page?

https://ebonus.gg/earn-coins/watch/lol

**Comment by Chetan7575** [comment]
Yes, adguard Working. i don't face any issue on that site.
First i told that what i use.

Anti adblock killer script on tempormonkey.
adguard adblocker.
and i add custom anti adblock killer filter from this site.
https://reek.github.io/anti-adblock-killer/
just slide page and select your adblocker. it will add automaticaly.
All done...

**Comment by hdpc2015** [comment]
Ok, but the video is loading for you? i can't play while using this script/adguard.

**Comment by Chetan7575** [comment]
but this video loading completely on my side. which browser do you use?

**Comment by Chetan7575** [comment]
wait wait, this issue also happened in my site. i complaint about this issue on adguard.

**Comment by Chetan7575** [comment]
Problem Fixed. Now Adguard Work. Without any ads and anti adblock warning.

**Comment by hdpc2015** [comment]
Excelent, thanks! Do you know what a have to do to make the video load automatically when the page's reload? It used to be that way.

**Comment by kaioloureiro** [comment]
> Problem Fixed. Now Adguard Work. Without any ads and anti adblock warning.

And what you did?

**Comment by Chetan7575** [comment]
@kaiohpj 
i did a complaint to adguard team.

**Comment by uBlock-user** [comment]
good then close this.

**Comment by kaioloureiro** [comment]
> @kaiohpj
> i did a complaint to adguard team.

Thank you. Its working now. I'm closing it.
