### ISSUE TITLE
FoodNetwork (foodnetwork.com) 

### ISSUE THREAD

**Issue by polleyt** [reek/anti-adblock-killer#4205]
Adblocker is still detected on the foodnetwork.com website:
![image](https://user-images.githubusercontent.com/13224057/50659220-c9442f00-0f50-11e9-9888-801604c5f7fd.png)

The anti-adblock killer is working great on all other sites I have tested so far. I do use FN pretty often for recipes, so it would be great to use it without the adblocker being detected! I'm using uBlock (version 1.17.4) on Chrome (version 71.0.3578.98). 

Thank you for any assistance!

**Comment by KiLL4FuNK** [comment]
eliminate anti-adblock killer project has been abandoned what protects you is the ublock origin. 

> https://github.com/reek/anti-adblock-killer/wiki#notice





it is solved with only enable annoyances filters @polleyt  

![2019-01-03_22h03_59](https://user-images.githubusercontent.com/36675858/50669411-d63e3e00-0fa3-11e9-8c06-bfcfa0b3ae2a.png)

**Comment by polleyt** [comment]
Thank you KiLL4FuNK! That seems to have done the trick. 

I didn't realize this project had been abandoned. Bummer. 

Thanks again.

**Comment by uBlock-user** [comment]
Abandoned since 2016
