### ISSUE TITLE
does not work on coinmarketcap

### ISSUE THREAD

**Issue by kopes18** [reek/anti-adblock-killer#4218]
https://coinmarketcap.com/currencies/ripple/

**Comment by euphorical** [comment]
Of course it's someone looking up XRP.. jk, lol =P
 
Same issue here. It was blocking it for a little while, but now the anti-adblock popup is showing up again.
The sheer number of ponzi schemes being advertised is ridiculous, and it's too bad they've gone with this route.

![ScreenShot 02-28-19](https://user-images.githubusercontent.com/5444311/53593089-c5561700-3b65-11e9-91f5-0a18cc511982.png)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice

**Comment by KiLL4FuNK** [comment]
use @kopes18

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/
