### ISSUE TITLE
digitaltrends.com

### ISSUE THREAD

**Issue by FlamingFox911** [reek/anti-adblock-killer#4234]
URL: https://www.digitaltrends.com/computing/best-laptops-under-300/
Screenshot: ![image](https://user-images.githubusercontent.com/11638944/55405704-a3ff9680-5528-11e9-8c23-b6f4c62ff319.png)
Browser: Chrome
Script Manager: TamperMonkey
Adblocker: Adblock Plus
Filter Lists:

- AakList (Anti-Adblock Killer)
- Adblock Warning Removal List
- ABP filters
- EasyList
- 

> ablebits.com###common-floatbanner-big
> ablebits.com##.floatbanner-big.br5-bigstrip
> soundcloud.com##.userNav__item.userNav__button.userNav__activitiesButton
> quora.com###__w2_qn1QSO3_wrapper
> quora.com##.irintcwobvlbueozgajd
> soundcloud.com##.notificationIcon.activities
> soundcloud.com##.header__userNavItem.header__userNavButton.header__userNavActivitiesButton
> experts-exchange.com##.ctaSolutionSticky
> medium.com##.u-fixed.u-bottom0.u-width100pct.u-backgroundWhite.u-boxShadowTop.u-borderBox.u-paddingTop10.u-paddingBottom10.u-zIndexMetabar.u-xs-paddingLeft10.u-xs-paddingRight10.js-stickyFooter
> soundcloud.com##.streamHTUpsell
> ontariohighwaytrafficact.com###fixusertop
> ontariohighwaytrafficact.com##.callout.large
> ontarioticket.com###upbg
> dev.to##.base-article-show-sidebar-variant
> aspdotnet-suresh.com###g207
> @@||businessinsider.com^$elemhide
> /mp3-ad/*$domain=open.spotify.com|play.spotify.com
> ||audio-fa.scdn.co/audio/$media,domain=open.spotify.com|play.spotify.com
> ||washingtonpost.com/wp-stat/pwapi/prod/*

**Comment by Eyremba** [comment]
Please read this... https://github.com/reek/anti-adblock-killer/wiki

This project has been abandoned & discontinued.

**Comment by FlamingFox911** [comment]
That's unfortunate. Was good while it lasted.

**Comment by KiLL4FuNK** [comment]
use @FlamingFox911

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/

**Comment by FlamingFox911** [comment]
I already switched from ABP to uBlock + AAK Cont. Thanks.
