### ISSUE TITLE
agar.io

### ISSUE THREAD

**Issue by alexander255** [reek/anti-adblock-killer#424]
Site shows unobtrusive Anti-AdBlock message:

    agar.io###helloDialog > center > small.text-muted
    agar.io###blocker

http://agar.io/
Mozilla Firefox (Iceweasel)
Greasemonkey
Adblock Edge
EasyList + FanBoy's Annoyance + AakList

**Comment by reek** [comment]
Thanks Alex

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
