### ISSUE TITLE
No more 3rd-party-filters in uBlock

### ISSUE THREAD

**Issue by Marco-Sulla** [reek/anti-adblock-killer#4245]
I don't know why I have to add these filter to Adblock Plus and uBlock (both are needed?) if I also have installed your userscript... anyway:

I tried also to paste 
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

and 
https://rawcdn.githack.com/reek/anti-adblock-killer/a87431fb62ac8f2264f193514ffaa8171418879b/anti-adblock-killer-filters.txt

in Custom filters, but they are discarded.

PS: `Subscribe from reeksite.com` link is broken in `Readme.md`
PPS: no problem in Adblock Plus.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/wiki#notice

the entire project died in 2016

**Comment by Marco-Sulla** [comment]
Well, you should mark as abandoned in greasyfork.org and in the other script sites... and in the readme of this repo.

**Comment by uBlock-user** [comment]
no amount of marking would help if people don't bother to read before posting.

**Comment by Marco-Sulla** [comment]
Excuse me? There's no information in the [Readme.md](https://github.com/reek/anti-adblock-killer/blob/master/README.md). Do you pretend an user must go to the wiki, that usually is empty on Github?

Furthermore I'm here because I read the description on greasyfork.org that links here, and have no warnings about the project. I could also install the userscript and I never knew that the project is dead.

So excuse me if I say you should inform your user better, because a simple obscure entry in the wiki it's not enough. Not at all.

**Comment by Marco-Sulla** [comment]
See #4246

**Comment by bogachenkove** [comment]
@MarcoSulla You have big brains, right?
Question. How will he accept this if the project is abandoned and he has gone into the sunset?
Look at how much PR is not accepted, but of course he will accept yours.

**Comment by uBlock-user** [comment]
No, excuse me first. Do I look like @reek ? He's the one who can merge PRs and edit readme, so instead of lecturing me, make an effort to go through the wiki or browse around. The project is dead for 2 fucking years ! and if you can't be arsed to even browse around and do some little research before slamming these pointless issues here, then it's your problem. You're the one who's not in the loop here like the rest of the others who can't simply/won't bother to take some time and do some browsing before hitting the New Issue button.

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/4204 and yet nobody read that either and it went down the drain and then on the other page, people don't read, period.

**Comment by Marco-Sulla** [comment]
@uBlock-user Yes, you're right. The next time I download the entire site with `curl` and I `grep` for any file that contains the words `abandoned`, `dead` or `f**d`.
