### ISSUE TITLE
wikitrik.com

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#4267]
https://wikitrik.com/XDpmW

(
Please disable your ad blocker!
This site is supported by the advertisement
Please disable your ad blocker to support us!!! 
)

**Comment by KiLL4FuNK** [comment]
use @xorcan

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/

**Comment by ghost** [comment]
no I'm using nano Adblocker with nano defender and I'm OK now :)
