### ISSUE TITLE
Hackintosh.zone

### ISSUE THREAD

**Issue by tancrackers** [reek/anti-adblock-killer#427]
When EasyPrivacy is enabled, Hackintosh.zone blocks your browsing and display this image / message:
https://s3.amazonaws.com/f.cl.ly/items/3F0t2c0L360t1A1l0A2W/disable-adblock.png

I disabled EasyPrivacy and noticed that when NoScript blocks "googlesyndication.com," this message gets triggered.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
