### ISSUE TITLE
Kissanime.com

### ISSUE THREAD

**Issue by dhanrahl** [reek/anti-adblock-killer#430]
Recently switched to a new video player. No longer shows video container with Userscript active, but audio remains (it's just hiding the div container). Using Firefox 38.0.5

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
