### ISSUE TITLE
videostar.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#431]
Hi, 
||4vod.tv//assets/js/adcheck.js?v=6$script,domain=videostar.pl

on videostar.pl . 

MajkiIT

**Comment by reek** [comment]
@MajkiIT 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
