### ISSUE TITLE
listenonrepeat.com Admiral notification

### ISSUE THREAD

**Issue by Oppion44** [reek/anti-adblock-killer#4326]
Annoying getadmiral popup and monthly subscription begging on https://listenonrepeat.com/

Because paying $110 for Netflix, Amazon etc. already isn't enough.

**Comment by liamengland1** [comment]
use uBlock Origin and Nano Defender

**Comment by Oppion44** [comment]
I'm using those and hudreds of custom filters. I wouldn't post here if all the "common" methods would be working.

**Comment by liamengland1** [comment]
Ok, may I suggest not using this list and expecting support from an abandoned project?

**Comment by Oppion44** [comment]
Thanks bogachenko :-)
