### ISSUE TITLE
oploverz.net needs fix

### ISSUE THREAD

**Issue by UkiND** [reek/anti-adblock-killer#433]
using ublock ,admuncher, and your script with gressmonkey, can't access the web with adblock enabled. 
thank you reek~

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey + Anti-Adblock-scipts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding

Change admuncher to ublock.

**Comment by UkiND** [comment]
well, one of this app should be disabled to open those web. problem
resolved , thanks

**Comment by reek** [comment]
@MajkiIT 
Thanks
