### ISSUE TITLE
onet.tv

### ISSUE THREAD

**Issue by osfp** [reek/anti-adblock-killer#434]
Some examples:

http://onet.tv/k/sawardega/sa-wardega-jurassic-world-dinosaurs-prank/cbw7rf

http://eurosport.onet.pl/pilka-nozna/kadra/adam-nawalka-blaszczykowski-nie-mam-zadnych-obaw/6vqc0v

**Comment by MajkiIT** [comment]
Duplicated https://github.com/reek/anti-adblock-killer/issues/423

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
