### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by isamuakira** [reek/anti-adblock-killer#4342]
Not Working anymore : http://www.ovagames.com
with adblock +

**Comment by isamuakira** [comment]
sorry, im turn on adblock opera

**Comment by KiLL4FuNK** [comment]
use @isamuakira

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/
