### ISSUE TITLE
turkanime.net

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#4344]
turkanime.tv changed their domain as turkanime.net and when i use aak, images which on turkanime doesn't loading.

**Comment by PentagramTr** [comment]
Bu filtre (AAK) artık desteklenmiyor ve en önemlisi de Türkçe sitelerde hiçbir işe yaramaz. Sadece AdGuard uzantısı ve filtreleri Türkçe siteleri destekler.

Eğer uBlock Origin kullanıyorsanız sadece aşağıdaki filtreleri seçin ve devamlı güncelleyin.

<details><summary>Screenshot:</summary>

![blo](https://user-images.githubusercontent.com/34379403/75311083-c304c680-5866-11ea-99cc-ee8a13292017.png)


</details>


AdGuard kullanıyorsanız bu filtreleri seçin ve filtreleri devamlı güncelleyin. Ek olarak Gizlilik Modu'nu açabilirsiniz ve "Genel" başlığındaki ayarların hepsini kapatın. "Filtre Güncelleme Sıklığı" ayarını ise siz belirleyin.

<details><summary>Screenshot:</summary>

![as](https://user-images.githubusercontent.com/34379403/75311097-c8621100-5866-11ea-966c-3311a1e3cf79.png)


</details>
