### ISSUE TITLE
https://www.lewat.club/post/fil-drama-korea-2020

### ISSUE THREAD

**Issue by abdullahhafizh** [reek/anti-adblock-killer#4354]
[https://www.lewat.club/post/fil-drama-korea-2020](https://www.lewat.club/post/fil-drama-korea-2020)

> **_my adblock still detected_**

`Chrome Version 78.0.3904.108 (Official Build) (64-bit)`
`Adblock Plus`

**Comment by KiLL4FuNK** [comment]
use @abdullahhafizh

uBlock Origin Google Chrome

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=es


uBlock Origin Mozilla Firefox

https://addons.mozilla.org/es/firefox/addon/ublock-origin/


uBlock Origin Opera

https://addons.opera.com/es-419/extensions/details/ublock/
