### ISSUE TITLE
onlinetv.planetfools.com (FuckAdblock)

### ISSUE THREAD

**Issue by warefoster** [reek/anti-adblock-killer#436]
http://www.onlinetv.planetfools.com/tvenvivo/tdn-deportes-en-vivo.php
http://imgur.com/j3YIKJR
Mozilla Firefox
Greasemonkey
Adblock Edge
EasyList + AakList

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey + Anti-Adblock-scipts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding

If I disable Greasemonkey I havent't any notification and see video.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
