### ISSUE TITLE
btava.com

### ISSUE THREAD

**Issue by thelastfantasy** [reek/anti-adblock-killer#437]
Sample page:
http://www.btava.com/search?keyword=mimk+036
Screenshot:
http://i.imgur.com/WcSczn8.png

**Comment by MajkiIT** [comment]
Solution is @@|http://www.btava.com/eroex.js$script,domain=btava.com

MajkiIT

**Comment by thelastfantasy** [comment]
Works, thank you!

2015-06-11 1:48 GMT+08:00 MajkiIT <notifications@github.com>:

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@MajkiIT 
Thanks, i will add it to AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
