### ISSUE TITLE
https://www.sozcu.com.tr/

### ISSUE THREAD

**Issue by alicantsezer** [reek/anti-adblock-killer#4376]
anti adblock killer does not work properly on this web page. Using Chrome, Adblock Plus, tempermonkey.

**Comment by ghost** [comment]
Bu filtre (AAK) artık desteklenmiyor ve en önemlisi de Türkçe sitelerde hiçbir işe yaramaz. Sadece AdGuard uzantısı ve filtreleri Türkçe siteleri destekler.

Eğer uBlock Origin kullanıyorsanız sadece aşağıdaki filtreleri seçin ve devamlı filtreleri güncelleyin.

**<details><summary>Screenshot:</summary>**

![blo](https://user-images.githubusercontent.com/34379403/75311083-c304c680-5866-11ea-99cc-ee8a13292017.png)


</details>


AdGuard kullanıyorsanız bu filtreleri seçin ve filtreleri devamlı güncelleyin. Ek olarak Gizlilik Modu'nu açabilirsiniz ve "Genel" başlığındaki ayarların hepsini kapatın. "Filtre Güncelleme Sıklığı" ayarını ise siz belirleyin.

Başka filtre kullanmayın çünkü gerek yok ve fazla filtre kullanmak bazı sitelerde sorun çıkarabiliyor. Ayrıca birden fazla reklam engelleyici de kullanmayın. Bu ikisinden birini seçin çünkü en iyisi bu ikisidir.


**<details><summary>Screenshot:</summary>**

![as](https://user-images.githubusercontent.com/34379403/75311097-c8621100-5866-11ea-966c-3311a1e3cf79.png)


</details>

**Comment by alicantsezer** [comment]
Thanks for notifying.
