### ISSUE TITLE
schoener-fernsehen.com

### ISSUE THREAD

**Issue by rafuse** [reek/anti-adblock-killer#438]
http://schoener-fernsehen.com/

After 1-2 minutes of watching, i get this anti-adblock message:
http://i.imgur.com/xzWxCSX.png

Mozilla Firefox for Mac 39.0 (Beta)
Greasemonkey
uBlock Origin
EasyList + EasyList Germany + AakList

Thank you for your great work btw :)

**Comment by MajkiIT** [comment]
Solution is |http://peer-stream.com/api/AdvertisementPlugin$object-subrequest

MajkiIT

**Comment by rafuse** [comment]
Adding a second "|" in front did the trick for me! Thanks alot!

||http://peer-stream.com/api/AdvertisementPlugin$object-subrequest

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@MajkiIT 
Thanks, i will add it to AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
