### ISSUE TITLE
plus-belle-la-vie-replay.blogspot.com

### ISSUE THREAD

**Issue by zifff** [reek/anti-adblock-killer#439]
http://plus-belle-la-vie-replay.blogspot.com/2015/06/plus-belle-la-vie-episode-2773.html
http://imgur.com/AoBMLlW  ( => anti-adblock )  
http://imgur.com/qV2ilqw ( => normal )
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey + Anti-Adblock-scipts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding 

I don't see notyfication. For me it's Ok. Update filters.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by zifff** [comment]
http://plus-belle-la-vie-replay.blogspot.com/2015/06/plus-belle-la-vie-episode-2773.html
http://imgur.com/J09xwqO
 =>anti-adblock :  I can see the whole page. The page is hiden.
I can see that the hiden div is  : 
<div class="global" id="publicite"><div id="adsense" class="global">

I changed publicite to publicitefull and adsense to adsensefull

<div class="global" id="publicitefull"><div id="adsensefull" class="global">

I can now see the whole page.
http://imgur.com/f05jOdM ( => normal )
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

Can you look ?

**Comment by reek** [comment]
@zifff 
Its ok for me, try update or re-subscribe Anti-Adblock Killer List.

**Comment by zifff** [comment]
I unsubscribe all filter I look at the web page.
New I subscribe the filter and now the page is Ok.

Thank you.

Bye.
