### ISSUE TITLE
https://www.sozcu.com.tr/ script is not working.

### ISSUE THREAD

**Issue by ozmenmurat** [reek/anti-adblock-killer#4393]

**Comment by ozmenmurat** [comment]
![ad block sözcü](https://user-images.githubusercontent.com/10380479/77820357-c784ff00-70f2-11ea-9e3e-de90ed3d7a15.jpg)

**Comment by liamengland1** [comment]
Use uBlock Origin.

**Comment by ozmenmurat** [comment]
> Use uBlock Origin.

OK. I will try.

**Comment by ozmenmurat** [comment]
> > Use uBlock Origin.
> 
> OK. I will try.

uBlock Origin can block adds. Thanks.
