### ISSUE TITLE
record.xl.pt (Can't view through picture album)

### ISSUE THREAD

**Issue by SW1FT** [reek/anti-adblock-killer#441]
Try going through the pictures using '<' or '>' buttons inside the current picture on http://www.record.xl.pt/multimedia/fotos/interior.aspx?content_id=953605

Mozilla Firefox Dev Edition 40.0a2
Greasemonkey
uBlock Origin 0.9.8.7.11
A lot of filter lists but the one that is doing this is Anti-Adblock Killer.

I've fixed it with this: `@@||record.xl.pt/pub/mrec_dynamic.aspx?pubvar=FOTOS`

**Comment by reek** [comment]
Obrigado SW1FT :smile:

**Comment by SW1FT** [comment]
De nada ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
