### ISSUE TITLE
Blocking login on libib.com

### ISSUE THREAD

**Issue by bdoserror** [reek/anti-adblock-killer#4413]
I was trying to log in to my account at https://libib.com/login and it seemed like the Login button was just being ignored.

After I disabled Anti-Adblock Killer, I was able to login successfully.

On Windows 10.
Chrome: Version 81.0.4044.138 (Official Build) (64-bit)
Tampermonkey: 4.10 (2020-04-28)
Anti-Adblock killler: // @version 10.0
Screenshot: https://imgur.com/m1qf6yk
Ad blocker: AdBlock
Filterlist: Acceptable Ads, Adblock custom filters, Anti-circumvention, EasyList, Adblock Warning removal, Cryptocurrency mining protection, AAK

**Comment by liamengland1** [comment]
https://github.com/reek/anti-adblock-killer/wiki

**Comment by bdoserror** [comment]
Thanks @llacb47 , I guess I missed that part.
