### ISSUE TITLE
anifansia.net

### ISSUE THREAD

**Issue by UkiND** [reek/anti-adblock-killer#443]
http://anifansia.net/anime/high-school-dxd-born/
http://imgur.com/044Aatz
Cool Novo / Chromium
Tempermonkey
uBlock + AdMuncher
EasyList

**Comment by reek** [comment]
Hi,

I dont use Chromium, but you can try with Chrome + uBlock + Tampermonkey
https://github.com/reek/anti-adblock-killer#supported-browsers

Regards
Reek
