### ISSUE TITLE
Not working on animeshouse.net

### ISSUE THREAD

**Issue by Slowftw** [reek/anti-adblock-killer#4432]
https://animeshouse.net/episodio/shigatsu-wa-kimi-no-uso-s1-episodio-1-legendado-hd/
![image](https://user-images.githubusercontent.com/46169656/87823602-11ccf000-c84a-11ea-8705-f7613daf445a.png)

**Comment by liamengland1** [comment]
https://github.com/reek/anti-adblock-killer/wiki

**Comment by Slowftw** [comment]
thx
