### ISSUE TITLE
kreanclix.com

### ISSUE THREAD

**Issue by ReVeNGe1993** [reek/anti-adblock-killer#445]
http://www.kreanclix.com/pages/clickads
http://oi59.tinypic.com/29zye8o.jpg
Chrome
Tampermonkey 
AdBlock Plus
AntiAdBlock Killer + AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Same issue: https://greasyfork.org/forum/discussion/4658/kreanclix-com
