### ISSUE TITLE
aternos.org

### ISSUE THREAD

**Issue by aldenasf** [reek/anti-adblock-killer#4459]
Browser: Firefox version 84.0.2 
Adblocker: AdBlocker Ultimate version 3.7.10

![image](https://user-images.githubusercontent.com/63831735/105694395-7f618380-5f33-11eb-802c-ba383aea72d5.png)

**Comment by FuccDucc** [comment]
It still amazes me that some people don't use their eyes..

[https://github.com/reek/anti-adblock-killer/wiki](https://github.com/reek/anti-adblock-killer/wiki)

`reek/anti-adblock-killer` is unmaintained and inactive for years (@reek gave up) so instead i advise you to use the fork located at [https://github.com/bogachenko/fuckfuckadblock](https://github.com/bogachenko/fuckfuckadblock) which is still being actively maintained and updated to ward off much more anti-adblockers.
