### ISSUE TITLE
AdGaurd Chrome Extension

### ISSUE THREAD

**Issue by ThePieMonster** [reek/anti-adblock-killer#4468]
AdGaurd Extension for Chrome doesn't seem to be [supported](https://openuserjs.org/scripts/reek/Anti-Adblock_Killer_Reek). 

[https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg)

**Comment by ghost** [comment]
Do you try reinstall adguard adblocker for Chrome?
