### ISSUE TITLE
getdebrid.com

### ISSUE THREAD

**Issue by z4g5r** [reek/anti-adblock-killer#447]
http://getdebrid.com
http://i.imgur.com/ULlZEBL.jpg
Opera
Tampermonkey
AdBlock
EasyList + AdBlock Warning Removal list + AakList
Issue: nevermind, took couple refreshes to make it work

**Comment by reek** [comment]
Hi,

I have tested and it works very well under Opera and Tampermonkey.
https://github.com/reek/anti-adblock-killer#help

See you
Reek

**Comment by muhasturk** [comment]
It seems still broken @reek

**Comment by reek** [comment]
@muhasturk 
Not for me
