### ISSUE TITLE
everytime i subscribe it takes me to a huge line of code(UblockOrigin)

### ISSUE THREAD

**Issue by Firefox289** [reek/anti-adblock-killer#4470]
as the title says

**Comment by FuccDucc** [comment]
It still amazes me that some people don't use their eyes..

[https://github.com/reek/anti-adblock-killer/wiki](https://github.com/reek/anti-adblock-killer/wiki)

`reek/anti-adblock-killer` is unmaintained and inactive for years (@reek gave up) so instead i advise you to use the fork located at [https://github.com/bogachenko/fuckfuckadblock](https://github.com/bogachenko/fuckfuckadblock) which is still being actively maintained and updated to ward off much more anti-adblockers.
