### ISSUE TITLE
Why @leet0rz has not been banned for his disruptive repetetive insulting another user?

### ISSUE THREAD

**Issue by felix-22** [reek/anti-adblock-killer#4495]
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046 is another similiar case to this one: #4451. Pure moderator abuse, I encounter such abuses all my life...and there's no one to complain to because noone gives a shit.

Instead, it only was the another user who was offending a lot less, who has been banned: 
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046#issuecomment-912563764 Is this some kind of bad joke, or rather [double standards](https://en.wikipedia.org/wiki/Double_standard), [hypocrisy](https://en.wikipedia.org/wiki/Hypocrisy) and [inconsistency](https://en.wiktionary.org/wiki/inconsistency) in moderation rules of some members of this https://github.com/notepad-plus-plus organisation? It should be simply one of these:
- to ban both of them
- to ban none of them
- to ban the one was who offending a lot more (leet0rz)

The following option is an unlogical abusement:
- to ban only the one who was offending a lot less (felix-22)

Moreover, they abuse censorship, they removed some uncomfortable comments for them, like this one:

> keczuppp : 
> > dail8859 : https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046#issuecomment-911649032 : 
> > @ donho Can we please block @ felix-22 from this organization? I think only you have access to do so and this argument is getting out of hand.
>
> > @ notepad-plus-plus notepad-plus-plus deleted a comment from felix-22 Sep 2, 2021
> > @ notepad-plus-plus notepad-plus-plus deleted a comment from keczuppp Sep 2, 2021
>
> What for ? From what you can see, the other one (leet0rz) is the one who offends a lot more, and felix-22 only writes back with arguments. 

So simple and obvious, it seems they run out of arguments and used the arguments of force and violence in desperation, it's so "unprofessional", so "disgusting", so "malicious", so "unhelpful" ... and so sad. Both moderation cases are a picture of misery and despair and the evidence that there is little justice in this world.

I know the truth hurts, let it hurt you for the rest of your life.

**Comment by felix-22** [comment]
> leet0rz : https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046#issuecomment-912167971
> 
> @ felix-22 No, what I wrote about the version last time was correct, not whatever you are trying to say. Completely delusional.
> 
> You are the one who started the name calling, calling people monkey in this thread, absolutely nothing happened before that as we all can read above, YOU started. You are highly unprofessional and have no place helping people anywhere. For you to just start calling people monkeys in a help thread tells me more about you than anything, go get your much needed mental care as I do not have time to deal with your psychological issues. Garbage places produce garbage people and I am blocking that garbage now :)

You're boring, you're like a broken cd player, stop crying all the fuking time, stop repeating the same shit every time, stop trolling, stop the fukin off-topic, manipulation and hypocrisy, your comments are full of shit, and there is no argument in them, only a desire to cry and call me names at all costs every time, even though I don't call you names, you constantly do, you don't answer my questions, you don't address my comments, you just troll, stonewall, and call me names throughout the conversation. 

A typical crybaby kid with[ Borderline_personality_disorder](https://en.wikipedia.org/wiki/Borderline_personality_disorder
)

And the other idiots in the thread let you do it instead of stopping you, and blame me instead, just because I respond to your crap? So when you post your shit in my direction it doesn't bother them, and when I reply to that shit in a civilized way, it bothers them. What the f..k kind of moderation is this?

**Comment by felix-22** [comment]
> leet0rz : https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046#issuecomment-912815899 :  even though he started the name-calling for no reason. I am blocking both of them too.

And so what that he started, given he stopped long time ago? While you continued to insult him in each of your comments throughout the conversation. You were the one who insulted a lot more and longer, and he was the only one who got banned. Like I said, It's a similiar case to this one: #4451. I'm wondering whether you don't get it, or are you just pretending not to understand? Stop playing dumb.

**Comment by garry-ut99** [comment]
> notepad-plus-plus/notepad-plus-plus#10046 (comment)

You're right.

**Comment by bomhar24** [comment]
> https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10046#issuecomment-912563764

Yeah.
