### ISSUE TITLE
It's blocking quora.com

### ISSUE THREAD

**Issue by mertemr** [reek/anti-adblock-killer#4509]
`Something went wrong. Wait a moment and try again.` page comes while userscript enabled.

**Comment by npn225** [comment]
To clarify the issue brought up by @mactorient, the site "quora.com" seems to identify usage the anti-adblock-killer script and blocks access to its site as a result - only providing the message: `Something went wrong. Wait a moment and try again.`

More info about my personal setup for the devs: 
OS - Linux Mint 20.2 
Browser - Mozilla Firefox 95.0.1
Userscript Manager - Tampermonkey 

Additional info:
Although I have this script running on Chromium through Tampermonkey, "quora.com" runs perfectly fine there. 
For me, the problem only arises when I try to run this anti-adblock-killer script while surfing "quora.com" on Firefox. 

P.S. Before anyone asks - No, I have not and will not test this with the Greasemonkey userscript.

Thanks in advance!
