### ISSUE TITLE
Kissanime.com (KissAnime Project ABE)

### ISSUE THREAD

**Issue by Metiiin** [reek/anti-adblock-killer#451]
http://i.imgur.com/OHb8MM6.jpg
Google Chrome
Tampermonkey
AdBlock Plus
EasyList, Adblock Warning Removal List, EasyPrivacy, Fanboy's Annoyance List, Spam404, Malware Domains, AakList

The script is hiding the video, I think it is conflicting with the Stylish addon, KissAnime Project ABE. It used to work fine together.

**Comment by reek** [comment]
Hi,

I go and look, if I can make something

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Metiiin** [comment]
Thank you, I look forward to a solution.

**Comment by Metiiin** [comment]
I had also contacted Kurim, the developer for the Stylish addon, and this is what he said (he also did a workaround that can still be broken again):
"
Kurim:

KA updated the page around the 6th of june and to this I had to update some of the video-page and anime-page tags otherwise things like the player wouldn't display.

I can't say that ive changed my style-writing patterns to cause these issues, if anything I believe this must be on Reeks table.

-- ::EDiT:: --
I'll try but I can't guarantee anything as PABE/CSS/Stylish doesn't have that many routes.
(which is why ive always pushed for the Ghostery addon as it never cared how I wrote my styles, it just worked)

-- :: EDiT:: --
DONE! However as expected the fault was with 'Anti-Adblock Killer'.

The current version of AAK removes several page-elements causing the style to hit the wrong boxes (like for instance the player window).

To come around this ive switched the targeting method but if KA starts changing stuff again then it's possible that this route will go out the window and I'd be forced to go back and AAK will break P:ABE again, and I can't really tailor the style to AAK because not everyone uses it.

More issues will also arise if more elements are removed that are used by my style or other peoples styles, my style isn't really 'special' when it comes to this as userstyles are written on-top of pre-existing data and the current AAK removes that very data.

The proper way to solve this is for Reek to wipe / nuke the content INSIDE the tags (divs) rather than removing them entirely."

**Comment by reek** [comment]
Hi,

Test this version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)

**Comment by Metiiin** [comment]
Hey, it still works. Were the changes what Kurim mentioned?

**Comment by HyphenSam** [comment]
The test version fixed the issue for me. I'm using uBlock Origin.

**Comment by augustus7hill** [comment]
What is the progress on this issue ? Seems like its still not working with firefox, ublock-origin with aak filter enabled. Seems like this site continuously changes its anti adblock scripts. Hacks that i use for proper functioning dont last for long.

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
