### ISSUE TITLE
tamrieltradecentre.com

### ISSUE THREAD

**Issue by scorpius2k1** [reek/anti-adblock-killer#4532]
https://us.tamrieltradecentre.com/pc/Trade/SearchResult?ItemNamePattern=test
https://i.imgur.com/KQbtXXb.png

**JS Blocking function, uses what appears to be a random hash in url as well**
GetAdMode()
https://us.tamrieltradecentre.com/bundles/View
https://us.tamrieltradecentre.com/bundles/View?v=URLfmeUmag2PEQlnwsPvniFr-IKKue5vdFJr9nXOjLE1

Firefox 100.0.2
Greasemonkey
uBlock Origin
EasyList + Aak

**Comment by capricorn180** [comment]
Posted this over on [[fuckfuckadblock](https://github.com/bogachenko/fuckfuckadblock/issues/312)](https://github.com/bogachenko/fuckfuckadblock/issues/312), looks like this one hasn't been updated for 6 years or so

**Comment by scorpius2k1** [comment]
> Posted this over on [[fuckfuckadblock](https://github.com/bogachenko/fuckfuckadblock/issues/312)]([bogachenko#312](https://github.com/bogachenko/fuckfuckadblock/issues/312)), looks like this one hasn't been updated for 6 years or so

Your absolutely right, I should have look at the date first. I will give bogachenko's a try and correspond there instead. Thank you!
