### ISSUE TITLE
Aliexpress.com (rule)

### ISSUE THREAD

**Issue by HenningJW** [reek/anti-adblock-killer#454]
https://www.hackster.io/rayburne/4-dollar-90-mips-32-bit-72-mhz-arm-arduino alternatively every search on aliexpress I try to right click open in new tab
Aliexpress won't open in a new tab. eg this link: http://imgur.com/mPebUpC The rule that does that is "||aliexpress.com^$popup" not sure if it helps but I _think_ changing the line to "||click.aliexpress.com^$popup" fixes it. Sorry for not filing a pull request
Mozilla Firefox & Chrome
No script manager
µBlock origin
Only this list activated (did this for testing purposes)

**Comment by reek** [comment]
Hi,

I just delete the rule, update your AakList

See you
Reek
