### ISSUE TITLE
vide-greniers.org

### ISSUE THREAD

**Issue by Thorbur** [reek/anti-adblock-killer#455]
Hi, I know it's better to make a pull request, but currently I'm a bit short on time.
However, I want to share my very basic attempt to let the very annoying adblock message bar on https://vide-greniers.org disappear. 
I just used it in greasemonkey and it seems to work very well, so feel free to include and/or adopt it:

// ==UserScript==
// @name        vg_antiantiadblock
// @namespace   thorbur
// @include     https://vide-greniers.org/*
// @version     1
// @grant       unsafeWindow
// ==/UserScript==
setTimeout(function(){unsafeWindow.$(".adsbygoogle").remove();}, 2e3);

**Comment by Thorbur** [comment]
D'oh just found the site is already supported. Somehow my previous search for the check before I posted the issue didn't work properly. Mea culpa.

**Comment by reek** [comment]
Hi,

Thank you, to have shared your solution

See you
Reek
