### ISSUE TITLE
up2stream.com (indiansexmms.co)

### ISSUE THREAD

**Issue by madeforonlyyou** [reek/anti-adblock-killer#456]
http://indiansexmms.co/2015/06/hot-gf-shows-sexy-figure-lover-desi-mms/
(the second video player from up2stream.com, detects adblock and refuses to play video)

Browser: Google chrome Version 43.0.2357.81 (64-bit) (Linux)
adblocker: ublock origin 0.9.9.1
screenshot: http://imgur.com/ErrjClp
My enabled filters:
 uBlock filters
 uBlock filters – Privacy‎ 
 uBlock filters – Unbreak‎ 
 Adblock Warning Removal List‎ (forums.lanik.us):
 Anti-Adblock Killer | Reek‎  (github.com):
 EasyList without element hiding rules‎ (forums.lanik.us): 
 Peter Lowe’s Ad server list‎ (pgl.yoyo.org)
 Malware Domain List‎ (malwaredomainlist.com)
 Malware domains‎ (www.malwaredomains.com)
 Malware domains (long-lived)‎ (www.malwaredomains.com)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by madeforonlyyou** [comment]
@reek This is not working again. Please take a look. Thanks

**Comment by reek** [comment]
Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
