### ISSUE TITLE
videostar.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#457]
Hi, videostar..pl change url to check Adblock is enable. On your filter are:
@@||static-videostar2.4vod.tv/assets/js/adcheck.js$script,domain=videostar.pl
now is https://static-videostar2.4vod.tv/assets/js/adcheck.min.js?v=1 

Can you change this?

MajkiIT

**Comment by reek** [comment]
Hi,

OK, I would change

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
Thanks. 

MajkiIT
