### ISSUE TITLE
wp.tv

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#458]
http://wp.tv/i,male-znane-fakty-z-dziejow-cesarstwa-japonskiego,mid,1717073,cid,4051,klip.html
https://www.dropbox.com/s/qajezh1r81lw48x/adblock22.png?dl=0
Mozila Firefox
Greasemonkey + Anti-Adblock-scipts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

Ads on movie.

**Comment by reek** [comment]
its ok for me

2015-06-21 23:17 GMT+02:00 MajkiIT <notifications@github.com>:

**Comment by MajkiIT** [comment]
I will test it. Give a few hours.

**Comment by MajkiIT** [comment]
I see ads here http://wp.tv/i,niezwykly-rzut-do-kosza-przypadek,mid,1720077,cid,5050,klip.html 
https://www.dropbox.com/s/9aexg7ak2vnp3xn/adblock23.png?dl=0

**Comment by MajkiIT** [comment]
I test it on 3 computers and on all I have ads on video.

**Comment by reek** [comment]
nothing
![capture](https://cloud.githubusercontent.com/assets/3474011/8334884/96db252c-1a9a-11e5-9077-ebe86388fc8e.PNG)

**Comment by MajkiIT** [comment]
Can you write me, witch list are you using?

**Comment by reek** [comment]
AakList
EasyList
EasyPrivacy

2015-06-24 18:09 GMT+02:00 MajkiIT <notifications@github.com>:

**Comment by MajkiIT** [comment]
I test it on ublock and adblock on you list of filters witch you are using and I have ads on movie. Maybe on this page there are same JS witch show ads only for users from PL...

**Comment by MajkiIT** [comment]
I find my mistake. Sorry
