### ISSUE TITLE
Anti Adblock and OneNote Clipper Extension on Chrome

### ISSUE THREAD

**Issue by phone8588** [reek/anti-adblock-killer#459]
After adding the anti-adblock script on the Chrome browser (using Tampermonkey) - the Onenote Clipper Extension from Microsoft on Chrome gives the following error - 

"Warning: This extension (Onenote Clipper) failed to modify the response header "content-security-policy" of a network request because the modification conflicted with another extension (Tampermonkey)."

After starting Chrome and going to the twitter.com page leads to the error popping up on the hamburger menu on Chrome (it going orange).

**Comment by reek** [comment]
Hi,

If the error is caused by Tampermonkey, you have to report it here
https://github.com/derjanb/tampermonkey

Regards
Reek

**Comment by phone8588** [comment]
The error is caused by the Anti-Adblock script. If I disable the Anti-Adblock script then Tampermonkey and Onenote Clipper continues to work just fine. I am on a Mac.
