### ISSUE TITLE
kwalifikacjawzawodzie.pl

### ISSUE THREAD

**Issue by Piter432** [reek/anti-adblock-killer#460]
http://kwalifikacjewzawodzie.pl/
![22-06-2015 r 22 38 47 - toff adb](https://cloud.githubusercontent.com/assets/5713816/8292542/821b6c66-1930-11e5-8582-ee51f3392ea6.png)
Google Chrome x86 v43 (probably the same is on Mozilla Firefox 38.0.5)
Tampermonkey with Anti-Adblock killer script
uBlock Origin 0.9.9.2
My filters + uBlock filters‎ + uBlock filters – Badware risks‎ + uBlock filters – Privacy‎ + uBlock filters – Unbreak + Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek‎ + EasyList‎ + EasyList without element hiding rules‎ + Peter Lowe’s Ad server list‎‎ (http) + Basic tracking list by Disconnect‎ + EasyPrivacy‎ + Fanboy’s Enhanced Tracking List‎ + Malvertising filter list by Disconnect‎ + Malware Domain List‎ (http) + Malware domains‎ (http) + Malware domains (long-lived)‎ [http] + Malware filter list by Disconnect‎ + Spam404 (http) [because I can't update https version in Chrome 43 on Windows XP] + Anti-ThirdpartySocial (see warning inside list) + Fanboy’s Annoyance List‎ + Fanboy’s Social Blocking List‎ + Dan Pollock’s hosts file‎ (http) + Fanboy+Easylist-Merged Ultimate List‎ + hpHosts’ Ad and tracking servers‎ (http) + MVPS HOSTS‎ + CHN: China: cjxlist (main focus on Chinese sites)‎ + CHN: EasyList China (中文)‎ + CZE, SVK: EasyList Czech and Slovak‎ + DEU: EasyList Germany‎ + JPN: ABP Japanese filters (日本用フィルタ)‎ + KOR: adblock-korea-contrib‎ + KOR: Fanboy's Korean‎ + POL: Adblock polskie reguly‎ + RUS: BitBlock List (Дополнительная подписка фильтров)‎ + RUS: RU AdList (Дополнительная региональная подписка)‎ + AakList (Anti-Adblock Killer)‎ + Adblock Polska‎ + Block all well known privacy trackers‎ (http) + cjxlist‎

**Comment by F4z** [comment]
Solution:
<pre>kwalifikacjewzawodzie.pl#@#.afs_ads</pre>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@F4z 
Thanks :+1:
