### ISSUE TITLE
clubic.com

### ISSUE THREAD

**Issue by devnoname120** [reek/anti-adblock-killer#461]
Requires to disable adblockers:
![Capture](http://image.noelshack.com/fichiers/2015/26/1435013026-cap.png)
http://www.clubic.com/video/premier-apercu/video-xiaomi-mi-gamepad-en-video-la-meilleure-des-manettes-android-pour-20-euros-466622.html

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
j'ai rien du tout, ta config et tes listes

**Comment by devnoname120** [comment]
Firefox, Greasemonkey, uBlock Origin (listes par d�faut), Ghostery (tous les blocages activ�s). Tout �a en derni�re version.

**Comment by reek** [comment]
essaye de désactiver Ghostery

**Comment by devnoname120** [comment]
�a devrait r�gler le probl�me, je vais essayer demain (mais �a serait quand m�me mieux que l'on puisse l'esquiver quoi qu'il arrive).

**Comment by devnoname120** [comment]
Je viens d'essayer, et désactiver Ghostery évite bien le problème.
Voici l'URL d'accès directe : http://player.m6web.fr/v1/player/clubic/466622.html?estatDomain=www.clubic.com&autoPlay=true&themeColor=0xc50000&btnPlayColor=0xc50000&fontColor=0xffffff&logoUrl=//www.clubic.com/img/logo-clubic.gif&showCarousel=false

**Comment by reek** [comment]
Salut,

Teste cette version: https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by devnoname120** [comment]
Je viens d'essayer, ça fonctionne bien. :+1:

**Comment by reek** [comment]
Ok, j'ai replacé leur player du coup pas de blocage ni de pub :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
