### ISSUE TITLE
Hireteen.com

### ISSUE THREAD

**Issue by vinctux** [reek/anti-adblock-killer#462]
Hey,

I just found one @ http://www.hireteen.com/

The `hireteen.com###adb-enabled` filter seems to solve it.

**Comment by reek** [comment]
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
