### ISSUE TITLE
plus-belle-la-vie-video.blogspot.com

### ISSUE THREAD

**Issue by zifff** [reek/anti-adblock-killer#464]
It is the same as http://plus-belle-la-vie-replay.blogspot.com/

Can you add the rules : 
plus-belle-la-vie-replay.blogspot.com#@##publicite
plus-belle-la-vie-replay.blogspot.com#@##adsense
plus-belle-la-vie-video.blogspot.com#@##adsense
plus-belle-la-vie-video.blogspot.com#@##publicite

**Comment by reek** [comment]
Yes, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
