### ISSUE TITLE
ville-ideale.com

### ISSUE THREAD

**Issue by sda2b** [reek/anti-adblock-killer#465]
http://www.ville-ideale.com
http://imgbox.com/M00hSHtd
Mozilla Firefox (38.0.5) OS X Mavericks
uBlock Origin + AakList

The anti-adblock message appears after 5 sec, when scrolling the webpage.
I tried several browser (Firefox, Safari, Chrome, Chromium) on Mac, Windows, Linux.. same results.

Thanks !

EDIT : I restarted my computer, the anti-adblock message doesn't appear anymore. So I think we can close this. :+1: 

Thanks for the anti-adblock-killer ! :+1:

**Comment by reek** [comment]
Thanks
