### ISSUE TITLE
http://binbox.io/

### ISSUE THREAD

**Issue by riverstore** [reek/anti-adblock-killer#466]
After entered the captcha, an anti-ablock appear
http://binbox.io/V9cPp

Waterfox 38.1, Windows 7 SP1 64bit
AakList, EasyList

Please have a look. Thanks a lot.

**Comment by F4z** [comment]
This should help: <pre>@@||binbox.io/adblock.js$script,domain=content.binbox.io</pre>

**Comment by riverstore** [comment]
It's work great. Thanks a lot.

**Comment by reek** [comment]
@F4z 
Thanks, I am going to add it.
