### ISSUE TITLE
gram.pl

### ISSUE THREAD

**Issue by Piter432** [reek/anti-adblock-killer#468]
http://www.gram.pl
![26-06-2015 r 20 03 05 - gpl toff adb](https://cloud.githubusercontent.com/assets/5713816/8384737/7866682c-1c43-11e5-9784-f16443f4dc4a.png)
Google Chrome x86 v43 (probably the same is on Mozilla Firefox 38.0.5)
Tampermonkey with Anti-Adblock killer script
uBlock Origin 0.9.9.2
My filters + uBlock filters‎ + uBlock filters – Badware risks‎ + uBlock filters – Privacy‎ + uBlock filters – Unbreak + Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek‎ + EasyList‎ + EasyList without element hiding rules‎ + Peter Lowe’s Ad server list‎‎ (http) + Basic tracking list by Disconnect‎ + EasyPrivacy‎ + Fanboy’s Enhanced Tracking List‎ + Malvertising filter list by Disconnect‎ + Malware Domain List‎ (http) + Malware domains‎ (http) + Malware domains (long-lived)‎ [http] + Malware filter list by Disconnect‎ + Spam404 (http) [because I can't update https version in Chrome 43 on Windows XP] + Anti-ThirdpartySocial (see warning inside list) + Fanboy’s Annoyance List‎ + Fanboy’s Social Blocking List‎ + Dan Pollock’s hosts file‎ (http) + Fanboy+Easylist-Merged Ultimate List‎ + hpHosts’ Ad and tracking servers‎ (http) + MVPS HOSTS‎ + CHN: China: cjxlist (main focus on Chinese sites)‎ + CHN: EasyList China (中文)‎ + CZE, SVK: EasyList Czech and Slovak‎ + DEU: EasyList Germany‎ + JPN: ABP Japanese filters (日本用フィルタ)‎ + KOR: adblock-korea-contrib‎ + KOR: Fanboy's Korean‎ + POL: Adblock polskie reguly‎ + RUS: BitBlock List (Дополнительная подписка фильтров)‎ + RUS: RU AdList (Дополнительная региональная подписка)‎ + AakList (Anti-Adblock Killer)‎ + Adblock Polska‎ + Block all well known privacy trackers‎ (http) + cjxlist‎

I can browse this website with this information, but I'd like to 'kill' it :P

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
Solution is @@|http://static0.gram.pl/js/advertising.js$script,domain=gram.pl

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
