### ISSUE TITLE
linkbucks.com

### ISSUE THREAD

**Issue by solchanel** [reek/anti-adblock-killer#469]
![2015-06-27_18-33-48](https://cloud.githubusercontent.com/assets/1663685/8392963/74eb2198-1cfb-11e5-80be-983634feb196.jpg)
AdBlock, AdBlock Plus, (AdsBypasser, anti-adblock-killer)

**Comment by reek** [comment]
http://www.linkbucks.com/CqZ5G

**Comment by reek** [comment]
Hi,

Your config please

**Comment by reek** [comment]
I see nothing, try update your filters
