### ISSUE TITLE
rapidmoviez.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#470]
http://rapidmoviez.com
http://rapidmoviez.com/release/stitchers-s01e04-720p-hdtv-hevc-x265-rmteam
http://i.imgbox.com/VsuEsJVK.png
Chromium Version 45.0.2443.0 (64-bit)
uBlock Origin 0.9.9.2 + Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎
Tampermonkey BETA 3.11.4666 + https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/

**my temporary solution:**
<code>rapidmoviez.com##.ab-alert</code>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
