### ISSUE TITLE
wp.pl and wp.tv

### ISSUE THREAD

**Issue by anti-adblock-fan** [reek/anti-adblock-killer#471]
I think they change something form today, because video on the site does't work :(
Like here:
http://wiadomosci.wp.pl/kat,1329,title,Zamach-w-Tunezji-cudem-przezyli-masakre,wid,17668330,wiadomosc.html
or
http://wp.tv/i,zamach-w-tunezji,mid,1727067,cid,4051,klip.html?_ticrsn=3&ticaid=51520a
But on:
http://pogoda.wp.pl/*
http://sport.wp.pl/*
it's ok

![img](https://cloud.githubusercontent.com/assets/13084298/8395572/c193a18c-1d78-11e5-917f-7b522c15dfef.png)

AB+ and AAK

**Comment by MajkiIT** [comment]
You block mp4 file np wp.pl . Add this list ==> https://www.certyficate.it/adblock/adblock.txt . This list resolve your problem.

**Comment by anti-adblock-fan** [comment]
Thx, it really works even without AAK, but sometimes i see ads before video what i try to watching.

Please delete all cookis like "wp.pl" and try watch this one http://wp.tv/i,co-polki-robia-teraz-na-wieczorach-panienskich,mid,1727093,cid,5050,klip.html

---polish translation---
Fakt działa dzięki :), ale czasami wyskakuje rekalma przed konkretnym video. Spróbuj usnąć cookis i włączyć video z linku powyżej.

Thx, (Dzięki)

**Comment by MajkiIT** [comment]
I use list (AAK filters, AAK Scripts and https://www.certyficate.it/adblock/adblock.txt) and on wp.pl, wp.tv I don't see ads.

**Comment by anti-adblock-fan** [comment]
Now i have a clean install FireFox, AdblockPlus, AAK filters, AAK Scripts and your filter from  https://www.certyficate.it/adblock/adblock.txt and sometimes unfortunately I see ads before video.
![asd](https://cloud.githubusercontent.com/assets/13084298/8402168/e4d92b38-1e38-11e5-8454-109c09b05cc0.png)

**Comment by MajkiIT** [comment]
Try use uBlock and update all filters and try again. I see that adblock have problems with update.

**Comment by anti-adblock-fan** [comment]
I've tried and the same problem :( I see ads.

Have a look
https://youtu.be/vvyW5yMGZjU

1st article aak doesn't work
2nd article aak works fine
3rd article aak doesn't work
4th article aak works fine

Why AAK doesn't work on 1 and 3 articles ?  the only difference is i've to click on video in 1st and 3rd article to see that info ( https://cloud.githubusercontent.com/assets/13084298/8395572/c193a18c-1d78-11e5-917f-7b522c15dfef.png ) maybe thats clue?

**Comment by MajkiIT** [comment]
For me it's problem with AAK Scripts. Maybe i export you my ublock settings?

**Comment by anti-adblock-fan** [comment]
I think so too.
Do you use FF or Chrome ?

**Comment by MajkiIT** [comment]
FF

2015-06-29 13:37 GMT+02:00 anti-adblock-fan <notifications@github.com>:

**Comment by anti-adblock-fan** [comment]
me too.
Maybe reek something advise.

**Comment by reek** [comment]
It does not work because I cannot get back the link of the video
