### ISSUE TITLE
bitcoinzebra.com

### ISSUE THREAD

**Issue by vinctux** [reek/anti-adblock-killer#472]
Hey,

I just found another one @ http://faucet.bitcoinzebra.com/faucet
![btczebra](https://cloud.githubusercontent.com/assets/9408266/8411900/a64776e2-1e86-11e5-9aaf-d3ef37d6d4a8.png)

This inline-script appears to be the problem:
```html
<div class="flexItem flexItem3">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Bitcoin Zebra: Large Rectangle (RHS) -->
    <ins class="adsbygoogle"
        style="display:inline-block;width:336px;height:280px"
        data-ad-client="ca-pub-6522562938491188"
        data-ad-slot="9679715156"></ins>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
</div>
```
```html
<div id="BodyPlaceholder_FailureMessagePanel" class="failure-message-panel">
    <span id="BodyPlaceholder_FailureMessage" class="failure-message">Bitcoin Zebra depends on the revenue from displaying a small number of adverts that may interest you, so that we can continue to payout.<br/>We respectfully ask you to disable your ad-blocking browser plugin/software or add this page to the exception list and then <a href='faucet'>refresh the page</a>
    </span>            
</div>  
```

Indeed, the real cause is this script line
```javascript
(adsbygoogle = window.adsbygoogle || []).push({});
```
which should be considered to be globaly blocked.

I hope it helps.

**Comment by maynak00** [comment]
tested in chromium x64+tampermonkey beta+ublock origin
firefox stable+greasemonkey+ublock origin
no antiadblock notice.
@vinctux **full report please**
**report guide:**https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by vinctux** [comment]
@maynak00 @reek Please see the comment #267

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
