### ISSUE TITLE
filmovizija.in

### ISSUE THREAD

**Issue by JohnMiller9898** [reek/anti-adblock-killer#474]
http://www.filmovizija.in/
![adblock-detected](https://cloud.githubusercontent.com/assets/13141946/8466240/b3b20c18-2050-11e5-99a6-34014089edde.PNG)
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by MajkiIT** [comment]
For my solution is 
@@|http://eosads.com/advertise.js$script,domain=filmovizija.in

**Comment by JohnMiller9898** [comment]
Thank you, it helps for now.

**Comment by JohnMiller9898** [comment]
Thank you, it helps for now.

**Comment by JohnMiller9898** [comment]
It doesn't work any more, have new filter?

**Comment by MajkiIT** [comment]
Update all filters like Easylist. Check then. Now i haven't any notifications.

**Comment by JohnMiller9898** [comment]
It seems ok for now, not sure how much longer, I'll reopen the issue if it stops working again. Thank you so much for your help.

**Comment by MajkiIT** [comment]
OK, If you have a problem then write again.

**Comment by JohnMiller9898** [comment]
I encountered the same issue again, have some new filters?

**Comment by MajkiIT** [comment]
Check this:
@@|http://filmovizija.in/cdn/js/jquery.popunder.js$script,domain=filmovizija.in
@@|http://eosads.com/popunder.js$script,domain=filmovizija.in

**Comment by JohnMiller9898** [comment]
It doesn't work. Have an other idea?

**Comment by MajkiIT** [comment]
Update easylist. It's works.

**Comment by JohnMiller9898** [comment]
www.filmovizija.in
![capture789](https://cloud.githubusercontent.com/assets/13141946/8763893/42e196fe-2db4-11e5-8296-578c3c81c7c8.PNG)
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

As you can see, now there is a difference in block window that they are using now and previous one shown little above this comment.

**Comment by MajkiIT** [comment]
Try this rule
@@|http://www.filmovizija.in/advertise.js?_=$xmlhttprequest,domain=filmovizija.in

**Comment by JohnMiller9898** [comment]
As always, thank you for now.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by JohnMiller9898** [comment]
New filter rules, please, doesn't work anymore.

**Comment by MajkiIT** [comment]
Check this
@@|http://ninovid.com/advertise.js$script,domain=filmovizija.in

**Comment by JohnMiller9898** [comment]
Ok for now.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
