### ISSUE TITLE
SportsPlays.com

### ISSUE THREAD

**Issue by rthompsonhi** [reek/anti-adblock-killer#478]
http://www.sportsplays.com/leaders/board/snapshot/0/friends/yesterday.html
http://imgur.com/y4MW68G
Chrome
TamperMonkey
uBlock
uBlock filters + uBlock filters -- Privacy + Anti-Adblock Killer + EasyList + Peter Lowe's Ad Server List + EasyPrivacy + Malware Domain List + Malware domains

**Comment by MajkiIT** [comment]
It's problem with Anti-Adblock Killer scipts. If I disable TamperMonkey then it's ok.

**Comment by rthompsonhi** [comment]
Not for me, if I disable TamperMonkey, it still gives the error with uBlock
on.  To prove I can see the page correctly, I disabled both and it no
longer complains.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
