### ISSUE TITLE
layer13.net

### ISSUE THREAD

**Issue by Afkjson** [reek/anti-adblock-killer#482]
https://layer13.net

Screenshot:
http://i.imgbox.com/QeAdfAxU.png

Browser:
Version 43.0.2357.132 (64-bit)
OS: Mac OSX 10.10.3

Tampermonkey v3.10.109

uBlock Origin 0.9.9.2

Adblock Warning Removal List
Anti-Adblock Killer | Reek
Easylist+ Peter Lowe’s Ad server list
EasyPrivacy
Malware Domains List 
Malware domains
Fanboy’s Annoyance List

The website uses "FuckAdBlock" in the scripts: "randomstuff.js" and "randomtask.js"

Because I never had the opportunity to do so until now: 
Thank you for your great work, Reek! You make the internet useable again :-)

**Comment by reek** [comment]
Error 522 Ray ID: 209eaf574b6d02dc • 2015-07-22 11:08:14 UTC
Connection timed out

**Comment by reek** [comment]
Already supported, i close issue
