### ISSUE TITLE
wetter3.de

### ISSUE THREAD

**Issue by hollaho** [reek/anti-adblock-killer#483]
http://www1.wetter3.de/gfs025.html
http://imgbox.com/63mCaJAz
Mozilla Firefox
Greasemonkey
uBlock Origin
Diverse (uBlock, Easy, Peter Lowe, Fanboy, AdblockWarningRemoval) and AakList

Description of Anti-Adblock mechanism:
script type="text/javascript" src="http://www.sponsorads.de/script.php?s=224455"></script

is blocked by uBlock Origin as ad link. But this script sets the preferrer variable, which is now checked by the calling page:

//alert(document.referrer)
if (typeof(preferrer)=="undefined" && document.referrer!="http://www1.wetter3.de/error_adblocker_gfs025.html" && document.referrer!="http://www2.wetter3.de/error_adblocker_gfs025.html")
{
  window.location.href="/error_adblocker_gfs025.html";
}

to forward the user to a nag screen.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
