### ISSUE TITLE
beta.speedtest.net

### ISSUE THREAD

**Issue by GhettoGirl** [reek/anti-adblock-killer#484]
http://beta.speedtest.net/
http://i.imgur.com/bWxKbWp.png
Mozilla Firefox (38.0.6)
Greasemonkey
Adblock Plus
EasyList
Fanboy's Social Blocking List
AdBlock Warning Removal List
Ant-AdBlocker List

NOTE: beside adblock, i also use /etc/hosts blocking. so the site and the speedtest WORKS without ads. i guess this long text on the website is just a lie :( what else it should be

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/562

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
