### ISSUE TITLE
exashare.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#486]
http://www.exashare.com/717sq6flr2kg
adblocker detected message: 
http://4.bp.blogspot.com/-3W69PiJh7U0/VFnmVUjb5lI/AAAAAAAAAJs/W08cXeRFXuA/s1600/Disable%2BAdblock.png
<img src="http://4.bp.blogspot.com/-3W69PiJh7U0/VFnmVUjb5lI/AAAAAAAAAJs/W08cXeRFXuA/s1600/Disable%2BAdblock.png" height="90%" width="90%">
Chromium x64
Tampermonkey BETA+ https://greasyfork.org/scripts/4881-adsbypasser/ https://greasyfork.org/scripts/735-anti-adblock-killer-reek/ https://greasyfork.org/scripts/4294-antiadware/
uBlock Origin
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com), EasyList‎ (adblockplus.org), EasyPrivacy (adblockplus.org)‎, Adblock Warning Removal List‎

**Comment by MajkiIT** [comment]
Update filters and try again.

**Comment by maynak00** [comment]
updated filters and userscript.still message:<code><small>Bloquer la pub c'est bloquer les revenus du site pour payer les serveur </small></code>

**Comment by Watilin** [comment]
Filters are inefficient: Exashare has started using dynamically named elements. I'm working on it.

**Comment by reek** [comment]
@Watilin 
Thanks for your help :smile:

**Comment by Watilin** [comment]
I made a PR. Check it ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
