### ISSUE TITLE
vipleague.se

### ISSUE THREAD

**Issue by theYet1** [reek/anti-adblock-killer#487]
http://www.vipleague.se/boxing/310934/3/ppv-ufc-189:-mendes-vs-mcgregor-live-stream-online.html
http://i.imgur.com/kOvunwi.png?1
Firefox
Greasemonkey
uBlock Origin
Easylist, Anti Adblock Killer, Adblock Warning Removal List, Peter Lowe's Ad Server list , ublock filters,ublock filters-badware, ublock filters-privacy, ublock filters-unbreak

**Comment by MajkiIT** [comment]
Update all filters and try again. I don't see notification.

**Comment by reek** [comment]
HI,

Please read instructions, you need install script manager and AakScript
https://github.com/reek/anti-adblock-killer#instruction

Do not forget to donate, review, share, follow and add to favorites.

See you
Reek
