### ISSUE TITLE
Kisscartoon.me

### ISSUE THREAD

**Issue by HardChibi** [reek/anti-adblock-killer#488]
http://gyazo.com/410dd26c2c4d8c452d91f0e867403c36

http://gyazo.com/abd679c90e28966fb8b3d87f44c5109f

http://gyazo.com/d66c811861d1559da324122bf2eebcff

Still can't use the site after updating it.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by BushTrocity** [comment]
I'm having the same problem it will play for a few seconds but then will stop. Sometimes the player will vanish all together.

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
