### ISSUE TITLE
mupvl.us

### ISSUE THREAD

**Issue by phuc365** [reek/anti-adblock-killer#489]
Firefox 39; uBlock Origin 0.9.9.3; Fanboy Complete List, Anti-Adblock Killer (FilterList & Script)

http://s15.postimg.org/nxpzbw04r/Untitled2.png

<b>Thank you for your interest.</b>

**Comment by MajkiIT** [comment]
Try this:
@@|http://www.advert.com/advert$image,domain=mupvl.us

**Comment by phuc365** [comment]
Thank you very much :) This problem solved

**Comment by MajkiIT** [comment]
Don't close this issue. Maybe Reek add this filter.

**Comment by phuc365** [comment]
Yes sir

**Comment by reek** [comment]
@MajkiIT 
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
