### ISSUE TITLE
blogspot.com.ar redirection 

### ISSUE THREAD

**Issue by rayman89** [reek/anti-adblock-killer#490]
(Warning NSFW Links) When loading pages like http://www.epicwallcz.blogspot.com.ar/ or http://www.masterwallcz.blogspot.com.ar/

the userscript redirects the page to http://www.blogspot.com/ncr/ which displays a 404

**Comment by reek** [comment]
Hi,

Thanks i will fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rayman89** [comment]
Work great. Thanks again.
