### ISSUE TITLE
can't install the filter

### ISSUE THREAD

**Issue by Long-Horse** [reek/anti-adblock-killer#491]
I tried all 4 links which take me to `abp:subscribe?location=https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt&title=Anti-Adblock%20Killer%20|%20Filters%20for%20Adblockers` when I click subscribe but nothing happens. What am I doing wrong?

Is it because I have uBlock Origin instead of ABP?

**Comment by MajkiIT** [comment]
Try use link on this page http://reek.github.io/anti-adblock-killer/subscribe.html . Which version of uBlock do you have?

**Comment by Long-Horse** [comment]
Origin 0.9.9.3

That link doesn't take me anywhere.

**Comment by MajkiIT** [comment]
Ublock have this list integrated on list. Enable this list.

**Comment by reek** [comment]
@MajkiIT 
Thanks
