### ISSUE TITLE
lggautotrasporti.esy.es

### ISSUE THREAD

**Issue by TheTipo01** [reek/anti-adblock-killer#492]
http://lggautotrasporti.esy.es/index.php
http://i.imgur.com/4BC376i.png
Google Chrome
Tampermonkey
Adblock Plus
EasyList Italy+EasyList,Malware Domains,EasyPrivacy

**Comment by MajkiIT** [comment]
Try this: @@|http://pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=lggautotrasporti.esy.es

**Comment by TheTipo01** [comment]
Thanks! It works!

**Comment by MajkiIT** [comment]
Please open this issue. Maybe Reek add this rule. 

Maciej Michalowski

Wysłane z iPada

Dnia 18 lip 2015 o godz. 21:43 Manuel <notifications@github.com> napisał(a):

**Comment by TheTipo01** [comment]
EDIT: Now it no longer works.

**Comment by MajkiIT** [comment]
update all filters and check then.

**Comment by TheTipo01** [comment]
Nothing.

**Comment by MajkiIT** [comment]
On your list I don't see Anti-Adblock Killer | Reek‎ ? Do you use this list?

**Comment by TheTipo01** [comment]
Obviously i use that list. But i found the script (i think the admin of the page modified the java script) : 	
http://lggautotrasporti.esy.es/016CB4514A9A4D87A5393B4A0E97A8B3/2B56782E-42CF-6444-864B-317D1BBF6D0D/main.js
Blocking this now make the notice disappear.

**Comment by MajkiIT** [comment]
I don't see this JS, but Ok.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
