### ISSUE TITLE
waterbitco.in

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#495]
Contributing a fix for the anti-adblocking on the site.

Filter is:
`@@||waterbitco.in/show_ads.js$script`

I recommend adding it to the existing line `@@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com` so it becomes `@@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com|waterbitco.in`

**Comment by reek** [comment]
Thanks

**Comment by Injust** [comment]
Could you please update it in the filter list? Thank you.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
