### ISSUE TITLE
cryptospot.me

### ISSUE THREAD

**Issue by krunox123** [reek/anti-adblock-killer#496]
https://cryptospot.me/
http://imgur.com/RW0JzPz
Google Chrome & UC Browser
Tampermonkey
uBlock Origin
EasyList + Anti-Adblock Kiler + Peter Lowe’s Ad server list + EasyPrivacy

**Comment by MajkiIT** [comment]
I use the same configuration and I don't see any notification. Update all filters and try then.

**Comment by krunox123** [comment]
I still get the message for me to disable adblock...

**Comment by MajkiIT** [comment]
It's problem with easy list. If I use EasyList without element hiding rules it's OK.

**Comment by MajkiIT** [comment]
I report this issue on easylist.subscription@gmail.com .

**Comment by krunox123** [comment]
I don't know but it also doesn't work even though I've enabled the EasyList without element hiding rules.

**Comment by MajkiIT** [comment]
If I disable EasyList and enable EasyList without element hiding rules on my PC is Ok.

**Comment by krunox123** [comment]
Yeah, it works flawlessly when I disable and enable EasyList without element hiding rules.

**Comment by MajkiIT** [comment]
Ok super. When I got answer from EasyList, I'll let you know.

**Comment by reek** [comment]
Hi,

You need install AakScript
https://github.com/reek/anti-adblock-killer#instruction

Regards
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
