### ISSUE TITLE
freebitco.in, freedoge.co.in

### ISSUE THREAD

**Issue by Injust** [reek/anti-adblock-killer#498]
https://freebitco.in/, https://freedoge.co.in/
http://i.imgur.com/rc8gTZB.png, http://i.imgur.com/eQnutJx.png
Google Chrome 43.0.2357.134 m (64-bit)
TamperMonkey
uBlock
uBlock filters, uBlock filters – Unbreak‎, Adblock Warning Removal List‎, Anti-Adblock Killer | Reek‎, and EasyList

**Comment by MajkiIT** [comment]
Are you see this notification after log in?

**Comment by Injust** [comment]
Yes, I get the notification if I log in, and try to claim a prize.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
