### ISSUE TITLE
btcacid.com

### ISSUE THREAD

**Issue by krunox123** [reek/anti-adblock-killer#499]
http://btcacid.com/
http://imgur.com/TxJDhE7
Google Chrome & UC Browser
Tampermonkey
uBlock Origin
EasyList + Anti-Adblock Killer + Peter Lowe’s Ad server list‎ + EasyPrivacy‎

**Comment by krunox123** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11461228/8797059/b99cd79a-2fcb-11e5-8a30-7abc081737a0.png)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,

Its ok for me have you installed AakScript ?

Regards
Reek

**Comment by MajkiIT** [comment]
Update Easylist.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
