### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#500]
Hi, 
```
@@||spaste.com/ads/
@@||juicyads.com^$subdocument,domain=spaste.com
```
source: https://forums.lanik.us/viewtopic.php?f=91&t=24061

**Comment by reek** [comment]
Thanks Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
