### ISSUE TITLE
comptoir-info.com

### ISSUE THREAD

**Issue by Lkisever** [reek/anti-adblock-killer#504]
http://www.comptoir-info.com/

https://imgur.com/MLKT6X4

Google Chrome 43.0.2357.134 m

Tampermonkey

Adblock Plus

Liste FR+EasyList 
Malware Domains
Fanboy's Social Blocking Lis
EasyPrivacy
AakList (Anti-Adblock Killer)

**Comment by F4z** [comment]
Try this:<pre>||comptoir-info.com/bck.js$script,domain=comptoir-info.com</pre>or this<pre>@@||comptoir-info.com^$elemhide</pre>

**Comment by Lkisever** [comment]
Thanks, it's perfect (I tried the first solution)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
