### ISSUE TITLE
gwiazdy.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#505]
http://gwiazdy.wp.pl/artykul/5888924973855361/tom-cruise-zareczony.html
![wp_15](https://cloud.githubusercontent.com/assets/11302675/8890010/2a1d9c9e-32f0-11e5-81f2-f732a259c2c9.png)
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

**Comment by reek** [comment]
Hi,

Its ok for me

**Comment by MajkiIT** [comment]
I still see ads.

**Comment by MajkiIT** [comment]
I update AAK Scipts and nothing. If it's Ok with you, close this Issue. I have problem only on this subdomain.

**Comment by reek** [comment]
Try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by MajkiIT** [comment]
perfectly no ads... thanks a lot.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
