### ISSUE TITLE
Exashare.com

### ISSUE THREAD

**Issue by rayman89** [reek/anti-adblock-killer#506]
Could you add support for http://www.exashare.com/14yqd7gbp3lk

After you click on the video to play the player is replaced by a warning asking to disable AB

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rayman89** [comment]
Thanks a lot.

**Comment by Watilin** [comment]
It seems that them Exashare guys are pretty reactive, they updated their client code. I'm currently looking for a workaround, I'll complete it in one day or two. Stay tuned!

**Comment by reek** [comment]
@Watilin 
Ok, thanks
