### ISSUE TITLE
4chan.com 

### ISSUE THREAD

**Issue by war59312** [reek/anti-adblock-killer#507]
Hi,

If you could please block the anti-ad msg on 4chan.com.

"Please support 4chan by disabling your ad blocker on"..

Example: https://boards.4chan.org/g/thread/49238337

Thaks,

Will

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by war59312** [comment]
Nice, thanks.
