### ISSUE TITLE
tree.tv

### ISSUE THREAD

**Issue by thoth291** [reek/anti-adblock-killer#508]
Firefox 39.0
AdblockPlus RuAdList+AakList+EasyList
OS X: 10.10.4 (14E46)
I'm sure I did proper installation of all the tools - as I don't see any problems on supported sites.
Thanks in Advance!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Impossible to reach the site, I would try later

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
