### ISSUE TITLE
adultmult.tv

### ISSUE THREAD

**Issue by Curranius** [reek/anti-adblock-killer#509]
http://adultmult.tv/anime/dyurarara.html
http://imgur.com/LJiXvXR
Chrome
Tampermonkey
AdBlock
EasyList + AakList

**Comment by MajkiIT** [comment]
Check this:
@@|http://pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=adultmult.tv

**Comment by Curranius** [comment]
Seems like it worked. Thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
