### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by piotr-szegda** [reek/anti-adblock-killer#510]
Player.pl support is now broken. 
uBlock Origin EasyList + Anti-Adblock Killer | 
Greasemonkey
Firefox

Log from Firefox:
```
TypeError: chromeMatch is null
Stack trace:
tvnRequirements.prototype.isWidevineReadyBrowser@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:23:4859
@http://s4.tvnplayer.cdntvn.pl/js/app.js?428:25:3179
tvnRequirements.prototype.checkLocation@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:23:1655
@http://s4.tvnplayer.cdntvn.pl/js/app.js?428:25:3022
Stack.prototype.refreshInnerText/<@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:12:367
.each@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:2:7784
jQuery.prototype.each@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:2:3120
Stack.prototype.refreshInnerText@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:12:295
@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:27:14
jQuery.Callbacks/fire@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:2:11778
jQuery.Callbacks/self.fireWith@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:2:13039
.ready@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:2:4942
DOMContentLoaded@http://s2.tvnplayer.cdntvn.pl/js/lib.js?428:2:1139
```
#192 #293

**Comment by MajkiIT** [comment]
Mozila Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter 

I don't see this bug. Do you update Greasemonkey?
![player](https://cloud.githubusercontent.com/assets/11302675/8904033/7f3a371a-345c-11e5-88b1-aaa07caf1069.png)

**Comment by piotr-szegda** [comment]
It seems that the problem affects only some movies, can you check this: http://player.pl/seriale-online/naznaczony-odcinki,84/odcinek-13,naznaczeni,S00E13,1410.html.

**Comment by piotr-szegda** [comment]
@MajkiIT Any news?

**Comment by MajkiIT** [comment]
On this link I don't see anything. Script which is include in AAK Scipt shows only film with best quality. On link which you send there is old film with medium quality.

**Comment by reek** [comment]
Hi,

I try to add a feature that will select quality, but will wait

**Comment by MajkiIT** [comment]
Best javascript:
(function(){var%20n=document.location.href.split(/[.,]/);%20var%20xmlhttp=new%20XMLHttpRequest();xmlhttp.open('GET','/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=2.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id='+n[n.length-2]+'&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920',false);xmlhttp.send();%20var%20o%20=%20eval('('+xmlhttp.responseText+')');var%20s=o.item.videos.main.video_content[1].url;var%20m=s.match(/:\/\/(?:www\.)?(.[^/]+)(.*)/);var%20xmlhttp=new%20XMLHttpRequest();xmlhttp.open('GET',m[2],false);xmlhttp.send();document.location.href=xmlhttp.responseText;})();

MEDIUM
javascript:(function(){var%20n=document.location.href.split(/[.,]/);%20var%20xmlhttp=new%20XMLHttpRequest();xmlhttp.open('GET','/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=2.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id='+n[n.length-2]+'&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920',false);xmlhttp.send();%20var%20o%20=%20eval('('+xmlhttp.responseText+')');var%20s=o.item.videos.main.video_content[0].url;var%20m=s.match(/:\/\/(?:www\.)?(.[^/]+)(.*)/);var%20xmlhttp=new%20XMLHttpRequest();xmlhttp.open('GET',m[2],false);xmlhttp.send();document.location.href=xmlhttp.responseText;})();

**Comment by piotr-szegda** [comment]
@MajkiIT Are you sure this is just quality problem? I am not JavaScript developer but this probably should not be empty: 
```
http://player.pl/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=2.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id=1410&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920 
```

**Comment by MajkiIT** [comment]
Problem with player.pl is very old. I find this page and I send script to Reek. Yesterday I send 2 script. 
PS. I 'm not a JS Developer.

**Comment by piotr-szegda** [comment]
In my opinion problem is on the vendor side. Quality is associated with it this problem. Could you  confirm @reek?

**Comment by MajkiIT** [comment]
Piotr show this https://www.youtube.com/watch?v=Q24rqrNCe9g

**Comment by piotr-szegda** [comment]
@MajkiIT This is exactly that same script as in AAK or in previous comment. It's base on Samsung player.pl API.

**Comment by MajkiIT** [comment]
I know, because I send them to Reek :D

**Comment by piotr-szegda** [comment]
@reek I have a workaround change format=json&v=2.0 to format=json&v=3.0.
Example:
```
http://player.pl/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=3.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id=1410&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920
```

**Comment by MajkiIT** [comment]
You can modify script localy.

**Comment by piotr-szegda** [comment]
@MajkiIT I know but it's TVN problem probably so we can't fix it.

**Comment by MajkiIT** [comment]
I know.

**Comment by reek** [comment]
Hi,

I just watched and actually it is not a question of quality, it is the json response that does not contain links to videos.

**Comment by tobsn** [comment]
it seems to be the widely used API key that stopped working:
ba786b315508f0920eca1c34d65534cd

I used to use:
http://player.pl/api/?platform=ConnectedTV&terminal=Samsung&format=json&v=2.0&authKey=ba786b315508f0920eca1c34d65534cd&type=episode&id=60154&sort=newest&m=getItem&deviceScreenHeight=1080&deviceScreenWidth=1920

returns now a 403, when changed to v=3.0 it returns:
{"status":"failed","code":10777,"info":"required upgrade application version"}

I think they just changed their API or the authkey isnt valid anymore

**Comment by reek** [comment]
@tobsn 
indeed, but I have no alternative

**Comment by piotr-szegda** [comment]
@reek: Take a look at this: 
https://github.com/mrknow/filmkodi/blob/master/plugin.video.mrknow/host/tvnplayer.py
`mainUrl2 = 'http://api.tvnplayer.pl/api2/?v=3.7&platform=Mobile&terminal=Android&format=json&authKey=4dc7b4f711fb9f3d53919ef94c23890c'`

**Comment by reek** [comment]
@piotr-szegda 
Well done :smile:

**Comment by reek** [comment]
@piotr-szegda 
Can you test ? 
 https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by piotr-szegda** [comment]
@reek I got request to install Silverlight.

**Comment by MajkiIT** [comment]
Reek I have solution 
http://miniskrypt.blogspot.com/2014/04/3-w-1.html 

https://www.youtube.com/watch?v=Q24rqrNCe9g

Can you add this to AAK scripts?

**Comment by reek** [comment]
@piotr-szegda 
@MajkiIT 
Can you test, thanks
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by MajkiIT** [comment]
For me it's not working.

**Comment by reek** [comment]
@piotr-szegda
@MajkiIT
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by MajkiIT** [comment]
Unfortunately, the same problem

**Comment by reek** [comment]
its ok for me on
http://tinyurl.com/o6d9h66
http://tinyurl.com/z77m4zh

**Comment by MajkiIT** [comment]
I find problem on my PC.I reinstall ublock and now its ok. Thanks again.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
