### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by github4321** [reek/anti-adblock-killer#512]
When browsing articles within these domains, adblocker plus is detected.

http://www.tek.no
http://www.gamer.no
http://www.teknofil.no

Result
http://i.imgur.com/hiHB4eu.jpg

Google Chrome
Tampermonkey
Adblock Plus
AakList + EasyList

**Comment by alexander255** [comment]
Hi reek!

Fix for this as script: http://pastebin.com/a3ihhBUX

**Comment by alexander255** [comment]
BTW: Just hiding the popup will not work since it will only show you the first few lines of the article, clicking on the "more"-style button will show the popup again…

**Comment by reek** [comment]
Hi,

Thanks, but dont work when i try to add to AAK
<code>
    tek_domains : {
      // by: Alexander255
      // issue: https://github.com/reek/anti-adblock-killer/issues/512
      host : ['tek.no', 'gamer.no', 'teknofil.no', 'insidetelecom.no', 'prisguide.no', 'diskusjon.no', 'teknojobb.no', 'akam.no', 'hardware.no', 'amobil.no'],
      onStart : function () {
        document.addEventListener("DOMContentLoaded", function () {
          var ad_frame = document.createElement("iframe");
          ad_frame.name = "_frame";
          document.body.appendChild(ad_frame);
          ad_frame.addEventListener("load", function () {
            ad_frame.contentWindow.inFIF = true;
          });
        });
      }
    },
</code>

**Comment by reek** [comment]
Firefox + ABP + Greasemokey

**Comment by alexander255** [comment]
Reason for the issue was that my script ran with `@grant none` while yours doesn't. Scripts with `@grant none` run directly in the context of their target page while others only see the content through a XRayWrapper. While this is usually not an issue in this case I was trying to set the JavaScript property `ad_frame.contentWindow.inFIF = true;` which is not part of the DOM. This change is not propagated to the page so the "ad check" fails and it looks like nothing happend.

    tek_domains : {
      // by: Alexander255
      // issue: https://github.com/reek/anti-adblock-killer/issues/512
      host : ['tek.no', 'gamer.no', 'teknofil.no', 'insidetelecom.no', 'prisguide.no', 'diskusjon.no', 'teknojobb.no', 'akam.no', 'hardware.no', 'amobil.no'],
      onIdle : function () {
        var ad_frame = document.createElement("iframe");
        ad_frame.name = "_frame";
        document.body.appendChild(ad_frame);
        ad_frame.addEventListener("load", function () {
          ad_frame.contentWindow.wrappedJSObject.inFIF = true;
        });
      }
    },

**Comment by reek** [comment]
Now works, thanks a lot :smile:

**Comment by github4321** [comment]
When will you release the next update? Or is it possible to already add it manually as a script in tampermonkey?

**Comment by reek** [comment]
In the coming days

**Comment by reek** [comment]
Yes, you can add manualy the code of alexander255

**Comment by github4321** [comment]
I tried to add a new user script with this:

// ==UserScript==
// @name        Anti-AdBlock tek.no
// @namespace   https://xmine128.tk/gm/
// @include     *://*.tek.no/*
// @include     *://tek.no/*
// @include     *://*.teknofil.no/*
// @include     *://teknofil.no/*
// @include     *://*.gamer.no/*
// @include     *://gamer.no/*
// @version     0.1.0
// @grant       none
// @run-at      document-start
// ==/UserScript==
 
document.addEventListener("DOMContentLoaded", function()
{
        var ad_frame = document.createElement("iframe");
        ad_frame.name = "_frame";
        document.body.appendChild(ad_frame);
       
        ad_frame.addEventListener("load", function()
        {
                ad_frame.contentWindow.inFIF = true;
        });
});

But it still blocks my Adblock Plus... Not sure if I'm doing it wrong though. Guess I'll just wait for the update.

**Comment by reek** [comment]
@github4321 
Remove it and install AakBeta: https://gist.github.com/reek/dc234ea9687056bd99fe (press Raw for install)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by aleksanderwaagr** [comment]
This doesn't appear to work in Chrome or Firefox. Using the latest version of the UserScript and the FilterList. Can you check this again?

**Comment by alexander255** [comment]
I've just verified that this site still works with AAK UserScript and breaks without. Are you sure you have the latest version of the AAK UserScript set up?

**Comment by aleksanderwaagr** [comment]
It seems to be broken in Chrome, but works in FF.

**Comment by reek** [comment]
@aleksanderwaagr 
actually it does not work with Chrome and Opera, thank you for the fix

**Comment by simonkaspersen** [comment]
Tek.no and it's daughterpages is still blocking content when using adblock. It does do a check if a ads-object is loaded or undefined, and will only load content if it is not blocked. 

It also contain white boxes where the ads are supposed to be

**Comment by reek** [comment]
@simonkaspersen 
this will be fixed, thank you

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Hi reek & all;
please see: https://forums.lanik.us/viewtopic.php?f=62&t=26438
