### ISSUE TITLE
VVVVID.it

### ISSUE THREAD

**Issue by Harlokk** [reek/anti-adblock-killer#513]
http://www.vvvvid.it/
http://i.imgur.com/tFCdxkn.jpg
Mozilla Firefox
AakList
uBlock Origin
EasyList + Peter Lowe’s Ad server list‎

<pre>
this.checkAdBlock = function (g, k) {
  var b = this.randomId(10);
  var l = this;
  img = $(document.createElement("IMG")).attr({
      src : "http://static.vvvvid.it/img/ad/advertisment.jpg?id=" + b,
      id : "img" + b
    }).css({
      display : "block",
      width : "1px",
      height : "1px",
      position : "absolute",
      top : "-10px",
      left : "-10px"
    });
  var d = $("<img id='adbimg2' src='http://static.vvvvid.it/img/pic01.jpg?id=" + b + "'/>");
  d.css({
    position : "absolute",
    top : "-10px",
    left : "-10px"
  });
  var m = function (n) {
    vvvvid.isAdBlockActive = n;
    if (k) {
      k(n)
    }
    if (n && g && vvvvid.user.get("userLogged")) {
      vvvvid.onAdBlock()
    }
  };
  var c = 0;
  var e = function (n) {
    ++c;
    a(n.target)
  };
  var j = function (n) {
    a(n.target)
  };
  var f = [];
  var a = function (n) {
    if (f.length === 0) {
      f.push(n);
      return
    }
    if (f.length === 1 && f[0] === n) {
      return
    }
    f.push(n);
    setTimeout(function () {
      var o = "#img" + b;
      var r = $(o);
      var s = $("#adbimg2");
      var q = MPImg.getDimensions(r.get(0));
      try {
        if (c < 2 && ($(o).length === 0 || $(o).css("display") === "none" || (q != null && (q.w != 2 || q.h != 3)))) {
          m(true);
          r.remove();
          s.remove();
          return
        }
        m(false);
        r.remove();
        s.remove()
      } catch (p) {
        vvvvid.log(p)
      }
    }, 500)
  };
  var h = function (n) {
    $("body").append(n);
    if (n.get(0).complete) {
      a(n.get(0))
    } else {
      n.load(j).error(e)
    }
  };
  h(img);
  h(d)
};
</pre>

**Comment by reek** [comment]
Sorry, content blocked for my contrry

<code>We are sorry,
this site is only available in Italy
due to copyright restrictions <7code>

**Comment by Harlokk** [comment]
hmm you could try a web proxy, maybe it works

**Comment by reek** [comment]
@Harlokk 
The ideal would be to use a VPN

**Comment by MajkiIT** [comment]
@Harlokk
Do you still see this notification?

**Comment by Harlokk** [comment]
@MajkiIT Yes :/

**Comment by MajkiIT** [comment]
I try to find a way to not see a geo lock. I tried to use proxy in Italy, biut it's not easy.

**Comment by reek** [comment]
@Harlokk 
Try add these rules
<pre>
@@||vvvvid.it/img/ad/advertisment.jpg
@@||vvvvid.it/img/pic01.jpg
</pre>

**Comment by Robotex** [comment]
It's working fine here using AAK | Reek 8.3, make sure to have Greasemonkey and js script active.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Harlokk** [comment]
ok! thank you guys !!
