### ISSUE TITLE
phonandroid.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#514]
Hi reek, 
on `http://www.phonandroid.com/` 

**phonandroid.com#@##adsense**

![anti-adblock](https://cloud.githubusercontent.com/assets/1873139/8998853/78fc777a-372a-11e5-8d93-ec012e712a77.png)

Thanks!

**Comment by reek** [comment]
Thanks again Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
