### ISSUE TITLE
slideplayer.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#515]
Hi; 
![no-adblock](https://cloud.githubusercontent.com/assets/1873139/9000305/1f2d4400-373d-11e5-8544-70fe212f7000.jpg)

on `http://slideplayer.fr/slide/1321500/`

**Comment by alexander255** [comment]
Hi reek!

The protection used by this site is identical with the one used by `slideplayer.org`!

Even circumventing the "share to download" rule can be archived using the exact same rule:
http://pastebin.com/wgT8ajHp

**Comment by SMed79** [comment]
and `http://slideplayer.com.br/`

**Comment by reek** [comment]
@alexander255 
Thanks good job  :+1:

**Comment by SMed79** [comment]
`@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?*$domain=slideplayer.com.br,slideplayer.fr,slideplayer.org`

**Comment by reek** [comment]
HI,

Thank you, but I will add alexander255 solution, for cons I'll add slideplayer.org

Regards
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
