### ISSUE TITLE
monova.org

### ISSUE THREAD

**Issue by Arcueides** [reek/anti-adblock-killer#516]
Hi,

Script resistant.  https://www.monova.org/

Please disable AdBlock to access site

<script async="" src="//www.monova.org/js/fuckadblock.js"></script>

Hope you can help ;)

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by mikhaelkh** [comment]
https://www.monova.org
https://imgur.com/6ckhDaU
[Latest Chromium for Windows x64](http://chromium.woolyss.com/download/)
Tampermonkey
uBlock Origin
Fanboy Ultimate + AakList

**Comment by mikhaelkh** [comment]
BTW, add [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines)

**Comment by reek** [comment]
@Arcueides 
Ok, I'll see how I can create, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
