### ISSUE TITLE
Script works even when list is disabled

### ISSUE THREAD

**Issue by mikhaelkh** [reek/anti-adblock-killer#520]
I have Latest [Chromium for Windows x64](http://chromium.woolyss.com/download/), Tampermonkey and uBlock Origin.
I installed script from github and **disabled** list in uBlock Origin.
All works as when list was enabled. Is that expected behaviour?

**Comment by reek** [comment]
HI,

This is normal, because they can operate without each other, as they unlock different sites

Regards
Reek
