### ISSUE TITLE
ipla.tv

### ISSUE THREAD

**Issue by piotr-szegda** [reek/anti-adblock-killer#522]
Example:
http://www.ipla.tv/Rodzina-zastepcza-odcinek-10/vod-27933
Script:
http://miniskrypt.blogspot.com/2012/09/inny-sposob-na-pobieranie-filmow-z-ipla.html
Same new videos use other format. I don't know workaround for it but old one should be simple to solve. 
New format example: http://www.ipla.tv/Rodzina-zastepcza-plus-odcinek-329/vod-170267

**Comment by reek** [comment]
Hi,

I am going to try to implement this in AAK so that it is automatically made

Regards
Reek

**Comment by reek** [comment]
Can you test: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw for install)

**Comment by piotr-szegda** [comment]
Work great. Good job.

**Comment by reek** [comment]
Thanks :smile:

**Comment by piotr-szegda** [comment]
Selecting episode from list sometime redirect to URL like this:
http://www.ipla.tv/Rodzina-zastepcza-odcinek-10/vod-27933#/r-30ai-4
It's don't work. Probably everything after # should be ignored.

**Comment by reek** [comment]
HI,

Remove <code>#/r-30ai-4</code>, I will correct this little bug for the next release

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
