### ISSUE TITLE
epoznan.pl/wtkplay.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#525]
![adblock](https://cloud.githubusercontent.com/assets/11302675/9086239/6d043b44-3b83-11e5-9358-104922855179.png)

http://wtkplay.pl/video-id-19757-szukaja_rak_do_pracy_przy_jesiennym_referendum_ws_jow_ow

solution is
@@|http://play.wtk.insys.pl/Scripts/InsysPlayer.v0.1.0/adTest.png$image,domain=play.wtk.insys.pl
@@|http://ad.adview.pl/ad/$xmlhttprequest,domain=play.wtk.insys.pl

**Comment by reek** [comment]
Thanks :smile:

**Comment by MajkiIT** [comment]
I write to EasyList to add exclude. ~wtkplay.pl##[class^="advertisement"]

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
