### ISSUE TITLE
turbodebrideur.com

### ISSUE THREAD

**Issue by BleuDiamant** [reek/anti-adblock-killer#526]
http://www.turbodebrideur.com/
http://i.imgur.com/Y8DxFsh.png
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

The script : 
<pre>
$(window).load(function(){
    setTimeout(function(){
        if ($("#pubdirecte img").size() == 0)
        {
            location = "http://www.turbodebrideur.com/adblock.php";
        }
    }, 1000);
});
</pre>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by streamdev** [comment]
Turbodebrideur.com anti adblock script updated :ghost:
I have bookmarked this page if you found how to bypass my script.
Have a good day :)
