### ISSUE TITLE
xiaopan.co

### ISSUE THREAD

**Issue by axarad** [reek/anti-adblock-killer#528]
Hi
Please add support for the following website (Forum) which shows an Adblock warning on a Splach Screen.
Thanks
Tested url: http://xiaopan.co/forums/threads/awus036ach.8126/
![untitled](https://cloud.githubusercontent.com/assets/10789454/9141714/a6b7c882-3d32-11e5-8d98-40682a2bfcf6.jpg)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
Reek what do you think about this solution:
@@|http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=xiaopan.co

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
