### ISSUE TITLE
youwatch.org

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#529]
Hi, 
`http://youwatch.org/embed-9j1p15u8ztwf-650x360.html`

![youwatch.org anti-adblock](http://i.imgur.com/HlQc0C4.png)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Thanks!

**Comment by SMed79** [comment]
**Youwatch** tab on `http://streamay.com/12204-les-minions.html`
```
@@||q41.twer.info/$script
@@||pla.folue.info/needes.js$script
```
https://hg.adblockplus.org/listefr/rev/4138a83470be
