### ISSUE TITLE
de.webfail.com

### ISSUE THREAD

**Issue by dschall** [reek/anti-adblock-killer#530]
Google Chrome
Tampermonkey
Adblock Plus
Ghostery
http://imgur.com/R3ZoKA5

**Comment by reek** [comment]
Hi,

Where is the problem , I see no antiadblock message

**Comment by dschall** [comment]
ah sorry, wrong blocker script.
I wanted to report this to "addefend klatsche", not here. my apologies.

**Comment by reek** [comment]
No worries
