### ISSUE TITLE
wyborcza.pl

### ISSUE THREAD

**Issue by piotr-szegda** [reek/anti-adblock-killer#531]
http://warszawa.wyborcza.pl/warszawa/1,34862,18526445,reprywatyzacja-w-warszawie-znow-chce-oddawac-budynki-i-tereny.html
http://imgur.com/ZcAT0vw
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by MajkiIT** [comment]
Try update EasyList. I don't this alert.

**Comment by MajkiIT** [comment]
I find solution: Problem is rule ||squid.gazeta.pl^ on EasyPrivacy. 

@@||squid.gazeta.pl/sqpwgl/$subdocument,domain=wyborcza.pl
@@||squid.gazeta.pl/info/squid/fprint.js$script,domain=squid.gazeta.pl
@@||squid.gazeta.pl/sqpwgl/$xmlhttprequest,domain=squid.gazeta.pl
@@||squid.gazeta.pl/info/squid/jquery-1.10.2.js,domain=wyborcza.pl

**Comment by reek** [comment]
Hi,

I think this single rule is sufficient
<code>@@||squid.gazeta.pl/sqpwgl/pwif$subdocument,domain=wyborcza.pl</code>

**Comment by MajkiIT** [comment]
I test it and if I add only @@||squid.gazeta.pl/sqpwgl/pwif$subdocument,domain=wyborcza.pl I still see notification. I clear cache. 

@piotr-szegda
Can you check?

**Comment by piotr-szegda** [comment]
@MajkiIT I confirm that. I forgot to write about EasyPrivacy in first comment. Maybe overriding checkAdBlock() solve problem forever.

**Comment by MajkiIT** [comment]
@piotr-szegda Ok thanks. Reek can you override checkAdBlock()? Maybe you use exlude to squid.gazeta.pl ?

**Comment by reek** [comment]
@piotr-szegda 
I will see

**Comment by reek** [comment]
@piotr-szegda 
Dont works need add rules
<code>
 @@||squid.gazeta.pl/info/squid/fprint.js$script,domain=squid.gazeta.pl
 @@||squid.gazeta.pl/sqpwgl/pwfpl$xmlhttprequest,domain=squid.gazeta.pl
 @@||squid.gazeta.pl/sqpwgl/pwif$subdocument,domain=wyborcza.pl
<code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
