### ISSUE TITLE
inn.co.il

### ISSUE THREAD

**Issue by yv-g** [reek/anti-adblock-killer#532]
http://www.inn.co.il/News/News.aspx/304042

http://imgbox.com/FXpsaJkC

Mozilla Firefox

ublock-origin

EasyList + AakList

**Comment by reek** [comment]
Hi,

I have no message

**Comment by yv-g** [comment]
My mistake. 
This site requires disable Adblock, even though I have installed anti-adblock-killer.

**Comment by reek** [comment]
Hi,

Try add this rule
<code>inn.co.il#@#.banner_ad</code>

**Comment by yv-g** [comment]
Hi,
Thanks for the quick reply.
Sorry for the stupid question.
How do I add this rule other filters?

2015-08-11 23:06 GMT+03:00 reek <notifications@github.com>:

**Comment by reek** [comment]
![capture](https://cloud.githubusercontent.com/assets/3474011/9210678/ee573742-407d-11e5-920c-7f82089a4815.PNG)

after paste rule, click on apply changes

**Comment by yv-g** [comment]
Unfortunately, it's not working.
The site is still requires disable Adblock.

2015-08-12 0:10 GMT+03:00 reek <notifications@github.com>:

**Comment by reek** [comment]
Ok, try install dev version: https://gist.github.com/reek/dc234ea9687056bd99fe (press raw)

**Comment by yv-g** [comment]
I do not use UserScript. 

I use ublock origin.

**Comment by reek** [comment]
You need install Greasemonkey, please read instructions

**Comment by yv-g** [comment]
I installed the script, but it still did not solve the problem.

**Comment by reek** [comment]
the dev version ?

**Comment by reek** [comment]
add this rule
<code>@@||inn.co.il^$elemhide</code>

**Comment by yv-g** [comment]
I'm sorry, but it is not working.

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer#help
