### ISSUE TITLE
clonezilla.fr (captchme.net)

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#533]
Hi reek; 

on `http://clonezilla.fr/telecharger/`

`@@||pagead2.googlesyndication.com/pagead/$domain=api.captchme.net`

![captchme-net](https://cloud.githubusercontent.com/assets/1873139/9188257/336a7878-3fd2-11e5-9621-420bce62ce17.png)

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
