### ISSUE TITLE
iconosquare.com

### ISSUE THREAD

**Issue by GoldMath** [reek/anti-adblock-killer#534]
Hi Reek,

http://iconosquare.com/viewer.php 
(You will need a Instagram account to login and see the blur/alert message)

http://imgur.com/DhUmBQJ

Opera 31.0
Tampermonkey
Adblock 2.35
EasyList + AakList + Adblock Warning Removal List

Thanks !

**Comment by reek** [comment]
Hi,

I dont use Instagram, can you create one me and send me http://reeksite.com/contact.php

**Comment by GoldMath** [comment]
*mail sent

**Comment by reek** [comment]
not received

**Comment by GoldMath** [comment]
is that good now ? I send it 3 times

**Comment by reek** [comment]
no, send to reekside@gmail.com

**Comment by reek** [comment]
Have you always anti-adblock message ? 
Because I have nothing that appears

**Comment by GoldMath** [comment]
It's look like in my configuration, the block is no longer active. 
Maybe they disable it or it's blocked by Adblock or whatever.
