### ISSUE TITLE
streamay.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#535]
Hi, 
**Youwatch** tab on `http://streamay.com/12204-les-minions.html`
```
@@||q41.twer.info/$script
@@||pla.folue.info/needes.js$script
```
https://hg.adblockplus.org/listefr/rev/4138a83470be#l1.48

**Comment by reek** [comment]
No need

**Comment by reek** [comment]
HI,

sorry, you were right, I will correct

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@SMed79 
New rule <code>@@||i93.whies.info^$script,domain=youwatch.org</code>

**Comment by SMed79** [comment]
Hi @reek; 
NOT needed for me http://i.imgur.com/zNOKCpI.png
I will recheck later !

**Comment by reek** [comment]
have you tried from a direct link http://youwatch.org/drt18f1uehtc

**Comment by SMed79** [comment]
Now i confirm found an anti-adb http://i.imgur.com/S0hZHfu.png but i can not to add to **Liste FR** because i need an issue in French web site. 
I have report on Easylist forum: https://forums.lanik.us/viewtopic.php?f=62&t=24552#p75383
