### ISSUE TITLE
filmovizija.me

### ISSUE THREAD

**Issue by JohnMiller9898** [reek/anti-adblock-killer#536]
![capture](https://cloud.githubusercontent.com/assets/13141946/9215482/91a444c6-40ab-11e5-9385-9da3a1d81a06.PNG)

Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

P.S. They changed domain from ''filmovizija.in'' to ''www.filmovizija.me''

**Comment by MajkiIT** [comment]
Add this and check:
@@|http://findvideo.tv/popunder.php$script,domain=filmovizija.me

**Comment by reek** [comment]
@MajkiIT 
that's right

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
