### ISSUE TITLE
lowcygier.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#539]
http://lowcygier.pl/promocje-cyfrowe/oferta-dnia-w-cdkeys-com-batman-ac-goty-i-cc-ultimate-edition/
http://lowcygier.pl/wp-content/themes/graphene/images/adblockers/top-big.png

Solution
@@||lowcygier.pl/wp-content/themes/graphene/js/ads.js$script

If you want to add cosmetic filters:
lowcygier.pl###moneymaker-1
lowcygier.pl##[style="min-width:730px; min-height: 90px; margin: 10px auto auto auto; text-align:center; overflow:hidden;"]

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
