### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#543]
![adblock2](https://cloud.githubusercontent.com/assets/11302675/9288417/22efb298-4346-11e5-9aa0-f0d70785007f.png)
https://portal.abczdrowie.pl/te-dziwne-sygnaly-wysylane-przez-twoj-organizm-swiadcza-o-spadku-
odpornosci
Mozila Firefox
Greasemonkey + Anti-Adblock-scipts
uBlock
Adblock Warning Removal List‎ + AakList + EasyList‎ with element hiding + Peter Lowe’s Ad server list‎ + EasyPrivacy‎ + Malware Domain List‎ + Polish filter

Ads on movie. 

The same alert like on wp.pl (https://github.com/reek/anti-adblock-killer/issues/300)

**Comment by reek** [comment]
Even when I deactivate AB and GM the message displays, the problem has to come from their

**Comment by MajkiIT** [comment]
If I disable uBlock I don't see message but many ads and video ad
![adblock3](https://cloud.githubusercontent.com/assets/11302675/9290417/e591d55a-4392-11e5-8a08-d6bcd0f82163.png)

**Comment by alexander255** [comment]
I can confirm @reek's observation: There is always an Anti-AdBlock message displayed.

Is this content be geo-locked to Poland by any chance? Could you try using a VPN service (such as [ZenMate](https://zenmate.com/)) and check if the site still works for you?

**Comment by MajkiIT** [comment]
ZenMate connected by Romania
![adblock34](https://cloud.githubusercontent.com/assets/11302675/9293583/01a2ab86-4431-11e5-86a3-e59540c259bd.png)

**Comment by MajkiIT** [comment]
Solution
@@|https://rek.www.wp.pl/vad.xml?rekid=233720&rektype=1&phtml=/portal.abczdrowie.pl/$xmlhttprequest,domain=portal.abczdrowie.pl
@@|https://js-agent.newrelic.com/$script,domain=portal.abczdrowie.pl
@@|https://dot.wp.pl/*/media.gif$image,domain=portal.abczdrowie.pl

**Comment by MajkiIT** [comment]
Reek filters to https://portal.abczdrowie.pl are include at https://www.certyficate.it/adblock/adblock.txt so I close issue.

**Comment by MajkiIT** [comment]
Hi Reek,
again I have problem with https://portal.abczdrowie.pl/niewinne-objawy-ktore-moja-byc-symptomem-raka
I see Adblock alert. Can you see that they change that it's not work now. I see random url like a95rptqvrwno2r.wp.pl .

**Comment by reek** [comment]
This rule works for me
<code>@@||wp.pl/bar.gif$xmlhttprequest,domain=portal.abczdrowie.pl</code>

**Comment by MajkiIT** [comment]
Yes Reek this rule is google. You are splendid :+1: But you must disable running AAK Scripts on this page, because if AAK Scripts are enable I see screen like this. 

![zrzut](https://cloud.githubusercontent.com/assets/11302675/13722491/f8996780-e847-11e5-9935-5d43efed7944.jpeg)

**Comment by reek** [comment]
Yes, I saw, I'll fix that too.

**Comment by MajkiIT** [comment]
Thanks again.

**Comment by derenma** [comment]
** In progress... Looks like these people are tracking these threads. :/

```
Comments from site:
      // Exclude domains
      // issue: https://github.com/reek/anti-adblock-killer/issues/1263
      // issue: https://greasyfork.org/en/forum/discussion/8422/
      // issue: https://github.com/reek/anti-adblock-killer/issues/986
      // issue: https://github.com/reek/anti-adblock-killer/issues/857
      // issue: https://github.com/reek/anti-adblock-killer/issues/617
      // issue: https://greasyfork.org/fr/forum/discussion/5426
      // issue: https://github.com/reek/anti-adblock-killer/issues/419
      // issue: https://github.com/reek/anti-adblock-killer/issues/377
```

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
