### ISSUE TITLE
crichd.tv

### ISSUE THREAD

**Issue by ecalevol** [reek/anti-adblock-killer#544]
I cant watch sports at this site.

http://www.crichd.tv/watch/177/england-under-19s-v-australia-live-streaming/

**Comment by reek** [comment]
HI,

Please read instructions, you need install script manager and AakScript
https://github.com/reek/anti-adblock-killer#instruction

Do not forget to donate, review, share, follow and add to favorites.

See you
Reek

**Comment by ecalevol** [comment]
i installed script manager and aaklist but the video plays but it still says to disable the adblocker using adblocker plus
![adlist](https://cloud.githubusercontent.com/assets/13814434/9291447/1dabc43c-438e-11e5-9d10-f9627d41a219.jpg)

![reek](https://cloud.githubusercontent.com/assets/13814434/9291449/273c5d9a-438e-11e5-901e-c25ddf8f28b2.jpg)

**Comment by ecalevol** [comment]
video plays but is dark and unwatchable til until i get rid of ant-adblocker

**Comment by reek** [comment]
You did not supply the wanted information

**Comment by ecalevol** [comment]
what do you need?

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

PS: I made a mistake about message

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/548
