### ISSUE TITLE
binbucks.com

### ISSUE THREAD

**Issue by ubless607** [reek/anti-adblock-killer#545]
http://binbucks.com/site/sc?v=MQ==&c=aHR0cDovL2V4YW1wbGUuY29t

Firefox 40.0.2 + Greasemonkey 3.3 + EasyList + AakList + ublock

**Comment by alexander255** [comment]
@reek
AAK script: http://pastebin.com/jfeddX7S
No filter rule possible since page content is replaced by Anti-AdBlock script.

**Comment by reek** [comment]
@alexander255 
Thanks, good job :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
