### ISSUE TITLE
aflamy.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#546]
Hi, 
`aflamy.com#@#.afs_ads` on `http://www.aflamy.com/portal/`

http://i.imgur.com/YDEJN7R.png

Thanks!

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
