### ISSUE TITLE
bitcoinaliens.com

### ISSUE THREAD

**Issue by DADEUSPER** [reek/anti-adblock-killer#547]
http://www.bitcoinaliens.com/faucet/
http://imgbox.com/wVzEszGT
Google Chrome
Tampermonkey
Adblock (getadblock.com)
EasyList+EasyPrivacy+Fanboy's Annoyances+Anti Adblock Filters+Malware Protection+Italian+Adblock Custom+AakList

The the same problem goes for Weekend bitcoin (http://www.weekendbitcoin.com/)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
