### ISSUE TITLE
gazeta.pl

### ISSUE THREAD

**Issue by ell22** [reek/anti-adblock-killer#549]
http://lublin.gazeta.pl/lublin/1,35640,17549734,PKP__Bilet_na_rower_przez_internet__Nie_ma_takiej.html
http://i.imgur.com/g64O3Yw.jpg
Mozilla Firefox
Greasemonkey
uBlock
µBlock filters‎
µBlock filters – Privacy‎ 
Anti-Adblock Killer | Reek‎ (raw.githubusercontent.com)
EasyList‎ 
Peter Lowe’s Ad server list‎
EasyPrivacy‎ 
Malware Domain List‎ (malwaredomainlist.com)
Malware domains‎
POL: Adblock polskie reguly‎
AakList (Anti-Adblock Killer)‎
facebook annoyances blocker
facebook news feed annoyances blocker‎
facebook sidebar blocker
Youtube: Other Annoyances‎
Youtube: Pure Video Experience‎
Youtube: Remove Comments‎
Youtube: Remove Youtube Suggestions‎

**Comment by MajkiIT** [comment]
add exclude
@@||squid.gazeta.pl/sqpwgl/$subdocument,domain=gazeta.pl

**Comment by reek** [comment]
@MajkiIT 
Thanks, I wiill add it

**Comment by MajkiIT** [comment]
@reek
You're welcome!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
