### ISSUE TITLE
receive-sms-online.info

### ISSUE THREAD

**Issue by a1b2c3d4** [reek/anti-adblock-killer#55]
When you click the number, this message appears:

We've detected that you're using AdBlock Plus or some other adblocking software. Please be aware that this is only contributing to the demise of the site. We need money to operate the site, and almost all of that comes from our online advertising. Please disable AdBlock Plus and refresh webpage!

thanks

**Comment by maynak00** [comment]
new antiadblock: http://www.receive-sms-online.info/advertisment.js
**try with:**
`@@||receive-sms-online.info/advert*.js$script`

**Comment by reek** [comment]
@maynak00 
thanks, i'll update

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
