### ISSUE TITLE
la-faculte.net

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#550]
Hi,
Please add support for www.la-faculte.net which shows the following pop-up about Adblock
Thank you!
Firefox 40+Adblock Edge+Easylist+Greasemonkey+AaK

![untitled](https://cloud.githubusercontent.com/assets/10789454/9337927/05f08492-45da-11e5-85c1-2bc4a8647ee7.jpg)

**Comment by MajkiIT** [comment]
Solution
la-faculte.net#@##adsense

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
