### ISSUE TITLE
www.femmeactuelle.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#551]
Hey Reek,
anti adblock message on `http://www.femmeactuelle.fr/`

![femmeactuelle](https://cloud.githubusercontent.com/assets/1873139/9367231/15e1bbde-46b4-11e5-9dd0-905525a48126.jpg)

Working for me:
```
@@||sascdn.com/config.js?nwid=$domain=femmeactuelle.fr
@@||sascdn.com/diff/js/smart.js$domain=femmeactuelle.fr
```

Thanks,
Med

**Comment by reek** [comment]
Thanks Med :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
