### ISSUE TITLE
bolor-toli.com

### ISSUE THREAD

**Issue by rrrgh** [reek/anti-adblock-killer#552]
http://www.bolor-toli.com blocks adblock plus even if anti-adblock killer is installed.

![screenshot from 2015-08-20 17-52-56](https://cloud.githubusercontent.com/assets/6065421/9386482/5a937bc2-4764-11e5-9754-813e4ffc0843.png)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
