### ISSUE TITLE
Rdio

### ISSUE THREAD

**Issue by ItsHipsterNoah** [reek/anti-adblock-killer#553]
http://www.rdio.com
http://i.imgur.com/k1rrxF3.png
Google Chrome
Tampermonkey
Adblock Plus
Adblock Warning Removal List, EasyList, EasyPrivacy, AakList

**Comment by reek** [comment]
See: https://greasyfork.org/fr/forum/discussion/4116

**Comment by Serv3rError404** [comment]
I'll take a look. Thanks.

**Comment by Serv3rError404** [comment]
I installed the script you provided, it's still showing that popup. :(

I have Adfender installed on my other PC, and it works fine. All Rdio ads are blocked. Unfortunately, Adfender isn't available for my other PC, which is a Macbook. I was hoping that this software could fix the problem.
