### ISSUE TITLE
algerie360.com

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#554]
Hi
Please ad support for this website: www.algerie360.com (script)
ublock origin+Easylist+Aak+Firefox 40)
Thank you
![untitled](https://cloud.githubusercontent.com/assets/10789454/9403758/b1cf7a4e-47e1-11e5-97ed-083bb7e5da56.jpg)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
