### ISSUE TITLE
tv3play (Wrong filters syntax)

### ISSUE THREAD

**Issue by Alex-302** [reek/anti-adblock-killer#555]
@@||adm.fwmrm.net/p/MTG_Live/ExternalHTMLAdRenderer.swf$object-subrequest,domain=tv3play.se,tv6play.se,tv8play.se,tv10play.se
need use | for separate domains

/anti-adblock$~stylesheet,~domain=mozilla.org
correct variant
 /anti-adblock$~stylesheet,domain=~mozilla.org

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
