### ISSUE TITLE
cpubenchmark.net

### ISSUE THREAD

**Issue by AxelRyder** [reek/anti-adblock-killer#556]
1. http://www.cpubenchmark.net/cpu.php?cpu=Intel+Core+i7-3770+%40+3.40GHz&id=896
2. http://i.imgur.com/qKTpBeo.png
3. Chrome 44.0.2403.157 m
4. Tampermonkey 3.11
5. AdBlock 2.37.2
6. https://raw.github.com/reek/anti-adblock-killer/master/anti- adblock-killer-filters.txt

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by AxelRyder** [comment]
It's gone, thank you very much
