### ISSUE TITLE
crichd.tv

### ISSUE THREAD

**Issue by Presently42** [reek/anti-adblock-killer#557]
http://www.crichd.tv/eurosport-1-hd-live-stream.php
http://i.imgur.com/SDCAHC9
Chrome unstable
Tampermonkey
uBlock Origin
My filters‎+uBlock filters‎+uBlock filters – Badware risks‎+uBlock filters – Privacy‎+uBlock filters – Unbreak‎+Anti-Adblock Killer | Reek‎+EasyList‎+Peter Lowe’s Ad server list‎+EasyPrivacy‎+Fanboy’s Enhanced Tracking List‎+Malware Domain List‎+Malware domains‎+Fanboy’s Annoyance List‎+Fanboy’s Social Blocking List‎

**Comment by Presently42** [comment]
The two problematic elements are very easily deactivated in chrome, using the element inspector: simply choose the frame over the player (the one slightly lower than the whole player frame) and delete it. This first is the simple text frame which says one must stop the adblocker to use the player. Then, using the element inspector, choose the same frame again: this removes the frame with the ads and whatever is causing the controls to be blocked.

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/548

**Comment by reek** [comment]
A solution will soon be published

**Comment by Presently42** [comment]
Apologies! I did search for other tickets, but I thought mine was the only one --- efficient dev! I guess I'm not too familiar with github. O dear.

**Comment by reek** [comment]
No worries :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Presently42** [comment]
There is still an issue: the site has a two-part system to blocking control of the player, as I noted in my second post. The first part has been successfully dealt with for the majority of channels, but the second part still exists, necessitating my using the inspector element to delete part of the site's code.

Perhaps, though, this is out of your purvue?

**Comment by reek** [comment]
Sorry, I forgot to correct this, but I'll take care.

**Comment by Presently42** [comment]
Whilst this site had been fixed, cridhd.tv has again changed their method of blocking adblock, rendering the previous fix unfortenately obsolete.

**Comment by reek** [comment]
I'll take a look

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
