### ISSUE TITLE
br.mangahost.com

### ISSUE THREAD

**Issue by xdextremex** [reek/anti-adblock-killer#558]
http://br.mangahost.com/
http://i.imgur.com/L1r1APS.png
Google Chrome
Adblock 
EasyList + AakList

<pre>
jQuery(function () {
  var scripts = jQuery('script');
  for (var i = 0; i < scripts.length; i++) {
    if (scripts[i].src.indexOf('br.mangahost.com/ads.js') >= 0) {
      testDisplay = false;
    }
    if (scripts[i].src == 'http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js') {
      if (!adsbygoogle.loaded) {
        testDisplay = true;
      }
    }
  }
  if (testDisplay) {
    jQuery('img').not('.post-ratings img, .brand img').attr('src', 'http://img.mangahost.com/br/adblock.png');
    jQuery('.ads').removeClass('ads336x280 ads728x90 ads160x600 ads300x250');
    jQuery('.ads').html('<div style="padding: 25px 30px; font-size: 21px; display: block !important;background: #333333;margin: 30px;line-height: 100%;"><span style="color:white">Por Favor</span> <span style="color: yellow">Desative Seu <img alt="AdBlock" src="http://img.mangahost.com/br/adblock.png" style="border:none"> ou BLOQUEADOR de AN&Uacute;NCIOS em nosso site.</span><br><em style="color: #94e0f6">Essa &eacute; a &uacute;nica colabora&ccedil;&atilde;o que pedimos para continuarmos no ar.</em>  <a style="color:white;" href="http://img.mangahost.com/br/tutorial_desativar_adblock.jpg" target="_blank" title="Clique!">Clique aqui para saber como desativar!</a> *Qualquer programa que fa&ccedil;a bloqueio de an&uacute;ncios continuar&aacute; a bloquear o site</div>');
  }
});
</pre>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller



http://www.hostingpics.net/viewer.php?id=287825AntiAdBlock.jpg%5D%5BIMG%5Dhttp://img11.hostingpics.net/pics/287825AntiAdBlock.jpg%5B/IMG%5D%5B/URL

**Comment by alexander255** [comment]
@reek If you haven't fixed this yet:

Filter list rules (removes banners):

    br.mangahost.com##.ads
   @@||br.mangahost.com/ads.js^$~script

User-script (prevents page images from being replaced by Anti-AdBlock messages): http://pastebin.com/4TanXGNr

The second filter list rule is required for the user-script to work.

**Comment by reek** [comment]
@alexander255 

I worked above it there a few minutes and I found a similar solution
<pre>
Aak.uw.adsbygoogle = {};
Aak.uw.adsbygoogle.loaded = true;
Aak.addStyle('.ads { display:none; }');
</pre>

Thank you again
Reek

**Comment by xdextremex** [comment]
what i have to do? i will need to edit by my self ?
i dont have ideia what to do

**Comment by alexander255** [comment]
@reek

Since the offical Google ads code uses:

    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>

I consequently injected an Array instead of an object into the page. Have checked your code in Firefox? Using `unsafeWindow.adsbygoogle = [];` resulted in object permission access exceptions being thrown in the browser console (hence the `cloneInto()` call).

I also tried to avoid injecting `display: none;` CSS rules, since I thought that using the AAK filter list should always be preferred over using JS code.

**Comment by reek** [comment]
@xdextremex 
You must wait until I update the script.

**Comment by reek** [comment]
@alexander255 
Ok, I'll use cloneIn, in this case, I used addStyle instead of a rule ab, so having everything in one place.

**Comment by reek** [comment]
@alexander255 
Can you take a look https://github.com/reek/anti-adblock-killer/issues/559

Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by smed79** [comment]
update, add:
`@@||cdn.komoona.com/scripts/kmn_sa.js$script,domain=mangahost.net`

**Comment by InitialDet** [comment]
It is detecting again
https://mangahost.org/
https://puu.sh/xcZJg/5180574e41.png
Chrome
Tampermonkey
uBlock Origin
EasyList + AakList
