### ISSUE TITLE
hackintosh.zone

### ISSUE THREAD

**Issue by Xeraser** [reek/anti-adblock-killer#559]
http://www.hackintosh.zone/
Takes 2-3 seconds then it redirects me to this page http://www.hackintosh.zone/donate.html and it tells me to disable adblock. I have ABP + AAK (On Firefox)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Xeraser** [comment]
Kinda short on money right now but I'll donate asap. Thanks for looking
into it.
Il 23/Ago/2015 21:41, "reek" <notifications@github.com> ha scritto:

**Comment by alexander255** [comment]
@reek
AAK Userscript: http://pastebin.com/yXf7uG4B

**Comment by Xeraser** [comment]
Works like a charm. Thanks a lot.

2015-08-24 13:53 GMT+02:00 Alexander Schlarb <notifications@github.com>:

**Comment by reek** [comment]
@alexander255 
Great, thanks :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by claviola** [comment]
This seems to be happening again.

**Comment by reek** [comment]
Ok, i will take a look

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
