### ISSUE TITLE
tv3sport.dk

### ISSUE THREAD

**Issue by bergses** [reek/anti-adblock-killer#560]
http://www.tv3sport.dk/fodbold/nyheder/lovebrol-frisparksmal-beckham-klasse/
http://imgur.com/1kPuymG
Google Chrome(Version 44.0.2403.157 m)
Adblock (same result with Adblock Plus)
TamperMonkey

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
HI,

Sorrym can't help you :(  <code>We're sorry. The video you are trying to watch is not available in your country.</code>

**Comment by MajkiIT** [comment]
@bergses add this to whitelist tv3sport.dk#@#.text_ads

**Comment by bergses** [comment]
@MajkilT Worked - thanks.
