### ISSUE TITLE
kingmaker.news

### ISSUE THREAD

**Issue by alexander255** [reek/anti-adblock-killer#561]
While we're add it with the Mac sites. Here's an AAK script for KingMaker.news: http://pastebin.com/hwSFTzYh

http://www.kingmaker.news/kingmaker/niresh-yosemite-with-intel-amd-installation-instructions/
Wait 10 seconds and it will send you to http://www.kingmaker.news/donate.html

**Comment by reek** [comment]
Hi,

Thanks good job :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
