### ISSUE TITLE
beta.speedtest.net

### ISSUE THREAD

**Issue by streetwolf** [reek/anti-adblock-killer#562]
http://beta.speedtest.net
http://i.imgur.com/CQErLvn.jpg
Mozilla Fx43
No script manager
uBlock Origin
uBlock Filters, EasyList,  EasyPrivacy, Fanboy's Enhanced Tracking List, Fanboy's Annoyance List, Anti-AdBlock Killer

<pre>
  setTimeout(scriptsLoaded(), 3000);

  function scriptsLoaded () {
    if (typeof adsOoklaComReachable == "undefined" && typeof window.require == "undefined" ) { 

      var head  = document.getElementsByTagName('head')[0];
      var link  = document.createElement('link');
      link.rel  = 'stylesheet';
      link.type = 'text/css';
      link.href = '/styles/icons/icons.data.svg.css';
      link.media = 'all';
      head.appendChild(link);

      var startButton = document.getElementsByClassName("js-start-test");
      startButton[0].style.opacity = ".2";

      var alertModal = document.getElementById("load-error-modal");
      alertModal.style.display = "block";
    }  
  }
</pre>

**Comment by reek** [comment]
Hi,

I am redirected to http://www.speedtest.net/, and I have no anti-adblock message. What your country ?

**Comment by streetwolf** [comment]
I thought you might have that problem.  I'm in the USA.


-----
Gary

----- Original Message -----

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/484

**Comment by alexander255** [comment]
I just tested creating an account on speedtest.net using ZenMate VPN USA, but it still redirects. This might be based on a cookie or something...

**Comment by streetwolf** [comment]
I was able to bypass the ad blocker message by adding these two rules to uBlock Origin under 'My rules':

beta.speedtest.net cdnst.net * allow
beta.speedtest.net speedtest.net * allow

**Comment by reek** [comment]
@alexander255 
Thank you for having tested with USA IP

@streetwolf 
Can you provide more information https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Extended, this will allow us can be to find a solution

**Comment by streetwolf** [comment]
The only thing I can think of is to use TeamViewer to get on my machine.  Then I can show you and maybe you can debug on my machine.

**Comment by reek** [comment]
@streetwolf 
I need the source code to analyze the anti-adblock script

**Comment by streetwolf** [comment]
Do you mean when I get the screen with the ad blocker message I should view the source, save it, and send it to you?  Or do you mean something else?

**Comment by reek** [comment]
@streetwolf 
with Adblock enabled and disabled

**Comment by reek** [comment]
@streetwolf 
Yes

**Comment by streetwolf** [comment]
Just put source with adblocker disabled on paste2.org

**Comment by reek** [comment]
@streetwolf
Yes again

**Comment by streetwolf** [comment]
here's the links
http://paste2.org/1hkYkjXF   Adblocker disabled
http://paste2.org/IM0s8PcY  Adblocker enabled

**Comment by reek** [comment]
install dev version http://tinyurl.com/pmnmb37

**Comment by streetwolf** [comment]
Ummm... How do I get your new script into uBlock Origin?

**Comment by reek** [comment]
install Greasemonkey after install dev version
https://github.com/reek/anti-adblock-killer#instruction

**Comment by streetwolf** [comment]
Doesn't seem to work.  It shows up in GM as 8.4.  I enabled your filters in uBlock Origin also.
