### ISSUE TITLE
turbodebrideur.com

### ISSUE THREAD

**Issue by quebec24** [reek/anti-adblock-killer#563]
http://www.turbodebrideur.com
http://imgur.com/o7ZKH0X
google chrome
adblock
Tampermonkey

**Comment by reek** [comment]
Hi,

Already fixed on 8.4, install from Github

See you
Reek

**Comment by quebec24** [comment]
Thanks for your quick answer but I already have version 8.4 installed:
http://imgur.com/rokOyme

and my list from adblock

http://imgur.com/b6pX39O

Am i doing something wrong?

**Comment by reek** [comment]
Its ok for me on Chrome and Firefox, try remove AakScript, restart browser and install AakScript

**Comment by reek** [comment]
if that does not work, please add https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Extended

**Comment by quebec24** [comment]
Thanks for your reply.
I tried with Firefox but it's the same thing
Source Code: http://paste2.org/9VHXHWFx
Extensions: Adblock plus, greasemonkey
Userscripts: http://imgur.com/R0LHyw9
Blocked Resources: http://imgur.com/sS3qoo9

**Comment by reek** [comment]
the problem comes from ListeFR, I'll see if I can fix with AakList

**Comment by quebec24** [comment]
Ok thanks for your help :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
