### ISSUE TITLE
arcor.de

### ISSUE THREAD

**Issue by alice-margatroid** [reek/anti-adblock-killer#564]
http://www.arcor.de/
http://i.imgur.com/Vnx92gO.png

Usage of those below?

math.floor()
n.charAt(e.floor(e.random()*n.length))

**Comment by reek** [comment]
HI,

Is advertising and not an anti-adblock message.

You can hide ads with this two rules
<code>arcor.de###oop_1 + div[id]</code>
<code>arcor.de###logoutdiv + .spacer.clear.h10 + .row + .spacer.clear.h10 + div[id]</code>

**Comment by alice-margatroid** [comment]
Oh you are right and sorry, I didn't realize that you meant overlays and other forms of messages. I was thinking anti-adblock counter-measures in general. Since they are very clever not to use a CDN for their ads on that website and change the element name all the time you reload.

Thank you a lot for these filtering rules and thanks for making your userscript. I have learned now more about creating my own filters.

**Comment by reek** [comment]
No worries, always ready to help :smile:
