### ISSUE TITLE
natemat.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#565]
http://natemat.pl/
![comment_y0ogapdoqotwsmvxlkstml5ffoosucnk](https://cloud.githubusercontent.com/assets/11302675/9493433/c42e3b04-4bff-11e5-8508-cb2b6fd44083.jpg)

Solution
natemat.pl#@#.afs_ads

**Comment by reek** [comment]
Hi,

No need with v8.4, now all site using this method will be neutralized

**Comment by MajkiIT** [comment]
Ok thanks.
