### ISSUE TITLE
cricfree.tv (biggestplayer.me)

### ISSUE THREAD

**Issue by psycohacker** [reek/anti-adblock-killer#566]
http://cricfree.sx/chelsea-tv-live-stream
http://imgbox.com/LTnb5lXa
Mozilla Firefox
Greasemonkey
ABP (AdBlockPlus)
Adblock Warning Blocking List + Easylist + Aaklist

<pre>
if ($('#adblock').is(":visible") == false) {
  $('#contenido').append('To get fullscreen and brighter screen DISABLE ADS BLOCKER and REFRESH Page');
}
</pre>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
