### ISSUE TITLE
krs-online.com.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#567]
http://www.krs-online.com.pl/images/whitelist.jpg

Solution
@@||krs-online.com.pl/js/showads.js$script,domain=krs-online.com.pl
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=krs-online.com.pl

**Comment by reek** [comment]
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
