### ISSUE TITLE
Multiup.com

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#568]
Hi
Anti-Adblock message on Multiup.com blocks download button (screenshot)
uBlock Origin+Firefox 40.03+Greasemonkey+Easylist+Aakiller
Tested Link: http://www.multiup.org/en/download/897175c28b62330d3614e44bc26023b6/en_windows_10_WZT-SVF.zip
![untitled](https://cloud.githubusercontent.com/assets/10789454/9556030/6b08212c-4dc9-11e5-85f6-d362ffb99d2a.jpg)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller


See: https://greasyfork.org/forum/discussion/5870

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
