### ISSUE TITLE
fr.misc.finance.banque.narkive.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#569]
Hi; 

![fr.misc.finance.banque.narkive.com](https://cloud.githubusercontent.com/assets/1873139/9559714/dadf1ade-4def-11e5-8737-0d46cc159ceb.png)

on `http://fr.misc.finance.banque.narkive.com/rHoFQ3xq/numero-iban-pour-les-banques-algeriennnes`
script `http://85.17.190.158/s/script.fr.min.js`

`DetectAdBlock=function`
`baitClass:'pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links'`

Thanks!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
