### ISSUE TITLE
doulci.net

### ISSUE THREAD

**Issue by ghost** [reek/anti-adblock-killer#57]
http://www.doulci.net/server-registration/
http://pastenow.ru/Upload/Paste/AAFA.png
Chrome 37
Tampermonkey
Adblock
EasyList + Russian List  + Anti-Adblock Killer | Filters for Adblockers

**Comment by clementine123** [comment]
I just enabled AAK in uBlock Origin and ensured that the subscriptions are updated. I then loaded http://doulci.net/ and still see the anti adblock warning on the page. Can you please check?
