### ISSUE TITLE
MultiUp.org

### ISSUE THREAD

**Issue by Brandit36** [reek/anti-adblock-killer#570]
1. "http://www.multiup.org/fr/download/89db9c7531ff1b5514abffff1a83d772/Inside.The.Walking.Dead-Documentaire.VOSTFR.720p-Brandit.avi" and "http://www.multiup.org/fr/mirror/89db9c7531ff1b5514abffff1a83d772/Inside.The.Walking.Dead-Documentaire.VOSTFR.720p-Brandit.avi"

2. "http://i.imgur.com/2wIuSJk.png" and "http://i.imgur.com/HmpLPA5.png"

3. Google Chrome

4. Tampermonkey

5. uBlock Origin

6. EasyList, AakList, Peter Lowe’s Ad server list‎, Adblock Warning Removal List

**Comment by reek** [comment]
Already fixed, update AakList

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/568

**Comment by Brandit36** [comment]
It's works ! Thanks !
