### ISSUE TITLE
not working in vgtv.no

### ISSUE THREAD

**Issue by techpulse** [reek/anti-adblock-killer#571]
http://www.vgtv.no/#!/video/116619/aatte-aar-gammel-storebror-tok-med-seg-soesken-paa-kjoeretur

**Comment by techpulse** [comment]
I updated the script and does not work.. I'm using Google Chrome.

Perhaps you are located outside of Norway, and the ads isn't going to appear for you..

**Comment by reek** [comment]
I can't block the videos ads

**Comment by techpulse** [comment]
Crazy, rip.
