### ISSUE TITLE
bricozone.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#574]
Hi, 
on `http://www.bricozone.fr/`

```
bricozone.fr#@#.adsbygoogle
@@/adBlockDetector/*$~third-party
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=bricozone.fr
@@||pagead2.googlesyndication.com/pub-config/ca-pub-*.js$domain=bricozone.fr

```

![bricozone.fr](https://cloud.githubusercontent.com/assets/1873139/9610015/cd6aa3dc-50ce-11e5-9e5b-1b7b7f3f2c4b.png)

Thanks!

**Comment by reek** [comment]
Thanks :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
