### ISSUE TITLE
Anti-adblock killer filter list interfares with Firefox 40's Get Add-ons display...again

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#575]
Only just noticed that troublesome Anti-adblock killer filter list rule is again interfering with the FF's "Get Add-ons" display.  I did confirm when it was last change to make it work in that rule, i.e., 

/anti-adblock$~stylesheet,domain=~mozilla.org

was working for a while.  But I just tried it in 40.0.3 and it no longer works.  Disabling that rule allows the "Get Add-ons" to display.

Still not earth shattering but I thought I should report it again anyhow.

**Comment by reek** [comment]
Ok, I'll delete it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
