### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by emannxx** [reek/anti-adblock-killer#576]
http://www.howtogeek.com
http://prntscr.com/8bkyl6
Google Chrome
uBlock Origin
my lists: http://prntscr.com/8bkz4y

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
**try this:**
>@@||howtogeek.com/adframe.js

*no comic sans font and no message on page*

**Comment by reek** [comment]
@maynak00 
This rule will be added has the next update

**Comment by emannxx** [comment]
Awesome. Thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
