### ISSUE TITLE
howtogeek.com

### ISSUE THREAD

**Issue by LtSneer** [reek/anti-adblock-killer#578]
http://i.imgur.com/tWcUjbL.png
Mozilla Firefox
Greasemonkey
uBlock Origin
Easylist +  Peter Lowe’s Ad server list‎

Additionally, they may be using this script:
https://gist.github.com/howtogeek/6b3ed7d917900229b37e

**Comment by maynak00** [comment]
**duplicate**
#576 
https://github.com/reek/anti-adblock-killer/issues/576#issuecomment-137193301

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
