### ISSUE TITLE
totaldebrid.org

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#580]
Hi,
Totaldebrid.org is redirecting to Adblock warning page (screenshot)
Used script from http://lutteadblock.blogspot.com/2014/11/le-script.html
URL: http://totaldebrid.org
(Firefox 40.0.3+Greasemonkey+Aak+Easylist+Ublock Origin)
Thanks
![untitled](https://cloud.githubusercontent.com/assets/10789454/9653539/e8348b26-521b-11e5-920f-289c3e2af50f.jpg)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
