### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by LOLfan** [reek/anti-adblock-killer#581]
1. http://player.pl/seriale-online/prawo-agaty-odcinki,562/odcinek-1,S07E01,36427.html
2. Before PLAY  https://drive.google.com/file/d/0B6CfoDXOIoZWOFFSckVzS25ZSHc/view?usp=sharing
3. After PLAY     https://drive.google.com/file/d/0B6CfoDXOIoZWSzY2NGUxYUlrU2s/view?usp=sharing
4. Mozilla Firefox
5. Greasemonkey
6. uBlock Origin
7. EasyList + AakList

**Comment by reek** [comment]
Here are two reasons for which it does not work
- You use Windows XP & Firefox
- Your IP isn't Polish

**Comment by MajkiIT** [comment]
Maybe try use this scripts.
http://www.certyficate.it/tvn-wp-player-pl-bez-reklam-adblock-usuwanie-reklam/

**Comment by reek** [comment]
@MajkiIT 
Does this link works it with you ?

**Comment by reek** [comment]
@LOLfan 
http://www.quirksmode.org/html5/tests/video.html

**Comment by MajkiIT** [comment]
This script is the same witch you have in yours script. 
https://github.com/reek/anti-adblock-killer/issues/293

**Comment by reek** [comment]
@MajkiIT 
Yes I understood

**Comment by LOLfan** [comment]
@reek
I'm using Windows 8.1 x64 and my IP is polish cuz I'm in Poland right now. I can watch three videos from quirksmode.org without any problems.

And let me get this straight: with AakList enabled in uBlock Origin I see whats on screenshot https://drive.google.com/file/d/0B6CfoDXOIoZWSzY2NGUxYUlrU2s/view When I disable AakList I see AdBlock warning and I can't watch video. And finally when I disable uBlock I can watch any videos on player.pl but with ads

**Comment by LOLfan** [comment]
@MajkiIT
Script with link you provided is awesome and it is working for me. I was searched for that. Thank You.

But anyway it is not so convinient like AakList could be if it will work properly.

**Comment by reek** [comment]
@LOLfan 
if you do not read the instructions, it is normal that it does not work

**Comment by LOLfan** [comment]
@reek
So it is my fault? AakList is working for you on player.pl or what...? Cuz i dont understand ;p

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#instruction

**Comment by LOLfan** [comment]
@reek 
So... ok it's working now but i didn't thought i need both: AakList filter in uBlock and script for Greasemonkey and in my opinion u could add some small info about that in Instruction. Cuz I didn't saw before that some addon need both filter and Greasemonkey script. That's why I made mistake.

P.S. I read Instruction before :)

**Comment by MajkiIT** [comment]
@Reek 
If I use Chrome, yours filters & scripts I see bug, because chrome don't use Silverlight, so I must add 2 filters
player.pl#@##vod 
@@||player.pl$elemhide

Maybe someone use this rules.
