### ISSUE TITLE
naruto-mx.net

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#582]
Hi, 
anti-adblock on : 
`http://www.naruto-mx.net/lecture-en-ligne/naruto_gaiden/000_Bonus_Special_Chapter_Boruto_Road_To_B/1`

![www.naruto-mx.net](https://cloud.githubusercontent.com/assets/1873139/9672123/baeeb38e-528f-11e5-8a62-00f508facf85.png)

source: https://forums.lanik.us/viewtopic.php?f=91&t=25038

Thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
