### ISSUE TITLE
premium-uploaded.net

### ISSUE THREAD

**Issue by GitHubro5** [reek/anti-adblock-killer#583]
Hi.

When I push Download button after paste link the premium-uploaded.net is redirecting to ad block warning page.
URL: http://premium-uploaded.net
![2015-09-05 11 26 39](https://cloud.githubusercontent.com/assets/14139205/9699653/077f6c42-5426-11e5-927f-b8138ed2fb32.png)

Safari 9.0
Tampermonkey 3.12.4752
uBlock 0.9.5.2
anti-adblock-killer 8.4
uBlock filters+uBlock filters privacy+EasyList+Peter Lowe’s Ad server list+EasyPrivacy+Malware Domain list+Malware domain.

**Comment by reek** [comment]
can you give me the link on which you are redirected

**Comment by reek** [comment]
Try just AakList + EasyList + EasyPrivacy

**Comment by GitHubro5** [comment]
Just I tried it, but It doesn't work. (still saying that please disable ad block...)

Here is a sample link.
http://uploaded.net/file/po20dgn9

Please try this link on http://premium-uploaded.net (just copy it and paste, then push download button)
Then you will see my problem.

**Comment by GitHubro5** [comment]
I found out why this is happens.
It is because I have turned anti-adblock-killer on with Tampermonkey, not on uBlock.

Even if both are same version, It doesn't work with Tampermonkey.

Thanks you.
