### ISSUE TITLE
tout-debrid.com

### ISSUE THREAD

**Issue by GitHubro5** [reek/anti-adblock-killer#584]
Hi.

When I only use internal AaK List on uBlock, It doesn't work on this site.
(but It works with Tampermonkey 3.12.4752+AaK script 8.4)

URL: http://tout-debrid.com (If the site ask you Password: tout-debrid)
![2015-09-06 3 28 57](https://cloud.githubusercontent.com/assets/14139205/9700719/ccb1e5f4-5448-11e5-8b4d-0ddcb95301aa.png)

Safari 9.0
uBlock 0.9.5.2
EasyList
EasyList Privacy
AaK List 8.4 with uBlock

**Comment by reek** [comment]
This is normal, because some antiblock are blocked by AakScript and others by Aaklist, so you must have both.

**Comment by GitHubro5** [comment]
Is it impossible to make that both things are same?

**Comment by alexander255** [comment]
No they are complimentary things:
AakList just contains rules about which elements and external resources a page should and shouldn't be able to access. That's all it does and all it can ever do.
AakScript contains deeper page modifications that interact which the site's JavaScript to fool it into thinking that ads are being shown normally.

AakList is more lightweight than AakScript but, for technical reasons outlined above, it cannot handle all possible cases.
AakScript can do everything that AakList can do and a lot more, but it requires more code and knowledge to do so (and its probably also less efficient in many cases as well). Unlike AakList it also requires a script manager to run (as opposed to being able to run as part of pretty much any decent AdBlocker).

Conclusion: It'd be possible to make AakList part of AakScript, but it'd be pretty pointless as most who use AAK use an AdBlocker anyways. It would also needlessly blow up AakScript, while (probably) being slower than using your native AdBlocker. Integrating AakScript into AakList is not technically possible (with the current generation of AdBlockers anyways).

**Comment by reek** [comment]
@alexander255 
Thank you for having so well explained the functioning of Ask to @GitHubro5

**Comment by GitHubro5** [comment]
Thank you for detailed answering.
