### ISSUE TITLE
VVVVID.it showing black screen

### ISSUE THREAD

**Issue by maddovr** [reek/anti-adblock-killer#585]
I have the latest ABP and anti-adblocker killer reek, however in vvvvid.it all i'm shown when i select an episode is a black screen. I'm using Windows 10 Pro x64 and Mozilla Firefox 40.0.3.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by Maddovr** [comment]
Sorry about that, here are all the info:

Link: http://www.vvvvid.it/#!show/370/shimoneta/371/482154/per-chi-e-il-buon-costume (registration required, also i picked a random one but all eps are like that)

Screen: http://i.imgur.com/vK57V4Z.png 

Browser: Mozilla firefox 40.0.3

Script Manager: Greasemonkey 3.3

Adblock: Adblock Plus 2.6.10

Lists: Easylist + AAK lists

**Comment by Maddovr** [comment]
Up.

**Comment by MajkiIT** [comment]
@Maddovr try add this to whitelist 
@@|http://des.smartclip.net/ads?type=dyn&plc=$xmlhttprequest,domain=vvvvid.it
