### ISSUE TITLE
noticiasautomotivas.com.br

### ISSUE THREAD

**Issue by DevXav** [reek/anti-adblock-killer#588]
http://www.noticiasautomotivas.com.br/
http://i.imgur.com/xRkbiwA.png
Google Chrome, Comodo Dragon (Based on Chromium 43.0.2357.81), Mozilla Firefox
None
AdBlock
EasyList + AakList

**Comment by MED-PRO** [comment]
Nothing on my side! do you Aak script And Tampermonkey? installed? check [Instructions](https://github.com/reek/anti-adblock-killer)

**Comment by reek** [comment]
https://greasyfork.org/forum/discussion/6050
