### ISSUE TITLE
articlerewritertool.com

### ISSUE THREAD

**Issue by WiFilter** [reek/anti-adblock-killer#589]
http://articlerewritertool.com/
http://imgur.com/x0tOjki
Mozilla Firefox
Greasemonkey
uBlock Origin
Easylist, Aaklist, Fanboy Lists, MVPS, Disconnect

Also
http://spinbot.com/
(Same developers/set of sites)

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
