### ISSUE TITLE
freedoge.co.in

### ISSUE THREAD

**Issue by injust** [reek/anti-adblock-killer#59]
https://freedoge.co.in
http://i.imgur.com/2cJzcnd.png
Google Chrome 37.0.2062.124 m 64-bit
N/A
µBlock
µBlock filters, Anti-Adblock Killer, EasyList, Peter Lowe’s Ad server list‎, Malware Domain List‎, Malware domains, Malware domains (long-lived), Spam404

**Comment by Injust** [comment]
Now that you are using AakScript, could you implement something to remove the ugly grey boxes where the advertisements used to be? This would be for freebitco.in and freedoge.co.in.

![image](https://cloud.githubusercontent.com/assets/3387175/7625224/cfc07a16-f9c2-11e4-947f-0a7497107096.png)

Thanks.

**Comment by kalgoop** [comment]
Still antiadblocker script is stopping me with the same message. On freebitco.in
Please tell me if you want any information or screenshots or login details.

**Comment by reek** [comment]
@kalgoop 
It's killed by AakList
