### ISSUE TITLE
lachainemeteo.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#590]
Hi reek, 
on `http://www.lachainemeteo.com/`

**`@@||a.ligatus.com/?ids=*&t=js$script,domain=lachainemeteo.com`**
https://hg.adblockplus.org/listefr/rev/b5bb870b3bb2#l1.102

![lachainemeteo](https://cloud.githubusercontent.com/assets/1873139/9829434/bd2b0f18-58fb-11e5-992e-68c63eec74ef.png)

You can remove old filters.

Thanks!
Med

**Comment by reek** [comment]
Already killed by AakScript

**Comment by SMed79** [comment]
Killed by **AakList** not **AakScript** :) 
`||lachainemeteo.com/js/lachainemeteo.js$script`
But this filter prevent loading a part of content > **MY FAVORITE WEATHER**.

![lachainemeteo](https://cloud.githubusercontent.com/assets/1873139/9832529/40a773e4-5975-11e5-98fd-27c03d7a9865.png)

**Comment by reek** [comment]
Ok, I'll add

**Comment by SMed79** [comment]
Hi @reek,
we can not player the video with this filter `||lachainemeteo.com/js/lachainemeteo.js$script`

check:
`http://videos.lachainemeteo.com/videos-meteo/video-videos-meteo-france/bulletin-france-78.php`

**Comment by reek** [comment]
I'll revome it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
