### ISSUE TITLE
clashofclans.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#591]
Hi, 
Anti-adblock message on `http://www.clashofclans.fr/forums/`
```
##.adblock_detector
##.adblock_floating_message
```
![clashofclans](https://cloud.githubusercontent.com/assets/1873139/9833058/fcc705b0-5981-11e5-9b15-7b4bd33505aa.png)

Thanks!

**Comment by reek** [comment]
Thanks Med !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
