### ISSUE TITLE
needrom.com

### ISSUE THREAD

**Issue by exodius48** [reek/anti-adblock-killer#593]
If i dont disable ad blocker, that site wont give me a download link.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by exodius48** [comment]
http://www.needrom.com/download/samsung-s6-dual-sim/
https://imgur.com/emQLy0r
Firefox Stable version (40.0.3)
Greasemonkey
uBlock Origin
EasyList+AAK & many more

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by exodius48** [comment]
Problem solved after i update subscription. Great job. :)

**Comment by reek** [comment]
:smile:
