### ISSUE TITLE
uflash.tv

### ISSUE THREAD

**Issue by boreddude001** [reek/anti-adblock-killer#594]
1. http://www.uflash.tv/video/14115/cum-for-hitchhiker

2. http://imgur.com/AGRXtED

3. google chrome

4. tampermonkey

5. adblock

6. anti-adblock killer reek

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Normally it should work, the problem may come from another extension or program or a rule that has been disabled.

if this is the case, you must allow the resource below
<code>http://www.uflash.tv/media/player/advertisement/advertisement.js</code>

Check if one of these extensions is problematic (Disable Anti-Adblock 3.1, Ghostery, Online Security Avast, Donotrackme, Privacy Badger, Disconnect, Blur, TrackerBlock, Kaspersky Anti-Banner, Freebox (Anti-pub), No Script).

**Comment by boreddude001** [comment]
Where would I put this?

document.write('<div id="qS8sdkfmx8">ADVERTISEMENT</div>');

Sorry noob here.

**Comment by reek** [comment]
Your extensions please

**Comment by reek** [comment]
Have you subscribed to AakList ?
https://github.com/reek/anti-adblock-killer#instruction

**Comment by reek** [comment]
Hi,

I just tested with Chrome and several adblocker. It seems that the problems come from the interaction of Adblocker and Chrome.

Until they solve the problem, I'll see if I can find an alternative solution.

For now, I can only recommend you to use Firefox

Regards
Reek

**Comment by boreddude001** [comment]
It worked! that link you gave me to subscribe made it work. IT's kinda nasty video though. Now washpo doesn't work... I'll post a new issue thread.

**Comment by reek** [comment]
Ok

**Comment by pro100Hub** [comment]
Hello.
I use uBlock for Firefox 65 and your List (https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt)
Is it possible to bypass the ban on viewing on the site uflash.tv? Video viewing is possible only when uBlock is turned off, but without it a lot of ads and pop-up windows.

Regards.
