### ISSUE TITLE
leveldown.fr

### ISSUE THREAD

**Issue by jordan092427** [reek/anti-adblock-killer#595]
http://leveldown.fr/
http://imgur.com/fZPxZfq
Google Chrome
Tampermonkey
Adblock Plus
Liste FR+EasyList
AakList (Anti-Adblock Killer)
EasyPrivacy
Adblock Warning Removal List
Fanboy's Annoyance List
AntiPubWeb

Ps: all web site was blocked

thx

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Normally it should work, the problem may come from another extension or program or a rule that has been disabled.

if this is the case, you must allow the resource below
<code>http://leveldown.fr/dist/js/advertisement.js</code>

Check if one of these extensions is problematic (Disable Anti-Adblock 3.1, Ghostery, Online Security Avast, Donotrackme, Privacy Badger, Disconnect, Blur, TrackerBlock, Kaspersky Anti-Banner, Freebox (Anti-pub), No Script).

**Comment by reek** [comment]
Have you subscribed to AakList ?
https://github.com/reek/anti-adblock-killer#instruction

**Comment by jordan092427** [comment]
Hi,

Yes i'm subcribe to AakList ( Filter + UserScript )

Only tampermonkey and adblock+ are enable

The problem is adblock when i disactivated it the web site work

I add http://leveldown.fr/dist/js/advertisement.js to personal filter on adblock+ (it's here??) but not work 

I re-intall adblock+ but the problem not solved (with Liste FR+EasyList, Adblock Warning Removal List and AakList (Anti-Adblock Killer) only )

What i can do?

Thanks

**Comment by reek** [comment]
Hi,

I just tested with Chrome and several adblocker. It seems that the problems come from the interaction of Adblocker and Chrome.

Until they solve the problem, I'll see if I can find an alternative solution.

For now, I can only recommend you to use Firefox

Regards
Reek

**Comment by jordan092427** [comment]
Ok, thank for help

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
