### ISSUE TITLE
mail.ru

### ISSUE THREAD

**Issue by icredt** [reek/anti-adblock-killer#596]
mail.ru probably the largest postal portal (plus search engines, and more) with millions of customers. In version 28 firefox it works fine with all adblock, but version 38 is already displays a message that you need to enable JavaScript. Versions of between 28-38 have not tried it, so I do not know with what kind of version of the problem begins. The message is displayed after entering the mailbox instead of a list of letters (on page e.mail.ru). I would like to have your killer helped in solving this problem. Sorry for Google Translate ...

mail.ru наверное наиболее крупнейший почтовый портал (плюс поисковик и многое другое) с миллионами клиентов. На версии firefox 28 он работает нормально со всеми adblock, но на версии 38 уже выдаёт сообщение о том, что нужно включить яваскрипт. Версии между 28-38 не пробовал, так что не знаю с какой именно версии начинается проблема. Сообщение это появляется после входа в почтовый ящик вместо списка писем (на странице e.mail.ru). Хотелось бы чтобы Ваш киллер помогал в решении данной проблемы. Извините за гугл транслейт...

**Comment by reek** [comment]
Hi,

Check that Javascript is enabled and activated if it is not.
http://activatejavascript.org/en/instructions

Take a screenshot of problem and post here
