### ISSUE TITLE
turbodebrideur.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#599]
Hi, 
`http://www.turbodebrideur.com/` force redirection to /adblock.php

`@@||pubdirecte.com/script/banniere.php?id=$script,domain=turbodebrideur.com`

Thanks!

**Comment by streamdev** [comment]
Hi SMed79,
I'm the owner of turbodebrideur, you can't block ads on our site, ads allows us to pay our charges.
You don't want ads? No problem, pay a Purevid subscription and enjoy it, it's very cheap.
Thanks for your understanding.

**Comment by SMed79** [comment]
@streamdev je n'ai rien contre vous ou votre web site. 
Regards,
Med
