### ISSUE TITLE
New Facebook Anti-Adblock Issue

### ISSUE THREAD

**Issue by alexzmercury** [reek/anti-adblock-killer#600]
Facebook has just enacted an anti-adblock checker (confirmed amongst other friends), so now messages are blocked as well as the newsfeed ticker.

**Comment by SMed79** [comment]
Hi, 
if you use [Adblock plus](http://adblockplus.org/) submit an **[issue repport](https://adblockplus.org/getting_started#false-negatives)** and paste the link here !

**Comment by ngyikp** [comment]
It was a false positive that the messages Javascript was compiled to a file named "RPNcr3s**-aD2**.js", Facebook fixed it by doing their daily Javascript re-compilation again.

https://forums.lanik.us/viewtopic.php?f=64&p=77341

**Comment by SMed79** [comment]
@ngyikp for the info.

**Comment by reek** [comment]
@ngyikp
Thanks, i close issue
