### ISSUE TITLE
not working on 990.ro

### ISSUE THREAD

**Issue by janusmuller** [reek/anti-adblock-killer#601]
www.990.ro

both chromium and firefox

TamperMonkey
Adblock
AAK 8.4
Ghostery

hoping for a release with this site included

thanks

**Comment by SMed79** [comment]
Hi, 
`@@||990.ro/functions/adgen2/adbanner.js?$script`

**Comment by janusmuller** [comment]
Hi, 
Thanks for that but I'm not sure if I'm doing this right, I forked the script, added this at: 

https://raw.githubusercontent.com/janusmuller/anti-adblock-killer/master/anti-adblock-killer-filters.txt

! 990.ro
@@||990.ro/functions/adgen2/adbanner.js?$script,~third-party

and modified listURL in dashboard

it doesn't work, it still detects AdBlock

**Comment by SMed79** [comment]
@janusmuller screen record http://getwebb.org/d/nQzZQxct

**Comment by janusmuller** [comment]
thanks! now it works, didn't know where to add that

**Comment by SMed79** [comment]
Note that you can request assistance on [EasyList Forum](https://forums.lanik.us/) or [Adblock Plus Forum](https://adblockplus.org/forum/).

**Comment by reek** [comment]
@SMed79 
Thank you for solution and for helping @janusmuller
