### ISSUE TITLE
journaldugeek.com (Network)

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#602]
Hi reek, 
on: 
```
http://www.journaldugeek.com/
http://www.journaldugamer.com/
http://news.pixelistes.com/
http://www.jdubuzz.com/
```

`@@/adscript.js$script,~third-party,domain=jdubuzz.com|journaldugamer.com|journaldugeek.com|pixelistes.com`

Thanks!

**Comment by reek** [comment]
Thanks Med :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
