### ISSUE TITLE
fossbytes.com

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#603]
hi,
http://fossbytes.com/top-10-best-free-antivirus-software-of-2015/

Popup box received:
Adblocker detected! Please consider reading this notice.
...
...

**Comment by SMed79** [comment]
Hi, 
try: 
`fossbytes.com#@##adsense`

**Comment by callmenemo491** [comment]
cheers. added that to my Adblock list and it stopped the pop-up.

**Comment by reek** [comment]
Thanks Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by manjusr81** [comment]
Hi,  its not working on this url    keshavcommoditycalls.com

**Comment by manjusr81** [comment]
Pls tell me how to go about.   I am using chrome latest

**Comment by smed79** [comment]
@manjusr81 add this filter https://forums.lanik.us/viewtopic.php?f=62&t=36035
see how to add custom filter https://adblockplus.org/forum/viewtopic.php?f=2&t=42013

**Comment by manjusr81** [comment]
NO LUCK. STILL SAME ERROR.  NOT WORKING

**Comment by manjusr81** [comment]
THANKS IT WORKED.

RGDS/MANJUNATH

**Comment by manjusr81** [comment]
Another POP UP AD.   Most of the time it pops up.   Pls provide a solution.
![selection_029](https://cloud.githubusercontent.com/assets/9315238/24233172/7d50a204-0fb6-11e7-91b9-d62c8dd49224.png)
![selection_030](https://cloud.githubusercontent.com/assets/9315238/24233176/817abd42-0fb6-11e7-82a2-d6b178e798ba.png)

**Comment by manjusr81** [comment]
I ll have to close the ad below by clicking the X close button everytime.

**Comment by smed79** [comment]
> Another POP UP AD....

Report unblocked ad at easylist forum.
