### ISSUE TITLE
showup.tv

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#604]
http://showup.tv/pinkfluffyunicorn or another stream.

Solution
@@|http://showup.tv/js/core/Advertisement.js$xmlhttprequest,domain=showup.tv

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
