### ISSUE TITLE
habrahabr.ru, megamozg.ru, geektimes.ru

### ISSUE THREAD

**Issue by mikhaelkh** [reek/anti-adblock-killer#606]
http://habrahabr.ru/, http://megamozg.ru/, https://geektimes.ru/
https://imgur.com/t3ONzSb
Chrome dev x64
Tampermonkey
uBlock Origin
Fanboy+Easylist-Merged Ultimate List‎,  Anti-Adblock Killer, RUAdList, BitBlock.

These 3 sites have the same design and banner.

**Comment by SMed79** [comment]
Hi,
try:
`@@/advertising.js$script,domain=habrahabr.ru|megamozg.ru|geektimes.ru`

**Comment by mikhaelkh** [comment]
@SMed79 This solution loads `advertising.js` while the purpose of this project AFAIK is to kill anti-adblock messages without whiltelisting ad scripts.

**Comment by reek** [comment]
@mikhaelkh 
<code>advertising.js</code> it's a bait file, it contains no advertising

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by wsmith1** [comment]
Current bait object is adriver from adriver.js

Please add this rule

```
@@/adriver.js$script,domain=habrahabr.ru|megamozg.ru|geektimes.ru
```

**Comment by reek** [comment]
@wsmith1 
Ok, thanks :+1:

**Comment by wsmith1** [comment]
There is a pull request #1078 for this, by the way.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
