### ISSUE TITLE
Remove banner

### ISSUE THREAD

**Issue by mikhaelkh** [reek/anti-adblock-killer#607]
You can remove banner from wiki and contributing.md pages, because banner on the main page is enough. By the way, banner on contributing.md page doesn't show because of the mistake in the first line.

**Comment by SMed79** [comment]
Hi, 
* the role of **anti-adblock killer** is to bypasse anti-adblocker
* request assistance on [Easylist forum](https://forums.lanik.us/) or [Adblock plus forum](https://adblockplus.org/forum/).
* link?

**Comment by mikhaelkh** [comment]
I'm talking about [this project](https://github.com/reek/anti-adblock-killer)

**Comment by callmenemo491** [comment]
i have found the mistake that @mikhaelkh is talking about on the "contributing.md" page.
here is the pull request with the modification: https://github.com/reek/anti-adblock-killer/pull/609

**Comment by reek** [comment]
I'll fix that

**Comment by reek** [comment]
done :+1: 
thanks callmenemo491
