### ISSUE TITLE
swagbucks

### ISSUE THREAD

**Issue by majig12346** [reek/anti-adblock-killer#608]
trying anything redicts you to this page: http://www.swagbucks.com/p/offer-unavailable
there is a banner on whole website( including homepage, when logged in) saying We think you've got an ad blocker installed.

http://www.swagbucks.com/

**Comment by SMed79** [comment]
Hello, 
I tried to register for testing but when I click on the button **Get Started** nothing happens.

**Comment by majig12346** [comment]
idk i guess try disabling adblock when u first test and making sure u type something in (fill in email, password)before you hit "Get Started", cuz the first thing I did when i went to that page was hit the button without typing in anything,and nothing happened

side note: i am using ublock origin
