### ISSUE TITLE
4tuning.ro

### ISSUE THREAD

**Issue by naturalspark** [reek/anti-adblock-killer#610]
http://www.4tuning.ro/
http://imgur.com/oANsTY4
Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by MajkiIT** [comment]
For me solution is 4tuning.ro#@#.adsbygoogle

**Comment by naturalspark** [comment]
It works for me too. Thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
