### ISSUE TITLE
stadium-live.biz (playerapp1.pw)

### ISSUE THREAD

**Issue by Kellerassel** [reek/anti-adblock-killer#611]
http://stadium-live.biz/Channel13.html

![stream](https://cloud.githubusercontent.com/assets/14200738/10029401/fa3e56b6-6171-11e5-8343-d3fd1972172b.jpg)

Browser: Firefox
Scriptmanager: Greasemonkey
Adblocker: AdBlock Plus

Filterlists:
EasyList Germany + EasyList
Adblock Warning Removal List
AakList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
