### ISSUE TITLE
vtele.ca

### ISSUE THREAD

**Issue by hinrik** [reek/anti-adblock-killer#612]
http://vtele.ca/videos/un-souper-presque-parfait/semaine-en-forme-ca-jase-entrainement-et-saine-alimentation-chez-valerie_84734.php
http://i.imgur.com/cVrE2Rt.png
Chrome Windows x64
Tampermonkey
uBlock Origin
Anti-Adblock Killer

**Comment by MajkiIT** [comment]
Geolock, I try ZenMate but nothing.

**Comment by hinrik** [comment]
Yeah, if you're outside Canada you need to view this through a VPN service (e.g. Hola).

**Comment by MajkiIT** [comment]
Hi, try to add this
@@||cdn.adgear.com/a/adgear.js/current/adgear.js$domain=vtele.ca

**Comment by hinrik** [comment]
Yep, it works!

**Comment by MajkiIT** [comment]
Ok thanks. Please don't close this issue. Maybe Reek add this rule.

**Comment by reek** [comment]
@MajkiIT 
Thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/752#issuecomment-181545194
