### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by boreddude001** [reek/anti-adblock-killer#613]
1. 
www.cbs.com/shows/the-late-show-with-stephen-colbert/video/920AB6FA-E98D-698A-CCD6-F8300945EE59/dr-ernest-moniz-explains-the-iran-deal/

2. imgur.com/kFsNe9T

3. Chrome

4. tampermonkey

5. adblock

6. reek aarklist (i think...)

**Comment by MajkiIT** [comment]
Can you try add this rule and check:

@@|http://pubads.g.doubleclick.net/gampad/ads$object-subrequest,domain=cbs.com

**Comment by reek** [comment]
@boreddude001 
Sorry, I have no solution yet

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/71

**Comment by boreddude001** [comment]
@MajkiIT 

Where do I add that rule?

**Comment by MajkiIT** [comment]
In adblock settings. Own filters ==> whitelist.

**Comment by boreddude001** [comment]
@reek 

Ok That easylist from 

https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt

Worked

**Comment by boreddude001** [comment]
@MajkiIT 

adding that single line alone without the easylist update from above unblocks the adblock blocker. But it stalls for a while saying advertising is loading, and then the video loads.

**Comment by MajkiIT** [comment]
I didn't update easylist, because I have fresh version. I know that you can see "advertising is loading", but it's same progress.

**Comment by reek** [comment]
Ï close if solved by EasyList
