### ISSUE TITLE
tibiopedia.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#615]
solution @@||tibiopedia.pl/js/show_ads.js$script,domain=tibiopedia.pl

**Comment by reek** [comment]
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
