### ISSUE TITLE
redundant rules

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#616]
@@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com has been made redundant by @@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com|waterbitco.in
playerhd1.pw###total_banner has been made redundant by playerhd1.pw##[id^="total"]
@@||onvasortir.com/advertisements.js$script has been made redundant by @@||onvasortir.com^$script
@@||onvasortir.com/smartadserver.com.js$script has been made redundant by @@||onvasortir.com^$script
@@||adsrv.gpm-digital.com/crossdomain.xml$object-subrequest,domain=rutube.ru has been made redundant by @@||adsrv.gpm-digital.com/$object-subrequest,domain=rutube.ru

**Comment by reek** [comment]
Thanks, i will fix it :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
You don't reduce all redundant's filters
@@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com has been made redundant by @@/show_ads.js$script,domain=bithourly.com|dailyfreebits.com|jewelrybitco.in|welovebtc.com

playerhd1.pw###total_banner has been made redundant by playerhd1.pw##[id^="total"]

@@||adsrv.gpm-digital.com/crossdomain.xml$object-subrequest,domain=rutube.ru has been made redundant by @@||adsrv.gpm-digital.com/$object-subrequest,domain=rutube.ru

**Comment by reek** [comment]
Thanks you again :+1:
