### ISSUE TITLE
Breaks fsf.org Wiki

### ISSUE THREAD

**Issue by teresaejunior** [reek/anti-adblock-killer#617]
I'm using Anti-Adblock Killer with Firefox 40 and Greasemonkey, and after having tested it multiple times, I found that it breaks the layout of the Free Software Foundation Wiki. See this page for example https://directory.fsf.org/wiki/IceCat, the whole description for IceCat is missing with Anti-Adblock Killer enabled!

Thank you for your attention!

**Comment by reek** [comment]
Hi

Ok, I'll exclude fsf.org

Thanks

**Comment by teresaejunior** [comment]
OK, thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
