### ISSUE TITLE
unshowmasonline.com

### ISSUE THREAD

**Issue by sigtus** [reek/anti-adblock-killer#618]
URL: http://unshowmasonline.com/
Screenshot: https://i.imgur.com/ldDzTHK.png
Browser: Waterfox 40.0.2
Script manager: Greasemonkey 3.4.1
Adblocker: uBlock Origin 1.1.1
Filterlists: AAK, EasyList, Peter Lowe, EasyPrivacy, and Fanboy.

**Comment by MajkiIT** [comment]
Domain dead ... 

Results
from DNS:	Inconclusive. DNS server returned an error: Name server failed
from Whois:	Taken.
conclusion:	Taken. The domain has been registered. However, the registrant may offer it for sale.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
@MajkiIT 
Domains is ok for me

**Comment by MajkiIT** [comment]
On my PC nslookup not resolve domain. Maybe tomorrow will be ok.

**Comment by reek** [comment]
@MajkiIT 
https://www.whatsmydns.net/flush-dns.html

**Comment by MajkiIT** [comment]
Thank you. I know, but dns of my ISP not resolve domain, but on google dns it's OK.

**Comment by MajkiIT** [comment]
Reek for me solution is ==> @@|http://unshowmasonline.com/banner.gif$domain=unshowmasonline.com

**Comment by reek** [comment]
@MajkiIT 
Ok, thanks

**Comment by sigtus** [comment]
@MajkiIT Thank you, I edited that one because it only worked on the main page, it works like a charm like this:
@@|http://unshowmasonline.com^banner.gif$domain=unshowmasonline.com

**Comment by MajkiIT** [comment]
Ok.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
