### ISSUE TITLE
Multiup.org

### ISSUE THREAD

**Issue by 514guy** [reek/anti-adblock-killer#619]
It seems like multiup.org has instituted an adblock-checker before allowing a file to be downloaded. I've tried whitelisting their "blockadblock.js" to no avail. I've tried disabling ABP on that specific page, to no avail.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by 514guy** [comment]
My apologies. The odd thing is that on W7x86, on FF stable, it doesn't occur. It's only occurring on W764 on Nightly 64-bit. Both have the exact same filterlists, extensions, and plugins. I made a backup of the x86 working ADB, and imported them to the 64-bit ADB, with no change. On the 32-bit, there is a hidden item that gets whitelisted, that is a part of this anti-adblock killer: multiup.org#@#.ADBAR . For some reason, it's not being seen by ADB on 64-bit Nightly. It may be that this an ADB issue.

http://www.multiup.org/download/e3cdec7cb1420d18fc367e64466be52c/DiRT_Complete_Edition_BLUS30975.part1.rar

Working on 32-bit: http://i.imgur.com/WYlnOzy.png
Not working on 64-bit: http://i.imgur.com/FJHDeyf.png

ABP dev 2.6.11.3984 beta
GM 2015.9.25 nightly
Easylist
Anti-Adblock KIller

**Comment by reek** [comment]
Weird, I use FF + ABP on W7x64 and it's ok.

Have you tested with AdBlock or uBlock ?

**Comment by 514guy** [comment]
I've posted this on ABP forum @ https://adblockplus.org/forum/viewtopic.php?f=1&t=40629 . It may be a nightly problem.

**Comment by Afkjson** [comment]
Hi,
I can confirm this problem.

FF 40.0.3
Greasemonkey 3.4.1
uBlock Origin 1.1.1
Easylist + uBlock default + EasyPrivacy + hpHosts + AdBlock warning removal list

Thank you for your creating Anti-AdBlock Killer!

**Comment by Afkjson** [comment]
There are two solutions:
1. Here: https://forums.lanik.us/viewtopic.php?f=64&t=24800
2. Replace "download" with "mirror" in URL.

This can be marked as solved when it gets added to Easylist.

**Comment by reek** [comment]
Thanks,
<code>multiup.org#@#.BannerAd</code>  is more appropriate.
<code>@@||multiup.org^$elemhide</code> while allowing all ads

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Brandit36** [comment]
The message appears again. Please fix.

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/677#issuecomment-148707342

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by maynak00** [comment]
adblocker detected
example link: http://www.multiup.org/en/download/22c3ec585f13afc7a03d485bea445574/Before.Sunset.2004.720p.BrRip.x264.mkv
**custom filter:**
>@@||195.154.104.153/pop.js$script,domain=multiup.org

Static filter /pop.js| found in:EasyList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
