### ISSUE TITLE
Failed to open URI google chrome

### ISSUE THREAD

**Issue by hillz1** [reek/anti-adblock-killer#620]
I'm using google chrome version 45 and ublock origin + tampermonkey, I'm stuck at step two, I get this every time I try to subscribe to the filter list, all links give the same error.

![](http://s18.postimg.org/g9f6bz2gp/image.png)

**Comment by MajkiIT** [comment]
Hi, if you open this url (https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt) on browser then is OK ?

**Comment by hillz1** [comment]
yes, it's working fine with that url

**Comment by MajkiIT** [comment]
Try add this url to adblock settings - add manually filters

**Comment by reek** [comment]
Hi,

If you use uBlock, you have just to enable AakList
<code>options -> 3rd-party-filters</code>

**Comment by MajkiIT** [comment]
Yes, he on use ublock. My mistake.

**Comment by hillz1** [comment]
Thank you reek, if you don't mind please update the description so that they won't ask the same question again in the future :D

**Comment by reek** [comment]
@hillz1 
Ok

**Comment by reek** [comment]
@hillz1 
That you think of the new subscription page ?
http://reek.github.io/anti-adblock-killer/#fiterlist

**Comment by hillz1** [comment]
I still get the same error after getting this pop up:
![error](http://s22.postimg.org/kb4fjaqup/image.png)

**Comment by reek** [comment]
@hillz1 
I can not do anything about it because uBlock does not support the protocol.<code>abp</code>
But now there are the statement to add the list.

**Comment by reek** [comment]
@hillz1 
I have also addeda note
https://github.com/reek/anti-adblock-killer#step-2-filterlist
