### ISSUE TITLE
hayhaytv.vn

### ISSUE THREAD

**Issue by klord9x** [reek/anti-adblock-killer#621]
http://www.hayhaytv.vn/

http://imgur.com/delete/jb59FN244wDEYwY

Google Chrome
Tampermonkey
Adblock Plus

**Comment by reek** [comment]
HI,

I have this message "HayHayTV đang bảo trì. Xin các bạn vui lòng trở lại sau.
Xin lỗi vì sự bất tiện này!"

**Comment by MajkiIT** [comment]
This page is online. I don't see any notification.
