### ISSUE TITLE
shippuden.tv

### ISSUE THREAD

**Issue by alex306** [reek/anti-adblock-killer#622]
http://shippuden.tv/414-sub-espanol.html
http://imgur.com/reAydar
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by alexander255** [comment]
Solution filters:

@@||shippuden.tv/ads.xml
@@||shippuden.tv/gkplugins_license.swf

**Comment by alex306** [comment]
Thank you very much! It worked perfectly. Have a nice day bro!

**Comment by reek** [comment]
@alexander255 
Thanks for rules :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
