### ISSUE TITLE
sharefreeall.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#623]
Hi, 
anti-adblock on `http://sharefreeall.com/niche/mac-osx-yosemite/best-download-manager-for-mac/`

`sharefreeall.com#@##adsense`

![sharefreeall](https://cloud.githubusercontent.com/assets/1873139/10119600/2e23c3d0-6492-11e5-9182-dc5b986e719b.png)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
