### ISSUE TITLE
exashare.com

### ISSUE THREAD

**Issue by ThePierrezou** [reek/anti-adblock-killer#624]
Hi,
http://exashare.com/galw2ge2kzsv
The video disappears and it says "l Bloquer la pub c'est bloquer les revenus du site pour payer les serveur"

Opera 32 bits

Violentmonkey

UblockO
(with 
-ublock filters
-ublock filters badware risks
-ublock filters privacy
-ublock filters unbreak
-Adblock Warning Removal List‎
-Anti-Adblock Killer | Reek
-EasyList
-Peter Lowe’s Ad server list‎
-Basic tracking list by Disconnect‎
-EasyPrivacy‎
-Fanboy’s Enhanced Tracking List‎
-Fanboy’s Annoyance List
-Dan Pollock’s hosts file
-MVPS HOSTS
-EU: Prebake - Filter Obtrusive Cookie Notices‎
-FRA: EasyList Liste FR)

(btw i have your anti adblock killer user script on violentmonkey, and the list on ublockO, is having the script is necessary ?)

<pre>

window.addEventListener("load", function(){
  var iframe = document.createElement("iframe");
  iframe.height = "1px";
  iframe.width = "1px";
  iframe.frameBorder = 0;
  iframe.id = "ads-text-iframe";
  iframe.src = "http://dowed.info/ads.html";
            
  document.body.appendChild(iframe);
  
  setTimeout(function(){
    var iframe = document.getElementById("ads-text-iframe");
    if(iframe.style.display == "none" || iframe.style.display == "hidden" || iframe.style.visibility == "hidden" || iframe.offsetHeight == 0)
    {
	  console.log('adblock kayen weld ladina');
	  $('.PubBas').html("<div style='font-size:20px;color:#fff;font-weight:bold;background-color:#B9122B;font-size: 15px; font-weight: bold; text-align:center; padding-top:30px; line-height: 35px'><img src=\"http://youwatch.org/images2/dfdyt.png\" height=\"90%\" width=\"90%\"><br /><small>l Bloquer la pub c\'est bloquer les revenus du site pour payer les serveur </small></div>");
      jwplayer().stop();
	  iframe.remove();
	  jwplayer().remove();
      if(typeof ga !== 'undefined') 
      {
        ga('send', 'event', 'Adblock', 'Yes', {'nonInteraction': 1}); 
      }
      else if(typeof _gaq !== 'undefined')
      {
        _gaq.push(['_trackEvent', 'Adblock', 'Yes', undefined, undefined, true]);
      }
    }
  }, 15000);
}, false);

/*
$('document').ready(function(){
	setTimeout('gwsyty()', 15000);
});*/
function gwsyty() {
	//ChyckAxImage($('#swCheck1'));
	//ChyckAxImage($('#swCheck2'));
	//ChyckAxImage($('#swCheck3'));
	console.log('executed script 2');
	//if (Gyrdc) {
	//if (document.getElementById('ads_bottom') == null) {
	//if(iframe.style.display == "none" || iframe.style.display == "hidden" || iframe.style.visibility == "hidden" || iframe.offsetHeight == 0) {
	//	$('.PubBas').html("<div style='font-size:20px;color:#fff;font-weight:bold;background-color:#B9122B;font-size: 15px; font-weight: bold; text-align:center; padding-top:30px; line-height: 35px'><img src=\"http://4.bp.blogspot.com/-3W69PiJh7U0/VFnmVUjb5lI/AAAAAAAAAJs/W08cXeRFXuA/s1600/Disable%2BAdblock.png\" height=\"90%\" width=\"90%\"><br /><small>l Bloquer la pub c\'est bloquer les revenus du site pour payer les serveur </small></div>");
	//	console.log('adblock kayen weld ladina');
	//	jwplayer().stop();
	//	jwplayer().remove();
	//	}
}

</pre>

**Comment by reek** [comment]
Hi

They even changed their system, I will try to fix it

You should instead use TamperMonkey

**Comment by ThePierrezou** [comment]
Ok, thanks.
Tampermonkey is only on beta for opera, and it's not updated since some month, and i'm too lazy to do manual update, then I use violentmonkey, and it seems to works well.

**Comment by reek** [comment]
The last time I tested Aak on Opera only TamperMonkey worked, if you tell me that ViolentMonkey works well, do as if I had said nothing.

Once I'd found a solution to exashare I would test on ViolentMonkey and TamperMonkey, just to be sure.

**Comment by ThePierrezou** [comment]
Ok, thank you very much for your work.

**Comment by Watilin** [comment]
This is a fix I successfully tested with GreaseMonkey and TamperMonkey.

For Opera/ViolentMonkey support I'm not sure, I don't know if the implementation supports all features used by the Aak script. If it doesn't, adaptation would require some work on the whole file, not only the Exashare part.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
