### ISSUE TITLE
sahadan.com

### ISSUE THREAD

**Issue by bkrucarci** [reek/anti-adblock-killer#630]
http://www.sahadan.com/adblocker.aspx
http://i.imgur.com/RezOGTa.png
Google Chrome
uBlock Origin

<pre>
    $(document).ready(function () {
        if ((typeof (AdmostClient) === 'undefined' || typeof (_amw1) === 'undefined') && window.location.href.indexOf("adblocker.aspx") == -1) {
            window.location.href = "http://www.sahadan.com/adblocker.aspx";
        }
    });
</pre>
Easylist + Peter Lowe + Anti-Adblock Killer

**Comment by MajkiIT** [comment]
For me solution is @@|http://go.admost.com/adx/js/admost.js$script,domain=sahadan.com

**Comment by reek** [comment]
@MajkiIT 
thank you, but I will add a solution with the script

**Comment by reek** [comment]
@bkrucarci 

Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
