### ISSUE TITLE
wpworld.pl,windowsowo.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#631]
http://i.imgur.com/NXJyxYS.png
http://windowsowo.pl/microsoft-excel-swietuje-30-urodziny/
https://wpworld.pl/45573/aplikacja-vine-dla-windows-phone-zaktualizowana/

solution wpworld.pl,windowsowo.pl#@##adBanner

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
