### ISSUE TITLE
dziennikwschodni.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#633]
http://www.dziennikwschodni.pl/wypadki/
http://i.imgur.com/K47HK8e.png

solution
dziennikwschodni.pl#@#.adholder

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

http://reek.github.io/anti-adblock-killer/
https://twitter.com/antiadbkiller
