### ISSUE TITLE
freeskier.com

### ISSUE THREAD

**Issue by gorhill** [reek/anti-adblock-killer#639]
Video widget from Vimeo is hidden on the page, unless uBlock Origin is disabled.

- http://freeskier.com/videos/new-footage-of-jp-auclair-and-andreas-fransson-released-one-year-after-their-passing
- http://imgur.com/eHkGPQZ (should be <http://imgur.com/w8j7hMk>)
- Chromium/Chrome
- Tampermonkey
- uBlock Origin
- EasyList + EasyPrivacy + [Liste FR](https://easylist-downloads.adblockplus.org/liste_fr.txt)

Workaround:
- Filters:
    - `blockadblock.js$script,domain=freeskier.com`
    - `freeskier.com###adb-enabled`
    - `freeskier.com#@##adb-not-enabled`
- Script:
    - https://greasyfork.org/en/scripts/12831-freeskier-com-anti-blockadblock-js

**Edited** as per comment below.

**Comment by reek** [comment]
Hi,

Thank you good job :+1: 

PS: Congratulations for uBlock Origin

Regards
Reek

**Comment by gorhill** [comment]
By the way, I decided to see what would happen without Liste FR (for some reasons I had in mind the user used this but in retrospect I don't think it is the case), and the above solution does not work completely with just EasyList alone. Here is what is _also_ needed:

- `blockadblock.js$script,domain=freeskier.com`
- `freeskier.com###adb-enabled`

**Comment by reek** [comment]
No need second rule, because AakList already blocked <code>blockadblock.js</code>

**Comment by reek** [comment]
Anyway, I'll add the two solutions :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
