### ISSUE TITLE
tvsierpc.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#640]
http://tvsierpc.pl/87,752-xiii_sesja_rady_powiatu_sierpeckiego.html
http://i.imgur.com/Ems7scq.png

@@||tvsierpc.pl/media/videoads/FILMY/*.mp4$object,image,domain=tvsierpc.pl

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
