### ISSUE TITLE
enlacespremium.biz

### ISSUE THREAD

**Issue by admax37** [reek/anti-adblock-killer#643]
Hi there.
This site blocks anti-adblock-killer.
The message returned is: http://tiny-paste.com/public/images/adblock.png

**Comment by MajkiIT** [comment]
for me, solution is
@@|http://bajaenlaces.com/adblock.js$script

**Comment by reek** [comment]
@MajkiIT 
Thanks again :smile:

**Comment by MajkiIT** [comment]
No problem. For me it's good fun.

**Comment by admax37** [comment]
Thanks for your replay MajkiIT.
It work's great !
What about miips.net. do you now how to bypasser?

**Comment by MajkiIT** [comment]
What is bad in this page miips.net.?

**Comment by admax37** [comment]
Hi there.

Is it possible to bypasser this site?

http://miips.net/b/A2.php

2015-10-05 20:53 GMT+01:00 Maciej M. <notifications@github.com>:

**Comment by MajkiIT** [comment]
If I disable adblock i see the same element. What you want to see?

**Comment by reek** [comment]
@admax37 
Report it to EasyList

**Comment by admax37** [comment]
My bad.

This site http://bajaenlaces.com/index.php  is a premium link generator.
When we tray to generate the link we must click in some ad in this window
http://miips.net/b/A2.php.

The problem is that I need to turn off the adblock to see the ad, I get not
one but hundreds.

Thank you in advance.




2015-10-05 21:58 GMT+01:00 reek <notifications@github.com>:

**Comment by reek** [comment]
@admax37 
I would try to create another userscript to bypass this problem

**Comment by admax37** [comment]
thank you

2015-10-05 23:11 GMT+01:00 reek <notifications@github.com>:

**Comment by reek** [comment]
@admax37 
Click on Raw for install
https://gist.github.com/reek/86af4b7376e5a8f9660a

**Comment by admax37** [comment]
Hi reek.
How does it work?
I can't make it work.
Thank you

2015-10-06 1:18 GMT+01:00 reek <notifications@github.com>:

**Comment by reek** [comment]
@admax37 
Your configuration ? (http://reek.github.io/anti-adblock-killer/#settings)

**Comment by admax37** [comment]
Did you try to download any file?
The same in chrome.

2015-10-06 17:00 GMT+01:00 reek <notifications@github.com>:

**Comment by admax37** [comment]
and a print screen

2015-10-06 17:55 GMT+01:00 joao sousa <paralixo42@gmail.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
