### ISSUE TITLE
eveskunk.com

### ISSUE THREAD

**Issue by Ethaks** [reek/anti-adblock-killer#645]
https://eveskunk.com/s
http://imgur.com/eEqVVeT
Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by MajkiIT** [comment]
Try this solution ==> 
@@|https://eveskunk.com/ad/300x250/ads/$xmlhttprequest,domain=eveskunk.com

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
