### ISSUE TITLE
jetradar.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#647]
http://www.jetradar.pl/
http://i.imgur.com/UhQF4ZX.png

@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=www.jetradar.pl
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$script,domain=www.jetradar.pl
jetradar.pl#@#.ad_container

or 
jetradar.pl##.ng-scope.no_adblock_wrapper

**Comment by reek** [comment]
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
