### ISSUE TITLE
hostuje.net

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#649]
http://hostuje.net/file.php?id=30cc2c360d2b272cab997ac92f2797bc
http://imgur.com/eJTuKZQ

Mozilla Firefox 41.0.1
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MajkiIT** [comment]
Update filters to current version.

I wrote it https://github.com/reek/anti-adblock-killer/issues/642
