### ISSUE TITLE
rek.www.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#650]
Reek on yours filters is included rule @@||rek.www.wp.pl/pliki/*_*.js$script (example of file http://rek.www.wp.pl/pliki/232410_201510071010.js) .

This rule causes some problems on pages like money.pl - see blank area (div adv* with random numbers).

I start testing what happen if I block it by rule ||rek.www.wp.pl/pliki/*_*.js$important . In a while I write to you that this rule @@||rek.www.wp.pl/pliki/*_*.js$script is important.

**Comment by reek** [comment]
ok, I'll delete this rule

**Comment by MajkiIT** [comment]
Reek if you can, please remove this rule @@||rek.www.wp.pl/pliki/_.js$script from your filters. If they problems I will add rule to official polish rules (https://www.certyficate.it/adblock/adblock.txt) .

**Comment by reek** [comment]
Done :smile:
