### ISSUE TITLE
proaudioz2.audio/

### ISSUE THREAD

**Issue by ECriew1928** [reek/anti-adblock-killer#651]
http://proaudioz2.audio/
http://imgur.com/67Yy4zp
Google chrome
Tampermonkey
uBlock Origin
AakList (Anti-Adblock Killer)

**Comment by MajkiIT** [comment]
Try this rule:
@@|http://advert.popunder.ru/banners/advert.php$image,subdocument,domain=proaudioz2.audio

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
