### ISSUE TITLE
al.ly

### ISSUE THREAD

**Issue by petarster** [reek/anti-adblock-killer#652]
please can somone help me with

http://al.ly/ECx3

http://i.imgur.com/7RZigyM.png
http://al.ly

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
my solution 
@@|http://al.ly/Advertiser.js$script,domain=al.ly
and later
al.ly#@#.text_ads

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
