### ISSUE TITLE
4shared.com

### ISSUE THREAD

**Issue by rayman89** [reek/anti-adblock-killer#654]
4shared.com makes you wait 1k seconds instead of 20 if it detects that you are using adblock (in my case ublock origin).
You need a free account to be able to download files from it.

Example link http://www.4shared.com/get/iqU_El9Mba/Kevin_MacLeod_Sneaky_Snitch_Ro.html

**Comment by MajkiIT** [comment]
Hi, If you think on this alert then add this rule 
@@||www.4shared.com/show_ad_.xml$stylesheet,domain=4shared.com

![4share](https://cloud.githubusercontent.com/assets/11302675/10388462/6b47fa60-6e6a-11e5-866b-ca200aaf2fb0.png)

**Comment by MajkiIT** [comment]
Next time add issue by this Report-Guide https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by rayman89** [comment]
Thanks for trying to help but that doesn't work for me.  I've read the report guide pic wasn't necessary in this case IMO.

**Comment by reek** [comment]
@rayman89 
The rule provided by MajkiIT is good.

Tested and working with Chrome + uBlock

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
