### ISSUE TITLE
freedisc.pl

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#656]
http://freedisc.pl/search/all/przyjaciele
http://imgur.com/TNksHkr  <--search not working blank page
http://imgur.com/XMpaDVL   <---search working 30 sec ad in the middle 

example link:
http://freedisc.pl/Viola_up,f-613303,przyjaciele-friends-s06e02-pl-480p-bdrip-xvid-ac3-elite-avi

Mozilla Firefox 41.0.1
 Greasemonkey
 uBlock Origin reg filters
 AakList
 POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

this is maybe more for MajkiIT then Reek the search on the website is not working correctly and if it works then 30 sec ad plays in front off all videos. don't know if its my combination of filters or website change something. but something for sure is broken

**Comment by MajkiIT** [comment]
@xxcriticxx Thanks tor your issue.

For this problem http://imgur.com/TNksHkr  ==> update filters to minimum version 2015101101

For adblock detection solution: @@|http://webshark.pl/adserver/*/main_script.js?advertise_check=1$script,domain=freedisc.pl

Ads on movie: ||ocs-pl.oktawave.com/v1/AUTH_*/Reklamy/$object-subrequest,domain=freedisc.pl

**Comment by MajkiIT** [comment]
@xxcriticxx all of this filters I added to polish filters, so just update filters.

**Comment by xxcriticxx** [comment]
MajkiIT thx for help

I reset to default settings my ublock origin i only added  Anti-Adblock Killer | Reek‎ + POL filters. i added your solution and part for vid adds and i get still blank page (http://imgur.com/TNksHkr)

what else can i check?

**Comment by MajkiIT** [comment]
Update polish filters. I added exclude for this problem.

**Comment by xxcriticxx** [comment]
i did update all i am at Version: 2015101102 for POL filters still get blank like the search glass is not working

**Comment by MajkiIT** [comment]
Can you export settings of ublock?

**Comment by xxcriticxx** [comment]
MajkiIT i fixed it 

i  restore default settings in both in firefox and ublock. install all again and it works. thx for the fix

**Comment by MajkiIT** [comment]
Ok thanks for information.

**Comment by reek** [comment]
@MajkiIT 
thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
