### ISSUE TITLE
player.pl - better quality

### ISSUE THREAD

**Issue by starhel** [reek/anti-adblock-killer#658]
Please consider changing quality for player.pl from standard to HD. To do this you have to change
```javascript
var standardURL = o.item.videos.main.video_content[0].url;
```
to
```javascript
var standardURL = o.item.videos.main.video_content[1].url;
```

Another qualities if you can add choosing them for user:
```
0 - standard
1 - HD
2 - very high
3 - high
4 - medium
5 - low
6 - very low
```

**Comment by reek** [comment]
Hi,

Ok, I'll add an option to enable HD quality.

**Comment by reek** [comment]
Option added
http://reek.github.io/anti-adblock-killer/#settings
