### ISSUE TITLE
gamestar.de

### ISSUE THREAD

**Issue by loltroll123** [reek/anti-adblock-killer#660]
http://www.gamestar.de/videos/specials,20/star-wars-battlefront,85459.html
http://imgur.com/rcBjAMs
Chrome
Tampermonkey
Adblock Plus

also tried with adguard & Disconnect.

Disconnect prohibits loading ad scripts for 2 secs. Then they appear anyways.

Thanks for your help! They even make worse videos for adblock users...

**Comment by MajkiIT** [comment]
What filters are you using?

**Comment by MajkiIT** [comment]
To disable adblock notification use this rule 
@@|http://www.gamestar.de/img/aktionen/_ad2.cfm?d=$image,domain=gamestar.de

But if you using AAK scripts there aren't any notofications and ads on movie.

**Comment by loltroll123** [comment]
Hello,

thanks for your reply. 

I downloaded Adblock Plus + the script you provided here https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek

I added your rule to the scripts on adblock. Unfortuantely I still have these adds.

Anything I forgot? Sorry, still a noob with this.

**Comment by MajkiIT** [comment]
do you have adblock filters added to Adblock?

**Comment by loltroll123** [comment]
I have these installed:

http://imgur.com/tzj4J1z

**Comment by MajkiIT** [comment]
You don't have AAK Filters https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

**Comment by loltroll123** [comment]
Thanks for your reply.

Where do I add these?

I just copy & paste it to "Add own Filters". Unfortunately the adds are still there.

Even with the @@|http://www.gamestar.de/img/aktionen/_ad2.cfm?d=$image,domain=gamestar.de added to this.

Or do I have to install these AAK Filters on a diffrent way?

Thanks very much for your time, patience and help!

**Comment by MajkiIT** [comment]
try add AAK Filter by subscribe on this page http://reeksite.com/anti-adblock-killer/#fiterlist

This rule add in own filters and whitelist filters

**Comment by loltroll123** [comment]
Thanks, I added it.. Unfortunately their anti Adblock seems quite good.

Adds still there.

**Comment by MajkiIT** [comment]
I make the same configuration like you have and if I have enable adblock I don't see ads. If I disable adblock then I see ads.

**Comment by loltroll123** [comment]
Weird... I just did what you said and subscribed to it. Anything else I need?

**Comment by MajkiIT** [comment]
My configuration
![adblock26](https://cloud.githubusercontent.com/assets/11302675/10418988/e292e7b4-7069-11e5-8f54-a6c9b8f19b23.png)

**Comment by loltroll123** [comment]
May I ask what Adblock you are using?

**Comment by MajkiIT** [comment]
2.6.11 and new uBlock Origin

**Comment by loltroll123** [comment]
Well this is weird, if I take all Adblockers OFF and just run your script, then everything works fine... No banners, no video adds before my videos.... 

it confuses me a bit

**Comment by loltroll123** [comment]
I figured out that on this URL "Easylist" is the problem. If you activate it, they play annoying adds and videos. If you take "Easylist" off, everything is fine.

**Comment by MajkiIT** [comment]
Can you try uBlock?

**Comment by loltroll123** [comment]
I switched to uBlock - same result. Easylist on, adds appearing, Easylist off, adds gone with your script.

**Comment by MajkiIT** [comment]
export please adblock settings I will see.

**Comment by loltroll123** [comment]
You mean doing the backup log for uBlock?

{
  "timeStamp": 1444668942548,
  "version": "1.2.0",
  "userSettings": {
    "advancedUserEnabled": false,
    "autoUpdate": true,
    "collapseBlocked": true,
    "colorBlindFriendly": false,
    "contextMenuEnabled": true,
    "dynamicFilteringEnabled": false,
    "experimentalEnabled": false,
    "externalLists": "! Examples:\n! https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt\n! https://easylist-downloads.adblockplus.org/fb_annoyances_sidebar.txt\n! https://easylist-downloads.adblockplus.org/fb_annoyances_newsfeed.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_full.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_comments.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_suggestions.txt\n! https://easylist-downloads.adblockplus.org/yt_annoyances_other.txt\nhttps://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt\nhttps://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt",
    "firewallPaneMinimized": true,
    "hyperlinkAuditingDisabled": true,
    "parseAllABPHideFilters": true,
    "prefetchingDisabled": true,
    "requestLogMaxEntries": 1000,
    "showIconBadge": true,
    "cloudStorageEnabled": false,
    "webrtcIPAddressHidden": false
  },
  "filterLists": {
    "https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "title": "AakList (Anti-Adblock Killer)",
      "group": "custom",
      "external": true,
      "off": false,
      "entryCount": 1241,
      "entryUsedCount": 0
    },
    "https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer-filters.txt": {
      "title": "",
      "group": "custom",
      "external": true,
      "off": false,
      "entryCount": 0,
      "entryUsedCount": 0
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt": {
      "title": "EasyList",
      "group": "ads",
      "homeURL": "https://easylist-downloads.adblockplus.org/easylist.txt",
      "supportURL": "https://forums.lanik.us/",
      "off": true,
      "entryCount": 58358,
      "entryUsedCount": 58319
    },
    "assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt": {
      "title": "EasyPrivacy",
      "group": "privacy",
      "homeURL": "https://easylist-downloads.adblockplus.org/easyprivacy.txt",
      "supportURL": "https://forums.lanik.us/",
      "off": false,
      "entryCount": 10485,
      "entryUsedCount": 10464
    },
    "assets/thirdparties/mirror1.malwaredomains.com/files/justdomains": {
      "title": "Malware domains",
      "group": "malware",
      "homeURL": "http://malwaredomains.lehigh.edu/files/justdomains",
      "supportURL": "http://www.malwaredomains.com/",
      "off": false,
      "entryCount": 11387,
      "entryUsedCount": 11318
    },
    "assets/thirdparties/pgl.yoyo.org/as/serverlist": {
      "title": "Peter Lowe’s Ad server list",
      "group": "ads",
      "homeURL": "http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext",
      "supportURL": "http://pgl.yoyo.org/adservers/",
      "off": true,
      "entryCount": 2439,
      "entryUsedCount": 2438
    },
    "assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt": {
      "title": "Malware Domain List",
      "group": "malware",
      "homeURL": "http://www.malwaredomainlist.com/hostslist/hosts.txt",
      "off": false,
      "entryCount": 1488,
      "entryUsedCount": 1488
    },
    "https://easylist-downloads.adblockplus.org/easylistgermany.txt": {
      "off": false,
      "title": "DEU: EasyList Germany",
      "group": "regions",
      "supportURL": "https://forums.lanik.us/viewforum.php?f=90",
      "entryCount": 9004,
      "entryUsedCount": 9004
    },
    "https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt": {
      "off": false,
      "title": "Anti-Adblock Killer | Reek",
      "group": "ads",
      "supportURL": "https://github.com/reek/anti-adblock-killer",
      "instructionURL": "https://github.com/reek/anti-adblock-killer#instruction",
      "entryCount": 1241,
      "entryUsedCount": 1240
    },
    "https://www.fanboy.co.nz/enhancedstats.txt": {
      "off": false,
      "title": "Fanboy’s Enhanced Tracking List",
      "group": "privacy",
      "supportURL": "https://forums.lanik.us/",
      "entryCount": 904,
      "entryUsedCount": 903
    }
  },
  "netWhitelist": "about-scheme\nbehind-the-scene\nchrome-extension-scheme\nchrome-scheme\nloopconversation.about-scheme\nopera-scheme",
  "dynamicFilteringString": "",
  "urlFilteringString": "",
  "hostnameSwitchesString": "",
  "userFilters": ""
}

**Comment by MajkiIT** [comment]
in file please :D

**Comment by loltroll123** [comment]
http://www.file-upload.net/download-10969261/my-ublock-backup_12.10.2015_18-55-42.txt.html

**Comment by MajkiIT** [comment]
import this, later update all filters and refresh page by CTRL+F5
https://www.dropbox.com/s/ohne5ad3g1y4vfr/ublock-kopia-zapasowa_12.10.2015%2C_19_39_49.txt?dl=0

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#help

**Comment by loltroll123** [comment]
Thanks for your dropbox link. Still the same, if I turn Easylist off, no adds. If Easylist is on, there are adds.

I probably just take Easylist away

**Comment by MajkiIT** [comment]
I tested it on 2 PC and I don't see ads.

**Comment by loltroll123** [comment]
mhh thats weird, just tried it with my new laptop. There are also adds with easylist.

Is there any chance they save that I used an adblock before to my ip or something like that? 

I just cant understand why it works without easylist haha

**Comment by MajkiIT** [comment]
update easylist and try.

**Comment by loltroll123** [comment]
nope, still adds with easylist. No adds without it.

But it is only the "normal" easylist. If I use "easylist Germany" it works.

**Comment by MajkiIT** [comment]
ok. Use easylist Germany.

**Comment by loltroll123** [comment]
ok, thanks a lot for your help. Im using a workarround for the website not working.

Using 2 adblockers... 1 with the easylist active for most of the websites and one without easylist.

I add an acception on the first adblock to not block adds for "gamestar.de" haha.

works...

Thanks a lot for your patience & help.

**Comment by frumpymoons** [comment]
Have exactly the same problem. Easylist on = ads, Easylist off = no ads.
Example:
![](http://img4host.net/upload/1615015352877ad1d4739.png)
