### ISSUE TITLE
Anti-adblock killer Reek (Google search bar on top right / conflict)

### ISSUE THREAD

**Issue by antipubweb-org** [reek/anti-adblock-killer#661]
anti-Adblock https://www.google.com/search?q=anti+adblock+killer&ie=utf-8&oe=utf-8
http://i.imgur.com/eZzyik4.jpg
http://i.imgur.com/AsGaNu9.jpg   http://i.imgur.com/4luKWT4.jpg   http://i.imgur.com/i9HCyvb.jpg
Mozzilla Firefox 41.0.1
Greasemonkey
Adblock Plus...
EasyList FR + antipubfirefox.org/antipub/antipubfirefox-adblocklist
Hello!
I can notice a slight conflict problem between your Anti-Adblock Killer Reek and research with Google search bar on top right of the Google page with Firefox 41.0.1. With your script Anti-adblock killer activated, and research with Google search bar (on top right) returned no result. By cons with the central search bar everything is ok. (see pictures attached). Thank you to let me know if the problem can be solved, please. Meanwhile, I send you my best regards and thank you for your excellent script. See you soon!

**Comment by reek** [comment]
HI,

**Comment by antipubweb-org** [comment]
HI !!
Very good !! thanks for the information :-)

**Comment by lewisje** [comment]
I've noticed something similar in Chrome, but that's whether using the omnibox search or going to Google's website first and using its own search box, and it doesn't even happen with all search terms, but consistently with a given term; I have discovered that it's the work of the Anti-Adblock Killer script (originally I thought it was an overzealous uBlock Origin filter, but I still got this problem when I disabled the extension).

**Comment by congma** [comment]
I also noticed something similar.  If you search for keywords like

* block ad block
* block antiadblock
* ad block block
* block block block ad
* kill adblock block
* high-order adblock
* recursive ad block
* ad remove block
* remove ad block
* ...

on Google, you get blank results.
But if you search for

* block block
* block block ad
* adblock kill block

you get the results.

Also, `" "`-quoted queries are not affected (or so it seems).

**Comment by banther7** [comment]
i am getting this issue as well. i have to disable greasemonkey to get it back

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by antipubweb-org** [comment]
HI !
Good job Reek ! Thank you a lot :-)
