### ISSUE TITLE
sme.sk

### ISSUE THREAD

**Issue by co5mo** [reek/anti-adblock-killer#662]
http://komentare.sme.sk/c/8031314/statisice-katolikov-si-zelaju-aby-papez-v-oblasti-ucenia-o-rodine-nic-nemenil.html

http://i.imgur.com/aufZ2bL.png
Chrome
uBlock Origin
EasyList + AakList

the message appears after you accept cookies and possibly reload the same page

**Comment by MajkiIT** [comment]
Solution komentare.sme.sk###js-top-info-bar-wrapper

**Comment by co5mo** [comment]
thanks @MajkiIT

**Comment by reek** [comment]
@MajkiIT 
thanks for rule

**Comment by MajkiIT** [comment]
No problem

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
