### ISSUE TITLE
efilmy.tv

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#663]
http://www.efilmy.tv/film,26483,Kraina-jutra-2015-Dubbing-PL.html

http://imgur.com/tlh4XUR  <---- captcha before movie starts
http://imgur.com/77EAco5  <----- ads play before movie starts 

Mozilla Firefox 41.0.1
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

before movie starts there is captcha and ads that play after that movie starts. looking for way to bypass all and go directly to movie.

**Comment by reek** [comment]
HI

Report it to PolishList or EasyList

**Comment by F4z** [comment]
To block ads before movies you can use this rule - <code>efilmy.tv##.addbackground</code>

**Comment by MajkiIT** [comment]
@xxcriticxx @reek I update polish filters

@F4z Thanks

**Comment by xxcriticxx** [comment]
reek that list sucks

**Comment by MajkiIT** [comment]
Polishlist is sucks?

**Comment by xxcriticxx** [comment]
MajkiIT i just use your list for PL filters 

now how to i force update?

**Comment by MajkiIT** [comment]
To the best protection you must use EAsyList+ PL filters . 

Open this list on web browser (https://www.certyficate.it/adblock/adblock.txt) . You should have version 2015101302 . If you see earlier press few times F5 . Next go to ublock settings ==> external filters ==> find polish filters on list and click clear cache and later apply.

**Comment by xxcriticxx** [comment]
easylist us filters + pl filters? right

**Comment by MajkiIT** [comment]
https://easylist-downloads.adblockplus.org/easylist.txt Included on uBlock
