### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by danackerson** [reek/anti-adblock-killer#665]
http://www.bild.de/news/startseite/news/news-home-16804530.bild.html

<img width="1018" alt="screen shot 2015-10-13 at 18 06 14" src="https://cloud.githubusercontent.com/assets/177846/10460561/24703134-71d5-11e5-8000-454e6692c4b5.png">

Mozilla Firefox
Greasemonkey
Adblock Plus
AakList

**Comment by alexander255** [comment]
Duplicate of #664. Yeah! :-)
