### ISSUE TITLE
topfilmz.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#667]
http://topfilmz.com/6207/the-gift-2015-hc-hdrip-720p-x264/

http://imgur.com/QiWNONP

Mozilla Firefox 41.0.1
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MajkiIT** [comment]
Solution
topfilmz.com#@##adsense

**Comment by reek** [comment]
@MajkiIT 
Thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
