### ISSUE TITLE
pastebin.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#669]
http://pastebin.com/DzhWmy2a

http://imgur.com/Tdciuba

Mozilla Firefox 41.0.1
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MajkiIT** [comment]
Solution 1 use AAK scripts
Solution 2 pastebin.com#@#.text_ads
Solution 3 pastebin.com###abrpm

**Comment by xxcriticxx** [comment]
sorry i forgot to install AAK scripts
