### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by frumpymoons** [reek/anti-adblock-killer#672]
http://www.ghacks.net/
http://i.imgur.com/faBOpOO.png

Chrome Version 46.0.2490.71 m (64-bit)
Tampermonkey 3.11
uBlock Origin v1.2.0

This problem occurs if you have AAKlist on but Easylist off.

**Comment by MajkiIT** [comment]
solution

@@||ghacks.net/wp-content/plugins/bwp-minify/*$stylesheet,domain=ghacks.net

**Comment by reek** [comment]
@MajkiIT 
Thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
