### ISSUE TITLE
shinden.pl

### ISSUE THREAD

**Issue by Smokk** [reek/anti-adblock-killer#673]
http://shinden.pl/external-video/3049-luckystar/view/29646
http://imgbox.com/qHCreSPT
Google Chrome
Tampermonkey
AdBlock 2.42.1
Acceptable Ads + EasyList + Polish + Russian + List of removing warning about AdBlock

Note: ABP icons shoud be buttons instead

**Comment by MajkiIT** [comment]
Solution shinden.pl#@#.AD-RC-300x250

You don't use AAK filters. 

PS I think you should use polish list witch is supported. Polish list witch is implemented on Adblock is old. Use this link to add filters https://www.certyficate.it/adblock/ .

**Comment by reek** [comment]
@MajkiIT 
thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Smokk** [comment]
Now it wokrs. Thank you guys. :)

**Comment by dthlfwp** [comment]
it doesn't work again, uBlock default+ Polish list.
