### ISSUE TITLE
kinoman.tv

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#676]
http://kinoman.tv/arrow-2012/s04e02/the-candidate-eng-0
http://imgur.com/BsZtIR8

Mozilla Firefox 41.0.1
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MajkiIT** [comment]
I don't see adblock alert or any notofication with adblock.

**Comment by reek** [comment]
add rule <code>kinoman.tv##IMG[src="http://static.kinoman.tv/assets/img/vip-info.png?v"]</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
