### ISSUE TITLE
MultiUp.org

### ISSUE THREAD

**Issue by Brandit36** [reek/anti-adblock-killer#677]
Hello.
1. http://www.multiup.org/download/e3cdec7cb1420d18fc367e64466be52c/DiRT_Complete_Edition_BLUS30975.part1.rar
2. https://i.imgur.com/gBhvLsg.png
3. Google Chrome 48.0.2535.0 dev-m
4. Tampermonkey
5. Ublock Origin v1.2.0
6. EasyList, AakList, Peter Lowe’s Ad server list‎, Adblock Warning Removal List

The message appears again. Please fix.

**Comment by MajkiIT** [comment]
solution
@@|http://195.154.75.196/ads.gif$image,domain=multiup.org

**Comment by Brandit36** [comment]
Thanks, really ! :)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Brandit36** [comment]
The message appears again ...

**Comment by MajkiIT** [comment]
Try this. This time I use universal rule.
@@||195.154.75.196/ad$image,domain=multiup.org

**Comment by Brandit36** [comment]
Thanks again !

**Comment by reek** [comment]
@MajkiIT 
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Brandit36** [comment]
They are leathery. Almost a month later, the message returns each time. They have to change something. The message is once again income.

**Comment by MajkiIT** [comment]
@@||195.154.75.196/pop.js$script,domain=multiup.org

**Comment by Brandit36** [comment]
Thank you very much for your work!

**Comment by MajkiIT** [comment]
No problem.

**Comment by reek** [comment]
@MajkiIT  :+1:

**Comment by MajkiIT** [comment]
@reek 
Maybe better rule will be @@||195.154.75.196/,domain=multiup.org

**Comment by p1nkyy** [comment]
Where to put this line?

**Comment by josereyes53** [comment]
They changed it again.
@@||195.154.104.153/$domain=multiup.org works for me now.

**Comment by reek** [comment]
@josereyes53 
Ok, I'll change it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Watilin** [comment]
Hi, long time I didn't pass by :)

I've had my own snippet for some time (around a month or two) and didn't need to change it. Exception rules-based solution tend to not last. I'm not fond of those.

Anyway, here's my code:
```javascript
var links = document.querySelectorAll("a.btn[style]");
for (var i = 0; i < links.length; i++) {
  if ("none" === links[i].style.display) links[i].style.display = "";
}

var buttons = document.querySelectorAll("button.detect");
for (i = 0; i < buttons.length; i++) {
  buttons[i].style.display = "none";
}
```

**Comment by reek** [comment]
@Watilin 
Glad to see you, I will add it as an alternative
