### ISSUE TITLE
javfor.me

### ISSUE THREAD

**Issue by Bluberius** [reek/anti-adblock-killer#678]
NSFW
http://javfor.me/89686.html
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList Germany + EasyList

Seems to only happen when switching to a different scene and after a few seconds.
To reproduce:
go to http://javfor.me/89686.html
click on the "watch online" button
click on "scene 1" (under video)
wait for ~10s
This happens: 
![2015-10-16 16 32 20](https://cloud.githubusercontent.com/assets/15158778/10544468/d2eca83c-7423-11e5-85a2-311cf5e89377.png)

Thanks

**Comment by MajkiIT** [comment]
try this
@@|http://js.juicyads.com/jac.js$script,domain=l1.jav4.me

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
@reek there are 2 scripts to detect adblock
At scene 2 is script @@||puhtml.com/7c/70/ab/$script,domain=l1.jav4.me

@Bluberius can you check it?

**Comment by reek** [comment]
@MajkiIT 
ok, I'll add this second rule

**Comment by MajkiIT** [comment]
Ok thanks... I check it on other PC

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
@reek on filters now is bug
you change rule from @@|http://js.juicyads.com/jac.js$script,domain=l1.jav4.me at @@|js.juicyads.com/jac.js$script,domain=l1.jav4.me . This rule should by @@||js.juicyads.com/jac.js$script,domain=l1.jav4.me

Of course it's my opinion.

**Comment by reek** [comment]
Actually, it's a mistake on my part, I will fix this, thank you

2015-10-21 21:35 GMT+02:00 Maciej M. <notifications@github.com>:

**Comment by reek** [comment]
Done !

2015-10-21 21:44 GMT+02:00 reek <reekside@gmail.com>:

**Comment by MajkiIT** [comment]
thank's  and I'm sorry for the trouble.
