### ISSUE TITLE
manga-sanctuary.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#681]
Hi, 
on `http://www.manga-sanctuary.com/`

```
@@||www.smartadserver.com/ac?pgid=$script,domain=manga-sanctuary.com
```

![adblockdetected manga-sanctuary.com](https://cloud.githubusercontent.com/assets/1873139/10559228/82fd216a-74e3-11e5-8442-3c43aef70d55.png)

Thank you!

**Comment by reek** [comment]
Thanks Med

**Comment by SMed79** [comment]
Changed :/ 
```
@@||www.smartadserver.com/config.js?$script,domain=manga-sanctuary.com
@@||r.sascdn.com/diff/js/smart.js$script,domain=manga-sanctuary.com
```

**Comment by reek** [comment]
Ok, thanks

2015-10-21 0:22 GMT+02:00 Med <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
