### ISSUE TITLE
vipleague.co

### ISSUE THREAD

**Issue by damnnative** [reek/anti-adblock-killer#682]
Link of the page: http://www.vipleague.co/
Screenshot: http://i.imgur.com/tslRjLC.png
Browser: Chrome
Script manager: Tampermonkey
Adblocker: UBlock Origin
Filterlists: Easylist, Easylist privacy, AakList, All UBlock lists, Peter's ad-server list, Warning removal list

Vipleague is detecting ad blockers again and is blocking videos instead of pages this time it seems. Hopefully you are able to circumvent this also.

**Comment by F4z** [comment]
Try this <code>@@||cache.zoomtv.me/includes/js/ads.js$script,domain=zoomtv.me</code>

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#instruction
