### ISSUE TITLE
channel4.com

### ISSUE THREAD

**Issue by loneswimmer** [reek/anti-adblock-killer#683]
http://www.channel4.com/programmes/drones-in-forbidden-zones/on-demand/61144-001
http://imgbox.com/0DfoCU6W
Mozilla Firefox
Greasemonkey
Adbock Plus
AakList

**Comment by reek** [comment]
No message for me

**Comment by loneswimmer** [comment]
Thanks for that -  did you sign in and try to play a programme?  What filter lists are you using?  Any info to help me worth this out would be much appreciated...cheers...

**Comment by loneswimmer** [comment]
Still can't get it to work - anyone have any ideas?

**Comment by reek** [comment]
No

**Comment by loneswimmer** [comment]
Did you try it?  Did it work for you?

**Comment by reek** [comment]
Try this rule
<code>@@||ak.http.anno.channel4.com^$object-subrequest</code>

**Comment by loneswimmer** [comment]
As in AdBlock > Filter Preferences > Customer Filters > Add Filter ?

If so, I still get "Adblock Software Alert" message from the website...

**Comment by reek** [comment]
Yes
