### ISSUE TITLE
"No update found." dialog is unecessary

### ISSUE THREAD

**Issue by xyzzy-xyzzy** [reek/anti-adblock-killer#684]
Periodically I've been seeing a dialog saying "No update found." in Firefox.  It took a little debugging to find out who was responsible for this and I discovered it was anti-adblock-killer.  Specifically it is displaying a dialog supplied by the following URL:

http://reek.github.io/anti-adblock-killer/notification.html#Tm8gdXBkYXRlIGZvdW5kLg==

Can something be done to prevent this dialog from being displayed (some kind of option maybe)?   I don't mind update checking, but I do mind being reminded of it (even if it does automatically time out).  An update actually being *required* maybe is one thing.  But being reminded that *nothing* needs to be updated is another and IMO unnecessary.

FWIW, I use [Add-on Update Checker](https://addons.mozilla.org/en-us/firefox/addon/addon-update-checker/) and I when scripts are updated on places like greasyfork.org it tells me updates are available.

Update:
By the way the reason I said it took a little debugging to find out who was displaying that dialog was because I don't always remember what icon goes with what addon, script, etc. (maybe I getting too old for this :-( )  So even if you don't agree with me about not displaying this dialog at least indicate *what* doesn't need to be updated (e.g., "**Anti-Adblock Killer** doesn't need updating").  Similarly for any other dialogs the script might display.

**Comment by reek** [comment]
http://reek.github.io/anti-adblock-killer/#settings
uncheck 'Check for newer versions.' and save

2015-10-19 2:10 GMT+02:00 xyzzy-xyzzy <notifications@github.com>:

**Comment by xyzzy-xyzzy** [comment]
Heh :-)  I never noticed that (settings) existed before.  Thanks. 

But I still think you should say *who* is posting those dialogs **in** the dialogs.

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#features

2015-10-21 3:29 GMT+02:00 xyzzy-xyzzy <notifications@github.com>:

**Comment by reek** [comment]
new feature on v8.5
https://github.com/reek/anti-adblock-killer#features

2015-10-21 4:06 GMT+02:00 reek <reekside@gmail.com>:

**Comment by reek** [comment]
also added on help
https://github.com/reek/anti-adblock-killer#help
