### ISSUE TITLE
Ad-defend: spox.com - shz.de

### ISSUE THREAD

**Issue by TonyTough** [reek/anti-adblock-killer#685]
Please add these domains
spox.com
shz.de
transfermarkt.de

to this script
ad_defend_general : {
	  // by: hamsterbacke
      // pull: https://github.com/reek/anti-adblock-killer/pull/467

**Comment by reek** [comment]
ok, I'll add

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
