### ISSUE TITLE
mirror.ninja

### ISSUE THREAD

**Issue by Morgenbroed** [reek/anti-adblock-killer#690]
Please add this site. They recently made all videos unplayable if you have adblock on.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
