### ISSUE TITLE
getting this message everytime i open browser

### ISSUE THREAD

**Issue by banther7** [reek/anti-adblock-killer#694]
happens on my default homepage google.com, i already deleted the current subscription and readded it. im using the palemoon fork Ad block latitude. 
![subcribe](https://cloud.githubusercontent.com/assets/8650114/10716968/b9b7c1d2-7b1f-11e5-9760-c99d85f00fd5.png)

**Comment by reek** [comment]
Hi

Anti-Adblock Killer is optimized to work with these browsers
https://github.com/reek/anti-adblock-killer#supported-browsers

otherwise, you can disable this warning in the settings
http://reek.github.io/anti-adblock-killer/#settings

Regards
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
