### ISSUE TITLE
Add rule for polskieradio.pl

### ISSUE THREAD

**Issue by FadeMind** [reek/anti-adblock-killer#695]
Please add rule for unblock video stream on polskieradio.pl site.

Samples:

http://www.polskieradio.pl/5/3/Artykul/1536136,Pawel-Kukiz-w-ciagu-dwoch-lat-ten-system-peknie

http://www.polskieradio.pl/5/3/Artykul/1536122,Wybory-parlamentarne-2015-Sondaz-pewna-wygrana-PiS-piec-partii-w-Sejmie

![a](http://i.imgur.com/EtvufuE.png)

**Comment by MajkiIT** [comment]
Check now.... for me all is ok.

**Comment by FadeMind** [comment]
Now is OK. I using standard ublock origin rules.

![1](http://i.imgur.com/6WtAxFG.png)

**Comment by MajkiIT** [comment]
No polish filters?

**Comment by FadeMind** [comment]
It is not all :D One sec:

![1](http://i.imgur.com/x8saHso.png)

Polish:
https://www.certyficate.it/adblock/adblock.txt
https://secure.fanboy.co.nz/fanboy-polish.txt

**Comment by MajkiIT** [comment]
fanboy-polish.txt is not supported
