### ISSUE TITLE
6play.fr

### ISSUE THREAD

**Issue by jordan092427** [reek/anti-adblock-killer#696]
http://www.6play.fr/ (all website (when look video))
http://imgur.com/BeUXP8q
Firefox + Google Chrome
Greasemonkey (firefox) + tampermonkey (google chrome)
Adblock Plus
Adblock Warning Removal List
Liste FR+EasyList
AakList (Anti-Adblock Killer)

ps: not ALL pub was blocked

Thank u

**Comment by reek** [comment]
Hi,

Report it to ListeFR

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
