### ISSUE TITLE
techsini.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#698]
http://imgur.com/VuSY9DV

Mozilla Firefox 41.0.2
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

<pre>
$(document).ready(function($) {

                        setTimeout(function() {
                            if ( typeof(window.google_jobrunner) === "undefined" ) {

                                //ad blocker installed - show notice

                                swal({
                                    title: "Adblocker Detected",
                                    text: "We have detected that you are using adblocking plugin in your browser. \n \n The revenue we earn by the advertisements is used to manage this website, we request you to whitelist our website in your adblocking plugin.",
                                    type: "warning",
                                    showCancelButton: true,
                                    confirmButtonColor: "#01A9DB",
                                    confirmButtonText: "Yes, I'll Whitelist",
                                    cancelButtonText: "Cancel",
                                    closeOnConfirm: false,   closeOnCancel: false
                                },
                                function(isConfirm){
                                    if (isConfirm) {
                                        swal("Thank you", "Thank you for whitelisting our website. :)", "success");
                                    } else {
                                        swal("Oh..", "Oh.. Hope you whitelist our website in your adblocking plugin soon!", "error");
                                    }
                                });

                            }

                        }, 10000);

                    });
</pre>

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
Solution on ublock 
techsini.com##script:contains(Adblocker Detected)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
`/simple-adblock-notice/*`

**Comment by reek** [comment]
EasyList has a conflicting rule
<code>@@/wp-content/plugins/simple-adblock-notice/*$script,~third-party</code>

**Comment by SMed79** [comment]
I am pending an explanation [f=62&t=29550](https://forums.lanik.us/viewtopic.php?f=62&t=29550).

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
