### ISSUE TITLE
b-website.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#699]
reek this your people 

http://b-website.com/adblock-notify-plugin-for-wordpress
http://imgur.com/yTeg6WU

Mozilla Firefox 41.0.2
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
ok thanks

**Comment by MajkiIT** [comment]
Easy solution b-website.com#@##adsense

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
