### ISSUE TITLE
cityam.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#700]
http://www.cityam.com/228206/all-british-businesses-will-have-access-to-fast-broadband-by-2020-david-cameron-confirms

i guess since blind is fix we see nothing on cityam.com but this is good read

http://www.theguardian.com/media/2015/oct/20/city-am-ban-ad-blocker-users
http://www.wired.co.uk/news/archive/2015-10/20/city-am-adblock-newspaper
http://digiday.com/publishers/city-becomes-first-uk-publisher-ban-ad-blockers/
http://www.mediapost.com/publications/article/260874/city-am-becomes-first-uk-news-site-to-block-ad-blo.html

**Comment by reek** [comment]
Thanks for news

**Comment by yoshimo** [comment]
http://www.cityam.com/assets/js/PbCode.min.js?v=1510260832.
If this script gets executed, the text gets blurred after the first few lines.
If i block it, it currently remains intact.

**Comment by xxcriticxx** [comment]
yoshimo can you take screenshot of the blurred text you see

**Comment by yoshimo** [comment]
![cy_blur](https://cloud.githubusercontent.com/assets/17909/10800422/076af342-7db2-11e5-9c13-055bc3120b03.PNG)
![cy_clean](https://cloud.githubusercontent.com/assets/17909/10800423/0770808c-7db2-11e5-9b90-b6673e2d3e1b.PNG)

**Comment by yoshimo** [comment]
The original text is still there and gets modified

**Comment by xxcriticxx** [comment]
the website works for me with no blurred text so do we have some type of script installed already??

MajkiIT or Reek can you please check out city am

**Comment by yoshimo** [comment]
So ABP with blurred text shows me the following filters hit:

![cy-hitlist](https://cloud.githubusercontent.com/assets/17909/10801455/b985bb52-7db7-11e5-8385-9d8c2bfc1080.PNG)

Haven't found the exact trigger yet

**Comment by xxcriticxx** [comment]
this what i have installed and i have no blurred

Mozilla Firefox 41.0.2
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MajkiIT** [comment]
@xxcriticxx I tested on two browsers and it's ok. 
@yoshimo try update all filters.

**Comment by MajkiIT** [comment]
@yoshimo update easylist 9 days ago they added exclude

https://hg.adblockplus.org/easylist/log?rev=cityam.com

**Comment by thoma5nator** [comment]
You could also disable CSS styling. The ad text will still be there, but so will the article.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
