### ISSUE TITLE
Kissanime.com

### ISSUE THREAD

**Issue by Basoeckn** [reek/anti-adblock-killer#701]
http://kissanime.com/Anime/Heavy-Object/Episode-002?id=117952 
http://i.imgur.com/uNceTfB.png
Mozilla Firefox
Greasemonkey
uBlock Origin and possibly uBlock (updated changed after one try, but did not investigate further)
AakList

Does not seem to be working with any video. Kissanime is already in the changelog. They updated their site recently, if that helps.

**Comment by xxcriticxx** [comment]
page works 100%

install greasemonkey and user scripts also i think your ublock is off i cant tell with background you have

**Comment by Basoeckn** [comment]
The page works, but does the video work for you?
After around 60 seconds the video blocks for me with any combination of ghostery and ublock on

**Comment by reek** [comment]
@Basoeckn 
Works for me

See: https://github.com/reek/anti-adblock-killer#help

**Comment by xxcriticxx** [comment]
yes video works with no problem install user scripts and everything will work
