### ISSUE TITLE
cuisineactuelle.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#702]
Hi, 
on `http://www.cuisineactuelle.fr/`

![cuisineactuelle fr](https://cloud.githubusercontent.com/assets/1873139/10805990/5dbd4ac2-7dd2-11e5-99e6-05f490f5e211.png)

```
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=cuisineactuelle.fr
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=cuisineactuelle.fr
```

Merci.

**Comment by reek** [comment]
Hi,
Thanks Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
