### ISSUE TITLE
handle  FuckAdBlock script

### ISSUE THREAD

**Issue by muhasturk** [reek/anti-adblock-killer#703]
It seems that your script could not handle FuckAdBlock script.

 https://github.com/sitexw/FuckAdBlock

**Comment by reek** [comment]
Obviously yes
https://github.com/reek/anti-adblock-killer#supported-sites

**Comment by muhasturk** [comment]
@reek I can not send you a link but you can see a warning on one of embedded openload videos.

```
 The publisher of the video doesnt allow adblock, please disable and reload 
```

**Comment by reek** [comment]
Hi,

See: https://github.com/reek/anti-adblock-killer/issues/707#issuecomment-154770812
