### ISSUE TITLE
gokano.com

### ISSUE THREAD

**Issue by RNTmedeiros** [reek/anti-adblock-killer#704]
gokano.com
http://i.imgur.com/PdQwhAv.png
Google Chrome
TamperMonkey
Adblock (getadblock.com)
EasyList + AakList

**Comment by MajkiIT** [comment]
Should I log in?

**Comment by RNTmedeiros** [comment]
yes

**Comment by MajkiIT** [comment]
solution
gokano.com#@#.adsbygoogle

**Comment by RNTmedeiros** [comment]
worked, thank you

**Comment by reek** [comment]
@MajkiIT 
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
