### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by RNTmedeiros** [reek/anti-adblock-killer#707]
https://openload.co/f/vBIYk58TQUc/Olha_o_tiro_Olha_o_tiro.wmv.mp4
http://i.imgur.com/Ywlz2Z1.png
Google Chrome
TamperMonkey
Adblock (getadblock.com)
EasyList + AakList

**Comment by MajkiIT** [comment]
solution
@@|https://openload.co/ad.php$xmlhttprequest,domain=openload.co

**Comment by RNTmedeiros** [comment]
you are fast haha, worked o/

**Comment by reek** [comment]
@MajkiIT 
Thanks again

**Comment by MajkiIT** [comment]
@reek  you're welcome

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Hi, 
`@@||openload.co/adv.php$xmlhttprequest,domain=openload.co`

on `http://mareplaytv.fr/video/lamour-est-dans-le-pre-episode-17-du-03-aout-2015/`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by muhasturk** [comment]
seems still does not work embedded openload videos

8.7 
Google Chrome Version 46.0.2490.80 (64-bit)
OSX 10.11.1

**Comment by reek** [comment]
@muhasturk 
Its ok for me, have update AakList ?

Tested embed
https://output.jsbin.com/hiwekopiro

**Comment by SMed79** [comment]
work for me http://getwebb.org/d/ljxTWltj

**Comment by muhasturk** [comment]
I had to update filter list manuelly on ublock.

I will donate keep going great job.

**Comment by reek** [comment]
@muhasturk 
Ok, thanks ::smile::
