### ISSUE TITLE
dagens.dk

### ISSUE THREAD

**Issue by klausenbusk** [reek/anti-adblock-killer#708]
http://www.dagens.dk/viralt/en-almindelig-tur-med-metro-blev-brat-afbrudt-h%C3%B8r-passagererne-synge-burhan-g
http://imgur.com/dHslHMA
Mozilla Firefox
I don't use any "script manager".
uBlock
EasyList + 10 others. Tried with just EasyList + this list, same result.

Block all request to avxwcuaagfcdn.net seems to fix it.
\*://avxwcuaagfcdn.net/\*

**Comment by MajkiIT** [comment]
for me solution is dagens.dk#@#.text_ads

**Comment by klausenbusk** [comment]
> for me solution is dagens.dk#@#.text_ads

I think it most optimal to block to avxwcuaagfcdn.net. No reason to waste bandwidth on a adblock detector script, when we filter the "warning" box out anyway.

**Comment by MajkiIT** [comment]
It's Reek decision. I wrote my solution.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
