### ISSUE TITLE
maskinteknik.dk

### ISSUE THREAD

**Issue by klausenbusk** [reek/anti-adblock-killer#709]
http://www.maskinteknik.dk/artikel/79804-gravemaskine-pa-skinner
http://imgur.com/61bN0Nk
Mozilla Firefox
I don't use any "script manager".
uBlock
EasyList + 10 others. Tried with just EasyList + this list, same result.

Looking at the source code, you can find a link to a .js file:
http://www.maskinteknik.dk/assets/templates/2014/jscache/2f77a7f1a38aa453f45b0525c0e7bb72.js
If you search for "annonceblokering" in that file, you can find the magic. Not sure if uBlock can filter javascript functions?

**Comment by MajkiIT** [comment]
try this @@||www.maskinteknik.dk/assets/templates/maskinteknik/gfx/ads.png

**Comment by klausenbusk** [comment]
> try this @@||www.maskinteknik.dk/assets/templates/maskinteknik/gfx/ads.png

Seems to work. How did you figure that out? :)

**Comment by MajkiIT** [comment]
How you can see alert is enable on end of loading page. I see on ublock witch element is blocking in the end. I whitelist this element and check it's ok.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
