### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by coolNAO** [reek/anti-adblock-killer#71]
http://www.cbs.com/shows/48_hours/video/C7sBoXjELUe5vZR89_xJYZJNWNm5jYqp/death-on-the-hudson/

probably not fixable but give it a shot? also if you got spare time look into the hulu ads?
![1](https://cloud.githubusercontent.com/assets/9362505/4749046/2759bb3c-5a7e-11e4-848f-98a9c7bde169.jpg)
![2](https://cloud.githubusercontent.com/assets/9362505/4749064/60730cc0-5a7e-11e4-9b57-48c4a03a99ef.jpg)

**Comment by pedrokleiz** [comment]
reek, I'm having the same problem.
<img width="675" alt="screenshot 2015-09-10 16 23 46" src="https://cloud.githubusercontent.com/assets/6828704/9800005/87f890a0-57d8-11e5-9b4a-c61906f3c232.png">

And I'm using this one too: https://secure.fanboy.co.nz/fanboy-espanol.txt

Any help?

**Comment by reek** [comment]
you subscribed to too many lists
try just EasyList+EasyPrivacy+AakList

**Comment by pedrokleiz** [comment]
With just EasyList and Anti-AdBlock killer it was the same thing.
I think it was the "||2mdn.net^$third-party,script"

Any help with that?

**Comment by reek** [comment]
Sorry, no solution, you must whitelist :(

**Comment by pedrokleiz** [comment]
Were you able to see the video with your own lists?

**Comment by reek** [comment]
@pedrokleiz 
No, i have message anti adblock

**Comment by MrSherlockHolmes** [comment]
Hmph. We must find a way to takle these defences... otherwise anti-adblock may be severely compromised.
