### ISSUE TITLE
RP-online (Ad-Defend)

### ISSUE THREAD

**Issue by yoshimo** [reek/anti-adblock-killer#710]
http://www.rp-online.de/ seems to use Ad-Defend but it does make it through the Reek-Script

**Comment by xxcriticxx** [comment]
i see the website for 5 sec then whole page goes white

**Comment by reek** [comment]
@yoshimo 
I see nothing

Please provide the information
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by yoshimo** [comment]
http://www.rp-online.de/panorama/ausland/flug-9268-russische-maschine-zerschellt-im-sinai-das-toedliche-ferienende-ueber-aegypten-aid-1.5525606
http://imgbox.com/gofvkCUk
Greasemonkey
Adblock Plus
EasyList , EasyListGermany , Easylist China, EasyPrivacy, Fanboys Annoyance List

**Comment by reek** [comment]
@yoshimo 
https://forums.lanik.us/viewtopic.php?f=90&t=26208

to report ad go to
https://forums.lanik.us/

**Comment by yoshimo** [comment]
@reek https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js has 
code for https://github.com/reek/anti-adblock-killer/issues/685 , and this is no different

**Comment by reek** [comment]
@yoshimo 
if that is the case I will add rp-online.de.

**Comment by TonyTough** [comment]
Hello,

motorradonline.de
is one more site to add, where code #685 seems to work.

**Comment by yoshimo** [comment]
http://www.20min.ch/ also is affected.
Maybe you should do it like https://openuserjs.org/scripts/schwarztee/AdDefend_Klatsche and don't require a website and do it globally.

**Comment by reek** [comment]
@TonyTough 
Thanks

@yoshimo 
for now I will do case by case, as this may cause some inconvenience, but I'll work on it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
