### ISSUE TITLE
cleodesktop.com

### ISSUE THREAD

**Issue by JonnyThree** [reek/anti-adblock-killer#711]
Hello this website is boring me, can you help resolving that? Thanks
http://www.cleodesktop.com
http://imgur.com/jRaoHcC
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by reek** [comment]
Hi,

Ok, but next time use report guide
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by JonnyThree** [comment]
Sorry i have edited message now

**Comment by reek** [comment]
Ok, thanks

**Comment by MajkiIT** [comment]
try this @@|http://pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=cleodesktop.com

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
