### ISSUE TITLE
www.rte.ie/player

### ISSUE THREAD

**Issue by Xarvz** [reek/anti-adblock-killer#712]
http://www.rte.ie/player/ie/show/the-meaning-of-life-with-gay-byrne-1302/10481172/
http://i.imgur.com/wCiwJUp.png
Chrome 
ublock origin
ublock origin
http://i.imgur.com/jLIrGb6.png

Keep up the good work! (^_^)

Edit: I just realized this could be content locked for you after I found another issue that you responded to with "Sorry, content locked for my country". Couldn't you just use a free VPN?

Edit: So I was very tired last night and posted this at 5 am, so I didn't bother to do many tests. Today I asked a friend if they had the same problem, he has just normal adblock I don't think he has anti-adblock-killer. To my surprise, it worked for him, so I downloaded normal adblock and set it to allow in incognito and it worked fine. So then I tried ublock origin in incognito and it also worked fine, but once I added ghostery to incog it failed. I then disabled each ghostery tracker one by one and found out it was double click?! http://i.imgur.com/BHOV2Mn.png I also tested it in firefox with just ublock origin and ghostery and it works fine even with double click blocked. So I'm not sure if there is much you could do about this considering it seems to be a weird ghostery/chrome problem. Sorry if I wasted any of your time. I've reported it to ghostery.

**Comment by reek** [comment]
No worries.

**Comment by 1-user** [comment]
#

**Comment by 093-2r5** [comment]
@2-user test _

**Comment by 093-2r5** [comment]
test
