### ISSUE TITLE
cloudwebcopy.com

### ISSUE THREAD

**Issue by vicgarin** [reek/anti-adblock-killer#714]
http://cloudwebcopy.com/

If you go to cloudwebcopy.com after 30 seconds the page redirects to link cryptors.

After going through all the link cryptors (3-4) it lands me to:

http://ads.cloudwebcopy.com/adblock.htm

PS. If you know of good rapidleech sites which don't require registering please let me know. Maybe a new repo with a list of sites and the premium accounts they support. ;) Anyways thanks for the free software.

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
