### ISSUE TITLE
pirlotvlive.com (dinozap.info)

### ISSUE THREAD

**Issue by LifeIsStrange** [reek/anti-adblock-killer#715]
http://www.pirlotvlive.com
the link
thanks!

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

PS: Next time review the guidelines for contributing

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by LifeIsStrange** [comment]
Oh really thanks and sorry the guidelines for contributing. I will go read this. 
Sorry for my bad english. 
I would like to give you donations, but sadly I am Just a french teenager and my parents not understund the need of donate to the free softwares.... When I will be adult I will give you donations. 

Thanks !

**Comment by reek** [comment]
Ok, no worries ::smile::

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by LifeIsStrange** [comment]
Amazing thanks again !
