### ISSUE TITLE
freebitco.in

### ISSUE THREAD

**Issue by RNTmedeiros** [reek/anti-adblock-killer#716]
freebitco.in
http://i.imgur.com/bfPRQu7.png
Google Chrome
TamperMonkey
Adblock (getadblock.com)
EasyList + AakList

**Comment by MajkiIT** [comment]
Alert is showing after log in?

**Comment by MajkiIT** [comment]
I see that easylist added 3 months ago Anti Adblock rules https://hg.adblockplus.org/easylist/rev/45461f20b464

**Comment by RNTmedeiros** [comment]
I disabled and activated the EasyList and it has been updated, it seems that is now working, thank you
