### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by mrgcohen** [reek/anti-adblock-killer#718]
cbs show's show the following message. 
![image](https://cloud.githubusercontent.com/assets/1027909/10943078/e9b7a802-82e0-11e5-98b3-8933fafb9f12.png)

http://www.cbs.com/shows/supergirl/video/92C4EB54-8372-A474-3F03-8CA1385134F3/supergirl-pilot/

Chrome
![image](https://cloud.githubusercontent.com/assets/1027909/10943360/12f34ba8-82e2-11e5-9eec-0787f96ca8d5.png)

**Comment by MajkiIT** [comment]
Geo lock

**Comment by mrgcohen** [comment]
Oh Is it location based? I'm in Maryland.

**Comment by reek** [comment]
Hi,
I already try to find a solution but without success, because you have to allow videos ads

**Comment by cleardarkz** [comment]
I found a solution for this...requires some script injection tho

**Comment by reek** [comment]
@cleardarkz 
did you try to add it with AakScript ?

**Comment by cleardarkz** [comment]
block this script:

http://c5255dfbeaf8de918c73-c9552ca9f9dab9ffb917d11bd7154762.r70.cf5.rackcdn.com/tbd5CRSAuXb104cCvylq.min.js

should do the trick.

**Comment by einstein95** [comment]
@cleardarkz: That doesn't work for me. Using the dynamic filter `cbs.com rackcdn.com * block` just shows nothing and the video doesn't play. I've also found the static filters `@@||pubads.g.doubleclick.net^$domain=cbs.com` and `@@||b.ifmnwi.club^$domain=cbs.com` to have the same effect.

**Comment by singron** [comment]
I used this rule in uBlock and it worked.

```
www.cbs.com http://c5255dfbeaf8de918c73-c9552ca9f9dab9ffb917d11bd7154762.r70.cf5.rackcdn.com/tbd5CRSAuXb104cCvylq.min.js * block
```

Maybe blocking all of rackcdn.com is too aggressive?

**Comment by cleardarkz** [comment]
@einstein95 I put a specific link to a specific script that requires blocking...blocking the entire rackcdn domain is going to result in what you experience since the entire CBS Player library is hosted on these servers.

The script above is a small script triggering an ajax request with some ad-block sensitive params, if your browser blocks the request (which Adblock does), the player blocks the content, otherwise it works flawlessly.

**Comment by einstein95** [comment]
Right, I just blocked the entire domain as the URL that it was using for me was a different one. After clearing cookies (with cbs.com it does matter) and disabling all but easylist and anti-adblock it works. I'll play around with this more.

**Comment by jyotidas** [comment]
I've found a somewhat annoying workaround using uBlock: turn it off, refresh the video page, and as soon as the ad starts loading, turn uBlock back on.
