### ISSUE TITLE
filmovizija.club

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#719]
my browser google chrome, adblocker with AakList, and script Anti adblocker killer for tempermonkey
only way i get  to bypass this is using adblock with adguard together and block this message with adguard, block an ad on this page with adguard, select the message and block it, with adblock doesn't work
![sem titulo](https://cloud.githubusercontent.com/assets/15664251/10959254/76fd3bd6-836e-11e5-999e-d78bac9713a8.png)

**Comment by reek** [comment]
HI,

filmovizija.club as change TLD (top level domain), i need update my rule

**Comment by MajkiIT** [comment]
@reek on yours filters is rule
@@||findvideo.tv/popunder.php$script,domain=filmovizija.me|filmovizija.in|filmovizija.com|filmovizija.net

Now solution is:
@@||filmovizija.club/advertise.js$script,domain=filmovizija.club

**Comment by reek** [comment]
@MajkiIT 
that's right ::smile::

**Comment by MajkiIT** [comment]
@reek I see that all old domains of filmovizija are dead or redirect to filmovizija.club, so maybe you can remove old rule.

**Comment by fabiobarao94** [comment]
thank you, how did you discovered?????

**Comment by MajkiIT** [comment]
I'm writing polish filters, so I can find rules which can be solution. On beginning I disable rule one be one and looking it is ok.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
