### ISSUE TITLE
youporn.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#720]
http://imgur.com/wz70onb

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

this looks like only like message. page works like it should. i think

**Comment by MajkiIT** [comment]
for me solution is
@@|http://media.trafficjunky.net/js/holiday-promo.js$script,domain=youporn.com

**Comment by reek** [comment]
@MajkiIT 
Thanks again ::smile::

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
