### ISSUE TITLE
dayt.se

### ISSUE THREAD

**Issue by clapfish** [reek/anti-adblock-killer#722]
Hey, can you add dayt.se to the list please?

**Comment by MajkiIT** [comment]
I don't see any alert or notification.

**Comment by xxcriticxx** [comment]
same here no msg in ie, chrome and firefox

**Comment by clapfish** [comment]
Weird, because im getting this error as attached.

http://imgur.com/Ca9rfaq

**Comment by alexander255** [comment]
Cannot reproduce either.

@clapfish Please provide the information [requested here](https://github.com/reek/anti-adblock-killer/wiki/Report-Guide). We still have no idea what software *you* are using. Also please provide which country you are accessing the site from.

**Comment by reek** [comment]
Hi,

I confirm there is an anti adblock with uBlock + Chrome, I have already found a solution

**Comment by clapfish** [comment]
@alexander255 My apologies for leaving those infos out.

dayt.se
http://imgur.com/Ca9rfaq
Google Chrome
Tampermonkey
AdblockPlus
Easylist + Aaklist

@reek Thank you. May i know where to input those codes?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
@reek 
solution in easylist
https://hg.adblockplus.org/easylist/rev/68c0411c862c
