### ISSUE TITLE
antiblock.org

### ISSUE THREAD

**Issue by kenmmn** [reek/anti-adblock-killer#723]
Aak.setLocal('AntiblockID', id[1]); // L3845
the key must be "antiblockId" bacause it referred to "localStorage.antiblockId"

**Comment by reek** [comment]
Hi

it's right, I'll fix that, thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
