### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#724]
https://portal.abczdrowie.pl/nadkwasota-zoladka
http://imgur.com/Ahf2nfV

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

MajkiIT do your magic! looks like same player on onet.pl and wp.pl

**Comment by MajkiIT** [comment]
Yes I see. It's like error on wp.pl

@@|https://adv.wp.pl/RM/Box/2015-03/x.gif$image,domain=portal.abczdrowie.pl
@@||egcfxjkcnn.wp.pl^$script,domain=portal.abczdrowie.pl

First rule if you use ony Easylist
Second if you use polish filters.

I will update polish filters. Give me 10 minutes.

**Comment by reek** [comment]
@MajkiIT 
Thanks again

**Comment by MajkiIT** [comment]
@reek 
You can close this issue. It's my mistake. I fixed it.

**Comment by reek** [comment]
@MajkiIT 
Ok
