### ISSUE TITLE
cloud.corporatecentral.com

### ISSUE THREAD

**Issue by pazi11** [reek/anti-adblock-killer#725]
Im trying to build a test app there but im getting a "You are using Corporate Central's free, ad supported subscription.
Please disable ad blocking on this page to continue using Corporate Central.
Thank You." message.

**Comment by alexander255** [comment]
Please provide [the information requested here](https://github.com/reek/anti-adblock-killer/wiki/Report-Guide).
Also: Could you describe what account type you have and what you specifically did after logging in?

I tested (created account, logged in, create forum, clicked around) with these credentials and their "awesome" service works just fine:
ad-test@mailinator.com
ad123$

**Comment by reek** [comment]
Hi,
I confirm there an alert box

**Comment by reek** [comment]
I found a solution, I will publish soon

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
