### ISSUE TITLE
rtlxl.nl

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#726]
Hi, 
when adblocker is activated this make the videos greyscale on : 
`http://www.rtlxl.nl/#!/het-collectief-geheugen-343312/f9dc7419-d140-a4a1-db7e-e6c7911d0275`

source: https://adblockplus.org/forum/viewtopic.php?f=1&t=42260

`@@||staticfiles.rtl.nl/lib/rtl.jsapi/pubads_impl_70r.js$script,domain=rtlxl.nl`

Thanks!

**Comment by reek** [comment]
Thanks again ::smiley::

**Comment by reek** [comment]
Done
