### ISSUE TITLE
Confliction between 2 subscriptions

### ISSUE THREAD

**Issue by MUFTAKiS** [reek/anti-adblock-killer#73]
Anti-AdBlock Killer conflict with main Easytlist which when they enable together anti-adblock killer dont work and when i disable easylist i get anti-adblock killer work good

i have firefox v33 + adblock plus 2.6.5

**Comment by anelafar** [comment]
big bozz please check

http://antiblock.org/?p=v3&demo
http://www.elmoslsal.com/%D8%A7%D9%84%D9%82%D9%88%D8%A7%D9%86%D9%8A%D9%86-2/
http://codeclan.altervista.org/

**Comment by anelafar** [comment]
please fix annooying message adblock plus detetected thanks sir

**Comment by reek** [comment]
@anelafar 
It's killed by AakScript, please see instruction

**Comment by anelafar** [comment]
hey dude pls check it this is too URLs SHORTENER http://al.ly/wuBq
annoying "Please Disable adblock plus"

**Comment by reek** [comment]
@anelafar
It's killed by AakScript, please see instruction
