### ISSUE TITLE
squidboards.com

### ISSUE THREAD

**Issue by CodyMKW** [reek/anti-adblock-killer#730]
Don't know where to post this but the script doesn't seem to work on http://squidboards.com maybe try this

squidboards.com##.funbox
squidboards.com##.premiumBlock
squidboards.com##.premiumContain

seems to work for me
![selection_003](https://cloud.githubusercontent.com/assets/8176523/11026651/06444668-867b-11e5-9d03-b0368d2e64c2.jpg)

**Comment by reek** [comment]
Hi,
Ok, thanks Cody ;)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
