### ISSUE TITLE
AdBlockConverter

### ISSUE THREAD

**Issue by KingThunder** [reek/anti-adblock-killer#731]
Here is the site: http://www.adblockconverter.com/
And here is the JS: http://www.adblockconverter.com/js/aab.js

Is there a way to block this?

**Comment by MajkiIT** [comment]
||adblockconverter.com/js/aab.js$script

**Comment by reek** [comment]
Ok, thanks for this new Anti-Adblock Tracker

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
