### ISSUE TITLE
mrpiracy.xyz

### ISSUE THREAD

**Issue by Rootzpower** [reek/anti-adblock-killer#732]
Hi,
First off all, thanks for your script.

Can you support http://www.mrpiracy.xyz 
The warning only appears when you go see a video.
Site need registration!
You can use these credentials i create for this occasion
Username: test@test.com
Password: test123

My config:
Mozilla Firefox 42.0
Greasemonkey 3.5
uBlock Origin 1.3.2
anti-adblock-killer 8.7 with last filter Anti-Adblock Killer | Reek‎

Screenshot:
![mrpiricy](https://cloud.githubusercontent.com/assets/15384112/11038209/b00915b0-86f9-11e5-9188-4da053fde633.png)

Thanks again and keep the good work :)

**Comment by reek** [comment]
Hi,
I will take a look

**Comment by MajkiIT** [comment]
Solution
@@|http://pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=mrpiracy.xyz

**Comment by Rootzpower** [comment]
@MajkiIT works!
That solucion i´ll included in next update?

**Comment by reek** [comment]
@Rootzpower 
Yes

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by nina94** [comment]
script do not work in mrpiracy.xyz anymore can update it please?

**Comment by MajkiIT** [comment]
For me it's Ok.

**Comment by reek** [comment]
@nina94 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by nina94** [comment]
sorry for late reply!

http://mrpiracy.xyz/
http://i.imgur.com/qAXlXe4.jpg?1
http://i.imgur.com/Ym5b6W8.jpg
Chrome 49.0.2623.75 m 
Tampermonkey
AdblockPlus
filterlists- AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
@nina94 
Thanks, but its killed for me.
See: https://github.com/reek/anti-adblock-killer#help
