### ISSUE TITLE
computerbild.de (Ad-Defend)

### ISSUE THREAD

**Issue by yoshimo** [reek/anti-adblock-killer#733]
AAK-Userscript 8.7 doesn't catch AdDefend on http://www.computerbild.de/artikel/cb-News-PC-Hardware-TAG-Heuer-Smartwatch-11201032.html
same solution as in #710 and #685

**Comment by reek** [comment]
Ok, thanks

**Comment by xxcriticxx** [comment]
website works for me no message found

**Comment by yoshimo** [comment]
![cb](https://cloud.githubusercontent.com/assets/17909/11164985/43ab1e0c-8b01-11e5-9eed-37ad58fe5926.PNG)

@xxcriticxx  clearly i see images here coming from i.computer-bild.de/imgs/  and only two things get them.
1) Using https://www.computer-bild.de as the ads get blocked for being mixed-content 
2) Kill the Ad-Defend Script.

**Comment by xxcriticxx** [comment]
page works as it should only few small ad on top and side 

no ad blocker msg found

going to https://www.computer-bild.de i get This Connection is Untrusted

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
