### ISSUE TITLE
Kissanime.to (change domain)

### ISSUE THREAD

**Issue by ayyTurger** [reek/anti-adblock-killer#734]
Just for example. This video: http://kissanime.to/Anime/Gintama/Episode-038?id=2424
http://imgur.com/JVYIoUJ
Google Chrome
Tamper Monkey
uBlock Origin v1.3.3
EasyList + Peter Lowe's Ad server list + AakList

**Comment by LordWicker** [comment]
Can confirm. What are the odds, I'm watching Gintama there as well:P

**Comment by WhatsCS** [comment]
I'm pretty sure this is due to them changing their domain to kissanime.to, I tested this by changing the url in the script and it worked.

**Comment by ayyTurger** [comment]
I'm not exactly sure how to do that. If you could please elaborate on how to do this. It would be most appreciated. :)

**Comment by spirgiuz** [comment]
@WhatsCS Nice tip, changing domains to kissanime.to in ad-block custom filters list fixed it for me too.

**Comment by reek** [comment]
Hi,
The problem is well-changing domain, I will fix it

**Comment by bgi123** [comment]
Seriously guys. Tell me how to change this URL. Is it with in the settings of the script? I am just using ad-blocker with anti-ad-block killer. Been control - f - kissanime in everything I could think of to change this url...

**Comment by LordWicker** [comment]
Press your tamper monkey (or whatever else) button, then press the anti-adblock killers dashboard button. Then just press the single line across the page that says "anti-adblock killer - Reek" You should be on a page that says "editor". Hit "search", and enter "Kiss". You should see the URL, then edit it to "to" instead of "com".

Sorry if I'm not being clear enough.

**Comment by bgi123** [comment]
Wow. I am so retarded. I should have just used the built in search function instead of using chromes control + f...

**Comment by MajkiIT** [comment]
@reek for me solution is: @@|http://kissanime.to/ads/madads.aspx$subdocument

**Comment by reek** [comment]
@MajkiIT 
thank you, but I already have a solution

**Comment by sIips** [comment]
Okay , I need help .

I followed everything correctly-or at least I think I did

but I'm still running into the same issue .

I have uBlock with Anti-Adblock Killer + Anti-Adblock Killer user script 

I even tried changing the domain in the script settings and this is how it looks like : 
![capture](https://cloud.githubusercontent.com/assets/13898573/11320292/270cb614-9049-11e5-8a0c-4be1ec9cbce5.JPG)

Any solution ?

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
