### ISSUE TITLE
iplex.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#735]
http://www.iplex.pl/filmy/prawdziwa-historia-kota-w-butach%2C8765
![implex](https://cloud.githubusercontent.com/assets/11302675/11059617/08136e4e-879b-11e5-9022-538907ce0827.png)

solution
@@||cdn3.iplex.pl/iplex3/static/js/ads.js$script

**Comment by xxcriticxx** [comment]
MajkilT you going update polish filter with this?

**Comment by MajkiIT** [comment]
Yes, I added it about 8 hours ago.

**Comment by reek** [comment]
Thanks Majkilt

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
