### ISSUE TITLE
d3xt3r bypasses AAK

### ISSUE THREAD

**Issue by RoxKilly** [reek/anti-adblock-killer#737]
http://d3xt3r.com/anti-adblock?test defeats anti-adblock-killer

Firefox 42
Greasemonkey
uBlock Origin 1.3.2 (EasyPrivacy, EasyList, Peter Lowe's Adserver, AAK)
Reek 8.7 userscript

**EDIT**: Strange; with Javascript enabled the block does not work. With Javascript disabled, the ad-blocker is detected.  The author [discusses](http://d3xt3r.com/anti-adblock) that with no JS, the page should display normally.  What's going on?

**Comment by reek** [comment]
Already supported

2015-11-10 19:34 GMT+01:00 RoxKilly <notifications@github.com>:

**Comment by RoxKilly** [comment]
![3](https://cloud.githubusercontent.com/assets/12346501/11071888/28eac034-87b1-11e5-840f-e8443a1fe8ad.png)

 With Javascript enabled the block does not work. With Javascript disabled (I used uBlock origin to disable first party js), the ad-blocker is detected. The author [discusses](http://d3xt3r.com/anti-adblock) that with no JS, the page should display normally.

**Comment by reek** [comment]
Have you enable AakList on uBlock ?

**Comment by RoxKilly** [comment]
Yes I have:
![4](https://cloud.githubusercontent.com/assets/12346501/11074750/5d7e256c-87bf-11e5-94cf-e828f0e2353e.png)

In this case, AAK works when JS is enabled, but when JS is disabled, I get the 'Ad-block detected' message.  After further investigating I figured out that if the file `http://d3xt3r.com/advertisement.js` must be allowed to load for AAK to work.  Because I browse with JS disabled, this file was never downloaded.  Once I allowed JS, AAK worked.  

Here is a screenshot from uBlock Origin network logger with JS disabled.  The site detects an ad-blocker:
![6](https://cloud.githubusercontent.com/assets/12346501/11074941/92fab254-87c0-11e5-94a1-40f8b3b4bccf.png)

Here is a screenshot with `http://d3xt3r.com/advertisement.js` only allowed. This time AAK works and the site is defeated:
![5](https://cloud.githubusercontent.com/assets/12346501/11074988/d33f17ba-87c0-11e5-99e6-1b1548c7ebb8.png)

**Comment by reek** [comment]
Hi,
It's clear that for AakScript works you need to enable javascript, because it's write in javascript.

**Comment by RoxKilly** [comment]
Thanks
