### ISSUE TITLE
giovanniterlingen.com

### ISSUE THREAD

**Issue by exodius48** [reek/anti-adblock-killer#738]
1. http://giovanniterlingen.com/
2. http://i.imgur.com/mbC69xX.png
3. Firefox 42 x86
4. Greasemonkey
5. uBlock Origin
6. AAK , Easylist,  MVPS HOSTS,  Fanboy’s Social Blocking List‎, and many more.

**Comment by MajkiIT** [comment]
@reek 
on Adblock solution is giovanniterlingen.com#@#.text_ads

but 
on uBlock then I add this still I see notification.

On page I see this JS

 <script src="assets/js/detect.js"></script>
      <script language="javascript">
         function detected() {
         	overlay = document.getElementById("overlay");
         	overlay.style.visibility = (overlay.style.visibility == "visible") ? "hidden" : "visible";
         }
         
         if(typeof detection === 'undefined') {
             detected();
         } else {
             detection.onDetected(detected);
             detection.onNotDetected(notDetected);
             detection.on(true, detected);
             detection.on(false, notDetected);
             detection.on(true, detected).onNotDetected(notDetected);
         }
         
         detection.setOption({
             debug: false,
             checkOnLoad: true,
             resetOnEnd: true
         });
      </script>

**Comment by reek** [comment]
@MajkiIT 
I have nothing, but i will add rule, thanks

**Comment by MajkiIT** [comment]
@reek 

On second PC I don't see notification. Give me time I will check it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by gi097** [comment]
o_O
