### ISSUE TITLE
Bild.de  - ads back

### ISSUE THREAD

**Issue by shuuk** [reek/anti-adblock-killer#740]
http://www.bild.de/
http://i.imgur.com/KU3SaAk.jpg
http://i.imgur.com/c2lQdbG.jpg
http://i.imgur.com/yoijb2m.jpg
Mozilla Firefox 42.0  32 bit
Greasemonkey
ublock
EasyList + AakList ( look at the screenshots )

Any idea why its not blocking anymore?

**Comment by xxcriticxx** [comment]
enable Easylist Germany under Regions, languages

**Comment by shuuk** [comment]
works now thank you
