### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by peakofelephants** [reek/anti-adblock-killer#741]
http://kissanime.to/Anime/Ranpo-Kidan-Game-of-Laplace/Episode-001?id=111766
http://imgur.com/YYGrQuL
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by pacohojaverde** [comment]
You just need to change a line of code to reflect the domain change:
`host : ['kissanime.com']` ...is changed to... `host : ['kissanime.to']`

**Comment by reek** [comment]
@pacohojaverde 
That's it

@peakofelephants 
The fix will be available in the next version, otherwise do manually

Related: https://github.com/reek/anti-adblock-killer/issues/734
