### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by aliasbusin** [reek/anti-adblock-killer#742]
http://kissanime.to/Anime/One-Punch-Man/Episode-006?id=119239
http://imgur.com/R1Ga0zi
Chrome
Tampermonkey
ublock origin
Easylist+Aaklist

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/734

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
