### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by bhattaraib58** [reek/anti-adblock-killer#744]
Though Your contribution in anti-adblock scripts everything was going very well in blocking anti-adblock scripts in Websites . Now as per new update almost all the sites are reconigising the anti adblock scripts and adblocks. Plz fix this .. And i am the donator of the program also so plz fix this 
![anti adblock detected](https://cloud.githubusercontent.com/assets/15843175/11162247/1aec230c-8ac1-11e5-8919-4d9cc5bfa2ee.jpg)
![untitled](https://cloud.githubusercontent.com/assets/15843175/11162249/1f85ea38-8ac1-11e5-9d00-eb7f79b0bed0.jpg)

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/734

**Comment by fabiobarao94** [comment]
it's now fixed use, adblock plus with adblock killer filter and use tempermonkey with adblock killer also
it works, i don't get any of those messages

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
