### ISSUE TITLE
thesimsresource.com

### ISSUE THREAD

**Issue by Legitness** [reek/anti-adblock-killer#747]
http://www.thesimsresource.com/
http://imgur.com/tzrnSbQ
Google Chrome 
TamperMonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,

Thanks, I will study your request, you will be informed that a solution is available.

In the meantime, consider making a donation.

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by fabiobarao94** [comment]
Hey just add this on your filters 
@@||d2kkl4buashh8c.cloudfront.net/ads/ads.js
this will allow the script to run and adblock will not be detected, and no ads either

**Comment by fabiobarao94** [comment]
Hey just add this on your filters 
@@||skidrowcrack.com/adsense.js
@@||skidrowcrack.com/adblockchecker.js
this will allow the script to run and adblock will not be detected, and no ads either

**Comment by fabiobarao94** [comment]
Hey for the web site http://www.thesimsresource.com/ just add this on your filters 
@@||d2kkl4buashh8c.cloudfront.net/ads/ads.js
this will allow the script to run and adblock will not be detected, and no ads either

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
