### ISSUE TITLE
filmovizija.co

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#748]
Hi,
on `http://www.filmovizija.co/`

![filmovizija](https://cloud.githubusercontent.com/assets/1873139/11166109/f3c6061a-8b26-11e5-9f59-287257b86258.png)

`@@||filmovizija.co/advertise.js$script`
Thanks!

**Comment by reek** [comment]
Thanks Med ::smile::

**Comment by fabiobarao94** [comment]
why you need  to put in the end $script ?, without that works too

**Comment by fabiobarao94** [comment]
hey and what this means ||
and this ^
please help iv'e read the adblock syntax but can't understand

**Comment by SMed79** [comment]
@fabiobarao94 
**Specifying filter options** https://adblockplus.org/filters#options
**Matching at beginning/end of an address** https://adblockplus.org/filters#anchors

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
