### ISSUE TITLE
skidrowcrack.com

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#749]
looks like skidrowcrack has changed their anti-adblock detection.
it is now displaying a pop-up:

URL:
http://www.skidrowcrack.com/

**Comment by reek** [comment]
Ok, i will take a look

**Comment by Anonim47** [comment]
The script anti adblock located at skidrowcrack.com/adblockchecker.js
Please add it into current filters :smile:

**Comment by reek** [comment]
Ok, thanks

2015-11-16 8:32 GMT+01:00 Yosef Adi Sulistyo <notifications@github.com>:

**Comment by fabiobarao94** [comment]
well i added but still anything @@||skidrowcrack.com/adblockchecker.js

**Comment by fabiobarao94** [comment]
Hey just add this for the website http://www.skidrowcrack.com/ on your filters 
@@||skidrowcrack.com/adsense.js
@@||skidrowcrack.com/adblockchecker.js

this will allow the script to run and adblock will not be detected, and no ads either

**Comment by callmenemo491** [comment]
perfect!  thanks!  tested it works!

**Comment by fabiobarao94** [comment]
you're welcome

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
