### ISSUE TITLE
kisscartoon.me

### ISSUE THREAD

**Issue by Spazturtle** [reek/anti-adblock-killer#750]
Domain: http://kisscartoon.me/*

Kisscartoon is currently detecting ad-block, likely uses a similar detection method to kissanime.to

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Spazturtle** [comment]
User error, script was disabled for some reason.
