### ISSUE TITLE
javfor.me

### ISSUE THREAD

**Issue by hehe13** [reek/anti-adblock-killer#751]
http://javfor.me/90212.html#
http://i.imgur.com/fzOr6t4.png
Google Chrome - Version 46.0.2490.86 m
TamperMonkey
UBlock Origin
AakList

**Comment by MajkiIT** [comment]
solution
@@|http://serve.popads.net/checkInventory.php$script,domain=l1.jav4.me

**Comment by hehe13** [comment]
Im probably stupid, but how to I do this?


http://i.imgur.com/8GIgofg.png


Im still getting the block page.


Thanks for the prompt response btw.


________________________________

**Comment by MajkiIT** [comment]
Put It on own rules/filters .

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
