### ISSUE TITLE
vtele.ca

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#752]
Hi,
on `http://vtele.ca/videos/l-arbitre/il-ne-faut-pas-juger-les-parents-trop-vite_85608.php`
![vtele.ca](https://cloud.githubusercontent.com/assets/1873139/11182038/e9587680-8c67-11e5-9df0-80a011336d6d.png)

`@@||cdn.adgear.com/a/adgear.js/current/adgear.js$script,domain=vtele.ca`

Thanks!

**Comment by reek** [comment]
Ok, thanks Med ::smile::

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
#790 #612 

![vtele.ca](http://i.imgur.com/vH9UoJC.png)

`@@||static-v.com/lib/js/_source/blockadblock.js$script,domain=vtele.ca`

**Comment by reek** [comment]
@SMed79 
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
