### ISSUE TITLE
aseanlegacy.net

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#753]
http://aseanlegacy.net/cbox.html

![image](https://cloud.githubusercontent.com/assets/15664251/11190491/b12a0b22-8c8d-11e5-8c9a-241352787038.png)

my browser google chrome, adblocker with AakList, and script Anti adblocker killer for tempermonkey
I already added 
@@||aseanlegacy.net/adsense/ads.png
@@||aseanlegacy.net/assets/*/*/advertisement.php$script

but still does not present the cbox content anyone knows please
i've anylized the code over and over again, but can't find a way

**Comment by fabiobarao94** [comment]
HAAA Sorry guys i already solve it, if anyone has the same problem i leave here the way to correct the problem in your filter list add this:
@@||aseanlegacy.net/assets/*.
it will work
the other 2 above doesn't work this @@||aseanlegacy.net/adsense/ads.png
@@||aseanlegacy.net/assets///advertisement.php$script or @@||aseanlegacy.net/assets///advertisement.php
does not work you need to put only this line @@||aseanlegacy.net/assets/*.
and it's done

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
