### ISSUE TITLE
vipbox.biz

### ISSUE THREAD

**Issue by nicknacnic** [reek/anti-adblock-killer#754]
This is a website that streams many sports games, and can detect adblock plus. Although unlike other websites, it asks the user to uninstall adblock, not just pause it. Any help? Cheers

http://vipbox.biz/

~N

**Comment by nicknacnic** [comment]
Link: http://vipbox.biz <http://vipbox.biz/>
Screenshot:

Browser: Chrome  version 46.0.2490.86
Scriptmanager: TamperMonkey version 3.12
Adblocker: AdBlock version 2.43
Filterlists: Youtube Center, Anti-Adblock Killer

A note about vipbox… click on a sport tab (I picked american football just to demonstrate tonight), find a game, click the link, and that’s how to get to one page of the site. If there’s any way I can help, please let me know.

Cheers,

Nic

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by nicknacnic** [comment]
Reek,

Thank you for resolving the VIPbox link so fast, excellent work. From the same link, vipbox.biz, when you click the tennis tab, it redirects to a site: http://sport.streams.tv/tennis/1216873 <http://sport.streams.tv/tennis/1216873>. And this link says underneath that “*stream may be available in other countries.” If you know of a country filter block userscript, or can get it done, please let me know. 

I have the same info as last time, which will be below with the screenshot:

Browser: Chrome  version 46.0.2490.86
Scriptmanager: TamperMonkey version 3.12
Adblocker: AdBlock version 2.43
Filterlists: Youtube Center 2.1.7, Anti-Adblock Killer version 8.8




If there’s anything else you need, please let me know. Thanks in advance.

Cheers,

Nic

**Comment by reek** [comment]
Hi,

the solution is to use a VPN

2015-11-23 15:55 GMT+01:00 nicknacnic <notifications@github.com>:

**Comment by nicknacnic** [comment]
I think vipbox.biz is playing a game of cat and mouse, any suggestions? 

Browser: Chrome  version 46.0.2490.86
Scriptmanager: TamperMonkey version 3.12
Adblocker: AdBlock version 2.43
Filterlists: Youtube Center, Anti-Adblock Killer

**Comment by nicknacnic** [comment]
I think vipbox.biz is playing a game of cat and mouse, any sugg 

Browser: Chrome  version 46.0.2490.86
Scriptmanager: TamperMonkey version 3.12
Adblocker: AdBlock version 2.43
Filterlists: Youtube Center, Anti-Adblock Killer
