### ISSUE TITLE
cnews.ru

### ISSUE THREAD

**Issue by ivanb-spb** [reek/anti-adblock-killer#760]
![adblock](https://cloud.githubusercontent.com/assets/15933607/11287265/553de022-8f2b-11e5-90fb-2189c906d2ea.png)

a. URL: http://www.cnews.ru/news/top/2015-11-19_microsoft_otkryla_kod_sredy_razrabotki_oblachnyh

DIV ID of pop-up object dynamically changes every time you load a page. Does not pop-up on the main cnews.ru page.

b. browser: google chrome

c. script manager: tampermonkey

d.blocker: Adblock

e. filter: AAklist

**Comment by SMed79** [comment]
Hi,
try to add: 
```
@@.png#$image,domain=cnews.ru
@@||cnews.ru^$elemhide
```

**Comment by ivanb-spb** [comment]
it works, thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by ememoho** [comment]
a. http://www.cnews.ru/news/top/2016-01-07_amerikanskij_servis_prosmotra_serialov_stal_dostupen
b. Mozilla Firefox 43.0
c. Greasemonkey 3.6
d. uBlock Origin 1.5.3
e. AakList

The current script v 9.0 does not appear to be killing the paywall on cnews.ru articles at this time.
Adding the lines suggested in the first comment to 'My filters' in uBlock works as a charm, though.

**Comment by reek** [comment]
@ememoho 
Have you subscribed to AakList ?

**Comment by ememoho** [comment]
@reek 
Yes, I have added and enabled the subscription, it is listed under the 'Custom' section of 3rd-party filters: "AakList (Anti-Adblock Killer)‎ : 1,346 used out of 1,398"

The list URI is https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
and it is of the actual version 9.0, however, I cannot find any rules for cnews.ru in it.

**Comment by reek** [comment]
@ememoho 
For me it's killed by AakScript, no need adblock rules

**Comment by ememoho** [comment]
@reek 
Odd. Just reproduced this on a clean browser profile.

1. Installed NoScript, Greasemonkey, uBlock Origin - restarted.
2. Added the AakScript from greasyfork
3. Opened a cnews.ru article (temp. allow scripts for this site in NoScript)
…
The paywall appeared.
Looks like NoScript is interfering somehow.

If I 'temporarily allow all this page' the paywall does not appear.
If I revoke all temp permissions, but leave only cnews.ru allowed, there is no pop-up.
Going from all restricted to only cnews.ru allowed, I get a pop-up.

This is not reproduced if external scripts are blocked via uMatrix.

**Comment by reek** [comment]
@ememoho 
Remove NoScript.

**Comment by ememoho** [comment]
@reek 
That's one option, I guess… Thanks for looking into this.
Sorry for bumping an issue without properly checking it beforehand.
