### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#761]
banner can't be block it seems they have generators for class

![image](https://cloud.githubusercontent.com/assets/15664251/11288350/1f9fda48-8f1b-11e5-8fe5-6653aa6e2af3.png)

a block them but still goes on
![image](https://cloud.githubusercontent.com/assets/15664251/11288359/37143944-8f1b-11e5-8a86-1045dbe942b3.png)

any way to get rid of it, or i need to create a wordlist with all cominations possible  codes and block all of them

**Comment by SMed79** [comment]
Hi,
already blocked with EasyList with these filters:
```
###ad1-placeholder
opensubtitles.org##.msg.hint
opensubtitles.org##.msg.star
opensubtitles.org##.right_side_fixed
/ads2.
/ads2.
||beatchucknorris.com^$third-party
/ad_slideout.
||bulletproofserving.com^$third-party
||opensubtitles.org/gfx/banners_campaigns/
||bulletproofserving.com^$third-party
```
Please repport non blocked ad **EasyList** forum https://forums.lanik.us/viewforum.php?f=62

**Comment by fabiobarao94** [comment]
that doesn't work at all just removes a portion, the big button ""WATCH NOW" still appears
they created a way to generate new codes for class every time the page is refresh
with the base64 hexadecimal
i've discovered another way to block them permanently
i put this
www.opensubtitles.club##LEGEND   -> this will remove the button remove ads
opensubtitles.club##IMG[src^="data:image/jpeg;base64"]     -> this will block all generated codes
opensubtitles.club##A[target="_blank"]

and i still block all scripts that the page loads,
like

http://static.opensubtitles.club/libs/js/ad_slideout.js?1
http://static.opensubtitles.club/libs/js/lscache.min.js
http://static.opensubtitles.club/libs/js/jquery.timeago/locales/jquery.timeago.pt.js
http://static.opensubtitles.club/libs/js/jquery.timeago/jquery.timeago.js
http://www.google.com/uds/solutions/videobar/gsvideobar.js?mode=new
http://www.google-analytics.com/analytics.js
etc...

result, the page loads faster and i can make download pretty fast


and i get this
![image](https://cloud.githubusercontent.com/assets/15664251/11303887/4830dc46-8f9d-11e5-82cc-af97c2cd643c.png)

**Comment by fabiobarao94** [comment]
and now it's not opensubtitles.org it's opensubtitles.club

**Comment by SMed79** [comment]
- Save your bookmarks/password.
- Reset your browser settings: 

**FF** https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings 
**Ch** https://support.google.com/chrome/answer/3296214?hl=en
- Install **Adblock Plus** https://adblockplus.org/

**Comment by fabiobarao94** [comment]
I have adblock plus
gogole chrome 
this works for me, theres no ads anymore with this

opensubtitles.org##[src^="data:image/jpeg;base64"] -> this will block all jpg generated codes
opensubtitles.club##IMG[src^="data:image/jpeg;base64"] -> this will block img jpeg generated codes
opensubtitles.org##A > IMG[src^="data:image/gif;base64"] -> this will block all gif generated codes
opensubtitles.org##.right_side_fixed > A
opensubtitles.org##TR > TD[colspan="9"]
opensubtitles.org##[style^="z-index: 99999; position: fixed; width: 100%;"]
opensubtitles.club##LEGEND -> this will remove the button remove ads
opensubtitles.club##A[target="_blank"]
opensubtitles.club##.msg.hint
opensubtitles.club##.msg.star
opensubtitles.club##.right_side_fixed
||bulletproofserving.com^

**Comment by SMed79** [comment]
no ads for me with **Easylist** without adding your filters.

**Comment by fabiobarao94** [comment]
the page is http://www.opensubtitles.club/pt/subtitles/6389092/arrow-brotherhood-pb
try open that and refresh  see if ads appear

**Comment by fabiobarao94** [comment]
hey i got a new way and much better
here
opensubtitles.org##IMG[src*="data:image/jpeg;base64"] 
opensubtitles.org##IMG[src*="data:image/jpg;base64"]
opensubtitles.org##img[src*="data:image/gif;base64"]
opensubtitles.org##DIV.content[style="position:relative;"] > A
opensubtitles.org###setofavi > DIV > DIV:first-child
opensubtitles.org##TR > TD[colspan="9"]
opensubtitles.org##[itemscope] > FIELDSET:first-child
opensubtitles.org##DIV + FIELDSET:last-child
||bulletproofserving.com^

![image](https://cloud.githubusercontent.com/assets/15664251/11306575/b041502e-8faa-11e5-851f-bd679ae0d538.png)

**Comment by fabiobarao94** [comment]
for the .club

opensubtitles.club##IMG[src*="data:image/jpeg;base64"] 
opensubtitles.club##IMG[src*="data:image/jpg;base64"]
opensubtitles.club##img[src*="data:image/gif;base64"]
opensubtitles.club##DIV.content[style="position:relative;"] > A
opensubtitles.club##[itemscope] > FIELDSET:first-child
opensubtitles.club##DIV + FIELDSET:last-child
opensubtitles.club##.right_side_fixed > A
opensubtitles.club##TR > TD[colspan="9"]
opensubtitles.club##[style^="z-index: 99999; position: fixed; width: 100%;"]
opensubtitles.club##LEGEND
opensubtitles.club##A[target="_blank"]
opensubtitles.club##.msg.hint
opensubtitles.club##.msg.star
||bulletproofserving.com^


![image](https://cloud.githubusercontent.com/assets/15664251/11306831/29657ce0-8fac-11e5-9413-0923ecbcd6fe.png)

**Comment by SMed79** [comment]
NON ads !
![aaaaaaaaa](http://i.imgur.com/fhzCGdD.png)

**Comment by reek** [comment]
@fabiobarao94
I had ads, but it was enough to make an update of my lists to see them disappear

**Comment by fabiobarao94** [comment]
yes i've noticed that now the filters have been updated and when i remove my own filters theres is no ads but before they were appearing so i done those filters
