### ISSUE TITLE
vipboxtv.co

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#765]
Hi,
on `http://es.vipboxtv.co/`

![es.vipboxtv.co](https://cloud.githubusercontent.com/assets/1873139/11312488/add22882-8fd6-11e5-903e-327e49edae76.png)

`@@|http://*$script,third-party,domain=es.vipboxtv.co`

**Comment by reek** [comment]
ok thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
