### ISSUE TITLE
forum.kardiolo.pl

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#766]
http://forum.kardiolo.pl/temat14314.htm

http://imgur.com/K1K6Mss

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

 either i lost last fix from MajkiIT or the code change

**Comment by xxcriticxx** [comment]
MajkiIT check rest of sub forums 

here is another adblock detected 

https://parenting.pl/portal/zatrucie-pokarmowe-u-dziecka-sprawdz-co-zrobic

**Comment by MajkiIT** [comment]
@xxcriticxx Thanks for your issue. I fixed it. Update polish filters.

**Comment by MajkiIT** [comment]
@reek Please close this issue. It's my mistake.

**Comment by reek** [comment]
@
