### ISSUE TITLE
FiveThirtyEight problem

### ISSUE THREAD

**Issue by pedrokleiz** [reek/anti-adblock-killer#767]
I was visting [FiveThirtyEight] (https://fivethirtyeight.com/features/how-data-nerds-found-a-131-year-old-sunken-treasure/) when I found this problem, if you need more data I can find it for you.
<img width="1042" alt="screen shot 2015-11-20 at 22 56 45" src="https://cloud.githubusercontent.com/assets/6828704/11316566/2e2534e0-8fda-11e5-90bc-2965f2edae97.png">
Bet Regards,
Pedro

**Comment by reek** [comment]
HI,
Yes i need more informations
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
