### ISSUE TITLE
phys.org

### ISSUE THREAD

**Issue by Havatra** [reek/anti-adblock-killer#768]
http://phys.org/news/2015-11-quantum-entanglement-room-temperature-semiconductor.html
http://i.imgur.com/MRJgWir.jpg
Google Chrome 45.0.2454.99
Greasemonkey
AdBlock
AakList

Anti-Adblock script on this page: http://cdn.phys.org/tmpl/v5/js/main.min.2.5.js

**Comment by MajkiIT** [comment]
Try this
phys.org#@#.adsbygoogle
@@|http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=phys.org

**Comment by reek** [comment]
@MajkiIT 
your rules are not good, but I have a solution with AakScript

**Comment by MajkiIT** [comment]
@reek sorry

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
