### ISSUE TITLE
securenetsystems.net

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#770]
Hi, 
on `http://streamdb4web.securenetsystems.net/v5/index.cfm?stationCallSign=WKIT&retry=true`

![securenetsystems](https://cloud.githubusercontent.com/assets/1873139/11319329/d2be47ba-9072-11e5-9db2-6e6c640c62a9.png)

`@@||securenetsystems.net/*/scripts/adv.js$script,~third-party`

Thanks!

**Comment by reek** [comment]
Thanks Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
