### ISSUE TITLE
cwtv.com

### ISSUE THREAD

**Issue by basildane** [reek/anti-adblock-killer#771]
http://www.cwtv.com/shows/supernatural/plush/?play=9327a462-63fb-49c5-862d-fe3ed0ad4733
http://imgur.com/gallery/Qfpa9Pu
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/762

**Comment by basildane** [comment]
Thanks, that worked.
I am interested in learning your API so I start fixing things myself if necessary.  Any docs anywhere?
