### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by Qwerty-Space** [reek/anti-adblock-killer#772]
http://antiblock.org/?p=v3&demo
http://i.imgur.com/axjhy4i.png
Google Chrome
TamperMonkey
uBlock Origin
Fanboy+Easylist-Merged Ultimate List + AakList

---------------------------------------------------------------------------------------------------------------------------------

I don't know if it is working correctly on the test site.  But it isn't working on http://kissanime.to

A few questions:
Do I need to disable JavaScript?

I have enabled it in uBlock:
http://i.imgur.com/vOGFPr0.png
And I have the script in TamperMonkey:
http://i.imgur.com/2oQzJuv.png
Have I done it right?

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/734

**Comment by sIips** [comment]
^
https://github.com/reek/anti-adblock-killer/issues/734

Consult to this thread to clear the issue .

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
