### ISSUE TITLE
redundant rule

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#774]
@@||cdn.adgear.com/a/adgear.js/current/adgear.js$script,domain=vtele.ca has been made redundant by @@||cdn.adgear.com/a/adgear.js/current/adgear.js$domain=vtele.ca

**Comment by reek** [comment]
thanks

2015-11-23 12:55 GMT+01:00 Maciej M. <notifications@github.com>:

**Comment by MajkiIT** [comment]
verdirectotv.com##div[id^="capaoverlay"] has been made redundant by verdirectotv.com##div[id^="capa"]

**Comment by MajkiIT** [comment]
Finished (after 2 seconds)!  4 redundant rules found!
verdirectotv.com##div[id^="capaoverlay"] has been made redundant by verdirectotv.com##div[id^="capa"]
foot-live.info###timer1 has been made redundant by streaming-foot.info,stream-foot.tv,foot-live.info##[id^="timer"]
foot-live.info###timer2 has been made redundant by streaming-foot.info,stream-foot.tv,foot-live.info##[id^="timer"]
foot-live.info###timer3 has been made redundant by streaming-foot.info,stream-foot.tv,foot-live.info##[id^="timer"]

**Comment by reek** [comment]
Thanks ;)

2015-12-22 18:07 GMT+01:00 Maciej M. <notifications@github.com>:

**Comment by reek** [comment]
Optimized !
