### ISSUE TITLE
jeu-concours.biz

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#775]
Hi,

![jeu-concours biz](https://cloud.githubusercontent.com/assets/1873139/11342162/31d6fa00-9206-11e5-86a7-854c6b0703d6.png)

on `http://www.jeu-concours.biz/nouveaute.php?journee=2015-11-18`

`@@||jeu-concours.biz/show_ads.js`

Thanks!

**Comment by reek** [comment]
ok, thanks

2015-11-23 17:19 GMT+01:00 Med <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
