### ISSUE TITLE
dpstream.net [ads]

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#776]
Hi;
can **AaKiller** script block ads on `http://www.dpstream.net/` provided by `goyavelab.com` ?
check if an pixel ad image is blocked on an iframe if yes reload **/?noduve** and display their ads.

![dpstream.net](https://cloud.githubusercontent.com/assets/1873139/11342432/b25eeb5a-9207-11e5-8d7f-c33d4363dec7.png)

![goyavelab](https://cloud.githubusercontent.com/assets/1873139/11342859/a3254e98-9209-11e5-95bc-cf31cef451e4.png)

also an overlay ads on embedded **PureVis** videos !
`http://www.dpstream.net/manga-2-naruto-shippuden-episode-438-VOSTFR.html`

![PureVis](https://cloud.githubusercontent.com/assets/1873139/11342693/eb969cd2-9208-11e5-99e1-8a8f149b03e9.png)

```
var PHENV = {}; PHENV.URL_SEARCH = window.location.search; var uniqueParam="noduve";
```

```
function __$dtctI(t) {
  null == PHENV.dtctDomain && (PHENV.dtctDomain = t, window.addEventListener("message", function(t) {
    -1 != (t.origin + "/").indexOf("//www." + PHENV.dtctDomain + "/") && t.data && PHENV.onDetection()
  }))
}
PHENV.getParams = function() {
  var t = window.location.search.substr(1);
  t = t.split("&");
  for (var n = new Array, e = 0; e < t.length; e++) {
    var o = t[e],
      i = o.indexOf("="),
      c = o,
      d = "";
    i > -1 && (c = o.substr(0, i), d = o.substr(i + 1)), n[c] = d
  }
  return n
}, PHENV.onDetection = function() {
  PHENV.onDetection = function() {};
  var t = PHENV.URL_SEARCH.indexOf(uniqueParam) > -1;
  if (t) window.PHXNBL_CB && PHXNBL_CB();
  else for (var n in location) 0 == n.indexOf("search") && 6 == n.length && (location[n] = PHENV.URL_SEARCH + (PHENV.URL_SEARCH.length > 1 ? "&" : "") + uniqueParam)
}, PHENV.dtctDomain = null,
function() {
  window.ec_check ? PHENV.onDetection() : navigator.userAgent.match("Kitt/[0-9]") ? PHENV.onDetection() : document.addEventListener && document.addEventListener("DOMContentLoaded", function() {
    var t = function(t) {
      t.parentElement.removeChild(t)
    }, n = document.createElement("script");
    n.setAttribute("src", "http://dtf.goyavelab.com/dtct.js"), n.addEventListener("load", function() {
      t(this)
    }), n.addEventListener("error", function() {
      t(this), PHENV.onDetection()
    }), null == document.body && (document.body = document.createElement("body")), document.querySelector("head").appendChild(n)
  })
}();
```

Thanks!

**Comment by SMed79** [comment]
New filter options in Adblock Plus !
https://adblockplus.org/development-builds/new-filter-options-generichide-and-genericblock
- **$generichide** (to disable all global hiding filters on a specific domain).
- **$genericblock** (to disable all global blocking filters on a specific domain).

dpstream.net >>> https://hg.adblockplus.org/listefr/rev/349e155c4871

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Anti adblock redirect to `/explication-adblock.html`

**Comment by reek** [comment]
@SMed79 
Already killed by AakScript (fuckadblock)
