### ISSUE TITLE
exrapidleech.info

### ISSUE THREAD

**Issue by MUFTAKiS** [reek/anti-adblock-killer#777]
this site give me captcha when visiting it then redirect to this message
"For support us maintain the service please disable ads blocking on our site"

**Comment by muhasturk** [comment]
+1

**Comment by reek** [comment]
Hi,

I will fix it, thanks

**Comment by yoshimo** [comment]
```
        <script>
            var dec_pid = false;
            bdvbnr_pid = false
        </script>
        <script src="http://bdv.bidvertiser.com/BidVertiser.dbm?pid=383865&bid=1021019" type="text/javascript"></script>
        <noscript><a href="http://www.bidvertiser.com/bdv/BidVertiser/bdv_xml_feed.dbm">xml search</a></noscript>
        <script>
            if (dec_pid !== 383865 || bdvbnr_pid === false) {
                document.location = 'http://www.exrapidleech.info/verify.php';
            };
        </script>
        <script>
            $(document).ready(function() {
                setTimeout(function() {
                    try {
                        frbid = $('iframe[id*=bdv]')[0].contentWindow;
                        if (frbid.document.URL === "about:blank") {
                            document.location = 'http://www.exrapidleech.info/verify.php';
                        }
                    } catch (err) {
                        console.log(err);
                    }
                }, 500);
            });
        </script>
```
Is the responsible redirect code

**Comment by MUFTAKiS** [comment]
i think if captcha removed the redirection will be removed too

**Comment by reek** [comment]
@yoshimo 
I know, I'll post soon a fix

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MUFTAKiS** [comment]
nothing changed still i get captcha!!

i dont know why you say every time updated and its not?!!

**Comment by reek** [comment]
@MUFTAKiS 
I can not remove the captcha it is to block the bot.

**Comment by MUFTAKiS** [comment]
just useless i still get the redirection and captcha!!

**Comment by reek** [comment]
@MUFTAKiS 
I know https://github.com/reek/anti-adblock-killer/issues/830

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
