### ISSUE TITLE
cloudyvideos.com

### ISSUE THREAD

**Issue by jefro108** [reek/anti-adblock-killer#781]
http://cloudyvideos.com
http://imgur.com/JmAMdhR
Google Chrome Mac
uBlock Origin
AakList + Adblock Warning Removal List + Peter Lowe’s Ad server list‎ + EasyList‎

**Comment by MajkiIT** [comment]
Use AAK Scripts.

**Comment by jefro108** [comment]
I'm using Anti-Adblock Killer | Reek‎  in uBlock Origin. Is there something else I need to do?

**Comment by MajkiIT** [comment]
https://github.com/reek/anti-adblock-killer/blob/master/README.md

Step 1 and 3

**Comment by jefro108** [comment]
Thanks, it works now.

I may have been confused by "Note: uBlock Origin, you need just enable AakList on Options -> 3rd-party-filters and "Apply changes"." into thinking I only needed to use uBlock Origin by it saying "you need just enable AakList..." :(

**Comment by reek** [comment]
@jefro108 
Antiblock used on cloudyvideos require AakScript, I'll replace 'need just' by 'must'. 

Note: AakList & AakScript are complementary each unblocked different websites.

**Comment by jefro108** [comment]
@reek 
Great. Thanks for all your hard work.

**Comment by reek** [comment]
@jefro108 
::smile::
