### ISSUE TITLE
Error [object Text] not removed !

### ISSUE THREAD

**Issue by tntc4** [reek/anti-adblock-killer#782]
Aak8.8 ["legacyclix.com", ["Error [object Text] not removed !"]] Anti-Adblock_Killer_%257C_Reek.user.js (line 264)

I see this error on almost every site.
![Screen Shot](http://s26.postimg.org/kp7eq3zg9/Screenshot_1.png)
Link to Screen Shot http://s26.postimg.org/kp7eq3zg9/Screenshot_1.png

Mozilla Firefox 42.0
Greasemonkey 3.6 + Anti-Adblock Killer | Reek 8.8

**Comment by hassanila97** [comment]
I have the same problem from the latest update... :(

**Comment by reek** [comment]
Ok, thanks i will fix it

2015-11-25 14:17 GMT+01:00 hassanila97 <notifications@github.com>:

**Comment by hassanila97** [comment]
Sorry but for me it's even worse now after the update....

**Comment by reek** [comment]
@hassanila97 
https://github.com/SuperGouge/anti-adblock-killer/raw/bbbe868ae64c14aba7d751a7d1d81a58ba98b676/anti-adblock-killer.user.js
