### ISSUE TITLE
tzetze.it (beppegrillo.it)

### ISSUE THREAD

**Issue by genox87** [reek/anti-adblock-killer#784]
http://www.tzetze.it/redazione/2015/11/il_su-24_russo_non_volava_sui_cieli_turchi/
http://imgur.com/KX61gg5
Google Chrome
uBlock
EasyList + AakList + ABP X Files + EasyList Italy

Source antiblock
http://www.beppegrillo.it/la_cosa/embed/39753

**Comment by yoshimo** [comment]
```
	<script type="text/javascript">

		function adBlockDetected() {
			console.log("ADBlock Detected");
			jQuery("#message").css('display', 'none').before('<img src="http://d2ddakkt2rzmi5.cloudfront.net/noab.jpg" style="width: 100%;" />');
		}
		function adBlockNotDetected() {
			console.log("No ADBlock");
		}
		
		//<![CDATA[
		jQuery(window).load(function(){

			//Display ADBlock Warning
			if(typeof cadetect=== 'undefined') {
				adBlockDetected();
			} else {
				cadetect.onDetected(adBlockDetected).onNotDetected(adBlockNotDetected);
			}
		});
		//]]>
	</script>
````
I assume killing adBlockDetected() and making sure cadetect isn't undefined should do it.

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Add the following js to the 'rules' section of @reek 's script:
```javascript
    beppegrillo_it : {
        // issue: https://github.com/reek/anti-adblock-killer/issues/784
        host : ['beppegrillo.it'],
        onStart : function () {
            Aak.addScript(function () {
                var cadetect = {
                    onDetected : function () { return this },
                    onNotDetected : function () { return this }
                };
            });
        }
    },
```

**Comment by reek** [comment]
@skr4tchGr3azyMonkiBallllllZzzz 
Good job :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
