### ISSUE TITLE
topserialy.sk

### ISSUE THREAD

**Issue by Horkyze** [reek/anti-adblock-killer#785]
The anti-adblock starts working when you want to watch any video. It probably has to do something with openload.io. Example video url: http://www.topserialy.sk/serialy/the-flash-s02e03
![screen](http://i.imgur.com/yAUft7x.png)
Chrome + Tampermonkey + AdBlock 

Filters: 
Acceptable Ads 
AdBlock custom filters 
EasyList 
AdBlock Warning Removal list 
Antisocial filter list 
EasyPrivacy 
Fanboy's Annoyances 
Malware protection
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

**Comment by reek** [comment]
Hi,
Fix <code>@@||topserialy.sk/js/scripts/ad.js$script</code>

**Comment by Horkyze** [comment]
I've forked your repo and added this line into anti-adblock-killer-filters.txt, updated the list in ad block to use my url, but it doesn't seem to work. I do however get this output in console:

Aak8.8 (2)
"www.topserialy.sk"
Arguments ["AdvertisementJs", "www.topserialy.sk", "http://www.topserialy.sk/js/scripts/advertisement.js"]

I am missing something?

**Comment by reek** [comment]
in this case you have to wait I put a new version of AakList

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Horkyze** [comment]
I am sorry to report it again, but its not working.

**Comment by reek** [comment]
@Horkyze 
Try update manually AakList

**Comment by Horkyze** [comment]
Worked, thanks. However when I click play, it still opens some ads is new window. Is that relevant to Aak? If no do you have any recommendation how to stop it?

**Comment by reek** [comment]
@Horkyze
actually, openload appears to block the video after a few seconds

**Comment by jackdizajn** [comment]
The anti-adblock starts working when i see this. Somefing is wrong :(
Where is problem ?
Example video url:
http://www.topserialy.sk/serialy/mike-molly-s01e01

**Comment by reek** [comment]
@jackdizajn 
I'll fix it, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by adoww** [comment]
Hello,

webpage has changed to topserialy.to  and the script doesn't work.

Please check.

Thanks.
addow
