### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by Keepermaster** [reek/anti-adblock-killer#788]
http://www.tek.no/artikler/test-asus-pb287q/160700
http://imgur.com/D0F8UVq
Google Chrome
Tampermonkey
Adblock
Aaklist

**Comment by simonkaspersen** [comment]
Second that. They have changed strategies about the blocking

**Comment by reek** [comment]
Hi,

I will fix it

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
***Add:***
```javascript
      onStart : function () {
          Aak.addScript(function () {
              gg = true;
          });
      }
```
**to the `tek_domains` section of @reek 's script:**
```javascript
    tek_domains : {
      // by: Alexander255
      // issue: https://github.com/reek/anti-adblock-killer/issues/512
      // issue: https://github.com/reek/anti-adblock-killer/issues/788
      host : ['tek.no', 'gamer.no', 'teknofil.no', 'insidetelecom.no', 'prisguide.no', 'diskusjon.no', 'teknojobb.no', 'akam.no', 'hardware.no', 'amobil.no'],
      onIdle : function () {
        var ad_frame = document.createElement("iframe");
        ad_frame.name = "_frame";
		ad_frame.style.display = "none";
        document.body.appendChild(ad_frame);
		ad_frame.contentWindow.wrappedJSObject.inFIF = true;
      },
      onStart : function () {
          Aak.addScript(function () {
              gg = true;
          });
      }
    },
```

**Comment by reek** [comment]
@skr4tchGr3azyMonkiBallllllZzzz 
thank you, but I already have a fix.

you can help by fixing issues without a label or with label no solution. because when I add the label is that I have already forecast a solution.

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Ok, got it :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
