### ISSUE TITLE
animeheaven.eu

### ISSUE THREAD

**Issue by Jolo248** [reek/anti-adblock-killer#789]
Anti-Ad blocker does not work on this website :P
http://animeheaven.eu/watch.php?a=Chaos%20HEAd%20Dubbed&ep=12

Thank you! :D

**Comment by reek** [comment]
Hi,

I will take a look

See you
Reek

**Comment by maynak00** [comment]
removed adblocker detected message with
@@||animeheaven.eu/a/showads.*$script,first-party

**Comment by Jolo248** [comment]
Do I need to paste this somewhere? :O

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
