### ISSUE TITLE
vtele.ca

### ISSUE THREAD

**Issue by mikhoul** [reek/anti-adblock-killer#790]
http://vtele.ca/videos/en-mode-salvail/francois-perusse-parodie-en-mode-salvail_86015.php

<ins>ABP is detected under Firefox 42 Win Greasemonkey (latest).</ins>

**Video don't start untill you shut off ABP**

Here's what I've found: 
![http://i.imgur.com/Ms8GaOP.png](http://i.imgur.com/Ms8GaOP.png)

But I don't have enough knowledge to bypass the detector  :crying_cat_face:

Best Regards !

**Comment by SMed79** [comment]
https://github.com/reek/anti-adblock-killer/issues/752#issuecomment-181545194
