### ISSUE TITLE
javfor.me [NSFW]

### ISSUE THREAD

**Issue by SadisticBastard** [reek/anti-adblock-killer#791]
http://javfor.me
On every video, after about 10 or so seconds, this thing pops up over the video player.
![](http://l1.jav4.me/img/Disable-Adblock.png)
Now, I'm not a technical guy at all, and I know jackshit about code, so if it's a simple fix I'm sorry. Also, I'm using uBlock Origin and Google Chrome if that means anything.

**Comment by reek** [comment]
HI,

Just read instruction
https://github.com/reek/anti-adblock-killer#step-2-filterlist

See you
Reek
