### ISSUE TITLE
Ad-Defend: several new sites

### ISSUE THREAD

**Issue by TonyTough** [reek/anti-adblock-killer#792]
Here are several new sites using Ad-Defend and should be added to #467

main-spitze.de
wormser-zeitung.de
lampertheimer-zeitung.de
wiesbadener-tagblatt.de
buerstaedter-zeitung.de
wiesbadener-kurier.de
rhein-main-presse.de
allgemeine-zeitung.de

ariva.de

**Comment by reek** [comment]
Hi,

Ok thanks Tony ;)

**Comment by TonyTough** [comment]
spiegel.de

is also one more site to add.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
