### ISSUE TITLE
Tisoomi - Anti-Adblock

### ISSUE THREAD

**Issue by TonyTough** [reek/anti-adblock-killer#793]
The following sites are using Anti-Adblock script.
The ads look like Ad-Defend, but it is from Tisoomi:

rechtslupe.de
motorsport-total.com
infranken.de
autozeitung.de
formel1.de
fremdwort.de
inside-handy.de

script a little different for:
podcast.de
getvids.de
spielespielen24.de

Maybe a filter like that for Ad-Defend could be added?

**Comment by yoshimo** [comment]
an earlier approach a tisoomi  was https://gist.github.com/anonymous/a9b9956baf1d59a107c5 ,maybe the code is still relevant

**Comment by yoshimo** [comment]
I edited the script from the EasyList forum a bit https://gist.github.com/anonymous/c2389a1a3b76ca1a05e6
I am targeting the detect() function, but maybe there is a better way.

**Comment by TonyTough** [comment]
Hi,

here still more tisoomi sites:

aussenwirtschaftslupe.de
dialo.de
donnerwetter.de

**Comment by reek** [comment]
@TonyTough 
I will add these site, but could make a anti-adblock screenshot, because I have no message.

**Comment by TonyTough** [comment]
Here are screenshots from the first 3 sites in the first post:
There are 2 ads on each: one at the top, and the other on the right side
(ublock origin with standard filters and easylistGermany + AAK filter and script activated)

rechtslupe.de:
http://postimg.org/image/jzbsbfnq3/
motorsport-total.com:
http://postimg.org/image/cmwjkc4wx/
infranken.de:
http://postimg.org/image/3msju7umz/


Do you need also screenshots from all the other sites?

**Comment by reek** [comment]
@TonyTough 
Thanks for screenshots

This anti-adblock seems to work only when one has a German IP,

In effect adds advertisements when adblocker is detected instead of a message.

I may be found a generic solution, I'm going to do some testing and I would test you

**Comment by TonyTough** [comment]
Hi,

gorhill from uBlock has updated the ublock filters:
https://github.com/gorhill/uBlock/issues/993

"I could reproduce with a VPN.
One was not dependant on inline scripts, so I will leave it to the filter list manitainers: infranken.de."

The filter seems to be:
autozeitung.de,formel1.de,fremdwort.de,inside-handy.de,motorsport-total.com,rechtslupe.de##script:contains(window.tisoomi)

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
