### ISSUE TITLE
novamov.com

### ISSUE THREAD

**Issue by MED-PRO** [reek/anti-adblock-killer#795]
Hi,
Video streaming website www.novamov.com has implemented an Anti-Adblock method (Screenshot).
I hope you find a solution.
Thank you
Ubolck Origin 1.3.6+Easylist +Aak 8.8 
Tested link: http://www.novamov.com/video/708949ce84b2d
![scr](https://cloud.githubusercontent.com/assets/10789454/11451968/d1593de8-95d7-11e5-9068-55e39f5ad550.jpg)

**Comment by reek** [comment]
Hi,

Ok, i will take a look

See you
Reek

**Comment by rayman89** [comment]
This also happens on videoweed as well. Should I create an other issue or this is enough?

**Comment by reek** [comment]
@rayman89 
no, I just need a video link

**Comment by rayman89** [comment]
http://www.videoweed.es/file/882fe852565ce

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rayman89** [comment]
Thank you a lot.
