### ISSUE TITLE
Flymer.ru

### ISSUE THREAD

**Issue by COOLak** [reek/anti-adblock-killer#796]
![fireshot screen capture 083 - flymer i - flymer_ru_bin](https://cloud.githubusercontent.com/assets/8677627/11452906/6a416834-9608-11e5-8c2f-23a323aecfa8.png)
http://flymer.ru/bin (only viewable when registered, the website is in Russian)
It says "To view this website you need to turn off ad blocking".
I have Firefox 42, AdBlock Plus with the subscriptions "AdBlock warning removal list", "RuAdList+EasyList", "Aaklist (Anti-AdBlock Killer)", as well as GreaseMonkey with the script "Anti-Adblock Killer | Reek" installed.

To this day, this warning was bypassed by Anti-AdBlock Killer, but it seems they changed their anti-adblocker settings or something, and now again I can't use this website without turning off AdBlock Plus. Please look into it, thank you.

**Comment by reek** [comment]
Hi

No message for me, i have this on http://flymer.ru/bin
<pre>
В корзине хранится до 20 переписок, где Вы прочли новое сообщение от собеседника, но ничего не ответили. В течение 24 часов Вы можете возобновить диалог, вернувшись к переписке и написав ответ. По истечении 24 часов короткие невозобновленные переписки автоматически удаляются. Долгосрочные сохраняются 30 дней.

Сейчас здесь пусто. 
</pre>

**Comment by COOLak** [comment]
Hmm, maybe try sending a note, and then when you get a reply, open the bin?

**Comment by COOLak** [comment]
Please type something in the text field there and press the purple button with "Запустить" on it. When a blue bar pops up in the right bottom part of the page (see this screenshot: http://s019.radikal.ru/i613/1512/6d/97c901f67976.png), please click the button above saying "корзина". And that adblock thing should pop up.

**Comment by reek** [comment]
Hi,
Sorry, I have no anti adblock and I do not understand Russian

**Comment by COOLak** [comment]
You don't have to understand Russian. Please watch this short video that I've made: https://youtu.be/y8dWpUfntiI

**Comment by COOLak** [comment]
Well, I even made a video, but you still marked it as "No Anti-Adblock Message". Ok.

**Comment by reek** [comment]
HI,

Well, let me see this video and give me information requested here
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by COOLak** [comment]
The video is above. Here it goes again: https://youtu.be/y8dWpUfntiI
Source code:
http://pastebin.com/mxBLWryJ
Extensions: http://pastebin.com/rFjjtees
User scripts: Anti-Adblock Killer | Reek 9.1
Blocked resources: http://imgur.com/aWLqpSu

**Comment by reek** [comment]
Hi,

I think I found a solution.

1. remove "Disable Anti-Adblock"
2. add these rules
<pre>
flymer.ru#@#.ad-unit
@@||pagead2.googlesyndication.com/pagead/show_ads.js$script,domain=flymer.ru
@@||pagead2.googlesyndication.com/pagead/js/r*/r*/show_ads_impl.js$script,domain=flymer.ru
</pre>

**Comment by COOLak** [comment]
Thank you. Just flymer.ru#@#.ad-unit was enough though. Adding the rest two makes the frames of google ads visible and they're trying to load forever. With only the first rule everything is perfect though: no ads, no frames, no anti adblock. Thanks again.

**Comment by reek** [comment]
Ok, I'll add it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by COOLak** [comment]
The issue returned with the same configuration, please look into it again and tell me what element should I disable this time, thank you.

**Comment by COOLak** [comment]
The issue somehow returned in exactly the same manner and there's no "flymer.ru#@#.ad-unit" thing anymore, they changed it. Could you look into it please?
