### ISSUE TITLE
nowvideo.sx/nowvideo.to

### ISSUE THREAD

**Issue by maklemenz** [reek/anti-adblock-killer#797]
nowvideo.sx/nowvideo.to implemented anti adblocking
Testlink: http://www.nowvideo.sx/video/e446aa5ab0b0e

**Comment by maklemenz** [comment]
Seems to be the same method as in #795

**Comment by reek** [comment]
Hi,

Ok, i will take a look

Thanks
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
