### ISSUE TITLE
www.wholecloud.net

### ISSUE THREAD

**Issue by maklemenz** [reek/anti-adblock-killer#798]
Testlink: http://www.wholecloud.net/video/7a5ec77442ef0
Seems to be the same technique used in #795, #797 
Used adblock with easylist on a chrome

**Comment by reek** [comment]
Hi,

Ok, i will take a look

Thanks
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
