### ISSUE TITLE
www.cloudtime.to

### ISSUE THREAD

**Issue by maklemenz** [reek/anti-adblock-killer#799]
They implemented anti adblock a few days ago.
Testlink: http://www.cloudtime.to/video/480d479855c91

Wouldn't be a problem if their ads wouldn't link to viruses and scam.

Thank you for this project!

**Comment by maklemenz** [comment]
Used adblock with easylist on a chrome

**Comment by reek** [comment]
Hi,

thank you for all the reporting I will unlock it all

**Comment by yoshimo** [comment]
``` @@||cloudtime.to/banner.php?* ```
seems to fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
