### ISSUE TITLE
darmowetv.pl

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#800]
https://darmowetv.pl/viewpage.php?page_id=6

http://imgur.com/aEuYCa8

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by MajkiIT** [comment]
@xxcriticxx o this url https://darmowetv.pl/viewpage.php?page_id=6 you always see warning. It's static port.
