### ISSUE TITLE
nowwatchtvlive.me (verdirectotv.com)

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#801]
http://nowwatchtvlive.me/channel-tab-frame/playboyvenus-1.php

http://imgur.com/gcqOHuf

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
Hi,

I will take a look

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
