### ISSUE TITLE
nowwatchtvlive.me (showsport-tv.com)

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#802]
http://nowwatchtvlive.me/channel-tab-frame/beinsports15hd-server-1.php

http://imgur.com/FwyP5a8

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by maynak00** [comment]
please try with
>||showsport-tv.com/js/detect.css$stylesheet
>||showsport-tv.com/js/detect.js$script

**Comment by MajkiIT** [comment]
For me only this
||showsport-tv.com/js/detect.js$script

**Comment by xxcriticxx** [comment]
i get link 1 and link 2 
underneath it "not found" shows up

**Comment by MajkiIT** [comment]
If you disable ublock then it's ok?

**Comment by xxcriticxx** [comment]
let me try

**Comment by xxcriticxx** [comment]
looks like both channels are offline so we cant check now

**Comment by xxcriticxx** [comment]
ok this ||showsport-tv.com/js/detect.js$script works i went to the domain and found working links. they do work only left is some smoke counters 30 sec before stream starts.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
