### ISSUE TITLE
myspass.de

### ISSUE THREAD

**Issue by TobsA13** [reek/anti-adblock-killer#803]
In video anti adblock

for example: http://www.myspass.de/myspass/shows/tvshows/tv-total-turmspringen/Qualifying-ARAG-30000-Euro-Wurf--/24756/
it is on all videos on myspass.de
http://puu.sh/lCg5b/ea8b793b00.jpg
µBlock
EasyList +  Anti-Adblock Killer | Reek‎ +  Adblock Warning Removal List‎ +  uBlock filters +  EasyPrivacy

**Comment by reek** [comment]
HI

Have you installed AakScript ?

See instructions https://github.com/reek/anti-adblock-killer#instruction

**Comment by TobsA13** [comment]
Yes I have installed aakscript, but I had an other problem with my browser. Sorry for open the issue, You can close it.
