### ISSUE TITLE
broadbandforum.co -> AdBlock Detector (XenForo Rellect) (Plugin)

### ISSUE THREAD

**Issue by skr4tchGr3azyMonkiBallllllZzzz** [reek/anti-adblock-killer#804]
Open any thread on broadbandforum.co and this shows up:

![screenshot-broadbandforum co 2015-11-29 11-22-29](https://cloud.githubusercontent.com/assets/10258622/11455559/b0c32c06-968b-11e5-87d4-95bb0ab25d21.png)

Used:
uBlock Origin v1.3.6
+ AakList (Anti-Adblock Killer)
+ Adblock Warning Removal List‎
+ EasyList
and your awesome script on GM v3.6 :)

Also tried blocking: http://broadbandforum.co/js/rellect/AdblockDetector/handler.min.js
but didn't work.

Would be great if you can look into it. Thanks.

**Comment by MajkiIT** [comment]
Try this
@@|http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=broadbandforum.co
broadbandforum.co#@#.adsbygoogle

**Comment by reek** [comment]
@MajkiIT 
Thanks

**Comment by MajkiIT** [comment]
Maybe you find better solution.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
