### ISSUE TITLE
mediafree.co

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#807]
Hi, 
on `http://mediafree.co/ekaq936u70k8/VF.CAM.ArabSeed.CoM.Taha.mkv.html`

![mediafree.co](https://cloud.githubusercontent.com/assets/1873139/11479524/c09e1d0e-9792-11e5-887c-c00b3d16b113.png)

```
@@||onclickads.net/apu.php?zoneid=$script,domain=mediafree.co
@@||go.oclasrv.com/apu.php?zoneid=$script,domain=mediafree.co
```

Thanks!

**Comment by yoshimo** [comment]
have you tried 
>> ||howtoremoveadblock.com/js/adblock-detector.js

**Comment by SMed79** [comment]
@yoshimo workink, i prefer your filter.
Thanks!

**Comment by reek** [comment]
@yoshimo 
Yes, good

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
