### ISSUE TITLE
blockadblock.com

### ISSUE THREAD

**Issue by MUFTAKiS** [reek/anti-adblock-killer#808]
many sites give me overlay page lock with this domain script and nothing stop it?
![0](https://cloud.githubusercontent.com/assets/9373221/11485993/01b81cb4-97bf-11e5-8055-f47f3392cd1b.PNG)

**Comment by reek** [comment]
Hi,

I need links to all these site so that I can try to find a solution.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by MUFTAKiS** [comment]
here is an example as i described above
http://blockadblock.com

**Comment by MajkiIT** [comment]
try this solution
blockadblock.com#@##banner_ad

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MUFTAKiS** [comment]
but it still 8.8

**Comment by reek** [comment]
@MUFTAKiS 
I have just update AakList

**Comment by MUFTAKiS** [comment]
where can i see the changelog of AakList??!!

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/commit/4f296d115bcbe2740554937d2912c0110821fd37

2015-12-01 2:33 GMT+01:00 MUFTAKiS <notifications@github.com>:

**Comment by reek** [comment]
history
https://github.com/reek/anti-adblock-killer/commits/master/anti-adblock-killer-filters.txt

2015-12-01 2:54 GMT+01:00 reek <reekside@gmail.com>:

**Comment by MUFTAKiS** [comment]
nothing changed still i get the same damn overlay :s

**Comment by reek** [comment]
Your config please

**Comment by MUFTAKiS** [comment]
what?

**Comment by reek** [comment]
Your browser, adblocker, scriptmanager ?

**Comment by MUFTAKiS** [comment]
firefox 42 + adblockplus 2.6.13 + greasemonkey 3.6

**Comment by reek** [comment]
you have the same setup as me, so it should work.

see: https://github.com/reek/anti-adblock-killer#help

2015-12-01 16:38 GMT+01:00 MUFTAKiS <notifications@github.com>:

**Comment by pcannell** [comment]
Not working again since BlockAdblock v 2.5

**Comment by reek** [comment]
@pcannell 
:/ I will fix
