### ISSUE TITLE
yes.fm

### ISSUE THREAD

**Issue by ricardogarceb** [reek/anti-adblock-killer#809]
http://www.yes.fm/player/star/maximafm
![1](https://cloud.githubusercontent.com/assets/16104126/11506935/0e62f81a-9852-11e5-858a-eb7a1900325f.png)
http://imgur.com/QOH53ti
Mozilla Firefox
No Script manager
uBlock
Default lists + AakList

<pre>
    var com_adswizz_synchro_url = "http://kriteria.adswizz.com/www/delivery/afr.php?zoneid=";
    var com_adswizz_synchro_DisplayElements = [['adw_1','247']];
    var com_adswizz_synchro_DisplayFallback_Elements = [["adw_1","-1"]];

    var com_adswizz_synchro_DisplayFallback_PrerollStart = 5000;
    var com_adswizz_synchro_autoplay=false;

	try {
    	com_adswizz_synchro_initialize("1");
	}
	catch(e) {
		yes.layout.showModalInformation("Debe tener instalado un bloqueador de publicidad. Por favor, configure www.yes.fm como excepción.");
	}
</pre>

**Comment by reek** [comment]
HI,

Thanks, i will take a look

See you
Reek

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Add the following to the 'rules' section of @reek 's script:
```javascript
    adswizz : {
        // issue: https://github.com/reek/anti-adblock-killer/issues/809
        host : ['yes.fm'],
        onStart : function () {
            Aak.addScript(function () {
                com_adswizz_synchro_initialize = function () {};
            });
        }
    },
```

**Comment by reek** [comment]
@skr4tchGr3azyMonkiBallllllZzzz 
Thanks good job ::smile::

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
