### ISSUE TITLE
[NEWS] We now know another of the big companies that pays Adblock Plus to unblock its ads

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#811]
http://www.businessinsider.com.au/criteo-pays-adblock-plus-to-appear-on-its-acceptable-ads-whitelist-2015-12

Adblock Plus Homepage ‹ Board index ‹ Moderated forums ‹ Acceptable ads proposals

https://adblockplus.org/forum/viewtopic.php?f=12&t=41128%E2%80%8B

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
The reason why I chucked out ABP and am currently using uBO. No more support for ABP #EViL

**Comment by SMed79** [comment]
@skr4tchGr3azyMonkiBallllllZzzz Acceptable ads option isn't "hidden" ! 
Here is how to disable of '**non-intrusive advertising**' > https://adblockplus.org/en/acceptable-ads#optout
