### ISSUE TITLE
winandmac.com

### ISSUE THREAD

**Issue by v998** [reek/anti-adblock-killer#813]
Original LINK (any URI on the site should do too): http://www.winandmac.com/2015/12/mark-zuckerberg-a-letter-to-our-daughter/

When detects adblocker, it redirects to http://www.winandmac.com/adblocker-detected/

![image](https://cloud.githubusercontent.com/assets/7825360/11530428/7a1e905e-992f-11e5-930a-1efa63aae699.png)

Chrome

Tampermonkey

uBlock Origin

![image](https://cloud.githubusercontent.com/assets/7825360/11530603/e4279fee-9930-11e5-8f43-5bc471b44106.png)

what i found: it inlines `an_scripts.js` in the HTML

**Comment by reek** [comment]
HI,

Ok, i will take a look

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
In @reek 's script,
___
***Replace:***
```javascript
    gametransfers_com : {
      // issue: https://github.com/reek/anti-adblock-killer/issues/592
      host : ['gametransfers.com'],
      onAlways : function () {
        Aak.setCookie('anCookie', true);
      }
    },
```
___
***With:***
```javascript
    an_scripts_adblock_notify : {
      // issue: https://github.com/reek/anti-adblock-killer/issues/592
      // issue: https://github.com/reek/anti-adblock-killer/issues/813
      host : ['gametransfers.com', 'winandmac.com'],
      onAlways : function () {
        Aak.setCookie('anCookie', true);
      }
    },
```
___
:smiley_cat:

**Comment by reek** [comment]
@skr4tchGr3azyMonkiBallllllZzzz 
Well done ::smile::

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
:smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
