### ISSUE TITLE
imgtiger.org

### ISSUE THREAD

**Issue by MUFTAKiS** [reek/anti-adblock-killer#814]
http://imgtiger.org

**Comment by MajkiIT** [comment]
What is wrong?

**Comment by MUFTAKiS** [comment]
![0](https://cloud.githubusercontent.com/assets/9373221/11541393/bdabf5b8-993a-11e5-82b4-09daa5b21e46.PNG)

**Comment by MajkiIT** [comment]
you see this after log in ?

**Comment by MUFTAKiS** [comment]
but when i visit images hosted there!

**Comment by MajkiIT** [comment]
But this is not adblock detect. The same situation is then you disable adblock. Please write to easylist.

**Comment by MUFTAKiS** [comment]
could you plz speak english ^_^

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
@MUFTAKiS use:
https://github.com/adsbypasser/adsbypasser

;)

**Comment by MUFTAKiS** [comment]
yeah i knew it but it show images in limited frame and i dont know how to add new url so i removed it tnx anyway

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
adsbypasser directly goes to the *real* image & it's not inside any frame. So what's the issue?

**Comment by reek** [comment]
@MUFTAKiS 
I just tested and I have no problems regarding Aak.
Otherwise, I recommend using Adsbypasser
