### ISSUE TITLE
cba.pl

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#815]
http://ziarnko.cba.pl/

solution
@@||go.idmnet.bbelements.com/bb/bb_one$script,domain=cba.pl
@@||go.idmnet.bbelements.com/please/showit/$script,domain=cba.pl

**Comment by reek** [comment]
Thanks Majkilt

**Comment by xxcriticxx** [comment]
MajkiIT fix the title please

**Comment by MajkiIT** [comment]
Title is ok. Cda.pl is free hosting and they add ads to all pages. So one rule to all.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MajkiIT** [comment]
@reek 

Ca you add other domains to this rule?  (j.pl, c0.pl i y0.pl) On this pages are the same situation. 

http://www.sp3.c0.pl/

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
