### ISSUE TITLE
voyageforum.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#816]
Hi, 
on `http://voyageforum.com/discussion/timimoun-beni-abbes-hiver-algerie-d7160361/`

![voyageforum com](https://cloud.githubusercontent.com/assets/1873139/11550361/be70af7c-996f-11e5-8633-ba65cdb1c8da.png)

`@@||images.voyageforum.com/advertisers/logos/$image,domain=voyageforum.com`

Thanks!
Med

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Hello Med, try adding the following CSS hiding rules to ABP/uBO/etc:
```css
voyageforum.com###mainColumn > div[id][style*="text-align"][style*="justify"]:first-child
voyageforum.com##div.PostAd
voyageforum.com##div[id^="betAds"]
voyageforum.com###mainColumn [id^="mainposttravelsbox"]
```

**Comment by SMed79** [comment]
Hi [@skr4tch](https://github.com/skr4tchGr3azyMonkiBallllllZzzz) , 
###mainColumn hide login and stat box http://i.imgur.com/1q0GOtk.png 
others filters already on **Liste FR** [/listefr/rev/41d44f017aff](https://hg.adblockplus.org/listefr/rev/41d44f017aff) & [/listefr/rev/8a148a8e0945](https://hg.adblockplus.org/listefr/rev/8a148a8e0945).

Thanks!

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
NO! not just `###mainColumn` but this whole thing:

`voyageforum.com###mainColumn > div[id][style*="text-align"][style*="justify"]:first-child`

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
**See:**

![ublock dashboard_-_2015-12-03_20 11 31](https://cloud.githubusercontent.com/assets/10258622/11563478/1bc57010-99fa-11e5-90bf-851c11075692.png)

**Comment by SMed79** [comment]
Ok, Thanks for the filter :)

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Did it work?

**Comment by SMed79** [comment]
Yes!
http://i.imgur.com/tqt379z.jpg

**Comment by reek** [comment]
Thanks guys

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
:smiley:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
```
@@||images.voyageforum.com^$image
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$domain=voyageforum.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$domain=voyageforum.com
```
Disable the anti-adblock and prevent the auto scrolling to the top.

**Comment by reek** [comment]
Thanks, Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Ronflexx** [comment]
Hello,

The issue is back once again, can you please advise ?

![image](https://cloud.githubusercontent.com/assets/24374919/23141344/b343a090-f7b6-11e6-9e9c-6bdb5dfbf33c.png)

Thanks
