### ISSUE TITLE
bild.de blocked again

### ISSUE THREAD

**Issue by barthramsay** [reek/anti-adblock-killer#817]
It seems bild.de updated their code.
uBlock and/or Scriptfilter does not work anymore since today.

**Comment by TonyTough** [comment]
I cannot confirm this.

I'm using Firefox 42 and uBlock Origin with newest filters (standard filters + Easylist Germany +AAK filter + Adblock Warning Removal List)

The  only problem is that with activated AAK script there is too much regular content filtered when you scroll down.
With deactivated AAK script the site works without problems.

**Comment by barthramsay** [comment]
I rechecked with Chrome&Safari and uBlock:  
It seems the problem is EasyList Germany. After deactivating EasyList Germany it seems to work correctly. Gonna analyze that...

**Comment by reek** [comment]
@barthramsay 
I confirm, the problem comes from the EasyList Germany, should report to EasyList Germany

@TonyTough 
The rule on AakScript I know which creates some bugs, but it was the only solution that prevented redirection, I'll probably delete this rule and keep only the rule on AakList

**Comment by TonyTough** [comment]
I posted it to the Easylist Germany forum.

**Comment by reek** [comment]
@barthramsay 
Ok, thanks

**Comment by barthramsay** [comment]
@reek 
I've analyzed their code. They are doing some more advanced checking against EasyList Germany.

This exception rules are now needed to block most ads on bild.de while still not triggering their Anti Adblock:

```
~bild.de##.fullBanner;
~bild.de##.powerplace;
~bild.de##.subchannelBanner1_1;
~bild.de##.subchannelBanner1_2;
~bild.de##.ads
~bild.de##.cbErotikContentbar15
~bild.de##.contentbar
~bild.de##.eyecatcher
~bild.de##.footerbar
~bild.de##.jetzt_aufnehmen
~bild.de##.rectangle
~bild.de##.servicelinks
~bild.de##.tea-rectangle
~bild.de##.txe
~bild.de##.yield
~bild.de##.adspecial
```

**Comment by veekoon** [comment]
Can comfirm @barthramsay list. But their is still a little popup which is grew and can be disabled with X mark. It seems to be a one-time thing.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by barthramsay** [comment]
The Anti Adblock targeting EasyList Germany still works even with newest UserScript+Filterlist. Only my additional rules from https://github.com/reek/anti-adblock-killer/issues/817#issuecomment-161957888 are helping. Will also try to report to EasyList Germany. But it seems they are frightened to move against bild.de Anti Adblock and will not move. https://forums.lanik.us/viewtopic.php?f=90&t=25851&start=15

**Comment by reek** [comment]
@barthramsay 
Saw there <code>@@||bild.de^$elemhide</code> rule, it is not necessary to add the following rules.
<pre>
~bild.de##.fullBanner;
~bild.de##.powerplace;
~bild.de##.subchannelBanner1_1;
~bild.de##.subchannelBanner1_2;
~bild.de##.ads
~bild.de##.cbErotikContentbar15
~bild.de##.contentbar
~bild.de##.eyecatcher
~bild.de##.footerbar
~bild.de##.jetzt_aufnehmen
~bild.de##.rectangle
~bild.de##.servicelinks
~bild.de##.tea-rectangle
~bild.de##.txe
~bild.de##.yield
~bild.de##.adspecial
</pre>

In any case, I tested on Firefox and Chrome and it works without these additional rules

**Comment by barthramsay** [comment]
@reek:
You're right. It is working. But for me only on Firefox and uBlock origin.
Does not work on Chrome (uBlock origin) nor on Safari (uBlock, not origin) here. I try to figure out why.

**Comment by reek** [comment]
@barthramsay 
I will perform additional test

**Comment by barthramsay** [comment]
@reek
I've found the problem now. It has to do with ublock advanced option which seems to be checked default on all browsers. English option (in filters category):

"Parse and enforce Adblock+ element hiding filters."

In German it is called:

"Kosmetische Filter zum Verstecken von Elementen analysieren und anwenden."

This option needs to be checked "off" on Chrome and Safari, then it works. On Firefox this option can be let enabled. Seems Chrome and Safari doing something different behind the scenes there and analyzing/performing this enforce hiding filters differently.

**Comment by reek** [comment]
@barthramsay 
Ok thank you, this will surely help other users, although in my case it is not necessary

**Comment by IDKwhattoputhere** [comment]
Bild.de doesn't work again in Chrome. When I block inline-scripts it works. Firefox is fine too.
[Screenshot](https://cloud.githubusercontent.com/assets/16030872/12799459/3616be00-cacf-11e5-8159-c2d0fe8ef0fc.png)
Unchecked "Kosmetische Filter zum Verstecken von Elementen analysieren und anwenden."
Google Chrome Version 48.0.2564.97
Tampermonkey 3.12.58 + AAK script 9.2
uBlock Origin v1.5.6 with the same lists as [here](https://github.com/reek/anti-adblock-killer/issues/987#issuecomment-177265193).
Has also been discussed here before: https://github.com/gorhill/uBlock/search?q=bild.de&type=Issues&utf8=%E2%9C%93
