### ISSUE TITLE
vipracing.info

### ISSUE THREAD

**Issue by entproject** [reek/anti-adblock-killer#818]
http://lsa---gr.blogspot.com/2015/04/stream-hd-1.html

http://vipracing.info/channel/opcion-1/frame

https://www.dropbox.com/s/2fnxk5ww6gb2jz1/adblock.bmp?dl=0
Google Chrome 

Tampermonkey

Ublock Origin

All default ublock lists( aaklist+easylist+...)

**Comment by entproject** [comment]
Why no anti adblock message?

If you scroll down the page you will see a window with a "stop" hand, and a "please disable addblock" message

**Comment by entproject** [comment]
this is a new print screen because previous was deleted by mistake

https://www.dropbox.com/s/2fnxk5ww6gb2jz1/adblock.bmp?dl=0

**Comment by reek** [comment]
I had not tested Chrome and indeed there is a message, I'll settle it

**Comment by reek** [comment]
add this rule
<code>vipracing.info##.in-video-adds</code>

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/1119

**Comment by entproject** [comment]
thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
