### ISSUE TITLE
lifehacker.com.au

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#821]
Hi, 
`#@#div[itemtype="http://schema.org/WPAdBlock"]`
on `http://www.lifehacker.com.au/`

![lifehacker.com.au](https://cloud.githubusercontent.com/assets/1873139/11604044/26217f24-9ae8-11e5-81ba-5961b07b0fc5.png)

Thanks!

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
