### ISSUE TITLE
hitek.fr

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#822]
Hi; 
![hitek fr](https://cloud.githubusercontent.com/assets/1873139/11608470/4fb2c820-9b6a-11e5-8381-b7b41805e2ad.png)

on `http://hitek.fr/`

`@@||hitek.fr/ads.js$script`

Thanks!

**Comment by reek** [comment]
Thanks again Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
anti-adblock banners + background ad
`@@||hitek.fr/adserver.js$script`

**Comment by reek** [comment]
Ok, thanks
