### ISSUE TITLE
xboxforum.pl

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#823]
http://imgur.com/SMySYsh

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
**Add:**
`xboxforum.pl##.noticeContainer:not(.hidden)`

**Here:**
![screenshot-ublock0 2015-12-06 00-36-05](https://cloud.githubusercontent.com/assets/10258622/11609623/b2ace78e-9bb1-11e5-91fb-e1ecd673d651.png)

**Comment by reek** [comment]
@skr4tchGr3azyMonkiBallllllZzzz 
Thanks :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
