### ISSUE TITLE
sortiesdvd.com

### ISSUE THREAD

**Issue by DelpheniX** [reek/anti-adblock-killer#824]
The video player for movie trailers doesn't appear, i have to turn the script off for the site to see it again but then the adblock warning show up. Try this link http://www.sortiesdvd.com/video-4161.html

**Comment by reek** [comment]
HI,

thank you, I'll fix this bug

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
