### ISSUE TITLE
computerbild.de - conflict with uBlock Origin filters

### ISSUE THREAD

**Issue by TonyTough** [reek/anti-adblock-killer#825]
Hi,

there seems to be a conflict with uBlock Origin latest filters and this site:
computerbild.de

With activated AAK List I have these big ugly ads:
http://postimg.org/image/l9xo00o6j/

With deactivated AAK List the ads are filtered out by UBlock's own filters.

I guess it has to do with
@@||sascdn.com$domain=bild.de
@@||smartadserver.com$domain=bild.de
in AAK List, from where the ad graphics are loaded..

**Comment by reek** [comment]
this should solve the problems
<pre>
@@||bild.de^$elemhide
@@||sascdn.com^$script,domain=bild.de
@@||smartadserver.com^$script,domain=bild.de
</pre>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
