### ISSUE TITLE
imageraider.com

### ISSUE THREAD

**Issue by COOLak** [reek/anti-adblock-killer#826]
![fireshot screen capture 085 - instant search - image raider - www_imageraider_com_search_ ped128178adfc9f5b48af729eab07045e](https://cloud.githubusercontent.com/assets/8677627/11611418/b8559a56-9bdd-11e5-9f46-57ecf0bc23e3.png)

https://www.imageraider.com/ - paste any image url in the search box and click "Check URLs". You will see the thing shown on my screenshot.

**Comment by reek** [comment]
HI,

Ok, I will take a look.

PS: Funny anti-adblock :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
