### ISSUE TITLE
ultimate-goldust.fr.fo

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#828]
Hi,
on `http://www.ultimate-goldust.fr.fo/`

![ultimate-goldust.fr.fo](http://imgur.com/h2oS1LYl.png)

`ultimate-goldust.fr.fo#@#.afs_ads`

Tnx!

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Done !
