### ISSUE TITLE
knowlet3389.blogspot.com

### ISSUE THREAD

**Issue by abccbaandy** [reek/anti-adblock-killer#83]
hi, I got block when access this link
http://knowlet3389.blogspot.com

got this alert
alert("不要遮蔽廣告啦, 請把本站加到例外\nDo Not block my ADs, Please. QAQ!")

my environment
chrome
Tampermonkey
Adblock Plus

list
Adblock Warning Removal List
EasyList China+EasyList
Anti-Adblock Killer | Filters for Adblockers

P.S.
maybe this code can fix the problem. 
I tried, it work, but don't really know why:(
```javascript
knowlet3389 : {
    host : ['knowlet3389.blogspot.com'],
    onStart : function () {
        Aak.addStyle("#gAds { height: 1px !important;width: 1px !important; display: none !important; }");
    }
},



```javascript
// 13.03.2016
$(document).ready(function() {
    setTimeout(function() {
        if (localStorage.noad === undefined && (16 >= $("#gAds").height() || 16 >= $("#gAd2").height())) {
            $("#Blog1").remove();
            sweetAlert("Oops.. please don't block my ADs", "請把本站加到ADblock例外清單, 或者在此網站上停用!", "warning");
        }
    }, 3456)
});
```

**Comment by MrSherlockHolmes** [comment]
Still problematic. https://i.gyazo.com/1bc73c1720ae0cff174c895eb68c41e8.png

**Comment by reek** [comment]
I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
