### ISSUE TITLE
exrapidleech.info detects Anti AB v8.9

### ISSUE THREAD

**Issue by sanGtH** [reek/anti-adblock-killer#830]
site detects Anti AB v8.9 : 
http://www.exrapidleech.info
Screenshot : 
http://img287.imagevenue.com/img.php?image=05997_exrapid_prob_122_536lo.jpg
Firefox
Greasemonkey
Ublock Origin
Aaklist + Easylist

**Comment by reek** [comment]
Hi,

I think the admin of <code>exrapidleech</code> watching us. but I will fix it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by MUFTAKiS** [comment]
im strongly recommend you to contact privately to save your work and effort plz
