### ISSUE TITLE
receive-a-sms.com

### ISSUE THREAD

**Issue by Fabio0dev0** [reek/anti-adblock-killer#831]
http://receive-a-sms.com/adblock
http://i.imgbox.com/eqvVi3as.jpg
Mozilla Firefox
Greasemonkey
Adblock Plus
---Adblock Warning Removal List
---EasyList Germany + EasyList
--EasyPrivacy
-AakList

**Comment by reek** [comment]
Hi,

Ok, i will take a look.

See you
Reek

**Comment by MajkiIT** [comment]
try this:

@@|http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=receive-a-sms.com

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
