### ISSUE TITLE
Comunio.de (AdDefend)

### ISSUE THREAD

**Issue by yoshimo** [reek/anti-adblock-killer#832]
usual bad code from AdDefend:

```
 var e = u(n, this),
a = [T("2l252vfuhhqvkrwv2exqghvoljd2gh2vfuhhqvkrwbppexgwqvb" + t.uabpRnd + "bgdt|udxfjp1jli", -3), T("2l252vfuhhqvkrwv2exqghvoljd2gh2vfuhhqvkrwblxprihprb" + t.uabpRnd + "bojzsktmr{|1jli", -3), T("2l252vfuhhqvkrwv2exqghvoljd2gh2vfuhhqvkrwbkmrqqrmxb" + t.uabpRnd + "bf}egkuthpx1jli", -3)],
r = a[Math.floor(3 * e.y / this.height)];
```

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
You add "host" manualy at https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L3803

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
