### ISSUE TITLE
Deprecated Code Warning in Chrome v8.9

### ISSUE THREAD

**Issue by pjlasl** [reek/anti-adblock-killer#833]
After I updated to version 8.9, Chrome started displaying the following message in its console:

    'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or
    'navigator.webkitPersistentStorage' instead.
    VM1257:4070 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

**Comment by reek** [comment]
Ok, thanks, i will fix it :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by JonasNo** [comment]
This issue have not been fixed.

Chrome stable Version 48.0.2564.116 m
Anti-Adblock Killer | Reek version 9.2

Test url: http://www.typkanske.se/synonym/fodelsedag

Console output:
```
VM2277:4236 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
VM2277:4236 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
```

**Comment by reek** [comment]
I use Firefox as I have that message in the console but I will fix this little bug

**Comment by 18763C27** [comment]
https://github.com/reek/anti-adblock-killer/blob/657d60e7b660e277ea98fef1f03947bf3fa04eb5/anti-adblock-killer.user.js#L4230-L4231

the `typeof` check here triggers the deprecation warnings

you need to do the `/^webkit/` check before it

```javascript
// this would work:
if (win.hasOwnProperty(prop) && !/^webkit/.test(prop) &&
  typeof win[prop] === 'object' && /^[a-z0-9]{4,10}$/i.test(prop)) {
```

**Comment by reek** [comment]
@18763C27 
Ok, thanks

**Comment by reek** [comment]
Fixed !
