### ISSUE TITLE
rlsbb.movie7share.net

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#834]
http://imgbox.com/2hfDd2Xb

Mozilla Firefox 42.0
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
Ok, i will take a look

**Comment by MajkiIT** [comment]
Static content. If you disable adblock alert still is.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
