### ISSUE TITLE
debridnet.com

### ISSUE THREAD

**Issue by Hongbo-Miao** [reek/anti-adblock-killer#836]
Not work on http://debridnet.com/
http://imgbox.com/yZ5i0jmG

Chrome  48.0.2564.22 dev (64-bit)
uBlock Origin 1.3.3
Tampermonkey  3.12.58
AakList (Anti-Adblock Killer)‎

**Comment by reek** [comment]
Hi,

Ok, i will take a look

**Comment by Hongbo-Miao** [comment]
Cool, thanks!

**Comment by MajkiIT** [comment]
@Hongbo-Miao this add this exclude @@||tags.h12-media.com/load.js$script,domain=debridnet.com

**Comment by Hongbo-Miao** [comment]
Thanks @MajkiIT. But after I adding this to My filters of uBlock Origin, it still does not work.
@@||tags.h12-media.com/load.js$script,domain=debridnet.com

**Comment by MajkiIT** [comment]
@Hongbo-Miao I tested this rule on 2 browsers. After I add this rule I don't have any redirects. Can you open this url (http://debridnet.com/) on browser private mode?

**Comment by Hongbo-Miao** [comment]
@MajkiIT No, it is not working... Let me try on Safari

**Comment by MajkiIT** [comment]
Can you give list of filters which are you using?

**Comment by Hongbo-Miao** [comment]
I am using https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
Others filters are from uBlock Origin itself.

**Comment by MajkiIT** [comment]
Easylist? EasyPrivacy‎?

**Comment by Hongbo-Miao** [comment]
@MajkiIT Oh, I am using all filters including two Chinese region filters. Haha

**Comment by MajkiIT** [comment]
Can you export yours uBlock settings?

**Comment by Hongbo-Miao** [comment]
Here you go:
https://www.dropbox.com/s/onugas19cnx4v59/my-ublock-backup_12-10-2015%2C_2-05-08_PM.txt?dl=0

**Comment by MajkiIT** [comment]
On yours filters.

![screen](https://cloud.githubusercontent.com/assets/11302675/11725534/8a6e867a-9f7a-11e5-97ba-2f12b7ce2a6a.png)

**Comment by Hongbo-Miao** [comment]
@MajkiIT So weird! Give me a second, let me try on Opera too!

**Comment by Hongbo-Miao** [comment]
@MajkiIT Same result on Opera... On other websites, Anti-Adblock Killer all works well. Only this one does not work.
I already added this to My filters of uBlock Origin: `@@||tags.h12-media.com/load.js$script,domain=debridnet.com`

**Comment by Hongbo-Miao** [comment]
@MajkiIT Oh, it is working now! I don't know why, but after I turn on Zenmate and turn off it in Opera, now it is working! In Chrome, I trun on Browsec and then turn off it, it works now too!

**Comment by MajkiIT** [comment]
Ok it's good news for me.

**Comment by Hongbo-Miao** [comment]
@MajkiIT It is very weird. Today both Chrome and Opera do not work again. Then I did same things like yesterday: change my IP address, and change back, it starts to work again.
