### ISSUE TITLE
samehadaku.net

### ISSUE THREAD

**Issue by satrianiboys** [reek/anti-adblock-killer#838]
http://www.samehadaku.net/
http://imgbox.com/vGaXESne

firefox 42
Greasemonkey
Adblock Plus
easylist + aaklist

Thank you

**Comment by SMed79** [comment]
`samehadaku.net#@##adsense`

**Comment by reek** [comment]
@SMed79 
Thanks

**Comment by satrianiboys** [comment]
Working fine, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
