### ISSUE TITLE
di.se

### ISSUE THREAD

**Issue by mrdemo007** [reek/anti-adblock-killer#841]
http://www.di.se
http://imgur.com/LjNTR41
Google Chrome (Version 47.0.2526.80 m)
uBlock Origin + Tampermonkey

**Comment by SMed79** [comment]
Hi, 
try to add:
```
www.di.se#@#.text_ads
@@||www.di.se/DiCommon/static/js/advertisement.js$xmlhttprequest,~third-party
```

**Comment by reek** [comment]
Thanks Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
