### ISSUE TITLE
hayan.tv

### ISSUE THREAD

**Issue by meda01** [reek/anti-adblock-killer#843]
http://hayan.tv/a/2015/gochiusa2/
Accessing a link, and then clicking any one of "XX화" 
"Adblock을 꺼주세요." printed message,

**Comment by MajkiIT** [comment]
Try add this rule hayan.tv#@##uzcrsite

**Comment by SMed79** [comment]
* in firefox + adblock plus u need to switch to easylist without hiding filters or disable **###uzcrsite**
* in chrome add: 
```
hayan.tv#@##uzcrsite
@@||hayan.tv/adp.htm
```
https://forums.lanik.us/viewtopic.php?f=62&t=27042#p82020

**Comment by reek** [comment]
Thanks guys !

**Comment by meda01** [comment]
thanks~ it works!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
