### ISSUE TITLE
wakanim.tv

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#844]
Hi,
on `http://www.wakanim.tv/fr/v2/catalogue/episode/1543/haikyu-9` 

/!\ (need login).

`@@||ads.stickyadstv.com/www/delivery/swfIndex.php?$xmlhttprequest,domain=wakanim.tv`

![wakanim.tv](http://i.imgur.com/FDr8LWT.png)

Thanks!

**Comment by reek** [comment]
Thanks !

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
