### ISSUE TITLE
armorgames.com

### ISSUE THREAD

**Issue by MininGamer** [reek/anti-adblock-killer#845]
http://armorgames.com/

![hax](https://cloud.githubusercontent.com/assets/12849869/11762604/4b74b862-a0e3-11e5-9973-4a6c06de6a7f.JPG)

``` javascript
  if (typeof ga_detect == 'object' && typeof ga_detect.blocked == 'function') {
    ga_detect.blocked(function () {
      jQuery('div[id^=div-gpt-ad-]').hide();
      jQuery('#edblock').show()
    })
  }

**Comment by SMed79** [comment]
Redirect me to `http://mad.com/?ag`

**Comment by reek** [comment]
@SMed79 
Me too

**Comment by SMed79** [comment]
@MininGamer from where (contry) you're browsing `ARMOURGAMES` ?

**Comment by MininGamer** [comment]
@SMed79 Ireland with Adblock plus Chrome

**Comment by reek** [comment]
@MininGamer 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by MininGamer** [comment]
@reek Here's the code:
https://gist.github.com/MininGamer/25b7c1a9f5a20ba47250

**Comment by SMed79** [comment]
@MininGamer `armourgames.com` or `armorgames.com` ? with **u** !!!
see >> https://forums.lanik.us/viewtopic.php?f=62&t=26779

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
Hi reek,
check > https://adblockplus.org/forum/viewtopic.php?f=2&t=42196&p=146690#p146690

**Comment by reek** [comment]
@SMed79 
Ok, I'll see

**Comment by reek** [comment]
@SMed79 
I'll add a rule AakScript

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
