### ISSUE TITLE
imgbb.net

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#847]
http://imgbb.net/v-5643cb5982364

text shown onscreen:
"Please disable your AdBlocker to support our free service! It means a lot!"

**Comment by maynak00** [comment]
please try with:
>@@||imgbb.net/js/ads.js$script
or
>imgbb.net###adblock_warning_msg

**Comment by callmenemo491** [comment]
both work.  am not sure which one is the best to use!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
