### ISSUE TITLE
ow.ly seems doesn't work if ublock was enabled

### ISSUE THREAD

**Issue by muhasturk** [reek/anti-adblock-killer#848]
Link: http://ow.ly/VPcWZ

I face generate issue on ow.ly when ublock was enabled. Can u make anything?

**Comment by maynak00** [comment]
Report Guide: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
Tested in chromium with uBlock origin enabled. generated short url succesfully (I can write Turkish if allowed by reek)
which OS, which web browser, maybe userscripts?
my test url: https://www.google.com.tr/maps generated url: http://ow.ly/VPdon

**Comment by reek** [comment]
Hi,
I could easily generate a link.

Please describe the problem and added a capture..
