### ISSUE TITLE
crichd.tv

### ISSUE THREAD

**Issue by dt4ever** [reek/anti-adblock-killer#849]
http://www.crichd.tv/bt-sport-1-live-stream.php
http://imgur.com/THaxbgO
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
HI,
Ok, I will take a look

**Comment by maynak00** [comment]
no problem with your link.but when I test with this link, adblocker detected: http://www.crichd.tv/sky-sports-1-live-stream-uk6.php
please try with:
>crichd.tv##div[id="notice"]

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
