### ISSUE TITLE
antiblock.org

### ISSUE THREAD

**Issue by Kara-ism** [reek/anti-adblock-killer#85]
Hi reek,

Thanks for your great effort about this useful script :D

As I mentioned in tittle, Antiblock.org doesn't work with script anymore.

Hope your fixing...Thanks again !!

[System Environments]
http://antiblock.org/?p=v3&demo
![n3y0glz](https://cloud.githubusercontent.com/assets/9511279/4961353/94fd8b9a-66cd-11e4-998d-4bf15d3ae604.png)
Opera 25.0.1614.68
Violent Monkey
Adblock Plus
EasyList + Anti-Adblock Killer | Filters for Adblockers
Windows 8 Business Edition

**Comment by pranav-prakash** [comment]
Not sure if it is just me, but antiblock.org blocker installed as a filter list doesn't work on ublock origin with easy list. Tried switching to adblock but same result there too.

It does work on http://d3xt3r.com/anti-adblock?test so I know that it is enabled though.

I can provide the blocked requests if necessary.

**Comment by reek** [comment]
Hi,

Please, your configurations and requests blocked.
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by pranav-prakash** [comment]
Chrome 42.0.2311.135 on OSX 10.9 
uBlock origin 0.9.7
Easylist Filters with Anti-Adblock-Killer installed as a filter

Requests blocked:

/pagead2.	    script	http://pagead2.googlesyndication.com/pagead/show_ads.js
468x60.	           image	http://antiblock.org/images/468x60.gif
###adtop	              dom	http://antiblock.org/?p=v3&demo
###sponsorAd1     dom	http://antiblock.org/?p=v3&demo
###ovadsense       dom	http://antiblock.org/?p=v3&demo
###head_ads	      dom	http://antiblock.org/?p=v3&demo
###bsap_aplink     dom	http://antiblock.org/?p=v3&demo
###adv-preroll	      dom	http://antiblock.org/?p=v3&demo
###adsense	      dom	http://antiblock.org/?p=v3&demo
###adholder	      dom	http://antiblock.org/?p=v3&demo
###ad-197	      dom	http://antiblock.org/?p=v3&demo

**Comment by reek** [comment]
Hi,

Please read instructions
https://github.com/reek/anti-adblock-killer#instruction

**Comment by pranav-prakash** [comment]
I feel so stupid now -- sorry for bothering you, go ahead and close this issue.
