### ISSUE TITLE
watchwrestling.uno and prowrestlingreports.com

### ISSUE THREAD

**Issue by Crardogg** [reek/anti-adblock-killer#850]
http://watchwrestling.uno/busy/
http://prowrestlingreports.com/cgi-bin/livestream1.php
https://imgur.com/viQpet9
Mozilla Firefox
Greasemonkey
Adblock Plus
Ablock Warning Removal List + EasyList + EasyPrivacy + Disable Malware + AakList (Anti-Adblock Killer)

**Comment by reek** [comment]
Hi,
Ok, I will take a look

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by wrestlng** [comment]
Do not forget to donate, review, share, follow and add to favorites.  Ablock Warning Removal List + EasyList + EasyPrivacy + Disable Malware + AakList (Anti-Adblock Killer)  http://wrestlng.com/busy/
