### ISSUE TITLE
kg-portal.ru

### ISSUE THREAD

**Issue by dananichev** [reek/anti-adblock-killer#856]
Some videos completely disappear while using ant-adblock-killer.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by dananichev** [comment]
http://kg-portal.ru/news/movies/video/

Two screenshots:
http://imgur.com/a/PzYnX
First one with userscript. Second one - without.

Mozilla Firefox
Greasemonkey
uBlock
Adblock Warning Removal List‎ + AAK List

**Comment by reek** [comment]
Ok, thanks, I'll exclude kg-portal.ru

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by dananichev** [comment]
Thanks!
