### ISSUE TITLE
AAK breaks Plunker editor

### ISSUE THREAD

**Issue by lsloan** [reek/anti-adblock-killer#857]
http://plnkr.co/

Using Anti-Adblock Killer | Reek v8.9 with Tampermonkey v3.12.58 in Google Chrome v47.0.2526.80 (64-bit) causes the editor in Plunker to fail.  Looking through the messages shown in the browser console, I can't see any that pertain directly to AAK or Tampermonkey.  However, if I disable the AAK script in the Tampermonkey console, Plunker will work correctly.

**Comment by reek** [comment]
Hi,
Ok, thanks, I'll add an exception

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
