### ISSUE TITLE
www.eurotransport.de

### ISSUE THREAD

**Issue by TonyTough** [reek/anti-adblock-killer#858]
Anti-Adblock notice, when opening site with ublock Origin with Standard Filters + AAK list + Easylist Germany and Firefox 43 64bit

"Mit eingeschaltetem AdBlocker können Sie die Inhalte von eurotransport.de leider nicht mehr sehen.
Jetzt AdBlocker ausschalten"

http://postimg.org/image/o5vpc23yz/

Edit:
for ublock the following filter seems to work
eurotransport.de##script:contains(antiAdBlock)

<pre>
http://www.eurotransport.de/js/elements/shared/Base/antiAdBlock.js

(function () {
        var targetUrl = "http://www.eurotransport.de/adblock-6784220.html";
        var currUrl = window.location.protocol + "//" + window.location.host + window.location.pathname;

        function onDetected() {
            if (targetUrl != currUrl) {
                window.location = targetUrl + "#" + currUrl;
            }
        }

        function onNotDetected() {
            if (targetUrl == currUrl) {
                window.location = window.location.hash.substring(1);
            }
        }

        if (typeof antiAdBlock === 'undefined') {
            onDetected();
        } else {
            antiAdBlock.onDetected(onDetected);
            antiAdBlock.onNotDetected(onNotDetected);
        }
    })()

</pre>

**Comment by reek** [comment]
Ok, thanks

<pre>
http://www.eurotransport.de/js/elements/shared/Base/antiAdBlock.js

(function () {
        var targetUrl = "http://www.eurotransport.de/adblock-6784220.html";
        var currUrl = window.location.protocol + "//" + window.location.host + window.location.pathname;

        function onDetected() {
            if (targetUrl != currUrl) {
                window.location = targetUrl + "#" + currUrl;
            }
        }

        function onNotDetected() {
            if (targetUrl == currUrl) {
                window.location = window.location.hash.substring(1);
            }
        }

        if (typeof antiAdBlock === 'undefined') {
            onDetected();
        } else {
            antiAdBlock.onDetected(onDetected);
            antiAdBlock.onNotDetected(onNotDetected);
        }
    })()

</pre>

**Comment by KingThunder** [comment]
See:

https://github.com/gorhill/uBlock/issues/1078

**Comment by reek** [comment]
@TonyTough 
@KingThunder 
this rule only works with firefox + ublock, I need one that works everywhere

**Comment by KingThunder** [comment]
The second one in https://github.com/gorhill/uBlock/issues/1078 works in firefox and chromium, idk if works at another ad blocker.

**Comment by gorhill** [comment]
@KingThunder The real filter does not use `fuckadblock.js-3.2.0`, the site uses a custom -- renamed -- version:

    ||eurotransport.de/*/antiAdBlock.js$script,first-party,redirect=AntiAdBlock.js

In uBO, `AntiAdBlock.js` is redefined as:

    (function() {
        window.antiAdBlock = {
            onDetected: function() {
                ;
            },
            onNotDetected: function(a) {
                a();
            }
        };
    })();

Could be more compact etc., but I like to be able to put breakpoints, which is more difficult when all is on one line.

**Comment by reek** [comment]
@gorhill 
thank you, I have a fix similar to yours that will solve this problem.

Have you ever a patch for Version 4.0.0-beta.3 ?
http://fuckadblock.sitexw.fr/beta/

**Comment by gorhill** [comment]
> Have you ever a patch for Version 4.0.0-beta.3 ?

Not yet, I work on a per-need basis and I haven't encountered a case for this one yet.

**Comment by reek** [comment]
Ok thanks

2015-12-17 18:43 GMT+01:00 Raymond Hill <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
