### ISSUE TITLE
nowvideo.sx

### ISSUE THREAD

**Issue by grenzor** [reek/anti-adblock-killer#859]
Cannot watch any videos because it tells users to disable adblock first.

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#instruction
