### ISSUE TITLE
al.ly  ads issue

### ISSUE THREAD

**Issue by mozkan007** [reek/anti-adblock-killer#860]
Hi.I am using ublock origin with up-to-date anti-adblock-killer filters.But the filters are not working on al.ly .It is warning that please disable adblocker.Please fix it.Thanks.

**Comment by maynak00** [comment]
https://github.com/reek/anti-adblock-killer/issues/859#issuecomment-164949464
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
https://github.com/reek/anti-adblock-killer#instruction
