### ISSUE TITLE
ruutu.fi

### ISSUE THREAD

**Issue by nomexa** [reek/anti-adblock-killer#862]
http://www.ruutu.fi/video/2026456
http://imgur.com/GSjgiaq
Google Chrome
Tampermonkey
uBlock Origin
EasyList + AakList

**Comment by reek** [comment]
Hi,
Try this rule
<code>@@||adserver.adtech.de/?adrawdata/$xmlhttprequest,domain=ruutu.fi</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
