### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by Giwayume** [reek/anti-adblock-killer#865]
They have recently implemented a new system which completely stops adblock users from viewing content.

http://www.forbes.com/
http://i.imgur.com/1FZL6Ih.png
Mozilla Firefox 42
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by Giwayume** [comment]
They're checking for display:none on a certain container. This seems to have resolved the issue.
```
forbes_com : {
    host : ['forbes.com'],
    onStart : function() {
        Aak.addStyle(".ads-container, .ads-container * { display: block; width: 0px; height: 0px; visibility: hidden; }");
    }
},
```

**Comment by reek** [comment]
HI,

Thank you, I'll add it

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by Giwayume** [comment]
Hmm nevermind I must have run into a race condition. It doesn't work consistently.

**Comment by reek** [comment]
too late, we will do better next time

**Comment by Giwayume** [comment]
It seems I was dodging the real issue. This actually works consistently.
```
forbes_com : {
    host : ['forbes.com'],
    onStart : function () {
        if (window.location.pathname.indexOf('/welcome') > -1) {
            Aak.setCookie('welcomeAd', 'true', 86400000, '/');
            Aak.setCookie('dailyWelcomeCookie', 'true', 86400000, '/');
            window.location = Aak.getCookie('toUrl') || 'http://www.forbes.com/';
        }
    }
},
```

**Comment by reek** [comment]
Thanks for fix.

2015-12-19 19:45 GMT+01:00 Giwayume <notifications@github.com>:
