### ISSUE TITLE
cineflixhd.net

### ISSUE THREAD

**Issue by roneyrogerio** [reek/anti-adblock-killer#867]
http://www.cineflixhd.net/
firefox

**Comment by reek** [comment]
Hi,
	
Please provide the information requested here, otherwise I will be rejected your request
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

See you
Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by yoshimo** [comment]
CineflixHD.net is using 
https://henscripts.googlecode.com/svn/trunk/BlockAdBlock/assets/advertisement.js
which is already whitelisted in the AAK list.

**Comment by reek** [comment]
@roneyrogerio 
https://github.com/reek/anti-adblock-killer#instruction
