### ISSUE TITLE
[NEWS] This startup believes it has found a way to make ad blocker users generate money for publishers

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#868]
http://www.businessinsider.com/optimal-launches-subscription-service-for-ad-block-users-2015-12

**Comment by TonyTough** [comment]
My opinion: This will not work at all.

If someone wants to support a small webpages they can spend money directly to the owner and donb't need one more privacy invading service that wants to make own profit.

**Comment by reek** [comment]
I expect to see it implemented
