### ISSUE TITLE
airmanga.eu

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#869]
Hi,
on `http://www.airmanga.eu/0noushiyaminato/chapitre-00/`

![airmanga](http://i.imgur.com/a1uGCLT.png)

`@@||mymanga.io/css/advertise.css`

Thanks!

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by einstein95** [comment]
Has been updated, filter to use now is
`@@||mymanga.io/css/ads.css$stylesheet`

**Comment by reek** [comment]
yes
