### ISSUE TITLE
bitcoin-gator.com

### ISSUE THREAD

**Issue by RNTmedeiros** [reek/anti-adblock-killer#874]
http://www.bitcoin-gator.com
http://i.imgur.com/HP7xEq8.png
Google Chrome
TamperMonkey
Adblock (getadblock.com)
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by yoshimo** [comment]
```@@||bitcoin-gator.com/public/adblock.js``` as filter exception should work

**Comment by reek** [comment]
@yoshimo 
it's right :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
