### ISSUE TITLE
Forbes.com

### ISSUE THREAD

**Issue by BenjaminChe** [reek/anti-adblock-killer#875]
http://www.forbes.com/forbes/welcome/
http://i.imgur.com/1FZL6Ih.png
Google Chrome
TamperMonkey
uBlock Origin
AakList

Hi, bringing this issue up once again.

I am aware of Issue #865, neither the fix currently in master 
```
forbes_com : {
	  // by: Giwayume
	  // issue: https://github.com/reek/anti-adblock-killer/issues/865
      host : ['forbes.com'],
      onStart : function () {
        Aak.addStyle(".ads-container, .ads-container * { display: block; width: 0px; height: 0px; visibility: hidden; }");
      }
    }
```
nor the revised fix mentioned in the issue thread
```
forbes_com : {
    host : ['forbes.com'],
    onStart : function () {
        if (window.location.pathname.indexOf('/welcome') > -1) {
            Aak.setCookie('welcomeAd', 'true', 86400000, '/');
            Aak.setCookie('dailyWelcomeCookie', 'true', 86400000, '/');
            window.location = Aak.getCookie('toUrl') || 'http://www.forbes.com/';
        }
    }
},
```

is successful at bypassing the adblock blocking wall.   

For reference, media coverage:
[Digiday](http://digiday.com/publishers/forbes-ad-blocking/)
[Digital Reader](http://the-digital-reader.com/2015/12/16/95221/)

This should be top priority, a major content producer is implementing very aggressive anti-adblock measures.

They are not stupid either.

The enforcement script (http://i.forbesimg.com/welcomead/scripts/2b1949a5.main.js) dynamically detects and picks enforcement measures (refer to ab-message 1, 2, 3 in the javascript) and offers an "ad-lite" Forbes experience as an incentive to turning off the adblock. 

Simply deleting the cookies (welcomeAd, dailyWelcomeCookie, forbes_ab) that trigger the block does nothing, because the script conducts adblock detection tests everytime the interstitial welcome page (http://www.forbes.com/forbes/welcome/) is loaded.    The original method of the spoofed ad container fails as well because of the AdManager implementation of the script and the fact that it's checked on interval.   Reference below:
```
insertGoogletagScript: function() {
                var a = this,
                    b = "https:" === document.location.protocol ? "https:" : "http:",
                    c = b + a._gpt.src;
                $.ajax({
                    url: c,
                    cache: !1,
                    timeout: a._gpt.timeout,
                    dataType: "script",
                    crossDomain: !0
                }).success(function() {
                    var b, c = 0,
                        d = 0,
                        e = setInterval(function() {
                            if (a.checking_adblock_gpt = !0, d += 10, "undefined" != typeof googletag && googletag.apiReady) return a._gpt.state = !0, a.checking_adblock_gpt = !1, void clearInterval(e);
                            if (d >= a._gpt.timeout) {
                                if (a._gpt.state = !1, clearInterval(e), a.getAdBlockState() || !a.is_mobile) return void(a.checking_adblock_gpt = !1);
                                b = setInterval(function() {
                                    return c += 10, googletag && googletag.apiReady ? (a.checking_adblock_gpt = !1, void clearInterval(b)) : void(2500 >= c || (Cookies.get("forbes_ab") ? a.displayAd("ab-message-2") : a.displayAd("ab-message-1"), a.setBypassCookie(!1), a.triggerAdBlockState(!0), a.checking_adblock_gpt = !1, clearInterval(b)))
                                }, 10)
                            }
                        }, 10)
                }).error(function(b, c) {
                    a._gpt.state = !1
                }).complete(function() {
                    var b = setInterval(function() {
                        null !== a._gpt.state && (a.trigger("AdManager:GPTStateSet", a._gpt.state), a.initialConfigure(), clearInterval(b))
                    }, 20)
                })
            },
```

and
```
 checkAdBlock: function() {
                for (var a, b = Math.random(), c = $(".ads-container>div"), d = c.length, e = Math.floor(b * d), f = window.fbs_settings && window.fbs_settings.classes ? JSON.parse(base64.decode(fbs_settings.classes)) : ["dynamic-ads"], g = [], h = 0; 5 > h || Math.random() < .7 && 10 > h; h++) g.push(f[Math.floor(Math.random() * f.length)]);
                $(c[e]).before(a = $("<div>", {
                    "class": g.join(" ")
                })), this.triggerAdBlockState("none" === a.css("display")), a.remove()
            },
```

Blocking the script itself renders it impossible to get past the welcome page.   

I've forked the project and am working on researching a fix, but I'm not very experienced in JS, would appreciate some help on this.

**Comment by Giwayume** [comment]
My fix doesn't delete those cookies, it sets them to true. It's been working consistently for me the past few days in FF and Chrome.

From what I could tell, the only thing their server was detecting before redirecting to the welcome page was that the 'welcomeAd' cookie was set to 'true'.

**Comment by Giwayume** [comment]
In other words, you don't even need to get past the welcome page or deal with the Javascript on it because it's a cookie issue.

**Comment by BenjaminChe** [comment]
On second look, you're right.   None of the fixes work if the welcome interstitial page is triggered, but your fix does bypass that page.   Thanks for the clarification.
