### ISSUE TITLE
theargus.co.uk

### ISSUE THREAD

**Issue by MrSleeps** [reek/anti-adblock-killer#877]
http://www.theargus.co.uk/news/14163024.Editor_s_note_regarding_Soho_House_and_Brighton_Seafront_Development/?ref=mr&lp=16

http://i.imgur.com/kgsnpLo.jpg
Chrome
Tampermonkey
Adblock Plus
EasyList + Malware + AAK

**Comment by reek** [comment]
Hi,

Ok, I'll kill it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
