### ISSUE TITLE
Office Web App no longer working with this script

### ISSUE THREAD

**Issue by Thaek** [reek/anti-adblock-killer#878]
On-Premise Microsoft Office Web Apps does no longer work when this script is enabled.
Message when trying to open a document: "Sorry, we ran into a problem"

**Comment by reek** [comment]
Hi,
Thank you, I'll add an exception

Merry Christmas
Reek

**Comment by reek** [comment]
Can you give me the address ?

**Comment by Thaek** [comment]
It's an on on premise web service, therefore the url is individual for each business :-(

**Comment by reek** [comment]
then the domain

**Comment by Thaek** [comment]
It's a software product that businesses install and use, so there are literally multiple thousands of different domains.

**Comment by reek** [comment]
I need these domains to exclude them, otherwise I can't help you
