### ISSUE TITLE
4shared.com

### ISSUE THREAD

**Issue by Wiiplay123** [reek/anti-adblock-killer#879]
http://www.4shared.com/video/mL1lHmFYce/Small_Cute_Kitten.htm
http://i.imgur.com/RRBMpJ9.png
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by MajkiIT** [comment]
try this rule:
@@||www.4shared.com/show_ad_.gif$image

**Comment by Wiiplay123** [comment]
Thanks! Finally works now, how did you figure it out so fast?

**Comment by MajkiIT** [comment]
It's good information for me. I'm writing Polish Adblock Filters, so it's easier to find solution.

**Comment by maynak00** [comment]
thanks @MajkiIT
problem with: Static filter /show_ad_ found in:EasyList

**Comment by reek** [comment]
@MajkiIT 
Thanks for rule

**Comment by wyatt8740** [comment]
@reek there's another problem but the same site. Looks like they changed something. Not sure if I should report this on the open bug, but I think that seems appropriate since it is open.
Mozilla Seamonkey
Greasemonkey
Adblock Plus
AakList + EasyList
1000 second countdown:
http://i.imgur.com/hmO1Hic.png

**Comment by maynak00** [comment]
I tested first link with uBlock Origin+Chromium, 20sec waittime(adblocker not detected)
@reek also thanks for:
Static filter @@||ad4.liverail.com^$xmlhttprequest found in: Anti-Adblock Killer | Reek
now video opening in same browser window.
this rule still working(thanks @MajkiIT): @@||www.4shared.com/show_ad_.gif$image

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
