### ISSUE TITLE
merlininkazani.com

### ISSUE THREAD

**Issue by bugrabodur** [reek/anti-adblock-killer#881]
http://www.merlininkazani.com/2015in_en_buyuk_hayal_kirikligi_yaratan_10_oyunu-oyun_galeri-85641p1.html
http://i.imgur.com/35ps3mm.png
Chrome
TamperMonkey
Adblock
AakList

**Comment by MajkiIT** [comment]
Try this:
@@||www.merlininkazani.com/js/ads.js$script,domain=merlininkazani.com

**Comment by bugrabodur** [comment]
Sorry i'm very noob at this. You want me to try this where? Should I add it to somewhere to be able to browse merlininkazani.com?

**Comment by maynak00** [comment]
@bugrabodur add it to your adblocker's custom filters.
Türkçesi: reklam engelleyici olarak kullandığın eklentinin ayarlarına girip yukarıda verilen filtreyi girmen gerekiyor

**Comment by bugrabodur** [comment]
OH! Epic! Thank you very much mate!


________________________________
Gönderen: maynak00 <notifications@github.com>
Gönderildi: 26 Aralık 2015 Cumartesi 15:12
Kime: reek/anti-adblock-killer
Bilgi: bugrabodur
Konu: Re: [anti-adblock-killer] http://www.merlininkazani.com/ (#881)


@bugrabodur<https://github.com/bugrabodur> add it to your adblocker's custom filters.
Türkçesi: reklam engelleyici olarak kullandığın eklentinin ayarlarına girip yukarıda verilen filtreyi girmen gerekiyor

-

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
