### ISSUE TITLE
Ad-Block detect with Player HTML5

### ISSUE THREAD

**Issue by borrougagnou** [reek/anti-adblock-killer#882]
The HTML5 Player detect the ad-block:
https://www.theoplayer.com/documentation/adblock-detection-and-prevention

This website use the anti ad-block with THEO Player:
![capture d ecran 2015-12-26 a 20 12 31](https://cloud.githubusercontent.com/assets/10796546/12007631/202698bc-ac0d-11e5-8e35-e94b98ed6fdd.png)
source:
http://www.wakanim.tv/fr/v2/catalogue/episode/1600/seraph-of-the-end-24
(Register this website for view the video)

and, when I remove the "div" or other for view video, it's impossible look... I have a black screen x.x
![capture d ecran 2015-12-26 a 20 22 11](https://cloud.githubusercontent.com/assets/10796546/12007662/645b0df0-ac0e-11e5-949d-09d08b84a75b.png)

just a sound...
Regards

----
Mozilla Firefox 43.0.2 MAC OSX 10.9
Greasemonkey 3.6
AakList (Anti-Adblock Killer) version 9 and default config.

**Comment by reek** [comment]
Hi,

Already fixed and its works for me.

See: https://github.com/reek/anti-adblock-killer#help

**Comment by borrougagnou** [comment]
I have a Update List and Filter List and no change....
I followed this link:
https://github.com/reek/anti-adblock-killer/issues/844

but I don't change....
I have already read the help page ... but I don't change... I have again the problem...

![capture d ecran 2015-12-27 a 00 24 27](https://cloud.githubusercontent.com/assets/10796546/12008265/3d67937c-ac30-11e5-92ec-15b1b2dc97ac.png)

**Comment by reek** [comment]
Ok, can you provide this infos:
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by borrougagnou** [comment]
?

**Comment by reek** [comment]
I need blocked ressources

**Comment by borrougagnou** [comment]
okay :)
