### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by AgentRev** [reek/anti-adblock-killer#883]
http://www.forbes.com/sites/gordonkelly/2015/08/26/windows-10-how-to-stop-forced-updates/
http://www.forbes.com/forbes/welcome/

Stuck in an infinite redirect loop until ad blocker is disabled:

![Forbes screenshot](http://i.imgur.com/UybqFad.png)

Ad blocker can be re-enabled without issues after getting past that page.

Mozilla Firefox 42.0
uBlock Origin 1.4.0

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/875

**Comment by AgentRev** [comment]
very well, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
