### ISSUE TITLE
cityam.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#884]
Hi, 
on `http://www.cityam.com/226918/tata-steel-confirms-1200-job-cuts`

![cityam](http://i.imgur.com/FEUnUt1l.png)

```
@@||cityam.com^$generichide
||googletagmanager.com/gtm.js?*$domain=cityam.com
@@/AdCode.js$domain=cityam.com
@@|https://securepubads.g.doubleclick.net$domain=cityam.com
```
sources:
https://adblockplus.org/forum/viewtopic.php?f=2&t=41962
https://forums.lanik.us/viewtopic.php?f=64&t=26001

Thanks!

**Comment by reek** [comment]
Ok, thanks

**Comment by maynak00** [comment]
adblocker still detected with uBlock Origin.
maybe not supported($generichide): https://github.com/gorhill/uBlock/issues/967
maybe @@||cityam.com^$generichide converted to(by uBlock Origin) @@||cityam.com^$elemhide

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
