### ISSUE TITLE
Pornhub NETWORK (PHN)

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#887]
**See also EasyList [Pornhub Network (PHN) issue](https://github.com/easylist/easylist/issues/195)**

**Comment by reek** [comment]
Hi,
Ok, thanks

**Comment by flyingzebras** [comment]
@reek As you see these are CSS classes and elements blocked. I suggest that you investigate the JS code to construct a proper JS injection.

**Comment by reek** [comment]
I'll fix this with AakScript

**Comment by flyingzebras** [comment]
@reek Ok, great. When will you add them?

**Comment by reek** [comment]
in a few days.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by flyingzebras** [comment]
@reek uBO have not yet updated AAK. When will it?

**Comment by reek** [comment]
@flyingzebras 
Force an update
<pre>uBlock Origin: Options -> 3rd-party-filters -> Click "Update now"</pre>

**Comment by flyingzebras** [comment]
@reek I did that before you told me about it, but nothing changed.

uBO 1.5.5 point AAK to chrome://ublock0/content/asset-viewer.html?url=https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt do not contain pornhub.com for example.

**Comment by reek** [comment]
@flyingzebras 
Its killed by AakScript not AakList, see instruction

**Comment by flyingzebras** [comment]
@reek So I need to use both uBO and something to execute the script from, say Greasemonkey?

**Comment by reek** [comment]
@flyingzebras 
Yes

**Comment by flyingzebras** [comment]
@reek Thanks.

**Comment by flyingzebras** [comment]
Unfortunately https://directory.fsf.org/wiki/UBlock_Origin have been unapproved until this issue have been resolved.

```Creative Commons Nocommercial, any version (#CC-BY-NC)

    This license does not qualify as free, because there are restrictions on charging money for copies. Thus, we recommend you do not use this license for documentation.

    In addition, it has a drawback for any sort of work: when a modified version has many authors, in practice getting permission for commercial use from all of them would become infeasible.```

**Comment by einstein95** [comment]
New anti-adblock, checks if `page_params.holiday_promo` returns as undefined. When the anti-adblock message is closed, it sets a cookie called `adBlockAlertHidden` to `1`.

**Comment by reek** [comment]
which domains ?

**Comment by einstein95** [comment]
http://www.pornhub.com/ on the mainpage. The message is "Looks like you've enabled AdBlock. Ads suck. Why don't you try the new Premium? It has everything you know and love but with 1080p, full-length videos and NO ADS."

**Comment by reek** [comment]
@einstein95 
Ok, I'll fix it.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by flyingzebras** [comment]
@reek NEWS: The tube8 sites have added block detection:

* tube8.com
* de.tube8.com
* jp.tube8.com
* tube8.es
* tube8.fr

**Comment by reek** [comment]
@flyingzebras 
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by flyingzebras** [comment]
@reek again: The tube8 sites have added block detection:

* [tube8.com](http://tube8.com), [de.tube8.com](http://de.tube8.com), [jp.tube8.com](http://jp.tube8.com)
* [tube8.es](http://tube8.es)
* [tube8.fr](http://tube8.fr)

Please open this issue.

**Comment by reek** [comment]
Killed by AakLiat, force update

**Comment by flyingzebras** [comment]
@reek I clicked on "Purge cache" in uBlock Origin and then on "Update now".

I only find this in AAKList:
>@@||media.trafficjunky.net/js/holiday-promo.js$script,domain=pornhub.com|tube8.fr|tube8.es|tube8.com

I still get this message on the tube8 sites: "You have Adblock enabled. Adblock has been known to cause issues with site functionality. If you experience any difficulties, please try disabling Adblock."

**Comment by reek** [comment]
@flyingzebras 
it is because of this rule uBO, disables it
`||trafficjunky.net^$important,third-party`

@gorhill
can you update this rule to
`||trafficjunky.net^$important,third-party,~domain=pornhub.com|tube8.fr|tube8.es|tube8.com`

**Comment by gorhill** [comment]
Why not just create the filter `pornhub.com,tube8.fr,tube8.es,tube8.com###adBlockAlertWrap`? This would not require allowing a 3rd-party connection.

**Comment by reek** [comment]
@gorhill 
it is also good, thank you

**Comment by flyingzebras** [comment]
@reek 

@reek gorhill said
> Why not just create the filter pornhub.com,tube8.fr,tube8.es,tube8.com###adBlockAlertWrap? This would not require allowing a 3rd-party connection.

I do not find this filter in uBO filters subscriptions nor in Anti-Adblock Killer List. Who's gonna add it?

**Comment by reek** [comment]
@flyingzebras 
I will add

**Comment by flyingzebras** [comment]
@reek It is still there.

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by flyingzebras** [comment]
Adblock detection active on all these domains now:

* [tube8.com](http://tube8.com)
* [tube8.fr](http://tube8.fr)
* [tube8.es](http://tube8.es)
* [youporn.com](http://youporn.com)
* [youporngay.com](http://youporngay.com)

**Comment by flyingzebras** [comment]
@reek Please have a look.

**Comment by flyingzebras** [comment]
@reek You said that you were going to add tube8* [17th Jul](https://github.com/reek/anti-adblock-killer/issues/887#issuecomment-233185339)

**Comment by flyingzebras** [comment]
@reek 

Adblock detection active on these Pornhub NETWORK sites:

* [tube8.com](http://tube8.com)
* [tube8.es](http://tube8.es)
* [tube8.fr](http://tube8.fr)
* [youporn.com](http://youporn.com)
* [youporngay.com](http://youporngay.com)

Todos
* Rename `youporn_network` (typo) to `pornhub_network_bar` (xtube.com is not owned by Pornhub but listed in the Pornhub NETWORK menu bar)

Add all Pornhub NETWORK listed domains like this:

>       pornhub_network_bar : {
>         // issue: https://github.com/reek/anti-adblock-killer/issues/887
>        // source: http://pastebin.com/TFB1dtgb
>         host : ['pornhub.com', 'porniq.com', 'pornmd.com', 'redtube.com', 'redtube.com.br', 'tube8.com', 'tube8.es', 'tube8.fr', 'thumbzilla.com', 'youporn.com', 'youporngay.com', 'xtube.com'],
>         ...
>         }
>       },


* Repair script for youporn.com and youporngay.com because the current script seen here have no effect on them:

>         onStart : function () {
>           Aak.setCookie("adblock_message", "closed");

* Add script for tube8.com, tube8.es, tube8.fr.

**Comment by flyingzebras** [comment]
I added a separate issue for [Pornhub Network (PHN)](https://github.com/reek/anti-adblock-killer/issues/2244) as MindGeek confirmed that they do not own Spankwire Sites as I thought.

**Comment by flyingzebras** [comment]
Adblock detection are active on these Pornhub NETWORK sites:

* [tube8.com](http://tube8.com)
* [tube8.es](http://tube8.es)
* [tube8.fr](http://tube8.fr)
* [youporn.com](http://youporn.com)
* [youporngay.com](http://youporngay.com)

Todos
* Rename `youporn_network` (typo) to `pornhub_network_bar` (xtube.com is not owned by Pornhub but listed in the Pornhub NETWORK menu bar)

Add all Pornhub NETWORK listed domains like this:

>       pornhub_network_bar : {
>         // issue: https://github.com/reek/anti-adblock-killer/issues/887
>        // source: http://pastebin.com/TFB1dtgb
>         host : ['pornhub.com', 'porniq.com', 'pornmd.com', 'redtube.com', 'redtube.com.br', 'tube8.com', 'de.tube8.com', 'jp.tube8.com', 'tube8.es', 'tube8.fr', 'thumbzilla.com', 'youporn.com', 'youporngay.com', 'xtube.com'],
>         ...
>         }
>       },


* Repair script for youporn.com and youporngay.com because the current script seen here have no effect on them:

>         onStart : function () {
>           Aak.setCookie("adblock_message", "closed");

* Add script for tube8.com, tube8.es, tube8.fr. Please remove `de.tube8.com, jp.tube8.com` from the script if sub domains are included automatically.

**Comment by flyingzebras** [comment]
Adblock detection are active on these Pornhub NETWORK sites:

* [youporn.com](http://youporn.com)
* [youporngay.com](http://youporngay.com)

Todos
* Rename `youporn_network` (typo) to `pornhub_network_bar` (xtube.com is not owned by Pornhub but listed in the Pornhub NETWORK menu bar)

tube8.com, tube8.es, tube8.fr have removed their anti-adblock detection. However, add all Pornhub NETWORK listed domains like this to make sure they _always_ will be blocked, no matter if they turn them on/off at random times on random sites:

>       pornhub_network_bar : {
>         // issue: https://github.com/reek/anti-adblock-killer/issues/887
>        // source: http://pastebin.com/TFB1dtgb
>         host : ['pornhub.com', 'porniq.com', 'pornmd.com', 'redtube.com', 'redtube.com.br', 'tube8.com', 'de.tube8.com', 'jp.tube8.com', 'tube8.es', 'tube8.fr', 'thumbzilla.com', 'youporn.com', 'youporngay.com', 'xtube.com'],
>         ...
>         }
>       },


* Repair script for youporn.com and youporngay.com because the current script seen here have no effect on them:

>         onStart : function () {
>           Aak.setCookie("adblock_message", "closed");

**Comment by flyingzebras** [comment]
# AAK 9.9

Adblock detection are active on these Pornhub NETWORK sites:

* [youporn.com](http://youporn.com)
* [youporngay.com](http://youporngay.com)

Todos
* Rename `youporn_network` (typo) to `pornhub_network_bar` (xtube.com is not owned by Pornhub but listed in the Pornhub NETWORK menu bar)

tube8.com, tube8.es, tube8.fr have removed their anti-adblock detection. However, add all Pornhub NETWORK listed domains like this to make sure they _always_ will be blocked, no matter if they turn them on/off at random times on random sites:

>       pornhub_network_bar : {
>         // issue: https://github.com/reek/anti-adblock-killer/issues/887
>        // source: http://pastebin.com/TFB1dtgb
>         host : ['pornhub.com', 'porniq.com', 'pornmd.com', 'redtube.com', 'redtube.com.br', 'tube8.com', 'de.tube8.com', 'jp.tube8.com', 'tube8.es', 'tube8.fr', 'thumbzilla.com', 'youporn.com', 'youporngay.com', 'xtube.com'],
>         ...
>         }
>       },


* Repair script for youporn.com and youporngay.com because the current script seen here have no effect on them:

>         onStart : function () {
>           Aak.setCookie("adblock_message", "closed");
