### ISSUE TITLE
al.ly

### ISSUE THREAD

**Issue by CalleHD** [reek/anti-adblock-killer#888]
Hi!
This link shortener blocks adblock!
[here example](http://al.ly/qBbXH)

![Image of Site](http://imgur.com/fomixeD.jpg)

Mozilla Firefox
Greasemonkey
Adblock Plus
EasyListGermany+EasyList + AakList

Could you fix it?

**Comment by reek** [comment]
Hi,

OK, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
