### ISSUE TITLE
hahasport.so / hahasport.me

### ISSUE THREAD

**Issue by rafuse** [reek/anti-adblock-killer#889]
http://hahasport.me/soccer
(open one of the links at the bottom of the page as the first few links are mostly offline)

http://imgur.com/HGvktEK
Mozilla Firefox 43
Greasemonkey
uBlock Origin 1.5.1 (default settings/filterlists)
EasyList +  Peter Lowe’s Ad server list + EasyPrivacy

**Comment by reek** [comment]
Hi,

Ok, I'll kill it.

See you
Reek

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rafuse** [comment]
Perfect, thank you!
