### ISSUE TITLE
Anti-Adblock Killer | Reek prompts in uBlock

### ISSUE THREAD

**Issue by rpodric** [reek/anti-adblock-killer#890]
Hi, thanks for all the hard work.

I've been noticing this in current versions of Firefox (Windows) over the last month or two, with uBlock.

Despite "Anti-Adblock Killer | Reek" being checked, about once a week the "Anti-Adblock Killer | Reek" user script (v9.0 now) displays a message saying "It seems that you have not subscribed to AakList (Anti-Adblock Killer."

I ignored that for a while, thinking that it was a mistake, but eventually I subscribed to it to see if it was different in any way from "Anti-Adblock Killer | Reek," which I'm subscribed to (and which is always updated) via uBlock.

The URL that subscribing to "AakList (Anti-Adblock Killer)" adds is:
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

The URL used in "Anti-Adblock Killer | Reek" in uBlock is:
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

Different URLs, but the same list. Maybe that's the issue in the detection logic?

**Comment by reek** [comment]
Hi,
I know, I will correct.

you can disable this notification here
http://reek.github.io/anti-adblock-killer/#settings

2015-12-28 21:37 GMT+01:00 rpodric <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by rpodric** [comment]
Thank you

**Comment by libove** [comment]
As per @zax-ftw's reference above this exact thing is now happening also to me presently. 
Chrome 64-bit  64.0.3282.167 on Windows 10 Enterprise 10.0.16299 Build 16299 (1709 Fall Creators Update).
