### ISSUE TITLE
kissanime.to

### ISSUE THREAD

**Issue by Smokeythebull** [reek/anti-adblock-killer#891]
So kissanime seems to be detecting im blocking ads, it was working fine and I dont believe anything has changed on my end. Hope I'm doing this right

http://i.imgur.com/MIkyWZn.jpg
chrome
im using ublock origin so im not too sure if that has its own scriptmanager...
Only use the stuff filterlists that are default on ublock origin

**Comment by xxcriticxx** [comment]
please install tamper monkey from https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo and user scripts from step 3 http://tinyurl.com/nd4qwlz

**Comment by reek** [comment]
@Smokeythebull 
Yes, require Tampermonkey + AakScript
