### ISSUE TITLE
openload.co (indiansexmms.co)

### ISSUE THREAD

**Issue by madeforonlyyou** [reek/anti-adblock-killer#892]
http://indiansexmms.co/2015/12/desi-secretary-for-promotion-enjoying-with-boss/ (NSFW)
(the second video player from openload.co, detects adblock and refuses to play video)

Browser: Google chrome Version 47.0.2526.106 (64-bit)
adblocker: ublock origin 0.9.9.1
screenshot: https://imgur.com/gallery/S0390zC
My enabled filters:
uBlock filters
uBlock filters – Privacy‎ 
uBlock filters – Unbreak‎ 
Adblock Warning Removal List‎ (forums.lanik.us):
Anti-Adblock Killer | Reek‎  (github.com):
EasyList without element hiding rules‎ (forums.lanik.us): 
Peter Lowe’s Ad server list‎ (pgl.yoyo.org)
Malware Domain List‎ (malwaredomainlist.com)
Malware domains‎ (www.malwaredomains.com)
Malware domains (long-lived)‎ (www.malwaredomains.com)

**Comment by xxcriticxx** [comment]
you got users scripts and tamper monkey installed?

please install tamper monkey from https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo and user scripts from step 3 http://tinyurl.com/nd4qwlz

**Comment by madeforonlyyou** [comment]
@xxcriticxx works. thanks
