### ISSUE TITLE
putlocker.is

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#894]
Hi;
on `http://putlocker.is/watch-suits-tvshow-season-1-episode-1-online-free-putlocker.html`
scr: http://i.imgur.com/DpdEcSc.png
`@@||jsc.mgid.com^*/putlocker.is.$script,domain=putlocker.is`
source: https://forums.lanik.us/viewtopic.php?f=64&p=83395

Thanks!

**Comment by reek** [comment]
Hi,
Ok, thanks Med :+1: 

Related: https://greasyfork.org/fr/forum/discussion/7602/

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by markhascole** [comment]
No doubt Putlocker is the best for watching movies online free but for any reason if you are looking for the alternate of Putlocker than you can go for Afdah, And here is the complete guide about Afdah.

[https://www.reviewsdir.com/watch-afdah-movies-and-tv-shows/](https://www.reviewsdir.com/watch-afdah-movies-and-tv-shows/)
