### ISSUE TITLE
anibatch.net

### ISSUE THREAD

**Issue by aryacebe** [reek/anti-adblock-killer#895]
please add anibatch.net site to script, thx

**Comment by reek** [comment]
Hi,

I'll take a look

**Comment by einstein95** [comment]
The page has a hidden button that calls `bsakAM4JlY.r('bsakAM4JlY')` which closes the adblock warning

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
