### ISSUE TITLE
agarserv.com

### ISSUE THREAD

**Issue by ZfsrGhS953** [reek/anti-adblock-killer#896]
http://www.agarserv.com/no-ad-blocker/
http://i.imgur.com/vsd7Svt.png
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by MajkiIT** [comment]
Try add this rule on whitelist 
agarserv.com#@##adsense

**Comment by ZfsrGhS953** [comment]
Thanks, it worked!

**Comment by reek** [comment]
@MajkiIT 
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
