### ISSUE TITLE
gq.com

### ISSUE THREAD

**Issue by caneda83** [reek/anti-adblock-killer#898]
http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
http://imgur.com/iKplF05
Google Chrome
Tampermonkey
Adblock Plus
Adblock Warning Removal List + EasyList + AakList

**Comment by reek** [comment]
I have nothing :/

**Comment by xxcriticxx** [comment]
same here maybe it was test they getting ready to deploy something

**Comment by caneda83** [comment]
Try clicking through to one of the articles. I'm getting it on all of them.

**Comment by xxcriticxx** [comment]
i did click through some articles 

are you in usa?

can you try to see if you get them in firefox?

can you try purge all cache and update now again and see what you get

**Comment by caneda83** [comment]
Yep, in the USA. I don't use Firefox (not even on my computer), so I can't try it.
Cleared Chrome's cache, updated Adblock Plus, tried again, found this: http://imgur.com/d1cOcwy

**Comment by xxcriticxx** [comment]
i guess we wait for other people to confirm i dont see it on firefox

**Comment by xxcriticxx** [comment]
http://imgur.com/a/mC4iA on firefox

**Comment by Giwayume** [comment]
I am also not getting it, Firefox or Chrome.

**Comment by reek** [comment]
@caneda83 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by caneda83** [comment]
Here's the source code I'm seeing: https://gist.github.com/anonymous/6c538c9f367fe9952998

**Comment by caneda83** [comment]
Here's the source code I'm seeing: https://gist.github.com/anonymous/6c538c9f367fe9952998

**Comment by caneda83** [comment]
Hit the wrong button there...

**Comment by reek** [comment]
@caneda83 
Lack: extensions, userscripts, blocked resources:

**Comment by caneda83** [comment]
Extensions: Adblock Plus, Evernote Web Clipper, Google Docs, Google Docs Offline, Google Hangouts, Google Sheets, Google Slides, Instagram for Chrome, Pin It Button, RescuTime for Chrome & Chrome OS, StayFocusd, Tampermonkey, UglyEmail

Userscripts: Anti-Adblock Killer

Adblock Plus doesn't give me the option to show blocked resources, and I'm in Chrome.

**Comment by reek** [comment]
@caneda83 
Try with uBlock and give me the blocked resources.

**Comment by caneda83** [comment]
Pop-up doesn't show with uBlock!

Here's the log:

19:20:28				image	http://www.gq.com/favicon.png
19:20:27		##.ytp-ad-progress-list	--	dom	https://www.youtube.com/embed/W55b4BcCPM4
19:20:27		##.text_ads	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.text_ad	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.textAd	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.text-ads	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.text-ad-links	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.text-ad	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.pub_728x90	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.pub_300x250m	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27		##.pub_300x250	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:27				xhr	https://api.bam-x.com/api/v0/events/publisher/gq/page_view/
19:20:27				image	http://www.gq.com/favicon.png
19:20:27				font	https://fonts.gstatic.com/s/roboto/v15/CWB0XYA8bzo0kSThX0UTuA.woff2
19:20:27				xhr	https://api.bam-x.com/api/v0/events/publisher/gq/page_view/
19:20:27				font	https://fonts.gstatic.com/s/roboto/v15/mErvLBYg_cXG3rLvUsKT_fesZW2xOQ-xsNqO47m55DA.woff2
19:20:27				image	https://i.ytimg.com/vi_webp/W55b4BcCPM4/sddefault.webp
19:20:27		||chartbeat.com^	--	script	http://static.chartbeat.com/js/chartbeat.js
19:20:26				inline-script	http://staticxx.facebook.com/connect/xd_arbiter.php?version=42#channel=f20442b1a8&origin=http%3A%2F%2Fwww.gq.com
19:20:26		/b/ss/*&aqe=	--	image	http://stats2.gq.com/b/ss/conde-gqcom/1/JS-1.4.1-D5NH/s82691637084353?AQB=1&ndh=1&pf=1&t=5%2F0%2F2016%2019%3A20%3A26%202%20300&D=D%3D&fid=256D6AB0F4865B17-041311497AF5FA69&ce=UTF-8&ns=condenast&pageName=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&g=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&r=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&cc=USD&ch=News%20Culture&v0=social_twitter&events=event2%2Cevent82%3D1&v2=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&l2=Sparklers%7CFireworks%7CNew%20Year&c3=D%3Dv3&v3=Celebrate%20the%20New%20Year%20by%20Watching%20a%20Guy%20Light%2010%2C000%20Sparklers%20at%20Once&c4=D%3Dv4&v4=56859c3bbc00c1ec1f141e60&c5=D%3Dv5&v5=article&c6=D%3Dv6&v6=News%20Culture&c7=D%3Dv7&v7=News%20Culture%2FNews&c11=D%3Dv11&v11=8%3A20%20PM%7CTuesday&v15=D%3Dv0&c16=not%20logged%20in&v16=not%20logged%20in&c17=6&v17=6&v20=D%3Dv0&c23=D%3Dv23&v23=Repeat&v24=1451671444684-581113.17_48&c30=D%3Dv30&v30=t.co&c32=D%3Dv32&v32=all&c34=article%7Cno%20value&c35=article&v35=article&c39=D%3Dv39&v39=t.co&c44=D%3Dv44&v44=null&c51=D%3Dv51&v51=desktop%20layout%3A1920x955&c55=D%3Dv55&v55=Jack%20Moore&c56=D%3Dv56&v56=1.6&c60=D%3Dv60&v60=null&c61=D%3Dv61&v61=104h%7C4d&c62=D%3Dv62&v62=2016-01-01T16%3A07%3A40.140Z&c68=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&v68=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&s=1920x1080&c=24&j=1.6&v=N&k=Y&bw=1920&bh=955&AQE=1
19:20:26				inline-script	https://staticxx.facebook.com/connect/xd_arbiter.php?version=42#channel=f20442b1a8&origin=http%3A%2F%2Fwww.gq.com
19:20:26		||mookie1.com^$third-party	--	script	http://b3.mookie1.com/2/LB/2280152163@x96?
19:20:26		||pixel.condenastdigital.com^	--	script	http://pixel.condenastdigital.com/config/gq.config.js
19:20:26		||scorecardresearch.com^	--	script	http://b.scorecardresearch.com/beacon.js
19:20:26		||scorecardresearch.com^	--	image	http://b.scorecardresearch.com/b?c1=2&c2=6035094&ns__t=1452039626577&ns_c=UTF-8&c8=Celebrate%20the%20New%20Year%20by%20Watching%20a%20Guy%20Light%2010%2C000%20Sparklers%20at%20Once%20%7C%20GQ&c7=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&c9=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter
19:20:26				frame	https://staticxx.facebook.com/connect/xd_arbiter.php?version=42#channel=f20442b1a8&origin=http%3A%2F%2Fwww.gq.com
19:20:26				frame	http://staticxx.facebook.com/connect/xd_arbiter.php?version=42#channel=f20442b1a8&origin=http%3A%2F%2Fwww.gq.com
19:20:26				image	https://api.bam-x.com/api/v0/session.gif?uid_bam=1558720350512121416
19:20:26		/event.gif?	--	xhr	http://event.condenastdigital.com/images/event.gif?e0_id=www.gq.com%2Fblocked_pageview&e0_ec=adblock&e0_env=dart&e0_sc=gq&e0_tit=Chrome%2C47.0.2526.106&e0_url=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&_=1452039624711
19:20:26		||facebook.com*/impression.php	--	image	https://www.facebook.com/impression.php/f3f40d354/?lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/s-code-contents-01f1a94c6a1e25b10009edf074a5c96fca0adcbd.js
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-5630268564746d6aa1002790.js
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-5612d1ab33663100170000ce.js
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-55d35214343538702e0004eb.js
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-551199493032300017ff0300.js
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-55887f29373031001400021f.js
19:20:26				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-55887f293730310014000230.js
19:20:26		||doubleclick.net^	--	script	https://static.doubleclick.net/instream/ad_status.js
19:20:26				script	https://www.google.com/js/bg/-Ps1iJvWGBmTVUUzMYLqRAlGj-KyO_h0L7-M6Ghkbv8.js
19:20:25		##.sticky-ad	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:25		##.displayAd	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:25		##.ad-wrapper	--	dom	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:25		/b/ss/*&aqe=	--	image	http://stats2.gq.com/b/ss/conde-gqcom/1/JS-1.4.1-D5NH/s82910033911466?AQB=1&ndh=1&pf=1&t=5%2F0%2F2016%2019%3A20%3A25%202%20300&D=D%3D&fid=256D6AB0F4865B17-041311497AF5FA69&ce=UTF-8&ns=condenast&pageName=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&g=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&r=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&cc=USD&ch=News%20Culture&v0=social_twitter&events=event2%2Cevent82%3D43&v2=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&l2=Sparklers%7CFireworks%7CNew%20Year&c3=D%3Dv3&v3=Celebrate%20the%20New%20Year%20by%20Watching%20a%20Guy%20Light%2010%2C000%20Sparklers%20at%20Once&c4=D%3Dv4&v4=56859c3bbc00c1ec1f141e60&c5=D%3Dv5&v5=article&c6=D%3Dv6&v6=News%20Culture&c7=D%3Dv7&v7=News%20Culture%2FNews&c11=D%3Dv11&v11=8%3A20%20PM%7CTuesday&v15=D%3Dv0&c16=not%20logged%20in&v16=not%20logged%20in&c17=6&v17=6&v20=D%3Dv0&c23=D%3Dv23&v23=Repeat&v24=1451671444684-581113.17_48&c30=D%3Dv30&v30=t.co&c32=D%3Dv32&v32=all&c34=article%7Cno%20value&c35=article&v35=article&c39=D%3Dv39&v39=t.co&c44=D%3Dv44&v44=null&c51=D%3Dv51&v51=desktop%20layout%3A1920x955&c55=D%3Dv55&v55=Jack%20Moore&c56=D%3Dv56&v56=1.6&c60=D%3Dv60&v60=null&c61=D%3Dv61&v61=104h%7C4d&c62=D%3Dv62&v62=2016-01-01T16%3A07%3A40.140Z&c68=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&v68=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&s=1920x1080&c=24&j=1.6&v=N&k=Y&bw=1920&bh=955&AQE=1
19:20:25		||demdex.net^$third-party	--	script	http://condenast.demdex.net/event?d_nsid=0&d_ld=_ts%3D1452039625780&c_pageName=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&c_referrer=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&c_channel=News%20Culture&c_campaign=social_twitter&c_events=event2%2Cevent82%3D43&c_eVar2=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&c_prop3=D%3Dv3&c_eVar3=Celebrate%20the%20New%20Year%20by%20Watching%20a%20Guy%20Light%2010%2C000%20Sparklers%20at%20Once&c_prop4=D%3Dv4&c_eVar4=56859c3bbc00c1ec1f141e60&c_prop5=D%3Dv5&c_eVar5=article&c_prop6=D%3Dv6&c_eVar6=News%20Culture&c_prop7=D%3Dv7&c_eVar7=News%20Culture%2FNews&c_prop11=D%3Dv11&c_eVar11=8%3A20%20PM%7CTuesday&c_eVar15=D%3Dv0&c_prop16=not%20logged%20in&c_eVar16=not%20logged%20in&c_prop17=6&c_eVar17=6&c_eVar20=D%3Dv0&c_prop23=D%3Dv23&c_eVar23=Repeat&c_eVar24=1451671444684-581113.17_48&c_prop30=D%3Dv30&c_eVar30=t.co&c_prop32=D%3Dv32&c_eVar32=all&c_prop34=article%7Cno%20value&c_prop35=article&c_eVar35=article&c_prop39=D%3Dv39&c_eVar39=t.co&c_prop44=D%3Dv44&c_eVar44=null&c_prop51=D%3Dv51&c_eVar51=desktop%20layout%3A1920x955&c_prop55=D%3Dv55&c_eVar55=Jack%20Moore&c_prop56=D%3Dv56&c_eVar56=1.6&c_prop60=D%3Dv60&c_eVar60=null&c_prop61=D%3Dv61&c_eVar61=104h%7C4d&c_prop62=D%3Dv62&c_eVar62=2016-01-01T16%3A07%3A40.140Z&c_prop68=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&c_eVar68=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once&d_rtbd=json&d_jsonv=1&d_dst=1&d_cb=demdexRequestCallback_condenast_0_1452039625780
19:20:25		||pixel.condenastdigital.com^	--	script	http://pixel.condenastdigital.com/config/gq.config.js
19:20:25		||mookie1.com^$third-party	--	script	http://b3.mookie1.com/2/LB/1348527048@x96?
19:20:25		||scorecardresearch.com^	--	script	http://b.scorecardresearch.com/beacon.js
19:20:25		||scorecardresearch.com^	--	image	http://b.scorecardresearch.com/b?c1=2&c2=6035094&ns__t=1452039625726&ns_c=UTF-8&c8=Celebrate%20the%20New%20Year%20by%20Watching%20a%20Guy%20Light%2010%2C000%20Sparklers%20at%20Once%20%7C%20GQ&c7=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter&c9=http%3A%2F%2Fwww.gq.com%2Fstory%2F10000-sparklers-at-once%3Fmbid%3Dsocial_twitter
19:20:25				inline-script	https://api.bam-x.com/api/v0/session.html
19:20:25				frame	https://api.bam-x.com/api/v0/session.html
19:20:25				script	https://s.ytimg.com/yts/jsbin/player-en_US-vflnrstgx/base.js
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/s-code-contents-01f1a94c6a1e25b10009edf074a5c96fca0adcbd.js
19:20:25		/delivery/afr.	--	frame	http://www.yimgr.com/support/www/delivery/afr.php?zoneid=141&refresh=110&cb=1452039625524&beacon=af014acc&n=a7f6970b
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-5630268564746d6aa1002790.js
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-5612d1ab33663100170000ce.js
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-55d35214343538702e0004eb.js
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-551199493032300017ff0300.js
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-55887f29373031001400021f.js
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/scripts/satellite-55887f293730310014000230.js
19:20:25				script	http://static.bam-x.com/tags/gq.js
19:20:25		||demdex.net^$third-party	--	script	http://condenast.demdex.net/event?d_stuff=1&d_dst=1&d_rtbd=json&d_cts=1&d_cb=aam_tnt_cb
19:20:25				inline-script	https://www.youtube.com/embed/W55b4BcCPM4
19:20:25		/ads/js/*	--	script	http://stag-cnads.condenastdigital.com/gq/ads/js/CN.dart.bun.js?_=1452039624710
19:20:25				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/mbox-contents-4c9cd512e7257ced6500aeeb800bab773ab71aba.js
19:20:25				image	http://media.gq.com/photos/56859e2f6aec210a6d1e38cd/master/w_840/Screen%20Shot%202015-12-31%20at%204.29.01%20PM.png
19:20:25				frame	https://www.youtube.com/embed/W55b4BcCPM4
19:20:25		||outbrain.com^	--	script	http://widgets.outbrain.com/outbrain.js
19:20:25				frame	https://www.youtube.com/embed/W55b4BcCPM4
19:20:25		/ads/js/*	--	xhr	http://www.gq.com/ads/js/cn.dart.bun.min.js?_=1452039624709
19:20:25				image	http://www.gq.com/images/logo-condenast.svg
19:20:25				script	https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0
19:20:25				image	http://www.gq.com/images/logo-instagram-gray.svg
19:20:25				image	http://www.gq.com/images/logo-tumblr-gray.svg
19:20:25				image	http://www.gq.com/images/logo-youtube-gray.svg
19:20:25				image	http://www.gq.com/images/logo-pinterest-gray.svg
19:20:24				image	http://www.gq.com/images/logo-twitter-gray.svg
19:20:24				image	http://www.gq.com/images/logo-facebook-gray.svg
19:20:24				image	http://www.gq.com/images/email-grey-sm.svg
19:20:24				image	http://www.gq.com/images/icon-facebook.svg
19:20:24				image	http://www.gq.com/images/icon-twitter.svg
19:20:24				image	http://www.gq.com/images/icon-pinterest-white.svg
19:20:24				image	http://www.gq.com/images/icon-facebook-white.svg
19:20:24				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/satelliteLib-c8da90121eaa0187860621724d5dfa1353fa5220.js
19:20:24		||static.parsely.com^$third-party	--	script	http://static.parsely.com/p.js
19:20:24				font	http://www.gq.com/fonts/A2regular/Regular-Bold.woff
19:20:24				font	http://www.gq.com/fonts/A2regular/Regular-Regular.woff
19:20:24				font	http://www.gq.com/fonts/Titling-Gothic-Narrow-Medium/Titling-Gothic-Narr-Medium.woff
19:20:24				image	http://www.gq.com/images/logo-gq-red-blue.svg
19:20:24				image	http://www.gq.com/images/icon-search.svg
19:20:24				image	http://www.gq.com/images/icon-newsletter.svg
19:20:24				font	http://www.gq.com/fonts/A2regular/Regular-SemiBold.woff
19:20:24				image	http://www.gq.com/images/logo-gq-red-blue-clipped.svg
19:20:24				script	http://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0
19:20:24				script	https://platform.instagram.com/en_US/embeds.js
19:20:24				script	https://platform.twitter.com/widgets.js
19:20:24		||boomtrain.com^$third-party	--	script	http://cdn.boomtrain.com/analyticstrain/9da018f363ab71187ba6154eee01217d/analyticstrain.min.js
19:20:24				script	https://s.ytimg.com/yts/jsbin/player-en_US-vflnrstgx/base.js
19:20:24				script	https://s.ytimg.com/yts/jsbin/www-embed-player-vflPrvcMb/www-embed-player.js
19:20:24				css	https://s.ytimg.com/yts/cssbin/www-embed-player-webp-vfl3j4Zuz.css
19:20:24				inline-script	https://www.youtube.com/embed/W55b4BcCPM4
19:20:24				script	http://www.gq.com/js/app.js
19:20:24				frame	https://www.youtube.com/embed/W55b4BcCPM4
19:20:24				script	http://assets.adobedtm.com/6372cf21ef88ee60bc2977a4898dcb5c7945a212/satelliteLib-c8da90121eaa0187860621724d5dfa1353fa5220.js
19:20:24				script	https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js
19:20:24				script	http://www.gq.com/js/app.js
19:20:24				image	http://media.gq.com/photos/56859e2f6aec210a6d1e38cd/master/w_680/Screen%20Shot%202015-12-31%20at%204.29.01%20PM.png
19:20:24				css	http://www.gq.com/css/v2/app.css
19:20:24		||optimizely.com^$third-party	--	script	http://cdn.optimizely.com/js/2755060886.js
19:20:24				inline-script	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter
19:20:24				doc	http://www.gq.com/story/10000-sparklers-at-once?mbid=social_twitter

**Comment by reek** [comment]
@caneda83 
Thanks, I have detected anti-adblock, they use a modified version of fuckadblock

**Comment by reek** [comment]
@caneda83 
Add these rules
<pre>
gq.com#@#.pub_300x250
gq.com#@#.pub_300x250m
gq.com#@#.pub_728x90
gq.com#@#.text-ad
gq.com#@#.textAd
gq.com#@#.text_ad
gq.com#@#.text_ads
gq.com#@#.text-ads
gq.com#@#.text-ad-links
</pre>

**Comment by caneda83** [comment]
Ok. Where? How?

**Comment by reek** [comment]
To uBlock -> option -> my filters
(This is to test if it works I would add to AakList)

**Comment by caneda83** [comment]
Ok. Not AdBlock Plus? uBlock was blocking it already.

**Comment by reek** [comment]
@caneda83 
we'll allowed, and not blocked because they are bait.

yes, you can do so on ABP, look at the options

**Comment by caneda83** [comment]
@reek Yep, those worked beautifully. Not showing with ABP anymore. Thanks!

**Comment by reek** [comment]
@caneda83 
Great  :smile:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
