### ISSUE TITLE
mangahop.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#899]
Hi;
on `http://www.mangahop.com/douluo_dalu_ii_jueshui_tangmen/58/8/`

![mangahop](http://i.imgur.com/T5RwiPV.png)

```
mangahop.com#@#.afs_ads
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=mangahop.com
@@||pagead2.googlesyndication.com/pagead/js/*/show_ads_impl.js$script,domain=mangahop.com
```

**Comment by reek** [comment]
Thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
