### ISSUE TITLE
crichd.tv

### ISSUE THREAD

**Issue by dt4ever** [reek/anti-adblock-killer#900]
http://www.crichd.tv/bt-sport-1-live-stream.php
http://imgur.com/8MhOWIx
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by Giwayume** [comment]
I'm new to this syntax, try this:
```
cast4u.tv##div#notice,div#adblock,div#video_ads_overdiv,div#floatLayer2
```

**Comment by reek** [comment]
@dt4ever 
Ok, I'll kill it

@Giwayume 
Thanks for rule

**Comment by dt4ever** [comment]
thanks a lot it works

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
