### ISSUE TITLE
4shared.com

### ISSUE THREAD

**Issue by rayman89** [reek/anti-adblock-killer#903]
Again 4shared.com displays the message that you have adblock so you have to wait 1k seconds for download instead of 20.

Example link http://www.4shared.com/get/LD5Tb_LVce/Dark_4_Image_Pack.html

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/903

**Comment by rayman89** [comment]
you mean #879 ? Wasn't that for 4shared blocking videos?

**Comment by einstein95** [comment]
Fixed in https://github.com/reek/anti-adblock-killer/pull/911

**Comment by reek** [comment]
@einstein95 
Thanks for fix
