### ISSUE TITLE
hornmatters.com

### ISSUE THREAD

**Issue by jameshilliard** [reek/anti-adblock-killer#904]
1. http://hornmatters.com/
2. 

![antiadblock](http://i.imgur.com/BculfTR.png)
3. Firefox
4. Greasemonkey
5. uBlock Origin
6. EasyList + AakList +  Adblock Warning Removal List‎ +  uBlock filters‎ +  uBlock filters – Privacy + uBlock filters – Unbreak

**Comment by MajkiIT** [comment]
Add this rule to my filters
hornmatters.com#@#.footer_ad

**Comment by reek** [comment]
@jameshilliard 
Ok, I'll kill it

@MajkiIT 
Thanks for rule

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
