### ISSUE TITLE
autokult.pl

### ISSUE THREAD

**Issue by mkozioro** [reek/anti-adblock-killer#905]
http://autokult.pl/26924,continental-czarno-widzi-przyszlosc-silnikow-diesla-w-samochodach-osobowych
Videos on that page
Mozilla Firefox
uBlock Origin
EasyList + AakList + Greasemonkey with usescript Install from greasyfork.org

**Comment by MajkiIT** [comment]
@reek 
add this domain to script
// Poland
    wp_domains : {
      // issue:  https://github.com/reek/anti-adblock-killer/issues/300
      host : ['biztok.pl', 'wp.tv', 'wp.pl', 'sportowefakty.pl', 'kafeteria.tv', '.wrzuta.pl', 'pudelek.tv', 'komediowo.pl', 'sfora.pl', 'autokrata.pl', 'sportfan.pl', 'wawalove.pl', 'hotmoney.pl', 'aleseriale.pl', 'babol.pl', 'snobka.pl', 'nocoty.pl', 'money.pl', 'abczdrowie.pl'],
      onIdle : function () {

**Comment by reek** [comment]
@mkozioro 
Ok, I'll kill it

@MajkiIT 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
