### ISSUE TITLE
vg.no anti-adblock

### ISSUE THREAD

**Issue by hansskogvold** [reek/anti-adblock-killer#906]
http://www.vg.no/
![asd](http://i.imgur.com/fFGjhP8.png)

they use that `<srrzp class="srrzp">` where srrzp is a random string trick

**Comment by reek** [comment]
HI,

It's killed for me, your config please ?

**Comment by hansskogvold** [comment]
Sorry. I had AAK enabled in uBlock, and it didnt block it. When I enabled the updated userscript it was blocked. Not an AAK issue :)

**Comment by reek** [comment]
Ok
