### ISSUE TITLE
faucetbitcoins.com

### ISSUE THREAD

**Issue by eXPerience83** [reek/anti-adblock-killer#912]
http://www.faucetbitcoins.com
http://imgur.com/SyfUavw
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by MajkiIT** [comment]
Try this
@@|http://www.faucetbitcoins.com/banner.gif$image,domain=faucetbitcoins.com

**Comment by eXPerience83** [comment]
It works! Thank you

**Comment by reek** [comment]
@eXPerience83 
Ok, I'll kill it

@MajkiIT 
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
