### ISSUE TITLE
koscian.net

### ISSUE THREAD

**Issue by MajkiIT** [reek/anti-adblock-killer#914]
Reek I have problem with this page. I add to uBlock rule ||www.koscian.net/photos/adv_ . After that I don't see ads, but I see Adblock alert. I find solution ||www.koscian.net/photos/adv_$object,important,redirect=1x1-transparent.gif , but it's not ideal rule. Can you look for this page?

![koscian](https://cloud.githubusercontent.com/assets/11302675/12138420/306c0fd2-b459-11e5-8069-7297f0a7a502.png)

**Comment by reek** [comment]
Hi,

I'll see if I can solve the problem with AakScript.

**Comment by reek** [comment]
Try this rule
<pre>
    koscian_net : {
      // issue: https://github.com/reek/anti-adblock-killer/issues/914
      // source: http://pastebin.com/yGSPBRqe
      host : ['koscian.net'],
      onIdle : function () {
        var elems = document.querySelectorAll('.ban');
        for (var i = 0; i < elems.length; i++) {
		  elems[i].remove();
        }
      }
    },
</pre>

**Comment by MajkiIT** [comment]
Add this rule to AAK scripts?

**Comment by MajkiIT** [comment]
I added to AAK and it's works. You are genius. Thanks a lot.

**Comment by reek** [comment]
:smile:

**Comment by MajkiIT** [comment]
Reek you will add this script to AAK scripts?

**Comment by reek** [comment]
Yes

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
