### ISSUE TITLE
rappers.in

### ISSUE THREAD

**Issue by 3498BoyZ** [reek/anti-adblock-killer#915]
http://www.rappers.in/de/topbeats.php?per=all&style=&Submit2=Go
I cant play the audios, because it detects my adblocker
See:http://abload.de/img/ddfgdfw6svj.png

**Comment by reek** [comment]
HI,

Ok, I'll kill it

See you
Reek

**Comment by 3498BoyZ** [comment]
Wow the answer was very fast :D

**Comment by reek** [comment]
More fast the fix :smile:
<code>
@@||rappers.in/js/antiadblock.js$script
</code>

**Comment by 3498BoyZ** [comment]
thx it works!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
