### ISSUE TITLE
Add Support For pastebin.com

### ISSUE THREAD

**Issue by war59312** [reek/anti-adblock-killer#916]
Hi,

Please add support for http://pastebin.com/.

"AD-BLOCK DETECTED - PLEASE SUPPORT PASTEBIN BY BUYING A PRO ACCOUNT"

Example: http://pastebin.com/y1AGCWLB

Thank you,

Will

**Comment by reek** [comment]
HI,

Killed for me, read instructions

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by war59312** [comment]
Updated to 9.1 and it's working now. That is, anti ad killed. :)

Sorry, will post correct info next time. Was in a rush. Thanks for fixing anyhow.

**Comment by reek** [comment]
OK :smile:
