### ISSUE TITLE
imgnova.xyz

### ISSUE THREAD

**Issue by discipleofphage** [reek/anti-adblock-killer#917]
http://imgnova.xyz/i/x.php?f=568876a201e4d.jpg
https://www.dropbox.com/s/97mh28u3bfojq3q/imgnova.jpg?dl=0
Google Chrome v47
Tampermonkey
Adblock Plus
Easy-List, Adblock warning removal, aaklist

<pre>
  (function () {
    var ca = document.createElement('script');
    ca.type = 'text/javascript';
    ca.async = true;
    var s = document.getElementsByTagName('script')[0];
    ca.src = 'http://serve.popads.net/checkInventory.php';
    ca.onerror = function () {
      setTimeout(function () {
        location.href =

          "http://www.imgnova.xyz/adblock.html";
      }, 1000);
    }
    s.parentNode.insertBefore(ca, s);
  })();
</pre>

**Comment by reek** [comment]
Hi, 
Ok, I'll kill it

**Comment by discipleofphage** [comment]
thank you.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
