### ISSUE TITLE
play.iprima.cz

### ISSUE THREAD

**Issue by auchEnia** [reek/anti-adblock-killer#920]
http://play.iprima.cz/anosefe/ano-sefe-i-9
Google Chrome
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Ji,
Ok, I'll kill it

**Comment by MajkiIT** [comment]
can you test this rule?
iprima.cz#@#.bannerAd

**Comment by auchEnia** [comment]
Thank you @MajkiIT, works like a charm.

**Comment by MajkiIT** [comment]
:+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
