### ISSUE TITLE
captchme.net / captchme.com

### ISSUE THREAD

**Issue by TonyJohnCil** [reek/anti-adblock-killer#921]
http://www.voxmakers.fr/?magicvideo=0#boitemagique & http://youtube-explorer.com/oauth2callback.php
http://imgbox.com/uvJjUXHU & http://imgbox.com/atVoamh9
Mozilla Firefox
Greasemonkey
uBlock Origin
uBlock Origin default lists & AakList

**Comment by reek** [comment]
Hi,

it's an anti-bot and not an anti-adblock, you must complete the captcha.

**Comment by TonyJohnCil** [comment]
Hi,

Are you sure ? If I turn off AAK, a message appears in the box asking me to turn off AdBlock. http://imgbox.com/gTseUQeY

**Comment by reek** [comment]
Ok

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by TonyJohnCil** [comment]
Thanks ! But it still doesn't work after updating the script and the list.
On http://www.voxmakers.fr/?magicvideo=0#boitemagique , I see a white screen, sometimes "invalid-challenge" when reloading Captch Me http://imgbox.com/IlNIFjAo .

I've installed the script in Chromium (uBlock Origin, Tampermonkey, same filterlists), I've the same problem.
On http://youtube-explorer.com/oauth2callback.php , I see a slider when reloading http://imgbox.com/9pxYJnFf , but it reloads the page and I've got an "invalid captcha" alert http://imgbox.com/C87jjda7 .

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by reek** [comment]
@TonyJohnCil 
Try this tule
<code>@@||googleads.g.doubleclick.net/pagead/ads$subdocument,third-party</code>

**Comment by TonyJohnCil** [comment]
Sorry, the rule doesn't change anything.
New fact, on Chromium with the slider, I'm now getting a partial view of the ad. http://imgbox.com/Mh2XHSi3 But it stills reload the page with the "invalid captcha" message.

Here are the advanced reports (for Firefox) :
Extensions : BetterPrivacy, Greasemonkey, uBlock Origin, DownloadHelper.
Scripts : Aak only.

For http://www.voxmakers.fr/?magicvideo=0#boitemagique : http://paste2.org/ZbG2jX81 (the whole page may contain other normal ads)
Blocked : http://imgbox.com/V0QUlFtc
For http://youtube-explorer.com/oauth2callback.php : http://paste2.org/UcNeNje6
Blocked : http://imgbox.com/vQbhpGj1

And thanks !

**Comment by reek** [comment]
Weird, it should work.

Has made an update extensions, and then test only with Firefox + uBO + GM

Did you change your host file ?

**Comment by TonyJohnCil** [comment]
No change with only uBlock and GreaseMonkey activated. No change to my hosts file (here is it : http://paste2.org/8DaMtcNV )

New fact, the problem I have with Chromium exists with Firefox too (I've got the slider captcha and the same problem mentioned before).

**Comment by TonyJohnCil** [comment]
I had some tests today with Firebug activated. I don't know if it has an importance, but the console give me two errors (with the two websites). http://imgbox.com/CaXmaTXD
The first one always appears when captchme loads.
The second one appears when I push the slider (if the slider is available, it never appears when captchme tries to load a video ad).

With private browsing and tracking protection, the first error is automatically blocked. http://imgbox.com/rvgaBs0W
Moreover, only with with Firebug, when I push the slider, a video ad tries to load. http://imgbox.com/zcmksb2o When the 20-second delay is over, another button loads to lead me to the "ad-website".

Finally, I've noticed that it doesn't change anything if Aak and its filter list are activated or not. With uBlock Origin only, I haven't got any message that warns me that AdBlock is activated (like the one I had some days before http://imgbox.com/gTseUQeY ). 

In all cases, the captchas still doesn't work.
I've got these types of problems with Chormium. Here are the errors. http://imgbox.com/daDnFj42 But the slider doesn't try to load any video ad (and it doesn't return any error in the console).

**Comment by reek** [comment]
Have you changed the IP Address DNS ?

With ublock origin deactivated, is that it works well ?

Otherwise tried this rule
@@||api.captchme.net/*

**Comment by TonyJohnCil** [comment]
No change to the DNS.
The ads shows normally with uBlock Origin deactivated, and I can pass the captcha.
With the rule, I can see ads with the captcha slider, the video ads are still blocked.

**Comment by TonyJohnCil** [comment]
No change to the DNS.
The ads shows normally with uBlock Origin deactivated, and I can pass the captcha.
With the rule, I can see ads with the captcha slider, the video ads are still blocked.

Oh, and I noticed that without the " @@||googleads.g.doubleclick.net/pagead/ads$subdocument,third-party" rule, the captcha slider is replaced with the message that warns me that AdBlock is activated.

**Comment by reek** [comment]
it's normal because <code>@@||googleads.g.doubleclick.net/pagead/ads</code> is an bait.

**Comment by TonyJohnCil** [comment]
I've noticed this because the rule didn't change anything some days before.

At this time, the two websites use only the video captcha, I haven't seen the slider one for a moment.

**Comment by TonyJohnCil** [comment]
New versions of the captchas today !
On http://www.voxmakers.fr/?magicvideo=0#boitemagique , it seems that a normal captcha loads (without ads), but I can't see it. http://imgbox.com/9w4JPLYd
On http://youtube-explorer.com/oauth2callback.php , the slider captcha has a new form, and I'm able to pass it (I push the slider and it unlocks the next page). http://imgbox.com/Kh8pVopt
No news from the video captcha.
I don't know who's in charge of the updates (captchme or the two websites that implements it ?). Is it a good idea to look for the problem if the captcha displays differently every day ?

**Comment by reek** [comment]
Have you looked at the side of your antivirus, antispyware, firewall, because it is they can sometimes block some ressouces.

**Comment by TonyJohnCil** [comment]
It looks there's nothing anormal with all of these.

But I've found something for http://www.voxmakers.fr/?magicvideo=0#boitemagique , the normal captcha (without ad) is blocked by the FR EasyList. If I remove this list, the normal captcha (without ad) loads.

So ... at this time, it's possible to access the two websites with AAK. I don't know if it means that the request is solved. I will check the two sites for some more days and look for changes on their side. The captchas may change again in the next days.

Thanks a lot !

**Comment by reek** [comment]
I'll see what blocks in List FR, and add a rule AakList

**Comment by reek** [comment]
This rule fix it
<code>@@||api.captchme.net/api/media$image</code>

**Comment by TonyJohnCil** [comment]
It works, thanks !

There's still no change to the captchas at this time. so I don't know how to test the video captcha provided by captchme, but the normal captcha and the slider captcha seem to work.

**Comment by reek** [comment]
Ok, let me know
