### ISSUE TITLE
nnm-club.me

### ISSUE THREAD

**Issue by Fossius** [reek/anti-adblock-killer#926]
http://nnm-club.me/ and https://nnm-club.me/
http://imgur.com/9dvdQP1
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList + Adblock Warning Removal List‎ + Peter Lowe’s Ad server list‎ + RUS: RU AdList

**Comment by maynak00** [comment]
**try with:**(custom filters)
>||assets.nnm-club.ws/forum/docs/requests.js
>||assets-ssl.nnm-club.ws/forum/docs/requests.js$script,domain=nnm-club.me

**Comment by Fossius** [comment]
maynak00   Thank's, works good!!

**Comment by reek** [comment]
@Fossius 
Ok, I'll kill it.

@maynak00 
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#fiterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
