### ISSUE TITLE
BlockAdblock 2.5 

### ISSUE THREAD

**Issue by pcannell** [reek/anti-adblock-killer#928]
Block Adblock updated their script on December 16th.

http://blockadblock.com/adblocking/blockadblock-update-2-5-available/

Since that update I'm getting the banner on all sites that have updated to BlockAdblock 2.5, such as http://blockadblock.com

**Comment by reek** [comment]
Related: https://github.com/reek/anti-adblock-killer/issues/808

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
