### ISSUE TITLE
3bmeteo.com

### ISSUE THREAD

**Issue by RNiK** [reek/anti-adblock-killer#929]
www.3bmeteo.com (insert a location in the top-bar then press search)
https://www.picflash.org/picture.php?key=GT5233&action=show
Mozilla Firefox 43.0.4
Greasemonkey 3.6
Adblock Plus 2.7
Filter Lists => https://www.picflash.org/picture.php?key=YITWVK&action=show

**Comment by maynak00** [comment]
**try this:**(add to your adblocker custom filters)
>www.3bmeteo.com###adblock_warning

**Comment by reek** [comment]
@RNiK 
Ok, thanks

@maynak00 
:+1:

**Comment by RNiK** [comment]
@maynak00 - Yeah, I know how to remove the DIV stating I'm using Adblock, that's not problem.
The problem is that site is able to <i>sense</i> Adblock.

**Comment by maynak00** [comment]
@RNiK **alternative filter:**
>@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=3bmeteo.com

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
