### ISSUE TITLE
linkbucks.com

### ISSUE THREAD

**Issue by RNTmedeiros** [reek/anti-adblock-killer#932]
www.linkbucks.com/agkP
http://i.imgur.com/RACQEu5.png
Google Chrome
TamperMonkey
Adblock (getadblock.com)
EasyList + AakList

**Comment by reek** [comment]
I have nothing, see https://github.com/reek/anti-adblock-killer#help or use https://greasyfork.org/fr/scripts/4881-adsbypasser

**Comment by RyanThaDude** [comment]
Seems they changed again. Using Firefox, uBlock Origin, Greasemonkey along with AdsBypasser.
![linkbucks-ad](https://cloud.githubusercontent.com/assets/2889250/12299654/b873acb4-b9e5-11e5-8b3f-5c476404d077.png)

**Comment by reek** [comment]
Try this
<code>@@||ipbryxumndcq.net^$subdocument,domain=sasontnwc.net</code>

**Comment by RNTmedeiros** [comment]
@reek worked for me, thanks

**Comment by RyanThaDude** [comment]
@Reek works great here, too. Thanks!

**Comment by reek** [comment]
@RNTmedeiros 
@RyanThaDude 
fine :smile:

**Comment by reek** [comment]
new rule
<code>@@||xjzrnogvyg.net^$subdocument,domain=sasontnwc.net</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
