### ISSUE TITLE
Change url of anti-adblock-killer-filters.txt

### ISSUE THREAD

**Issue by hidekuro** [reek/anti-adblock-killer#933]
Now, filter url is `https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt` but it seems old.

Use `raw.githubusercontent.com` instead of `raw.github.com`.

**Comment by reek** [comment]
Hi,
No need.

**Comment by hidekuro** [comment]
Certainly it works, but why does not change?

**Comment by reek** [comment]
precisely because it works

**Comment by hidekuro** [comment]
I see! thanks response.
