### ISSUE TITLE
cine-media.fr (captchme)

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#934]
Hi,

![captcha.me](http://i.imgur.com/AqMd7Th.png)

on `http://www.cine-media.fr/concours/tentez-de-gagner-un-coffret-7-dvd-de-la-filmographie-de-quentin-tarantino-1452276599.html`

`@@||googleads.g.doubleclick.net/pagead/ads?$subdocument,domain=cine-media.fr`

Merci.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
