### ISSUE TITLE
phonearena.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#936]
http://www.phonearena.com/news/LG-invited-us-to-a-Feb-21-2016-event-in-Barcelona-but-what-does-a-music-box-have-to-do-with-the-LG-G5_id77368
http://imgur.com/3D7bXuZ

Mozilla Firefox 43.0.4
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

<pre>
function checkAds() {
  if (typeof _gaq !== 'undefined') {
    if ($("#footeradvert").height() == "0") {
      _gaq.push(['_trackEvent', 'Adblock', 'Yes', undefined, undefined, true]);
      $('#right_column').prepend('<div class="adblock_awareness"><img src="//s-cdn.phonearena.com/images/adblock-awareness.png?3"></div>');
    } else {}

  }
}
</pre>

**Comment by reek** [comment]
Hi,
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
