### ISSUE TITLE
cnx-software.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#937]
http://www.cnx-software.com/2016/01/12/rockchip-rk3229-and-rk3399-32-bit-and-64-bit-processors-support-4k-10-bit-h-265-and-hdmi-2-0/

http://imgur.com/y3JtlY6

Mozilla Firefox 43.0.4
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
