### ISSUE TITLE
lewebtvbouquetfrancophone.overblog.com

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#938]
Hi,
anti-adblock message and redirection to `lutteadblock.blogspot.ca`

on `http://lewebtvbouquetfrancophone.overblog.com/2015/09/bfmtv-en-direct-bfmtv-live-bfmtv-online-bfmtv-expat-stream3.html#heading1`

Thanks!

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
