### ISSUE TITLE
hdkinoteatr.com

### ISSUE THREAD

**Issue by MorviCool** [reek/anti-adblock-killer#939]
http://www.hdkinoteatr.com/drama/22175-vyzhivshiy.html
https://imgdepo.com/show/8846043
Chrome
Tampermonkey
uBlock origins
EasyList + AakList

**Comment by reek** [comment]
Hi,
It's killed for me with AakScript
https://github.com/reek/anti-adblock-killer#instruction

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
