### ISSUE TITLE
[uBlock+Firefox Only] Bypass apkmirror.com countdown while strictly block ad servers

### ISSUE THREAD

**Issue by kowith337** [reek/anti-adblock-killer#940]
Hello, I'm too new for here...
Because uBlock0 on Firefox can use specific inline-script filter rules, I had looking around about this and found solution while completely block ad servers (e.g. uMatrix or uBlock dynamic filtering), regardless of AAK Script and/or AAKList loaded or not.

Details of some part of code that appear in "View Source"
```javascript
var ranTwice = false;

function OGmzNbqouH() {
  var visibleAds = 0;
  jQuery(".gooWidget > .adsbygoogle" ).each(function( i ) {
    visibleAds += jQuery(this).children().length;

  });
  console.log("Visible ads: " + visibleAds);


  var canRunAds = false;
  if(visibleAds >= 2) { canRunAds = true; } else { canRunAds = false;}

  if(jQuery(".downloadButton").length > 0) {
    if(canRunAds == true)
    {
      jQuery(".downloadButton").removeClass("disabled");
    }
    else
    {
      var elapsedTime = 0;
      var totalTime = 15;
      jQuery(".downloadButton").addClass("disabled");
      jQuery(".downloadCountdown").show();

      //Ad blocker is running for sure, show the countdown
      var timerInterval = setInterval(function() {
        elapsedTime += 1;
        var timeLeft = totalTime - elapsedTime;

        jQuery("#secondsLeft").text(timeLeft);

        if(timeLeft == 1)
        {
          jQuery("#secondsPlural").text("second");
        }
        else
        {
          jQuery("#secondsPlural").text("seconds");
        }

        if(elapsedTime >= totalTime) {
          elapsedTime = totalTime;
          jQuery(".downloadCountdown").slideUp("slow");
          jQuery(".downloadButton").removeClass("disabled");
          clearInterval( timerInterval );
        }

      }, 1000);

      jQuery("#downloadCountdownBar").width("100%");
    }

    if(canRunAds == false) {
        jQuery("#sidebar .latestWidget").css("margin-top", "0px");
    }

    if(canRunAds && !ranTwice)
    {
      ranTwice = true;
      //window.setTimeout(function(){doCheck();}, 1000);
    }
  }
}

jQuery(window).load(function() { OGmzNbqouH(); })
```
- random character after `function` is randomly generated, so may be cannot block this checker easily.
- `canRunAds`, `visibleAds` It's variable value that check how many ads has appear on screen, if it below or not equal as 2, download button will be disable and dimmed, also countdown timer has been placed by this code.<br />
`jQuery(".downloadButton").addClass("disabled");
jQuery(".downloadCountdown").show()`
- I think it's not recommended to touch `.downloadButton`, otherwise download button will completely disappear.

Worked filter is should be...
```
apkmirror.com##script:contains(canRunAds)
apkmirror.com##script:contains(visibleAds)
apkmirror.com##script:contains(.downloadCountdown)
```
It's no need to add them all into filter lists, just add only one from above and uBlock will remove entire inline-script node that matched.
I hope it still work for long, unless site admin has changed their code.

Sorry, I'm not good for English.

**Comment by reek** [comment]
Hi,
thank you, but I will not add your rules, because I want a solution that works on all browsers and adblockers

**Comment by IDKwhattoputhere** [comment]
Maybe @Gorhill will take it: https://github.com/gorhill/uBlock/issues
