### ISSUE TITLE
world4ufree.cc

### ISSUE THREAD

**Issue by deepakgaria** [reek/anti-adblock-killer#942]
this site always show
![123](https://cloud.githubusercontent.com/assets/16687975/12315272/0b81c882-ba9f-11e5-99cd-5a0d7ad55437.png)

**Comment by reek** [comment]
Hi,
It's killed for me, check if AakScript is enabled,
otherwise add rule
<code>world4ufree.cc#@#.afs_ads</code>

**Comment by maynak00** [comment]
for me adblocker detected message still exist.
**blocked with:**
>world4ufree.cc##.ui-resizable.ui-front.ui-corner-all.ui-widget-content.ui-widget.ui-dialog
>world4ufree.cc##.ui-front.ui-widget-overlay

**Comment by deepakgaria** [comment]
still not happn

**Comment by reek** [comment]
@deepakgaria 
Your confing
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by worldfree4u** [comment]
Visit Worldfree4u.ind.in

**Comment by deepakgaria** [comment]
it start again showing ads
