### ISSUE TITLE
Please set AAKList and AAKScript free

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#943]
@reek From https://github.com/gorhill/uBlock/wiki/Filter-list-licenses:

"Some of the 3rd-party filters (simple data files) in this software are under non-free licenses. However, it is not clear that the works in question are actually subject to copyright or that the licensing terms could apply. As such, we urge you to use redistribute those filters with caution that someone may try to claim copyright on the works." - Joshua Gay, Licensing & Compliance Manager, Free Software Foundation

uBlock Origin -> Settings -> 3rd-party filters -> Anti-Adblock Killer | Reek‎: This points to https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt which is distributed under Creative Commons NC-clause, classified as a non-free software license by the Free Software Foundation. However, the FSF gave me green light to approve uBO on the FSD (https://directory.fsf.org/wiki/UBlock_Origin) because filters cannot be non-free as stated in the first paragraph.

I would love to add AAKScript (https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js) to the Free Software Directory but I cannot do so as long as it is distributed under the NC-clause.

**Comment by reek** [comment]
HI,
You can share, copy and redistribute the material in any medium or format.
The only restriction is not to return him paying.
https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by flyingzebras** [comment]
Unfortunately https://directory.fsf.org/wiki/UBlock_Origin have been unapproved until this issue have been resolved.

From https://www.gnu.org/licenses/license-list.html#CC-BY-NC
"Creative Commons Nocommercial, any version (#CC-BY-NC)

    This license does not qualify as free, because there are restrictions on charging money for copies. Thus, we recommend you do not use this license for documentation.

    In addition, it has a drawback for any sort of work: when a modified version has many authors, in practice getting permission for commercial use from all of them would become infeasible."

**Comment by reek** [comment]
I will delete the NC clause in version 9.2.

**Comment by flyingzebras** [comment]
@reek Namaste.

**Comment by reek** [comment]
During the week

**Comment by reek** [comment]
Done !

**Comment by flyingzebras** [comment]
Very good @reek, I made sure that the uBlock entries in the FSD was approved again.

**Comment by IDKwhattoputhere** [comment]
@flyingzebras It still says:
> Do not approve until https://github.com/reek/anti-adblock-killer/issues/943#issuecomment-174195474 have been resolved

**Comment by flyingzebras** [comment]
@IDKwhattoputhere Reported and solved. Thanks.
