### ISSUE TITLE
srnk.co

### ISSUE THREAD

**Issue by callmenemo491** [reek/anti-adblock-killer#944]
hi, could you help with this site:
http://srnk.co/i/3VFAv

displays text:
We’ve detected that you’re using AdBlock Plus or some other adblocking software.
Please Disable your Ad Blocker for this website to access this content!
After you disable your Ad Blocker reload this page to have unrestricted access.
Remember, advertising keeps the internet content free!

**Comment by reek** [comment]
Hi,
Ok, I'll kill it.

**Comment by MajkiIT** [comment]
Try this exclude
@@|http://srnk.co/js/ads.js$xmlhttprequest,domain=srnk.co

**Comment by callmenemo491** [comment]
@MajkiIT, perfect thanks!

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
