### ISSUE TITLE
10starmovie.me

### ISSUE THREAD

**Issue by AlexisOhanian** [reek/anti-adblock-killer#945]
Hi;
on https://10starmovie.me/watch-the-emperor-in-august-2015-online.html

screenshot :- http://i.imgur.com/9Aw4qDC.png

video is not working

source: http://www.blackhatworld.com/blackhat-seo/black-hat-seo/810937-https-not-working-wordpress-site.html

**Comment by reek** [comment]
Hi,
It's at <code>10starmovie.me</code> webmaster, it be reported the problem because it has to do with the protocol.

Replaces <code>https://</code> by <code>http://</code> and see that it works

Regards
Reek
