### ISSUE TITLE
Bug? Sessionstore in Firefox 43.0.x is broken with your script turned on.

### ISSUE THREAD

**Issue by Defab** [reek/anti-adblock-killer#946]
Hi Reek,

sadly, when your ant-adblock-script is turned on, my FF (43.0.1/4 32bit Windows 7 64bit) don't use the sessionstore feature correctly. After the last update from your script, any new tab i open and let it open to take it to the new session, my FF save the tab only as "New Tab" without the url information. The old tabs, they existed before the last update, are restored correctly. Even with all my addons deactivated except greasemonkey, the problem exists. With Firefox v42 the problem doesn't exist at all with addons on/off.

regards

**Comment by reek** [comment]
Hi,
Can you test this version:  https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by Defab** [comment]
Hi,

it does not work neither.

**Comment by reek** [comment]
Ok and now https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by Defab** [comment]
Hi,

sorry for my late response, i have a lot of work to do. This script seems to work. No "New Tab" anymore.

**Comment by reek** [comment]
Can you test this beta version, because I have made a few changes
https://gist.github.com/reek/dc234ea9687056bd99fe

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
