### ISSUE TITLE
mtlblog.com

### ISSUE THREAD

**Issue by ThirdMoonSoftware** [reek/anti-adblock-killer#948]
http://www.mtlblog.com/2014/12/poutine-burritos-are-the-tortilla-wrapped-piece-of-heaven-you-never-knew-existed/
https://imgur.com/jtj9Wau
Mozilla Firefox 43.0.4
Greasemonkey
Ublock Origin
Adblock Warning Removal List‎ + Anti-Adblock Killer | Reek + EasyList‎ + Peter Lowe’s Ad server list

**Comment by reek** [comment]
HI,

Ok, I'll kill it.

Related: https://greasyfork.org/forum/discussion/7753

**Comment by maynak00** [comment]
**try this:**
>@@||cdn.mtlblog.com/wp-content/themes/narcity-theme/legal/ads.advert.js$script,domain=mtlblog.com

**Comment by SMed79** [comment]
`@@||cdn.mtlblog.com^*ads.$script,~third-party`

**Comment by ThirdMoonSoftware** [comment]
Thanks SMed79 that worked swimmingly...

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by SMed79** [comment]
sc: http://i.imgur.com/VGb0tBz.png
see → https://forums.lanik.us/viewtopic.php?f=64&t=29754

**Comment by reek** [comment]
@SMed79 
Thanks, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer.user.js">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
