### ISSUE TITLE
datalog.co.uk

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#949]
http://www.datalog.co.uk/browse/detail.php/CompanyNumber/USNY4828957/CompanyName/THE+LAW+OFFICE+OF+RITESH+K.+MALLICK,+PLLC

http://imgur.com/GKxvFzA

Mozilla Firefox 43.0.4
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
Hi,

Ok, I'll kill it.

See you
Reek

**Comment by MajkiIT** [comment]
Try this rule:
@@|http://www.datalog.co.uk/js/ads.js$script,domain=datalog.co.uk

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
