### ISSUE TITLE
srnk.co

### ISSUE THREAD

**Issue by admax37** [reek/anti-adblock-killer#951]
Hi there.
This scrip don´t work at srnk.co.
Thank You.

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/944

**Comment by admax37** [comment]
Thank You.
I will try it.

2016-01-16 22:49 GMT+00:00 reek <notifications@github.com>:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
