### ISSUE TITLE
darkbtc.info

### ISSUE THREAD

**Issue by eXPerience83** [reek/anti-adblock-killer#953]
http://www.darkbtc.info/
http://imgur.com/NkHXiTl
Mozilla Firefox
Greasemonkey
uBlock Origin
EasyList + AakList

**Comment by reek** [comment]
Hi,
Ok, I'll kill it

See you
Reek

**Comment by MajkiIT** [comment]
Try this
@@|http://www.darkbtc.info/banner.gif$image

**Comment by eXPerience83** [comment]
Hi MajkilT, still detecting the adblocker and the antiadblock script

**Comment by MajkiIT** [comment]
Hi eXPerience83, do you add this rule to "my filters" on ublock?

**Comment by eXPerience83** [comment]
Ok, it works. thank you

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
