### ISSUE TITLE
linkbucks.com

### ISSUE THREAD

**Issue by ZeroXFFF1** [reek/anti-adblock-killer#955]
Screenshot: http://i.imgur.com/BLb2OZK.png

**Comment by reek** [comment]
See: https://github.com/reek/anti-adblock-killer/issues/932#issuecomment-171374469

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
