### ISSUE TITLE
br.mangahost.com

### ISSUE THREAD

**Issue by jeff-alves** [reek/anti-adblock-killer#957]
http://br.mangahost.com/
http://imgur.com/dy7dyV4    - ABP disabled
http://imgur.com/DcV9mT4    - ABP enabled
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

http://br.mangahost.com/manga/fairy-tail-br/468/1
Is added a style to the image: style="opacity: 0.8; width: 60%;"
http://imgur.com/hVHWJ05    - ABP disabled
http://imgur.com/Q1dhCwL    - ABP enabled
Google Chrome
Tampermonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
HI,

Ok, I'll kill it, thanks.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
