### ISSUE TITLE
Rutube.ru

### ISSUE THREAD

**Issue by COOLak** [reek/anti-adblock-killer#958]
This is a Russian video hosting website, I'm giving a link to a sample video, but this is the same with any video on it: https://rutube.ru/video/372a373b14f856b8b06bd0cdbc4c80bd/?ref=logo

Basically, when adblocker is on, you can't choose the quality of videos, and it's only letting you watch them in the lowest quality.

Without adblocker: http://imgur.com/oriaGsH
With adblocker: http://imgur.com/UumX1Tn

I think everything is straightforward from the screenshots. When adblocker is off, before seeing the video you have to watch annoying video advertisements like on YouTube, which you can later close by pressing cross at the up right corner of the video, but in this case even 2 in a row. And when adblocker is on, you can't choose video quality.

Source code with adblock off: http://pastebin.com/2QfKJTCg
Source code with adblock on: http://pastebin.com/BSFwP8Ey

Browser: Firefox 43.0.4
Adblocker: Adblock Plus with the subscriptions "AdBlock warning removal list", "RuAdList+EasyList", "Aaklist (Anti-AdBlock Killer)", as well as GreaseMonkey with the script "Anti-Adblock Killer | Reek" 9.1.
Extensions: http://pastebin.com/HHaubMW5
Blocked resources: http://imgur.com/s3DuRHr

P.S. as found out, the issue might not persist for people from other countries but Russia, and maybe it's only showing up with Russian IP addresses. But I attached source code, etc, so I hope you can figure it. Thanks in advance.

**Comment by reek** [comment]
sorry, I have no solution
