### ISSUE TITLE
croydonguardian.co.uk

### ISSUE THREAD

**Issue by SMed79** [reek/anti-adblock-killer#959]
Hi,

![croydonguardian.co.uk](http://i.imgur.com/9UTkZbQ.png)

on `http://www.croydonguardian.co.uk/news/14208804.Southern_could_be_stripped_of_its_franchise_if_it_does_not_improve__appalling__service/`

`||d3ujids68p6xmq.cloudfront.net^`

source: https://forums.lanik.us/viewtopic.php?f=62&t=27941

Thanks!

**Comment by reek** [comment]
Ok, thanks Med

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
