### ISSUE TITLE
tobys.dk

### ISSUE THREAD

**Issue by fabiobarao94** [reek/anti-adblock-killer#960]
![image](https://cloud.githubusercontent.com/assets/15664251/12422975/4cc2ed50-bec1-11e5-9c72-e9972204924d.png)

http://www.tobys.dk/css/counter-strike-source-hacks/p7-v3-9-588/
adblock detected can't download, hard to remove only no script extension works

``` javascript
function checkAds() {
  if ($(".checkAb").height() == "0") {
    $(".remove").hide();
    $(".abMessage").after("<div class='noads'><strong><i class='fa fa-exclamation-triangle'></i> Disable AdBlocker on this domain to display download links <i class='fa fa-exclamation-triangle'></i></strong><p>You should know that the ads on this site help us pay for hosting costs, domain renewal, and keeping us motivated to provide you with new content.</p><br /><p>Please consider disabling your AdBlocker for this domain, we promise our ads are unobtrusive and won't disturb you. <strong>Thank you &lt;3</strong></p><br /><p>Link:<br /><a href='https://www.youtube.com/watch?v=BJaR4SMShhE' target='_blank' rel='nofollow'>How to disable AdBlocker</a></p></div><br />");
  }
}

**Comment by reek** [comment]
Hi,

Ok, try this rule
<code>@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=tobys.dk</code>

**Comment by fabiobarao94** [comment]
SORRY, it doesn't work, i've tried

**Comment by reek** [comment]
Your config ?

**Comment by fabiobarao94** [comment]
what config?

**Comment by reek** [comment]
Try theses rules
<pre>
tobys.dk#@#.adsbygoogle
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=tobys.dk
@@||pagead2.googlesyndication.com/pagead/js/r*/r*/show_ads_impl.js$script,domain=tobys.dk
</pre>

**Comment by fabiobarao94** [comment]
the message still appears 
![image](https://cloud.githubusercontent.com/assets/15664251/12433774/f7326ec6-befa-11e5-88a8-20ba73c33f11.png)

**Comment by reek** [comment]
Your browser
Your script manager
Your adblocker
Your filterlists

**Comment by fabiobarao94** [comment]
![image](https://cloud.githubusercontent.com/assets/15664251/12433800/10949dc6-befb-11e5-987c-b8b575b71809.png)

**Comment by fabiobarao94** [comment]
my browser google chrome

**Comment by reek** [comment]
Put filters on top and click "Guardar"

**Comment by fabiobarao94** [comment]
![image](https://cloud.githubusercontent.com/assets/15664251/12434107/79e112d6-befc-11e5-978a-2c9eeff887f8.png)
![image](https://cloud.githubusercontent.com/assets/15664251/12434112/7e5269e6-befc-11e5-8c28-d1b684f8b400.png)

**Comment by fabiobarao94** [comment]
again!!! :(

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#help
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by fabiobarao94** [comment]
I already have that filter see all my filters
![image](https://cloud.githubusercontent.com/assets/15664251/12434279/aa31436a-befd-11e5-8c92-ac16c4e174cb.png)

**Comment by fabiobarao94** [comment]
see tampermonkey extension 
![image](https://cloud.githubusercontent.com/assets/15664251/12434463/aeacb0d6-befe-11e5-9240-7469f6eb99be.png)

**Comment by maynak00** [comment]
@reek, tested 2 filters but not working.
my filter for fixing problem: ||tobys.dk/css$inline-script,domain=tobys.dk
*but this will/maybe broke some functionality of page
![2016-01-20_235539](https://cloud.githubusercontent.com/assets/6183830/12464538/1f093e7a-bfd2-11e5-8337-4656f34e6295.png)

**Comment by reek** [comment]
@maynak00 
@fabiobarao94 

Try these rules, works for me. 
<pre>
tobys.dk#@#.adsbygoogle
@@||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,domain=tobys.dk
@@||pagead2.googlesyndication.com/pagead/js/r*/r*/show_ads_impl.js$script,domain=tobys.dk
</pre>

Which extensions do you use ?

**Comment by fabiobarao94** [comment]
I use Adblock plus, tampermonkey, and disconect

**Comment by fabiobarao94** [comment]
and i've tried all you gave me but still appears the message, the only way i can bypass this is using another extension called No Script, but i would like to do it with adblock, because with no script i have to enable and then disable to download from Adfly because it blocks in Adfly, and it's boring doing the same process over and over again

**Comment by maynak00** [comment]
@fabiobarao94
for disconnect,No Script extensions, read: https://github.com/reek/anti-adblock-killer#help
@reek problem fixed with tobys.dk#@#.adsbygoogle

but empty spaces on page
added also(not important):
>www.tobys.dk###aswift_0
www.tobys.dk###aswift_0_anchor
www.tobys.dk###aswift_0_expand
www.tobys.dk###aswift_1
www.tobys.dk###aswift_1_anchor
www.tobys.dk###aswift_1_expand
www.tobys.dk###aswift_2
www.tobys.dk###aswift_2_anchor
www.tobys.dk###aswift_2_expand

**Comment by reek** [comment]
@fabiobarao94 
Don't use NoScript and remove/disable Disconect, restart and try again

**Comment by reek** [comment]
@maynak00 
thanks, but I will not add:
<pre>
    www.tobys.dk###aswift_0
    www.tobys.dk###aswift_0_anchor
    www.tobys.dk###aswift_0_expand
    www.tobys.dk###aswift_1
    www.tobys.dk###aswift_1_anchor
    www.tobys.dk###aswift_1_expand
    www.tobys.dk###aswift_2
    www.tobys.dk###aswift_2_anchor
    www.tobys.dk###aswift_2_expand
</pre>

**Comment by fabiobarao94** [comment]
OK i disabled the extension disconect and it works, why does the extension disconect interfere with adblock??

**Comment by reek** [comment]
@fabiobarao94 
Because Disconnect block the invisible sites that track your search and browsing history.

**Comment by fabiobarao94** [comment]
and that's good right, to be anonymous

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
