### ISSUE TITLE
razercrypt.com

### ISSUE THREAD

**Issue by eXPerience83** [reek/anti-adblock-killer#961]
http://razercrypt.com/btc/?r=1KAZ3b7EbWxwkXm28AEG17zRzY7ZKM9yHP
The web is http://razercrypt.com/btc/ but you need to register, so you can use my wallet address to check it 1KAZ3b7EbWxwkXm28AEG17zRzY7ZKM9yHP
http://imgur.com/SezvDNd
It doesn't detect ublock, it detects the ant-iadblock killer script or greasemonkey
I need to desactivate ublock origin and greasemonkey to make it work

Mozilla Firefox
Greasemonkey
Ublock Origin
EasyList + AakList

**Comment by reek** [comment]
Hi,

Ok, I'll fix it

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
