### ISSUE TITLE
gaytube.com

### ISSUE THREAD

**Issue by flyingzebras** [reek/anti-adblock-killer#962]
See https://github.com/gorhill/uBlock/issues/1260 for examples

There are ```data:image/png;base64``` in ```<script data-cfasync='false' type='text/javascript'>```

Example ```<span style='display:block;width:94px;height:37px;margin:0 auto;background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAF...```

Can you break them?

**Comment by reek** [comment]
Hi,

Ok, I'll kill it.

See you
Reek

**Comment by reek** [comment]
I have a solution but it will be with AakScript,

**Comment by flyingzebras** [comment]
@reek Fixed in https://github.com/gorhill/uBlock/issues/1260

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
