### ISSUE TITLE
fanfiktion.de

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#963]
URL: http://www.fanfiktion.de/
Screenshot: 
![](https://cloud.githubusercontent.com/assets/16030872/12464133/d6a9a138-bfc7-11e5-9776-cc0b67e13d1d.png)
Special ads only displayed to adblock users. EasyList didn't add it: https://forums.lanik.us/viewtopic.php?f=90&t=27703

**Comment by reek** [comment]
These rules are good for me
<pre>
||fanfiktion.de/pics/*.gif$domain=fanfiktion.de
fanfiktion.de###ad-leaderboard-inner
</pre>

**Comment by IDKwhattoputhere** [comment]
Yes, but there's no list which contains them. I thought you might want to add those.

**Comment by reek** [comment]
Ok, I'll add them

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
