### ISSUE TITLE
[NEWS] Tracking blocker Ghostery accused Adblock Plus of extorting money from advertisers

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#964]
http://www.businessinsider.com/ghostery-accuse-adblock-plus-of-extortion-2016-1

http://www.businessinsider.com.au/ghostery-accuse-adblock-plus-of-extortion-2016-1

**Comment by Giwayume** [comment]
I really should switch to uBlock but I'm too lazy.
