### ISSUE TITLE
iptvforever.com

### ISSUE THREAD

**Issue by xxcriticxx** [reek/anti-adblock-killer#967]
http://www.iptvforever.com/channel
http://imgur.com/tzjvvYP

Mozilla Firefox 43.0.4
Greasemonkey
uBlock Origin reg filters
AakList
POL: polskie filtry do Adblocka i uBlocka‎ (www.certyficate.it)

**Comment by reek** [comment]
HI

Ok, I'll kill it

**Comment by yoshimo** [comment]
whitelist http://www.iptvforever.com/js/adsbygoogle.js?v=1.1
'''adblock = false;''' is all it does

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
