### ISSUE TITLE
brainyquote.com

### ISSUE THREAD

**Issue by Spamme1** [reek/anti-adblock-killer#968]
The most annoying thing is a css class in the document body, which block the mouse events, the scrolling and the text selection.

.nopt{pointer-events:none;overflow:hidden;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;-o-user-select:none;user-select:none}

**Comment by Giwayume** [comment]
I don't see any ads or anti-adblock messages with the latest script/filters.

**Comment by reek** [comment]
@Spamme1 
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide
