### ISSUE TITLE
NinjaKit Import fails

### ISSUE THREAD

**Issue by pitichampi** [reek/anti-adblock-killer#969]
Hi !

Since v8, importing the script in NinjaKit for Safari fails. Importing or copy/paste does the same : the code display becomes weird after a few lines...

Example : 
<img width="1372" alt="capture d ecran 2016-01-24 a 19 15 25" src="https://cloud.githubusercontent.com/assets/1125819/12538051/7d07762c-c2cf-11e5-936e-7951ab8e812c.png">

It doesn't happen with previous versions (including 7.9). 

I guess I could use an other browser but hey... you know :)

Have you any ideas of the origin of this issue ?

My system : Mac OS X 10.11.3, Safari 9.0.3, NinjaKit 0.9.1.

**Comment by Giwayume** [comment]
That's definitely a bug with NinjaKit, by the looks of it. Why don't you try tampermonkey on Safari instead? http://tampermonkey.net/?ext=dhdg&browser=safari

**Comment by reek** [comment]
Yee, try Tampermonkey, 
I can't test it because safari stopped the developement on windows

**Comment by pitichampi** [comment]
I just didn't notice that Tampermonkey was available for Safari... It works like a charm ! Maybe you should remove NinjaKit from the suggestions for Safari (as it causes some issues). If you need testers with Safari, don't hesitate :)
