### ISSUE TITLE
dlneko.org

### ISSUE THREAD

**Issue by exodius48** [reek/anti-adblock-killer#972]
http://dlneko.org/home-insurance-as-the-impressive-idea/?link=aHR0cDovL3d3dy50dXNmaWxlcy5uZXQvaWFybmQ1NWg2MWZt
http://s29.postimg.org/a6d3g2jd3/2016_01_25_205043.png
Firefox Stable version (43.0.4)
Greasemonkey
uBlock Origin
EasyList+AAK, Adblock Warning Removal List‎, Peter Lowe’s Ad server list‎, Anti-ThirdpartySocial, Fanboy’s Annoyance List‎, Fanboy’s Social Blocking List , etc

**Comment by reek** [comment]
Hi,
I have nothing, give me all the names lists

**Comment by exodius48** [comment]
@reek try to download any file from here http://nekonime.com/
i got popup to disable adblock yesterday, but this morning that popup disappear, its weird

**Comment by maynak00** [comment]
**try this:**(custom filter)
>dlneko.org##.xDialog
dlneko.org##.DialogMask

**Comment by reek** [comment]
@exodius48 
nothing for me
Give me all https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced
and lists subscribed

**Comment by exodius48** [comment]
@reek  
Source Code: http://paste2.org/wjzJOAeX
Extensions: uBlock Origin, Greasemonkey, Multifox, Mega, Zenmate, IDM integration, Clean Links
Userscripts: AAK, AdsBypasser,Anti Adware
Blocked Resources: http://imgur.com/zYDifQ2

**Comment by exodius48** [comment]
@maynak00 seems that custom works bro, thank you. :)

**Comment by reek** [comment]
@exodius48 
Ok, I'll add rules @maynak00

@maynak00
Thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
