### ISSUE TITLE
telegraph.co.uk

### ISSUE THREAD

**Issue by lamwilton** [reek/anti-adblock-killer#973]
http://www.telegraph.co.uk/news/uknews/crime/12133227/Man-51-arrested-on-suspicion-of-murder-after-body-found-in-search-for-missing-India-Chipchase.html
http://i.imgur.com/7dPo77n.jpg
Google Chrome
Tampermonkey
Adblock
Easylist + Aaklist + Ad Block Warning Removal List + Adblock Custom Filters

**Comment by reek** [comment]
I have nothing /:

**Comment by SMed79** [comment]
@reek https://forums.lanik.us/viewtopic.php?f=62&t=27804#p85896

@lamwilton lamwilton copy/past the [html code](http://www.wikihow.com/View-Source-Code) on http://nopaste.linux-dev.org/ and post the link here.

**Comment by SMed79** [comment]
@reek I can reproduce now on chromium/chrome http://i.imgur.com/NxU1rF3.png
Disable **easyprivacy** list before testing !

`||optimizely.com^$third-party`

**Comment by reek** [comment]
@SMed79 
always nothing

@lamwilton 
can you test

**Comment by SMed79** [comment]
Hi reek,
confirmation > https://forums.lanik.us/viewtopic.php?f=62&t=27804#p86146

**Comment by reek** [comment]
@SMed79 
Ok, thanks Med :+1:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
