### ISSUE TITLE
bitvid.sx 

### ISSUE THREAD

**Issue by dalek1967** [reek/anti-adblock-killer#974]
Link to actual page.  
http://www.bitvid.sx/file/65abb03247a9a 

I hope the above link works. 

Screenshot
http://imgur.com/FUy8Nmh  

Browser
Firefox 43.0 

Script manager
Greasemonkey 3.6

Adblocker
Adblock plus 2.7.1

Filterlists
Easylist  Aaklist  Ruadlist+easylist  Peter Lowe'slist 

I started out with just the first two but added the others to see if it would help.  It didn't help tho.  

![bitvid - video hosting](https://cloud.githubusercontent.com/assets/6623735/12574476/ba4171a0-c3c9-11e5-83f7-7babc4df07af.png)

I run up on these sites from time to time.  Would you prefer I open a seperate thread for each one or just post them on this same thread?  All of them will likely be video download sites.  I'll report them one at a time since when you fix one, it just may fix others that use the same method.  Basically, I won't flood you with a huge list but test to see if changes fix other sites as well first.  

Thanks much for the effort you put into this.  :-)

**Comment by dalek1967** [comment]
I hope this helps.  I disabled this filter.  /banner.php  When I disable that filter, this site works.  The site sort of works funny but it works good enough that downloadhelper can grab the video.

**Comment by maynak00** [comment]
**try this:**(custom filter)
>@@||bitvid.sx/banner.php$script,domain=bitvid.sx

optional:
>www.bitvid.sx###aad

**Comment by reek** [comment]
@dalek1967 
Ok, I'll kill it, open a seperate thread for each site

@maynak00 
Well done

**Comment by IDKwhattoputhere** [comment]
Similar to https://github.com/reek/anti-adblock-killer/issues/795

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
