### ISSUE TITLE
www.gamer.com.tw & ani.gamer.com.tw

### ISSUE THREAD

**Issue by GazCore** [reek/anti-adblock-killer#975]
https://greasyfork.org/en/scripts/16525-anti-baha-anti-ad-block/code
↑This can added to Anti-Adblock Killer? thx

ani.gamer.com.tw
http://i.imgur.com/igXdlNG.png

**Comment by reek** [comment]
Ok, I'll add a rule for gamer.com.tw

**Comment by GazCore** [comment]
ani.gamer.com.tw
http://vgy.me/iQIW3c.png

This is also anti adblock.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
