### ISSUE TITLE
Switch to a free license

### ISSUE THREAD

**Issue by pizzamaker** [reek/anti-adblock-killer#976]
Creative Commons licenses don't fit very well for software, and an NC license means your work is considered proprietary, unfortunately. Even with the source code visible for people to see.

I'd suggest a strong copyleft license such as AGPLv3 for it, or if you prefer permissive ones, maybe stick with Mozilla's MPL. But AGPLv3 is da bomb, really. :)

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/issues/943#issuecomment-174195474

**Comment by reek** [comment]
What license do I use with the following conditions ?

Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

**Comment by pizzamaker** [comment]
LGPL, I believe.

**Comment by reek** [comment]
I'll keep cc without NC-clause
