### ISSUE TITLE
site ios-blog

### ISSUE THREAD

**Issue by muhasturk** [reek/anti-adblock-killer#977]
http://www.ios-blog.co.uk/tutorials/swift/parse-json-deserialization/

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by maynak00** [comment]
**try this:**
>@@||ios-blog.co.uk/*/showads.js$script,domain=ios-blog.co.uk

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
