### ISSUE TITLE
Cultofmac.com

### ISSUE THREAD

**Issue by rodalpho** [reek/anti-adblock-killer#978]
Adblock-style filter to remove the anti-adblock popup:

||cdn.cultofmac.com/wp-content/plugins/com2014-ads/static/js/frontend-functionality.js$script,domain=www.cultofmac.com

This applies to any page on their website.

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
