### ISSUE TITLE
rutube.ru

### ISSUE THREAD

**Issue by Marutinovich** [reek/anti-adblock-killer#98]
While watching videos there, example http://rutube.ru/video/person/238840/
Open any video, and after few seconds notice will pop up at upper part , claiming that I am using ad blocker, and so - it force me to watch it in low quality.
Screenshot http://i.imgur.com/NVdgiko.jpg
Firefox 33.1.1, Greasemonkey and Adblock Plus
Filters: RuAdList+EasyList, Adblock Warning removal list, EasyPrivacy, AntiAdBlock KIller

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/mvpl5ku">Update</a> : UserScript<br>Step 2: <a href="http://tinyurl.com/mulnz7l">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
