### ISSUE TITLE
windows7themes.net

### ISSUE THREAD

**Issue by Koveras** [reek/anti-adblock-killer#980]
They have an explode function to change the current url after a while, but strangely enough, it's not there on each page, depends which article you visit. (search for explode in source, you should either find the function or the timer that starts it)

http://windows7themes.net/en-us/how-to-enable-windows-7-aero-theme/
That article had both parts for me when I checked

http://windows7themes.net/
Has none of it.

**Comment by reek** [comment]
Hi,
Already reported https://greasyfork.org/fr/forum/discussion/7871

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
