### ISSUE TITLE
6play.fr

### ISSUE THREAD

**Issue by Kaotic** [reek/anti-adblock-killer#981]
ADS URL: http://*.damoh.6play.fr/
If i block this URL message with "We regret not being able to allow you access to this video.
An advertisement blocking software or "ad-blocker" present on your browser to prevent the dissemination of advertising messages."

Thankyou

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by Kaotic** [comment]
Oh, sorry guy i didn't view this.

- Link page contains anti-adblock: [6play.fr/n-c-i-s-los-angeles-p_838..](http://www.6play.fr/n-c-i-s-los-angeles-p_838/Saison-7-episode-6-c_11544442) and all others videos.
- Screenshot: http://imgur.com/GOeyQrb
- My browser: Google Chrome v48.0.2564.97 m
- My script manager: Tampermonkey v3.12.58
- My adblocker: AdBlock v2.48
- My filterlists: EasyList, (*.damoh.6play.fr for 6play ADS server), French list.

**Comment by SMed79** [comment]
@Kaotic known issue (videoplaza anti-adblock) for the moment unfortunately can not be blocked, there is no way to remove these videos ad without blocking at the same time access to the content itself.

**Comment by reek** [comment]
@Kaotic 
try this
<code>@@||videoplaza.tv^$object-subrequest,domain=6play.fr</code>

**Comment by Kaotic** [comment]
Didn't work @reek :/

**Comment by SMed79** [comment]
@Kaotic didn't work this mean you want to block `*.damoh.6play.fr` and in the same time solve the anti-adblock?

**Comment by Kaotic** [comment]
I tried 2 solutions @SMed79

**Comment by SMed79** [comment]
@Kaotic  see if helps: 
`@@||6play.fr/publicite-$script`

**Comment by Kaotic** [comment]
@SMed79 With this i have ADS, i *.damoh.6play.fr + @@||6play.fr/publicite-$script = We regret not being able to...

Thanks for help @reek and @SMed79 ;)

**Comment by SMed79** [comment]
@Kaotic try using [Captvty](http://captvty.fr/) or [youtube-dl](https://github.com/rg3/youtube-dl).

`youtube-dl "your-video-url" -o - | vlc  --file-caching=5000 -`

demo: https://vid.me/hA6n

**Comment by Kaotic** [comment]
@SMed79 with Captvty not possible beacause all videos have DRM security and youtube-dl Unsupported URL + DRM.

**Comment by SMed79** [comment]
> Captvty not possible because all videos have DRM security
Sorry, my apologies for not having been able to help :-/
