### ISSUE TITLE
tek.no

### ISSUE THREAD

**Issue by hnaess** [reek/anti-adblock-killer#984]
http://www.tek.no/artikler/norsk-barneskoleelev-fikk-stot-na-kaller-apple-tilbake-ipad-og-mac-ladere/275436
http://imgur.com/hJatGvT
Chrome version 48.0.2564.97 m
uBlock Origin v1.5.6
uBlock (defaults) + EasyList
Anti-Adblock Killer | Reek‎ (github.com): 1,471 used out of 1,471

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer#instruction
