### ISSUE TITLE
Do you have any idea for kill this script ?

### ISSUE THREAD

**Issue by GreanMaster** [reek/anti-adblock-killer#985]
[jsFiddle](https://jsfiddle.net/vxkt69fz/)

that on the body tag

one solution I got is insert `height:1px;` to `style` attribute like this

`<div id="tester" style="display:none; height: 1px;">`

thank :+1:

**Comment by reek** [comment]
What is the website address so I added a rule on AakScript ?

**Comment by GreanMaster** [comment]
Thank @reek but don't mind with that

At first , I throght only adblock will solve that 

I throght your script is huge now.

**Comment by reek** [comment]
Ok, anyway this system can be bypassed with a rule AdBlock or a rule Javascript

Yes, Aak earn some experience every day :smile:
