### ISSUE TITLE
exacttarget.com (salesforce marketing cloud) - email preview mode disabled

### ISSUE THREAD

**Issue by leftynaut** [reek/anti-adblock-killer#986]
The preview window (both desktop and mobile) for emails appears blank when this script is enabled.

**Comment by xxcriticxx** [comment]
how do you use this script on the mobile?

**Comment by leftynaut** [comment]
I'm not using it on mobile. I'm talking about previewing what an email looks like on a mobile device, using the Salesforce Marketing Cloud website on a regular desktop browser

**Comment by reek** [comment]
@leftynaut 
add <code>exacttarget.com</code> to the list of domains to exclude
https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L4578

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
