### ISSUE TITLE
digitalcitizen.life

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#987]
http://www.digitalcitizen.life/security-everyone-reviewing-bitdefender-total-security-2016?page=0%2C1
![](https://cloud.githubusercontent.com/assets/16030872/12697275/b583e594-c77f-11e5-81bc-68ef5db31bca.png)

I reported it to EasyList but they didn't add it: https://forums.lanik.us/viewtopic.php?f=62&t=27890

``` javascript
    //    AdBlocker Detection

    var session_storage = sessionStorage.pages_visited
    if (session_storage === undefined) {
      sessionStorage.setItem('pages_visited', 0)
    } else {
      session_storage++;
      sessionStorage.setItem('pages_visited', session_storage);
    }


    if (($(".dfp-tag-wrapper:visible").length == 0) && (sessionStorage.getItem('AdPopState') != 'shown') && (session_storage == 1)) {
      $("#dont-block-our-ads-popup").delay(2000).fadeIn();
      sessionStorage.setItem('AdPopState', 'shown');
    }

    if ($(".dfp-tag-wrapper:visible").length == 0) {
      $('.TopAdBanner').addClass('AdBlocked');
    }

    $("#dont-block-our-ads-popup").click(function () {
      $(this).fadeOut();
    });

**Comment by reek** [comment]
HI,

Ok, I'll kill it, but can you add your configuration (see report guide) ?

**Comment by IDKwhattoputhere** [comment]
Google Chrome Version 47.0.2526.106
Tampermonkey 3.12.58 + AAK script 9.1
uBlock Origin v1.5.6
Filters: 
![](https://cloud.githubusercontent.com/assets/16030872/12697481/07899d5c-c785-11e5-99e8-5a9dd52ef99f.png)
\+ Block-EU-Cookie-Shit-List

**Comment by reek** [comment]
Ok, thanks

**Comment by IDKwhattoputhere** [comment]
@reek Yea, sorry for that.

Why is there suddenly some JS in my issue comment? I don't remember putting it there. :confused:

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
