### ISSUE TITLE
alluc.ee

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#988]
http://www.alluc.ee/l/Big-Buck-Bunny/thuieff
![](https://cloud.githubusercontent.com/assets/16030872/12697362/8cff5174-c781-11e5-8e74-fa3b46ca8364.png)
Adblocker message and special ads for adblock users.
EasyList didn't add it again: https://forums.lanik.us/viewtopic.php?f=62&t=27806

**Comment by reek** [comment]
Ok, thanks

**Comment by maynak00** [comment]
**try with:**
>@@||alluc.ee/js/ads.js*$script,domain=alluc.ee

**Comment by IDKwhattoputhere** [comment]
Thanks, it works. One ad left: `www.alluc.ee###aovl`

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by IDKwhattoputhere** [comment]
Thanks for all your great work. You are awesome!
