### ISSUE TITLE
gaijin.at

### ISSUE THREAD

**Issue by IDKwhattoputhere** [reek/anti-adblock-killer#989]
Exclusive ads for adblock users.
http://www.gaijin.at/olspwgen.php
![](https://cloud.githubusercontent.com/assets/16030872/12697435/9062fdc8-c783-11e5-9bc1-0983a161110e.png)
Not added by EasyList: https://forums.lanik.us/viewtopic.php?f=64&t=27026

**Comment by reek** [comment]
Ok, thanks

**Comment by maynak00** [comment]
**try with:**
>@@||gaijin.at/ads/advertising.js$script,domain=gaijin.at

**Comment by IDKwhattoputhere** [comment]
Thanks, it works.

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
