### ISSUE TITLE
needing tuturial to add own sites.

### ISSUE THREAD

**Issue by darknessblade** [reek/anti-adblock-killer#990]
hello, 

i have found this tool recently, and its working like a charm on all global sites i use.

now i want to add local sites from my country to that list.
is there any tuturial of how i can do this. (finding the detection scripts)
--------------------------------------
i am using maxthon 4.4 (great browser, with addblock build in)
with violent monkey (same kind of tool as grease monkey)
--------------------------------------
all scripts work like they should be.

if there are issues with combiality with my browser i will update this in my post

**Comment by reek** [comment]
https://adblockplus.org/en/filters

**Comment by darknessblade** [comment]
no i meant how to make a ANTI-addblock script, tried copying a existing one and changing it but this failed

**Comment by reek** [comment]
then you must learn javascript :smile:
