### ISSUE TITLE
filehorse.com

### ISSUE THREAD

**Issue by maynak00** [reek/anti-adblock-killer#993]
**filter:**
>@@||static.filehorse.com/js/ads.js$script,domain=filehorse.com

or
>@@||static.filehorse.com/*/ads.js$script,domain=filehorse.com

**Comment by reek** [comment]
Ok, thanks

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
