### ISSUE TITLE
talktv.vn

### ISSUE THREAD

**Issue by t2hv33** [reek/anti-adblock-killer#995]
http://talktv.vn/archieeeee
http://talktv.vn/best.udyr.vn

http://i.imgur.com/qrnMUgv.png
Chrome
Tampermonkey
uBlock Origin
Adblock Warning Removal List‎ + AakList +  
           ABPVN List [download.cnet.com]‎  http://abpvn.com/filter/abpvn-pgn3BB.txt

**Comment by t2hv33** [comment]
Fixed!
Add List: FMFS 2.0 http://pastebin.com/raw/7G8f8S2W
And this fix.
But don't know how to do that.
Need some one explain.
Thanks so much. that means alot to me

**Comment by reek** [comment]
uBlock Origin: Options -> 3rd-party-filters, paste url in textarea

**Comment by reek** [comment]
Or try add this rule
<code>@@||talktv.vn/resource/third-party/jwplayer/ads.js$object-subrequest</code>

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
