### ISSUE TITLE
leporno.org

### ISSUE THREAD

**Issue by XtremeDesire** [reek/anti-adblock-killer#996]
im using RU Aadlist + EasyList but always get this message

leporno.org
http://imgbox.com/O9AtBqTg

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by XtremeDesire** [comment]
btw. do i need to use the adblocklplus subscription & greasemonkey script together or just one of them?!

**Comment by reek** [comment]
It will use AakScript (Greasemonkey), but I recommend to use both

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller

**Comment by XtremeDesire** [comment]
dammmmit!! still get the same message :-1:

**Comment by reek** [comment]
https://github.com/reek/anti-adblock-killer/wiki/Report-Guide

**Comment by reek** [comment]
why did you write blockadblock.com instead of leporno.org, that's why it does not work

**Comment by reek** [comment]
I would fix it in the next version

**Comment by XtremeDesire** [comment]
because its blockadblock.com script loaded when i work on leporno.org site!!

i think you should knew that if you work on it you even didnt test it before publish?!! my god!! did you check the "interested in blcoking adblock on your own site"

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
