### ISSUE TITLE
mac4ever.com

### ISSUE THREAD

**Issue by pitichampi** [reek/anti-adblock-killer#997]
https://www.mac4ever.com/actu/107997_quel-personnage-emblematique-de-nintendo-arrivera-sur-ios
http://i.imgur.com/2R5xRYW.jpg
Safari
tampermonkey
Adblock (getadblock)
EasyList + AakList

**Comment by reek** [comment]
Ok, I'll kill it

**Comment by maynak00** [comment]
adblocker not detected for my first visit.
**try this:**
>@@||mac4ever.com/adserver.adtech.de/script.js$script,domain=mac4ever.com

**Comment by pitichampi** [comment]
It doesn't appear every time... That's really annoying. But it did appear again (with your filter).

**Comment by maynak00** [comment]
tried today and 1 time get adblocker detected message.
**try this:**
>www.mac4ever.com###simplemodal-container
www.mac4ever.com###simplemodal-overlay

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
