### ISSUE TITLE
mangas.zlx.com.br

### ISSUE THREAD

**Issue by deidark** [reek/anti-adblock-killer#998]
https://mangas.zlx.com.br/ler-nanatsu-no-taizai-online/capitulo-0/48441-i-wish-scan#/!page50
http://i.imgbox.com/seFokLaW.png
Mozilla Firefox
Greasemonkey
Adblock Plus
EasyList + AakList

**Comment by reek** [comment]
Hi,

Ok, I'll kill it

**Comment by reek** [comment]
Try this
<code>@@/js/lib/controllers/Leitor/Leitor.min.js$script,domain=mangas.zlx.com.br</code>

**Comment by deidark** [comment]
thanks.

**Comment by deidark** [comment]
I have trying to used that code `@@/js/lib/controllers/Leitor/Leitor.min.js$script,domain=mangas.zlx.com.br` but sometimes work and other time don't work.

**Comment by reek** [comment]
when this happens gives me blocked resources and page url
see: https://github.com/reek/anti-adblock-killer/wiki/Report-Guide-Advanced

**Comment by deidark** [comment]
Source Code: http://paste2.org/KEjyCtvD
Extensions: Greasemonkey, Adblock Plus
Userscripts: Anti-Adblock Killer 
Blocked Resources: http://i.imgur.com/fGmZyvu.png

**Comment by reek** [comment]
However, the rule has been applied, I have no alternative to offer you

**Comment by reek** [comment]
Hi,<br><br>Anti-AdBlock Killer has been updated ! <a href="https://github.com/reek/anti-adblock-killer#changelog">Changelog</a><br><br>Step 1: <a href="http://tinyurl.com/ong3bfe">Update</a> : UserScript<br>Step 2: <a href="http://reek.github.io/anti-adblock-killer/#filterlist">Update</a> : FilterList<br><br>Do not forget to donate, review, share, follow and add to favorites.<br><br>See you<br>Reek

https://github.com/reek/anti-adblock-killer/
https://twitter.com/antiadbkiller
