### ISSUE TITLE
Execution of script failed error (Aak 9.2 and Tampermonkey Beta 4.0.5054)

### ISSUE THREAD

**Issue by offhub** [reek/anti-adblock-killer#999]
It was working with Aak 9.1.

Aak 9.1 + TM Beta = Ok
Aak 9.2 + TM Beta = Failed

`ERROR: Execution of script 'Anti-Adblock Killer | Reek' failed! Cannot read property 'bind' of undefined`

`TypeError: Cannot read property 'bind' of undefined
    at Object.Aak.registerConsole (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:241:46)
    at Object.Aak.initialize (eval at <anonymous> (eval at <anonymous> (unknown source)), <anonymous>:98:9)`

**Comment by reek** [comment]
HI,

I will fix these errors
Although there are errors, but it works anyway, 

Thanks

**Comment by reek** [comment]
did you these mistakes at all sites ?
because I, not

**Comment by offhub** [comment]
Yes, i did.

I also tested Aak 9.2 with previovus TM Beta versions, here are the results:

- Aak 9.2 + TM Beta 4.0.5054 = Failed
- Aak 9.2 + TM Beta 4.0.5047 = Failed
- Aak 9.2 + TM Beta 4.0.5035 = Failed
- Aak 9.2 + TM Beta 4.0.5008 = Ok

**Comment by reek** [comment]
I use these versions and that's ok.
<pre>
Tampermonkey v3.12.58 (chrome)
Tampermonkey v3.13.4956 (opera)
</pre>
should report the problem to TM

**Comment by offhub** [comment]
Yes, no problem with stable and beta 4.0.5008 versions. I already reported to TM. Thanks

**Comment by reek** [comment]
ok, I'll look at my side if I can do something

**Comment by offhub** [comment]
> Fixed. http://tampermonkey.net/changelog.php?version=4.0.5059&ext=gcal

**Comment by reek** [comment]
Ok, thanks
